### ISSUE TITLE
Help using input's onChange event properly 

### ISSUE THREAD

**Issue by tusharkhatiwada** [erikras/redux-form#1003]
Hi,
I'm learning React recently and have started to do a small project using it. I found out this great Component for using Dynamic Forms. I've come across a problem and seeking for some professional's help. 
Here is the code :

```
import React, { Component } from 'react';
import { reduxForm } from 'redux-form';
import _ from 'lodash';


const FIELDS = {
	username: {
		type: 'text',
		label: 'Username',
		id: 'username',
		icon: 'fa fa-user'
	},
	password: {
		type: 'password',
		label: 'Password',
		id: 'password',
		icon: 'fa fa-key'
	}
};

class Login extends Component {

	constructor(props) {
		super(props);
		this.state = {
			username: '',
			password: ''
		};
	}

	onSubmit() {
		console.log("It Worked!!");
	}
	onInputChange(event) {
		// this.setState({
		// 	username: event.target.value,
		// 	password: event.target.value
		// })
    console.log(event.target.value);
	}

	renderField(fieldConfig, field) {
		const fieldHelper = this.props.fields[field];

		return(
			<div className={`form-group ${fieldHelper.touched && fieldHelper.invalid ? 'has-danger' : ''}`}>
				<label className='sr-only'>{fieldConfig.label}</label>
				<div className="input-group">
					<div className="input-group-addon"><i className={fieldConfig.icon} ></i></div>
					<input type={fieldConfig.type} className='form-control' id={fieldConfig.id} placeholder={fieldConfig.label} onChange={this.onInputChange.bind(this)} {...fieldHelper} />
				</div>
					<div className='text-help'>
						{fieldHelper.touched ? fieldHelper.error : ''}
					</div>
			</div>
		);
	}

	render() {
		const { handleSubmit } = this.props;
		return(
			<form className="mixForm col-sm-4" id="loginDiv" onSubmit={handleSubmit(props => this.onSubmit(props))} >
				{_.map(FIELDS, this.renderField.bind(this))}
				<button type="submit" className="btn btn-info" id="loginBtn">Log In</button>
			</form>
		);
	}
}

function validate(values){
	const errors = {};

	_.each(FIELDS, (type, field) => {
		if(!values[field]) {
			errors[field] = `Enter a Valid ${field}`;
		}
	});
	return errors;
}

export default reduxForm({
	form: 'Login',
	fields: _.keys(FIELDS),
	validate
})(Login);

```

On the Input tag I've used the **onChange** event but for some reason, it doesn't seem to work. Am I missing something?

Also I want to give the inputs a **value**. like:
`value={this.state.username}` for Username and` value={this.state.password}` for Password. How do I do this dynamically. I tried using `value={this.state.fieldConfig.id} `and `value={this.state.{fieldConfig.id}}` but both threw errors.

**Comment by babsonmatt** [comment]
I believe `{...fieldHelper}` is overwriting your onChange

**Comment by tusharkhatiwada** [comment]
@babsonmatt : Awesome! That worked. Thanks.
How about the **value** property ? How do I make sure the **input** tags get their respective state ?

**Comment by ooflorent** [comment]
This is a usage question, and we encourage you to ask it on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

This is the only way to ensure the same question doesn’t get asked many times in a row, and that folks who have the same question in the future will be able to find it.

I’m closing for these reasons.
