### ISSUE TITLE
v6: Submit from parent while decorating component with both `reduxForm` and `connect`

### ISSUE THREAD

**Issue by jervi** [erikras/redux-form#1005]
The "Submit from parent" example from v5 still works with redux-form v6, as long as I only decorate the component with `reduxForm`. If I also decorate it with `connect`, the `submit()` function on the referenced component is undefined.
I can work around the issue by specifying `{withRef: true}` as the fourth argument to `connect`, and then call the `submit` function like this instead: `onClick={() => this.refs.myComponent.getWrappedInstance().submit()}`.
I'm not sure if this is something that can actually be solved, but the workaround could maybe be documented if you plan to port the "Submit from parent" example from v5.

**Comment by erikras** [comment]
This isn't so much a "workaround" as just _the way you get to the wrapped instance when using `connect()`_, as documented by `react-redux`. While it's generally not one HOC library's job to document functionality of another HOC library, you may be right that `connect()` is the most likely one to be used in conjunction with `reduxForm()`, and might deserve a mention in the docs.

**Comment by oallouch** [comment]
It was so much simpler in V5 when mapStateToProps was directly in reduxForm .
The parent doesn't need to know how the child form was made (with or without connect).
Double win: no more connect wrapping AND we keep the direct submit.

**Comment by UweWindt** [comment]
Is there any reason, why you changed the reduxForm parameter definition in v6?
I also need some Extra- information from the redux-store in my form definition.
The solution in v5 was pretty handy.

**Comment by staab** [comment]
I've run into this as well, but I happen to have a bunch more hoc's I wrap the child with, which don't support unwrapping. The workaround I'm using now is the event emmitter on submit thing, which is gross and not reduxy at all; I did try using the startSubmit action creator, but that doesn't really do the whole process; and easy affordance for this would be a `submitForm(formName)` action creator that's either a thunk or ties in with some middleware. Of course, then you'd need to support thunks or middleware, but that would be my preferred approach.

**Comment by diegohaz** [comment]
I think we could continue with the work in #908

**Comment by danielrob** [comment]
Quite certain [remote submit example](http://redux-form.com/7.0.3/examples/remoteSubmit/) resolves this issue as it did in #908. If I've missed something, please advise :), closing.
