### ISSUE TITLE
does reduxMountPoint support paths instead of a single key?

### ISSUE THREAD

**Issue by jedwards1211** [erikras/redux-form#1006]
I've gotten in the habit of telling a lot of redux components/actions the path where the their state is found within the redux state.  This makes for maximum reusability as it can be used on redux state living absolutely anywhere.  Is it possible to do that with this library?

**Comment by erikras** [comment]
`reduxMountPoint` is going away in `v6`. You should use `getFormState`, which should provide you with all the flexibility you could need.
