### ISSUE TITLE
best-practice way to get formName in props

### ISSUE THREAD

**Issue by fairbairn** [erikras/redux-form#1007]
Haven't seen a way to get to the `formName` that's passed in as `form` for `reduxForm()`.  Is there a reason it's not available in props the same way `formKey` is provided?

What's the best way to get to it?

**Comment by erikras** [comment]
Yeah, it's not currently available. But I don't understand where you need it where you don't have it. If you're talking about what you're passing to the decorator, you've already got it in the same file as your component.

**Comment by fairbairn** [comment]
It's a nice way to have a pre-defined identifier for the actual form 
that we can use downstream for our own purposes.  We use a lot of common 
internally-built components that are wrapped by reduxForm, and we were 
looking for a pleasant and already implemented way of knowing which form 
was what.  The formName assigned in reduxForm works for us.  Would just 
be a convenience really, instead of us adding more custom props in other 
places in the application to provide the same value.

**Comment by erikras** [comment]
I've added the form name to the props for `v6`. You can PR the same for `v5` if you care enough.

**Comment by erikras** [comment]
Released `v6` change as [`v6.0.0-alpha.14`](https://github.com/erikras/redux-form/releases/tag/v6.0.0-alpha.14).
