### ISSUE TITLE
For deep-forms isPristine is false when adding and removing fields in an array without modifying any of the sub-values

### ISSUE THREAD

**Issue by r-tock** [erikras/redux-form#1009]
Change of array is not considered as isPristine.

**Comment by r-tock** [comment]
lets say `fields = { fieldKey: [{value: 'first'}, {value; 'second''}] }`  Now try removing the second entry.
isPristine is not caught.

**Comment by erikras** [comment]
Yep. Known bug that probably won't get fixed in `v5`, but is already fixed in `v6`. There are some workarounds discussed in previous issues: #391 #484 #749
