### ISSUE TITLE
Dealing with component state (not related to form data)

### ISSUE THREAD

**Issue by jsdmc** [erikras/redux-form#101]
Hola! I played around with redux-form and found out that actually it's quite hard to create completely stateless component. For example, you have a form where some fields appear only when some checkbox is checked etc. For me it looks strange to move out this tiny UI logic to redux-form and define some callbacks in parent components. 
How are you dealing with such cases guys?
Cheers

**Comment by erikras** [comment]
Could you not do something like this?
```js
render() {
  const {fields} = this.props;
  return (
    <div>
      <input type="checkbox" {...fields.toggle}/>
      {fields.checkbox.value ? <div>
        // additional fields
        <input type="text" {...fields.someOtherField}/>
      </div>}
    </div>
  );
}
```

**Comment by jsdmc** [comment]
Yep, sure. It's the way to do it using redux-form. But if checkbox value is not a part of data you want save - you have to select then only needed props from data you get in form submit handler. That's my concern

**Comment by erikras** [comment]
Ah, sure. If you need additional non-form state, then that's up to you. If you really want to only toggle on a checkbox and you are really averse to having normal React state in your component, you could do some semi-disgusting hack and read the DOM state.
```js
render() {
  const {fields} = this.props;
  return (
    <div>
      <input type="checkbox" ref="toggle"/>
      {this.refs.toggle.checked ? <div>    // <----------- gross
        // additional fields
        <input type="text" {...fields.someOtherField}/>
      </div>}
    </div>
  );
}
```

**Comment by jsdmc** [comment]
I'm not against having state for component =) Just asking and advice what is best practice to handle such cases. According to documentation redux-form helps to avoid having component state. And it's right way. So maybe we can think about how to distinguish (configure) between "data fields" and "helper fields"?
P.S. Ideally, my vision is to have for each react component it's own redux state (local redux infrastructure) and be more isolated. What's your opinion about that? 
Thanks
