### ISSUE TITLE
v6 — Can't read the property wrapped of undefined

### ISSUE THREAD

**Issue by damamsrinivas** [erikras/redux-form#1010]
I'm using immutable import. I copy pasted this example in my project. 
http://redux-form.com/6.0.0-alpha.13/examples/immutable/

I'm getting the error `Can't read the property wrapped of undefined`
![screenshot from 2016-05-20 11-20-16](https://cloud.githubusercontent.com/assets/19143973/15418448/176311dc-1e7d-11e6-98db-8a91eaaf7432.png)

**Comment by erikras** [comment]
Well, the example is working, so there must be something different in your project. Can you share some of the code around the usages of `Field`?

**Comment by nygardk** [comment]
I get the same error when upgrading to a newer than version 6.0.0-alpha.7. Unfortunately I cannot provide an example but just wanted to confirm that there probably is something to this.

I predict it has something to do with higher-order components that are connected with redux-form.

**Comment by erikras** [comment]
> do you see any problem with the following ?

No. Unless you want something from the state to be used as a parameter to `redux-form` (like in the [Initializing From State Example](http://redux-form.com/6.0.0-alpha.13/examples/initializeFromState/)), then the order does matter. But if you are just connecting to any other part of the Redux state, the order does not matter, e.g. [Selecting Form Values Example](http://redux-form.com/6.0.0-alpha.13/examples/selectingFormValues/).

**Comment by nygardk** [comment]
@erikras, I was able to track down the problem. It appears that if a component is a "page" component used directly with react-router, it causes this error.

[Download example project](https://www.dropbox.com/s/sav8eb733brm3ka/redux-form_error_example.zip?dl=1)

**Comment by erikras** [comment]
First of all, 👍 👍  for providing a whole sample project. Unfortunately, I can't get that example to run because it's missing a `.eslintrc` file.

However, it doesn't _sound_ like this is a problem with `redux-form`. If I recall the chatter correctly, React Router v3-alpha is supposed to address issues with Redux compatibility. You might try that.

**Comment by steffenmllr** [comment]
Having the same issue here and I'm not using react-router - trying to narrow the problem down. I updated from `6.0.0-alpha.7` to `6.0.0-alpha.13`

**Comment by steffenmllr** [comment]
@erikras I'm not sure if this is expected behavior or a bug :)

```js
// This works as expected
let SimpleForm = (props) => {
    return (
        <form>
            <Field name="firstName" component="input" type="text" placeholder="First Name"/>
        </form>
    );
};

SimpleForm = reduxForm({
    form: 'simple'  // a unique identifier for this form
})(SimpleForm);

export default class Test extends React.Component {
    render() {
        return (
            <div className="test">

                <h1>Forms</h1>
                {SimpleForm}
            </div>
        );
    }
}
```

```js
// This throws Cannot read property 'wrapped' of undefined
@reduxForm({
    form: 'styleguide_form'
})
export default class Styleguide extends React.Component {
    render() {
        return (
            <div className="test">
                <form>
                    <Field name="firstName" component="input" type="text" placeholder="First Name"/>
                </form>
            </div>
        );
    }
}
```

**Comment by nygardk** [comment]
@erikras, @steffenmllr, I noticed that if you include a form component on a page when the form is created within the same module, it works just fine. However, if you import the form component from another module, it throws this error.

It got me thinking it could have something to do with the way how babel transforms modules. I tried all syntaxes: default export, named export and module.exports and nevertheless they all worked the same in this case. I tried with the newest versions of all related babel-modules.

_However_, when I _exported an object with a reference to the form component_ instead, it worked.

works:
```js
export default { test: FormComponent };
...
import FormComponent from 'FormComponent';

<FormComponent.test />
```

not works:
```js
export default FormComponent;
...
import FormComponent from 'FormComponent';

<FormComponent />
```

You can try this in the project I created. The `.eslintrc` should also now be included correctly. [Download it from here.](https://www.dropbox.com/s/sav8eb733brm3ka/redux-form_error_example.zip?dl=1l)

**Comment by nygardk** [comment]
Allright. I downgraded webpack from version `2.1.0-beta.7` to version `1.13.1` and webpack-dev-server from `2.0.0-beta` to `1.14.1`, and now the case works that didn't work earlier. So, it most probably has something to do with the module loading.

**To make it work with webpack 2, the workaround currently is to export an object with a reference to the form component, instead of the form component itself.**

**Comment by xmityaz** [comment]
I have the same issue when importing Form component from another module. I'm using webpack `1.13.1`, but unfortunately, normal export - import module cause this error.
@nygardk's workaround works for me.
However, it seems quite hacky, especially for big projects. Is there any chance that issue can be fixed in the scope of redux-form?

**Comment by d0ntth1nc** [comment]
Upgrade react-hot-reload to v3 and the problem  is gone

**Comment by bochen2014** [comment]
`webpack.HotModuleReplacementPlugin()`
is the problem.

so far upgrade react-hot-loader to v3 is the only solution

**Comment by alexpanov** [comment]
Upgrading to react-hot-loader v3 fixed the issue for me too. Luckily, it was a very easy upgrade by just replacing `react-hot` to `'react-hot-loader/webpack'` in the `loaders` section

**Comment by niksosf** [comment]
@alexpanov 
Are you using babel and a .babelrc file for your es6? so in your loaders section, do you just put loader: 'react-hot-loader/webpack' instead of the older loader: 'react-hot/babel'?

**Comment by alexpanov** [comment]
@niksosf yes, I am using Babel. 
The project that I was referring to has a webpack loader section configured to use `react-hot`, not `react-hot/babel`. I do not fully understand the difference between the two and can't advise.

**Comment by khayong** [comment]
I find it hard to upgrade my project to react-hot-reload v3, also exporting object with a reference to the form component [https://github.com/erikras/redux-form/issues/1010/#issuecomment-221515925](https://github.com/erikras/redux-form/issues/1010/#issuecomment-221515925) is quite troublesome if lots of form components to include.

Coincidentally, I found the method below work for me. Just need to install additional package of [recompose](https://github.com/acdlite/recompose), and compose `defaultProps` higher order component with `reduxForm`.

```
import {compose, defaultProps} from "recompose";

let SimpleForm = (props) => {
    return (
        <form>
            <Field name="firstName" component="input" type="text" placeholder="First Name"/>
        </form>
    );
};

export default compose(
  defaultProps({}), // Passed empty props.
  reduxForm({
    form: "fieldConfig",
  })
)(SimpleForm);
```

**Comment by dskoda1** [comment]
Upgrading to react-hot-loader@3.0.0-beta7 and changing a loader in webpack config from:
`"react-hot"` 
to
`"react-hot-loader/webpack"`
Fixed this for me.

**Comment by molszanski** [comment]
I would like to confirm, that moving to 3.0-beta did the trick.

Please find webpack@3.4 and react-hot config

Webpack Config
  ```coffeescript
module.exports = (defaultSettings) ->

  entry: [
    "webpack-dev-server/client?http://127.0.0.1:#{defaultSettings.port}"
    'webpack/hot/only-dev-server'
    'react-hot-loader/patch'
    './src/index'
  ]
  defaultModules:
    rules: [
      test: /\.coffee$/
      use: [
          loader: 'react-hot-loader/webpack'
          options: exclude: /(node_modules)/
        ,
          loader: 'babel-loader'
          query: presets: ['es2015', 'react', 'stage-2']
        ,
          loader: 'coffee-loader'
      ]
    ,
      test: /\.(js|jsx)$/
      exclude: /node_modules/
      use: [
          loader: 'react-hot-loader/webpack'
          options: exclude: /node_modules/
        ,
          loader: 'babel-loader'
          query: presets: ['es2015', 'react', 'stage-2']
      ]
    ]

```
```js
"devDependencies": {
    "babel-core": "^6.25.0",
    "babel-loader": "^6.4.1",
    "babel-preset-env": "^1.5.2",
    "babel-preset-es2015": "^6.22.0",
    "babel-preset-latest": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-2": "^6.24.1",
    "babel-preset-stage-3": "^6.24.1",

    "webpack": "^3.4.1",
    "react-hot-loader": "^3.0.0-beta.7",

    "coffeescript": "^2.0.0-beta3",
    "coffee-loader": "github:webpack-contrib/coffee-loader#0ea4d6a7cc9ffc7c8f7a0c6eb3fd3fedea9943b8"

}
```
