### ISSUE TITLE
redux-form doesn't play nice with immutable's combineReducers

### ISSUE THREAD

**Issue by fourcolors** [erikras/redux-form#1011]
If you do something like 

```
  import { combineReducers } from 'redux-immutable'

```

then try to pass the formReducer into it, it breaks and says 'form must be set on state'

**Comment by erikras** [comment]
Immutable JS is only somewhat supported [through a hack](http://redux-form.com/5.2.3/#/faq/immutable-js) in `v5`, but it is supported [out of the box](http://redux-form.com/6.0.0-alpha.13/examples/immutable/) in `v6`.
