### ISSUE TITLE
[V6]How can I get actions?

### ISSUE THREAD

**Issue by Darmody** [erikras/redux-form#1013]
`import { arrayPush } from 'redux-form'` can not access it. I am using v6.0.0-alpha.13

**Comment by Darmody** [comment]
https://github.com/erikras/redux-form/blob/v6.0.0-alpha.13/src/index.js 

I think it export the wrong actions?

**Comment by erikras** [comment]
Yep, this is a bug.

**Comment by erikras** [comment]
Rectified. Will be published in next release.

**Comment by erikras** [comment]
Released as [`v6.0.0-alpha.14`](https://github.com/erikras/redux-form/releases/tag/v6.0.0-alpha.14).
