### ISSUE TITLE
V6 - touched states leak on FieldArray.remove

### ISSUE THREAD

**Issue by q42jaap** [erikras/redux-form#1014]
I'm using a FieldArray with a component class, one of the cool features is that it allows me to just `push({})` a new object in, and `remove(itemIndex)` remove items.
However, when I remove an item, the `touched` bools are not changed, so it seems.
This is easily noticeable with valdiation.

I'm currently commuting, so I'll be a bit short, but what I'm doing is this:

``` js

export default class JsonFormArrayEditor extends React.Component {

  render() {
    console.log('JsonFormArrayEditor.props', this.props);
    const {push} = this.props;
    return <div className="JsonFormArrayEditor">
      <RaisedButton label="+ Document" type="button" onClick={() => push({})}/>
      {this.props.map((arrayItemPointer, arrayIndex) => this.renderArrayItem(arrayIndex, arrayItemPointer))}
    </div>;
  }

  renderArrayItem(arrayIndex, arrayItemPointer) {
    const {remove, schema: {items: itemsSchema}} = this.props;
    return <div key={arrayIndex}>{arrayIndex}
      <button onClick={() => remove(arrayIndex)}>Remove</button>
      <JsonAnyEditor pointer={arrayItemPointer} schema={itemsSchema}/>
    </div>;
  }
}
```

The array component is used like this:

``` js
        return <FieldArray
          name={pointer}
          schema={schema}
          component={JsonFormArrayEditor}/>;
```

I have validation function which takes jsonschema and takes the validation output and creates an errors object the way redux-form needs it.

When I create an object in the array, and toch the fields so they invalidate, create a new (untouched) 2nd item in the array, and then remove the first item.
The touched bools on that 2nd items (which has become the first item) transfer from one array item to the next...

Maybe I'm doing something wrong, or this might be a small bug. Of course, the touched flag is purely for display purposes. I'm using that like in the examples:

``` js

export default class JsonFormTextEditor extends React.Component {
  render() {
    const {schema, touched, error, ...throughProps} = this.props;
    return <TextField
      floatingLabelText={schema.label}   // schema.label is my own "extension" to jsonschema.
      errorText = {touched && error}
      {...throughProps}
    />;
  }
}
```

**BTW**
Redux Form made creating this super easy, if you're interested I could try to create a seperated example for you to put up. Or maybe this would need to be a separate package (I'm using material-ui for all the string/number/... types atm, that would have to be pluggable, in which case an example would be less effort ATM).

**Comment by erikras** [comment]
@q42jaap I'm always interested in new, novel examples. 👍

**Comment by huan086** [comment]
Very likely due to the array key being arrayIndex. Try keying it with something that uniquely identifies the array item

**Comment by q42jaap** [comment]
@huan086 good point, I'll have to think about how to do that, since I don't have a natural key field in this case.

**Comment by q42jaap** [comment]
I'm closing this, I confirmed that the index as key does this, I think it's difficult to prevent.
