### ISSUE TITLE
How to not validate initialValues

### ISSUE THREAD

**Issue by tonyxiao** [erikras/redux-form#1016]
my `validate` method is getting called for initialValues. Is that intended? How do I work around this if I do not want to validate the initial set of values?

**Comment by erikras** [comment]
Your `validate` function will be called with the values of the form on every render. Why is this a problem?

The standard pattern is to only show the validation errors when a field has been `touched`.

**Comment by tonyxiao** [comment]
Ah perfect, just what I wanted. Thanks!

**Comment by tonyxiao** [comment]
Is there a `touched` attribute for the entire form? (for global error under key `_error`)

**Comment by erikras** [comment]
> Is there a `touched` attribute for the entire form?

No, you'll have to `||` those together yourself.

**Comment by erikras** [comment]
`v6` does have an `anyTouched` flag.

**Comment by tonyxiao** [comment]
Fantastic, looking forward to v6! Thanks for your help @erikras
