### ISSUE TITLE
V6 - Questions about initialize and reset

### ISSUE THREAD

**Issue by Darmody** [erikras/redux-form#1017]
I'm using V6.0.0-alpha.13

When I changed the initialValues, form seems do not auto re`initialize`. Is it a bug?

I remember it works in V5.

So, I manually call the `initialize` function passed from `reduxForm` component.
After it re`initialize`, form values didn't reset. Is it a bug?

And I found that the `reset` function passed from `reduxForm` do not work. I have to use action creator function `reset` to `reset('formName')`

**Comment by reyhansofian** [comment]
have you dispatch those command?

in my case, it works by using `dispatch` from redux-thunk

```
import { initialize } from 'redux-form';

const SomeComponent = () => {
  return (
     <a onClick={() => this.props.dispatch(initialize('formName'))}>Reinitialize</a>
  );
}
```

**Comment by Darmody** [comment]
@reyhansofian Yep, I manually call the `initialize`, But I think it may be auto reinitialize by initialValues changing.

**Comment by gustavohenke** [comment]
Happy new year guys! 😁 

I don't know how v6.0.0-alpha.13 used to work, but in more recent V6 releases, you need to specify `enableReinitialize: true` in the `reduxForm` HOC:

```js
reduxForm({
  form: "formName",
  enableReinitialize: true
})( Form );
```
