### ISSUE TITLE
Request: Include validation library

### ISSUE THREAD

**Issue by rodryquintero** [erikras/redux-form#1019]
How about including a validation library along with the package. The idea is to make validation as simple as setting an attribute. Similar to the [formsy-react](https://github.com/christianalfoni/formsy-react) project.

`<input validation="isEmail" name="email" value={email} />`

**Comment by ooflorent** [comment]
React Form won't include a validation library but would provide interoperability with other libraries.
See #726,  https://github.com/erikras/redux-form/issues/852#issuecomment-213911244 and [`tools.md`](https://github.com/erikras/redux-form/blob/4ff709cf89d89715b4ee94254bc22c035dfc5bd5/tools.md).
