### ISSUE TITLE
Changing field value right before form submission

### ISSUE THREAD

**Issue by woniesong92** [erikras/redux-form#1020]
```javascript
  onSubmit(event) {
    event.preventDefault()
    this.props.fields.phoneNumber.onChange("1231231234")
    this.props.handleSubmit(this.props.actions.signUp)(event)
  }
```

I tried to change a field's value right before form submission, but that didn't have an effect.
I also tried setting `fields.phoneNumbre.value` directly, or setting the input value.
How can I change a field's value right before form submission?

**Comment by erikras** [comment]
You append the value to the JSON manually.
```js
<form onSubmit={this.props.handleSubmit(values =>
    this.props.actions.signUp({
      ...values,
      phoneNumber: '1231231234'
    })
  )}/>
```

**Comment by smeijer** [comment]
Is it possible to add a pre-submit hook to a Field? So the normalizing of the data becomes the responsibility of a custom field, and not of one of the _n_ form implementations?

For example in the case of Draftjs, I prefer to store the raw editor state, but submit a string value.

**Comment by erikras** [comment]
@smeijer Interesting idea. However, in [my Draftjs-based input implementation](https://gist.github.com/erikras/5ca8dc618bae5dbc8faf7d2324585d01), I never noticed any performance issues with storing the value in markdown. I think the important thing is that it's not re-parsing the value from markdown on every keypress; it's just letting the component keep its own state and reporting on changes.

**Comment by moimael** [comment]
I'd also love to see a pre-submit hook, my use case is a custom signature field, I wanna upload it to a third party provider (cloudinary) and send the url of the upload when submitting the form.

**Comment by cyrus-za** [comment]
+1 to the idea. I am using a 3rd party component (Material-ui-chip-input) which requires both the value (id in my case) and the label (name) in an object, but when I want to save it to the backend, I want to only send the value (id) of all the selected items. Kind of like how a checkbox group works. 

With that in mind it would be ideal to keep the actual value on the form to be `{id: 'some-id', label: 'Some Label' }` but the submit function sends `'some-id'`.

**Comment by smeijer** [comment]
Another even more simple case for which a `pre-submit` hook would help, is returning a real number from a `<input type="number" />`. Currently; the number is returned quoted, as a string. A `pre-submit` would be able to force it into being a `number`.

I don't understand why a simple but helpfull method as this wouldn't be implemented. Are you willing to accept a PR for this case?

```jsx
// same arguments as `normalize`
const parseNumber = (value, previousValue, allValues) => {
  return Number(value);
};

<input type="number" preSubmit={parseNumber} />; // preSubmit / parseValue / valueOut ?
```

**Comment by cyrus-za** [comment]
@smeijer I think for number in TextField it has a parse property
`<Field component={TextField} type="number" parse={val => parseInt(val)} />`

That's what I got and it works, but I use TextField from redux-form-material-ui. I can't remember if I found that in their documentation or redux-form. So not sure if it will work for `input` but if that is specific to redux-form-material-ui (also done by @erikras ) then I would suggest moving that functionality over to redux-form

**Comment by nicolasflorth** [comment]
@cyrus-za 
Hi! Can you tell me please how you solved to have only 'some-id' instead of {id: 'some-id', label: 'Some Label' } on form submit? I am stuck on my project because of this. Thanks!

**Comment by cyrus-za** [comment]
Hi @nicolasflorth I use the parse and normalize functionality.
https://redux-form.com/7.2.0/examples/normalizing/

**Comment by exah** [comment]
Why this issue is closed? Is there any plans to implement `preSubmit`?

**Comment by dlombardi** [comment]
field level access to a preSubmit hook would help in cases where textInputs are debounced and you want to flush them to update redux.

**Comment by tgreen7** [comment]
if you call change and then put your handleSubmit in a setTimeout like:

```
setTimeout(() => {
      handleSubmit(this.updateData)()
    });
```

it seems to work.

Not sure if this while have any bad consequences.

**Comment by VincentCharpentier** [comment]
I'm also a bit confused on how to normalize my inputs.
My most frequent issue is when I want to trim text values. If I use the normalize property it will prevent the user from typing space at the end of the input.
For instance I cannot type "John Doe" because I will be stuck at "John".
I wish I could normalize only before submit and keep that code separate from the submit code
