### ISSUE TITLE
V6 feature request: trigger submission on blur

### ISSUE THREAD

**Issue by Deadarius** [erikras/redux-form#1021]
Currently in order to save changes I have to hack into internals of redux-form using a middleware that intercepts `redux-form/BLUR` action. But this way I cannot use validation properly. It would be amazing to either have opportunity to access validation state or configure it to submit on blur.

**Comment by erikras** [comment]
Have a look at #908. It's quite possible that V6 will eventually support submission via action. Does that seem sufficient for your needs?

**Comment by kristian-puccio** [comment]
That would be nice for react-native where there is no <form> component

**Comment by gustavohenke** [comment]
I'm closing this. It's been a while since the last comment.
Additionally, whoever needs this feature, go with https://github.com/erikras/redux-form/issues/1021#issuecomment-220918897 solution.
