### ISSUE TITLE
Error when integrating with React-Widgets DropdownList

### ISSUE THREAD

**Issue by liqili** [erikras/redux-form#1022]
When I use component `DropdownList` (from react-widgets) together with `Input` component, I met issues. My code is attached as below. I select value from the `DropdownList` and then click any `Input`, then met the errors:

```
getValue.js:33 Uncaught TypeError: Cannot read property 'type' of null'.
```

[AddEveForm.txt](https://github.com/erikras/redux-form/files/276932/AddEveForm.txt)

**Comment by erikras** [comment]
That error means that `onChange` is getting called with something that looks like an event, but does not have a `event.target` set. You should do something like this to see what it is.

```js
<DropdownList
  {...appId}
  onChange={event => {
    console.log(event)
    appId.onChange(event) // will still throw error
  }}
  style={{marginBottom: 15}}
  data = {appIds}
  // defaultValue={field.defaultValue}
  disabled = {submitting}
  valueField='code' 
  textField='value'
  filter='contains'
/>
```

**Comment by liqili** [comment]
@erikras 
The error still appears.

**Comment by erikras** [comment]
Yes, I know. What did you see in the console log?

**Comment by ooflorent** [comment]
This is a usage question, and we encourage you to ask it on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

This is the only way to ensure the same question doesn’t get asked many times in a row, and that folks who have the same question in the future will be able to find it.

I’m closing for these reasons. However you can keep adding details about your issue and we'll do our best to answer it.

**Comment by liqili** [comment]
@erikras 
Just like this.No target property.
`Object {value: "AAA", code: "AAA"}`
