### ISSUE TITLE
V6 - ArrayItem gets set to undefined instead of {}

### ISSUE THREAD

**Issue by q42jaap** [erikras/redux-form#1023]
I `push({})` an array item in a `FieldArray`. When I touch fields, they are validated using my sync validation function.
When I focus an blur some of the Fields in the array item, the array entry changes from `{}` to `undefined`.

I think it's a bug that the `{}` that I pushed is changed to undefined.

Empty strings are correctly set to undefined, which is, I think, correct behaviour.

**Comment by erikras** [comment]
Is this what you're talking about? How it goes from `{}` to `null`?

![screencast](http://i.giphy.com/eypGHFRhykmqY.gif)

**Comment by q42jaap** [comment]
That seems to be what is happening, although, I'm seeing undefined instead of null.

**Comment by q42jaap** [comment]
{} changing to null was unexpected to me, is there a reason behind that? Why would focus&blur cause a change from something valid (in a certain context) to invalid. From a json point of view, {} means something else as null.

**Comment by q42jaap** [comment]
The value in the store is set to `null`, but the valdatie function gets `{array:[ undefined]}` instead of `{array:[null]}`.
So maybe that's a bug too.

**Comment by erikras** [comment]
Yeah, it's a bug. Thanks for helping to test.

**Comment by erikras** [comment]
Just to clarify.... we think that it _should_ remain as `{}`?

**Comment by erikras** [comment]
Should be fixed by previous commit. Will comment here again when it is released.

**Comment by erikras** [comment]
Released as [`v6.0.0-alpha.14`](https://github.com/erikras/redux-form/releases/tag/v6.0.0-alpha.14).

**Comment by q42jaap** [comment]
works like a charm!
