### ISSUE TITLE
V6 Textfield with spaces

### ISSUE THREAD

**Issue by StijnAvdL** [erikras/redux-form#1027]
I cant have a textfield where it is possible to have also spaces in it. This is my component:

`<Field name="bug" component={bug =>
                            <TextField type="text"
                                hintText = "Fout rapporteren"
                                floatingLabelText="Fout rapporteren"
                                errorText = {bug.touched && bug.error}
                                fullWidth={true}
                                {...bug}
                                />
                        }/>`

And my simple schema:

`export default({SimpleSchema}) => ({
    name: "BUG_FORM",
    schema: new SimpleSchema({
        bug: {
            type: String
        }
    })
});`

But still in my form its not valide to insert a space. Can someone help me with this problem?

I have the following env:

- redux-form: 6.0.0-alpha.13
- material-ui: 0.15.0
- aldeed:simple-schema: 1.5.3

**Comment by erikras** [comment]
I can confirm that `redux-form@6.0.0-alpha.13` and `material-ui@0.15.0` work fine together, so your problem must be with the third library. You should raise the issue there.
