### ISSUE TITLE
V6 - Custom value reducer

### ISSUE THREAD

**Issue by eloytoro** [erikras/redux-form#1028]
So I was writing my own form tool since the previous versions of `redux-form` were lacking the awesomeness of v6 until I read the docs for the new version and immediately decided to drop my code and adopt the library (funny enough the API was very similar and I only had to change some prop names to get it working)

But writing custom form fields that handle complex values (like for example an autocomplete field that holds information of whats being shown in the input and what the actual value is) led me to write reducer-esque logic in my component logic

The `value` of my custom input field has this structure

```javascript
{
  inputText,
  data
}
```
where `inputText` is whats being shown and `data` is the value i care about

So when my autocomplete input changes I usually call `onChange` like this

```javascript
onChange({
  ...value,
  inputText: 'asdf'
})
```

And I thought this was very similar to actual reducers. If we were somehow able to catch actions dispatched to the form and describe how to handle the resulting value it would ease this logic

Proposed API

```javascript
// action creator
setInputText = (inputText) => {
  type: SET_INPUT_TEXT,
  inputText
};

// on input text change
onChange(setInputText('asdf'));

// the reducer
const autocompleteValueReducer = (value, action) => {
  switch (action.type) {
    case SET_INPUT_TEXT:
      return {
        ...value,
        action.inputText
      };
    default: return value;
  }
};

// pass it over to redux form
reduxForm({
  form: 'myForm',
  valueReducers: {
    autocomplete: autocompleteValueReducer
  }
})(MyForm);
```

**Comment by erikras** [comment]
First of all, thanks for suggesting API. :+1: But, I'm not sure that I understand the example and what it adds to the API. You are wanting to provide a function that the value for a specific field be filtered through before being saved to the Redux store?

**Comment by eloytoro** [comment]
@erikras more like "reduced" through, but yes thats the idea.
The value of a form field could be interpreted as a state

**Comment by erikras** [comment]
Sounds a bit like the [`normalize()` API](http://redux-form.com/5.2.4/#/api/reducer/normalize) from `v5` (not yet – but will be! – implemented in `v6`), except not as flexible. Am I wrong?

**Comment by erikras** [comment]
See #1115. It will be in next release.
