### ISSUE TITLE
V6 - field names with square brackets and validation

### ISSUE THREAD

**Issue by keown** [erikras/redux-form#1030]
version: 6.0.0-alpha.13

validation doesn't work if props `name` of `Field ` component contains square brackets.

**Comment by erikras** [comment]
I'm going to need more than that. Show me your validation function and your `Field`.

**Comment by erikras** [comment]
Square brackets are treated as arrays. See the validation working on the [Field Arrays Example](http://redux-form.com/6.0.0-alpha.13/examples/fieldArrays/).

**Comment by keown** [comment]
@erikras this is a gist of my form

https://gist.github.com/keown/b32309ad8d43faa996299d3730275117

**Comment by erikras** [comment]
Yeah, that syntax is not supported. Try `user.email`. The only thing allowed inside square brackets are array indices.
