### ISSUE TITLE
[V6 alpha 13] - Re-render still occurs on the entire form component

### ISSUE THREAD

**Issue by peterpme** [erikras/redux-form#1031]
Hey,

The work you've been doing for redux-form V6 has been amazing! Thanks 👍 

I did notice however that the entire form is still being re-rendered on key press. I've attached a screenshot below of the example project for reference:

http://redux-form.com/6.0.0-alpha.13/examples/simple/

Thanks again!

![re-render](https://cloud.githubusercontent.com/assets/1211905/15482221/1707e040-20f4-11e6-8608-f9d85751f613.gif)

**Comment by erikras** [comment]
What makes you think the whole form is being rerendered? And what's up with those funky colors?

**Comment by peterpme** [comment]
Hey, sorry for the lack of context! I'm using react-devtools in Chrome.

When you click `trace React updates` it'll automatically highlight the selections that are being updated!

**Comment by erikras** [comment]
Ooh!! That's new to me. Thanks!

However, you are confusing _updates_ with _renders_. Yes, the form component does receive new props on every keypress, but it does not re-render.

**Comment by peterpme** [comment]
Ah cool, thanks!
