### ISSUE TITLE
V6 alpha 13 - Field not binding value on changing

### ISSUE THREAD

**Issue by katcu** [erikras/redux-form#1034]
![image](https://cloud.githubusercontent.com/assets/19196404/15504391/4d36429e-21f1-11e6-9134-7cac08324a99.png)

Just tried alpha 13, but got a confusing problem that it seems the input filed did't bind any value during the typing.

And I'm using mxstbr/react-boilerplate with it.

**LoginForm.js**
```javascript

import React, {Component} from 'react';
import {Field,reduxForm} from 'redux-form';

const LoginForm = (props) => {
  const { handleSubmit, pristine, reset, submitting } = props
  return (
    <form onSubmit={handleSubmit}>
      <Field name="username" component={username =>
          <div className={username.asyncValidating ? 'async-validating' : ''}>
            <input type="text" {...username} placeholder="Username"/>
            {username.touched && username.error && <span>{username.error}</span>}
          </div>
        }/>
    </form>
  )
}

export default reduxForm({
  form: 'simple'  // a unique identifier for this form
})(LoginForm)
```
container : **Login.js**

```
class Login extends React.Component {
  render() {
    return (
      <LoginForm />
    );
  }
}


function mapDispatchToProps(dispatch) {
  return {
    dispatch,
  };
}

export default connect(createSelector(
  selectLogin(), (login) => ({ login })
), mapDispatchToProps)(Login);
```

**Comment by Iuriy-Budnikov** [comment]
+1

**Comment by Iuriy-Budnikov** [comment]
Issue with onchange

**Comment by Iuriy-Budnikov** [comment]
Nope, was my mistake. It works well.

**Comment by katcu** [comment]
@Iuriy-Budnikov sure it works well standalone. could it be compatibility issue in 

> asynchronously loaded components ---[ref blog](http://blog.mxstbr.com/2016/01/react-apps-with-pages/)

? I am facing another problem when intergrate `mxstbr/react-boilerplate` with `mjrussell/redux-auth-wrapper`
@mxstbr

**Comment by Iuriy-Budnikov** [comment]
@katcu did you add form to reducer ?

**Comment by Iuriy-Budnikov** [comment]
[https://github.com/erikras/react-redux-universal-hot-example/blob/master/src/redux/modules/reducer.js#L8](url)

**Comment by katcu** [comment]
@Iuriy-Budnikov @erikras Pls check out my branch which I reproduced the issue:
https://github.com/katcu/redux-form-with-react-boilerplate

**Comment by katcu** [comment]
@Iuriy-Budnikov Just forget it~ I've given it up, I found another similar boilerplate that works fine with it.
Thanks for your help :+1:

**Comment by ericalli** [comment]
Also experiencing the same issue as @katcu when using [react-boilerplate](https://github.com/mxstbr/react-boilerplate) or any other project that asynchronously loads components. The form initializes and change events fire (with the correct payload), but the value is not binded to the corresponding field.

Any idea why this could be happening? Using redux-form v6.0.0-alpha.14
