### ISSUE TITLE
V6 - How to show field error on submit

### ISSUE THREAD

**Issue by VladShcherbin** [erikras/redux-form#1035]
Currently, to show the error, we check the field for `touched` and `error`. When we submit and get errors from the server, we have the `error`, but the field isn't *touched*, so the field error is not shown.

Example from the docs - [Submit Validation](http://redux-form.com/6.0.0-alpha.13/examples/submitValidation/). Click *Log In* and you won't see the field errors until you touch them.

What's the recommended way to show the errors?

**Comment by erikras** [comment]
It's supposed to mark all the fields as `touched` when you submit.

Sounds like you've found a bug. 👍  Well done.

**Comment by erikras** [comment]
Published fix as [`6.0.0-alpha-15`](https://github.com/erikras/redux-form/releases/tag/v6.0.0-alpha.15).
