### ISSUE TITLE
V6 - Question: How to see errors for other fields.

### ISSUE THREAD

**Issue by tnrich** [erikras/redux-form#1036]
Hey there, 

I'm excited to try out v6, but I was wondering how to tell if another field has an error. I saw that there is a "value selector". Will there be an equivalent "error selector" sometime in the future? 

Or is there already a way to view errors for the entire form? 

Thanks!
Thomas

**Comment by erikras** [comment]
> Will there be an equivalent "error selector" sometime in the future?

Yes. There will be some mechanism for that. I haven't decided exactly how, though, yet. #841

> Or is there already a way to view errors for the entire form?

Not at the moment.

**Comment by tnrich** [comment]
Okay, let me know what you decide :)

**Comment by tnrich** [comment]
Any update on this one @erikras ? Thanks very much!

**Comment by gustavohenke** [comment]
v6.2.0 went with `getFormSyncErrors` and `getFormSubmitErrors` 🎉
