### ISSUE TITLE
FieldArray sub fields not rerendered on FieldArray elements insert/remove

### ISSUE THREAD

**Issue by tnrich** [erikras/redux-form#1038]
I'm seeing an issue where other Fields within a FieldArray aren't re-rendered when the field array has new elements inserted/removed.

Here is a contrived example of what is happening: 

``` js
<FieldArray name='sequences' component={function (seqs) {
  return <div>
    <button onClick={function () {
      seqs.push('')
    }}> Add another field</button>
    {seqs.map(function (seq) {
      <Field name={seq} component={function (sequence) {
          if (seqs.length > 1) {
            return <div>more than 1</div>
          }
          return <div>less than 1</div>
        }}/>
      }) }
  </div>
}}/>

```

When I add fields, the first field is stuck at "less than 1"

Hopefully this makes sense. 

Cheers,
Thomas

**Comment by erikras** [comment]
Yep, I understand the problem exactly. You cannot rely on closures (e.g. `seqs`) in your components. See #985 and the explanation I gave today on [`v6.0.0-alpha.14`](https://github.com/erikras/redux-form/releases/tag/v6.0.0-alpha.14)'s release.

If you could give a less contrived example about what you want to accomplish, perhaps I could suggest a solution.

**Comment by tnrich** [comment]
Hey @erikras , thanks for the explanation. I'm still struggling to figure out how to allow my subFields to rerender when their neighbors change, as well as remove themselves from and shuffle their order within the array. It seems like you touched on it here, but I still have a few questions about it:

>How would we write stuff with FieldArray if we're no longer allowed to use arrow functions?
>>Sure, you will.

>```js
const renderMembers = array =>
  (
    <div>
      {array.map(name => <Field name={name} component="input"/>)}
      <button type="button" onClick={() => array.push()}>Add Member</button>
    </div>
  )

>@reduxForm({ form: 'myForm' })
class MyForm extends Component {
  render() {
    const { handleSubmit } = this.props
    return (
      <form onSubmit={handleSubmit}>
        <FieldArray name="members" component={renderMembers}/>
      </form>
    )
  }
}
```

Imagine now that the Field within render members needs to do things like remove itself from the array or update its state based on the number of items within the array. How would we go about that in this case?



Here is my actual code (sorry it's quite messy. I'm in the middle of refactoring it to use v6). AddInserts gets its inserts array from the : 
```js
//Design.js
...
function renderInserts (inserts) {
      return <AddInserts
        runj5={runj5}
        j5Running={j5Running}
        changePage={changePage}
        //disabled={destinationVector.error || assembly_methodType.error || !(caretPosition > -1 || selectionLayer.start > -1) }
        inserts={inserts}
        />
    }
...
render() {
          <FieldArray 
            name="inserts" 
            component={renderInserts}/> 
}
...


//AddInserts.js
export default class AddInserts extends React.Component {
  render () {
    var {disabled, inserts, runj5, j5Running} = this.props;
    console.log('rerendering!:')
    
    function renderInsert (_insert) {
      var insert = {
        ..._insert,
        onChange: function(event) {
          _insert.onChange({sequence: event.target.value})
        },
        onDrop: function(files) {
          //tnr: we'll want to do basic checking here
          files.forEach(function(file, index) {
            var fileReader = new FileReader() //tnr it might not be the most effecient to instantiate multiple file readers
            fileReader.onload = function(event) {
              anyToJson(event.target.result, function(result) {
                if (index === 0) {
                  _insert.onChange({...result[0].parsedSequence, fromFileUpload: true
                  })
                } else {
                  //add all the inserts up to 8 total..
                  inserts.push({...result[0].parsedSequence, fromFileUpload: true})
                }
              })
            }
            fileReader.onerror = function(err) {
              console.error(err)
            }
            fileReader.readAsText(file)
          });
        }
      }
      return <div>
        <label className="insertLabel"> Insert #{index + 1} </label>
        <div className="insertInputContainer">
          <div className="leftInputContainer">
            <SequenceInput placeholder="Input insert sequence" input={insert}/>
          </div>
          
          <div className="rightInputContainer">
            <SortUp className={"moveUpButton" + (index === 0 ? ' disabled' : '')} type="button" onClick={() => {
                if (index !== 0) {
                  inserts.swap(index, index - 1);  // swap field with it's predecessor
                }
              }}/>
              
            <Close className={"removeInsertButton " + (inserts.length === 1 ? ' disabled' : '')} type="button" onClick={() => {
                  if (inserts.length !== 1) {
                    inserts.remove(index);
                    var clicked = false;
                    var msg = "Undo insert deletion"
                    alertify
                    .closeLogOnClick(true)
                    .log(msg, function(ev) {
                      ev.preventDefault();
                      if (!clicked) {
                        inserts.insert(insert.value, index);
                        clicked=true;
                      }
                    })
                  }
                }}><i/> Remove insert
              </Close>
              <SortDown className={"moveDownButton " + ((index === inserts.length - 1) ? ' disabled' : '')} type="button" onClick={() => {
                  if (index !== inserts.length - 1) {
                    inserts.swap(index, index + 1); // swap field with it's successor
                  }
                }}
                />
            </div>
          </div>
        </div>
    }
    return (
	    <div className="AddInserts">
        <Card disabled={disabled} number={3} title='Add Inserts' className='AddInserts'>
        	<div>
  	      	{inserts.map((insert, index) => {
              return <Field name={insert} component={renderInsert}/>
            }
  	      	)}
  	      	<button className="addInsertButton" type="button" onClick={() => {
  	      		inserts.push('')
  	      	}}><i/> + Add an additional insert
  	      	</button>
  	      	<br/>
            <div className='taRunJ5Wrapper'>
              <button className="computeButton" type="button" onClick={() => {
                runj5()
              }}><i/> Run inFusion designer
              </button>
              <ReactCSSTransitionGroup transitionName="taSpinner" transitionEnterTimeout={500} transitionLeaveTimeout={500}>
              {
                j5Running &&
                  <Spinner key='spinner'/>
              }
              </ReactCSSTransitionGroup>
            </div>

        	</div>
        </Card>
  	  </div>
    )
  }
}
```

Thanks for the help and I hope the example makes sense. It has some deliberate errors in it currently because I'm not sure how to solve the inserts passing problem...

**Comment by tnrich** [comment]
From what @ooflorent said earlier, it looks like I'll need to do this:

>Whenever component changes, Field does not re-render.
You must add extra props to your Field element if you want them to update:
```js
render() {
  const {isLoading} = this.props
  return (
    <Field
      name="fieldName"
      isLoading={isLoading}
      component={field =>
      <div>
        <input
          type="text"
          disabled={field.isLoading}
          {...field}  />
      </div>
    }/>
  )
}
```

@erikras is the above pattern still the recommended approach for getting the field's component to update?

Thanks again!

**Comment by ooflorent** [comment]
@tnrich You should avoid the closure. But the pattern is the same. See https://github.com/erikras/redux-form/issues/976#issuecomment-220016992

**Comment by tnrich** [comment]
@ooflorent and @erikras, thanks for the help. I still have a couple questions though. 

First off is the following code "correct"?
If so, this pattern seems a little funky when dealing with field arrays.. 

```js
...
function renderInserts (fields) {
//How should we destructure off the fields here, like this?
var {disabled, ...inserts} = fields
  return <AddInserts
    inserts={inserts}
    />
}
...
<FieldArray 
  name="inserts"
  disabled={disabled}
  component={renderInserts}/>  
```


It seems strange to me to pass the props down on the "fields" object. 
Could there be a second argument perhaps? 

```js
function renderInserts (inserts, props) {
var {disabled} = props
  return <AddInserts
    inserts={inserts}
    />
}
```

Or maybe give the fields a named key..?

```js
function renderInserts ({fields, disabled}) {
  return <AddInserts
    inserts={inserts}
    />
}
```

What do you all think? Thanks again!

**Comment by tnrich** [comment]
Any thoughts @erikras and @ooflorent. Does this question make sense?

**Comment by erikras** [comment]
> It seems strange to me to pass the props down on the "fields" object.  Could there be a second argument perhaps?

It makes perfect sense on `<Field>`, but you might have a good argument for separating it for `<FieldArray>`, as the pseudo-array object, which you are calling `fields`, perhaps should be its own thing. I normally just call it `array`, but `fields` might be a better term. Your last example `({ fields, disabled })` makes a lot of sense.

Any others want to weigh in on this?

**Comment by babsonmatt** [comment]
I'm a fan of `({ fields, disabled })` as well

**Comment by erikras** [comment]
Go vote over on #1063.

**Comment by satyaki20** [comment]
Hi , i am using FieldArray and i want my fieldArray to have one default element. and then user can add more. Can any one please help me how to insert an default element in default fields Array?

**Comment by hasibsahibzada** [comment]
I have an issue with the boolean values with checkBox components. 
If i want to push a checkbox value (true or false) to the fields, the checkbox with the "true" value gets merged in the field store but not with the "false".
```javascript
    onCheckboxChange(e) {
          const { fields } = this.props;
          const value = e.target.checked;
          const name = e.target.name;
          const updatedField = Object.assign({}, fields.pop(), { [name]: value });
         // updatedField contains the new value with false or true value.
          fields.push(updatedField);
        // but after pushing the store does not contain the field with the false value.
}
```
note: the initialvalues for the fields contains false values.

**Comment by danielrob** [comment]
Closing this out on general expiry grounds, not sure there is a specific purpose this issue is serving at this point. Feel free to bring new evidence to light!

 @satyaki20 `initialValues` can be used on e.g. `fieldName[0]` to provide a default value.
