### ISSUE TITLE
Expose submit bound action (enhancement)

### ISSUE THREAD

**Issue by alexwix** [erikras/redux-form#104]
I have a form that Im trying to render inside a another component (a react-bootsrap modal) like this:
```javascript
      <Modal
        show={showModal}
        onHide={this.closeModal}>
        <Modal.Header closeButton>
          <Modal.Title>Add Item</Modal.Title>
        </Modal.Header>
        <Modal.Body>
          <DynamicItemForm ref="form" context={this.context} formName="Add" fieldsNeeded={Object.keys(itemProps)} />
        </Modal.Body>
        <Modal.Footer>
          <Button onClick={this.closeModal}>Close</Button>
          <Button bsStyle="primary" onClick={this.submitForm}>Save</Button>
        </Modal.Footer>
      </Modal>
```
I want to submit the form using the button that is rendered in the Modal.Footer. 
This is the only way that I managed to do it with the current implementation:
```javascript
  submitForm() {
    var event = new Event('submit');
    React.findDOMNode(this.refs.form).dispatchEvent(event);
  }
```
What do you think about exposing a submit bound action?  
That way my submitForm would look something like:
```javascript
  import {submit} from 'redux-form';

  submitForm(data) {
    const {  dispatch  } = this.props;
    dispatch(submit(formName))
  }
```

**Comment by erikras** [comment]
Hmm... and what would that submit do, exactly, since you haven't supplied an `onSubmit` prop to your form element?

**Comment by alexwix** [comment]
I'm sorry I forgot to mention that. I do provide an onSubmit handler inside the `DynamicItemForm` component and it is supposed to just push the data to the server.

**Comment by erikras** [comment]
The problem is that you can't really use Redux actions to pass information between components, you can only update the store via your reducer. So, to accomplish this, redux-form would have to save a `pleaseSubmitNow: true` value to its store, wait for that to be passed in as a prop, detect that the value has changed from `false` to `true`, and then call `this.props.onSubmit()`. Gross. Smells like an antipattern.
