### ISSUE TITLE
V6 - Does it really require React V15?

### ISSUE THREAD

**Issue by epeli** [erikras/redux-form#1041]
Or would `^0.14.0 || ^15.0.0-0` work too? In my testing it seems to work well.

**Comment by ooflorent** [comment]
`redux-form@6` does a lot to ensure managed inputs are compatible with `react@15`. That's why we raised the version. Allowing `react@0.14` without testing on it is not is a bad idea. Moreover, there is not reason not to update to v15.

**Comment by ooflorent** [comment]
But yes, it could work on `react@0.14` but we don't want to support it.

**Comment by epeli** [comment]
Fair enough. Not a big deal. I just find it weird because 15.0.0 is not a breaking change after 0.14.0. React devs just wanted to signal the maturity of React with it.

**Comment by ooflorent** [comment]
It is because it changes how manage components work.
