### ISSUE TITLE
No access to event object 

### ISSUE THREAD

**Issue by damamsrinivas** [erikras/redux-form#1046]
When I use handleSubmit in-built function, event object is not bound to my callback event. I get fields as the first argument and some other function as the second. I want know the target event.

**Comment by ooflorent** [comment]
When using `handleSubmit` you can't access the event. You have to replace this:

```js
<form onSubmit={this.props.handleSubmit}>
```

By something like:

```js
// Update `render` to use your own event listener
<form onSubmit={this.onSubmit}>

// Define the listener
onSubmit(event) {
  const {target} = event
  //     ^^^^^^

  this.props.handleSubmit(event)
}
```
