### ISSUE TITLE
V6-alpha.14 How to pass props into custom component?

### ISSUE THREAD

**Issue by Darmody** [erikras/redux-form#1048]
How to pass other props into custom component ?

```javascript
  <Field name='field' component={renderField(myProps)}
```

That works fine in alpha.13, but for alpha.14, it will cause `lose focus` issue #961.

**Comment by babsonmatt** [comment]
@Darmody I believe you can just set them on Field

**Comment by Darmody** [comment]
@babsonmatt Oh! u are right!
