### ISSUE TITLE
Default values are different from form field values

### ISSUE THREAD

**Issue by arkwright** [erikras/redux-form#105]
I have an `<input type="text" />` into which the user can enter an integer. This field's default value is populated with whatever `Number` is stored in the corresponding model, obtained via JSON API.

If the user does not touch the field, `onSubmit` will receive the original (default) value, the number `1`. But if the user _does_ touch the field, redux-form returns the appropriate `input.value`, which is the string `"1"`.

This means that for optional non-string types, my data handlers have to handle `undefined`, `""`, `1`, and `"1"`. I feel that if the `input.value` returns a string, the `onSubmit` and validator ought to _always_ see a string.

**Comment by erikras** [comment]
Excellent point.

**Comment by arkwright** [comment]
For what it's worth, I'm working around the issue right now by running my models through a conversion function, casting, e.g., numbers to strings before the form defaults are hydrated.

**Comment by erikras** [comment]
Hmm... One problem I foresee is that there might be a custom component that takes an integer and calls `onChange` with an integer, and it seems wrong to break that by doing `toString` conversions at some point in the process.

**Comment by arkwright** [comment]
Yeah. One solution would be to have the component receive the value first, then the HOC can read the value back and persist it in the store. This might not be desirable, though, because I suspect you're simply putting the defaults into the store, and letting the appropriate `props` set the value; the approach I just described would require that each component's value be set in two different ways (both directly and via `props`).

Another way might be to set the defaults in the store, let them trickle down, then read the component values (the component can cast them if desired), then set the defaults again (if the values differ), _then_ do initial validation.

**Comment by erikras** [comment]
I think this is up to the developer to maintain the types. It would be pretty simple to do some formatting and/or parsing in a [normalizer](http://erikras.github.io/redux-form/#/examples/normalizing).
