### ISSUE TITLE
Connecting Mapdisptachtoprops in V6 reduxForm() 

### ISSUE THREAD

**Issue by jasan-s** [erikras/redux-form#1050]
Version 5 allowed to pass in reduxForm(config:Object, mapStateToProps?, **mapDispatchToProps?**, mergeProps?, options?)

however the Version 6 only has reduxForm(config:Object) . 

How do we pass in our Action creators to handle submit?

**Comment by ooflorent** [comment]
Using `react-redux`'s `connect` HoC.

**Comment by jasan-s** [comment]
so i would export default the connect HOC rather than the reduxForm?

**Comment by erikras** [comment]
https://github.com/erikras/redux-form/issues/698#issuecomment-221721037

```js
class MyForm extends Component {}
MyForm = reduxForm(config)(MyForm)
MyForm = connect(mapStateToProps, mapDispatchToProps)(MyForm)
export default MyForm
```

Order does not matter unless you are specifically passing some state into `redux-form`, as in the [Initializing From State](http://redux-form.com/6.0.0-alpha.14/examples/initializeFromState/) example.

**Comment by luisrudge** [comment]
This should be in the docs :heart:

**Comment by jaspersorrio** [comment]
Its December already and this is still not in the first example.

http://redux-form.com/6.3.1/docs/GettingStarted.md/

**Comment by erikras** [comment]
@jaspersorrio What, specifically, should be in the docs? The only reason for confusion was that `v5` used to do the binding for you, but `v6` does not, which it explicitly says in the [`v6` Migration Guide](http://redux-form.com/6.3.1/docs/MigrationGuide.md/#-mapstatetoprops-and-mapdispatchtoprops-). It doesn't make sense to list all the things a library does _not_ do on the Getting Started page.

**Comment by Schachte** [comment]
I think this is a very big change that should be clearly documented...

**Comment by alexbahl** [comment]
100% needs to be in the docs........ what should of taken me 1 sec looking at the docs took me forever to figure out on my own due to lack of documentation.

**Comment by gustavohenke** [comment]
PRs are welcome

**Comment by jaspersorrio** [comment]
Hey @erikras thanks for this library. I apologise if i may sound rude earlier. I agree with what you say. However i just wanted to highlight what @alexbahl said. It took me a day to find this information. And it made no sense for me to read the migration guide to V6 as i wasn't a V5 user.

Your new users might face the same problem if you don't make this clear.

**Comment by machadogj** [comment]
It would also be very helpful to document somewhere that the `error` prop can't be overridden by this approach.

**Comment by Recmo** [comment]
I'm working arroudn this issue using the following wrapper:

```js
import { connect } from 'react-redux';
import { reduxForm } from 'redux-form';

const defaultFormName = config => Component =>
  reduxForm({
    form: Component.displayName || Component.name,
    ...config,
  })(Component);

const optionalConnect = (stateMap, actionMap) => Component =>
  stateMap || actionMap ? connect(stateMap, actionMap)(Component) : Component;

const connectForm = (config, stateMap, actionMap) => Component =>
  optionalConnect(stateMap, actionMap)(defaultFormName(config));
```

You use it as `connectForm()(Component)` pretty much as the v5 one mentioned in the issue description. It has some nice features:

* `config.form` is now optional (Form name defaults to component name)
* redux's `connect` is only used when necessary (i.e. either of the maps is defined)

**Comment by ecavalier** [comment]
const postNewPost=reduxForm({
  form: 'postNew'

})(PostsNew);

function mapDispatchToProps(dispatch) {
  return bindActionCreators({createPost},dispatch)
}
export default connect(null,mapDispatchToProps)(postNewPost)

**Comment by AlisterC93** [comment]
It's currently July and the learner docs still haven't been updated to explain this change. Could someone get on this before this issue is a year old? Maybe save someone else 2 hours trying to figure out what they've configured wrong when it's the package itself? Would be cool.
