### ISSUE TITLE
Json Form Sometimes Miss OnSubmit Function and Post Form

### ISSUE THREAD

**Issue by sarbland** [erikras/redux-form#1051]
I'm using Json Form and submitting the form but sometimes it miss it's `onSubmit` event and postback the page and send form in url. Which causes the error of URL too long.

Unable to debug the `onSubmit` event because it didn't trigger.

```js
onSubmit: function (errors, values) {
		debugger;
event.preventDefault ? event.preventDefault() : event.returnValue = false;
				
if (typeof(ValidateSubmit) == 'function')
{
	if(ValidateSubmit(values) == false)
	{
		return false;
	}
}
```

**Comment by ooflorent** [comment]
This is a usage question, and we encourage you to ask it on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

This is the only way to ensure the same question doesn’t get asked many times in a row, and that folks who have the same question in the future will be able to find it.

I’m closing for these reasons.

**Comment by sarbland** [comment]
Sorry for irrelevant post. I've posted on StackOverflow as well, hope for respond with solution there.

[http://stackoverflow.com/questions/37461661/json-form-sometimes-miss-onsubmit-function-and-post-form](url)

Thank you.

**Comment by ooflorent** [comment]
It looks like your question is about to get closed. I suggest you to add relevant tags on it and your component code, including the `reduxForm` call.
