### ISSUE TITLE
6.0.0-alpha.14: registerField / unregisterField are not exported

### ISSUE THREAD

**Issue by babsonmatt** [erikras/redux-form#1052]

**Comment by erikras** [comment]
That was somewhat intentional. Can you give a good reason why they should be?

**Comment by babsonmatt** [comment]
> redux-form exports all of its internal action creators, allowing you complete control to dispatch any action you wish. 
> registerField(form:String, name:String, type:String)
> Registers a field with the given name and field type ('Field' or 'FieldArray') with the store.

I figured since it was in the docs it was fair game :smile:

I was just converting some older forms from v5 to v6 and I realized we were using a field that had no visual representation (so basically a hidden field of sorts) and with v6 that field would need to be registered in order for us to use it.  That being said, this is probably poor form so maybe not the best case for the action to be made avail.

**Comment by erikras** [comment]
Ha! I didn't realize it was in the docs. Hmmm....

Seems like something like this might work.

```js
const noRender = () => null
...
<Field name="myHiddenField" component={noRender}/>
```

But yeah, you _probably_ shouldn't be registering and unregistering fields manually. I think the right answer is to remove that from the docs.

**Comment by babsonmatt** [comment]
@erikras sounds good, thanks for the suggestion
