### ISSUE TITLE
6.0.0-alpha.13 potentially got updated?

### ISSUE THREAD

**Issue by brotzky** [erikras/redux-form#1054]
Hi,

Were there any updates mistakingly pushed to 6.0.0-alpha.13 when 6.0.0-alpha.14 was released? I don't recall seeing action redux-form/REGISTER_FIELD followed by redux-form/UNREGISTER_FIELD in my redux-logger. Also, the losing focus on type now occurs on _only one of my input fields_, but _not_ the other other one. A very strange bug that I can't solve, so this is one of my last ideas.

I've tried reverting to 2 days ago, but the error persists. Everything was working fine at that point.

**Comment by erikras** [comment]
That may have happened to the [6a13 examples](http://redux-form.com/6.0.0-alpha.13/examples/).

Also, I think I messed up the tagging on the release of 6a14, so if you're git tags, there may be some problems. But the 6a13 in NPM is the same as the day it was released, as NPM doesn't let you do shenanigans like that.

**Comment by brotzky** [comment]
Thanks, I'll get back to here once I resolve the issue!

**Comment by brotzky** [comment]
Hmmm, do you know what would fire `redux-form/REGISTER_FIELD. It seems the only field that fires that is also the same field that loses focus on typing. `6.0.0-alpha.13`

**Comment by brotzky** [comment]
So after looking to the paint rendering function built into Chrome Dev Tools I've come to the conclusion that:

The first input field entirely re-renders on every change event. 
The second input field _does not* re-render on every change. 

Anyone know why they would have different behaviours? Seems very odd. 
` react@15.1.0`, `6.0.0-alpha.13`.

**Comment by brotzky** [comment]
I resolved the issue by adding

```javascript
  shouldComponentUpdate(nextProps) {
    return nextProps.id !== this.props.id;
  }
```
The input field doesn't re-render anymore on input change / typing
