### ISSUE TITLE
initialValues only works for first rendered form of name

### ISSUE THREAD

**Issue by jayphelps** [erikras/redux-form#1055]
Sort of a tough problem to explain, so feel free to modify the title.

The issue I'm experiencing is that I have a _very_ complex, multi-page form, so I'd like to take the very redux approach of splitting certain fields and sections into their own components and then having them connect to the store/redux-form themselves. In general, the approach works, however the `initialValues` feature only seems to work on the first-rendered component for that given form name. They need to share the same form name because the top-level form handles submitting of the entire form.

Here's a minimial viable reproduction: http://jsbin.com/xicileg/edit?js,output

```js
const NameField = reduxForm({
  form: 'example-form',
  fields: ['name'],
  initialValues: {
    name: 'Bilbo Baggins'
  }
})(
  ({ fields: { name } }) =>
    <div>
      Name: {name.value || 'THIS IS NOT SET WITH DEFAULT'}
    </div>
);

const Form = reduxForm({
  form: 'example-form',
  fields: ['message'],
  initialValues: {
    message: 'works'
  }
})(
  ({ fields: { message } }) =>
    <div>
      <div>Top level value: {message.value}</div>
     <NameField />
    </div>
);
```

If I provide every field to the top-level component, it works, however this is now makes the top-level form need to know the schema up-front which in my case it cannot because the inner components vary depending on dynamic conditions only known by the children. i.e. I really would rather not have to define the entire schema w/ initialValues for every field in the form in one place as it appears that will make maintenance a nightmare for me.

Perhaps this isn't a bug and is expected behavior? If so, any insight on decoupling is appreciated.

**Comment by kristijanhusak** [comment]
I had the similar issue, just make sure you pass unique `formKey` prop to the form, together with `initialValues`, and it should work (same way the Redux asks for `key` property). Something like this should work for you:

```js
const Form = reduxForm({
  form: 'example-form',
  fields: ['message'],
  initialValues: {
    message: 'works'
  }
})(
  ({ fields: { message } }) =>
    <div>
      <div>Top level value: {message.value}</div>
     <NameField formKey="uniqueKey"/>
    </div>
);
```

**Comment by erikras** [comment]
This is a known bug that dates back to #621, however, #843 should have just fixed it.

I will expedite the next release to publish that bug fix.

**Comment by erikras** [comment]
Fix published as [`v5.2.5`](https://github.com/erikras/redux-form/releases/tag/v5.2.5).

**Comment by jayphelps** [comment]
@erikras well that was fast. Glad to hear a fix was already in the works. I had seen #621 and also experienced the "not until second render" bug, didn't realize it was the same issue. 👍 

Thanks!

**Comment by erikras** [comment]
That's pretty awesome. If you go to your JSBin and flip the `4` to a `5` in the `redux-form` import, the problem vanishes. I ❤️ JSBin!
