### ISSUE TITLE
infinite loop on switching to 6.0.0-alpha.14 with autofocus

### ISSUE THREAD

**Issue by pathsny** [erikras/redux-form#1056]
Hi, I have a form with autofocus=true. I noticed that on switching from v13 to v14 alpha that the page would hang and my redux logger is spewing a ton of 
 redux-form/FOCUS events

**Comment by erikras** [comment]
What is `autofocus=true`? That's not a `redux-form` thing.

**Comment by pathsny** [comment]
It's an html5 attribute on input https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input. 
It tells the browser that this field should have focus when the form is first rendered. This works exactly as expected on alpha-13, but on 14 I run into the loop.

**Comment by brotzky** [comment]
Are you using specifically using `<input type="text" autoFocus />` ?
https://facebook.github.io/react/docs/tags-and-attributes.html#html-attributes

**Comment by pathsny** [comment]
I'm using material-UI. So  <AutoComplete autoFocus={true}...

**Comment by erikras** [comment]
All `redux-form` is doing is dispatching a `FOCUS` action when the `onFocus` event handler is called. If Material UI is calling that a bazillion times, that's Material UI's problem.

**Comment by gustavohenke** [comment]
@erikras is probably right, it's not an issue of Redux Form.
I'm using `autoFocus` quite a lot in my apps and had no problems so far.
