### ISSUE TITLE
V6 Alpha 14 - React hot loader breaks forms

### ISSUE THREAD

**Issue by alisd23** [erikras/redux-form#1057]
It looks like the webpack react-hot-loader loops over all form components' prototype properties before any of the forms have rendered. This causes a call to the (in my case) **valid** property on the form component, which crashes at this line (in the getter):

``` javascript
 return this.refs.wrapped.getWrappedInstance().valid
```
It seems there is no wrapper ref yet as this is called before the render function is called, therefore before the ref is created.

Maybe just need some extra error checking to check the refs object exists? I can put a pull request in if you think that makes sense

**Comment by nygardk** [comment]
Can you check if it's the same problem as in #1010, i.e. does the provided workaround help in your case?

**Comment by mikepugh** [comment]
It appears to be the same problem as #1010 . I updated my export per the recommendation and now hot loading works again.

**Comment by ooflorent** [comment]
I'm closing the issue since @nygardk provided a solution in https://github.com/erikras/redux-form/issues/1010#issuecomment-221524502.
