### ISSUE TITLE
V6 - Checkbox as a custom element

### ISSUE THREAD

**Issue by VladShcherbin** [erikras/redux-form#1058]
I'm trying to do a custom checkbox component, but it's a bit weird. Simple example:

```js
<Field
  name="isVisible"
  component={ props => <input type="checkbox" {...props} /> }
/>
```

This component will have a `value` prop, but not the `checked` prop. Even initial `boolean` value doesn't help. So in order to make it work, we need to do so:

```js
<Field
  name="isVisible"
  component={ props => <input type="checkbox" {...props} /> }
  type="checkbox"
/>
```

Is it supposed to work this way?

**Comment by babsonmatt** [comment]
@VladShcherbin I'd say that's working as intended, Field needs to know what kind of component it's working with

**Comment by erikras** [comment]
Yes, that is working as expected. The recommended way to do that is:

```js
<Field name="isVisible" component="input" type="checkbox"/>
```

**Comment by VladShcherbin** [comment]
@babsonmatt @erikras I still don't get it. This was just a simple example. A little bit bigger one:

```js
const Checkbox = props => (
  <div className="form-group">
    <label htmlFor={props.name}>{props.label}</label>
    <input type="checkbox" id={props.name} {...props}
    {props.touched && props.error && (
      <p className="error">{props.error}
    )}
  </div>
)
```

Now, we can use it this way:

```js
<Field name="isVisible" component={Checkbox} />
```

I expect the custom `Checkbox` component to be complete, so I can use the above syntax. But, unfortunately, I will always need to add `type` to it so it looks like this:

```js
<Field name="isVisible" component={Checkbox} type="checkbox" />
```

For me, this is weird as I expect custom component to be independent. Maybe it is possible to make `Field` understand, when to add `checked` prop (for example from type of initial value)

Even in the docs:

> checked
> An alias for value only when value is a boolean. Provided for convenience of destructuring the whole field object into the props of a form element.

The initial value is boolean, but still it has `value`, but not the `checked` prop.
