### ISSUE TITLE
v6 Show form values in confirmation dialog - formValueSelector alternative in form component?

### ISSUE THREAD

**Issue by anyong** [erikras/redux-form#1059]
How can I display the currently input form values for the user to confirm before actually submitting the form?

The form name is not available anywhere within the connected form component, by default, so I end up doing this every time:

```js
<MyFormComponent
    form={someFormName}
    formName={someFormName}
/>
```

So that I can access `this.props.formName` from within the component, and then I also end up either duplicating all of the field names for calling `formValueSelector`, or manually navigating to the form in the state tree to get `state.form.formName.values`. What I'd like to do is simply this:

```js
class MyFormComponent extends Component {
  // ...
  render () {
    const values = this.props.getFormValues();

    return (
      <form onSubmit={this.props.handleSubmit}>
        {/* form Fields ... */}
        <button type="button" onClick={showDialog}>Confirm</button>
        <Dialog>
            Are you sure?
            {/* show the values here */}
            <button type="submit">Yes, Do It</button>
        </Dialog>
      </form>
    )
  }
}
```

It seems like `getFormValues` would be pretty trivial to implement and it would make this kind of thing a lot easier. Am I missing something, or is there a better way to do this already?

Thanks.

**Comment by ooflorent** [comment]
Redux Form exposes `values` which is not currently documented.

- [`src/values.js`](https://github.com/erikras/redux-form/blob/v6/src/values.js)
- [`src/__tests__/values.spec.js`](https://github.com/erikras/redux-form/blob/v6/src/__tests__/values.spec.js)

**Comment by anyong** [comment]
@ooflorent Sorry but I'm not exactly clear on how to use `values`, could you give an example? It looks like I'm supposed to do something like this:

```js
import {
    reduxForm,
    values,
} from 'redux-form';

class MyForm extends Component {
    render () {
        return (
            <div>
                <Field name="test" component="input"/>
                {this.props.values.test}
            </div>
        );
    }
}

let ValuesForm = values(config)(MyForm);

ValuesForm = reduxForm(config)(ValuesForm);

export default ValuesForm;
```

But this doesn't seem to work, at least, it doesn't add a `values` prop to the form component.

I also don't understand how I'm supposed to use either this or `formValueSelector` and still pass in the form name dynamically without wrapping the entire form component in a function, i.e.,

```js
function makeForm (formName) {
  class Form extends Component {
    // ...
  }
  const valueSelector = formValueSelector(formName);
  connect(...)
  return Form;
}
```

It seems like there should be a better way to do this?

**Comment by brneto** [comment]
@ooflorent Why have values not been documented yet? Can I use it or it can be removed in the future versions?
