### ISSUE TITLE
Poll: FieldArray API – passing through additional props

### ISSUE THREAD

**Issue by erikras** [erikras/redux-form#1063]
Let's say your field has an array of hobbies, like [the current FieldArray example](http://redux-form.com/6.0.0-alpha.14/examples/fieldArrays/). At the moment, the API looks like:

```js
const renderHobbies = (fields) =>
  fields.map(field => <Field name={field} component="input" type="text"/>)
...
<FieldArray name="hobbies" component={renderHobbies}/>
```

The important thing to note, for the sake of this discussion, is that `renderHobbies` takes _only one parameter_, which is the pseudo-array object that provides methods like `map` and `forEach` to iterate through field names.

Okay, fine, but what if you want to pass a config parameter into `renderHobbies`. Let's say you want to limit the number shown for some reason, so you want to pass a `maxShown` prop.

Currently, this would be accomplished like this:

```js
const renderHobbies = (fields) =>
  fields.map((field, index) =>
    index < fields.maxShown ?
    <Field name={field} component="input" type="text"/> : 
    null)
...
<FieldArray name="hobbies" component={renderHobbies} maxShown={5}/>
```

Note that the `maxShown` prop gets attached _to the pseudo-array object_. On #1038, @tnrich has questioned how much sense that makes.

So we're having a poll. Using the new emoji response feature of GitHub, please vote for the comment below that best represents your preference. You may suggest alternatives and vote for the suggested alternatives.

**Comment by erikras** [comment]
## Option 1

Leave it like it is, with the props being placed directly onto the pseudo-array.

```js
const renderHobbies = ({ maxShown, ...fields }) =>
```

**Comment by erikras** [comment]
## Option 2

Put the props into a separate parameter

```js
const renderHobbies = (fields, props) =>
```

**Comment by erikras** [comment]
## Option 3

Combine them both into an object, with a key of.... `fields`?

```js
const renderHobbies = ({ fields, maxShown }) =>
```

**Comment by ooflorent** [comment]
In my opinion, option 3 is the best because `component` is a real React component unlike option 2. Option 1 would be a pain to implement because `fields` would not be an array...

**Comment by erikras** [comment]
I think @ooflorent just nailed the argument against Option 2. That's why I went with Option 1 initially.

**Comment by epeli** [comment]
I agree. Just changed my vote from 2 to 3.

**Comment by MrEfrem** [comment]
I for the 2 option. Because fields is the required parameter which isn't transferred obviously to a component, and maxShow is just transferred obviously. Thus props it is logical to transfer everything by object the second parameter.

**Comment by q42jaap** [comment]
Option 3 it is! Nice change!
