### ISSUE TITLE
6.0.0-alpha.14 - syncErrors in reducer

### ISSUE THREAD

**Issue by babsonmatt** [erikras/redux-form#1064]
Would it make sense for consistency sake to keep syncErrors within the reducer, along with asyncErrors and submitErrors?  This would make it easy for people to create a selector to access errors on the form outside of the scope of each field.

**Comment by gustavohenke** [comment]
Happy new year, @babsonmatt! 😁 
Sorry for taking this long to reply!

Recent releases of redux-form v6 include `getFormSyncErrors` selector.
[Docs](http://redux-form.com/6.4.2/docs/api/Selectors.md/)
