### ISSUE TITLE
v6 Testing Philosophy

### ISSUE THREAD

**Issue by telaviv** [erikras/redux-form#1065]
I'm having some trouble unit testing code in v6 that I had no issues with in v5. There are some invariants that make working with redux in tests super awesome but v6 seems to break these invariants in kind of uncomfortable ways.  

1. You should be able to unit test a component by mounting a component and injecting props.
2. Subcomponents should not have a dependency on the implementation of their parents.
3. You shouldn't need to test the container to test the wrapped component.

In v5 I was able to test code simply by mounting my unwrapped component, inject `fields` + a fake `handleSubmit` and I can trivially unit test even the most complex logic.

As soon as I tried something similar in v6 I get this error:
`Error: Field must be inside a component decorated with reduxForm()`

I found that super odd because I've never worked with a sub-component that necessitated how I write my component. It meant that for the first time I was actually forced into integration testing the `reduxForm` container instead of unit testing my component. 

The only way I think I can test my code is by creating a store, wrapping the container in a provider, and even after then it's unclear how to test complex code like async validation.

I like a lot of the new v6 changes. I more just want to make devs aware of something that may be an unexpected regression of the design. That unless I'm missing something it seems that component unit testing is now impossible.

**Comment by erikras** [comment]
Perhaps you've figured this out because you closed the issue, but this is because the `Field` needs `context` information from the form.

**Comment by stevenmusumeche** [comment]
How was this solved?

**Comment by vforvikash** [comment]
Please tell us how you resolved this?

**Comment by bigfish** [comment]
I've been struggling with this for hours. I'm unable to test the rendering of fields. I've tried setting _reduxForm in the context of the form component (also declaring it in .childContextTypes of the form... but no joy.

**Comment by vaughnwalters** [comment]
any thoughts on how to resolve this? @telaviv   I am getting the same ```Error: Field must be inside a component decorated with reduxForm()

``` error

**Comment by vaughnwalters** [comment]
any thoughts on how to resolve this? @telaviv I am getting the same `Error: Field must be inside a component decorated with reduxForm()`

**Comment by maxevilmind** [comment]
Experiencing this issue while testing redux/react with jest and enzyme. Does anybody has a solution?
