### ISSUE TITLE
<select> field does not respect initialValues

### ISSUE THREAD

**Issue by arkwright** [erikras/redux-form#107]
I have a `<select>`:

```
<select name="amount">
  <option value=""></option>
  <option value="one">One</option>
  <option value="two">Two</option>
</select>
```

If I initialize the form with `initialValues={({})}` (empty object) select option `two`, and then call `resetForm()`, the `<select>` will continue to show `two`.

If I initialize the form with `initialValues={({ amount: '' })}`, the form will reset properly.

**Comment by erikras** [comment]
That seems reasonable. `'' !== undefined` You could always set the `<select>`'s value to `field.value || ''`.

**Comment by arkwright** [comment]
Works for other inputs, though.

Thanks for the workaround, I'll use that!

**Comment by arkwright** [comment]
Setting `select.value = undefined` in my console does indeed reset it. Perhaps there is a bug in redux-form?

**Comment by erikras** [comment]
What do you see for the state in redux-devtools? `resetForm()` should really revert to whatever you passed to `initializeForm()`.

**Comment by erikras** [comment]
There was a similar problem with `<textarea>`s. I think v3.0 has fixed this. [I recommend upgrading](https://github.com/erikras/redux-form/releases/tag/v3.0.0).
