### ISSUE TITLE
Idea: Component class as a prop instead of adapters

### ISSUE THREAD

**Issue by oreqizer** [erikras/redux-form#1073]
**Now (6.0.0-alpha.14):** put a string `component` name prop in a `Field`  and then attach an adapter

**Proposal:** put a component class in `component` prop without having to declare adapters and relying on a string

##### Current usage:
```javascript
<Field
    name="username"
    component="TextField"
    floatingLabelText="Username"
/>
```

and then:
```javascript
reduxForm({
    form: 'myForm',
    adapter,
})(Component);
```

##### Proposed usage:
```javascript
<Field
    name="username"
    component={TextField}
    floatingLabelText="Username"
/>
```

without other work. Then `Field` will pass all given props to the component, with `redux-form` ones attached as well.

Basically instead of mounting adapters, you'd just pass the wrapped component itself. In case of `redux-form-material-ui`, let's say you'd do the following:

```javascript
import { WrappedTextField } from 'redux-form-material-ui';

const MyForm = props =>
  <form onSubmit={props.handleSubmit}>
    <Field
      name="username"
      component={WrappedTextField}
      floatingLabelText="Username"
    />
  </form>;

export default reduxForm({
  form: 'myForm',
})(MyForm);
```

**Comment by ooflorent** [comment]
What you are proposing here is implemented since the first release of Redux Form 6. Adapters are just a convenient way for lib author to style a hole set of components.

**Comment by oreqizer** [comment]
Ohh I understand, I read the docs wrong - my bad. it's [here](http://redux-form.com/6.0.0-alpha.14/docs/api/Field.md/) at `component : Component | Function | String`.

**Comment by ooflorent** [comment]
I think your issue would better fit to `redux-form-material-ui` repository.
