### ISSUE TITLE
onSubmit function not initialised in SubmitFromParentContainer

### ISSUE THREAD

**Issue by fabarea** [erikras/redux-form#1075]
Taking the code as such from the [submit-from-parent](http://redux-form.com/5.2.5/#/examples/submit-from-parent?_k=7z0vnn), I get the following warning

```
Warning: Failed propType: Required prop `onSubmit` was 
not specified in `SubmitFromParentContainer` 
```

And submitting the form, triggers this error

```
Uncaught Error: You must either pass handleSubmit() 
an onSubmit function or pass onSubmit as a prop
```

This is because onSubmit was never defined when [passed](https://github.com/erikras/redux-form/blob/gh-pages/5.2.5/src/examples/SubmitFromParentContainer.js#L26) to the sub-component. What piece would be missing?

**Comment by gustavohenke** [comment]
It's been a while since the last comment here, so I'm closing this issue.
In case you're still tracking this issue, try with newer versions of redux-form and open a new issue!
