### ISSUE TITLE
v6 - Field values not binding to asynchronously loaded components

### ISSUE THREAD

**Issue by ericalli** [erikras/redux-form#1076]
Experiencing the same issue as #1034 when using [react-boilerplate](https://github.com/mxstbr/react-boilerplate/) or any other project I've tried that asynchronously loads components. 

The redux form initializes and change events fire (with the correct payload), but the value is not binded to the corresponding field.

Using redux-form v6.0.0-alpha.14

**Comment by chris-garrett** [comment]
I know it's been awhile but I was experience this issue and it turns out you need to use the immutable form as documented here: http://redux-form.com/6.2.0/examples/immutable/
