### ISSUE TITLE
Simple redux form not showing up, webpack and react NodeJS application

### ISSUE THREAD

**Issue by kevinmachstudio** [erikras/redux-form#1079]
I'm following the [Simple Redux Form example](http://redux-form.com/5.2.5/#/examples/simple?_k=c1itn4) and transferred the code to my client side file in my NodeJS application, in which I use webpack to compile it into a bundle.js file. However, no form shows up on the page (no error in the console and also when I look at the source code, I don't see any react or es6 related content). Am I missing a step here?

**Comment by ooflorent** [comment]
This is a usage question, and we encourage you to ask it on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

This is the only way to ensure the same question doesn’t get asked many times in a row, and that folks who have the same question in the future will be able to find it.

I’m closing for these reasons.
