### ISSUE TITLE
calling handleChange('fieldName', newValue) does not fire change event

### ISSUE THREAD

**Issue by bdefore** [erikras/redux-form#108]
According to the redux-form docs you can call `handleChange` passing in the field name and new value rather than have it be in an `onChange` event of the UI component sending a SyntheticEvent. But the action never fires if you call `this.props.handleChange('fieldName', newValue)`.

A workaround for now is to call `this.props.handleChange('fieldName', newValue)()`

This is on version 0.7.

**Comment by erikras** [comment]
Also true on v2.0.0.

**Comment by erikras** [comment]
Fixed in v2.2.4.
