### ISSUE TITLE
v6: FieldArray.push + immutable causes "TypeError: list.splice is not a function"

### ISSUE THREAD

**Issue by Pongetti** [erikras/redux-form#1082]
Hello all!  I've put some test code below.  Its fairly simple.  Just a button "Add Row" and a text box for each row in the FieldArray.

```js
import {Field, FieldArray, reduxForm} from "redux-form/immutable";

@reduxForm({
	form: "servicesForm"
})
export class TestingBedPage extends React.Component {
	render() {
		return (
			<div>
			<FieldArray
				name="services"
				component={fields =>
					<div>
						<button onClick={() => fields.push(Map({}))}>Add Row</button>
						{fields.map( row => {
							return <Field key={row} name={row + ".service_length"} component={field => <input type="text" {...field} />} />
						})}
					</div>
				}
			/>
			</div>
		)
	}
}
```

First I click Add Row once or twice to get some empty rows.  This works without issue.
I then focus on any of the input boxes.
I then click Add Row again but this time I get "TypeError: list.splice is not a function"

This doesn't occur if I switch to the non-immutable version of redux-form.

I'm using 6.0.0-alpha.13.  I didn't try with this exact code snippet with alpha 14 but in my real code I still had the same issue with 14 (I'm having some other issues with it so switched back to 13 for now)

Thanks!

**Comment by Palid** [comment]
The problem is this code in file `/lib/structure/immutable/index.js`:
```js
  splice: function splice() {
    var list = arguments.length <= 0 || arguments[0] === undefined ? (0, _immutable.List)() : arguments[0];
    var index = arguments[1];
    var removeNum = arguments[2];
    var value = arguments[3];
    return removeNum ? list.splice(index, removeNum) : list.splice(index, 0, value);
  }
```
It gets Map as the 'list', so instead of splicing it it just throws an error.

**Comment by erikras** [comment]
Thanks, @Palid. Yep. I wrote a test to recreate it. Somehow the touching of the fields is converting the `[]` into a `{}` (the immutable equivalents). It either needs to not do that or to turn `{}` into `[]` before doing the splice, like it does for `undefined`.

**Comment by Palid** [comment]
@erikras Temporarily you can just use Immutable.toList() if it's not a List. This will fix the problem, but may turn into a weird performance problem later.

**Comment by Palid** [comment]
I'm going to fork this and try to resolve the problem - it blocks me at my job. 
Bleeding edge much. ;)

**Comment by erikras** [comment]
My initial thought for a hack was to use `isList(list) || List()`, but I think it might be better to investigate what `BLUR` is doing.

The test I mentioned was extremely basic. Please make a minimal test in `reduxForm.spec.js` to replicate the steps @Pongetti said (or a shorter path if you know of one), and then fix it.

**Comment by Palid** [comment]
The serious fix may take a while, right now I'm taking quick&dirty approach. :)

**Comment by erikras** [comment]
Published fix in [`6.0.0-alpha-15`](https://github.com/erikras/redux-form/releases/tag/v6.0.0-alpha.15).

**Comment by Palid** [comment]
@erikras looks like you were a lot faster than me, had some stuff to do and it would still be untouched for a week. Sorry about that.

**Comment by Pongetti** [comment]
Thanks for the hard work guys!  Not to be annoying but the error is still occurring when you try to remove a field. 

Code is below.  Its the same but compatible with alpha-15 and an added button that removes the last row.

```

import {Field, FieldArray, reduxForm} from "redux-form/immutable";

@reduxForm({
    form: "servicesForm"
})
export class TestingBedPage extends React.Component {
    render() {
        return (
            <div>
            <FieldArray
                name="services"
                component={({fields}) =>
                    <div>
                        <button onClick={() => fields.push(Map({}))}>Add Row</button>
						<button onClick={() => fields.remove(fields.length-1)}>Remove Row</button>
                        {fields.map( row => {
                            return <Field key={row} name={row + ".service_length"} component={field => <input type="text" {...field} />} />
                        })}
                    </div>
                }
            />
            </div>
        )
    }
}
```

**Comment by pzmudzinski** [comment]
Any news on that?
