### ISSUE TITLE
Form Not Clearing via Reducer Plugin (Regression in v5.2.5)

### ISSUE THREAD

**Issue by minznerjosh** [erikras/redux-form#1083]
Since `v5.2.5`, clearing the form with method "A" on [this page](http://redux-form.com/5.2.5/#/faq/how-to-clear?_k=i2bey7) no longer works.

I have made a JSFiddle that demonstrates the issue:

https://jsfiddle.net/minznerjosh/aLc0uvxw/6/

If you like, I could look at fixing the issue myself and send a PR. I could get it done sometime tomorrow.

P.S. Thanks for all your work on redux-form! I've been using it quite extensively for a new app I've been building and it's been great overall!

**Comment by danielrob** [comment]
@minznerjosh would you be willing to update us on the status of this ticket?

**Comment by minznerjosh** [comment]
@danielrob I'm afraid I'm now using v6+ so I'm not sure what the status of this is.

**Comment by danielrob** [comment]
Thanks for the update! v5 is on sort of PRs accepted support level now so I'll go ahead and close this :).
