### ISSUE TITLE
[v5] handleSubmit submits only fields specified in that particular component instance

### ISSUE THREAD

**Issue by jayphelps** [erikras/redux-form#1086]
If you have multiple components that are using the same form name, I personally expected that all fields in that form (by name) would be included in the `onSubmit` invoked by `handleSubmit`. Instead, only the fields you specified in your decorator for that particular component instance will be submitted.

Interesting enough, in creating the JSBin I also discovered that the `onSubmit` you provide is per component as well, where instead I expected that providing another `onSubmit` would override the previous; that is, a single form would seemingly only want a single submit handler?

JSBin: http://jsbin.com/jajuna/edit?js,output

```js
const NameField = reduxForm({
  form: 'example-form',
  fields: ['name'],
  initialValues: {
    name: 'Bilbo Baggins'
  },
  onSubmit(values, done) {
    console.log('inner values', values);
    // inner values Object {name: "Bilbo Baggins"}
  }
})(
  ({ fields: { name }, handleSubmit }) =>
    <div>
      <div>
        Name: <input {...name} />
      </div>
      <button onClick={handleSubmit}>inner submit</button>
    </div>
);

const Form = reduxForm({
  form: 'example-form',
  fields: [],
  // fields: ['name'],
  onSubmit(values, done) {
    console.log('outer values', values);
    // outer values Object {}
  }
})(
  ({ handleSubmit }) =>
    <form onSubmit={handleSubmit}>
      <NameField />
      <button type="submit">outer submit</button>
    </form>
);
```

This pattern of decorating multiple components with `@reduxForm` with the same form name is useful for extremely complex forms (like I have) where you would otherwise have to pass the fields down many levels and all over the place, and have a single point for `initialValues`. Instead, I can split them up and not need to know "how they work" or need a full schema upfront, that might otherwise be tough to know.

**Comment by clayne11** [comment]
This is completely solved in `v6`.

**Comment by jayphelps** [comment]
@clayne11 Good to know! Though as it is still in alpha we cannot commit to using it at this point.

**Comment by ooflorent** [comment]
@jayphelps It won't be addressed in v5 unless it could be implemented without breaking changes (and I really doubt about the feasibility). However, v6 is pretty stable and the API is almost finalized (see https://github.com/erikras/redux-form/issues/1099#issuecomment-223830548).
