### ISSUE TITLE
V6 field arrays, change array elements outside function render()

### ISSUE THREAD

**Issue by mauvew** [erikras/redux-form#1087]
In V5, we can simply update the elements of an array field, as fields is a prop. Like the docs demos:

```js
for (let childIndex = 0; childIndex < 30; childIndex++) {
  addValue('deep', 'children')
  for (let awardIndex = 0; awardIndex < 10; awardIndex++) {
    addValue('deep', `children[${childIndex}].awards`)
  }
}
```
This can also be put in a out function instead of `render()`

in V6, we can update the elements of field arrays within `<FieldArray>`, just wondering that is it possible to provide an option to update elements outside `render()`? As this seems quite basic and can bring lots of flexibility.

**Comment by clayne11** [comment]
You can do this using a redux action. See http://redux-form.com/6.0.0-alpha.15/docs/api/ActionCreators.md/

**Comment by ooflorent** [comment]
You must use action creators to do this.
