### ISSUE TITLE
[v5] addField on nested fields doesn't work at leaf of `first[].second.third[]`

### ISSUE THREAD

**Issue by jayphelps** [erikras/redux-form#1090]
Similar to #630, but with a different property path structure.

`first[].second.third[].addField({ forth: "DOESNT WORK" })`

While most nested structures work, for whatever reason this particular order of them does not. Just like #630, the `fields` array in the `ADD_ARRAY_VALUE` action is empty.

JSBin: http://jsbin.com/wodoxe/edit?js,output
```js
const Form = reduxForm({
  form: 'example-form',
  fields: [
    'first[].second.third[].forth'
  ],
  initialValues: {
    first: [{
      second: {
        third: []
      }
    }]
  }
})(
  ({ fields: { first }, values }) =>
    <div>
      <pre>{JSON.stringify(values)}</pre>
      <button
        onClick={() => first[0].second.third.addField({ forth: 'DOESNT WORK' })}
      >
        Add
      </button>
    </div>
);
```

No errors.

**Comment by erikras** [comment]
Published in [`v5.3.0`](https://github.com/erikras/redux-form/releases/tag/v5.3.0).
