### ISSUE TITLE
Focus on the form field after submit

### ISSUE THREAD

**Issue by Nishant-Pathak** [erikras/redux-form#1092]
Hi @erikras ,

Thank you for providing the awesome library which reduce the development effort and reduces the boiler plate a lot.

I have a use case in which I display 3 different form in tab views. On each tab I want to focus on the first field.

```javascript
  componentDidMount = () => {
    this.refs.firstField.focus()
  }

```

but this only focus the form field in first time and first form only. If I move across tabs, it is not focusing again, I can understand that componentDidMount fires once only.
Is there a way to do that.

Other this is after submit I have to clear the form and again focus on the firstField. Focus is not working there too. Issue is mentioned here: http://stackoverflow.com/questions/37576673/focus-on-the-form-field-after-submit

**Comment by erikras** [comment]
I answered the question on SO, but the "when I switch tabs" use case is different. It depends on how you are doing the tab switching, so I'd need to see that code.

If you're doing it like the [Wizard Example](http://redux-form.com/5.2.5/#/examples/wizard), where the component is only rendered by its component when it is visible, then `componentDidMount()` should work for each individual tab. But if you are using CSS or something to show and hide the tabs, then they will all have been mounted already, and you'll have to use some sort of javascript call, like

```js
this.refs.tab1.focusFirstInput()
```

...and then create a `focusFirstInput()` method on each of your tab components.

**Comment by pathakNishant** [comment]
Am using https://getmdl.io/components/index.html#layout-section/tabs to render the tabs. It renders all 3 tabs together.

**Comment by Nishant-Pathak** [comment]
Am using https://getmdl.io/components/index.html#layout-section/tabs to render the tabs. It renders all 3 tabs together.

**Comment by ooflorent** [comment]
I'm closing the issue because it is a usage question not directly related to Redux Form.
However, feel free to continue the discussion.
