### ISSUE TITLE
handleSubmit does not call the callback

### ISSUE THREAD

**Issue by alangumer** [erikras/redux-form#1096]
I have a simple form with input file, I want to call submit in `onChange` event but nothing happen, i used the solution in #330 but in this case not works (`this.props.handleSubmit(submit)` is not called), here is the code:

```js
<input type="file" multiple {...files} value={null} onChange={event => {
  this.props.fields.files.onChange(event);
  console.log( 'event' );
  setTimeout(() => { // wait for ?change to make it to redux state
    console.log( 'setTimeout' );
    this.props.handleSubmit(submit); // not called submit function
  });
}}/>
```

**Comment by ooflorent** [comment]
It looks like a bug. I've created a [JSBin](http://jsbin.com/ciyiquyoki/1/edit?js,console,output) to reproduce it. Adding `onSubmit` on `<Form />` seems to fix the issue.

**Comment by alangumer** [comment]
thank you @ooflorent for the JSBin, I play with it and still doest not call the callback

**Comment by alangumer** [comment]
the problem was that <FileForm/> should define onSubmit={this.handleSubmit} so:
`<FileForm onSubmit={this.handleSubmit}/>` and of course make sure you have defined that function handleSubmit = (data) => { ... and then the code below works :)

```js
<input type="file" multiple {...files} value={null} onChange={event => {
  this.props.fields.files.onChange(event);
  setTimeout(() => { 
    this.props.handleSubmit();
  });
}}/>
```

**Comment by kamilio** [comment]
We stumbled upon this issue/feature and it caused us slight confusion, just to clarify

`handeSubmit` called with `event` as argument is called immediately. However when called with function, it returns function (thunk) that still needs to be called. Below you can find two use cases.

```jsx
// will be called with event as argument
 <Footer
          onConfirm={ handleSubmit } /> 

// behaviour can be enhanced
 <Footer
          onConfirm={ handleSubmit(onConfirm) } />
```
