### ISSUE TITLE
How to reset the form after async call

### ISSUE THREAD

**Issue by cjroebuck** [erikras/redux-form#11]
Say I have a login form that submits credentials to my api server. I don't want to call `this.reset()` in the components submit handler because I'm not sure yet whether the user logged in successfully. 

So my form component listens on something like auth.isLoggedIn from global state and in `componentWillReceiveProps` I check the value of this prop. If `nextProps.isLoggedIn` is true, I redirect and now I want to reset the form. The trouble is, resetting the form within `componentWillReceiveProps` leads to an infinite loop. So the question I have is where is the best place to call `reset` without getting into this issue?!

Thanks!

**Comment by Gazler** [comment]
I'm not sure if this is the suggested way to do it or not. I did something like:

        dispatch({
          type: types.CREATE_POST_SUCCESS,
          post: res.body
        });
        dispatch({
          type: "REDUX_FORM_RESET"
          form: "newPostForm"
        });

**Comment by erikras** [comment]
The actions are exported now.

```javascript
import {reset} from 'redux-form';
...
dispatch(reset('myForm'));
```

**Comment by tnguyen14** [comment]
In the reducer, how would the `resetForm` method be called?

**Comment by tnguyen14** [comment]
Oh, I just realized that just dispatching the `reset` action is sufficient, I don't have to call `resetForm` manually.

**Comment by erikajon** [comment]
I'm dispatching `reset('myForm')`, which successfully resets all of the text input fields but not the `files` input field. Do I need to do something in particular to reset that?

**Comment by abdalla** [comment]
the textarea component is not cleaning using dispatch(reset('myform')) :(
