### ISSUE TITLE
[v6] array selector

### ISSUE THREAD

**Issue by shulcsm** [erikras/redux-form#1106]
Add a way to select collection from FieldArray perhaps `array[].child` or `array[*].child`. Meanwhile is there a way to get values in get values in render of FieldArray without selector?

**Comment by clayne11** [comment]
What do you mean by "select collection"? What are you trying to select? You can get the value of a `FieldArray` using a `formValueSelector`. What are you trying to accomplish?

**Comment by shulcsm** [comment]
Yes, i'm talking about formValueSelector. It supports "deep" paths, but it doesn't really work if you have FieldArray in your path. I does if you want to get concrete position `field.fieldarray[0].field`, but it's impossible to "pluck" each child with something like this `field.fieldarray[].field`.
`{
    field: {
        fieldarray:[
            {
                field: "A"
            },
            {
                field: "B"
            }
        ]
    }
}` I want "A", "B", for arbitrary length of fieldarray.

**Comment by ooflorent** [comment]
Currently `formValueSelector` does not work on arrays:

```js
const selector = formValueSelector('myForm')
const state = {
  form: {
    myForm: {
      values: {
        mice: ['Jaq', 'Gus', 'Major', 'Bruno']
      }
    }
  }
}

// This test fails :-(
expect(selector(state, 'mice'))
  .toEqual({
    mice: ['Jaq', 'Gus', 'Major', 'Bruno']
  })
```

Fixing this would solve the issue without having to implement masks because you could do:

```js
selector('mice').map(_.property('some.field'))
```

I would be really happy to accept a PR that implements this! What do you think about this @erikras?

**Comment by erikras** [comment]
I'm confused. ☝️ That test passes.

**Comment by ooflorent** [comment]
I will investigate on _why_ it hasn't work the first time.

**Comment by shulcsm** [comment]
Ok, from what i understand you are going to fix array issue but if i want to traverse arrays i'm on my own?

**Comment by ooflorent** [comment]
```js
// Create a selector for `myform`
const selector = formValueSelector("myform")

// Create an accessor for `child` sub field
const getChild = _.property("child")

// Connect the component
connect(
  // Select `array` field and extract `child`
  // It mimics `array[].child`
  state => selector(state, "array").map(getChild)
)
```

**Comment by shulcsm** [comment]
Thanks. Great work on v6.
