### ISSUE TITLE
unit testing ?

### ISSUE THREAD

**Issue by samidarko** [erikras/redux-form#111]
I would like to test my login form as followed but **loginForm** is the decorated element so **loginForm.refs** is undefined. Should I export the form 2 times (decorated and undecorated), test the undecorated one (suggested [here](https://rackt.github.io/redux/docs/recipes/WritingTests.html) in the *Connected Components* part) with the required mocked up properties or is there another way? Thank you

```javascript
describe('login form ', function () {
    it('should validate', function () {
        const createFakeStore = fakeData => ({
            getState() {
                return fakeData;
            },
            subscribe(fn) {
            },
            dispatch() {
            }
        });

        let data = {auth: {tokenExpiry: parseInt(moment().add(1, 'days').toDate().getTime()/1000), isFetching: false}};
        var handleSubmit = jasmine.createSpy();
        var loginForm = TestUtils.renderIntoDocument(
            <LoginForm onSubmit={handleSubmit} store={createFakeStore(data)} />);
        var form = TestUtils.findRenderedDOMComponentWithTag(loginForm, 'form');
        loginForm.refs.username.getDOMNode().value = 'username';
        loginForm.refs.password.getDOMNode().value = 'password';
        TestUtils.Simulate.submit(form);
        expect(handleSubmit).toHaveBeenCalledWith({username: 'username', password: 'password'});
    });
});
```

**Comment by erikras** [comment]
I'm sorry, but I am woefully inept at React component testing. But yes, I would definitely test the undecorated form (one of the benefits of redux-form, and react-redux, in general, is that your decorated component can be relatively dumb, and therefore more easily testable), and maybe test the decorated version as well, although it's more unclear to me how that would work.

**Comment by johanneslumpe** [comment]
@samidarko @erikras I feel that it would make sense to declare form component as pure functions (as of react 0.14) and then wrap them inside of container component which gets decorated.

This has two benefits:

1) We can be sure that the form component is really 'dumb'
2) We do not have any issues getting to the form component in our unit tests (we do not have to add another export etc.)

The test for the actual component would then only have to pass in a mocked set of fields (which can be easily done with a helper function) and other used props and only has to test that functions are being called properly. This leaves `redux-form` completely out of the mix.

Technically you wouldn't have to test the decorated component very much, because we should assume that `redux-form` works properly. So the container could be tested in terms of whether it passes the correct props to the dumb component and whether it called the proper actions when the form is submitted in a valid state.

Thoughts?

**Comment by samidarko** [comment]
Thanks @erikras for your answer. Finally I will do as recommended in the redux doc, export the [class](https://github.com/GephenSG/react-redux-es6/blob/master/src/js/components/LoginForm.js#L15) and the module and test the [class](https://github.com/GephenSG/react-redux-es6/blob/master/test/specs/components/loginForm_test.js#L2)

But I suppose I should mock up the properties added by connectReduxForm ?

**Comment by erikras** [comment]
Yes, mock up those properties. Re-open if you have any more questions.

**Comment by yugal2** [comment]
Hi @samidarko , 

Can you provide the way you mocked up the connectReduxForm properties for unit testing?

Thanks.

**Comment by samidarko** [comment]
Hi @yugal2 ,

Finally I never did it but I could explain you how I would have done.

Lets say you have a component Form.js, and usually redux-form is wrapping it like following:

```javascript
Form = reduxForm({
    form: 'myForm',
    fields: ['username'],
    validate: validate
})(Form);

export default Form;
```

I would also export my component class and not test the default export.

```javascript
export class Form extends React.Component {
...
```

and I would import the form without the redux-form wrapping as redux-form is already tested and we assume the configuration is done correctly, if not it will be detected soon enough and patched.

In my test, I import:

```javascript
import { Form } from '../path/to/Form';
```

and NOT 

```javascript
import Form from '../path/to/Form';
```

Then from here I would mock up the following props I pass to the component :
```javascript
const {fields: {username}} = this.props;
```

(not sure of the exact code, I'm just making up everything)

using Jasmine:
```javascript
describe('hopefully', function () {
    it('should work', function () {
        let props = {
            fields: {username: {value: 'something', onChange: jasmine.createSpy('onChange')}
        };
        let renderer = TestUtils.createRenderer();
        renderer.render(<Form {...props} />);
        let output = renderer.getRenderOutput();
        ... the test
    });
});
```
 
I think this is the idea. We could ask @erikras confirmation. I'm not sure of the props you need to mock up (onBlur, ...) but you can look at  the API documentation.

Hope it helps :)

**Comment by erikras** [comment]
On #911, @andrewmclagan said he will be writing up some docs on `redux-form` unit testing. I have not done much testing of _usages_ of the library, so I look forward to seeing what he comes up with.

**Comment by andrewmclagan** [comment]
yes that is forth-coming.

**Comment by bpmckee** [comment]
How can we get valid outputs from `getValues()` by passing an object.  No matter what I pass returns {} as the result.

I have a couple use cases where this is necessary.  For example, I need to make sure a submit button is not disabled with a valid form.  The disabled property relies on my validator which is tested separately.  However, the result from getValues is what is passed to the validator and if it's always {} then I can't really test anything.

**Comment by tylercollier** [comment]
I've been waiting on unit test examples and documentation too, and when I figured out a few techniques, I wanted to write about them and share. Hopefully andrewmclagan's docs are better, but in the meantime I created a project to show off both unit testing with forms and integration tests with redux-form.

The project is at https://github.com/tylercollier/redux-form-test.

**Comment by tylercollier** [comment]
@bpmckee Here's what I tried in my integration test that worked fine: `getValues(store.getState())`. If I log that to the console, it outputs the following as expected with my simple test that sets the value of the first name field:

```
{ form: { contact: { firstName: 'Joe' } } }
```

If that doesn't get you what you need, please put your question on stackoverflow.
