### ISSUE TITLE
Invariant Violation: v6.0.0-alpha.13 input is a void element tag and must not have `children`

### ISSUE THREAD

**Issue by dtothefp** [erikras/redux-form#1110]
I'm sure I'm doing something stupidly simple wrong but getting this error using the simple example in the v6 docs http://redux-form.com/6.0.0-alpha.13/docs/GettingStarted.md/

```
invariant.js:45Uncaught Invariant Violation: input is a void element tag and must not have `children` or use `props.dangerouslySetInnerHTML`. Check the render method of bound createElement.
```

Example branch here: https://github.com/dtothefp/redux-form-example/blob/v6/src/js/components/contact-form.js

Changing the example to just String `input` works 😄 
```jsx
<form onSubmit={handleSubmit(this.handleSubmit)}>
  <div>
    <label>First Name</label>
    <Field name="firstName" component="input" type="text"/>
  </div>
  <div>
    <label>Last Name</label>
    <Field name="lastName" component="input" type="text"/>
  </div>
  <div>
    <label>Email</label>
    <Field name="email" component="input" type="email"/>
  </div>
  <button type="submit">Submit</button>
</form>
```

**Comment by erikras** [comment]
Try switching to `component="input"` instead of `component={React.DOM.input}`.

**Comment by dtothefp** [comment]
haaa..@erikras I just tried this before your comment and it works 😄

**Comment by qnm** [comment]
@erikras Is this a general case to use `"input"` over `React.DOM.input` ?

I ask because the documentation still references `React.DOM.input` - I'll submit a PR to fix the docs if this should be changed.

**Comment by erikras** [comment]
@qnm Yes. The docs have been updated, but not yet published. They will be with the next release.

**Comment by qnm** [comment]
Good to know, thanks Erik.

On 20 June 2016 21:48:09 GMT+10:00, Erik Rasmussen <notifications@github.com> wrote:
>@qnm Yes. The docs have been updated, but not yet published. They will
>be with the next release.
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/erikras/redux-form/issues/1110#issuecomment-227120852

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
