### ISSUE TITLE
[v6] Get field.value using selector

### ISSUE THREAD

**Issue by olegkalyta** [erikras/redux-form#1111]
I use redux-form to render complex object `items=[item]`:

``` js
item: {
  name, 
  type,
  value
}
```

Then, to get it's value after editing i use selector

``` js
const selector = formValueSelector('actionModal')
const action = Object.assign({}, selector(state, 'items'))
```

In result variable i see `type, name` field but there is not `value`.

What is best way to get it?

**Comment by gustavohenke** [comment]
It's been a while since the last comment here, so I'm closing this issue.
In case you're still tracking this issue, try with newer versions of redux-form and open a new issue!
