### ISSUE TITLE
cannot import Field

### ISSUE THREAD

**Issue by mayacode** [erikras/redux-form#1118]
Hello

I just started to use redux-form, I switched from react-redux-form. And stuck in very beginning. I would like to use redux-form together with material-ui components, so I have line like this:
`import { Field, reduxForm } from 'redux-form';`

but `Field` is undefined, so I get react error, that component cannot be undefined...

"redux-form": "^5.2.5"

**Comment by erikras** [comment]
`Field` was introduced in `v6`. Try
```js
"redux-form": "6.0.0-alpha.15"
```
