### ISSUE TITLE
V6.0.0-alpha.15 - unnecessary rerender problem

### ISSUE THREAD

**Issue by Darmody** [erikras/redux-form#1119]
https://github.com/erikras/redux-form/blob/v6.0.0-alpha.15/src/Field.js#L72

For alpha 15 props are passded through `props`. As `props` is an object, it may cause unnecessary rerender.

For instance:

```jsx
<Field
  props={{ type: 'time' }}
  component={SendAtField}
  name="sendAt"
/>
```

Because `{ type: 'time' }` always is a new object, shallowEquals check will never be true.

It has to change to:

```jsx
// outside the component, define a global variable
const props = { type: 'time' }

...

<Field
  props={props}
  component={SendAtField}
  name="sendAt"
/>
```

**Comment by ooflorent** [comment]
> For alpha 15 props are passed through `props`.

This is wrong. `props` is just a workaround for TypeScript users where `Field` does not support polymorphic properties. The _old_ way is the recommended one:

```js
<Field
  type='time'
  component={SendAtField}
  name="sendAt"
/>
```

However, I'm working on a patch to improve this.

**Comment by erikras** [comment]
@Darmody, this is an excellent point, and I would have agreed with you, but the test I just added does _not_ rerender when the form rerenders, and the `props` object is recreated.

I also improved the docs about `props`.

**Comment by Darmody** [comment]
@ooflorent Sorry for misunderstanding that!

@erikras yep, I found that too.Maybe it will be a potential problem.
