### ISSUE TITLE
v6: option to pass fields to FieldArray outside of using initialValues

### ISSUE THREAD

**Issue by babsonmatt** [erikras/redux-form#1123]
I'm not entirely sure if I'm missing something here... but my use case / issue is the following:

I have a list of users and I render a FieldArray which renders a row per user.  If I delete a user... I have to call remove(index) to keep the FieldArray up to date with the actual count of users from state.  This seems problematic since users could potentially be deleted from a reducer via other means outside of this form (for example) and my form would continue to render a row for the missing user.

Does it make sense to just pass FieldArray an array of the 'fields' I wanted a field created for?  Apologies if I'm missing something here.

Thanks!

**Comment by erikras** [comment]
I'm not sure if I'm understanding you correctly, but you can teach `redux-form` to listen to external actions via the [`reducer.plugin()` API](http://redux-form.com/6.0.0-alpha.15/docs/api/ReducerPlugin.md/), so if you are worried about a user being removed elsewhere in your webapp, you could potentially have your form reducer listen to whatever `REMOVE_USER` action was dispatched.

**Comment by ooflorent** [comment]
I'm closing the issue since @erikras gave a good answer! Feel free to continue the discussion if you have other questions.

**Comment by babsonmatt** [comment]
@erikras thanks for the info
