### ISSUE TITLE
[v6] hasError only allows strings?

### ISSUE THREAD

**Issue by tacomanator** [erikras/redux-form#1125]
Is there a reason validation errors can only be strings? 

```JavaScript
// from hasError.js
if (syncError && typeof syncError === 'string') {
  return true
}
```

I have a validator that can return multiple errors. I would like to format them into a `ul` list and return a React element from the validate function. Showing the error works now, but the field isn't considered to have an error because the error isn't a string. Can we allow objects and arrays, or at least arrays (the element can be created on the form)?

For your reference I'm applying this to a password field which gets errors from [owasp-password-strength-test](https://www.npmjs.com/package/owasp-password-strength-test).

**Comment by ooflorent** [comment]
@erikras This is problematic. Our apps always define errors as objects (React Intl message descriptors)

I tried to fix this but it doesn't work with Immutable.js:

```diff
diff --git a/src/hasError.js b/src/hasError.js
index e1687b6..bd6550b 100644
--- a/src/hasError.js
+++ b/src/hasError.js
@@ -1,5 +1,10 @@
 import plainGetIn from './structure/plain/getIn'
 
+const isError = (error) => {
+  return error !== '' && typeof error === 'string'
+    || error !== null && typeof error === 'object'
+}
+
 const getErrorKey = (name, type) => {
   switch (type) {
     case 'Field':
@@ -18,15 +23,15 @@ const createHasError = ({ getIn }) => {
     }
     const errorKey = getErrorKey(name, type)
     const syncError = plainGetIn(syncErrors, errorKey)
-    if (syncError && typeof syncError === 'string') {
+    if (isError(syncError)) {
       return true
     }
     const asyncError = getIn(asyncErrors, errorKey)
-    if (asyncError && typeof asyncError === 'string') {
+    if (isError(asyncError)) {
       return true
     }
     const submitError = getIn(submitErrors, errorKey)
-    if (submitError && typeof submitError === 'string') {
+    if (isError(submitError)) {
       return true
     }
```

The broken test:

```js
it('should return true for objects', () => {
  const field = fromJS({ name: 'foo', type: 'Field' })
  expect(hasError(field, fromJS({
    foo: { id: "some.key" }
  }))).toBe(true)
})
```

```
  1) hasError.immutable should return true for objects:
     Error: Expected false to be true
      at assert (node_modules/expect/lib/assert.js:29:9)
      at Expectation.toBe (node_modules/expect/lib/Expectation.js:70:28)
      at Context.<anonymous> (hasError.spec.js:34:12)
```

**Comment by cayuu** [comment]
Yas! 

Would allow all kinds of fun. `redux-form` already passes whatever you declare as the error through cleanly (Arrays, objects, even React Elements) - https://jsfiddle.net/e8sd61ea/4/

This all works, apart from you know, the validity flag setting correctly 😭

**Comment by eliseumds** [comment]
Any update on this issue? We're also using `<FormattedMessage>` here :S

**Comment by erikras** [comment]
Thanks for the reminder, @eliseumds. I'll try to prioritize this before release.

**Comment by erikras** [comment]
I'm pretty sure that this was inadvertently fixed with the addition of [Selectors](http://redux-form.com/6.0.0-rc.4/docs/api/Selectors.md/) in `v6.0.0-RC.4`.

Can someone please confirm?

**Comment by eliseumds** [comment]
@erikras just tested and `rc.4` was indeed broken. I guess it was fixed by https://github.com/erikras/redux-form/commit/3393ab3365eedad810daac0f5ec8544087089f5f

**Comment by tacomanator** [comment]
Tested in rc5 and appears to be working for my scenario.
