### ISSUE TITLE
[V6] Avoiding closures for remove operations in FieldArrays

### ISSUE THREAD

**Issue by pulse00** [erikras/redux-form#1128]
As since [alpha-14](https://github.com/erikras/redux-form/releases/tag/v6.0.0-alpha.14) it's highly discouraged to use closures inside an `FieldArray`, i'm wondering if it also applies to things like `remove` callbacks (where an inner element needs a reference to the `fields` object for calling the `remove` method with the current index).

Example from the [docs](http://redux-form.com/6.0.0-alpha.15/examples/fieldArrays/):

```jsx
const renderMembers = ({ fields }) => (
  <ul>
    <li>
      <button type="button" onClick={() => fields.push({})}>Add Member</button>
    </li>
    {fields.map((member, index) =>
      <li key={index}>
        <button
          type="button"
          title="Remove Member"
          onClick={() => fields.remove(index)}/>
        <h4>Member #{index + 1}</h4>
      </li>
    )}
  </ul>
)
```

I'm referring to the 2 `onClick` callbacks here. Is this also a performance problem? If yes: How would one move that closure in the outer scope, as it clearly needs a reference to the `fields` object?

**Comment by ooflorent** [comment]
You could use [`withHandlers`](https://github.com/acdlite/recompose/blob/master/docs/API.md#withhandlers) from [recompose](https://github.com/acdlite/recompose). First you need to declare how to render a hobby:

```js
const Hobby = withHandlers({
  handleRemove: props => () => props.onRemove(props.index)
})(
  ({ handleRemove }) => (
    <li>
      <button
        type="button"
        title="Remove Hobby"
        onClick={props.handleRemove}/>
      <Field
        name={props.hobby}
        type="text"
        component={renderField}
        placeholder={`Hobby #${props.index + 1}`}/>
    </li>
  )
)
```

Then you update the field loop:

```js
fields.map((hobby, index) =>
  <Hobby key={index} index={index} hobby={hobby} onRemove={fields.remove} />
)
```

**Comment by pulse00** [comment]
> you could use withHandlers from recompose.

great, thanks !

**Comment by erikras** [comment]
> you could use withHandlers from recompose.

Wow, that's a great pattern. Perhaps we need a `GoodPractices.md` for stuff like that.
