### ISSUE TITLE
Validation and "handleSubmit"

### ISSUE THREAD

**Issue by mschipperheyn** [erikras/redux-form#113]
I had a hard typing getting my head around async validation and handleSubmit (they seemed the same to me) because I didn't realize that handleSubmit was actually: handle a successful submission. The term handleSubmit suggests to me that this function will be called on clicking submit. Also, as I understand it, it will only be called after both synchronous and asynchronous validation pass. 

I realize that the "if and only if" part makes this clear, but it's easy to miss. I suggest a minor textual correction:
handleSubmit will call the function passed into ContactForm's onSubmit prop, if and only if the synchronous validation passes.
=>
handleSubmit will call the function passed into ContactForm's onSubmit prop, after validation (both synchronous and asynchronous) completes successfully.

**Comment by erikras** [comment]
Thanks. :+1: That is clearer.
