### ISSUE TITLE
[v5] "overwriteOnInitialValuesChange: false" still resets fields' "touched" property, thus hiding error messages

### ISSUE THREAD

**Issue by yched** [erikras/redux-form#1130]
Using 5.2.5, "overwriteOnInitialValuesChange: false" does preserve user input on fields when initialValues change (with the restriction/bug pointed in #1112)

However, redux-form/INITIALIZE action that is dispatched when initialValues change still resets the  'touched' property of each field.

According to http://redux-form.com/5.2.5/#/examples/synchronous-validation, the common recommended practice for displaying form validation errors relies on myField.touched (`{myField.touched && myField.error && <div>{myField.error}</div>}`).

So this means that even with "overwriteOnInitialValuesChange: false", when the initialValues change, the current user input are preserved, but the errors that were possibly being displayed suddenly go out of sight ?

**Comment by yched** [comment]
Maybe "do not overwrite the form when the initialValues prop changes" should also mean that the set of fields that are considered as "touched" are not reset either ?

**Comment by danielrob** [comment]
Closing with bulk close of v5 issues. If this issue still requires action and/or also affects v6/7, please request a reopen with details or raise a new issue. v5 PR's are still welcomed.
