### ISSUE TITLE
Remove onBlur validations

### ISSUE THREAD

**Issue by DWboutin** [erikras/redux-form#1131]
Hi!

Is there a way to set to off onBlur validations?

Thank you

**Comment by mihirsoni** [comment]
@DWboutin If you're validating field then what is issue in validating onBlur ?

**Comment by DWboutin** [comment]
They just don't want onBlur validations... I explained them that onBlur validations are really greats, but they don't want it.

**Comment by ooflorent** [comment]
Actually validation occurs on `change`. Instead of changing how Redux Form runs the validation, why don't control when the error is displayed? Set `touchOnChange` and `touchOnBlur` to `false`. Then only the submission will mark them as `touched`.

**Comment by DWboutin** [comment]
Thank you very much!
