### ISSUE TITLE
[v6] Accessing errors

### ISSUE THREAD

**Issue by shulcsm** [erikras/redux-form#1134]
From what i understand errors are not part of the store. Is there a way to "bubble" errors or inject all errors into form prop?

``` js
// hasErrors = field1.invalid || field2.invalid;
const SomeFieldset = ({ hasErrors }) => (
  <fieldset className={classNames({'error': hasErrors})}>
    <Field name="field1" component="input" type="text" />
    <Field name="field2" component="input" type="text"/>
  </fieldset>
);
```

I thought i could work around it by setting some state in `validate()` but it's not possible since it's called in `render()`

**Comment by babsonmatt** [comment]
Similar question, how would one go about showing errors for radio buttons? As it is now it appears each radio would have the error displayed next to it - is there a way to get errors to a "group" level above the radios themselves?  Apologies if I'm missing something here.

**Comment by alurim** [comment]
@babsonmatt what we've done to solve the issue of radio buttons is create a `RadioButtoGroup` component that is used as a component for `Field`. Something like this:

```
const RadioButtonGroup = ({
	children,
	value,
	display,
	touched,
	invalid,
	error,
	...otherProps,
}) => {
	return (
		<div>
			<div>
				{
					Children.toArray(children)
						.filter(c => !!c)
						.map(child => cloneElement(child, {
							...otherProps,
							checked: child.props.value === value,
						})
					)
				}
			</div>
			<div>
				{
					touched ? error : null
				}
			</div>
		</div>
	)
}
```

**Comment by gustavohenke** [comment]
Regarding the original issue:
Starting with v6.2.0, `getFormSyncErrors` and `getFormSubmitErrors` selectors got added.

Regarding the problem with checkboxes/radios validation: please try, in your validator function, set an error for the name of the `<FieldArray>`.
[The docs](http://redux-form.com/6.4.1/docs/api/FieldArray.md/) contain some interesting ideas on how to do this.
