### ISSUE TITLE
Values not passed as props to the decorated component.

### ISSUE THREAD

**Issue by larsbs** [erikras/redux-form#1135]
According to the documentation, the decorated component should receive values as a prop, but the prop is not being passed down to the decorated component, it's only on the final component. I mean:

`Form(Decorated)` has `values` as a prop, but `Decorated` doesn't receive that prop. Is this the intended behavior or is something failing here?

**Comment by ooflorent** [comment]
`values` is a special property and cannot be overridden.
Other non-Redux Form props should be valid:

```js
<MyDecoratedForm foo="bar">
                 ^^^^^^^^^
              pass down `foo`
```

Inside `MyDecoratedForm`:

```js
<div>{this.props.foo}</div>
      ^^^^^^^^^^^^^^
       display `bar`
