### ISSUE TITLE
[v6] How can I dispatch 'inialiaze' in a right way?

### ISSUE THREAD

**Issue by olegkalyta** [erikras/redux-form#1137]
I need to give my form new initialValues, so i need to dispatch 'initialize' action.
I tried to follow docs section on initialize:
`initialize(form:String, data:Object, fields:Array<String>)`
How i try to do it:

```javascript
// import actionCreator & wrap it in dispatch:
import { initialize as initializeForm } from 'redux-form'
...
const ActionModalForm = reduxForm({ form: 'actionModal' })(ActionModal)
return connect(state => 
  ({ initialValues: state.actionValue}),
  { initialize: initializeForm }
) 
(ActionModalForm)

//Execute init action when i need it:
initialize('actionModal', newValue)

```

Then in console i see action details:
![1](https://cloud.githubusercontent.com/assets/1133682/15983792/745e3c32-2fbb-11e6-9b35-f01271e3095b.PNG)
So no init value were passed

My solution with redux-actions:
```javascript
forceInit: createAction('redux-form/INITIALIZE', action => action, () => ({ form: 'actionModal' }))
```

**Comment by eloytoro** [comment]
form components are injected an `initialize` prop function, did you try that?

**Comment by Darmody** [comment]
I think you forget to dispatch initialize action.

**Comment by olegkalyta** [comment]
@eloytoro You are right, `initialize` from prop forks fine for me, thanks!
