### ISSUE TITLE
Redux-form how to make it work with React-Select

### ISSUE THREAD

**Issue by Ahmtdnz** [erikras/redux-form#1138]
Hi, aswome work!

I am trying to use [react-select ](http://jedwatson.github.io/react-select/)with redux-form but react-select(event.target.value) == null.

is there a way to make redux-form with react-select?

Thanks for help.

**Comment by ooflorent** [comment]
Hi!

This is a usage question, and we encourage you to ask it on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

This is the only way to ensure the same question doesn’t get asked many times in a row, and that folks who have the same question in the future will be able to find it.

I’m closing for these reasons.
