### ISSUE TITLE
Drag and Drop between Input fields

### ISSUE THREAD

**Issue by kshreve** [erikras/redux-form#114]
Selecting text from a redux-form connected input field, and then dragging and dropping to another input field does not currently work.

**Comment by erikras** [comment]
Do you know what event gets fired on a text drop?

**Comment by kshreve** [comment]
Correct. The event is `drop`, the handler is `onDrop`.

**Comment by erikras** [comment]
They really need to put the "close and comment" button on the opposite side. You're the third person I've seen today make that error (and I do it often).

I don't suppose `event.target.value` is set when `onDrop` is triggered, is it? Otherwise you could just say `onDrop={fields.myField.onBlur}`.

**Comment by kshreve** [comment]
Ha, I know I thought the "close and comment" meant close the preview.

Unfortunately event.target.value is not set.

**Comment by erikras** [comment]
How frustrating! From what I can tell in Chrome, the drop event has no information whatsoever about the data being dropped in, and it fires an `onChange` for with whatever was already in the recipient field.

Any ideas?
