### ISSUE TITLE
[v6] Initializing the form unregisters all the fields

### ISSUE THREAD

**Issue by eloytoro** [erikras/redux-form#1140]
Dispatching `initialize` unregister all of the form fields, causing errors upon submission.
Also the third parameter `fields` (from the most recent docs) doesn't seem to apply to v6 since redux-form no longer needs to define the form fields in the form config.

Steps to reproduce:

1. Load a form
2. Make sure all fields were registered to the form
3. Dispatch `initialize`
4. Notice that the form state no longer no longer has `registeredFields`
5. Submitting the form causes an error

**Comment by eliseumds** [comment]
The methods `reset` and `destroy` are doing the same. My use case is: I have a "Reset" button that resets the form and then automatically submits it. Because `registeredFields` disappear, we get:

````
Uncaught TypeError: Cannot read property 'map' of undefined
```

[at this line](https://github.com/erikras/redux-form/blob/v6/src/reduxForm.js#L181).

**Comment by eloytoro** [comment]
This appears to be fixed in recent versions, closing it
