### ISSUE TITLE
Submit onBlur

### ISSUE THREAD

**Issue by hwaterke** [erikras/redux-form#1142]
Hi,

Thanks a lot for this library, works like a charm for the simple use cases.
I'm trying to submit a form when a field loses focus but I'm not sure how to go about it.
Looks like there is already a onBlur function that expects the value.
Can I simply use the following or am I gonna break something?

```
<input type="text" autoFocus onBlur={handleSubmit} {...myField}/>
```

Thanks a lot for your help.

**Comment by ooflorent** [comment]
You can use it, it's fine.

**Comment by oyeanuj** [comment]
@hwaterke Is that the solution you ended up using for submitting when a field loses focus?
