### ISSUE TITLE
6.0 A15 Not retrieving correct values?

### ISSUE THREAD

**Issue by timothyallan** [erikras/redux-form#1147]
Just installed alpha15 and copied http://redux-form.com/6.0.0-alpha.15/examples/syncValidation/ verbatim into my app. So I have a form named 'syncValidation' in a new component.

I can see Redux doing it's thing and sending out the appropriate state changes, and can see the fields in DevTools monitor.

![screen shot 2016-06-12 at 10 32 16 am](https://cloud.githubusercontent.com/assets/1995135/15992431/55f33526-3089-11e6-8668-2973cfef7dac.png)

However, typing/clicking anything seems to never gets saved in the redux state, so the text fields never actually populate even though I can see my typing registering.

![screen shot 2016-06-12 at 10 36 00 am](https://cloud.githubusercontent.com/assets/1995135/15992435/a25e9798-3089-11e6-8bcc-07ae8795af98.png)

I've tried production and hot-reload builds as I'd read that hot reload sometimes messes things up, with the same result.

Any suggestions?

**Comment by ooflorent** [comment]
Are you passing arrow functions in `component`?

**Comment by timothyallan** [comment]
I copied http://redux-form.com/6.0.0-alpha.15/examples/syncValidation/ exactly. It uses ```renderField``` for ```component``` which is an arrow function.

**Comment by ooflorent** [comment]
Sorry, I wasn't precise enough. What I wanted to know is if you were using this pattern:

```js
<Field name="foo" component={foo => <input {...foo} type="text" />} />
```

Using arrow function is fine. Creating within `render` or another functional component is not.

Could you add some code to your issue? Since the example you're mentioning is working fine, the issue is might be related to your component.

**Comment by timothyallan** [comment]
That's the thing, the SyncValidationForm.js from the demo IS my component :)

I'm simply putting it in a parent component and instantiating it using:

````
import SyncValidationForm from 'components/SyncValidationForm';
import styles from './styles.css';

export class LoginPage extends React.Component {
  render() {
    return (
      <div className={styles.loginPage}>
        <SyncValidationForm />
      </div>
    );
  }
}
````

**Comment by timothyallan** [comment]
If the demo is working fine with A15, then it's just got to be something getting mucked up on my end somewhere. I'll keep hunting then, thanks for the help :)

**Comment by timothyallan** [comment]
For anyone else with this... make reeeeeeal sure that you  
```import { Field, reduxForm } from 'redux-form/immutable';```
 instead of 
```import { Field, reduxForm } from 'redux-form';```
When using Immutable.js ;)
