### ISSUE TITLE
File input field clears when different field gets focus

### ISSUE THREAD

**Issue by renarsvilnis** [erikras/redux-form#1148]
Hi, having trouble with file inputs in a complex form scenario. I have a multi-page (*wizard*) form, where one of the steps contains a file input.

Everything goes as expected when I pick a file through the file input. The `FileList` containing a single file is passed to validation and afterwards back in react component the `fields.file.value` is a `FileList` instance of length 1. But once I focus any other input field on the save form page, the `FileList` becomes empty.

![redux-form-issue](https://cloud.githubusercontent.com/assets/3515099/15995168/18b43052-311f-11e6-9f17-ab1fca13fe4b.gif)

## Code
Relevant code blocks from the above gif example.

> the `file` variable is the field object from `this.props.fields`.

`Currently selected file name box`

```javascript
handleFileRemove () {
  const file = this.props.fields.biometric.file;
  file.onChange(null);
}

let fileName = 'No file selected';
let fileRemoveBtn = null;

if (file.value instanceof FileList && file.value.length) {
  fileName = file.value[0].name;
  fileRemoveBtn = (
    <img
      src={require('../../images/button-close.svg')}
      alt="close"
      onClick={this.handleFileRemove.bind(this)}
    />
  );
}

<div className={classNames({
  'checkout__fileinput-display': true,
  'checkout__fileinput-display--error': file.touched && file.error,
  'checkout__fileinput-display--has-file': fileName
})}
>
  {fileName}
  {fileRemoveBtn}
</div>
```

`The file input button`

```javascript
<div className="checkout__row">
  <label className="button button--fileupload button--purple button--fixed-width">
    {'Browse file'}
    <input
      type="file"
      {...file}
      value={''}
    />
  </label>
</div>
```

### UPDATE
Found out from debugging redux actions that the `redux-form/CHANGE` for the file input contains a empty `FileList`. But the validation function receives the correct/non-empty `FileList`. Have tried removing the validation, just to check if somehow it does not mutate, which it didn't.

<img width="978" alt="screen shot 2016-06-13 at 04 56 06" src="https://cloud.githubusercontent.com/assets/3515099/15995395/4a688130-3123-11e6-9a37-1006e5fb2f04.png">

## `onBlur` not called on file input

Also noticed that onBlur is not called, thus `touched` always stays `false`. Resolved it by attaching my own `onChange` listener of the file input, that just proxies the `event` to the fields `onBlur` so that `touched` gets modified.

```javascript
handleFileChange (ev) {
  const fileField = this.props.fields.biometric.file;
  fileField.onBlur(ev);
}
```

## Setup

- react: "15.1.0"
- redux: "3.5.2"
- redux-form: "5.2.5"

**Comment by ooflorent** [comment]
You could try to _noop_ the default `onBlur` handler since Redux Form will try to override the value by extracting it from the `blur` event.

```js
onBlur={() => this.props.fields.biometric.file.onBlur()}
                                               ^^^^^^^^
                                               no event
```

**Comment by renarsvilnis** [comment]
Solved the input file clearing by passing `undefined` instead of an `empty` string. 

```javascript
<input
  type="file"
  {...file}
  onChange={this.handleFileChange.bind(this)}
  value={undefined}
/>
```

And solved the `onBlur` issue by handling the `onChange` and sending the `event` to `field.onBlur`.

```javascript
handleFileChange (ev) {
  const fileField = this.props.fields.biometric.file;
  fileField.onBlur(ev);
  this.forceUpdate();
}
```


> Edit2: Be careful with shouldComponentUpdate because diffing FileList may fail

I used `forceUpdate()` to force a update for the file.
