### ISSUE TITLE
createConnectReduxForm requires 'react' and blocks native

### ISSUE THREAD

**Issue by mschipperheyn** [erikras/redux-form#115]
createConnectReduxForm imports react-redux as opposed to react-redux/native. As such, it has a dependency on 'react'. Am I missing something?

**Comment by erikras** [comment]
I would be surprised if that was causing any problems, but it was _definitely_ an inconsistency. Thank you. :+1: 

[v2.0.1](https://github.com/erikras/redux-form/releases/tag/v2.0.1)

**Comment by mschipperheyn** [comment]
Great, yeah, if you try to import 'react' in a react-native app, it bombs

**Comment by erikras** [comment]
Hmm. Other people have been using redux-form in RN apps, though. Can you confirm that this fixes your problem?

**Comment by mschipperheyn** [comment]
Yes, it does (I think that this feature was added since 2.0.0, 6 days ago, so presumably nobody noticed yet)

**Comment by erikras** [comment]
Awesome. Thank you, again, @mschipperheyn.

**Comment by mschipperheyn** [comment]
u2!
