### ISSUE TITLE
Bluebird & asyncValidate

### ISSUE THREAD

**Issue by q42jaap** [erikras/redux-form#1151]
I'm using bluebird in an asyncValidate method. When the field which will trigger asyncvalidate has focus, and I click submit, the async validation is triggered from the handleSubmit function.

My validation function returns Promise.resolve({}), so submit goes through. The submit function in it's turn does an api call using bluebird again.

When this happens, I get a bluebird specific warning
```
Warning: a promise was created in a handler but was not returned from it
```
Which is explained here: http://bluebirdjs.com/docs/warning-explanations.html#warning-a-promise-was-created-in-a-handler-but-was-not-returned-from-it

The stacktrace shows my submit function and it also shows a "previous" event.
This previous event is the handleSubmit function.

I've tracked it down to this line:
https://github.com/erikras/redux-form/blob/master/src/handleSubmit.js#L35

The submit function passed to handleSubmit should return something, but my submit function looks something like this:
```
function mapDispatchToProps(dispatch) {
  return {
    onSubmit(values) {
      dispatch(doSomething(values));
    },
  };
}
```
Adding a `return null;` after the dispatch resolves the warning.

I'm not sure if redux form should be aware that returning undefined in bluebird has some warning side-effect. 

I could not track down whether the promises in that code path are necessary, if it's not it might be worth to change it.

Otherwise, it might be worth documenting this bluebird behaviour somewhere, so others who run into this have a chance of reading about it.

**Comment by erikras** [comment]
Hmm... I usually use a [promise middleware](https://github.com/erikras/react-redux-universal-hot-example/blob/master/src/redux/middleware/clientMiddleware.js) that causes `dispatch()` to return a promise. `redux-form`'s `handleSubmit()` allows for synchronous submission by examining whether or not the `onSubmit` it has returns a promise. It sounds like you're doing sync submission with async validation, which is a combination I don't believe I had considered.

> I'm not sure if redux form should be aware that returning undefined in bluebird has some warning side-effect.

I agree.

> Otherwise, it might be worth documenting this bluebird behaviour somewhere, so others who run into this have a chance of reading about it.

Maybe, but I'm not sure _where_ that documentation should go. Perhaps just this well-titled issue is enough?

**Comment by q42jaap** [comment]
The submission I'm doing is something like this:
```
dispatch({type: 'SOME_API_CALL_REQUEST'})
doSomeApiCall()
  .then((someResult) => dispatch({type: 'SOME_API_CALL_SUCCESS', someResult}))
  .catch((error) => dispatch({type: 'SOME_API_CALL_FAILURE', error}))
```
We use these events in some other place (mostly api activity and showing a generic error dialog).

I'm not sure I understand what you meant by
> It sounds like you're doing sync submission with async validation

**Comment by q42jaap** [comment]
I guess we can leave it at this...
