### ISSUE TITLE
Validation not called on props change

### ISSUE THREAD

**Issue by neopostmodern** [erikras/redux-form#1152]
I found [this comment](https://github.com/erikras/redux-form/issues/118#issuecomment-154549927), which points out that I can access *any part of the state* during validation by providing a `mapStateToProps`.

So now I have
```jsx
function serverErrorToProps(state) {
  return {
    serverError: state.error
  }
}
function Validation(fields) {
  return (values, props) => {
    console.log("Props passed to validate:", props);
    // ...
  }
}

class RequestForm extends Component {
  // ...
}

reduxForm({
  form: 'request-form',
  fields: Object.keys(Fields),
  validate: Validation(Fields)
}, serverErrorToProps)(RequestForm);
```

The idea: if the server sends back an error concerning a specific field, I want to show them on the field itself, not in the global error message we usually display.

But validate apparently doesn't get called on when the props change, only when the form changes.

(I recognize that there might be better ways to display error messages from the server - and I'll look into them - but I still found this worth reporting.)

**Comment by alurim** [comment]
I think this is desired behavior. Validation only concerns itself with changes to the form so other prop changes wouldn't influence its behavior. redux-form does provide a mechanism for validating for specific fields from the server with asyncValidate See the example [here](http://redux-form.com/5.2.5/#/examples/asynchronous-blur-validation?_k=ks0k4k) as something to go off of!

**Comment by erikras** [comment]
Sync validation gets called on every single render.

**Comment by neopostmodern** [comment]
Am I misunderstanding something, or is that not actually working?

I did some print debugging (code pretty much the same as above) and my log says:
```
[...]
Validation.js?85f1:5 Server error passed to Validate null
UserForm.js?0cd4:16 Server error passed to render() null
api.js?cd39:40 POST http://localhost:3001/users 400 (Bad Request)callApi @ [...]
UserForm.js?0cd4:16 Server error passed to render() Object {Mail: "Already exists"}
[...]
```
So clearly it gets rendered again, but it *doesn't* seem to validate again.

**Comment by danielevns** [comment]
Was this ever resolved? I have the same issue in v6: Synchronous validation is not being performed on props change despite `render` being called.

**Comment by gustavohenke** [comment]
Hi @danielevns, that was from the v5 age. 
It would be great if you could open a new issue with an example.

**Comment by rafaelcorreiapoli** [comment]
I'm having this problem too
Using redux-form v6.8.0

**Comment by danielevns** [comment]
@rafaelcorreiapoli As discussed in the linked issue #2809, this is per design. The workaround is to use [`shouldValidate`](https://redux-form.com/6.8.0/docs/api/ReduxForm.md/#-shouldvalidate-params-boolean-optional-).
