### ISSUE TITLE
v6 — result.then(...).catch is not a function

### ISSUE THREAD

**Issue by FutureKode** [erikras/redux-form#1155]
Version: ^6.0.0-alpha.15

This line here on submit: https://github.com/erikras/redux-form/blob/v6/src/handleSubmit.js#L19

I have several forms and it is only happening on a form that has initialValues passed in as a prop

**Comment by gustavohenke** [comment]
Hi @FutureKode, have a happy new year! Sorry for the delay in replying.
Can you check with some recent releases?

I'll close here because this was for an alpha version, and the code even changed until v6.0.0 final was released.
