### ISSUE TITLE
Dependent Fields in v6

### ISSUE THREAD

**Issue by ruiaraujo** [erikras/redux-form#1156]
How should one handle dependent field errors in v6?
Imagine two fields whose errors depend on the value of both fields like a password creation.
The validate gathers all the errors but the Field only rerenders if I touch it again.

Is this on purpose or a bug?

**Comment by alurim** [comment]
If you were able to hook up a component to two fields this would be trivial again (what I'm proposing [here](https://github.com/erikras/redux-form/issues/1173)). The `Field` component is great and it forces developers to write components that only need to re-render when the field they care about is changed in the store, but there are edge cases like this where IMO it makes sense to hook up a component to multiple fields.

**Comment by gustavohenke** [comment]
`Fields` component did that - check #1554
