### ISSUE TITLE
[v6] values prop not being passed through redux-form

### ISSUE THREAD

**Issue by alurim** [erikras/redux-form#1159]
I'm currently migrating to v6 and my component was using the `values` field that v5 passed through. After  converting it to user a `formValueSelector` I noticed that if I named the prop `values` it doesn't get passed through (other names for the prop do though). See this [simple repro diff](https://github.com/erikras/redux-form/compare/v6...alurim:patch-1). Is this intentional? If not a fix would be totally appreciated.

**Comment by alurim** [comment]
Also it seems that a prop named `state` isn't being passed through `FieldArray` or `Field`.

**Comment by frost555** [comment]
I think the problem with 'values' prop is that it will change on every keypress - therefore your entire form will rerender alot. You can workaround this by query state tree.
Like this 

    export let formValuesSelector = (state) => state.form.payment.values;

**Comment by alurim** [comment]
@frost555, I'm talking about something other than the v5 `values` prop. I'm saying in v6 if you pass in a prop with the name `values` into a decorated `reduxForm` component it get's stripped out.

**Comment by ooflorent** [comment]
`values` is removed in v6. You should use [`formValueSelector`](http://redux-form.com/6.0.0-alpha.15/docs/api/FormValueSelector.md/).

**Comment by sungwoncho** [comment]
@ooflorent The doc for `0.6.5` still references `values` as an instance API (http://redux-form.com/6.0.5/docs/api/ReduxForm.md/). Should this be removed, then? Happy to open a PR.
