### ISSUE TITLE
I followd the demo. But got a error

### ISSUE THREAD

**Issue by bodyno** [erikras/redux-form#1160]
Uncaught Error: You must either pass handleSubmit() an onSubmit function or pass onSubmit as a prop

Like this.
How can I do with it

**Comment by erikras** [comment]
What demo? Show your code.

**Comment by bodyno** [comment]
It's here
http://redux-form.com/5.2.5/#/examples/simple?_k=uz3p2z

I just follow this.
But got this error on my code.
Everything is all right.
Only on me click the submit button.
Then show:
Uncaught Error: You must either pass handleSubmit() an onSubmit function or pass onSubmit as a prop

**Comment by callmephilip** [comment]
Seeing the same problem with http://redux-form.com/5.2.5/#/getting-started?_k=5y2bix
Reproduced here: https://github.com/thebakeryio/redux-form-issue

**Comment by bodyno** [comment]
Even this throw an error
https://github.com/thebakeryio/redux-form-issue
Why?
I didn't touch anything

**Comment by callmephilip** [comment]
@erikras any thoughts on this?

**Comment by gabrielpugliese-luizalabs** [comment]
You guys can see the reproduction link in this issue (I've got another issue related):
https://github.com/erikras/redux-form/issues/1165

**Comment by crittelmeyer** [comment]
Not sure if this is related, but I'm seeing the "You must either pass handleSubmit() an onSubmit function or pass onSubmit as a prop" error message when trying to run the 6.0.0-alpha asyncValidation example here: http://redux-form.com/6.0.0-alpha.15/examples/asyncValidation/

**Comment by erikras** [comment]
Well, the problem is exactly what the error message says it is. Suggestions for how to more clearly reword it are welcome.

I wish I could anchor-link directly to it, but scroll down to the `handleSubmit` section [of the docs](http://redux-form.com/5.2.5/#/api/props).

In the example, we are providing an `onSubmit` prop to the decorated form component.

[Here's a PR to fix your example](https://github.com/thebakeryio/redux-form-issue/pull/1/files).

**Comment by callmephilip** [comment]
Thanks for taking time to look into this, Erik. I think you should update 'Getting started' examples to reflect this (http://redux-form.com/5.2.5/#/getting-started?_k=uo5tq0) since they are currently misleading especially the **That's it! There is no Step #3!** part

**Comment by axe-z** [comment]
Yes I've been stuck for hours, all the steps should be there... this is ... Extremely misleading.
