### ISSUE TITLE
action creator for validation errors

### ISSUE THREAD

**Issue by beornborn** [erikras/redux-form#1162]
I use redux-saga for side effects.

I need to show error for my form by passing action.

like 

``` javascript
import { validationErrors } from 'redux-form'
...
yield put(validationErrors('form', 'password', 'bad password', {form_error: 'Login failed'))
```

how can I do that?

**Comment by gustavohenke** [comment]
Just use normal validation.
Here are some examples:
- [Sync validation](https://redux-form.com/6.4.0/examples/syncValidation)
- [Async validation](https://redux-form.com/6.4.0/examples/asyncValidation)
- [Submit validation](https://redux-form.com/6.4.0/examples/submitValidation)

**Comment by beornborn** [comment]
@gustavohenke 
It's not the correct answer. 
Of course before asking I checked basic documentation and googled it, I was really desperate to find an answer if decided to create an issue understanding that it will be answered in half a year. 

the way to integrate to saga is the next and is not described on docs: 

container: 
```javascript
export const mapDispatchToProps = (dispatch: Function): Object => ({
  submitForm: (formData) =>
    new Promise((resolve, reject) => {
      dispatch(createAction(SAGA_SEND_ACCOUNT_STATUS_CHECK)({formData, resolve, reject}))
    })
})
```

saga:
```javascript
export function* perform(a) {
  try {
    const { formData, reject, resolve } = a.payload
    const mutation = mutationByAction[a.type]

    yield put(createAction(TOGGLE_RIGHT_LOADING)())
    const memberId = yield select(selectMemberId)
    const response = yield call(apolloClient.mutate, {
      mutation: getMutation(mutation),
      variables: Object.assign({}, {id: memberId}, formData)
    })
    const data = response.data[mutation]

    if (data.status === 'Fail') {
      const error = new SubmissionError({ _error: data.errors.join(', ') })
      yield call(reject, error)
      yield put(createAction(TOGGLE_RIGHT_LOADING)())
    } else {
      const member = yield call(getMember, {payload: {id: memberId}})
      yield put(createAction(SET_MEMBER_IN_LIST)({member}))
      yield put(createAction(TOGGLE_RIGHT_LOADING)())
      yield call(resolve)
    }
  } catch (err) { console.log(err) }
}
```

**Comment by gustavohenke** [comment]
Sorry if I was rude to you.
I don't know how the docs looked like back in june (I only started using redux-form as of october). If they weren't helpful - the best we can do is hope they are clearer nowadays.

It's generally best to ask such type of questions at StackOverflow, using the redux-form tag; it's very likely that you'll get responses _way faster_.

---

redux-saga/redux-form integration really is a hot topic:
- #2227
- yelouafi/redux-saga#161

And I agree that new examples is probably a good idea, given the popularity of both libs.

---

So, looking again at your original question, you could probably use `stopSubmit` action creator, but beware that it'll also flip the `submitting` flag of your form.
https://github.com/yelouafi/redux-saga/issues/161#issuecomment-254939672
