### ISSUE TITLE
How to access props in the onSubmit function?

### ISSUE THREAD

**Issue by diegohaz** [erikras/redux-form#1163]
I was expecting to work with `onSubmit` the same way I do with `asyncValidate`, but it lacks the last parameter (props). Anyone knows how to access it?

```js
const onSubmit = (data, dispatch, props) => {
  console.log(props) // undefined
}

export default reduxForm({
  form: 'login',
  fields: ['email', 'password'],
  validate,
  onSubmit
})(LoginForm)
```

**Comment by ooflorent** [comment]
You could not access `props` from `onSubmit`.
If you want access them, you could do it this way:

1. Create a bound method to forward the component's properties:

    ```js
    onSubmit = (values, dispatch) => {
      this.props.onSubmitWithProps(values, dispatch, this.props)
    }
    ```

2. Call the newly created method inside on traditional `onSubmit` property:

    ```js
    this.props.handleSubmit(this.onSubmit)
    ```

3. Pass `onSubmitWithProps` instead of `onSubmit`:

    ```js
    // Define `onSubmitWithProps`
    const onSubmitWithProps = (values, dispatch, props) => {
      console.log(props) // Object
    }

    // Inside `render`
    <LoginForm onSubmitWithProps={onSubmitWithProps} />
    ```

**Comment by diegohaz** [comment]
Thank you. It works.

Have you thought to make it pass props by default?
Would just change this line? https://github.com/erikras/redux-form/blob/master/src/handleSubmit.js#L13

**Comment by benwiley4000** [comment]
@ooflorent this is simply a bad solution for folks who want to be able to use functional React components, available in newer versions of React, i.e. avoid classes with bound methods. I see no reason not to pass `props` to `onSubmit`? They're passed to validation, they should be available `onSubmit` as well.

**Comment by tzapu** [comment]
i would also benefit greatly from having access to props on onSubmit...
thank you

**Comment by diegohaz** [comment]
@erikras can you take a look at this?

**Comment by olistic** [comment]
This has been taken care of in [v6.0.2](https://github.com/erikras/redux-form/releases/tag/v6.0.2).

**Comment by ntomallen** [comment]
To beginners like me, trying to figure out how this works, it looks like this:

```
// yourjsfilehere.js
export const submit = (values, dispatch, props) => {
  console.log(props) // Logs the props from redux-form, as well as the props available to the React component which contains the form.
}
```

And declare the form as normal
```
import { Field, reduxForm } from 'redux-form'
import React from 'react'
import { submit } from './yourjsfilehere'

const FormWithProps = ({handleSubmit, id}) => {
    return (
        <form onSubmit={handleSubmit(submit)}>
            // Your form here ...
        </form>
     )
}

export default reduxForm({
  form: 'FormWithProps '
})(FormWithProps )
```

I hope this is helpful to others trying to use this.

**Comment by mtpetros** [comment]
It took me a little digging to find this answer, so just to be explicit, you can access props if you are using onSubmit outside the component like so:

```
export default reduxForm({
  form: 'myForm',
  onSubmit: (values, dispatch, props) => {
    console.log(values);
    console.log(dispatch);
    console.log(props);
  }
})(LoginForm)
```

**Comment by jmny** [comment]
see also : https://redux-form.com/7.3.0/docs/faq/handlevson.md/

**Comment by herarya** [comment]
@mtpetros thanks bro, work 💯

**Comment by w121211** [comment]
Although `props` can be access through `onSubmit: (values, dispatch, props) => {...}`, the props seems to be the `ownProps` rather than `state props` (which processed via `mapStateToProps`).
My question is how can I access the `state props`?

**Comment by danielrob** [comment]
@w121211 are you sure that you're wrapping the connect function around the reduxForm function. If you do it the other way around, the props from react-redux won't have been injected yet. So: 

`connect(reduxForm(YourForm))` not `reduxForm(connect(YourForm))`

(Just a guess.)
