### ISSUE TITLE
asyncBlurFields not in example (6.0.0-alpha.13)

### ISSUE THREAD

**Issue by OKNoah** [erikras/redux-form#1164]
The example reads:

> You will also need to specify which fields should fire the asynchronous validation when they are blurred with the `asyncBlurFields` config property.

But the example doesn't show `asyncBlurFields` anywhere.

http://redux-form.com/6.0.0-alpha.13/examples/asyncValidation/

**Comment by gustavohenke** [comment]
Fixed some time in the past 👴
