### ISSUE TITLE
[v5] Can't send from parent if you don't pass onSubmit but do call handleSubmit with a custom function

### ISSUE THREAD

**Issue by gabrielpugliese-luizalabs** [erikras/redux-form#1165]
### Problem

Using redux-form 5.2.5, I've tried to change the submit from parent example: instead of receiving a `onSubmit` func, receives a `customSubmit` func that will be the param for `handleSubmit` inside the decorated form. But you receive this message when submiting:

```
Uncaught Error: You must either pass handleSubmit() an onSubmit function or pass onSubmit as a prop
```
### Reproduction

 http://www.webpackbin.com/VyhtSY9Vb
You see that I've changed `SubmitFromParentContainer.js:27` and then changed `SubmitFromParentForm.js:22` to be a form: `<form onSubmit={handleSubmit(customSubmit)}>`
### Why is this useful?

In my real world app, I wanted to keep the submit logic inside the decorated form. So, instead of passing a customSubmit to `<SubmitFromParentForm>`, it would have its own and I would return the form like this:
`<form onSubmit={handleSubmit(this.customSubmit)}>`

**Comment by gabrielhpugliese** [comment]
Well, I've debugged the source code and I understand now why it would never work the way it's designed. We don't have a reference to the `onSubmit` function of the form and you explicitly call this:
`submitPassback(() => this.handleSubmit());  // wrapped in function to disallow params` that override the other one.
I don't see how the desired effect could happen in the way it is implemented and not using state. Probably with state it would be possible to "register" that `handleSubmit` was called with a function.

**Comment by danielrob** [comment]
Closing with bulk close of v5 issues. If this issue still requires action and/or also affects v6/7, please request a reopen with details or raise a new issue. v5 PR's are still welcomed.
