### ISSUE TITLE
[v5.2.4] Is Redux Form Reusable for Create and Update Forms

### ISSUE THREAD

**Issue by switmac** [erikras/redux-form#1168]
I am using the same form component for create and update form but it appears to be using the same form instance. Since the initial values I set for the update form appears also in the create form. I also have the same form name for both the create and update I created will that matter? 
Am I missing something? Please let me know.. thanks!

```js
export default reduxForm({ form: 'GateForm' }, null, null)(GateForm);
```

**Comment by ooflorent** [comment]
The `form` parameter defines the internal name of the form. So if you instantiate twice the form, both forms will share the same internal stored values (`state.form[formName]`). The workaround is simple. 

**1. Specify different `form` (preferred solution)**

If you omit the `form` parameter, you can specify it using `props`.

```js
// GateForm.js
export default reduxForm({})(GateForm)

// UpdateGate.js
<GateForm form="updateGate" />

// NewGate.js
<GateForm form="newGate" />
```

The stored values will be:

```js
{
  form: {
    updateGate: { /* ... */ },
    newGate: { /* ... */ },
  }
}
```

**2. Use `formKey` (removed in v6)**

This time, you don't change how the form is defined. However, you have to pass a `formKey` to the component:

```js
// UpdateGate.js
<GateForm formKey="update" />

// NewGate.js
<GateForm formKey="new" />
```

The stored values will be:

```js
{
  form: {
    GateForm: {
      update: { /* ... */ },
      new: { /* ... */ },
    }
  }
}
```

**Comment by switmac** [comment]
Thank you for this solution @ooflorent ! much appreciated. :+1:

**Comment by NeXTs** [comment]
@ooflorent Any analogue of formKey in v6?
There are FieldArray but it doesn't fit cases like [this](http://redux-form.com/5.3.1/#/examples/multirecord)
Multiple forms with unique submit button.

FieldArray as I understood may be used with sungle form and single submit button while I need to validate each row independently

**Comment by erikras** [comment]
P.S. The solution to "what to do in v6 with no `formKey` is just to pass a different name for the `form` prop.

**Comment by NeXTs** [comment]
Yep, thanks, figured out this from ooflorent's example

**Comment by TirthankarMukherjee** [comment]
I am using 6.3.2. What is the work around when I need to initialize & reinitialize the form for update, and now I want to re-use it for create as well.
`
IndexForm = reduxForm({
  form: 'indexForm',
  enableReinitialize: true,

})(IndexForm);

IndexForm = connect(
  state => ({
    initialValues: state.indexUpdate,
  })
)(IndexForm);

export default IndexForm;
`
