### ISSUE TITLE
[v6] RFC: Complex Fields API addition

### ISSUE THREAD

**Issue by alurim** [erikras/redux-form#1173]
Currently my application has complex inputs that are wired with two fields. Although this is totally achievable with the current API, I've had to create multiple wrapper components and string through Field props to get what I'd like. Consider this example:

We're building a todo item with two fields "description" and "tags". Not only can you add tags to a todo item, but they're also automatically added if a tag's name is in anywhere in the description. Currently I'd have to wire it up like so:

``` js
const TodoItemDescriptionEnhancedWithDescriptionAndTags = ({ descriptionField, ...tagsField }) => {
    <input 
        {...descriptionField}
        onChange=(event => {
            descriptionField.onChange(event)
            const value = event.target.value
            if (tagInDescription(value)) {
                tagsField.onChange((tagsField.value || []).concat(value))
            }
        }) 
    />
}

const TodoItemDescriptionEnhancedWithDescription = descriptionField => {
    <Field
        name="tags"
        component={TodoItemDescriptionEnhancedWithDescriptionAndTags}
        descriptionField={descriptionField}
    />
}

const TodoItemDescription = () => {
    <Field
        name="description"
        component={TodoItemDescriptionEnhancedWithDescription}
    />
}

<Field
    name="description"
    component={TodoItemDescription}
/>
```

As you can see this is a pain. It gets worse if you want `TodoItemDescription` to take its own props as those have to wired through all the components themselves to not get subsumed into the field props.

What if `Field`'s `name` prop also takes an array of field names and if it is an array and for every element (let's say named "foo") in that array it generates a "fooFields" object that contains all the props for the "foo" field. Then the code would be much simpler and look like so:

``` js
const TodoItemDescription = ({ descriptionField, tagsField }) => {
    <input 
        {...descriptionField}
        onChange=(event => {
            descriptionField.onChange(event)
            const value = event.target.value
            if (tagInDescription(value)) {
                tagsField.onChange((tagsField.value || []).concat(value))
            }
        }) 
    />
}

<Field
    name={["description", "tags"])
    component={TodoItemDescription}
/>
```

Wanted to see if this seemed valuable to others before trying to send out a PR to accomplish this goal. Lemme know!

**Comment by gustavohenke** [comment]
`Fields` made it possible! Check #1554
