### ISSUE TITLE
No 'dev' run script as documented in Examples.

### ISSUE THREAD

**Issue by mojochao** [erikras/redux-form#1174]
The Examples docs (http://redux-form.com/5.2.5/#/examples?_k=hp317d) indicates that I can run the examples in the 'gh-pages' branch locally with 'npm run dev' script.  No such script exists in package.json in the 'gh-pages' branch.

**Comment by ooflorent** [comment]
This script exists: [gh-pages/5.2.5/package.json#L10](https://github.com/erikras/redux-form/blob/gh-pages/5.2.5/package.json#L10)

```js
"dev": "node ./node_modules/better-npm-run dev"
```

**Comment by abkamran** [comment]
The download didn't have the dev script specified in package.json. Will use the above one. But, it's really not included during download.
