### ISSUE TITLE
Can't clear form state using undefined in form reducer plugin

### ISSUE THREAD

**Issue by Fauntleroy** [erikras/redux-form#1175]
The [documentation states](http://redux-form.com/5.2.5/#/faq/how-to-clear?_k=4vazzt) that you can clear a form by returning `undefined` using the form reducer plugin, but that does not seem to be the case. Here's the code I'm using:

```js
formReducer.plugin({
  'update-password': function (state, action) {
    switch (action.type) {
      case UPDATE_USER_PROPERTIES_SUCCESS:
        return undefined;
      default:
        return state;
    }
  }
});
```

I can, however, manually clear individual fields by returning empty objects on their keys:

```js
return {
   ...state,
   password: {},
   newPassword: {}
};
```

Am I doing something incorrectly? Is the documentation wrong?

**Comment by sknoslo** [comment]
What version of redux-form are you using? Assuming 5.2.5, based on the link you provided, this functionality is broken (see #1083). If you are using v6, checkout the [new documentation](http://redux-form.com/6.0.0-alpha.15/docs/api/ReducerPlugin.md/).

**Comment by Fauntleroy** [comment]
Duplicate of https://github.com/erikras/redux-form/issues/1083
