### ISSUE TITLE
Problem with setting the initialValues on my fields

### ISSUE THREAD

**Issue by srajchevski** [erikras/redux-form#1177]
So I have a simple form consisted of two fields :
```js
export const fields = [ 'name', 'group' ];
```

and my problem is that I can't populate their initialValues with the values from my 'user' , because props is undefined in the export default compose function.

This works perfectly fine: 

```js
export default compose(
  connect(mapStateToProps, actions),
  reduxForm({
    form: 'editUser',
    fields,
    initialValues: {
      name: 'ss',
      group: 'lolo'
    },
    validate
  })
)(EditUser)
```
But when I switch 'ss' and 'lolo' with either this.props.user.name OR this.state.username (my defined state variable filled with the user's name) i get an error saying that PROPS OR STATE are undefined.
I'm sure the solution is simple, but i just couldn't figure it out.

**Comment by alurim** [comment]
Howdy! note that `this` isn't tied to the component when you define the options for `reduxForm`. Instead try something like this:

```
export default _.flow(
	reduxForm({
		form: 'editUser',
		fields,
	}),
	connect({
		(state, props) => ({
			initialValues: {
				name: this.props.name
			},
		})
	})
)
```

To use state to initialize the form see [`initializeForm`](http://redux-form.com/5.2.4/#/api/props?_k=qi1mq5) and do it after the state is set.

**Comment by ooflorent** [comment]
You could use this pattern to solve your issue:

```js
function mergeProps(stateProps, dispatchProps, ownProps) {
  return {
    ...stateProps,
    ...dispatchProps,
    initialValues: {
      name: ownProps.user.name,
      group: ownProps.user.group,
    }
}

export default compose(
  connect(mapStateToProps, actions, mergeProps),
  reduxForm({
    form: 'editUser',
    fields,
    validate
  })
)(EditUser)
```

**Comment by srajchevski** [comment]
The best way I found around this problem was setting the `initialValues` in the mapStateToProps function like so:
`function mapStateToProps (state) {
	return { initialValues : state.users.user };
}`
, so my name and group fields populate automatically.
