### ISSUE TITLE
OnSubmit still called after validate fails?

### ISSUE THREAD

**Issue by timothyallan** [erikras/redux-form#1180]
I'm using v6 a15...

According to the docs ```handleSubmit``` will ```run validation, both sync and async, and, if the form is valid, it will call this.props.onSubmit(data) with the contents of the form data.```

I've implemented the technique from this post https://github.com/yelouafi/redux-saga/issues/161#issuecomment-191312502. Now I've got an onSubmit defined that invokes a Saga. However, the issue is that the OnSubmit always gets called, even when my form is failing! The errors display as they should on the form, but my onSubmit still gets called.

Form header is  ```<form onSubmit={handleSubmit}>```

and the relevant code below

```
const validate = (values) => {
  const errors = {};
  /// bunch of error handling here
  return errors;
}
```
```
function mapDispatchToProps(dispatch) {
  return {
    dispatch,
    onSubmit: (values) =>
      new Promise((resolve, reject) => {
        dispatch(loginUser({ values, resolve, reject }));
      })
  };
}
export default (
  connect(mapStateToProps, mapDispatchToProps)(
    reduxForm({ form: 'loginForm', validate })(LoginPage)));
```

**Comment by tyrsius** [comment]
This is happening to me too, same version

**Comment by timothyallan** [comment]
Okay, I've got a working, errr, workaround.

```
import { SubmissionError } from 'redux-form/immutable';
......
function mapDispatchToProps(dispatch) {
  return {
    dispatch,
    onSubmit: (values) => {
      const validated = validate(values);

      if (Object.keys(validated).length > 0) {
        return new SubmissionError(validated);
      }

      return new Promise((resolve, reject) => {
        dispatch(loginUser({ values, resolve, reject }));
      });
    }
  };
}
```

**Comment by ooflorent** [comment]
@timothyallan That's how I usually do.

**Comment by tyrsius** [comment]
@ooflorent Why did you close this? A workaround exists, but this is still a bug, isn't it? If not, then the documentation is wrong.
