### ISSUE TITLE
Unhandled promise rejection -  SubmissionError

### ISSUE THREAD

**Issue by OKNoah** [erikras/redux-form#1181]
My code

```js
export default class LoginModal extends React.Component {
  registrationHandler (values) {
    this.props.dispatch(postUser(values))
    .catch(() => {
      throw new SubmissionError({ username: 'An error.' });
    });
  }


  render () {
    return (
      <div
        id="Login"
        className={ classes.loginContainer }
      >
        <div className={ classes.forms }>
          <div className={ classes.register }>
            <Register
              onSubmit={::this.registrationHandler}
              generateInput={::this.generateInput}
            />
          </div>
        </div>
      </div>
    );
  }
}
```

I have tried using `SubmissionError` many different ways. I have put it in my reducer like this

```js
export function postUser (user) {
  return {
    types: [USER_POST, USER_POST_SUCCESS, USER_POST_FAILURE],
    promise: (client) => client.post('/user', {
      data: user
    })
    .catch(error => {
      throw new SubmissionError({ username: 'Error!' });
    })
  };
}
```

or

```js
case USER_POST_FAILURE:
  throw new SubmissionError({ _error: error });
```

This gets the same result. I can also move the `SubmissionError` several levels up or down from the component with `redux-form` in it, but no joy.

**Comment by OKNoah** [comment]
Really struggling to understand how this works.

**Comment by erikras** [comment]
You're missing a `return`.
```js
   return this.props.dispatch(postUser(values))
// ^^^^^^
```

**Comment by OKNoah** [comment]
@erikras Thanks again!

**Comment by erikras** [comment]
We all do stupid stuff like that. I've lost count of the number of times I've forgotten to return a promise. 😄

**Comment by OKNoah** [comment]
@erikras Actually, I have never put `return` before `dispatch`. It's new to me.

**Comment by erikras** [comment]
Your action creator looked a lot like my [client middleware](https://github.com/erikras/react-redux-universal-hot-example/blob/master/src/redux/middleware/clientMiddleware.js) (which I still use almost everywhere), so I guessed it was probably returning a promise.

**Comment by OKNoah** [comment]
@erikras Indeed it is! Where would I be without react-redux-universal-hot-example?

**Comment by Rosuav** [comment]
I know I'm necro'ing, but thank you for this tracker issue - it solved one of my students' problems. Perhaps the need to return what dispatch returns should be mentioned in docs somewhere?
