### ISSUE TITLE
v6 — Problem with use in redux-saga and immutableJS

### ISSUE THREAD

**Issue by rcholic** [erikras/redux-form#1182]
I run into the following problem with the simple sync validation redux-form example in my react.js app based on react-redux
```
Uncaught (in promise) Error: Element type is invalid: expected a string 
(for built-in components) or a
 class/function (for composite components) but got: undefined.
```
*Code:*
```js
<Field name="username" component={username =>
                      <div>
                        <input type="text" {...username} placeholder="Username"/>
                        {username.touched && username.error && <span>{username.error}</span>}
                      </div>
                    }/>
```

In the custom form component (UserRegistrationForm), I have the following code:
```js
export default reduxForm({
    form: 'registrationForm',
    fields,
    validate,
})(UserRegistrationForm);
```

And in my root reducers, I mounted redux-form reducer to *form*:
```js
    form: formReducer,  // redux-form mounted at 'form'
```

So I was wondering what caused the error with the example code above. I guess the *component* part in *Field* is causing it, but I've no idea how to fix it. Any help is appreciated!

**Comment by raizyr** [comment]
Did you see this?  http://redux-form.com/5.2.5/#/faq/immutable-js  It helped me with some similar errors.

**Comment by ooflorent** [comment]
Do not define your component using an arrow function inside `component` prop. This is not supported and creates an insane amount of clumsy behaviors. Details are in the [v6.0.0-alpha.14 release notes](https://github.com/erikras/redux-form/releases/tag/v6.0.0-alpha.14). Please reopen this issue if after correctly upgrading your forms the error is still there!
