### ISSUE TITLE
v6 — Changing initialValues should update per-field dirty/pristine

### ISSUE THREAD

**Issue by hathawsh** [erikras/redux-form#1188]
I'm using redux-form 6.0.0-alpha.15. I'm enjoying using it, but there's a problem with the 'dirty' state.

In a form I'm working on, I added a visual indicator next to each field to show whether that field is currently dirty or pristine. After I submit the form and the server accepts the changes, the form's initialValues object is updated to the values I just submitted. Because the initialValues I'm passing to the form now matches the new field values, I would expect fields to become pristine, but that is not happening; the changed fields remain dirty. It turns out redux-form ignores changes to initialValues until I reinitialize or remount the form.

I could reinitialize the form, but that is not an acceptable solution because the user may have changed field values after submission and I don't want to overwrite their changes. Instead, I added a temporary workaround that computes dirty state by comparing the latest initialValues with the current values.

I looked at the cause and I see that redux-form copies initialValues to Redux state. I wonder if it would make more sense to keep initialValues in component props only and never copy it to the Redux state where it can fall out of sync with component props. Would that change conflict with anything? An alternative is to provide some kind of changeInitialValues() method, but that would be a lot less intuitive.

**Comment by ms88privat** [comment]
Maybe you could dispatch an action, which removes the dirty flag?

http://redux-form.com/6.0.0-alpha.15/docs/api/ReducerPlugin.md/

@erikras would this be the right use case for the ReducerPlugin?

PS: sideNote question: Why is the flag "anyTouched" in the Store but "dirty" is not?

**Comment by erikras** [comment]
This will be solved in the next release with an `enableReinitialize` config parameter. #1121.

> PS: sideNote question: Why is the flag "anyTouched" in the Store but "dirty" is not?

@ms88privat `dirty` is calculated from the values in the store by comparing `value` and `initial`.

**Comment by ms88privat** [comment]
@erikras Thanks. Could you please show me the code snippet for this? I can't find it.

I need this dirty flag on a different place, is there a possibility to expose your selector / computation on this?

**Comment by hathawsh** [comment]
This was solved in 6.x.
