### ISSUE TITLE
initialize action creator first parameter- formName not work in v6

### ISSUE THREAD

**Issue by sevenLee** [erikras/redux-form#1189]
redux-form: 6.0.0-alpha.13

In doc, `initialize` method: 

```js
initialize(form:String, data:Object, fields:Array<String>)
```

But in fact, when I input the first param:form, it won't send my datas correctly

my first code:
```js
@connect(
  state => ({
    themeRoot        : state.themeRoot
  }),
  { updateStyles, addTodo, initialize }
)
@reduxForm({
  form: 'ControlForm'
})
export default class Control extends Component {
  constructor(props){
    super(props);
    this.saveConfig = this.saveConfig.bind(this);
  }

  static propTypes = {
    initialize: PropTypes.func.isRequired
  }

  componentDidMount() {
    this.props.initialize('ControlForm', {
      skin: {
        general: {
          body: 123
        }
      }
    }, ['skin.general.body']);
  }

 ....
}
```
In my expected, it should send deep nest data:

```js
skin: {
    general: {
      body: 123
    }
 }
```
But the result can't get the data

![](https://cloud.githubusercontent.com/assets/1096175/16216953/a1432792-37a1-11e6-92d6-0913e25df2de.png)

when I delete first params, it runs correctly:

```js
componentDidMount() {
    this.props.initialize( {
      skin: {
        general: {
          body: 123
        }
      }
    }, ['skin.general.body']);
  }
```
![](https://cloud.githubusercontent.com/assets/1096175/16216976/e5b3c210-37a1-11e6-8408-63bac0e4be62.png)

Any one have encountered the context?

**Comment by ooflorent** [comment]
The documentation wasn't up-to-date. The actual signature is:

```js
initialize(form:String, data:Object)
```

In v6, fields are not setup at initialization but at mount-time. It means that until you render the field, it won't be loaded into the store.

**Comment by sevenLee** [comment]
Hi, @ooflorent 

But I used :`initialize(data:Object)` , it could work great

if I used `initialize(form:String, data:Object)` , it won't run correctly like above screen shot

I didn't insert any fields parameters in `initialize`

**Comment by ooflorent** [comment]
Actually I was talking about the action creator (`initialize(form: String, values: Object)`).
The `initialize` you are referring to is a bound action creator (`form` is bound).

1. If you want to initialize your form within your component, then don't provide the form name.

    ```js
    this.props.initialize(initialValues)
    ```

2. If you want to initialize your form outside your component, use the AC with the form name.

    ```js
   dispatch(initialize("myForm", initialValues))
    ```

**Comment by sevenLee** [comment]
Thanks! very clear now :)

About the initialize usage of different contexts, is there more detail AC usage description on the document in the future?

**Comment by ooflorent** [comment]
The documentation will never be good enough... It would be great if you had a _Recipes_ section with detailed use cases and resolutions. Unfortunately we don't have much time and barely enrich the documentation...
