### ISSUE TITLE
async example 

### ISSUE THREAD

**Issue by mschipperheyn** [erikras/redux-form#119]
Are there any solid examples of redux-form out there that include async validation. Having a lot of problems getting it to work (React-Native). The poor Chrome es6/es7 debugging experience doesn't help so an example would really help.

Also in relation to using actions that return (redux-)thunks

**Comment by mschipperheyn** [comment]
I just realized that the reason I'm not getting my head around may be that I expect the async function called by the asyncValidate function to return something (a successfully logged in user or a set of errors).

However, the idea is probably more that the async function that is being called to make a dispatch of these events (error, success), so that it can be fire and forget. Is this correct? If I want to return something, I should probably not use thunks and use async / await (tried that, didn't get it to work) or standard Promise approach in the async function.

If my assumption regarding thunks is correct, is there some structured way available to dispatch the validation exceptions?

Little lost here.

**Comment by erikras** [comment]
On example, albeit a little weak is [here](https://react-redux.herokuapp.com/survey). If you put `bobby@gmail.com` into the Email field, it will show an error after a second or two.

Personally, I think the better UX is to do server-side validation on submit only, but the other is included for things like choosing an available screen name (e.g. Twitter signup), where doing uniqueness validation early on in the form process is useful.

Does that help?

**Comment by mschipperheyn** [comment]
Well, it seems every example in the field of redux takes a different approach often with various degrees of indirection (e.g. bindActionCreators) . It's kind of confusing at times. For redux-form there is very little documentation, especially regarding async validation. 

I would just like for instance a complete login example that replaces the 
"// do async validation"
in the documentation, ideally with some different approaches, e.g. fire forget / return value. For instance, in the case of fire forget, you would need to respond to validation exceptions through a reducer and the connect function. 

My debugger on react-native is skipping whole blocks of code sometimes, I assume because it doesn't like some es7 features or whatever. So, it would be nice to have a good reference on this.

**Comment by mschipperheyn** [comment]
Could you explain why this is not working? I can see that the network request returns successfully.
The point of trying to return a value is to make sure that the asyncValidate method doesn't actually complete "successfully".

    	function asyncValidate(data, dispatch){
	  //if successful we will automatically end up in the parent handleSubmit
	  return new Promise((resolve,reject) => {
		const errors = {};

		dispatch(loginUser(data.username, data.password))
		.then((json) => {

		  dispatch(userActionCreators.saveUser(json.user));

		  resolve(json.errors);
		})
		.catch(err => {
		  reject(err);
		});


	  });
	}
	
	[...]
	
	export function loginUser(email, password){

	  return dispatch => {

		dispatch(login(email, password));

		// try{
		return fetch(config.urls.loginUrl,{
			method:'post',
			headers:headers,
			body:JSON.stringify({
				username:email,
				password:password
			})
		})
		.then(response => status(response,dispatch))
		.then(response => response.json())
		.then(json => {
			console.log(json);
			return json;
		})
		.catch(err => {
		  console.error(config.urls.loginUrl, err);
		  return err;
		});
	  }
	}

**Comment by erikras** [comment]
I'm not following. `loginUser()` returns a function that takes `dispatch`, but then you are calling `dispatch(loginUser())`?? Shouldn't you be dispatching an action? Do you have a redux middleware that is returning promises?

**Comment by mschipperheyn** [comment]
I'm using thunk-middleware.

So, what I'm trying to achieve is that the errors object in asyncValidate gets populated with exceptions that may return from loginUser or with a user. (The dispatch(loginUser(email,password)) is just a placeholder for an action that will perhaps create a loader animation. Let's forget about it.)

Any suggestions?

**Comment by mschipperheyn** [comment]
Ok, so I made a next version. I'm now getting data successfully returned to the LoginForm. However, when I reject the Promise, the error value on the associated field remains null. Any suggestions?

loginactions.js

	export function loginUser(email, password){

	  return dispatch => {

		return fetch(config.urls.loginUrl,{
			method:'post',
			body:JSON.stringify({
				j_username:email,
				j_password:password
			})
		})
		.then(response => status(response,dispatch))
		.then(response => response.json())
		.then(json => {
			/**
			 * json.errors object has shape
			 * json.errors = {
			 *		password: 'bad password'
			 * }
			 */
			json.errors = errors;

			return json;
		})
		.catch(err => {
		  console.log(config.urls.loginUrl, err);
		  return Promise.reject(err);
		});
	  }
	}


LoginForm.js

	function validate(data){

	  const errors = {};

	  if( !data.username || data.username.length === 0 ) {
		errors.username = getMessage('errors.required');
	  }

	  if( !data.password || data.password.length === 0 ) {
		errors.password = getMessage('errors.required');
	  }

	  return errors;
	}

	function asyncValidate(data, dispatch){
	  return new Promise((resolve,reject) => {
		const errors = {};

		let json = dispatch(loginUser(data.username, data.password))
		.then((json) => {

		  if(Object.keys(json.errors).length > 0){
			reject(json.errors);
		  }else{
			dispatch(userActionCreators.saveUser(json.user));
			resolve(errors);
		  }

		})
		.catch(err => {
		  reject(errors);
		});


	  });
	}

	@connectReduxForm({
	  form: 'login',
	  fields: ['username', 'password'],
	  validate: validate,
	  asyncValidate: asyncValidate
	})
	export default class LoginForm extends React.Component {

	  render() {
		const { fields: {username, password}, handleSubmit } = this.props;
		return (
		  <View>
			<View>
			  <View>
				<TextInput
				  {...username}
				/>
				{username.error && username.touched && <Text>{username.error}</Text>}
			  </View>
			  <View>
				<TextInput
				  secureTextEntry={true}
				  {...password}
				/>
				{password.error && password.touched && <Text style={formStyles.errorBlock}>{password.error}</Text>}
			  </View>
			</View>
		  </View>
		);
	  }
	}

**Comment by mschipperheyn** [comment]
Oh, I see that you updated the example. I see that if I add valid:false and resolve instead of reject, I do get the appropriate error message. I recommend updating the docs with this. Also, it would seem to make more sense to instead of force users to set "valid:false", to allow them to "reject" in stead of resolve. Seems more natural
