### ISSUE TITLE
Radiobuttons set field value just by tabbing over them

### ISSUE THREAD

**Issue by cgoehl** [erikras/redux-form#1190]
See example:
[https://react-redux.herokuapp.com/survey](https://react-redux.herokuapp.com/survey)

Just tab over all inputs. In the end, 'Male' will checked.

This does not happen in vanilla HTML forms. The reason might be, that the <input type="radio" value="male"/> sends the 'blur' action on loosing focus and the blur action saves the value to the form state.

**Comment by cgoehl** [comment]
**Workaround**

Disabling input.onBlur for radio-buttons and mapping input.onChange to field.onBlur seems to be a workaround. I am not sure whether it has any side-effects...

`<input 
          {... field}
          onChange={field.onBlur}
          onBlur={null}
          type='radio'
          value={value}
          name={name}
          checked={value === field.value} />`

**Comment by ooflorent** [comment]
**Proper workaround:**

```js
<input {...field} type="radio" onBlur={null} />
```
