### ISSUE TITLE
redux-form does not pass a value from material-ui AutoComplete

### ISSUE THREAD

**Issue by mayacode** [erikras/redux-form#1192]
I was googling and asking on SO. But it doesn't look like anyone has a solution.

I try to use material-ui AutoComplete component, and can achieve everything, exept retrieving real value of clicked element in AC list.

I tried to dispatch manually `redux-form/CHANGE` action with all needed data, using provided in AutoComplet method `onNewRequest`. I can see it works, can even see, that inside form object my field has desired value. But just after `redux-form/CHANGE` is triggered by me with proper values, redux-form triggers `redux-form/BLUR` with OLD value (typed by me). And in the end, the old value is sent onSubmit.

Is there any solution to make it work together?

UPDATE:

```
"react": "15.1.0",
"redux": "3.0.5",
"redux-form": "6.0.0-alpha.15",
"material-ui": "0.15.0",
```

**Comment by ooflorent** [comment]
We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question. I’m closing for this reason.

In order to manage to connect a component to Redux Form, the component must initialize its state using `value` and trigger changes using `onChange`. Material UI `AutoComplete` does not.

```js
import MaterialUIAutoComplete from "material-ui/AutoComplete"

export const AutoComplete = props => (
  <MaterialUIAutoComplete
    {...props}
    onUpdateInput={props.onChange}
    searchText={props.value}
  />
)
```

**Comment by StRibbon** [comment]
Yes I have a solution/workaround, simply use a redux action to save the autocomplete item data selected from your component then within your request, call getState() to pull the data from your store and simply modify/attach to the form body that came from redux-form.
