### ISSUE TITLE
General error and form validation

### ISSUE THREAD

**Issue by Adrien-P** [erikras/redux-form#1194]
I want to use the general error (_error) for some errors returned by my server-side API.
However, setting such _error forces the prop 'valid' to be false.
My issue is that in some cases, there is an error but that does not mean the form is invalid (and so I want to let the user be able to click on the Submit button again).
For example, let's say there is a network error (server timeout), I want my users to be able to send the same form again.
Is there any way to do what I want within redux-form?

**Comment by tyrsius** [comment]
V6 offers SubmissionError for this http://redux-form.com/6.0.0-alpha.15/docs/api/SubmissionError.md/

**Comment by gustavohenke** [comment]
@tyrsius is correct.
