### ISSUE TITLE
in V6, how to submit on enter

### ISSUE THREAD

**Issue by oallouch** [erikras/redux-form#1195]
I used to do:

```js
export function addSubmitOnEnter(props) {
  const checkKey = e => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      props.handleSubmit()
    }
  }
  const fields = props.fields;
  for (let fieldName in props.fields) {
    let field = fields[fieldName];
    field.onKeyPress = checkKey;
  }
}
```
but now I don't have the fields.
Is there a simple solution ? I'm sure there is :)

**Comment by ooflorent** [comment]
Use HTML.

```js
<form onSubmit={handleSubmit}>
  {/* Define your fields here ... */}
  <button type="submit">Send</button>
</form>
```

Then your form should submit on enter.
It doesn't matter if you're using v5 or v6.

**Comment by mrdududu** [comment]
But if the button outside form tag?

**Comment by danielrob** [comment]
@mrdududu see the remote submit example in the docs? Does that cover it for you?

**Comment by Simcsa** [comment]
The remote submit example in the docs does not cover how to submit on enter in that case. And in the example of submitting on enter in the docs, the button needs to be inside a form and to have a submit type. So how can I use remote submit on enter?
