### ISSUE TITLE
[v6.0.0-alpha.15]  FieldArray move and removeAll undefined?

### ISSUE THREAD

**Issue by tnrich** [erikras/redux-form#1197]
I'm not sure if maybe something isn't updating properly, but here is what my "inserts" array looks like:

![image](https://cloud.githubusercontent.com/assets/2730609/16244387/90f70a66-37b0-11e6-878f-607a67efb3b6.png)

This is after running `npm i -S redux-form@v6.0.0-alpha`

Is anyone else seeing this issue with alpha.15?

Thanks!

**Comment by alurim** [comment]
@tnrich, yep seeing this as well!

**Comment by erikras** [comment]
Confirmed. This is a bug. The following screenshot is from the published [Field Arrays example](http://redux-form.com/6.0.0-alpha.15/examples/fieldArrays/).
![redux form 2016-06-21 17-51-04](https://cloud.githubusercontent.com/assets/4396759/16247652/c4e0ea5e-37d8-11e6-945a-d7b954b581da.jpg)

Thanks, @tnrich!

**Comment by erikras** [comment]
This has been fixed. I will comment again here when the fix has been released.

**Comment by erikras** [comment]
Published in [`v6.0.0-rc.1`](https://github.com/erikras/redux-form/releases/tag/v6.0.0-rc.1).
