### ISSUE TITLE
Export actions on top level

### ISSUE THREAD

**Issue by johanneslumpe** [erikras/redux-form#12]
I think it would be useful, if we exported all actions on the top level object.

The use cases for this are for example:

- triggering a change to a form outside of a component (for example when we need to prefil it with data we do not have at reducer-init time)
- resetting a form (as mentioned in #11)

In code:
```javascript
import { change, reset } from 'redux-form';

// change a form field or initially populate it prior to rendering
change('myForm', 'myField', 'whoop');

// reset a form
reset('myForm');
```

Thoughts?

**Comment by erikras** [comment]
How's that for response time? :smile:

**Comment by johanneslumpe** [comment]
:+1: amazing!
