### ISSUE TITLE
how to disable field in redux-form

### ISSUE THREAD

**Issue by geminiyellow** [erikras/redux-form#1205]
hi @erikras ,

could you tell me how to disable field in redux-form?

there is not `disabled` attr in form, if i want to skip one field's validate , or remove it in submit data, 
i have to reset the `fields` and `validate`. hope you can help me .

**Comment by ooflorent** [comment]
Pass a prop to your form, then read it from `validate`:

```js
<MyForm disabledFields={["foo", "bar"]} />
        ^^^^^^^^^^^^^
  This in Redux Form related!
```

```js
function validate(values, props) {
  console.log(props.disabledFields) // foo, bar
}
```

**Comment by geminiyellow** [comment]
@ooflorent thank you, i can not found the `disabledFields` in docs, could you tell me where is it?

**Comment by ooflorent** [comment]
Sorry I made a typo and my message wasn't clear! 

There is no prop do do that. However, `props` are passed to `validate` so you can use them to mark some fields as disabled. In my example, I decided to create a prop named `disabledFields` to hold this information. It's up to you to name this property and instrument `validate`.
