### ISSUE TITLE
Documentation out of date? resetForm() should be reset()?

### ISSUE THREAD

**Issue by OKNoah** [erikras/redux-form#1208]
Two issues here, see comments.

```
submitMyForm(data) {
  const {createRecord, resetForm} = this.props; // <-- should be reset, not resetForm?
  return createRecord(data).then(() => {
    resetForm();
    // do other success stuff
  });
}

render() {
  const {handleSubmit, submitMyForm} = this.props; // <-- submitMyForm is on this.props?
  return (
    <form onSubmit={handleSubmit(submitMyForm.bind(this))}>
      // inputs
    </form>
  );
}
```

Seems like `submitMyForm` should from this `this`, not `this.props`. Unless this is in another component and being passed in as a prop. But then how does it get `resetForm`?

Here is the page: http://redux-form.com/6.0.0-alpha.13/docs/faq/HowToClear.md/

**Comment by erikras** [comment]
Thanks, @OKNoah! You are correct on all counts.
