### ISSUE TITLE
[V6] In contrast to the docs, values object not passed to form props

### ISSUE THREAD

**Issue by halayli** [erikras/redux-form#1209]
a reduxForm wrapped component isn't passed the current values object.

Looked at the code, it seems to  be removed from the passable props:

https://github.com/erikras/redux-form/blob/v6.0.0-alpha.15/src/reduxForm.js#L274

**Comment by ooflorent** [comment]
You're correct, the documentation is not up to date.
I'll be happy to review any PR fixing this!

**Comment by halayli** [comment]
sounds good! Will submit a PR over the weekend.

**Comment by erikras** [comment]
What's the problem here? The current values are _not_ passed. Does it say in the docs somewhere that they are?

**Comment by halayli** [comment]
@erikras in the docs under instance api, there's a values property that needs to be removed since this has gotten replaced by formValueSelector.

http://redux-form.com/6.0.0-rc.1/docs/api/ReduxForm.md/

**Comment by erikras** [comment]
I think you're confusing `props` with instance variables/methods. The docs are correct. What they mean is that you can something like:

```js
render() {
  return (
    <div>
      <MyDecoratedForm ref="theForm"/>
      <button
        type="button"
        onClick={() => console.log(this.refs.theForm.values)}>
        Log Values
      </button>
    </div>
  )
}
```

**Comment by halayli** [comment]
ah! my bad. "on an instance" vs "in an instance". subtle one. I'll go ahead and close. :)
