### ISSUE TITLE
"npm test" on windows fails to run tests - suggested fix.

### ISSUE THREAD

**Issue by rluiten** [erikras/redux-form#1212]
I am on Windows 10 64 bit.
node --version
v6.2.2
npm --version
3.9.5

When i run `npm test` I get error.
`Error: cannot resolve path (or pattern) ''src/**/__tests__/*''`

Notice the extra quotes shell parsing being less than helpfull I believe.

Currently the npm script is as follows will not find the path on windows.
`"test": "mocha --compilers js:babel-register --recursive --recursive 'src/**/__tests__/*' --require src/__tests__/setup.js"`

If I convert the single quotes to escaped double quotes it runs fine.
`"test": "mocha --compilers js:babel-register --recursive --recursive \"src/**/__tests__/*\" --require src/__tests__/setup.js"`

I believe using escaped double quotes will still work fine on on other platforms so may be worth switching to ?

Cheers, Robin

**Comment by ooflorent** [comment]
Thanks for the report! Could submit a simple PR to fix this?

**Comment by rluiten** [comment]
Created.
