### ISSUE TITLE
[V6 alpha-15] Fields .insert() action not working?

### ISSUE THREAD

**Issue by tnrich** [erikras/redux-form#1215]
Hey there, 

I'm calling `fields.insert(1,{some:data})` to no avail... 

It appears that the redux form action is getting triggered correctly, but it doesn't seem to be updating the store:

![image](https://cloud.githubusercontent.com/assets/2730609/16351173/9e8d85f0-3a18-11e6-97ad-b999b92a138e.png)

I feel like I may have filed something similar to this before, so I hope this isn't a duplicate. (I wasn't able to find any identical issue after a small search). Thanks!

**Comment by erikras** [comment]
From your screenshot, it looks like your index is an object, not an integer, and your payload is `1`. It looks like you've got the parameters backwards.

**Comment by tnrich** [comment]
Aha! It seemed like it must have been user error :)

**Comment by tnrich** [comment]
Thanks @erikras
