### ISSUE TITLE
has-error class when validation

### ISSUE THREAD

**Issue by chienvuhoang** [erikras/redux-form#1216]
Hi all,
I'm using react-form in my project, but i can't see class 'has-error' append when form validate like example of React-form below:

<img width="856" alt="screen shot 2016-06-25 at 5 21 44 pm" src="https://cloud.githubusercontent.com/assets/19221658/16356204/85079868-3afa-11e6-85c9-d960f31605f9.png">

My form just display error message only and not append any class error. Please help me for this issue.
I'm missing something config?

**Comment by ooflorent** [comment]
The code on the example pages does not include the presentational logic.
You should read the complete example source:

https://github.com/erikras/redux-form/blob/gh-pages/5.2.5/src/examples/SubmitValidationForm.js

**Comment by chienvuhoang** [comment]
Thanks @ooflorent :)
