### ISSUE TITLE
Normalizing Floats

### ISSUE THREAD

**Issue by dpwrussell** [erikras/redux-form#1218]
Hi,

I've had a read of many open issues here and it seems that having non-string form values is OK! I have some form values that are floating point numbers. This works fine for initial display but I am struggling with how to handle this for input.

The first thing I did was to make a normalizer (using v5 at the moment).

```js
  form: formReducer.normalize({
    SmallMolecule: {
      molecular_mass: value => value && parseFloat(value)
    }
  })
```

This ensures that the value always remains a float so that `dirty` is appropriate should `123.45` become `123.46` then back to `123.45`  for example.

I was pleased with that, but then I hit a roadblock. What if there are no decimal places? Say, `123`. It becomes impossible to enter the decimal point in the field because when you type it, normalize immediately removes it.

What is the recommended workaround for this? Am I simply forced to using strings for float input fields?

I am wondering if it might be nice to have a value and a displayValue. Nearly always displayValue would simply reference value, but when needed, it could be used to get around situations like this (normalize would set the displayValue to `123.` and the value to `123`. displayValues could then be reset at the users discretion (e.g. on submit). This isn't a well thought out idea so there might be a huge flaw for internal reasons that I am not familiar with.

Finally, great work on redux-forms, other than this problem I am finding it the perfect way to do forms in React+Redux. Before I was always frustrated that form libraries would want to handle both state and rendering which never made sense to me.

Cheers

**Comment by erikras** [comment]
That is pretty funny. Isn't programming fun? Seems like you'd have the same problem with an empty string going to `NaN`, right?

You will _either_ have to use strings as your input values, _or_ special case all the weird edge cases in your normalizer. Something like this (untested):

```js
value =>
  !value || !value.length || value[value.length - 1] === '.' ?
    value : parseFloat(value)
```

**Comment by dpwrussell** [comment]
Empty string going to NaN isn't such a big problem as the initialValue would have been undefined in my case so that's easy to special case and it doesn't have the same problem with data entry.

I had considered the special casing of course, but in the end it doesn't really buy you anything over strings because on form submission you still have to process the float values as they could be strings (if the field was blurred when at `123.`. Also, if you have any fields which interrelate, it's no longer possible to rely on the type of the float. e.g. if you have a validator that checks if x > y. Now that validator would also have to handle strings.

displayValue idea was no good?

**Comment by ooflorent** [comment]
In my vision, normalization shouldn't be used to accommodate the display of any values but to coerce complex values into the store. So, what does this imply?

1. Store your values as floats
2. Implement value constraints using the normalizer (but keep floats)
3. Implement the mask at the component level, not the normalizer

**Comment by dpwrussell** [comment]
@ooflorent I completely agree with this usage pattern, this is actually what I wanted; To be able to coerce values into the store.

However, I don't think there is a mechanism in redux-forms right now that can cope with the example I laid out above. Either you only coerce when the value is valid or not in some intermediate state (and otherwise leave it as a string in the store) or you use a string. I would welcome an example of how to properly use normalisation in that use case.

Cheers

**Comment by ooflorent** [comment]
I think the only missing part is a masked input component. Here is a dummy component to achieve this. It bypasses Redux Form normalizer because in this case it would be overkill.

```js
class MaskedInput extends Component {
  constructor(props) {
    super()

    this.handleBlur = this.handleBlur.bind(this)    
    this.handleChange = this.handleChange.bind(this)    
    this.state = {
      value: props.value,
    }
  }

  componentWillReceiveProps(nextProps) {
    this.setState({
      value: nextProps.value,
    })
  }

  handleBlur() {
    if (this.props.onBlur) {
      // Swallow the event to prevent Redux Form from
      // extracting the form value
      this.props.onBlur()
    }
  }

  handleChange(event) {
    const value = event.target.value

    // Update the internal state to trigger a re-render
    // using the formatted value
    this.setState({value})

    if (this.props.onChange) {
      // Notify the normalized value
      this.props.onChange(
        this.props.normalize(value)
      )
    }
  }

  render() {
    return (
      <input
        {...this.props}
        value={this.props.format(this.state.value)}
        onBlur={this.handleBlur}
        onChange={this.handleChange}
      />
    )
  }
}

MaskedInput.defaultProps = {
  format: x => x,
  normalize: x => x,
}

MaskedInput.propTypes = {
  format: PropTypes.func.isRequired,
  normalize: PropTypes.func.isRequired,
  value: PropTypes.any,
  onBlur: PropTypes.func,
  onChange: PropTypes.func,
}
```

**Comment by funwithtriangles** [comment]
I went with the normalizing solution. Keeping the whole thing as a string and dealing with the edge cases:

```javascript
export const onlyDecimal = (value) => {
  value = value
    .replace(/[^0-9.]/g, '') // Remove all chars except numbers and .
    .replace(/^0+/, '') // Remove any leading 0s

  // Create an array with sections split by .
  const sections = value.split('.')

  // If numbers exist after first .
  if (sections[1]) {
    // Join first two sections and truncate end section to length 2
    return sections[0] + '.' + sections[1].slice(0, 2)
  // If original value had a decimal place at the end, add it back
  } else if (value.indexOf('.') !== -1) {
    return sections[0] + '.'
  // Otherwise, return original value
  } else {
    return value
  }
}
```

And here are all my passing tests, just so you know!

```javascript
describe('(Normalizer) onlyDecimal', () => {
  it('Returns a string with only numbers', () => {
    let expected = '123456'
    let actual = n.onlyDecimal('123456')
    expect(actual).to.equal(expected)

    expected = '1234'
    actual = n.onlyDecimal('1234a')
    expect(actual).to.equal(expected)

    expected = '1234'
    actual = n.onlyDecimal('1!2!3!4')
    expect(actual).to.equal(expected)

    expected = ''
    actual = n.onlyDecimal('ab')
    expect(actual).to.equal(expected)
  })

  it('Allows for one decimal symbol', () => {
    let expected = '10.'
    let actual = n.onlyDecimal('10.')
    expect(actual).to.equal(expected)

    expected = '10.0'
    actual = n.onlyDecimal('10.0')
    expect(actual).to.equal(expected)

    expected = '1234.56'
    actual = n.onlyDecimal('1234.56')
    expect(actual).to.equal(expected)

    expected = '1234.56'
    actual = n.onlyDecimal('1234.56.12')
    expect(actual).to.equal(expected)

    expected = '1.1'
    actual = n.onlyDecimal('1.1.1.1.1.1')
    expect(actual).to.equal(expected)
  })

  it('Truncates to 2 decimal places', () => {
    let expected = '10.00'
    let actual = n.onlyDecimal('10.000')
    expect(actual).to.equal(expected)

    expected = '10.12'
    actual = n.onlyDecimal('10.12345')
    expect(actual).to.equal(expected)

    expected = '10.12'
    actual = n.onlyDecimal('10.12345.00.102.123')
    expect(actual).to.equal(expected)
  })

  it('Removes leading zeros', () => {
    let expected = '123456'
    let actual = n.onlyDecimal('0123456')
    expect(actual).to.equal(expected)

    expected = '123456'
    actual = n.onlyDecimal('00000123456')
    expect(actual).to.equal(expected)

    expected = ''
    actual = n.onlyDecimal('0')
    expect(actual).to.equal(expected)
  })
})
```

**Comment by wesley6j** [comment]
I used another solution:
In a normal text input, compare past value and current value in `handleChange`. If a comma is added at the end of the string, skip sending `onChange` event and edit input value manually (have a state value that is passed as a prop to input). The rest are handled by `format` and `parse` props.
