### ISSUE TITLE
how to achieve this scrolling effect with wizard form? (question) 

### ISSUE THREAD

**Issue by jasan-s** [erikras/redux-form#1220]
![wizard-form](https://cloud.githubusercontent.com/assets/13863953/16371896/3f809b3c-3bfe-11e6-8b32-4c61dfcc7389.gif)

**Comment by ooflorent** [comment]
Don't do a wizard form. Implement your form logic using React's state, then wire it to Redux Form.

**Comment by jasan-s** [comment]
@ooflorent  would you mind elaborating.
