### ISSUE TITLE
How to access redux-form state in other reducer or dispatch a form field's onChange action from other reducer

### ISSUE THREAD

**Issue by shakalakatechie** [erikras/redux-form#1223]
Please help me with any example code for this scenario.

I have an action logic in my other reducer that needs to update my form state by either directly modifying the full state or dispatch form field's onChange action.

**Comment by erikras** [comment]
All of `redux-form`'s action creators [are exported](http://redux-form.com/5.2.5/#/api/action-creators?_k=fuhteq), so you may dispatch a change event from anywhere you'd like.

**Comment by shakalakatechie** [comment]
Thanks for your reply. Could you please help me understand how I can get access to dispatch() in my reducer.

**Comment by ooflorent** [comment]
In redux, you don't call `dispatch` from your reducer but from your components (or your action creators if you use the thunk middleware). You could also use `redux-saga` to hook on Redux Form and create complex workflow.
