### ISSUE TITLE
Handle async submission.

### ISSUE THREAD

**Issue by myyellowshoe** [erikras/redux-form#1228]
I have a form that has no submit button. I'd like to be able to edit inputs, watch for passed validation and then submit the form to a function (to handle sending it to a server) after the onChange event?

What would be the recommended way to go about something like this?

Thanks!

**Comment by tnrich** [comment]
v5 or v6?

**Comment by ooflorent** [comment]
There a plenty ways of submitting the value on change:

1. **Simple solution: drop Redux Form!** Redux Form is not design for this use case. It is relatively easy to implement a form system is plain React.
2. **Brute-force.** Wrap each `onChange` listener and try to submit is there is no error.
3. **Saga.** Redux Saga is really powerful to hook on a form. You could easily watch for modifications and submit from the saga.

**Comment by myyellowshoe** [comment]
Yeah I think I'll pass on redux-form for in this case. I'm diving into using redux more so this has been more of a test for learning more than anything. Was diving into brute force stuff yesterday but just felt forced and not built for this case.

Thanks gents!
