### ISSUE TITLE
Slow performance on huge form

### ISSUE THREAD

**Issue by vincentfretin** [erikras/redux-form#123]
I have a real performance issue with a form (10 to 30 fields) that do a really slow rerender on every key press. (without redux-devtools).
Like I explained on https://github.com/rackt/redux/issues/691#issuecomment-147069319
I use a custom shouldComponentUpdate method to fix the issue. The issue being that all functions on the field prop ('onChange', 'onBlur', 'onFocus', 'onUpdate', 'handleChange', 'handleBlur', 'handleFocus') are actually different on each rerender an so the standard shouldComponentUpdate that do a simple shallowEqual returns always True and then React call the render method on every field.
I don't really know it there is something we can do in redux-form to avoid recreating the functions...
any idea?

**Comment by gaearon** [comment]
I think `ReduxForm` should cache [these functions](https://github.com/erikras/redux-form/blob/e186c35e78ab7dbe912c147f748eced4bd815606/src/createReduxForm.js#L226-L240) by the field name instead of creating them in `render`.
You can use [`ReactStateSetters`](https://github.com/facebook/react/blob/master/src/renderers/shared/reconciler/ReactStateSetters.js) as an inspiration for such a cache.

**Comment by ooflorent** [comment]
This is really an issue. Having 3 fields literally freezes the app.

**Comment by erikras** [comment]
This is one of my top priorities.

**Comment by erikras** [comment]
In v2.2, the event handlers are all cached, so they will only ever be created if the props they depend on change (which is unlikely for the lifetime of your form). Can you see if this improves your situation any?

The redux-form HOC _must_ make your form re-render on every input, but perhaps your individual field components could only re-render if their values change.

**Comment by vincentfretin** [comment]
I'm at conferences this week. I will test this next week. Thanks.

**Comment by ooflorent** [comment]
Perfs are now better. Thanks :+1:

**Comment by insin** [comment]
I'm using a shallow equals comparison on the object redux-form provides for each field.

Testing with 2.2.4, `onDrag` is still different each render, e.g. changing the Origin field in the example below:

![redux-form-2 2 4-ondrag](https://cloud.githubusercontent.com/assets/226692/10480878/cbe2127c-7264-11e5-81d5-281ca2122b11.png)

**Comment by erikras** [comment]
Hmm.. `onDrag` and `field` both change with the value, but I guess I should make the caching mechanism smarter to not change _every_ `onDrag` and `field` with each render, only the ones where the value has changed. Thanks for this, @insin.

**Comment by vincentfretin** [comment]
Tested with 2.4.5, all functions are good except for onDrag that change every time there is a render.

**Comment by erikras** [comment]
This problem should go away entirely in `v3.0.0-beta-1`. It was one of the major goals of the redesign.

**Comment by erikras** [comment]
[`v3.0.0-beta-1` is out](https://github.com/erikras/redux-form/releases/tag/v3.0.0-beta-1).

**Comment by jhabdas** [comment]
On a related note, I was able to achieve acceptable performance on a complex form with all controls managed using Redux. See the following issue for more: https://github.com/rackt/react-redux/issues/123#issuecomment-174326027
