### ISSUE TITLE
Get input values without formValueSelector() in typescript and react ES6 components

### ISSUE THREAD

**Issue by tommy-dev** [erikras/redux-form#1230]
Hi, this might be a stupid question. I managed to use `formValueSelector()` to get each input value in typescript and ES6 react component but how to I get the values without it? 

2 screenshots below best explains what I mean. Thank you in advance.

![image](https://cloud.githubusercontent.com/assets/13111256/16402886/6d7c1dd2-3d33-11e6-88f1-1d69469669a6.png)

![image](https://cloud.githubusercontent.com/assets/13111256/16402908/aef80b7c-3d33-11e6-99b3-7738bc3603d2.png)

**Comment by tommy-dev** [comment]
To clarify  your documentation seems to suggest there is a way to submit input values without formValueSelector() or have I interpreted this all wrong?

![image](https://cloud.githubusercontent.com/assets/13111256/16403513/55e6467e-3d39-11e6-953c-760b221ac6f5.png)

**Comment by erikras** [comment]
The `onSubmit` function you give to your decorated form component (or give to `this.props.handleSubmit`) will be passed the values when the form is submitted.
