### ISSUE TITLE
State from other form

### ISSUE THREAD

**Issue by L-L-B** [erikras/redux-form#1232]
I'm on version 5.2.5.

I'm new to using this so this is probably a stupid question, but I'm not sure how to get part of a forms state to another forms props.

I have a generic component (address finder) that will be used system wide to provide data to many different forms, it performs an async action and stores the results of that action in its own state.

I have another form in which I want some part of the state from the generic component to populate some of the fields on this form.

What would be the best approach to this?

**Comment by ooflorent** [comment]
This is a usage question, and we encourage you to ask it on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

This is the only way to ensure the same question doesn’t get asked many times in a row, and that folks who have the same question in the future will be able to find it.

I’m closing for these reasons.
