### ISSUE TITLE
[v6.0.0-alpha.15] Field type="number" strange behavior with float value

### ISSUE THREAD

**Issue by turboza** [erikras/redux-form#1236]
We can reproduce this from your example in v6.0.0-alpha.15
http://redux-form.com/6.0.0-alpha.15/examples/syncValidation/

Check the Age field.
- Type any float with 0 as a decimal, ex. `1.02`, it will remove `.0`   
   So no way we can type `1.02` or `1.203`
- Type `-` or `+` will clear the fields.

**Comment by erikras** [comment]
This is a consequence of #1100 and was discussed at length on #1218.

I'm not sure what correct behavior is. The HTML5 arrows on the `type="number"` fields seem to favor integers, so it seems like if you need floats, you might need to use `type="text"`.
