### ISSUE TITLE
Submitting value is always false 

### ISSUE THREAD

**Issue by DSoe** [erikras/redux-form#1238]
Hello, 

I am not sure what I did wrong, but the submitting value is always false in my case. Since the submitting value is always false, during the submit, the Register button is never disabled. I am using the redux-thunk middleware, and I have the followings:

```js
handleFormSubmit(formProps) {
    console.log("signing up user");
    this.props.registerUser(this.props.id, this.props.email, formProps.firstName, formProps.lastName, formProps.password);
}


render () {
    const { handleSubmit, fields: { email, firstName, lastName, password, passwordConfirm }, t , submitting} = this.props;
<form onSubmit={handleSubmit(this.handleFormSubmit.bind(this))}>
//
...
   <button action="submit"  disabled={submitting}>{t('content.register')}</button>
...
//
</form>
  }

In my action creator,

export function registerUser(id, email, givenName, surName, password) {
   return function(dispatch) {
    return dispatch(updateUserPersonalData(id,email,givenName, surName)
    ).then(() => {
    dispatch(sendMail('confirmation-email')),
    browserHistory.push('/profiles?email='+email);
  })
}
}

export function updateUserPersonalData(id, email, givenName, surName) {
  return function(dispatch) {
    let jsonData = {
      "primaryEmailAddress" : email,
      "givenName" : givenName,
      "surname" :  surName,
      "displayName" : givenName + " " +  surName
    }

    let url = `${root_api_url}/v1/updateuser?id=${id}&info=ldapInfo`;
    return axios.put(url, jsonData)
    .then(response => {
      dispatch({
            type: UPDATE_USER_DATA,
            payload: JSON.parse(response.data)
            });

    })
  }
}
```

Thank you

**Comment by erikras** [comment]
The `submitting` flag only works if your `onSubmit` returns a Promise, so that `redux-form` can track when it starts and ends.

**Comment by enkay** [comment]
I'm returning a Promise on `onSubmit` but `submitting`is still always false.
I'm using `redux-thunk` middleware and I return `fetch` from the action like in the example found here: http://redux.js.org/docs/advanced/AsyncActions.html.
Do you have any idea what else could be going on?

**Comment by cheesemacfly** [comment]
@erikras I found that `submitting` is `false` even if you use a promise for the `onSubmit` props if only the sync validation kicks in and return a non-empty errors object. Is that the expected behavior?

**Comment by RamonBeast** [comment]
I just noticed the same behavior, if it is expected, what would be the right way to have a disable button when the submitting action is in progress?

**Comment by stevenmusumeche** [comment]
This is still a problem.

**Comment by cheesemacfly** [comment]
@RamonBeast I created a state property in my component called `canSumbit` that I set appropriately depending on conditions to "solve" the problem. Not ideal but it removes this blocker.

**Comment by gustavohenke** [comment]
Can anyone create a working demo using JSFiddle, Webpackbin, Codepen, whatever?
It's gonna be easier to see the actual problem.

**Comment by touqeerkhan11** [comment]
Guys why dont you just pass the resolve around and use it when you are done with async stuff?
So for example if you are using axios in your thunk
```
handleSubmit(values) {
    return new Promise(resolve => {
        this.props.myThunkWhereIsCallAsync(values, resolve);
    })
}
```
and then in the thunk you can resolve the promise to turn submitting to false just like that!

**Comment by rullyramanda** [comment]
What if i'm using redux-saga not redux-thunk?

**Comment by carmouche** [comment]
I was able to solve this by using the redux form action creators `startSubmit()` and `stopSubmit()` provided here: http://redux-form.com/6.7.0/docs/api/ActionCreators.md/.  I used the redux `matchDispatchToProps` to create a function that can explicitly dispatch an action to toggle the `submitting` prop passed by redux-form.

In my redux connected parent component I did:
```
import {startSubmit, stopSubmit} from 'redux-form';
... // other imports

class FormParentComponent extends Component {
    handleSubmit(e) {
        e.preventDefault();
        this.props.setSubmittingState('reduxFormInstanceLabel', true);
        this.props.actions.submitForm()
            .then((response) => {
                this.props.setSubmittingState('reduxFormInstanceLabel', false);
                // do other things after submitting is finished
            });
    }
    render() {
        return <ReduxFormComponent handleSubmit={this.handleSubmit.bind(this)} />
    }
}

mapStateToProps() {
    ...
}

function mapDispatchToProps(dispatch) {
    return {
        actions: bindActionCreators(Actions, dispatch),
        setSubmittingState: (form, isSubmitting) => {
            if (isSubmitting === true) {
                dispatch(startSubmit(form))
            } else if (isSubmitting === false) {
                dispatch(stopSubmit(form))
            }
        }
    };
}

export default connect(
    mapStateToProps,
    mapDispatchToProps
)(FormParentComponent);
```

I don't think it is the most elegant or best solution, but it worked for me and might help someone.

**Comment by agm1984** [comment]
Here is what I did, and it works perfect so far:

```
class Something extends Component {
    constructor(props) {
        super(props)
        this.state = { busy: false }
    }

    handleFormSubmit({ field1, field2 }) {
        this.setState({ busy: true })

        // doing work
        // ok done:

        this.setState({ busy: false })
    }

    render() {
        // inside form:
        <button action="submit" disabled={this.state.busy}>
            {(this.state.busy) ? 'Please wait...' : 'Submit'}
        </button>
    }
}
```

**Comment by codrex** [comment]
I don't really know what the cause is, but I feel that the submitting props only works in a functional base form component.

**Comment by kopax** [comment]
@agm1984 
perfect if `doing work` is not asynchrone task.

I am facing the same issue and I am using redux-saga. I can't pass a Promise. Anybody else have  different purposition?

**Comment by thfrei** [comment]
I am using redux-saga as well. Ended up using a variable in redux-state and pass it to the submit button as prop. When clicking the submit-button, action to toggle isSubmitting is dispatched, thus button gets disabled. At the end of my submit*()-saga the action is dispatched again, enabling the button for further usage.

```
    <Button
      type="button"
      onClick={() => {
        dispatch(actions.toggleSubmitting());
        dispatch(submit(FORM_NAME));
      }}
      disabled={disabled || isSubmitting}
      style={{float: 'left'}}
    >
      Save
    </Button>
```

Hint: Props come via selectors, so I composed my form component. Maybe there is a more cleaner solution however.
```
export default InspectionFormForFeatureGroup = compose(
  connect(
    (state, props) => ({
      form: FORM_NAME,
      onSubmit: submitHandlerWValidation(state, props),
      validate: connectedValidate(state, props),
    })),
    connect(createStructuredSelector({
      isSubmitting: selectors.isSubmitting(),
    })),
    reduxForm({}) // https://github.com/erikras/redux-form/issues/3083
  )(InspectionFormForFeatureGroup);
```
(this is composed, since we are using props on the Component as form-properties)

selector
```
export const isSubmitting = () => (state) => state.getIn(['qm', 'submitting']);
```

**Comment by ashokdey** [comment]
I am using **redux-saga** and I solved this ```submitting``` issue by manually dispatching the **redux-form** actions. 

**Also you can see the source code [here](https://github.com/ashokdey/blog-saga)**

**Code of LoginForm component**

```javascript

const LoginForm = (props) => {
  // getting handleSbmit and submitting which are received as props
  const {handleSubmit, submitting } = props;
  
  return (
    <div>
      <Grid centered>
        <Form onSubmit={handleSubmit} loading={submitting}>
          <Field
            component={CustomInput} name="username"
            type="text" placeholder="Your username"
            label="Username"
          />
          <Field
            component={CustomInput} name="password" 
            type="password" placeholder="minimum 5 chars long"
            label="Password"
          />
          <Button style={{marginTop: '1em'}} primary type='submit'>Login</Button>
        </Form>
      </Grid>
      <Grid centered>
        <div style={{paddingTop: '2em'}}>
          New Here? <Link to="/register"> Register Me </Link>      
        </div>
      </Grid>
    </div>
  );
}

export default reduxForm({
  form: 'LoginForm'
})(LoginForm);
```

**Code where LoginForm is rendered**
Here inside your custom submit function, dispatch the ```startSubmit``` from ```redux-form```

```javascript
import { loginUser } from './actions';
// importing startSubmit from redux-form
import { SubmissionError, startSubmit } from 'redux-form';
import LoginForm from '../../../components/LoginForm';

class Login extends Component {
  constructor(props){
    super(props);
    this.handleSubmit = this.handleSubmit.bind(this);
  }

  handleSubmit({ username = '', password = '' }) {
    // dispatch startSubmit when your form is submitted
    this.props.startSubmit('LoginForm');
    const error = {};
    let isError = false;

    if (username.trim() === '' || username.trim().length < 5) {
      error.username = 'Required and minimum 5 chars';
      isError = true;
    }

    if (password.trim() === '' || password.trim().length < 5) {
      error.password = 'Required and minimum 5 chars';
      isError = true;
    }

    if (isError) {
      throw new SubmissionError(error);
    } else {
      this.props.loginUser({ username, password });
    }
  }

  render() {
    return (
      <LoginForm onSubmit={this.handleSubmit} />
    );
  }
}
// mapping dispatch to props 
export default connect(null, { loginUser, startSubmit })(Login);
```

**Code for your saga**
```javascript
// at the top, import the stopSubmit action from redux-form
import { stopSubmit } from 'redux-form';

.
.
.
.

// inside the handle login generator
function* handleLogin(action) {
  try {
    const { data } = yield(call(loginUser, action.payload));
    const response = data;
  
    localStorage.setItem('user', `${response.data.token}`);
    yield put(loginUserSuccess(response.data.token));
    yield put(stopSubmit('LoginForm'));
  } catch (error) {
    //get response from server 
    const { response } = error;
    const message = response.data.message;
    yield put(loginUserFailed(message));
    yield put(stopSubmit('LoginForm'));
  }
}

```

If you find it helpful, **star** my repo. 
Suggestions and improvements ? open an issue [here](https://github.com/ashokdey/blog-saga/issues)

**Comment by MrDesjardins** [comment]
The issue of this thread is a limitation that surprised me at first. I was expecting a library called `Redux-Form` to be fully compatible with `Redux` lifecycle which works with the help of middleware more than executing saving directly into a component. 

A potential modification of the library could be to add in the Redux Store of the form "isSubmitting" to true/false. It can turn to `true` when submitting the form and have to call a specific action turn to turn it back to `false`.

**Comment by MrDesjardins** [comment]
The implementation of my solution of my earlier comment is already in place.

If you have a middleware doing asynchronous saving what you need to do:

1- Import
```import { stopSubmit, startSubmit } from "redux-form";``` 

2- Before doing your asynchronous (Ajax) calls the action to start submitting:
``` next(startSubmit(FORM_NAME));```
In my case, `next` is what dispatch to the next middleware and end up being handled by reducers.

3- When the asynchronous work is done (success or reject response), call the stop action:
`next(stopSubmit(FORM_NAME));`

**Comment by arielgk** [comment]
This works for me: 


ajaxStatus actions

```
export function beginAjaxCall() {
  return {type: actiontypes.BEGIN_AJAX_CALL};
}

export function ajaxCallError() {
  return {type: actiontypes.AJAX_CALL_ERROR};
}
```

 ajaxStatus reducer:
```
function actionTypeEndsInSuccess(type) {
    return type.substring(type.length - 8) === '_SUCCESS';

}

export default function ajaxStatusReducer(state = initialState.ajaxCallInProgress, action) {
    if (action.type === actiontypes.BEGIN_AJAX_CALL) {
        return state + 1;
    } else if (action.type === actiontypes.AJAX_CALL_ERROR || actionTypeEndsInSuccess(action.type)) {
        return state  -1;
    }
    return state;
}
```

in the send method I call beginAjaxCall before the ajax call, and dispatch a action ended on _SUCCESS on the response

```
export const sendForm = (data) => {
    return (dispatch,getState) => {
        dispatch(beginAjaxCall())
    
        axios.post()
            .then(function (response) {
                    dispatch({type: types.SUBMIT_FORM_SUCCESS, success: 1});
            })
            .catch(function (error) {
                    dispatch(ajaxCallError())
            });
    }
}
```
then I just add the submit button component

```
<RemoteSubmitButton disabled={ajaxCallInProgress !== 0}/>


```

(taken from Cory House Redux Course)
