### ISSUE TITLE
Radio button example

### ISSUE THREAD

**Issue by ekosz** [erikras/redux-form#124]
Hey there,

I'm trying to figure out how to use this library with a form that has radio buttons. I'm noticing there's no examples in this repository or the react-redux-universal-hot-example repo. 

An examples folder that has examples for text fields, radio buttons, checkboxes, and selects would be really really useful to work off of.

Thanks!

**Comment by erikras** [comment]
Good idea. I'll come up with one.

**Comment by jozan** [comment]
I'm also looking some examples how to use select and checkboxes.

**Comment by erikras** [comment]
The [Widgets page](https://react-redux.herokuapp.com/widgets) uses a select.

**Comment by erikras** [comment]
Radio buttons and a checkbox can be seen working [here](https://react-redux.herokuapp.com/survey).

**Comment by Fedcomp** [comment]
Is there any working example where one of radio buttons is default? cannot make it work with initialValues.

**Comment by mdgbayly** [comment]
@Fedcomp 

I've also been struggling to get radio buttons to work with initialValues.

There seems to be some kind of collision going on if you include code like in the forms example:

<input type="radio" {...sex} value="male" checked={sex.value === 'male'}/>

The inclusion of the {...sex} spread attribute seems to be conflicting with the checked prop (as each field has a checked prop too which is initially undefined.

To work around it I'm trying to add the redux-form attributes i'm interested in explicitly

e.g.

<input type="radio" value="male" onChange={sex.onChange} checked={sex.value === 'male'}/> Male

**Comment by MitchWeiss** [comment]
This is definitely a bug, value doesn't get set when an initialValue is provided. Not a great solution but I managed to get it to work by manually setting the value just prior to rendering:

`if (!frequency.value && frequency.initialValue) {`
`      frequency.value = frequency.initialValue`
`    }`

I would love to see a fix for this though!

**Comment by Fedcomp** [comment]
@mdgbayly worked well. But it's probably should be fixed in redux-form is possible.

**Comment by MitchWeiss** [comment]
@mdgbayly's solution doesn't seem to work for me since field.value is undefined until a radio button has been selected by a user. What am I missing?

```
initialValues: {frequency: "14"}
```

```
<Row>
  <Col xs={12}>
    <label className="checkbox-inline">
      <Input 
        type="radio" 
        value="0"
        label="One Time" 
        bsStyle={ frequency.touched && frequency.error ? 'error' : null }
        checked={ frequency.value == "0"}
        onChange={ frequency.onChange }
      />
    </label>
    <label className="checkbox-inline">
      <Input 
        type="radio" 
        value="7"
        label="Weekly" 
        bsStyle={ frequency.touched && frequency.error ? 'error' : null } 
        checked={ frequency.value == "7"}
        onChange={ frequency.onChange }
      />
    </label>
    <label className="checkbox-inline">
      <Input 
        type="radio" 
        value="14"
        label="Fortnightly" 
        bsStyle={ frequency.touched && frequency.error ? 'error' : null } 
        checked={ frequency.value == "14"}
        onChange={ frequency.onChange }
      />
    </label>
  </Col>
</Row>
```

Frequency has the following properties:
```
active: false
defaultChecked: false
defaultValue: "14"
dirty: false
error: "Required"
initialValue: "14"
invalid: true
name: "frequency"
onBlur: (event)
onChange: (event)
onDragStart: (event)
onDrop: (event)
onFocus: ()
onUpdate: (event)
pristine: true
touched: false
valid: false
visited: false
__proto__: Object
```

**Comment by Fedcomp** [comment]
You should not pass all props, only pass onChanged and checked props to radio buttons, and add initial state. Worked for me.

**Comment by MitchWeiss** [comment]
That's exactly what I am doing. I only send checked and onChange. No luck...

**Comment by tomduncalf** [comment]
So the proper way to handle this is to add `checked={inputProps && option.value === inputProps.value}` or similar to each radio input? I was expecting this to be automatically handled when populating the form. Not a big deal, but wondering if @erikras could chime in?

**Comment by davidkpiano** [comment]
That's correct, @tomduncalf. `<input {...fields.<model>} />` automatically adds certain properties, but since it can't know whether the input is a text, radio, checkbox, etc., it omits the `checked` prop, so you have to supply that yourself.

**Comment by tomduncalf** [comment]
I see, I was wondering if there was a way for it to know what kind of field
it is, but that makes sense if it can't. Thanks!

**Comment by trevorr** [comment]
I think there's another use case for radio buttons that isn't supported by this: Binding each radio button to a separate boolean field, such that at most one field should have the value `true` and the rest `false`. For example, you have a "deep form" containing an array of objects, and you want to use a radio button to select one as default/preferred. You can override `name` on each button to a common value to get them to act as a group, but obviously the default `onChange` handler won't work right.

I could diverge from my server-side data model to instead have a top-level field indicating which object in the array is selected (in which case I could use the radio buttons as described above), but I couldn't just use the array index because objects can be deleted anywhere in the array. My best idea so far is to introduce a hidden/unbound, client-only, unique ID for each object (probably set using a counter maintained as part of the form state) and use that as the radio button value. Still, that's pretty complicated, so I'm wondering if there's a simpler solution I'm overlooking. @erikras?

**Comment by erikras** [comment]
@trevorr That sounds like something that could be handled by a custom input component. Sort of like [this idea to use checkboxes to control array membership](https://github.com/erikras/redux-form/issues/434#issuecomment-169171734). You could also manage it at the reducer level, with the `plugin()` interface, turning the set of booleans into a single virtual field. It seems like too rare a case for the library to handle for you, though.

**Comment by trevorr** [comment]
@erikras Thanks, that link is very helpful. I'm new to redux-form, so I had been wondering the right way to do simple things like programmatically change the value of fields. (For some reason, I hadn't thought of calling their `onChange` method. I was using the `change` action creator directly, but that's more difficult, as you don't get the autobinding to the form and field, and if it's just called "change", it seems to get filtered out of the props by `reduxForm()`.) Anyway, agreed that the use case doesn't need to be handled by the library if there's a straightforward way to accomplish it with the techniques you mention.

**Comment by trevorr** [comment]
In case it helps anyone else, here is a one-hot reducer plugin:

```
import { actionTypes } from 'redux-form'
import write from 'redux-form/lib/write'

const onehotReducer = (fieldName: string) =>
  (state: Object = {}, action: { type: string }): Object => {
    switch (action.type) {
      case actionTypes.CHANGE: {
        const { field } = action
        const suffix = '].' + fieldName
        if (field.endsWith(suffix)) {
          const openIndex = field.lastIndexOf('[')
          if (openIndex >= 0) {
            const arrayField = field.substring(0, openIndex)
            const value = !!action.value
            if (value) {
              state = write(arrayField + '[].' + fieldName + '.value', false, state)
            }
            state = write(field + '.value', value, state)
          }
        }
        return state
      }
    }
    return state
  }
```
It plugs in to the form reducer like this:
```
const store = createStore(
  combineReducers({
    // ...
    form: formReducer.plugin({
      contact: onehotReducer('preferred')
    })
  })
)
```
Given an array field with a "preferred" property, such as `things[].preferred`, it can be used in JSX like this:
```
{this.props.fields.things.map(thing =>
  // ...
  <Input type="radio" label="Preferred"
      name="preferredThing"
      checked={thing.preferred.value}
      onChange={thing.preferred.onChange} />
)}

**Comment by mkny** [comment]
How about this thing will work, with <Fields /> ? How to set the radio values to this. The website documentation is not helping me with this. Can someone help?

**Comment by strobox** [comment]
@mkny Yes, actual answer for this thread is http://redux-form.com/6.7.0/examples/simple/

**Comment by dmmarmol** [comment]
@strobox that link doesn't show how to set a default value for a single radio who share the same name with others. I'm still facing the same situation.

**Comment by danielrob** [comment]
@dmmarmol, initialize the value of the `name` you have assigned to all the radio buttons in the group, to the `value` that of your desired radio button to be checked, using `initialValues`.

**Comment by dmmarmol** [comment]
@danielrob I see what you mean, and you're right. Unfortunately due to the fact that I'm wrapping a custom `radio` component with a High Order Component that outputs the `redux-form` `<Field>` with my component as the value of the prop `component={}` I'm strugglin on make it work, but I've tested without my HOC and it works. 
Thanks!

**Comment by NickAlvesX** [comment]
I make it this way:

`
const RadioButtons = ({ name, options }) => (
    <div className='radio-options'>
        <Field
            component={({input, options}) => (
                options.map(option => <div key={option.id} className='radio-input'>
                    <input
                        id={option.id}
                        type='radio'
                        {...input}
                        value={option.value}
                        checked={option.value === input.value}
                    />
                    <label htmlFor={option.id}>{option.label}</label>
                </div>)
            )}
            name={name}
            options={options}
        />
    </div>
);

RadioButtons.propTypes = {
    options: PropTypes.arrayOf(PropTypes.shape({
        id: PropTypes.string.isRequired,
        label: PropTypes.string.isRequired,
        value: PropTypes.string.isRequired
    })),
    name: PropTypes.string.isRequired
};

<RadioButtons name={inputsNames.gender} options={[
    {
        id: 'gender-male',
        label: 'Male',
        value: 'M'
    },
    {
         id: 'gender-female',
         label: 'Female',
          value: 'F'
     }
]}/>
`

**Comment by NickAlvesX** [comment]
I make it this way:

````javascript
const RadioButtons = ({ name, options }) => (
    <div className='radio-options'>
        <Field
            component={({input, options}) => (
                options.map(option => <div key={option.id} className='radio-input'>
                    <input
                        id={option.id}
                        type='radio'
                        {...input}
                        value={option.value}
                        checked={option.value === input.value}
                    />
                    <label htmlFor={option.id}>{option.label}</label>
                </div>)
            )}
            name={name}
            options={options}
        />
    </div>
);

RadioButtons.propTypes = {
    options: PropTypes.arrayOf(PropTypes.shape({
        id: PropTypes.string.isRequired,
        label: PropTypes.string.isRequired,
        value: PropTypes.string.isRequired
    })),
    name: PropTypes.string.isRequired
};

<RadioButtons name='gender' options={[
    {
        id: 'gender-male',
        label: 'Male',
        value: 'M'
    },
    {
         id: 'gender-female',
         label: 'Female',
          value: 'F'
     }
]}/>
```

And then I can select the value with selector(state, 'gender').
