### ISSUE TITLE
Datetime input options?

### ISSUE THREAD

**Issue by davidhtien** [erikras/redux-form#1240]
I've been trying to use https://github.com/zippyui/react-date-picker with no luck, can't get the onChange to work. Any suggestions?

I also noticed that this library uses moment.js which doesn't play well with redux, could that be the problem?

**Comment by ooflorent** [comment]
> can't get the `onChange` to work. Any suggestions?

I played with it and it works as expected.

```js
<DateField {...fields.publishedAt} />
```

> I also noticed that this library uses moment.js which doesn't play well with redux, could that be the problem?

No because `onChange` sends the date as a `String` and `value` also accepts a `String`.
