### ISSUE TITLE
Validate returning undefined as values

### ISSUE THREAD

**Issue by mmahalwy** [erikras/redux-form#1241]
Version `5.3.0`

Validate is returning `undefined`, see: 

```js
const validate = (...args) => {
  const errors = {};
  console.log(args);
  // if (!values) return errors;
  //
  // if (!values.email) {
  //   errors.email = 'Required';
  // } else if (!/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i.test(values.email)) {
  //   errors.email = 'Invalid email address';
  // }
  //
  // if (!values.password) {
  //   errors.password = 'Required';
  // }
  //
  // if (fields.includes('passwordConfirmation') && !values.passwordConfirmation) {
  //   errors.passwordConfirmation = 'Required';
  // }
  //
  // if (
  //   fields.includes('passwordConfirmation') &&
  //   values.password &&
  //   values.passwordConfirmation &&
  //   values.password !== values.passwordConfirmation) {
  //   errors.passwordConfirmation = 'Does not match password';
  // }

  return errors;
};

@reduxForm({
  form: 'authentication',
  validate
})
export default class AuthenticationForm extends Component {
  static propTypes = {
    fields: PropTypes.object,
    handleSubmit: PropTypes.func,
    CTA: PropTypes.string.isRequired,
    authError: PropTypes.object,
    submitting: PropTypes.bool
  };

  render() {
    const { fields: { email, password, passwordConfirmation }, handleSubmit, CTA, authError, submitting } = this.props;
    const styles = require('./style.scss');

    return (
      <form className="login-form" onSubmit={(event) => event.preventDefault()}>
        <FormGroup>
          <FormControl {...email} type="email" placeholder="Email" />
          {
            email.touched && email.error &&
            <div className={`text-left ${styles.errorText} text-danger`}>{email.error}</div>
          }
        </FormGroup>
....
```

**Comment by mmahalwy** [comment]
Seems like this has happened right after 5.3.0 was released...

**Comment by vdh** [comment]
I had the same issue with the validate function getting passed `undefined` values with 5.3.0, downgrading to 5.2.5 fixed it for me.

- For me the issue happened on `redux-form/CHANGE` actions, but `redux-form/START_SUBMIT` sent the values through to the validate function like normal.
- I couldn't debug the reasons why, but only some forms encountered this issue. I couldn't see any major differences between the components, so I suspect it could be related to where in the React DOM the form is rendered? My form encountering the issue was rendered inside a dynamic child component.

**Comment by ooflorent** [comment]
I'm not able to reproduce the issue. It is really strange because the diff between v5.2.5 and v5.3.0 is really small ([see here](https://github.com/erikras/redux-form/compare/v5.2.5...v5.3.0))!

**Comment by scottbessler** [comment]
isnt it this?
```
  const values = form._initialized === false ? initialValues : getValues(fields, form);
  const syncErrors = validate(values, props) || {};
```

in that an uninitialized form without initialValues would call validate on undefined?

**Comment by ooflorent** [comment]
Yes it must be these lines but since the form is initialized when mounted, the validation should not be called. cc @yesmeck @erikras

**Comment by yesmeck** [comment]
I write a spec for this issue, @mmahalwy @vdh @scottbessler Plz take a look above PR to ensure I did not misunderstand the bug.

**Comment by erikras** [comment]
Thanks for taking this one, @yesmeck.

**Comment by JeroenNelen** [comment]
Can confirm running into this issue, going back to 5.2.5 indeed fixed it.

Kind regards,

**Comment by vdh** [comment]
@yesmeck Now that I think about it this issue could be related to `initialValues`, I don't remember setting it on the form, it was a simple one with a single text field (unfortunately the offending code is on my work machine at the moment).

The issue I ran into was that after I had entered text into the field, the validate function was still passed undefined for `values`. I double-checked the redux state and the field value was definitely being set in the redux form state, but the validate function was passed undefined for every change action. It was only on the submit action that the true form values were passed in.

**Comment by ljovanovic** [comment]
I was seeing the same issue.  Very simple form with a single field that would not load, indicating that values was undefined in the synchronous validation routine.  I was not setting any initial values on the form.  I was able to resolve the issue by adding '  initialValues: {}' in the mapStateToProps routine.  As far as I can tell the form is fully functional again.

**Comment by erikras** [comment]
Should be better in [`v5.3.1`](https://github.com/erikras/redux-form/releases/tag/v5.3.1).

**Comment by mmahalwy** [comment]
thanks @erikras
