### ISSUE TITLE
onSubmitSuccess not firing when onSubmit is a Promise

### ISSUE THREAD

**Issue by ryan-sherpa** [erikras/redux-form#1242]
@puradox

I'm passing a promise in to `handleSubmit` and passing the `onSubmitSuccess` key in the options hash, however the `onSubmitSuccess` never fires. 

If I pass a function instead of a promise to `handleSubmit` then the `onSubmitSuccess` function will fire. 

I tried to dig into the library and debug myself, but after an hour without being able to get `console.log` firing from within the node_module (being bundled by webpack) I have been forced to give up. 

Here's what I said in code, fwiw. 

*Not working:*
```js
render() {
  ...
  <form onSubmit={handleSubmit(myPromise)}>
    ...
  </form>
  ...
}


export default reduxForm(
  { 
    form: 'something',
    onSubmitSuccess: () => {
        console.log('onSubmitSuccess called (actually I am not called')
    },
    fields
  },
  mapStateToProps,
  {someAction}
)(MyComponent)
```

*Working:*

```js
render() {
  ...
  <form onSubmit={handleSubmit(() => {console.log('submit!')})}>
    ...
  </form>
  ...  
}

export default reduxForm(
  { 
    form: 'something',
    onSubmitSuccess: () => {
        console.log('onSubmitSuccess called (yes, yes I do get called')
    
    },
    fields
  },
  mapStateToProps,
  {someAction}
)(MyComponent)
```

**Comment by ooflorent** [comment]
`handleSubmit` only accepts functions. You must not pass a `Promise` but a function returning a `Promise`:

```js
handleSubmit(values => new Promise((resolve, reject) => {
  api.doStuff(values, (err, res) => {
    if (err) {
      reject(err)
    } else {
      resolve(res)
    }
  })
}))

**Comment by ryan-sherpa** [comment]
Oh shoot, i misspoke. When you pass a function which returns a promise the onSubmitSuccess callback never fires.

**Comment by ryan-sherpa** [comment]
It may be because i am resolving without passing a value. I will test this when i get to my computer.
