### ISSUE TITLE
[v6]  radio button input field with a boolean value not a string value not working right.

### ISSUE THREAD

**Issue by rluiten** [erikras/redux-form#1243]
Is this intended to work right if I use an actual boolean javascript value for input radio field.

Creatd an input field radio button.
```html
trueBool <Field name="trueBool" type="radio" value={true} component="input" />
```
Using redux-logger trace for actions generated by redux=form i get the following 
`action Object {type: "redux-form/CHANGE", meta: Object, payload: "true"}`

It fails to check the radio button when clicked.
I suspect its because the payload is a string and the field is a javascript boolean

At the moment I think I may need to force my boolean fields in my view model to be strings.
Thank you for your attention and any feedback.
Cheers, Robin

**Comment by ooflorent** [comment]
In HTML, when using an `input[type="radio"]` its value will be a `String`. So it is the same in RF. If you want to change this behavior, don't use an `input` but a custom component. You could also use a normalizer to transformer the value before writing it into the store.

**Comment by brentmclark** [comment]
You can also add the code below to your boolean radio.  

``` javascript
checked={myBoolValue === 'true' || myBoolValue === true}
```

**Comment by mcavaliere** [comment]
For those interested, below is a sample of code using a normalizer to make this work. 
```js
const normalizeBoolean = value => {
    if (value === "true") {
        return true;
    }

    if (value === "false") {
        return false;
    }

    return value;
};
```
```js
<Field name="active" component="input" type="radio" value={true} normalize={normalizeBoolean}/>
{' '}
Yes

<Field name="active" component="input" type="radio" value={false} normalize={normalizeBoolean}/>
{' '}
No
```
