### ISSUE TITLE
Redux-Form and React Native - undefined

### ISSUE THREAD

**Issue by Dudyboy** [erikras/redux-form#1245]
I am trying to slove problem with Redux Form and React Native. I am new in this, so any help I will appreciate. Everything works fine except it is not fire events onBlur, onChange, onUpdate and so on. Only one onChangeText is working correctly.

Next problem is that everything works fine, but just with:
`import {reduxForm} from 'redux-form';`

When I import: 
`import {reduxForm} from 'redux-form/native';`

... it shows me this error:

![error](https://cloud.githubusercontent.com/assets/20220049/16481479/c6c11496-3eab-11e6-8405-930c1751a8c3.png)

Again, thanks for help.

Dependencies:
`"react": "^15.0.2",
    "react-dom": "^15.1.0",
    "react-motion": "^0.4.4",
    "react-native": "^0.26.2",
    "react-redux": "^4.4.5",
    "redux": "^3.5.2",
    "redux-form": "^5.2.5",`

**Comment by inetfuture** [comment]
> Next problem is that everything works fine, but just with:
> import {reduxForm} from 'redux-form';
> 
> When I import: 
> import {reduxForm} from 'redux-form/native';
> 
> ... it shows me this error:

The docs said `redux-form/native` is deprecated: http://redux-form.com/5.3.1/#/faq/react-native?_k=tev6la

**Comment by Dudyboy** [comment]
Thank you for your answer. I thought, that I am doing something wrong, because I cant find solution, why it not work onBlur, onChange, onUpdate ...
