### ISSUE TITLE
[v6] after `returnRejectedSubmitPromise` is removed, unhandled promise error on submit of invalid form.

### ISSUE THREAD

**Issue by bsr203** [erikras/redux-form#1246]
Hi,

few days ago, `returnRejectedSubmitPromise` is removed, but these changes

```
-    if (returnRejectedSubmitPromise) {
 -      return Promise.reject(syncErrors)
 -    }
 +    return Promise.reject(syncErrors)
```

 cause issue in this scenario when use with the master.

When I submit the form first time, `valid` flag is true, and handles my result/promise correctly in the `if` section. But, if I try to submit again, `valid` is false, submit is never called and rejecting at the `else` branch causes below error.

```
new:1 Uncaught (in promise) Object {}
```

so, it never calls my `onSubmit` and its reject handler and causes unhandled promise error. Not sure where should I catch it, or we should not return `Promise.reject`in this case.

**Comment by bsr203** [comment]
I could solve the above err/ issue by catching it at the `onSubmit` like

```
(stateProps, dispatchProps, parentProps) => {
  return {
    onSubmit: (formData) => dispatchProps.onSubmit({
      // ....
    }).catch(err => console.log(err)),
  };
}
```

let me know if that is intentional and should be the way to use the API. thanks.

**Comment by jcheroske** [comment]
I am running into this too. Everything still seems to be working even though I'm getting the error message. If I put the `catch` in, it does squelch the error, but it prevents the SubmissionError from being properly displayed.

**Comment by oyeanuj** [comment]
@bsr203 @jcheroske Did you guys end up with a solution here?

**Comment by likerRr** [comment]
@erikras Probably the issue might be closed, a lot of things has updated since this.
