### ISSUE TITLE
Emit serialized form data on submit

### ISSUE THREAD

**Issue by gsklee** [erikras/redux-form#125]
Does there exist a way to emit the serialized form data as the action payload when `onSubmit` is triggered?

**Comment by erikras** [comment]
Hmm... Well, if the `value` props are set properly on all the inputs, and they should be, you could probably just use the regular html form submit to send the data. It somewhat defeats this library's purpose of maintaining the form data in a nice JSON structure, but it might work.

I googled "json to form data" and found _no one_ wanting to convert in that direction, and many people trying to go the other way, so your requirement is somewhat suspect.
