### ISSUE TITLE
initialValues causes maximum stack

### ISSUE THREAD

**Issue by mmahalwy** [erikras/redux-form#1252]
```js
@reduxForm({
  fields: ['geolocation', 'keyword', 'startDate', 'endDate'],
  form: 'searchPageSearch'
},
(state, { location }) => ({
  initialValues: {
    startDate: moment(location.query.startDate),
    endDate: moment(location.query.endDate),
    keyword: location.query.q
  }
}))
```

Seems like `moment` is causing this problem. Any ideas for alternatives?

**Comment by chrismcleod** [comment]
Faker can also cause this issue.
```
export default reduxForm({form: "myForm", fields}, (state) => {
  return {
    initialValues: {
      cost: "1",
      title: faker.commerce.productName()
    }
  };
})(MyForm);
```

**Comment by erikras** [comment]
What is `location.query.startDate` in your example?

Seems a little big of an abuse of `mapPropsToState`, as you are not pulling those dates from the `state`. So your code will generate brand new `moment` instances on every single Redux state change.

**Comment by yesmeck** [comment]
I don't think this is bug of redux-form. Compute data in `mapPropsToState ` is anti-pattern in redux. Further more, as @erikras said you are not pulling those dates from the state, so you don't need `mapPropsToState` actually.

**Comment by chrismcleod** [comment]
What is the recommended way of doing what Im trying to do which is, each time the form is mounted, I want to randomly generate a title as the default value.

**Comment by mmahalwy** [comment]
@erikras right, i think that might be the problem since `location.query.startDate` is coming from the props, that being said, what would be the right way to do with to bootstrap `initialValues` by using just the props and nothing from the state?
