### ISSUE TITLE
[v6] Optimize FieldArray Request

### ISSUE THREAD

**Issue by alurim** [erikras/redux-form#1253]
I discovered that every time a field in a `FieldArray` changes, the component that I pass into `FieldArray` re-renders. This became a bottle neck so I enhanced it with `pure` from `recompose` and assumed the perf issue would be fixed.

Instead I discovered that currently the `FieldArray` component passes in a `fields` object that changes every time a subfield changes to the component it's passed as a prop. This means that for a array of fields when I type in one the default behavior is that all of them re-render. I'm currently getting around this by only updating when the fields object length changes. This is working for me currently, but it'd be great if `fields` itself was the same object so users of this library can simply use `pure` to optimize this use case. 

Would this be desirable or possible?

**Comment by erikras** [comment]
> I'm currently getting around this by only updating when the fields object length changes.

This is what `FieldArray` did initially, but it was insufficient, as it would not rerender when the order of elements in the array changed.

I am seeing the rerendering that you are describing. But I'm not sure anything other than the `shallowEqual()` being performed is sufficient to properly render an array of fields. I think it might be up to the individual implementer to be smart about how the fields are rendered.
