### ISSUE TITLE
npm package containing coverage report html files causes issues with building 

### ISSUE THREAD

**Issue by pyry** [erikras/redux-form#1255]
NPM packages for recent version 5.3.0 and 5.3.1 seem to include coverage reports under node_modules/redux-form/coverage/lcov-report/ which cause build issues on Meteor:

`node_modules/redux-form/coverage/lcov-report/src/events/__tests__/createOnBlur.spec.js.html:1:
   Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)`

Work around is to manually remove coverage folder, but is there specific reason why this is included in the package ?

**Comment by erikras** [comment]
Oops. Sorry about that.
