### ISSUE TITLE
Is there a way to intercept the handleSubmit callback?

### ISSUE THREAD

**Issue by pavelvolek** [erikras/redux-form#126]
Is it possible to do some pre-processing of the data before submitting the form? 

The use case could be when the submit button is pressed, it would go through all values of all fields and trim the white spaces in the string values, re-run the validation and, if everything is still valid, it should continue with submitting. Otherwise, the submit should stop and show the form with validation errors on the fileds where validation failed after running the trim.

**Comment by pavelvolek** [comment]
What I had on my mind was something like this:
```js
onSubmit(data) {
  let noChange = true;

  Object.keys(data).forEach((key) => {
    const value = data[key];
    const newValue = value.trim();

    if (newValue !== value) {
      noChange = false;
      this.props.handleChange(key, newValue)();
    }
  });

  if (noChange) this.props.onSubmit(data);
}

render() {
  return (
    <form onSubmit={handleSubmit(this.onSubmit)}>
    ....
    </form>
  );
}
```
But with the difference, that if any value is trimmed but everything still passes the validations, then it should continue submitting the form with the new data.

Imagine there is a `name` field with *required* validation rule. 
The value `'   '` should be trimmed to `''` and the form should not be sent (the new value doesn't pass the *required* validation.
The value `' John  '` should be trimmed to `'John'` and the form with the new value can be sent.

**Comment by erikras** [comment]
Sure, since `onSubmit` is just a function, you can wrap it in whatever other function you'd like.

As for trimming whitespace, I might recommend using a [normalizing function](https://github.com/erikras/redux-form#normalizing-form-data).

**Comment by erikras** [comment]
Normalizing docs are now [here](http://erikras.github.io/redux-form/#/api/reducer/normalize).

**Comment by pavelvolek** [comment]
@erikras thank you, but I do not get how to use normalization in my case.
I want to trim whitespaces in all the string inputs (first name, last name, note, message, etc.) just before the form is submitted. I understand that with the normalization function I could prevent user to write whitespaces at the begining of the input filed. But how to use it for trimming the whitespaces at the end of the string when the input (textarea) can contain multiple words? I do not want to prevent user to write space at the end, I just wanna trim the unecessary whitespaces left at the end of the string before submit..

**Comment by erikras** [comment]
Okay, sure. You would do it like you have, but rather than calling anything to change the form value, you would just change the value in the `data` object you pass to `this.props.onSubmit()`. After your submit succeeds, you should initialize the form with the values saved to the server (so that all the fields get their `pristine`/`dirty` flags reset).

**Comment by pavelvolek** [comment]
got it, thank you.
