### ISSUE TITLE
Complex Values example returns inconsistent form

### ISSUE THREAD

**Issue by stefanv** [erikras/redux-form#1261]
Re: http://redux-form.com/5.3.1/#/examples/complex?_k=w819ii

If the user clicks "Submit" without touching the form, favorite hobby is returned as an entry in the dictionary.  Once favorite hobby is modified (click, select item), it becomes a string in the response.

**Comment by erikras** [comment]
That's a bug in that ObjectSelect component that I wrote for that example, not with `redux-form` itself.

**Comment by stefanv** [comment]
Sure; do you have a separate bugtracker for issues with the documentation?

**Comment by erikras** [comment]
No. But I'm not too worried about the v5 docs at the moment, so close to the v6 launch. That was a hastily thrown together component in the first place. If you wanted to debug it and submit a PR, I'd gladly accept.
