### ISSUE TITLE
Getting error "Cannot read property 'wrapped' of undefined" with v6.0.0-rc.1

### ISSUE THREAD

**Issue by krambertech** [erikras/redux-form#1262]
Hi,

I am using `redux-form/immutable` and getting error `Uncaught TypeError: Cannot read property 'wrapped' of undefined`

![image](https://cloud.githubusercontent.com/assets/10474869/16539857/2d04ad1e-4058-11e6-8365-cfd7a671fd6f.png)

This is how I use it:

**reducers.js**
```js
import { combineReducers } from 'redux-immutable';

import { reducer as form } from 'redux-form/immutable';

export default combineReducers({
    // ...
    form,
    // ...
});
```

**LoginForm.jsx**
```js
import React, { Component } from 'react';
import { reduxForm, Field } from 'redux-form/immutable';

import TextField from 'components/base/TextField';
import Button from 'components/base/Button';

import cx from './LoginForm.less';

const renderInput = (props) =>
    <TextField
        className={cx('field')}
        {...props}
    />;

@reduxForm({
    form: 'login'
})
export default class LoginForm extends Component {
    render() {
        const { handleSubmit } = this.props;

        return (
            <form className={cx('base')} onSubmit={handleSubmit}>
                <Field
                    name='username'
                    props={{ placeholder: l('Email') }}
                    component={renderInput}
                    type='text'
                />

                <Field
                    name='password'
                    props={{ placeholder: l('Password') }}
                    component={renderInput}
                    type='password'
                />
                <Button
                    primary
                    fullWidth
                    huge
                    type='submit'
                    label={l('Log in')}
                />
            </form>
        );
    }
}
```

Am I doing something wrong?

Thank you in advance :)

**Comment by d0ntth1nc** [comment]
Yes.

You are using react-hot-loader 1.3.0 which causes all getters to be executed. Upgrade it to the latest version (3.*)

**Comment by krambertech** [comment]
Thanks.

**Comment by mars76** [comment]
Hi,

 The latest version for react-hot-loader still seems to be 1.3.0. Where to find 3.* version.

 https://www.npmjs.com/package/react-hot-loader

https://github.com/gaearon/react-hot-loader

Both the above links are showing 1.3.0 as latest

**Comment by krambertech** [comment]
It is in beta, you can find [branch](https://github.com/gaearon/react-hot-loader/tree/next) and [pull request](https://github.com/gaearon/react-hot-loader/pull/240) here.

docs: https://github.com/gaearon/react-hot-loader/tree/next-docs
upgrade example: https://github.com/gaearon/redux-devtools/commit/64f58b7010a1b2a71ad16716eb37ac1031f93915

**Comment by d0ntth1nc** [comment]
1. Type in cmd: npm view react-hot-loader versions
2. Pick the latest version (3.0.0-beta.2 at this time)
3. Type in cmd: npm i react-hot-loader@3.0.0-beta.2
4. Enjoy

**Comment by ThiagoMiranda** [comment]
@d0ntth1nc updated the react-hot-loader version but now my hot loader don't work ( keep saying: hot reload failed. please refresh your browser ). Any thoughts?

Webpack config
```javascript
let config = Object.assign({}, baseConfig, {
  entry: [
    'webpack-dev-server/client?http://127.0.0.1:' + defaultSettings.port,
    'webpack/hot/only-dev-server',
    './src/index'
  ],
  cache: true,
  devtool: 'eval-source-map',
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoErrorsPlugin(),
    new BowerWebpackPlugin({
      searchResolveModulesDirectories: false
    })
  ],
  module: defaultSettings.getDefaultModules()
});

// Add needed loaders to the defaults here
config.module.loaders.push({
  test: /\.(js|jsx)$/,
  loader: 'react-hot!babel-loader',
  include: [].concat(
    config.additionalPaths,
    [ path.join(__dirname, '/../src') ]
  )
});
```

**Comment by d0ntth1nc** [comment]
'react-hot-loader/patch' should be first in the entries array.

There is no documentation yet but there is some info in [pull request](https://github.com/gaearon/react-hot-boilerplate/pull/61) which has links to [this](https://github.com/gaearon/redux-devtools/commit/64f58b7010a1b2a71ad16716eb37ac1031f93915) and [this](https://github.com/gaearon/react-hot-boilerplate/commit/b52c727937a499f3efdc5dceb74ae952aa318c3a) commit.
