### ISSUE TITLE
InitializeFromStateForm example uncaught TypeError

### ISSUE THREAD

**Issue by jlsa** [erikras/redux-form#1263]
I'm new to creating Issues on Github so bare with me.
I was trying out the 6.0.0-rc.1 and I found the InitializeFromStateForm example to return an error

**Uncaught TypeError: Cannot read property 'data' of undefined**

The code is exactly copied from the example so it's not that I have typed it wrong.

It seems to happen around

```
InitializeFromStateForm = connect(
  state => ({
    initialValues: state.account.data // pull initial values from account reducer
  }),
  { load: loadAccount }               // bind account loading action creator
)(InitializeFromStateForm)
```

where it can't seem to find state.account.data

**Comment by erikras** [comment]
`account` is where the Account reducer is mounted onto the redux state [here](https://github.com/erikras/redux-form/blob/v6/examples/initializeFromState/src/index.js#L12).

**Comment by bnlambert** [comment]
The link returns 404
