### ISSUE TITLE
v2.2.0 is not working

### ISSUE THREAD

**Issue by luisrudge** [erikras/redux-form#127]
After upgrading, my validation stopped working.

![image](https://cloud.githubusercontent.com/assets/941075/10471334/39ffb3c4-71eb-11e5-8c83-5da2cf1468b6.png)

**Comment by Nicktho** [comment]
Seeing this aswell. `data` is undefined in my validation functions.

**Comment by Nicktho** [comment]
Likewise on `2.1.0`, reverting to `2.0.0` fixed the issue for me.

**Comment by luisrudge** [comment]
2.1.0 works for me
________________________________
De: Nick Matenaar<mailto:notifications@github.com>
Enviada em: ‎13/‎10/‎2015 23:38
Para: erikras/redux-form<mailto:redux-form@noreply.github.com>
Cc: Luís Rudge<mailto:luis@luisrudge.net>
Assunto: Re: [redux-form] v2.2.0 is not working (#127)

Likewise on `2.1.0`, reverting to `2.0.0` fixed the issue for me.

---

**Comment by erikras** [comment]
Thanks guys. Will investigate.

**Comment by erikras** [comment]
Try v2.2.1.
