### ISSUE TITLE
[v6] grouped prop selector is not working

### ISSUE THREAD

**Issue by subicura** [erikras/redux-form#1271]
v6-rc.1

```
connect(
  state => selector(state, 'first', 'second')
)(MyFormComponent)
```

This is OK. I can use `this.props.first`.

```
connect(
  state => ({
    values: selector(state, 'first', 'second')
  })
)(MyFormComponent)
```

This is not working. `this.props.values` is undefined.
Is there any solution for this?

**Comment by subicura** [comment]
I found solution. `values` is reserved value for redux. Do not use this name.
I think http://redux-form.com/6.0.0-rc.1/docs/api/FormValueSelector.md/ this example should be changed.
Is it right?

**Comment by erikras** [comment]
`values` is not reserved for `redux`, but `redux-form` does use it, so yes, there will be a collision if you use that prop on your decorated form component. Docs have been changed.
