### ISSUE TITLE
override a field's onChange() function to take input array value on the fly

### ISSUE THREAD

**Issue by rcholic** [erikras/redux-form#1272]
I am trying to use the [DropZone](https://github.com/okonet/react-dropzone) component in my reactjs-based app for uploading multiple files. There is field called pics for my redux-form, and the following works for uploading a single file:

**in the render() function:**

```
<Row>
                  <Dropzone
                     { ...pics }
                     onDrop={ this.dropFile }
                 >
                   <div>Try dropping some files here, or click to select files to upload.</div>
                 </Dropzone>
              </Row>
```

**My dropFile() function:**

```
dropFile(files, evt) {
        console.log('received files: ', files);
        this.props.fields.pics.onChange(files); // use *files* to update the field pics value here        
    }
```

Although uploading a single file works, it does not allow uploading multiple files (dropped multiple files into DropZone). I guess the reason is the **onChange** function overwrites the previous file(s), so I was wondering if it's possible to override the **onChange** function so that a field can take an input array on the fly.

**Edit:**

In a hacky way, I have the reducer listen to the `redux-form/CHANGE` event, but I would like to know if there's any better way. Thanks

**Comment by danielrob** [comment]
Hi @rcholic, sorry noone got back to you on this. I think it's reasonably expected that people would intercept the `onChange` function using custom components with the pattern: 
```
onChange(e) {
    let nextValue
   // do stuff
  this.props.input.onChange(nextValue)
}
```
