### ISSUE TITLE
all fields are resetting when changing an initial value attached to redux state

### ISSUE THREAD

**Issue by FuzzySockets** [erikras/redux-form#1273]
```js
function mapState(state) {
    return {
        initialValues: {
            terms: state.register.toJS().terms.value
        }
    };
};

[map dispatch object here]

export const MyFormContainer = reduxForm({
    form: 'myForm',
    fields: ['email', 'password', 'terms']
}, mapState, mapDispatch)(MyForm);

<input type="checkbox" {...terms} onChange={this.handleTermsToggle.bind(this)}/>
```

When clicking the checkbox, the email and password fields are cleared. If I use the overwriteOnInitialValuesChange: false flag, the checkbox can no longer be checked or unchecked. Is this not the correct way to attach a simple boolean value from an existing redux state?

**Comment by FuzzySockets** [comment]
Turns out I was approaching the problem from the wrong angle. I needed to remove that chunk of the state tree altogether, and instead, use { change } from 'react-redux' in my outside component to modify the value.

**Comment by erikras** [comment]
So you solved the problem?

**Comment by FuzzySockets** [comment]
@erikras The initialValues behavior in version 5 still seems a little wonky to me, but this is all set on my end now; closing.
