### ISSUE TITLE
[6.0] Getting other props into field render function

### ISSUE THREAD

**Issue by OKNoah** [erikras/redux-form#1275]
I have a function to render a field outside my class like this

```
const renderNameField = (state, field) => (
  <InlineTextField
    field={field}
    className={ state.editMode ? classes.inputEditing : classes.textarea }
    fieldType="input"
    text={ field.value }
    editable={ state.editMode }
  />
);
```

It's used in the class like this

```
export default class Editables extends Component {
  static propTypes = {
    params: PropTypes.object
  }

  constructor (props) {
    super(props);
    this.state = {
      editMode: true
    };
  }

  render () {
    return (
      <div>
        <Field
          name="name"
          component={renderNameField.bind(null, this.state)}
        />
      </div>
    );
  }
}
```

However, using this method of `bind` seems to get the same problem the arrow functions did: the field loses focus upon `onChange`.

The other way of passing props into a field rendering function is to pass the function in as a prop from the parent component. However, I hope there's another way because I'd like the component to know how to render itself.

**Comment by erikras** [comment]
Right. The `bind()` is creating a new function on every render.
```js
  constructor (props) {
    super(props);
    this.state = {
      editMode: true
    };
    this.renderNameField = this.renderNameField.bind(this)    
  }

  renderNameField(field) {
    return renderNameField(this.state, field)
  }

  // . . .
  <Field name="name" component={this.renderNameField}/>
```

**Comment by OKNoah** [comment]
@erikras Thank you!

**Comment by OKNoah** [comment]
Note to anyone else with this issue:

I can to do what @erikras mentioned, plus do `<Field name="name" component={::this.renderNameField}/>` (note the `::` added to the start of `this.renderNameField`).

If you don't do this, changing any of your props/state will not cause your component to re-render. In my example, going into "editMode" would not affect the component at all, until I clicked on it.
