### ISSUE TITLE
Can i connect redux-form [v6] to other state, like in [v5]?

### ISSUE THREAD

**Issue by DimaRGB** [erikras/redux-form#1280]
Please answer to this question.

http://stackoverflow.com/questions/38201194/can-i-connect-redux-form-v6-to-other-state-like-in-v5

Thanks.

**Comment by qakovalyov** [comment]
+1

**Comment by DimaRGB** [comment]
Seems impossible to use way like in `v5`.

Now need to connect manually. [See answer](http://stackoverflow.com/a/38207925/2996072).

I think `v5` way **more convenient**.
But `v6` way **more clear**.
