### ISSUE TITLE
[v6] Clearing errors?

### ISSUE THREAD

**Issue by FuzzySockets** [erikras/redux-form#1282]
I've scoured the documentation hoping to find a way to easily clear form errors.  Is there an action creator for this? I'm looking to allow the user to "x" out of an error message at the field or form level.

**Comment by NeXTs** [comment]
Have you looked at example's sources?

https://github.com/erikras/redux-form/blob/v6/examples/simple/src/SimpleForm.js#L58

**Comment by FuzzySockets** [comment]
@NeXTs  I'm not looking to clear the entire form.  Just the error message(s).

**Comment by erikras** [comment]
Well, you can dispatch [`untouched(form, ...fields)`](http://redux-form.com/6.0.0-rc.1/docs/api/ActionCreators.md/#-untouch-form-string-fields-string-) to mark them as untouched, which, in most use cases will result in the errors being hidden. Does that help?

**Comment by FuzzySockets** [comment]
@erikras This doesn't appear to work.  I'm looking to allow the user to hide a form level error (_error).

**Comment by erikras** [comment]
Okay. `stopSubmit(form)` with no errors should work. There is no `clearError()` action.

**Comment by FuzzySockets** [comment]
@erikras Cheers to you good sir, it works!

**Comment by erikras** [comment]
Should be fixed in [`6.0.0-rc.3`](https://github.com/erikras/redux-form/releases/tag/v6.0.0-rc.3).

**Comment by y2k-shubham** [comment]
Neither untouched nor stop submit works for me.
I want to clear the form as well as the errors. 
And the link by @NeXTs gives me 404

**Comment by FuzzySockets** [comment]
@y2k-shubham Try:

`import { reset } from 'redux-form';`

Then:

`dispatch(reset('yourFormName'))`
