### ISSUE TITLE
[v6 rc1] Revalidation does not clear errors

### ISSUE THREAD

**Issue by estaub** [erikras/redux-form#1284]
Validation errors are not cleared when the user corrects them.

I'm new with redux-form, so I thought this was my badness, but after seeing the same behavior on http://erikras.github.io/redux-form-material-ui/, I'm not so sure.  

At http://erikras.github.io/redux-form-material-ui/, 

1. click in "Name" field
2. click in "Email" field.  The "Name" field now goes red.
3. click back in "Name" field and enter text.  The "Name" field stays red.
 
Nothing you do (AFAICT) will clear the error message.

In my case, I see that the validation function is returning a correct "errors" object, but the "error" on fields that are absent in that "errors" object are not cleared on the field itself.  So it looks like a redux-form issue.

**Comment by erikras** [comment]
Thanks. This is a known bug I'm working on.

**Comment by erikras** [comment]
This was introduced in 6rc1. It does not exist in 6a15.

**Comment by erikras** [comment]
Should be fixed in [`6.0.0-rc.3`](https://github.com/erikras/redux-form/releases/tag/v6.0.0-rc.3).

**Comment by brotzky** [comment]
@erikras 
Just downloaded 6.0.0-rc.3 and it is indeed fixed! Thank you **so much** for the awesome support. Having the errors within redux state is awesome.
