### ISSUE TITLE
[v6 rc2] react-widgets data prop broken

### ISSUE THREAD

**Issue by Zaiban** [erikras/redux-form#1285]
The newest update breaks react-widgets integration. You can test this easily:

`<Field name="test" component={Combobox} data={['data1', 'data2']} />`

When opening the list it displays "There are no items in this list".

Already updated everything else to work with rc2 but could not get this working.

**Comment by aight8** [comment]
Extra passed properties (here "data") is not available in the field component anymore.

**Comment by Zaiban** [comment]
Alright I made a wrapper for widgets and now they work perfectly.

Closing this issue.

**Comment by tejans24** [comment]
So, what's really the solution for this?

**Comment by Zaiban** [comment]
Create wrappers for widgets in some file in your app. For example:

`export const renderCombobox = props => <Combobox {...props.input} />;
export const renderMultiselect = props => <Multiselect {...props.input} />`

Then just import those where ever you need them and use them like you previously used Combobox, Multiselect etc..

**Comment by tejans24** [comment]
can I still pass in props through the Field using "props={{ valueField: "value", textField: "language", data: languages }}" ?

**Comment by erikras** [comment]
@tejans24 They are under `input`. e.g.

```js
const renderInput = props => {
  console.log(props.input.valueField)
  console.log(props.input.textField)
  console.log(props.input.data)
}
```

```js
<Field
  name="myField"
  component={renderInput}
  valueField="value"
  textField="language"
  data={languages}/>
```

Or, if you really want to use the `props` prop, the following is equivalent:

```js
<Field
  name="myField"
  component={renderInput}
  props={{
    valueField: "value",
    textField: "language"
    data: languages
  }}/>
```

**Comment by erikras** [comment]
By the way, a set of wrappers, like @Zaiban demonstrated, is pretty much all [`redux-form-material-ui`](https://github.com/erikras/redux-form-material-ui) is. If someone wanted to publish a set of them for other popular UI widget libraries, like React Widgets, I'm sure others would use it.
