### ISSUE TITLE
[v6 rc2] {...fields.input} no longer updates field value in reducer

### ISSUE THREAD

**Issue by brotzky** [erikras/redux-form#1286]
EDIT:

I feel like an idiot. I setup the form reducer incorrectly and it caused a ton of issues.

I had
```JavaScript
const appReducer = combineReducers({
  forms: formReducer,
});
```
but you you explicitly need to use **form**
```JavaScript
const appReducer = combineReducers({
  form: formReducer,
});
```

case closed. good night.

**Comment by eliseumds** [comment]
We've all been there xD
