### ISSUE TITLE
how to mount the redux-form reducer at the child node of the state tree?

### ISSUE THREAD

**Issue by shikelong** [erikras/redux-form#1287]
redux-form version: 5.3.1
redux version: 3.2.1
------
I mount the redux-form reducer at the child node and it take a error:

```
 Uncaught Error: You need to mount the redux-form reducer at "form"
```
![form](https://cloud.githubusercontent.com/assets/4499997/16606011/d87b5d44-4366-11e6-8056-57439b15ead0.png)

So can I mount the redux-form reducer not at the top-level of the state tree?  

Regards.

**Comment by erikras** [comment]
You've closed this, so perhaps you have the answer, but the answer, for future visitors is:

You can specify a `getFormState(state) => redux-form slice` config parameter to accomplish this. So, if you really wanted to (there is rarely a good reason) do what you're doing, you could do:

```js
OperatorManagementForm = reduxForm({
  form: 'operatorManagementForm',
  getFormState => state => state.operatorManagementReducer.form
})(OperatorManagementForm)
```

**Comment by adrian-moisa** [comment]
Thank you @erikras for the answer! The docs don't show a sample how to use this. I have many modules in my app with huge state and I want to separate forms per module at least. having all forms in one top level branch of the store is going to get nasty fast. So using `getFormState` in multiple branches spares me from big trouble later on when the store grows.
