### ISSUE TITLE
[v6] initialValues no longer works with wizard forms

### ISSUE THREAD

**Issue by clayne11** [erikras/redux-form#1293]
I'm not sure when this was introduced, but I'm no longer able to use `initialValues` with wizard-style forms.

`initialValues` used to only run once for the entire wizard. Now each time a new component mounts it resets the store with the initial values even though I want to save the values that are currently in the store.

**Comment by mike1808** [comment]
Yeah, I've noticed too and moved my initial values to my "master form" which aggregates all steps.

**Comment by clayne11** [comment]
I've fixed this by simply calling the `initialize` action. It's more powerful anyways.

**Comment by akhayoon** [comment]
I initialized everything in the parent form with `initialValues` and then passed it down to the other pages in the wizard and it worked.

Previously, only Page one would work and not Page two of the wizard.

**Comment by ToxicSalt** [comment]
@clayne11 Can you post a code example? Right now my parent component fetches initial data on mount and passes that data as a prop to each child form. I have set my child forms to dispatch initialize with the data in componentWillMount. The problem I'm having is every time a child form is unmounted it's reset to the initial values even if changed (just like the original issue you posted).
