### ISSUE TITLE
Input selector not redrawn on prop update

### ISSUE THREAD

**Issue by stefanv** [erikras/redux-form#1294]
I have [a form](https://github.com/acrellin/cesium_web/blob/fe9e2efe7f86b6588a30b6e28b562583de204254/public/scripts/Features.js#L40) that contains a [input selector](https://github.com/acrellin/cesium_web/blob/fe9e2efe7f86b6588a30b6e28b562583de204254/public/scripts/Form.js#L88).  When new props come in, the redux-form _state_ correctly updates, but the component fails to redraw itself.

As a workaround, I [added a key](https://github.com/acrellin/cesium_web/blob/fe9e2efe7f86b6588a30b6e28b562583de204254/public/scripts/Features.js#L39) to my element, which forces a redraw when necessary.

**Comment by danielrob** [comment]
@stefanv sorry no support was ever provided on this. Moving to v6+ of redux would probably be advice for this one year later, as v5 will accept PR's but is not actively supported.

**Comment by stefanv** [comment]
Thank you, @danielrob.  I appreciate you following up.
