### ISSUE TITLE
Autofocus on 2nd field not applying, and field.touched is true, with initialValues 

### ISSUE THREAD

**Issue by jonathan-stone** [erikras/redux-form#1295]
Hi, thanks for creating Redux-Form. Overall I'm sure it is saving lots of dev time.

I'm seeing unexpected interactions between initialValues, field.touched, and autofocus.
I have the first field ("subject") populated from initalValues, and the second field ("emailBody") set to autofocus.

There are two problems:
- When the form loads, the Subject field has focus even though it is NOT set to autofocus. 
- emailBody.touched is set to true even though the user has not interacted with the form at all. This means the validation error is displayed right when the form opens up.

My guess is that it happens like this:
1. Form loads 
2. Autofocus happens, sets focus to emailBody field
3. Redux-form populates subject field, inadvertently setting focus to it and causing a blur event on the emailBody field

Can you recommend a workaround?

The form:

```
const { circleName,
    fields:{ subject, emailBody },
    error,
    handleSubmit,
    mySubmitHandler,
    submitting,
    onCancel,
    ...otherprops } = this.props;
<form onSubmit={ handleSubmit((values)=>{mySubmitHandler(values, otherprops);}) }>
        <input className="input-field" type="text" name="subject" placeholder="Message subject" {...subject}/>
        <br/>
        <textarea autoFocus name="emailBody" placeholder="Type your message here"
          rows="15" className="input-field"
          {...emailBody}/>
        <br/>
        { (emailBody.touched && error) && <div>{ error }</div> }
        <br/>
        <button name="send-message" className="submit-button">Send Message</button>
        <br/>
        <Link to="/circles" className="modal-cancel-link">Cancel</Link>
      </form>
```

The container:

```
function mapStateToProps(state, ownProps)
{
    return {
        initialValues: {'subject': 'A message from someone'},
    };
}

function mapDispatchToProps(dispatch, ownProps)
{
  return {
    mySubmitHandler: (values, props) =>{
      const { user } = props;
      dispatch(sendEmail(values, user.id));
    }
  };
}


function clientValidate(values)
{
  const { subject, emailBody } = values;
  console.log("Client validate message");
  if (!subject || !emailBody)
  {
    console.log("Client validation failed.");
    return {
      subject: "Enter a subject",
      description: "Enter a message",
      _error: "Enter a subject and a message."
    };
  }
}

const fields = ['subject', 'emailBody'];
const MessageContainer = reduxForm ({
  form: 'message_create',
  fields,
  submitting: false,
  validate: clientValidate,
}, mapStateToProps, mapDispatchToProps)(Circle_Message);
```

**Comment by nex2hex** [comment]
same issue
autoFocus attribute don't work with redux-form

**Comment by goodbomb** [comment]
+1 same issue

**Comment by Dr1Ku** [comment]
+1, `autoFocus` doesn't work with (at least an older) version either, currently using `5.3.3`. 

I'm also using a custom `<InputField>` component which renders, among other stuff, an ordinary `<input>` tag. Passing `autoFocus` via props (`<input autoFocus={this.props.autoFocus}>`) or adding `autoFocus`, i.e. `<input autoFocus>` doesn't yield any results. 

The rendered `<input>` only contains other props such as `required`, `title` etc. Other `bool`-based props such as `readOnly` work. 

Interestingly enough, passing some other obscure HTML form props, such as `formMethod: "foo"`, results in the attributes getting attached to the `<input>`.

**Comment by sbussard** [comment]
+1 please pass all of the correct attributes to native html form elements

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input

**Comment by danielrob** [comment]
Closing with bulk close of v5 issues. If this issue still requires action and/or also affects v6/7, please request a reopen with details or raise a new issue. v5 PR's are still welcomed.
