### ISSUE TITLE
[v6] not able to have two same components with different initial values

### ISSUE THREAD

**Issue by mauvew** [erikras/redux-form#1296]
Say we have a table contains some rows, each row contains some data that can be edited. One example is the [react-redux-universal-hot-example](https://react-redux.herokuapp.com/widgets)

![image](https://cloud.githubusercontent.com/assets/14197252/16634946/fd983f0a-43c7-11e6-8158-8ab5b40ae34b.png)

In this example, we can edit more than one row. 
![image](https://cloud.githubusercontent.com/assets/14197252/16634984/27680798-43c8-11e6-844d-4b52d19b43b2.png)

However, in the V6 version, editing one row is fine, but when clicking the edit button to edit the second one, the value of the second row will override the first row, like the following:
![image](https://cloud.githubusercontent.com/assets/14197252/16635055/7758f474-43c8-11e6-99fd-513158613668.png)

I found this is due to that there is only one EditForm object created under state form, and the initial value is shared between these two forms, just wondering is there any way to make it work? Or it supposed to be like this. Thanks

**Comment by erikras** [comment]
You need unique form names. You can pass the form name in as a prop.
```js
<WidgetRowForm form={`widgetForm_${widget.id}`} initialValues={widget}/>
```

**Comment by mauvew** [comment]
Thanks, @erikras , will close this issue. :+1:
