### ISSUE TITLE
[v6] Additional event handlers for input in Field 

### ISSUE THREAD

**Issue by mike1808** [erikras/redux-form#1299]
Hi, I have the following problem with react@15.2.0 and with redux-from@6.0.0-rc.2. I need to add additional function that would be triggered on some events w/o removing the default one.

Consider the following example:

``` js
<Field name="username" component={UsernameField} onInputBlur={handleUsernameBlur} />
```

``` js
// UsernameField
import { flow } from 'lodash';

function UsernameField({ input }) {
  return (
    <input type="text" {...input} onBlur={flow(input.onBlur, input.onInputBlur)} />
  );
}
```

React 15.2.0 pop out this warning `Warning: Unknown prop`onInputBlur`on <input> tag. Remove this prop from the element.`. 
They are several solutions:
1. Do no spread entire `input` and assign one by one (it's painful)
2. Use rest arguments

``` js
function UsernameField({ input: { onInputBlur, ...input } }) {
  return (
    <input type="text" {...input} onBlur={flow(input.onBlur, onInputBlur)} />
  );
}
```
1. Add some new prop to `<Field />` which will assign that props to Field props itself, not to `props.input`.
2. Your solution?

**Comment by joefiorini** [comment]
@mike1808 @erikras I just ran into this as well trying to upgrade from v5. It seems weird to me that `Field` splats all of its props into `props.input`, since there's a limited set of props that are considered valid for `input`. I too need to pass custom props into `Field`; these should definitely not be passed to the `input` as well.

**Comment by mike1808** [comment]
@joefiorini I've already got used to it. Sometimes this features helps (let's say you want to pass `disabled` property).

**Comment by gustavohenke** [comment]
Some of these events were made available in recent versions of redux-form v6.
