### ISSUE TITLE
Does not work when passed props named 'actions'

### ISSUE THREAD

**Issue by haradakunihiko** [erikras/redux-form#130]
In the latest version of redux-form, almost all redux-form's actions (like handleChange, handleBlur) throw exceptions. I guess this is because of the cache implementation.

Here is a pseudo code
```js
MyComponent extends Component{
  render() {
    return <ReduxFormConnectedComponent actions={this.props.myActions} />
  }
}
```
I just passed actions props. It seems lazyCache intercept the props and use it for redux-form's action.
Any idea?

**Comment by erikras** [comment]
Ha! Great find. Will fix asap.

**Comment by erikras** [comment]
Try `v2.2.5`.
