### ISSUE TITLE
Option to disallow registering fields for which there are no initial values

### ISSUE THREAD

**Issue by aldendaniels** [erikras/redux-form#1303]
Right now, I can initialize redux form with values:

``` javascript
{
  firstName: 'John'
  lastName: 'Doe'
}
```

And then accidentally use different field names:

``` jsx
<Field name="nameFirst" ... />
```

And redux-form will register `nameFirst` as a field instead of warning. A `strict` option that would avoid this would be useful.

**Comment by gustavohenke** [comment]
This is kinda unusual feature... no one else upvoted it, and there aren't comments, so I'm curious if you ever managed doing it another way.
What was your outcome, @aldendaniels?

**Comment by erikras** [comment]
Redux Form can't really provide a warning for this, since it can't know if you have another value called `nameFirst` that was initialized as `undefined`.
