### ISSUE TITLE
Intial Focus/Blur Rerenders entire form

### ISSUE THREAD

**Issue by aldendaniels** [erikras/redux-form#1305]
Using v4 RC2. Seems like a bug.

**Comment by erikras** [comment]
Can you be more specific? How do you know it's rerendering? Are you using validation?

**Comment by gustavohenke** [comment]
Considering that we have this in [the v6 migration guide](http://redux-form.com/6.4.0/docs/MigrationGuide.md/), @aldendaniels was probably right:

> In v5, only the outer form component was connected to the Redux state, and the props for each field were passed in via the form component. The problem with this is that the entire form component had to rerender on every single keypress that changed a form value.

v6 doesn't have this problem anymore, so... will close here.
