### ISSUE TITLE
[v6] FieldArray don't get "touched" property

### ISSUE THREAD

**Issue by clayne11** [erikras/redux-form#1308]
I use the `touched` property to determine when to show an array for a given field.

`FieldArray` doesn't get passed `touched` and so there's no way to determine when to show the error for this field.

`touched` is also overridden in the when the `FieldArray` has child values.

**Comment by JozefBiros** [comment]
I am using redux-form v7.0.3 and prop meta.touched is missing from FieldArray.

**Comment by danielrob** [comment]
@JozefBiros this is intentional as the value is an array, so the concept of touched doesn't make sense. See #2207.

**Comment by xjunior** [comment]
@danielrob I only display `error` when the value is `touched`. How do you suggest implementing this instead?

**Comment by eldyvoon** [comment]
@xjunior found a solution yet?

**Comment by xjunior** [comment]
@eldyvoon for my case, yes. Instead of using `touched` to display errors, I'm using `submitFailed`. That did the trick to me.
