### ISSUE TITLE
onChange validation

### ISSUE THREAD

**Issue by Lonelind** [erikras/redux-form#131]
Hi! I am tying to do a validation at ```change``` event. I need to prevent input of not-valid chars, that are not in characters map (i.e. RegExp) or exceeding max length.

So, in first approximation it looks like 
```jsx
/* ... */
render () {
    const { fields: {
        name,
    }, handleSubmit } = this.props;

    return (
        <input
            type="text"
            required={true}
            {...name}
            onChange={(evt) => {
                if (evt.target.value.length >= 255 || somePatternMatching) {
                    console.log('I TRY TO STOP')
                    return;
                }

                name.onChange(evt);
            }}
        />
    );
}
/* ... */
```

I've tried onChange and handleChange both. But I've caught strange bug: when I enter symbols, that are not accepted here with RegExp, logging string is passed to console (it says that ```somePatternMatching``` works correctly), but the value inside my ```input``` changes. Next, I clean up my ```input``` with Backspace button and start to enter these symbols again, nothing but accepted symbols are entering. Maybe something inside dispatches an action to change the field regardless to my attempt to prevent it? Or how to make this correctly?

**UPD:** In addition, I tried to set ```onKeyDown``` prop to my ```input``` with the same function (it calls onChange at the end too) — and it worked correctly. But it looks like an overhead. Of course, I can write a function to get callbacks and avoid duplicates in code, but is it proper way to pass the same functions inside both props when onChange in standard way can handle this alone?

**Comment by erikras** [comment]
You might want to check out the [normalizer](https://github.com/erikras/redux-form#normalizing-form-data) docs. Is that enough for your needs?

**Comment by erikras** [comment]
Normalizer docs are now [here](http://erikras.github.io/redux-form/#/api/reducer/normalize).
