### ISSUE TITLE
[v6] How to ref <Field>'s onChange func?

### ISSUE THREAD

**Issue by smilingpoplar** [erikras/redux-form#1312]
I'm migrating from v5 to v6 (with dropzone.js to upload images).

In v5, I can directly call field.onChange():

```    
onChangeImageIds() {
  ...
  this.props.field.onChange(imageIds);
}
```

Now in v6, using <Field>, how should I ref this field.onChange()?

I'v tried using `<Field ref='xxx'>`, and then `this.refs.xxx` to get ref to `<Field>`. But this ref has neither `onChange` nor `input` property.

**Comment by stevengoldberg** [comment]
`onChange` gets passed as a prop to the component you provide to `<Field>`. Check out the example [in the docs for Field](http://redux-form.com/6.0.0-rc.3/docs/api/Field.md/).

**Comment by smilingpoplar** [comment]
@stevengoldberg As you said, we can get the `onChange` as prop *inside* a `<Field>` render component. 

But, how can I ref to the `onChange` *outside* the `<Field>`? Say, I have a component A containing the `<Field>`, and A needs to call the `<Field>`'s `onChange` func?

**Comment by smilingpoplar** [comment]
In order to get a `Field`'s onChange func, I need:

1. define `Field` with ref&withRef 
    ```
<Field name={name} component={MyInput} type="hidden" ref="myInput" withRef />
```

2. define a render component
    ```
/* eslint-disable react/prefer-stateless-function */
class MyInput extends Component {
  render() {
    return (
      <input {...this.props.input} />
    );
  }
}
MyInput.propTypes = {
  input: PropTypes.object.isRequired,
};
```

3. then get the onChange func
   ```
const { props: { input: { onChange } } } = this.refs.myInput.getRenderedComponent();
```

Any better solution? @erikras

**Comment by GuillaumeCisco** [comment]
Hello @smilingpoplar, I encountered the same issue and simply used `props.input.onChange`.
See comment here: https://github.com/erikras/redux-form/issues/71#issuecomment-234234555
Hope it helps ;)

**Comment by smilingpoplar** [comment]
@GuillaumeCisco Right. But I wanna ref it *outside* the <Field> component, so I also need `ref`&`withRef`.

**Comment by BryIsAZombie** [comment]
@smilingpoplar The way ive been going about it is importing change from redux-form
```javascript
import { change } from 'redux-form';
```
and then just having a handleChange helper that takes the value and does whatever i need to do with it. Then I dispatch the change from a decorated reduxForm component.

```javascript
let KioskMoneyOrder = (props) => {

  const handleChange = (e) => {
    let value = e.target.value;
    ...
    props.dispatch(props.change('contact[fee_amount]', value);
  }

  return (
    <Field
      name="contact[fee_amount]"
      type="number"
      component={renderField}
      step="0.01"
      min="0"
      onChange={handleChange}
      hideLabel={true}
      className='kiosk-money-order__input'
    />
  )
}
```
