### ISSUE TITLE
Normalizer doesn't work when stateless function is given to components props of the Field

### ISSUE THREAD

**Issue by simonkoener66** [erikras/redux-form#1314]
Here are the code example.
Normalizer will work in this code:
`<Field name="test" component="text" placeholder="Enter someting..." normalize={value => value && value.toUpperCase()}/>`

But not in this code:
`<Field name="test" component={test => 
  <input type="text" name="test" {...test}/>
} normalize={value => value && value.toUpperCase()}/>`

**Comment by mmakarin** [comment]
I have the same issue in 6.0.2

**Comment by rafaelbiten** [comment]
I had this problem and using `format` instead of `normalize` did the trick for me.
This doesn't actually change the data you have on your store. If you want to do that, then use both.

`format` is the first part of the 

> http://redux-form.com/6.2.0/docs/ValueLifecycle.md/

**Comment by danielrob** [comment]
The above code would not work because spreading `test` adds an input and a meta prop. You want to spread `test.input`. 

I've tried this here https://codesandbox.io/s/kR1JK361J, and could not reproduce. If you think this issue is still reproducible, please feel free to advise.
