### ISSUE TITLE
Doesn't seem to honour `GET` requests in <form> elements.

### ISSUE THREAD

**Issue by mrcthms** [erikras/redux-form#1315]
I'm working with a form with an `action` and a `GET` `method`, and using redux-form to validate the form before submission. The validation all works fine, and I both the `handleSubmit` and `onSubmitSuccess` callbacks fire correctly, so I know the validation is correct.

However, the form doesn't fulfil the `action` and `method` of the form, so it appears as though redux-form is doing some kind of `preventDefault` method or something weird.

Shortened example of the code is below:

``` jsx

var Component = React.createClass({
  onSubmit: (data) => console.log(data),
  render: function () {
    return (
      <form method="GET" action="/path/to/action" onSubmit={handleSubmit(this.onSubmit)}>
        ...fields
      </form>
    );
  }
});

export var ReduxForm = reduxForm({
  form: 'form',
  fields,
  validate: handleValidate.bind(null, fields, rules),
  onSubmitSuccess: () => console.log('success')
})(Component);
```

And then when the form submits, I get the form data logged in the console, and a `success` message from the `onSubmitSuccess` callback, but I don't get taken to the `form`'s `action` attribute, just stay on the same page.

Is this expected, and intended behaviour? And if so, is there a way to ensure that form submissions like this can be executed correctly?

**Comment by OKNoah** [comment]
You should probably set up a function to do the `GET` request, like

    onSubmit (values) { // values is all the values of the form
      superagent
        .get("/path/to/action")
        .send({
          name: values.name
        })
        .end((error, response) {
          // handler error or response
        });
    }

Although, in react/redux this is usually done in a store, which is another topic.

**Comment by gustavohenke** [comment]
If you completely remove the `onSubmit` prop from your `<form>`, then you'll get the desired behavior.
However you'll not get the coolness of Redux Form validations executed as soon you click your submit button 😢 Validations will still work, but only as your blur fields.

And don't forget that you should disable your submit button using the `valid` prop!
```
<button type="submit" disabled={!this.props.valid}>Submit</button>
```

Or, you could simply... use @OKNoah's suggestion :)

Finally, @mrcthms, as it's been a while since you created this issue, let us know what you ended up doing and close the issue.

**Comment by mrcthms** [comment]
@gustavohenke thanks for the reply (@OKNoah thanks for yours too – must have missed it at the time!) I feared that was the case. I'm working on an application that – at present, anyway – doesn't utilise AJAX/History API, so we've had to resort for a classic `location` change:
```javascript
const onSubmit = data => {
  const { pathname } = window.location;
  window.location = `${pathname}/preview?${qs.stringify(data)}`;
}
```

Not the most elegant solution but it's working for us for now!
