### ISSUE TITLE
onSubmit vs handleSubmit

### ISSUE THREAD

**Issue by mdramos** [erikras/redux-form#1317]
using 6.0.0-rc.3

The way this works is pretty confusing. The docs don't help much: http://redux-form.com/6.0.0-alpha.4/docs/faq/HandleVsOn.md/ (i get the naming convention, but the way it works below is confusing)

not sure why this works:

**parentComponent.js** 
```javascript
handleLoginAttempt(values) {
    console.log(values);
}

render() {
  return (
    // HERE 1: prop name is "onSubmit", won't work if named "handleSubmit"
    <LoginForm onSubmit={this.handleLoginAttempt} {...this.props}/>
  );
}
```
**formComponent.js**
```javascript
// HERE 2: why handleSubmit but not onSubmit like we named it above ?
const { handleSubmit } = this.props;
  return (
     <form className="login-form" onSubmit={handleSubmit}>
...

**Comment by OKNoah** [comment]
`handleSubmit` is a part of redux-form that will automatically look for and `onSubmit` prop and run it.

**Comment by reywright** [comment]
@OKNoah is there anyway to get around this? Default defaultProps or anything similar? I don't really have a desire for the component that houses this form to know anything about the form... but the way this is architected, I have no choice

**Comment by zhenyulin** [comment]
I found this very confusing as well, as it relied on the user/developer knowing this convention; Would be great to use any prop name to define the handler function. Can imagine it is doing a `handleSubmit` null check to decide if to use async form submission atm?
