### ISSUE TITLE
[v6] react-addons-shallow-compare 15.2.0 dep breaks React 15.0/1 users

### ISSUE THREAD

**Issue by HankMcCoy** [erikras/redux-form#1319]
Currently there is a dependency on `"react-addons-shallow-compare": "^15.2.0"` in the [package.json for rc.3](https://github.com/erikras/redux-form/blob/v6.0.0-rc.3/package.json#L50). This causes a problem for those of us still using React 15.1 or lower with NPM 2, since that package has a peer dependency on React 15.2.

Since the functionality provided by that package is super minimal, might it be possible to replace it with a simple local implementation to prevent weird dependency issues with older React versions? If that's something that sounds reasonable I'd be happy to tackle opening a PR for it if you don't have bandwidth for such a change.

**Comment by UweWindt** [comment]
I have the same problem.
in my project i have as dependency to React-Bootstrap which i not 15.2 ready.
I think other people will have similar situations.
In general it will take a while until all React Libraries have converted to React 15.2.
Meanwhile i helped myself, with manually modifying the package.json.

**Comment by HankMcCoy** [comment]
PR opened, in case this is a change @erikras is open to: https://github.com/erikras/redux-form/pull/1331

**Comment by gustavohenke** [comment]
Fixed by #1331
