### ISSUE TITLE
[6.0.0-rc.3] component render function docs unclear

### ISSUE THREAD

**Issue by BraunreutherA** [erikras/redux-form#1322]
In the documentation the render function for `<Field />` is written like: 
```
const renderField = props => (
  <div>
    <label>{props.placeholder}</label>
    <div>
      <input {...props}/>
      {props.touched && props.error && <span>{props.error}</span>}
    </div>
  </div>
)
```

Actually the placeholder, name etc. is not directly on the props object - It's on `props.input`
So the function should more look like: 

```
const renderField = ({ input, touched, error }) => (
  <div>
    <label>{input.placeholder}</label>
    <div>
      <input {...input}/>
      {touched && error && <span>{error}</span>}
    </div>
  </div>
);
```

**Comment by k-italy** [comment]
@BraunreutherA This seems to be an intentional breaking change as of v6.0.0-rc.2
https://github.com/erikras/redux-form/releases/tag/v6.0.0-rc.2

**Comment by BraunreutherA** [comment]
Ah - didn't notice. So this should get into the docs :)

**Comment by gabeweaver** [comment]
@BraunreutherA there is bug in the docs that resets the version you are browsing to rc.1...caught me a few times. You have to manually over ride the URL in the browser to rc.3 to view the most recent docs. http://redux-form.com/6.0.0-rc.3/docs/api/Field.md/

**Comment by erikras** [comment]
@gabeweaver is correct.

Perhaps the docs need a more prominent version display-and-selector. In the header somewhere. I'll look into it.
