### ISSUE TITLE
onChange is changing field initialValue to updated value, never dirty

### ISSUE THREAD

**Issue by fairbairn** [erikras/redux-form#1324]
We're pretty good at ReduxForm, but this one has us stumped.

We're passing in a field called "liens", we're rendering it as a `<select multiple>`.

Down the page we're generating checkboxes (manually) with an onChange event wired to this function...

```
onChange(e) {
        let options = this.props.fields.liens.value || [];
        // check if the check box is checked or unchecked
        if (e.target.checked) {
            // add the numerical value of the checkbox to options array
            options.push(e.target.value)
        } else {
            // or remove the value from the unchecked checkbox from the array
            let index = options.indexOf(e.target.value);
            options.splice(index, 1)
        }

        // this.props.initializeForm(this.props.liveData);
        this.props.fields.liens.onChange(options);
    }
```

The initialValues coming into the form is `{ liens: [] }`

If we click on a checkbox down the page and it fires it's onChange() handler above, it successfully puts the new values in the array held by the field, however reduxForm behind the scenes (somehow) also updates the field's `.initialValue` to the same `.value` property, and it never shows dirty.  The form doesn't show dirty either; however, if we focus into the select then all of a sudden it changes things, but the initialValue is never again in sync with how it should have been maintained from the initialValues passed in the form.

Why would reduxForm ever modify the .initialValue of a field element responding to a field.onChange() function call?

For completeness, our checkbox does this..

```
<input type="checkbox"
checked={_.includes(liens.value, liability.get('id'))}
onChange={::this.onChange}
id={liability.get('id')}
value={liability.get('id')}/>
```

and the select is...

```
<select multiple {...liens}>
{liabilities.map(liability => {
return <option key={liability.get('id')} value={liability.get('id')}>{liability.get('id')}</option>
})}
</select>
```

Upon our form loading, our field props are this...

```
{
    "name": "liens",
    "value": [],
    "initialValue": [],
    "valid": true,
    "invalid": false,
    "dirty": false,
    "pristine": true,
    "active": false,
    "touched": false,
    "visited": false,
    "autofilled": false
}
```

If we click on a checkbox, the field props change to this..

```
{
    "name": "liens",
    "value": [
        "5f2c295f-5abe-4b3a-91a5-35dc65d2f435"
    ],
    "initialValue": [
        "5f2c295f-5abe-4b3a-91a5-35dc65d2f435"
    ],
    "valid": true,
    "invalid": false,
    "dirty": false,
    "pristine": true,
    "active": false,
    "touched": false,
    "visited": false,
    "autofilled": false
}
```

Totally frustrated why the initialValue gets out of sync.  BTW, the initialValues of the form does not change.

What do we need to do to properly update an array-based field using onChange so that the form state (dirty not getting set either) and field state operate correctly?

`"redux-form": "^5.3.1"`

**Comment by lauterry** [comment]
Any update on this ?

I got the same issue

**Comment by danielrob** [comment]
Closing with bulk close of v5 issues. If this issue still requires action and/or also affects v6/7, please request a reopen with details or raise a new issue. v5 PR's are still welcomed.

**Comment by cvanem** [comment]
I had a similar issue.  My problem turned out to be incorrectly using slice in my onChange function.  When I updated the selected value, I was inadvertently also updating the initialValues field because the object reference was the same between the two instances.

> For object references (and not the actual object), slice copies object references into the new array. Both the original and new array refer to the same object. If a referenced object changes, the changes are visible to both the new and original arrays.


Non-Working Code
```
changeItemOld = (id, selected) => {
	var newitems = this.props.items ? this.props.items.slice() : [];
	newitems.forEach(i => {
		if (i.id == id) {
			i.selected = selected;
		}
	});			
	this.props.onChange(newitems);
}
```

Working Code

```
changeItem = (id, selected) => {
	var newitems = this.props.items.map(i => ({ ...i }));			
	newitems.forEach(i => {				
		if (i.id == id) {
			i.selected = selected;
		}				
	});			
	this.props.onChange(newitems);
}
```

**Comment by NurbekGithub** [comment]
@cvanem 
slice actually creates new array. So this is really strange why it didn't work out that way. I have this issue. I see that Change action dispatches, but form is still not dirty((

**Comment by vileppanen** [comment]
Same here: in my implementation, onClick on checkbox dispatches action, that sets state with newly created array using spread syntax --> the form initializes the field with the states values right away, so it appears pristine. redux-form v7

**Comment by rendomnet** [comment]
Anyone found reason?
