### ISSUE TITLE
Can form submit ignore syncErrors?

### ISSUE THREAD

**Issue by farrrr** [erikras/redux-form#1325]
At present design of redux-form, if there are validation errors, the forms cannot be submitted. It's reasonable to regular scenarios.

Imagine that there is a user who initials a huge project which has tons of fields to edit. The user may need to edit it for many times, so it would be better if he can save the form temporarily every time he edits them even there are validate errors, and be able to confirm the correctness of all the fields right before he submits the project to admin. Still, we hope that error messages exist to help the user do the formats. 

We tried to trace handleSubmit code and found that it would be submitted only when there are no syncErrors. Is it possible to add a forceSubmit argument to allow it be saved as syncErrors exist? Or is there any better solution?

Now we've already used redux-form in production. For now, we customize our validator in render function to display errors instead of using redux-form's validation. However, it's not a good way that revalidates all fields in every render. We still want to find a better one.

**Comment by iampeter** [comment]
@farrrr have you found a solution? because I am looking for the same thing.

**Comment by iampeter** [comment]
I tried:
```
  specialSubmit(event) {
    event.preventDefault();

    const {
      handleSubmit,
      handleSetCustomValidationState
    } = this.props;

    handleSetCustomValidationState(true);

    return handleSubmit(this.submit, this.props.values, this.props, this.props.asyncValidate);
  }
```

with 
```
<form onSubmit={this.specialSubmit} >
```

Then I could differentiate `validate` basing on the custom validation state, but `handleSubmit` doesn't get called properly.

**Comment by farrrr** [comment]
@iampeter not yet, but I have a workaround. 

It will show validation errors but won't block submit. if some of fields that you want to block submit, you can definite them in createValidator.

This is also a dirty solution, so I wanna find a better one.

- Validate
```javascript
import Validator from 'validatorjs';
import _ from 'lodash';

const validateRules = {
  main: {
    rules: {
      title: 'required|max:40',
      summary: 'required',
      ...
    },
    attributes: {
      title: '專案名稱',
      summary: '計畫摘要',
      ...
    },
  },
  ...
}

const ruleSelector = (rules, fields = []) => (fields.length ? _.pick(rules, fields) : rules);

export default function createValidator(form, fields) {
  const rules = ruleSelector(validateRules[form].rules, fields);
  const attributes = ruleSelector(validateRules[form].attributes, fields);

  return (data) => {
    const validation = new Validator(data, rules, localization));

    validation.setAttributeNames(attributes);

    return validation.fails() ? _.mapValues(validation.errors.all(), error => _.head(error)) : {};
  };
}

```

- MainForm
```javascript
const MainForm = (props) => {
  const {
    handleSubmit,
    formData,
    checker,
    anyTouched,
    ...
  } = props;

  const validation = anyTouched ? checker(formData) : {};

  return (
    <form onSubmit={ handleSubmit }>
      <Field
        name='title'
        validation={ validation }
        component={ Form.Text }
        ...
      />
      <Field
        name='summary'
        validation={ validation }
        component={ Form.Text }
        ...
      />
      ...
    </form>
  );
}

export default connect(
  ...
)(reduxForm({ form: 'main' })(MainForm));
```

- Main
```javascript
class Main extends React.Component {
  render() {
    return (
      <MainForm
        validate={ createValidator('main', ['title'], true) }
        checker={ createValidator('main') }
        ....
      />
    );
  }
}
```

- Form.Text
```javascript
export default class Text extends React.Component {
  getErrorMsg() {
    const { input: { name, validation }, error, touched } = this.props;

    if (touched && error) {
      return error;
    }

    if (_.has(validation, name)) {
      return validation[name];
    }

    return null;
  }

  getValidateState() {
    const { input: { name, validation }, error, touched } = this.props;

    if (touched && error) {
      return 'error';
    }

    if (validation) {
      return _.has(validation, name) ? 'error' : 'success';
    }

    return null;
  }

  getHelpBlock() {
    const { input: { name, validation }, error, touched } = this.props;

    if ((touched && error) || _.has(validation, name)) {
      return (
        <span>{ this.getErrorMsg() }</span>
      );
    }

    return null;
  }

  render() {
    const { input: { validation, name, ...rest } } = this.props;

    return (
      <FormGroup
        controlId={ name }
        validationState={ this.getValidateState() }
        bsClass="..."
      >
        <FormControl
          name={ name }
          { ...rest }
        />
        { this.getHelpBlock() }
      </FormGroup>
    );
  }
}
```

**Comment by iampeter** [comment]
I ended up doing main validation (required) with `redux-form`, and the side one (suggested required) with additional data in the store.

I am using [`redux-saga`](https://github.com/yelouafi/redux-saga) to watch for `redux-form/INITIALIZE`, `redux-form/BLUR` and `redux-form/CHANGE` actions and dispatch my custom ones that handle the additional validation.

**Comment by JakeLin1024** [comment]
I think you can call the stopSubmit Action before saving.

**Comment by clayne11** [comment]
What I would do in this situation is intercept the `submit` click before calling `handleSubmit`. Since all of the form values are in the `redux` store, you can simply grab the values out of the store and submit them. You don't have to pass through the `redux-form` validation at all.

**Comment by gustavohenke** [comment]
Guys, why don't you use warnings instead?
