### ISSUE TITLE
[v6] Best practice for ComboField

### ISSUE THREAD

**Issue by dpwrussell** [erikras/redux-form#1329]
Hi,

I had this form component in V5. Basically it is using bootstrap input addons to have a component that represents a text field and a checkbox (https://react-bootstrap.github.io/components.html#forms-input-addons).

I was going through upgrading to V6 and got a bit stuck here. My V5 component render:

``` jsx
<FormGroup bsSize='xs' error={ input.error } dirty={ input.dirty }>
  <Col componentClass={ ControlLabel } sm={4}>
    { input.label }
  </Col>
  <Col sm={8}>
    <InputGroup>
      <FormControl type="text" placeholder={ input.placeholder } value={ input.value } disabled= { disabled } { ...input }/>
      <InputGroup.Addon>
        <input type="checkbox" aria-label={ checkInput.label } { ...checkInput } disabled= { disabled }/>
      </InputGroup.Addon>
    </InputGroup>
  </Col>
</FormGroup>
```

At first I thought that I would put the `Field`s inside my component. One for each of the two fields. That didn't seem to make sense though as the error reporting and dirtyness needs to be known to the `FormGroup` which is outside of either of the fields.

Is the only option to use `formValueSelector`? The documentation makes that sound very unappealing if the whole form is going to start re-rendering whenever these values change.

**Comment by alurim** [comment]
@dpwrussell consider using a `Fields` component like I've defined here: https://github.com/erikras/redux-form/issues/841#issuecomment-226886437, I've run into the exact same problem and this was the solution I found worked best for me.

**Comment by gustavohenke** [comment]
@alurim is right.

@dpwrussell, if you have any further problems, let us know.
