### ISSUE TITLE
Uncaught TypeError: _this.runSyncValidate is not a function

### ISSUE THREAD

**Issue by quicksnap** [erikras/redux-form#133]
`Uncaught TypeError: _this.runSyncValidate is not a function`

You will see this in the `/survey` email field in redux-universal-hot-example. Too sleepy, can't look at it now..

**Comment by quicksnap** [comment]
The email field, when you blur off it. :zzz: :sleeping: :zzz: :sleeping: :zzz: :sleeping:

**Comment by erikras** [comment]
Just waking up here. I'll get it. Thanks!

Try not to dream of redux actions. :-)

**Comment by erikras** [comment]
Hmm... I'm not seeing this. You might have been hallucinating. :smile:

Let me know if it's still broken when the sun comes up.

**Comment by quicksnap** [comment]
Fresh install of `node_modules` with Node 4.2.0 / NPM 3.3.6:

http://www.gfycat.com/CautiousFirstAmericanalligator

**Comment by erikras** [comment]
released fix in v2.3.1.
