### ISSUE TITLE
[V6] [Discussion] would be any cause if we move initializing of form to componentDidMount ?

### ISSUE THREAD

**Issue by mihirsoni** [erikras/redux-form#1330]
Hi @erikras  

I know regarding initializing by exposed action API in redux-form, would does that make any difference if we move whole  initialize logic to `componentDidMount` instead of `componentWillMount` ? 

More over uses cases are , let's say you directly initialize form from either `localStorage` if you do it in `componentWillMount` you will see the Dom Difference from React as localStorage is not accessible on server side.

**Comment by gustavohenke** [comment]
I would say, yes, go ahead and do it. No problems IMO.
Let us know about any problems you found so to enhance the docs.
