### ISSUE TITLE
[V6 rc3] react-widgets (esp. Multiselect) example broken

### ISSUE THREAD

**Issue by melinath** [erikras/redux-form#1332]
Following c8829456f1569724ecc7d755c644366d6ff9ccbf all custom props are passed in under `props.input` rather than directly on `props`. This means that react-widgets can no longer find the props it relies on (i.e. for Multiselect, `props.data`, `props.valueField`, etc.)

Best workaround seems to be: Make a wrapper component for Multiselect that pulls the props out of input.

**Comment by melinath** [comment]
For some reason the contents of my multiselect component get wiped on every blur event.

**Comment by melinath** [comment]
Additionally, props.onBlur isn't a function, so as set up this keeps throwing errors – but if I remove that line then the multiselect element gets oddly blanked every blur event.

**Comment by erikras** [comment]
> Best workaround seems to be: Make a wrapper component for Multiselect that pulls the props out of input.

Yes.

**Comment by melinath** [comment]
Setting `onBlur={() => null}` works, but that means `blur()` isn't being called. Can't quite track where that's being set / what potentially vital function it should be doing. But that's a problem for another time I guess.

**Comment by gustavohenke** [comment]
The examples are better nowadays. Please open a new issue if problems persist.
