### ISSUE TITLE
[V6 r3] Improve documentation of submit behavior

### ISSUE THREAD

**Issue by melinath** [erikras/redux-form#1334]
The behavior of the 'submit' handling is very poorly defined. The [Submit Validation](http://redux-form.com/6.0.0-rc.3/examples/submitValidation/) docs are flat out wrong, as they define a "submit" function which isn't actually used properly in the actual component definition – it would need to either be passed into the reduxForm call as onSubmit or passed directly into handleSubmit as described in the [Props](http://redux-form.com/6.0.0-rc.3/docs/api/Props.md/) documentation.

Additionally, the docs are very unclear about the difference between handleSubmit and onSubmit. Even the FAQ titled [What's the difference between handleSubmit and onSubmit?](http://redux-form.com/6.0.0-rc.3/docs/faq/HandleVsOn.md/) is not helpful, as it speaks to general conventions in the react community rather than the actual implementation of this library. To make things worse, it describes onSubmit _exclusively_ as a prop on the form component which the provided handleSubmit should get passed to – when in fact, redux-form also supports an onSubmit property being passed to the wrapped form component which has its own semantics and which you definitely _should not_ be passing handleSubmit into.

In a more general sense, the documentation for submission is in a number of different spots, including: Props, Submit Validation, FAQ, reduxForm(), and SubmissionError. I could imagine a more fleshed-out version of Submit Validation being useful, though at that point it would more be a guide to submission in general rather than just about submit validation.

**Comment by ezekielchentnik** [comment]
agreed.  we just had to deal with figuring this out, and much explaining it to folks not real close to the code.

**Comment by melinath** [comment]
Is this a place that I could make a PR? How are the online docs being generated?

**Comment by clayne11** [comment]
The docs are generated from within the repo in the `docs` folder. If you make a PR you can update the docs for `v6` in that folder.

**Comment by NeXTs** [comment]
@melinath Oh mate, I had exact same thoughts but you described it much better!

**Comment by erikras** [comment]
I would definitely be open to doc improvement PRs.

**Comment by kwirke** [comment]
It would also be nice to point out in the API docs that handleSubmit() is calling onSubmit with 'dispatch' as the second parameter. Now you can only infer it from the Submit Validation example.

**Comment by melinath** [comment]
tbh I'm a little confused about the passing of dispatch to onSubmit – won't people generally just be using bound actions created with mapDispatchToActions? I'm guessing this is just me not being familiar with the convention / subsystem at work?

**Comment by kwirke** [comment]
Yes, generally, but Redux and react-redux both allow you to not use it. From react-redux API docs for 'connect':
> If you omit it [mapDispatchToProps param], the default implementation just injects dispatch into your component’s props.

I don't see why redux-form should be more opinionated than them, but this is a design choice and it's not mine to make, although it is good to consider it :)

**Comment by kwirke** [comment]
Yes, generally, but Redux and react-redux both allow you to not use it. From [react-redux API docs for 'connect'](https://github.com/reactjs/react-redux/blob/master/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options):
> If you omit it [mapDispatchToProps parameter], the default implementation just injects dispatch into your component’s props.

I don't see why redux-form should be more opinionated than them, but this is a design choice that is not mine to make, although it is good to consider it :)

**Comment by marr** [comment]
@melinath im not sure about the dispatch question, but `handleSubmit` will be a prop given to the `reduxForm` wrapped component. Say you have a container where you'd want to manage the forms submit, by calling `handleSubmit` in the wrapped form class, it will delegate up to the `onSubmit` prop passed to it.
```
class Container extends Component {
  handleSubmit(values, dispatch) {
    console.log(values)
  }
  render() {
    return<Form onSubmit={this.handleSubmit} initialValues={...} />
  }
}

class Form extends Component {
  render() {
    return <form onSubmit={this.props.handleSubmit}>
      ...
    </form>
  }
}
```

**Comment by gustavohenke** [comment]
I think the docs improved *a lot* since RC times.
Therefore, if you still think they must be improved in any way, please open a formal request to change the docs (or even better - open a PR yourself! Docs are very easy to change!).
