### ISSUE TITLE
[V5] Custom things from state don't appear in fields

### ISSUE THREAD

**Issue by kirill-konshin** [erikras/redux-form#1337]
Let's say, I have a following `state`:

``` json
{
  "form": {
    "myForm": {
      "myField": {
        "errors": ["Foo", "Bar"],
        "value": ""
      }
    }
  }
}
```

I expect that `errors` array will be available via:

``` js
let {fields} = this.props;
// do something with fields.myField.errors
```

Errors array gets populated to state on unsuccessful actions by `.plugin()` reducer. I am using reducers for everything including the async validation, when form is submitted then the promise-based action is dispatched (or I can dispatch an error synchronously instead if sync validation fails there), so I can wire to promise's error dispatch and propagate errors to appropriate fields.

**Comment by bmhaskar** [comment]
Similar thing is happening for me I am attaching plugin in store 
` form: formReducer.plugin({
        MyForm: MyReducer
    }),`

In MyReducer 

`switch (action.type) {
        case MY_ACTION:
            state = Object.assign({},state);
            state.myField.value = "1";
            return state;`

I don't get the updated field value in **componentWillReceiveProps**.  Is there any other way to achieve the same.

**Comment by bmhaskar** [comment]
My mistake I was looking at wrong place. I was looking at 
```javascript
this.props.fields.myField.value 
``` 
instead it is in
```javascript  
this.props.values.myField
```

**Comment by danielrob** [comment]
Closing with bulk close of v5 issues. If this issue still requires action and/or also affects v6/7, please request a reopen with details or raise a new issue. v5 PR's are still welcomed.
