### ISSUE TITLE
Pass context to synchronous validation

### ISSUE THREAD

**Issue by jcalfee** [erikras/redux-form#1338]
Looks like your passing values and props to the API validate callback: `validate(values, props)` .. It might be a good idea to include `this` so that would give access to global component variables and state.  Validation should be no more limiting than creating a component with manual validation.

**Comment by jcalfee** [comment]
Better yet, can you just bind the validation function to this?  That would be awesome, you don't need that awkward 3rd paramter.  If you did this already it just needs to be in the docs, that would not be obvious.

**Comment by erikras** [comment]
Interesting.... No, `validate` is not being bound to anything at the moment.

**Comment by jcalfee** [comment]
Now I have to validate against something in the state.  This time, no work around except to run my own form code..

**Comment by gustavohenke** [comment]
Adding the component's `this` doesn't feel like a good idea to me, however I fail to see a better way to access the component's state 😕

**Comment by gustavohenke** [comment]
More than two years have gone by without a comment here, so I'm closing!
