### ISSUE TITLE
Dynamic form could get fields out of order

### ISSUE THREAD

**Issue by joefiorini** [erikras/redux-form#1339]
I'm using redux-form to build forms configured in YAML. In the YAML, each field is configured as an object, then I specify each form as an object that has an array of field names. That array specifies the order of the fields. I then iterate over the fields object given to my by redux-form to render each field.

Although I haven't run into this as an issue yet, it seems like there is a risk of my fields coming back in the wrong order. Since redux-form creates an object out of the array I hand in, and (afaict) does not pass the original array on to the decorated component, I lose the ability to use that array to guarantee I'm iterating over the fields in the original order.

What if we passed the original array of fields (maybe called `fieldsList`?) along with the generate fields object? An alternative might be to make `fields` be a Map instead of an object, since Maps [do guarantee key order](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map#Objects_and_maps_compared).

**Comment by zombieJ** [comment]
+1, I have the same concern.

**Comment by kristian-puccio** [comment]
I do a very dynamic form with redux-form and I pass through an array of
'widget' definitions that I generated the array of field strings from.

I pass this as widgets but can be anything.
Each 'widget' contains info like input type, label etc.

If you use v6 you no longer need to generate the list of fields and just
reregistering a widget with a form using Field is enough.

**Comment by joefiorini** [comment]
@kristian-puccio I opened this before I had looked at v6 in detail. Closing since redux-form will no longer have this issue. Thanks!
