### ISSUE TITLE
Feature: ability to define implications of a change on another field

### ISSUE THREAD

**Issue by jussi-kalliokoski** [erikras/redux-form#134]
Consider a pretty common subscription scenario where there's a form with two fields:

* Contract period.
* Billing period.

There's also a constraint that billing period can't be greater than contract period, for obvious reasons. This can already be modeled in `redux-form` with a validate function, that makes the other billing period error if you change the contract period to be lower than the contract period. However, I personally try to build UIs in a fashion that errors that the user must manually fix are used only as a last resort, which is not the case in examples like this. Instead we can limit the billing period options to be capped at the contract period and when contract period gets changed, cap the billing period value at that value as well.

Currently I have to resort to making a special-case reducer just for this, replicating parts of redux-form (like `pristine`, `submitting`). Would be cool to be able to define relationships in some sane way. I'm not sure what that would be, yet. Maybe just a function that takes the old values and new values and returns the proper new values.

```javascript
function mapValues (values) {
  return {
    billingPeriod: Math.min(values.billingPeriod, values.contractPeriod),
    contractPeriod: values.contractPeriod,
  };
}
```

This could also be used for providing defaults instead of the `undefined`s you get now and would match the error behavior with the value behavior.

**Comment by erikras** [comment]
Seems like this could be done with a [normalizer](https://github.com/erikras/redux-form#normalizing-form-data). Am I wrong?

**Comment by erikras** [comment]
```js
form: formReducer.normalize({
  billingForm: {
    billingPeriod: (value, previousValue, allValues) =>
      Math.min(value, allValues.contractPeriod)
  }
```

**Comment by jussi-kalliokoski** [comment]
Oh I missed that part of the docs, jumped it over because I thought it was about [gaearon/normalizr](https://github.com/gaearon/normalizr), sorry.

Thanks a lot! :heart: May I ask why this is in the reducer while the validation is in the form annotation? I'm feeling a bit uncomfortable with the missing link when someone looking at the form code has to figure out where behavior like this has been defined as normally they have the actions to guide them (it dispatched this action -> this reducer is listening to that type of action). But I suppose they should consult the redux-form docs in that case or I should leave a hint in the component.

**Comment by erikras** [comment]
Excellent point about the dichotomy, but it really is necessary, as there are two parts to redux-form, the component and the reducer, and they are each in charge of validation and normalization respectively. I suppose that the component _could_ normalize in the `onChange` function, but it really is a superior design for the reducer to be in full control over its data, just receiving actions and modifying state.
