### ISSUE TITLE
[v6 rc3] Field should use this.props.children instead of component props

### ISSUE THREAD

**Issue by thecaddy** [erikras/redux-form#1340]
Title pretty much says it.  I'm using the release candidate of version 6 and it doesn't follow the way you'd typically use a react component child.  Passing components as props along with a separate props prop feels clunky and error prone. 

The render of Field should use `this.props.children` and the render return the Field props.

```
var cloneWithProps = require('react-addons-clone-with-props');

class Field extends Components {
  ...
  render(){
    return cloneWithProps(this.props.children, {...propsPassedByField});
  }
}
```

It would be used like this:

```
const RenderField = props => (
  <div>
    <div
      <span>{props.things}</span>
      <input {...props.input}/>
    </div>
    {props.touched && props.error && <span>{props.error}</span>}
  </div>
)

class Inputs extends Component {
  render() {
    <Field type="text"
      name="field">
      <RenderField things={this.props.things} />
    </Field>
  }
}
```

instead of:

```
const RenderField = props => (
  <div>
    <div>
      <span>{props.things}</span>
      <input {...props.input}/>
    </div>
    {props.touched && props.error && <span>{props.error}</span>}
  </div>
)

class Inputs extends Component {
  render() {
    <Field type="text"
      component={RenderField}
      props={{things: this.props.things}}
      name="field"/>
  }
}

```

**Comment by wmertens** [comment]
It's a pick your poison situation: Either make it obvious that your
component will be messed with, using a less-obvious syntax, or magically
provide the props that influence the input field, at the cost of a copy.

Personally I dislike magic, unless it is very clear what will happen.

Anyway, both syntaxes can coexist at the tiny cost of a null check on
props.component…

**Comment by chrisbateman** [comment]
I think there's already some confusion about how the `<Field>` props work with the current setup.

For example, in the above example with `props={{things: this.props.things}}` - in the RenderField component, "things" is available at `this.props.input.things` - not `this.props.things`. Which causes issues in React 15 since you're not supposed to pass random props to native elements.

So that pretty much leaves you without a way to pass props to RenderField.

**Comment by thecaddy** [comment]
@chrisbateman thats exactly right and why this would be better served using `this.props.children` cloning with props than the current way where props passed in are attached to input and thus doing a spread will throw an error.

I understand the "pick your poison" @wmertens is talking about however, the passing of props to `props.input` leaves more confusion and opens the doors to error more so than simple check on conflicting props on the child before cloning.

**Comment by thecaddy** [comment]
```
const RenderField = props => (
  <div>
    <div
      <span>{props.input.things}</span>
      // This will puke in 15.2 because of things
      <input {...props.input}/>
    </div>
    {props.touched && props.error && <span>{props.error}</span>}
  </div>
)
```

**Comment by wmertens** [comment]
I thought the whole point of .input was to only provide props that DOM
input elements understand?

**Comment by thecaddy** [comment]
> I thought the whole point of .input was to only provide props that DOM
input elements understand? @wmertens

Agreed, thus why passed props shouldn't be attached to `input`, and using a nested component with its own props and parent `Field` component wrapping it will attach its necessary props including `input`.

**Comment by mattkrick** [comment]
call me trashy, but I just call this from my `renderField`:

```
const makeDomInput = (input) => ({
  autoFocus: input.autoFocus,
  name: input.name,
  onBlur: input.onBlur,
  onChange: input.onChange,
  onFocus: input.onFocus,
  placeholder: input.placeholder,
  type: input.type,
  value: input.value,
});
```

In my mind, there are 2 discrete entities, `input` and `domInput`, the latter being a subset of the former. @erikras did us a solid by grouping the `input` together in 1 clean object, it isn't too hard to weed out your custom stuff (although having this built-in would be just super).

**Comment by richardscarrott** [comment]
@thecaddy I think I agree with you, it feels a little more natural passing it as a child. You could perhaps wrap `<Field />` like this:

```
function MyField({ children, ...other }) {
    return (
        <Field {...other} component={(props) => {
            return cloneElement(children, props)
        }} />
    )
}

<MyField>
    <MyInput />
</MyField>
```

**Comment by erikras** [comment]
Quite a bit of thought went into this when crafting `v6`. Believe me, I also find the passing of a component as a prop mildly disgusting. It breaks the whole XML-y feel of the JSX, which _feels_ wrong to those of us who have been closing tags for decades. However, the trade off was made for the following reasons:

* Ultimately the library user has more control
* Reduced magic

> both syntaxes can coexist at the tiny cost of a null check on `props.component`…

The `cloneElement()` method is one of the items to be investigated once `v6` ships, so it is entirely possible that this syntax might come to `redux-form`.

Thank you all for your thoughtful discussion on this topic.

**Comment by chrisbateman** [comment]
@erikras In the meanwhile, is there a recommended way to pass custom props to components? Just have to extract them from props.input (see #1397)?

**Comment by stevemao** [comment]
With
```js
const RenderField = props => (
  <div>
    <div
      <span>{props.things}</span>
      <input {...props.input}/>
    </div>
    {props.touched && props.error && <span>{props.error}</span>}
  </div>
)

class Inputs extends Component {
  render() {
    <Field type="text"
      name="field">
      <RenderField things={this.props.things} />
    </Field>
  }
}
```

It's still not obvious where/how you pass `props.input` to `RenderField`. It's too much magic. I think the right pattern is to use *HOC*:

```js
const RenderField = props => (
  <div>
    <div
      <span>{props.things}</span>
      <input {...props.input}/>
    </div>
    {props.touched && props.error && <span>{props.error}</span>}
  </div>
)

const Input = withField({
  type: 'text',
  name: 'field'
})(RenderField)
```

If you want to pass extra props, just simply compose with `withProps` from [`recompose`](https://github.com/acdlite/recompose)

**Comment by gustavohenke** [comment]
I didn't read the whole thread with lots of attention, but sounds like it was about the way custom props were handled in old v6 RC versions.

This is pretty much stable nowadays -- you may pass them to `Field` directly or via [`props` prop](https://redux-form.com/7.2.1/docs/api/field.md/#-code-props-object-code-optional-). Also the docs on `Field` are quite good on that subject.

Any other changes, please open a new issue or a PR.
