### ISSUE TITLE
Should I use v5 or v6

### ISSUE THREAD

**Issue by cristian-sima** [erikras/redux-form#1346]
Hi. I am new to redux-form and I've seen there are 2 version.

Therefore, my question is simple. Should I learn v5 or v6?

**Comment by cristian-sima** [comment]
I have a feeling that v6 is more interesting :)

**Comment by cristian-sima** [comment]
And if you say v6, which version should I use?

**Comment by cristian-sima** [comment]
I have chosen v6 :d

**Comment by jontewks** [comment]
![image](https://cloud.githubusercontent.com/assets/3970573/16849661/5bba21be-49b0-11e6-954f-01c0d7890b79.png)
