### ISSUE TITLE
[v6 alpha.15] [possible bug] Submit Validation Example

### ISSUE THREAD

**Issue by cristian-sima** [erikras/redux-form#1347]
[That code](http://redux-form.com/6.0.0-alpha.15/examples/submitValidation/) that does not work, but if I do in `SubmitValidationForm.js` in `renderField` function: 

![image](https://cloud.githubusercontent.com/assets/12199042/16838704/48372e5c-49d3-11e6-8d24-3219136f25f2.png)

```

      <input {...props.input}/>

```

rather than

![image](https://cloud.githubusercontent.com/assets/12199042/16838696/3d5ec4f4-49d3-11e6-8db6-79445b10f205.png)

```
      <input {...props}/>

```

then it works

**Comment by sknoslo** [comment]
It looks like you are using the latest version of redux-form but looking at "old" documentation. This was a recent change (#1276). You can find the proper docs [here](http://redux-form.com/6.0.0-rc.3/examples/submitValidation/).

**Comment by cristian-sima** [comment]
Nice :D Thanks

**Comment by cristian-sima** [comment]
@sknoslo It seems all the examples send to the `6.0.0-rc.1` version while it is `6.0.0-rc.3`

Is that the way it should be?

**Comment by sknoslo** [comment]
@cristian-sima I'm not sure but I'm guessing a lot of the examples just haven't been updated to reflect that change. So when reading rc.1 docs just make sure you are passing ```...props.input``` into your input components rather that just ```...props```.
