### ISSUE TITLE
[v6 alpha.15] [possible bug] Broken link

### ISSUE THREAD

**Issue by cristian-sima** [erikras/redux-form#1348]
On [this page](http://redux-form.com/6.0.0-alpha.15/examples/simple/)

![image](https://cloud.githubusercontent.com/assets/12199042/16840598/328ebda8-49de-11e6-9a47-3bd147f3fbfb.png)

**Comment by gustavohenke** [comment]
Fixed sometime in the past 👴 

Have a happy 2017!

**Comment by cristian-sima** [comment]
Happy new 2017 code year!
