### ISSUE TITLE
Define redux and react-redux as peer dependencies

### ISSUE THREAD

**Issue by ooflorent** [erikras/redux-form#135]
Locking `redux` and `react-redux` is really annoying since it prevents using newer versions (or may duplicate packages). This is a problem since react 0.13 will use `react-redux@3.*` and 0.14 `react-redux@4.*`.

**Comment by erikras** [comment]
Sounds reasonable. PR it?

**Comment by ooflorent** [comment]
Well, do you still react@0.13 support?

**Comment by erikras** [comment]
I have a project that depends on a lib that requires 0.13, which means that I cannot upgrade all the other libs that have left 0.13 behind, which sucks.

I'm not aware of any of the code in this library that would be incompatible with supporting both 0.13 and 0.14, so if it's possible to define the peer dep in such a way that it would work with a 0.13 project and a 0.14 project, that seems like it would be more flexible. But if it's not possible, then I guess we can require 0.14. Clearly, the react-redux train is moving on without 0.14, so I redux-form should probably be on it.

Was that ambiguous enough of a decision? :smile: TL;DR: 0.13 would be nice, but not necessary.

**Comment by erikras** [comment]
Awesome. Thanks, @ooflorent! Released as `v2.2.8`.

**Comment by ooflorent** [comment]
You're welcome! I needed this update :wink:
