### ISSUE TITLE
Performance / Rerendering

### ISSUE THREAD

**Issue by s4ge** [erikras/redux-form#1350]
Taking the following code: 

``` jsx
renderField(field) {
    const hasError = field.touched && field.error;
    const props = {
      ...field.input,
    };

    if (hasError) {
      props['data-content'] = field.error;
    }

    return (
      <div className={`field${hasError ? ' error' : ''}`}>
        <input {...props} />
      </div>
    );
  }

  render() {
    const { submitting, handleSubmit } = this.props;

    return (
      <form ref="form" className="ui attached fluid form segment" onSubmit={handleSubmit}>
        <Dimmer visible={submitting} inverted />
        <Field
          component={this.renderField}
          name="email"
          placeholder="E-Mail Addresse"
        />
        <Field
          component={this.renderField}
          type="password"
          name="password"
          placeholder="Passwort"
        />
        <Field
          component={this.renderField}
          type="password"
          name="passwordConfirmation"
          placeholder="Passwort wiederholen"
        />
        <div className="ui divider"></div>
        <button
          className="ui fluid teal labeled icon button"
          disabled={submitting}
          type="submit"
        >
          <i className="user icon"></i>
          Benutzer erstellen
        </button>
      </form>
    );
  }
```

Leads to the following wasted times, for **just putting focus on the first field**:

```
0   "ReduxForm > Connect(Form(Form))"   2.83    1   1
1   "Field > Connect(ConnectedField)"   2.74    3   3
2   "Connect(ConnectedField) > ConnectedField"  0.41    1   1
3   "ConnectedField > renderField"  0.15    1   1
```

Typing 3 chars into the first field then makes things even worse:

```
0      "Field > Connect(ConnectedField)" 0.37 2 8
```

Just check it for yourself using the perf addon.
I can just guess how bad things could become when my forms grow.
I did not check your code so far, but do you use immutable already?

**Comment by s4ge** [comment]
Things became true. The update leak grows exponentially with the amount of fields. With a couple of fields in my form, I get 129 wasted renders for Connect(ConnectedField), creating a wasted render time of 6.16ms. My form isn't finished yet but it's already hard to enter data.

**Comment by erikras** [comment]
Your `this.renderField()` function is not actually getting called except when it absolutely needs to. Render out a `{{++renders}}` counter to see this. I don't fully understand what the `printWasted()` is displaying. Sort of by definition, every time your Redux state changes, `Connect` has to figure out if the slice it is listening to has changed, so for every connected component on your page, `Connect` is going to register a "wasted" update.

> My form isn't finished yet but it's already hard to enter data.

You are actually seeing lag in the UI performance? If you can share a demo of this, that would be very helpful.

**Comment by melinath** [comment]
I'm seeing this as a big problem on our form, which has about 200 fields displayed. Every time I type in a field, the form has to run mapStateToProps on every field displayed in order to determine whether something has changed. Although each mstp call is small on its own, they have added up to make the interface extremely laggy.

**Comment by melinath** [comment]
<img width="627" alt="screen shot 2017-04-11 at 11 37 33 am" src="https://cloud.githubusercontent.com/assets/299979/24924899/4d21760e-1eab-11e7-89e0-48d12473f572.png">

The steps I took to produce these times / render counts were:
1. Click on a field.
2. Type once.
3. Click off the field.

**Comment by melinath** [comment]
Here's a gif showing the performance. I'm typing at normal speed on these inputs.

![redux-form-slow](https://cloud.githubusercontent.com/assets/299979/24925081/f9c679ae-1eab-11e7-84e0-8ffbdba280fe.gif)

**Comment by melinath** [comment]
In our case, this seems to have been a red herring after all - although it _looked_ like the slowdown was in redux-form, the actual issue was that we had some inefficiency in other MSTPs for the view and in our shouldComponentUpdate calls. Along the way we also experimented with not using redux-form Fields and instead calling registerField / unregisterField manually, which did seem to offer a _slight_ performance boost.

**Comment by danielrob** [comment]
Closing since it's been precisely a year with no response.
