### ISSUE TITLE
[6.0.0-rc.3] redux-form have a dependency of "react-addons-shallow-compare": "^15.2.0"

### ISSUE THREAD

**Issue by rockallite** [erikras/redux-form#1351]
When I run `npm i redux-form@6.0.0-rc.3`, it yells:

```
└─┬  redux-form@6.0.0-rc.3 
  ├── es6-error@3.0.1 
  ├── UNMET PEER DEPENDENCY react@^15.2.1
  └── react-addons-shallow-compare@15.2.1 
```

Currently I'm still using React 15.1 because of the [unknown props warning](https://facebook.github.io/react/warnings/unknown-prop.html) introduced in 15.2. And I notice that there is a weird dependency in `package.json` of redux-form v6.0.0-rc.3:

```
"react-addons-shallow-compare": "^15.2.0"
```

This effectively forces us to use React 15.2. Is this a mistake?

**Comment by nvma** [comment]
Unknown props warning with React 15.2.1 has been fixed in rc2. As per https://github.com/erikras/redux-form/issues/1249#issuecomment-230032764.
https://github.com/erikras/redux-form/releases/tag/v6.0.0-rc.2

**Comment by rockallite** [comment]
Thanks @nvma . I use React 15.1 because there are still third-party libraries which aren't updated to support React 15.2, and are currently used in my project.

But that's not the key problem. The problem is that the `"react-addons-shallow-compare": "^15.2.0"` dependency prevents us from using any versions of React lower than 15.2.

My question is:

* Is this dependency of the specific version `^15.2.0` necessary?
* If that's true, is redux-form incompatible with React 15.1 and below since v6?

**Comment by erikras** [comment]
No, it's not required. This should be fixed to allow 15.1.

**Comment by rockallite** [comment]
Should it allow 0.14.x, too? 😄

**Comment by erikras** [comment]
Hmmm... I can't recall what all that would entail.

**Comment by rockallite** [comment]
React 0.14 is the last version that supports IE8.

However, I see source code with `Object.defineProperty(..., {enumerable: true})` usage (in `fieldValue.js`), and this will [silently fail in IE8 even with es5-shim](https://github.com/es-shims/es5-shim#may-fail).

So, you're right, @erikras. I think there's no reason to support React 0.14 now.

**Comment by gustavohenke** [comment]
Dependency removed by #1331
