### ISSUE TITLE
[6.0.0-rc.3] Field props not passed to component

### ISSUE THREAD

**Issue by chrisbateman** [erikras/redux-form#1353]
Neither extra properties nor the`props` property on `<Field>` are being passed to the child component.

Looking in the devtools - you can see them on the `ConnectedField` - but that's where they stop.

This means that the following example from the docs does not work (`disabled` isn't passed to `renderField`):

```javascript
const renderField = (field) => (
    <div class="input-row">
      <input type="text" {...field.input}/>
      {props.touched && props.error && !props.disabled && <span className="error">{props.error}</span>}
    </div>
  )

// inside your render() method
<Field component={renderField} props={{ disabled: true }} />
```

**Comment by chrisbateman** [comment]
So I was confused about where the props were supposed to go (on the `input` property, rather than the root-level props). May open another issue for this (since it restricts the use of some form components inside `<Field>`).

The example isn't working because of props-vs-field mixups.

**Comment by jmarceli** [comment]
I'm experiencing same issue. Did you find any workaround/solution?

**Comment by jmarceli** [comment]
I've found correct way to use props. See example in #1360
