### ISSUE TITLE
Value shouldn't look for a prop within the object

### ISSUE THREAD

**Issue by eloytoro** [erikras/redux-form#1355]
Im having issues creating complex value types that instead of holding strings hold objects/bools/arrays or any other thing.
But this really puzzled me https://github.com/erikras/redux-form/blob/v6/src/events/getValue.js#L41
I had to read the source to figure out what was going on.
Turns out calling `onChange` with an object that has a `value` key will use the value of that key as the new value, which is very cryptic.
Please remove this

**Comment by erikras** [comment]
Published in [`v6.0.0-rc.4`](https://github.com/erikras/redux-form/releases/tag/v6.0.0-rc.4).
