### ISSUE TITLE
[6.0.0.rc-3] Documentation update required

### ISSUE THREAD

**Issue by jmarceli** [erikras/redux-form#1360]
Section **Redux / Form /API** is outdated. See #1353.
Stateless function example should (probably) look like this:

```
// outside your render() method
const renderField = (field) => (
    <div class="input-row">
      <input type="text" {...field.input}/>
      {field.input.touched && field.input.error && !field.input.disabled && <span className="error">{field.input.error}</span>}
    </div>
  )

// inside your render() method
<Field component={renderField} props={{ disabled: true }} />
```

I would make a pull request with this updated example but I don't know where is documentation repo.

**Comment by chrisbateman** [comment]
There's been a little bit of discussion at #1340. I would argue that this behavior should be changed, since it prevents you from passing custom props to the component.

**Comment by marr** [comment]
this is an important one, esp with the major breaking changes in v6, its important to get the docs/upgrade guide right
