### ISSUE TITLE
V6 - Question about shouldComponentUpdate in reduxForm.js

### ISSUE THREAD

**Issue by Darmody** [erikras/redux-form#1362]
https://github.com/erikras/redux-form/blob/v6.0.0-rc.3/src/reduxForm.js#L167

Should it be changed to using shallow equal?

There is a problem, if I change the initialValues, component won't update because the check for initialValues be skipped.

**Comment by gustavohenke** [comment]
Can you elaborate your issue, please?
What's the deal with how `shouldComponentUpdate` is implemented?

**Comment by Darmody** [comment]
I think this question is outdated.
