### ISSUE TITLE
[6.0.0.rc-3] Question formValueSelector

### ISSUE THREAD

**Issue by BryIsAZombie** [erikras/redux-form#1363]
Is there any straight forward way to get all of the values out of Redux store?
I have a multi-tab wizard and am going to display a review page of about 30 values for the final step. So far only seeing formValueSelector and specifying multiple fieldNames.

**Comment by thecaddy** [comment]
There should be a way to pull all values from the form with a single call since... you know, its a form you typically have all the fields together for a reason.

**Comment by BryIsAZombie** [comment]
Went about it by connecting the last page to the store and using .values on the form.

```javascript
KioskFormFourthPage = connect(
  // Selecting all values out of store to display for review
  state => ({
    kioskValues: state.form.kiosk.values
  })
)(KioskFormFourthPage);
```
