### ISSUE TITLE
Change field value and submit immediately

### ISSUE THREAD

**Issue by igorbarbashin** [erikras/redux-form#1366]
I'm kind of stuck trying to programmatically set a value for some field and programmatically submit the form.
Not sure if I chose the right strategy in first place, but hopefully figuring it out will make me better understand redux and redux-form.

Basically I want to archive my record by clicking "Archive" button. It should set `active` field to false and submit at the same time.

Here's what I'm trying in the form component:
```javascript
constructor() {
    super();
    this.handleArchive = this.handleArchive.bind(this);
  }

handleArchive() {
    // I see the CHANGE event in Redux dev tools and it does change the field value
    this.props.dispatch(this.props.change('active', false));

    // But this field value is still true when form submits
    const submitter = this.props.handleSubmit(this.props.onSubmit);
    submitter();
  }
```

So I guess there's some sort of race condition, though I thought redux should be synchronous by nature.
Anyways, I tried to wrap the submitter in `setTimeout` and it worked! (though it looks like a yucky hack)

```javascript
handleArchive() {
    this.props.dispatch(this.props.change('active', false));
    setTimeout(() => {
      const submitter = this.props.handleSubmit(this.props.onSubmit);
      submitter();
    }, 0);
  }
```

Is there a better way of doing that?

**Comment by igorbarbashin** [comment]
Actually it's not that bad and I found a concise inline code for it:
```jsx
<Button
  onClick{() => {
    dispatch(change('active', false));
    setTimeout(() => handleSubmit(onSubmit)());
>
  Archive
</Button>
```

**Comment by harlynx** [comment]
I ran into the same issue, but I do not like timeout hacks. I approached this the following way.

```javascript
change('active', true);
handleSubmit(values => onSubmit({ ...values, active: true }))();
```

I would prefer a more intuitive way of achieving this though.

**Comment by jordanmkoncz** [comment]
I ran into this issue as well, @harlynx's solution worked for me in redux-form v6.5.0.

**Comment by mlippens** [comment]
Why does everyone insist on using a `setTimeout`? How can that even be reliable? On any issue or topic that suggests a solution this seems like the people suggest most often. I like @harlynx approach better then, at least it has a guarantee to be consistent, at least if you only change one field at a time.

**Comment by zelongc** [comment]
Came across the same issue here. you guys are awesome.

**Comment by zelongc** [comment]
` 
  submitToReview () {
    const formValues = this.props.study.values;
    const valueToSubmit = Object.assign({}, formValues, {state: 'REVIEWING'});
    this.onSubmit(valueToSubmit, this.props.dispatch);
  }
`
This is my final solution to achieve 'Changing value before submiting' + 'remote submit'. Hope it helps others.
Thanks to @harlynx @igorbarbashin

**Comment by tommyalvarez** [comment]
> I ran into the same issue, but I do not like timeout hacks. I approached this the following way.
> 
> ```js
> change('active', true);
> handleSubmit(values => onSubmit({ ...values, active: true }))();
> ```
> 
> I would prefer a more intuitive way of achieving this though.

Where do you get the 'values' variable from ?
