### ISSUE TITLE
onSubmitFail async errors

### ISSUE THREAD

**Issue by kristian-puccio** [erikras/redux-form#1367]
Async errors aren't being reported in the onSubmitFail function.

I'm pretty sure this functionality exists in v5.

**Comment by erikras** [comment]
I mean for them to be, so if they are not, this is a bug. A failing test would be a nice thing to provide. 😉 

I'm on vacation this week so I won't get back to this for a few days.

**Comment by kristian-puccio** [comment]
coolio, I'll look at getting you a test.

Enjoy your holiday 👍

**Comment by stevenmusumeche** [comment]
This is still a problem.  Any progress?

**Comment by chirag04** [comment]
I'm hit by this. errors are reported on first submission. On second submission, asyncValidate is not called and onSubmitFail is called without erros.

**Comment by chirag04** [comment]
`persistentSubmitErrors` solves the problem for me. I couldn't find any documentation on it tho.

**Comment by danielrob** [comment]
[This](https://github.com/erikras/redux-form/blob/1f08e34d0f9809898396b3e40ab1e1ba0966377c/src/__tests__/handleSubmit.spec.js#L147) & [this](http://redux-form.com/7.0.3/docs/api/ReduxForm.md/#-code-onsubmitfail-function-code-optional-) I think that well and truly closes this issue. Advise otherwise if otherwise!

**Comment by chirag04** [comment]
@danielrob my comment is still valid: https://github.com/erikras/redux-form/issues/1367#issuecomment-249400487

I tested right now on v7.03

**Comment by erikras** [comment]
Published fix in [`v7.0.4`](https://github.com/erikras/redux-form/releases/tag/v7.0.4).
