### ISSUE TITLE
Can we open an issue for implementing in-build autosuggest with redux-form

### ISSUE THREAD

**Issue by nitte93** [erikras/redux-form#1374]
In my recent project I had a need for implementing one of the fields as auto suggest.
While Redux-form is superbly good with other form related actions, integrating a plain auto-suggest with a simple validation  requires importing a couple of 3rd part modules / or if you want to integrate your know auto-suggest then that too comes at a cost of 100s of healthy hair.
My suggestion is why not implement an in-build autosuggest with Redux-form

**Comment by gustavohenke** [comment]
Visual components do not belong into Redux Form core project.
Thanks for using Redux Form!
