### ISSUE TITLE
Requesting a Redux Form submit via a redux action

### ISSUE THREAD

**Issue by moredip** [erikras/redux-form#1376]
# Background

We are using Redux Form to build a large wizard-y workflow which involves 10+ screens of forms (what fun!). We've been really enjoying Redux Form so far, it's made this work very straightforward.

![wireframe]
(https://gist.github.com/moredip/64ff8ebed1471c607b7388cf75373ff5/raw/fece494cd44768b35f5816f84b94d9d459657b9b/wireframe.jpg)

# Problem

As you can see from my hi-fidelity wireframe we have a sidebar nav which allows the user to navigate between form screens. When a nav item is clicked we want to be able to trigger a Redux Form submit, both to save the changes in the form and also to perform validation. However we haven't found a clean way to do this using Redux Form.

# Current Solution

Our current solution is to wrap each form component inside a stateful component which uses a `ref` to capture the `submit` function which Redux Form exposes on the form component - pretty much exactly as shown in [the Submit From Parent example in the docs](http://redux-form.com/5.3.1/#/examples/submit-from-parent). However we then have to register that submit function in a central registry so that when a nav item is clicked we can trigger the function. We need to use that central registry because the nav component is quite far away from the form components in the React hierarchy.

We're not super happy with this approach. It requires us wrapping all our forms with another component, and just generally doesn't feel very 'redux-y'. We'd much rather have clicks on a nav item trigger a redux action and handle things inside a reducer. Unfortunately this doesn't really seem possible because Redux Form doesn't expose a way to trigger form submit via an action, only via the submit function exposed on the stateful form component itself.

Is there a better way to do this? Is there some way we can get the same functionality without having to capture the submit function? Are we just fundamentally approaching this the wrong way?

**Comment by moredip** [comment]
Oh and of course I'm very happy to elaborate further on how our current solution works, or share any other info that's needed.

**Comment by kristian-puccio** [comment]
Try have a look at the wizard example. I have a similar situation and just
trigger a save to local storage on submit then without unmounting the form
(see wizard) I show the next section.

**Comment by moredip** [comment]
@kristian-puccio thanks for the pointer, but I'm not sure that example helps much here. The main issue for us is that we need to invoke trigger a form submit (or perhaps just a validation) from somewhere where we don't have a direct reference to the form components. In the wizard example the coordination between form pages is done from a parent component that has access to all the things it needs. 

That's sort of how we're implementing it now, but it feels a bit kludgey and we'd prefer to use a more redux-centric approach.

**Comment by kristian-puccio** [comment]
Have a look at the action creators
http://redux-form.com/6.0.0-rc.3/docs/api/ActionCreators.md/

It allows you to dispatch an action to trigger those events from anywhere.

I believe this functionality exists in v5 as well

**Comment by erikras** [comment]
The only thing you cannot currently do via a dispatched action is actually submit the form. That is because there is a sequence of things that happens on form submit, and I have not yet figured out exactly how that could be done, but it is an objective post `v6` release.

You could potentially use an [HOC drill](https://medium.com/@erikras/the-hoc-drill-pattern-a676a3889ced#.h0are77es) to expose deeper API to your higher level components.

**Comment by moredip** [comment]
Thanks @erikras. I think our current approach is pretty close to that HOC drill pattern. We're passing a `registerSubmit` function into each component, which as I understand it is the equivalent to `methodCallback` in your HOC drill example. 

Sounds like for now this is our best option. Feel free to close this issue as you see fit.

**Comment by diegohaz** [comment]
Hey, guys, I've published [redux-form-submit](https://github.com/diegohaz/redux-form-submit), which adds the submit action creator to redux-form. It still has some limitations, but maybe we can add this to redux-form itself in the future.
