### ISSUE TITLE
Number input value returns a number, not a string

### ISSUE THREAD

**Issue by RHavar** [erikras/redux-form#1377]
In the case of an `<input type="number">` form field, getting the value is returning a number.

This is inconsistent with the documentations
`The value of this form field. It will be a boolean for checkboxes, and a string for all other input types.`

As well inconsistent normal DOM behavior (i.e. if you access the dom directly). It makes doing some validation impossible, like telling the difference between when a user entered "1.1" (allowed) and "1.1000" (not allowed) or "1.1000000000000001" which all are being converted to 1.1, making validation impossible

**Comment by RHavar** [comment]
Hm, I see when it's provided to the validate function it's actually a string. It's just if you access it via  this.props.fields.x.value  it's a number. I guess really just the documentation should be updated

**Comment by RHavar** [comment]
This applies to `6.0.0-rc.3` as well

**Comment by gogoge** [comment]
Seems the behavior has been changed in v5.3.0 ?

References:
- [5.3.0 release note, change the behavior about input type](https://github.com/erikras/redux-form/releases/tag/v5.3.0)  

>  Feature: type="number" inputs will now be detected and the values returned will be a Number. If this breaks something in your form, switch your input to type="text" and it will behave as before. #1100

- [Document about the input type](https://github.com/erikras/redux-form/blob/428e9f06b8f6e5deace99eb6ab17b61739cb31d9/docs/api/Field.md#inputvalue-any)

**Comment by danielrob** [comment]
@RHavar could you confirm this no longer applies? Numbers appear to now be being returned as strings: https://codesandbox.io/s/ppo3YXy2.
