### ISSUE TITLE
6.0.0-rc.3 import { propTypes } from 'redux-form' => undefined

### ISSUE THREAD

**Issue by stipsan** [erikras/redux-form#1378]
Acording to the docs it should be possible to import it and use it in the wrapped component:
http://redux-form.com/6.0.0-rc.3/docs/api/Props.md/

My team haven't used previous releases of redux-form so if this breakage happened in this particular release is unknown.

**Comment by olslash** [comment]
+1 -- is this a build issue? https://github.com/erikras/redux-form/blob/master/src/index.js#L27

**Comment by andrewtorres** [comment]
+1

**Comment by erikras** [comment]
Can someone confirm that this is still a problem in 6rc4?

**Comment by andrewtorres** [comment]
I am currently using 6rc4 and the problem still persists. This is where I had first noticed the issue.

**Comment by gustavohenke** [comment]
This was fixed by some older release 👴
