### ISSUE TITLE
UPDATE_SYNC_ERRORS being called after I start typing

### ISSUE THREAD

**Issue by nyjy85** [erikras/redux-form#1381]
So something weird is going on in my form.  When I focus into an input to start typing, it stops after the first letter and I have to focus into the input again with my mouse to continue typing.  I looked at the actions and when I type in the first letter, it dispatched action UPDATE_SYNC_ERRORS.  Could this be the reason why this issue is occurring?  If so, what can I do to fix this?

**Comment by clayne11** [comment]
Are you creating a component inside the `render` function like this?

```javascript
<Field 
  name='test'
  component={() => <div/>}
/>
```

If so, `React` is unable to detect that it's the same component because it's actually a different instance. You need to declare your components outside of `render`.

**Comment by nyjy85** [comment]
@clayne11 I was creating the component inside the render.  When I took it out, it worked!  Thank you!!

But now I've run into another problem.  The form I'm using is repeated based on the number of travelers.  So there are 2 instances of the same form.  When I fill in the value of the first form, it also fills it in the for the second form - so there's some sort of two-way binding going on.  Do you know what is causing this?

**Comment by clayne11** [comment]
The whole point of `redux-form` is that it stores all of the values of the form inside the `redux` store. There is a single source of truth which is the store. You can only have one instance of each form.

You can either:

1. Create a new form name, such as `traveler-1`, `traveler-2` dynamically
1. Use a `FieldArray` and have each instance of the form be a member of the array.

Depending on your use case one of those should work.

**Comment by nyjy85** [comment]
Ok I see.  I'm having a little trouble understanding how FieldArray works in my case.  The examples I see are mapping through a property called 'fields'.  I need mine to map through the number of travelers, which in this case is 2.  Traveler's is an array of traveler objects which is on props, so it's accessed via `this.props.travelers`.  This is what my render looks like:

```
class TravelerForm extends React.Component {
  render () {
    return (
      <div>
        <FieldArray name='travelers' component={renderTravelers} props={{travelers: this.props.travelers}} />
      </div>
    )
  }
}
```
And this is what `renderTravelers` looks like:
```
const renderTravelers = props => (
  <div>
  {props.travelers.map((traveler, index) =>
    <Row key={index}>
      <Field name={`first_name${index}`} component={renderField} placeholder='First Name' type='text' />
      <Field name={`last_name${index}`} component={renderField} placeholder='Last Name' type='text' />
      <Field name={`gender${index}`} component={renderSelect} />
      <Field name={`date_of_birth${index}`} component={renderField} placeholder='Date of birth' type='date' />
    </Row>
  )}
  </div>
)
```
Is this the right way to do it?  I'm not mapping though props.fields at all and to be honest, don't really know how to use it in my case.  The examples of `FieldArray` I'm seeing are with a form that has an "Add another field" button, which I don't have. Something tells me that I should be mapping through `props.fields` instead of `props.travelers` but how can I tell `props.fields` that I want it to map the number of travelers on this trip?  I hope my question isn't too confusing.

**Comment by gustavohenke** [comment]
Hi @nyjy85, try defining `initialValues.travelers`.
This way `props.fields` will be bound to it (as long the `FieldArray` name prop is the same), and you can [just follow the documented example for `FieldArray`](http://redux-form.com/6.4.3/examples/fieldArrays/).
