### ISSUE TITLE
Optional CTRL+S for submit / save

### ISSUE THREAD

**Issue by kromit** [erikras/redux-form#1387]
Title. Is there any built in way to achieve this?. Would be a nice feature. I can not count how often I've seen that chrome "save as" dialog. :smile:

**Comment by clayne11** [comment]
If you want to do that you can hook up a listener to the `window` for `keyPress` and then submit the form the event handler. That's outside of the scope of `redux-form`.

**Comment by kromit** [comment]
I know I can do that. The problem is that this is outside of scope. It's a global listener. I would need to register and unregister it for each form manually. I could write a wrapper for the form, but an integrated option would be nice.

**Comment by clayne11** [comment]
It doesn't make sense to add this functionality as it's not a standard action on the web. You can easily write a higher-order component to handle what you're looking for.

**Comment by erikras** [comment]
Yeah, hotkeys are beyond the scope of this library. Because of the way React wraps events, there is a chance that you might need to use something like [`react-native-listener`](https://github.com/erikras/react-native-listener) to prevent the browser's default behavior.
