### ISSUE TITLE
Question: Access additional object props in FieldArray

### ISSUE THREAD

**Issue by sgentry** [erikras/redux-form#1389]
First off, great work on this module! Nice to see documentation like you've put together for this.

I Haven't been able to figure this out, so hoping someone can give me a few pointers. I'm using the FieldArray, in v6, to render a list of widgets.

`<FieldArray name="widgets" component={renderWidgetInstance} />`

Inside of it's component render function, I want to display the widget title in a Panel header and then render the widgets metadata field array. How can I access additional properties on my widget items for labels and other logic? Any advice would be much appreciated.

`const renderWidgetInstance = ({ fields }) => (
  <div>
    {
      fields.map((widget, index) => {
        return (
          <Panel key={index} header={widget.title} >
            <FieldArray name={`${widget}.metadata`} component={renderWidgetMetadata} />
          </Panel>
        );
      })
    }
  </div>
);`

**Comment by mattbroekhuis** [comment]
did you ever figure out how to do this?

**Comment by sgentry** [comment]
No, other than to use the [formValueSelector ](http://redux-form.com/6.0.5/examples/selectingFormValues/) which caused my entire form to re-render more than I wanted.

**Comment by danielrob** [comment]
I think the most appropriate answer here would have been to render a `Field` component, as Erik mentioned elsewhere, there's no rule that says a Field must actually be a form input, it can just be used as a connector, e.g. to extract the fields meta. In theory, the performance should never be less than that of a standard form, which, we hope, is acceptable! 

As this is a fairly old question at this point, I'll go ahead and eagerly close this out, but feel free to revive this if desired.
