### ISSUE TITLE
Best practice for passing a hidden value?

### ISSUE THREAD

**Issue by FuzzySockets** [erikras/redux-form#1390]
What is the standard way to pass some additional key:value data to your submission handler? I have two forms which use the same submission handler and I want to vary the response slightly based on the form type.  I tried using a hidden input field, but the value was not passed.  I tried using 'initialize' in my render function:

```
this.props.initialize({
  formType: 'contact'
});
```

But this broke the form and logged a bunch of warnings to the console:

> bundle.js:25662 Warning: setState(...): Cannot update during an existing state transition (such as within `render` or another component's constructor). Render methods should be a pure function of props and state; constructor side-effects are an anti-pattern, but can be moved to `componentWillMount`.

For now I'm just wrapping my submission handler in the component and appending to values.

**Comment by erikras** [comment]
The error you got is because you can't do stuff that changes state in `render()`, like it says. You could do that in `componentWillMount()` or `componentDidMount()` if you wish.

But you have already arrived to the correct solution: wrapping your submission handler to append the values. 👍

**Comment by aftabnaveed** [comment]
@FuzzySockets your solution just sends the values passed to initialize function. Rest fo form Fields are ignored. How are you passing other form fields along with those you included in initialize method?

**Comment by aftabnaveed** [comment]
Sorry I missed the "wrapping your submission handler to append the values" part.  It now works.
