### ISSUE TITLE
Dependent cascading select list doesn't rerender

### ISSUE THREAD

**Issue by adamtal3** [erikras/redux-form#1393]
I've been struggling for some time with building a form that contains several select lists and changing one of them affects a different one (makes some of the options disabled).

I'm using version 6.0.0-alpha.15.

Changing 1 field doesn't re-render the other fields.

I'm using `formValueSelector` to get the current form values so I can filter select2 items be the value of select1 but no matter what I tried, nothing triggers a re-render of the select2 component.

I even tried invoking `initialize` or `change` on every update but nothing seems to make it render again.

Is what I'm trying possible?

**Comment by clayne11** [comment]
Should be possible. Can you post a reproduction repo?

**Comment by adamtal3** [comment]
I tried setting up a codepen to show my problem (simplified).

At the moment it doesn't run at all because for some reason the form doesn't register any fields but maybe you can fix it without effort and see if it works:
[http://codepen.io/adamtal/pen/JKkWEb?editors=0011](http://codepen.io/adamtal/pen/JKkWEb?editors=0011)

**Comment by adamtal3** [comment]
While trying to reproduce the issue for you, I moved from my custom material-ui field component to [redux-form-material-ui](https://github.com/erikras/redux-form-material-ui) wrappers and it works now.
Thanks!
