### ISSUE TITLE
[6.0.0-rc.3] validation messages require custom component type

### ISSUE THREAD

**Issue by bjbrewster** [erikras/redux-form#1394]
Hi,

I love the redux-form package and love the idea of simplifying forms further by having Field component types but I find the validation examples overly simplistic in that they all use a common custom component type to render the field label and error message but only support `<input ...` type.  

To support select, textarea, checkboxes and radio button groups etc, it it possible to write the custom component to understand all types similar to your Field component understands `select` etc, or do you recommend users create their own library of custom components for each type of input component?

Also, is it possible to get field errors in the main form to show errors as before (would also require touched property) and not require custom components to simply show an error?

Many thanks,
Brendan

**Comment by erikras** [comment]
> do you recommend users create their own library of custom components for each type of input component?

Yes.

> Also, is it possible to get field errors in the main form to show errors as before (would also require touched property) and not require custom components to simply show an error?

Not really. This was an intentional performance optimization to not require the entire form to rerender when an input changes.
