### ISSUE TITLE
[v6] Can't pass custom props to Field component

### ISSUE THREAD

**Issue by hampusohlsson** [erikras/redux-form#1397]
Right now there is no way of passing custom props to the Field component without React complaning. A common scenario would be a textfield with some help text. The suggested way of creating the form fields, as seen in first code snippet below, will emit an error as `helptext` is not a valid native prop of an input field (sidenote, apparently `label` is).

``` js
// Form.js
import { reduxForm, Field } from 'redux-form'
import MyTextField from './MyTextField';

render() {
  return <form>
    <Field 
      type="text" 
      name="username" 
      component={MyTextField}
      label="Username"
      helptext="Please enter a name between 6-20 chars. No spaces" 
    />
    <Field 
      type="password" 
      name="password" 
      component={MyTextField}
      label="Password"
    />
  </form>
}

// MyTextField.js
export default function(props) {
  return <div>
    <label>{props.label}</label>
    <input {...props.input} />
    {props.touched && props.error && <span className="error">{props.error}</span>}
    <div className="helptext">{props.helptext}</div>
  </div>
}
```

The workaround I'm doing now (is below actually your preferred solution? @erikras)
It does not feel like the cleanest way of doing things, as I have to import the redux-form Field component into the file of one of my "dumb" components, essentially eliminating usage outside of redux.

``` js
// Form.js
import { reduxForm } from 'redux-form'
import MyTextField from './MyTextField';

render() {
  return <form>
    <MyTextField
      type="text"
      name="username"
      label="Username"
      helptext="Please enter a name between 6-20 chars. No spaces" 
    />
    <MyTextField 
      type="password"
      name="password"
      label="Password"
    />
  </form>
}

// MyTextField.js
import { Field } from 'redux-form';

const renderField = (props) => {
  return <div>
    <input {...props.input} />
    {props.touched && props.error && <span className="error">{props.error}</span>}
  </div>
}

export default function(props) {
  return <div className={styles.textField}>
    <label className={styles.label}>{props.label}</label>
    <Field type={props.type} name={props.name} component={renderField} />
    <div className={styles.helptext}>{props.helptext}</div>
  </div>
}

```

A potential solution could be to add any unrecognized/custom props of the Field component to a custom property called `custom`. That way you could build a clean form component like this

``` js
// MyTextField.js
export default function(props) {
  return <div>
    <label>{props.custom.label}</label>
    <input {...props.input} />
    {props.touched && props.error && <span className="error">{props.error}</span>}
    <div className="helptext">{props.custom.helptext}</div>
  </div>
}
```

**Comment by frost555** [comment]
You can create HoC that will extract custom property outside of props.input.

    import mapProps from 'recompose/mapProps';
    var propRemap = ({input: {custom, ...input}, ...rest}) => ({custom, input, ...rest});
    export let RemappedComponent= mapProps(propRemap);

see https://github.com/acdlite/recompose/blob/master/docs/API.md#mapprops

**Comment by chrisbateman** [comment]
Passing custom props to props.input and then extracting them feels kind of clumsy. Would definitely like to have a cleaner way of doing this.

**Comment by hansoksendahl** [comment]
I have run into the same issue.  Our team was using a component library which consumed a flat set of props.  Updating to reduxForm meant either wrapping each form element in a higher order component or altering each of our components.  In both cases it feels clumsy, I would prefer that reduxForm's Field component passed a flat object instead of `{ input: {...}, ...otherProps}`

**Comment by olslash** [comment]
same issue here -- merging custom props into `input` forces users to do a lot of awkward manual management, and i'm not sure what benefit we're gaining from that style.

**Comment by olslash** [comment]
BTW here's my solution for now:

```javascript
import { omit } from 'lodash';

export const remapReduxFormProps = (WrappedComponent) => {
  return class WithRemappedCustomProps extends React.Component {
    static propTypes = {
      input: shape({
        customProps: object
      })
    };

    render() {
      const props = {
        ...this.props,
        ...this.props.input.customProps,
        input: {
          ...omit(this.props.input, 'customProps')
        }
      };

      return (
        <WrappedComponent { ...props } />
      );
    }
  };
};
```


then use `customProps` on `<Field>` the same way you'd use `props`

```javascript
<Field name={ id }
            component={ remapReduxFormProps(Component) }
            customProps={ options }
/>
```

:sweat::sweat::disappointed:

**Comment by xjlu** [comment]
I think this is a huge issue in v6. It basically make redux-form incompatible with majority react components. On http://redux-form.com/6.0.0-rc.3/docs/api/Field.md/#props, it mentions that we can pass custom props, but it doesn't seem to support it all.

**Comment by erikras** [comment]
You guys are making some good points.

Please cast a vote over on #1425.

**Comment by gustavohenke** [comment]
This is no longer a problem 👴, custom props are in the root, and input props are namespaced with `input`.
