### ISSUE TITLE
Allow null validation

### ISSUE THREAD

**Issue by dzannotti** [erikras/redux-form#14]
Having to create dummy functions that return an empty object adds unnecessary code, please allow for null validator

**Comment by erikras** [comment]
Just to make sure I understand, you are asking for a way to not have any validation?

FYI, I've got some breaking changes in the works coming in the next day or two. Won't be hard to migrate.

**Comment by dzannotti** [comment]
That's correct, currently i use `@reduxForm('myform', () => {})` to work around this

**Comment by erikras** [comment]
@dzannotti, I'd appreciate your opinion of the new v0.0.7 API.

**Comment by dzannotti** [comment]
Thank you so much!
