### ISSUE TITLE
Deep validation submitError placing

### ISSUE THREAD

**Issue by petrleocompel** [erikras/redux-form#1401]
ReduxForm  - 5.3.1

If you will make deep form example
`
complements[].complement
complements[].complementTypeId
`
Next you will make validation 

```
const requireFields = (...names) => data =>
    names.reduce((errors, name) => {
        if (!data[name]) {
            errors[name] = i18n('global.validation.required')
        }
        return errors
    }, {});

const validate = function (values) {
    let errors = {};

    errors.complements = values.complements.map(requireFields('complementTypeId', 'complement'));

    return errors;
}
```

After submit validation is in store in field ```complements``` I will receive this
```
complements: [
        {
            "_isFieldValue": true,
            "complementTypeId": {"touched": true, "_isFieldValue": true},
            "complement": {"touched": true, "_isFieldValue": true},
            "submitError": {"complementTypeId": "Pole je povinné", "complement": "Pole je povinné"}
        }
]
```
But I would expect
```
complements: [
        {
            "complementTypeId": {"touched": true, "_isFieldValue": true, "submitError": "Pole je povinné"},
            "complement": {"touched": true, "_isFieldValue": true, "submitError":  "Pole je povinné"},
        }
]
```

So i thing there is some problem with adding this deep form - because it contains ```"_isFieldValue": true,``` - and its set by ```makeFieldValue```

**Comment by petrleocompel** [comment]
For now solution
-----
Make validation on field when submit failed - in render
```<FormInput type="text" {...complement.complement} error={submitFailed && complement.complement.touched && !complement.complement.value ? i18n('global.validation.required') : null} />```

**Comment by ryanbeard** [comment]
Also an issue for me (v5.3.3). Quite frustrating as it prevents the form from being submitted without any feedback to the user.

As @petrleocompel mentions above, it seems the array itself is assigned a `_isFieldValue` property when I suspect it shouldn't be. This is stopping `setErrors` from mapping the `submitError` value into the actual field.

**Comment by ryanbeard** [comment]
Okay, I didn't need to fix anything in the end. Turns out the issue is using `addField` with empty arguments when an array is storing objects. e.g.
```
// Form field array
'selections[].id'
'selections[].name'

// This confuses the reducer (ADD_ARRAY_VALUE) into thinking you're adding an empty 
// value to the array and therefore adds the '_isFieldValue' flag to the new array item directly,
// breaking validation later on
this.props.fields.selections.addField();

// The reducer realises you're adding an object of empty values and sets the '_isFieldValue'
// flags on the appropriate id/name props instead
this.props.fields.selections.addField({
    id: null,
    name: null
});
```
@petrleocompel - I suspect this may be the root cause of your problem somewhere in your code.

**Comment by petrleocompel** [comment]
Yes, you are right :+1: ... But even in official doc you can find this
```
<button type="button" onClick={() => {
            children.addField()    // pushes empty child field onto the end of the array
          }}><i/> Add Child
          </button>
```
 
Thank you and i'm closing this issue.
