### ISSUE TITLE
[v6] Question. - form with multiple submit buttons, detect which button

### ISSUE THREAD

**Issue by rluiten** [erikras/redux-form#1402]
At the moment I am attaching a handler to each submit button so that I can know in the submit handler which  one triggered the submit, using setState() to just track at component level only which button was pressed.
Just wondering if there might be some other way to detect which button as I have to thread this submit button clicked handler down through 2 layers of components.

Might there be some way I have missed to get the values object as given to submit via some other api possibly ?

**Comment by joewestcott** [comment]
For future visitors... this approach works on `v6`
http://stackoverflow.com/questions/37168954/redux-form-how-to-handle-multiple-buttons

**Comment by rluiten** [comment]
@joewestcott thanks for the comment I think it will this will improve my solution.
It also seems to me the doc is better than it was few months back :) so glad to have gone back there again to.
