### ISSUE TITLE
Tutorial for connecting redux-form to redux

### ISSUE THREAD

**Issue by cristian-sima** [erikras/redux-form#1406]
Any tutorial about this. I have tried for documentation, but there is nothing there

**Comment by alex-pex** [comment]
Did you look here : http://redux-form.com/6.0.0-rc.3/docs/GettingStarted.md/ ?
You have to follow it carefully. You cannot rename the root key used by formReducer (I wanted to use _forms instead). If the reducer is properly configured, you have nothing special to do.

**Comment by cristian-sima** [comment]
No. I do not mean that.

I mean, having a simple form (eg. adding a client) and how do I connect the data from form to the redux state, update the form and reset when everyting is fine. Then if I have an error, to show it

**Comment by stunaz** [comment]
check this http://redux-form.com/6.0.0-rc.1/examples/initializeFromState/

**Comment by gustavohenke** [comment]
@cristian-sima, does @stunaz's link suffice?

**Comment by cristian-sima** [comment]
Yep. Thanks
