### ISSUE TITLE
Calculated values (v5)

### ISSUE THREAD

**Issue by burtyish** [erikras/redux-form#1408]
I'm really impressed with the thoroughness of redux-form so far. But I just ran into this issue and I'm looking for an elegant solution.

I have a 'deep form' with a dynamic amount of item lines. Each line shows a read-only `subTotal` value that is calculated from input fields (say A, B, C) on that line.
Then there's a `total` which shows the sum of all the `subTotals`.

So the question is what's the best way to maintain the `subTotal` (update it on each change in an item)  in a way that I'll be able to access later to calculate the grand total.

I've tries a couple of approaches:

1.Add a `items[].total` in the `reduxForm` `fields` configuration. Every time A,B or C changes in an item, I'll call
```
this.props.fields.total.onChange(
  sumfunc(this.props.fields.A.value, this.props.fields.B.value, this.props.fields.C.value)
)
```
This requires that I duplicate this line 3 times (in the A,B, and C onChange handlers).

2.Write a reducer plugin that catches the CHANGE action and modifies the value of the `total` in the state. That requires some regex parsing to get the index of the item and the name of the field. 

(v5.3.1)

**Comment by richardscarrott** [comment]
I think I understand your problem. In redux you usually wouldn't store derived data in the store but it would instead be computed within `mapStateToProps`. So you could do something like this:

```
reduxForm(state => {
    return {
        subTotal: sum(state.form.yourForm.A.value, state.form.yourForm.C.value, state.form.yourForm.C.value)
    }
})(MyForm)
```

Then `subTotal` would be available in the component.

**Comment by tyrsius** [comment]
You might want to consider updating to v6. The [selector](http://redux-form.com/6.0.0-rc.3/docs/api/FormValueSelector.md/) api was built for exactly this

**Comment by burtyish** [comment]
OK, thanks for the replies. I will update to v6 once it's officially released.
In the meantime, I'm calculating the value in my `mapStateToProps` function. It's not elegant or efficient but it'll have to do for now.
