### ISSUE TITLE
[v6] Focus first field when hit reset

### ISSUE THREAD

**Issue by cristian-sima** [erikras/redux-form#1411]
Now, it does not focus any field, but it would have been nicer to focus the first one.

For instance, I want to add a lot of invoices and after I finish one I want to jump to the first field of the next one

**Comment by erikras** [comment]
`redux-form` does not call anything on your DOM nodes, it only passes props down. You will need to use refs to call `focus()` on your DOM element yourself.

```jsx
focusFirst() {
  this.refs.firstFieldRef    // the Field
    .getRenderedComponent()  // the input component
    .focus()
}

...

<Field name="firstField" ref="firstFieldRef" withRef component="input"/>
```

**Comment by cristian-sima** [comment]
The problem is that I am calling the `reset` function in this way in the `mapDispachToProps`:

```js
resetReduxForm (formID) {
      dispatch(reset(formID));
    },
```

So, I dispatch a reset

**Comment by cristian-sima** [comment]
@erikras Any thought about this?

**Comment by erikras** [comment]
Same thought as before. `redux-form` doesn't have any refs to your DOM nodes on which to call `focus()`. That's up to you.

**Comment by cristian-sima** [comment]
Can you **confirm** that is the following way, the correct way of focusing the element with the `name`=`Name` after a successful submit?

It works, it did not display any warnings, but I want to make sure you confirm it.

```jsx

class Form extends React.Component {

  props: FormPropTypes;

  nameField: any;

  handleSubmitForm: (data : ArticleForm) => Promise<*>;
  handleRegisterRef: (node : any) => void;

  constructor (props : FormPropTypes) {
    super(props);

    this.handleSubmitForm = (data : ArticleForm) => {
      const {
        handleSubmit,
      } = this.props;

      const {
        nameField,
      } = this;

      return handleSubmit(data).then(() => {
        nameField.focus();
      });
    };

    this.handleRegisterRef = (node : any) => {
      this.nameField = node;
    };
  }

...
}

```

and then somewhere in the `Form.render()`:

```jsx

  <Field
          autoFocus
          component={NameInput}
          label="Denumire"
          name="Name"
          onRegisterRef={this.handleRegisterRef}
          placeholder="ex. Cozonac cu stavide 500 gr"
          withRef
          />
  <Field
          {...numericBehavior}
          component={renderInput}
          label="Prețul unitar"
          name="UnitPrice"
          placeholder="ex. 24,99"
        />

... and more fields
```

and I do the trick by wrapping a state-less component like `renderInput` in a simple `NameInput`

```jsx
class NameInput extends React.Component {

 props:  renderInputPropTypes;

  render(){
    return renderInput(this.props);
  }
}
```


```jsx
const renderInput = ({
    autoFocus,
    input,
    placeholder,
    onRegisterRef,
    label,
    meta: { touched, error },
  }: renderInputPropTypes) => {
  ... boring stuff

  return (
    ...
        <input
          {...input}
          aria-label={label}
          className={`form-control ${getInputForm()}`}
          id={input.name}
          placeholder={placeholder || label}
          ref={onRegisterRef}
          type="text"
          />

   ...

  );
};

```

---
Other note: It was working also without the wrapping, using just the state-less `renderInput` component, but `redux-form` was complaining every time.

**Comment by cristian-sima** [comment]
Also, I am avoiding the `getRenderedComponent`, by going directly to the source using a callback (as the new react specs recommends)

**Comment by cristian-sima** [comment]
Hmm I got a problem. I typed something fast and then hit Enter and did this for a couple of times and I got this

![image](https://cloud.githubusercontent.com/assets/12199042/17705403/e109ee72-63e0-11e6-9f33-48829b2f9693.png)

**Comment by RohanDamani** [comment]
You can simply add autoFocus to the component <Field> is rendering - 

`                        <Field name="clientName" component={renderFirstInput} type="text" placeholder="Client Name*" />
`

`import React from 'react'
import { FormGroup, ControlLabel, FormControl } from 'react-bootstrap'

const renderInput = field => {
    console.log('field', field)
    return (
        <FormGroup>
            <ControlLabel>{field.placeholder}</ControlLabel>
            <div>
                <FormControl {...field.input} autoFocus />
                {field.meta.error && field.meta.touched && <span>{field.meta.error}</span>}
            </div>
        </FormGroup>
    )
}

export default renderInput`
