### ISSUE TITLE
[v6 rc3] onChange on Field is not defined

### ISSUE THREAD

**Issue by anaibol** [erikras/redux-form#1414]
```javascript 
<Field name="interest" component={f =>
  <InterestSelector onChange={val => {
    console.log(f);
    f.onChange(val)
    this.goNext()
  }} />
} />
```

![selection_184](https://cloud.githubusercontent.com/assets/3210177/17211622/d596e524-54ca-11e6-81da-f21c175b212f.png)

**Comment by erikras** [comment]
You've missed two things in your migration process:

1. [You may not inline "fat arrow components" inside your form's render() method.](https://github.com/erikras/redux-form/releases/tag/v6.0.0-alpha.14)
2. You should be using `f.input.onChange(val) (see `[`v6.0.0-rc.2`  release notes](https://github.com/erikras/redux-form/releases/tag/v6.0.0-rc.2))

**Comment by anaibol** [comment]
Oh! Sorry I missed that. I will check all release notes next time..
Thanks!
