### ISSUE TITLE
How to know form fields are valid from parent component

### ISSUE THREAD

**Issue by tai2** [erikras/redux-form#1417]
In my project, I have a component which has common fields but no submit buttons.
This is intended to reuse these fields from many places.

I know redux-form provides a way for [submitting from parent component](http://redux-form.com/5.3.1/#/examples/submit-from-parent?_k=6p9s7q).
But I want to disable the submit button with grayed out until whole fields are valid .

Is there a way to check decorated form component fields are valid or not?

**Comment by erikras** [comment]
There is in `v6`, yes. Not in `v5`.

**Comment by tai2** [comment]
http://redux-form.com/6.0.0-rc.3/docs/api/ReduxForm.md/
Wow! form level valid and invalid! cool!
