### ISSUE TITLE
[v6 rc3] Function renderers being recreated on dirty/pristine change

### ISSUE THREAD

**Issue by jschloer** [erikras/redux-form#1418]
I'm trying to wrap some components as custom Fields, but having some trouble with losing focus when the value first changes from it's pristine to dirty state, and the same when it changes back. I'm not sure if that's the cause or if it's just coincidental.

Easiest way to see it is with the following:
```es6
import React, { Component } from 'react';
import { reduxForm, Field } from 'redux-form';

class App extends Component {
  render() {
    const renderInput = (formProps) => <input {...formProps.input}/>;
    return (
      <div >
            String:<Field name="test" component="input" type="text"/>
            Function:<Field name="test" component={renderInput} type="text"/>
      </div>
    );
  }
}

export default reduxForm({
    form:'testForm',
    initialValues: {
        test:'test'
    }
})(App);
```
When you start typing in the function based text box, you lose focus after typing the first key, but subsequent key presses work fine. On the String based component, all key presses work. 
It seems like the component is being recreated when switching from pristine to dirty in the function version, but not on the string version. 

Is there any way around this?

**Comment by erikras** [comment]
Yep. That's because you are defining your `renderInput` function inside `render()`. See the "Breaking Change" section of [the `v6a14` release notes](https://github.com/erikras/redux-form/releases/tag/v6.0.0-alpha.14).

**Comment by jschloer** [comment]
Ahh, I see. Thanks for the help. Was just coming back to update that it works fine for class based components, but then you already knew that...

Sorry I hadn't found that announcement on my own. Thanks again
