### ISSUE TITLE
[v5] Submit is not setting all fields touched, as API claims

### ISSUE THREAD

**Issue by L5eoneill** [erikras/redux-form#1419]
We're on 5.3.1, and the API doc on validation states "When you submit the form, all the fields are marked as touched, allowing any of their validation errors to show." Our form (which is in a modal)

My validate function is called properly and is responding with an error object with the right field names, etc. (from console:)

`errors
Object {username: "A username is required"}
`

But if the user doesn't touch a field manually, the validation error is not showing up in my form upon submit.

This is our field component:

`<FormGroup controlId={field.name}`
`validationState={field.touched && field.error ? 'error' : null}>`
`<ControlLabel>{`${label} ${required ? '*' : ''}`}</ControlLabel>`
 `<HelpBlock>`
`{field.touched && field.error && <div>{field.error}</div>}`
`</HelpBlock>`
`<Control type={type}`
`placeholder={placeholder} {...field} >`
`</Control>`
`</FormGroup>`

If I even focus the username field, the required error shows up. When I click my submit button, the error goes away. As if 'field.touched' is set to false.

After submit is called, we have a call to this.props.untouchAll(), but that's afterward:

`constructor(props) {`
`super(props);`
`this.handleSubmit = ::this.submit;`
`}`

`submit(user) {`
`this.props.handleSubmit(user);`
`this.props.resetForm();`
`this.props.untouchAll();`
`}`

and removing that doesn't seem to make any difference. The form is begun thus:

`<form ref={formRef} onSubmit={data => handleSubmit(this.handleSubmit(data))}>`

 Is something wrong in 5.3.1?

Thank you

**Comment by richardscarrott** [comment]
It looks although you're using [`handleSubmit`](http://redux-form.com/5.3.1/#/api/props?_k=87qfz8) incorrectly.

Have you tried:

```
<form ref={formRef} onSubmit={handleSubmit(this.handleSubmit)}>
```

**Comment by L5eoneill** [comment]
It wasn't that, but the trying to get a field component to not show errors until submit is pressed, when the field is a separate module. How can it be made aware of the form's submit being pressed?

**Comment by danielrob** [comment]
Closing with bulk close of v5 issues. If this issue still requires action and/or also affects v6/7, please request a reopen with details or raise a new issue. v5 PR's are still welcomed.
