### ISSUE TITLE
Rejected onSubmit promise isn't passing in error prop

### ISSUE THREAD

**Issue by jetpacmonkey** [erikras/redux-form#1423]
**Version 6.0.0-rc.3**

Minimal test case:

```javascript
import React from 'react';
import { reduxForm } from 'redux-form';

function Test({ error, handleSubmit, submitting }) {
  return (
    <form onSubmit={handleSubmit}>
      {submitting.toString()}: {error}
      <br />
      <button>Submit</button>
    </form>
  );
}

export default reduxForm({
  form: 'test',
  onSubmit: () => new Promise((res, rej) => {
    setTimeout(() => rej({ _error: 'err' }), 500);
  }),
})(Test);
```

I see `submitting` changing to `true` and then back to `false`, but nothing ever gets rendered for the `error`. I'm still somewhat new to redux-form, am I making a bad assumption here, or is something broken?

**Comment by jetpacmonkey** [comment]
I figured it out. I was looking at an example from an older version of `ReduxForm`, before `SubmissionError` was added.

**Comment by oyeanuj** [comment]
@jetpacmonkey Can you elaborate on the solution you figured out here? I think I'm having a similar issue..

**Comment by jetpacmonkey** [comment]
@oyeanuj anything that gets raised from inside `onSubmit` needs to be wrapped in a `SubmissionError` in order for it to actually get treated as a validation error. See http://redux-form.com/6.0.2/docs/api/SubmissionError.md/
