### ISSUE TITLE
Poll: Field component props structure

### ISSUE THREAD

**Issue by erikras** [erikras/redux-form#1425]
The release of `v6` is eminient. There is a lot of talk, however, around the recent breaking change introduced in [`v6.0.0-rc.2`](https://github.com/erikras/redux-form/releases/tag/v6.0.0-rc.2) which involved walling off the `value`, `onChange`, etc. that Redux Form provides your component into an `input` key. See discussion on #1397.

We need to nail this down before `v6` is released.

There are three types of props that `Field` has to deal with and provide to your component:

* `input` props - Props meant specifically for the input element, like `value`, `onBlur`, etc.
* `meta` props - Metadata about your field that Redux Form is providing, like `error`, `dirty`, etc.
* `custom` props - Any other props that you have given to `Field`

Currently, based on the quick decision I made to get `6rc2` out the door, the props given to your component look like (I hope this notation is self explanatory):

```js
{
  input {
    ...input,
    ...custom
  },
  ...meta
}
```

I can understand why some people have found it annoying that the additional stuff they want to pass gets lumped in with the `input` props.

One thing is for sure, that the `input` props need to be separated from the rest. We need to decide on how we want the others to be organized. Please vote on the options presented below using the 👍 buttons, and feel free to suggest alternatives, and provide reasons for your vote. The last poll we had like this had a clear winner until someone explained why another option was superior and convinced us all.

**Comment by erikras** [comment]
## Option 1

How it is now:

```js
{
  input: {
    ...input,
    ...custom
  },
  ...meta
}
```

```jsx
const renderInput = field => {
  const { input: { label, ...rest} } = field // extract label key out of input props
  return <div>
    <label>{label}</label>
    <input {...rest}/>
    {field.touched && field.error && <span>{field.error}</span>}
  </div>
}

<Field name="myField" component={renderInput} label="My Field" placeholder="Type here..."/>
```

**Comment by erikras** [comment]
## Option 2

Separate all of them:

```js
{
  input,
  meta,
  custom
}
```

```jsx
const renderInput = field =>
  <div>
    <label>{field.custom.label}</label>
    <input {...field.input} placeholder={field.custom.placeholder} type={field.custom.type}/>
    {field.meta.touched && field.meta.error && <span>{field.meta.error}</span>}
  </div>

<Field name="myField" component={renderInput} label="My Field" placeholder="Type here..."/>
```

**Comment by erikras** [comment]
## Option 3

Lump `custom` and `meta` together in the root:

```js
{
  input,
  ...custom,
  ...meta
}
```

```jsx
const renderInput = field =>
  <div>
    <label>{field.label}</label>
    <input {...field.input} placeholder={field.placeholder} type={field.type}/>
    {field.touched && field.error && <span>{field.error}</span>}
  </div>

<Field name="myField" component={renderInput} label="My Field" placeholder="Type here..."/>
```

**Comment by kristian-puccio** [comment]
Happy with 2 or 3. I voted 2 as it allows me to define wrapper components easily. Things like an error label. I just throw it the meta and boom all my inputs have the correct error message handling.

I can't understand number 1. I thought the whole point of separating out input props is so they could be passed straight to a dom input and react wouldn't complain. If we are putting all the extra props in there and having to filter them out, well just mix everything together and provide a filter function with the library as it's sort of what everyone is having to do anyways.

I guess maybe it's sort of assumed that you'll know the extra props that are being passed to a Field so you'll just grab those off but for me I have  a dynamic form and all of the possible props for all of the possible widgets types are being passed all the time so it's a lot of stuff I have to filter off.

**Comment by hampusohlsson** [comment]
Voted for 2 and 3 as well, both would fix the problem. Although, option 3 might seem a little cleaner with less typing, number 2 might be the most flexible option. Let's say you wanted a custom property called `error` for some reason, it would collide in 3, but not in 2

**Comment by olslash** [comment]
Voted 3 because it's the simpler api, with a slight reservation about key collisions.

**Comment by markuso** [comment]
How about a 4th option:

```
{
  input,
  ...meta,
  custom
}
```

This would allow any future props from the library to be added without any conflicts and keeps all custom props contained under `custom`.

**Comment by erikras** [comment]
Dammit.<sup>1</sup> I was literally implementing Option 2, but it looks like we might have a write-in victor again, so I'm going to delay implementation for another day.

If any of you that voted for Option 2 think @markuso's Option 4 is superior, please change your vote.

--

<sup>1</sup> by which I mean "YAY! 🎉"

**Comment by erikras** [comment]
To reiterate the pros and cons here:

**Option 2** is a little verbose, but not that bad if you are good at using ES6 destructuring syntax, and will absolutely have no naming conflicts.

**Option 4** will also have no naming conflicts, since the library can assure that no `meta` prop will ever be named `input` or `custom`, and, while less explicit about the three categories of props than Option 2, will end up in writing slightly less destructuring code.

**Comment by kristian-puccio** [comment]
I like 4. The other way it to flip it slightly
```
{
  input,
  meta
  ...custom
}
```
That way you can pass a defined "Meta" set of props to other things

**Comment by epeli** [comment]
I would prefer @kristian-puccio's suggestion.

In the others I find it surprising that the the props passed to the <Field> get pushed in to a wrapper object.

This feels the most clean to me:

```js
const renderInput = ({input, meta, label}) => (
  <div>
     <label>{label}</label>
     <input {...input} />
     {meta.touched && meta.error && <span>{meta.error}</span>}
  </div>
);

<Field component={renderInput} label="my custom label" />
```

**Comment by erikras** [comment]
Brilliantly articulated, @epeli.

**Comment by erikras** [comment]
## Conclusion

Okay. What we've learned from this poll:

* The current way sucks.
* There is no _obviously_ right answer to this, so in the end it comes down to a judgement call.

I'm going to declare @kristian-puccio's solution the winner: 🏆

```js
{
  input,
  meta
  ...custom
}
```

For all the reasons outlined by @epeli above, and another one that I found whilst implementing it, namely that it deals very well with the `children` prop. If the `custom` props were anywhere other than in the root, then it makes `children` very awkward.

A sincere thank you to everyone who participated and retweeted this poll. Cheers. 🍻

**Comment by erikras** [comment]
Okay guys, check out [`v6.0.0-rc.4`](https://github.com/erikras/redux-form/releases/tag/v6.0.0-rc.4).

**Comment by andrewmclagan** [comment]
Awesome, such great work... I should really keep an eye on this repo OR lock into a version...

We have a complex render function, as we use it to render not just `<input />` elements. For those wanting to take a look:

````javascript
/* eslint-disable react/prop-types */

import React, { createElement } from 'react';
import classNames from 'classnames';

/**
 * Stateless field render function
 *
 * @author Andrew McLagan <andrewmclagan@gmail.com>
 */

const RenderField = ({ input, meta, field, ...props }) => {

  // 1. Destructure props we dont want on the <input />
  const { wrapClassName, label, description, ...inputProps } = props;

  // 2. Determine the wrapping class
  const _wrapClassName = classNames('form-field', input.type, input.name, wrapClassName, {
    error: meta.touched && meta.error, // checkbox fields dont get touched as there is no blur event
    valid: meta.touched && meta.valid,
  });

  // 3. Determine the <input /> class
  const _className = classNames(inputProps.className, 'form-control');

  return (
    <div className={_wrapClassName}>
      {label && <label htmlFor={input.id}>{inputProps.required && <span className="required">*</span>}{label}</label>}
      {description && <p className="description">{description}</p>}
      {createElement(field, { ...input, ...inputProps, className: _className })}
      {meta.touched && meta.error && <div className="text-danger">{meta.error}</div>}
    </div>
  );
};

RenderField.displayName = 'RenderField';

export default RenderField;
````

From the form field:

````javascript
import React, { PropTypes } from 'react';
import { renderComponent } from 'components';
import { Field } from 'redux-form';

/**
 * Field component wrapper
 *
 * @author Andrew McLagan <andrewmclagan@gmail.com>
 */

const FormField = props => (
  <Field id={props.name} {...props} field={props.component} component={renderComponent}>
    {props.children}
  </Field>
);

FormField.propTypes = {
  component: PropTypes.any.isRequired,
  name: PropTypes.string.isRequired,
  children: PropTypes.node,
};

FormField.displayName = 'FormField';

export default FormField;
````

**Comment by erikras** [comment]
@andrewmclagan Fantastic and flexible example. Thanks!

I think you mean
```jsx
  <Field id={props.name} {...props} field={props.component} component={RenderField}/>
                                                                       ^^^^^^^^^^^
```
Also, passing `{props.children}` is redundant.

**Comment by andrewmclagan** [comment]
Haha well spotted, I modified the example on the fly... Thanks!

**Comment by lundn** [comment]
@andrewmclagan Awesome, this is exactly what I would like to have in our solution. Could you please include a simple implementation of the FormField? Can't quite seem to understand how to use this. What should be passed in the ```component``` prop? I'm trying this in my redux form: 
`<FormField name={`Field_${fieldObject.name}`} type="text" label={fieldObject.label} description={fieldObject.description} component={ ??? } />`
