### ISSUE TITLE
[v6 rc3] Adding a field for uploading multiple images

### ISSUE THREAD

**Issue by rcholic** [erikras/redux-form#1429]
I am experimenting the `redux-form v6.0.0 rc.3` and trying to add a field for uploading multiple images. 

*Idea 1:* add field with type="file"
```
attachImages(images) {
        console.info('images received: ', images);
    }

<Field
                      name="pics"
                      component={renderInput}
                      placeholder="Pictures"
                      onDrop={this.attachImages}
                      type="file" />

```

*Idea 2:* Using the third-party `Dropzone` component:
```
onDrop(files, evt) {
        console.log('received files: ', files);
        evt.preventDefault();
    }

<Dropzone
                     onDrop={ this.dropFile }
                 >
                   <div>Try dropping some files here, or click to select files to upload.</div>
                 </Dropzone>
```

I've tried both ideas, but the first one cannot trigger the `onDrop` function at all, and the second idea seems more promising, however, I don't know how to add a field with the API for ver 6.0.0 rc.3. Anyone knows?

**Comment by r4j4h** [comment]
What does the `renderInput` component look like? Is it passing on the type as expected?

**Comment by rcholic** [comment]
@r4j4h see the code below for `renderInput`, which renders an input field
```
export const renderInput = field =>
  (<div>
    <input {...field.input} className="form-control"/>
    {field.touched &&
     field.error &&
     <span className="error">{field.error}</span>}
  </div>)
```

**Comment by rcholic** [comment]
After much struggling, I made my second idea work by modifying the `onDrop` callback for the `Dropzone` component a little bit. The modification includes using the `dispatch` function of the reduxForm wrapper component with the action type `redux-form/CHANGE`.
```
onDrop(files, evt) {
        console.log('received files: ', files);
        evt.preventDefault();
        this.props.dispatch({
            type: 'redux-form/CHANGE',
            field: 'images',
            value: files, // files is an array of File
        });
    }
```
Then in the reducer, I watch for the action type `redux-form/CHANGE` and extract the files for uploading. This may be a little bit too hacky, but it works with the current ver 6 RC3 API.

**Comment by BBB** [comment]
@rcholic I've updated my example on how to use Dropzone with redux-form. It might be of interest to you: https://github.com/BBB/dropzone-redux-form-example
