### ISSUE TITLE
[v6 rc3] getRenderedComponent() returning undefined when called on 'input' component

### ISSUE THREAD

**Issue by bmv437** [erikras/redux-form#1437]
Hi there. In v6-rc3 I'm having issues with the following example:

```javascript
focusFirst() {
  this.refs.firstFieldRef    // the Field
    .getRenderedComponent()  // the input component
    .focus()
}

...

<Field name="firstField" ref="firstFieldRef" withRef component="input"/>
```

example taken from this [issue](https://github.com/erikras/redux-form/issues/1411#issuecomment-235833302).

The issue is that `getRenderedComponent()` is returning undefined when the component is the string `input`. It does successfully return a React Component when the component props is defined like so:

```javascript
class MyComponent extends React.Component {
  render() {
    const {input} = this.props;
    return <input {...input} />
  }
}

...

<Field name="firstField" ref="firstFieldRef" withRef component={MyComponent} />
```

Then the issue is since it returns a React Component, you can't use `.focus()` because it's not a ref to the dom node, its a React Component.

Did something break somewhere, because I'm 90% sure the first example I gave used to work, but no longer does. 

Thanks,
Brandon

**Comment by erikras** [comment]
Thanks for this. I'm fairly certain that the prop rejiggering that I did today in #1435 will fix this for the next version. Please report back if it is not. Release of RC4 is hours away.

**Comment by erikras** [comment]
Try again with [`v6.0.0-rc.4`](https://github.com/erikras/redux-form/releases/tag/v6.0.0-rc.4).

**Comment by bmv437** [comment]
That seems to have fixed it, thanks!

One other question though related to the upgrade. What is the preferred method of passing props like `disabled` and `placeholder` now that they are grouped together with the custom props?

Is there a better way then what I have here?

```javascript
class TextInputField extends Component {
  render() {
    const {input, meta: {touched, error}, ...custom} = this.props;
    return (
      <div>
        <input {...input} {...custom} />
        {touched && error && !custom.disabled && <span className='error'>{error}</span>}
      </div>
    );
  }
}

...
<Field name='myInput' component={TextInputField} placeholder="you can't type here" disabled /> 
```
