### ISSUE TITLE
Tabbing through a radio group selects an option. Should it?

### ISSUE THREAD

**Issue by jeremy-putt** [erikras/redux-form#1438]
I have a radio group, and when I tab through it, it selects an option instead of just moving on with its life.

It doesn't feel like this is the desired behavior of a radio group.

Simple Example has the same behavior http://redux-form.com/6.0.0-alpha.15/examples/simple/

**Comment by erikras** [comment]
Interesting. This behavior is different in Safari, Firefox and Chrome, so I think this is either:

* A problem that React's `SyntheticEvent` system needs to handle/unify, or
* Not a problem, as users of a particular browser will be aware of how their browser behaves

**Comment by jeremy-putt** [comment]
That is interesting. In chrome, I've found the radio group on the example page to behave differently to other instances of radio groups (in the wild), so at the least it's a react or redux-form or implementation issue.

It behaves the way I've described in Chrome, IE 11 & Edge at least.

I've played around in the getValue event code and found that for a radio button, it just returns 'value' every time, it doesn't seem to check if the 'checked' property is true. Checking if 'Checked' is checked (wow...) before returning 'value' does solve this issue.

`if (type === 'radio) { return checked ? value : '' }`

Not sure if that's the right approach though..

**Comment by jeremy-putt** [comment]
I have a local branch which is behaving itself, and some unit tests, but can't seem to push them up for your perusal. I believe I have to be added as a collaborator?

**Comment by jeremy-putt** [comment]
Hey @erikras, still interested in hearing your thoughts on the above.

**Comment by erikras** [comment]
Published fix in [`v5.3.4`](https://github.com/erikras/redux-form/releases/tag/v5.3.4).
