### ISSUE TITLE
[v6 rc4] props are not passed from <Field /> to native input

### ISSUE THREAD

**Issue by sputinyk** [erikras/redux-form#1439]
props like "placeholder" and "type" are not passed to ...field.input
Eg.:

```
const InputText = field =>
    <div>
        <input {...field.input} />
        {field.meta.touched && field.meta.error &&  <span className="error">{field.meta.error}</span>}
    </div>
```

`<Field name="foo" placeholder="my placeholder" type="password"  component={InputText} />`

produces:

`<input name="foo" />`

**Comment by raygesualdo** [comment]
According to the RC4 [release notes](https://github.com/erikras/redux-form/releases/tag/v6.0.0-rc.4), the `placeholder

**Comment by raygesualdo** [comment]
For additional reading on what is passed in `props.input`, check out the most recent docs on [input props](http://redux-form.com/6.0.0-rc.4/docs/api/Field.md/#input-props).

**Comment by echenley** [comment]
Interesting decision here. Why wouldn't extra props just be merged in with the input props? Now we have to explicitly pass props or use both `{ ...field }` and `{ ...field.input }`. I assume the tradeoff is that you don't have to destructure props if you're rendering more than a single input?

How I'm doing it now:

```js
```

**Comment by stunaz** [comment]
@echenley  or you can use https://github.com/erikras/redux-form-material-ui

**Comment by sputinyk** [comment]
sorry guys, I don't RTFM :/

So @echenley , it's boring make this treatment, everything should be a single place.
I was using V6RC3 and work, but now...

So, thanks @raygesualdo  and everyone!

(sorry for my bad english)
