### ISSUE TITLE
V5 - Complex values example doesn't work

### ISSUE THREAD

**Issue by davidfurlong** [erikras/redux-form#1440]
http://redux-form.com/5.3.1/#/examples/complex?_k=m8uqn5

Changing Line 34 of ObjectSelect.js to

```
const val = Array.isArray(value) ? value.map(JSON.stringify) : value
```

Fixes it for me. Problem was value was "\"1\"" not "1". Although I'm not sure this will work with multiple

**Comment by danielrob** [comment]
Closing with bulk close of v5 issues. If this issue still requires action and/or also affects v6/7, please request a reopen with details or raise a new issue. v5 PR's are still welcomed.
