### ISSUE TITLE
[v5] unknown props warning when spreading in 15.3

### ISSUE THREAD

**Issue by Plummat** [erikras/redux-form#1441]
Not sure when React added this, but there are now warning when you pass unknown props down to a HTML element, which means the beauty of "input {...firstName} /" now results in:

**Warning: Unknown props `initialValue`, `autofill`, `onUpdate`, `valid`, `invalid`, `dirty`, `pristine`, `active`, `touched`, `visited`, `autofilled` on <input> tag. Remove these props from the element.

**Comment by erikras** [comment]
Yep. I'm afraid as long as you're using `v5`, you'll have to pass the field object through a function like:
```js
const domOnlyProps = ({
  initialValue,
  autofill,
  onUpdate,
  valid,
  invalid,
  dirty,
  pristine,
  active,
  touched,
  visited,
  autofilled,
  ...domProps }) => domProps
```
`v6` has its own solution to this. #1425

**Comment by MicheleBertoli** [comment]
thanks @erikras 

the `error` prop has to be removed as well

**Comment by jsj14** [comment]
So do we have to declare this object in every redux form?
