### ISSUE TITLE
What is the correct way to populate a dynamic form with initial data?

### ISSUE THREAD

**Issue by gsklee** [erikras/redux-form#145]
`initialValues` is not the answer because it doesn't seem to change with subsequent rerenderings.

**Comment by gsklee** [comment]
In other words - is there any way to modify `field.value` in the `connectReduxForm` decorator??

**Comment by gsklee** [comment]
This is what I'm doing currently but I don't like it:

```javascript
render () {
    const {text, fields: {displayedText}} = this.props;

    return (
      <main>
        <form>
          <textarea
            {...displayedText}
            value = {displayedText.value || text}
          ></textarea>
        </form>
      </main>
    );
  }
```

**Comment by gsklee** [comment]
Note that `this.props.text` in the above example can change after rerenderings.

**Comment by gsklee** [comment]
The example doesn't work... it will block off any attempt to make changes to the text area.

**Comment by erikras** [comment]
Does it work with an `<input type="text"/>`?

**Comment by bbenezech** [comment]
@gsklee I use

```javascript
  componentWillMount() {
    if (this.props.pristine) this.props.initializeForm(this.props.todo);
  }

  componentWillUnmount() {
    if (this.props.pristine) this.props.destroyForm();
  }
```
inside the form component. It works like a charm.

The fact that you do not destroy dirty forms when it unmounts make the changes stick around in the store even when the form is out of dom.
Pristine forms are kicked out, keeping memory overhead to a minimum. You should also destroy forms after submit success (to reset defaults), depending on your UX.

**Comment by erikras** [comment]
Possibly related: https://github.com/facebook/react/issues/2533

**Comment by pbojinov** [comment]
@erikras I'm having the same problem with `<input type="text"/>` not setting a form value in a subsequent render because a value is initially `undefined`. 

I'm getting around it by waiting for all the prop data I need to be defined before rendering the form.

``` javascript
// ...
render: function() {
    let userId = this.props.userId : '';
    let fields = {
        user_id: userId,
        name: 'placeholder name'
    };
    let userForm = <span/>;
    if (userId) {
        userForm = <UserForm
            initialValues={fields}
            onSubmit={this.handleSubmit}/>
    }
    return (
        userForm
    );
}
// ...
```

**Comment by erikras** [comment]
This is my next priority to address with version 3.

**Comment by elmeister** [comment]
@gsklee, have you tried to use `form: formReducer.plugin` reducer to set new text values for the form fields? Please check the [example with password value change](http://erikras.github.io/redux-form/#/api/reducer/plugin).

**Comment by elmeister** [comment]
@erikras, concerning the issue https://github.com/facebook/react/issues/2533 - could you please clarify, if the mentioned case is the reason why resetForm doesn't affect textareas values?

**Comment by gsklee** [comment]
@elmeister This is some very basic use case that I'd expect the lib offers an easy way to handle this need, presumably through a config property.

**Comment by elmeister** [comment]
@gsklee, default value can be used only for uncontrolled components, changing value of controlled one [isn't actually a basic usage](https://facebook.github.io/react/docs/forms.html#controlled-components). @erikras proposed [quite neat solution](http://erikras.github.io/redux-form/#/api/reducer/plugin) for the moment. Could you please share if you seen better implementations for React components?

**Comment by elmeister** [comment]
@erikras, thanks, I found [an answer how to reset textarea at Stackoverflow](http://stackoverflow.com/questions/26358144/how-to-reset-a-reactjs-element) - works like a charm after add `key={id.value}` inside form tag.

**Comment by erikras** [comment]
What an interesting hack. Thanks, @elmeister!

There's no real way for redux-form to know if your form element is a `<textarea>`, so it's really up to each developer to add this...at least until React fixes the awkwardness.

**Comment by thedamon** [comment]
I would love to see this in the documentation somewhere... I can understand that it's somewhat outside of redux-form's purview.. but coming into the library I had assumed this would all be taken care of

**Comment by jpierson** [comment]
Sorry I know that this question is closed but I wanted to get some clarification whether the phrase "dynamic form" in the title of this issue is refering to the same dynamic concept as the [Dynamic Form](http://erikras.github.io/redux-form/#/examples/dynamic?_k=bknxvc) example.

**Comment by erikras** [comment]
@jpierson I don't think the word "dynamic" means much on this issue. The problem was unrelated to altering the `fields` array at runtime, which is what "dynamic" means in the examples.

**Comment by thedamon** [comment]
Yeah Erik is right. I completely misunderstood what was meant by 'dynamic'
when I was looking at the library at first. :/
