### ISSUE TITLE
More bound functions on form props

### ISSUE THREAD

**Issue by CarsonF** [erikras/redux-form#1452]
So I just saw the array functions redux-form passing into your form component. It made me start comparing those props to the action creators. I noticed most of them were there but a couple were missing. Notability the `change` function. I think it would be helpful to have `change` function passed in as well.

`focus` and `blur` are also left out, but those make be a bit trickier. Will calling those actually focus/blur the element or just sync their state in the store? I'm thinking the latter...

**Comment by gustavohenke** [comment]
`change` is there nowadays.

The behavior of `focus` and `blur` is exactly what is documented:

> `blur(form:String, field:String, value:any)`
> Saves the value to the field.
>
> `focus(form:String, field:String)`
> Marks the given field as active and visited.

They won't touch the DOM.
