### ISSUE TITLE
Broken link to the documentation

### ISSUE THREAD

**Issue by ilyjs** [erikras/redux-form#1454]
http://redux-form.com/6.0.0-alpha.15/examples/material-ui/

For controls like SelectField we need to simulate the onChange manually. As props have been exposed in redux-form you can fire onChange manually. Read more [here](http://redux-form.com/docs/api/Field.md#usage). 

**here**  links to http://redux-form.com/docs/api/Field.md#usage but this page is not available.

**Comment by erikras** [comment]
Thanks. I'm not going to go back and fix the 6a15 docs, but it will be fixed in all future versions.
