### ISSUE TITLE
I can't set  the readonly attr on input element 

### ISSUE THREAD

**Issue by yy-hh** [erikras/redux-form#1455]
parent  comp:  \<com.Input label='地址' tips='请输入地址' {...address}/>'
child comp:     \<input type={type | 'text'} readonly="readonly"  name={name} placeholder={tips} {...this.props}/>

I try set but when doesn't work  I don't know why.
here is what i see in chrome.where is my readonly attr???
\<input type="0" name="address" placeholder="请输入地址" label="地址" value="yngyang">

**Comment by erikras** [comment]
[`readOnly` (mixed case) is a boolean attribute in React](https://facebook.github.io/react/docs/jsx-in-depth.html#boolean-attributes).

**Comment by yy-hh** [comment]
also need Camel-Case thanks @erikras
