### ISSUE TITLE
Custom className for Field (of type select)

### ISSUE THREAD

**Issue by cristian-sima** [erikras/redux-form#1456]
I want to have something like this

`<Field component="select" class="custom-select" />`

to be : 

`<select class="custom-select"> .... </select>`

How do I do?

**Comment by erikras** [comment]
[You need to use `className`](https://facebook.github.io/react/docs/jsx-in-depth.html#html-tags-vs.-react-components).

**Comment by cristian-sima** [comment]
Thank you
