### ISSUE TITLE
[Question]: why does redux-form go through a redux store?

### ISSUE THREAD

**Issue by tugberkugurlu** [erikras/redux-form#1459]
I was looking for this on documentation and I was not able to see the reason why redux-form goes through a redux store and needs a reducer? I am imagining that the form validation state is the concern of my the component which has the form in it. I cannot think of a reason why I would want that state exposed to the store.

**Comment by rcholic** [comment]
I think the answer is partly in the name of this awesome library **redux**-form, which explains why it uses redux and a store. Another reason for using a redux store/reducer is the whole point of one-way data flow so as to KISS. - my $0.02

**Comment by erikras** [comment]
Good questions, @tugberkugurlu. When I was starting with Flux and Redux, I also had concerns about "exposed state", but they turn out to be unfounded. The Redux store is no more exposed than any other kind of client-side state.

But the "Why Redux?" question comes down to these two facts:

* Doing forms properly in React requires a _lot_ of state management
* Redux is _excellent_ at state management

This slide from a talk I gave recently describes how React forms and Redux fit so well together. (click on it to see the rest of the slides)

[![SpeakerDeck](https://cloud.githubusercontent.com/assets/4396759/17412014/f0bc9ad2-5a7a-11e6-9b55-a46e044a6938.jpg)](https://speakerdeck.com/erikras/abstracted-form-state-with-redux-form?slide=30)

**Comment by tugberkugurlu** [comment]
@erikras thanks, that's helpful. I can see the benefit now. It's also lighting up with existing redux tools like redux-logger which makes it straight forward to debug things.
