### ISSUE TITLE
[v6 rc4] Wizard form fails validation after a few steps.

### ISSUE THREAD

**Issue by fini** [erikras/redux-form#1460]
Hi!

Using the technique from the rc.4 Wizard Form Example, I've run into some strange issues, where validation stops working after some pages. I've tried swapping the order of the pages, and they work fine, as long as they are moved to earlier steps. I use disabled={pristine || submitting || invalid} on the submit buttons, but when the bug occurs the form says it's valid, even though it should fail and not be able to submit.

I have compared the code for a few hours, and it seems identical to the sample, except for more steps (5) and other Fields (radio buttons, checkboxes etc.)

I'll try and give more information on request, but unfortunately I don't have time to make a complete public test case at this moment.

I think the issue was also on rc.3, but alas I cannot easily switch back to test, because of all the changes that happened in rc.4.

Best Regards

**Comment by erikras** [comment]
This isn't much to work with, but I'd suggest that you try and examine the Redux store and see if the `registeredFields` correspond to the ones displayed on each page.

**Comment by fini** [comment]
@erikras Thanks for responding, I know it was a bit vague, but I was lost ;)

I have inspected the Redux events `redux-form/REGISTER_FIELD` & `redux-form/UNREGISTER_FIELD`.

I can see that they both seem fire correctly, but when bug occurs there are zero elements in registeredFields. ;(

**Comment by erikras** [comment]
Yep, that would make validation not run. 😄 Sounds like you're clicking submit when you have no fields displayed. ?

**Comment by fini** [comment]
There are fields on all the pages, one field on the first (checkbox), three radio button groups on the second page (each group contains three radio buttons and Field for the error message, as in the example), and then the third page has a single radio button group.
It correctly dispatches the UNREGISTER_FIELD & REGISTER_FIELD events, but they do not get added to registeredFields when the bug occurs, the first two pages are nicely updated in registeredFields. The pages themselves work fine, and if I switch the pages around, they validate fine, and the previous working page is now buggy.

**Comment by eliseumds** [comment]
I'm not sure if it's related, but on `rc4`, the form values are being sent even though it has errors.

**Comment by jervi** [comment]
If you go to the wizard example (http://redux-form.com/6.0.0-rc.4/examples/wizard/) I think you can reconstruct the problem. Fill out the form until step 3. Then go back to step 2 and remove or invalidate the email. You are then able to go to step 3 and submit the form.

**Comment by jervi** [comment]
It seems like it is enough to just navigate backwards in the wizard to totally break the validation. The problem did not occur in rc.3.

**Comment by erikras** [comment]
Fix published in [`v6.0.0-rc.5`](https://github.com/erikras/redux-form/releases/tag/v6.0.0-rc.5).
