### ISSUE TITLE
[v6 rc4] 'Values' not passed to props of wrapped component

### ISSUE THREAD

**Issue by jsdmc** [erikras/redux-form#1462]
Values should be passed to wrapped component.

**Comment by jsdmc** [comment]
Ah, ok. 
Didn't knew about this change. So, now only use selectors to get values from state?
Probalbly docs should be updated.

**Comment by jsdmc** [comment]
My fault, docs are fine. 
So for anyone who will read this. Values can be accessed either using provided selectors to read from state, or accessing `ownProps` in `connect((undefined, { values }) => ({ values }))`

**Comment by erikras** [comment]
No worries. We all make mistakes like this.
