### ISSUE TITLE
[v6] What is a right way to get form values?

### ISSUE THREAD

**Issue by olegkalyta** [erikras/redux-form#1467]
Now in `stateToProps` i use:

`currentValues: state.form.FORMNAME ? state.form.FORMNAME.values : {}`

And i am getting extra render, because initially form values are empty and after initialization - are not.
I feel i am getting values absolutely wrong. Is there better way?

**Update**: found formValueSelector which basically does the same

**Comment by gustavohenke** [comment]
> And i am getting extra render, because initially form values are empty and after initialization - are not.

You would get extra renders anyway whenever your form values are updated.

> found formValueSelector which basically does the same

Yup, that would be the best way, because the rule to select the values is contained in redux-form, not your app.

**Comment by gustavohenke** [comment]
> You would get extra renders anyway whenever your form values are updated.

This is, unless you implement `shouldComponentUpdate`, of course!
