### ISSUE TITLE
Getting warning when set webpack 2 option `resolve.mainFields` field

### ISSUE THREAD

**Issue by nktssh** [erikras/redux-form#1469]
When you set your `webpack 2` config like this:
`resolve.mainFields = ['jsnext:main', 'main']` (see more about this section [here](https://github.com/webpack/docs/wiki/Configuration#resolvepackagemains))
you'll get a warning during build:

> WARNING in ./~/redux-form/es/createAll.js
> 22:15 export 'default' (imported as 'propTypes') was not found in './propTypes'

Transpiled code in node_modules:

```
// /es/createAll.js
import propTypes from './propTypes';
```

```
// /es/propTypes.js
export var propTypes = { //
    ...
}
```

As you can see `propTypes` is exported as named, not `default`

**Comment by gustavohenke** [comment]
This was fixed by #1524, but somehow the issue was not closed 😕
