### ISSUE TITLE
initialize form should "untouch" form elements / reset validation exceptions

### ISSUE THREAD

**Issue by mschipperheyn** [erikras/redux-form#147]
I might be mistaking but after dispatching initialize for a form and reloading the form, I immediately see the sync validation exceptions I created before. Could it be that either the validation exceptions are not being reset or that the the form fields are not being "untouched"?

**Comment by erikras** [comment]
I'm pretty sure that this was never a problem, but I'm quite sure it's not a problem in v3. [I recommend upgrading](https://github.com/erikras/redux-form/releases/tag/v3.0.0).
