### ISSUE TITLE
v6 rc3 to rc4 Field is not passing optional props to custom component

### ISSUE THREAD

**Issue by vinayrajp** [erikras/redux-form#1475]
First off, thank you for creating this amazing library.

I was disabling an input field in rc3 by doing the following:
```
const renderInputField = field => (
	<div className="form-group">
		<label>{field.input.label}</label>
		<div>
			<input {...field.input}/>
			{field.touched && field.error && <span className="error">{field.error}</span>}
		</div>
	</div>
);
```

and using it in Field as follows:
`<Field name="currency" type="text" className="form-control" 												 label="Currency" component={renderInputField} props={{ disabled: true }} />`

However, I have upgraded to rc4 and the following doesn't work anymore.
```
const renderInputField = ({ input, label, type, meta: { touched, error } }) => (
	<div className="form-group">
		<label>{label}</label>
		<div>
			<input {...input} className="form-control" type={type} />
			{touched && error && <span className="error">{error}</span>}
		</div>
	</div>
);
```
`<Field name="currency" type="text" label="Currency" component={renderInputField} props={{ disabled: true }} />`

The input rendered is not disabled. I had to move the className prop from Field to input as well. What is the new way to accomplish what I was doing with rc3? Thanks for your help.

**Comment by ArcanisCz** [comment]
Yesterday i tried this from documentation (http://redux-form.com/6.0.0-rc.4/docs/api/Field.md/) and it worked fine. Do you happen to not read RC4 changelog where Field api change is described? (https://github.com/erikras/redux-form/releases)

```
// outside your render() method
const renderField = (field) => (
    <div className="input-row">
      <input {...field.input} type="text"/>
      {field.meta.touched && field.meta.error && 
       <span className="error">{field.meta.error}</span>}
    </div>
  )

// inside your render() method
<Field name="myField" component={renderField}/>
```

**Comment by ArcanisCz** [comment]
This is mentioned in RC4 changelog (https://github.com/erikras/redux-form/releases/tag/v6.0.0-rc.4). Back in RC2, your custom props was mixed into "input" prop. Now, they are injected as a "top level prop"

It should probably look somewhat as this (note that added prop in arguments)

```
const renderInputField = ({ input, label, type, meta: { touched, error }, disabled }) => (
    <div className="form-group">
        <label>{label}</label>
        <div>
            <input {...input} disabled={disabled} className="form-control" type={type} />
            {touched && error && <span className="error">{error}</span>}
        </div>
    </div>
);
```

if you want to pass all custom props as before, i would use spread operator


```
const renderInputField = ({ input, label, type, meta: { touched, error }, ...other }) => (
    <div className="form-group">
        <label>{label}</label>
        <div>
            <input {...other} {...input} className="form-control" type={type} />
            {touched && error && <span className="error">{error}</span>}
        </div>
    </div>
);
```

**Comment by vinayrajp** [comment]
Ty @ArcanisCz . That worked beautifully!!
