### ISSUE TITLE
async validate doesn't fail on general errors

### ISSUE THREAD

**Issue by mschipperheyn** [erikras/redux-form#148]
asyncValidate seems to always resolve in case of general exceptions. On redux-form 2.4.1, the form contains two fields: username and password:

	function asyncValidate(data, dispatch){

	  return new Promise((resolve,reject) => {
		const errors = {};

		dispatch(loginUser(data.username, data.password))
		.then(json => {

		  if(Object.keys(json.errors).length > 0){
			dispatch(showFormException());
			reject(json.errors); <= this stops async validation
		  }else{
			dispatch(saveUser(json.user));
			resolve(errors);
		  }

		})
		.catch(err => {
                  //perhaps the remote server is down. Something went wrong
		  reject(); <= after this, handleSubmit is called
		});
	  });
	}

Or

	function asyncValidate(data, dispatch){

	  return new Promise((resolve,reject) => {
		const errors = {};

		dispatch(loginUser(data.username, data.password))
		.then(json => {

		  if(Object.keys(json.errors).length > 0){
			dispatch(showFormException());
			reject(json.errors);
		  }else{
			dispatch(saveUser(json.user));
			resolve(errors);
		  }

		})
		.catch(err => {
                  //perhaps the remote server is down. Something went wrong
		  resolve({valid:false}); <= after this, handleSubmit is called
		});
	  });
	}

but this works

	function asyncValidate(data, dispatch){

	  return new Promise((resolve,reject) => {
		const errors = {};

		dispatch(loginUser(data.username, data.password))
		.then(json => {

		  if(Object.keys(json.errors).length > 0){
			dispatch(showFormException());
			reject(json.errors);
		  }else{
			dispatch(saveUser(json.user));
			resolve(errors);
		  }

		})
		.catch(err => {
                  //perhaps the remote server is down. Something went wrong
		  reject({password:"bla"}); <= async validation fails successfully
		});
	  });
	}

So, it would seem that for async validation to fail, at least one of the form fields needs to be part of the error object. I would argue that any call to "reject" should lead to async validation to fail.

**Comment by mschipperheyn** [comment]
What are your thoughts on this?

**Comment by erikras** [comment]
> So, it would seem that for async validation to fail, at least one of the form fields needs to be part of the error object. I would argue that any call to "reject" should lead to async validation to fail.

I agree.

**Comment by mschipperheyn** [comment]
Fixed by commit 304c5170fcb15183886e371ffb5d6087ae49316e
