### ISSUE TITLE
Was the code size optimized?

### ISSUE THREAD

**Issue by wmertens** [erikras/redux-form#1481]
I was very surprized when I found out that the minified size of redux-form is 60k, making it one of my biggest dependencies. See https://npmcdn.com/redux-form@5.3.2/dist/

When I had a quick peek at the code, the source sizes are nowhere near the 160k unminified.

Are there perhaps dependencies that should not be part of the package? Is this the smallest it can go?

**Comment by erikras** [comment]
Is there more that can be done than [this](https://github.com/erikras/redux-form/blob/master/webpack.config.js#L4-L20)?

`redux-form.min.js` for `v6` is even bigger: `75.2 kB`. 😳

**Comment by wmertens** [comment]
Well, there is also the DedupePlugin, but the best thing to do is to generate the webpack stats and throw them through https://github.com/robertknight/webpack-bundle-size-analyzer

**Comment by erikras** [comment]
Yup. I did all of that. `Dedupe` was the difference between `75.2` and `74.9` above.

Pardon the ignoring of `v5`, but...well... This is the `v6`  build with said analyzer:
```
lodash: 29.99 KB (15.2%)
  <self>: 29.99 KB (100%)
lodash.keys: 6.46 KB (3.28%)
  <self>: 6.46 KB (100%)
lodash.isarguments: 5.58 KB (2.83%)
  <self>: 5.58 KB (100%)
lodash.isarray: 5.04 KB (2.56%)
  <self>: 5.04 KB (100%)
lodash._getnative: 3.78 KB (1.92%)
  <self>: 3.78 KB (100%)
es6-error: 2.61 KB (1.32%)
  <self>: 2.61 KB (100%)
invariant: 1.48 KB (0.751%)
  <self>: 1.48 KB (100%)
hoist-non-react-statics: 1.35 KB (0.687%)
  <self>: 1.35 KB (100%)
shallowequal: 1.16 KB (0.586%)
  <self>: 1.16 KB (100%)
array-findindex-polyfill: 947 B (0.469%)
  <self>: 947 B (100%)
is-promise: 165 B (0.0817%)
  <self>: 165 B (100%)
<self>: 138.68 KB (70.3%)
```
And that is including all of @jdalton's lodash trickery, like [`babel-plugin-lodash`](https://github.com/lodash/babel-plugin-lodash). It comes down to how expensive it is to do a proper `deepEquals()`.

**Comment by jdalton** [comment]
It's hard to gauge this as the full build of Lodash v4.15.0 is 23KB gzipped. None of these numbers show the minified/gzipped size. It may have been covered in the past but you could reduce the build by sticking with `lodash` over mixing `lodash` and `lodash.xyz` packages.

Here's an example of this snippet bundled using `babel-plugin-lodash` and `lodash-webpack-plugin`:

#### index.js
```js
import { omit } from 'lodash';
omit({ 'a': 1, 'b': 2 }, ['b']);
```

#### output
```shell
➜  bar webpack index.js bundle.js
Hash: 0a64efcab7e950e4519c
Version: webpack 1.13.1
Time: 1687ms
    Asset     Size  Chunks             Chunk Names
bundle.js  14.1 kB       0  [emitted]  main
    + 18 hidden modules

➜  bar webpack index.js bundle.js
Hash: 0a64efcab7e950e4519c
Version: webpack 1.13.1
Time: 1852ms
    Asset     Size  Chunks             Chunk Names
bundle.js  2.52 kB       0  [emitted]  main
    + 18 hidden modules

➜  bar gzip-size bundle.js | pretty-bytes
918 B

➜  bar webpack index.js bundle.js --json | webpack-bundle-size-analyzer
lodash: 10.8 KB (97.8%)
<self>: 243 B (2.15%)
```

The actual minified+gzip size of the bundle is 918B (so less than 1KB).
The ungzipped size minified size is 2.52 kB.

**Comment by erikras** [comment]
`redux-form.min.js.gz` is `16,661 bytes`

**Comment by jdalton** [comment]
@erikras It's even less. (when gzipping for web folks use a level of 9 instead of the default 6)
```shell
gzip-size redux-form.min.js| pretty-bytes
16.54 kB
```

**Comment by jdalton** [comment]
Even better with [brotli](https://github.com/google/brotli) at 14.33 kB

**Comment by wmertens** [comment]
That's good enough for me, closing :)
