### ISSUE TITLE
value and onChange is not passed into custom input components

### ISSUE THREAD

**Issue by tugberkugurlu** [erikras/redux-form#1485]
[Here](http://redux-form.com/6.0.0-rc.4/docs/faq/CustomComponent.md/), it says:

> The minimum interface needed for a custom component to work with redux-form is to make sure that value and onChange are passed properly. 

However, I cannot see `value` and `onChange` being passed into my `ServerSelection` component with my below usage:

```js
<Field name="server" component={ServerSelection} servers={servers} />
```

I can see  `value` and `onChange` under `this.props.input`:

![image](https://cloud.githubusercontent.com/assets/328122/17476650/042efa2a-5d59-11e6-9de5-702fe630d858.png)

I worked around the issue for now:

```js
<Field name="server" component={props => 
    <ServerSelection servers={servers} 
        value={props.input.value} 
        onChange={props.input.onChange} /> } 
/>
```

**Comment by erikras** [comment]
Thanks. Those docs were out of date. You are correct in the way you have figured out to do it.
