### ISSUE TITLE
 prop type `touched` is invalid; it must be a function, usually from React.PropTypes

### ISSUE THREAD

**Issue by 10thfloor** [erikras/redux-form#1487]
`"redux-form": "^6.0.0-rc.3"`

Trying out the canonical text input example and I'm getting this error, I'm not sure what is going wrong here...

#### Component code:

```js
import React, {PropTypes} from 'react';
import TextField from 'material-ui/TextField';

const renderTextField = ({ input: { label }, name, type, touched, error }) => (
  <TextField
    id={name}
    type={type}
    hintText={label}
    floatingLabelText={label}
    errorText={touched && error}
  />
);

renderTextField.propTypes = {
  error: PropTypes.string,
  input: PropTypes.object,
  name: PropTypes.string,
  touched: PropTypes.boolean,
  type: PropTypes.string,
};

export default renderTextField;
```

<img width="669" alt="redux-form-error" src="https://cloud.githubusercontent.com/assets/901466/17490550/35eba51e-5d58-11e6-8748-af0d283328e6.png">

Same error occurs with a regular (non-material-ui) input.

**Comment by erikras** [comment]
`touched` was under `input` in `6RC3`. I recommend upgrading to `6RC4`, where [it is now under `meta`](https://github.com/erikras/redux-form/releases/tag/v6.0.0-rc.4).

e.g.
```js
const renderTextField = ({ input, name, type, { meta: { touched, error } } }) =>
```
