### ISSUE TITLE
[v6 rc4] File input validation

### ISSUE THREAD

**Issue by HriBB** [erikras/redux-form#1488]
I'm not sure if this is a bug or not, but form is not validated when file input changes.

Steps to reproduce
1. open form with file input
2. click on file input to open the dialog and select some file
3. click on file input again, but don't select any files, just close the dialog
4. no files are selected and no errors are displayed

This is my console log output
```
==> validate
action @ redux-form/UPDATE_SYNC_ERRORS 
action @ redux-form/REGISTER_FIELD 
action @ redux-form/FOCUS 
action @ redux-form/BLUR 
==> validate
==> onInputChange number of files 1
action @ redux-form/FOCUS 
action @ redux-form/BLUR 
==> validate
action @ redux-form/UPDATE_SYNC_ERRORS 
==> onInputChange number of files 0
action @ redux-form/FOCUS 
```

I am using Chrome 52.0.2743.116 (64-bit) on Linux.

@erikras you can close this issue if this is intended behavior.

**Comment by erikras** [comment]
Well, I'm a little concerned that there is no `CHANGE` action dispatched. It looks like maybe you have overridden the default `props.input.onChange` and forgotten to call it.

**Comment by HriBB** [comment]
Ohhhh stupid me :) I upgraded to `rc4` which uses a different `Field` props structure and forgot to call `props.input.onChange`. I guess my head is not working right from too much work :) Anyway it works now, thank you very much!

Closing the issue, however I believe that there's still one use case where I have to resort to a somewhat hacky solution to suppress the error. When browser dialog is opened, the `Field` is blurred and error is shown, so I attach an additional `onClick` handler to set the `opened` property to true and when browser dialog is closed, `Field` is focused again and I set `opened` to false, and error is shown as expected. 

I am attaching my `UploadField` implementation for the reference and in hopes someone finds a better/cleaner solution:

```
import React, { Component, PropTypes } from 'react'
import classnames from 'classnames'

import './UploadField.scss'

/**
 * Selectfield polyfill until mdl implements it
 *
 * Note: onFocus/onBlur timeouts are needed for mdl animations to work.
 *
 * @see https://github.com/google/material-design-lite/issues/4475
 * @see https://github.com/google/material-design-lite/issues/854
 */
export default class UploadField extends Component {

  constructor(props) {
    super(props)
    this.state = { focused: false }
    this.opened = false
  }

  onFocus = (e) => {
    this.opened = false
    this.props.input.onFocus(e)
    this.focusTimeout = setTimeout(() => {
      this.focusTimeout = null
      this.setState({ focused: true })
    })
  }

  onBlur = (e) => {
    this.props.input.onBlur(e)
    this.blurTimeout = setTimeout(() => {
      this.blurTimeout = null
      this.setState({ focused: false })
    })
  }

  onChange = (e) => {
    this.props.input.onBlur(e)
    if (this.props.onChange) {
      this.props.onChange(e)
    }
  }

  onClick = (e) => {
    this.opened = true
  }

  componentWillUnmount() {
    if (this.focusTimeout) clearTimeout(this.focusTimeout)
    if (this.blurTimeout) clearTimeout(this.blurTimeout)
  }

  render() {
    const { browse } = this.refs
    const { input, label, meta: { pristine, touched, visited, error, dirty }, ...other } = this.props
    const files = browse && browse.files.length
    const className = classnames({
      'mdl-uploadfield': true,
      'mdl-uploadfield--floating-label': true,
      'is-dirty': dirty,
      'is-focused': this.state.focused,
      'is-invalid': error && (touched || visited) && !files && !this.opened,
    })
    const props = {
      type: 'file',
      onFocus: this.onFocus,
      onBlur: this.onBlur,
      onClick: this.onClick,
      onChange: this.onChange
    }
    return (
      <div className={className}>
        <input className={'mdl-uploadfield__input'} ref={'browse'} {...input} {...other} {...props}/>
        <label className={'mdl-uploadfield__label'}>{label}</label>
        {touched && error && <span className="mdl-uploadfield__error">{error}</span>}
      </div>
    )
  }

}
```

If anyone is interested, I can post `UploadField.scss` as well ;)
