### ISSUE TITLE
Question: how to handle async validation exception and retry

### ISSUE THREAD

**Issue by mschipperheyn** [erikras/redux-form#149]
Ok, so I am validating a password against the server. The form has two fields and a submit button. Both fields are required which is checked "sync". 

The async server validation return an error and so the password field gets marked with an exception: allValid = false. 

Now, if I don't change anything, and I try to resubmit the form, sync validation will not reevaluate the status of the password field, which has content and should therefore pass validation, and remove the validation exception on the password field. 

But, anything typed in the password field will run sync validation again, clear the validation exception and allow me to resubmit. 

But what if the async exception was caused by the server being down or I entered a 4g dead zone? I might just want to resubmit since the values are correct.

Correct me if I'm wrong, but seems like handleSubmit doesn't do a sync validate before going to asyncValidate and therefore doesn't clean up any field specific exceptions that might have been created by the previous async submission. Perhaps there is a better way for me to handle this or this is considered an edge case.

**Comment by erikras** [comment]
If I were you, I'd be doing the password validation on the server on submit, not on password blur. The async validation on blur is mostly for things like choosing a unique username. Does that make sense?

**Comment by mschipperheyn** [comment]
Well, I don't use asyncBlur, I was just talking about asyncValidate. I consider asyncValidate the actual form submit, since I don't see why I would do two round trips to store an item (through handleSubmit). The case still holds regardless, I think, which is essentially: after an asyncValidation exception, a field has to be changed (which in turns runs sync validation and clears the exception) in order for resubmission to work again.

**Comment by erikras** [comment]
[Async validation](http://erikras.github.io/redux-form/#/examples/asynchronous-blur-validation) is much more robust now in v3. [I recommend upgrading](https://github.com/erikras/redux-form/releases/tag/v3.0.0).
