### ISSUE TITLE
onChange event not firing using checkbox

### ISSUE THREAD

**Issue by mb0606** [erikras/redux-form#1494]
From Doc  5.3.0 

```
       <div>
          {Object.keys(this.state).map(field =>
            <label key={field}>
              <input type="checkbox"
                checked={this.state[field]}
                onChange={event => this.setState({ [field]: event.target.checked })}/> {labels[ field ]}
            </label>
          )}
        </div>
```

The checkbox does not change state from checked to unchecked. I had to use a work around which works

```
                  <label key={"academic"}>
                    <input type="checkbox"  value="academic" checked={prefs.academic} {...academic}
                      onChange={(event) => {
                        academic.onChange(event.target.checked)
                        prefs.academic = !academic.checked
                        this.handleCheckChange()
                      }}
                    /> Academic
                  </label>
```

**Comment by jonjaques** [comment]
@mb0606, That's actually how you're supposed to do it. Shouldn't be using setState, as form state is held in the reducer.

**Comment by jonjaques** [comment]
However, I'm having the same issue in `6.x`.

```
<Field component="input" type="checkbox" props={{ onChange(e) { console.log(e) } }} />
```

Am I using this correctly?

**Comment by jervi** [comment]
There is no reason to use the `props` attribute. This (kind of) works (the function fires):
```jsx
<Field component="input" name="myCheckbox" type="checkbox" onChange={e => { console.log(e); }} />
```
However, by setting the onChange attribute, you are hijacking the event from redux-form, so the form state will not update. If you just do this, it should work:
```jsx
<Field component="input" name="myCheckbox" type="checkbox" />
```

**Comment by jonjaques** [comment]
Hmm, I wasn't able to get it to trigger via either props or directly passing onChange - however, I'm using a custom `component` function, and I may not have been passing properly there. 

I'm using react-bootstrap, which itself has a form abstraction - so that could possibly be the issue. 

I ended up adding special logic to my `component` fn, and I'm using the `change` action creator to fire off the values into redux. Dirty but it works.

**Comment by clayne11** [comment]
You shouldn't need to do that. Can you post a gist of all the code you're using?

**Comment by jonjaques** [comment]
Sure! BTW, this is straight out of a WIP app that is on a tight schedule - so please excuse the hackiness, I'm almost certainly doing it wrong :)

https://gist.github.com/jonjaques/2878d539f3c8ea08bd268d37170cd1b6

**Comment by danielrob** [comment]
Closing, please update/request re-open if this usage/support issue is still relevant.
