### ISSUE TITLE
Payload not updated on redux-form/CHANGE

### ISSUE THREAD

**Issue by nilaybrahmbhatt** [erikras/redux-form#1497]
Hi , i currently using 

```
"react": "15.2.1",
"react-native": "0.30.0",
```

and 

```
"react-redux": "^4.4.5",
"redux": "^3.5.1",
"redux-form": "^6.0.0-alpha.13",
```

but when i started writing on textbox  "redux-form/CHANGE " event fired but payload is undefined in that..

problem occurs after updating react-native
![screen shot 2016-08-09 at 11 38 11 am](https://cloud.githubusercontent.com/assets/6310631/17506410/48c9a98c-5e26-11e6-9d62-6fee5e63accd.png)

**Comment by erikras** [comment]
@nilaybrahmbhatt I don't use `react-native`. Can you do some research and figure out where the value is in the `SyntheticEvent`? The code where `redux-form` is trying to read the value is in [`getValue()`](https://github.com/erikras/redux-form/blob/180c4201e264add64f1cd44f56167b16b2ec6267/src/events/getValue.js#L16-L40). See if you can figure out what has changed between versions of `react-native`.
