### ISSUE TITLE
Can I use redux-form without redux?

### ISSUE THREAD

**Issue by CrisLi** [erikras/redux-form#1498]
Redux-form is awesome, it helps me reduce a lot of code. I am thinking that whether we can use redux-form without redux. I am looking at Mobx recently, is that possible combine Mobx and redux-form?

**Comment by erikras** [comment]
No. `redux-form` depends on `react-redux`.

**Comment by harsimranb** [comment]
@erikras I saw the twitter post saying that this is now possible. https://twitter.com/dan_abramov/status/630774054237175808?lang=en.  Is this documented somewhere? Couldn't find any documentation.
