### ISSUE TITLE
Simple form example causes TypeError: this.refs is undefined in 6.0.0-rc.3

### ISSUE THREAD

**Issue by thj-dk** [erikras/redux-form#1499]
I'm giving 6.0.0-rc.3 a try but I'm stuck with the simplest example. I've been following the new Getting Started guide.

I'm receiving the following error: `TypeError: this.refs is undefined`
Thrown here, in redux-form.js:
```
{
	key: 'valid',
	get: function get() {
		return this.refs.wrapped.getWrappedInstance().isValid();
	}
}
```

```
// TestForm.jsx
import React from "react";
import { Field, reduxForm } from "redux-form";

class TestForm extends React.Component {
    render() {
        const { handleSubmit } = this.props;

        return (
            <form onSubmit={handleSubmit}>
                <div>
                    <label>First Name</label>
                    <Field name="firstName" component="input" type="text"/>
                </div>
                <div>
                    <label>Last Name</label>
                    <Field name="lastName" component="input" type="text"/>
                </div>
                <div>
                    <label>Email</label>
                    <Field name="email" component="input" type="email"/>
                </div>
                <button type="submit">Submit</button>
            </form>
        );
    }
}

TestForm = reduxForm({
  form: 'contact'
})(TestForm);

export default TestForm;



// TestPage.jsx
import React from "react";
import PageContent from "components/PageContent";
import IBox from "components/IBox";
import TestForm from "./TestForm";

export default class FindOrders extends React.Component {
    showResults(values) {
        console.log(values);
    }

    render() {
        return <PageContent header="Ordre Oversigt">
            <IBox>
                <TestForm/>
            </IBox>
        </PageContent>
    }
}
```

**Comment by hathawsh** [comment]
I'm not sure if this is the cause, but I noticed you're defining the name TestForm twice in the same scope. Depending on the way you're compiling the Javascript, your browser might be choosing the first or second definition of TestForm. To prevent any possible name clash, I would replace this:

```javascript
TestForm = reduxForm({
  form: 'contact'
})(TestForm);

export default TestForm;
```
... with this:
```
export default reduxForm({
  form: 'contact'
})(TestForm);
```

**Comment by davidfurlong** [comment]
> TestForm = reduxForm({
>   form: 'contact'
> })(TestForm);
> 
> export default TestForm;

The Simple example Erik provides does the same.

**Comment by hathawsh** [comment]
That's true. The cause is probably something else. I've never seen the error you're encountering, sorry.

**Comment by thj-dk** [comment]
All right. I'll continue debugging to see if there's something conflicting with redux-form.

**Comment by thj-dk** [comment]
So, I've found the issue. It's when the webpack loader react-hot is enabled for jsx files. If I remove this, redux-form is working as expected.

Anyone using the react-hot loader with redux-form 6?

**Comment by hathawsh** [comment]
FWIW, I'm using webpack-hot-middleware (based on https://github.com/davezuko/react-redux-starter-kit) instead of react-hot-loader. I've seen one nasty compilation error (it broke a `let` variable with a different value per branch), but other than that, it has been working for the last few months.

**Comment by aarryy** [comment]
The same issue here. react-hot loader causing the issue also confirmed.

**Comment by erikras** [comment]
It sounds like this is caused by `react-hot-loader` and is not a problem with this library. I'd recommend submitting an issue over there.

**Comment by aarryy** [comment]
Just for those who are interested, upgrading `react-hot-loader` to 3.0.0-beta.2 fixed the issue for me. Although it brought another react-router related issue when using async routes in the project, I did find a way to overcome that issue after some searching.
