### ISSUE TITLE
De-emphasize ES7 in docs

### ISSUE THREAD

**Issue by gaearon** [erikras/redux-form#15]
The important part is that it's reducer factory + HOC.
ES7 decorator is just neat syntax sugar for applying HOC, rather than a central idea of this repo.
Currently, README makes it sound like using it requires enabling ES7 decorators, which is not the case.

I suggest downgrading the examples to ES6 like in [React Redux new README](https://github.com/gaearon/react-redux), and maybe showing ES7 decorator syntax as bonus at the end.

**Comment by erikras** [comment]
Good call. I'm working on an API-breaking change, and I'll include this in it.

**Comment by gaearon** [comment]
:+1:

Btw I'm thrilled about this lib. It shows a pattern I've been really missing in my apps.

**Comment by erikras** [comment]
How about now?

**Comment by gaearon** [comment]
Good! I submitted #18.
Description in Github project header should also be updated.
