### ISSUE TITLE
Question: How to duplicate connectReduxForm() within custom connect()

### ISSUE THREAD

**Issue by webmasterkai** [erikras/redux-form#150]
I understand there is convenience and some opinion by using `connectReduxForm()` but I'm struggling to understand how to include the actions and properties in my own connect() wrapper.

After reading your ducks-modular-redux proposal I was a little disappointed not to find something similar here. It looks like #17 was basically asking the same question. I can't tell if anything came out of it.

In your DynamicForm example you create a new class within the render function and then wrap that new class with `connectReduxForm()`. In my case I have already wrapped the DynamicForm component with a redux connect() and it's confusing why I can't include the necessary props/actions at that time. Is it possible to wire things up (gain access to the action creators) without connectReduxForm? I like to keep my components as dumb as possible. To me, connecting to redux within the component file adds too much intelligence.

Maybe I'm just missing something obvious...

Thanks for all your contributions and any help you can provide!

**Comment by webmasterkai** [comment]
Okay, maybe my answer was just further down the README... https://github.com/erikras/redux-form#advanced-usage

**Comment by erikras** [comment]
:smile: :+1:
