### ISSUE TITLE
Proper way to change connected fields

### ISSUE THREAD

**Issue by 2j2e** [erikras/redux-form#1500]
Let's assume you have countries and cities fields. If you select some country cities list should be rebuilded and selected value cleared. What's the proper way to handle it? I'm using v6-rc4 and Field wraps my custom component.

**Comment by erikras** [comment]
First of all, congrats on submitting issue #1500. 🎉 Hooray for round numbers!

Two options:

1. Middleware - you could have a middleware piece that could listen for a `redux-form/CHANGE` action for the `country` field, and then calls the `loadCities()` action creator which would load the cities.
2. You could use a [`formValueSelector`](http://redux-form.com/6.0.0-rc.4/docs/api/FormValueSelector.md/) to inject the value of the `country` field into your component as a prop, and then in `componentWillUpdate()`, listen for changes to the `country` prop and fire off the city loading from there.

**Comment by umidbekkarimov** [comment]
@erikras what about updating city field (setting value to null) ?

p.s. Saw you today in YouTube, great job!

**Comment by clayne11** [comment]
You can fire a `CHANGE` action to update the field in question.

**Comment by 2j2e** [comment]
@erikras Nice explanation. I took 2nd option. Example for other researchers:
```js
import { formValueSelector, change } from 'redux-form'
const formSelector = formValueSelector('form');
@connect(state => ({
  country: formSelector(state, 'country'),
  city: formSelector(state, 'city'),
}
```
``` js
componentWillUpdate(nextProps) {
    if (this.props.country != nextProps.country) {
      this.props.dispatch(change('form', 'city', ''));
    }
}
```

**Comment by kailashvele** [comment]
What if I have to clone as well and map the country state and city for each iteration separately?

**Comment by yentsun** [comment]
In 2017 you can easily handle filed change with sagas!
In the component
```
// no handling here
<Field name="query" type="text" id="query" component="input" />
```
In the saga:
```
export function* fecthWithQuery(query) {
    try {
        const {data: {list}} = yield call(api.get, '/something/', {
            params: {query}
        });
        yield put(actions.queryListReceived(list));
    } catch (error) {
        yield put(actions.requestFailed('Failed to get list by query', error));
    }
}

export function* handleFormChange({meta: {field}, payload}) {
    yield call(delay, 500);  // debounce
    switch (field) {
        case 'query':
            yield call(fecthWithQuery, payload);
    }
}

function* formWatcher() {
    yield takeLatest('@@redux-form/CHANGE', handleFormChange);
}

export default formWatcher;
```

**Comment by siorra** [comment]
I spend two days for search solution or this issue
