### ISSUE TITLE
v5 Dynamic form fields are not in redux store until interation

### ISSUE THREAD

**Issue by vict-shevchenko** [erikras/redux-form#1501]
Hello, 

I have faced an issue, that when using dynamic forms, and adding new field it is not added to redux store until it is not been focused.

As a result, field value passed to handleSubmit function is `undefined`;

Also a side effect of this situation is that when form is initialized with `initilaValues = {a:1, b:2, c:3}`, and `fields=["a","b"]`, after "c" field is added dynamically it actually has an initial value in it(but not in redux store). When focusing "c" field - the value is getting cleared.

Is there some standard solution for such case?

Thanks for help.

**Comment by vict-shevchenko** [comment]
My temporary solution is manually call ```onBlur``` for newly added fields in the main form component, .

```
componentWillReceiveProps(new_props) {
        const new_fields = new_props.fields;
        const old_fields = this.props.fields;

        Object.keys(new_fields).forEach(field_name => {
            const new_field = new_fields[field_name];

            if (!old_fields[field_name]) {
                new_field.onBlur(new_field.touched ? new_field.value : new_field.initialValue);
            }
        }, this);
    }
```

**Comment by danielrob** [comment]
Closing with bulk close of v5 issues. If this issue still requires action and/or also affects v6/7, please request a reopen with details or raise a new issue. v5 PR's are still welcomed.
