### ISSUE TITLE
Documentaion link error - v6.0.0-rc.2

### ISSUE THREAD

**Issue by brendanmcgivern** [erikras/redux-form#1502]
The documentaion for v6.0.0-rc.2 examples navigates to v6.0.0-rc.1 examples when clicking on an example link.
 - Navigate to http://redux-form.com/6.0.0-rc.2/examples/
 - Click on any of the links under the Examples section on the left side navigation
 - Then from there, click another link under the Examples section on the left side navigation

After navigating to an example from an exmaple page, the url swaps from v6.0.0-rc.2 back to v6.0.0-rc.1.

**Comment by erikras** [comment]
Yes, a mistake was made there, and thanks for pointing it out, but I don't think I'll be fixing the docs for old versions. Very soon there should be no one using the old RC's.
