### ISSUE TITLE
When destroyOnUnmount is set to false, values are getting reset

### ISSUE THREAD

**Issue by thanhvuong** [erikras/redux-form#1503]
I have a form (using rc4) with destroyOnUnmount set to false. When my component switches to a modal that calls the change action creator, the form calls redux-form/INITIALIZE and I lose all my values on the form.  It used to work in previous versions of redux-form. Is this a bug?

**Comment by erikras** [comment]
Try [`enableReinitialize: false`](http://redux-form.com/6.0.0-rc.4/docs/api/ReduxForm.md/#-enablereinitialize-boolean-optional-).

**Comment by thanhvuong** [comment]
Forgot to mention that I tried setting enableReinitialize to false despite the docs saying it defaults to false.

**Comment by d-winter** [comment]
Similar problem here (rc3).
Using destroyOnUnmount set to false and an object of default values.
After navigating to another route and back, the form is reinitialized.
Without the initial values it works.

**Comment by babsonmatt** [comment]
Is this a bug? @d-winter pls fix, thx

**Comment by jchiellini** [comment]
Has any progress been made on this issue? Because I just ran into it as well. Removing initial values will solve the issue, but that is a really heartbreaking solution since its the only was to pre-populate values into the form.

**Comment by erikras** [comment]
Will investigate. 🔍

**Comment by jchiellini** [comment]
Much appreciated sir.

**Comment by erikras** [comment]
This has been fixed by #1556. I will comment again here when the fix has been published in a release.

**Comment by babsonmatt** [comment]
@erikras thanks a lot

**Comment by erikras** [comment]
Fix published in [`v6.0.0-rc.5`](https://github.com/erikras/redux-form/releases/tag/v6.0.0-rc.5).
