### ISSUE TITLE
reselect + formValueSelector doesn't work

### ISSUE THREAD

**Issue by GuilhermeMedeiros** [erikras/redux-form#1505]
I'm trying to use `formValueSelector` together with `reselect`. Basically I need to verify if the value of one of the fields matches certain criteria, so I can show some other fields.

```js
const formSelector = formValueSelector('myForm')
const myFieldTitle = (state) => formSelector(state, 'title')
const doSomethingWithTitleSelector = createSelector(myFieldTitle, (title) => {
    return doSomethingWithTitle(title)
})

function doSomethingWithTitle() { ... }

const Form = reduxForm({
    form: 'myForm',
})(TheComponent)

export default connect(
    state => ({
        titleWithSomethingDone: doSomethingWithTitleSelector(state)
    })
)(Form)
```

I don't see a reason why it wouldn't work. If I send the `title` on the mapStateToProps the component renders again normally.

**Comment by GuilhermeMedeiros** [comment]
My bad. `react-select` changed their api slightly and I was doing a wrong check. The example above should work.

**Comment by rluiten** [comment]
Thanks for your issue pointed me in the right direction.
