### ISSUE TITLE
Two types of asynchronous validation

### ISSUE THREAD

**Issue by KateKate** [erikras/redux-form#151]
Hi! Thanks a lot for your form. I would like to make two different async validations: 1/ for submitting the form 2/ blur some fields. For async fields validation it's required another url and another response processing. How could I identify that validation was triggered due to field blurring? Thanks in advance!

**Comment by erikras** [comment]
I would recommend doing the submit validation when you actually submit the form. If the promise returned from the function passed to `handleSubmit` is rejected, the rejection reason can be your validation errors. Does that make sense?

```js
render() {
  const submit = (values) => {
    return new Promise((resolve, reject) => {
      // the ajax call would go here
      reject({ name: 'That username is taken' });
    });
  };
  const {fields, handleSubmit} = this.props;
  return (<div>
      // ... field rendering here ...
      <button onClick={handleSubmit(submit)}>Submit</button>
    </div>);
}
```

**Comment by KateKate** [comment]
Yep! Thanks for idea!

**Comment by KateKate** [comment]
Could you please give more details about dispatching submit validation.
I made as you advised, but replace `const submit` with `dispatch(validateForm(values))`. `validateForm` invokes action, that looks:
```
case SET_VALIDATION_ERROR:
    const errors = {};
    const errorsData = action.payload.errors;
    if (errorsData.length > 0) {
      for (let el of errorsData) {
        errors[el.source.parameter] = el.title;
        errors.valid = false;
      };
    }
    return {
      ...state,
      errors
    };
```
But it doesn't work, the form doesn't show the errors. Could you plz advice how could I set form errors with dispatch(action). Thanks in advance!

**Comment by erikras** [comment]
You need to be returning a promise. Do you have a redux middleware that returns promises?

**Comment by KateKate** [comment]
I use [redux-effects-fetch](https://github.com/redux-effects/redux-effects-fetch). 
The code of action:
```
import { fetch } from 'redux-effects-fetch';

function validateForm(data) {
  console.log(data);
  return bind(fetch(opt('formValidationUrl'), {
    method: 'POST',
    headers: {
      'content-type': 'application/json;charset=UTF-8'
    },
    body: JSON.stringify({user: data }),
  }), registerUser, setValidationError)
}
```
Should setValidationError also return the promise?

**Comment by erikras** [comment]
I had not seen `redux-effects` before. Interesting.

Here's how the `redux-form` submit validation works:

---
The `handleSubmit()` function that `redux-form` provides expects a `(values) => Promise` parameter. For you to get submit errors into `redux-form` that promise needs to be rejected with a `{field1: 'error1', field2: 'error2'}` shaped object.

---
What actions you dispatch inside that function is up to you.
