### ISSUE TITLE
Form refreshes after submit using synchronous validation

### ISSUE THREAD

**Issue by jeffschwartz** [erikras/redux-form#1510]
package.json:
```json
 "dependencies": {
    "babel-polyfill": "^6.9.1",
    "react": "^15.2.1",
    "react-dom": "^15.2.1",
    "react-redux": "^4.4.5",
    "react-router": "^2.6.0",
    "redux": "^3.5.2",
    "redux-form": "^6.0.0-rc.4",
    "redux-thunk": "^2.1.0"
  },
```

my form:
```javascript
import {Field, reduxForm} from "redux-form";

const validate = values => {
    const errors = {};
    let required = "Required!";

    console.log("validate called! values =", values);

    if (!values.name) {
        errors.name = required;
    }
    if (!values.company) {
        errors.company = required;
    }
    if (!values.category) {
        errors.category = required;
    }
    if (!values.rating) {
        errors.rating = required;
    }
    if (!values.vgpg) {
        errors.vgpg = required;
    }
    if (!values.nic) {
        errors.nic = required;
    }

    return errors;
};

const renderField = (field) => (
    <div className="form-item-container">
        <div className="label-container">
            <label htmlFor={field.name}>{field.label}: </label>
        </div>
        <div className="input-container">
            <input {...field.input} type="text" />
            {field.meta.touched && field.meta.error &&
            <span className="invalid-value">{field.meta.error}</span>}
        </div>
    </div>
);

const EliquidAddForm = ({handleSubmit, pristine, submitting, invalid}) => {
    console.log("handleSubmit", handleSubmit);
    return (
        <form onSubmit={handleSubmit}>
            <div className="form-container">
                <h2>Add A New Eliquid</h2>

                <Field name="name" label="Name" className="input-container__input" component={renderField} placeholder="enter name" autoFocus="true" />

                <Field name="company" label="Company" className="input-container__input" component={renderField} placeholder="enter company"/>

                <Field name="category" label="Category" className="input-container__input" component={renderField} placeholder="enter category"/>

                <Field name="rating" label="Rating" className="input-container__input" component={renderField} placeholder="enter rating"/>

                <Field name="vgpg" label="Vg/Pg" className="input-container__input" component={renderField} placeholder="enter vg/pg"/>

                <Field name="nic" label="Nic" className="input-container__input" component={renderField} placeholder="enter nic"/>

                <div className="form-item-container">
                    <div className="button-container">
                        <button type="submit" disabled={pristine || submitting || invalid}>Submit</button> <button type="button">Cancel</button>
                    </div>
                </div>
            </div>
        </form>
    );
};

export default reduxForm({
    form: "newEliquid",
    validate
})(EliquidAddForm);
```

When submitting the form, my form submit handler is called with the following:
![screen shot 2016-08-10 at 5 59 38 pm](https://cloud.githubusercontent.com/assets/271288/17572779/5c7d23ce-5f24-11e6-9715-dc20c5c679f7.png)

After submitting the form, the page is refreshed and the url in the browser address bar looks like the following:
```
http://localhost:8080/eliquid/create?name=1&company=2&category=3&rating=4&vgpg=5&nic=6
```

**Comment by hathawsh** [comment]
It looks like you need to provide an onSubmit function, otherwise the browser falls back to the default form submission mechanism, which is GET with a query string and a full page load.  There are two ways to provide the onSubmit function:

1. Provide the function directly to handleSubmit by changing `<form onSubmit={handleSubmit}>` to `<form onSubmit={handleSubmit(mySubmitFunction)}>`.

2. Provide an onSubmit prop in the component that creates your `EliquidAddForm`.  For example, `<EliquidAddForm onSubmit={mySubmitFunction} />`.

The documentation has an example of how to write a submit function: http://redux-form.com/6.0.0-rc.4/examples/submitValidation/

**Comment by hathawsh** [comment]
... or perhaps you provided a submit function, but an error is happening and the browser is reacting to the error by falling back to the default form submission mechanism. If that's the case, you should be able to see the error in the browser developer console.

**Comment by jeffschwartz** [comment]
@hathawsh I'm passing an onSubmit handler via props from a container component:
```javascript
import EliquidAddForm from "./eliquid-add-form";

const EliquidAddContainer = () => {
    const handleSubmit = () => {
        console.log("handleSubmit called, form values =", arguments);
    };
    return (
        <EliquidAddForm handleSubmit={handleSubmit}/>
    );
};

export default EliquidAddContainer;
```

And in the form component itself the handleSubmit prop is being consumed:
```javascript
onst EliquidAddForm = ({handleSubmit, pristine, submitting, invalid}) => {
    console.log("handleSubmit", handleSubmit);
    return (...);
```

No errors occur when the form is submitted and my handleSubmit callback is being called with a single argument but no field values and I am logging it to the console. Please see my original post above for the argument my handleSubmit callback is receiving.

**Comment by hathawsh** [comment]
Shouldn't `<EliquidAddForm handleSubmit={handleSubmit}/>` be `<EliquidAddForm onSubmit={handleSubmit}/>`? You need your form to call redux-form's handleSubmit, which in turn calls the onSubmit prop, which is your own handleSubmit function.

**Comment by jeffschwartz** [comment]
@hathawsh thank you very much. Yes, that clears up the refresh issue but my callback still isn't getting values passed to it. Here's what it is receiving:

![screen shot 2016-08-10 at 7 20 39 pm](https://cloud.githubusercontent.com/assets/271288/17574520/dcb6f4c4-5f2f-11e6-84c5-18d4208abac0.png)

**Comment by jeffschwartz** [comment]
@hathawsh it's now working. Sorry to have raised a bogus red flag :(. Thank you for your assistance. I am closing this one out.

**Comment by hathawsh** [comment]
I'm glad I could help!

**Comment by jeffschwartz** [comment]
@hathawsh btw I just learned that fat arrow functions do not have an arguments object. Well sort of because if you console.log(arguments) from within one in Chrome at least it does exist but it isn't the same object you would get if called from within a plain old function declaration. Live and learn lol. Thanks again.
