### ISSUE TITLE
Inconsistencies on custom Field components' props

### ISSUE THREAD

**Issue by marr** [erikras/redux-form#1512]
I am running into a strange issue where the props I set on a Field object are getting set on the child component differently depending on where I run them. For example, with a component defined:

```
// Label.js
render() {
  return this.props.children
}

and in use:
<Field component={Label}>Foo</Field> 
```

In some cases, I see `this.props.children` undefined but defined on `this.props.input.children`, and other times I see it defined in `this.props.children`.

Why would that be inconsistent?

**Comment by naw** [comment]
`<Field>` changes the structure of props it passes depending on whether the `component` you give it is a low-level DOM component (like `input`), or a high-level thing like `YourCustomComponent`.

**Comment by gustavohenke** [comment]
Hi @marr, I know this is quite old, but if you still see this problem, let us know including some code that reproduces your issue.
