### ISSUE TITLE
[5.3.1] No good way to dynamically exclude sync validator for conditional field

### ISSUE THREAD

**Issue by freen** [erikras/redux-form#1514]
I've also described this issue on StackOverflow: http://stackoverflow.com/questions/38871734/redux-form-how-do-i-dynamically-exclude-one-sync-validator/38878379

My redux-form decorated form component conditionally has an `email` field, depending on my redux state (depending on whether or not the user is a guest.)

I only want to sync-validate that field when it is present (when it is conditionally rendered.) The form's validator includes an email field validator, and currently this validator runs even when the field has been excluded from the form during render.

When I "instantiate" the form's validator, and when I pass the validator as an argument to the redux-form decorator, state isn't known. So I'm unable to decide whether to include the `email` field validator, in either of these places.

I think there should be a way to conditionally exclude / include / skip / invoke a particular field's sync validator, either based on state, or whether the field was rendered, etc.

Below: Problem Code, Hack Solutions, Possibly Good Solutions.
## Problem Code

**MyForm.js**

``` javascript
import validate from './MyFormValidator';

// [form class whose render optionally shows the email component]

export default reduxForm(
  {
    form: 'myForm',
    fields,
    validate // I don't know here if the email field will be rendered
  }
)(MyForm)
```

**MyFormValidator.js**

``` javascript
import {createValidator, required, email} from '../../utils/validation';

export default createValidator({
  email: [email], // I don't know here if the email field will be rendered
  country: [required],
  // ...
});
```

**utils/validation.js**

``` javascript
export function email(value) {
  // Was the input rendered? Should I be asking that question here?
  const emailRegex = /.../i;
  if (!emailRegex.exec(value)) {
    return 'Please provide a valid email address.';
  }
}

export function required(value, message) {
  if (isEmpty(value)) {
    return message || 'Required.';
  }
}

export function createValidator(rules) {
  return (data = {}) => {
    const errors = {};
    Object.keys(rules).forEach((key) => {
      const rule = join([].concat(rules[key]));
      const error = rule(data[key], data);
      if (error) {
        errors[key] = error;
      }
    });
    return errors;
  };
}
```

My sync validation is modeled after this implementation, linked to from the 4.2.0 redux-form docs (I'm using 5.3.1): https://github.com/erikras/react-redux-universal-hot-example/blob/master/src/utils/validation.js
### 1. Do a `null` check for the value inside the validator, to detect whether the input has been rendered.

This complicates the validator's logic and usage, invites bugs / misuse, and requires the additional hack that the input's value must, in the guest scenario, be explicitly set from null to an empty string, pre-render in `componentWillReceiveProps`. This is the only way the validator can distinguish between "the input wasn't rendered" and "the input wasn't touched".

Thanks to [@lewiscowper](https://twitter.com/lewiscowper) who suggested this solution on some JavaScript Slack. 

To avoid false-positive usages of the validator, I renamed it `emailUnlessNull`.

``` javascript
export function emailUnlessNull(value) {
  // Don't validate the text field if it's value is undefined (if it wasn't included in the form)
  if (value == null) {
    return;
  }
  const emailRegex = /.../i;
  if (!emailRegex.exec(value)) {
    return 'Please provide a valid email address.';
  }
}
```

**MyForm.js**

Here I have to explicitly set the value to an empty string, if I want validation to run. Otherwise if the input is never touched, the validator will pass, since it will receive a `null` value.

``` javascript
componentWillReceiveProps(nextProps) {
  const { values, fields, isGuestOrder } = this.props;
  // Set field's value to empty string so the validator knows it was rendered
  if (isGuestOrder && values.email == null) {
    fields.email.onChange('');
  }
}
```
### 2. Include the user's guest state as a hidden input, so that the data is accessible to all validators.

One shouldn't have to include inputs inside the form in order to communicate state or configure the form.
## Possibly Good Solutions
- **Map state to the validator?** It's the same information the Form component is using to render the field, or not.
- **Configure the validator inside the component?** Not sure if this goes against React patterns. But adding or removing fields, or totally configuring the validator, inside the component could also work.

**Comment by baronswindle** [comment]
I would modify the API of your `createValidator()` function. Allow it to take either an object or a function as an argument. If it's a function, it should accept `values` (form values) and `props` (from the decorated component) and return a rules object. This will allow you to modify the rules you validate against based on the values of props in the component.

```
    function createValidator(mapValuesAndPropsToRules) {
      return (values, props) {
        let rules;
        if (typeof mapValuesAndPropsToRules === 'function') {
          rules = mapValuesAndPropsToRules(values, rules);
        } else {
          rules = mapValuesAndPropsToRules;
        }
        return validate(rules, values);
      }
    }

    export function validateBasedOnMap(rules, values) {
      const errors = {};
      Object.keys(rules).forEach((key) => {
        const rule = join([].concat(rules[key]));
        const error = rule(values[key], values);
        if (error) {
          errors[key] = error;
        }
      });
      return errors;
    }

    export default createValidator((values, props) => {
      let rules = {
        country: [required]
      };
      if (/* check props */) {
        rules.email = [email];
      }
      return rules;
    });
```

**Comment by Mitch-Henson** [comment]
@freen and I work together and we finally got around to solve this issue. Just wanted to thank @baronswindle for the code snippet. It works like a dream!

**Comment by baronswindle** [comment]
@Mitch-Henson You guys inspired me to use a new validation pattern that has made our team much more productive, so I should be thanking you!

**Comment by danielrob** [comment]
Closing with bulk close of v5 issues. If this issue still requires action and/or also affects v6/7, please request a reopen with details or raise a new issue. v5 PR's are still welcomed.
