### ISSUE TITLE
[6.0.0-rc.4] type prop in documentation

### ISSUE THREAD

**Issue by vitaminwater** [erikras/redux-form#1515]
In this doc [here](http://redux-form.com/6.0.0-rc.4/docs/MigrationGuide.md/#-v6-):

`<input {...field.input}/>  // No type specified. That is specified below in <Field>`
then
`type="text"/>                     // "type" prop will get forwarded to <input>`

but the type prop appears outside the `input` attribute in props.

**Comment by erikras** [comment]
Great catch! That changed recently. Will fix.
