### ISSUE TITLE
Best practice to manipulate a field's value

### ISSUE THREAD

**Issue by mohebifar** [erikras/redux-form#152]
Assume that I need to change the value of username input field upon the change of last name field. The reason why the username should be kept on the input is to let the user manipulating it. The way to do it is to call the `change` action to change the value of *username* input. But we need to override the `onChange` prop on *lastName* input. It seems sloppy and I wonder if it has drawbacks.

```jsx
<input {...lastName} />
<input {...username} />
```

**Comment by erikras** [comment]
The best practice to manipulate `field2`'s value based on `field1`'s value is to use [a normalizer](https://github.com/erikras/redux-form#normalizing-form-data).

**Comment by mohebifar** [comment]
Thanks.
One other thing, let's say if there was no `field1`. For example, if we needed to change `lat` and `lng` pair input values by dragging around a marker on a Leaflet or Google map.

**Comment by erikras** [comment]
Same thing. If you want to restrict a value based on anything, you can "normalize" it. The code in the readme shows how to keep a string value in all upper case, for example. Just as easy to keep a lat-long coordinate within a certain radius.

**Comment by mohebifar** [comment]
No I didn't mean to keep it in a certain radius. See the image. I mean changing those values by dragging that blue marker while the users can change it themselves.
 
![Example](https://cloud.githubusercontent.com/assets/6104558/10601214/bb4d7322-771c-11e5-9d58-4d49c9ee243b.png)

Normalizing is done in reducer. What I say is in component layer.

**Comment by erikras** [comment]
Sure, that can be done with `onChange` calls. Ideally, you'd have a map component that would either call `onChange` as the user drags the marker, and/or `onBlur` when the marker was dropped.

**Comment by mohebifar** [comment]
I got it. :+1: Thanks.

**Comment by xcatliu** [comment]
@erikras, do you mean call the `this.props.fields.xxx.onChange()` directly?

**Comment by erikras** [comment]
@xcatliu Yes, you may do that. If `onChange` receives an event (if it was passed to an input), it will try to get the value from the `event.target`, but you can also just call `onChange(newValue)`.

**Comment by xcatliu** [comment]
@erikras Thx~

**Comment by xcatliu** [comment]
@erikras How can I know the ending of onChange? Is there any API like this:

```js
onChange(newValue, callback);
```

**Comment by erikras** [comment]
No, `onChange` is synchronous.

**Comment by xcatliu** [comment]
@erikras If I call `this.props.handleSubmit()` after `onChange`, the values seems not update. Code fragment:

```js
handleClick() {
  // do something
  this.props.fields.xxx.onChange(newValue);
  console.log(this.props.values);                       // not update
  this.props.handleSubmit();                              // submit old values
}
```

**Comment by erikras** [comment]
That is true. The props get repopulated on a subsequent process tick.

I suspect that there is a flaw in your design if you are wanting to `onChange` and `handleSubmit` in the same code block. But you could conceivably do something like:
```js
this.props.onSubmit({ // <---- what handleSubmit would call
  ...this.props.values,
  xxx: newValue
});
```

**Comment by xcatliu** [comment]
@erikras Yes I get it, thanks for helping me!

**Comment by gabrielhpugliese** [comment]
Is there any way to change multiple values at once without using initialize()? What I'm doing right now is:
```
const values = getValues(form.signupPF);

initialize('signupPF', Object.assign({}, values, {
  address,
  neighborhood,
  city,
  state
}), Object.keys(fields));
```

Is this correct?

**Comment by erikras** [comment]
@gabrielhpugliese No, there is no form of the `CHANGE` action that works on multiple fields. If you didn't want to use `initialize`, which will affect your `dirty`/`pristine` state, you will have to dispatch the `CHANGE` actions individually for each field.

**Comment by gabrielhpugliese** [comment]
No problems with initialize, just to know if it would be OK or would cause some weird side-effect. Thanks.

**Comment by anselmdk** [comment]
@erikras when I'm trying to call `this.props.onSubmit` I'm getting `Uncaught TypeError: this.props.onSubmit is not a function`. I also don't find it in http://erikras.github.io/redux-form/#/api/props - maybe the api has changed?

**Comment by anselmdk** [comment]
...I'm using `4.1.4`.

**Comment by gabrielhpugliese** [comment]
Tried this.props.handleSubmit?

**Comment by anselmdk** [comment]
Yeah, that works, but I want to pass additional data, like this:
```js
this.props.onSubmit({ // <---- what handleSubmit would call
  ...this.props.values,
  xxx: newValue
});
```

**Comment by anselmdk** [comment]
Also `this.props.handleSubmit();` seems to work, while doing this and trying to manipulate the data seems to just fail silently.
```js
this.props.handleSubmit(data => {

});
```

**Comment by erikras** [comment]
@anselmdk Because `onSubmit` is a specific proprietary prop for `redux-form`, it is removed from the props. You will need to call your prop something else (e.g. `submitForm`) for it to show up in the props of your decorated component.

**Comment by anselmdk** [comment]
@erikras thanks. In the end I ended up using the solution with the hidden field, as I also needed to do some different validation based on the field value - seems to work okay!

**Comment by astrauka** [comment]
@erikras 
> The props get repopulated on a subsequent process tick

I am using async validation to fetch postal code from server once member changes it.
Member also has ability to change country, thus I need to rerun the validation on country change.
Currently I delay the postal code field touch to allow country field to update it's value.
Is there an option to determine when the field got updated such that I don't wait too long or too short?

**Comment by joaoreynolds** [comment]
the ability to run onChange on multiple values in one action would be great. Or rather, in my situation, I want to replace an entire subdocument array with a new one.

In other words, I have a "field": `'collectionFields[].orderNum'`. `collectionFields` is an array of input fields my users can configure and reorder. So I'm changing the orderNum values for `collectionFields`. I was hoping to just take my array of collectionFields, change the ordering of them, and replace it with an identical array of redux-form objects, but with new values for orderNum. (my reordering component returns a new array of objects with orderNum values) Something like:

`this.props.fields.collectionFields.replace(orderedFields)` This assuming orderedFields is an array of redux-form instances (or whatever you call them).

My alternative working solution for now is:
```
this.props.fields.collectionFields.map((myFormField, index) => {
      myFormField.orderNum.onChange(orderedFields[index].orderNum.value)
    })
```

It's annoying though, because the `redux-form/CHANGE` action is dispatched a whole bunch of times for what seems could be done in a single action.

Just an enhancement recommendation.

**Comment by szokrika** [comment]
Hi, I'm trying to do this:

```
addressUpdated(newAddress) {
    //TODO, tell Redux form that a value is now available!
    this.props.fields.address.onChange(newAddress.label);
  }
```
**address** is a hidden field that should get a value once addressUpdated is called.
I get an error
```
Uncaught TypeError: Cannot read property 'onChange' of undefined
```

Component is generated:

```
<Field id="address" name="address" type="hidden" component={fieldFactory} />
```
```
const fieldFactory = ({id, input, label, type, meta: { touched, error } }) => {
if(type.match(/hidden/)){
    return(
      <div>
      <input id={id} {...input} type={type} />
      {touched && error && <span>{error}</span>}
      </div>
    );
  }
}
```

Any ideas?

**Comment by chaitanya0bhagvan** [comment]
@szokrika I had the same issue when migrating from v5 to v6. I solved it like this by giving a **ref**  and adding **withRef={true}** to the Field I would like to modify.

`<Field type='text' ref='name' withRef={true} label='Name' name='Name' component={renderInput} value={this.state.location.name}/>`

When I want to change the field value I do this 

`this.refs.name.getRenderedComponent().props.input.onChange(newName);`

Please note this Cannot be used if your component is a stateless function component

**Comment by Jevgenius** [comment]
Hey!

Im kinda new to react. And couldn't figure out how and where i should rewrite my onChange to get things working. PS. Im using react-select as my selectInput component.

here is part of my form. I would appriciate of any concrete examples with the custom onChange.

```
const BasicForm = props => {
const { error, handleSubmit, pristine, reset, submitting, countries, phonePrefixes } = props;
return (
        <div className="form step1">
            <form onSubmit={handleSubmit}>
                <Field
                    name="country"
                    className="form-control"
                    component={selectInput}
                    options={countries}
                    placeholder="Country"
                />
                <Field
                    name="phonePrefix"
                    className="form-control"
                    component={selectInput}
                    options={phonePrefixes}
                    placeholder="Prefix"
                />

                <button type="submit" disabled={submitting}>REGISTER
                    <i className="fa fa-chevron-right">&nbsp;</i>
                </button>
            </form>
        </div>
)};
```

**Comment by kaueburiti** [comment]
@Jevgenius in your case you should write the custom onChange in the `selectInput` file, and pass this custom onChange to the `react-select`.

**Comment by zackshen** [comment]
@erikras i'm using redux-form v6, where is `props.fields` property ? i can't find it in the api document, Does it be removed ?

**Comment by saitonakamura** [comment]
@zackshen It was removed, see the [v5->v6 migration guide](http://redux-form.com/6.6.1/docs/MigrationGuide.md/)

**Comment by anmol1591** [comment]
**Stories**
storiesOf("URLField", module)
  .add("default", () => (
    <ThemeProvider theme={theme}>
      <URLField primaryLabel="Your Team Url" secondaryLabel="(letters, numbers and dashes only)" urlDescription=".taskvalue.com" warningText="For some weird reason, that didn’t work. Please try again to continue" validUrl="true" />
    </ThemeProvider>
  ))

**code**
const URLField = ({ validUrl , urlDescription, primaryLabel, warningText, secondaryLabel }) => (
  <Wrapper>
    <Label small grey>{primaryLabel}</Label>
    <Label small green>{secondaryLabel}</Label>
    <Urlwrapper>
      <Input validUrl={validUrl} />
      <Text>{urlDescription}</Text>
    </Urlwrapper>
    <Warning>
      <img src={alert} alt="" />
      <Text warning>{warningText}</Text>
    </Warning>
  </Wrapper>
);


**CSS**
input {
    text-align: right;
    display: inline-block;
    padding: 10px 2px;
    background: ${props => props.validUrl === "true" ? `url(${valid}) no-repeat left 10px center` : `url(${invalid}) no-repeat left 10px center`};
  }

Any idea about how to change background

**Comment by himawan-r** [comment]
@xcatliu if i may ask, where did you get the reference this.props.fields.xxx.onChange()? i wanted to try this, i cannot seems to get the fields reference from onchange of my first field?
