### ISSUE TITLE
[6.0.0-rc.4] Set defaultValue after first focus?

### ISSUE THREAD

**Issue by cpsubrian** [erikras/redux-form#1521]
I'm sure I'm missing something obvious here, but I tried doing the following and it messed with the actual 'focusing' of the field in weird ways.

```js
const MyDateField = (props) => {
  return (
    <input
      {...props.input}
      type='text'
      onFocus={(e) => {
        props.input.onFocus(e)
        if (!props.input.value) {
          props.input.onChange('today')
        }
      }}
    />
  )
}
<Field name='date' component={MyDateField}/>
```

**Comment by clayne11** [comment]
Why aren't you setting the value when the form is rendered rather than when the field is focused?

**Comment by erikras** [comment]
Yes, this should be done with [`initialValues`](http://redux-form.com/6.0.0-rc.5/docs/api/ReduxForm.md/#-initialvalues-object-string-string-optional-).

**Comment by cpsubrian** [comment]
More of a question than a issue, so no need to re-open, but what I actually want is an empty field on init, and only fill a default date in if they focus the (empty) field.

**Comment by cpsubrian** [comment]
Aka, like the title says 😉

**Comment by erikras** [comment]
Okay, how about you hide the value until the field is `visited`?

```jsx
<input {...props.input} value={props.meta.visited ? props.input.value : ''}/>
```

That would do it.

**Comment by cpsubrian** [comment]
That looks really clean. Will give it a shot.  Thanks!
