### ISSUE TITLE
How to get Field value and pass it to FieldArray value with Push event? V6-RC3

### ISSUE THREAD

**Issue by haaswill** [erikras/redux-form#1522]
I have a FieldArray component supposed to show telephones. The user can add a telephone object containing a number Field, a type Field and a button to add the phone into the phone list(FieldArray).

The Phone List component contains a button with the function fields.remove(index) which I pass the phone index to.

**My phone object is:** {number: number, type: type}

**Currently using:** React 0.15.3, Redux-Form 6.0.0-rc3, Material-UI 0.15.3

**Phone fields declaration:**
`<Field name="phoneNumber" component={renderMaskedTextField} label={"Telefone"} type="text" mask="(99) 9999-99999"/>`

`<Field name="phoneType" component={renderSelectField} label="Tipo">
      {PHONE_TYPES.map((option, index) => {
        return <MenuItem value={option.value} primaryText={option.label} key={index}/>;
      })}
</Field>`

**Code I use to add the phone component into the list:**

`<IconButton onClick={() => handleAddClick({number: field.input.phone.number, type: field.input.phone.type})} style={styles.addButton}>
   <Add color="#fd084a"/>
</IconButton>`

**I need a way to get both Field values and pass it to my handleAddClick()**

**Add function:**

`const handleAddClick = (phone) => {
   fields.push(phone);
};`

**Also open to new ways to solve this :D**

**Comment by cwallervand** [comment]
Sound like this might be related to issue #1448 "Access to values with FieldArray" ?

**Comment by clayne11** [comment]
I'm not really following what you're trying to do with the code. I don't think it's related to #1448 though. Can you post a more complete gist of how you're using all of these components together? Also when writing Javascript in the issue please use ````javascript` to open your code tag so it get's highlighted properly and is easier to read.

**Comment by haaswill** [comment]
Sorry, I will try to explain my case better.
So, I have a two steps wizard form. On the second step, I have a FieldArray:
(Clean version of my wizard form)
```javascript
      <form onSubmit={handleSubmit}>
        <Card style={styles.card}>
          <CardHeader style={styles.cardHeader} title="Traga seu negócio para o scheduler" titleStyle={styles.cardHeaderTitle} textStyle={styles.cardHeaderText}/>
          <CardText style={{padding: 0}}>
            <div style={styles.cardText}>
              <FieldArray name="phones" component={renderPhones}/>
            </div>
          </CardText>
          <CardActions style={styles.cardActions}>
            <div style={styles.actionButtons}>
              <FlatButton label="Voltar" onTouchTap={handlePrevious}/>
              <RaisedButton label="Cadastrar!" primary={true} type="submit"/>
            </div>
          </CardActions>
        </Card>
        {renderAlert}
      </form>
```
In another file, I have my wrappers for Material-UI components, within this wrappers, I have the declaration of `renderPhones` used by `<FieldArray/>`.
Here is my declaration:
```javascript
export const renderPhones = ({fields}) => {
  const PHONE_TYPES = [
    { value: "Fixo", label: "Fixo"},
    { value: "Celular", label: "Celular"},
  ];
  const renderPhone = field => (
    <div style={styles.field}>
      <div style={styles.phone}>
        <p style={{margin: 0}}>{field.input.phone.number} - {field.input.phone.type}</p>
        <IconButton onClick={(e) => handleDeleteClick(field.input.index)} style={styles.deleteButton}>
          <Delete color="#fd084a"/>
        </IconButton>
      </div>
      {field.touched && field.error && <div className="error">{field.error}</div>}
    </div>
  );
  const handleAddClick = (phone) => {
    fields.push(phone);
  };
  const handleDeleteClick = index => {
    fields.remove(index);
  };
  return (
    <div style={styles.phones}>
      <List style={{padding: 0}}>
        {fields.map((phone, index) =>
          <Field name={`phone_${index}`} component={renderPhone} phone={phone} index={index} handleDeleteClick={handleDeleteClick} key={index}/>
        )}
      </List>
      <div style={styles.phoneField}>
        <Field name="phoneNumber" component={renderMaskedTextField} label={"Telefone"} type="text" mask="(99) 9999-99999" style={{display: "flex", alignSelf: "stretch", flexDirection: "column", flex: 3}}/>
        <Field name="phoneType" component={renderSelectField} label="Tipo" style={{marginLeft: 10, display: "flex", alignSelf: "stretch", flexDirection: "column", flex: 2, height: 72}}>
          {PHONE_TYPES.map((option, index) => {
            return <MenuItem value={option.value} primaryText={option.label} key={index}/>;
          })}
        </Field>
        <IconButton onClick={() => handleAddClick({number: field.input.phone.number, type: field.input.phone.type})} style={styles.addButton}>
          <Add color="#fd084a"/>
        </IconButton>
      </div>
    </div>
  );
};
```
And here are the components used by `renderPhones`:
```javascript
export const renderSelectField = field => (
  <div style={field.input.style ? field.input.style : styles.field}>
    <SelectField {...field.input} onChange={(e, index, value) => field.input.onChange(value)} value={field.input.value} floatingLabelText={field.input.label} fullWidth>
    </SelectField>
    {field.touched && field.error && <div className="error">{field.error}</div>}
  </div>
);

export const renderMaskedTextField = field => (
  <div style={field.input.style ? field.input.style : styles.field}>
    <TextField hintText={field.input.hintText} floatingLabelText={field.input.label} fullWidth type={field.input.type} {...field.input}>
      <InputMask mask={field.input.mask} maskChar={field.input.maskChar}/>
    </TextField>
    {field.touched && field.error && <div className="error">{field.error}</div>}
  </div>
);
```
I hope I made myself clear, thanks for the response.

**Comment by naw** [comment]
You have two fields (`phoneNumber` and `phoneType`) that belong to your main form, whose values you want to "copy" into a `FieldArray` whenever the user clicks a button.

The values for those two fields are stored in the redux store. The typical way to get those values is to `connect` a component to the store in advance, so that the current values are always available to the component as props.  Then, when the button is clicked, you just read the values from props.

You need to `connect` your `renderPhones` component to `phoneNumber` and `phoneType` using `formValueSelector`.

At least, that's one way to do it.

**Comment by clayne11** [comment]
I don't think that's the correct approach.

You have a couple of issues with your code.

1. You need to use `fields` name for it's child components. The way you are assigning the name as `phone_${index}` will not work:

```javascript
        {fields.map((phone, index) =>
          <Field name={phone.name} component={renderPhone} phone={phone} index={index} handleDeleteClick={handleDeleteClick} key={index}/>
        )}
```

2. You're attempting to use two fields in the `redux`, namely `phoneNumber` and `phoneType` into the `phones` array. You are running into the issue that @naw mentioned above, but I don't like the idea of using other values in the form to populate the new entry in `phones`.

There's two solutions to this.

1. Simply push a new, empty object, and have the user fill it out AFTER they've pushed it into the store. That way the entry they are making is directly updating the correct area in the store.

1. If you're hellbent on allowing the user to enter the information before pushing it into the array, I would use a separate form for `phoneNumber` and `phoneType`, and upon submitting that form push the values from that form into the `phones` array.

**Comment by haaswill** [comment]
Thank you @naw and @clayne11, now I understand my issue.
My first thought was to make a blank entry and then let the user fill it. I like your idea @clayne11. I am still struggling to think the React way, but I do want to. I will change my functional components to class components and rearrange my phone to match what your idea. I will post it here when it's done.

**Comment by clayne11** [comment]
I'm not saying to use class components. Use functional components, but give them a camel-cased noun name describing what they are rather than a verb name describing what they're rendering. I'm simply suggesting changing the name of the component from `renderPhones` to `PhoneFieldArray` or something of the sort.

**Comment by haaswill** [comment]
Oh, now I get it, yet I agree with you, @clayne11. Thanks for the tip.

**Comment by haaswill** [comment]
So, here is my refactored component:
```javascript
export const PhonesFieldArray = ({fields}) => {
  const PHONE_TYPES = [
    { value: "Fixo", label: "Fixo"},
    { value: "Celular", label: "Celular"},
  ];
  return (
    <div style={styles.phones}>
      <List style={{padding: 0}}>
        {fields.map((phone, index) => {
          return (
            <div style={styles.field} key={index}>
              <div style={styles.phoneField}>
                <Field name={`${phone}.number`} component={MaskedTextFieldWrapper} hintText={"Telefone"} type="text" mask="(99) 9999-99999" style={{flex: 3, marginRight: 2}}/>
                <Field name={`${phone}.type`} component={SelectFieldWrapper} hintText="Tipo" style={{flex: 2, maxHeight: 48, width: 108}}>
                  {PHONE_TYPES.map((option, index) => {
                    return <MenuItem value={option.value} primaryText={option.label} key={index}/>;
                  })}
                </Field>
                <IconButton onClick={() => fields.remove(index)} style={styles.deleteButton}>
                  <Delete color="#fd084a"/>
                </IconButton>
              </div>
            </div>
          );
        })}
      </List>
      <FlatButton label="Adicionar telefone" type="button" onClick={() => fields.push()}/>
    </div>
  );
};
```
