### ISSUE TITLE
[Development] Add eslint-plugin-import

### ISSUE THREAD

**Issue by clayne11** [erikras/redux-form#1525]
`eslint-plugin-import` is a great `eslint` plugin that speeds up development by detecting any unresolvable imports. We should add it to the project to help catch these issues as early as possible.

**Comment by clayne11** [comment]
Ran into an issue with this PR.

Tracking the fix in `eslint-plugin-import` https://github.com/benmosher/eslint-plugin-import/issues/416

**Comment by erikras** [comment]
Can you PR this?

**Comment by clayne11** [comment]
I will do it sometime this week.
