### ISSUE TITLE
[6.0.0-rc.4] Error on submitting form

### ISSUE THREAD

**Issue by amboy00** [erikras/redux-form#1527]
This all previously worked, but I'm updating react/redux and redux-form and now I have js errors.

This is a component loaded into a product page.

```javascript
import React, { Component, PropTypes } from 'react';
import { reduxForm } from 'redux-form';
import { addProduct } from './actions';

class AddProductForm extends Component {
  
  onSubmit(props) {
    this.props.addProduct(props);
  }

  render() {
    const { fields: { productID }, handleSubmit } = this.props;

    return (
      <form onSubmit={handleSubmit(props => this.onSubmit(props).bind(this))}>
        <input type="hidden" {...productID} />
        <button type="submit">Add to Cart</button>
      </form>
    );
  }
}

const formData = {
  form: 'AddProductForm',
  fields: ['productID']
}

export default reduxForm(formData, null, {addProduct})(AddProductForm);
```

the error that's returned is **"You must either pass handleSubmit() an onSubmit function or pass onSubmit as a prop"**.

If I update that one line of code to be `<form onSubmit={handleSubmit}>`  I no longer get the error.  However, on submit the same error comes up.

[update]  I've fudged the code around to get rid of that error, but it looks like I might have taken one step forward and took another step back. `addProduct` isn't a part of `props` any more.  So how would I now call that function from my actions?

**Comment by amboy00** [comment]
Found the solution in #1491.

```javascript
// export default reduxForm(formData, null, {addProduct})(AddProductForm);
export default connect(null, {addProduct})(reduxForm(formData)(AddProductForm));
```

I think this would be a good candidate to include in the migration docs.

**Comment by asincrono** [comment]
Thanks God (well, not really, thanks you).
It was driving me mad.
Couldn't see anything in the docs.
I'm tired. Thanks. Really tired.
