### ISSUE TITLE
 Unknown prop `model` on <form> tag

### ISSUE THREAD

**Issue by colorfulberry** [erikras/redux-form#1529]
`warning.js?8a56:44 Warning: Unknown prop `model` on <form> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop     in form`

The browser has this warning

**Comment by brotzky** [comment]
That was a new addition to React v15.2.0
https://github.com/facebook/react/blob/master/CHANGELOG.md#1520-july-1-2016
https://twitter.com/dan_abramov/status/751066839359361024

The latest version of Redux Form has no issues with this. Double check the props you are passing yourself and remove what's not needed. It looks like `prop model` can be removed in your case.

**Comment by colorfulberry** [comment]
@brotzky  Ge it, Thanks  help.
