### ISSUE TITLE
Readme doesn't include examples for input types other than "text"

### ISSUE THREAD

**Issue by albinekb** [erikras/redux-form#153]
I think the title says it all.
How do i use this with checkbox, radio, textarea?

**Comment by erikras** [comment]
This is a very valid criticism of the README. Thank you for bringing it up.

But until I can get around to remedying it, checkout [SurveyForm.js](https://github.com/erikras/react-redux-universal-hot-example/blob/master/src/components/SurveyForm/SurveyForm.js) ([demo running here](https://react-redux.herokuapp.com/survey)).

**Comment by albinekb** [comment]
Thank you :+1: That's useful, I'm new to react so it's hard to figure out how to do it without examples!

**Comment by erikras** [comment]
[Better examples now, with v3](http://erikras.github.io/redux-form/#/examples/simple).
