### ISSUE TITLE
[v6.x] InitialValues are assign even when fields don't exist

### ISSUE THREAD

**Issue by andrewmclagan** [erikras/redux-form#1530]
in [0.6.x] InitialValues are assign even when fields don't exist.

for example 
````javascript
const initialValues = {
	name: 'Andrew',
	age: 32
	height: 192,
};

<MyForm initialValues={initialValues} />
 
````

Where Form only has `name` and `age`:

````javascript
<form>
	<Field name="name" />
	<Field name="age" />
</form>
````

When submitting the `values` parameter `onSubmit` still has all the fields from initial values. should it not only be passing through properties/fields that are actually relating to form field components?

that is why hidden fields exist?

**Comment by JMacLulich** [comment]
Would it be possible to only send through initial parameters that are in the form? instead of relying on `onSubmit` to filter the parameters you can do it before hand.

This does seem like a BUG though.

**Comment by andrewmclagan** [comment]
Yah I can do it, although it seems like a responsibility of the library to me.

**Comment by erikras** [comment]
It does not seem obvious that one way is better than another. For instance, I often will load a record from the server that is shaped like `{ id: 42, name: 'redux-form', starred: false }` and only show inputs for the values that I want to edit. It's especially nice for the `onSubmit` function to get back the full object, with its unique id to send back to the server.

**Comment by andrewmclagan** [comment]
Yeah the more u think on it, cleaning out those properties could hinder allot of use cases. Better to have the data then not at all
