### ISSUE TITLE
(V6.0.0-rc.4) Action creator no available in props while using reduxForm call.

### ISSUE THREAD

**Issue by asincrono** [erikras/redux-form#1532]
I'm trying to call an action creator when I push the submit button.
First I import my action creator `loginRequest`
```
import loginRequest from '../../actions/loginActions'
```

Then I write a class method that will call that action creator (as it should be accessible via props)
```
class LoginForm extends Component {
  constructor(props) {
    super(props)
    this.handleFormSubmit = this.handleFormSubmit.bind(this)
  }
 
  handleFormSubmit ({ email, password }) {
    console.log('hola')
    this.props.loginRequest(email, password)
  }
```

In my form I have the handlesubmit call
```
render () {
    const {handleSubmit, reset, pristine, submitting, valid } = this.props
    return (
      <form onSubmit={handleSubmit(this.handleFormSubmit)}>
        <Field
          name="email"
          label="Email"
...
```

Finally I call `reduxForm` to make the action creator accessible via props:
```
export default reduxForm(formOptions, null, { loginRequest })(LoginForm)
```

But inside `handleFormSubmit` I'm unable to see the property `loginRequest`. As it's undefined.

I don't understand what is happening. Shouldn't the action creators passed to `reduxForm` third argument visible in the LoginForm props?

**Comment by rluiten** [comment]
redux-form does not perform mapStateToProps or mapDispatchToProps.
You still need to use connect() from react-redux for that.
An example which shows this is http://redux-form.com/6.0.0-rc.4/examples/initializeFromState/

**Comment by asincrono** [comment]
Thanks @rluiten. Probably should be explicit in migration. Same happened in [#1527](https://github.com/erikras/redux-form/issues/1527) and [#1491](https://github.com/erikras/redux-form/issues/1491).
