### ISSUE TITLE
Can I do some validation before submit?

### ISSUE THREAD

**Issue by gezichenshan** [erikras/redux-form#1535]
E.g. I have a form with 4 inputs.I hope the 1st & 2nd inputs validated when I click the "Get cell phone verification code" and the 3rd and 4th still pristine.
Can I make this through?

**Comment by brotzky** [comment]
Yes, just don't create any validation functions for the 3rd and 4th inputs. I don't think it's possible to keep certain inputs of a form pristine when you call handleSubmit. If you really need that functionality, you can try separating the 4 inputs into 2 separate forms.

**Comment by gezichenshan** [comment]
@brotzky Thanks for your reply.
My example includes "Get cell phone verification code"button and "submit"button.I just want the 1st & 2nd inputs validated when I click the former one and the whole 4 inputs validated when I click the latter one, i.e., the submit button.
I want to keep them in one form. Is there any possibilities?

**Comment by brotzky** [comment]
Hm, not that I'm aware, sorry.

**Comment by gezichenshan** [comment]
Thank you.I create a submit function func() and do mapStateToProps.Then I call it in parent container by this.refs.xxx.stateProps.func().Not the best solution,but meets what I need.
