### ISSUE TITLE
[v6 rc4] Redux-form and DateTimePicker from react-widgets

### ISSUE THREAD

**Issue by KseniyaT** [erikras/redux-form#1536]
Hello!

Does redux-form 6.0.0-rc.4 work with DateTimePicker (react-widgets version 3.4.4)?

I have an error when i am trying to use the code:

```
const dateTime = ({input, ...rest}) =>
  <DateTimePicker
    {...input}
    format='LL'
    onBlur={() => input.onBlur()}
    {...rest}
  />;
```

```
class DateField extends Component {
  constructor(props, context) {
    super(props, context);
  };
  render(){
    return (
      <Field
        component={dateTime}
        name={this.props.name}
        time={this.props.time}
      />
    )
  }
}
```

Thank you for your answer!

**Comment by JMacLulich** [comment]
Yes, it should work fine.

I'm using DateTimePicker as well, I use it like this:

in `componentDidMount`

```javascript
$('.date-input').datepicker({
       format: "dd/mm/yyyy",
       weekStart: 1,
       autoclose: true,
       todayHighlight: true,
       orientation: "bottom left",
   }).on('changeDate', handleDateChangeEvent);
```

and I have a function defined like this:

```
 handleDateChangeEvent(ev) {

    var fieldName = $(ev.target).attr('name')
    var value = moment(ev.date).format('DD/MM/YYYY')

    this.props.dispatch(this.props.blur(fieldName, value))
  }
```

and this handles setting the value of the form.

Cheers, Jason.

**Comment by JMacLulich** [comment]
@KseniyaT I realised later that it's not the same DateTimePicker! but hopefully I may have given you an idea to try out. I haven't used that particular react library. But I have used `react-bootstrap` extensively with `redux-form` but mostly just the modal stuff.

**Comment by KseniyaT** [comment]
@JMacLulich thank you for your fast answer! :-)

**Comment by KseniyaT** [comment]
It is nessesary to pass value into onBlur().

const dateTime = ({input, value, ...rest}) =>
  <DateTimePicker
    {...input}
    format='LL'
    value={value}
    onBlur={() => input.onBlur(value)}
    {...rest}
  />;
