### ISSUE TITLE
[6.0.0-rc.4]How do I get rid of DOMPropertyOperations warnings?

### ISSUE THREAD

**Issue by chrisngobanh** [erikras/redux-form#1538]
![screen shot 2016-08-15 at 10 31 24 am](https://cloud.githubusercontent.com/assets/8410793/17673017/0de67874-62d4-11e6-9731-7668e110ef33.png)

When I create an input field with Redux Form with the type `email`, I keep getting these warnings printed to my console. This doesn't happen when I create an input field normally.

In other words, 

```
<input
  name="email"
  type="email"
/>
```
The above doesn't show any warnings when I type in the field.

```
<Field
  name="email"
  type="email"
  component="input"
/>
```
The above shows warnings when I type in the field. 

IIRC, I did not see this issue when I was using earlier versions of Redux Form.

How do I prevent these warnings from showing up?

**Comment by brotzky** [comment]
Appears to be related to Chrome and React. You can see the warning is coming from within React.
`DOMPropertyOperations.js?930e:147`

https://github.com/facebook/react/issues/7487

**Comment by erikras** [comment]
Nice call, @brotzky. Closing this.
