### ISSUE TITLE
submit validation example is missing something

### ISSUE THREAD

**Issue by djshapiro** [erikras/redux-form#1540]
The [Submit Validation example](http://redux-form.com/6.0.0-rc.4/examples/submitValidation/) defines a submit.js file with a submit function, but that function never get used. I assume it's meant to be used in SubmitValidationForm.js.

**Comment by BenBarber** [comment]
The submit function should be passed though to your form as a prop labeled onSubmit. This is then bound to the handleSubmit action which handles the form submission.

**Comment by erikras** [comment]
Thanks for pointing that out. 👍 Fixed in [`v6rc5` version of the docs](http://redux-form.com/6.0.0-rc.5/examples/submitValidation/).

```jsx
import submit from './submit'

...

<form onSubmit={handleSubmit(submit)}>

...

</form
```
