### ISSUE TITLE
[6.0.0-rc.4] Getting SET_SUBMIT_FAILED on Safari

### ISSUE THREAD

**Issue by ReLrO** [erikras/redux-form#1541]
I am getting SET_SUBMIT_FAILED on every form submit when using Safari. This is how one of my forms look like:

```
import React from 'react'
import { reduxForm, Field } from 'redux-form'

const validate = (values) => {
  const errors = {}
  if (!values.name) {
    errors.name = 'Required'
  }
  return errors
}

export class CreateGroupForm extends React.Component {

  render () {
    const { handleSubmit } = this.props

    return (
      <form className='main-banner__form' onSubmit={handleSubmit}>
        <div className='form-group'>
          <div className='form-control contenteditable'>
            <div className='contenteditable__container'>
              chatsummit.com/
              <Field className='contenteditable__input' placeholder='______________' type='text'
                name='name' component='input' />
            </div>
          </div>
          <button type='submit' className='button button--default button--rounded'>Get Started</button>
        </div>
      </form>
    )
  }
}
CreateGroupForm.propTypes = {
  handleSubmit: React.PropTypes.func.isRequired
}

export default reduxForm({
  form: 'CreateGroup',
  validate
})(CreateGroupForm)
```

This works without issues both on Chrome and on Firefox, but not on Safari. 
I will appreciate any help.

Thanks!

**Comment by erikras** [comment]
What does your Redux store look like? Is there any `meta` data in the `SET_SUBMIT_FAILED` action?

**Comment by BraunreutherA** [comment]
Hi there, I got the same problem - in any browser. When the fields are empty I get an empty Object but as soon as I fill the form the error occurs. In the action there is some meta but no description about the error:

{
  "form": "signup",
  "fields": {
    "0": "email",
    "1": "password"
  }
}

**Comment by ReLrO** [comment]
Sorry for not updating sooner. I figured out the issue and it was not related to the new redux-form. I am using fetch to make async calls and fetch didn't work well with Safari until I installed whatwg-fetch and followed their package instructions.

**Comment by BraunreutherA** [comment]
Never mind, i've set the non immutable reducer and used the immutable version later on. Sorry for confusion.

**Comment by renanbandeira** [comment]
@BraunreutherA what reducer are you using? I'm facing a non related issue with Safari (when the LOAD action is dispatched I get a blank screen with no errors) and redux storage and I wonder if you are using the same library
