### ISSUE TITLE
Loading initialValues asynchronously from saga [question]

### ISSUE THREAD

**Issue by oakley808** [erikras/redux-form#1542]
Hi.
What is the best way to handle initialization where the initialValues are loaded asynchronously? I found the "[Initialize From State](http://redux-form.com/6.0.0-rc.4/examples/initializeFromState/)" example quite helpful, but it only got me part way to the finish line.

I put out an action from my redux-saga after the initializing data was fetched from the server.

```
yield put({ 
  type: 'redux-form/INITIALIZE',  
  meta: { form: 'myReduxForm' }, 
  payload: myfetchedData 
})
```

Is there a better way to handle it?

**Comment by erikras** [comment]
That seems fine. You should use the [`initialize()` action creator](http://redux-form.com/6.0.0-rc.4/docs/api/ActionCreators.md/), though.

```js
import { initialize } from 'redux-form'
```

**Comment by gustavohenke** [comment]
My usual plan for this is, from my saga, trigger an action that stores the data.
Then I use a selector to get the value out of the store, directly into the `initialValues` prop.

It's just one way to do it, Erik's idea is another 😄
