### ISSUE TITLE
addField and removeField are not updating dirty

### ISSUE THREAD

**Issue by tb** [erikras/redux-form#1543]
I have redux-form like:

    form: 'itemsForm',
    fields: [
      'items[].id',
      'items[].name'
    ],

Both `addField` and `removeField` for items are not updating `dirty` (see http://redux-form.com/5.3.1/#/api/props)

How can I fix it?

**Comment by erikras** [comment]
This is a known bug of `v5` that will most likely never be fixed. It was part of the impetus behind the complete redesign of `v6`.

Related: #391

**Comment by danmo** [comment]
@erikras this ticket/issue shouldn't be ignored just because it has backward compatibility implications.

Either provide a deep pristine check solution by adding a new form property (deepPrestineEnabled:true?) or provide an accepted workaround.
