### ISSUE TITLE
Help needed on FieldArray with React Component

### ISSUE THREAD

**Issue by ozum** [erikras/redux-form#1544]
Hi,

With `redux-form v6.0.0-rc.4`, I'm trying to understand how to use FieldArray with a react component.

Below is simplified example which is an **anti-pattern** because of `this.props.fields.remove(index)`.

I will appreciate if someone show me an appropriate way to remove a form array element, when used with react component (not pure function).

Regards,

## ANTI-PATTERN
```js
class Lines extends React.Component {
  constructor(props) {
    super(props);
  }

  render() {
    return (
      <div>
        {this.props.fields.map((line, index) =>
          <div key={index}>
            <Field 
              name={`${line}.taxPercent`} 
              component="input" 
              type="number"
              defaultValue={line.taxPercent}
            />
            <button
              type="button"
              onClick={() => this.props.fields.remove(index)}>
                Delete
            </button>
          </div>
        )}
      </div>
    );
  }
}
```
```js
class MyForm extends React.Component {
  render() {
    <form onSubmit={this.props.handleSubmit}>
      <FieldArray name="lines" component={Lines} />
    </form>
  }
}
```

**Comment by erikras** [comment]
Why do you feel that this is an antipattern? How do you normally remove an item from an array without its index?

**Comment by ozum** [comment]
I intuitively thought that mutating props via `this.props.fields.remove()` is an anti-pattern. I should have missed something and posted here for help.

After some investigation I see that `this.props.fields.remove()` creates an action and does not mutate props. **(I'm still not sure about that, am I correct with this?)**

If my guess is correct and it does not mutate, could you please add documentation for Field Array example with custom react component and a message about that Array Field methods do not mutate props. That would really helpful for redux and redux-form beginners like me. `pop`, `shift`, `remove` etc. seems like mutators.

**Comment by erikras** [comment]
Thank you for this. 👍 You made a very reasonable assumption. I have updated the docs.
