### ISSUE TITLE
[v6 rc4] Question: dispatch actions onBlur to increase form speed

### ISSUE THREAD

**Issue by vladra** [erikras/redux-form#1551]
Is there anyway to change default behaviour for form, to dispatch actions not onChange event, but after onBlur event.

I can't find this in documentation anywhere, but I've seen few people mentioned this ability in other issues.

Currently my form contains 36 fields, and it's pretty slow. So I was thinking about how to improve performance

Thanks in advance

**Comment by kristian-puccio** [comment]
Remember to test with the prod build of react, makes a massive difference.

I think you only need to apply the onChange on blur thing you mentioned to
text inputs and text areas.

Have a look at this gist:
https://gist.github.com/kristian-puccio/3a03b96109331c13e6cdf37aead958b1

Basically I'm ignoring the onChange and dealing with that only inside the
class. The onBlur triggers as per normal.

**Comment by vladra** [comment]
Great! Thans for tip
