### ISSUE TITLE
Input loses focus after a single "keyDown" event

### ISSUE THREAD

**Issue by m2mathew** [erikras/redux-form#1557]
Using v6.0.0-rc.4 with the Material-UI library. We are using ImmutableJS, so I thought I would try out the version 6 with Immutable built in.

Definitely a noob at using Redux-form, so I probably should not jump in on the most cutting-edge version. However, the library seems to take care of several things that can be a hassle in other settings. I have all of my validation and everything working fine, but want to see if this library can make it easier to reason about across our entire app.

When my input field has an `onChange`, the field loses focus after entering a single character...specifically when the key is initially pressed. I know that redux-form works `onBlur`, but using that instead of `onChange` seems to do nothing different.

Below, the `DescriptiveTextField` you see is just a decorative wrapper for the MUI `TextField` component.

Thanks for any help in these untested waters for me! 😄 

```javascript
renderCCForm() {
    const CCDetails = this.props.accountCreditCardDetails;

    const ccField = ({ input, label, type, meta: { touched, error } }) => (
      <DescriptiveTextField
        errorText={touched ? error : ''}
        floatingLabelText="Credit Card Number"
        onChange={this.handleUpdateCreditCardInfo}
        value={formatCCNumber(CCDetails.get('CardNumber'), CCDetails.get('Type'))}
        width="224px"
        {...input}
      />
    );

    return (
      <div>
        <Field
          component={ccField}
          name="ccNumber"
          type="text"
        />
     .........and so on
```

**Comment by clayne11** [comment]
You're creating a new function in each render. You need to move the component definition outside of the render function.

```javascript
    const ccField = ({ input, label, type, meta: { touched, error } }) => (
      <DescriptiveTextField
        errorText={touched ? error : ''}
        floatingLabelText="Credit Card Number"
        onChange={this.handleUpdateCreditCardInfo}
        value={formatCCNumber(CCDetails.get('CardNumber'), CCDetails.get('Type'))}
        width="224px"
        {...input}
      />
    );

renderCCForm() {
    const CCDetails = this.props.accountCreditCardDetails;

    return (
      <div>
        <Field
          component={ccField}
          name="ccNumber"
          type="text"
        />

```

**Comment by m2mathew** [comment]
Found that this issue is also referenced [here](https://github.com/erikras/redux-form/issues/1094) back in June 2016...just in case some wayward traveler ends up here one day.
