### ISSUE TITLE
[6.0.0-rc.5] form level error persisting in the store sometimes

### ISSUE THREAD

**Issue by bmv437** [erikras/redux-form#1564]
Hey @erikras, I found a bug(s) in the new implementation of `_error` for sync validation. There is also one small logic error that I fixed in #1558, before you pushed this fix out in #1560.

I believe you need to delete the `error` from the state if it got removed from the error payload, and field level errors still exist. otherwise the form level error persists until all field level errors are removed.

This should affect `STOP_ASYNC_VALIDATION`, `STOP_SUBMIT`, and `UPDATE_SYNC_ERRORS` action handlers.

in the reducer it currently looks like this:
```javascript
if (_error) {
    result = setIn(result, 'error', _error)
}
```

should look like this:
```javascript
if (_error) {
    result = setIn(result, 'error', _error)
} else {
    result = deleteIn(result, 'error')
}
```

Now I'm also seeing the `UPDATE_SYNC_ERRORS` action handler not firing when the result of `validate()` changes from `{ _error: 'something' }` to `{ }`

I think in `reduxForm.js` the `updateSyncErrorsIfNeeded` function needs to also take into account changes in the form level `error` prop. currently it only gets `nextSyncErrors`, but should also get something like `nextFormError` and compare to props.error and fire `updateSyncErrors`

I hope all that makes sense, and I'm not misunderstanding anything.

Thoughts?

**Comment by erikras** [comment]
Wow, I totally did not see #1558. Sorry about that.

**Comment by erikras** [comment]
I have fixed this bug. I messed up the commit, so I couldn't do a nice PR for it, thought.
