### ISSUE TITLE
feature request: Errors for collections

### ISSUE THREAD

**Issue by chrisbateman** [erikras/redux-form#1565]
Looking for the ability to add an error message to a group of checkboxes. For example, imagine a group of checkboxes with the error message: "You must select at least one option below."

FieldArray works great if you have a grouping of inputs which represent the same thing (they all share the same name/id in the data). But for this case - each checkbox would need to have a unique name/id.

One option might be to create a FieldCollection component which would be similar to FieldArray (but would manage an object, rather than an array).

Another option might be to make it so that you can provide an error message for a deeply nested object:

```javascript
<Field name="checkboxGroup.one" component="input" type="checkbox" />
<Field name="checkboxGroup.two" component="input" type="checkbox" />

// validate
errors.checkboxGroup = 'group error';
// or
errors.checkboxGroup = {_error: 'group error'};
```

**Comment by clayne11** [comment]
This already exists. If there is an `{_error: 'some error'}` on `checkboxGroup` it will be passed down to a field with the name `checkboxGroup`.

**Comment by chrisbateman** [comment]
@clayne11 Thanks for the response - I didn't see rc.5 was released this morning with `<Fields>`!

However, I'm not sure I quite understand how it's supposed to work. Here's what I'm doing:

```javascript
<Fields names={['checkboxGroup.one', 'checkboxGroup.two']} component={renderChecks} />
```

This validation code correctly causes the form to be invalid:
```javascript
errors.checkboxGroup = {
    one: 'field error'
};
```

But this does not:
```javascript
errors.checkboxGroup = {
    _error: 'group error'
};
```

I also tried the same validation code with 2 `<Field> elements, as in my original example, and I'm getting the same behavior.

I'm probably missing something...

**Comment by clayne11** [comment]
You don't need to use `Fields`. Just a simple `Field` component:

```javascript
<Field name='checkboxGroup'/>
```

That will receive the error prop: 
```json
{
  _error: 'Group error',
  one: 'One error',
  two: 'Two error',
}
```

**Comment by chrisbateman** [comment]
@clayne11 How would you put multiple inputs inside a single `<Field>`? I haven't been able to find any examples of this.

If I have `<Field name='checkboxGroup' component={renderGroup} />` - the `renderGroup` function will only have a single `field.input` prop to pass into an `<input>`.

**Comment by chrisbateman** [comment]
@clayne11 Nevermind, I think I figured it out - just put `<Field name="checkboxGroup.two">` inside `renderGroup`.
