### ISSUE TITLE
[v6rc5] validate is not a valid key when passing object to reduxForm()

### ISSUE THREAD

**Issue by jwyuen** [erikras/redux-form#1568]
I'm not sure if this was intended or not, but the docs make it seem like you should be able to have a validate: validator key pair.  As an example:

Does not work
```
SomeForm = reduxForm({
  form: 'someForm',
  validate: validation
})(SomeForm);
```

This works
```
SomeForm = reduxForm({
  form: 'someForm',
  validation
})(SomeForm);
```

I'm using v6 rc5 w/ react-boilerplate and following the Immutable example:
http://redux-form.com/6.0.0-rc.5/examples/immutable/

The docs in question:
http://redux-form.com/6.0.0-rc.5/docs/api/ReduxForm.md/

**Comment by erikras** [comment]
The key is `validate`. It sounds like you're doing something else wrong. Can you describe what you mean by "does not work"? Your `validation` variable is a function, right?

**Comment by jwyuen** [comment]
It works insofar as I don't see any errors in the console and it looks like the validation is working since I see messages in the console if I'm typing something that doesn't pass validation (such as a bad email address).  Before when I was passing `validate: validation`, it was giving me `Uncaught TypeError: values.get is not a function`. That being said I'm pretty new to the whole react redux ecosystem and that includes using redux-form.  

But ya `validation` is a function.  It's basically almost the same code that's on the Immutable example.

**Comment by jwyuen** [comment]
Ok it looks like I spoke too soon because it's actually still not working.  This might be an entirely different problem than the one I initially described because when I console.log(values) in my validation function like below, the value of `values` is initially a map object like `Map {size: 0, _root: undefined, __ownerID: undefined, __hash: undefined, __altered: false}` if I don't type anything into any of the fields.  If I type something into one of the fields, it's no longer a map object but rather just a plain object like `Object {clientName: "k"}`


Validate code:
```
const validate = (values) => {
  // IMPORTANT: values is an Immutable.Map here!

  console.log(values);
  const errors = {};
  if (!values.get('clientName')) {
    errors.clientName = 'Required';
  } else if (values.get('clientName').length > 2) {
    errors.clientName = 'Must be 15 characters or less';
  }
  if (!values.get('clientEmail')) {
    errors.clientEmail = 'Required';
  } else if (!/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i.test(values.get('clientEmail'))) {
    errors.clientEmail = 'Invalid email address';
  }
  
  return errors;
};

export default validate;
```

**Comment by jwyuen** [comment]
So I guess the simple 'fix' for this is to not use the `.get` function for the variable passed to the validate function.  But does that mean the object being passed to the validate function is not an immutable object?

**Comment by erikras** [comment]
The `values` passed to `validate` should be an immutable `Map` __*IF*__ you are importing everything from `'redux-form/immutable'`. It sounds like you aren't doing that.

**Comment by jwyuen** [comment]
I'm doing `import { Field, reduxForm } from 'redux-form/immutable'`, just like in the example in the docs (http://redux-form.com/6.0.0-rc.5/examples/immutable/).  I guess I should also mention I have this wired up in https://github.com/mxstbr/react-boilerplate

**Comment by jurStv** [comment]
@jwyuen I think your problem is that you should also `import { reducer } from 'redux-form/immutable'` like you do with `{ Field, reduxForm }`. It should solve missing `.get` method error on validation.

**Comment by jwyuen** [comment]
@jurStv Ah!  That was exactly it!  Thanks!
