### ISSUE TITLE
Confusing description about decorator syntax

### ISSUE THREAD

**Issue by ramdog** [erikras/redux-form#157]
Where the README reads...

>Using ES7 decorator proposal, the example above could be written as:

...it's a bit confusing.  What _part_ of the example could have been replaced?  It makes it seem like all you have to do is add that decorator to the class, but I think it's just referring to the bit below:
>// apply connectReduxForm() and include synchronous validation

Maybe worth clarifying.

**Comment by erikras** [comment]
You're right. I'm working on a rewrite of docs. Your suggestion will be taken into consideration. Thank you.
