### ISSUE TITLE
[v6rc3] anyTouched value does not update when Robot Selenium test fills a form

### ISSUE THREAD

**Issue by Merri** [erikras/redux-form#1572]
In my code I'm not submitting the form through usual means, because the form data is part of a much larger API request. Therefore to know whether to update values from a form managed by redux-form I check for the anyTouched value before SPA page transition to see if an API request has to be sent with updated values.

The problem is that anyTouched value doesn't appear to redux-form state upon a field change and this is troublesome with a Selenium test: it fills the form, but anyTouched value never gets set. This probably because blur events don't trigger as they would with human interaction, only change events.

I attempted to workaround this in a test by focusing to a form field and then focus to another element, but for some reason this doesn't seem to trigger state update; now it is getting too late for me to debug this in greater detail. I probably give up next week and just send the form data every time the page transition happens, removing the benefit of reduced API calls gained with anyTouched value.

It would be nice if anyTouched would reflect true state after immediate change instead of relying on user to trigger blur events.

**Comment by erikras** [comment]
I would guess that you are not seeing a `redux-form/BLUR` action dispatched, which means that Selenium is not calling `onBlur`. If that is the case, there's not really much that the library can do for you.

**Comment by Merri** [comment]
Looking further into this the problem is that no programmatical change causes any events to ever trigger. For example, doing this from console:

`document.querySelector('[name="testElement"]').value = 'Something'`

There is no `redux-form/CHANGE` or any other event.  This probably makes all browser testing tools incompatible. With Robot Framework and Selenium I can do this to workaround the problem:

`Execute Javascript      document.querySelector('[name="testElement"]').dispatchEvent(new Event('blur'))`

But this feels very hacky, because directly setting `.value` should cause a change to state. The only nice part is that doing a single blur event to any input field gets all the form state updated.

**Comment by erikras** [comment]
It sounds like there's nothing that `redux-form` can do about this as a library that provides event listeners, so I'm going to close this issue.
