### ISSUE TITLE
[v6] Redux-Form doesn't play well with ImmutableJS when using FieldArray

### ISSUE THREAD

**Issue by Reanmachine** [erikras/redux-form#1574]
I've created a full example with information about this problem here: [redux-form-failing-cases/immutable-array/](https://github.com/Reanmachine/redux-form-failing-cases/tree/master/immutable-array)

Here's a brief of the problem:
----

It seems that `form.fields.<name>` is being accidentally created as a `Map` instead of a `List` with relation to the `onBlur` or `onFocus` calls trying to set `touched` for an `FieldArray` when using ImmutableJS

*Additionally, the `value` for a field in a `FieldArray` field is defaulting to `Map()` which serializes out to the input as `"Map{}"`.*

Here's the description copied from the repository:
----

**Disclaimer:** I am new to `redux-form` and may very well be doing something incorrect, but I've tried
to follow the information available in the most recent documentation & some of the more important tickets
related to the issue:

* [[v6] Can't pass custom props to Field component #1397](https://github.com/erikras/redux-form/issues/1397)
* [Poll: Field component props structure #1425](https://github.com/erikras/redux-form/issues/1425)

I made this repository mostly because it was easier to illustrate the problem as I'm not intimately
familliar with the `redux-form` codebase.

**I suspect the problem is related to [this line](https://github.com/erikras/redux-form/blob/v6/src/reducer.js#L39) 
in `reducer.js`**. I believe that calling `setIn` here may be the problem as the object at `${key}` (in this case 
`fields.things` doesn't exist, so when it creates `things` it does what is described in the 
[immutableJS documentation](https://facebook.github.io/immutable-js/docs/#/Map/setIn):

> Returns a new Map having set value at this keyPath. If any keys in keyPath do not 
> exist, **a new immutable Map will be created** at that key.

This seems to be triggered when the `onFocus` and `onBlur` get fired as they need this object to
specify if it was `touched` or not.

**Comment by erikras** [comment]
Excellent reporting and analysis! 👍👍 This was the source of several other bugs as well. Fixed by #1591. I will comment here again when the fix has been released.

**Comment by erikras** [comment]
Published in [`v6.0.1`](https://github.com/erikras/redux-form/releases/tag/v6.0.1).

**Comment by Reanmachine** [comment]
@erikras Unfortunately only one of the problems was solved in [`v6.0.1`](https://github.com/erikras/redux-form/releases/tag/v6.0.1).

I'm still encountering `list.splice is not a function` because the `setIn` call during `FOCUS` is inserting the value as `Map`. 

## Reason

Lodash's `toPath` doesn't have any indication of paths that are sourced from arrays. The path `thing[0]` just becomes `["thing", "0"]`.

Additionally ImmutableJS's `setIn`, `updateIn` has two problems with how it's being used:

1. It doesn't have a notation in the path info to tell it to create that level as a `List` instead of a `Map`, you can see an example [in this jsbin](https://jsbin.com/fayusafeja/1/edit?js,console).
2. It treats `{}` as the unset value, so when it encounters `undefined` in the path it can't resolve the path and blows up.

## Fix

I took a crack at fixing the problem:

[Pull Request branch, Tests Passing, Lint Passing](https://github.com/Reanmachine/redux-form/tree/reanmachine/immutable-array-setIn) *(See below for why it's not a PR yet).*

I first tried by simply pre-setting all the array paths before calling `setIn`, this led to the discovery of problem no. 2. 

So the solution I ended up with relies on pre-loading the array with an empty `Map` at the index if there's parts that come afterwards. [See Source](https://github.com/Reanmachine/redux-form/blob/reanmachine/immutable-array-setIn/src/structure/immutable/setIn.js#L43-L45).

When I dogfooded the changes in my two projects I had mixed results. My production project works perfectly, the `fields.others` gets created as a `List` (array when toJS()):

![Working!](https://i.imgur.com/ehCssgE.png)

However my test project I linked in the original ticket was met with this scary error

> invariant.js:38 Uncaught Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).

Which leads me to assume I've missed something important or disrupted existing behavior that isn't covered by a unit test.

**Comment by erikras** [comment]
Published #1716 in [`v6.0.3`](https://github.com/erikras/redux-form/releases/tag/v6.0.3).
