### ISSUE TITLE
Can't get values

### ISSUE THREAD

**Issue by darkyen** [erikras/redux-form#1575]
I'm using redux form v6.0.0-rc4. I'm unable to get current values as `this.prop.values` is this a known bug? My current workaround is to use selectFormValues but its not very idiomatic.

**Comment by brotzky** [comment]
The original issues was solved something like this:

`myValue: this.state.form && this.state.form.myForm && this.state.form.myForm.values && && this.state.form.myForm.values`

This got refined to `formValueSelector()` which makes it simple to grab multiple form values into a single object. I'm not sure what you find not very idiomatic about it, but I'm sure the maintainers are always happy to hear suggestions.

This is how we do it:

```Javascript
const selector = formValueSelector('myForm');

const mapStateToProps = state => ({
  myFormValues: selector(state, 'firstName', 'lastName', 'email', 'telephone'),
});

personalForm = reduxForm({
  form: 'myForm',
})(personalForm);

export default connect(mapStateToProps)(personalForm);
```

**Comment by erikras** [comment]
What @brotzky said. 👍

**Comment by darkyen** [comment]
```
const mapStateToProps = state => ({
  myFormValues: selector(state, 'firstName', 'lastName', 'email', 'telephone'),
  // ^^^ values become available as this.props.myFormValues
});
```

Thats how I'm doing it so far, didn't think it was a good way of doing it (multiple forms!).

**Comment by sungwoncho** [comment]
@brotzky The doc says that `values` is an instance API available to a decorated form component (http://redux-form.com/6.0.5/docs/api/ReduxForm.md/).

I thought I would be able to use `this.props.values` to retrieve the current values of the form. I feel that the doc is misleading. What am I not missing, and should we improve the doc?

**Comment by brotzky** [comment]
Hmm, interesting. It's not being added in any of my cases. I think it could be an error with the documentation.
