### ISSUE TITLE
Unable to get deep forms

### ISSUE THREAD

**Issue by arunreddy3039** [erikras/redux-form#1580]
render() {
    const { field, ...rest } = this.props 
    return <input {...field} {...rest}/>

in this code unable to find from where the ...rest has been called.!!

**Comment by clayne11** [comment]
Could you provide a bit more context? It's not clear what your form looks like or what you're trying to do.
.

**Comment by arunreddy3039** [comment]
http://redux-form.com/5.3.1/#/examples/deep?_k=kgg49l  

I'm trying to implement exact code but in PureInput.js 

 render() {
    const { field, ...rest } = this.props
    return <input {...field} {...rest}/>
  }

in this code unable to find from where the ...rest has been called.!!

**Comment by erikras** [comment]
> in this code unable to find from where the ...rest has been called.!!

I don't understand this statement. Do you understand how the [ES6 rest operator](http://exploringjs.com/es6/ch_destructuring.html#sec_rest-operator) works?

**Comment by arunreddy3039** [comment]
ERROR in ./src/client/app/components/PureInput.js
Module build failed: SyntaxError: C:/Users/Documents/web-test/src/client/app/components/PureInput.js: Unexpected token (12:19)

  10 | 
  11 |   render() {
> 12 |     const { field, ...rest } = this.props
     |                    ^
  13 |     return <input {...field} {...rest}/>
  14 |   }
  15 | }

BabelLoaderError: SyntaxError: C:/Users/Documents/web-test/src/client/app/components/PureInput.js: Unexpected token (12:19)

  10 | 
  11 |   render() {
> 12 |     const { field, ...rest } = this.props
     |                    ^
  13 |     return <input {...field} {...rest}/>
  14 |   }
  15 | }

    at transpile (C:\Users\Documents\web-test\node_modules\babel-loader\index.js:52:13)
    at Object.module.exports (C:\Users\Documents\web-test\node_modules\babel-loader\index.js:131:12)
 @ ./src/client/app/components/DynamicForms/Deepform.js 32:17-40

**Comment by erikras** [comment]
Sounds like you are missing the `es2015` preset in you `.babelrc`. I'm closing this as it is not related to this library. This is not the place to seek webpack build help.
