### ISSUE TITLE
[v6 rc.5] Docs/Behaviour mismatch with fieldRenderer

### ISSUE THREAD

**Issue by eyn** [erikras/redux-form#1582]
In the docs (in a couple of places) the listing suggests that you can do:

```
const fieldRenderer = (props) => (
  <div>
    <label>{props.title}</label>
    <div>
      <input type="text" {...props} />
      {props.touched && props.error && !props.disabled && <span className="error">{props.error}</span>}
    </div>
  </div>
  )

```
as a field renderer. When actually using this it doesn't update the form as props.input and props.meta are not expanded. This code works:

```
const fieldRenderer = (props) => (
  <div>
    <label>{props.title}</label>
    <div>
      <input type="text" {...props.input} {...props.meta} {...props} />
      {props.touched && props.error && !props.disabled && <span className="error">{props.error}</span>}
    </div>
  </div>
  )
```

Not sure what the desired API is (the former is simpler). Guess this is due to https://github.com/erikras/redux-form/blob/v6/src/ConnectedField.js#L59 and https://github.com/erikras/redux-form/blob/v6/src/ConnectedField.js#L61.

**Comment by jdreesen** [comment]
The code in the examples is indeed wrong. `{...field.input}` are the only props meant to be used in the input field itself. Thus you have to use `<input {...field.input} type="text"/>` as it's shown in the `Field` API docs.

**Comment by erikras** [comment]
> In the docs (in a couple of places) the listing suggests...

Can you point to the specific places in the docs that are wrong? From your description, I'm having trouble finding them.

**Comment by jdreesen** [comment]
Well, it seems my comment from yesterday that states that the docs are wrong was actually... wrong :confused: 

I'm not able to find any place where it's wrong either. I just had a quick look in the docs yesterday and didn't notice that the arguments are destructured in the function definition and thus could be used as `{...input}` directly.

Maybe @eyn has overlooked this too?

**Comment by erikras** [comment]
You might have been looking at an older version of the docs. I'm going to close for now. @eyn, speak up if you can find a problem again.

**Comment by eyn** [comment]
Yep - just looked again - think I was using the 6.0.0-alpha docs rather than the rc.5 ones. Sorry for wasting your time!
