### ISSUE TITLE
[v6 rc5] Changing Field props does not re-render

### ISSUE THREAD

**Issue by smirea** [erikras/redux-form#1585]
Example:

```js
@reduxForm({ name: 'myForm' })
class Foo {
    state = { highlighted: 0 }

    render () {
         return <div>
            <button onClick={() => this.setState({highlighted: Math.random()})}>Click Me!</button>
            <Field name='bar' highlighted={this.state.highlighted} component={renderField} />
         </div>
    }
}

const renderField = ({input, highlighted}) =>
    <div>{highlighted}</div>
```

Clicking on the button changes the component's (Foo) state, re-renders's Foo, passes the updated custom props (highlighted) to the `Field`, but `Field` does not re-render

In the current implementation it makes it very hard to work with custom props as they don't force a re-render and thus aren't as useful as they can be. 
A workaround is to perform these operations on the store itself, but that doesn't make sense for state that might be shared by multiple componenets

**Comment by erikras** [comment]
There is a unit test that shows that this is working. I've updated it (see commit above) to be more like your example. I wonder what is different in your scenario?

**Comment by smirea** [comment]
ok that is odd, re-trying the example and it works for me now as well :|

Thanks for the reply! I'll close this and re-open if I can reproduce it again.
