### ISSUE TITLE
Submit handler / hasErrors validation bug

### ISSUE THREAD

**Issue by willmcclellan** [erikras/redux-form#159]
I think a bug was introduced in 1ad1a71 in relation to #156  and the `hasErrors` function here https://github.com/erikras/redux-form/blob/1ad1a71b1e0a9da6c218b28a52f3700960cce73f/src/createReduxForm.js#L27

My submitHandler was not triggering at all, so after tracing the code to find where it stopped I ended up here: https://github.com/erikras/redux-form/blob/1ad1a71b1e0a9da6c218b28a52f3700960cce73f/src/createReduxForm.js#L246

For me `syncErrors` is an empty object `{}` which suggests no errors, but the `hasErrors` function returns true for it, where I assume it should return false?

Reverting to 2.4.2 fixes the issue

**Comment by erikras** [comment]
Fix released in v2.4.5.
