### ISSUE TITLE
[v6] FieldArray not re-rendering after add/remove

### ISSUE THREAD

**Issue by cobells** [erikras/redux-form#1592]
The recent commit to fix the FieldArray re-rendering bug (b4fc32dade0c011c79487e0fb0f0c8775e5f6059) had the side effect that the FieldArray doesn't re-render after adding/removing fields

**Comment by erikras** [comment]
Doh! 😳

**Comment by erikras** [comment]
Fixed by #1594.

**Comment by erikras** [comment]
Double thanks for testing my changes on the unreleased bleeding edge. 👍 🍻

**Comment by erikras** [comment]
Published in [`v6.0.1`](https://github.com/erikras/redux-form/releases/tag/v6.0.1).
