### ISSUE TITLE
[rc-5] Fields is not working in IE (10)

### ISSUE THREAD

**Issue by jervi** [erikras/redux-form#1595]
It seems like the new `Fields` component is not working in IE.
The console displays the following not very helpful error:
> Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `AppContainer`.

> SCRIPT5022: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `AppContainer`.

It does not happen in other browsers, and the error goes away if I remove the Fields component.

**Comment by erikras** [comment]
Ugh... will investigate... 🔍 😡

![3fc png 2016-08-23 11-53-09](https://cloud.githubusercontent.com/assets/4396759/17887768/3772dd22-6928-11e6-9a2e-80ac46556996.jpg)

**Comment by jervi** [comment]
Sorry, I checked again, and it seems like it is only IE 10 that has this problem. It works in IE 11. I don't know which browsers you support, but leaving IE 10 behind might not be a very controversial decision. That being said, everything else in Redux Form v6 seems to work in IE 10, so it _might_ be worth fixing anyways.

**Comment by KaboomFox** [comment]
I think this is related to this: https://github.com/babel/babel/pull/3527 i'll test it out tomorrow. If it is the case then the fix is just upgrading babel to 6.14

**Comment by alexanbj** [comment]
@KaboomFox You are probably right. We struggled to get the application I'm currently working on running in IE10, but upgrading to Babel 6.14 fixed that!
