### ISSUE TITLE
[Question][v6] Recipe for throwing SubmissionError from an Action Creator.

### ISSUE THREAD

**Issue by malreynolds** [erikras/redux-form#1597]
Hi.

I want to do Submit Validation on a form, as well as perform some custom redux actions. 

Say I have an onSubmit as an action creator, such as this one: 

```javascript
export function login({ email, password }) {
    return function (dispatch) {
        // Make API call here
        fetch('/rest-auth/login/',{
            method: 'POST',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                email: email,
                password: password,
            })
        }).then(response => {
            if (response.status == 200)
                return response.json().then(data => {
                    dispatch({type: AUTH_USER});
                    localStorage.setItem('token', response.token);
                    browserHistory.push('/navigation');
                })
            else return response.json().then(errors => {
                throw new SubmissionError({ ...errors, _error: 'Login failed!' });
            })
        })
    }
}
```

I quickly realized that my SubmissionError won't get picked up by onSubmit, because it's executed as a thunk, so I instead get an Uncaught SubmissionError inside the promise. 

Is there a proposed recipe as to what the best way to achieve this is, for example dispatch some redux-form action inside my thunk, which would have the same effect as throwing a submission error?

Thanks.

**Comment by erikras** [comment]
Perhaps you could

1. Just `return` the `SubmissionError`.
2. dispatch [`stopSubmit(form, errors)`](http://redux-form.com/6.0.0-rc.5/docs/api/ActionCreators.md/#-stopsubmit-form-string-errors-object-) manually from in your middleware. As long as your promise is rejected, it should halt the submission.

Please report back if either of these options worked.

**Comment by malreynolds** [comment]
Hi, I turned login into a utility function instead of an action creator and made use of the dispatch that is being passed to handleSubmit to solve my use case.

```javascript
export function login({ email, password, dispatch }) {
    return fetch('/rest-auth/login/',{
        method: 'POST',
        headers: {
            'Accept': 'application/json',
            'Content-Type': 'application/json'
        },
        body: JSON.stringify({
            email: email,
            password: password,
        })
    }).then(response => {
        if (response.status == 200)
            return response.json().then(data => {
                dispatch({type: AUTH_USER});
                localStorage.setItem('token', response.token);
                browserHistory.push('/navigation');
            })
        else return response.json().then(errors => {
            throw new SubmissionError({...errors, _error: 'Login failed. ' +
                                       (errors['non_field_errors'] ? errors['non_field_errors'][0] : '')})
        })
    })
}
```

Your first suggestion doesn't work, because it would be the thunk that's returning the `SubmissionError` to the middleware, not my `handleSubmit` function.

I was able to do it with `stopSubmit`, but because my `handleSubmit` function no longer returns a promise, the form would first go through a `SUBMIT_FORM_SUCCEEDED` action (which I wanted to avoid),  after which it would pickup the `stopSubmit`.
