### ISSUE TITLE
Rename action types

### ISSUE THREAD

**Issue by gaearon** [erikras/redux-form#16]
Minor thing, but I suggest `redux-form/CHANGE_FIELD`, etc, as action types. We wanted to suggest this convention to third party packages so their action names don't clash.

**Comment by erikras** [comment]
Okay, but the actual string values are prefixed with `REDUX_FORM_`. That should be good enough, no?

**Comment by erikras** [comment]
Or is it the `lib-name/ACTION` syntax for the string value your are suggesting?

**Comment by gaearon** [comment]
I'm suggesting it for the string value over the prefix form. We'll use `redux/*`, `redux-devtools/*` for "scoped" actions. Makes sense?

**Comment by erikras** [comment]
Got it! :+1:

**Comment by erikras** [comment]
I chose lower case, kebab case for the action name after the `/`. Is that okay, or should it really be uppercase?

**Comment by gaearon** [comment]
I think upper case is the convention we use pretty much everywhere, so it will look weird in devtools, etc.

**Comment by erikras** [comment]
Okay. Not big enough for version rev, but next version will have them in uppercase.
