### ISSUE TITLE
[v6] formValueSelector and immutablejs

### ISSUE THREAD

**Issue by ntucker** [erikras/redux-form#1602]
This doesn't appear to work when using immutablejs. I'm just getting nothing returned

**Comment by erikras** [comment]
There are pretty extensive unit tests for `formValueSelector` with immutablejs that are passing.

Can you share some code?

**Comment by ntucker** [comment]
hackedSelector is my replacement for formValueSelector that works

```javascript
import { formValueSelector } from 'redux-form'

function hackedSelector(form) {
  return (state, field) => state.getIn(['form', form, 'values', field])
}
const orderSelector = hackedSelector('discovery/order')

@connect(
  (state) => ({
    quantity: orderSelector(state, 'quantity'),
    price: orderSelector(state, 'price'),
  })
)
```

```javascript
import { Field, reduxForm, SubmissionError } from 'redux-form/immutable'
reduxForm({ form: 'discovery/order', validate: validateOrder })(Order)
```

Is `import { formValueSelector } from 'redux-form'` supposed to import from redux-form/immutable as well?

**Comment by ntucker** [comment]
Confirmed this was due to import path.

```
import { formValueSelector } from 'redux-form/immutable'
```

fixes it.

Maybe this is really a documentation issue. Maybe just a note in the immutable section about how you should import EVERYTHING not just stuff in the examples there.
