### ISSUE TITLE
Call form.submit() from within my component decoratored by @reduxForm

### ISSUE THREAD

**Issue by miracle2k** [erikras/redux-form#1604]
I don't know why I keep running into these edge cases, but another issue I have is that I need to  `submit()` the form from inside the `@reduxForm` component, but without using a submit button element.

Unless I am missing something, the only two ways to submit the form, currently, are:
- `this.refs.form.submit()` from the parent component, the one that owns the `@reduxForm`'ed component. But below `@reduxForm` I don't have the ref.
- Using a submit button. I need to call submit in JavaScript.

My workaround right now is this:

`this.props.form.handleSubmit(new Event(1))`

This calls the validation & submit, because using the fake argument we make `handleSubmit` think it's really from the form. I wonder if calling `handleSubmit` without any argument could be a third supported mode.

**Comment by gustavohenke** [comment]
See [Remote Submit](http://redux-form.com/6.5.0/examples/remoteSubmit/)
