### ISSUE TITLE
[v6-rc5] Getting initialValues inside form

### ISSUE THREAD

**Issue by glibin** [erikras/redux-form#1607]
In rc.3 I can get initialValues inside form: 

```
<MyForm initialValues={model} ...>
```

and 

```
const MyForm = (props) => {
    const { initialValues } = props;
}
```

After updating to rc.5 `initialValues` are not in props anymore.

Also does not work with `connect`:

```
const MyForm = connect(
    state => ({ 
        staff: state.model, // <-- will be in props.staff
        initialValues: state.model // <-- will not be in props
    })
)(MyFormRedux);
```

Is that expected behavior in rc.5?

**Comment by jdreesen** [comment]
Should be fixed by #1598 and in the next release.

**Comment by itaylorweb** [comment]
Im having a similar issue with initialValues.

`const mapStateToProps = (state) => {
  const selectedCustomer = selector(state, 'customer');

  return {
    updateQuote: state.updateQuote,
    customerList: state.customerList,
    productList: state.productList,
    initialValues: state.updateQuote.quote,
    selectedCustomer: selectedCustomer ? _.find(state.customerList.customers, { _id: selectedCustomer }) : state.updateQuote.customer
  }
};
`

The form loads with no values so I am having to force it by calling: this.props.initialize(); in componentWillMount

**Comment by erikras** [comment]
See @jdreesen's comment.
