### ISSUE TITLE
[v6rc5] Error when using normalize on immutable form field

### ISSUE THREAD

**Issue by bghveding** [erikras/redux-form#1608]
Hi,

I'm using redux-form with immutablejs (redux-form/immutable).

When adding a normalize function to a field, I get an error everytime a change is triggered on that field (e.g. adding some text to a text input). The error is `Uncaught TypeError: state.setIn is not a function`

I've tested this with a simple field like this:

```
<Field 
  name="firstName" 
  component="input" type="text" 
  normalize={(val) => val} 
/>
```

![2016-08-24 12_30_05-greenshot](https://cloud.githubusercontent.com/assets/2187766/17927607/bc7d3908-69f6-11e6-8340-eed0fc9c1e89.png)

Has anyone else experienced this? Other than this, the form works as expected.

**Comment by erikras** [comment]
My guess it that you are not _also_ importing the form reducer from `redux-form/immutable`.

Either that or that you are not using a library like `redux-immutablejs`.

https://github.com/erikras/redux-form/blob/v6/examples/immutable/src/index.js#L6-L7

**Comment by bghveding** [comment]
Thanks @erikras, that was it :)

Feel kind of stupid now :P

**Comment by DanielMSchmidt** [comment]
Updated Link for other people like me: https://github.com/erikras/redux-form/blob/v6.0.5/examples/immutable/src/index.js#L6-L7
