### ISSUE TITLE
Potential issue with asynchronous validation

### ISSUE THREAD

**Issue by skeary-immt** [erikras/redux-form#161]
Hi Erik,

Thanks for a great library. Using v2.4.4 of the library we also came across the problem outlined in https://github.com/erikras/redux-form/issues/159. Moving to v2.4.5 seems to address that problem but we're still having an issue with a form that was previously working.

The new issue appears to be related to the asynchronous validation the form uses as it (now) passes the synchronous validation. Looking through the redux-form code I think there may be an issue with the changes made in v2.4.2 (commit  1ad1a71). The code that seems to be the problem is in src/createReduxForm.js:

```
const handleErrors = asyncErrors => {
             dispatch(actions.stopAsyncValidation(asyncErrors));
-            return isAsyncValid(asyncErrors);
+            return hasErrors(asyncErrors);
           };
```

Before this routine used to return *true* if the form was valid and *false* if not. Now it seems to return *false* if the form is valid and *true* if not. It doesn't look like the calling code has changed to reflect this.

if you like I can submit a PR. I haven't yet because I'm not sure if I'm missing something. Let me know if you want me to.

Cheers,
Simon

**Comment by erikras** [comment]
[Upgrade to v3](https://github.com/erikras/redux-form/releases/tag/v3.0.0).
