### ISSUE TITLE
[v6] Fields component custom props documentation bug or code bug?

### ISSUE THREAD

**Issue by rmarscher** [erikras/redux-form#1612]
Checking out the new Fields component. The [docs](http://redux-form.com/6.0.0-rc.5/docs/api/Fields.md/#props) show that custom props will be passed in alongside the fields, but actually they are passed within the field properties. Apologies if this was already reported, but I didn't find it in my search of the issues here.

Relevant code is here - [ConnectedFields.js line 45](https://github.com/erikras/redux-form/blob/v6/src/ConnectedFields.js#L45). It adds the `rest` containing the custom props.

It looks like a quick fix could be to include `...rest` after `...custom` in the createElement call on [line 65](https://github.com/erikras/redux-form/blob/v6/src/ConnectedFields.js#L65).

Or potentially drop [line 51](https://github.com/erikras/redux-form/blob/v6/src/ConnectedFields.js#L51 ) to remove the properties from being duplicated within each field.

Or update the documentation to show the additional props exist within each field. Personal preference is for the properties to be passed as shown in the docs.

Thanks! I have a "wizard" style form where some of the pages have fields that appear after the previous fields have been filled out. It seems the Fields component should localize the amount of this form that needs to re-render.

**Comment by jdreesen** [comment]
> Apologies if this was already reported, but I didn't find it in my search of the issues here.

I reported it here #1583 and it should already be fixed here #1589 and will thus be available in the next release.

**Comment by rmarscher** [comment]
Ah. I should have tested against the head of the v6 branch. Sorry and thanks!!
