### ISSUE TITLE
Autosaving form race conditions with form collections

### ISSUE THREAD

**Issue by akiellor** [erikras/redux-form#1615]
**Context**
- redux-form version: 5.3.2
- form which triggers `handleSubmit()` in the following scenarios:
  - on blur of any field
  - on addition to a collection
  - on removal of an element in a collection
- form has overwriteOnInitialValuesChange: false
- form has a collection named 'foo'

**Scenario**
1. User types into 'foo[0].value'
2. Blur fires from 'foo[0].value' and triggers submit
3. User presses 'add new foo'
4. New foo is added to screen
5. Submit resolves with new api result with foo collection with 1 value
6. Initial values changes 
7. New foo from step 4 is removed from the screen

Given that overwriteOnInitialValues is set to false, I would expect that any change to the initialValues should have no impact on the rendering.

I'm working on a PR with a test to try reproduce this issue and would love some feedback on either my use case or potential implementation hints.

**Comment by Sir4ur0n** [comment]
Have you tried using redux-form 6.0.1?
