### ISSUE TITLE
Selector getFormValues always return 'undefined'

### ISSUE THREAD

**Issue by stunaz** [erikras/redux-form#1617]
I am trying to use the selector `getFormValues ` from [http://redux-form.com/6.0.0-rc.4/docs/api/Selectors.md/](http://redux-form.com/6.0.0-rc.4/docs/api/Selectors.md/) but I am always getting `undefined`, If i try to get the values from the store using `state.form.myForm.values`, than it is working.

**Comment by clayne11** [comment]
How are you calling it? The docs look like they're wrong.

It should be `(state) => getFormValues('myForm')(state)` based on the description below the example.

**Comment by erikras** [comment]
@clayne11 is correct. Share code.

**Comment by stunaz** [comment]
my code was exactly like the one in the example.
Thanks @clayne11 , I was misleading by the documentation

so instead of calling it like 
`values: getFormValues('myForm')`

I should have call it like:

`values: getFormValues('myForm')(state)`

**Comment by erikras** [comment]
Could you point out exactly where the docs are misleading, because I looked, briefly, and did not see it.

**Comment by stunaz** [comment]
sure, here
http://redux-form.com/6.0.1/docs/api/Selectors.md/ in the example
```
MyComponent = connect(
  state => ({
    values: getFormValues('myForm'),
    dirty: isDirty('myForm'),
    pristine: isPristine('myForm'),
    valid: isValid('myForm'),
    invalid: isInvalid('myForm')
  })
)(MyComponent)
```

**Comment by erikras** [comment]
🙈 Thanks for that. 👍
