### ISSUE TITLE
[question] Wizard form and initialValues

### ISSUE THREAD

**Issue by stunaz** [erikras/redux-form#1618]
How to initialize a wizard form ?
When I set the values on firstPage using `initialValues`, it is fine. the values are there, I can navigate to the second page, and it is also fine, but as soon as I go back to the first page the values are initialized **again**. Is there a way to check if the form is already initialized and therefore prevent initialization?

**Comment by babsonmatt** [comment]
Are you using destroyOnUnmount: false?

**Comment by stunaz** [comment]
yes

**Comment by stunaz** [comment]
I guess I could use `keepDirtyOnReinitialize`, not just if it is for the right purpose

**Comment by stunaz** [comment]
Actually it makes sense. I had to initiate my form on the smart component. Taking doc example [http://redux-form.com/6.0.1/examples/wizard/](http://redux-form.com/6.0.1/examples/wizard/), i have to initialize & declare my form in the wizardForm.js and not in the first page

**Comment by brethubbard** [comment]
@stunaz I am running into this same issue. Do you have a working example of what you mean by 

>  i have to initialize & declare my form in the wizardForm.js and not in the first page

**Comment by brethubbard** [comment]
@stunaz Nevermind, I understand what you mean now. Thank you for this!

**Comment by Snowbell92** [comment]
@brethubbard would you please to explain it to this newbie? I have to set and submit with an `initialValue`, in case the field comes empty from the user (it's a location component and there's no guarantee of having https, so I can't make it a mandatory field). Thanks.

**Comment by brethubbard** [comment]
Yeah, if you look at the example http://redux-form.com/6.0.1/examples/wizard/ you would initialize the form in `WizardForm` using the `initialValue` prop rather than on the `WizardFormFirstPage.js` because `WizardForm` is initialized only once whereas the 'WizardFormFirstPage` is initialized every time you visit that page of the form. Does that make more sense?

**Comment by Snowbell92** [comment]
what I don't understand is, do I have to connect or not?

**Comment by brethubbard** [comment]
I believe you only have to connect it if you want to initialize it from values inside the store. Otherwise you can just pass the default values as a prop in `initialValues`.

**Comment by Snowbell92** [comment]
thank you! That helped a lot!
