### ISSUE TITLE
Make it easier to browse old documentation

### ISSUE THREAD

**Issue by ryanlewis** [erikras/redux-form#1621]
Congrats on the v6 release!

Unfortunately for us, at the moment we will continue to use v5, and finding v5 documentation is now harder, as http://redux-form.com/ redirects to http://redux-form.com/6.0.1. http://www.redux-form.com/5.3.1/ still works however.

**Comment by erikras** [comment]
I'm open to suggestions. There is a link to [this page](http://redux-form.com/6.0.1/docs/DocumentationVersions.md/) at the bottom of the left nav.

**Comment by ryanlewis** [comment]
Whoops, didn't see that. That's enough for me.

Might be worth linking to that page on the main splash page, maybe underneath the 4 main CTAs?

**Comment by ryanlewis** [comment]
Ah, still an issue.

If for example I am on http://redux-form.com/5.3.1/#/?_k=4zxszn , clicking Examples redirects me to the examples page for version 6.0.1.

**Comment by erikras** [comment]
Yeah, that's a problem with the way the docs were before they all got their own directory. I'll fix a few of the latest versions, but not all of them.

**Comment by erikras** [comment]
There, those readme links are fixed.
