### ISSUE TITLE
[DOCS] - All css for example pages are broken

### ISSUE THREAD

**Issue by stunaz** [erikras/redux-form#1623]
The examples pages are trying to load [http://redux-form.com/6.0.0/bundle.css](http://redux-form.com/6.0.0/bundle.css) which doesn't exist.

I guess it should have been [http://redux-form.com/6.0.1/bundle.css](http://redux-form.com/6.0.1/bundle.css)

**Comment by wesleysmyth** [comment]
<img width="1282" alt="screen shot 2016-08-25 at 4 13 21 pm" src="https://cloud.githubusercontent.com/assets/6476956/17984408/f9089a32-6ade-11e6-925b-c147d4e70820.png">

**Comment by myrubapa** [comment]
And opening left sites

**Comment by erikras** [comment]
Just discovered this myself. Thanks. :facepalm:

**Comment by jdreesen** [comment]
The example pages are displayed correctly now but all links in the menu suddenly change to `v6.0.0` (which doesn't exist) when visiting an example page :/
