### ISSUE TITLE
Provide list of registered fields to validate() function

### ISSUE THREAD

**Issue by andrepcg** [erikras/redux-form#1624]
Using redux-form v6.0.1

I have a huge form with lots of fields and those fields need to be validated to check if all of them are filled.

Validation:

```
function validateValue(value) {
  return value ? null : 'required';
}

export default function validate(values) {
  const errors = {};
  Object.keys(values).map((id) => {
    errors[id] = validateValue(values[id]);
  });

  return errors;
}
```

This validation iterates over all the values in the form and marks it `required` or `null`. The problem arises when the fields are not initialized (via `initialValues` or `initialize(values)`) and the variable `values` in the validate function does not contain any field and no field is marked as `required`.

In order to solve this I have to create an object with all the fields names as keys and `null` as value and pass it to `initialValues`. Imagine I have a form with hundreds of fields (like a questionnaire).

Is it supposed to work like this or I've got a bug somewhere in my code? Or should the form state be initialized with each field and an empty value (when the field is registered)?

**Comment by fchienvuhoang** [comment]
I have a problem with initialValues on v6 two, i was downgrade to v5

**Comment by erikras** [comment]
`redux-form` makes no guarantees that there will be a key-value pair in the `values` object for every field in your form. Did `v5` really give you `{ field1: undefined, field2: undefined }` to validate? You will need to maintain an array of fields to `map()` over instead of `Object.keys(values)`.

**Comment by erikras** [comment]
Although... the thing calling `validate()` does have a list of all the registered fields, so perhaps that could be passed to the validation function....

**Comment by andrepcg** [comment]
I think that would be useful in some cases, this one for example. I have a huge list of fields and don't want to manually maintain them but I still want to validate each one of them

**Comment by jakoandersen** [comment]
Any news on this?

**Comment by gustavohenke** [comment]
@jakoandersen you can use [`getFormMeta` selector](https://redux-form.com/7.2.1/docs/api/selectors.md/#-code-getformmeta-formname-string-code-returns-code-state-gt-formmeta-object-code-).

It returns an object in the shape of `{ fieldName: { visited, touched } }` -- I doubt we'll be adding any more than that.

Will close the issue for now as it's been a while since its last comment.

**Comment by jakoandersen** [comment]
Thanks, appreciate it. Will use that!

**Comment by harrygreen** [comment]
Maybe I'm doing something unintended... but I found `registeredFields` in the second param object to the `validate` function.

I'm using it like this:

```js
export const validate = (values, {registeredFields}) => {
  let errors = {}
  if (!registeredFields) return errors // `validate` is called on mount, when `registeredFields` is empty

  Object.keys(registeredFields).map(registeredField => {
    const value = values[registeredField]
    switch (registeredField) {
      case 'name':
        if (!value || value.trim() === '') {
          errors[registeredField] = 'required'
        }
      // validation rules for each field

  return errors
})
```

**Comment by yasserhussain1110** [comment]
I am trying what harryGreen suggested. I don't get the registered field.
