### ISSUE TITLE
version which compatible with node v0.12.4

### ISSUE THREAD

**Issue by yinglinchen-minted** [erikras/redux-form#1625]
Hi, 
I am trying to find an older redux-form version which is compatible with node v0.12.4. How can find it? 

Thanks

**Comment by erikras** [comment]
I'm not sure. But I can provide you a list of all the versions available on npm to sift through. I'm not sure how useful the old ones will be unless you are also using old versions of React, Redux, etc.

`6.0.1, 6.0.0-rc.5, 6.0.0-rc.4, 6.0.0-rc.3, 6.0.0-rc.2, 6.0.0-rc.1, 6.0.0-alpha.15, 6.0.0-alpha.14, 6.0.0-alpha.13, 6.0.0-alpha.12, 6.0.0-alpha.11, 6.0.0-alpha.10, 6.0.0-alpha.9, 6.0.0-alpha.8, 6.0.0-alpha.7, 6.0.0-alpha.6, 6.0.0-alpha.5, 6.0.0-alpha.4, 6.0.0-alpha.3, 6.0.0-alpha.2, 6.0.0-alpha.1, 5.3.3, 5.3.2, 5.3.1, 5.3.0, 5.2.5, 5.2.4, 5.2.3, 5.2.2, 5.2.1, 5.2.0, 5.1.4, 5.1.3, 5.1.2, 5.1.1, 5.1.0, 5.0.1, 5.0.0, 4.2.2, 4.2.1, 4.2.0, 4.1.16, 4.1.15, 4.1.14, 4.1.13, 4.1.12, 4.1.11, 4.1.10, 4.1.9, 4.1.8, 4.1.7, 4.1.6, 4.1.5, 4.1.4, 4.1.3, 4.1.2, 4.1.1, 4.1.0, 4.0.7, 4.0.6, 4.0.5, 4.0.4, 4.0.3, 4.0.2, 4.0.1, 4.0.0, 3.1.7, 3.1.6, 3.1.5, 3.1.4, 3.1.3, 3.1.2, 3.1.1, 3.1.0, 3.0.12, 3.0.11, 3.0.10, 3.0.9, 3.0.8, 3.0.7, 3.0.6, 3.0.5, 3.0.4, 3.0.3, 3.0.2, 3.0.1, 3.0.0, 3.0.0-beta-4, 3.0.0-beta-3, 3.0.0-beta-2, 3.0.0-beta-1, 2.4.5, 2.4.4, 2.4.3, 2.4.2, 2.4.1, 2.4.0, 2.3.1, 2.3.0, 2.2.8, 2.2.7, 2.2.6, 2.2.5, 2.2.4, 2.2.3, 2.2.1, 2.2.0, 2.1.0, 2.0.1, 2.0.0, 1.7.0, 1.6.8, 1.6.7, 1.6.6, 1.6.5, 1.6.4, 1.6.3, 1.6.2, 1.6.1, 1.6.0, 1.5.3, 1.5.2, 1.5.1, 1.5.0, 1.4.1, 1.4.0, 1.3.4, 1.3.3, 1.3.2, 1.3.1, 1.3.0, 1.2.1, 1.2.0, 1.1.0, 1.0.1, 1.0.0, 0.6.1, 0.6.0, 0.5.0, 0.4.1, 0.4.0, 0.3.0, 0.2.5, 0.2.4, 0.2.3, 0.2.2, 0.2.1, 0.2.0, 0.1.3, 0.1.2, 0.1.1, 0.1.0, 0.0.9, 0.0.8, 0.0.7, 0.0.5, 0.0.4, 0.0.3, 0.0.2, 0.0.1`
