### ISSUE TITLE
[v6] Pass props to handleSubmit

### ISSUE THREAD

**Issue by olistic** [erikras/redux-form#1629]
Hi! Would you consider passing `props` as a third argument to the `handleSubmit` function? This was implemented in the last `v5` release (#1548 #1546). If so, I'm happy to create a PR, just let me know.

**Comment by erikras** [comment]
Sure, go ahead.

**Comment by prescottprue** [comment]
+1 For this

**Comment by olistic** [comment]
Perfect, will send the PR during the weekend.

**Comment by erikras** [comment]
Published in [`v6.0.2`](https://github.com/erikras/redux-form/releases/tag/v6.0.2).

**Comment by gkatsanos** [comment]
@erikras @baronswindle is this documented somewhere?

**Comment by devhyunjae** [comment]
@erikras agree with @gkatsanos. Had to spend hours to find that handleSubmit passes props. Need some updates on the doc!

**Comment by ntomallen** [comment]
Likewise. Spent several hours trying to figure out how to properly handle submit with an extra parameter, and I still can't find documentation on how to do it.

**Comment by gustavohenke** [comment]
Hi @ntomallen @devhyunjae @gkatsanos,
See [`onSubmit`](https://redux-form.com/7.0.4/docs/api/reduxform.md/#-code-onsubmit-function-code-optional-) docs.  I'm not sure about what `handleSubmit(customSubmitFunction)` though.

**Comment by ntomallen** [comment]
I just figured it out! That documentation has it there, but I must have looked over it. Here's a basic example of how to use it:

```
// yourjsfilehere.js
export const submit = (values, dispatch, props) => {
  console.log(props) // Logs the props from redux-form, as well as the props available to the React component which contains the form.
}
```

And declare the form as normal
```
import { Field, reduxForm } from 'redux-form'
import React from 'react'
import { submit } from './yourjsfilehere'

const FormWithProps = ({handleSubmit, id}) => {
    return (
        <form onSubmit={handleSubmit(submit)}>
            // Your form here ...
        </form>
     )
}

export default reduxForm({
  form: 'FormWithProps '
})(FormWithProps )
```

I hope this is helpful to others trying to use this.

**Comment by dhia1997** [comment]
I want to pass history prop from withRouter inside handleSubmit function, how can i do it?

**Comment by conor909** [comment]
I would also like to pass my own custom argument to my handleSubmit function
