### ISSUE TITLE
Problems mounting elsewhere using connect

### ISSUE THREAD

**Issue by JohanNordlinder** [erikras/redux-form#163]
Hello

I'm trying to follow the *Advanced Usage - Doing the connect()ing Yourself* examples from the readme but have no luck. Basically what I want to achieve is to mount the reducer under *store.kontaktuppgifter* instead of *store.form*. I hope you won't mind some Swedish :).

The problem is whatever I return from mapStateToProps() the form still mounts under *store.form.kontaktuppgifterForm* as declared in the argument to reduxForm().

```javascript
class KontaktForm extends Component {
 // code...
}

KontaktForm = reduxForm({
  form: 'kontaktuppgifterForm',
  fields: ['personnummer', 'fornamn', 'efternamn', 'epost', 'telefonMobil', 'telefonHem', 'telefonDagtid'],
  validate: kontaktValidation
})(KontaktForm);

function mapStateToProps(state) {
  console.log('store', state.kontaktuppgifter.kontaktuppgifterForm);
  return {
    form: state.kontaktuppgifter.kontaktuppgifterForm,
  };
}

function mapDispatchToProps(dispatch) {
  return {
    ...bindActionCreators(kontaktuppgifterActions, dispatch),
    dispatch  // <----- passing dispatch, too
  };
}

// apply connect() to bind it to Redux state
KontaktForm = connect(mapStateToProps, mapDispatchToProps)(KontaktForm);

// export the wrapped component
export default KontaktForm;

```
Reducers look like this
```javascript
//Others...
import kontaktuppgifter from './kontaktuppgifter';
import {reducer as form} from 'redux-form';

export default combineReducers({
  //Others...
  form,
  kontaktuppgifter
});
```

Reducer for the  kontauppgifter form
```javascript
const initialState = {
  kontaktuppgifterForm: {},
  faktureringsuppgifterForm: {},
};

export default function map(state = initialState, action = {}) {
  switch (action.type) {

  //... Other functions
}
```

What am I missing here? Thanks in advance.

**Comment by erikras** [comment]
Some things you're misunderstanding:

1. Really, the only good reason to mount it somewhere other than `form` is because you already have a reducer mounted at `form` that you cannot move. Redux is such a young technology that this really does not happen because no one has old legacy reducers in their project.
2. Wherever you mount your redux-form reducer, must be _only_ used by redux-form. It looks like you've got another reducer already mounted at `state.kontaktuppgifter` doing other things. You can't do that.
3. If you wanted to mount it somewhere other than form, you would do:

```js
//Others...
import kontaktuppgifter from './kontaktuppgifter';
import {reducer as form} from 'redux-form';

export default combineReducers({
  //Others...
  annanplats: form, // <----------
  kontaktuppgifter
});
```
and then:
```js
class KontaktForm extends Component {
 // code...
}

KontaktForm = reduxForm({
  form: 'kontaktuppgifterForm',
  fields: ['personnummer', 'fornamn', 'efternamn', 'epost', 'telefonMobil', 'telefonHem', 'telefonDagtid'],
  validate: kontaktValidation
})(KontaktForm);

function mapStateToProps(state) {
  return {
    form: state.annanplats.kontaktuppgifterForm // <---------
  };
}

function mapDispatchToProps(dispatch) {
  return {
    ...bindActionCreators(kontaktuppgifterActions, dispatch),
    dispatch
  };
}

// apply connect() to bind it to Redux state
KontaktForm = connect(mapStateToProps, mapDispatchToProps)(KontaktForm);

// export the wrapped component
export default KontaktForm;
```
Does that help?

**Comment by JohanNordlinder** [comment]
Thanks for the quick answer! So how would I organize my forms inside the store, for a big application containing 10+ number of forms one would think that keeping all of them under store.form would look cluttered.

I was basically thinking about having the store structure described below for my data, keeping related values together separate from other forms.

store{
    contactInformation{
       contactInformationForm: {},
       invoiceInformationForm: {},
       useContactInfoAsInvoiceInfo: true
    }
}

**Comment by erikras** [comment]
You're overthinking it, I think. What's the problem with having all your form data under `state.form`? You name the forms different things. If you _really_ want a hierarchical reducer structure elsewhere in your app, you could do that, but I don't see the value. If you do `componentWillUnmount() { this.props.destroyForm(); }` (which will be the default behavior in v3), it doesn't clutter up your redux state at all.

**Comment by JohanNordlinder** [comment]
You're probably right, we've just started with react and redux and are still trying to make sense of how it all fits together. One of the reasons I wanted the data in a separate hierarchical structure was to make serialization and deserialization to/from Json easier but fetching the data from *store.form.whatever* at that time shouldn't be a problem. Another reason was to make it easier to understand how the different data/forms relate to each other, which are part of the same "input group".

I'll go ahead and keep my forms under the default location and maybe give them smart names that tell which input group they belong to. Thanks for clarifying this and for your effort developing this package.
