### ISSUE TITLE
example code doesn't match

### ISSUE THREAD

**Issue by pdavidow** [erikras/redux-form#1630]
The example code for the SimpleForm shown here: 
http://redux-form.com/5.3.1/#/examples/simple?_k=sjdo1m
does not match the github code shown here:
https://github.com/erikras/redux-form/tree/master/examples/simple/src

(I haven't looked at the other examples yet)

**Comment by erikras** [comment]
That's because the examples in master are for `v6`, and you are looking at the `v5` docs.

The `v5.3.1` example code is [here](https://github.com/erikras/redux-form/tree/gh-pages/5.3.1/src/examples).

**Comment by pdavidow** [comment]
I would expect that http://redux-form.com/ should have the latest and
greatest code, and yet it looks like v6 has in fact been released.


On Fri, Aug 26, 2016, at 02:45 PM, Erik Rasmussen wrote:
> That's because the examples in master are for v6, and you are looking
> at the v5 docs.
> The v5.3.1 example code is here[1].
> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[2], or mute the thread[3].
>


Links:

  1. https://github.com/erikras/redux-form/tree/gh-pages/5.3.1/src/examples
  2. https://github.com/erikras/redux-form/issues/1630#issuecomment-242818760
