### ISSUE TITLE
v6 - initialValues not updating

### ISSUE THREAD

**Issue by thebeardednerd** [erikras/redux-form#1647]
I can't seem to get the initialValues to update properly in my form. On first entry it's fine, but on second entry, it's pulling the previous values.

`import React, { Component, PropTypes } from 'react';`
`import { Field, reduxForm, reset } from 'redux-form';`
`import { connect } from 'react-redux';`
`import { fetchWidth } from '../../actions/read';`
`import { updateWidth } from '../../actions/update';`
`import { deleteWidth } from '../../actions/delete';`
`import { Link } from 'react-router';`
`
`
`const validate = values => {`
`const errors = {}`
`if (!values.width) {`
`errors.width = 'Enter a width'`
`} else if (isNaN(Number(values.width))) {`
`errors.width = 'Must be a number with no more than 2 decimals'`
`}`
`return errors`
`}`
`
`//RENDER FIELDS`
`const renderField = ({ input, label, type, meta: { touched, error } }) => (`
`   <div className={ `form-group ${touched && error ? 'has-error' : ''}` }>`
`       <label className="control-label">{label}</label>`
`       <input {...input} type={type} className="form-control" placeholder={label} />`
`       {touched && error && <div className="help-block">{error}</div>}`
`   </div>`
`)`
`
`
`class EditWidth extends Component {`
`   static contextTypes = {`
`       router: PropTypes.object`
`   };`
`
`componentWillMount() {`
`this.props.fetchWidth(this.props.params.id);`
`}`
`
`   onDeleteClick() {`
`       this.props.deleteWidth(this.props.params.id)`
`           .then(() => {`
`               this.context.router.push('/hda/admin/widths/');`
`           });`
`   }`
`
`onSubmit(props) {`
`this.props.updateWidth(this.props.params.id, props)`
`.then(() => {`
`this.context.router.push('/hda/admin/widths/');`
`});`
`}`
`
`   render() {`
`       const { handleSubmit, pristine, submitting, reset } = this.props;`
`       console.log(this.props.initialValues);`
`       return (`
`
`<div>`
`<form onSubmit={handleSubmit(this.onSubmit.bind(this))}>`
`<div className="row">`
`<div className="col-xs-6">`
`<h3><Link to="/hda/admin/">Main Menu</Link> > <Link to="/hda/admin/widths/">Manage Widths</Link> >  Edit width</h3>`
`</div>`
`<div className="col-xs-6 text-right">`
`
`                           <button type="button" className="btn btn-danger" data-toggle="modal" data-target="#myModal">Delete</button>`
`                       </div>`
`                   </div>`
`                   <div className="row">`
`                       <div className="col-xs-12">`
`
`<Field name="width" type="text" component={renderField} label="Width" />`
`
`                           <button type="submit" className="btn btn-primary">Submit</button>`
`                           <button type="button" className="btn btn-default" disabled={pristine || submitting} onClick={reset}>Reset</button>`
`                           <Link to="/hda/admin/widths/" className="btn btn-default">Cancel</Link>`
`                       </div>`
`                   </div>`
`               </form>`
`
`<div className="modal fade" id="myModal" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">`
`<div className="modal-dialog">`
`<div className="modal-content">`
`<div className="modal-header">`
`<button type="button" className="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span className="sr-only">Close</span></button>`
`<h4 className="modal-title" id="myModalLabel">Delete</h4>`
`</div>`
`<div className="modal-body">`
`Are you sure?`
`</div>`
`<div className="modal-footer">`
`<button type="button" className="btn btn-default" data-dismiss="modal">Cancel</button>`
`<button type="button" className="btn btn-danger" onClick={this.onDeleteClick.bind(this)}>Yes, delete now</button>`
`</div>`
`</div>`
`</div>`
`</div>`
`
`           </div>`
`       );`
`   }`
`}`
`
`
`
`function mapStateToProps(state) {`
`return {`
`initialValues: state.widths.item`
`};`
`}`
`
`EditWidth = reduxForm({`
`   form: 'EditWidthForm',`
`   validate`
`})(EditWidth);`
`
`EditWidth = connect(mapStateToProps, { fetchWidth, updateWidth, deleteWidth })(EditWidth);`
``
`export default EditWidth`

My console is showing that it first loads the previous state, then the current state, but it populated the form with the previous state

`Object {id: "3", width: "72.00"}`
`Object {id: "5", width: "25.00"}`

**Comment by Sir4ur0n** [comment]
Are you using v6.0.1?
According to [the documentation](http://redux-form.com/6.0.1/docs/api/ReduxForm.md/), you must pass the prop `enableReinitialize=true` to the form for it to update beyond the first `initialValues`.

**Comment by thebeardednerd** [comment]
WOW! Thank you so much. I wish i knew 3 days ago it was that simple. This fixed my issue.

**Comment by mynnx** [comment]
I'm not entirely clear on how this example works though; it seems like it's using `initialValues`

**Comment by mynnx** [comment]
I'm not entirely clear on how this example works though; it seems like it's using `initialValues` to populate the state with empty values, and then the `loadData()` action updates the state.  Without `enableReinitialize`, how does redux-form pick up new values from state?

http://redux-form.com/6.0.1/examples/initializeFromState/

It looks like `INITIALIZE` isn't being fired until after the `loadData` completes, but in my experience `INITIALIZE` happens as soon as the wrapped component is first rendered.  Can anyone explain?

**Comment by Sir4ur0n** [comment]
@mynnx In my experience - but I might be totally wrong, it's just some behavior I had already noticed in my code - initialization using `initialValues` doesn't trigger if `initialValues` is undefined/empty (which in a way makes sense because this would be useless). So the first time `initialValues` contains actual values, it triggers form initialization.

**Comment by gustavohenke** [comment]
As the initial issue was solved, will close here. 
Feel free to open a new issue for further clarifications.
