### ISSUE TITLE
Validation Warnings

### ISSUE THREAD

**Issue by ilxanlar** [erikras/redux-form#1649]
Could redux-form support fields **validation warnings**?

```
@reduxForm(
  {
    form: 'formName',
    fields: ['fieldOne', 'fieldTwo', ...],
    validate: validator,
    validateWarnings: warningValidator // Warnings
  }
)
```

Validation errors disable form submission until form has no error, but validation warnings simply warn users but still allow us to submit our form. So, we can have `warning` along with `error` in every field.

I was dealing with big and hard-to-fill forms, then I felt the need for warnings. I was wondering... does it worth discussing?

**Comment by btroop** [comment]
i was wondering about this, too. great for passwords that are too short, weak, etc.

**Comment by timhwang21** [comment]
I would be interested in this, as well. My form involves budgets, and I'd like to warn users who input values that are valid, but questionable (e.g. value over daily allowed budget). Thanks!

**Comment by timhwang21** [comment]
If anyone else has this use case, I spent some time today working on this feature. Test coverage isn't 100% yet, but I'll be working on that more later.

[Link to the diff of my fork](https://github.com/erikras/redux-form/compare/master...timhwang21:master)

We are using this internally to provide two levels of severity for warnings. @erikras , would this possibly be something that would have merit as a feature? 

(I'm entirely new to open source, so please forgive any faux pas being committed!)

**Comment by erikras** [comment]
Added warnings in [`v6.1.0`](https://github.com/erikras/redux-form/releases/tag/v6.1.0).
