### ISSUE TITLE
Possible to trigger validation externally?

### ISSUE THREAD

**Issue by damassi** [erikras/redux-form#165]
In leu of the nested form possibility discussed in the other thread, I've taken a pretty massive form and broken up into a series of nested sub forms. Is it possible to call a validation method externally from the component form? Looking in the actionCreators it doesn't seem like this is possible and I can't quite figure out how to elegantly address this issue.

**Comment by erikras** [comment]
You _could_ dispatch the necessary actions yourself a `touch('formName', ...fields)` (that would show any sync errors) and then a `startAsyncValidation('formName')` (optional, only if you're showing an indicator) and `stopAsyncValidation('formName', errors)` to set the errors in the forms.

**Comment by damassi** [comment]
Is it possible to validate by just passing in the form name?

**Comment by erikras** [comment]
Are you talking about sync or async?

**Comment by damassi** [comment]
Sync for now

**Comment by damassi** [comment]
But if I have to rewrite the sync form to behave asyncronously I can do
that too, though this seems like a useful ask.

**Comment by erikras** [comment]
You may now submit your form (which will trigger validation) from outside your decorated component. [`v4.2.0`](https://github.com/erikras/redux-form/releases/tag/v4.2.0)

**Comment by damassi** [comment]
Awesome, again really excellent work :+1:

**Comment by geminiyellow** [comment]
@erikras 

could i trigger async validation externally ?

my code looks like this:

```
<Form 
  onChange={ (values, dispatch, { asyncValidate }) => asyncValidate(values, dispatch) }
/>
```

the `asyncValidate` is working, but the error cannot be caught by form.

it shown: `Uncaught (in promise)`
