### ISSUE TITLE
Custom component with multiple fields in multiple forms

### ISSUE THREAD

**Issue by bobmonteverde** [erikras/redux-form#1653]
I'm in the middle of transitioning a form I made manually into a redux-form (my form is literally the combination of all the examples... 5 step wizard, custom fields, using material-ui (w/ redux-form-material-ui), got a FieldArray... and ideally will also be utilizing immutable). 

I have a custom Code input, then I have a component that includes 3 of these Code inputs (one for js, one for html, one for css) and this component is used twice in 1 form, and once in another (so far, will probably be using this elsewhere as well).   I can't seem to figure out the cleanest way to implement this..... Ideally I'd like to be able to pass the "form" key that's set in y reduxForm decorator (so that any given complete "form" will belong to the same object in my state), as well as a prefix (so my input names will be `${prefix}.js`, `${prefix}.css`, and `${prefix}.html`)... that way the form that has 2 won't have a naming collision.

While every other part of my form was literally covered clearly in the examples section (kicking myself in the ass for not using redux-form in the first place)... I'm sure this is a common enough issue that people have a good way to solve it... I just haven't found an answer I liked yet.   The closest I ca think of is having the component have it's own unique form key, and simply providing a unique prefix for every use of the form...... if that's what I have to do, I'll do it... but would definitely prefer if each "form" I have was under the same key

**Comment by bobmonteverde** [comment]
I'm thinking this *may* be the use case for the "Fields" component...

**Comment by Sir4ur0n** [comment]
Not the easiest scenario to understand from this description :D If I understand well, you have an input component (let's call it CustomInputField) and you want to reuse it across multiple forms, and even multiple times across the same form.

Is that your use case? If not, please provide a minimalist example of what you're trying to achieve.

If that's your use case, then use a Field inside your CustomComponent, and pass a `name` prop to your CustomInputField.

**Comment by bobmonteverde** [comment]
OK, so I think I got this working with Fields (tho TBH not sure exactly why I stopped getting the decorator error, and of course forgot to commit in the middle of this coding, so don't have a poitn to go back to with the issue).  My solution is a tiny bit hacky, tho it appears to produce exactly what I had hoped for (without being too ugly).  The main gist of it is I started using Fields, and I added a prefix string, then tweaked my Fields in my component... so it looks like:

```
<Fields names={['prefix.js', 'prefix.html', 'prefix.css']}  prefix='prefix' component={MyComponent} />

const MyComponent = ({prefix, ...props} ) => (
  <div>
    <Field name={`${prefix}.js`} {...props[prefix].js} component={Code} />
    <Field name={`${prefix}.html`} {...props[prefix].html} component={Code} />
    <Field name={`${prefix}.css`} {...props[prefix].css} component={Code} />
  </div>
)
```

Of course there is the issue of not being able to validate the props since you don't know the prefix ahead of time... but with that exception, this appears to do exactly what I need (even producing the data structure exactly as I wanted).  Also, I believe Fields is not recommended since all of the Fields redraw when any are changed... I haven't investigated that much yet, but since these are Code editors, and heavier weight than simple text fields, I am slightly concerned.

Anyway, still wondering if anyone has a better solution for this.

**Comment by bobmonteverde** [comment]
@Sir4ur0n you are close to correct, just my my custom component contains 3 Fields (which happen to be custom components themselves, tho I don't think that matters here).   My original code was thorwing an error since the custom component that has the 3 Fields was not connected/decorated by reduxForm (since it was used in different forms, and at least, as it was defined without wrapping it in an additional function, I was not able to pass a custom 'form' key to the reduxForm decorator.

**Comment by Sir4ur0n** [comment]
I'm a bit confused. Why do you need `Fields`? What is wrong with just using directly
```javascript
const MyComponent = ({prefix, ...props} ) => (
  <div>
    <Field name={`${prefix}.js`} {...props[prefix].js} component={Code} />
    <Field name={`${prefix}.html`} {...props[prefix].html} component={Code} />
    <Field name={`${prefix}.css`} {...props[prefix].css} component={Code} />
  </div>
)
```
Then you can reuse `MyComponent` in any form and this will work perfectly. You shouldn't get any error.

**Comment by bobmonteverde** [comment]
I was getting an error because the component I was doing that in originally is not connected via the reduxForm decorator.... but as I said, I forgot to commit in that messed up state, so it may have been due to some other code.... I'll see if I can reproduce my original problem, and post that just to clarify.

**Comment by danielrob** [comment]
If new information comes to light that suggests this is an issue with redux-form, please advise!
