### ISSUE TITLE
Autocomplete Attribute (redux-form version 6.0.1)

### ISSUE THREAD

**Issue by labzar** [erikras/redux-form#1657]
Hello Erikras

I have some issues in redux-form version 6.0.1, the autocomplete in fields doesn't work, i can't have my previous submitted infos (my history of subbmited infos).

I have tried many solutions for example added the attribut "autoComplete" to fields but it doesn't work :(

I have noticed this bug in redux-form version 6.0.1, because it didn't exist in the version 5.3.1, so i wanna work with the latest version because it's better than 5.3.1 and includes many new features that i wanna explore in my apps.

Thank you in advance.
Have a great day :)

**Comment by bradwestfall** [comment]
Also having this issue

**Comment by gustavohenke** [comment]
Using latest versions I was not able to reproduce this issue.
Even so that I almost always set `autoComplete="off"` in my fields, because I don't want these previous values.

So please try a newer version, and if it still doesn't work, open a new issue with a reproducible example.

**Comment by kellyjoyner** [comment]
I am also experiencing this issue. I have tried setting autoComplete="off" at the form and input/formField levels with no success. I also followed someone else's advice and created 'hidden' input fields above my username and password field but had no success with that either. Has anyone found a solution?

**Comment by pacozaa** [comment]
@kellyjoyner I am here looking for the same thing.

**Comment by philmcp** [comment]
Make sure you capitalise "complete" i.e. autoComplete. Worked for me:

`<input autoComplete="off" {...input} type={type} placeholder={placeholder} className={className} />`
