### ISSUE TITLE
redux-form docs for getFormValues selector is misleading

### ISSUE THREAD

**Issue by timhwang21** [erikras/redux-form#1658]
On [this page](http://redux-form.com/6.0.1/docs/api/Selectors.md/) in the docs, an example for using `redux-form` selectors is given here:

``` javascript
MyComponent = connect(
  state => ({
    values: getFormValues('myForm')(state),
    dirty: isDirty('myForm')(state),
    pristine: isPristine('myForm')(state),
    valid: isValid('myForm')(state),
    invalid: isInvalid('myForm')(state)
  })
)(MyComponent)
```

However, it seems like a prop named `values` is not accessible from within the form. I suspected this may be a similar issue as fixed in #1598, but [the prop is there](https://github.com/erikras/redux-form/blob/master/src/reduxForm.js#L343).

Code example:

``` javascript
const mapStateToProps = (state, props) => {
    // ...some irrelevant logic
    return {
        values: getFormValues('FlightEditor')(state),
        _values: getFormValues('FlightEditor')(state),
    };
};
```

In debugger, before the form is initialized:

![screen shot 2016-08-30 at 12 05 30 pm](https://cloud.githubusercontent.com/assets/5831434/18097062/5e1ffe46-6eaa-11e6-96af-29258c19cabb.png)

Both `values` and `_values` are undefined. As expected -- form didn't initialize yet.

After the form is initialized:

![screen shot 2016-08-30 at 12 05 54 pm](https://cloud.githubusercontent.com/assets/5831434/18097074/6f5c27b6-6eaa-11e6-8dd4-ce1271cc2c0b.png)

Somehow `_values` has the correct value, but `values` remains undefined.

Is this intended? If so, the docs should be changed IMO. If not, I'm curious why. I can't seem to find anything in the code that would prevent a variable named `values` from being propagated.

**Comment by m19** [comment]
I can confirm I had the exact same problem.
Workaround was changing `values: getFormValues('myForm')(state)` to `formValues: getFormValues('myForm')(state)`.

**Comment by timhwang21** [comment]
Interesting! I think I found some other workaround in the end, but I'll give this a shot. Thank you!

**Comment by alexcoady** [comment]
+1. `values` always equals `undefined`, as soon as it's renamed everything works as expected. This had me pulling my hair out.

**Comment by lama-pacos** [comment]
cool

**Comment by alex-shamshurin** [comment]
I use `formValues      : getFormValues('myForm')(state),` and it is always `undefined`

**Comment by brethubbard** [comment]
+1 thanks for the workaround. I have been struggling with this selector for a while now.

**Comment by andrerpena** [comment]
Please someone fix this. I lost 1 hour on this. Thanks @m19 for the workaround. Saved my sanity.

**Comment by gustavohenke** [comment]
> Please someone fix this

You can always do it yourself @andrerpena, this is the beauty of open source!

**Comment by andrerpena** [comment]
You are right. I'll look into it.

Em 20 de mai de 2017 20:10, "Gustavo Henke" <notifications@github.com>
escreveu:

Please someone fix this

You can always do it yourself @andrerpena <https://github.com/andrerpena>,
this is the beauty of open source!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/erikras/redux-form/issues/1658#issuecomment-302904372>,
or mute the thread

**Comment by andrerpena** [comment]
You are right. I'll look into it.

Em 20 de mai de 2017 20:10, "Gustavo Henke" <notifications@github.com>
escreveu:

**Comment by danielrob** [comment]
Is this bug actually still true? I cannot reproduce on 7.0.3: https://codesandbox.io/s/BLZPLNJY

**Comment by capozzic1** [comment]
I have 7.0.3 and this is still a bug. formValues did work. Thanks alot!

**Comment by MarcusHurney** [comment]
I am can confirm this is still a bug

**Comment by Snowbell92** [comment]
@danielrob's code worked for me though.

**Comment by saeedjalali1** [comment]
I have the same issue, because I use Immutable.js. After change input from 
```import { getFormValues } from 'redux-form```
to 
```import { getFormValues } from 'redux-form/immutable'```
everything works fine.

**Comment by danielrob** [comment]
Could someone who believes this issue is still existent please provide a reproduction sandbox? 

The sandbox I linked clearly shows this working, which makes it hard to address the issue (note: you must enter a value in the form in my sandbox since the initial state of the form is undefined).

**Comment by timhwang21** [comment]
For what it's worth, I can't reproduce in sandbox. So I'm all for closing.

**Comment by timhwang21** [comment]
For what it's worth, I can't reproduce in sandbox with the latest version. So I'm all for closing.
