### ISSUE TITLE
Set non-field errors on an object in a FieldArray

### ISSUE THREAD

**Issue by halayli** [erikras/redux-form#1659]
As far as I can tell, it isn't possible to set a non-field error (like the form wide error) on an object in an array. 
This is useful as sometimes there are non-field errors that are applied to an object in an array but not to a particular field in the object.

**Comment by nktssh** [comment]
@halayli 
It is possible, try this in your `validate` function:
```
errors.your_field_name._error = "Some error"
```

**Comment by halayli** [comment]
@nktssh I tried that but the error never made it into the props of "your_field_name"'s error where "your_field_name" is of the form "form.members[0].submember[2]._error

**Comment by melinath** [comment]
Pretty sure you have to use a nested object like:

```
{
	members: [
		{
			submembers: [
				null,
				null,
				{
					_error: 'message!'
				}
			]
		}
	]
}
```

**Comment by danielrob** [comment]
This appears answered. If it is not, take a look at #3242, or let it be known!
