### ISSUE TITLE
handleSubmit with clientMiddelware.js response

### ISSUE THREAD

**Issue by andresgutgon** [erikras/redux-form#166]
Hey, I'm using https://github.com/erikras/react-redux-universal-hot-example as base for my project. Now I'm making my first redux-form form. I'm not sure if I'm doing it right.

First here the code:
``` javascript
import { COMPLETE_SIGNUP_FAIL } from 'redux/modules/signup/complete';
// ....
  handleSubmit(data) {
    const fail = COMPLETE_SIGNUP_FAIL;

    return this.props.complete(data).then((response) => {
      if (response.type !== fail) {
        this.props.initialize('signupComplete', {});
        // do something on success like redirect user.
        return Promise.resolve({});
      }

     // Here manipulate server response to map redux-form error format
      const errorsKeys = Object.keys(response.error);
      const formErrors = errorsKeys.reduce((formatedErrors, key) => {
        formatedErrors[key] = response.error[key][0];
        return formatedErrors;
      }, {});

      return Promise.reject(formErrors);
    });
  }
```

As you can see I'm using a redux action `this.props.complete` to make an AJAX call agains my API. This is great. I've a reducer for this call and when the server response I get `error` and `type`. 

`type` is my reducer fail constant: `COMPLETE_SIGNUP_FAIL`. 

In my case I've to do error manipulation from server response before reject the promise and pass it to redux-form. 

My first try was to do it on my reducer. But then in the `.then` clause I do not have access to `this`. So I've to do server error manipulation on `handleSubmit`. 

Can you tell me if I'm doing it right?

Thanks for the great work

## Extra
On extra question. If my server response with success I want to do a redirect. Is `handleSubmit` the right place to do it?

**Comment by andresgutgon** [comment]
Ok, is one of those javascript things I do not get. If I use the OLD good `self` I can do this

``` javascript
  handleSubmit(data) {
    const self = this;

    return this.props.complete(data).then(() => {
      const errors = self.props.completeSignupErrors;

      if (Object.keys(errors).length) {
        return Promise.reject(errors);
      }

      // do something on success
      self.props.initialize('signupComplete', {});
      return Promise.resolve({});
    });
  }
```

As you can see now I've moved error manipulation `completeSignupErrors` to my FAIL reducer.

But I don't get why I don't have access to `this` using an arrow function `() =>`

**Comment by erikras** [comment]
That is very strange. You _really_ should have access to `this` in your arrow function.

You code looks pretty reasonable to me. I see no major flaws.

**Comment by erikras** [comment]
Did you figure this out? Can you provide more information that might help me help you?

**Comment by andresgutgon** [comment]
No, sorry I did not get why I need `self`

**Comment by erikras** [comment]
Trust in your `self`. This `self` doubt is not healthy. :grinning: 

Joking aside, does your code work, at least?

**Comment by andresgutgon** [comment]
Yes, is working :) Thanks @erikras you can close it. I'm pretty sure is my mistake. I figure out. If I find the reason and is interesting I'll share with you :smile:

**Comment by andresgutgon** [comment]
Maybe I have an idea of what was my mistake. On `render` method I had this:

```javascript
   <MyForm onSubmit={this.handleSubmit}
```

And `this` was undefined on `onSubmit` method. But what realy have now is this:
```javascript
   <MyForm onSubmit={::this.handleSubmit}
```

With that strange notation my form is working without `self`. 

At the end I have changed that strange notation `::` for a more convintional `.bind(this)`
This is my form now:

```javascript
   <MyForm onSubmit={this.handleSubmit.bind(this)}
```

**Comment by erikras** [comment]
Yes, that is exactly the problem. If I'd've seen that line, I'd've said something. Glad you got it worked out.
