### ISSUE TITLE
Field-dependent validation

### ISSUE THREAD

**Issue by ndnhat** [erikras/redux-form#1661]
I have a situation where I need to validate a "text" input based on the value of a "checkbox" input. If the "text" input is empty, and the "checkbox" is checked, then I need to display an error. This is fairly simple with the validate() function.

````
const validate = (form) => {
  const { textField, checkbox } = form;
  const errors = {};

  if (!textField && checkbox) {
    errors.textField = "You have to fill out the field";    
  }
  return errors;
};
````

However, I also want to uncheck the checkbox when this error occurs. I'm starting to think that validate() is not the place to do this because if I do uncheck the checkbox, the validation condition will no longer be true and the error will go away. 

How should I go about doing this?

**Comment by Sir4ur0n** [comment]
You want the checkbox switching value to happen also whenever a field is modified and then the focus is lost (onBlur), or only onSubmit?

If it's whenever the field is modified (even without onBlur), then you can use [normalizing](http://redux-form.com/6.0.1/examples/normalizing/) to change the value of the checkbox if the text field is empty.

**Comment by ndnhat** [comment]
Ah yes. Thank you very much. I think that's a great idea. 👍 

I can use normalize to prevent the checkbox from being checked. Only thing is, I would then have to manage the state of this error message. But I think I can live with that.

Thanks again for pointing me in this direction. Much appreciated.
