### ISSUE TITLE
Feature: Ability to provide initialValues with Immutablejs (Map or Record)

### ISSUE THREAD

**Issue by ntucker** [erikras/redux-form#1662]
Currently I'm converting my state to JS, which I'm sure is then converted back since I'm using immutable everywhere.

```javascript
  (state) => {
    const basicInfo = ::BasicInfoRecord.makeFindSelector({})(state).toJS()
    return {
      initialValues: basicInfo,
    }
  },
```

**Comment by cristian-sima** [comment]
It works for me, however you have to use a `Map`

**Comment by jferg2010** [comment]
@cristian-sima - any chance you could provide a code example. I can't seem to get it to work, even when passing in a Map.

**Comment by RockingRolli** [comment]
Same issue here. Neither Record nor Map seem to work.

**Comment by jferg2010** [comment]
I figured out my issue. I had correctly imported from _redux-form/immutable_ in my form component, but my reducer was still importing from _redux-form_. The result was that the top-level form state was an object, even though the underlying entries in the state, such as values and initialvalues, were maps. 

The reducer import should read 

**import {reducer as formReducer} from 'redux-form/immutable'**

It might be worth clarifying that in the immutable example docs.

**Comment by ntucker** [comment]
This still doesn't work for Records...I have been importing from `import { reducer as formReducer } from 'redux-form/immutable'` the whole time
