### ISSUE TITLE
http://redux-form.com/6.0.1/examples/react-widgets/ page isn't loading

### ISSUE THREAD

**Issue by flaprogrammer** [erikras/redux-form#1666]
Can't see the examples =(

**Comment by kevinzwh** [comment]
The gh-pages directory of 6.0.1/examples/react-widgets is missing its **dist** folder which includes bundle.js most importantly which allows the form to function. 

I went ahead and built the files from the source & added them in this PR https://github.com/erikras/redux-form/pull/1674

**Comment by gustavohenke** [comment]
Was fixed by #1674.
