### ISSUE TITLE
[V6] I can't access to form props in react-native

### ISSUE THREAD

**Issue by AlessandroCorradini** [erikras/redux-form#1668]
I don't understand how can I access to form props. I used `formValueSelector` as suggested the documentation, but doesn't work. Where is my mistake?

**LoginForm.js**

```
'use strict';

import React from 'react';
import { Field, reduxForm, formValueSelector } from 'redux-form';
import { TextInput, View, TouchableHighlight, Text } from 'react-native';
import { connect } from 'react-redux';

class LoginForm extends React.Component {

    handeSubmit(email, password){ alert(`email: ${email} and password: ${password}`)};

    render() {

        return (
            <View>
                <Field
                    name="email"
                    component={TextInput}
                    placeholder="Email"
                />
                <Field
                    name="password"
                    component={TextInput}
                    placeholder="Password"
                    secureTextEntry={true}

                />
                <TouchableHighlight onPress={() => this.handeSubmit(this.props.email, this.props.password)}>
                    <Text>Submit</Text>
                </TouchableHighlight>
            </View>
        );
    }
}


LoginForm = reduxForm({
    form: 'loginForm'
})(LoginForm);

const selector = formValueSelector('loginForm');

function mapStateToProps(state){
    return {
        email: selector(state, 'email'),
        password: selector(state, 'password'),
    }
}

LoginForm = connect(mapStateToProps)(LoginForm);

export default LoginForm;
```
**LoginPage.js**

```
'use strict';

import React from 'react';
import {View} from 'react-native';
import Container from '../../components/Container';
import LoginForm from '../../components/forms/LoginForm';

class LoginPage extends React.Component {
  render() {
    return (
        <Container>
            <LoginForm/>
          </Container>
    );
  }
}



export default LoginPage;
```

![screenshot_20160831-161930](https://cloud.githubusercontent.com/assets/13152962/18132344/bb50aa9c-6f96-11e6-8c9b-067a4ad76cfa.png)

**Comment by AlessandroCorradini** [comment]
I use `alert(this.props)` onPress button and this is the output. There aren't `email` and `password`.

![screenshot_20160831-170355](https://cloud.githubusercontent.com/assets/13152962/18134562/16d73eb4-6f9f-11e6-9872-cde2c6bdf859.png)

**Comment by AlessandroCorradini** [comment]
I found the solution. TextInput doesn't work with redux-form as it is. It need a component than pass the redux-form props:

class TextField extends React.Component {
      render(){
        const { input: { value, onChange } } = this.props;
        return (
                <TextInput
                    style={[styles.textInput, margin]}
                    onChangeText={(value) => onChange(value)}
                    value={value} underlineColorAndroid="transparent" selectTextOnFocus={true} {...this.props}
                />
        );
    }
}

![screenshot_20160831-190650](https://cloud.githubusercontent.com/assets/13152962/18138658/1631164c-6fae-11e6-9276-3d0839628af4.png)

**Comment by Fandekasp** [comment]
Wow, I was stuck on trying to use react-native with redux-form, and finally found this thread. Would be great to have a React Native example with this tip, thx!

**Comment by jpaas** [comment]
I've tried this using redux-form 6.0.2 and redux-native 0.32.1 but I can't get it to work. Every time the value prop is hooked up to the TextInput, it eats the characters so you can't see them. Also every time I receive the handleSubmit, the values argument is an empty object.

I asked about this a week ago on StackOverflow https://stackoverflow.com/questions/39331420/cant-get-redux-form-6-0-2-working-with-react-native-0-32-0 but haven't gotten any answers.

Does this work with react-native? Can we get a working example?

**Comment by jpaas** [comment]
It only seems to work if I don't bind the value prop. But it still does not pass the form values to my handleSubmit callback.

**Comment by erikras** [comment]
I don't have any experience with RN. It would be great if someone that did would write an example rather than only wishing that it were so. Such a PR would be accepted.

**Comment by sean-madhavan** [comment]
I got it working recently with RN 0.32.0

- form.js
```
render() {
    const {handleSubmit, authSignin} = this.props;

    return (
      <View>
        <Text>Email</Text>
        <Field name="email" component={EmailField} />
        <Text>Password</Text>
        <Field name="password" component={PasswordField} />
        <Button onPress={handleSubmit(authSignin)}>Sign In</Button>
      </View>
    );
  }
```

- email-field.js
```
import React, { Component } from 'react';
import { TextInput } from 'react-native';
import styles from '../../styles';

export default class EmailField extends Component {
  render(){
    const { input: { value, onChange }, ...otherProps } = this.props;
    return (
      <TextInput
        keyboardType="email-address"
        style={styles.textInput}
        onChangeText={(value) => onChange(value)}
        value={value}
        {...otherProps}
      />
    );
  }
}
```

Text field would be just same as email field if you remove keyboard type.

**Comment by jpaas** [comment]
Thanks @sean-madhavan for the sample. I tried it as you've shown, but I still have the same problems. 

1. The TextInput removes every character I type so the field remains empty. The redux store only contains the last character I typed. Removing `value={value}` seems to prevent it, but obviously we want the field to show the redux store value.

2. The submit callback receives an empty object for the first argument (values). I've also tried binding the email and the password using the formValueSelector, but the props remain undefined.

Out of desperation, I've now tried upgrading to react-native 0.33.0 and redux 3.6.0.

**Comment by sean-madhavan** [comment]
@jpass I guess the problem lies in redux management. When are you updating redux store value to display on text field?

**Comment by jpaas** [comment]
@sean-madhavan - I'm not doing any updating of the store beyond what the redux-form Field wrapper is doing

**Comment by sean-madhavan** [comment]
@jpaas can you post latest code with my sample on stackoverflow?

**Comment by jpaas** [comment]
@sean-madhavan Code posted at https://stackoverflow.com/questions/39331420/cant-get-redux-form-6-0-2-working-with-react-native-0-32-0

**Comment by Fandekasp** [comment]
In my case, I was also running in the issue "validate method receives empty values", and just figured out why: When adding an **onChangeText** method to my field, it was effectively overwriting the redux-form one, hence not saving the prop in the form field. Removing it fixed the issue

**Comment by jpaas** [comment]
@Fandekasp clearing text as I type ONLY happens when have `value={value}`. If you are not binding onChangeText, is there anything you are binding besides value?

**Comment by Fandekasp** [comment]
Here's my code, if that's of any help.

----

TextField.js
```
import React from 'react';
import { TextInput } from 'react-native';

const { PropTypes } = React;


const TextField = (props) => {
  const {
    style,
    input: { value, onChange },
    meta: { error, touched },
    ...otherProps,
  } = props;

  return (
    <TextInput
      // Let's only change the text color instead of showing error messages
      style={(touched && error) ? [style, { color: 'red' }] : style}
      underlineColorAndroid="transparent"
      onChangeText={text => onChange(text)}
      value={value}
      selectTextOnFocus
      {...otherProps}
    />
  );
};

/* eslint-disable react/forbid-prop-types */
TextField.propTypes = {
  style: PropTypes.object.isRequired,
  meta: PropTypes.object.isRequired,
  input: PropTypes.object.isRequired,
};


export default TextField;
```


Email.js
```
import React from 'react';
import ReactNative from 'react-native';
import autobind from 'autobind-decorator';
import Button from 'react-native-button';
import Hyperlink from 'react-native-hyperlink';
import {
  Field,
  reduxForm,
  SubmissionError,
} from 'redux-form';
// ...

const formOptions = {
  form: 'email',
  validate: validateEmailLogin,
  touchOnChange: true,
  fields: ['email', 'password'],
};

@reduxForm(formOptions)
class Email extends Component {
  static propTypes = {
    fetchUserBy: PropTypes.func.isRequired,
    form: PropTypes.any.isRequired, // eslint-disable-line
    handleSubmit: PropTypes.func.isRequired,
  };

  @autobind
  async handlePress({ email, password }) {
    const { fetchUserBy } = this.props;

    try {  // api call
      await fetchUserBy('email', [email, password]);
    } catch (error) {
      Alert.alert(t.errorTitle, t.loginError);
      throw new SubmissionError({
        email: t.loginError,
        password: t.loginError,
      });
    }
  }

  render() {
    const { handleSubmit } = this.props;

    return (
      <View style={styles.view}>
        <View style={styles.labelWrapper}>
          <Text style={styles.label}>
            { t.emailLabel }
          </Text>
        </View>
        <View style={styles.inputWrapper}>
          <View style={[styles.textInputWrapper, styles.innerTextInput]}>
            <Field
              style={BaseStyles.TextInput}
              name="email"
              type="email"
              component={TextField}
              placeholder={t.emailPlaceHolder}
              placeholderTextColor={BaseStyles.lightGray}
              keyboardType="email-address"
              returnKeyType="next"
            />
          </View>
          <View style={styles.textInputWrapper}>
            <Field
              style={BaseStyles.TextInput}
              name="password"
              type="password"
              component={TextField}
              placeholder={t.passwordPlaceHolder}
              placeholderTextColor={BaseStyles.lightGray}
              returnKeyType="next"
              secureTextEntry
            />
          </View>
        </View>
        <View style={styles.buttonTextWrapper}>
          <Button
            containerStyle={styles.buttonWrapper}
            style={styles.button}
            onPress={handleSubmit(this.handlePress)}
          >
            { t.login }
          </Button>
          <Hyperlink
            style={styles.textWrapper}
            linkText={t.passwordForgotten}
            onPress={redirectTo}
          >
            <Text style={styles.text}>
              {PASSWORD_FORGOTTEN_URL}
            </Text>
          </Hyperlink>
        </View>
      </View>
    );
  }
}


export default connectToProps(Email, 'user', Actions);
```

validate.js
```
/**
* @flow
*/
/* eslint no-console: ["error", { allow: ["log"] }] */

const t = {
  required: 'Field required',
  badEmail: 'Email is incorrect',
};

// Terribly simple and easily circumvented
const isEmail = text =>
  (typeof text === 'string') && /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i.test(text);


const validateEmailLogin = (values) => {
  const errors = {};
  if (!values.email) {
    errors.email = t.required;
  }
  if (!values.password) {
    errors.password = t.required;
  }
  if (!isEmail(values.email)) {
    errors.email = t.badEmail;
  }
  return errors;
};

export default validateEmailLogin;
```

**Comment by davidfurlong** [comment]
@Fandekasp I'm pretty sure that fields of the reduxForm constructor is deprecated in v6

**Comment by davidfurlong** [comment]
I've tried several of these and none seem to work. My issue is that redux-form is updating the form state in the redux state but this state is not by default being connected to my component. `this.props.form` is `"loginForm"` instead of what it should be, the fields object

**Comment by jpaas** [comment]
My question was answered on StackOverflow. It seems that I had set up my reducers using `redux-immutable` but I wasn't importing `redux-form/immutable`. All good now. Thanks to all who tried to help out.

**Comment by JeroenNelen** [comment]
Hey all,
I'm a bit confused at the moment, I got 2 different versions of a form working with react-native and redux-form;
1. the way @AlessandroCorradini did it (using a connected component and the selector to get the data from the form)
2. they way @jpaas did it, posted here: https://stackoverflow.com/questions/39331420/cant-get-redux-form-6-0-2-working-with-react-native-0-32-0 , without connecting the component and without selectors

In both cases I correctly get the form data... Which one would be preferable? The less verbose one and AFAIK more performant is number 2, because there is no mapStateToProps etc there (and I want it to be a stateless component anyway...)
am I overlooking something?

Cheers,

**Comment by Tushant** [comment]
I see most of are posting their solution regarding react native and redux form. I am posting either, thinking that my code might help other 

Here is my working code with output 

```javascript
import React, { Component } from 'react';
import { Field, reduxForm } from 'redux-form';
import { View, Text, TextInput } from 'react-native';
import { Button } from 'react-native-elements';


const renderTextField = ({ input, label, meta: { touched, error }, ...custom }) => (
        <TextInput
            placeholder={label}
            onChangeText={(value) => input.onChange(value)}
            {...input}
        />
);

class DeviceIO extends Component {
    onSubmit = (props) => {
        console.log('props', props);
    }
    render() {
        const { previousPage, handleSubmit } = this.props;
        return (
            <View>
                    <Field
                        name="deviceName"
                        label="Device Name"
                        component={renderTextField}
                    />
                    <Field
                          name="deviceTimeout"
                          component={renderTextField}
                          label="Device Timeout"
                    />
                    <View style={{ marginTop: 12}}>
                        <Button
                            raised
                            icon={{ name: 'ios-arrow-round-back-outline', type: 'ionicon' }}
                            iconLeft
                            title='Back'
                            backgroundColor='#ff4c4c'
                            onPress={() => previousPage()}
                        />
                        <Button
                            raised
                            icon={{ name: 'ios-arrow-round-forward-outline', type: 'ionicon' }}
                            iconRight
                            title='Next'
                            backgroundColor='#ff4c4c'
                            onPress={handleSubmit(props => this.onSubmit(props))}
                        />
                    </View>
            </View>
        );
    }
}

export default reduxForm({
  form: 'createDevice',
  destroyOnUnmount: false,
})(DeviceIO);

```

Sorry the design is terrible right now :) 

http://imgur.com/a/2EwfF 

Thanks,
Happy Coding

**Comment by zunder** [comment]
@Tushant just for completeness, in this part of your example you shouldn't spread input:
```javascript
const renderTextField = ({ input, label, meta: { touched, error }, ...custom }) => (
<TextInput
    placeholder={label}
    onChangeText={(value) => input.onChange(value)}
    {...input}
/>);
```
Having it additional to onChangeText causes the action to be fired twice, the second one not changing the state of the redux store, but just being an unnecessary duplicate.

**Comment by kubido** [comment]
I got undefined for `this.props.input` is that props from redux-form or I need to do something to get `this.props.input` ?
