### ISSUE TITLE
Typings for 6 version

### ISSUE THREAD

**Issue by flaprogrammer** [erikras/redux-form#1669]
Hi, I haven't found type definitions file for new version, but didn't found it yet. Have you some ideas to use 6th version on typescript now?

**Comment by huan086** [comment]
@CarsonF is working on it. See https://github.com/erikras/redux-form/pull/1318

**Comment by reprise108** [comment]
Is this still being worked on? I would also like to use this in our TypeScript project!

**Comment by gustavohenke** [comment]
Closing in favor of the popular #1211
