### ISSUE TITLE
Hook or option to destroy @connected form on `componentWillUnmount`

### ISSUE THREAD

**Issue by damassi** [erikras/redux-form#167]
I'm in the process of laying out a few pretty complex and large forms, including quite a few add/duplicate/remove types, and it would be great to be able to automatically destroy the form if the component is unmounted. Is this possible right now? Looking through the docs there are a few action creators that could possibly handle this, but I"m wondering about the best way to approach.

**Comment by erikras** [comment]
`v2.4.x` has a `destroyForm` prop, so you can do `componentWillUnmount() { this.props.destroyForm(); }`

`v3.x` will make this the default behavior.

**Comment by damassi** [comment]
Ok great, thanks for the response! Awesome work
