### ISSUE TITLE
asyncValidate error on blur after update to v6.0.1

### ISSUE THREAD

**Issue by s-e-b** [erikras/redux-form#1675]
Hello,

today I tried updating redux-form from `6.0.0-rc.4` to `6.0.1`. It all went smoothly except I am now getting the following error for one of my fields whenever it is being blurred:

```
Uncaught Error: asyncValidate function passed to reduxForm must return a promise
```

This is surprising to me as I am not using async validation anywhere in my code and I'm not passing any `asyncValidate` function to `reduxForm()`. I was able to work around the issue by explicity passing a _dummy_ `shouldAsyncValidate` function which just returns false (`() => false`), however, I feel like that shouldn't be needed.

I tried to isolate the problem and create a jsbin that triggers the error but unfortunately didn't manage to do so. Nevertheless, I wanted to ask whether anybody has an Idea what the root cause for this could be? I didn't have any errors using redux-form version `6.0.0-rc.4`.

Here's the stacktrace - in case that helps:
<details>
    <summary>

Stacktrace</summary>

```
    Uncaught Error: asyncValidate function passed to reduxForm must return a promise

    asyncValidation         @ asyncValidation.js:17
    (anonymous function     @ reduxForm.js:350
    asyncValidate           @ reduxForm.js:355
    (anonymous function)    @ createOnBlur.js:42
    (anonymous function)    @ TagsInput.js:104
    notifyAll               @ CallbackQueue.js:67
    close                   @ ReactUpdates.js:60
    closeAll                @ Transaction.js:204
    perform                 @ Transaction.js:151
    perform                 @ ReactUpdates.js:90
    flushBatchedUpdates     @ ReactUpdates.js:173
    closeAll                @ Transaction.js:204
    perform                 @ Transaction.js:151
    batchedUpdates          @ ReactDefaultBatchingStrategy.js:63
    batchedUpdates          @ ReactUpdates.js:98
    dispatchEvent           @ ReactEventListener.js:150
```

</details>

For what it's worth: That's all react/redux-form code. The only code that stems from me is the `TagsInput`. The code in the referenced line is just calling the `onBlur` callback with an array of strings. The onBlur callback is redux-form's `createOnBlur` function.

I am using the following versions:

```
"react": "15.2.1"
"react-redux": "4.4.5"
"redux": "3.5.2"
"redux-form": "6.0.1"
```

Any help and/or pointers are much appreciated.

Thanks

**Comment by gustavohenke** [comment]
Hi @s-e-b, thanks for the report.
Have you ever fixed your problem?

In case you manage to have some code that reproduces the issue, please post it here.
Don't forget to try newer versions.

**Comment by m1m6** [comment]
I Have the same issue, i didn't use async validation in anywhere!

**Comment by s-e-b** [comment]
Hi @gustavohenke,

thanks for getting back to me. Yes, I did manage to "fix" the issue eventually - albeit it was by coincidence.

The problem - in my case - was that I was naivly spreading `props` onto children elements. This caused redux-form's `onChange` or `onBlur` callback (I can't remember which one it was) to be overridden by mistake. And it seems that this lead to the asyncValidate error. 

I'm not sure why this wasn't a problem with version `6.0.0-rc.4` and only showed up after updating to `6.0.1`. But cleaning up the properties and only passing down what was actually needed fixed the issue for me and I could remove the dummy `shouldAsyncValidate` function that I had added previously.

Hope that helps other people that might have a similar issue.

**Comment by m1m6** [comment]
@s-e-b  I have the same problem as you, I passed the props onto children elements, and that's why i'm getting asyncValidation error, can u please provide me with the props you passed them down ?

**Comment by s-e-b** [comment]
@m1m6 My exact `props` are probably not of much use to you as I was using a custom component that needed custom properties. But here's a simplified example of the issue:

Initially I had something like this:
```
const MyInputField = props => (
    <Field
        component={ <MyInputComponent /> }
        { ...props } />
);
```
The problem was that `props` contained some property the overrode a redux-form default because I spread it onto the `Field` component. I _think_ the problematic property was `onChange` or `onBlur`. (But it might very well have been something related to validation - I can't remember.) I didn't expect that property to be there but it was due to me repeatedly spreading `props` somewhere higher up the component tree.

So instead of spreading all `props` onto the `Field` I only picked the ones that were really needed, e.g.:

```
const MyInputField = ({ name, placeholder, value, ...rest }) => (
    <Field
        component={ <MyInputComponent /> }
        name={ name }
	placeholder={ placeholder }
	value={ value } />
);
```

This fixed the issue for me.

**Comment by colvint** [comment]
```
reduxForm({
    asyncBlurFields: [] // this seems to prevent the error
  })(MyAwesomeForm)
```

**Comment by laurengreenway** [comment]
+1 to this issue, not using async validate in my project, but getting this error on one form. 

asyncBlurFields fix works, but feels hacky and still trying to figure out why

**Comment by gustavohenke** [comment]
I'm closing this issue. For anyone reading this: if you are still having problems and is able to create a reproducible example in a new issue, we can have a look at it!

This type of thing isn't a common bug for redux-form, so must be something related to the setup of you folks.

**Comment by nicotsou** [comment]
I had the same issue and the solution was stupid. Someone forgot 2 nested redux forms. It was throwing this error until I removed the one of them 💃

**Comment by drewdecarme** [comment]
I had the same issue during a major refactor and it turned out I was wrapping a sub component in redux forms when a parent component was already wrapped in redux forms.

**Comment by charlax** [comment]
Had the same issue, not sure it makes sense to have two redux-form wrapped within each other, maybe there could be a warning or a better error?
