### ISSUE TITLE
[v6] parse and format should be called with field name

### ISSUE THREAD

**Issue by huan086** [erikras/redux-form#1677]
I have `Fields` that rely of fields of different type. For example, a time selector consisting of hour, minute (number) and am/pm (string).

All the fields trigger the same `parse` and `format`, giving no way to differentiate the number fields from the string fields

**Comment by erikras** [comment]
Fix published in [`v6.1.0`](https://github.com/erikras/redux-form/releases/tag/v6.1.0).
