### ISSUE TITLE
"redux-form/CHANGE" action sets Material-UI TextField value as [object Object]

### ISSUE THREAD

**Issue by PharaohMaster** [erikras/redux-form#1678]
I'm using completely exact example code for Material-UI.
https://github.com/erikras/redux-form/blob/v6.0.1/examples/material-ui/src/MaterialUiForm.js
I've tested it with `"material-ui": "0.15.3"` and `"material-ui": "0.15.4"`.

Problem occurs when I try to write some text and then completely delete it from input field. When last character is deleted from the field, the field gains new value of `[object Object]`.
I'm inspecting Redux DevTools and this last action is leading to unexpected behaviour.

`type:"redux-form/CHANGE",
meta: {
  form:"MaterialUiForm"
  field:"firstName"
  touch:true
},
payload:{
  filter: ""
}`

Looking a little bit at material-ui `TextField` it is expecting only string as a value but payload is not string but `{filter: ""}` object and that is why value is set as `[object Object]`.

**Comment by erikras** [comment]
I am not seeing this behavior in the example.

Have you tried using [`redux-form-material-ui`](https://github.com/erikras/redux-form-material-ui)?

**Comment by PharaohMaster** [comment]
You are completely right. After a little bit investigating in our code base some other reducer was interfering and changing action for redux-form (completely undetected bug so far). When we fixed that, everything is working like it should. Sorry for false alarm.
