### ISSUE TITLE
[v6][proposal] optional legacy v5 fallback for easier migration

### ISSUE THREAD

**Issue by kromit** [erikras/redux-form#1683]
1. reason: I am struggling with the idea of giving away the control of the state and meta from the form to the fields. I think it makes the fields too atomic. The form has de facto no idea what the fields are doing, so greater field relations are much more difficult to control.
2. reason: I have a lot of giant forms with a lot of combined fields. With v6 I would need to create a static component for each combination without the need to reuse it even once. This makes v6 virtually unusable for me.

The idea: the `Fields` component has almost the same functionality as the v5 form, it provides the `fields` to the rendered component. 

Wie could provide a higher order function to wrap the old v5 form internally with the `Fields`component and a list of names.

Quick and dirty solution using a `legacyForm`:

```
export default reduxForm(legacyForm(LoginForm,['username', 'password']));
```

```
export const legacyForm = (WrappedComponent,names) => {

return class LegacyForm extends Component {
        static childContextTypes={
            formProps:PropTypes.any,
            wrappedComponent:PropTypes.any
        }
        getChildContext() {
            return {
                formProps: this.props,
                wrappedComponent: WrappedComponent
            };
        }
        render(){
            return(
                <Fields names={names} component={FieldsProvider}/>
            );
        }
    }
}
}

class FieldsProvider extends Component{
    static contextTypes={
        formProps:PropTypes.any,
        wrappedComponent:PropTypes.any
    }
    render() {
        const {formProps,wrappedComponent} =this.context;
        return createElement(wrappedComponent, {fields:this.props, ...formProps})
    }
}

```

This would allow a painless migration from v5 to v6 without the need to change everything

**Comment by gustavohenke** [comment]
Hi @kromit! What you ended up doing?
