### ISSUE TITLE
Access full field properties in form

### ISSUE THREAD

**Issue by shawnmclean** [erikras/redux-form#1687]
In pre-redux-form 6, I have UI state on the form that depends on whether a specific field was invalid or not. I can't wrap this state inside the component that I pass to `Field`.

`formValueSelector` does not help me as it gives only the raw values.

How can I get the state of a field input with its validation from my `mapStateToProps` or in the form itself?

**Comment by huan086** [comment]
There's a `Fields` component where you can get both the field to display and the field where you check for valid/invalid

**Comment by danielrob** [comment]
@huan086 thank you. I've never seen the use case for `Fields` described so simply. 

Closing this usage question due to non-response.
