### ISSUE TITLE
Calculated Props usage

### ISSUE THREAD

**Issue by lordakshaya** [erikras/redux-form#169]
How can I use the calculated props for the following (e.g. if my calculated prop name is sum) :
1. in Validate method ( currently `props.sum` isn't defined )
2. displaying errors ( I'm setting the error msg as `error.sum = 'blah blah'` but in the render method `sum.error` isn't available)
3. On submit, the calculated props arent returned.

Is it possible to achieve it in the current state of this module?

**Comment by erikras** [comment]
No. Validation is only available for fields.

**Comment by lordakshaya** [comment]
@erikras I think that takes out my point 1 n 2 out for now. Perhaps I'll try to make it available, if thats the vision of the mod. 

What about my point 3 i.e. returning calculated values onSubmit. Is that possible? Or would that also be a part of the TODO list for this component?

**Comment by erikras** [comment]
No, I don't really think that's part of the vision. At least I don't see a compelling reason to support it.

**Comment by lordakshaya** [comment]
@erikras let me explain my use case. I m building a form that takes a 6-digit OTP from the user as input via 6 text boxes (with max length = 1 each). I have a calculated property which is concatenated string of the values present in the text boxes. 

Now, I'd like to use the calculated property for validation purposes (and also returning it on form submission) instead of putting the re-calculation logic in my validate method & the form submit method to keep things clean. 

WDYT? Wouldn't adding the calculated property on the validation methods + the submission method make sense?

**Comment by gowram** [comment]
another use case would be product price = Price + VAT/Tax
VAT / Tax vary based on product

**Comment by erikras** [comment]
I would make a function that took all the form values and returned all the form values + the calculated properties. `addCalcProps`, we'll call it. And then you can reuse it everywhere you need it.
```js
validate(rawValues) {
  const values = addCalcProps(rawValues);
  // do validation
}

handleSubmit(rawValues) {
  const values = addCalcProps(rawValues);
  // do submission
}
```
This really isn't functionality that redux-form should support, it's additional functionality, with trivial code reuse, that is up to the individual project.
