### ISSUE TITLE
Suggestion: don't bundle examples

### ISSUE THREAD

**Issue by mschipperheyn** [erikras/redux-form#1690]
Working examples should have non minified source code, so it's easier to follow the flow and reason about why your code is not working like in the example

**Comment by erikras** [comment]
You mean on redux-form.com? It has source maps. Is that not good enough?

![sourcemaps](https://d1ro8r1rbfn3jf.cloudfront.net/ms_43774/l59rl8h50KmxuPcz1Tug2DbV7qwRtW/Redux%2BForm%2B2016-09-05%2B09-27-18.jpg?Expires=1473146907&Signature=IX50R8mgTUTQbbbflupWtwxiQH0ufqoeWuAvfCYGkGFt38WNMmMgBJ0Pe8jy249~2~Z-3P4yp5LB~Ln6QfDrKckQQRugRKx7rrNDoSH8W9lGuT2PlF1h-tsoy3PeM24rtX6gNwkkoRH7s8f21MNgczk2dVJpq548wM2DheeGeKMsjfoiXzeV2EorwQcXtx-Gntw9S9fSnrH8Bf~k5wENAutIb5HWNDeTY8HRO~4ZLcJ57ofji1XzDCPOtyw2WLKrTG-DqansMV66HB6y-P8U1JvdvsuFxpoHPeDLcXPmbINhY21WpIwjHivvCUj-JcBBBOvFtt6LzIB8hzV13Lspvg__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)

**Comment by mschipperheyn** [comment]
Ah ok. Yeah, that would be. I hadn't realized.
