### ISSUE TITLE
Field Arrays and immutable js

### ISSUE THREAD

**Issue by KyKyPy3** [erikras/redux-form#1694]
Do you have a working example of the Field Arrays with immutable js? All my attempts to make it work lead to error "list.splice is not a function".

**Comment by KyKyPy3** [comment]
After several unsuccessful attempts, I seem to have found a workaround. Instead of such code:

`<Button type="button" onClick={() => fields.push({)}>Add</Button>`

You should to write:

`<Button type="button" onClick={() => fields.insert(fields.length, fromJS({}))}>Add</Button>`

Maybe someone will be useful.

**Comment by erikras** [comment]
Make 100% sure that you are importing _everything_ in redux-form from `'redux-form/immutable'`. Not just the reducer, but all the components as well.

**Comment by KyKyPy3** [comment]
Yes, I always use 'redux-form/immutable'. But even with my workaround, after validate my data, I still can not add something to the list and get 'list.splice is not a function'.

**Comment by KyKyPy3** [comment]
Its quite simple to reproduce. I took you Field Arrays Example, change 
`import { Field, FieldArray, reduxForm } from 'redux-form'`
to 
`import { Field, FieldArray, reduxForm } from 'redux-form/immutable'`
in all places.

Delete validation and change:

`<button type="button" onClick={() => fields.push({})}>Add Member</button>`
to 
`<button type="button" onClick={() => fields.push(fromJS({}))}>Add Member</button>`

After that you should do the following steps:
* Add member and set some data in fields
* Click Save
* Try to add member

**Comment by Reanmachine** [comment]
I have just submitted a pull request #1716 that probably will address this issue. It has to do with how `Map.setIn` functions in immutable-js.

**Comment by KyKyPy3** [comment]
Reanmachine, I checked your changes but they don't work. When I change one parameter in the nested model, it overwritten all other parameters in nested model.

**Comment by Reanmachine** [comment]
Can you be more specific? At least specific enough that I could try and reproduce it in a unit test and patch anything wrong with it?

**Comment by joepjoosten** [comment]
Analysed the problem myself an hour ago, same conclusion as @Reanmachine. 

Problem is in setIn function in combination with immutable maps and list. Should be solved in redux-form. Maybe a feature request for immutable for handling maps and list setIn... 

I'm trying the pull request now.

**Comment by KyKyPy3** [comment]
This test fail with you fix:

```javascript
it('should add to an existing List2', function () {
    let initial = fromJS({
      a: {
        b: [
          {
            c: '123',
          }
        ]
      }
    })

    let result = setIn(initial, 'a.b[0].d', '12')

    let a = result.get('a')
    expect(a).toExist('a missing')

    let b = a.get('b')
    expect(b).toExist('b missing')

    let b0 = b.get(0)
    expect(b0).toExist()

    let b0c = b0.get('c')
    expect(b0c).toEqual('123')

    let b1 = b.get(1)
    expect(b1).toExist()

    let b1c = b1.get('c')
    expect(b1c).toEqual('12')
  });```

**Comment by KyKyPy3** [comment]
This test is failed with you fix:

```javascript
  it('should add to an existing List2', function () {
    let initial = fromJS({
      a: {
        b: [
          {
            c: '123',
          }
        ]
      }
    })

    let result = setIn(initial, 'a.b[0].d', '12')

    let a = result.get('a')
    expect(a).toExist('a missing')

    let b = a.get('b')
    expect(b).toExist('b missing')

    let b0 = b.get(0)
    expect(b0).toExist()

    let b0d = b0.get('d')
    expect(b0d).toEqual('12')

    let b0c = b0.get('c')
    expect(b0c).toEqual('123')

  });
```

**Comment by joepjoosten** [comment]
Yep, See it happening also, will look into it

**Comment by KyKyPy3** [comment]
Problem is solved if use mergeDeepWith instead of mergeDeep.

**Comment by Reanmachine** [comment]
I took a look at this during lunch, you are right! It was an oversight on my part, I've updated the PR and hopefully @erikras will see it soon for v6.0.3.
