### ISSUE TITLE
[v6] change and blur form props are not bound to dispatch

### ISSUE THREAD

**Issue by mindmelting** [erikras/redux-form#1696]
The `change` and `blur` props are not bound to dispatch as the docs suggest.

See here: https://github.com/erikras/redux-form/blob/master/src/reduxForm.js#L443

For now have to dispatch manually.

**Comment by erikras** [comment]
Hmm. Apparently when I fixed #1579 with #1588, I didn't bind them to `dispatch`.

Okay, will fix.

**Comment by erikras** [comment]
Fix published in [`v6.0.3`](https://github.com/erikras/redux-form/releases/tag/v6.0.3).
