### ISSUE TITLE
[v6] Can't initialize values from redux connect

### ISSUE THREAD

**Issue by vaclav-zeman** [erikras/redux-form#1697]
I've been struggling with initializing values from redux connect. I've got v 6.0.2 and have checked _Initialize From State_ section in docs many times. 

My (reduced) code: 
```
// ...
import { reduxForm, formValueSelector, Field } from 'redux-form';
import { connect } from 'react-redux';

@reduxForm({
  form: 'myForm'
})
@connect(state => ({
  initialValues: {
    name: 'john' // or something like state.user.name
  }
}))
export default class Investment extends Component {
  render() {
    return (<div>
       <Field name="name" component="radio" value="john" />
    </div>);
  }
}
```

This code above simply does not work - the initialize action doesn't even dispatch. However when I add the initialValues in the reduxForm decorator, it suddenly works (but state is not available course).

Code that works (only for static values):
```
@reduxForm({
  form: 'myForm',
  initialValues: {
   name: 'john'
  }
})
```

**Comment by vaclav-zeman** [comment]
Oh. I just found out that it works when I don't use the ES7 decorators. Instead of that I need to use the decorators like this:
```
Investment = reduxForm({ ... })
Investment = connect({ initialValues: ... })
export default Investment;
```

That's interesting. Is there any way to use the ES7 decors without breaking the functionality?

**Comment by erikras** [comment]
The order matters. The `@connect()` needs to be _outside_ the `@reduxForm()`.

```jsx
@connect(state => ({
  initialValues: {
    name: 'john' // or something like state.user.name
  }
}))
@reduxForm({
  form: 'myForm'
})
export default class Investment extends Component {
}
```
