### ISSUE TITLE
[v6.0.2] Doc potential improvements

### ISSUE THREAD

**Issue by bbenezech** [erikras/redux-form#1699]
Hello Erik,

``` javascript
function mapStateToProps(state, props) {
  return {
    formValues: getFormValues(props.form)(state),
  }
}

export default connect(mapStateToProps)(reduxForm({})(Login))
```

works

``` javascript
function mapStateToProps(state, props) {
  return {
    values: getFormValues(props.form)(state),
  }
}

export default connect(mapStateToProps)(reduxForm({})(Login))
```

does not work.
More precisely, fields update but the form itself never refreshes.

 `values` should never be used as a prop key, probably because it overrides ReduxForm internal state.

This contradicts: http://redux-form.com/6.0.2/docs/api/Selectors.md/

``` javascript
import {
  getFormValues,
  isDirty,
  isPristine,
  isValid,
  isInvalid
} from 'redux-form'

MyComponent = connect(
  state => ({
    values: getFormValues('myForm')(state),
    dirty: isDirty('myForm')(state),
    pristine: isPristine('myForm')(state),
    valid: isValid('myForm')(state),
    invalid: isInvalid('myForm')(state)
  })
)(MyComponent)
```

I didn't PR the doc because I am not sure if the behavior is intended.

Also I don't grasp the reason for apparent duplication of functionality between `getFormValues` and `formValueSelector`.

**Comment by danielrob** [comment]
I think avoiding props collisions on the published API falls under comes under being acquainted with react. Also, getFormValues states that it is a decorator which is standard language. However, I've added the PR above to clarify the nature of formValueSelector - that it is a "selector" api (aka selector factory in this case).

**Comment by gustavohenke** [comment]
@danielrob - shall we close this one? The docs are a lot better now after your change :)t

**Comment by danielrob** [comment]
Yep! Closing :).
