### ISSUE TITLE
Remove dependency on Redux and React Redux

### ISSUE THREAD

**Issue by gaearon** [erikras/redux-form#17]
I may be wrong, but I'm not convinced that this library needs to *depend* on Redux or React Redux.
In particular, I'm not convinced that `@reduxForm` should use `connect()` inside.

Why not let the user take care of connecting? Then they understand _how_ it binds to Redux, can customize the connection point (#4) by using `connect()` API, and it's intuitive _where_ the bound state will appear.

It's slightly more typing but I think the benefits outweigh the downsides.

Instead of

```js
import React, {Component, PropTypes} from 'react';
import reduxForm from 'redux-form';

@reduxForm('contacts', contactValidation)
export default class ContactForm extends Component {
```

you'd write

```js
import React, {Component, PropTypes} from 'react';
import reduxForm from 'redux-form';

@connect(state => ({ form: state.contacts })) // or wherever you mount your reducer
@reduxForm(contactValidation)
export default class ContactForm extends Component {
```

The component generated by `ContactForm` would just accept `dispatch` and `form` state as props. It wouldn't need to worry which version of React Redux you use (or even if you use alternative bindings), as long as you pass `dispatch` and `form`.

This also opens up for reducers that delegates forms by dynamic IDs. E.g. you may have `editItemForms` reducer that calls ReduxForm-generated reducer for `state.editItemForms[itemId]`. And you can connect it to a form component, given a userId, thanks to React Redux API letting you use props:

```js
import React, {Component, PropTypes} from 'react';
import reduxForm from 'redux-form';

@connect(
  state => ({
    forms: state.editItemForms
  }),
  null,
  ({ forms }, dispatchProps, parentProps) => ({
    ...parentProps,
    ...dispatchProps,
    form: forms[parentProps.itemId]
})
@reduxForm(contactValidation)
export default class ContactForm extends Component {
```

**Comment by erikras** [comment]
Your mind continues to amaze me.

**Comment by erikras** [comment]
I think the only thing you are wrong about is that (unfortunately) you've still got to pass the slice name, either as decorator parameter or prop, to reduxForm, because it has to include the slice name with each action.

```javascript
@connect(state => ({ form: state.contacts }))
@reduxForm('contacts', contactValidation)
export default class ContactForm extends Component {
```

Does that make sense? Am I wrong?

It's a real shame that the reducer and the connector _and_ the form HOC all need to know about the mount point.

**Comment by gaearon** [comment]
Yes, it's a problem. Need to think more.

**Comment by gaearon** [comment]
:+1:

**Comment by erikras** [comment]
Love a library that has no "dependencies" section of the package.json! :smiley:

**Comment by dzannotti** [comment]
I think this is a setback, having to declare connector and my form slice twice because of this it's redundant

**Comment by erikras** [comment]
I think that in the long run, the advantage of the decoupling is going to outweigh the burden of having to specify a string twice (could always be declared as a variable). Nothing stopping you from declaring your own `@reduxConnectForm(sliceName, validate)` decorator if it gets too annoying.

**Comment by erikras** [comment]
@gaearon, I thought more. :smile: 

> It's a real shame that the reducer and the connector and the form HOC all need to know about the mount point.

With [v0.3.0](https://github.com/erikras/redux-form/releases/tag/v0.3.0), I have eliminated two of of these three points of duplication, as the reducer no longer needs to know about the form name, as it lazily initializes on the first action, and the connector just needs to put `(state) => state.form`, no matter what the form name. So now, the only place where you have your `formName` is in the `reduxForm()` call. It _definitely_ would be be convenient to tuck the `@connect` call inside `@reduxForm`, as it's needed _every time_, but a purely functional library with no dependencies sure is a beautiful thing.

**Comment by gaearon** [comment]
How about having `reduxForm` *and* `connectReduxForm` as an opinionated convenience method?

**Comment by erikras** [comment]
@gaearon: Convince me as to the importance of not depending on, and being opinionated about, `react-redux`. Already, this library is using a react component, so it's not like it's going to be compatible with `angular-redux` or `hot-new-2018-framework-redux`. I don't feel _such_ a burden keeping this repo up to date when the `react-redux` api changes, since I'm actually dogfooding it. Is there value beyond the functional elegance of being dep-free?

**Comment by gaearon** [comment]
We've been breaking its API for a couple of times and adding/removing features so I wanted to avoid screwing you up by removing something you depend on for your API :-)

We hit 1.0 so it's fairly stable now. However I'm not sure how it would work with React Native because `react-redux` currently lets you choose `connect` from `react-redux/native` instead. By using it directly you'd remove RN support (not sure if anybody uses Redux Form on RN?)

When React 0.14 is out and [RN support won't require a separate entry point](https://github.com/rackt/react-redux/pull/71), this issue will be solved, as the same `connect()` will work for any platform.

**Comment by erikras** [comment]
Okay, thanks. I'm fine with leaving RN people out in the cold (or stuck on the current _totally awesome_ version) until React 0.14 comes out.

**Comment by gaearon** [comment]
If you bring this in, I'd still suggest keeping the internal distinction, even if not in the public API.

**Comment by erikras** [comment]
There could still be a `reduxFormNoConnect` option for the people who want to attach to the Redux store at somewhere other than `state.form`. Still mulling it over...

**Comment by gaearon** [comment]
I like `reduxForm()` and `connectReduxForm()` because it's a non-breaking change (people can migrate slowly) and explains exactly what happens. You can change the docs to use `connectReduxForm()`.
