### ISSUE TITLE
Async validation not being called on submit after supplying initialValues

### ISSUE THREAD

**Issue by ashwinvandijk** [erikras/redux-form#1700]
When I enter some details in my form for the first time, async validation is called and working as expected. I save these values to localstorage, so when the user refreshes the page, the values are still filled in. 

If the user enters a wrong value, async validation is called, and the field is marked as an error. However, if the user refreshed, the value is still there, but the validation is never ran so the user can submit the form just fine.

I set up the form like this:

    @reduxForm({
      form: 'userdataTop',
      validate,
      asyncValidate,
      asyncBlurFields: ['car_licenceplate', 'user_zipcode']
    })

and I fill the form by dispatching the `initialize` action creator from redux-form:

    dispatch(initialize('userdataTop', initialValues));

`initialValues` is an key-value object, with the key being the name of the field to be filled.

**Comment by ruiaraujo** [comment]
Look here http://redux-form.com/6.0.2/docs/api/ReduxForm.md/  at shouldAsyncValidate.

You can customise the behaviour to fit what you want.

**Comment by erikras** [comment]
If you are using `handleSubmit` correctly, it should run async validation before submitting.

**Comment by erikras** [comment]
@ruiaraujo nailed it.

**Comment by ashwinvandijk** [comment]
Found my problem, hadn't to do anything with this function. I have switch in my async validation, because I do not want to do unnecessary API calls. I only want to do the call for the field that's blurred. But when the trigger is submit, there isn't a blurredField, so none of the validations is called. Thanks for pointing me in that direction!
