### ISSUE TITLE
Field component always takes 100% width

### ISSUE THREAD

**Issue by mehrdaad** [erikras/redux-form#1707]
Im using redux-form v6.  
The problem is that the ``Field`` component always takes 100% of it's container. (all of it is inside a div)  
Is there any way to prevent this?  
for e.g making div a span or changing width?

**Comment by smirea** [comment]
the `Field` component returns its children and does not wrap with anything, so what you return from `component={...}` should be what you get

Example:

```
@reduxForm({form: 'test'})
class Test extends React.Component {
    render () {
         return <Field name='someProp' component={() => <div className='i-am-root'>Hello</div>}
    }
}
```

The above will convert to exactly the return value of `<div class="i-am-root">Hello</div>`

**Comment by mehrdaad** [comment]
Yeah styling was related to material-ui not redux-form. sorry for opening issue here.
