### ISSUE TITLE
Failed to render form in v3.0.0-beta1 due to the use of `array.includes()`

### ISSUE THREAD

**Issue by markuso** [erikras/redux-form#171]
The compiled babel code within the npm module that is using the new JS feature `array.includes()` is breaking redux-form functionality in my setup. The line in question seems to be here:
https://github.com/erikras/redux-form/blob/master/src/readFields.js#L35

There might be other instances though. I do use this in my own code just fine as I transpile using Babel stage 0, but I do not transpile npm modules of course.

**Comment by erikras** [comment]
Very strange. I was assuming `babel-loader` would transpile that down for me. I'm going to try and collect a few more bugs before another release if you don't mind. Thanks for catching that.

**Comment by markuso** [comment]
Yes I understand. Thanks for looking into it Erik.
