### ISSUE TITLE
Example showing how to modify application state

### ISSUE THREAD

**Issue by Gothbag** [erikras/redux-form#1710]
Greetings,
I can't wrap my head around how to modify the state, beyond the form's state, for instance adding the values of the form as an object to an array contained within the state. Could an example be added showing how to do that?

Thank you very much

**Comment by gustavohenke** [comment]
Nowadays, there are [some selectors](http://redux-form.com/6.4.3/docs/api/Selectors.md/) which could be helpful for you.
