### ISSUE TITLE
[v6.0.2] change prop: no dispatch bug

### ISSUE THREAD

**Issue by bbenezech** [erikras/redux-form#1719]
`change(field:String, value:any) : Function` does not have any effect (no action dispatched)
`autofill(field:String, value:any) : Function` works as intended

**Comment by andynoelker** [comment]
I am also getting this behavior (`autofill` works but `change` does not) when using `redux-form/immutable`.

**Comment by erikras** [comment]
Dupes #1696

**Comment by erikras** [comment]
Fix published in [`v6.0.3`](https://github.com/erikras/redux-form/releases/tag/v6.0.3).
