### ISSUE TITLE
Prop `formName` passed into form component is not accepted in v3.0.0-beta1

### ISSUE THREAD

**Issue by markuso** [erikras/redux-form#172]
Most of the forms in my project are using some kind of reusable form components where I pass in the `formName` along as a prop. It all worked perfectly before the upgrade. Now it is complaining that `form` prop is not provided from parent component.

Is this something that is a breaking change which we need to replace everywhere in our code? Is the prop `formName` no longer a valid option?

**Comment by erikras** [comment]
Sorry. `formName` got renamed to `form`. I'll update the migration guide.

Can you confirm that that fixes your issue?

**Comment by markuso** [comment]
Yes it does fix the issue when I rename. So you are saying that `formName` is now `form` and it takes a string? How about `formKey`, was not changed too?

**Comment by erikras** [comment]
Because React has a special meaning for the `key` prop. Thanks for confirming!
