### ISSUE TITLE
[v6.0.2]: Validate based upon `required` prop

### ISSUE THREAD

**Issue by dtothefp** [erikras/redux-form#1723]
It seems that the only way to conditionally validate a field in your validation function is to pass initial options into the validation function to know if a field is `required` or potentially access the current state of the form in the store (although it doesn't look like the store maintains any state of whether the field is "required" or not).

I've seen related issues https://github.com/erikras/redux-form/issues/1514 of trouble validating/removing validation from a field that is shown or hidden. Seems like if a `required` attribute were put on a field and this prop was somehow represented in the store of the props given to the validation function it might make things easier? A user hiding/showing a `required` attribute would be necessary anyway so the browser doesn't "yell" upon submit, so if there were some way to be aware of the `required` fields in a form this might be useful?

Is there something I'm missing and an easier way to do this?

**Comment by SpainTrain** [comment]
Would #917 provide sufficient capability to do this?

**Comment by danielrob** [comment]
Closing due to non response / many advances in this vein since this proposal was asked.
