### ISSUE TITLE
buttons without type attribute behave as "submit" buttons

### ISSUE THREAD

**Issue by Akronix** [erikras/redux-form#1724]
Hi!

I've discovered that if there's any button without the _type_ attribute defined, it by default behaves as a _submit_ buttons. 

To reproduce it, I've taken the examples/simpleForm sample and I've removed the type and onclick attributes from the "Clear Values" button, then, I've filled the form and pressed "Clear Values".
Instead of doing nothing it does the "submit" action.

Here's an animation showing it:
![anim](https://cloud.githubusercontent.com/assets/2631430/18316136/bdb2c9d6-7519-11e6-82c5-c048740ba1e6.gif)

The modified code for **SimpleForm.js** can be found [here](https://gist.github.com/Akronix/5ae69adfb1f8968d3ea1422dda7321a6)

Moreover, I've experienced buttons with an undefined _type_ attribute they do _submit_, even though if they had the _onClick_ attribute defined to do something else (like _reset_).

**Comment by Guria** [comment]
http://www.w3schools.com/tags/att_button_type.asp
https://makandracards.com/makandra/31495-be-careful-when-using-buttons-without-a-type-attribute

**Comment by Akronix** [comment]
I see...
Anyways, I was missing some type of warning somewhere :confused:
