### ISSUE TITLE
How to access type in validate function?

### ISSUE THREAD

**Issue by CoteViande** [erikras/redux-form#1725]
I would like to validate based on the type (or whether it is required or not) of each input rather than the values array. In order to avoid creating a validate function for each form.

Is that possible (without regex on the value name)?

(The implementation suggested here could probably also do: [#1207](https://github.com/erikras/redux-form/issues/1207) )

**Comment by SpainTrain** [comment]
Other related issue: #917 #1723

**Comment by CoteViande** [comment]
[#1207](https://github.com/erikras/redux-form/issues/1207) )
