### ISSUE TITLE
[v6.0.2] Proposal: make form's submitFailed prop accessible in Field

### ISSUE THREAD

**Issue by timhwang21** [erikras/redux-form#1726]
I'm not sure if there's a better way to accomplish this -- if so, please let me know!

In order to reduce boilerplate, I've written a higher order component to wrap my widgets for use with `redux-form`:

``` javascript
const reduxFormify = Component => props => {
  const {input, label, meta: {touched, error}, ...custom} = props;
  return (
    <div>
      <Component
        label={label}
        {...input}
        {...custom}
      />
      {touched && error && <span>{error}</span>}
    </div>
  );
};

export default reduxFormify;
```

For my particular form, I only want to show errors if something went wrong (not synchronous) so I'd like to replace my display logic with `{submitFailed && error && <span>{error}</span>}`. Right now, I am passing `submitFailed` from my form to every instance of `<Field>`, and it would be handy if this was done under the hood. I imagine this is a common use case and would be a fairly minor change.

If this change is acceptable I can make a PR. I'm fairly new to open source (and programming in general) so I'm still unfamiliar with the whole process. Thanks!

**Comment by gustavohenke** [comment]
`meta.submitFailed` added in v6.4.3!
Related: #2346, #567

**Comment by jedwards1211** [comment]
This is also helpful for automatically focusing a field that has an error after submit failed, thank you guys!
