### ISSUE TITLE
[v6] Preserving state in Fields nested in FieldArray

### ISSUE THREAD

**Issue by huan086** [erikras/redux-form#1727]
Some of my component passed to Field/Fields has React state. The Field/Fields, nested in FieldArray, are created for each element in the array. The Field/Fields can be reordered.

Following the FieldArray example by using index as the key fails for my case, as the React state always stay at the same index and did not get reordered.

To get state to move when reordered, I've used `formValueSelector` to select the ID of each element to use as the key.

```js
const selector = formValueSelector("syncValidation");
const EditContents = connect(function (state) {
    return {
        ids: selector(state, "contents").map(content => content.id)
    };
})(EditContentsBase);
```

This makes state follow the reordering for normal components. However, for Field/Fields, due to the array index change, the name/names passed into the Field/Fields changes. E.g. when index 0 and 1 are swapped, the Field at 0 moves to 1, thus the name changes from `contents[0]` to `contents[1]`. This in turn triggers https://github.com/erikras/redux-form/blob/master/src/Field.js#L33, which generates a **new class** from `connect`. React sees the new class and thus destroys the old `ConnectedComponent`, along with my component and its state.

My proposal is that the ConnectedComponent should be cached by reduxForm, instead of the Field/Fields itself. The form context would contain a `getOrAddConnectedComponent(name/names, component)` that the Field/Fields would use to cache or retrieve from cache.

For cache invalidation, reduxForm would keep track of which name/names are used during render, and destroy the ConnectedComponents that are not used.

**Why not cached by FieldArray?**
We will run into the problem again when we have FieldArray nested in FieldArray

**Update**
My proposal doesn't seem to work. State is still lost. We can't cache by name, since after `contents[0]` becomes `contents[1]` after swapping index 0 and 1.

A possibility is to construct ConnectedField once, and have mapStateToProps dynamically select from state given ownProps.name https://github.com/reactjs/react-redux/issues/265#issuecomment-174344345

**Comment by skolmer** [comment]
Got the same issue with Field components inside of a FieldArray. If I reorder items in the FieldArray the nested Field components disappear. After submitting the Form the reordered List gets rendered as expected.

**Comment by Aaronius** [comment]
Have either of you found workarounds for this?

**Comment by huan086** [comment]
Yup, look at my pull request

**Comment by skolmer** [comment]
@erikras unfortunately the state of nested field is still being destroyed in 6.0.4. This can be reproduced if you use a Field component inside of a FieldArray component and use fields.move() to reorder your items. 

I thinks this also destroys focus of the input elements. If you tab through Fields inside a FieldArray you will see that the focus gets lost.

**Comment by huan086** [comment]
@skolmer Did you assign each row with a unique key instead of using the index? You need to use fromValueSelector. Look at my first post.

**Comment by skolmer** [comment]
@huan086 Thanks for your help! Would be nice to have a solution that works without setting unique keys manually. In my case I have a list without unique identifiers. I could generate some id's but this feels more like a workaround than a solution.
