### ISSUE TITLE
404 page error on http://redux-form.com/6.0.2/syncValidation

### ISSUE THREAD

**Issue by jinxac** [erikras/redux-form#1729]
This is not a major issue, but found this while going through documentation http://redux-form.com/6.0.2/syncValidation throws 404 error.

**Comment by huan086** [comment]
Which page did you get that URL from? The correct URL should be http://redux-form.com/6.0.2/examples/syncValidation/

**Comment by jinxac** [comment]
Yes.. on http://redux-form.com/6.0.2/examples/simple/  if you click for synchronous validations it lands here
