### ISSUE TITLE
No longer can use `ref` prop on sub-forms in v3.0.0-beta1

### ISSUE THREAD

**Issue by markuso** [erikras/redux-form#173]
We have many sub-forms that are initiated with `formKey` and we assign `ref` to them so we can get a reference the DOM element to scroll it into view and such. This is now broken after upgrade with the console message below:

`Warning: Stateless function components cannot be given refs (See ref "562e5b712aaa6d9d77ac242a" in ConnectedForm created by SectionItemsList). Attempts to access this ref will fail.`

Is there a solution to this and do you know if it is one of the breaking changes?

I do like the automatic destroy of form data on component unmount. It allowed us to remove all of the manual empty initialization we were doing to clear the data. Thank you!

**Comment by erikras** [comment]
I'm slowly coming to the conclusion that the new functional stateless component structure is only useful for the smallest, dumbest components. Which is unfortunate, since it's so delightfully terse. I might have to change some of the redux-form wrapping components into proper `Component` classes. In the meantime, it seems like you could throw your ref onto a `<div>` around your form component.

**Comment by markuso** [comment]
I have to agree with you on the stateless components. I was excited when I first saw the idea, but after analyzing the components I write it seemed like, as you said, for "the dumbest components" only. I can think of a few in my current project but not as many as the React team indicated where most components will be able to use stateless functions. I rarely use `setState` but I have state in redux and redux-form in most areas, and they don't fit the bill apparently.

Thanks Erik. I look forward to your beta2 release, and in the meantime I will report any other issues I may find until then.

**Comment by markuso** [comment]
Fantastic. All forms within our app are back to proper functionality and error free with your v3.0.0-beta-2 release. Thank you a million.

**Comment by erikras** [comment]
Awesome! That's a smooth migration!

**Comment by erikras** [comment]
Ha, so I just integrated v3 into a project that is still on react 0.13. It's cool how redux-form doesn't have a direct runtime dependency on react. Also I suspect that it would not have worked before this fix to remove the stateless syntax. Yet another reason to avoid stateless syntax components.

**Comment by markuso** [comment]
Totally! This is great news given that some folks are still on React 0.13. That is what I love about redux-form with very minimal dependencies. I bet it could one day be independent of redux and can work with any flux implementation. But I do prefer redux over all the others at this time and thank you for creating it.

**Comment by gaearon** [comment]
I wouldn't be so quick to dismiss this as a fault of functional components. 

>In the meantime, it seems like you could throw your ref onto a <div> around your form component.

That's the proper way to do it.

Avoid using refs on composite components.

In the worst case, you can wrap a custom component in your own component where you call `findDOMNode(this)`. But wrapping in a `div` is easier and doesn't break encapsulation.

**Comment by danehansen** [comment]
I've got a custom component inside a redux-form, and can't reach it using refs. i'm not looking for the actual dom node, but the react component, so i can call a method on it. how can i do this the least sloppy way possible?

**Comment by erikras** [comment]
@danehansen Calling methods on child components is generally an antipattern in react/redux-land. If you think that you need to do that, you should seriously reconsider your design.

However...

You could – and this is disgusting – pass a callback prop down.

```js
class Page extends Component {
  render() {
    return <MyForm sendMethod={method => this.doStuff = method}/>;
  }
}

@reduxForm({ /* config and stuff */ })
class MyForm extends Component {
  componentWillMount() {
    this.props.sendMethod(this.doStuff.bind(this));
  }

  doStuff() {
    // method you want to call
  }

  render() {
    return <form>
      // inputs and stuff
      </form>;
  }
}
```
Then, from anywhere in `Page`, you could call `this.doStuff()` and it would call the method in your wrapped form. As I said, it's disgusting, but javascript first order functions allow all kinds of abuse like this.

**Comment by danehansen** [comment]
Yea, understandable that its an antipattern, but just trying to trigger a quick success or fail animation contained in a form based on the results of the submit, not anything that concerns any other portion of the app. It seems like there should be an easier way to do this. Thanks.

**Comment by 2easy** [comment]
Hi, is there a way to stop automatic destroy action on unmount? I've got specific usecase, where user can preview his cart in a modal (using react-bootstrap) like this:
`<Modal show={showCart} onHide={toggleShowCart}><CartFrom /><Modal>`
But when modal hides, `redux-form/DESTROY` gets triggered and user looses all items.
