### ISSUE TITLE
change needs to be dispatched??

### ISSUE THREAD

**Issue by gilesbradshaw** [erikras/redux-form#1730]
In the docs you say 

> change(field:String, value:any) : Function

> Changes the value of a field in the Redux store. This is a bound action creator, so it returns nothing.

however I am finding that this returns an action which I then need to dispatch

**Comment by gabeweaver** [comment]
https://github.com/erikras/redux-form/issues/1696

**Comment by erikras** [comment]
Fix published in [`v6.0.3`](https://github.com/erikras/redux-form/releases/tag/v6.0.3).
