### ISSUE TITLE
[v6.0.2] Input blurs on first keypress

### ISSUE THREAD

**Issue by bobbypriambodo** [erikras/redux-form#1731]
I just upgraded from v4.2.2 to v6.0.2 (so late, I know), and everything works except I'm having a weird bug where my input blurs on first keypress. Specifically:

1. I open a page with a form in it
2. I focus on an input by clicking
3. I enter a character, the character shows up, but the input blurs!
4. I have to click on it again, and now it works normally

I also notice that this happens for each form. Suppose I have three reduxForm-decorated forms on one page, all three suffers from the same bug (for each of the form, the first keypress blurs the input).

I don't see this bug happen on the examples so the problem is most probably within my code during migration to v6.

I wrap a `Field` component with my own component for easier abstraction. Here is a component:

```javascript
import React, { PropTypes } from 'react';
import { Field } from 'redux-form';

const TextInput = ({ name, placeholder, label, helpText }) => {
  const renderField = (field) => (
    <div className="form-text">
      <div className="form-text__title">
        <label htmlFor={name}>{label}</label>
      </div>
      <div className="form-text__input">
        <input type="text" placeholder={placeholder} {...field.input} />
      </div>
      {helpText &&
        <h6 className="form-text__description">{helpText}</h6>
      }
    </div>
  );

  return <Field name={name} component={renderField} />;
};

TextInput.propTypes = {
  name: PropTypes.string.isRequired,
  placeholder: PropTypes.string.isRequired,
  label: PropTypes.string.isRequired,
  helpText: PropTypes.string,
};

export default TextInput;
```

Then I used the `TextInput` component on my form:

```javascript
import React, { PropTypes } from 'react';
import { reduxForm } from 'redux-form';

import { TextInput, SubmitButtons } from './components/form';

import { saveDetail } from './profileReducer';

const saveHandler = (values, dispatch) =>
  dispatch(saveDetail(values));

const DetailForm = ({ handleSubmit }) => (
  <form onSubmit={handleSubmit(saveHandler)}>
    <TextInput
      label="First Name"
      name="firstName"
      placeholder="Alex"
    />
    <SubmitButtons />
  </form>
);

DetailForm.propTypes = {
  handleSubmit: PropTypes.func,
};

export default reduxForm({
  form: 'detail',
})(DetailForm);
```

Did I mess up somewhere? I'm using React 15.3.1.

**Comment by kerlends** [comment]
You can't define your input function within the render. See: http://redux-form.com/6.0.2/docs/api/Field.md/#usage

**Comment by bobbypriambodo** [comment]
Oh, you are indeed right, @kerlends. I must have missed that.

Basically I was trying to avoid changing the API of my TextInput component, and this is the least change of it that I could manage (I used to pass the `field` to the TextInput on v4, now I changed it to pass `name` instead).

The way I could think of is returning only the `renderField` function and use it like this:

```javascript
  // in my form
  ...
  <Field
    name="firstName"
    component={
      TextInput({
        label: 'First Name',
        ...
      })
    }
  />
  ...
```

But it looks somewhat ugly... I could change the TextInput name to a normal-ish function name, possibly `getTextInputComponent` or something, but still.

Is there a way to achieve this?  Or is my approach above the recommended way? Thanks, by the way.

**Comment by bobbypriambodo** [comment]
Oh, wait, I just realized that I can just use the 3rd approach of using the default string, like this:

```javascript
const TextInput = ({ name, placeholder, label, helpText }) => (
  <div className="form-text">
    <div className="form-text__title">
      <label htmlFor={name}>{label}</label>
    </div>
    <div className="form-text__input">
      <Field name={name} component="input" type="text" placeholder={placeholder} />
    </div>
    {helpText &&
      <h6 className="form-text__description">{helpText}</h6>
    }
  </div>
);
```

Will try this tommorow and see if this helps.

**Comment by kerlends** [comment]
Any additional props passed to `Field` will be accessible by the `renderField` component like such:

```
const renderField = ({ input, placeholder, label, helpText }) => (    
  <div>  
    <label>{label}</label>  
    <input
      type='text'
      placeholder={placeholder}
      {...input}
    />  
  </div>  
);  
```

And then in your form, use it with:

```
<Field
  name='firstName'
  label='First name'
  placeholder='First name'
  helptext='...'
/>
```

**Comment by bobbypriambodo** [comment]
@kerlends I see, thanks for that. I'll try both yours and mine and see which fits my codebase better :) Cheers!

**Comment by bobbypriambodo** [comment]
I ended up going with combinations of the above two solutions. Went with mine for simple ones like the provided TextInput, and used @kerlends approach for some other complex input components. The bug has now gone away, therefore I'm closing this issue. Thanks for the help!

**Comment by shikelong** [comment]
Thank you!
