### ISSUE TITLE
call handleSubmit from onChange method

### ISSUE THREAD

**Issue by Attimo91** [erikras/redux-form#1732]
I wrote simple form that has select input and i want to submit this form when the value of this input change but it seems impossible to do. I have seen some solutions but they no longer work. In my opinion that functionality should exist... Is there a simple way to achive this ?

**Comment by osmanov** [comment]
it works for me v6.3.2
```javascript
...
  render () {
    const { handleSubmit } = this.props
    return (
      <form onSubmit={handleSubmit}>
        <Field name="favoriteColor"  component={ props =>{
          const {input} = props
            return <select {...input} onChange={event => {
              input.onChange(event)
              setTimeout(handleSubmit)
            }}>
             <option value="green">green</option>
             <option value="blue">blue</option>
             <option value="orange">orange</option>
          </select>
        }}/>
      </form>
    )
  } 

```

**Comment by danielrob** [comment]
Closing given that redux-form provides the developer with access to everything they need to do this  by hooking into the onSubmit function. If it's thought there should be some magic to make this more user friendly please request a re-open with a proposal.
