### ISSUE TITLE
Change reducer's mount field to some internal value

### ISSUE THREAD

**Issue by Bloomca** [erikras/redux-form#1738]
Hello!

We have to mount reducer for all forms to the field `form`, which doesn't make any sense for me – why we do it at all? Think about ES2015 – they created the whole new primitive type for it, `symbol`, so I think that this field should be imported from the library itself too.
So, with this approach we will avoid this [ugly](http://redux-form.com/6.0.2/docs/api/Reducer.md/) approach with additional function to all redux forms.

So the mount will be:

``` javascript
const { combineReducers } from 'redux';
const { REDUCER_FIELD, formReducer } from 'redux-form';

combineReducers({
  ...allReducers,
  [REDUCER_FIELD: formReducer
});
```

Or just one function, which will just do object assigning of two objects:

``` javascript
const { combineReducers } from 'redux';
const { augmentReducer } from 'redux-form';

combineReducers(augmentReducer(allReducers));

```

What are your thoughts about it?

**Comment by wmertens** [comment]
The redux store should be JSON-serializalble at all times, so Symbol is not
an option I think

**Comment by Bloomca** [comment]
Well, that's a good point, but the point here is to use some internal value, which can be any creepy string – to avoid all possible overlaps with existing reducer fields.

**Comment by wmertens** [comment]
it would have to be consistent across invocations… Using `form` has not
been a problem so far, and you can change it too, with getFormState

**Comment by Bloomca** [comment]
All invocations should be done through selectors – so user shouldn't know this key at all!
It should be like a black box.

You can change it, yes, but it is painful, and you have to create another component to wrap all forms in it.

**Comment by wmertens** [comment]
How would the selectors know the key? It still needs to be available
somewhere…

**Comment by Bloomca** [comment]
Selectors will be exported through the library, so the key will be stored inside library too. The concept is super easy, it is just a `$$__REDUX_FORM_REDUCER_KEY` – the name which won't be taken.

The key goal is to abstract library from getting values by hand from the redux state, only through selectors.

**Comment by wmertens** [comment]
Ok, so redux-form could have a `.reduxKey(newKey)` function that sets the internal key, and keep it as a singleton. You'd still have to set it in your root reducer manually. That should be easy, right @erikras?

**Comment by gustavohenke** [comment]
This issue saw no more comments in a good while. I'm closing it for now.
