### ISSUE TITLE
Change property in form component

### ISSUE THREAD

**Issue by aelyseev** [erikras/redux-form#1746]
The description of the change property from documentation:
`change(field:String, value:any) : Function`
_Changes the value of a field in the Redux store. This is a bound action creator, so it returns nothing._, [here](http://redux-form.com/6.0.2/docs/api/Props.md/)

But in fact this is an action creator without binding:
`const boundChange = (field, value) => change(initialProps.form, field, value, !!initialProps.touchOnChange, !!initialProps.persistentSubmitErrors)`

**Comment by jdreesen** [comment]
See https://github.com/erikras/redux-form/issues/1696

**Comment by aelyseev** [comment]
@jdreesen thank you.

**Comment by erikras** [comment]
Fix published in [`v6.0.3`](https://github.com/erikras/redux-form/releases/tag/v6.0.3).
