### ISSUE TITLE
[6.0.2] reduxForm.js:340 Uncaught TypeError: name.replace is not a function

### ISSUE THREAD

**Issue by Lumiahma** [erikras/redux-form#1747]
Hi,

I've been using redux-form on my project for building some fairly large forms (100+ fields). Everything has been working well so far, but I've been running into type errors with the async validation:

> reduxForm.js:340 Uncaught TypeError: name.replace is not a function

My current test function looks like this:

`const asyncValidate = (values, props) => {`

```
return sleep(100) // simulate server latency
    .then(() =>
    {
        if(_.get(values, part7.field1, -1) <= 0 ){

            throw {
                'part7.field1': 'Error: field value too small, must be at least 1'
            };
        }
     }
```

...
`)} 
export default asyncValidate`

Line 340 (actually 294) in redux-form. js looks like this:

`var isBlurredField = !submitting && (!asyncBlurFields || ~asyncBlurFields.indexOf(name.replace(/\[[0-9]+\]/g, '[]')));`

Any help would be appreciated.

**Comment by gustavohenke** [comment]
Hi @Lumiahma, do you still have this problem? If you don't, what was the resolution?

I'm curious because I know async validation used to have a few problems back in the first releases of the 6.x.x versions.
