### ISSUE TITLE
Anyway to retrieve a field's meta object externally?

### ISSUE THREAD

**Issue by dkwin** [erikras/redux-form#1748]
Hi guys

I was wondering if there is any way to access a Field's meta object externally?  I actually want to make a pop up editor for the fields in my form so I want to access the field meta/input objects externally.

For example,

`let fieldReference = <Field name="someName" component={SomeComponent}/>`

after the field has been rendered and user enters input, I'd want to access the meta object.
`console.log (fieldReference.meta.error);`

It seems that fieldReference does not have the meta object readily available.   I'm well aware that I can access the meta object within the SomeComponent perfectly fine but I was wondering if I could access the meta object externally via a reference to the field.

**Comment by huan086** [comment]
You can have multiple `Field` with the same name. Whenever you need the `input`, or `meta`, create a `Field`

**Comment by dkwin** [comment]
@huan086 

Thanks for the reply, however, could you give an example?

**Comment by huan086** [comment]
```html
<Fields names={["someName","someName1","someName2"]} component={ComponentForShowingAllErrors}/>

<Field name="someName" component={ComponentForGettingInput}/>
```

only requirement is that the fields are inside reduxForm, which isn't problem, since I wrap the entire page in reduxForm

```html
<Provider store={store}>
    <TheReduxForm {...this.props} />
</Provider>
```

**Comment by erin-doyle** [comment]
This does seem to work though it sort of feels a little more like a hack than an official solution.  I find the resulting code a little confusing having multiple fields with the same names in the same form doing different things.

**Comment by danielrob** [comment]
I've duplicated this discussion in a more broad way at #3289, I will close this as a duplicate / inactive usage question.
