### ISSUE TITLE
Initial values from container component

### ISSUE THREAD

**Issue by gilesbutler** [erikras/redux-form#1749]
Hey,

I have a container component that passes through my initial values as props using mapStateToProps.

```
const mapStateToProps = (state) => (
  {
    initialValues: {
      applicantAgent: 'female',
      applicantPhone: '123123',
    },
  }
);

const mapDispatchToProps ...

const FormContainer = connect(
  mapStateToProps,
  mapDispatchToProps
)(Form);

export default FormContainer;
```

I can see in the Redux dev tools that the initial values are being picked up by Redux Form:
![screen shot 2016-09-13 at 16 20 20](https://cloud.githubusercontent.com/assets/790734/18463503/06bf01f4-79ce-11e6-8add-d0ec8dc940dc.png)

But the actual form fields are empty. If I set the exact same initial values on the reduxForm decorator it works correctly:

```
export default reduxForm({
  form: 'TestForm',                 // <------ same form name
  destroyOnUnmount: false,     // <------ preserve form data
  enableReinitialize: true,
  keepDirtyOnReinitialize: true,
  validate,                    // <------ only validates the fields on this page
  initialValues: {
     applicantAgent: 'female',
     applicantPhone: '123123',
  },
})(Form);
```

I've tried with and without `enableReinitialize` & `keepDirtyOnReinitialize` but they don't make any difference.

I'm using Redux Form 6.0.2 and redux-form/immutable as we are using Immutable if that makes a difference.

I just can't seem to get this working, is it a bug or am I missing something?

Thanks

**Comment by gilesbutler** [comment]
Sorry, I've only just seen this issue as well https://github.com/erikras/redux-form/issues/1744 - seems to be the same thing

**Comment by gilesbutler** [comment]
Work around: https://github.com/erikras/redux-form/issues/1399#issuecomment-255253588

**Comment by xierui0423** [comment]
@gilesbutler Propably you are not using form reducer from redux-form/immutable

**Comment by gilesbutler** [comment]
@xierui0423 I was using the reducer from redux-form/immutable. Unfortunately I'm not working on this project anymore and don't have access to the code so will close.
