### ISSUE TITLE
The property `checked` is not provided when `value` is a boolean in v3.0.0-beta-2

### ISSUE THREAD

**Issue by markuso** [erikras/redux-form#175]
The documentation says that the property `checked` of some field will be exported along side the `value` property when it is a boolean value. This is not happening in the latest version anymore.

**Is this by design or is it missing?** I do understand that it is only supposed to be available for booleans. Checkboxes and material design switches are what is effected now. I did change them all and manually assigned `checked={fields.myfield.value}` to get around it in the latest beta version for now.

On the other hand, the properties `defaultChecked` and `defaultValue` are correctly provided but they are not documented. It may be useful for others to know this details in the docs.

**Comment by erikras** [comment]
That's a mistake on my part.

Excellent feedback, @markuso!

**Comment by markuso** [comment]
Given that redux-form went through an entire rewrite, these are minor overlooks. No big deal. By the time you get to full v3.0.0 it will be sparkly :smiley: I am glad as was able to report some of this to be of value. Thanks for the awesome work Erik.

**Comment by erikras** [comment]
Fixed by @kuy. Released in v3.0.0-beta-4.
