### ISSUE TITLE
v6 vs v5: mapStateToProps and mapDispatchToProps

### ISSUE THREAD

**Issue by jroysdon** [erikras/redux-form#1753]
**mapStateToProps and mapDispatchToProps**

> In v5, the reduxForm() decorator allowed these parameters to be given and it passed them along to react-redux's connect() API.
> 
> v6 no longer does this. You will need to separately decorate your form component with connect() yourself if you need to access other values in the Redux store or bind action creators to dispatch.

I admit, I am new and was just getting in to Redux forms in V5, going through a tutorial. I wanted to do more and started reading the V6 and it broke much of what I had done. Not a big deal yet as I said, I am new and trying to make a boilerplate/framework for other applications. 

My question is where can I find information/examples of how to connect/bind and decorate?  I have a login form that was working under V5 using redux. I wanted to add more functionality like date pickers and radio button groups and the documentation for V5 appears to be gone (in favor of V6).

Thanks,

Jim

**Comment by clayne11** [comment]
You can find the `react-redux` bindings here https://github.com/reactjs/react-redux.
