### ISSUE TITLE
Rendering different types of fields in a FieldArray

### ISSUE THREAD

**Issue by mikeengland** [erikras/redux-form#1754]
Hi,

First off, great job with this module, it works very well and has great documentation.

One question I have involves adding different types of fields into a field array. For example, I want to render a list of fields for a category, however, the field array can contain a combination of different field types/components.

For example, a user clicks on the add button of a field array. This add button is a dropdown and allows the user to select a category type, e.g. type 1, type 2, type 3 or type 4. Ideally, I would be able to pass some extra information when using the onClick fields.push() e.g. fields.push(type: 'type1'}). Then, when I render the field array using fields.map I would like to get the type and then, based on this render a different component depending on the type.

Is there an easy way of doing this as I can't find a way of retrieving this information when mapping through the fields.

Thanks in advance!

Modified field array example: 

``` javascript


// ... some function to return different component fields depending on the hobby type
const getHobbyField = ({type}) ....

const renderHobbies = ({ fields, meta: { error } }) => (
  <ul>
    <li>
      <button type="button" onClick={() => fields.push({type: 'football'})}>Add Hobby</button>
    </li>
    {fields.map((hobby, index) =>
      <li key={index}>
        <button
          type="button"
          title="Remove Hobby"
          onClick={() => fields.remove(index)}/>
        {getHobbyField(hobby.type}} // returns a football component/field when the add hobby button is clicked
      </li>
    )}
    {error && <li className="error">{error}</li>}
  </ul>
)
```

**Comment by huan086** [comment]
I think the new `fields.get(index)` does what you need

**Comment by mikeengland** [comment]
Interesting, I'll take a look. In the meantime I used the push method to add a key to the field in redux form and then rendered a field component that rendered a component containing logic on what to display.
