### ISSUE TITLE
Where did focus go? 6.0.0-rc.4 to 6.0.2

### ISSUE THREAD

**Issue by mattkrick** [erikras/redux-form#1756]
upgrading from rc4 to 6.0.2 and I noticed that `focus` is no longer being passed through. I didn't see this change mentioned in the release notes. Should this still exist?

**Comment by jordanh** [comment]
Here's a compare between tags, I'm looking 👀  if I can see anything: https://github.com/erikras/redux-form/compare/f9b75cf...9186bd3

**Comment by gustavohenke** [comment]
The prop of the decorated form? It's there nowadays
