### ISSUE TITLE
FieldArray - initial fields and values

### ISSUE THREAD

**Issue by tomasztomys** [erikras/redux-form#1761]
How can I add initial fields with initial values in FieldArray?

**Comment by skvale** [comment]
you can set a value with `initialValues ` in `reduxForm`
going off of the example in the docs: [fieldArrays](http://redux-form.com/6.0.5/examples/fieldArrays/)
```javascript
export default reduxForm({
  form: 'fieldArrays',
  validate,
  initialValues: {
    members: [{firstName: 'john', lastName: 'Doe', hobbies: []}]
  }
})(FieldArraysForm)
```

**Comment by superfunkminister** [comment]
What's the best way to programatically initialise a FieldArray within a FieldArray? For example, for every member added, I always want the hobbies array populated by at least one hobby, so that the user doesn't have to click "Add a hobby" - the field is already visible.

**Comment by skvale** [comment]
@superfunkminister 
The first button in `renderMembers` looks like 
```javascript
<button type="button" onClick={() => fields.push({})}>Add Member</button>
```
try to use an array in the object you are pushing to `members`, something like `{hobbies: ['coding']}` i.e.
```javascript
<button type="button" onClick={() => fields.push({hobbies: ['coding']})}>Add Member</button>
```

**Comment by superfunkminister** [comment]
So converting the component to be class based and adding the below seems to work!

```js
componentWillMount() {
  this.props.fields.push();
}
```

**Comment by nothingrandom** [comment]
@superfunkminister 

Your solution leads to an "TypeError: Cannot read property 'length' of undefined" error for me. If I remove the length call altogether, I get a "TypeError: Cannot read property 'push' of undefined".

Any suggestions to what will be causing these two issues?

**Comment by nothingrandom** [comment]
Okay, back again with a less hacky solution.

```
componentDidMount() {
  this.initializeForm();
}

initializeForm() {
  const values = [{}];
  
  this.props.initialize({ workexperiences: values });
}

renderForm({fields}) {
  return (
    <div>
      {fields.map((members, index) =>
        <div className="form">
          <!-- insert your form here -->
        </div>
      )}
    </div>
  );
}

render() {
  return (
    <div>
      <FieldArray name="members
        component={this.renderForm}
      />
    </div>
  );
}
```

**Comment by ShoaibKhazer** [comment]
@Nuruddinjr This is how I am doing it `componentDidUpdate(prevProps) { 
        if (prevProps.data !== this.props.data) {
            const { data } = this.props;
            const initialValues = { questions : data}
            this.props.initialize(initialValues)
        }
    }`
