### ISSUE TITLE
Document arguments given to onSubmit handler?

### ISSUE THREAD

**Issue by peteruithoven** [erikras/redux-form#1763]
I was having problems figuring out how to use props when submitting forms, in the end, by going to [the source code](https://github.com/erikras/redux-form/blob/master/src/handleSubmit.js#L21) I figured out that since [v5.3.3](https://github.com/erikras/redux-form/releases/tag/v5.3.3) the onSubmit handler gets the props as argument. Super usefull! But not documented? 
Maybe we could list the arguments in the following docs section? 
http://redux-form.com/6.0.2/docs/api/ReduxForm.md/#-onsubmit-function-optional-

**Comment by x2764tech** [comment]
There are some details here http://redux-form.com/6.0.2/docs/api/Props.md/#-handlesubmit-eventorsubmit-function- too

**Comment by pierreio** [comment]
It actually gets `(values, dispatch, props)`. I was interested myself in dispatch.

**Comment by gustavohenke** [comment]
This was documented some time ago!
