### ISSUE TITLE
[v6] how to show validation errors for select field

### ISSUE THREAD

**Issue by raj-adroit** [erikras/redux-form#1764]
In v6 we can show the **input validation error** by creating custom **renderField**, Anywhere i unable to find the same example for **select** field. also i don't to do that..

Please share the example code, if any one have it.. else please help me to achieve that...

related stackoverflow question: http://stackoverflow.com/questions/39493993/redux-form-v6-show-validation-error-for-select-field

Thank you

**Comment by raj-adroit** [comment]
I got the answer in stackoverflow http://stackoverflow.com/questions/39493993/redux-form-v6-show-validation-error-for-select-field


```
const renderSelectField = ({ input, label, type, meta: { touched, error }, children }) => (
  <div>
    <label>{label}</label>
    <div>
      <select {...input}>
        {children}
      </select>
      {touched && error && <span>{error}</span>}
    </div>
  </div>
)
```
Consume it in the form:

```
<Field name="username" type="text" component={renderField} label="Username">
  { mySelectOptions.map(option => <option value={option.value}>{option.text}</option>) }
</Field>
```

**Comment by truongluu** [comment]
Thanks you very much
