### ISSUE TITLE
Bundling validation rules with fields

### ISSUE THREAD

**Issue by wlingke** [erikras/redux-form#1765]
I'm writing a few custom field types that I'd like to package into modules for reusability. However, I have been unable to think of the right way to bundle the validation rules with the fields. It seems that validation rules are only included at a form level. Is there a way to include validation rules at a field level or am I missing something?

If not, should this feature be considered for a future release?

**Comment by erikras** [comment]
It has been considered and will probably make a future release.

In the meantime, it seems like you could export both your custom component and a validation function.

```js
import { CustomField, validateCustomField } from 'myCustomField'

const validate = values => {
  const errors = {}
  errors.myCustomValue = validateCustomField(values.myCustomValue)
  return errors
}
```

That would let you keep those concerns modularized for now.

**Comment by wlingke** [comment]
Okay cool. thanks!

**Comment by SpainTrain** [comment]
related (dupe?) #917 #1207

**Comment by gustavohenke** [comment]
v6.3.0 finally included Field level validation 😎
