### ISSUE TITLE
[6.0.3] dist/redux-form.js is missing

### ISSUE THREAD

**Issue by skolmer** [erikras/redux-form#1769]
In 6.0.3 the dist directory does only contain a redux-form.min.js not redux-form.js this leads to: Module not found: Error: Cannot resolve module 'redux-form'

https://unpkg.com/redux-form@6.0.3/dist/redux-form.js
https://unpkg.com/redux-form@6.0.3/dist/redux-form.min.js

**Comment by erikras** [comment]
What the...? I wonder what broke that?

**Comment by erikras** [comment]
I may have upgraded npm since the previous release.

**Comment by bbenezech** [comment]
/lib is missing a lot of files too.
Only /es looks unimpacted

**Comment by erikras** [comment]
Republishing....

**Comment by skolmer** [comment]
Looks ok now, thanks!
https://unpkg.com/redux-form@6.0.4/dist/redux-form.js
