### ISSUE TITLE
[v6.0.4] double dispatch on all field changes

### ISSUE THREAD

**Issue by bbenezech** [erikras/redux-form#1771]
Can confirm it did not happen with 6.0.2 (checked twice)

**Comment by bbenezech** [comment]
Can someone confirm/infirm? It looks like an environmental bug, but I can't figure why it would not happen on 6.0.2. :(

**Comment by erikras** [comment]
Oh. I think I know.

**Comment by erikras** [comment]
Fixed in [`v6.0.5`](https://github.com/erikras/redux-form/releases/tag/v6.0.5).

**Comment by bbenezech** [comment]
Thx 💃
