### ISSUE TITLE
[6.0.x] reset() is not resetting to last pristine state 

### ISSUE THREAD

**Issue by skolmer** [erikras/redux-form#1776]
If I load a form with `initialValues`, change some input values, save the form, edit again and then `reset()` the form, it resets to the `initialValues` of the first load instead of the updated values provided via `mapStateToProps`.
If I use `enableReinitialize` the `reset()` is working as expected. In my opinion `reset()` should reset the form to the last `pristine` state and not to the `initialValues` provided when the form was initialized.

**Comment by Lube** [comment]
If its called twice, it will also attempt to submit, this sounds like a bug.

**Comment by ncphillips** [comment]
@skolmer I'm going to try and tackle this. This exact issue has been really bothering me with #1902 

I've written a failing test for this, which I have posted in that above issue, but I'm having a hard time figuring out where it should be fixed.
