### ISSUE TITLE
Suggestion: warnings (non-invalidating errors)

### ISSUE THREAD

**Issue by timhwang21** [erikras/redux-form#1779]
Formally requesting this feature suggested several weeks ago (#1649).

My form involves budgets, and I'd like to warn users who input values that are valid, but questionable (e.g. value over daily allowed budget).

Because I need this feature, I've written this functionality in a fork: [Link to diff](https://github.com/timhwang21/redux-form/commit/fe008cc14d868e024b64c27e745afeafd5ba72da).

I saw in the contributing guidelines that non-trivial features should be vetted as issues first. I didn't want to just create a pull request, as I'm still not very experienced with this whole open source thing.

Thanks!

**Comment by erikras** [comment]
Added warnings in [`v6.1.0`](https://github.com/erikras/redux-form/releases/tag/v6.1.0).
