### ISSUE TITLE
Anyone using this lib with Google maps API ? 

### ISSUE THREAD

**Issue by jasan-s** [erikras/redux-form#1782]
I'm trying to integrate autocomplete on using redux-form field. Can't seem to figure out how to do it. anyone implement this successfully ?  there also react-google-maps, has anyone maybe integrated redux-form with that?

**Comment by stunaz** [comment]
Been building google-autocomplete with material-ui, not yet integrated it with redux-form.
See my class:

```javascript
import React from 'react';
import TextField from 'material-ui/TextField';

export default class GoogleAutoComplete extends React.Component {

	constructor(props) {
		super(props);

		this.autocomplete = null;
		this.handlePlaceChanged = this.handlePlaceChanged.bind(this);
	}

	componentDidMount() {
		this.autocomplete = new google.maps.places.Autocomplete(this._input.input, {types: ['geocode']});
		this.autocomplete.addListener('place_changed', this.handlePlaceChanged);
	}

	componentWillUnmount() {
		this.autocomplete.removeListener('place_changed');
	}

	handlePlaceChanged() {
		if (this.props.onPlaceChanged) {
			this.props.onPlaceChanged(this.autocomplete.getPlace());
		}
	}

	render() {
		return <TextField ref={(c) => this._input = c} {...this.props} name={this.props.name} />;
	}
}

GoogleAutoComplete.propTypes = {
	name: React.PropTypes.string.isRequired,
	onPlaceChanged: React.PropTypes.func
};
```

I guess what is remaining to do is to use it with redux-form in `component`
let me know if you come up with a better approch

**Comment by jasan-s** [comment]
@stunaz how are you defining google?  I tested your code and google is not defined error come up.

**Comment by stunaz** [comment]
yes, you should load google map library 
`<script src="https://maps.googleapis.com/maps/api/js?libraries=places"
		async defer
		type="text/javascript"></script>`

**Comment by jasan-s** [comment]
I did that already

**Comment by stunaz** [comment]
hmm that is all I have, I call it like this:
`<GoogleAutoComplete name="address" onPlaceChanged={this.handlePlace} placeholder={'Enter address'} />`

**Comment by jasan-s** [comment]
i got it working, the problem was the function to create new maps object ran before the script loaded:                                      ```
componentDidMount () {
    this.script = document.createElement('script')
    this.script.src = `https://maps.googleapis.com/maps/api/js?key=${googleMapsAPIKey}&libraries=places`
    this.script.async = 1
    this.script.defer = 1
    this.script.onload = () => this.initAutocomplete()
    this.script.onerror = () => this.initAuthcompleteFailed()

    document.body.appendChild(this.script)
  }

  componentWillUnmount () {
    document.body.removeChild(this.script)
    this.autocomplete.removeListener('place_changed')
  }

  initAutocomplete () {
    console.log('Google Maps Loaded')
    this.autocomplete = new google.maps.places.Autocomplete(this._input.input, {types: ['geocode']})
    this.autocomplete.addListener('place_changed', this.handlePlaceChanged)
  } 
```

**Comment by jasan-s** [comment]
however, now i need to get it working with redux-form

**Comment by stunaz** [comment]
I think you will just have to update the`store` in `handlePlaceChanged`... I am not currently working on that part in my app, but would be interested in your findings

**Comment by jasan-s** [comment]
Darn it, couldn't get it to work with Redux-form.  But at least the autocomplete works  , I just dispatch 2 separate Actions to grab data from redux-form and the autocomplete field and then run an async thunk.

**Comment by Jeremboo** [comment]
Hi,

You can also using npm package `google-maps` to load the google api.

```
import GoogleMapsLoader from 'google-maps';

GoogleMapsLoader.KEY = 'Your key;
      GoogleMapsLoader.LIBRARIES = ['places'];
      GoogleMapsLoader.load((google) => {
        this.autocomplete = new google.maps.places.Autocomplete(this.refs.googleInput, {types: ['geocode']});
        this.autocomplete.addListener('place_changed', this.handlePlaceChanged);
      });
```

And use that on redux-form... I wil try still

**Comment by main-kun** [comment]
Have you guys managed to make this work? Would love to see an example

**Comment by jasan-s** [comment]
@main-kun  I did get it working : 
here is a gist https://gist.github.com/jasan-s/a8893acf550b4ee147629bb6fcd64154

the autocomplete gist contains lots of other logic that is not essential .

**Comment by kaueburiti** [comment]
Im trying to use the `redux-form` with `react-google-maps` and had no success with that.
My ideia is:
- The user can click on the map and the input will get that coordenates as value
- If the user edit the input with a new coordenate, the map will respond to that action

But i just can't make it work, anyone has any ideia?

**Comment by gustavohenke** [comment]
Hi @kaueburiti, please [ask at StackOverflow](https://stackoverflow.com/questions/ask?tags=redux-form), using the `redux-form` tag, and don't forget to explain your question well and show what you've got so far!
After you do that, please post the question link here so one of us can answer it over there.

**Comment by kaueburiti** [comment]
@gustavohenke I **finally** solve my question, i literally did it right now :D
What do you think? Should i post my solution here to anyone that has a similar problem? Or should i create a issue or something like that?

**Comment by gustavohenke** [comment]
Feel free to post it here, perhaps as a self-contained gist/JSFiddle/something else :)

**Comment by yokodev** [comment]
@gustavohenke Hi I'm trying to use redux-form and google maps  how did you solve it?

**Comment by gustavohenke** [comment]
Hi @yokodev, I never used Google Maps with Redux Form.
@kaueburiti, on the other hand, was able to integrate them. Perhaps he is able to help you.

**Comment by kaueburiti** [comment]
@yokodev What exactly is your problem?

I, basically have used redux-form + [react-google-maps](https://github.com/tomchentw/react-google-maps), the only thing that you have to do that's was not clear to me was that:
1) The GoogleMaps component has a `onClick` method, to handle click's events.
2) There you can get the click event and the `latLng`.
3) *The tricky part is*: when you create this method, it should use the `changeField` method (that comes from the redux-form's component Field) to change the property on your redux-form that save the coordinates.

**Comment by yokodev** [comment]
Honestly this is a new requirement, and I was doing the initial research, I've just recently come to use redux-form and have no idea where to start I have two fields long and lat which I presume I have to link with google-maps and that's all I know. :D So I'm just starting out. So any ideas are very welcome thanks

**Comment by kaueburiti** [comment]
@yokodev ok, i hope what i said help you anyway. Any doubts just write here!

**Comment by yokodev** [comment]
@kaueburiti 
1. Question: I'm looking the "Call for maintainers" in  react-google-maps is it safe for the comunity to use it?
2. I just copy and pasted the first example in the doc withGoogleMaps and its giving me some errors about _.noop not defined... so its not that simple huh. :D I'll look into at home.
Ok all I want is a component to display a marker base on the Lat and Long, and be able to move the marker and ouput its  Lat,Long so that it can be consumed by redux-form. any ideas are very welcome 
Thanks

**Comment by kaueburiti** [comment]
@yokodev 
1 - Well, there's no a definitive answer to this question. If you expect updates, and new features and etc, definitely `react-google-maps`will not be the best option. But i believe that it is safe to use, i cant see why it should not be safe :)

2 - Just copy and paste is not a good idea. This error occurs because, in the first example, they use the `_.noop`  method, from lodash, that basically returns undefined. You should define your own methods, and if you dont need to handle the `onMapLoad`(for example), you can just remove from the component call. And remember, try to understand what you are copying, to figure out what is really going on.

**Comment by yokodev** [comment]
@kaueburiti 
ok I have this 
```js
export const SimpleMap= withGoogleMap(props =>(
  <GoogleMap
    defaultZoom={8}
    defaultCenter={{lat:-34.397,lng:150.644}}
    onClick={props.onMapClick}
  />)); 
```
and I was able to get this **Object {lat: -34.22230638839619, lng: 150.3533935546875}**
Now I don't know how to get to step 3 and pass in the latLng into it 
```js
<Field name='latitude' component={MyInput} />
<Field name='longitude' component={MyInput} />
```
in the Docs http://redux-form.com/6.5.0/docs/api/Props.md/  we have : 
```doc
change(field:String, value:any) : Function

Changes the value of a field in the Redux store. This is a bound action creator, so it returns nothing.
```
but how do I get the **props** of the siblings in the map click event context?
Thanks :D

**Comment by yokodev** [comment]
well I did this 
```js
this.props.change('latitude',lat);
```
and it worked . I'm not sure if  there is a better way 
what do you think?

**Comment by kaueburiti** [comment]
@yokodev i think that is a good solution, no problem with that :D
