### ISSUE TITLE
Navigation on site for 6.0.5 docs are going to 6.0.3 404s

### ISSUE THREAD

**Issue by JedWatson** [erikras/redux-form#1783]
Was clicking through the examples, and all the navigation on the left (e.g. on page http://redux-form.com/6.0.5/examples/normalizing/) link to 404s (i.e. http://redux-form.com/6.0.3/examples/fieldArrays)

Replacing the `6.0.3` in the URL with `6.0.5` gets you to the right place, but I thought I'd mention it.

Had a look at where the code for the site is generated from in the `website-template` branch, but it wasn't immediately obvious where the version number is injected.

**Comment by kevinzwh** [comment]
It's been fixed by #1784 now!

**Comment by erikras** [comment]
I have a script that generates the docs for every release, but the `6.0.3` - `6.0.5` releases were a bit of a disaster and this got overlooked. Thanks to @kevinzwh for the quick repairs.
