### ISSUE TITLE
How to disable the other form fields on selecting one field in form

### ISSUE THREAD

**Issue by bairisuresh** [erikras/redux-form#1788]
I need help for the below two issues:
1. i need to disable some form fields on entering/selecting the value for other field.
2. How to get all the form filed values?
   If the form field is not entered i need `{"fieldname : ""}` after submitting.( means in formProps)
   
   ``` js
   handleFormSubmit(formProps) {
      console.log('formProps', formProps)
   }
   ```

**Comment by bairisuresh** [comment]
any help on this

**Comment by sseppola** [comment]
I was working on hiding a field based on a separate field value, similar to what you're trying to do, so I thought I'd share what I've found.

Redux-form v6 does not automatically give you all the values anymore as it forced the entire form to be re-rendered with every form change. In v6 you have "opt in" to the values, which you can do using a selector via connect ([example](http://redux-form.com/6.0.5/examples/selectingFormValues/)) or use one of the components Field or Fields.

```
<Field
  name="joinPolicy"
  component={({ input, meta, ...rest }) => {
    if (input.value === 'password') {
      return <Field
        name="password"
        type="text"
        component={renderField} />
    }

    return null
  }} />
```
I'm not sure if this is the recommended way to do it, but it demonstrates how you can access field values to hide/show another component.
The meta prop above will contain a lot of interesting props like "touched", "dirty" etc. which you can use to solve your first issue.
Regarding your second issue, I guess you could just use initialValues to init the field to ""

**Comment by erikras** [comment]
I would recommend using the `formValueSelector` over "nesting" `Field` components like in @sseppola's example.

If, for some reason, you need more than just the value of another field (e.g. `valid` or `dirty`), you can use the [`Fields` component](http://redux-form.com/6.0.5/docs/api/Fields.md/) to get the props for more than one field at a time.

**Comment by danielrob** [comment]
Closing as this question appears to be answered.
