### ISSUE TITLE
How to push new field in FieldArray from outside render function?

### ISSUE THREAD

**Issue by raapperez** [erikras/redux-form#1790]
Hi, I am using redux-form v6.0.5 and it is great.

I am trying to add new items in the FIeldArray but it need to be done by a button from outside the FieldArray component render function. How it can be done?

I already saw in the docs this way to do from inside the component render function:

```
const renderMembers = ({ fields, meta: { touched, error } }) => (
  <ul>
    <li>
      <button type="button" onClick={() => fields.push({})}>Add Member</button>
...
```

**Comment by slavab89** [comment]
You can either use arrayPush (You'll need the dispatch to do the action) or populate the click back to the form and there perform the push.

```javascript
import { arrayPush } from 'redux-form';

// ...
dispatch(arrayPush('myForm', 'myFieldName', {}));
// ...
```
