### ISSUE TITLE
anyone using redux-form with react-toolbox?

### ISSUE THREAD

**Issue by jasan-s** [erikras/redux-form#1791]
I can get the input component of react-toolbox to work but the date-picker and time-component I cannot.

**Comment by jasan-s** [comment]
update: if i pass down error = {error} into the Field component I see the errors but only after  i have clicked submit on a valid email addres

**Comment by aislanmaia** [comment]
I'm trying right now to get working redux-form and react-toolbox and this is being time consuming bring all together.. :(
Seems that the new api to fields is a pain for using with a library of components like React Toolbox. Can anyone help out ?

**Comment by klk1010** [comment]
I was able to successfully combine the two. I created a transition component for each input type. I was already wrapping the react-toolbox components for custom styling consistency.
```
import React from 'react';
import { MyTextInput } from './';

// Designed for use with redux-form
const FormInput = ({ input, meta: { touched, error }, ...custom }) => (
  <MyTextInput
    error={touched && error ? error : ''}
    {...input}
    {...custom}
  />
);

export default FormInput;
```
I also initialized my dropdown options from the redux store and set initial values for my form. 
To use `FormInput`: 
```
import { connect } from 'react-redux';
import { Field, reduxForm } from 'redux-form';

const MyForm = ({ customDropdownOptions }) => (
  <form>
    <Field
       component={FormInput}
       name="myName"
       label="myLabel"
       // if component is a dropdown component
       source={customDropdownOptions}
    />
  </form>
)

function mapStateToProps(state) {
  const { myPage } = state.foo.bar;
  return {
    customDropdownOptions: myPage.myCustomDropdownOptions,
    // initialValues is an optional prop used by redux-form
    // You don't have to manually set the form field default values yourself if you do this
    initialValues: myPage.myInitialFormValueObject
  };
}

const form = reduxForm({ form: 'myForm' });

export default connect(mapStateToProps)(form(MyForm));
```
`state.foo.bar` would be the standard redux path for pulling out the piece you want from the store.

I love how using `redux-form` eliminates the need for creating my own actions and reducers for input fields. Wonderful job!

**Comment by azimgd** [comment]
DatePicker works for me. I had to remove `onBlur` prop tho, it was causing pointless dispatches when selecting a date on calendar.

```
export const renderDatePicker = ({ input: { onBlur, ...inputForm }, label, ...custom }) => (
  <DatePicker
    label={label}
    {...inputForm}
    {...custom}
  />
);
```

```
<Field type="text" name="startDate" label="Start date" component={renderDatePicker} />
```

**Comment by gustavohenke** [comment]
In fact, it works, as I'm using it (not very advanced usages so far), and folks provided some good examples here!
