### ISSUE TITLE
Animation on swapfield

### ISSUE THREAD

**Issue by nsuthar0914** [erikras/redux-form#1792]
Is there a way i could add animation to show movement of elements in fieldarray while swapping them?
A simple persistence of background color of element would also work, but for that i would need to pass data to the fields; Fields.map only have a element name which is not much use.

**Comment by gustavohenke** [comment]
This is quite out of scope here.

However, I use [react-sortable-hoc](https://github.com/clauderic/react-sortable-hoc), which works great for this. By default it will only animate the movement itself, but you could try other stuff as well.
