### ISSUE TITLE
custom data in fieldArray now working

### ISSUE THREAD

**Issue by alirezavalizade** [erikras/redux-form#1794]
this is my fieldArray component:

```
const openingHours = (props) => {

  const {fields, meta: {touched, error}} = props;

  return (
    <ul>
      {fields.map((day, index) =>
        <li key={index} className="noMargin noListStyle">
          <Row>
            <div className="hidden">
              <Field
                name={`${day}.day`}
                type="text"
                component={"input"}
              />
            </div>
            <Col xs={4}>
              <Field
                name={`${day}.start_time`}
                type="text"
                component={FormGroupTime}
              />
            </Col>
            <Col xs={4}>
              <Field
                name={`${day}.end_time`}
                type="text"
                component={FormGroupTime}
              />
            </Col>
          </Row>
        </li>
      )}
    </ul>
  )
};
```

and this is my form : 

`<FieldArray name="working_hours" component={openingHours}/>`

im want pass custom fields to `working_hours`,like this data : 

`['SUN', 'MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT']`

i dont want push a data to fields like examples in redux-form website, when i pass fields props to `working_hours FieldArray` its not working...how to pass a custom data to `working_hours FieldArray`

**Comment by ElfenLiedGH** [comment]
try 

this.openingHours({fields, meta: {touched, error}}){
>>your code here<<<
}

<FieldArray name="working_hours" component={this.openingHours.bind(this)}/>

**Comment by gustavohenke** [comment]
You can simply use `initialValues` for this.
Or even better, there's no need to use `FieldArray`. Simply do this:

```js
<ul>
{ [ "SUN", "MON", ... ].map( day => {
  // render as usual
  return <li>...</li>
}) }
</ul>
```
