### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by gitMonks** [erikras/redux-form#1796]
Hi Erik,

Thanks for the redux-form. Just to let you know that the link to " Synchronous Validation" example is broken at this URL:

http://redux-form.com/6.0.5/examples/simple/

Thanks 
Imran

**Comment by kevinzwh** [comment]
Seems to be related to #1783 
I did a check through all of the examples and found another instance of this in the Async Validation example. I'll open a PR for this shortly for another quick fix.
