### ISSUE TITLE
enableReinitialize needed

### ISSUE THREAD

**Issue by adriano-di-giovanni** [erikras/redux-form#1798]
First of all,
thanks for Redux Form.

I read [Initialize From State] and tried myself to implement it.

``` javascript
import React, { Component } from 'react'
import { connect } from 'react-redux'
import { Field, reduxForm } from 'redux-form'
import { fetchMember } from '../../actions/members'
import TextField from './TextField'

class EditMemberForm extends Component {
  componentWillMount() {
    const { fetchMember, id } = this.props
    fetchMember(id)
  }
  render() {
    console.log(this.props)
    return (
      <form>
        <Field component={TextField} displayName="Nome" name="item.firstName" />
        <Field component={TextField} displayName="Cognome" name="item.lastName" />
      </form>
    )
  }
}

const config = {
  form: 'editMember',
  enableReinitialize: true
}

let Form = reduxForm(config)(EditMemberForm)

const mapStateToProps = state => ({
  initialValues: state.member
})

const mapDispatchToProps = {
  fetchMember
}

Form = connect(mapStateToProps, mapDispatchToProps)(Form)

export default Form
```

but I have to use `enableReinitialize` in order to have the form updated when member data are fetched.

Member data are

``` javascript
{
  isFetching: true,
  item: {
    firstName: 'Adriano',
    lastName: 'Di Giovanni'
  }
}
```

I also tried to clone `redux-form` and run the examples but I get several errors (mocha, babel-preset-es2015-no-common-js)

**Comment by skolmer** [comment]
This happens if you set initialValues before your data is fetched. You could add a check like this to set the initialValues prop only if state.member is fetched:

```js
const mapStateToProps = state => ((state.member && !state.isFetching)?{
  initialValues: state.member
}:{})
```

**Comment by monkeymonk** [comment]
Impossible to get an initialValues for me too. Even using @skolmer check.

This is really a dumb thing being very complicated... -_-'

Any clues on how to use an async value from the state and putting it in initialValues ?

**Comment by skolmer** [comment]
@monkeymonk  Are you sure that your initialValues object structure matches the names of your Field/FieldArray components? The above code is working fine for me.

**Comment by monkeymonk** [comment]
@skolmer Ok... indeed a typo issue! Sorry for that... and thank you! This is working fine. ;-)

**Comment by joaoreynolds** [comment]
I feel like this pattern could be better, skolmer's solution above feels wrong (you'd have to do that to every form?)

**Comment by danielrob** [comment]
Closing as this was a typo issue. @joaoreynolds, if you would like elaborate further on how this could be improved, please raise a new issue.
