### ISSUE TITLE
Dynamic forms with v 3.0.0-beta-2

### ISSUE THREAD

**Issue by KateKate** [erikras/redux-form#180]
Thank you for new documentation! Short question. Should dynamic forms work the same as in previous version? I have dynamic form and after upgrading the version the validation was broken. Doesn't validate at all, valid/invalid/error attributes are not updated.
I followed this example https://github.com/erikras/redux-form/tree/v2.4.5#dynamic-forms

**Comment by erikras** [comment]
They should when I get around to testing them, which I have not yet. Hence the big warning in the readme. I'll let you know, but it might be next week sometime...

**Comment by damassi** [comment]
Curious about this too. Do you plan on merging this in next week? I'm wondering if I should make a note to the team that an upgrade is coming in the near term and to get ready, or to hold off and continue as we are currently. (Also thanks for bearing with my series of questions; in the middle of a big form project right now)

**Comment by lemonCMS** [comment]
I have got working dynamic forms with validation in redux 3, so i would say that they are working.

**Comment by erikras** [comment]
You rock, @lemonCMS! Will definitely check that out when crafting the dynamic form example.

**Comment by damassi** [comment]
@lemonCMS - did you have to do anything outside of the official API?

**Comment by erikras** [comment]
The main difference between v2 and v3 that facilitates dynamic fields is that the `fields` can be passed as a prop to your decorated component now, which saves all the hassle of the v2 dynamic form example.

**Comment by damassi** [comment]
oh wow! that's really great news.

**Comment by erikras** [comment]
:-) Want better news? I'm expecting to release v3 tomorrow. :tada:

**Comment by damassi** [comment]
Right on :+1:

**Comment by lemonCMS** [comment]
Oh thats great. I am looking forward for an example on how to do it the way you discribe. Right now i am using the v2 way for creating dynamic forms.

@damassi the only thing i had to do to make the dynamic forms work, with an store for initial data, was to add an shouldComponentUpdate check, to see if the store if the same as the next store and the return false. If i did not do that, the dynamic form would come in some kind of loop and then the browser would crash.

But perhaps when using the new V3 kind of creating dynamic forms this would not be needed anymore..

**Comment by erikras** [comment]
v3.0.0 released. Here's the [dynamic form example](http://erikras.github.io/redux-form/#/examples/dynamic).

**Comment by lemonCMS** [comment]
I am busy creating a [redux-form-generator](https://www.npmjs.com/package/redux-form-generator). Hopefully there is an need for this and code contributions will be made :)
