### ISSUE TITLE
Nested field validation

### ISSUE THREAD

**Issue by jmaltis** [erikras/redux-form#1802]
Hello there,

I'm trying to validate nested field (ie, field with a name like `language.id`) but can't make it work to get the appropriate error.
For any non-nested field (like `language` for exemple), if validation fails I will get the `meta.error` object filled with the occurred error, and will be able to display it.
But if the name refer to a nested object, with the exact same validation rule, `meta.error` is always undefined.

Thanks all for the great job !

**Comment by slavab89** [comment]
How does your errors object look?
You can almost always resolve this by building something similar to http://redux-form.com/6.0.5/examples/fieldArrays/

**Comment by jmaltis** [comment]
Let's suppose I have a two-field form (label and language.id).
If i let both fiels empty, my submitted values will look like : 
`{"language":{"id":null}}`
As a result, my error object will look like that :
`{"label":["Required"],"language.id":["Required"]}`

`meta.error` won't be undefined for the field "label", but it will be for "language.id".

**Comment by cmzairi** [comment]
Not sure if I understand this correctly but perhaps you can do something like this?

`if(!values.language){
  errors.language = { id: "Required" }
}`

**Comment by jmaltis** [comment]
Ok you finally made me understand the issue.
My error object looked like `{"label":["Required"],"language.id":["Required"]}`, but it should look like `{"label":["Required"],"language":{"id":["Required"]}}` instead.
Thank you

**Comment by gregwym** [comment]
For whoever finds the answer, while this works, it isn't support well with typescript. 
Work around is to use `[]` notation to access nested error fields.
