### ISSUE TITLE
Custom Component: value becomes synthetic event onChange

### ISSUE THREAD

**Issue by mschipperheyn** [erikras/redux-form#181]
Ok, so I'm not sure how to describe this issue precisely.

I'm using custom textfield components from react-native-material-kit and since upgrading to redux-form 3.0.0-beta-2, I'm having a problem where the value of the textfield onChange gets replaced by a Synthetic event, in stead of by the actual textual value. I thought initially this issue was on the side of them, but now I don't think so: https://github.com/xinthink/react-native-material-kit/issues/47 

I've traced this back to createOnChange which dispatched a synthetic event which works it way up the change and finally gets reduced to the "value" key which then shows up as a property for my TextField and throws an exception.

**Comment by erikras** [comment]
Can you step into [`getValue()`](https://github.com/erikras/redux-form/blob/master/src/events/getValue.js#L4) and tell me what the `event` parameter is? Which of the return paths is taken?

**Comment by mschipperheyn** [comment]
The event parameter = 'SyntheticEvent'. No path seems to be taken, it seems to fail isEvent validation.

I've added a few screenshots
<img width="994" alt="screen shot 2015-10-29 at 09 05 28" src="https://cloud.githubusercontent.com/assets/384959/10816722/46d50738-7e1c-11e5-9398-a1a0b51b7a45.png">
<img width="985" alt="screen shot 2015-10-29 at 09 00 56" src="https://cloud.githubusercontent.com/assets/384959/10816724/46d9c520-7e1c-11e5-8a75-b58161e18087.png">
<img width="982" alt="screen shot 2015-10-29 at 09 00 33" src="https://cloud.githubusercontent.com/assets/384959/10816723/46d86a90-7e1c-11e5-9684-c8ba3a8e4ec2.png">

**Comment by erikras** [comment]
Aha! `isEvent()` is expecting `event.target` to be defined. My mistake for misunderstanding "[Every SyntheticEvent object has the following attributes](https://facebook.github.io/react/docs/events.html)", I guess. I guess I can just check the existence of `stopPropagation` and `preventDefault`...

**Comment by mschipperheyn** [comment]
Ok, didn't follow you. But glad we made progress ;-)

**Comment by erikras** [comment]
Fixed in v3.0.0-beta-4
