### ISSUE TITLE
[v6] reducer plugin defined for one unique form, but it executes for all forms

### ISSUE THREAD

**Issue by raj-adroit** [erikras/redux-form#1810]
We can write reducer plugin like below 

```javascript
import { createStore, combineReducers } from 'redux'
import { reducer as formReducer } from 'redux-form'
import { AUTH_LOGIN_FAIL } from '../actions/actionTypes'

const reducers = {
  // ... your other reducers here ...
  form: formReducer.plugin({
    login: (state, action) => {   // <----- 'login' is name of form given to reduxForm()
      switch(action.type) {
        case AUTH_LOGIN_FAIL:
          return {
            ...state,
            values: {
              ...state.values,
              password: undefined // <----- clear password value
            },
            fields: {
              ...state.fields,
              password: undefined // <----- clear field state, too (touched, etc.)
            }
          }
        default:
          return state
      }
    }
  })
}
const reducer = combineReducers(reducers)
const store = createStore(reducer)
```

I wrote a reducer plugin like this, it works perfect for login form..  The problem is it also executes for other form's also...

Currently am fixing that like this

```javascript
if (action.meta && action.meta.form == 'login' && action.meta.field == 'role_id')  {
.....
switch(action.type) {
        case "redux-form/CHANGE":
....
}
```

**Comment by raj-adroit** [comment]
Looks like its not an issue.. its feature 👍

**Comment by oakley808** [comment]
@raj-adroit Why is it a feature? I would call this a bug. 
I have two forms on a page, if they both have a field named, let's say "status", I might only want to manipulate the status on one form. This 'feature' would change both forms status field.

**Comment by gustavohenke** [comment]
Hi @oakley808, this is how Redux works: a store receives all actions.
You only deal with those that you really want.

This is well explained in [the `reducer.plugin` docs](http://redux-form.com/6.5.0/docs/api/ReducerPlugin.md/).

**Comment by oakley808** [comment]
Thanks @gustavohenke 
The docs should probably state that. The example makes it look like it specifically targets the `login` form in the docs:
`login: (state, action) => {   // <----- 'login' is name of form given to reduxForm()`
