### ISSUE TITLE
Type defs

### ISSUE THREAD

**Issue by alexeygolev** [erikras/redux-form#1812]
I think official flow and TS type declarations would be quite useful.

**Comment by radziksh** [comment]
It's in progress: https://github.com/erikras/redux-form/pull/1318. So far you can manually add files from this PR. It's ready by 80-90 percents. Works quite well for me.

**Comment by alexeygolev** [comment]
ok, TS is covered by that PR. What about flow? I can work on a PR for flow if the maintainers are interested in adding it

**Comment by kristian-puccio** [comment]
I got one working for flow but it's pretty poor really, I haven't had a
chance to tidy it up and flesh it out.

But if you are thinking of creating a typedef for flow have a look at
flow-typed https://github.com/flowtype/flow-typed/
There is a typedef for V5 there so a PR for V6 would be very welcome.

**Comment by stunaz** [comment]
@alexeygolev are you working on this ?

**Comment by blackxored** [comment]
I would also want to see this going.

**Comment by danielrob** [comment]
On the flow side well... 7.x 🎉, on the TS side this duped #1211, see https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/redux-form which is where the types are held now.
