### ISSUE TITLE
using of DateTimePicker from react-widgets

### ISSUE THREAD

**Issue by radziksh** [erikras/redux-form#1813]
I have a problem by using DateTimePicker. Value in input is correct but selected value in DateTimePicker is less for one day:
![screenshot_27](https://cloud.githubusercontent.com/assets/1275228/18632889/6f1e1182-7e82-11e6-9923-109a92119b10.png)

component:

``` javascript
const renderDateTimePicker = function (params) {
        return <DateTimePicker
                {...params.input}
                time={params.time}
                format='LL'
                value={params.input.value}
                onBlur={() => params.input.onBlur(params.input.value)}
                />;
        }
```

using:

``` javascript
<Field
 component={renderDateTimePicker}
 name="fromDate"
 time={false}
 />
```

could you, please, add info how to use it? in http://redux-form.com/6.0.5/examples/react-widgets/ 

**ps:** I use typescript, so I can't use: `= ({ input, **...rest** }) =>` part

**Comment by gustavohenke** [comment]
This issue doesn't belong to our GitHub issue tracker.
We request you to [ask again at StackOverflow](https://stackoverflow.com/questions/ask?tags=redux-form), using the `redux-form` tag, then post the question link here.
*As usual*, don't forget to explain your question well and show what you've got so far!

This is because the GitHub issue tracker is better suited for discussions related to bugs and improvements of Redux Form.
Meanwhile, StackOverflow is better at keeping popular questions visible, while separating feature-related questions from help-related questions.

Thanks for using Redux Form!

**Comment by radziksh** [comment]
This behavior looked like a bug. That's why I added it here. I also suggested to make the improvement: write use case into the documentation. Here is a possible bug and suggestion for improvement, what I did wrong?

**Comment by gustavohenke** [comment]
There are tons of questions at our issue tracker related to datepicker usage:
https://github.com/erikras/redux-form/search?q=datepicker&type=Issues&utf8=%E2%9C%93

Sometimes I have the impression that if people contributed to a single StackOverflow question regarding redux-form + datepicker integration (the right place for questions) they would be enjoying lots of quality answers.

There's even a PR #2119 detailing how to use react-widgets datepicker, but it was probably lost.
It's not even available on the docs for v6.2.1 (first release after it was merged).

Finally, that bug to me seems like related to react-widgets itself - perhaps something related to timezones? We have this problem in the company work I for.

**Comment by radziksh** [comment]
Yes, it's probably something to do with time zones, but maybe it would be a good idea to add an example of using into the documentation, because it's the first place where users are looking for information. Especially if there are ton of questions related to datepicker's usage that shows the need to add it in the documentation. But this is just my opinion.

**Comment by gustavohenke** [comment]
> Especially if there are ton of questions related to datepicker's usage that shows the need to add it in the documentation

I agree.
While the code for PR #2119 was lost, anyone is allowed to step in and fix that with broader usage examples. We are an open source project.
