### ISSUE TITLE
Is it compatible with react-bootstrap ?

### ISSUE THREAD

**Issue by asicfr** [erikras/redux-form#1814]
I use https://github.com/react-bootstrap/react-bootstrap in my project
and i'm looking for a cool solution for forms.
Is redux-form compatible with react-bootstrap ? 

Thanks

**Comment by kevinzwh** [comment]
Yes definitely compatible with react-bootstrap - I've tried out most of react-bootstrap components myself with redux-form and it works pretty seemlessly. The only adjustments you might need to be mindful of is how onChange, onBlur, value...etc. props are passed into react-bootstrap components. 

Most of them are pretty plug and play with redux-form, there are only a few that need minor adjustments of how the props are passsed in.

**Comment by dreyks** [comment]
@kevinzwh could you provide a minimal example? Do I need to create a proxy component for each bootstrap field I use? Otherwise how do I pass props to the underlying bootstrap component?

**Comment by SpOOnman** [comment]
I suggest due to popularity of react-bootstrap it should be as well documented as Material UI in docs.

**Comment by kevinzwhuang** [comment]
Sure @SpOOnman, that's fair! I could write an example displaying various react bootstrap form components and their usage with redux form and maybe note some adjustments that may be needed for some components.

As another note on this, V6 especially works really well with react bootstrap since you can abstract many meta & input props to handle error and validation states with higher order components to create form groups for you. I could write more about this too.

**Comment by SpOOnman** [comment]
This was my first form with both react-bootstrap and redux-form and you're right - it worked quite well. I've started with Material UI examples. I've just wondered - if bootstrap is so popular why there is no example documentation on this? Maybe I miss something?

So - yes, a few examples would be really helpful. Thank you!

**Comment by vasek123** [comment]
Are there any examples available at the moment?

**Comment by gustavohenke** [comment]
Hi @vasek123, no, no official examples available.

Anyone: feel free to send us a PR.

**Comment by DrYSG** [comment]
@vasek123 and @gustavohenke Well, I recently tried this https://github.com/erikras/redux-form/issues/2917 and had all sorts of odd issues, so I would suggest examples might help.

**Comment by danielrob** [comment]
Linking this to #1750 as well.

**Comment by gustavohenke** [comment]
Not much attention over here. Closing this issue.
