### ISSUE TITLE
Reducer plugin can't see previous state

### ISSUE THREAD

**Issue by rennat-eb** [erikras/redux-form#1817]
We have codependent form fields each other (start and end times) so we are using a plugin to change the end time when the start time changes. We're doing this using `reducer.plugin` and listening to redux-form's build in `CHANGE` event.

When this plugin runs, it receives the result of the built-in reducer without access to the previous values.

This seems like a trivial fix by adding an additional argument to plugin functions `previousState` or including previous values in `CHANGE` action's meta information.

Thoughts?

**Comment by erikras** [comment]
Fix published in [`v6.1.0`](https://github.com/erikras/redux-form/releases/tag/v6.1.0).
