### ISSUE TITLE
[v6.0.2-6.0.5] Sync validation makes errors flicker on changing

### ISSUE THREAD

**Issue by ntucker** [erikras/redux-form#1819]
Specifying a validate `reduxForm({ form: 'discovery/order', validate: validateOrder })` that always returns the same error object:
When I change the form values the error flickers in an out on every keystroke. This did not exist in 6.0.1.

Edit: Tested between versions - it first appears in 6.0.2. I'm guessing this is related to 

> Bug fix involving submission error not being cleared. #1654 #1641 Thanks, @ortex!

Probably need to separate that logic for sync errors.

**Comment by willdevelops** [comment]
+1 on this... It's causing my error banners to cause massive amounts of screen reflow.  Anyone else seeing this or have a fix?

**Comment by ortex** [comment]
I fixed this issue. Now, need fix tests.
@erikras Can you tell why you write: 

```
expect(state)
      .toEqual(setIn(fromJS({
        foo: {
          values: {
            myField: 'value',
            myOtherField: 'otherValue'
          }
        }
      }),
        'foo.syncErrors',
        {
          myField: 'myField error',
          myOtherField: 'myOtherField error'
        }))
```
Instead just: 
```
expect(state)
      .toEqual({
        foo: {
          values: {
            myField: 'value',
            myOtherField: 'otherValue'
          },
          syncErrors: {
            myField: 'myField error',
            myOtherField: 'myOtherField error'
          }
        }
      })
```
