### ISSUE TITLE
Fields props on v3.0.0-beta-2

### ISSUE THREAD

**Issue by ingro** [erikras/redux-form#182]
Hello! I've updated the project I'm working on currently to 3.0.0-beta-2. One issue I'm facing is that I can't rely no more on props passed to my decorated component to know if the input should be rendered.

```javascript
shouldComponentUpdate(nextProps) {
    return nextProps.field.error !== this.props.field.error;
}
```

Even if the `error` attribute did change, logging both `nextProps.field.error` and `this.props.field.error` have the same value, so the input isn't rendered and the error isn't show.

This is a changed in 3.0? The above code used to work on 2.4.5.

Thanks for you time and for this great library :)

**Comment by ingro** [comment]
I wrote the issue while I was in hurry, so I will add some more details that can help to understand better the problem.

This is my form component's render method:

```jsx
        let { fields: { from, to, subject, content }, handleSubmit } = this.props;

        return (
            <form onSubmit={handleSubmit}'>
                <FormInput label='From' field={from} />
                ...
           </form>
         );
```

`FormInput` is just a widget that render an input, and the `shouldComponentUpdate` method I wrote in the original issue is part of it.

**Comment by erikras** [comment]
I don't understand. You say the error changed but is also `===`? Is the error returned by validation different between the two renders?

With v3, you really shouldn't need to have a `shouldComponentUpdate()` like this, because the field value should be `===` to the previous one unless one of the field's property changes (this was not the case in v2.4.5). This was one of the major goals of v3.

**Comment by ingro** [comment]
Yep, on the first render both `nextProps.field.error` and `this.props.field.error` are `undefined`, then I write some invalid value and on the next render both values contain the string reporting the error. On 2.4.5 instead after I wrote an invalid value`this.props.field.error` was `undefined` while `nextProps.field.error` contained the error string, so the widget re-render only in that case. It's very strange.

If i comment out the `shouldComponentUpdate` method all the widgets re-render themself even if I just blur one field.

Maybe I'm doing something wrong? I just used the new `reduxForm` method to connect my form component to the redux store, there are some other steps to updgrade from 2.4.5. to 3.0? Thank you.

**Comment by erikras** [comment]
OHHH, I understand the problem now! This is a bug. Thank you!

I need to generate a new copy of the field object if any of its properties change.

**Comment by ingro** [comment]
Ahh, now it's clear, this.props and nextprops are the same object! Glad
that it helped!

**Comment by erikras** [comment]
Released fix under [v3.0.0-beta-3](https://github.com/erikras/redux-form/releases/tag/v3.0.0-beta-3).

**Comment by ingro** [comment]
Thanks for the fast fix, I will try it tomorrow! :)

**Comment by ingro** [comment]
Just to report that everything is back to a working status, I changed the `shouldComponentUpdate` method to just do a shallow comparison between `this.props` and `nextProps`, simplifying the code. 
Nice job with 3.0!

**Comment by panayi** [comment]
I'm almost certain this is still an issue with nested fields (such as the shipping fields in http://redux-form.com/4.2.0/#/examples/deep?_k=n2ytkg). The value of such fields in `this.props` are the same as in `nextProps`, which means the objects are probably mutated. @erikras if you are not aware of the issue (or can't spot it), I can post a fiddle.
