### ISSUE TITLE
values parameter in validate function has changed in version 6 which might cause problems

### ISSUE THREAD

**Issue by niksajanjic** [erikras/redux-form#1824]
This isn't bug in a sense that it is explicitly breaking something, but API for version 6 has changed on this matter and it wasn't mentioned in the docs. Let's say we have 2 fields, _email_ and _password_, and we want to validate those 2 fields inside validate function. On initial render, where both fields are empty validate function gets called with values object being empty:

```
{}
```

whilst in version 5 it was like this:

```
{ email: undefined, password: undefined }
```

Then, if user types in something it will be the same in both versions:

```
{ email: test@email.com, password: 1234567 }
```

But if user empties out both inputs, for version 6, object will again be empty:

```
{}
```

And for version 5 it gets set to empty string:

```
{ email: '', password: '' }
```

In case we want to validate both fields being required, for version 5 we had to check if value is _undefined_ or empty string (although it would be better that it's always empty string) but for version 6 it can be a problem if you name your field for instance _email.first_ (which is allowed by docs) then you will have a problem of deep nesting where you first need to check if _email_ object exists before checking for _first_ property.

Wouldn't it be better if it was like in version 5 only that every input would be set to empty string if there's no value instead of being undefined on initial render? Thoughts?

**Comment by lucaboieru** [comment]
+1

**Comment by danielrob** [comment]
Since we're onto v7 territory, I'll close this. If you still believe this is relevant please re-raise as a new discussion.
