### ISSUE TITLE
Readonly / Disabled fields

### ISSUE THREAD

**Issue by DWboutin** [erikras/redux-form#183]
Hi, i'm trying to get the best setup EVER to handle CRUD in a single component. Your package works very well... But i wonder how i can handle my Read state... 

How can i set the fields at readonly when i initialize them like this? 
```
this.props.dispatch(initialize('contact', {
  name: 'test'
}));
```

**Comment by erikras** [comment]
redux-form doesn't currently manage readonly or disabled state. Normally, I find that whether a field is disabled or not can depend on many things and often needs to be calculated from other bits of state, which makes it a bad candidate for saving in state itself.
