### ISSUE TITLE
[v6] How to empty a value/field?

### ISSUE THREAD

**Issue by monkeymonk** [erikras/redux-form#1833]
In v5 we doing something like this:

```
<button type="button" onClick={() => fields.name.onChange('')}>&times;</button>
```

How can we do the same in v6?

**Comment by Aaronius** [comment]
Use the `change` action creator: http://redux-form.com/6.0.5/docs/api/ActionCreators.md/

It will look something like:

```
dispatch(change('formName', 'name', ''));
```

**Comment by monkeymonk** [comment]
Hello @Aaronius, and thank you but... could you give a more complete example ?

I don't know how and where doing the `dispatch(change('formName', 'name', ''));`

Also, how can we use this to work with `FieldArray` ?

I'm sorry but I'm filling more and more confuse about `redux-form`... 

Thank you.

**Comment by huan086** [comment]
Put your button inside a Field

```jsx
function Button(props) {
    return (
        <button type="button" onClick={props.input.onChange("")}>&times;</button>
    );
}

<Field name="name" component={Button} />
```

When in doubt, just wrap in a Field, Fields or FieldArray.

**Comment by monkeymonk** [comment]
Thank you @huan086 ! Indeed, I think this the better way to do this.
