### ISSUE TITLE
asyncValidation not working on blur (but works on submit)

### ISSUE THREAD

**Issue by mikeengland** [erikras/redux-form#1834]
Hi,

I have created a form and wanted to use async validation to ensure that the name field doesn't already exist. I have a form like in the example:

``` javascript
form = reduxForm({
    form: 'form',  // a unique identifier for this form
    validate,
    asyncValidate,
    asyncBlurFields: ['name']
})(form);
```

In my asyncValidate function (looks just like the example although I have implemented an AJAX get using Axios), when i console.log the values that are passed in, the value that was just edited appears as undefined, however all other fields are there.

When I submit however, the field value is there correctly. Any ideas?

Thanks!

**Comment by Vargentum** [comment]
Verify that you provided `onBlur` handler into your underlying input component. I've fixed the same problem by doing it.

**Comment by kesiena115** [comment]
@Vargentum  what do you mean? Could you please provide an example? I cannot see any additional `onBlur` handler in [this example](http://redux-form.com/6.7.0/examples/asyncValidation/) in the documentation, yet it works.

**Comment by kesiena115** [comment]
I think I've figured it out. Here's what my `renderInput()` now looks like. The important thing here is the line with `onBlur=...`

    renderInput({
        input,
        label,
        type,
        meta: { asyncValidating, touched, error, active }
      }) {
      return (
        <Item>
          <Input
            placeholder={label}
            {...input}
            type={type}
            onBlur={() => input.onBlur(input.value)}
          />
        </Item>
      );
    }

**Comment by gustavohenke** [comment]
Thanks for the tip, @kesiena115. That should have been @mikeengland's problem as well.

Will close for now, but let us know if there's more to it that we should be aware of.
