### ISSUE TITLE
Adding onFocus to an input element doesn't focus and swallows first click when clicking on an element

### ISSUE THREAD

**Issue by RyanAtViceSoftware** [erikras/redux-form#1836]
The gif below shows the issue. If you notice after adding `onFocus={input.onFocus}` it takes longer to focus the input text element and this is because I have to click twice.

**Code**
individuals.js

``` javascript
import React, {PropTypes} from "react"
import {Field, reduxForm, FieldArray} from 'redux-form'
import Individual from './Individual'
import {DropdownList} from 'react-widgets'
import {DateField} from 'react-date-picker'

const Individuals = ({fields}) => {
  const renderField = ({input, label, type, meta: {touched, error}}) => 
  <div>
      <label>{label}</label>
      <div>
        <input
          value={input.value}
          onChange={input.onChange}
          onBlur={input.onBlur}
          onFocus={input.onFocus}
          type={type}
          placeholder={label}/>
        {touched && error && <span>{error}</span>}
      </div>
    </div>

  return (
    <div>
      <ul>
        <li>
          <button type="button" onClick={() => fields.push({})}>Add Spouse or Child</button>
        </li>
        {fields && fields.map((individual, index) =>
          <li key={index}>
            <button
              type="button"
              onClick={() => fields.remove(index)}>Remove Individual
            </button>

            <Field
              name={individual + '.firstName'}
              type="text"
              component={renderField}
              label="First Name"/>
            -----------------------------------------------------

          </li>
        )}
      </ul>
    </div>)
}

Individuals.propTypes = {
  fields: PropTypes.object
}

export default Individuals
```

the above code is called by this code

``` javascript
import React, {PropTypes} from 'react'
import {reduxForm, FieldArray} from 'redux-form'
import Individuals from './Individuals'


let MyNeeds = ({handleSubmit, onMyNeedsFormSubmit}) => {
  return (
    <div>
      <form onSubmit={handleSubmit(onMyNeedsFormSubmit)}>
        <h1>I need coverage for</h1>
        <FieldArray name='individuals' component={Individuals}/>
        <button type="submit">Submit</button>
      </form>
    </div>
  )
}

MyNeeds.propTypes = {}

const validate = values => {
  const errors = {}
  return errors
}


export default MyNeeds = reduxForm({
    form: "myNeedsForm",
    validate
  }
)(MyNeeds)
```

**Screen Capture**
![reduxformfocusissue](https://cloud.githubusercontent.com/assets/10080111/18723896/122c497e-8000-11e6-8325-ef721a0725ef.gif)

**Comment by domhede** [comment]
I have something similar going on.

**Comment by gustavohenke** [comment]
Ah... the classic error of having the component within the render function :)

Have a look here: https://codesandbox.io/s/x703v0kj4z
Basically, all you needed to do was moving the `renderField` outside the `Individuals` component.

There are plenty of material around our GitHub issues and StackOverflow too why this is wrong.

**Comment by umair-dev** [comment]
@gustavohenke can you link to example GitHub issues/StackOverflow post(s) about why it's wrong? I'm not clear on why events get swallowed with the poster's original code.

**Comment by gustavohenke** [comment]
Sure!
- #1094
- #1609
- #2129
- #2921
- #3388
- https://stackoverflow.com/questions/46172141/in-react-js-fields-losing-focus-after-first-onchange
- https://stackoverflow.com/questions/39839051/using-redux-form-im-losing-focus-after-typing-the-first-character
- https://stackoverflow.com/questions/45345932/redux-form-v6-generating-dynamic-form-with-unique-keys-loses-focus-on-entering
- https://twitter.com/andrestaltz/status/768087662557274112
- https://medium.com/netscape/react-performance-anti-pattern-creating-functions-in-render-ddeb5ebd2933

Enough?

**Comment by umair-dev** [comment]
Yes. Thanks so much

**Comment by Thomasin500** [comment]
Having a similar issue to [#2412](https://github.com/erikras/redux-form/issues/2412)

However, declaring the component outside of the render() function does not seem to fix the issue and unfortunately, the webpackbin from the linked issue has expired. 

Any thoughts?

**Comment by shamanking** [comment]
Thanks @gustavohenke , it looks so good.
