### ISSUE TITLE
Include submission errors in component props

### ISSUE THREAD

**Issue by stevenmusumeche** [erikras/redux-form#1839]
When a form submission fails (a SubmissionError is thrown), the error message is not passed into the form as a prop.  For example, if my submission function was:

```
ajax.submit(whatever).fail(() => {
    throw new SubmissionError({_error: 'error from the server'});
});
```

The props for the form component should include this.  Currently, they do not.  I realize there is an onSubmitFail method, but that doesn't allow me to see/display the error message in the actual form.  

Am I approaching this wrong?

**Comment by Ethaan** [comment]
Did you get a way to get this on the Component?

**Comment by stevenmusumeche** [comment]
@Ethaan check this issue: https://github.com/erikras/redux-form/issues/1786
