### ISSUE TITLE
handleSubmit doesn't fire submit actions

### ISSUE THREAD

**Issue by IwanKaramazow** [erikras/redux-form#184]
There's something very strange going on.
This code doesn't fire a redux submit action on submit:
```
class LoginForm extends Component{
	submitt(){
		console.log("test");
	}
	render(){
    	const { fields: {mail, password}, handleSubmit, submitting } = this.props;

    	return (
    		<form className="forms" onSubmit={handleSubmit(::this.submitt)}>
			    <section>
			        {renderInput(mail,'E-mail','text')}
			    </section>
			    <section>
			        {renderInput(password,'Wachtwoord','password')}
			    </section>
			    <section>
			        <button type="primary" onClick={handleSubmit(::this.submitt)}>
			        	Log in
			        </button>
			    </section>
			    {submitting && <h1>IS SUBMITTING!!!!!!!</h1>}
			    {!submitting && <h1>NOT SUBMITTING!!!!!!!</h1>}
			</form>

    		);
    }

}
export default reduxForm({
  form: 'login',
  fields: ['mail', 'password'],
  validate: syncValidate
})(LoginForm);
```
Is this an issue in 3.0.0 beta2? Or am I forgetting something?

**Comment by erikras** [comment]
It won't call your submit function if sync validation is failing. That seems the most likely cause. Put a `console.log` at the end of your `syncValidate` function. If it's anything other than `{}`, the submit won't go through.

**Comment by IwanKaramazow** [comment]
Thanks a lot! Just wasted 2 hours in debug-hell🔥 without tracing it back to ```{}```

Took this function from the React Redux hot universal example, my 'issue' was hiding at line 3.
```
export function createValidator(rules) {
  return (data = {}) => {
    const errors = {}; //{valid: true}; => Has to be {} !
    Object.keys(rules).forEach((key) => {
      const rule = join([].concat(rules[key])); // concat enables both functions and arrays of functions
      const error = rule(data[key]);
      if (error) {
        errors[key] = error;
        errors.valid = false;
      }
    });
    return errors;
  };
}
```

This can be closed.

PS: awesome work with Redux-Form, this is a life saver!

**Comment by erikras** [comment]
Yep. [Had to change](https://github.com/erikras/react-redux-universal-hot-example/commit/b46921a990991e85522dbfc3195a46490a8f4e90#diff-0401b80c2ec4739ac8c03ce9d4b28cefL49) that when I upgraded it to v3. :-)
