### ISSUE TITLE
Feature Request: 'FieldArray' to be sortable?

### ISSUE THREAD

**Issue by JakeLin1024** [erikras/redux-form#1840]
Hey, I was just wondering if the FieldArray could be sortable? 
A common use-case for this is to sort a 'table' after clicking table head columns.

Is it possible to provide a Action Creator like 'arraySort(args...)' or stuff like that?

Any ideas?

**Comment by clayne11** [comment]
You can do that yourself with `arraySplice`. You can take the values, sort them, then splice the entire array back in.

**Comment by JakeLin1024** [comment]
Yes, this can be done by grabbing the values from state and sort them using array.sort function. 
I don't think '''arraySplice''' is necessary. 
The '''arraySort''' was just an assumption, though. closing.

**Comment by iyn** [comment]
In theory this should be easily done with the `array.splice` action, but at this point there's a bug that prevents it (`array.splice` only inserts 1 element and ignores the rest) - https://github.com/erikras/redux-form/issues/2031

Until the issue with the `array.splice` is solved, I described my workaround here: https://github.com/erikras/redux-form/issues/1758:

> Right now, my workaround is to use https://github.com/tshelburne/redux-batched-actions to batch `array.removeAll` and multiple `array.insert` calls with the desired items/objects)

`array.insert` calls in the batched actions array should be in the order you want.

**Comment by mikeinsf** [comment]
I solved my issue with this using the redux-form change action. Get the current array, sort it in your code, and dispatch the change action on the field, passing it your sorted array. This method also resulted in a cleaner function. My field name is tags. When I add a new one I want it added and the array re-sorted.

started with this function:
```
             const addItem = (item) => {
                let arr = tags.fields.getAll() || [];
                arr.push(item);
                arr.sort((a, b) => a.toLowerCase().localeCompare(b.toLowerCase()));
                tags.fields.removeAll();
                let x = 0;
                while (x < arr.length) {
                    tags.fields.insert(x, arr[x]);
                    x++;
                }
            }
```

ended with this code:
The parameter 'alphabetical' is a simple sort function that makes sure array.sort handles case properly.
```
        import { change } from redux-form

         const addItem = (item) => {
                const {setTags} = this.props;
                const arr = (tags.fields.getAll() || []).concat([item]).sort(alphabetical);
                setTags(arr);
         }

         function mapDispatchToProps(dispatch) {
             return {
                 setTags: (value) => {
                     dispatch(change('my-form', 'tags', value));
                 }
             };
         }
```

**Comment by shabaz-ejaz** [comment]
How about if you have dynamically generated fields with FieldsArray? So in your example `tags` would be something that is dynamically generated like this:

```
 {fields.map((protein, index) => <div key={index} className="feature-item ui-sortable-handle">
                <li>
                                    <Field
                                        name={`${protein}.title`}
                                        type="text"
                                        className="input-text input-box"
                                        component={renderField} />
                                </li>
</div>
```

How would you go about saving the sorted values for this?
