### ISSUE TITLE
Validate fields with variables instead of static values

### ISSUE THREAD

**Issue by llopez95** [erikras/redux-form#1841]
Hi,

I'd like to know if there is any way to validate synchronously my datas using some variables state (or props component) ?

What I have :
`if (!item || item.get('duration') > 2) { ... }`
What I'd like to do :
`if (!item || item.get('duration') > maxDuration) { ... }`

Is it possible? Should I perform an async validation?

Thanks in advance for your informations!

**Comment by timhwang21** [comment]
You can put the validation function in `mapStateToProps`, and then use your props in the validation function. I haven't poked around with using local state, so unfortunately I can't help on that front.

**Comment by llopez95** [comment]
@timhwang21 Thanks for your advice! I did find a workaround, without any certaincy...!

My form is using ArrayFields that need a custom validation for each indivual child of those Arrays. (see `borrowers` and `loans`)
![image](https://cloud.githubusercontent.com/assets/21169556/18813875/a975e3ce-8309-11e6-9d02-4ea8e312ca35.png)

I added to my form state the "dynamic" values that I need to use to validate (minDuration & maxDuration).
Each time I'm selecting a data from a selectbox, I am calling my own action before dispatching the "redux-form/CHANGE" action.

I then have access (in my validate.js function) to the "dynamic" datas.

I don't really like this workaround since I do feel that I'm doing something wrong. Those extra values are not revealant to the form and I suspect that I should do that differently... !

**Comment by timhwang21** [comment]
Where are these dynamic values coming from, state or props? You can actually put your `validate` in `mapStateToProps` versus `reduxForm`, if you need props. 

Also, from the docs: 

> IMPORTANT: All of these configuration options may be passed into reduxForm() at "design time" or passed in as props to your component at runtime.

**Comment by llopez95** [comment]
@timhwang21 When I'm entering my route, an asynchronus call is made to an API and then stored into a slice of my state. My values are then coming from the state.

Thanks for quoting the docs. Dispite my research, I'm still a React newbie and I couldn't figure that by myself. I'll try your suggestion! Thanks again for your time and your explanation.

**Comment by timhwang21** [comment]
In your form component:

```javascript
const mapStateToProps(state, props) => {
  let myAsyncValues = state.whereverYourValuesAre

  return {
    // other stuff
    validate: () => /* do something with myAsyncValues and validate */
  }
}
```

**Comment by llopez95** [comment]
Works like a charm! Thank you very much!

The last thing I'll have to figure out is how to split this validate function into a separate file !

**Comment by akhayoon** [comment]
The way I ended up doing it looks like this. Note that my mapStateToProps function is inline inside the connect() function.

After this, I was able to use any values in my redux store inside the validation function.

```
LocationsFormPageOne = connect(
    (state) => 
    {
        const {LocationsForm} =         state.form;
        const {locations}           =         state.locationsReducer;

        return {
            validate: () =>
            {
                return validate(LocationsForm.values, locations);
            }
        }
    },
)(LocationsFormPageOne)
```

**Comment by akhayoon** [comment]
@timhwang21, I'm finding the problem with the approach is the it's delayed by one action. Meaning that if I empty a required field, it won't respond after a blur event, but only after I edit another field. 

Is this happening to you at all? My example is on the post above that I'm using.

**Comment by timhwang21** [comment]
I'm not sure I see what you mean, if you post your form code I may be able to help.

**Comment by akhayoon** [comment]
@timhwang21, It seems that I just had to use AsyncValidate for the fields that I need to use non-static values by using asyncBlurFields
