### ISSUE TITLE
Redirect to another route after successful submission?

### ISSUE THREAD

**Issue by stevenmusumeche** [erikras/redux-form#1847]
What is the best way to handle redirecting to a new route (I'm using React Router, but any router should follow a similar pattern)?  I've been able to get it to work like this, but it feels wrong.

```
    componentWillReceiveProps(nextProps) {
        if (nextProps.submitSucceeded) {
            this.props.router.push('/dashboard/customer');
        }
    }
```

**Comment by josenavarro-famoco** [comment]
Maybe you could use the function onSubmitSuccess, that is called when the form is submitted successfully, and you get the data and the dispatch function, so you can redirect

**Comment by stevenmusumeche** [comment]
@josenavarro-famoco thanks! The problem is that react-router's push method is not available in that function

**Comment by josenavarro-famoco** [comment]
I think you can import the push method form react-router in the form, and then use it in the dispatch

**Comment by stevenmusumeche** [comment]
thank you
