### ISSUE TITLE
Synchronous Validation not working

### ISSUE THREAD

**Issue by marchock** [erikras/redux-form#1848]
Updating the form using this code below stops synchronous validation and allows a user to submit the form

``` js
 const mappedAddress = {
            ...this.props.form.values,
            addressOne: retrievedAddress.Line1,
            addressTwo: retrievedAddress.Line2,
            city: retrievedAddress.City,
            postcode: retrievedAddress.PostalCode,
            countryCode: retrievedAddress.CountryIso2
        }

        this.props.initialize(mappedAddress);
```

Is there another option to update the form without using "initialize"?

**Comment by slavab89** [comment]
You have the method of initialising from state
http://redux-form.com/6.0.2/examples/initializeFromState/

**Comment by gustavohenke** [comment]
@slavab89 is right, you can initialize your form this way as well.

If that way doesn't help you, let me know, and please include a minimal, working example of your issue.
