### ISSUE TITLE
<Field/> Component Issue

### ISSUE THREAD

**Issue by Dalanir** [erikras/redux-form#1849]
Hello !

I'm having some trouble with the <Field/> Component, I have those errors :

<img width="842" alt="capture d ecran 2016-09-22 a 17 56 19" src="https://cloud.githubusercontent.com/assets/4061263/18756002/80716934-80ee-11e6-9bf4-d3801a5d2d9c.png">

My Code (morveover very simple)

```
import React, { Component, PropTypes } from 'react';
import { Field, reduxForm } from 'redux-form';

import styles from './index.module.scss';
import cssModules from 'react-css-modules';

class SubscriptionForm extends Component {

  static propTypes = {
    subscriber: PropTypes.object,
    handleSubmit: PropTypes.func,
    submitting: PropTypes.bool,
    pristine: PropTypes.bool,
    reset: PropTypes.func,
  };

  render() {
    const { handleSubmit, pristine, reset, submitting } = this.props;
    return (
      <form className="form" onSubmit={ handleSubmit } >
        <div>
          <Field name="email" component="input" type="email" placeholder="Email" />
        </div>
        <div>
          <Field name="password" component="input" type="password" />
        </div>
        <button type="submit" disabled={pristine || submitting}>Submit</button>
        <button type="button" disabled={pristine || submitting} onClick={reset}>
          Clear Values
        </button>
      </form>
    );
  }

}

export default reduxForm({
  form: 'subscriptionForm',
  fields: [],
})(cssModules(SubscriptionForm, styles));
```

Any ideas on where I do shit ?

Thanks a lot

**Comment by JalilArfaoui** [comment]
Weird ... I usually have this error when I have a bad import (const/default) ... but I don't see here 

Does your code work if you remove the reduxForm () enhancer ?

**Comment by naw** [comment]
Are you sure you're importing v6 instead of v5 of redux-form? If you're using v5, `Field` would be undefined.

**Comment by Dalanir** [comment]
Thanks for your answers,

I have no more issues, very weird... I upgrade the react-hot-loader module and now it's working !

Thanks again !
