### ISSUE TITLE
int  always convert  string

### ISSUE THREAD

**Issue by qq645381995** [erikras/redux-form#1852]

**Comment by qq645381995** [comment]
{id:1}   -->  {id:"2"}

**Comment by qq645381995** [comment]
send need  parseInt(id)

**Comment by erikras** [comment]
Low English, ok. 👍 [`parse` prop](http://redux-form.com/6.0.5/docs/api/Field.md/#-parse-value-parsedvalue-optional-)

```jsx
const parse = value => value === undefined ? undefined : parseInt(value)

...

<Field name="id" parse={parse}/>
```
Does that help?

**Comment by gustavohenke** [comment]
> Does that help?

As it's been a while, I will consider this as "yes".
Also this issue seems like a duplicate of #1377

**Comment by Noitidart** [comment]
@erikras is there any way to parseOut and parseIn? Because in react native the `<TextInput>` element requires a string value, if it doesn't it throws a warning. So when coming in I need to do a `.toString()` and when going to submit I need to do `parseInt()`

**Comment by Noitidart** [comment]
Bump on `parseIn` vs `parseOut`. Is this possible folks?

**Comment by erikras** [comment]
@Noitidart Isn't `format()` what you need? See [Value Lifecycle](http://redux-form.com/7.0.3/docs/ValueLifecycle.md/).
