### ISSUE TITLE
reject promise on submit

### ISSUE THREAD

**Issue by josenavarro-famoco** [erikras/redux-form#1854]
I am returning the promise for the onSubmit, but when i reject the promise i don't get the errors in the handleSubmit function of the redux-form
`const error = new SubmissionError(errorObject);
 reject(error);`
And the handleSubmit doesn't get the error as an instance of SubmissionError.
How can i send the error in a way that the handle submit recognize my errors?

**Comment by gustavohenke** [comment]
Please provide a minimal reproducible example.
