### ISSUE TITLE
(v6) How to get fields' meta property ouside the Field?

### ISSUE THREAD

**Issue by hank7444** [erikras/redux-form#1855]
In V5, I can get meta from this.props, but how to do this in V6?

 I tried "getFormValues" & "formValueSelector" but only get fields' value :(

my v5 example as follows:

```

  componentDidUpdate(prevProps) {

    const {
      asyncValidate,
      fields: {
        id,
      },
    } = this.props;

    const {
      fields: {
        id: prevId,
      },
    } = prevProps;

    if (id.value !== prevId.value && id.valid) {
      asyncValidate();
    }
  }
```

**Comment by oyeanuj** [comment]
@hank7444 did you ever find a solution to this one?

**Comment by gwendall** [comment]
Have a look at `getFormSyncErrors` (http://redux-form.com/6.1.1/docs/api/Selectors.md/)

**Comment by danielrob** [comment]
Related #3289.
