### ISSUE TITLE
(v5) Could release "Add a way to access the wrapped component from" #1224 ?

### ISSUE THREAD

**Issue by hank7444** [erikras/redux-form#1856]
thx a lot!!

**Comment by jeremy-putt** [comment]
I agree! Another v5 release would be very welcome :+1:

**Comment by jeremy-putt** [comment]
Hey @erikras , pretty sure you're a busy man, but would you be able to fire off a v5 release or give us an idea of when it might be released?

Thanks!!

**Comment by gustavohenke** [comment]
v5.3.4 published with this fix :)
