### ISSUE TITLE
Support form level validation within the validation function

### ISSUE THREAD

**Issue by vladnicula** [erikras/redux-form#186]
See http://stackoverflow.com/questions/33414545/how-can-redux-form-validation-based-on-multiple-fields-be-implemented for reference. @erikras Thanks for answering btw :+1: 

There should be a way to decide form level errors in the validation function. Right now validation is done on the field level, and _error is hidden in the documentation somewhere. 

Maybe we could discuss things a bit more here. I'm willing to take a look at how it could be done, but it seems we need to think about the approach first.

**Comment by erikras** [comment]
How about a `submissionFailed` boolean prop that defaults to `false` and gets set to `true` when a submission fails for _any_ validation reasons?

**Comment by x1a0** [comment]
`_error` field works fine for me (thank you @vladnicula for bringing up this question). Why do we need a new boolean prop?

**Comment by vladnicula** [comment]
@x1a0 I believe that a error message that happens only when submitting is a worthy addition. The main reason for needing a flag is so we don't check twice if we should show or not show an generic from error that happens after pressing the submit button/running the submit action somehow.

Here's the scenario I have: 
There's 2 'directors' and an 'applicant' in the form. The form is valid if at least one director is provided and the applicant is there as well. I'm validating email addresses on each one of them. This is the field level validation and works well. 

For the directors condition, the _error object can be populated in the validate function with a generic error saying that at least one director needs to be provided. When the form loads, this error will already be generated, since both fields are empty. 

In my view, I need to check the _error object and also the 2 directors, and make sure that they have been touched before showing this. So I'm basically guessing that the form has been submitted. Also, if I just "touch" the two directors without submitting I get the error message with this implementation. This is an acceptable side effect I guess.

Conclusion?

**Generic form errors that happen on submit don't have a clear way of being exposed ONLY on submit**. We always need to check that all fields have been touched. 

Maybe I'm missing something, and this "form level" error can be generated only when the submit button is pressed. 

I'm gonna take a look at this this weekend hopefully.
