### ISSUE TITLE
FieldArray component doesn't receive "name" prop

### ISSUE THREAD

**Issue by clayne11** [erikras/redux-form#1866]
The `Field` component receives the `name` prop from the `ConnectedField`. The `FieldArray` component doesn't receive the `name` prop.

For certain use cases, such as introspecting a form's schema to determine it's behavior, the name is required to look up the schema definition.

**Comment by pcalves** [comment]
@erikras Any particular reason why the `FieldArray` component stopped receiving the `name` prop? It was working at least until 6.0.2.
