### ISSUE TITLE
How can I import Redux-Form's actions and use it?

### ISSUE THREAD

**Issue by cisen** [erikras/redux-form#1869]
No example shows hao to use the actions. It confuses me.

**Comment by JakeLin1024** [comment]
Do you mean Action Creators?

if so, you can,
import { initialize } from 'redux-form';
and then somewhere in your code,
dispatch(initialize(args...));

BTW, this is an usage question. You shoulda asked on stackoverflow.

**Comment by cisen** [comment]
OK, thank you!
