### ISSUE TITLE
SubmissionError with sync submit handler

### ISSUE THREAD

**Issue by tugberkugurlu** [erikras/redux-form#1872]
> asked this on SO but didn't get a response there: http://stackoverflow.com/questions/39164925/submissionerror-with-sync-submit-handler-in-redux-form

On redux-form, I can propagate a general form error from an async submit handler by throwing a `SubmissionError` just like described [here](http://redux-form.com/6.0.0-rc.5/examples/submitValidation/). However, this doesn't seem to work when my submit handler doesn't return a promise. Is there way to achieve the same error propagating behavior of async submit handler with sync submit handler?

**Comment by bertjwregeer** [comment]
Your `onSubmit` function:

```
        return new Promise((resolve, _reject) => {
                throw new SubmissionError({
                    fieldname: 'some error',
                    _error: 'Form could not be submitted.',
                });
        });
```

Basically create a new promise that is returned, and inside that promise throw the `SubmissionError`. Not the most elegant, but it works.

**Comment by tugberkugurlu** [comment]
@bertjwregeer seems like a good enough workaround, thx! I was gonna go with that but wanted to see if there is a legitimate way to do this.
