### ISSUE TITLE
Assiging intialValues to FieldArray

### ISSUE THREAD

**Issue by Aldizh** [erikras/redux-form#1874]
First i would like to thank you for the awesome work.
I was wondering if we can assign inital values to the field array component.
In this example i am passing initialValues as an extra parameter which holds an object and i would like to push that to fields pseudoArray before rendering the form grid

`const RenderPricingCriteria = ({ fields, meta: { touched, error }, initialValues }) => (
  <div className="col-1-1">
    renderGrid(fields.push(initialValues))
   ....
  </div>
)`

React is complaining that i can't edit fields as it is already being rendered, but this is the only place i have access to fields.

Any thoughts on how to approach this problem?
Thanks

**Comment by Aldizh** [comment]
So as it turns out, As long as your data input matches the form structure, initialValues will 'magically' populate the form inputs. I had a problem setting the default for one of the input fields (Object select field) when each selection is an object but that is another problem. Closing this.

**Comment by abodero** [comment]
This link helped me figure out what i was doing wrong: 
https://codesandbox.io/s/Ww4QG1Wx 

If you change: 
export default reduxForm({
  form: 'fieldArrays', // a unique identifier for this form
  validate,
   initialValues: {
    members: [
      { firstName: 'john', lastName: 'Doe', hobbies: [] },
      { firstName: 'john2', lastName: 'Doe2', hobbies: [] },
      { firstName: 'john3', lastName: 'Doe3', hobbies: [] }
    ],
  },
})(FieldArraysForm);

You get the initialValues working fine. In my case i was using an older version of redux-form
