### ISSUE TITLE
error missing on immutable form

### ISSUE THREAD

**Issue by bochen2014** [erikras/redux-form#1875]
I'm using immutable redux form, and find that the error object is missing from my decorated form  component.

```
error : any

A generic error for the entire form given by the _error key in the result from the synchronous validation function, the asynchronous validation, or the rejected promise from onSubmit.
```

I've also confirmed this on redux-form/examples/immutable/ImmutableForm.js

```
const ImmutableForm = (props) => {
  const { error,handleSubmit, pristine, reset, submitting } = props
  console.log(error)  // <------------------- always undefined! even when user name is empty
  return (
    <form onSubmit={handleSubmit(test)}>
      <Field name="username" type="text" component={renderField} label="Username"/>
      <Field name="email" type="email" component={renderField} label="Email"/>
      <Field name="age" type="number" component={renderField} label="Age"/>
      <div>
        <button type="submit" disabled={submitting}>Submit</button>
        <button type="button" disabled={pristine || submitting} onClick={reset}>Clear Values</button>
      </div>
    </form>
  )
}
```

**Comment by bochen2014** [comment]
ok. seems I have got it wrong. 

the error object that redux-form would pass to your decorated component is the SubmissionError object returned in your onSubmit function; 
it does NOT propagate the error object returns from validate prop of redux-form.

So how can I get field errors from my wrapped form component??

**Comment by kristian-puccio** [comment]
You could create a selector for it and grab the data using react-redux's connect function.

Use the redux devtools to see the state tree.
I don't use immutable but for me the path is state.form['myformname'].syncErrors or state.form['myformname'].asyncErrors

You could create a selector where you pass in the name of the form and the name of the field and it could return an errors for you.

**Comment by ocolot** [comment]
If anyone looks this up, note that any import from `redux-form` and not `redux-form/immutable` in your code will break things like error handling (even if it 'appears to work' at first sight).

**Comment by danielrob** [comment]
Answers include `getFormMeta`, creating your own custom selector as @kristian-puccio suggested, or using `Field` or `Fields` to act as connectors to get the fieldMeta you need.
