### ISSUE TITLE
Vagueness in the api docs

### ISSUE THREAD

**Issue by NSLS** [erikras/redux-form#1876]
In the latest API Documentation, on the page API -> reduxForm()
http://redux-form.com/6.0.5/docs/api/ReduxForm.md/
, the doc states, that the decorated component will have a `values` prop, containing the values of the form. However, using immutable decorator (haven't tested the normal one), no such field is passed, and I'm confused whether it should be passed whatsoever, because the `props` page, which should describe all the props passed to the child component, does not have any mention of such field. 
Therefore, I am curious, is it a bug or just a mistake in the documentation?
Thanks.

**Comment by clayne11** [comment]
The docs don't mention that anywhere. The docs mention that the `reduxForm` component will have a `values` property if accessed via a `ref`.

**Comment by NSLS** [comment]
Oh, I see now. Thanks!
