### ISSUE TITLE
[v6] immutable FormReducer causes fatal exception: "One of the sources for assign has an enumerable key on the prototype chain. This is an edge case that we do not support. This error is a performance optimization and not spec compliant."

### ISSUE THREAD

**Issue by jpaas** [erikras/redux-form#1877]
If I use the FormReducer from redux-form/immutable, the createFieldProps causes an exception when trying to Object.assign the meta props. Looks like its expecting state to be a js object instead of an immutable one.

**Comment by axelardu** [comment]
Hey there,
Having the same problem with redux-form v6.1.0 .
Did you manage to get it fixed?

**Comment by jpaas** [comment]
No I ended up having to fall back to using the non-immutable reducer

**Comment by cayter** [comment]
Facing the same issue. Is this a bug or it's because of we're not using it correctly?

**Comment by Prudwell** [comment]
Anyone found anything new on this? Same problem for me.

**Comment by erikras** [comment]
Published fix in [`v6.4.2`](https://github.com/erikras/redux-form/releases/tag/v6.4.2).
