### ISSUE TITLE
handleSubmit v5 migrate to v6

### ISSUE THREAD

**Issue by fa10** [erikras/redux-form#1879]
Hi i have a issue i am trying to migrate from v5 to v6 and in my code right now i am using this to handle submit.

``` javascript
handleApiSubmit(action, success, error) {
    const { handleSubmit } = this.props;

    return handleSubmit((values, dispatch) =>
      new Promise((resolve, reject) => {
        dispatch(action(this.modifyValues(values)))
          .then(
          (result) => {
            if (result.success) {
              resolve();
              if (success) {
                success(result);
              }
            } else {
              reject(modelStateErrorToFormFields(result.errors));
              if (error) {
                error(result);
              }
            }
          },
          (result) => {
            reject(modelStateErrorToFormFields(result.errors));
            if (error) {
              error(result);
            }
          });
      })
    );}
```

How can i merge this to v6?

**Comment by mschipperheyn** [comment]
Well, first of all. I would review the migration documentation, which is fairly complete. Then, if you run into issue, ask a specific question. You will need to use a new type of SubmissionError to identify validation exceptions. So, this modelStateErrorToFormFields should return that SubmissionError object. If you can, I would recommend using async await style code. Much more readable. But that's just a personal opinion

**Comment by danielrob** [comment]
Closing due to non response after eight months!
