### ISSUE TITLE
Adding reCAPTCHA

### ISSUE THREAD

**Issue by fireredlink5000** [erikras/redux-form#1880]
Did anyone try to add reCAPTCHA to redux-form?

**Comment by xz64** [comment]
I have added recaptcha using `react-google-recaptcha` and `redux-form` v6.

Here is how I did it:

1. Add a field named `captcharepsonse` (or anything you want) to the `fields` array when you call `reduxForm`.
2. Create a Captcha component using `react-google-recaptcha`:

    ```jsx
    const Captcha = (props) => (
      <div>
        <ReCAPTCHA
          sitekey={process.env.RECAPTCHA_SITE_KEY}
          onChange={props.input.onChange}
        />
        </div>
    );
    ```

3. Use `redux-form`'s `<Field>` component to link the captcha response to your redux form

    ```jsx
    <Field name='captcharesponse' component={Captcha}/>
    ```

I am using this method in one of my projects. I have put links to the relevant code below:

[form definition](https://github.com/xz64/voting-app-frontend/blob/1d18bba32c195977b5cc3d29c1a089677fced62a/src/register/RegisterContainer.jsx)
[form](https://github.com/xz64/voting-app-frontend/blob/1d18bba32c195977b5cc3d29c1a089677fced62a/src/register/RegisterFormView.jsx)
[captcha component](https://github.com/xz64/voting-app-frontend/blob/1d18bba32c195977b5cc3d29c1a089677fced62a/src/forms/Captcha.jsx)

PS - It looks like the maintainers would prefer this question to be posted on StackOverflow with a `redux-form` tag according to [CONTRIBUTING.md](https://github.com/erikras/redux-form/blob/master/CONTRIBUTING.md)

**Comment by fireredlink5000** [comment]
Thanks so much!

**Comment by eneskaya** [comment]
Thanks @xz64 ! How to use this with `size="invisible"` attribute on the ReCAPTCHA element?

**Comment by Nik-H0** [comment]
In case someone finds this useful, this is how I added redux-form field errors to the reCAPTCHA.

```javascript
// in some component
renderRecaptchaField(field) {
    const { meta: { touched, error } } = field;
    return (
      <div>   
        <ReCAPTCHA 
          sitekey="..." 
          onChange={field.input.onChange}
        />
        <div><p className="text-danger">{ touched ? error : '' }</p></div>
      </div>
    );
  }

render() {
  return (
    <Field name="recaptcha" component={this.renderRecaptchaField} />
  );
}
```

Don't forget to hookup the errors in the form validate function passed to reduxForm.

```javascript
function validate(values) {
  const { recaptcha } = values;
  const error = {};

  if (!recaptcha) {
    error.recaptcha = 'reCAPTCHA required.';
  }
  return error;
}

export default reduxForm({
  validate,
  form: 'Login'
})( connect(mapStateToProps, mapDispatchToProps)(YouComponent) );
```

That should also prevent the form from being submitted unless the reCAPTCHA is checked.

**Comment by davidfurlong** [comment]
@Reggino I have found a way to do this using invisible recaptcha, but its not beautiful

```js // Register.js
import ReCAPTCHA from 'react-google-recaptcha';

class Register extends React.Component {
  captcha = null;
  data = null;
  register = data => {
    this.data = data;
    this.captcha.execute();
  };
  registerWithCaptcha = (captcharesponse: string) => {
    const d = Object.assign({}, omit(this.data, ['terms']), {
      language: this.props.getLocale(),
      captcharesponse: captcharesponse
    });
    this.captcha.reset();
    return this.props
      .register(d)
      .then(responseHandler(this.props.notifSend, { showSuccess: false }));
  }
  render(){
   return (
    <RegisterForm onSubmit={this.register} captchaRender={() => (<ReCAPTCHA
            ref={(el) => { this.captcha = el }}
            sitekey={sitekey}
            onChange={(value) => this.registerWithCaptcha(value)}
            size={"invisible"}
          />)} /> 
  )  
 }
}
```

```js // RegisterForm.js
export const RegisterForm = ({ handleSubmit, t, captchaRender }) => (
  <form
    className="form-center"
    onSubmit={handleSubmit}
    style={{ overflowY: 'auto', overflowX: 'hidden' }}
  >
    <Field
      name="email"
      type="email"
      component={l_TextInput}
      label={t('email')}
      placeholder={t('email_ph')}
    />
    <Field
      name="password"
      type="password"
      component={l_PasswordInput}
      label={t('password')}
      placeholder={t('password_ph')}
    />
    <br />
    {captchaRender()}
    <div style={{ float: 'right' }}>
      <SubmitButton label={t('register')} translateKeys={t} />
    </div>
  </form>
);

```

**Comment by nihlton** [comment]
Just a note:  

was able to implement this without trouble, but then tried to implement in another place with size='invisible'..

remember to make sure the key you're using supports invisible.
