### ISSUE TITLE
touched property not set to true if I set onBlur and onFocus event.

### ISSUE THREAD

**Issue by tecnolocoEdan** [erikras/redux-form#1882]
If I set custom onBlur and onFocus events in my component the touched property is not set to true when input change, and vallidate function is not called. The resulting error is not shown.

`import React from 'react'

const InputForm = ({ input, type, label, icon, placeholder, meta:{touched, error}, onBlur, onFocus })=> {

```
let inputIcon= icon ? <span className={'input-group-addon'+' '+ icon}></span>:<span className="icon-user"></span>;

return(
    <div className="form-group">
        <label >{label}</label>
        <div className="input-group">
            {inputIcon}
            <input {...input} className="form-control" onBlur={onBlur} onFocus={onFocus} type={type} placeholder={placeholder} />
        </div>
        {touched && error && <div className="form-group-error-container">{error}</div>}
    </div>
)
```

}

export default InputForm`

**Comment by andismith** [comment]
I also have this problem. If I remove my custom onBlur/onFocus events then touched is set to true, but if I have these custom events touched stays at false.

Any ideas?

**Comment by mynnx** [comment]
Your custom function has to call the field's `onBlur` / `onFocus` functions, otherwise redux-form won't be aware that the element has been focused or blurred.

`<input onBlur={(e) => {console.log('I blurred!');  input.onBlur(e)} />`

**Comment by tecnolocoEdan** [comment]
I totally fogot to close this issue. I realized that I had to do what @mynnx said.

**Comment by andismith** [comment]
Great, thanks
