### ISSUE TITLE
Re-calculating form fields based on field change.

### ISSUE THREAD

**Issue by asaf** [erikras/redux-form#189]
Hey,

I have a situation where changing a field (i.e a selectbox option) changes the form's fields.

I'm wondering what would be the best approach to cause fields re-calculation,

Any idea?

Thanks.

**Comment by erikras** [comment]
I'm still designing an example for such a case. I haven't yet gotten around to implementing it yet.

In v3, you can pass in the fields array as a prop to your decorated form component. That's the recommended way.

**Comment by asaf** [comment]
That's nicer, but still, an input change won't cause the decorated form component to be re-rendered, so the fields won't be re-calculated...

**Comment by erikras** [comment]
[`v3.0.0` supports this](http://erikras.github.io/redux-form/#/examples/normalizing).
