### ISSUE TITLE
Conditionally show an input field based on its value in the FieldArray

### ISSUE THREAD

**Issue by adam-bernau** [erikras/redux-form#1890]
Is it possible to render various widgets component for a field in the FieldArray based on its value?

``` javascript
const renderCities = ({ fields }) => { ... };
....
<FieldArray name="cities" component={renderCities} />
```

So it's possible to get a field value in the "renderCities" function?

**Comment by gustavohenke** [comment]
Try using `getFormValues` selector.

[Docs](http://redux-form.com/6.4.3/docs/api/Selectors.md/)
