### ISSUE TITLE
setting _error in submit handler without SubmissionError

### ISSUE THREAD

**Issue by jampy** [erikras/redux-form#1898]
I know that the async submission handler I can use `SubmissionError` to signal any _validation_ errors found during submission. The documentation states that `SubmissionError` should _only_ for validation errors and _not_ for low-level AJAX errors:

> SubmissionError
> A throwable error that is used to return submit validation errors from onSubmit. The purpose being to distinguish promise rejection because of validation errors from promise rejection **because of AJAX I/O problems or other server errors**.

In my case I'd like to use `_error` to show the user that it was not possible to submit the form and that he shall try again. 

I cannot (should not) use `SubmissionError` for that, especially because the form cannot be resubmit unless a field is changed (see also #1884).

But then, how can I set `_error` in my submit handler?

**Comment by terencechow** [comment]
+1

**Comment by MilllerTime** [comment]
> I cannot (should not) use SubmissionError for that, **especially because the form cannot be resubmit unless a field is changed**

I'm on redux-form 6.1.0 and `SubmissionError`s with only an `_error` key do not prevent repeated form submission, even without touching any fields. Only field-specific errors prevent submission as you described.

Even though using `_error` works, the documentation's description of `SubmissionError` (as you mentioned) does make it feel dirty using an `_error` for non-validation issues. It would be a nice enhancement to have a built-in method of communicating those types of errors from within a `handleSubmit` function!

I have a workflow that avoids this problem, with the trade-off of more complexity for more control. [`onSubmit` receives the redux `dispatch` function as a second parameter](http://redux-form.com/6.1.1/docs/api/ReduxForm.md/#-onsubmitsuccess-function-optional-). So, I place async form submission code inside of a redux-thunk action creator which I `dispatch` from `onSubmit` (always returning a promise from all functions). I then `dispatch` actions from the thunk to track the state of the request myself, and `connect` the form (or higher-level component) to that state. This allows dispatching non-validation errors and many other types of information to influence rendering.

For simple forms it feels like overkill. For more complex forms it can be convenient. It's probably too much code to post examples, but hopefully that paints a proper picture of one workaround.

**Comment by jampy** [comment]
> I'm on redux-form 6.1.0 and SubmissionErrors with only an _error key do not prevent repeated form submission, even without touching any fields. Only field-specific errors prevent submission as you described.

You're right. I'm using 6.2.0 and the problem seems to have disappeared. :)

**Comment by erikras** [comment]
I'm closing this based off @jampy's comment.
