### ISSUE TITLE
Following semver

### ISSUE THREAD

**Issue by johanneslumpe** [erikras/redux-form#19]
Are you willing to follow semver more closely? :) I know `redux-form` is very very young, but I feel that it might be a good thing now to at least signal breaking changes by bumping the minor version, instead of just the patch version. Thoughts on this?

**Comment by erikras** [comment]
Excellent suggestion. I'm an OSS n00b, and just learned about semver yesterday.

**Comment by johanneslumpe** [comment]
Ah ok cool, no worries :) Usually you'd bump the major version, if there is a breaking change, the minor version if you add new features which do not break old behavior and the patch version for bugfixes etc.

Some projects choose to add a disclaimer that pre-1.0 a bump in the minor version can contain breaking changes.

**Comment by erikras** [comment]
I mean, she's only 13 days old! :-)

It certainly _feels_ like the API is stabilizing, but who knows...

Thank you for your suggestion. I'm going to close this ticket for now, as it's not so much of an actionable item that can be completed, but a suggestion for going forward. I might even start a changelog!
