### ISSUE TITLE
[v6.0.5] Array field re-renders on value change

### ISSUE THREAD

**Issue by kokweng91** [erikras/redux-form#1907]
It works fine when the form it's not initialize with values, but when I set initial values for the field arrays, every value type into the input will cause a re-render

**Comment by patrickpoh** [comment]
Do you mean it will trigger an unregister action? 
For example, if u type on it, it will 'kick' you out of the field such that you have to click on the field again to continue typing.

**Comment by kokweng91** [comment]
yea, anyway I've solved it, just needa move render Field to outside of the class to prevent re-rendering.

**Comment by patrickpoh** [comment]
hey man! Im currently putting my render Field inside the class cause im using the state to make the dropdown function. you got any idea how i can do it if i shift it out of the class?

Just to be clear, my dropdown function is like if i click one button of the field. it will show more details of the field.

**Comment by kokweng91** [comment]
u can pass ur state as props like <Field something={this.props.something} >

**Comment by patrickpoh** [comment]
but i can't edit the things i pass in it if i place the renderFieldArray outside of the class. Cause i couldnt call setState etc
