### ISSUE TITLE
Async validation demo throws 'unhandled promise rejection'

### ISSUE THREAD

**Issue by dprentis** [erikras/redux-form#1908]
Trying to implement async blur validation, but getting 'unhandled promise rejection' error when a validation error is detected.

Have been implementing according to the demo here http://redux-form.com/6.0.5/examples/asyncValidation/ - which in fact throws the same error.

**Comment by akhayoon** [comment]
Can you show some code, you might be missing something.

I added both validate, asyncValidate and then asyncBlurFields['myfieldName'] and then returned the promise the same way they do in the asyncValidate.js in the example. 

It works after that, but it also prints the form error as an exception in the console.

**Comment by dprentis** [comment]
yes, it works, but I get the error in the console as you describe - no code needed, just check the demo page

**Comment by allapologies** [comment]
@dprentis @akhayoon 
Guys, do you have any ideas how to avoid this console.log errors? Throwing such errors in production code is not something that I expect :(

**Comment by gustavohenke** [comment]
I guess this was fixed in v6.1.0: #1843, #1297
