### ISSUE TITLE
Only one form works

### ISSUE THREAD

**Issue by DWboutin** [erikras/redux-form#191]
Hi,

I created a really simple project with a login form and another form with 3 fields. The second form won't work at all... I did exactly the same as the first one.

This is my reducers: https://github.com/DWboutin/Beverage/blob/master/src/reducers/index.js

My first form (Login form) is working well: https://github.com/DWboutin/Beverage/blob/master/src/components/forms/LoginForm.react.js

But my second form reload the page and nothing works. https://github.com/DWboutin/Beverage/blob/master/src/components/forms/RecipeForm.react.js

What did i do wrong? I have read the docs, but maybe i don't understand it well... Can i have some help please?

Thank you

**Comment by erikras** [comment]
What do you mean by "nothing works"? You can't type in the fields? Presumably its the `LoginForm`'s container that is dispatching the actions to your `login` reducer. You haven't yet made a `recipe` reducer?

**Comment by DWboutin** [comment]
When i do the recipe reducer and i submit my form, it reload the whole page and posting form values in the url.

**Comment by erikras** [comment]
I have no idea what this `formReducer()` function you are calling is. Don't do that.

> it reload the whole page and posting form values in the url

That sounds like it's not respecting your `onSubmit` prop and using the default `method="get"` html behavior, which is very, very odd.

Can you share a screenshot of your redux-devtools state, specifically `form > recipe`, values after you have filled out valid values into your recipe form and clicked submit?

**Comment by DWboutin** [comment]
This is my console infos about my handleSubmit function. I can't give you a screenshot about the onSubmit form because it do the submit no matter what i try (preventDefault, return false...)

![capture d ecran 2015-10-30 a 11 42 56](https://cloud.githubusercontent.com/assets/1322006/10850334/678c931c-7efb-11e5-9d19-90db4655116f.png)

**Comment by DWboutin** [comment]
I just pushed my last commits if you want to check

**Comment by DWboutin** [comment]
Any advices on how i can make it work?

**Comment by DWboutin** [comment]
Now, it's says that i have no onSubmit functions, but i have one.

This is my handleSubmit function: https://github.com/DWboutin/Beverage/blob/master/src/components/pages/RecipeCreatePage.js#L9-L13

And this is my component: https://github.com/DWboutin/Beverage/blob/master/src/components/forms/RecipeForm.react.js#L10-L29

![capture d ecran 2015-11-02 a 11 47 52](https://cloud.githubusercontent.com/assets/1322006/10888010/d686623a-8157-11e5-803a-f8ceec43b4e6.png)

**Comment by erikras** [comment]
I tried to run a fork of your example, but there seems to be a config file missing. When I renamed `config.dist.js` to `config.js`, it ran, but it seemed to be ignoring the `onSubmit` in the `<form>` and I couldn't put any console logs...maybe browserify was stripping them because I was using the production config or something?

Anyway, I gave you a couple of PRs to nudge you in the right direction, but I'm not entirely sure what your problem is.

**Comment by erikras** [comment]
Ah, I see you've upgraded to v3 now. Let me know how that goes. But do remove the `reduxMountPoint` config parameter.

**Comment by DWboutin** [comment]
the config.js is just this:

```
var config = {
  APP_PORT: 3000,
  ROOT_FOLDER: __dirname,
  API_URL: 'http://localhost:4000',
};

module.exports = config;
```

Not much... And Browserify don't have configurations. The login form work well too... I'll try to remove `reduxMountPoint`

**Comment by DWboutin** [comment]
With your pullRequest everything works. Thank you very much!

do this line must clear the whole form? Because the textarea doesn't reset his value. (do i create another issue about this?) 

```
dispatch(initialize('recipeForm', {})); // clear form
```

**Comment by erikras** [comment]
The fix for that is here: https://github.com/erikras/redux-form/issues/145#issuecomment-152090278

It's awkward, I know. I'll have to include it in a FAQ or something.

**Comment by DWboutin** [comment]
Thank you VERY much for your help! I'll try to write a good guide for redux-form in my SO question: http://stackoverflow.com/questions/33237818/react-redux-whats-the-best-way-to-handle-crud-in-a-form-component/33393459#33393459

**Comment by DWboutin** [comment]
It's seems that my login form doesn't work now... :S

**Comment by erikras** [comment]
I gotcha. Easy misunderstanding. https://github.com/DWboutin/Beverage/pull/3

**Comment by DWboutin** [comment]
This is very weird indeed... Why i pass a `onSubmit` prop on my container and it transform into a `handleSubmit` prop for my component?

Thank you

**Comment by erikras** [comment]
It's the (unwritten?) React naming convention.

#### `handleX` is what you name the function that you pass to the `onX` prop.
```js
render() {
  const handleClick = () => console.log('Clicked!');
  return <button onClick={handleClick}>Click me</button>;
}
```
Since the only way that redux-form can provide you with functionality is to pass it as a prop, it passes you a `handleSubmit` for you to pass to `onSubmit`.

**Comment by DWboutin** [comment]
Good, i'll take a good note of this!

Thank you

**Comment by lakesare** [comment]
I had the same issue with my page refreshing on form submit.
That was caused by me using passing `handleSubmit` instead of `onSubmit` in mapDispatchToProps. It was not very clear from docs for me that it would be the case.
