### ISSUE TITLE
Passing in a list of validation functions to the Field component

### ISSUE THREAD

**Issue by mikeengland** [erikras/redux-form#1910]
Hi,

Instead of having one validation function which runs when the form is validated, it would be really nice to be able to pass in specific validation functions that accept the field's value and return an error message if an error is found, or null if no error is found. Example functions would be NotNull, Regex, Minimum, Between etc...

This would enable developers to write easily-testable validation functions once and then re-use these across their applications without having to touch a large validation function. This is a common approach in Java and there is even a spec for this. Hibernate Validator is an example:
http://hibernate.org/validator/.

The error object could be constructed by iterating through all of the fields and running all  of the validation functions passed to the components.

Is there any appetite to add validation functionality like this in the future?

Thanks for your hard work on the module!
Mike

**Comment by SpainTrain** [comment]
@mikeengland would https://github.com/koorchik/js-validator-livr work for your use case?  We have been using it very effectively with redux-form, and as a bonus we have one validation spec for each field that we use across both our React app and Python backend servers.

If there is interest, we could easily extract the functions we use to turn livr rules into RF validation functions into a module and publish it on npm.

**Comment by mikeengland** [comment]
@SpainTrain This module looks like it solves a similar issue to what I was describing. Thank you for sharing it. I'd be very interested in seeing the code you are using to use this with Redux Form. Maybe you can share a gist or a repo here?

My ideal would still be to allow a validator prop to be added to the Field components, but this sounds like a good stop-gap solution. I'd like to see the ability to add a validation function that runs against the field's current value, whilst also having the ability to gain access to the entire form values in the validation functions if needed. The current implementation of running the validation function every time doesn't feel modular enough to me.

**Comment by twheys** [comment]
Looks like this got added as a feature http://redux-form.com/6.3.1/examples/fieldLevelValidation/

**Comment by gustavohenke** [comment]
You're right, @twheys!
