### ISSUE TITLE
InitialValues from component's props.

### ISSUE THREAD

**Issue by GolanPachu** [erikras/redux-form#1914]
Hi, I want to pass initialValues from the component's props.

I saw this issue: https://github.com/erikras/redux-form/issues/837, Which is exactly what I want but there is no solution there.

So how can I do it?

**Comment by patrickpoh** [comment]
hey man. do it in the componentWillUpdate lifecycle. 
when your props is "ready" , fire  this.props.initialize({yourstuff: nextProps.yourstuff});

**Comment by GolanPachu** [comment]
@patrickpoh Thanks man, works like a charm.

**Comment by mdboop** [comment]
For what it's worth, I ran into this same issue, but using `componentWillUpdate` fires every time the field is edited. I changed it to:

```javascript
componentDidMount() {
  this.props.initialize({ ...this.props.user });
}
```

That works just fine for me.
