### ISSUE TITLE
Are the docs wrong?

### ISSUE THREAD

**Issue by dagda1** [erikras/redux-form#1920]
Looking at [this](http://redux-form.com/6.0.0-alpha.4/examples/asyncValidation/) page, the fields are created like this:

```
        <label>Username</label>
        <Field name="username" component={username =>
          <div className={asyncValidating === 'username' ? 'async-validating' : ''}>
            <input type="text" {...username} placeholder="Username"/>
            {username.touched && username.error && <span>{username.error}</span>}
          </div>
        }/>
```

But if I try that in my app like this:

```
  <Field name="city"
         component={city =>
                    <input type="text" className="form-control" {...city}
                           placeholder="enter a city for a 5 day forecast"/>}/>
```

I get this error:

> Unknown props `input`, `meta` on <input> tag

The props passed to the component function contains an input property so it should look like this:

```
  <Field name="city"
         component={city =>
                    <input type="text" className="form-control" {...city.input}
                           placeholder="enter a city for a 5 day forecast"/>}/>
```

Where the spread operator is used with `city.input` instead of `city`.

Am I right or have I missed something.

**Comment by jdreesen** [comment]
You are looking at the docs for `6.0.0-alpha.4` ;)

**Comment by gustavohenke** [comment]
Yup, that docs were probably under heavy development at that time.
We had some other issues reporting problems with other examples, which have been fixed at some point.
