### ISSUE TITLE
Access to validation errors object (or field.error) in v6

### ISSUE THREAD

**Issue by sericaia** [erikras/redux-form#1923]
Hello,

I want to do something like what we do here with [selecting form values](http://redux-form.com/6.0.0-alpha.11/examples/selectingFormValues/), but for errors. I'm migrating from v5 to v6 and I need to access to validation/errors object to understand if there is any error and disable a button if there is. How can I do it with redux-form v6?

Thanks!

**Comment by erikras** [comment]
Is the `invalid` state of the entire form sufficient? If so, [use a selector](http://redux-form.com/6.0.5/docs/api/Selectors.md/).

**Comment by felix-d** [comment]
https://github.com/erikras/redux-form/pull/1932

**Comment by erikras** [comment]
Published fix in [`v6.1.1`](https://github.com/erikras/redux-form/releases/tag/v6.1.1).
