### ISSUE TITLE
[6.1.0] syncValidateFailed set to true after calling initialize

### ISSUE THREAD

**Issue by clayne11** [erikras/redux-form#1925]
On some of my wizard-style forms, I manually call the `initialize` action creator to initialize the form.

In `6.0.5`, if I initialized the form I would then be able to to submit the form immediately. In `6.1.0`, `syncValidateFailed` is getting set to true and I can't submit until I update a field at which point the sync errors are reevaluated and `syncValidateFailed` goes away.

I do have a field that's failing sync validation, however it isn't registered at the time so this shouldn't be causing the issue.

**Comment by erikras** [comment]
This must be related to #1892 #1819.

**Comment by chungeunkim** [comment]
+1 for this error. `syncValidateFailed` field will not go away until you fill in form and change its value.

**Comment by letranloc** [comment]
+1 `syncValidateFailed` will go away after the second `redux-form/CHANGE` event dispatched.

**Comment by andi5** [comment]
The wizard example is broken as well:
http://redux-form.com/6.1.0/examples/wizard/

**Comment by bmv437** [comment]
I'm seeing the same thing as @letranloc. Does #1945 solve this? and what's the ETA for release?
Thanks @ortex and @erikras!

**Comment by erikras** [comment]
Published fix in [`v6.1.1`](https://github.com/erikras/redux-form/releases/tag/v6.1.1).
