### ISSUE TITLE
[6.1.0] Form has been submitted even when async validation fails

### ISSUE THREAD

**Issue by diegohaz** [erikras/redux-form#1929]
In #1843, this change was made: https://github.com/elodszopos/redux-form/commit/73d60f8a75512e8b0fe16d3884f10f6994be8bd9

The test passes because [it still returns a rejected promise](https://github.com/erikras/redux-form/blob/f6e1fb9316f6201f259d0ce761908618513f2e0c/src/__tests__/handleSubmit.spec.js#L103)

Also, this test needs to be rewritten, because even if you return a resolved promise it passes (`catch` doesn't run).

**Comment by diegohaz** [comment]
A possible solution would be verifying if asyncValidation has returned something other than undefined, but I think it would be better to revert the PR. Uncaught promises isn't that thing.

**Comment by diegohaz** [comment]
I'll send a PR later today.

**Comment by erikras** [comment]
Published fix in [`v6.1.1`](https://github.com/erikras/redux-form/releases/tag/v6.1.1).

**Comment by diegohaz** [comment]
Thank you, @erikras . Can you publish the new version to npm?
