### ISSUE TITLE
How to access input element nested in Field?

### ISSUE THREAD

**Issue by felix-d** [erikras/redux-form#1933]
I use GoogleMaps API and its address autocomplete feature for one of my projects.

I have a `Field` for the address, but I need to provide its corresponding nested input form element to GoogleMaps API. 

With Redux Form <6 this was doable because it didn't require to use a `Field` wrapper component. Using React-Bootstrap, I could simply get the input through the `refs` chain e.g. `this.refs.addressField.refs.input`.

With Redux Form 6, I have a component wrapper around React-Bootstrap `<Input/>` that is passed to the `component` prop of my address `Field` component. 

```javascript
import { Input } from 'react-bootstrap';

class InputField extends Component {
  render() {
    const { type, placeholder, input, children } = this.props;
    return (
      <Input type={type} ref="bootstrap" placeholder={placeholder} value={input.value} onChange={input.onChange}>
        {children}
      </input>
    );
  }
};

...
import { Field } from 'redux-form';

<Field
  component={InputField}
  ref="address"
  type="text"
  name="address"
/>
```

Everything works well except I can't access the nested `input` from outside the `InputField` component, more specifically in my form component. The only way I found feels hackish, I wrap a span with an id `address` around the `Field` component and access the DOM directly.

```javascript
// form-control is set by react bootstrap
document.getElementById('address').getElementsByClassName("form-control")[0]
```

It works but I'm wondering if there is not a simpler solution to the problem. Thanks!

**Comment by shikelong** [comment]
+1

**Comment by JakeLin1024** [comment]
You could try(untested)
```
<Field
  component={InputField}
  ref="address"
  type="text"
  name="address"
  withRef="true"  <== add this
/>

this.refs.address.getRenderedComponent().refs.input
```

**Comment by felix-d** [comment]
`getRenderedComponent()` indeed worked 👍

**Comment by igorrKurr** [comment]
In case if anybody is interested in this topic, there is another way to achieve that:

```
import { TextInput } from 'react-native';

class TextField extends Component {
  render() {
    const { input, refName, ...rest } = this.props;
    return (
      <TextInput     
        ref={refName} 
        value={input.value} 
        onChange={input.onChange}
        {...rest}
      />
    );
  }
};
...

<Field
  component={TextField}
  name="address"
  refName={(ref) => this.input = ref}
/>

this.input  // <--- here we go!
```
And for topickstarting example it will look like:

```
this.input.refs.input
```

The trick here is to don't use `ref` name for property will be passed to underlying input component.

**Comment by vasymus** [comment]
Also, we can use
`
import {findDOMNode} from 'react-dom'
...
<FIeld component = {SomeCustomComponent} {...otherProps} ref = {this.getInputRef} />
...
getInputRef = (ref) => {
    if (ref) {
        const node = findDOMNode(ref)
        this.input = node.nodeName.toLowerCase() === "input" ? node : node.querySelector("input")
    }
}
...


`
