### ISSUE TITLE
Having a hard time getting default selected fields to work

### ISSUE THREAD

**Issue by dannymk** [erikras/redux-form#1938]
Initializing the form works perfectly as in the example:  http://redux-form.com/6.0.5/examples/initializeFromState/

However, setting default "selected" values is another story.  As you can see I use an action to return the default value of the "relist" field but the field remains unchecked.

![bug](https://cloud.githubusercontent.com/assets/131285/19222826/46e0379c-8e2f-11e6-8581-497b860d6cad.png)

The field is defined as such in the form:

            <div className="form-group">
              <label className="control-label">Relist</label>
              <div>
                <label className="radio-inline"><Field name="relist" component="input" type="radio" value="1" />1</label>
                <label className="radio-inline"><Field name="relist" component="input" type="radio" value="2" />2</label>
                <label className="radio-inline"><Field name="relist" component="input" type="radio" value="3" />3</label>
              </div>
            </div>

>export default connect( state => ({
    initialValues: state.newItemFormValues 
  }), {setDefaults})(NewItemFormComponent);

I have examined the example over an over and after two days I am still a little baffled as to why this is not working for me.  I am absolutely sure that there is something I am missing here but I can't figure out what.

>  "dependencies": {
    "axios": "^0.14.0",
    "core-js": "^2.0.0",
    "normalize.css": "^4.0.0",
    "react": "^15.0.0",
    "react-bootstrap": "^0.30.3",
    "react-dom": "^15.0.0",
    "react-redux": "^4.4.5",
    "react-router": "^2.8.1",
    "react-widgets": "^3.4.4",
    "redux": "^3.6.0",
    "redux-form": "^6.1.0",
    "redux-promise": "^0.5.3",
    "redux-thunk": "^2.1.0"
  }

**Comment by JakeLin1024** [comment]
Can you try { relist: '2' };  This is only weird thing I can see

**Comment by dannymk** [comment]
Does not matter.  I tried it both ways, an integer and a string.

**Comment by dannymk** [comment]
Ah!  Interesting.  In all this time I did not notice one thing.  If I go back to the root route and I come back to the form the default values are set.  It is like it needs to re-render the components once the default values are set.  I will continue to try things to see if I can get it to work.

**Comment by dannymk** [comment]
Seems like I have been bitten by the bug/feature:  [https://github.com/erikras/redux-form/issues/621](url)

**Comment by dannymk** [comment]
AH! Got it!  Had to pass: enableReinitialize:true as described in the example but not shown in the example :-)
