### ISSUE TITLE
Is there a way to get field values inside a form component?

### ISSUE THREAD

**Issue by zation** [erikras/redux-form#1939]
Let's say we have a form like below:

Boy Number: input
Girl Number: input
Total Number: {boyNumber + girlNumber}

I want to show the total number when body input or girl input changed. For now, I can use selector in the container and pass the totalNumber into this form. If this form will be used in multiple containers, the duplicated selector logic will be kind of trouble. If I can get the filed value inside the form component, this feature will be super easy and the form will be more reusable.

**Comment by JakeLin1024** [comment]
This is more of a question than a new feature.

Would [normalizing ](http://redux-form.com/6.0.5/examples/normalizing/) help?

**Comment by JakeLin1024** [comment]
Oops. Sorry. You meant real-time update on the total input? I guess normalizing doesn't help.

**Comment by zation** [comment]
@JakeLin1024 Thanks for response! Actually, Total Number is not an input, it's just a display, a text to show the total number of boy and girl. I've checked the normalizing document. I think it can implement this kind of feature, will try it later. But from the semantic side, I think normalizing should not use for a text display...

**Comment by Aaronius** [comment]
@zation take a look at the [`Fields` example](http://redux-form.com/6.0.5/docs/api/Fields.md/). You would do something like:

```
<Fields names={[ 'boyNumber', 'girlNumber' ]} component={renderTotal}/>
```

Where `renderTotal` would add the values of the two fields and display the result.

**Comment by zation** [comment]
@Aaronius Thanks! This is a perfect solution! I'll close this issue
