### ISSUE TITLE
[6.1.0] Validation error bug

### ISSUE THREAD

**Issue by khakulov** [erikras/redux-form#1940]
Following code brings validation error! There are no validation error on 6.0.x 

``` javascript
function validate(values) {
  return {
    email: values.email ? null : messages.EMAIL_REQUIRED_ERROR,
    password: values.password ? null : messages.PASSWORD_REQUIRED_ERROR,
  };
}
```

**Comment by dmason30** [comment]
If syncErrors has properties then it currently returns as not valid regardless of that properties value. As a work around you need to be selective about which fields you return.

**Comment by khakulov** [comment]
no, the validate function returns an object with explicit value on properties, that says that there are and error on this property or not.

**Comment by dmason30** [comment]
Yes that is what i said, but there is a bug.

if state has:
```
syncErrors: {
   email: null,
}
```

then it is going fail submitting as it is treating email as an errored field as it is clearly not checking the value,

**Comment by ortex** [comment]
@khakulov Check this behavior in [v6.1.1](https://github.com/erikras/redux-form/releases/tag/v6.1.1)

P.S:
See [documentation](http://redux-form.com/6.1.1/docs/api/ReduxForm.md/)

> 
> validate : (values:Object, props:Object) => errors:Object [optional]
> 
> a synchronous validation function that takes the form values and props passed into your component. If validation passes, it should return {}. If validation fails, it should return the validation errors in the form { field1: <String>, field2: <String> }. Defaults to (values, props) => ({}).
> 
> See Synchronous Validation Example for more details.

**If validation passes, it should return {}.**

**Comment by gustavohenke** [comment]
@ortex put it clearly.
