### ISSUE TITLE
shouldAsyncValidate don't contain link to props of an object

### ISSUE THREAD

**Issue by vstebunov** [erikras/redux-form#1947]
Why shouldAsyncValidate don't contain link to props of an object, like asyncValidate?

**Comment by danielrob** [comment]
Sorry you didn't get a response! Usage like these may gain more responses on StackOverflow (the issue tracker is primarily for bugs/feature requests). shouldAsyncValidate has a validate parameter that receives props just like asyncValidate function. Essentially the difference is that the former provides much more configurability, while asyncValidate just runs at the default time (onblur and onsubmit).

**Comment by danielrob** [comment]
Apologies that last comment was wrong, I should not read documentation on mobile when header sizes are nearly the same! If this issue is still relevant, perhaps you could expand on your use case and request a re-open?
