### ISSUE TITLE
redux-form 6.1.0 Warning: Unknown prop `meta` on <div>

### ISSUE THREAD

**Issue by westpsk** [erikras/redux-form#1952]
when I run the example of react-widgets , It has warnings, since I found the same issue has fixed ^ 6.1.0 ?  but I when I run still found this...  

```
warning.js:36 Warning: Unknown prop `meta` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by Widget)
    in Widget (created by DropdownList)
    in DropdownList (created by Uncontrolled(DropdownList))
    in Uncontrolled(DropdownList) (created by renderDropdownList)
    in renderDropdownList (created by ConnectedField)
    in ConnectedField (created by Connect(ConnectedField))
    in Connect(ConnectedField) (created by Field)
    in Field (created by ReactWidgetsForm)
    in div (created by ReactWidgetsForm)
    in form (created by ReactWidgetsForm)
    in ReactWidgetsForm (created by Form(ReactWidgetsForm))
    in Form(ReactWidgetsForm) (created by Connect(Form(ReactWidgetsForm)))
    in Connect(Form(ReactWidgetsForm)) (created by ReduxForm)
    in ReduxForm
    in div (created by b)
    in div (created by b)
    in div (created by b)
    in div (created by b)
    in b
    in Provider
```

**Comment by westpsk** [comment]
something wrong with my version? 
![snip20161013_1](https://cloud.githubusercontent.com/assets/12495017/19318648/2202cffc-90dc-11e6-91f2-ac230f4b974d.png)

**Comment by thprapav** [comment]
Not a real solution but manually modifying node_modules/react-widgets/lib/Widget.js (line 46) and adding meta prop fixed the warning for me.

`var props = _objectWithoutProperties(_props, ['meta', 'className', 'tabIndex', 'open', 'dropUp', 'disabled', 'readOnly', 'focused']);`

"react": "15.3.2",
"react-widgets": "3.4.4",
"redux-form": "6.1.0",

**Comment by n0ne** [comment]
I changed function:

      const renderDropdownList = ({ input, meta, ...rest }) =>
          <DropdownList {...input} {...rest} />

**Comment by paulhands** [comment]
@gustavohenke I tried using the updated example as you have linked to and still received the same error message. However that disappeared when I tried @n0ne 's solution. Just a heads up

**Comment by gustavohenke** [comment]
Will fix this in the docs.

**Comment by gustavohenke** [comment]
@erikras, while looking at the examples in order to fix this, I discovered that the code is very different to what is shown in the docs.

See:
- https://github.com/erikras/redux-form/blob/v6.5.0/examples/react-widgets/src/ReactWidgetsForm.js
- http://redux-form.com/6.5.0/examples/react-widgets/

**Comment by jhwheeler** [comment]
I'm getting the same warning, but not doing anything related to react-widgets. Should I open a new issue and post my code there?

**Comment by gustavohenke** [comment]
It seems like this was really fixed in earlier versions of the docs.
