### ISSUE TITLE
Getting access to redux dispatch in reduxForm connected component

### ISSUE THREAD

**Issue by tnrich** [erikras/redux-form#1953]
Hey there,

I am just wondering if there is a reason that redux-form doesn't pass dispatch to the component reduxForm wraps. 

For example:

```
var CreateCutsite = reduxForm({
  form: 'customEnzymes', 
  initialValues: {
    name: 'Example Enzyme',
  },
  validate
})(MyComponent)
```

Why does MyComponent not have access to redux's dispatch method?

It seems like I'll need to go through a second wrapping in order to get dispatch:

```
var CreateCutsite = reduxForm({
  form: 'customEnzymes', 
  initialValues: {
    name: 'Example Enzyme',
  },
  validate
})(connect()(MyComponent))
```

Wouldn't this be easier if reduxForm just passed dispatch along with its other props?

Thanks!
Thomas

**Comment by tnrich** [comment]
Hmm upon further inspection, it looks as if the dispatch is being "eaten" by the <Fields/> component. 

I am passing dispatch in to my fields component like this: 
```
<Fields names={[
    'sequence',
  'name',]} {...props} component={MyComp}
```
where dispatch is one of the properties on the props object

But dispatch never makes it to the props of MyComp.

I think that it must be getting stripped by the Fields component. Can you verify that this is indeed the case?

Thanks!

**Comment by gustavohenke** [comment]
2+ years without a comment here, so I'm closing!

**Comment by FatehAK** [comment]
Same issue here `dispatch` prop is being eaten up by the `<Field/>` component.

**Comment by iamandrewluca** [comment]
@FatehAK @tnrich You can access dispatch using `meta.dispatch`
https://github.com/redux-form/redux-form/blob/ccebdcd0270edd699b9c381a65fefe742fdadc90/src/createFieldProps.js#L143
