### ISSUE TITLE
How to get fields' status

### ISSUE THREAD

**Issue by snowcxt** [erikras/redux-form#1954]
What is the proper way to get the fields' status? I'm using this code:

``` js
@connect((state, props) => ({
  fields: state.form['formName'] && state.form['formName'].fields
}))
```

**Comment by slavab89** [comment]
You are able to get the fields status (pristine, dirty etc.) from within the render function of the field.
The redux store only holds the values and field names, everything else can be found in the props of each element (Form, Field, FieldArray etc.)

**Comment by snowcxt** [comment]
I want to show something based on the current active field. What's the best practice?

**Comment by slavab89** [comment]
I may not understand what exactly you need heh but do the active field is the one that has focus on, right?

So inside some field you might access it

```javascript
renderComponent(props) {
    const active = props.meta.active;
    // And do what you want with the active indication
    return (<input ....... />
}

<Field name="myInput" component={renderComponent} />
```

If you want to show something entirely different on the page, say write the current active field that maybe you can 'listen' on the redux-form/FOCUS action (not sure its the correct name heh) and then save in your store the focused field and then use that information for.. something?

**Comment by davincho** [comment]
Probably my question is similar to @snowcxt one:
How do you access the status of a field outside of its render function?
In my case I would like to render an error summary of fields, but only those that have been 'touched'.

**Comment by srosset81** [comment]
I also need to know, within my Form component, weither or not a Field is pristine.
Maybe a formPristineSelector could be introduced? Or better yet, a formFieldSelector() which would contain all the different status of a field? (value, error, touched, pristine...)

**Comment by kellyrmilligan** [comment]
in my case, I have 2 fields, and 1 label( a month and year selector). I would like to make the label for both red if either one has an error. I can't get the meta values to accurately do this from what I am reading in this thread.

**Comment by alex-shamshurin** [comment]
There is a special selector `getFormMeta('myForm')(state)` to take meta data from the form level, but I cannot get it work. The goal is conditional rendering field label depending upon whether the field is active or not. Is this an issue with selector?

**Comment by gustavohenke** [comment]
@alex-shamshurin @davincho @srosset81 @kellyrmilligan @snowcxt 
See https://codesandbox.io/s/A0o8Zvn9. `getFormMeta` was introduced as of [v6.7.0](https://github.com/erikras/redux-form/releases/tag/v6.7.0).

This may not be enough for some of your needs (eg it doesn't return whether a field is dirty), but it may help you start.
In case you need more meta data to be returned by this selector, please open a new issue as a feature request.

**Comment by danielrob** [comment]
https://github.com/erikras/redux-form/issues/3103#issuecomment-312556081 may be useful for anyone reading this thread.

**Comment by chris-verclytte** [comment]
Here is how I dealt with it if it can help someone:
```
const Form = connect((state, ownProps) => {
  const meta = getFormMeta(ownProps.form)(state)
  const active =
    (meta && Object.keys(meta).find(field => meta[field].active)) || null

  return { active }
})(Form)
```

Thus it will refresh the form with `active` property set to the name of the field having focus.
