### ISSUE TITLE
Example for React native - Immutable - Redux

### ISSUE THREAD

**Issue by axelardu** [erikras/redux-form#1955]
Hi,

Is it possible to get an example for react-native with rexux & immutable with the latest (6.1.0) tag?
Did not find an example anywhere.

Thanks!

**Comment by bitdivine** [comment]
I just went on a hunt for examples of redux-form as there are none in the examples section http://redux-form.com/6.1.1/examples/  This is what I found:

* Without immutable, this was enough to get me up and running: https://gist.github.com/namelos/34c042c7a6f88808088b17de258a34c4
* With immutable, this SO question very nearly has a working example - see the comments: https://stackoverflow.com/questions/39331420/cant-get-redux-form-6-0-2-working-with-react-native-0-32-0

HTH.

**Comment by bitdivine** [comment]
By the way, I found http://beerpay.io yesterday.  Erik, you should sign up.  I'd buy you a beer.  It's not quite as cool as "Send money every time I comment :beer: on Github" but I guess it's close enough! :-)

**Comment by mschipperheyn** [comment]
I use redux-form in react-native. Do you have any specific issues?

**Comment by bitdivine** [comment]
Yes.  A lack of examples.  As a complete react novice this was a bit of a problem.  But that is now solved and I have my forms all wired up! :-)

**Comment by JeroenNelen** [comment]
@mschipperheyn  and @bitdivine I'm currently bumping into these errors after submitting a form:

I switched to use the formReducer from redux-form/immutable, but when I then submit a value I get the following errors (I added the .toJS() to the values object that I receive in the handleSubmit function):
```
ExceptionsManager.js:62 One of the sources for assign has an enumerable key on the prototype chain. This is an edge case that we do not support. This error is a performance optimization and not spec compliant.handleException 
@ ExceptionsManager.js:62handleError 
@ InitializeJavaScriptAppEngine.js:120reportFatalError 
@ error-guard.js:30guard 
@ MessageQueue.js:47callFunctionReturnFlushedQueue 
@ MessageQueue.js:104onmessage 
@ debuggerWorker.js:44
ExceptionsManager.js:82 
Unhandled JS Exception: One of the sources for assign has an enumerable key on the prototype chain. This is an edge case that we do not support. This error is a performance optimization and not spec compliant.reactConsoleError @ ExceptionsManager.js:82console.error @ YellowBox.js:61logIfNoNativeHook @ RCTLog.js:38__callFunction @ MessageQueue.js:234(anonymous function) @ MessageQueue.js:105guard @ MessageQueue.js:45callFunctionReturnFlushedQueue @ MessageQueue.js:104onmessage @ debuggerWorker.js:44
ExceptionsManager.js:82 Warning: performUpdateIfNecessary: Unexpected batch number (current 29, pending 27)
```

I can dismiss the errors and continue but that's not really an option. Anyone any clue?
I'm not using Object.assign anywhere in my own code because I'm working with Immutability...

Kind regards,


the problem is further illustrated in this thread: 
https://github.com/erikras/redux-form/issues/1744 
any suggestions are more than welcome as I'm a bit stuck with this issue...

**Comment by mschipperheyn** [comment]
I don't use redux-form/immutable

**Comment by erikras** [comment]
Published fix in [`v6.4.2`](https://github.com/erikras/redux-form/releases/tag/v6.4.2).

**Comment by esbenp** [comment]
[I made an example repository right here.](https://github.com/esbenp/react-native-redux-form-example/tree/master/src)

[I also wrote an in-depth article about the subject here](http://esbenp.github.io/2017/01/06/react-native-redux-form-immutable-styled-components/)

**Comment by sbalay** [comment]
[Here's another post with some examples](https://t.co/AGysIhRS8A). Hope it helps!
