### ISSUE TITLE
[v6] Conditionally hiding Fields based on values from other Fields

### ISSUE THREAD

**Issue by creativenode** [erikras/redux-form#1960]
I'm trying to work out the best approach to hide a field, or a number of fields, based on the value given in another field. My app has been updated from v5, where this was a trivial matter, as the field values were available and the form rendered on changes. The v5 examples covered this, I can't see anything in the v6 examples.

One example scenario is if the user chooses a particular `select` option a series of fields would appear. I've read threads using `display: none` but that feels wrong, but what mechanism do you use to trigger the change? How to I weave that into the redux-form Field component?

This is what I'm struggling with. How I trigger the state change from within the Field Component? Then once I understand how the trigger happens do I store the state in my redux-form components  state or in the redux store? I'd like to use redux and create the necessary action and reducer.

Any input would be gratefully received.

**Comment by ToxicSalt** [comment]
You can use [http://redux-form.com/6.1.0/docs/api/FormValueSelector.md/](formValueSelector()) to pass field values into your form's props. Then you can conditionally render other fields based on the value of the prop.

**Comment by creativenode** [comment]
Thank you for your comment, sometimes you just can't see something in plain sight!

**Comment by gkatsanos** [comment]
@DylanSimowitz this link is broken.

**Comment by DylanSimowitz** [comment]
@gkatsanos http://redux-form.com/6.6.3/docs/api/FormValueSelector.md/

**Comment by timscott** [comment]
Using `formValueSelector` depends the component holding the field knowing what form it's in, which it might not in the case of composed forms. It also will not do the job if the field is inside a `FieldArray` in which case the field name will have an unknowable prefix.

There need to be some way to get field values apart from higher order of composition.

**Comment by kktam** [comment]
The new demo example is located in this link [http://redux-form.com/6.0.5/examples/selectingFormValues/](http://redux-form.com/6.0.5/examples/selectingFormValues/)

**Comment by erikras** [comment]
Say you want to show field B if and only if field A's value is > 20.

Another option, aside from the `formValueSelector` everyone else has put forward here, is to connect to the state of both fields using [`<Fields/>`](http://redux-form.com/7.0.1/docs/api/Fields.md/). You can render field A with a regular `<Field/>` component, and then render field B with `<Fields/>`, using only the `input.value` data from field A.

Make sense?
