### ISSUE TITLE
Show Validation Like Spotify Sign up

### ISSUE THREAD

**Issue by andrerecinto** [erikras/redux-form#1962]
Hi there, I'm looking for some guidance on how to show validation. I'm trying to model our form validation like Spotify's signup. The criteria is to only show validation ONLY when the form input has been previously touched AND has been dirty'd up before (they have inserted a value BUT have removed it or changed from the original value).

When you initially land on the page and start tabbing through the inputs WITHOUT putting any values, you'll notice you won't see any validation messages. But if you go back to the input and add some value, that's when the error messages display. 

I've been trying a combination of meta.touched, meta.dirty, meta.visited and I just can't get the right combination to get it to behave like Spotify's form. I noticed meta.dirty toggles according to the form value, meaning if you have a value, then it is set to true, but if you remove that value, it becomes false again... Is there a meta property that gets toggled once for when a user inputs a value? Kind of like how meta.visited is toggled only once for onFocus?

Any help would be greatly appreciated. 

Thanks.

https://www.spotify.com/us/signup/

**Comment by Aaronius** [comment]
What if you set `touchOnBlur` to `false` and `touchOnChange` to `true`? See http://redux-form.com/6.1.0/docs/api/ReduxForm.md/.

**Comment by andrerecinto** [comment]
Thank you :) That got me where I needed to be!
