### ISSUE TITLE
6.1.0 Validation a Keypress Behind?

### ISSUE THREAD

**Issue by digitaldawn** [erikras/redux-form#1963]
Apologies in advance - my developer terminology is awful - I'll do my best to explain the situation...

I upgraded an application yesterday to 6.1.0 and my tests now appear to be broke as validation on wizard forms seems to be a keypress behind. After spending a while debugging I checked the documentation again and was able to replicate on the examples there - so I presume this is a bug...

**To Replicate:**
1. Go to http://redux-form.com/6.1.0/examples/wizard/
2. Type a single character into the 'First Name' field and a single character into the 'Last Name' field. 
3. Click next.
4. You should notice that the page doesn't take you to the next page.
5. If you add another keystroke to any input in the form, that button will re-activate. 

---

I was unable to replicate this in 6.0.5 (http://redux-form.com/6.0.5/examples/wizard/) so presume this is a bug introduced in 6.1.0?

---

PS. Really appreciate the teams work on redux-form. Really is fantastic to use! Keep it up!

**Comment by ortex** [comment]
It was fixed in #1925 and released in [v6.1.1](https://github.com/erikras/redux-form/releases/tag/v6.1.1)

**Comment by gustavohenke** [comment]
Thanks @ortex 👍
