### ISSUE TITLE
Does this module work with angular 2?

### ISSUE THREAD

**Issue by Redigast13** [erikras/redux-form#1968]
Hello! I use angular 2 with [ng2-redux](https://github.com/angular-redux/ng2-redux) module. Is it possible to use this `redux-form` module with angular 2? I create forms in angular 2 using [ReactiveFormsModule](http://blog.thoughtram.io/angular/2016/06/22/model-driven-forms-in-angular-2.html).

**Comment by davidkpiano** [comment]
Unfortunately not. This is heavily tied in to React, despite the name.
