### ISSUE TITLE
Include parent elements in form examples

### ISSUE THREAD

**Issue by thedamon** [erikras/redux-form#197]
I have been spending a lot of time trying to find how to properly set up a form and run into a number of issues and confusions; and I'm finding a lot of similar questions in the issues here. 

I think that if the examples included the code behind parent elements that make everything work, this would help a lot for people starting off with the library!

**Comment by erikras** [comment]
Most of the examples are passing no extra props to the form components.

**Comment by afhammad** [comment]
i'm with @thedamon. No where in the documentation or examples is it mentioned how to populate the form (for example when editing an existing record), after digging through the issues i found a link (https://github.com/erikras/react-redux-universal-hot-example/blob/master/src/containers/Survey/Survey.js) to this which showcases the parent component using the initialize prop to pass the state

**Comment by thedamon** [comment]
@erikras sure thing.. I guess, but reading the docs I don't know that! 

It's always nice to "see" the whole picture so I can more easily write off issues.. especially bc a few version issues will result in errors like 'did not pass in required prop dispatch' or things like this.
I could save some time and worry if I could see immediately that this wasn't supposed to be necessary.

**Comment by jpierson** [comment]
@thedamon, Looking through that survey sample in hopes that it may help lead me to a solution to issue #209 I ran into what looks like an operator `::` that I'm unfamiliar with. I've attempted to google it to make sense out of it but often like other symbolic operators they don't lend themselves well to text based queries.

**Comment by erikras** [comment]
`::this.someMethod` is shorthand for `this.someMethod.bind(this)`.

**Comment by erikras** [comment]
I will keep this in mind as I build out new examples. So far, there is nothing of interest in the thing calling the examples, but the repo containing the examples is [freely available to be run locally](http://erikras.github.io/redux-form/#/examples).

**Comment by anorudes** [comment]
+1. Where can i see full example? I don't know how to get state form on submit and call "e.preventDefault();"
Erikras, can you help me?)

I want to make this code work:
```
  onAdd(e, data) {
   console.log(data);
    e.preventDefault();
  }
```
```
<form onSubmit={this.onAdd}>
```

All examples don't have example submit code =(

**Comment by erikras** [comment]
@anorudes At the top of the page that I linked to, where it says "To download and run these examples locally, ..."

Your `onSubmit={this.onAdd}` example is wrong. You need to look at the `handleSubmit` entry on [the `props` API page](http://erikras.github.io/redux-form/#/api/props).
