### ISSUE TITLE
[v6] Action for after INITIALIZE (dynamic content)

### ISSUE THREAD

**Issue by slavab89** [erikras/redux-form#1970]
Hi,
So i've been using this module for a few weeks and its AWESOME!!
I do have some problem that i'm facing and i'm not sure how to address it.

I have a form that has some static fields and a table. The table represents an array of objects that i have so each row is an object.
Lets say its a class with a bunch of students - the students will be in the table.
Because this table data is an array its dynamic therefore there are REGISTER_FIELD actions fired after the 'initial' render (This can take several seconds even).
I want to block the user from being able to edit the data until all the table is loaded (Show a spinner or something) but i'm not sure how to do that.
I know there is an INITIALIZED action but its not a promise or something and it just tells me that the form begins its loading..

Is it possible to do such a thing? Somehow?

**Comment by gustavohenke** [comment]
> I want to block the user from being able to edit the data until all the table is loaded (Show a spinner or something) but i'm not sure how to do that.

You can do that by using Redux itself - when your request starts, you set in your store `loading = true`. When your request finishes, you set `loading = false`, plus the data.
[redux-request-state](https://www.npmjs.com/package/redux-request-state) is probably able to help you with this task.
