### ISSUE TITLE
How to notify custom field components of validate/submit event?

### ISSUE THREAD

**Issue by alvaro1728** [erikras/redux-form#1972]
I have a custom component (Foo) with its own state and data and it needs to know when the form is being submitted so that it can validate itself and either prevent the submit (by failing), or finalize its data and allow the submit to proceed.  So it looks something like this:

```
  renderFoo({ input: {value, onChange} }) {
    return (
      <Foo value={value} onChanged={onChange} />
    );
  }

  render() {
    return (...
        <div className="form-group">
          <label htmlFor="foo">Foo:</label>
          <Field name="foo" component={this.renderFoo} />
        </div>
    );
  }
```

How do I notify Foo that the form is being submitted/validated and that it should return false if the data isn't valid?

Thanks,
Alvaro

**Comment by danielrob** [comment]
You can use field level validation for this  now, see http://redux-form.com/7.0.3/examples/fieldLevelValidation/. Sorry it took ten months! Does this answer your question?

**Comment by gustavohenke** [comment]
Closing due to low activity.
