### ISSUE TITLE
Allow initialValues to be a function, not just object

### ISSUE THREAD

**Issue by sergeyzwezdin** [erikras/redux-form#1973]
It would be very handy, if we can pass function to initialValues property instead of object like this:

``` javascript
reduxForm({
  form: 'form1',
  initialValues: () => {
    return {
      field1: 'my value'
    };
  }
})
```

This very useful when form initial state changed during the time. For now, I'm not sure how to change initial values. The only idea is to dispatch `INITIALIZE` message, but it looks for me as some kind of hack.

**Comment by clayne11** [comment]
There's nothing wrong with dispatching the `INITIALIZE` action. It's not a hack, you just have an advanced usage of the library that most people don't need. The full power of `redux` actions is always available if you need to perform an advanced feature that isn't baked into the library.

**Comment by gustavohenke** [comment]
@clayne11 is right. I fail to see the point of accepting a function.

Also, most of the times my `initialValues` are changed in the state-to-props conversion made possible by `@connect()` from react-redux.
