### ISSUE TITLE
FieldArray shouldComponentUpdate problems

### ISSUE THREAD

**Issue by svsool** [erikras/redux-form#1975]
Hi, I think we must use custom shouldComponentUpdate for ConnectedFieldArray component. When we using FieldArray all fields props writes as own properties of array and deepEqual works wrong in this case:

```
const state1 = [];
const state2 = [];
state1.touched = true;

deepEqual(state1, state2); // true
// shouldComponentUpdate in ConnectedFieldArray will return false, but this wrong behaviour, because props changed
```

But component must be rerendered.

I get this bug when resubmitting form with FieldArray and validation errors not rendered, because shouldComponentUpdate return false. In result user don't understand why he can't submit form, because don't see validation errors

PR #1976

**Comment by erikras** [comment]
I'm not sure I understand the the problem. Can you add a test in the PR that would fail before your fix but passes after?

**Comment by jeremy-carbonne** [comment]
I have a similar problem with rendering with fieldArray, I have a drag and drop when I call fields.move the field doesn't rendering all the time

> fieldArray render
> fields.move 1 -> 2
> fields.move 2 -> 3
> fields.move 3 -> 2
> fields.move 2 -> 1
> fields.move 1 -> 0
> fieldArray render
> fields.move 0 -> 1
> fieldArray render
> fields.move 1 -> 2
> fields.move 2 -> 3
> fields.move 3 -> 2
> fields.move 2 -> 1
> fields.move 1 -> 0
> fieldArray render



When i commented shouldComponentUpdate in ConnectedFieldArray.js, i have no problem


> fields.move 0 -> 1
> fieldArray render
> fields.move 1 -> 2
> fieldArray render
> fields.move 2 -> 3
> fieldArray render
> fields.move 3 -> 2
> fieldArray render
> fields.move 2 -> 1
> fieldArray render
> fields.move 1 -> 0
> fieldArray render
> fields.move 0 -> 1
> fieldArray render
> fields.move 1 -> 2
> fieldArray render
> fields.move 2 -> 3
> fieldArray render

**Comment by svsool** [comment]
issue was fixed in commit https://github.com/erikras/redux-form/commit/3203db2136e6149fbd1be85ddd3d4b999771253a
