### ISSUE TITLE
Developing process

### ISSUE THREAD

**Issue by VladimirPal** [erikras/redux-form#1986]
Hi guys!
Currently i am working on some redux lib and trying to discover your really great project.
And i don't understand how you develop it?
I see examples and commands in package.json, but i have to rebuild the whole lib each time i change something.
I can plug redux-form to my own example and use it from src or use webpack alias, but I think i miss something, give me advise please.

**Comment by VladimirPal** [comment]
@erikras @mihirsoni Can you share your experience?

**Comment by gustavohenke** [comment]
@VladimirPal for this type of stuff it'll probably be better if you ping @erikras at Twitter
