### ISSUE TITLE
how to pass my form name to `formValueSelector` when use `form` props to pass name for form component

### ISSUE THREAD

**Issue by alirezavalizade** [erikras/redux-form#1987]
```
items.map((data)=>{
  return(
<CreateYourOwnPackageProductItemForm form={`CreateYourOwnPackageProductItemForm${data.uid}`}
                                               onSubmit={this.onSubmit}
                                               initialValues={data}
                                               test={this.test}
          />
);
})

```

im use Multirecord Form version 6,im want connect to values in my form component,according to documents we should pass the name to `formValueSelector` function...
`
formValueSelector('*****FORM NAME****')`

and i dont know my forms names...how to handle this?

**Comment by kinyat** [comment]
```javascript
export default reduxForm({
  form: 'YOUR_FORM_NAME_HERE', 
  validate
})(CreateYourOwnPackageProductItemForm)
```

**Comment by alirezavalizade** [comment]
@kinyat :|

**Comment by gnarf** [comment]
something like
```js
const formName = `MyForm${data.uid}`
<YourForm form={formName} formName={formName} />
```
would give you `formName` in your form component.

you could also wrap that functionality in your classes' export: 

```js
const Form = reduxForm({...})(CreateYourOwnPackageProductItemForm)
export default props => <Form {...props} formName={props.form}>{props.children}</Form>
```

**Comment by gnarf** [comment]
(in the realm of quick workarounds that might help you...)

I think parts of that information might also be on the `_reduxForm` in `context`

**Comment by gnarf** [comment]
oh actually - lol -- I forgot it just passes along that prop as `form` anyway, so you can use that

**Comment by rizedr** [comment]
@alirezavalizade to be fair, `formValueSelector` is just another thunk, meaning it will return a function, thus you can do something like this:
```
const mapStateToProps = (state, initialProps) => {
  return {
    myField: (formValueSelector(initialProps.form))(state, 'myField'),
  };
};
```

Where `initialProps.form` is the name of your form.

Might have come a little late to the party but I think others might find this useful. @gustavohenke I think this is ready to be closed.

**Comment by gustavohenke** [comment]
Thanks for the heads up, @rizedr.
