### ISSUE TITLE
Normalizer Doesn't Show Formatted Value on Initial Load

### ISSUE THREAD

**Issue by andrefox333** [erikras/redux-form#1988]
Hi, 

I have a form that has a phone normalizer (similar to the example [here](http://redux-form.com/6.1.1/examples/normalizing/)) and I'm using it strictly for UI view purpose only. I have some code that strips out all non-numeric characters before it submits it to the server.

My issue is, when I reload this existing data (i.e editing an existing form and loading it with initialValues), I'm expecting to see the phone number field to render in (555) 555-1212 format but instead I see it in 5555551212 (which is the raw value from server) **UNTIL** I focus in and out of the field then it goes into the format I want.

Any suggestions?

Thanks :)

A short video clip of the issue
https://drive.google.com/open?id=0B9Ib6hMl5grMSkRVRHRtVzcwTU0

**Comment by ashwinvandijk** [comment]
I have the same issue. I even tried calling the blur, and change functions manually, but that also doesn't seem to work.

**Comment by rafaelbiten** [comment]
Same thing here and I was wondering if any of you found a solution for this problem...

**Comment by rafaelbiten** [comment]
Oh, this is still a problem if you want to keep your Form component as a simple stateless component like I do, cause you can't use redux-form `initialize` inside a stateless component. Now that I'm passing initialValues when mapping state to props, I have this problem again =/

**Comment by rafaelbiten** [comment]
Ok, I think I finally understood the problem and how to get around it:

Using `format` instead of `normalize` did the trick for me.
`format` doesn't actually change the data you have on your store like the `normalize` does so, if you want to do that, then use both.

```
<Field component={MyCustomInputField} name="phone" format={normalizePhone} normalize={normalizePhone} label="Phone" type="tel" />
```

`format` is the first part of the [Value Lifecycle Hooks](http://redux-form.com/6.2.0/docs/ValueLifecycle.md/)

Hope this helps!

**Comment by andrefox333** [comment]
@rafaelbiten adding format worked for me :)

**Comment by pcgilday** [comment]
Like @rafaelbiten pointed out, the [Value Lifecycle Hooks](http://redux-form.com/6.2.0/docs/ValueLifecycle.md/) point out the difference in format and normalize functions.

> I'm using it strictly for UI view purpose only.

This is exactly what the `format` prop is for. 

The normalize prop is for a function to normalize the data before it goes into the redux store, this is why it is intentionally not called until after a user interaction. This is detailed in the value lifecycle hooks diagram linked to above. 

@andrefox333 - It appears this has been resolved, if that is the case, it may be helpful to close the issue and lighten the amount of issues @erikras has to sort through 😄

**Comment by andrefox333** [comment]
Thanks again :) i appreciate all the support!

**Comment by sydinh** [comment]
@andrefox333 @rafaelbiten I have the same issue now. It catchs me that `Uncaught TypeError: value.replace is not a function`
Please, help me!
