### ISSUE TITLE
Bug: UNREGISTER_FIELD called when component Field is mounted in gets unmounted (even with destroyOnUnmount: false)

### ISSUE THREAD

**Issue by mschipperheyn** [erikras/redux-form#1990]
I have a problem with a wizard like structure that contains of various components that each have a structure like so.

```
@reduxForm({
  form: 'posteditor',
  validate,
  destroyOnUnmount:false,
})
class FuturePostModal extends Component {
```

So, each is referencing 'posteditor' as form in order to centrally store the input data. Some of the field components are part of Modals. So, the Field is part of one component and the actual field editor is opened as part of a Modal, something like this.

```
class PostActionComponents extends React.PureComponent {

  constructor(props) {
    super(props);
  }

  render() {
    return (
      <View>
        { this.getTagsModal() }
      </View>
    );
  }

  getTagsModal(){
    const { tagModalIsVisible, tags } = this.props.state;
    return (
      <TagModal
          modalVisible={tagModalIsVisible}
          onClose={this.onCloseTagModal}
          onCancel={this.onCancelTagModal}
          tags={tags}
          visible={tagModalIsVisible}
          />
     )
  }

  onCloseTagModal(selectedItems = []){
    const { actions } = this.props;
    actions.saveTags(selectedItems);
    actions.toggleTagModal();
  }

  onCancelTagModal(){
    const { actions } = this.props;
    actions.toggleTagModal();
  }
}


@reduxForm({
  form: 'posteditor',
  destroyOnUnmount:false,
})
class TagModal extends React.PureComponent {

  constructor(props) {
    super(props);
    this.handleSubmit = this.handleSubmit.bind(this);
  }

  handleSubmit(data){
    this.props.onClose(data);
  }

  tags(field) {
    return (

      <SearchBoxHolder
        id={field.name}
        localSearch={field.localSearch}
        url={field.url}
        isRequired={field.isRequired}
        placeholder={field.placeholder}
        selectMultiple={field.selectMultiple}
        maxCountSize={field.maxCountSize}
        minQueryLength={field.minQueryLength}
        queryDelay={field.queryDelay}
        initialValues={field.initialValues}
        idLabel={field.idLabel}
        resultsKey={field.resultsKey}
        resultCountKey={field.resultCountKey}
        resultLabel={field.resultLabel}
        onBack={field.onCancel}
        onClose={(id,data) => {
          field.input.onChange(data => data.map(el => el.id).join(','));
          field.onClose(data);
        }}
        />
    )
  }

  render(){

    const { tags, visible } = this.props;

    return (
      <View style={styles.container}>
        <Modal visible={visible} animationType="slide" transparent={true}>
          <Field
            name="tags"
            component={this.tags}
            placeholder={getMessage('ui.search') + ' ' + getMessage('ui.tags')}
            type="text"
            value={tags.map(el => el.id).join(',')}
            props={{
              localSearch:false,
              selectMultiple:true,
              maxCountSize:2,
              minQueryLength:3,
              queryDelay:150,
              idLabel:'id',
              resultsKey:'result',
              resultCountKey:'resultCount',
              resultLabel:'label',
              onCancel: this.handleSubmit,
              onClose:this.handleSubmit,
              isRequired:false,
              initialValues:tags,
              url:config.getRESTEndpoint(URLS.TAGS)
            }}
          />
        </Modal>
      </View>
    );
  }
}
```

The props.onClose method just sets a state variable that shows or hides the modal. Nothing else.

The problem I have is that each time I close the modal, I see 

```
 action @ 15:40:19.030 redux-form/UNREGISTER_FIELD 
```

for the relevant field, and I lose the selected value (not the form itself). Any idea why this is happening and any suggestions to debug this?

Could it be that all fields are unmounted deregistered automatically when they are unmounted? If that's the case, than we need to have a destroyOnUnmount: false option at Field level. But basically, I would argue that unregister_field should never be called automatically when the global destroyOnUnmount = true.

**Comment by mschipperheyn** [comment]
Assuming I'm right about the deregistering on unmount, I will refactor the code now so that the Field reference is in the root form as opposed to it being in the Modal itself. Still, this is a bug

**Comment by mschipperheyn** [comment]
Yup, refactoring worked. So, basically, redux-form unregisters a field when the object the Field is mounted in, gets unmounted. This should not happen. It should probably not even happen, when destroyOnUnmount is true, because this setting applies to the entire form.

**Comment by mschipperheyn** [comment]
Now that I was forced to refactor my code to keep all the Fields out of Modals, I realize that it is possible to do so. It's just a little more challenging. But I do like the resulting code. So, I would argue that unregistering fields should NOT occur when destroyOnUnmount is false. That's simply a bug. But in other situations, it should.

**Comment by erikras** [comment]
Published in [`v6.2.0`](https://github.com/erikras/redux-form/releases/tag/v6.2.0).

**Comment by sergi** [comment]
I am still running into this bug with v6.2.0

**Comment by ithinkdancan** [comment]
this update appears to have created a new issue in wizard style forms with dynamically displayed fields not being properly unregistered causing my form validation to run on unmounted fields. any workarounds?

**Comment by erikras** [comment]
Potential fix released as [`v6.5.0`](https://github.com/erikras/redux-form/releases/tag/v6.5.0).

**Comment by fenos** [comment]
This issue is still not fixed in V6.5.0

**Comment by rurabe** [comment]
Also seeing it in `6.6.3`

**Comment by voidjumper** [comment]
It's also persisting in 6.7.0

**Comment by erikras** [comment]
If someone could recreate this in [a sandbox](https://github.com/erikras/redux-form#-code-sandboxes-), that would be hugely beneficial.

**Comment by tikotzky** [comment]
@ithinkdancan are you seeing the error on a form that is being initially server rendered?

**Comment by ithinkdancan** [comment]
@tikotzky in our case we intentionally omit the redux form state from the preloaded state we send to the client when rendering server side so the client will reconcile itself. However, this particular bug has not been an issue since the forceUnregisterOnUnmount flag was added and we set it in all our sub forms. Be glad to assist further if you need help.

**Comment by Zaggen** [comment]
The bug is still present on 6.8.0

**Comment by zoe-andrews** [comment]
I'm getting an issue using field arrays when fields are unregistered and reregistered again after deleting one of the field array fields.  It seems to be related to this thread.  

From what I can tell when you delete something from a field array, the values from the next field in the array get copied to the array slot that the field is being deleted from (and then the slot at the end is removed).  This appears to cause fields to be registered in the slot that the values are copied to, before being unregistered again.  When these fields are registered the count of each is incremented to 2 and when they are unregistered the count is decremented back to 1.  That part is fine, but the logic for removing fieldValidators is done on unregister and doesn't take into account the fieldRegister count so you lose validation for these fields when the unregister events happen, even though they still exist.

Setting destroyOnUnmount to false seems to provide a temporary workaround to this issue, but clearly has side effects as the fields remain registered in the store.
