### ISSUE TITLE
Allow submit with errors

### ISSUE THREAD

**Issue by VladimirPal** [erikras/redux-form#1991]
Can i allow submit with errors?
After SubmissionError i can't submit again until change something in form, but what if my error is "no internet connection" and user don't need change anything.

**Comment by alex-shamshurin** [comment]
Probably you should  dispatch(initialize('myForm', newInitialValues)) to reset it

**Comment by gustavohenke** [comment]
> Can i allow submit with errors?

No, you can't. You better show warnings instead.

**Comment by gustavohenke** [comment]
Okay, so I was wrong 😳 
PR #2246 seems like fixed this one.
