### ISSUE TITLE
Feature: initialValuesProp option

### ISSUE THREAD

**Issue by ntucker** [erikras/redux-form#2007]
This would be the name of a prop that provides the initialValues, so parents don't have to coerce themselves.

``` javascript
@reduxForm({ initialValuesProp: 'profile', form: 'MyForm' })
class MyForm ....

...
<MyForm profile={profile} />
```

**Comment by gustavohenke** [comment]
@erikras, what do you think? Sounds useful to me.

**Comment by gustavohenke** [comment]
Almost 1 year without this seeing new comments, I'm closing it.
