### ISSUE TITLE
Can't type in text fields

### ISSUE THREAD

**Issue by Hunrik** [erikras/redux-form#2009]
I have a form in a modal using redux-form. I have several text fields, but you can not type in them. My suspicion is that the text field doesn't get the onChange event from the redux-form but I couldn`t find any clue what am I doing wrong.
The problem is maybe it is used in a modal which loads later, but I couldn't find any evidence

My code is:
```
import React from 'react'
import { Button, Modal, Form, Message } from 'semantic-ui-react'
import { Field, reduxForm } from 'redux-form'

const renderField = ({ input, label, type, meta: { touched, error, warning } }) => {
  console.log(input)
  return (
  <Form.Field>
    <label>{label}</label>
    <input {...input} placeholder={label} type={type} />
    {touched && (error && <Message error>{error}</Message>)}
  </Form.Field>
)}

let AddNewModal = (props) => {
  const { handleSubmit, pristine, submitting, closeNewSite, isAddNewOpen, submit } = props

  return (
    <Modal dimmer='blurring' open={isAddNewOpen} onClose={closeNewSite}>
      <Modal.Header>Add a new site</Modal.Header>
      <Modal.Content>
        <Form onSubmit={handleSubmit}>
          <Form.Group widths='equal'>
            <Field name='domain' type='text' component={renderField} label='Domain' />
            <Field name='sitemap' type='text' component={renderField} label='Sitemap URL' />
          </Form.Group>
          /**
           * Other fields 
           * /
          <Button type='submit' disabled={pristine || submitting}>Save</Button>
        </Form>
      </Modal.Content>
      <Modal.Actions>
        <Button color='black' onClick={closeNewSite} content='Close' />
        <Button positive icon='save' labelPosition='right' onClick={submit} content='Save' disabled={pristine || submitting} />
      </Modal.Actions>
    </Modal>
  )
}

export default reduxForm({
  form: 'newsite'
})(AddNewModal)
```

**Comment by Hunrik** [comment]
I Found the problem. I forgot to inject the redux-form`s reducer.

**Comment by pcs2112** [comment]
@Hunrik Hi,
 I have a question for you since i noticed you're using Semantic and display an inline error.
Have you noticed input fields loosing focus when the error is displayed or is hidden when using sync validation?

**Comment by AlexDunmow** [comment]
Hi @pcs2112,

I'm noticing this behaviour. It's incredibly annoying. Have you figured out a work around?

**Comment by pcs2112** [comment]
@AlexDunmow i found a work around, the issue seems to be more with how the semantic modal behaves, displaying errors inline using sync validation causes the modal to adjusts its top position making the input field loose focus.
To work around i had to disable the sync validation and just use server side validation and then 
set the following props in my form:

touchOnBlur=false
persistentSubmitErrors=true
validate=null

**Comment by GreGGus** [comment]
Hey,

I'm using Semantic UI React and Redux form.
Everything is working, but i'm loosing focus after first char in any input.
I don't use arrow function in render.

My redux-form is inside Semantic Modal.

How did you avoid this behavior?


I tried with simple redux form : Working.
Add this exactly same form inside Modal => Loose focus on first type.

Thanks

**Comment by NaeemAbbas** [comment]
Dear check that did you inject correctly in reducer, same problem was with me.

**Comment by pcs2112** [comment]
Did issue no longer occurs in the latest version of React semantic.
