### ISSUE TITLE
normalize and plugin

### ISSUE THREAD

**Issue by kyleboyle** [erikras/redux-form#201]
How do I use both at the same time? Am I missing something?

**Comment by Misneit** [comment]
Is this possible or not? Thanks

**Comment by kyleboyle** [comment]
yeah you just do reducer.normalize({}).plugin({})

**Comment by Misneit** [comment]
Thanks a lot. Order metters?

**Comment by kyleboyle** [comment]
order does not matter, it's just method chaining off the reducer object (normalize and plugin return the augmented reducer object)

**Comment by bryce-larson** [comment]
thanks, i had the same question
