### ISSUE TITLE
how to set initial values

### ISSUE THREAD

**Issue by godmar** [erikras/redux-form#2012]
I'm trying to create a form that displays the current user's username in a field, but redux-form sets field.input.value to "". The user name is available in the redux store. I have:

```
render() {...
const user = this.props.user;
console.dir(user); // user.username has the correct value
return ....
<LabeledFormField value={user.username} name="username" label={'Username'} />
```

then I have

```
const LabeledFormField = props =>
{
    console.log(`LabeledFormField.props.value ${props.name} -> ${props.value}`);
    return (<FormGroup>
    <ControlLabel>{props.label}</ControlLabel>
    <Field name={props.name} component={fieldMaker} value={props.value}
           type={props.type || "text"} />
  </FormGroup>);
}
```

where I also see the correct value, which I then pass onto redux-form's Field component.  This is when things go haywire:

```
// as per http://redux-form.com/6.1.1/docs/MigrationGuide.md/
// https://github.com/erikras/redux-form/issues/1557
// make sure to look at 6.1.1 release notes
// this function must be defined only once.
const fieldMaker = field =>
{
console.log("in fieldMaker"); console.dir(field);   // now field.input.value is ""
return    (<div>
        <FormControl {...field.input} type={field.type}/>
        {field.meta.touched &&
         field.meta.error &&
         <HelpBlock className="error">{field.meta.error}</HelpBlock>}
    </div>)
}
```

Here, field.input.value (which redux-form sets) has the value "". For the correct value to appear in the &lt;input&gt; element, redux-form would need to set the 'value' attribute of the 'field.input' object it passes to my fieldMaker function. It doesn't.

I am a little bit frustrated that tasks such as setting the initial value of a form field, which required zero thought in the old days, are now so terribly complicated.

My next step would be to reverse-engineering redux-form, or to drop it. I'm obviously new to redux.

**Comment by godmar** [comment]
PS: I'm also setting 'initialValues' and I verify that:
```
    console.dir(this.props.initialValues.username);  // has correct value "myuser"
```
in the outer component's render() has the correct value.
FWIW, fieldMaker isn't called after that (which is how I understand it should be, to avoid the 'rerendering' bug that necessitated fieldMaker in the first place).  So it should be calling 'setValue()' or some such if the initialValue changes?

**Comment by godmar** [comment]
The [documentation](http://redux-form.com/6.1.1/docs/api/Field.md/) says:

"All other props will be passed along to the element generated by the component prop."

Yet, when I code:

```
class MyFormControl extends React.Component
{
    render() {
        console.dir(this.props);
        const field = this.props.field;
        return    (<div>
            <FormControl {...field.input} type={field.type}/>
            {field.meta.touched &&
             field.meta.error &&
             <HelpBlock className="error">{field.meta.error}</HelpBlock>}
        </div>)
    }
}

const fieldMaker = field => <MyFormControl field={field} />
```
and then:
```
    <Field name={props.name} component={fieldMaker} value={props.value}
           type={props.type || "text"} />
```

the component 'MyFormControl' does not receive the property 'value' I passed to Field, contrary to documentation.

**Comment by godmar** [comment]
I figured it out.  I inadvertently had the wrong order for how the components were wrapped. Instead of connect()ing the reduxForm()'ed component, I was reduxForming the connect()ed component.

Wrong:
```
reduxForm(formOptions)(connect(mapStateToProps, mapDispatchToProps)(form))
```

Correct:
```
connect(mapStateToProps, mapDispatchToProps)(reduxForm(formOptions)(form))
```

In other words, reduxForm and connect do not commute!

Suggestion: add a note to the documentation to make this clear. The [example](http://redux-form.com/6.1.1/examples/initializeFromState/) does it correctly, but doesn't point out that it works only in this order. 

The [upgrade guide](http://redux-form.com/6.1.1/docs/MigrationGuide.md/) simply states: 'You will need to separately decorate your form component with connect() yourself if you need to access other values in the Redux store or bind action creators to dispatch.' which doesn't make the order clear.

This could be a problem in particular for people migrating from v5 where, apparently, the order didn't matter (?).

**Comment by iyn** [comment]
@godmar I'm glad you solved the problem and shared your solution here. I think you (or somebody with permissions) should close this issue now.

**Comment by godmar** [comment]
Don't think it's just "my issue". I worked from code that worked perfectly fine in v5.

I'd like a developer to comment whether a) this lack of commutativity should be documented or even b) a warning should be built-into reduxForm if it's possible to detect it at runtime.

It would probably save a lot of people a lot of time. This is the second big hiccup I hit with redux-form v6, after the double rendering issue. (Why is the double rendering issue biting a lot of people? Because the 6.0.0alpha4 documentation has a higher pagerank on Google than the 6.1.1 documentation.)

**Comment by iyn** [comment]
@godmar Sure, I understand. So, given that, what do you think are concrete actionable steps here (e.g what exactly and where should be the info about the double rendering issue)?

**Comment by godmar** [comment]
The double rendering issue is separate from this one.

Concrete steps: Take down [this page](http://redux-form.com/6.0.0-alpha.4/docs/MigrationGuide.md/)

See [this result](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=redux-form%20input%20rendering)

**Comment by iyn** [comment]
Maybe the better option would be to add some notice/message at the top of that page and a link to the current version documentation, what do you think?

**Comment by godmar** [comment]
A message at the top is easily missed. People scan this page directly for "what's different in v6". If you want to add a message, mark the wrong part (where it does `component={field => ...}` in red).

**Comment by gustavohenke** [comment]
I don't feel like removing docs for a released version is the right move.
Also, HOCs are simple function calls composition.

**Comment by Peterabsolon** [comment]
Thanks so much for this, I'm using decorators and I was going insane already. Setting up initialValues from the parent worked but connecting inside didnt.

Much love, wow

**Comment by alicerocheman** [comment]
I believe I'm having the same problem, and ordering connect and reduxForm properly doesn't solve the issue...

```JSX
import React from 'react';
import { PropTypes } from 'prop-types';
import { bindActionCreators } from 'redux';
import { connect } from 'react-redux';
import * as modelActions from 'data/model/actions';
// import InitForm from './InitForm';
import { reduxForm, Form, Field } from 'redux-form';

class Sandbox extends React.Component {
  initialize = () => {
    this.props.actions.modelInitialize();
  };

  render() {
    return (
      <div>
        Hello!
        <Form onSubmit={this.initialize} model={this.props.model}>
          <label htmlFor="width">Width</label>
          <Field
            name="width"
            component="input"
            type="number"
            value={this.props.model.initialSize[0]}
            parse={Number}
          />
        </Form>
      </div>
    );
  }
}

Sandbox.propTypes = {
  model: PropTypes.shape().isRequired,
  actions: PropTypes.shape({
    modelInitialize: PropTypes.func.isRequired,
  }).isRequired,
};

const mapStateToProps = state => ({
  model: state.model,
});

const mapDispatchToProps = dispatch => ({
  actions: bindActionCreators(modelActions, dispatch),
});

export default connect(mapStateToProps, mapDispatchToProps)(
  reduxForm({ form: 'initialization' })(Sandbox),
);
```

my input doesn't receive the value even though:
<img width="598" alt="field" src="https://user-images.githubusercontent.com/21168856/35182242-23049f1c-fdd1-11e7-91fc-9510c2d880b8.PNG">
<img width="596" alt="connect" src="https://user-images.githubusercontent.com/21168856/35182243-2a740288-fdd1-11e7-86cb-cc52f78e63c6.PNG">
<img width="599" alt="connectedfield" src="https://user-images.githubusercontent.com/21168856/35182244-2ea79f22-fdd1-11e7-81b3-606d4e81a684.PNG">
<img width="598" alt="input" src="https://user-images.githubusercontent.com/21168856/35182247-3631931a-fdd1-11e7-9c2e-b49ab3cae989.PNG">

**Comment by ArtixZ** [comment]
having same issue as @alicerocheman

**Comment by mgvparas** [comment]
Given the setup below, i was able to load initial values to my form. But the thing is, i am now unable to use my custom dispatch functions in my component. An example would be the _onCancelButtonClick_ shown below. TBH, i can't really tell what happened inside connect, but somehow, the props doesn't have the _onCancelButtonClick_ anymore. 

```
const MyComponent = (props) => {
    const { onCancelButtonClick } = props; //onCancelButtonClick will have a value of undefined here.

    return <form>
        <Button onClick={() => onCancelButtonClick()}>
            Cancel
        </Button>
    </form>
}

const mapStateToProps = (state) => {
    return {
        formData: state.formData
    });
}

const mapDispatchToProps = (dispatch) =>{
    return {
        onCancelButtonClick: () => {
            dispatch(formDismiss());
        }
    }
}

const MyComponentForm= reduxForm({
    form: 'form',
    enableReinitialize: true
})(MyComponent);

export default connect(
    mapStateToProps,
    mapDispatchToProps,
    state => Object.assign(state, {
        initialValues: state.formData
    })
)(MyComponentForm);
```

**Comment by mgvparas** [comment]
figured it out. it turns out, i just had to include the _initialValues_ assignment to the mapStateToProps function, along with the others.

this:
`
const mapStateToProps = (state) => {
    return {
        formData: state.formData
        _initialValues: state.formData_
    });
}
`

instead of this:
`
export default connect(
    mapStateToProps,
    mapDispatchToProps,
    _state => Object.assign(state, {
        initialValues: state.formData
    })_
)(MyComponentForm);
`
