### ISSUE TITLE
Need partial Destroy/Reset, It will be named as a new action "wipe"

### ISSUE THREAD

**Issue by TugrulAsik** [erikras/redux-form#2015]
While working with many inputs in a page, you need a partial destroy/reset to clear/reset some inputs. 
I can do it manually with an external wipe(String...) function which accepts field array and  executes untouch&clear actions to fields.

A specific action/function will be good for this behaviour.

**Comment by danielrob** [comment]
This issue was duplicated by #2224, closing as a duplicate of #2224.
