### ISSUE TITLE
getFormValues returns undefined

### ISSUE THREAD

**Issue by Aaronius** [erikras/redux-form#2017]
I have a form with a textfield. If I call `getFormValues` before using the form, I get an empty object. If I then type a character into the textfield and call `getFormValues` I get an object with the field's value. If I then hit backspace to remove the character I just typed and call `getFormValues`, I get `undefined`.

I wouldn't ever expect `getFormValues` to return `undefined`. Either way, it seems inconsistent that sometimes it returns an empty object and sometimes returns `undefined`.

We're using 6.1.1.

**Comment by tatemz** [comment]
Me too

**Comment by alex-shamshurin** [comment]
What is the use of `getFormValues `, we can get form values anyway `state.for,myForm`. Can we?

**Comment by notgiorgi** [comment]
Same happens in case of `onSubmit`. If user doesn't fill out any of the values you get `undefined` in stead of empty object. Also if user fills out only some of the fields, unfilled fields will be undefiined.

If you look at examples (e.g. [here](http://redux-form.com/6.2.0/examples/simple/)) you can this clearly in the **Values** section.

**Comment by Xurma2** [comment]
Have a similar problem. If fields untapped, validation does not work. 
While I decided it by adding **initialValue** with empty lines _""_

What to do next I do not know...

**Comment by alex-shamshurin** [comment]
To make validation work each time I did this in HOC:

`persistentSubmitErrors: true,`

then In onSubmit callback:

```
submitForm(values, dispath) {
    const {autoCompleteData, reset} = this.props;
    this.button.blur();
    
    return new Promise((resolve, reject) => {
      let errors = {};
      try {
        if (!values.from || values.from.length === 0) {
          errors.from = 'from is not specified';
        }
        ...
                
        if (Object.keys(errors).length) {
          reject(new SubmissionError(errors));
        } else {
          resolve(values);
        }
      } catch (error) {
        console.log('caught a error during form validation: ', error);
      }
    })
  }
```

And then in form reducer where are form values I delete all submitErrors

`delete newState.submitErrors`

**Comment by Aaronius** [comment]
I'm so glad I found this issue; it's the same problem I just ran into! Oh look, I'm also the one the reported it almost a year ago. ¯\_(ツ)_/¯

**Comment by danielrob** [comment]
:P #contributorsneeded

**Comment by Aaronius** [comment]
👍  Not a knock on redux-form or the community (which includes me), just a funny observation.

**Comment by danielrob** [comment]
I certainly meant to sadface hashtag that one in a comical way :D.

**Comment by erikras** [comment]
When a form has no values in it, `redux-form` stores the values as `undefined` rather than `{}` to guarantee that a form that was given no `initialValues` (i.e. `initialValues === undefined`) will be `pristine` when it is empty.

I cannot get `getFormValues()` to return an empty object, so perhaps this inconsistency mentioned in the original issue comment is no longer a problem? See sandbox:

[![Edit Redux Form - getFormValues Example](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kwjxvVlN)

**Comment by gustavohenke** [comment]
> I cannot get getFormValues() to return an empty object, so perhaps this inconsistency mentioned in the original issue comment is no longer a problem?

I will consider the no-response as "no longer a problem".

For people watching this thread: you can also try [`formValues`](https://redux-form.com/7.2.1/docs/api/formvalues.md/) and [`formValueSelector`](https://redux-form.com/7.2.1/docs/api/formvalueselector.md/), if that helps you somehow.
