### ISSUE TITLE
Slow events on large form

### ISSUE THREAD

**Issue by melinath** [erikras/redux-form#2023]
I have a large form (~190 rows, 1-2 fields per row) inside a modal. Opening and closing the modal seems to be slowed down by a large backlog of REGISTER and UNREGISTER events - only when that's worked through am I able to get the app to respond to me again.

It's possible this is only in development because of event logging. It's still inconvenient even if that is the case, though.

**Comment by iyn** [comment]
Which version of redux-form do you use?

One possible workaround I can see: you can pass `destroyOnUnmount: false` to the modal's `reduxForm` and after closing the modal, you can manually call the `destroy` action from `redux-form` (more info: http://redux-form.com/6.1.0/docs/api/ActionCreators.md/)

**Comment by melinath** [comment]
I'm currently on 6.0.2. I'm going to try updating to 6.1.1.

**Comment by melinath** [comment]
Seems about the same on 6.1.1.

**Comment by iyn** [comment]
And did you try my suggested workaround with manually destroying the form after closing the modal?

**Comment by melinath** [comment]
Disabling the event logger in redux dev tools resolves this for me.

**Comment by Industrial** [comment]
I'd like to reopen this ticket.

Just ignoring the log of actions is NOT a solution for me. Looking at the action creators there is only a `REGISTER_FORM` and `UNREGISTER_FORM` action.

My question is: Since all of the form fields are passed into the Form component and all of them are known at render time, why not just have only one `REGISTER_FIELDS`?

I now have 15msec page load time and 5000 milliseconds of render time due to 100+ actions of REGISTER_FIELD being called before I even see a thing rendered.

**Comment by aray12** [comment]
I am having the same issue. I have created a page that has ~6 forms that are only 1-3 fields. The actions being fired to initialize those forms are taking causing ~2 seconds of no response. This is a super simple test where both console logging and redux devtools are being used, but the issue exists to a still noticeable extent with a production build.

![image](https://user-images.githubusercontent.com/8671174/27521298-25cc7364-59d0-11e7-895e-6405a2617297.png)

**Comment by mikeengland** [comment]
I agree, I think a 'bulk register fields' would offer a good speed improvement when rendering large forms.

**Comment by alexxmde** [comment]
Did you solved or worked around this issue somehow? I'm experiencing the same here.

**Comment by liederivative** [comment]
any update or work around on this issue ? I'm also experiencing the same .
