### ISSUE TITLE
[6.1.1] getFormSyncErrors is not exported in redux-form/immutable

### ISSUE THREAD

**Issue by gipsy-king** [erikras/redux-form#2025]
It is in createAll.js, I think it just needs to be added to src/index.js and src/immutable.js.

**Comment by jdreesen** [comment]
Already partially fixed by #1983 but needs to be added to `src/immutable.js`, I think.

**Comment by gustavohenke** [comment]
Does this still happens?

**Comment by vdh** [comment]
@gustavohenke Yes, I just ran into this with 6.4.3. `src/immutable.js` is missing `getFormSyncErrors`, `getFormAsyncErrors`, `getFormSubmitErrors`, `registerField` and `unregisterField`.

**Comment by gustavohenke** [comment]
Fixed by #2425

**Comment by erikras** [comment]
Fix released as [`v6.5.0`](https://github.com/erikras/redux-form/releases/tag/v6.5.0).
