### ISSUE TITLE
Is there a way to prevent validate from running when form is rendered server side?

### ISSUE THREAD

**Issue by kellyrmilligan** [erikras/redux-form#2027]
I can see in componentWillMount, which happens on the server side as well, that it's calling validate. is there a way to stop this from happening , like using componentDidMount instead maybe?

**Comment by clayne11** [comment]
What's the purpose of not calling validate for SSR?

**Comment by kellyrmilligan** [comment]
Well initially I was just think the values object would have the keys, like values.email, anyway I was running into a sitution where validate didn't like that I was sending undefined instead of a string. I was surprised that validate was even being called server side since it seems like a client side only feature

**Comment by clayne11** [comment]
It makes sense to run it server side, because then you can render the
proper sync errors using SSR and your user sees the fully-rendered page
immediately. Is there an issue with having validate run on the server? What
do you mean validate "didn't like" it? Validate is used to calculate the
sync errors, and you generally don't show sync errors until a field is
touched anyways. Additionally those sync errors are going to be calculated
on mount so you might as well calculate them on the server.

**Comment by alex-shamshurin** [comment]
@clayne11 What does it mean fully-rendered page with errors from server? Form is filling out and validating on client. What is the use to calculating sync errors? When it happens? Form must appear cleared, then user fill it out, then validate. What errors can be before it?

@kellyrmilligan 
I simply did
```
const validate = (values, props) => {
      if (__SERVER__) return {}; 
      }
      ....
}
```

**Comment by kellyrmilligan** [comment]
@clayne11 yeah that's kind of my point. I don't see the value in doing validation in the form ui on the server side, which happens if used in component will mount. I did something similar to just make sure things are there before validating.

**Comment by gustavohenke** [comment]
A good use for SSR validations are when you persist your store state into a session for example, and you want to later return to some form.
It'll be rendered from the server with the proper validations in place.

Anyway, starting with v6.2.0 you have the option to use `shouldValidate` config, like this:

```js
reduxForm({
  form: "myForm",
  // Could use something else like process.env.BROWSER set by Webpack, etc
  shouldValidate: () => !isServerSide
})
```

**Comment by kellyrmilligan** [comment]
I think a basic example app where ssr and validations are used would be great here because I'm still not seeing it as useful tbh.
