### ISSUE TITLE
How do you get *all* form values?

### ISSUE THREAD

**Issue by ads1018** [erikras/redux-form#2028]
The docs only describe how to select individual fields by name.

**Comment by brotzky** [comment]
You could always go the old fashioned way

```JavaScript
const mapStateToProps = state => ({
  formValues: state.form && state.form.formName && state.form.formName.values,
});

return connect(mapStateToProps)(MyComponent);
```

**Comment by ads1018** [comment]
Thanks. Any idea why formValues would return undefined?

**Comment by ads1018** [comment]
Nevermind, forgot add name attributes to input field.

**Comment by brotzky** [comment]
Glad it worked

**Comment by notgiorgi** [comment]
I used your method, but `formValues` are passed to `Connect(Form(CalcForm)))` (see the screenshot bellow), not directly to my `CalcForm` component.

I'm doing it like this
```
const CalcForm = () => <form> {/* ... */} </form>
const DecoratedCalcForm = reduxForm({ /* ... */)(CalcForm)

export default connect(mapStateToProps, mapDispatchToProps)(DecoratedCalcForm)
```

![image](https://cloud.githubusercontent.com/assets/12987425/19828067/7e682528-9dcd-11e6-8b2c-d0c0a2538095.png)
