### ISSUE TITLE
State not updated when using a reducer that isn't created with combineReducers()

### ISSUE THREAD

**Issue by YoniH** [erikras/redux-form#2029]
For various reasons, my app's root reducer is not created with combineReducers(). Instead, I provide an explicit reducer function.
_(As a side note, here you can read about reasons for doing this: http://redux.js.org/docs/recipes/reducers/BeyondCombineReducers.html)_

When I use such a root reducer, it doesn't seem to respond to redux-form's actions. As a result, the form state can't be changed.

Here's an illustration:

```javascript
import { reducer as formReducer } from 'redux-form';
import { combineReducers } from 'redux';

const rootReducer1 = combineReducers(
  {
    //...other reducers
    form: formReducer
  }
);

const rootReducer2 = (state = {}, action) => (
  {
    //...other reducers
    form: formReducer
  }
);

export default rootReducer1; /* works */
//export default rootReducer2; /* doesn't work */
```

What am I missing?

**Comment by iyn** [comment]
From: http://redux-form.com/6.1.1/docs/api/Reducer.md/

> If you absolutely must mount it somewhere other than form, you may provide a `getFormState(state)` function to the `reduxForm()` decorator, to get the slice of the Redux state where you have mounted the `redux-form` reducer.

It seems that you just need to use `getFormState` when creating a form.

**Comment by YoniH** [comment]
Thanks @iyn, but I **did** mount it at _form_, as you can see in my code example.

What I missed is that I had to actually **call** the reducer in my custom implementation, to construct the new state. This is what combineReducers() does - it takes an object with reducer functions as values, and calls them to construct the new state.

So this works:

```javascript
import { reducer as formReducer } from 'redux-form';
import { combineReducers } from 'redux';

const rootReducer = (state = {}, action) => (
  {
    //...other reducers
    form: formReducer(state.form, action)
  }
);

export default rootReducer;
```

**Comment by iyn** [comment]
@YoniH It seems that I misunderstood your reducers setup. I actually saw that you had `redux-form` reducer mounted as `form` in the `rootReducer1` (so you could access the form data simply with `state.form`), but in the case of `rootReducer2` it wasn't the same way, so `getFormState` could be used. Anyway, it's good you solved the problem :)
