### ISSUE TITLE
Autocomplete state is not preserve while it is working with TextField

### ISSUE THREAD

**Issue by Tushant** [erikras/redux-form#2033]
I have used material ui in redux form and i am facing following problem which i have raise my question on SO too but no help yet. I am confused where to raise an issue. Should i raise it on material-ui or here? Sorry if i am in the wrong place.

```javascript
const renderAutoComplete = ({
        input,
        label,
        datasource,
        meta: { touched, error }, ...custom }) => (
    <AutoComplete
        hintText={label}
        floatingLabelText={label}
        filter={AutoComplete.noFilter}
        openOnFocus
        className="autocomplete"
        errorText={touched && error}
        dataSource={datasource}
        onNewRequest={(selectedItem) => {
            const value = selectedItem.id;
            return input.onChange(value);
        }}
        onUpdateInput={(selectedItem) => {
            const value = selectedItem.value;
            return input.onChange(value);
        }}
        {...input}
        {...custom}
    />
);
<div>
     <Field
        name="deviceIcon" component={renderAutoComplete}
        label="Device Icon"
        datasource={listOfIcon}
     />
</div>
```

**Comment by iyn** [comment]
First of all, you don't need to `return input.onChange(value);`, simple `input.onChange(value);` should be enough.

What is the structure of the `selectedItem` (what fields does it have - like `id`, `value`?)?
Why in the `onNewRequest` you have `selectedItem.id` and in `onUpdateInput` `selectedItem.value`? In both cases you update the `redux-form` field (by calling `onChange`), but with different value in different cases. Have you tried doing just `input.onChange(selectedItem)` and then 'extract' desired data by hand when submitting the form?

**Comment by Tushant** [comment]
I changed my onRequest and onUpdate like you have said but is not working yet. 

onNewRequest={(selectedItem) => {
            input.onChange(selectedItem);
        }}
        onUpdateInput={(selectedItem) => {
            input.onChange(selectedItem);
        }}

selectedItem has field like id, text and value object. I tried input.onChange(selectedItem.text) too but no favor.

**Comment by iyn** [comment]
I don't have experience with material-ui, but according to this page: http://www.material-ui.com/#/components/auto-complete you can set `searchText` prop on the AutoComplete component. Can you try doing that (e.g. setting `searchText={input.value}`). Also, I think you should use `input.onChange(selectedItem.text)` in the `onNewRequest` and `onUpdateInput`.

Let me know if that helps.

**Comment by Tushant** [comment]
i consoled input and it showed me name:deviceIcon, onChange onBlur etc etc with empty value.

**Comment by Tushant** [comment]
Yes it worked now and yes i have to use **selectedItem.text**

**Comment by Tushant** [comment]
Thanks for your support.

**Comment by iyn** [comment]
Sure, glad I could help :). Can you please close the issue now?

**Comment by Tushant** [comment]
Sure.

Thanks
