### ISSUE TITLE
two forms with the same name. is that ok?

### ISSUE THREAD

**Issue by gabor** [erikras/redux-form#2034]
i have to handle a situation where my form is made up from two parts, and they live at separate places in the DOM, so i cannot just have both in one redux-form.

(for example, imagine an text-field at one place in the DOM, and the submit-button at an another place in the DOM, where i have to enable/disable the submit-button after every change in the text-field based on validation logic)

 it seems that i can simply create 2 reduxForms for those parts, and as long as they have the same "name", things seem to work fine enough.

i'd just like to know, is this something i should be doing, or there are some better ways to handle such a situation?

**Comment by iyn** [comment]
IMO you just need 1 form and need to 'connect' different component to this form. Create your form in a regular way and then use `redux-form` selectors and action creators to manually react to changes.

Action creators: http://redux-form.com/6.1.1/docs/api/ActionCreators.md/
Selectors: https://redux-form.com/6.1.1/docs/api/FormValueSelector.md

Say you have your form in one component (with everything setup as in the most examples) and then you have your submit component with the submit button and in that component you can use `redux-form` selector to check if the inputs were `touch`ed and submit the form on click by dispatching `startSubmit` action.

**Comment by gabor** [comment]
thank you for the idea, but unfortunately i do not think it will be enough.

for example, imagine i have the submit-button at a separate place, and i want to have it disabled as long as the form is `pristine`. can i use the selectors to get this information? from what i saw,i can only get field-values...

**Comment by iyn** [comment]
If you want just check if the whole form is pristine, you can use `isPristine` selector: http://redux-form.com/6.1.1/docs/api/Selectors.md/

**Comment by gabor** [comment]
oh, interesting. sorry, somehow i was scrolled to the form-value-selectors.

this could work, will check. thanks.

**Comment by iyn** [comment]
No need to apologize :). I posted the link to the `formValueSelector` in the first post but more detailed info about selectors in on the Selectors page. Please update the issue if that solves your usecase (so other people in the future will be able to use this solution as well) and if so, close the issue.

**Comment by danielrob** [comment]
Closing due to non response.

**Comment by gabor** [comment]
sorry i somehow forgot about this github-issue. for people reaching this in the future:  the approach where connect external widgets to the form with selectors work generally, but i reached an another problem later, where i had two submit-buttons outside of the form, and i needed to know which one was used to submit, and i was unable to do it (you cannot give additional data to the `submit` action-creator). in such cases two-forms-with-same-name seems the way to handle it. (or the `submit` action creator will have to change and be able to accept additional data)
