### ISSUE TITLE
Error syntax while trying the Material UI example in docs

### ISSUE THREAD

**Issue by ferrwanz** [erikras/redux-form#2036]
Hello,
I'm new to this redux-form and I use the Material UI in my project. So I try to use the Material UI example in docs. I just copied and pasted the example codes in Material UI section, but I got syntax error when build it. The error is on **spread** syntax. 
![screenshot from 2016-10-28 01 21 35](https://cloud.githubusercontent.com/assets/14013568/19779908/42ab5378-9cad-11e6-9c2f-55308ff89ab3.png)

Here's my webpack config :
```
const path = require('path');
const webpack = require('webpack');
const CleanWebpackPlugin = require('clean-webpack-plugin');
const LodashModuleReplacementPlugin = require('lodash-webpack-plugin');

var BUILD_DIR = path.resolve(__dirname, 'web/assets/webpack');
var APP_DIR = path.resolve(__dirname, 'src/AppBundle/Resources/public/js');

var config = {
  devtool: 'eval-source-map',

  entry: {
    bundle: APP_DIR + '/index.js'
  },

  output: {
    path: BUILD_DIR,
    filename: '[name].js',
    publicPath: '/assets/webpack/'
  },

  resolve: {
    modulesDirectories: ['node_modules'],
    root: [
      path.resolve('node_modules'),
      path.resolve('src/AppBundle/Resources/public/js'),
    ],
    extensions: ['', '.jsx', '.scss', '.js', '.json']
  },

  plugins: [
    new webpack.NoErrorsPlugin(),
    new CleanWebpackPlugin(['webpack'], {
      root: path.resolve(__dirname, 'web/assets/'),
      verbose: true,
      dry: false
    }),
    new webpack.optimize.OccurenceOrderPlugin(),
    new LodashModuleReplacementPlugin,
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': JSON.stringify('development')
    })
  ],

  module: {
    loaders: [
      {
        test: /\.js?$/,
        exclude: /node_modules/,
        loaders: ['babel-loader'],
      },
      {
        test: /\.json?$/,
        loader: 'json'
      },
      {
        test: /\.s?css$/,
        loaders: ['style', 'css', 'sass'],
        exclude: /(node_modules)\/react-toolbox/
      },
      {
        test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/,
        loader: 'url-loader?limit=10000&minetype=application/font-woff'
      },
      {
        test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
        loader: 'file-loader'
      },
      {
        test: /\.(jpg|png)$/,
        loader: 'url-loader?limit=10000'
      }
    ]
  },
  sassLoader: {
    includePaths: [
      './node_modules',
      './node_modules/grommet/node_modules'
    ]
  }
};

module.exports = config;
```

Anyone can help me with this? Thanks before.

**Comment by iyn** [comment]
It's not related to `redux-form` but to the JS syntax itself/babel. Object spread syntax was introduced in ES6, you need to either use this babel plugin: https://babeljs.io/docs/plugins/transform-object-rest-spread/ or ES2015 preset (https://babeljs.io/docs/plugins/preset-es2015/) in your webpack/babel config.

To use ES2015 preset, you need to install it first:
```
npm install babel-preset-es2015 --save-dev
```

Then you can create `.babelrc` file in the root dir of your project with the following content:
```
{
  "presets": ["es2015"]
}
```

(`babel-loader` from your webpack config will automatically use the config from the `.babelrc`)

Let me know if that helps.

**Comment by ferrwanz** [comment]
Actually I have done that before in my .babelrc. I use babel-preset-es2015: ^6.16.0. Haven't tried the transform-object-rest-spread. Should I include it too ?

This is my current .babelrc
```
{
  "presets": ["es2015", "react"],
  "env": {
    "development": {
      "plugins": ["lodash", "transform-react-jsx-img-import"]
    }
  }
}
```

**Comment by iyn** [comment]
AFAIK you should also include `transform-object-rest-spread` in the `plugins` section of your `.babelrc`. I edited my previous post to include that info.

**Comment by ferrwanz** [comment]
It did solve the problem by including it.
Thanks a lot @iyn. :+1:
