### ISSUE TITLE
Redux Form Not updating Select Component

### ISSUE THREAD

**Issue by brunobraga95** [erikras/redux-form#2042]
Hello guys I am using a library called [recompose](https://github.com/acdlite/recompose) to create my components. I am trying to create a select component. When I use it outside of redux form, it works great. But when I wrap it with a <Field> the current selected value will not change. Only the first option will be displayed, and when I select another one, it just winn not change. 

PS:When I console.log(event.target.value) inside my OnChange function, the correct value will be displayed i.e the one I choose. But (always a but) The value will not be updated in the actual select.

### My SelectOne Component

`const SelectOneComponent = ({columns, label, input, style, optionsList, handleChange, isEmpty}) => {
  ....
  return (
    <div className={SelectOneWrapperClasses} style={{textAlign: 'left'}}>
      <div className={SelectOneInnerClasses}>
        <div className={isEmpty ? '' + styles.isEmpty : styles.hasContent + ' ' + styles.inputIsFocused}>
          <label htmlFor=''>{label}</label>
          <select className='form-control'
            {...input}
            onChange={handleChange}
            disabled={style === 'disabled'}>
            {options}
          </select>
        </div>
      </div>
    </div>
  )
}
const SelectOne = compose(
  withState('isEmpty', 'updateEmpty', true),
  withHandlers({
    handleFocus: props => () => props.updateFocus(isFocused => true),
    handleChange: props => event => {
      event.target.value === props.label ? props.updateEmpty(isEmpty => true)
      : props.updateEmpty(isEmpty => false)
    }
  }),
  mapProps((props) => ({
    ...props
  })),
  defaultProps({
    columns: '6',
    label: 'SelectOne',
    style: 'default'
  })
)(SelectOneComponent)

export default SelectOne`

### How it is being called

`   <Field name='selectOneSuccess' component={SelectOne} columns='12' label='Select Success'                          optionsList={['option', 'options2']} style='success' />`

**Comment by mschipperheyn** [comment]
This is a stackoverflow type question. I suggest only submitting issues here that point to bugs and new feature requests.

**Comment by TeyimPila** [comment]
I am facing this same problem
