### ISSUE TITLE
Warning: Failed prop type: Invalid prop `value` of type `string` supplied to `Knob`, expected `number`

### ISSUE THREAD

**Issue by Tushant** [erikras/redux-form#2043]
I have a redux-form developed which has knob component(react-canvas-knob). I want some validation to apply for it but i get an error when i use {...input} props. If i dont use {...input} props i don't get Failed prop type error but error occurred during validation cannot shown.

The problem to me is the use of {...input} props. Both knob component and DatePicker component has issue with it. Knob component has issue with Invalid prop value of type string supplied to Knob, expected number and DatePicker component has similar issue Invalid prop value of type string supplied to DatePicker, expected object.

```javascript
const renderKnob1 = ({
                input,
                minValue,
                meta: { touched, error },
                handleMinChange,
            }) => (
        <div className="knob">
            <Knob
                value={input.value === '' ? minValue : input.value}
                onChange={handleMinChange}
                bgColor="#f3f3f4"
                width={110}
                height={110}
                fgColor="#1ab394"
                errorText={touched && error}
                {...input}
            />
        </div>
        );

const renderDate = ({ input, meta: { touched, error } }) => (
    <DatePicker
        hintText="pick a date"
        textFieldStyle={{ color: '#3333' }}
        hintStyle={{ color: '#3333' }}
        errorText={touched && error}
        value={input.value !== '' ? new Date(input.value) : null}
        {...input}
    />
);

<Field
     name="knob1"
     minValue={this.state.minValue}
     handleMinChange={this.handleMinChange}
     component={renderKnob1}
/>

<Field name="date" component={renderDate} autoOk />;

```

**Comment by iyn** [comment]
When you use `{...input}` it overrides the `value` prop you set before it. You need to do something like this:

```
<YourComponent
someProps={someValue}
{...input}
value={yourValue}
```

So the component will receive the value processed the way you want.

**Comment by Tushant** [comment]
I had tried that before but it still gave me error. 

```javascript
<div className="knob">
        <Knob
            value={minValue}
            onChange={handleMinChange}
            bgColor="#f3f3f4"
            width={110}
            height={110}
            fgColor="#1ab394"
            errorText={touched && error}
            {...input}
        />
    </div>
```
I get an error but if i provide value then the state of its value is preserved and also validation error is shown. The problem is i get an error at initial.

**Comment by Tushant** [comment]
The date is working but not knob component.

**Comment by iyn** [comment]
The obvious problem is with the
```js
const requiredFields = ['input'];
```
line - you don't have any `Field` named `input` (at least not that I can see), you have `knob1` and `knob2` and this is what you should check. If you have a problem, you can always add simple `console.log` at the top of the function to check the data you are given (your `console.log` in the code you pasted is never evaluated), e.g:
```
const validate = values => {
  console.log(values);
  // rest of the validation code
}
```

**Comment by Tushant** [comment]
The state is preserved. For that i had to change my onChange event as 

```javascript
onChange={(value) => input.onChange(value)}
```

my validations works now but i could not show an error in my UI. 

```javascript
if (values.knob1 > values.knob2) {
        console.log('error');
        errors.knob1 = 'minimum value should not exceed maximum value';
    }
```

Thanks for noticing me to use ```knob1``` and ```knob2``` in requiredFields.

**Comment by iyn** [comment]
You need to take care of displaying the error yourself in the `Knob` component. You're passing `errorText` prop - this should be displayed in the component.

**Comment by Tushant** [comment]
Yes it should but it is not. The error is shown in console, though.

**Comment by Tushant** [comment]
Is it because the component has not error props?

**Comment by iyn** [comment]
Yes, I think that's correct @Tushant, https://github.com/joshjg/react-canvas-knob only accepts data related to the knob, you need to display the error in the `renderKnob` method, like:
```jsx
<Knob
(your props here)
/>
{touched && error}
```

**Comment by Tushant** [comment]
I already tried that using 

```javascript
<Knob
      {...input}
       value={input.value !== '' ? input.value : minValue}
       onChange={(value) => input.onChange(value)}
 />
    {touched && error && <span>{error}</span>}
```
the error is not shown.

**Comment by Tushant** [comment]
I did following to check if the error is rendering in the component or not 

```javascript
{error ?
        <div className="error">
            {touched && error}
        </div>
        :
        <span />
    }
```

when there is no error empty span element is shown. If there is error then <div class="error"></div> is shown on inspect element.

**Comment by Tushant** [comment]
just using ```{error}``` works.

**Comment by iyn** [comment]
Oh, right! It seems that `redux-form` isn't setting `touched` property of the `Knob`, like on regular inputs. I understand that the issues is solved? Can you please close it now?

**Comment by Tushant** [comment]
Yeah sure. Thanks. This is the most responsive community. I supremely appreciate your support.

**Comment by iyn** [comment]
Great, glad I could help :).
