### ISSUE TITLE
Only one default export allowed per module

### ISSUE THREAD

**Issue by tarim** [erikras/redux-form#2044]
Hi there,

I updated my dependencies, after update, I got error messages. Here is details. Need help.

Thanks,

ERROR in ./src/components/details.js
Module build failed: SyntaxError: C:/src/components/details.js: Only one default export allowed per module.

   **export default** connect(mapStateToProps,api)(Details);
 **export default** reduxForm({
    form: Details',
    fields,
    validate
},mapStateToProps,api)(Details);

**Comment by iyn** [comment]
It's not a problem with `redux-form`. As error message states, you can only have 1 default export in the file. If you use v6 (if you use versions below v6 please ignore this sentence), I can also see another problem with the code you posted - `reduxForm` API is different now, as it only takes configuration object and component and you pass mapStateToProps and api variables.

Assuming that you're using v6, you can do something like this:
```
export const DetailsForm = reduxForm({
// your redux-form config
})(Details);

export default connect(mapStateToProps){DetailsForm);
```

The default export here is component decorated with `reduxForm` and redux `connect`, but `redux-form` decorated component is also exported and can be imported somewhere else (e.g for tests) like this: `import { DetailsForm } from '(component path'`.

Does this solve your issue?

**Comment by gustavohenke** [comment]
As @iyn kindly answered, I'll close this one 😄
