### ISSUE TITLE
Policy to point people to StackOverflow when issue is related to their programming errors rather than problems with redux-form

### ISSUE THREAD

**Issue by iyn** [erikras/redux-form#2045]
I've been trying to help with the issues influx here, but when I answer few questions on one day, there are even more the next day. The problem is - most of the issues are related to the errors with people code and their mistakes rather than bugs and issues related to the `redux-form`. And because of that, I think it's hard to use Issues to be able to improve `redux-form` by fixing regular bugs/add features.

My proposal: when the issue/problem is obviously related to the bug in the person code rather than in `redux-form`, people/contributors should close the issue and point people to submitting the issue to SO. I know that it's in the guidelines for contributing but I don't see it enforced (i.e: issues are not closed and there's not info about moving the question to SO). What I'm proposing is more strict attitude and really enforcing the guidelines rule about SO.

**To be clear:** I'm not suggesting ignoring people's bugs and problems, I think we should still try help solve the problem when possible (e.g by suggesting what may be wrong), but still close the issue and point to SO.

I'd be happy to help, if @erikras is willing to grant me permission for closing/managing the issues. Or at least I could tag some issues so others could verify my judgement.

I honestly believe that the project can move forward faster with better focus (which can be improved with this policy, IMO). `redux` is the example project that has the policy I'm proposing (and people are still trying to help where possible), I think that it works great.

Please let me know what you think about this proposal.

**Comment by MilllerTime** [comment]
It does seem that there are more questions that belong on SO than issues/bugs with redux-form. The contribution guidelines already make mention that SO is better for personal code questions, but perhaps a more proactive approach would be beneficial at this point!

**Comment by gustavohenke** [comment]
Hey guys,
I've been given the mission of taking the number of open issues down around here :)

I'm using redux-form for a few months only, and I'm not an expert. I haven't tried lots of its possibilities yet, 
but mostly because I'm lazy in making a better form UX.
Therefore, whenever I can readily identify a question among so many issues, I do my best to answer it then close it.
