### ISSUE TITLE
Where is the "instance API"?

### ISSUE THREAD

**Issue by jampy** [erikras/redux-form#2048]
http://redux-form.com/6.1.1/docs/api/ReduxForm.md/ documents an "Instance API" that should provide a `values` property among others.

I don't understand where that API is.

```javascript
TreatmentForm = reduxForm({
  form: "TreatmentForm",
  destroyOnUnmount: false,
  enableReinitialize: true
})(TreatmentForm);
```

I don't get a `values` property passed the `props` of `TreatmentForm`.

Neither has the component instance a `values` property (`this.values` within `TreatmentForm`).

Also, I can't find the values anywhere in the component passed to `<Field component=... />`

Furthermore, the [selecting form values example](http://redux-form.com/6.1.0/examples/selectingFormValues/) accesses the Redux store directly instead of using any `values` object.

Is the documentation wrong or am I missing something?

In my concrete case I have a form input component that depends on the value of another form input.

**Comment by jampy** [comment]
Never mind. I understand that it's about the form *instance* that can be accessed via `refs`.

**Comment by unam3** [comment]
So, where it is, devs?

**Comment by unam3** [comment]
And why if I passed `values` prop with manually set up value in redux-form I get prop with undefined value in wrapped component?

**Comment by gustavohenke** [comment]
Hi @unam3! The instance APIs documented all around Redux Form site talk about methods and properties available when you request a reference to any of its components.

For example:

```
class MyForm extends Component {
  render () {
    // this.refs.bla now points to a Field instance
    // See http://redux-form.com/6.6.3/docs/api/Field.md/#instance-api
    return <Field name="bla" component="input" ref="bla" />
  }
}
```
