### ISSUE TITLE
Cannot type @ in validation example

### ISSUE THREAD

**Issue by epsitec** [erikras/redux-form#205]
Somehow, the magic behind the state auto-updating does not work for me on the [synchronous validation](http://erikras.github.io/redux-form/#/examples/synchronous-validation) example.

I cannot type `@` in any of the text fields (I am using a Swiss-French keyboard layout, which means that `@` requires me to type `Alt Gr`-`2`. If I switch to the US keyboard layout, everything works as expected (but then, `@` is generated by typing `Shift`-`2` and does not involve the right `Alt Gr` key).

**Comment by wmertens** [comment]
That seems impossible based on the code… there is nothing intercepting Alt as far as I can tell. Can you try adding https://github.com/fcomb/redux-logger and seeing what state changes are coming throngh?
If you remove redux-form and provide an empty fields object, does it work?

**Comment by SamLebarbare** [comment]
Shortcut interception is perhaps buggy?

https://github.com/gaearon/redux-devtools-dock-monitor/issues/1

**Comment by erikras** [comment]
Works okay for me with my Spanish keyboard layout (also `Alt-2` for `@`) on OS X. Pretty sure this isn't redux-form's fault.

**Comment by epsitec** [comment]
On a standalone test of redux-form everything works fine. However, on the online Redux Form tutorial it does not work. Sam is suspecting the shortcut interceptor used for the `Ctrl+H` or `Ctrl+Q` stuff.

**Comment by erikras** [comment]
Yep, I think @SamLebarbare is right.
