### ISSUE TITLE
Getting a value based on fields

### ISSUE THREAD

**Issue by hdmsoftware** [erikras/redux-form#2053]
So, I am not sure if this is possible..I have a deep nested fields object and part of it is something like
options: [
{optionid:1, name:'name 1', description:'description 1'},
{optionid:2, name:'name 2', description:'description 2'}
].

When I do something like in my render function
 {
   fields.map(function(option, index)  {
       console.log(option) -- I get option here which is a path to the deep nested location. something like "items[0].options[0].name","items[0].options[0].description"
   })
}

My question is how do I get the actual value here, not the path. I need to compare that value ( in my case id) with some other value and based on that render a Field component.

Any suggestion will be appreciated.

**Comment by gustavohenke** [comment]
Use `getFormValues` selector:

```js
let Component = ({ formValues }) => {
  console.log( formValues );
  return <div>...</div>;
};

Component = reduxForm({ form: "myForm" })( Component );
Component = connect( state => ({
  formValues: getFormValues( "myForm" )( state )
}))( Component );
```

[Docs](http://redux-form.com/6.4.1/docs/api/Selectors.md/)
