### ISSUE TITLE
Allow revalidation based on changing props

### ISSUE THREAD

**Issue by palmsey** [erikras/redux-form#2054]
My validation function depends on some non-redux-form values that are passed as props to the form component using `connect`. These values determine which form fields are required. I'd like to automatically revalidate the form when these connected props change, but it looks like validation isn't triggered because `defaultShouldValidate` returns false as long as the form values haven't changed.

I don't see how I can override this. Is there a different way I should set up this type of validation?

**Comment by palmsey** [comment]
I can get the desired behavior by dispatching a change to a fake field on the form whenever the external values change, but it seems like there should be a better way to do this.

**Comment by Aaron7** [comment]
The commit from #1995 allows you to override `defaultShouldValidate` using the `shouldValidate` config property.

It has been merged, so the next release should include it :)

**Comment by gustavohenke** [comment]
Hi @palmsey, can you please update Redux Form to at least v6.2.0 and check whether @Aaron7 is right?

**Comment by palmsey** [comment]
@gustavohenke this works as described. @Aaron7 thanks!
