### ISSUE TITLE
redux-form - getFormValues

### ISSUE THREAD

**Issue by Shadowman4205** [erikras/redux-form#2059]
Hello,
I am using first time redux-form. 
I have got CourseForm Component and i export it to CreateCourse Component with:
```
CourseForm = reduxForm({
    form: 'report'
})(CourseForm);

at CreateCourse i do this 
function mapStateToProps(state){
    return {
        course: state.form
    };
}
```

and on click i call saveCourse(this.props.course)
and it is give 3 objects , registeredFields,fields and values. But i want get only the values. 
i do not how use correctly getFromValues.

I tried putting this on CourseForm component
```
CourseForm= connect(
    state =>({ formValues: getFormValues('report')(state)})
)(CourseForm);
```
without changing CreateCourse Component.

Can someone guide me?

**Comment by alex-shamshurin** [comment]
Can you reformat your code at first? It's difficult to read.

**Comment by Shadowman4205** [comment]
Ok i get the values with handleSubmit, i forgot to use it in my form. Thanks.

**Comment by niksajanjic** [comment]
If you want to get it from state here is documentation about it:

http://redux-form.com/6.2.0/docs/api/Selectors.md/
http://redux-form.com/6.2.0/examples/selectingFormValues/

Also, if this issue has been resolved, please close it.
