### ISSUE TITLE
What is minimum I have to pass so form will update to state.

### ISSUE THREAD

**Issue by thedamon** [erikras/redux-form#206]
I would love to see some examples of onSubmit etc. All the examples I see seem to reinitialize the form to a blank state, but I don't see where the Redux state is being updated. And I'm not sure how much sate-updating is done by default through the redux-form library. So I'm trying to figure out what to put into my `onSubmit` etc but the examples are not reducing my confusion..

Say I have a singular `applicant` object in my state with a name field.
```
class App extends React.Component {
render() { return(
<ApplicantForm
  initialValues={this.props.applicant}
  onSubmit={updateApplicant} //the action for updating applicants
/>
);}
export default connect((state)=>state)(AdvancedMode);
}
```
```
class ApplicantForm extends Component {
	render() {
		const {fields: {name}, handleSubmit} = this.props;
		return (
			<form onsubmit={handleSubmit}>
				<label>Name:</label><input type="text" {...name} />
				<input type="submit" value="save" onClick={handleSubmit}/>
			</form>
		);
	}
}

ApplicantForm = reduxForm({
	form: 'applicant',
	['name']
})(ApplicantForm);

export default ApplicantForm;
```
With this setup it is updated, and re-renders on change and submit, but when I submit, it ends up with a 'redux-form/TOUCH' action and never actually updates the applicant in state.

my reducer looks like:
```
function applicant(state = {}, action){
	switch (action.type) {
	case UPDATE_APPLICANT:
		return Object.assign({}, state, action.applicant);
	default:
		return state;
	}
}
```

**Comment by erikras** [comment]
Where is your `updateApplicant` function? You left that out, so I can't tell if you are dispatching the `UPDATE_APPLICANT` action correctly.

**Comment by thedamon** [comment]
updateApplicant() is imported from my actions.js. Basically matches the
examples for setting up actions in the redux docs... I will post complete
code later on when I'm at my computer.

**Comment by erikras** [comment]
Have you figured this out?

**Comment by anorudes** [comment]
>I would love to see some examples of onSubmit etc.
+1
