### ISSUE TITLE
about nested FieldArray some question

### ISSUE THREAD

**Issue by timtian** [erikras/redux-form#2065]
when you use in nested FieldArray like this
```js
const renderMembers = ({ fields, meta: { touched, error } }) => (
  <ul>
    <li>
      <button type="button" onClick={() => fields.push({})}>Add Member</button>
      {touched && error && <span>{error}</span>}
    </li>
    {fields.map((member, index) =>
      <li key={index}>
        <button
          type="button"
          title="Remove Member"
          onClick={() => fields.remove(index)}/>
        <h4>Member #{index + 1}</h4>
        <Field
          name={`${member}.firstName`}
          type="text"
          component={renderField}
          label="First Name"/>
        <Field
          name={`${member}.lastName`}
          type="text"
          component={renderField}
          label="Last Name"/>
        <FieldArray name={`${member}.hobbies`} component={renderHobbies.bind(this)}/>
      </li>
    )}
  </ul>
)
```
i only  change example 
> <FieldArray name={`${member}.hobbies`} component={renderHobbies/>
to
> <FieldArray name={`${member}.hobbies`} component={renderHobbies.bind(this)}/>

you have to  click twice  to focus input(Hobby#1)..until click#2  focus to Hobby#1

![image](https://cloud.githubusercontent.com/assets/3632841/19932707/f3c81d42-a14b-11e6-81b0-0f39e7094eff.png)

**Comment by bmv437** [comment]
Hi there. I'm unsure what your question is about exactly?

**Comment by gustavohenke** [comment]
Hi @timtian, you question is not clear.
Also, in React when a function is supposed to render a component it's usually not a good idea to call `.bind(this)` on it, as the new component may interfere with the external component's `this`.

In case you can show us code that reproduces your issue, it would be great.
