### ISSUE TITLE
Do we need getFormSubmitErrors ?

### ISSUE THREAD

**Issue by rndm2** [erikras/redux-form#2069]
I need to get submitErrors, and I think it should be created new selector getFormSubmitErrors like getFormSyncErrors. Isn't it?

**Comment by bmv437** [comment]
If you think it's a useful feature, then I would suggest you come up with an implementation and create a PR 😄

**Comment by rndm2** [comment]
Ok, I will

**Comment by dpwrussell** [comment]
I think this could probably be closed.

**Comment by gustavohenke** [comment]
Yup @dpwrussell!
