### ISSUE TITLE
Sync validate trigger

### ISSUE THREAD

**Issue by luckyraul** [erikras/redux-form#2071]
Hi guys. 

How can I trigger a sync form validation of a form by name ? 

Currently I need to show all field's errors from action if my form is invalid.

**Comment by Mottoweb** [comment]
Hi,

You can control the display of errors in your renderField function. Usually you'd want to show errors when the field was touched.

So you can either dispatch a submit action like explained - here http://redux-form.com/6.2.1/examples/remoteSubmit/ this will mark touched all your fields.
