### ISSUE TITLE
Redux Form 6.1.1 - validation on blur is not working on react-native

### ISSUE THREAD

**Issue by kmanishprdxn** [erikras/redux-form#2073]
I'm working on react-native (Android) where I'm using redux-form 6.1.1.

One weird behaviour I've notice i.e redux-form doesn't perform validation when I remove focus(blur) from input field, however on submit validation is working as intended.

Please guide me here. Below is my code.

**Text field component**

```
<TextInput
  keyboardType={ textType ? textType : 'default' }
  onChangeText={ (val) => onChange(val) }
  value={ value }
  underlineColorAndroid="transparent"
  style={ styleInput }
  {...this.props}
/>

{/* Error message */}
<View>
  {
    touched && error ?
    <Text>{error}</Text>
    : null
  }
</View>
```

**Implementation of this text field component as below**

```
// Import text field
import TextField from 'src/components/text_input/text_input';

......
......

<Field
  component={TextField}
  name="phoneNumber"
  placeholder="Mobile Number"
  styleInput={styles.inputs}
  styleInputWrap={styles.inputView}
/>
```

**validate function**

```
function validate(values) {
  const err = {};

  // common function for phone number validation
  validatePhoneNumber(err, 'phoneNumber', values.phoneNumber);

  return err;
}
```

**Note:** I observe that from **touched && error** condition error contains required error message but touched remains false even after switch/focus to another input field. As soon as I hit the submit button touched flag set to true.

**Comment by kmanishprdxn** [comment]
I found the workaround for this but still if their is any better way then please update.

below is my updated code(with working blur event).

**Updated Text field component**

```
const {
  input: { value, onChange, onBlur }
} = this.props;
... 
...
<TextInput
  keyboardType={ textType ? textType : 'default' }
  onChangeText={ val => onChange(val) }
  onBlur={ val => onBlur(val) } {/* <--- added onBlur function */}
  value={ value }
  underlineColorAndroid="transparent"
  style={ styleInput }
  {...this.props}
/>

{/* Error message */}
<View>
  {
    touched && error ?
    <Text>{error}</Text>
    : null
  }
</View>
```

I just passed onBlur props/function provided by redux-form field to onBlur function of TextInput field(provided by react-native) and every thing is working properly.

**Comment by JeroenNelen** [comment]
Any updates/news on this one?
I noticed we can also use dirty in stead of touched but it looks like a bug to me none-the-less.

Kind regards,

**Comment by ryanhomer** [comment]
I'm having the same issue in React (JS) which is not in accordance with the default behaviour according to the manual. It does indeed appear to be a bug. While the workaround is nice, it means having to pass the onBlur function each time into my custom field render function in order to hook it up to the actual input control.

**Comment by deepaksisodiya** [comment]
My workaround

```
function asyncValidate(values, dispatch, props) {
  const errors = {};
  let emailId;
  if (!values.emailId) {
    // on Android, the values object somehow has emailId as undefined
    emailId = props.values.emailId;
  } else {
    emailId = values.emailId;
  }
 
  return errors;
}
```
