### ISSUE TITLE
Irritating issue with redux-form.com

### ISSUE THREAD

**Issue by Pszek** [erikras/redux-form#2080]
Please add css property ```white-space: nowrap;``` to  ```a``` element containting 'Redux-form' header/title in the left Navbar.

![zrzut ekranu 2016-11-04 o 14 13 56](https://cloud.githubusercontent.com/assets/10253750/20006686/08f2031a-a299-11e6-93e4-f37bf7be978f.png)

**Comment by gustavohenke** [comment]
This is fixed.
