### ISSUE TITLE
Hamburger button unresponsive

### ISSUE THREAD

**Issue by Pszek** [erikras/redux-form#2081]
Hamburger button visible on smaller screens is unresponsive in Chrome (both desktop & mobile; didn't try in different browsers).

![zrzut ekranu 2016-11-04 o 14 18 23](https://cloud.githubusercontent.com/assets/10253750/20006835/b3cbcfe6-a299-11e6-9ba4-51d93bfc8a4e.png)

**Comment by gustavohenke** [comment]
Cool, it seems like this happens because of an error in some pages.

```
Uncaught TypeError: Cannot read property 'PropTypes' of undefined
    ...
Uncaught ReferenceError: initReact is not defined
    at (index):114
```

In the examples, for example (doh!), that icon works...

**Comment by gustavohenke** [comment]
Will close here, since it seems like it's a duplicate of #1808 with less information
