### ISSUE TITLE
Update radio group label based on required validation?

### ISSUE THREAD

**Issue by moksamedia** [erikras/redux-form#2087]
Given the simple example formulation of the radio group:

`      <div>
        <label>Sex</label>
        <div>
          <label><Field name="sex" component="input" type="radio" value="male"/> Male</label>
          <label><Field name="sex" component="input" type="radio" value="female"/> Female</label>
        </div>
      </div>`

How can I update the label based on required validation? That is to say, I want the radio group to be required, and I want to be able to update the text and/or class of the <label> tag if the user tries to submit the form without answering. What is the recommended way of accomplishing this?

Thanks,

Andrew

**Comment by moksamedia** [comment]
Never mind. Figured it out. Nothing like asking for support to get the answers flowing.

**Comment by lakesare** [comment]
@moksamedia, trying to do the same thing, how did you solve it?

**Comment by moksamedia** [comment]
You just use a Field component with an items prop that maps to the input items in a custom render component or method.

`     <Field
        name="someName"
        component={RadioBox}
        items={[
          {value: "wilderness", text: "Wilderness"},
          {value: "center", text: "Retreat Center"},
          {value: "mix", text: "Mix of wilderness and indoor practice"},
        ]}
      />
`

`
class RadioBox extends React.Component {

  render() {

    let {
      input,
      name,
      items,
      meta: { touched, error, warning }
    } = this.props;

    let classes = ['form-input-group'];

    if (touched) {
      classes.push('touched');
      if (error) {
        classes.push('has-error has-feedback')

      }
      else if (warning) {
        classes.push('has-warning has-feedback')
      }
    }

    return (
      <div className={classes.join(' ')}>
        <SwitchLabel {...this.props}/>
        <div className="radio-box-input-group">
          {items.map((item) => (
            <label key={item.value}><input onChange={input.onChange} checked={ input.value === item.value } name={name} type="radio" value={item.value}/> {item.text}</label>
          ))}
        </div>
      </div>
    )

  }`

Does that make sense?
