### ISSUE TITLE
Button Click Triggers OnSubmit listener

### ISSUE THREAD

**Issue by Kamps-Duac** [erikras/redux-form#2092]
Using `"redux-form": "^6.0.5"`, clicking on any element of type `button` without explicitly declaring that button element to be `type="button"` triggers the form submission. The functionality should require the button to be explicitly declared as `type="submit"`, or documentation should clearly state that the form will be submitted if `type="button"` is omitted.

**Comment by UnbrandedTech** [comment]
This was such a PITA to figure out, should be in the Docs as a red popup. OR make redux form require a submit button...

**Comment by niksajanjic** [comment]
It don't think it should be mentioned in the documentation. If button doesn't have type attribute set it is going to be submit button by default. That is defined by specification and developers should be aware of that so this isn't redux-form problem.

https://www.w3.org/TR/html401/interact/forms.html#edef-button
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button

**Comment by gustavohenke** [comment]
Thanks for doing the job @niksajanjic :)
