### ISSUE TITLE
Add feature so that _errors is only cleared on submit.

### ISSUE THREAD

**Issue by fingermark** [erikras/redux-form#2098]
One of the features I really like about redux-form is the ability to set a global/general form error, such as "invalid username or password."  In my code I have `reject(new SubmissionError({_error: message}))` and then I display that error in my login form with something like `<div className='error'>{error}</div>` at the very top of the form.  This works great, but as soon as the user enters text into a field that error message goes away and the page jumps.  

I would like to keep validation the same for all input fields (which I believe defaults to onSubmit and onChange -- I don't know how to set it to just onSubmit and onBlur), but add the ability to only clear the _error onSubmit.  This would result in the `_error`only clearing when the form is submitted and thus the page only jump when the user clicks `submit`.

**Comment by umidbekkarimov** [comment]
You can use `submitFailed` and  `submitSucceeded` props to control error text visibility

**Comment by grossmail1** [comment]
6.2.0 release notes says this has been fixed. Which version are you using?

**Comment by gustavohenke** [comment]
@fingermark, please check with v6.2.0.
Related: #1980
