### ISSUE TITLE
[6.2.0, 6.1.1] Issue has us lost between two versions.

### ISSUE THREAD

**Issue by nmaves** [erikras/redux-form#2099]
We have found ourselves stuck somewhere between 6.1.1 and 6.2.0 and could use some help.

We have a wizard form and are seeing two different issues.

The first issue is around a  manual field change ( `this.props.input.onChange(...)`) within our component.   I see the onChange action just fine and our redux state for that form is updated but render is never called and there for our submit button is never re-enabled per the code below.

This was working in 6.1.1 using the code below.

```
const { handleSubmit, error, invalid } = this.props
```

```
<button className="button-primary" type="submit" style={[ invalid && disableStyle ]}
						disabled={invalid}>
``` 

It fails on 6.2.0 and I think has to do with the reversal of code in the PR #1980 

The second issue of ours is resolved by upgrading to 6.2.0.  We have a different page within the same wizard form where the form is becoming valid when it should not be.  We feel this is somehow related to #1925.

Can any one turn the light house on and help git us though the fog?

**Comment by grossmail1** [comment]
I recently saw something similar when I upgraded to 6.2. We have a custom component calling an onChange but that wasn't rerendering one of our components that was looking at the state of the form.  I haven't found a solution and didn't have time to dig into the code so I just rolled it back.

**Comment by nmaves** [comment]
This was an issue with a configuration issue on our side.

**Comment by amangeot** [comment]
Hello guys,
I just saw the new `shouldValidate` function which is:
> An optional function you may provide to have full control over when sync validation happens.

I was wondering if it was a use case for wizard forms, have you tried it ?
