### ISSUE TITLE
Deep form structure and deep validation

### ISSUE THREAD

**Issue by vslinko** [erikras/redux-form#21]
Hi! Thank you for your library.

I want to use `redux-form` with complex deep structures. Simple example of complex structure I want to use:

```js
{
  users: Array[
    {
      name: string,
      group: {
        name: string
      }
    }
  ],
  confirmed: boolean
}
```

What are you think, is it possible to implement in `redux-form`?

Also I have [validator for complex deep structures](https://github.com/vslinko/strulidator).
I'm in deep refactoring right now, but I'll release a new version soon with async validation, simpler API, etc.
So, could you change API of validator from `({}) => {}` to something like that:

```js
type ValidatorResult = {valid: true, [key: string]: any}
type Validator = (data: Object) => ValidatorResult | Promise<ValidatorResult>
```

And check only for `valid` property, not for every object key.
With that API I could use my validation library with your form library.

**Comment by vslinko** [comment]
Your example of validator with my API suggestion:

```js
function contactValidation(data) {
  const errors = {valid: true};
  if(!data.name) {
    errors.name = 'Required';
    errors.valid = false;
  }
  if(data.address && data.address.length > 50) {
    errors.address = 'Must be fewer than 50 characters';
    errors.valid = false;
  }
  if(!data.phone) {
    errors.phone = 'Required';
    errors.valid = false;
  } else if(!/\d{3}-\d{3}-\d{4}/.test(data.phone)) {
    errors.phone = 'Phone must match the form "999-999-9999"';
    errors.valid = false;
  }
  return errors;
}
```

**Comment by erikras** [comment]
That seems perfectly reasonable.

**Comment by vslinko** [comment]
I see you done with validator API, thank you.
But what are you think about complex deep structures?

**Comment by erikras** [comment]
Oh, does your library not bubble up the `valid:false`'s up to the top?

I don't think it's redux-form's responsibility to implement fancy validation. That should be up to the user of the library.

**Comment by vslinko** [comment]
I probably put it unclear.

I talking about form data, not validation. Now `redux-form` supports only flat forms:

```js
createFormReducer('contacts', ['name', 'address', 'phone'])
```

Do you have plans to support nested forms in `redux-form`?

**Comment by erikras** [comment]
Ah! I see.

I'm not sure. When things get deep, you end up with complex schemas. Name-value pairs are so delightfully simple. If someone (you?) could come up with a good proposal for how to do deep forms that still allowed for a simple flat form api, I'd be willing to consider it. Nothing is springing immediately to mind, and most of my form needs are pretty flat.

**Comment by vslinko** [comment]
That's great. When I'll build next complex form I'll try to create PR with my solution.
