### ISSUE TITLE
Map dispatch to form

### ISSUE THREAD

**Issue by rdubrock** [erikras/redux-form#210]
Sorry if this has been answered elsewhere, I'm a Redux beginner, and I couldn't find anything in the docs or here on Github. 

I'm having trouble mapping dispatch to ReduxForm. Im setting up my reducers like this:

    import { reducer as formReducer } from 'redux-form';
    import foo from './foo';
    import bar from './bar';

    const rootReducer = combineReducers({
      foo,
      bar,
      form: formReducer
    });

    export default rootReducer;

and then combining them like so:

    import rootReducer from '../reducers/index';

    const loggerMiddleware = createLogger();

    const createStoreWithMiddlware = applyMiddleware(
       thunkMiddleware,
      loggerMiddleware
    )(createStore);

    export default function configureStore(initialState) {
      const store = createStoreWithMiddlware(rootReducer, initialState);
      return store;
    }

and then mapping dispatch to props like this:

    function mapDispatchToProps(dispatch) {
      return {
        actions: bindActionCreators(Actions, dispatch),
      }
    }

    export default connect(
      mapStateToProps,
      mapDispatchToProps
    )(App)

And then I have a form component that I am wrapping in a reduxForm like this:

    TestForm = reduxForm({
      form: 'testForm',
      fields: ['firstName', 'lastName', 'email']
    })(TestForm);

    export default TestForm;

But I get an error: 
    Warning: Failed propType: Required prop `dispatch` was not specified in `ReduxForm(TestForm)`. Check the render method of `TestFormParent`.

What is the best way to inject dispatch into a form component?

**Comment by pyryjook** [comment]
I'm having the same problem.

**Comment by rdubrock** [comment]
I figured it out last night. The docs on npm are different and a little more complete. Instead of wrapping your form component in reduxForm(), wrap it in connectReduxForm(). Check it out [here] (https://www.npmjs.com/package/@jimpick/redux-form#submitting-your-form).

**Comment by pyryjook** [comment]
ok, thanks!

**Comment by erikras** [comment]
Yeah, sorry. While v3 is in beta, there's an inconsistency between the docs and the current "release" version at npm.
