### ISSUE TITLE
Decorated form doesn't receive documented values instance prop

### ISSUE THREAD

**Issue by jaredh159** [erikras/redux-form#2101]
According to: http://redux-form.com/6.2.0/docs/api/ReduxForm.md/

... in the section labeled _Instance API_ the decorated component should have access to a `values` property, which should be

> The current values of all the fields in the form.

But, no matter what I do, I can't get the documented `values` property, either in my own code, or by pulling down the simple example and modifying it.

A simple example is conditionally rendering something in the form based on the current value, which seems like exactly what the documented `values` object would be ideal for.

```ES6
import React from 'react'
import { Field, reduxForm } from 'redux-form'

const MyForm = ({ handleSubmit, values }) => (
  <form onSubmit={handleSubmit}>
    <div>
      <Field name="name" component="input" type="text"/>
      {values.name === 'Fred' && <b>Hi Fred!</b>} // <-- error! `values` undefined
    </div>
  </form>
);

export default reduxForm({ form: 'myForm' })(MyForm);
```

Or am I totally mis-understanding the documentation?

**Comment by niksajanjic** [comment]
I personally use selectors to get values from Redux store:

http://redux-form.com/6.2.0/examples/selectingFormValues/

But I can confirm that this doesn't work. Either it's not yet supported or it's not meant to be and it's not removed from docs.

**Comment by oyeanuj** [comment]
This seems to be a breakage in 6.2.0. It used to work fine in 6.1 but not any more. I get the same `values` undefined error in the the validate function on form initialization.

cc: @erikras, any thoughts on what might be going on?

**Comment by oyeanuj** [comment]
On further investigation, seems like #2091 fixes this problem for me. @jaredh159, you might want to try that.

**Comment by martinhorsky** [comment]
@jaredh159 Yes, you misunderstand docs and maybe what "instance" in React world means.

You are trying to get values from prop `values`. But it does not exists.

`values` you mentioned are available from instance of decorated component. 
To understand that, let's see example:

```javascript
import React from 'react'
import { Field, reduxForm } from 'redux-form'

const MyForm = ({ handleSubmit }) => (
  <form onSubmit={handleSubmit}>
    <div>
      <Field name="name" component="input" type="text"/>
    </div>
  </form>
);

export default reduxForm({ form: 'myForm' })(MyForm);
```

```javascript
import React, { Component } from 'react'
import MyForm from './MyForm'

class MyContainer extends Component {

  componentDidMount() {
    console.log(this.form.values) // <-- here you can get values from instance of reduxForm
  }

  render() {
    <MyForm ref={ (instance) => { this.form = instance } } />
  }
}
```
That's how Instance API works. You can see from example it's designed for different usecase.

You should use what @niksajanjic suggests... 
`formValueSelector` + `connect`
see: http://redux-form.com/6.2.0/examples/selectingFormValues/

I hope this explanation will help. 😀

**Comment by gustavohenke** [comment]
Amazing explanation, @martinhorsky, thank you!
