### ISSUE TITLE
Infinite REGISTER_FIELD/UNREGISTER_FIELD loop

### ISSUE THREAD

**Issue by elmeister** [erikras/redux-form#2103]
First of all - thanks for the great component to keep form state in a Redux store!
It helps us a lot to manage customisable forms.

The problem we have with 6.2.0 is that infinite REGISTER_FIELD/UNREGISTER_FIELD loop appears when we try to get form field values. Initial values is an object, containing array `{ dataLocators: [] }`. Here is the code we use to get current values:
```
@reduxForm({
  form: 'layout-generator-settings',
  validate
})
@connect(
  state => ({
    values: selector(state, 'dataLocators')
  })
)
```
That's it, now everything redux-form does on form load - registering and unregistering all values in array 
<img width="411" alt="screen shot 2016-11-09 at 22 01 30" src="https://cloud.githubusercontent.com/assets/10223953/20142674/57400ade-a6c8-11e6-8a33-668bdc48dc38.png">
<img width="403" alt="screen shot 2016-11-09 at 22 04 13" src="https://cloud.githubusercontent.com/assets/10223953/20142700/7e4a6e30-a6c8-11e6-9e17-fed0795e246f.png">

Will appreciate your help a lot.

**Comment by niksajanjic** [comment]
I can't say I know what is happening, but I usually have connect decorator before redux decorator. With this arrangement your redux decorator will pass down values which will be object of all values in a form, here:

http://redux-form.com/6.2.0/docs/api/ReduxForm.md/#instance-api

Now, after that you are overriding those values by defining values through connect so my guess is that is doing something weird for you. Try changing name in connect and maybe you should revert decorators. Maybe that helps.

**Comment by elmeister** [comment]
@niksajanjic, thanks a lot for your efforts and help!
Both - decorators order and values name was taken from [Selecting Form Values](http://redux-form.com/6.2.0/examples/selectingFormValues/) sample.
I've tried to revert connect and reduxForm decorators and to rename **values** to **stateValues**, but unfortunately situation is the same.
Actually passed initial values are reachable - `values: selector(state, 'dataLocators')` returns correct values from `state.form[formId].values.dataLocators`.
The only problem is the infinite loop of REGISTER_FIELD/UNREGISTER_FIELD actions.

After 3 UNREGISTER_FIELD state looks like this:
<img width="251" alt="screen shot 2016-11-11 at 10 35 55" src="https://cloud.githubusercontent.com/assets/10223953/20203543/c467e004-a7fa-11e6-8adc-c10367859675.png">

Then, after 3 REGISTER_FIELD, state contains 5 registered fields:
<img width="369" alt="screen shot 2016-11-11 at 10 37 52" src="https://cloud.githubusercontent.com/assets/10223953/20203558/eed99224-a7fa-11e6-87dc-061a68e4657e.png">

When all 5 fields registered, redux-form continue to unregister last 3 of them, then register them again and so on. 

Same situation with loop appears without selector usage, with `connect` before `reduxForm`.
```
@connect(
  state => ({
    values: state.form[formId] ? state.form[formId].values.dataLocators : []
  })
)
@reduxForm({
  form: formId,
  validate
})
```
Without connect (when `@connect` block is removed) everything is fine with loop, but current selected values aren't available.

**Comment by elmeister** [comment]
Well, the problem is mentioned in [Selecting Form Values Example](http://redux-form.com/6.2.0/examples/selectingFormValues/), here it is: _**WARNING**: Use this method sparingly, as it will cause your entire form to re-render every time one of the values you are selecting changes._
Re-render triggered Field component unmount and for each unmount all fields was unregistered, then component was mounted, so all fields was registered again, props change triggered component remount and so on.
Switch to stateless functions and pass values directly fixed the problem, thanks for help!
