### ISSUE TITLE
createOnDrop loses value of text area

### ISSUE THREAD

**Issue by mattkrick** [erikras/redux-form#2105]
I have a card. inside that card is a textarea. When i drag that card to another spot, it works fine _unless i click inside the textarea to begin the drag_. If I do that, then when I drop it, a CHANGE action is triggered, which sets the value to `''`.
Is this expected? 

Can provide a repo if needed, cheers!

**Comment by Marinolinderhof** [comment]
same as https://github.com/erikras/redux-form/issues/1352

**Comment by gustavohenke** [comment]
Closing in favor of #1352.
