### ISSUE TITLE
Having crazy hard time trying to set the value of an input when changing the value of another one  

### ISSUE THREAD

**Issue by bstenm** [erikras/redux-form#2106]
Just want to set the value of an input text to empty when clicking on a radio button and giving up after a few hours trying unsuccessfully... Any idea?

**Comment by elmeister** [comment]
@bstenm, what is the main difficulty? Have you checked [selecting form values](http://redux-form.com/6.2.0/examples/selectingFormValues/) topic of the documentation?

**Comment by bstenm** [comment]
Yes I have and I understand how to access form values but I just don't see how to set an input value programmatically? Am I missing something obvious? Do you have a working example?
Cheers!!

**Comment by elmeister** [comment]
`input.onChange(newValue)`?

**Comment by elmeister** [comment]
Please check [this option](https://github.com/erikras/redux-form/issues/622) as well

**Comment by bstenm** [comment]
hey yes thanks a lot mate, that's what I was trying and the option that made more sense, but for some reason I couldn;t make it work. I;ll try again it's probably sth silly I can't see because that really should work.
Cheers!!
