### ISSUE TITLE
Custom input component props

### ISSUE THREAD

**Issue by Neophy7e** [erikras/redux-form#2108]
In the [docs](http://redux-form.com/6.2.0/docs/faq/CustomComponent.md/) it says 

> The minimum interface needed for a custom component to work with redux-form is to make sure that value and onChange are passed properly. These are pretty standard prop names, so it's possible that your component will work right out of the box.

But as you can see [here](https://github.com/erikras/redux-form/blob/master/src/ConnectedField.js#L64-L70) the value and onChange props aren't passed in a pretty standard way to a custom component but they are passed inside an input object props.

Would it be interesting to maybe have an optional prop that can be passed to the Field component that will pass standardized props directly ?

**Comment by niksajanjic** [comment]
You can already pass any other props you want to Field component and then attach it to your input:

```
<Field
  name="email"
  component={Input}
  placeholder="This is placeholder"
  type="email"
/>
```

```
const Input = (props) => {
  const { input, meta, ...rest } = props;

  return (
      <input {...input} {...rest} />}
  );
};
```

Now your input will have placeholder and type selected through ...rest (spread operator).

**Comment by gustavohenke** [comment]
As @niksajanjic answered this one, I'll close it.

**Comment by raykudo** [comment]
When I try to submit the form I found my value of  ``` <Field name="email" component={Input} />``` is not updated. I can call a callback from Input and get the value at Component rendering ```<Field>``` but not sure how to change the value of <Field>.
