### ISSUE TITLE
validate action

### ISSUE THREAD

**Issue by snowcxt** [erikras/redux-form#211]
Could you provide `validate`, `getValues` and `sumbit` actions so that I can easily reuse the components in any forms. For example, I can create an Address component and use it in the profile form. I can call   `this.props.validate('address')` to trigger the validation of the Address component and call `this.props.getValues('address')` to get the actual values.

**Comment by erikras** [comment]
I'm not sure I understand. What is `this` in your example? The component that contains your reusable `<Address/>` input component?

**Comment by Lonelind** [comment]
An ability to validate form fields separately is very useful for me. For example, I have one single form to submit. But it is big and for usability purposes I need it to be filled by parts, step-by-step with separate validation for every step: you couldn't fill any step without filling up the previous one with valid data. This looks like a wizard or something.

**Comment by snowcxt** [comment]
Just need two more actions like `initailize` or `change`. e.g. You can get the values by `var address = this.props.getValues('address')` (`this` is a react component, definitely you need to connect to the redux form) So the code could like it:

```javascript
import {getValues} from 'redux-form';
@connect(null, {
  getValues
})
export default class Profile extends Component {
    getAddress(){
      return this.props.getValues('address');
    }
}
```

**Comment by erikras** [comment]
Huh? How can dispatching an action return store values without some Redux middleware?

**Comment by snowcxt** [comment]
You are right. But could you provide the `validate` action? Which just trigger the validation action for a form.

**Comment by snowcxt** [comment]
Furthermore, I'd like to pass in a new validation function for a form. e.g. I could use `Address` on the profile page and all the fields are optional, but when it's on the admin page all the field would be required.  So I'd could need an options parameter, like

```javascript
this.props.validate('address', a_validation_function);
```

Is that possible?

**Comment by erikras** [comment]
As of `v3.0`, all config properties passed to `reduxForm()` can be passed as props to your decorated component, so the sync validation function would be included. However, I might choose to use the fact that the props are passed in to the sync validation function to give an `addressRequired={true}` prop for your validation function to check. If that makes sense...

**Comment by snowcxt** [comment]
Could you provide an example?

**Comment by erikras** [comment]
```js
@reduxForm({
  form: 'profile',
  validate: (values, props) => {
    const errors = {};
    if (!values.firstName) {
      errors.firstName = 'Required';
    }
    if (props.requireAddress) {
      if (!values.street) {
        errors.street = 'Required';
      }
      if (!values.city) {
        errors.city = 'Required';
      }
    }
    return errors;
  }
})
class Profile extends Component {
  render() {
    const {fields: {firstName, street, city}} = this.props;
    return (
      <div>
        <input type="text" {...firstName}/>
        <Address {...{street, city}}/>
      </div>
    );
  }
}

class Address extends Component {
  render() {
    const {street, city} = this.props;
    return (
      <div>
        <input type="text" {...street}/>
        <input type="text" {...city}/>
      </div>
    );
  }
}

class ProfilePage extends Component {
  render() {
    return (
      <div>
        <h1>Profile</h1>
        <Profile requireAddress={false}/>
      </div>
    );
  }
}

class AdminPage extends Component {
  render() {
    return (
      <div>
        <h1>Admin Profile</h1>
        <Profile requireAddress={true}/>
      </div>
    );
  }
}
```
Does that help?

**Comment by snowcxt** [comment]
Thank you very much!

But I still need a way to trigger the submit event externally. So that I can reuse a component in different forms. Do you have a plan for that?

**Comment by erikras** [comment]
It's being thought about. :grimacing: :hourglass: Not sure yet about the best solution.

**Comment by snowcxt** [comment]
I just need something like it

```javascript
this.props.validate('address');
```

which just triggers the validate event of the address form and then I can get the result from props.

**Comment by damassi** [comment]
I was just about to file an issue for the same thing. Our form setup is quite complex and big, with a lot of individual forms being combined together, with their values being serialized up to a higher order "resource" reducer on change or submit. The thing is, the 'Submit' button has no knowledge of any of the other forms, just the overall "formData" object as it is returned from the HOR. 

Do you know of a solution that would allow me to click a submit button that then dispatches a synchronous "validate" action to an array of forms that I can then check against before allowing a proper submit?

**Comment by damassi** [comment]
Wondering if any more thought has been given to this? I just updated redux-form to the latest from a few versions back (great work on backwards compat, btw). @snowcxt's approach is essentially what i need, but via an action creator. Any help / direction would be appreciated.

**Comment by ooflorent** [comment]
It is possible to trigger a validation using `handleSubmit(noop)`. This is currently the only way of doing this.

**Comment by magnusheino** [comment]
Was this issue resolved?

I am using field-level validation, and I want to trigger the validator to revalidate a field. Not because the value has changed, not because the user has done anything, but because the validator has changed. How can this be done? 

Right now I dispatch the change-action for the field with the same value + ' '... but that is not nice :-P Is there really no way to validate a field besides changing the value?

**Comment by alex-shamshurin** [comment]
I think the issue should be reopened. I really need `validate` action creator. I need form values to be restored from the local storage, and when it's done, all field values are restored  via `change` action and all fields are `touched`  - sync validation does not occur.

**Comment by AlisterC93** [comment]
I would also appreciate this functionality.

**Comment by likerRr** [comment]
Also need some trigger to validate a form. 
For now since my form fields display errors only when they touched, so I use `touch` action creator when user opens form for editing, like this:

```
dispatch(touch('myForm', ...Object.values(MyForm.requiredField)));
// MyForm.requiredField is an object with required fields
```

**Comment by RaulTsc** [comment]
+1

**Comment by alex-shamshurin** [comment]
Reopen this, please

**Comment by erikras** [comment]
[Sync] Validation happens on every render. Validation has never _not_ been run. This issue predates when the sync validation errors were finally put into Redux, and now we have [selectors](https://redux-form.com/7.0.4/docs/api/selectors.md/#-code-getformsyncerrors-formname-string-code-returns-code-state-gt-formsyncerrors-object-code-) to fetch them.

I'm confused as to the motives to reopen this issue. Please enlighten me?

**Comment by alex-shamshurin** [comment]
Ok, I understand that, but how to run _validation_ when I need it?

**Comment by danielpowell4** [comment]
Here is a hack to force the form to rerender and thus revalidate

```
// simulate an event to trigger a revalidate via componentShouldUpdate
let toggleValidationCount = 0;
export const forceRevalidateForm = _ => dispatch => {
  dispatch(change("formNameHere", "forceValidate", toggleValidationCount++));
};
```

I'm dispatching this action to revalidate a form when the validation type is toggled as such:

```
onValidationRuleClick = rule => {
    return () => {
      this.props.setValidationRule(rule);
      this.props.forceRevalidateForm();
    };
  };
```

The use case for the app I'm working on includes a convenience validation toggle for downstream actions.

Validation type 1: for users entering a potential lead (less info required, left tab)
Validation type 2: for users entering a client for activation (more info required, right tab)

![validation toggle](https://user-images.githubusercontent.com/15863213/37852157-2e953b0a-2ea7-11e8-9c01-a358610c8f3f.gif)

Another option could be to have the validation type stored as a value in the form, but this is the solution we ended up with
