### ISSUE TITLE
FieldArray with a lot of redux-form/REGISTER_FIELD and redux-form/UNREGISTER_FIELD

### ISSUE THREAD

**Issue by luiskhernandez** [erikras/redux-form#2111]
Hi, i am trying to create a EditableField component. An element that when you click on it, it toggles to a Field so you can edit it.

I have a FieldArray field that renders a lot of Components with this `EditableField` comp

The issue is that when typing i am getting a lot of `redux-form/REGISTER_FIELD and redux-form/UNREGISTER_FIELD` from the other fields that are not being changed.

Should i hide/show the fields with css, or there is any way on how to prevent this

``` 
 class EditableField extends Component {

  state = {
    editable: false
  }

  toogleEdit () {
    this.setState({ editable: !this.state.editable })
    }
  shouldComponentUpdate(nextProps, nextState) {
    return this.state.editable !== nextState.editable
  }

  render () {
    const { presenter, cancelOption } = this.props
    if (this.state.editable) {
      this.field = this.props.field(this.toogleEdit.bind(this))
      return (
        <div>
          {this.field}
          {cancelOption &&  <span className='editable--button' onClick={() => this.toogleEdit()} > Cancel </span> }
        </div>
      )
    } else {
      return (
        <div className='editable' onClick={ () => this.toogleEdit() } >{presenter}</div>
      )
    }
  }
}
```

full code at [survey-builder](https://github.com/luiskhernandez/survey-builder)

**Comment by igorbarbashin** [comment]
@luiskhernandez have you figured out this issue?
