### ISSUE TITLE
validation stops working if I overwrite onBlur for Field

### ISSUE THREAD

**Issue by KTruong888** [erikras/redux-form#2112]
I have a Field that needs some custom onBlur functionality, but when I implement my functionality, the normal sync validation stops working. I can still see the error getting updated within props.meta.error when I console log with componentDidUpdate, but it doesn't actually show the error. 

I've tried tinkering with manually dispatching a 'touch' action, and trying asyncValidation too, but the error field doesn't show up unless I leave the onBlur prop alone. 

Is there a way I can implement my own onBlur function, while still retaining the original error validation stuff?

This is the component I'm making:

```
class PostalCodeTextInput extends React.Component { // eslint-disable-line
  fetchAddressesValid = () => {
    // this.props.async();
    if (this.props.input.value.length > 5) {
      if (!this.props.meta.error) {
        this.props.fetchAddresses(this.props.input.value);
      }
    }
  }

  render() {
    const { helpText, input, label, type, meta: { touched, error } } = this.props;
    const classNames = classnames({
      'text-input': 'text-input',
      'form-group': 'form-group',
      invalid: touched && error,
    });
    return (
      <div className={classNames}>
        <label htmlFor={label}>{label}</label>
        <div>
          <input
            {...input}
            type={type}
            placeholder={label}
            onBlur={this.fetchAddressesValid} // *
          />
          {touched && error && <p className="warning">{error}</p>}
        </div>
        <small><em>{helpText}</em></small>
      </div>
    );
  }
}

```

And this is the validation that's supposed to apply:

```
const validate = (values) => { // eslint-disable-line
  const errors = {};

  // NewAddressFields
  if (!values.get('postal_code')) {
    errors.postal_code = 'Required';
  } 
```

**Comment by KTruong888** [comment]
and the link to the stackoverflow question with pictures:

http://stackoverflow.com/questions/40535105/how-to-keep-sync-validation-with-redux-form-v6-while-implementing-custom-onblur

**Comment by niksajanjic** [comment]
You shouldn't overwrite onBlur without enabling redux-form onBlur functionality. Can you please try this:

    onBlur={(e) => {
      input.onBlur(e);
      this.fetchAddressesValid();
    }}

This way you are still doing what you want onBlur, but you are also enabling redux-form onBlur action at the same time. I suppose this should fix the issue for you. Enhancement should happen in the future:

https://github.com/erikras/redux-form/issues/883

Another thing to note, sometimes you will need to do this:

    onBlur={(e) => {
      input.onBlur(e);
      setTimeout(() => this.fetchAddressesValid());
    }}

If you don't call your function with timeut than you will have props from last tick instead of fresh new values from last change.

**Comment by KTruong888** [comment]
Thanks for solving this month long struggle.
