### ISSUE TITLE
6.2 Radio Input unable to set to boolean false if initial value is null

### ISSUE THREAD

**Issue by PJ2000** [erikras/redux-form#2116]
I'm unable to set a Field of type radio to false if the initial value is null. It looks like redux form sets the value to '' if the initial value is null. If the value is set to false, the form does not set the value. However, if the value is set to true, then false, then the false value is set. This is only the case if I use boolean true/false values. If I set it to 'false' or 'true', things seem to work fine. Annoyances come up when I want to validate values and much prefer to check the properties as booleans vs strings. Is this a bug or is this as working as expected? Are there any work arounds?

**Comment by niksajanjic** [comment]
You shouldn't pass null as initial value, radio button expects boolean. Make sure to set it to false if it's not boolean, that should cover it for you.

```
connect(state => ({
  initailValues: {
    radioButton: typeof state.radio === 'boolean' ? state.radio : false,
  },
}))
```

**Comment by PJ2000** [comment]
I actually have a state of null. I want the user to actually select an option so before the user selects, the value is null or undefined. Is there a way to get it to work with initial undefined, the true/false after?

**Comment by niksajanjic** [comment]
I'm not sure to be honest, but in case your state is null try not to set initialValue at all, and in case it is boolean, set it to that state.

**Comment by ardentum** [comment]
@PJ2000 Did you find any workaround? I have similar issue with three-state checkbox: `<Field>` doesn't rerender itself when value changes from `false` to `null` or back.

**Comment by gregeinfrank** [comment]
I'm seeing a similar issue - but the field is actually saved on the store as `false` but there is no re-render of the form

**Comment by nlehrer** [comment]
@gregeinfrank Did you figure out any solution to this? I'm totally stumped.

**Comment by gregeinfrank** [comment]
@nlehrer see https://github.com/erikras/redux-form/issues/2456 for the details of where the bug is...

I think I fixed by defaulting my "no-value" state to `undefined` rather than `null`, but I can't remember now after a year :)

**Comment by nlehrer** [comment]
It turns out this is fixed but I was using an old version of `redux-form`. Rookie mistake!
