### ISSUE TITLE
CHANGE event on custom field component removes focus from input

### ISSUE THREAD

**Issue by anonmily** [erikras/redux-form#2120]
Hi everyone! :)

I just recently started the migration from v4 to v6 of redux-form (v6.2.0), and I'm really loving the improvements so far. I noticed a quirk, though, with using a custom component for the Field. 
Once I type the first character into a previously empty text field, the component loses focus and I have to click on it again to continue typing. The problem goes away once I use the default Field component `<Field component="input" type="text" name="input" />` rather than a custom component, e.g.:

```
<Field name="username" component={username =>
	<div>
		<input type="text" {...username.input} />
		<ErrorMessage message={ username.meta.touched && username.meta.error } background={false} />
	</div>
}/>
```

I'm not sure if I'm doing something wrong, or if it's a bug?

To reproduce:
1. Have a Field with a custom input component.
2. Start typing into input field. After the CHANGE event is fired, now I'm no longer focused on the input field and will have to click on the field again in order to continue typing, after which there are no issues.

My entire form component:

```
import React, { Component } from 'react'
import is from 'simply-is'
import _ from 'lodash'
import Promise from 'bluebird'

import { Field, reduxForm } from 'redux-form'
import { FormGroup } from '../ui/forms'
import { ErrorMessage } from '../ui/messages'
import { LoadingDots } from '../ui/loading'

class LoginForm extends Component {
  render() {
	const { error, handleSubmit, pristine, reset, submitting, syncErrors } = this.props
	return (
	  <form onSubmit={handleSubmit} className="loginform l-top-labels">
		<FormGroup className="username">
			<label htmlFor="username">Username</label>
			<Field name="username" component={username =>
				<div>
					<input type="text" {...username.input} />
					<ErrorMessage message={ username.meta.touched && username.meta.error } background={false} />
				</div>
			}/>
		</FormGroup>
		<FormGroup className="password">
			<label htmlFor="password">Password</label>
			<Field name="password" component={password =>
				<div>
					<input type="password" {...password.input} />
					<ErrorMessage message={ password.meta.touched && password.meta.error } background={false} />
				</div>
			}/>
		</FormGroup>
		<FormGroup className="remember">
			<Field name="remember" component="input" type="checkbox"/>
			<label htmlFor="remember">Remember me for 30 days</label>
		</FormGroup>
		<button type="submit" className="btn blue submit">
			{ submitting ? (<span>Logging in <LoadingDots /></span>) : "Submit" }
		</button>
		<ErrorMessage message={error} background={false} />
	  </form>
	)
  }
}

export default reduxForm({
	form: 'login',
	initialValues: {
		'remember': true
	},
	validate: (values) => {
		let errors = {}
		if(!values.username){
			errors.username = 'Username required'
		}
		if(!values.password){
			errors.password = 'Password required'
		}
		return errors
	}
})(LoginForm)
```

I originally suspected it had to do with the synchronous validation (e.g. the UPDATE_SYNC_ERRORS event), but the issue happens even when I remove validation entirely and disappears when using the default Field component.

**Comment by anonmily** [comment]
Gah! Sorry, just found out what was going wrong. This issue is the same as #1323, and the problem had to do with inline fat arrows for the custom component. Instead of:

```
<Field name="username" component={username =>
	<div>
		<input type="text" {...username.input} />
		<ErrorMessage message={ username.meta.touched && username.meta.error } background={false} />
	</div>
}/>
```

The fat-arrow input component declaration should be declared separately, not inline:
```
const FormInput = (field) =>{
	return (
		<div>
			<input type="text" {...field.input} />
			<ErrorMessage message={ field.meta.touched && field.meta.error } background={false} />
		</div>
	)
}
```
and then, for the input itself:
```
<Field name="username" component={FormInput}/>
```

I have no idea why, but I was looking at the 6.0.0 version docs, hence the confusion... 😅 Thanks for the great work on the library, and sorry again for opening this duplicate issue.

**Comment by alfonsoperez** [comment]
For anyone coming from Google, this is also the problem when a on a checkbox click redux-form dispatches the `FOCUS` actions but not the `CHANGE` one.
