### ISSUE TITLE
FormSection - FieldArray relative path incorrect?

### ISSUE THREAD

**Issue by brycejacobs** [erikras/redux-form#2121]
```
<form>
    <FieldSection name="contacts">
        <Contacts />
    </FieldSection>
</form>

class Contacts extends Component{

  renderContacts = ({fields}) => {
    <ul>
      <li><button onClick={() => fields.push({})}>Add Detail</button>
      { fields.map(field => <Field name={`${field}.detail`} component='input' type='text' /> }
    </ul>
  }

  render(){
    return <div>
      <FieldArray id="contactDetailsInput" name="contactDetails" component  ={this.renderContacts} />
  </div>
  }
}
```

The change event for the detail will emit a meta path that looks like ```contacts.contacts.contactDetails[0].detail```

Is this intended behavior?

**Comment by bmv437** [comment]
Yea, that's definitely an issue. I just verified it.
jsfiddle here:
https://jsfiddle.net/1j67zoge/2/

and here is a screenshot of the state after adding two fields, and modifying both
![image](https://cloud.githubusercontent.com/assets/1403707/20503329/1473c276-b010-11e6-83f6-64356638dbc8.png)

you can see the double `contacts.contacts` nesting in the redux inspector, and it looks like `fields.push({})` is working correctly though.

**Comment by popasquat89** [comment]
I'm pretty sure the issue is the appending of the path somewhere. I wish I had time to roll a patch, but I'm swamped right now.

**Comment by at0g** [comment]
Experiencing this also.
Also noticed differing behaviour when there is a field name in the root of the form as the name of a nested field array.

eg.
```
<form>
    <FieldArray name="foo" ... />
   <FormSection name="bar">
      <FieldArray name="foo" ... />
      <FIeldArray name="baz" ... />
  </FormSection>
</form>

// values.foo // contains the expected value
// values.bar.foo // contains the expected value, because foo is registered in the root of the form?
// values.bar.baz // not the right value
// values.bar.bar.baz // contains the value of baz
```

**Comment by erikras** [comment]
Fix released as [`v6.5.0`](https://github.com/erikras/redux-form/releases/tag/v6.5.0).

**Comment by incoqnito** [comment]
In version 6.8.0 its also broken, i have a `<FormSection name="core"` and inside my form action a `<FieldArray name="products"`, in the store appears core.core.products. I have quicked fixed it by `${field.name.replace('core.', '')` and it works like expected.

**Comment by bmv437** [comment]
Hey @incoqnito, I created a fork of my original jsfiddle but using redux-form 6.8.0, and it seems to work fine.
https://jsfiddle.net/788uu5au/
Screenshot of it working:
![image](https://user-images.githubusercontent.com/1403707/27596208-dc629740-5b2c-11e7-9b75-abedfdec7e39.png)


can you put together a codesandbox with an example of the path being broken? You can fork any of the codesandbox examples in the README.md

Thanks!
