### ISSUE TITLE
Validation function gets passed undefined `values` during initial render

### ISSUE THREAD

**Issue by kgoggin** [erikras/redux-form#2122]
I'm fairly certain this is similar to what people are describing as an issue with #621, but since that issue was closed some time ago I figured I'd make a fresh one.

I'm using v6.2.0 and experiencing an issue with my sync validation function getting passed `undefined` when it gets called by `reduxForm.js`'s `componentWillMount`. Pretty sure this is because the `INITIALIZE` action hasn't cleared the store yet to set the `initialValues` as the form's actual `values`. Digging into the internals of `validateIfNeeded`, I can see that `this.props.values` is `undefined`, and there's nothing in the logic there to prevent that from getting handed off to to the validation function.

I realize that I could theoretically write a custom `shouldValidateResult` to just ignore validation on the initial render, but that doesn't sit great with me because theoretically the `initialValues` could be invalid. I guess I could also pull `initialValues` from the props argument that gets provided to the validation function and use those if needed, but again, that seems a little janky.

Would it work to default to `this.props.initialValues` if we're not done initializing yet? Theoretically we could track some state internal to the reduxForm component related to whether or not the `INITIALIZE` action had finished firing yet (`hasInitialized`?), and then if that was true, and `this.props.values === undefined` we could use `this.props.initialValues`.

I'm guessing based on some of the other comments this issue affects more than just validation, so theoretically we'd likely want to do this anywhere we're accessing `this.props.values` during the initial render? I'm not familiar enough with the source to understand how big of a deal that'd be, but if that's a direction the maintainers are comfortable pursuing I'd be willing to give it a shot.

**Comment by kgoggin** [comment]
One other solution that would make using `initialValues` inside the validation function less janky is if I could do it if I knew it was the initial render, and only then. So, we'd need to pass that value to the validation function somehow, I suppose as a third argument? That wouldn't help any issues unrelated to validation and would put the responsibility back on the user to figure this out, but I assume it'd be a much easier change. Just another idea to consider...

**Comment by eliseumds** [comment]
@kgoggin, PR https://github.com/erikras/redux-form/pull/2091 is merged and we should have a new release soon.

**Comment by stunaz** [comment]
oh got the same problem yesterday when I updated to 6.2.0, had to implement a function for `shouldValidate`, to prevent validation on `initialRender`

**Comment by kgoggin** [comment]
@eliseumds awesome, thanks for the update! Not sure how I missed that issue when I searched for mine :).
