### ISSUE TITLE
Typing in Material-UI TextField does not populate field

### ISSUE THREAD

**Issue by tatemz** [erikras/redux-form#2123]
I am using redux-form@6.2.0 and material-ui@0.16.2 and redux@3.6.0.

When I use the [material-ui example](http://redux-form.com/6.2.0/examples/material-ui/), I am unable to type into the text field - it remains blank while typing.

Any thoughts?

**Comment by tatemz** [comment]
Silly me... it was because I forgot to add the reducer:

```
import reducers from './reducers'
import { reducer as formReducer } from 'redux-form'

const store = createStore(
  combineReducers({
    ...reducers,
    form: formReducer,
  }),
)
```

**Comment by blainegarrett** [comment]
This should be good to close.

**Comment by mschipperheyn** [comment]
You should be able to close your own question I think

**Comment by blainegarrett** [comment]
@tatemz - if this is a non-issue now, please close if you have permission.

**Comment by erikras** [comment]
@blainegarrett Thanks for your issue policing. I often do not have time.
