### ISSUE TITLE
Really need to set value in hidden field programatically

### ISSUE THREAD

**Issue by bstenm** [erikras/redux-form#2127]
Hi there, i can not find a way to set a value in a field, it is no bound to any onChange event, i just need to set a value. Ideally something like that
`<Field
    setValue={some-value}
    type="hidden"
    .../>`
Is there any way to achieve that? If not would anybody be able to point me to where I could add that functionality in the redux-form codebase if I fork it?
Thanks a lot!

**Comment by x2764tech** [comment]
Can you pass the value in for the hidden field in the initialValues? (It's a bit confusing at first, but look at the sample at http://redux-form.com/6.2.0/examples/initializeFromState/ to see how to pass values into the form)

**Comment by x2764tech** [comment]
you can also use the `defaultValue` on the Field too (see http://redux-form.com/6.0.0-alpha.4/docs/api/Field.md/#-defaultvalue-any-optional- )

**Comment by bstenm** [comment]
Unfortunately initialValues won't do as I also need to set the value after some user actions. I tried `defaultValue` but for some reason I get that error message:
`warning.js:36 Warning: ConnectedField containsrr an input of type text with both value and defaultValue props. `
and when I submit the form it doesn;t appear in the data submitted?
Cheers!!

**Comment by x2764tech** [comment]
yeah, sorry, `defaultValue` was removed (was looking at old docs for some reason).

Could use the `normalize` function for the field? or, failing that, write a `reducer.plugin`?

**Comment by bstenm** [comment]
As far as I understand `normalize` is only called when you enter sth in the specific field, no idea i there is a way with reducer.plugin yet I might give it a try... But I feel there should be a simple way to achieve what I'm trying? Without redux-form that is extremely  straight forward, that's the downside of libraries I guess, it helps a lot in many respects but then you lose some flexibility.
Anyway, thanks a lot for your input (no pun intended :D )!!

**Comment by x2764tech** [comment]
What are you actually trying to do? What's the complete process?

**Comment by bstenm** [comment]
Ok, so the user can upload some photos, when he does that the photos appear on the page straight away, each with a two inputs fields (one for a caption, one for a description). he when he submits the form I get the caption and description for each photos and save them to a database. Now I also want them to be able to drag-drop the items (one item being a photo/caption/description set) to change the order in which they will be displayed. So I need to keep track of the order of each item and save that too when they submit the form. So I'm trying to find a way to get all that info (captions/descriptions/order) submitted as form data at the same time. The easiest way would be to keep track of the order of each item in a hidden field along side the caption and description fields. So each time they drag drop I would change the value of the hidden field. Does that make sense?

**Comment by x2764tech** [comment]
I'd tend to keep things like that in the application state - it's what's it's there for.

**Comment by bstenm** [comment]
Yes that's a good idea David, and I'm probably gonna go for that.

**Comment by x2764tech** [comment]
@bstenm - if you have any success with that, then close the ticket to let the project admins know you don't need any more help

**Comment by grossmail1** [comment]
why don't you want to use an onChange action creator? That would store the data in the hidden field, or even make a hidden field unnecessary?

**Comment by aceofspades** [comment]
Seems to me that normalization needs to apply to the entire form, not just each field. I'd like to see the name of the field passed in to the normalize function (to avoid having to duplicate functions), and then be able to modify any of the form value within the function. I'm not seeing any other hooks to be able to do this, thoughts?

In my case, I use virtual fields that are convenient for the front-end UI, but I want to have other fields defined for the API that are not necessarily 1-to-1.

**Comment by sckoh** [comment]
you can use action creators to change the value of your hidden field

http://redux-form.com/6.4.3/docs/api/ActionCreators.md/

**Comment by andreme** [comment]
The component you have wrapped with reduxForm receives a change function in the properties: this.props.change('fieldname', new_value);

**Comment by bstenm** [comment]
Hey! That's what I was looking for, I was not aware of this one. Cheers!!

**Comment by kellyrmilligan** [comment]
I think actionCreators are going to work better for me personally, as I have a rather specialized form input, and hooking into its `onChange` will let me dispatch accordingly to update the form to handle it a bit cleaner in the submit handler.

**Comment by mCzolko** [comment]
This is basically a hidden field. And also I think this would work in React v16 or never.
```
<Field
    name="name"
    val="John"
    component={({ input, val }) => input.onChange(val)}
/>
```

**Comment by ilovett** [comment]
```
  constructor(props) {
    super(props);
    this.inputEl = React.createRef();
  }

  onCustomThing(event) {

    const customEvent = new Event('change');
    this.inputEl.current.value = event.currentTarget.dataset.rating;
    this.onChange && this.onChange(customEvent);

  }

  render() {
       <input type="hidden" ref={ this.inputEl } { ...input } />
  } 
```
