### ISSUE TITLE
Active prop showing incorrect value

### ISSUE THREAD

**Issue by davegri** [erikras/redux-form#2128]
I'm using `redux-form` 4.2

For some reason my field is still showing true when it is not in focus, the docs say:
```
It will only work if you are passing onFocus to your input element.
```

What does that mean exactly?

Does this only work if I have multiple fields, ie does one need to gain focus for another to lose it?

**Comment by wlingke** [comment]
Also not sure how this is supposed to work..

**Comment by gustavohenke** [comment]
As it's been a while and you were using an old version of redux-form, please let us know about what you ended up doing.
