### ISSUE TITLE
input lose focus

### ISSUE THREAD

**Issue by wolfnether** [erikras/redux-form#2129]
when input value change from empty string to something else ConnectedField trigger redraw because input field in the store is created, the reverse case trigger the redraw

http://prntscr.com/d7yodz
http://prntscr.com/d7yohc

because of "nextPropsKeys.length !== thisPropsKeys.length"
https://github.com/erikras/redux-form/blob/master/src/ConnectedFields.js#L30

**Comment by martinhorsky** [comment]
Can i see the code? You maybe loose focus on input because you define component every `render()`.

There is a note in documentation:
> You must define the stateless function outside of your render() method, or else it will be recreated on every render and will force the Field to rerender because its component prop will be different. If you are defining your stateless function inside of render(), it will not only be slower, but your input will lose focus whenever the entire form component rerenders.
> 
> http://redux-form.com/6.2.0/docs/api/Field.md/

**Comment by wolfnether** [comment]
```javascript
const renderField = (t) => ({ name, input, label, type, meta: {touched, error, active } }) => {
  return (
    <div key={name}>
      <label>{t(label)} {touched && error && <span className="text-danger">{t(error.type, error.ctx)}</span>}</label>
      <div>
        <input  {...input} type={type} placeholder={t(label)}/>
      </div>
    </div>);
}

export class SignInPage extends React.Component {
  render() {
    const { t , error, pristine, reset, submitting,handleSubmit } = this.props;
    const loading = pristine || submitting;
    return (
      <form onSubmit={handleSubmit(formAction)}>
        <Field name="email" type="email" component={renderField(t)} label="email" value=''/>
        <Field name="password" type="password" component={renderField(t)} label="password" value=''/>
        <br/>
        <div>
          <button type="submit" className={"btn"+(loading?'':" btn-primary")} disabled={loading}>{t('submit')}</button>
          <button type="button" className={"btn"+(loading?'':" btn-primary")} disabled={loading} onClick={reset}>{t('clear')}</button>
        </div>
      </form>
    )
  }
}
```

**Comment by martinhorsky** [comment]
You do exactly what I though you do.

Rename your `renderField` to `createComponent` and you will see the issue there in `SignInPage`.

---

Here is the snippet how you need change your code to make it work properly. Focus on your `t` prop in this example.

```javascript

const InputWithLabel = ({ t, name, input, label, /* ... */ }) => { // <-- here you can get your `t` function
  return /* ... */;
}

export class SignInPage extends React.Component {
  render() {
    const { t , /* ... */ } = this.props;
    return (
      <form>
        {/* you can pass `t` function in prop */}
        <Field name="email" type="email" component={InputWithLabel} label="email" value="" t={t} />
        {/* ... */}
      </form>
    )
  }
}
```

**Comment by terencechow** [comment]
I think my problem is associated with this. Currently I have a decorator called `withError` that wraps a component and adds the form errors below. Doing it this way allows me to wrap not just components I create, but also components in other libraries.

However I'm getting a loss of focus on the initial keydown. @martinhorsky, your solution turns the decorator function into a component. Is there anyway we can keep the decorator function? 

For reference here is my code, (to make sure my problem is the same):

```
function withErrors (WrappedComponent) {
  return class WithErrors extends Component {
    render () {
      const { meta: { touched, error, warning } } = this.props
      return (
        <div>
          <WrappedComponent {...this.props} />
          {
            touched && ((error && <span>{error}</span>) || (warning && <span>{warning}</span>))
          }
        </div>
      )
    }
  }
}

const Input = (props) => ( <input {...props.input} type={props.type} />)

const ClientForm = (props) => (
    <form onSubmit={props.handleSubmit}>

      <div className={styles.formGroup}>
        <label htmlFor='client'>Client Name</label>
        <Field name='client' component={WithErrors(Input)} type='text' />
      </div>

      <button
        className={styles.submit}
        type='submit'
        disabled={props.submitting || !props.valid}>Submit</button>
    </form>
)

export default reduxForm({
  form: 'client',
  validate
})(ClientForm)
```

**Comment by WaNgeL-SaTaR** [comment]
Same problem with hight order component when render method exist in it. `"redux-form": "^6.5.0"`. 

Example: 

```js
import React, { Component } from 'react';
import { FormGroup, ControlLabel, HelpBlock } from 'react-bootstrap';

export default function FieldGroup(WrappedComponent) {
  return class extends Component {
    getValidationState() {
      const {
        meta: {
          valid,
          touched,
        },
      } = this.props;
      if (touched) {
        return valid
          ? null
          : `error`;
      }
      return null;
    }

    render() {
      const {
        label,
        meta : {
          error,
          warning,
        },
      } = this.props;
      return (
        <FormGroup
          validationState={this.getValidationState()}
        >
          {label &&
            <ControlLabel>
              {label}
            </ControlLabel>
          }
          <WrappedComponent
            {...this.props}
          />
          <HelpBlock className='helpBlock'>
            { error }
            { warning }
          </HelpBlock>
        </FormGroup>
      );
    }
  };
}
```

**Comment by michaelnagy** [comment]
I'm getting this same issue when using a decorator. The input loses focus everytime some state change in the form. Here is my code:
https://gist.github.com/michaelnagy/a400e9b243553da8e0ce094a0855b2a1

**Comment by gustavohenke** [comment]
I didn't read thru the whole thread, but I see a common patterns among everyone those who I looked at the code.

You're creating a new component _everytime_ a prop changes, thus it's a new DOM node.
You should never do that (I know it's tempting...) - instead simply move what is static to outside of your `render` function/functional component, and pass the rest as props to the `Field` component. 
It will work - I promise!
