### ISSUE TITLE
FormSection should not add prefixName to its children component.

### ISSUE THREAD

**Issue by mtiger2k** [erikras/redux-form#2148]
Greeting,

I was switching to 6.2.0, but I encountered an issue.
When I use FormSection with Fields with custom component, like the following:
`<FormSection name="hkaddress">
  <Fields component={Address} path="hkaddress" names={['province', 'city', 'county', 'address', 'postCode']} />
</FormSection>`

But in Address component, the props object contains {hkaddress: {province, city, county}}, so I have to pass a path to find the Field object.

> getPath() {
        let path = this.props.path;
        let arr = path.split('.');
        let parent = this.props;
        _.each(arr, (field)=>parent=parent[field]);
        console.log(parent);
        this.province = parent.province;
        this.city = parent.city;
        this.county = parent.county;
        this.address = parent.address;
        this.postCode = parent.postCode;
    }

> render() {
        this.getPath();
        //const { province, city, county, address, postCode } = this.props[this.props.path]
        let addressTitle = this.props.addressTitle;;
      return (
        <div className="form-group">
            <label className="control-label col-sm-1">{addressTitle}<span className="required">*</span></label>
            <div className="col-sm-1"><select className="form-control" {...this.province.input} onChange={this.handleProvinceChange.bind(this)} ><option value="">Province</option>{this.provinceOption()}</select></div>
            <div className="col-sm-1"><select className="form-control" {...this.city.input} onChange={this.handleCityChange.bind(this)} ><option value="">City</option>{this.cityOption(this.province)}</select></div>
            <div className="col-sm-1"><select className="form-control" {...this.county.input} ><option value="">County</option>{this.countyOption(this.province, this.city)}</select></div>
            <div className="col-sm-5"><input className="form-control" {...this.address.input} placeholder="地址" type="text" onBlur={this.validateAddress.bind(this)} /><p className="text-danger">{this.state.addressValidate}</p></div>
            <label className="control-label col-sm-1">Postcode<span className="required">*</span></label>
            <div className="col-sm-2"><input className="form-control" {...this.postCode.input} placeholder="Post code" type="text" maxLength="6" onBlur={this.validatePostCode.bind(this)} /><p className="text-danger">{this.state.postCodeValidate}</p></div>
        </div>
      )
    }

I think the Fields/Field should not care about the parent path, it's FormSection's responsibity to attach the values object to its parent object.

Please suggest the right way to use FormSection and Fields.

Thanks and Best Regards.

**Comment by bmv437** [comment]
You're right, it looks like there was never a test written to test make sure the `FormSection` created values at the right depth for the `Fields` component, and that they were accessible inside the `Fields` component with the right scope.

I wrote a fix and associated test over here:
https://github.com/bmv437/redux-form/tree/FormSection-Fields-names-fix

submitting a PR as well.

**Comment by erikras** [comment]
Fix published in [`v6.2.1`](https://github.com/erikras/redux-form/releases/tag/v6.2.1).
