### ISSUE TITLE
Question: showing a validation summary

### ISSUE THREAD

**Issue by sgentile** [erikras/redux-form#2158]
I would like to show a summary of all the validation errors in my form - I have a complex master detail form (similar to the hobbies example.).  Any pointers or examples of a validation summary ?

thanks

**Comment by bmv437** [comment]
I would suggest using the `getFormSyncErrors` selector, which returns the errors for the entire form
http://redux-form.com/6.2.0/docs/api/Selectors.md/

**Comment by sgentile** [comment]
Thanks, so I show the form is not valid (invalid is false - the individual
item is showing the error) and yet this selector is not showing any errors
- so for whatever reason it isn't picking it up

**Comment by bmv437** [comment]
I whipped up a jsFiddle with a working example. It uses the current version of redux-form (v6.2.0).
https://jsfiddle.net/bmv437/j7bdhL6s/

I ended up creating a `ErrorSummary` component, that is separately connected to the state with the `getFormSyncErrors` selector. That way we don't pass the sync errors into the decorated form component (causing unnecessary re-renders).

let me know if you have any questions 😄

**Comment by sgentile** [comment]
Thank you - I'll take a look at it

**Comment by oyeanuj** [comment]
@sgentile I have taken a slightly different approach to 'summary' of errors. I actually use the sync validation to construct error message based on the combination of fields showing the error and store that in the `errors._error` variable, and then the have the form display that.
