### ISSUE TITLE
[6.2.0] Handler functions cause re-rendering

### ISSUE THREAD

**Issue by oreqizer** [erikras/redux-form#2159]
Hi,

been experimenting with [this addon](https://github.com/garbles/why-did-you-update). I noticed that functions created as handlers cause re-rendering:

![screen shot 2016-11-23 at 16 32 10](https://cloud.githubusercontent.com/assets/11172408/20568007/3d144160-b19b-11e6-9919-398a9dfa8e49.png)

This is my minimal setup:

```javascript
const TextInput = props => (
  <TextField
    name={props.name}
    value={props.input.value}
    onChange={props.input.onChange}
    onFocus={props.input.onFocus}
    onBlur={props.input.onBlur}
  />
);

const Form = props => (
  <form onSubmit={props.handleSubmit}>
    <Field
      name="test"
      component={TextInput}
    />
  </form>
);

export default reduxForm({
  form: 'test',
})(Form);
```

You can see in the screenshot that `onChange`, `onFocus` and `onBlur`'s identities change.

Am I wrong, or is it possible to be adjusted?

**Comment by oreqizer** [comment]
I was digging through the code and found [this](https://github.com/erikras/redux-form/blob/master/src/createFieldProps.js#L48). I suspect it's because the arrow function creates a new identity every time the props change.

I will try to submit a PR, although it may take some time 😄  never contributed before and it's one hell of a codebase.

**Comment by oreqizer** [comment]
Created a PR: https://github.com/erikras/redux-form/pull/2161

*TODO:*
- [ ] separate handler logic
- [ ] write tests

Let me know if you require any adjustments regarding codestyle and such. 😄

**Comment by oreqizer** [comment]
Help needed: the PR has broken a whole bunch of tests. I can fix them, however, I'd prefer if a core maintainer reviewed the changes so I don't do redundant work

**Comment by oreqizer** [comment]
PR progress:
* fixed tests
* fixed coverage

https://github.com/erikras/redux-form/pull/2161

**Comment by gustavohenke** [comment]
Yep, #2161 did it, closing! And thanks @oreqizer!
