### ISSUE TITLE
Multiselect uneven sizes with 6.2.0

### ISSUE THREAD

**Issue by Jaikant** [erikras/redux-form#2163]
I am reasonably new. I am using multiselect and I would like the display to look a little bit more even.
Here is what I am seeing -

<img width="831" alt="screen shot 2016-11-25 at 8 17 42 am" src="https://cloud.githubusercontent.com/assets/3472565/20616880/74504f2c-b30b-11e6-99f9-92afecbcfbda.png">

When I update the bundle.css in index.html from

http://redux-form.com/6.0.0-alpha.15/bundle.css
to
https://redux-form.com/6.2.0/bundle.css

it fixes the problem. 
Please help.

**Comment by gustavohenke** [comment]
So you where using the CSS file from the docs site?
Please don't do that. Build your own.
