### ISSUE TITLE
Is it possible to make HTTP requests in normalizers?

### ISSUE THREAD

**Issue by Gothbag** [erikras/redux-form#2164]
Greetings
Well, the subject of the issue, is it possible to make HTTP requests within normalizers? Can anyone provide a working example please if so?

Thank you very much

**Comment by gustavohenke** [comment]
Usually, no.
HTTP requests are async operations, and a normalizer is a sync operation - it must return the next value of the field.

The only way possible to do this is by using synchronous XMLHttpRequests.
Beware that this will render your app unresponsive until the request has finished.

How to make a sync request is off-topic here.
