### ISSUE TITLE
Unable to use {React.cloneElement(this.props.children, this.props)}

### ISSUE THREAD

**Issue by iitgrad** [erikras/redux-form#2167]
So I am using react-router to manage my routes. My children components need to have access to props, so I have to use {React.cloneElement(this.props.children, this.props)} to instantiate the child component.  However, if that child component is a redux-form, it throws the following warning.

warning.js:45Warning: Failed propType: Invalid prop `form` of type `object` supplied to `Form(UserDetail)`, expected `string`. Check the render method of `Connect(Form(UserDetail))`

And the redux state for the form is messed up because the name of the form (which should be the first key) comes back as "object Object".

Note if I just create the child using JSX this way, it works but now I don't have access to props.
{this.props.children}

Any ideas?

**Comment by gustavohenke** [comment]
> it works but now I don't have access to props.
> {this.props.children}

Does this means you don't have acces to `children` prop?

If so, you'll need to pass it like this: `<Component { ...this.props }>{ this.props.children }</Component>`

**Comment by gustavohenke** [comment]
ping @iitgrad
