### ISSUE TITLE
Compose multiple forms on submit

### ISSUE THREAD

**Issue by ingro** [erikras/redux-form#217]
Hello, I'm trying to manage a very complex form and I'd like to share thoughts on how to handle it in a better way (I'm using 3.0).

Let's say I have a component that contains all my forms:

```javascript
class FormContainer extends Component {

    render() {
        return(
            <div>
                <ContactForm />
                {this.getProposals()}
                <button onClick={this.handleSubmit.bind(this)}>Submit</button>
            </div>
        );
    }

    getProposals() {
        let proposals = [];

        for (let i = 0; i < this.state.proposalsNum; i++) {
            proposals.push(
                <ProposalFormContainer num={i} values={this.getProposalValaues(i)} />
            );
        }

        return proposals;
    }

    handleSubmit() {
        // how to handle this?
    }

    getProposalValaues(i) {
        // return the initial values for that proposal
    }
}

export default connect(state => { form: state.form })(FormContainer);
```

`ContactForm` is "static" and contains only the contact informations but the user can create from 0 to n "proposals". To better manage them I thought to create a proposal form for each one, like this:

```javascript
export class ProposalFormContainer extends Component {

    render() {
        const { num } = this.props;

        class ProposalForm extends Component {

            static propTypes = {
                fields: PropTypes.object.isRequired
            }

            render() {
                const { price, description } = this.props.fields;

                return (
                    <div>
                        <input type='text' {...price} />
                        <input type='text' {...description} />
                    </div>
                );
            }
        }

        ProposalForm = reduxForm({
            form: `proposal_${num}`,
            fields: ['price', 'description'],
            destroyOnUnmount: false,
            validate: validateProposal
        })(ProposalForm);

        return <ProposalForm initialValues={this.props.values} />;
    }
}

export default ProposalFormContainer;
```

Problem is, from the `handleSubmit` method of my container, I need to know:
- if there are validations errors on any of the forms;
- if one or more forms are not pristine;
- the values of the fields for all forms;

Since `FormContainer` is connected to the Redux's store I could get some data from the forms. I've written helper functions (mostly based on `redux-form`) to extract values and check if a form is pristine, the bigger problem remaining is validation.

Even if I can see errors on screen while I touch the fields, the data from Redux's store is not on sync, `asyncError` and `submitError` are undefined on the field, and also `_error` is undefined on the form.

How could I get around this problem? It would be possible in a future release to export more info on the form's reducer (like valid, pristine, etc.)?

If someone has any suggestion about how to tackle this problem it would be much appreciated, thank you!

**Comment by erikras** [comment]
Wow, that's a complicated use case!! Nothing obvious is coming to me. I've got some plans to enable an arbitrary depth of nested fields in the future, so eventually maybe all of that could live in the same form component, but that's not supported at the moment, I'm afraid... :disappointed:

**Comment by ingro** [comment]
Thanks for the reply, I understand it is not a common use case, so I guess I should take a custom path to resolve the problem. Another big issue I may hit (since we are talking of more than 100 inputs in the worst case) is performance. Do you think it will be possible in the future to avoid emitting some events (like focus or blur which I don't need to store) or to batch some actions with a debounce function?

**Comment by erikras** [comment]
You can already omit `onChange` by either passing the props from `fields.yourField` manually, or by overriding them with a noop, e.g. `<input type="text" {...yourField} onChange={()=>null}/>`.

**Comment by ingro** [comment]
Ah, you're right! Thanks for the suggestions!

**Comment by luisrudge** [comment]
@ingro I had to do something like that too and I figured the best way is to "denormalize" all the fields inside redux-form. Something like that: 

```js
//fields from contact form
const fields = ['name', 'phone', 'address'];

if(proposals) {
  proposals.forEach((s, index) => {
    //fields from a proposal
    fields.push(`proposals[${index}][name]`);
    fields.push(`proposals[${index}][amount]`);
    fields.push(`proposals[${index}][description]`);
  });
}

const CustomForm = reduxForm({
  form: 'customForm',
  fields
})(FormContainer);

return (
  <CustomForm {...props} />
);
```

After that, use [this lib](https://github.com/christianalfoni/form-data-to-object) to create a json object from that weird string keys and post that to your api

**Comment by ingro** [comment]
@luisrudge I tried a similar approach, it could work but it's a little cumbersome especially when you have to deal with validation.

**Comment by luisrudge** [comment]
Yeah.. It's not great, but it's not that bad either. Here's what I'm doing:

```js
import {createValidator, required} from 'utils/validation';

const createValidation = (pageTemplate) => {
  const validation = {
    path: required,
    templateId: required
  };
  if(pageTemplate) {
    pageTemplate.offers.forEach((s, index) => {
      const key = `offers[${index}]`;
      validation[`${key}[offerId]`] = required;
      validation[`${key}[linkId]`] = required;
    });
  }
  return createValidator(validation);
};

const AddPageForm = reduxForm({
  form: 'addWebsitePage',
  fields,
  validate: createValidation(pageTemplate)
})(AddPage);
```

**Comment by mattydoincode** [comment]
I am running into similar use cases in my application. We're a records management system so we often have the idea of "widgets" where you might add N of an item. A great example is you have a person, but that person can have more than one address. So I'm trying to make the form for each item it's own component. The ways I'm getting around the problems this causes are by just reaching deep into the underlying state and modifying it. The point of redux-form is that all state is in the global state, so here, for example, is how I "get me all the current values for the forms of the items on the page" when I'm trying to submit a form that has one of these widgets:

```javascript
const invalidKeys = ['_active', '_asyncValidating', '_error', '_submitting'];
export function getFormListFromState(state, formName, formKeys) {
    const formData = state.form[formName];
    const results = [];
    _.forEach(formKeys, (formKey) => {
        const specificForm = formData[formKey];
        const filteredForm = _.omit(specificForm, invalidKeys);
        const valueObj = {};
        _.forIn(filteredForm, (data, key) => {
            valueObj[key] = data.value;
        });
        results.push(valueObj);
    });
    return results;
}


```
I'm currently thinking about how to do validation, but it might involve going outside of redux-form's built in stuff, and then setting the errors manually in my form reducer.

**Comment by haradakunihiko** [comment]
I'm also in the same situation, and ignore validation stuff like @mattydoincode. My workaround is creating HOC which is same interface as redux-form to pass function which collects all data.
```js
let Page = ({ list, collectValues }) => {
  return (
    <div>
      {list.map( (item) => <ConnectedForm formKey={item.id} />)}
      <Button onClick={() => console.log(collectValues( list.map((item) => item.id) ))} />
    </div>
  );
}
Page = connectMultipleRecord({form: 'users', fields: [ 'name', 'address' ] }, Page);
```
https://gist.github.com/haradakunihiko/c7b668308f7a2791f1f3

In this way, I have to run validation by myself and check if the each record is dirty comparing the initialValue to filter to send the data to the server. However, I chose this way because the 'pristine' for the each form is also necessary , in order to show the user if that form is changed or not by changing the color of the row.

**Comment by jpierson** [comment]
I know this isn't directly related to redux-form but I did want to share something applicable that I found recently about WebComponents. Due to the isolation involved in the shadow DOM it appears that it is possible to have nested forms if forms are defined within component boundaries. Perhaps this will have future implications if the shadow DOM is adopted by ReactJS or other UI libraries. The details provided by Abhinav are available on [this SO post](http://stackoverflow.com/a/33737780/83658).

**Comment by greaber** [comment]
Another use case is just wanting the `pristine` state for a `beforeunload` listener.  Would it not be possible to make all the props passed to a form available from outside the form?  It seems to me that the great advantage of having your form state in Redux rather than component state is that it should make it easier when your form state is tied up in various ways with state elsewhere in your app.  But Redux Form has a limited API for such interop (exposed action creators and `getValues`), and the docs warn tell you to avoid using it.

**Comment by erikras** [comment]
With [`v4.2.0`](https://github.com/erikras/redux-form/releases/tag/v4.2.0), you may now call submit from your parent component, so you could potentially call submit on several forms, each with their own validation, and collect the values together.

**Comment by ingro** [comment]
@erikras that's a very good news! You're doing a great job with this library :)

**Comment by ademuk** [comment]
@erikras I'm using the `submit` method to submit several forms at once from the parent container. I want to know when all forms are valid, and their respective values. How would you go about this? How would you "collect the values together"?

**Comment by ademuk** [comment]
I went with this:

```js
const forms = this.props.forms;
{forms.map(function (form) {
  return (
    <Form
      key={form.id}
      ref={form.id}
      formKey={form.id}
      fields={fields}
      onSubmit={data => data}/>
  );
}, this)}
<button onClick={this.handleSubmitClick}>Submit</button>
```

```js
handleSubmitClick() {
  const forms = this.props.forms;
  const results = forms
    .reduce((prev, curr) => {
      const formId = curr.id;
      const results = this.refs[formId].submit();
      if (results) {
        prev[formId] = results;
      }
      return prev;
    }, {});

  if (Object.keys(results).length === forms.length) {
    this.props.onFormSubmit(results);
  }
}
```

**Comment by theone3nu** [comment]
this.refs[formId].submit() is returning undefined.. How do i get the data outside the redux form?

**Comment by 3Cbwaltz** [comment]
Not sure if there was ever a concrete solution to this. I had the same questions as @ademuk. But ended up going with something like what he outlines in his latter post. My question now is with validation. I have my two forms and a submit button in my parent component that has an onClick handler. The onClick then manually does the form submits individually. Is there a way to get each form to do it's own validation (probably submit validation) and then cancel the submitting process?This would replace having to do it manually in the button onClick handler. Here is what I have.
```javascript

let errorsArea = "";
    if(!_isEmpty(this.state.errors)){
       errorsArea = (
          <ul style={{color: "#ff1515", backgroundColor: "#fff0f0", border: "1px solid #ffd7d7"}}>
              { this.state.errors.map((error, i) => 
                 <li key={i}>{error}</li>) 
               }
         </ul>
     );
}

return (
<div>
     {errorsArea}
      <CommonForm
         ref='formCommon'
         id="formCommon"
         store={store}
         onSubmit={(values) => {return values;}}
      />
     <SpecificForm 
        ref='formSpecific'
        id='formSpecific'
        onSubmit={(values) => {return values;}}
     />
     <div>
        <button className="btn btn-primary" title="Submit" onClick={this.handleSubmit} >Submit</button>
     </div>
 </div>);
```

```javascript
handleSubmit(){
   var $this = this;
   let resultsCommon = this.refs.formCommon.submit();
   let resultsSpecific = this.refs.formSpecific.submit();
   let formData = Object.assign(resultsCommon, resultsSpecific);
   
    //we shouldn't do this
   let errors = this.validate(formData);
   if(_isEmpty(errors)){
       this._onSuccess(formData);
       this.setState({
            errors: ""
       });  
    }else{
       this.setState({
           errors: errors
       });
   }
}

validate(values){
  let errors = [];
  if(!values.name){
     errors.push("Name field is required")
  }
  return errors;
}
```

**Comment by TrevorHinesley** [comment]
Couldn't you use FormSection for this? http://redux-form.com/6.5.0/docs/api/FormSection.md/

**Comment by willshu2049** [comment]
Hi Florent. Thanks for you answer. This works only if I do not connect the component to redux store. For example, the code below works:

    //in the parent component, render the child component
    <CommentModal commentId={comment.id} functionality='editComment' form={`EditCommentForm_${comment.id}`} initialValues={comment}/>

    //export the child component. mapStateToProps is null.
    ...
    export default connect(
      // mapStateToProps
      null,
      // mapDispatchToProps
      { addComment, editComment, openModal, closeModal }
    )(reduxForm({
        validate,
        enableReinitialize: true,
      })(CommentModal)
    );

However, if I am trying to connect the component to redux store, like below:

    export default connect(
      // mapStateToProps
      ({modalState})=>({modalState}),
      // mapDispatchToProps
      { addComment, editComment, openModal, closeModal }
    )(reduxForm({
        validate,
        enableReinitialize: true,
      })(CommentModal)
    );

It stops working. The initial values for all forms will be the initial values of the last form. I tried using ownProps, without luck:

    function mapStateToProps({modalState}, ownProps ){
      console.log(ownProps)
      return {
        modalState,
        initialValues: ownProps.initialValues
      }
    }

Please, can anyone help?

**Comment by willshu2049** [comment]
It's a somewhat more complicated problem than issue #217. I want to have multiple forms in one component. In the parent component, I use form={...} and initialVlaues={...} to pass in initial values for each form. It works as the solutions in the above posts suggested.

However, this works only if I do not connect the child component to redux store. For example, the code below works:

    //in the parent component, render the child component
    <CommentModal commentId={comment.id} form={`EditCommentForm_${comment.id}`} initialValues={comment}/>

    //In the child component file, export the child component. mapStateToProps is null.
    ...
    export default connect(
      // mapStateToProps
      null,
      // mapDispatchToProps
      { addComment, editComment, openModal, closeModal }
    )(reduxForm({
        validate,
        enableReinitialize: true,
      })(CommentModal)
    );

However, if I am trying to connect the component to redux store, like below:

    export default connect(
      // mapStateToProps
      ({modalState})=>({modalState}),
      // mapDispatchToProps
      { addComment, editComment, openModal, closeModal }
    )(reduxForm({
        validate,
        enableReinitialize: true,
      })(CommentModal)
    );

It stops working. The initial values for all forms will be the initial values of the last form. I tried using ownProps, without luck:

    function mapStateToProps({modalState}, ownProps ){
      console.log(ownProps)
      return {
        modalState,
        initialValues: ownProps.initialValues
      }
    }

Can anyone suggest what the problem is, or a solution?
