### ISSUE TITLE
Share store state across two routes

### ISSUE THREAD

**Issue by danielo515** [erikras/redux-form#2172]
Hello,

I'm not sure if what I'm trying to do is correct, but definitively it is causing me problems.

I have two routes, one that creates a resource and another one that lists that resource. Let's say such resources are... users. So I have one route which is createUsers and another one which is named listUsers.

What I want (and currently doing) is to share the piece of the state they work on, so I can list the newly created users on a special list when I navigate from createUsers to listUsers. Normally users are fetched from an API, but I want to provide the instant feedback of seeing the users you have just created if they are.
So what I want is to divide the scope on 

```js
store: { users: {
             fetched: [/* fetched from the API */], 
             created: [/* created on the tool*/]
}
```

The only what that I found for doing such thing is to name the reducer of both routes with the same name, so I have the paths like this:

```js
 path: '/create',
      name: 'createUser',
      /*......*/
        importModules.then(([reducer, sagas, component]) => {
          injectReducer('users', reducer.default);
 path: '/list',
      name: 'listUsers',
      /*......*/
        importModules.then(([reducer, sagas, component]) => {
          injectReducer('users', reducer.default);
```

I tried to match the initial state of both reducers (so both returns as inital state `{ fetched:[] created: [] }`, but the **actual problem** is that once one reducer has been injected, it is not re-injected again. So when I first navigate (refreshing the page) to `/create`, then only the createUsers reducer is loaded, even if open the `/list` route. It happens the same the other way around.

How can I fix this? Another good practice instead of what I'm doing right now?

**Comment by gustavohenke** [comment]
Some ideas on how to do it:
https://medium.com/@Scarysize/syncing-redux-stores-across-browser-tabs-fff04f975423#.3oajn1mmy

Additional idea, not included in this post: shared web workers.
