### ISSUE TITLE
[Feature Request] Include 'submitting' and 'submitSucceeded' in the selectors

### ISSUE THREAD

**Issue by oyeanuj** [erikras/redux-form#2173]
To implement a solution discussed in #2169 (@erikras's 'Many little forms' solution) cleanly, I need to manage logic in the parent container based on whether each of the little forms (auto-saving each field) are submitting or have submitted, etc. 

Looking through the documentation in the [API](http://redux-form.com/6.2.0/docs/api/Selectors.md/), it seems that while one can check for errors or state of a field, there is no selector giving access to see if form is `submitting`, has `submitSucceeded` or `submitFailed`. 

In simple cases, one can access the state directly through custom selectors. But for sake of consistency as well as for more complex cases, it might be worthwhile having the following selectors:

1. `isSubmitting`: Corresponds to the `submitting` prop.
2. `hasSubmitSucceeded`: Corresponds to the `submitSucceeded` prop.
3. `hasSubmitFailed`: Corresponds to the `submitFailed` prop.

Not sure if there are more complex reasons for not having those selectors, but I would love to understand more!

**Comment by oyeanuj** [comment]
@erikras Also I see that one can't access field level errors within the form. I'm curious for the reasoning there - does it make too prescriptive that the error has to be accessed/displayed alongside the field?

Alternatively, is that something you could see be one of the selector?

**Comment by theKashey** [comment]
Normally - you should have selectors `from outside` for all props you have `inside`. But someone forgot to add them.

**Comment by erikras** [comment]
Fix published in [`v6.4.0`](https://github.com/erikras/redux-form/releases/tag/v6.4.0).
