### ISSUE TITLE
Textarea not setting touched to true when blurred

### ISSUE THREAD

**Issue by gridworkz** [erikras/redux-form#2174]
Has anyone tried a simple textarea field in 6.20? It doesn't set `touched` to true like the input field does. It gets set properly when `touchAll()` is called after a submit but the sync validation errors I've set in my form only fire when blurring input fields. I did the following as a little test on the textarea field:
...
`onBlur={() => {console.log(touched)}}`

No matter what I do, touched is always false. I'm not sure the syntax for setting `touched` manually (or `touch` for that matter). I find the docs to be a little terse and mis-leading at times. I know docs are tough given the constant movement of things.

... Anyhow, I've gone through the docs on touch / touched but I'm still a little confused on how to actually use them in my form. Any pointers / examples greatly appreciated.

Dave-o

**Comment by jhang** [comment]
I ran into a similar issue. I had to manually set the blur, change and value. It may or may not be related to your issue. 

```
const TextArea = props => {
    return <Field component={renderTextArea} {...props} />
}

const renderTextArea = props => {
    const {
        name,
        input,
        meta: {
            touched, error, warning
        }
    } = props;
    return (
        <textarea
            onBlur={input.onBlur}
            onChange={input.onChange}
            value={input.value}
            name={name}
            />
    );
}
```

**Comment by gridworkz** [comment]
You're a star, worked like a charm! Thanks so much.

**Comment by developer239** [comment]
I love you.

**Comment by iamdavidmartin** [comment]
i love jhang too.
