### ISSUE TITLE
Field used a select from Semantic UI react

### ISSUE THREAD

**Issue by Tilican** [erikras/redux-form#2177]
### Steps
hi,
I create a field with as component a Form.Select from semantic ui react component.

<Field
              label="Configuration"
              name="key"
              options={this.props.selectBox}
              component={GenerateField}
              required
            />

<Form.Select
            search
            label={field.label}
            options={field.options}
            onChange={(e, data) => field.input.onChange(data.value)}
             required={field.required}
          />

### Expected Result
Not an error ...

### Actual Result
Uncaught TypeError: Cannot set property 'initialValue' of null(…)
postUpdateWrapper @ ReactDOMSelect.js:167
postUpdateSelectWrapper @ ReactDOMComponent.js:293
notifyAll @ CallbackQueue.js:76
close @ ReactReconcileTransaction.js:80
closeAll @ Transaction.js:206
perform @ Transaction.js:153
perform @ Transaction.js:140
perform @ ReactUpdates.js:89
flushBatchedUpdates @ ReactUpdates.js:172
closeAll @ Transaction.js:206
perform @ Transaction.js:153
batchedUpdates @ ReactDefaultBatchingStrategy.js:62
batchedUpdates @ ReactUpdates.js:97
dispatchEvent @ ReactEventListener.js:147

### Version
6.2.0

thx

**Comment by flipvrijn** [comment]
I have the same problem. Whenever I use a select component with Redux Form, the same TypeError occurs. 

I found a related issue, but there the blame is put onto React though: https://github.com/erikras/redux-form/issues/321
