### ISSUE TITLE
[6.2.0] Unregister Field Action is still maintaining the value of the field in the store

### ISSUE THREAD

**Issue by adrianbon** [erikras/redux-form#2178]
Using Redux Form: 6.2.0

I'm creating a dynamic form where a user can add fields or remove fields on the fly. Currently when a value is entered into the **_'status'_** field and the field is then subsequently removed from the dynamic form the value of the '**_status_**' field is still being persisted in the redux form store found in the '**_values_**' object. The screenshot below can provide a better insight into this issue:

![image](https://cloud.githubusercontent.com/assets/5655287/20673200/7b14ab98-b584-11e6-9484-36b0b283ba01.png)

Therefore the issue is that the unregister field is not handling the removal of the value from the store and thus not ensuring that the UI and the store are synchronised.

**Comment by ordoghl** [comment]
I ran into the same issue. As a quick workaround I created a reducer plugin to remove values of unregistered fields:

```js
const store = createAppStore(combineReducers({
  ...reducers,
  form: formReducer.plugin({
    patientForm: (state, action) => {
      if (action.type === 'redux-form/UNREGISTER_FIELD') {
        return state.deleteIn(['values', action.payload.name])
      }
      return state
    }
  }),
}), [thunk])
```
Seems to work in my case.

**Comment by adrianbon** [comment]
@ordoghl thanks!...this solution worked. I'm trying to figure out now how to make it generic without specifying the 'Form ID' since it is not really a maintainable approach.

**Comment by ordoghl** [comment]
Another problem with it that the form will not remember the previously set dynamic field values when the user switches between different set of dynamic fields. I think it would be a better approach to deal with unregistered fields just before submit (e.g. filter values by registered fields).

**Comment by nhjk** [comment]
I have this issue as well and I think #2032 are #2168 duplicates of this. The plugin above works (thanks!) but as you guys pointed out, removing the value from the form store in `redux-form/UNREGISTER_FIELD` would be ideal.

**Comment by adrianbon** [comment]
@erikras what is your opinion on this issue?

**Comment by oakley808** [comment]
@ordoghl reducer plugin worked for me. (Thank you!)
 As of at least v6.2.1 you'll have to update the check for action type to
```action.type === '@@redux-form/UNREGISTER_FIELD'```

**Comment by gustavohenke** [comment]
Hi @oakley808, you can import the proper action type, eg

```js
import { actionTypes } from "redux-form";

// then in your plugin
if ( action.type === actionTypes.UNREGISTER_FIELD ) {}
```

Note however that they aren't documented yet, but #2459 plans on making it happen.

**Comment by plouc** [comment]
For those not using immutable, using @ordoghl approach:

``` javascript
import { combineReducers }                                        from 'redux'
import { reducer as formReducer, actionTypes as formActionTypes } from 'redux-form'

const removeUnregisteredFormFieldValue = (state, action) => {
    if (action.type !== formActionTypes.UNREGISTER_FIELD) return state

    const { values: { [action.payload.name]: unregistered, ...values } } = state
    return { ...state, values }
}

const reducers = combineReducers({
    ...reducers,
    form: formReducer.plugin({
        formA: removeUnregisteredFormFieldValue,
        formB: removeUnregisteredFormFieldValue,
    }),
})
```

**Comment by Razinsky** [comment]
Any update on this? I'm having the same exact issue where some parts of a form can be hidden and if any value has already been entered, it would stick in the store.

My workaround (which sucks) is to use the autofill action creator to set values to `null` when the fields are being removed. The key/pair stays in the store but the `null` value helps to filter out the values to submit.

I think it would make a lot of sense to remove values from the store when the related Field is unmounted.

Thanks. By the way redux-form is greeeeat 👍

**Comment by Ricka7x** [comment]
Same issue here!

**Comment by erikras** [comment]
My opinion on this issue is that there may be values in the store that are not displayed as fields on the page. This is especially useful for primary keys. Therefore, `UNREGISTER` should not remove the values. Just because a field is no longer on the page does not mean that it should be removed from the store. e.g. a [Wizard Form](http://redux-form.com/6.6.2/examples/wizard/).

**Comment by joefiorini** [comment]
I'm using redux-form for a Wizard Form and I think I would prefer this behavior. The reason I don't care about losing fields that aren't displayed is because after each step of the wizard I reinitialize the form with the latest values (using `enableReinitialize: true`). That way I can always look at `initialValues` to see _everything_ that has been captured so far, and `values` to see only what's being captured for the current step.

I'm going to give the above plugin a try and see if this behavior breaks anything in my app, but I think it probably won't.

Maybe this could be an option, like `keepFieldValuesOnRegister`?

**Comment by fezhengjin** [comment]
@erikras I find out that if i return `null` in the `parse` property of `Field`, the value of the field will be removed. So what about a new option, like:
```
willUnmount : (value, name) => changeValue [optional]
```
and then we can use it like this:
```
<Field name="myField"  component={MyCustomInput} willUnmount={() => null} />
```
or any other parsing that we want when the `Field` will be unmounted.

**Comment by klochner** [comment]
Is there a way to access the registered fields in the onSubmit handler?  I'd be content to do my own diff of submitted fields against registered fields.

**Comment by dfalt** [comment]
@klochner A little dated at this point but in case you (or anyone else) is looking here -- the `onSubmit` handler is passed three props: `values`, `dispatch`, and `props` (the `redux-form` wrapped component props).

One of the `props` passed is `registeredFields` which should give you what you're looking for.
