### ISSUE TITLE
6.2 Form selector for warnings

### ISSUE THREAD

**Issue by PJ2000** [erikras/redux-form#2179]
With the new feature for warnings, is there a way to know if a form has any warnings? Currently, for forms, we're able to use isValid, isInvalid, etc. Is there something a 'hasWarnings' ?

**Comment by PJ2000** [comment]
Sorry, I originally closed this because I thought it was the same as another item. I'm only trying to check if there are warnings or not. I don't actually need to get the actual warnings.

**Comment by gustavohenke** [comment]
The other issue you mention is very likely #2176 😉
