### ISSUE TITLE
[6.x.x] Form gets re-created when an event occurs after being destroyed 

### ISSUE THREAD

**Issue by tubalmartin** [erikras/redux-form#2191]
Let me thank you guys in advance for such an excellent lib!!

Today while playing with your lib I've encountered something interesting. To reproduce this issue with a form key `TEST` do:

* Fire a `redux-form/DESTROY` action for the `TEST` form:
  * `TEST` form gets destroyed nicely.
* And afterwards fire a `redux-form/BLUR` action for the `TEST` form:
  * `TEST` form is re-created after being destroyed.

I would expect post-destroy actions that should not create a form to be ignored. What do you think?

To overcome that behavior one can wrap the redux-form reducer:

```js
import { actionTypes, reducer } from 'redux-form'

export default function form (state, action) {
  switch (action.type) {
    // Action types that should not re-create a form
    case actionTypes.BLUR:
      return action.meta.form in state ? reducer(state, action) : state
    default:
      return reducer(state, action)
  }
}
```

But as I said above, I expected the redux-form reducer to handle these cases.

**Comment by sdruipeng** [comment]
#775
The timing is critical. Eric recommends to issue the destroy action in the handleSubmit handler

**Comment by tubalmartin** [comment]
@sdruipeng Yeah, I know timing is critical but shouldn't the redux-form reducer ignore certain actions performed on a non-existing form?

**Comment by sdruipeng** [comment]
I am not familiar with the way you write your reducer.
The following is the way I write the reducer in a typical React-Router-Redux website project.
I do not have to intervene with the toplevel reducer.

```
import {combineReducers}        from 'redux'
import {reducer as form}        from 'redux-form'
import {routerReducer}          from 'react-router-redux'
import auth                     from './auth'
import signup                   from './signup'
import mode                     from './mode'
import asyncUsername            from './asyncUsername'
import asyncPhone               from './asyncPhone'

export default combineReducers({
  routing: routerReducer,
  auth,
  signup,
  form,
  mode,
  asyncUsername,
  asyncPhone
})
```

**Comment by tubalmartin** [comment]
@sdruipeng I think you're not getting my point...I'm not talking about an issue that does not allow me to do something with the library. In fact, I've had no problems using the library and it's been six months so far in the project I'm working on (big app with many forms, we started with v5 and then migrated in one day to v6 painlessly). 

I'm questioning from a pure logic point of view whether it makes sense to re-create a form when certain actions such as a BLUR happen once it's been destroyed.

**Comment by sdruipeng** [comment]
the OnBlur handler depends on Promise to fetch the results, and a new Promise object needs to be created every time when an OnBlur event is triggered.

**Comment by zemzheng** [comment]
@tubalmartin Thank you for your solution.

And in my case i need to ignore the re-create in submit/async_validate, so i use:
```javascript
import { actionTypes, reducer } from 'redux-form'

export default function form (state, action) {
    switch( action.type ){
        case actionTypes.INITIALIZE:
        case actionTypes.REGISTER_FIELD:
            break;
        default:
            let { meta : { form } = {} } = action;
            // action to a form while the target form is destoryed
            if( form && !( form in state ) ) return state;
    }
    return reducer(state, action)
}
```

**Comment by danielrob** [comment]
Closing this as it appears resolved. If there was a lesson here that could be reflected in the lib to make it better, please notify!
