### ISSUE TITLE
Material UI Example Page doesn't work

### ISSUE THREAD

**Issue by mstmustisnt** [erikras/redux-form#2194]
http://redux-form.com/6.2.1/examples/material-ui/

Error in console

```
Uncaught Error: Cannot find module "react/lib/EventPluginHub"              injectTapEventPlugin.js:23
```

**Comment by erikras** [comment]
The 6.2.1 examples are broken at the moment. Working on it. Change the url to 6.2.0 for now.

**Comment by erikras** [comment]
Fixed.
