### ISSUE TITLE
Field Array Example Club Name TextField not working.

### ISSUE THREAD

**Issue by artLopez** [erikras/redux-form#2195]
I am getting an error in the Field Arrays example. I'm not able to enter text into the Club name textfield. 

`reactProdInvariant.js:31Uncaught Error: Minified React error #119; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=119 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.(…)`

**Comment by erikras** [comment]
Yes. All the examples are giving this at the moment. I'm working on it.

**Comment by erikras** [comment]
Fixed now. Something `yarn` did caused the problem. Thank you for your prompt reporting.
