### ISSUE TITLE
Reduce repo size

### ISSUE THREAD

**Issue by kvey** [erikras/redux-form#2196]
Repo git history contains the dist/bundles for all of the examples.
No real reason for the repo to be so large

**Comment by gustavohenke** [comment]
Editing the history now simply isn't feasible.
Would change all commit hashes, so we better stick to the 132 MB of the `.git` directory.

**Comment by erikras** [comment]
I had not considered this when I chose to host the website on `gh-pages`. An acceptable trade-off for the free, always up, fast docs hosting, though, I guess.
