### ISSUE TITLE
Custom bindActionCreators

### ISSUE THREAD

**Issue by johanneslumpe** [erikras/redux-form#22]
Do you think it is a good idea to introduce a custom binding function?

I feel that it's not a lot of work to just write

```javascript
function mapDispatchToProps(dispatch) {
  return {
    ...bindActionCreators(actionCreators, dispatch),
    dispatch
  }
}
```
in order to receive `dispatch`. If not anything else, it would be more obvious what's happening. Just some food for thought, I'm just curious about your opinion.

**Comment by erikras** [comment]
I think you might be right. Thanks for challenging me on this.

**Comment by johanneslumpe** [comment]
Always :)
