### ISSUE TITLE
Regression: v6.2.1 breaks seamless immutable

### ISSUE THREAD

**Issue by marbemac** [erikras/redux-form#2204]
Not sure if it's redux-form or seamless, but I opened this issue there: 

https://github.com/rtfeldman/seamless-immutable/issues/175

The issue stems from the setInWithPath performance patch, specifically changing to arr.slice() instead of [...arr]: 

https://github.com/erikras/redux-form/pull/2175/files#diff-ba79b920ecda0b13b45785ad078f6958L14

This will likely break any redux-form installations using seamless-immutable. For now, we've pegged our redux-form to 6.2.0, but any installs that are loose on the patch version will be affected when they npm/yarn up.

**Comment by huan086** [comment]
Ops my bad. Would [].concat(state) produce a mutable array? Was trying to avoid the call to _toConsumableArray, that's why I changed it to slice.

**Comment by huan086** [comment]
```js
var a = ['a'];
Object.freeze(a);
a[0] = 'no change';

var b = a.slice();
b[0] = 'b';

var c = [].concat(a);
c[0] = 'c';

console.log(a); // gives ['a']
console.log(b); // gives ['b']
console.log(c); // gives ['c']
```

looks like `slice` should give a mutable copy.

**Comment by marbemac** [comment]
You'd think so right? It does not seem to with seamless-immutable.

Check out the example I posted here:
https://github.com/rtfeldman/seamless-immutable/issues/175

**Comment by huan086** [comment]
@marbemac can you test whether my pull request fixes the problem?

**Comment by marbemac** [comment]
@huan086 just checked, and yes indeed!
