### ISSUE TITLE
multiple select

### ISSUE THREAD

**Issue by carlos-peru** [erikras/redux-form#2205]
Can somebody point me to the docs for multiple select if they are supported? Thanks!

**Comment by mikeengland** [comment]
You can just wrap a multiple select component such as React Select, and when calling the Redux Form onChange function (which is passed as a prop) ensure that you return an array of all the selected options. Redux Form just helps you easily store field values in the state, it is up to you to tell it what to store.

**Comment by optyler** [comment]
Hi @mikeengland , I'm trying to use both `react-redux` and `react-select` as @carlos-peru but I'm kind of new on react and I don't know if I did it properly. In order to update my store values and display the selected value on `react-select` component I shall do it like that, is it ok ? 
It seems strange to me to store the value in both `store` for `redux-form` and `state` for `react-select`...

```jsx
import React, { Component, PropTypes } from 'react';
import Select from 'react-select';

class SearchableSelect extends Component {
  state = { };

  setValue(input, value) {
    input.onChange(value);    // update redux-form Feild.
    this.setState({ value }); // update redux-select Async value to display.
  }

  render() {
    const { input, async, ...rest } = this.props;

    if (async) {
      return (
        <Select.Async
          simpleValue
          onChange={(val) => this.setValue(input, val)}
          value={this.state.value}
          {...rest}
        />
      );
    }

    return (
      <Select
        simpleValue
        onChange={(val) => this.setValue(input, val)}
        value={this.state.value}
        {...rest}
      />
    );
  }
}

export default SearchableSelect;
```

And it is used like that : 
```jsx
<Field
              async
              component={SearchableSelect}
              loadOptions={getReporters}
              name="Reporter"
              optionComponent={PersonSelectOption}
              value={reporterValue}
              required
            />
```
Or 
```jsx
<Field
              component={SearchableSelect}
              disabled={!reporterValue}
              name="Building"
              optionComponent={BuildingSelectOption}
              options={this.state.buildingOptions}
              required
            />
```

**Comment by mikeengland** [comment]
Hey @optyler, you shouldn't need to store the values in the component state and the Redux store. The Redux Form 'Field' component already provides you the current value in the Redux state in the input prop, see: http://redux-form.com/6.3.1/docs/api/Field.md/.

I am afraid I haven't got any of my Redux-Form code to hand (excuse any errors), but you should be able to do something like:

```javascript
import React, { Component, PropTypes } from 'react';
import Select from 'react-select';

export default class SearchableSelect extends Component {
  render() {
    const { onChange, value, async, ...rest } = this.props;

    if (async) {
      return (
        <Select.Async
          simpleValue
          onChange={val => this.onChange(input, val)}
          value={value}
          {...rest}
        />
      );
    }

    return (
      <Select
        simpleValue
        onChange={val => onChange(input, val)}
        value={value}
        {...rest}
      />
    );
  }
}
```

and

```javascript
<Field component={SearchableSelect}
       name="Building"
       optionComponent={BuildingSelectOption}
       options={this.state.buildingOptions}
       required
       {...input}
/>

// ...
const selector = formValueSelector('TicketNewForm');
export default connect(
  state => {
    const buildingValue = selector(state, 'Building');
    const reporterValue = selector(state, 'Reporter');
    return {
      buildingValue,
      reporterValue,
    };
  }
)(reduxForm({ form: 'TicketNewForm' })(TicketNewForm));
```

Let me know if that helps, if not I can explain further. 

FYI, it would probably be worth you simplifying the 'if async then' part of your component as there is duplicate code there, for example something like:

(again sorry if there are any errors, I haven't tried to run it. There may be better ways to do it.):
```javascript
import React, { Component, PropTypes } from 'react';
import Select from 'react-select';

const ReactSelectContainer = props => {
  if (props.async)
    return <Select.Async {...props}/>;
  else
    return <Select {...props}/>;    
}

export default class SearchableSelect extends Component {
  render() {
    const { onChange, value, async, ...rest } = this.props;

    return <ReactSelectContainer async
                                                       simpleValue
                                                       onChange={val => this.onChange(input, val)}
                                                       value={value}
                                                       {...rest}/>
  }
}
```

**Comment by optyler** [comment]
Thank's, it's much cleaner now :-D

As I need to interact between `SearchableSelect`s I think I could not apply your last recommandations. I have a `form` with multiple `Field`s components and some of them are _connected_ together...

If I simplify the code, the most common use case is as follow : 
``` jsx
refreshYearsOptions(){
  this.setState({ years: [] }); // options to give to react-select
  this.props.change('Years', null); // set to null if Authors go back to '' value

  xhr.get(`abc.com/author/${this.props.author_id}/years`)
       .then(({body}) => this.setState({ options: body }); // options to give to react-select)
}
// quite the same for `refreshBooksOptions()`

render() {
 return(
  <Form>
    <Field name='Authors' 
        async
        callback={refreshYearsOptions}
        component='SearchableSelect'
        loadOptions={xyz} /> // onChange, refresh `options` in `Year` through callback
    <Field name='Years'
        callback={refreshBooksOptions}
        component='SearchableSelect'
        options={this.state.years} /> // onChange, refresh `options` in `Books` through callback
    <Field name='Books'
        component='SearchableSelect' 
        options={this.state.books} />
  </Form>
)}
```
And in the `SearchableSelect` component the property `onChange()` is as follow : 
```jsx
          onChange={(val) => {
            onChange(val);
            callback(val);
          }}
```

It's already working but if you see more improvements, don't hesitate ,)

**Comment by optyler** [comment]
I [saw someone](https://github.com/erikras/redux-form/issues/1415) trying to do it with plugins, is it better?

**Comment by mikeengland** [comment]
If you want to modify the value of one field when you change another e.g. Setting it to have a null value, you should definitely use the reducer plugins that redux form provides. Then, you can just dispatch an action when you change a field  which will itself change the other redux form values. There is documentation on how this works. It will be much clearer than using different callbacks to manually control this. 

From memory there is also another function that can be called to change any fields value by name, but this will not reset any meta data like whether the field has been touched or not.

**Comment by gustavohenke** [comment]
As this is more of a discussion than an issue with redux-form, I'll close it.
