### ISSUE TITLE
FieldArray touched not set properly

### ISSUE THREAD

**Issue by wlingke** [erikras/redux-form#2207]
In the example: http://redux-form.com/6.2.1/examples/fieldArrays/

If you click submit - we see that the error showing "At least one member must be entered" comes up. This is correct and expected.

However, if you do the following:
1. Click Submit
2. Click Add Member
3. Remove the Member

The error no longer shows up (because the field is not marked touched).

**Comment by huan086** [comment]
@erikras The `FieldArray` is using `meta.touched`, which is not documented! `meta.touched` cannot be supported as the store state `fields` that's backing it is an array.

Thus currently, there is no way to get the error to show up. With #2473, the first submit no longer shows the error.

**Comment by nktssh** [comment]
@huan086 is there any way to show `FieldArray` error to user on first submit?

**Comment by huan086** [comment]
Need a pull request to add FieldArray.meta.submitFailed prop

**Comment by danielrob** [comment]
Closing as [submitFailed will be documented in 7.0.4](https://github.com/erikras/redux-form/pull/3282), and this reproduction is [fixed against 7.0.3](http://redux-form.com/7.0.3/examples/fieldArrays/)
