### ISSUE TITLE
Access to submitErrors

### ISSUE THREAD

**Issue by mmahalwy** [erikras/redux-form#2210]
I am noticing that when an error is sent through `SubmissionError` which is not a field, it gets put into a key called `submitErrors`. This is not accessible via a prop in the form.

Example:
![image](https://cloud.githubusercontent.com/assets/3749095/20830916/9ab36448-b837-11e6-9527-5d721cc44395.png)
I'd like to access the `fullMessages` key but i cannot.

**Comment by swp44744** [comment]
**@mmahalwy** I guess you can access them by:
`const submitErrorsValues = state.form.formName.submitErrors`
`console.log('error',submitErrorsValues[fieldName]);`

**Comment by gustavohenke** [comment]
You can do this with the `getFormSubmitErrors` selector:

```
connect( state => ({
  submitErrors: getFormSubmitErrors( formName )( state )
}))(formComponent);
```

**Comment by Floriferous** [comment]
Is there a reason that submitErrors is not passed in props? I understand there's a workaround, but it's not clear to me why most other props can be accessed directly via a prop, but not this one (and a few others of course)?

**Comment by herarya** [comment]
@gustavohenke i same issue, not still null `getFormSubmitErrors ` , `from 'redux-form/immutable`
