### ISSUE TITLE
How to modify a field based on another one

### ISSUE THREAD

**Issue by TeaBough** [erikras/redux-form#2212]
I've two Datepicker components (`start` and `end`). In my form I'd like to keep the `end` input value after the `start`. This means that when the user change the `start` input and that value become bigger than the `end` field, I'd like the end field to automatically increase. 

How can I do that with redux-form ?

**Comment by Malax** [comment]
What about using the normalizing feature? You get passed the old and new values along with all values in the form to normalize your end value. See: http://redux-form.com/6.2.1/examples/normalizing/

**Comment by TeaBough** [comment]
yup, but is it possible to modify `fieldB` from the normalizer of `fieldA` ?

**Comment by Malax** [comment]
There is always the _change_ function that is passed to your form as a prop that you can use to programatically change fields. See the [props documentation](http://redux-form.com/6.2.1/docs/api/Props.md/) for more info.

**Comment by TeaBough** [comment]
Nice ! I didn't notice that ! Thanks !

**Comment by Malax** [comment]
If this issue is resolved, you should close it. That way @erikras does not have to sift though resolved  issues. :)

**Comment by erikras** [comment]
😫 so... many... open... issues... 😩 

Closing this one. 👍
