### ISSUE TITLE
undo/reset for a field

### ISSUE THREAD

**Issue by jole78** [erikras/redux-form#2224]
Couldn't find it in the docs or other places.

It would be a nice enhancement to be able to reset/undo just one field and restore the value to the initial value it had when it was mounted.

**Comment by danielrob** [comment]
(with signature `reset(...fields)`)

**Comment by erikras** [comment]
Fix published in [`v7.2.0`](https://github.com/erikras/redux-form/releases/tag/v7.2.0).
