### ISSUE TITLE
Can you use redux-form with redux-saga?

### ISSUE THREAD

**Issue by pbgnz** [erikras/redux-form#2227]
How do you go about it?

**Comment by erikras** [comment]
The one problem is that redux-form relies on the use of Promise middleware to some extent, but it might be possible. I have not, but I believe that others have. I shall let someone more experienced in such matters respond....

**Comment by Sparragus** [comment]
@pbgnz I'm also looking for a proper way to handle this. So far I've found this: https://github.com/yelouafi/redux-saga/issues/161#issuecomment-191312502

**Comment by Sparragus** [comment]
I like this solution even better: https://github.com/yelouafi/redux-saga/issues/161#issuecomment-254939672

**Comment by bghveding** [comment]
I've been using https://github.com/colinbate/redux-form-submit-saga in our projects with no issues so far.

**Comment by gustavohenke** [comment]
That issue from redux-saga already includes some good ideas on how to integrate both libs (and I'm using them).
@erikras, probably adding some examples on how to integrate both libs is a good call.

**Comment by TrevorHinesley** [comment]
@gustavohenke how exactly did you implement the suggestion by oanylund?

```
function* createEntity(entity, apiFn, formId, newEntity) {
  yield put( entity.request() )
  yield put( startSubmit(formId) )
  const {response, error} = yield call(apiFn, newEntity)
  if(response) {
    yield put( entity.success(response) )
    yield put( reset(formId) )
    yield put( stopSubmit(formId) )
  }
  else {
    yield put( entity.failure(error) )
    // handle and format errors from api
    yield put( stopSubmit(formId, serverValidationErrors) )
  }
}
```

I'm not sure what `entity` and `newEntity` are, or how to call this properly.

**Comment by gustavohenke** [comment]
That's what my sagas usually look like:

```js
function *mySaga ( action ) {
    yield put( startSubmit( MY_FORM ) );

    try {
        const response = yield call( api.createUser, action.payload );
        yield put( stopSubmit( MY_FORM ) );
        yield put( reset( MY_FORM ) );
    } catch ( e ) {
        yield put( stopSubmit( MY_FORM , e.response.data ) );
    }
}
```

`api` object contains methods that wrap logic around [axios](https://github.com/mzabriskie/axios).

I hope it helps.

**Comment by TrevorHinesley** [comment]
Thank you!

**Comment by TrevorHinesley** [comment]
Do you use handleSubmit at all? Or just override it and dispatch that saga?

**Comment by gustavohenke** [comment]
> Do you use handleSubmit at all? Or just override it and dispatch that saga?

I usually bind an action creator to a prop `onSubmit`.

**Comment by loayzag91** [comment]
I see a lot of people asking about dispatching a saga on a submit, which I understand is the most practical usage of sagas.
However, what if I would like to make an API call in the event that a user makes a selection that should provide options related only to that selection?

In case an example is needed to be clear; I would like to make an API call for every city in the state that the user selects. I thought I could have the redux-form 'select' input dispatch an action on 'CHANGE' that the saga would pick up before being handled by the reducer and cause the API call to trigger, but I could not get this to work. 

Is this a problem with saga integration, or am I simply trying to do something redux-form isn't meant to do; dispatching a separate action along side with the CHANGE action meant to update the store?

**Comment by TrevorHinesley** [comment]
@loayzag91 I'm not sure you can guarantee that the saga would answer the call BEFORE the reducer, but it should indeed pick it up if you dispatch it. I don't see why that wouldn't work on first glance.

**Comment by loayzag91** [comment]
I'm sorry, I made a simple mistake. I didn't realize that the action that was being dispatched for every change was `'@@redux-form/CHANGE'` not just `'CHANGE'` or even `'redux-form/CHANGE'.` Once my sagas were listening for the correct action, they worked as expected.

Redux-Saga works fine as a middleware for what I was trying to accomplish. Seems other people have posted solutions for form submission as well. I can't think of any other special use cases for redux-saga. Why is this issue still open? Is this a request to create an example in the docs?

**Comment by bghveding** [comment]
@TrevorHinesley @loayzag91 From the saga docs

> It's important to note that when an action is dispatched to the store, the middleware **first forwards the action to the reducers** and then notifies the Sagas. This means that when you query the Store's State, you get the State after the action has been applied. However, this behavior is only guaranteed if all subsequent middlewares call next(action) synchronously. If any subsequent middleware calls next(action) asynchronously (which is unusual but possible), then the sagas will get the state from before the action is applied. Therefore it is recommended to review the source of each subsequent middleware to ensure it calls next(action) synchronously, or else ensure that redux-saga is the last middleware in the call chain.

https://redux-saga.js.org/docs/api/index.html#selectselector-args

@loayzag91 I recommend importing the CHANGE action from redux-form, in case the type changes

e.g.
```js
import { actionTypes } from "redux-form";

yield takeLatest(actionTypes.CHANGE, action => doSomething());
```

**Comment by alpox** [comment]
For anyone interested, i ran into the same issue with my project and i put together a solution based on the ones proposed before. The difference is that it does not need the redux form identifier and neither the redux action types/creators:

https://github.com/redux-saga/redux-saga/issues/161#issuecomment-314480664

The good thing about it is that one can easily create an action creator in the `redux-actions` way and one only has to wrap the saga into a ` formSaga` call when giving it to `takeEvery`. Thats all it takes then to make the dispatch return a promise which automatically resolves/fulfills depending on if the saga threw an error or run through successfully.

So its possible to just throw a submission error in the saga right away without having the rest of the clutter.

I also made on top of what you find in my other comment an additional wrapper around `formSaga`:

```
export function standardPromiseSaga(
    prefix: string,
    originalSaga: (...args: any[]) => any,
) {
    function* standardSaga(action: any) {
        try {
            yield put(pending(prefix));
            const response = yield call(originalSaga, action);
            yield put(fulfilled(prefix, response));
        } catch (err) {
            yield put(error(prefix, err));

            if (
                err &&
                err.response &&
                err.response.data &&
                err.response.data.error
            )
                throw new SubmissionError({
                    _error:
                        err.response.data.error.fields ||
                        err.response.data.error,
                });

            // Rethrow error if its not a SubmissionError
            throw err;
        }
    }
    return formSaga(standardSaga);
}
```
This one might inspire, but its not a standalone function since it also needs a reducer to work properly and your errors might be located somewhere else in the return data of your api.

It just makes it possible for me to call
```
function* getUserSaga({ payload: username }) {
    yield call(api.getUser, username);
}

yield takeEvery("SOME_ACTION_TYPE", standardPromiseSaga(getUserSaga));
``` 
And `standardPromiseSaga` does all the work for me like setting the states for pending/error/fulfilled, rejecting with an error for `redux-form`, resolving with the right data etc.

I hope someone might find this useful :-) it helps me a lot in my app.

**Comment by andidev** [comment]
> > Do you use handleSubmit at all? Or just override it and dispatch that saga?

> I usually bind an action creator to a prop onSubmit.

This will make redux-form to incorrectly create an SET_SUBMIT_SUCCEEDED action. Is there  anyway to avoid this?
