### ISSUE TITLE
Question: Adding a show/activate call to the API

### ISSUE THREAD

**Issue by mattkrick** [erikras/redux-form#223]
I have a field called `name` that is rendered to a span. That span has an onClick which changes my `isEditing` state to true. By changing that state, the component rerenders, replacing the span with an input so now I can edit the name. Right now, `isEditing` is a state that belongs to the component, but I'd like to put in the redux store (preferably through redux-form). Is there a pattern to do this?

I tried passing the form field props to both the span & the input. My idea was that if I could call a focus from the span (via the direct action creator or through calling a `handleFocus`) I could change the `active` state & use that to trigger rendering the input, but I don't think that works with non-input elements.

**Comment by mattkrick** [comment]
Ah nevermind, v3 made this possible!
In case someone else has the same problem...

```
render() {
    const fieldName = 'foo';
    const isEditing = this.props.active === fieldName;
    return (
      <div>
        {isEditing ?
          <input {...this.props.fields[fieldName]} autoFocus={true} /> :
          <span {...this.props.fields[fieldName]} onClick={this.props.fields[fieldName].onFocus}>Foo</span>}
      </div>
    );
  }
```

**Comment by erikras** [comment]
Ha! Clever workaround to call the field's `onFocus` on the span's `onClick`. :+1:
