### ISSUE TITLE
Wizard Form Live example in the documentation is not working properly

### ISSUE THREAD

**Issue by KamilHavlicek** [erikras/redux-form#2231]
Live example of http://redux-form.com/6.2.1/examples/wizard/ is most likely not working properly.

![reduxform7](https://cloud.githubusercontent.com/assets/6735567/20948547/fe7f339a-bc14-11e6-9fc5-7b18c8d2f51d.gif)

To reproduce the bug, please follow these "test steps":
1) Enter John into the First Name field
2) Enter Doe into the Last Name field
3) Press Next button (to get to the second step)
4) Click on Previous button (to get to the first step)
5) Click on Next button -> and nothing is happening. Expected behaviour: It should go to the Step 2, but it stays on the first form step.

Interestingly, example http://redux-form.com/6.2.0/examples/wizard/ works, but http://redux-form.com/6.2.1/examples/wizard/ does not.

**Comment by hamczu** [comment]
I have just encountered the same issue - I can confirm it's not related to example code, but it just stopped working. It looks like there's a regression.

**Comment by kristofferh** [comment]
Fields no longer get unregistered when `destroyOnUnmount=false` (but they do get registered) so when you advance to the second screen and then go back it'll try to validate against fields that are no longer visible. I'm not exactly sure what use case #2113 was solving (there's no description in the pull request), but it definitely breaks the multi-form/wizard example.

**Comment by erikras** [comment]
Fix published in [`v6.4.0`](https://github.com/erikras/redux-form/releases/tag/v6.4.0).
