### ISSUE TITLE
Redux-form will unmount when a button inside the form is clicked

### ISSUE THREAD

**Issue by ripitrust** [erikras/redux-form#2235]
Hi 
I am wondering if there is a way to stop the form from unmounting itself when a button is clicked inside the form (even though the button is not the submit button)

**my current use case is :** 
when user fill in the `id` field, he can click on a button like "find info" to query the backend and auto populate some fields of the form 

**my problem are** 

1. In normal case, I can get my form to be updated by setting the `initialValues` props with the new value returned from api call. However, due to the unmounting issue, the `id` is cleared, because of the `destroyOnUnmount` is True

2. If I set the `destroyOnUnmount` to False,  the `id` field is retained, but new value assigned to `initialValues` will not be rerendered

3. Some of my fields inside the form are using react-select async,  so everytime the form is unmounted and mounted, the react-select will trigger the api call, which is not necessary https://github.com/JedWatson/react-select/issues/1369

4. Because of the unmounting, everytime when user fill up the form and click submit, if there is an error, all the input will be lost (cleared)

and also, upon reading this issue https://github.com/erikras/redux-form/issues/145 ,  seems like reducer plugin is the correct way to perform the auto update action ? 

Thanks !

**Comment by Aaronius** [comment]
@ripitrust This might be obvious and you may already know about it, but it's a bugger when you don't know or forget: is your button like this?

```
<button type="button">Button</button>
```

If it doesn't have `type="button"` then it defaults to being a submit button. It sounds like in this case you don't want a submit button.

**Comment by ripitrust** [comment]
@Aaronius  Thanks for the reply

Indeed I didn't put the type

But I think this problem is caused by un-mounting and re-mounting of the form component

I added the `type='button'` but it is still un-mounted when this button is clicked

**Comment by flyingalex** [comment]
I also got the same error,any update?

**Comment by dcarr178** [comment]
On latest redux-form, the form unmounts on me when I add <button> without a type but works fine if I use <button type="button">

**Comment by boy-techy** [comment]
@ripitrust  Can you provide SandBox ?

**Comment by gustavohenke** [comment]
Given the OP didn't chime in in more than a year, I'll close this issue.
Feel free to continue the discussion.
