### ISSUE TITLE
Please hoist statics..

### ISSUE THREAD

**Issue by delijah** [erikras/redux-form#2237]
..when using reduxForm.

https://github.com/mridgway/hoist-non-react-statics

**Comment by erikras** [comment]
Eh? This library is already doing that. Can you demonstrate where/how it is not?

**Comment by delijah** [comment]
Might be a mistake. Can't remember the exact use case. Thanks for your reply though!

**Comment by samcorcos** [comment]
@erikras Here's an example where statics aren't being hoisted:

https://github.com/react-community/react-navigation/issues/332#event-961713900

**Comment by russelh15** [comment]
Experiencing the same issue when using React-Navigation and ReduxForm.

**Comment by jamesalways** [comment]
Hi! Please fix it! Same issue when using React-Navigation. Thanks!

**Comment by russelh15** [comment]
@jamesalways The work around I used is to apply the navigationOptions to the component after it's wrapped in ReduxForm. I hope that helps you.
