### ISSUE TITLE
Remote submit breaks when submit function passed to handleSubmit

### ISSUE THREAD

**Issue by andynoelker** [erikras/redux-form#2238]
I've been messing around with [remote submit](http://redux-form.com/6.2.0/examples/remoteSubmit/) lately and it works **beautifully** whenever I pass my submit function to `reduxForm()` as a config value. However, if I instead supply it to my `handleSubmit()` function on the form, my app breaks with the following error:
```
You must either pass handleSubmit() an onSubmit function or pass onSubmit as a prop
```
Note that I am using `redux-form/immutable` and that I'm using stuff like `bindActionCreators` so maybe there is some weird combination there or maybe my implementation is simply wrong, but this seems like a bug to me.

I'm using:
redux-form v6.2.1
redux v3.6.0
react v15.3.1

Here's a simplified version of my code:

**Wrapper.js**
```
import { bindActionCreators } from 'redux';
import { connect } from 'react-redux';
import { submit } from 'redux-form/immutable';

const mapDispatchToProps = function (dispatch) {
  return bindActionCreators({
    submit: submit
  }, dispatch);
};

class Wrapper extends Component {
  render() {
    return (
      <MyForm />
      <SubmitButton submit={submit} />
    );
}

export default connect(mapStateToProps, mapDispatchToProps)(Wrapper);
```

**MyForm.js**
```
import validate from './validate';

class MyForm extends Component {
  mySubmitFunction = (values) => {
    console.log('submitted!');
  }

  render() {
    const { handleSubmit } = this.props;

    return (
      <form onSubmit ={handleSubmit(this.mySubmitFunction)}>
        <Field ...fieldProps />
      </form>
    );
  }
}

export default reduxForm({ form: 'myForm', validate })(MyForm);
```

**SubmitButton.js**
```
export default class SubmitButton extends Component {
  submit = () => {
    this.props.submit('myForm');
  }

  render() {
    return <button onClick={this.submit}>Submit</button>
  }
}
```

Shouldn't this code work? I'm making my submit function local to the `MyForm` class here, but it still breaks if it is an external function. Once again, this works perfectly if I pass an external submit function to `reduxForm()` instead. Is this a bug?

**Comment by theKashey** [comment]
You have to pass onSubmit to redux-form constructor, not the "Form".
Logic is simple - you will trigger action, and redux-form will submit itself. And in this save - it just dont see your logic in onSubmit prop of form.
But should. Or have to indicate in documentation: please always use onSubmit as prop of redux-form, cos bla-bla-bla undefined behavior in some saves.

**Comment by andynoelker** [comment]
@theKashey I know that I could pass an external function into the redux-form constructor as this is exactly how it is done in the documentation. And that works fine for me. But according the Remote Submit documentation page:

> submit function must be given to the form component via either a config value passed to reduxForm() **or via a prop**

It says right there that you can *also* provide it **via a prop**. I want to trigger an action for submit, not use an external function. Therefore I think I would have to define this on the form component itself as I don't have access to my actions outside of my components (and to do so would break with redux architecture). @erikras is the documentation wrong here or am I just not getting something?

**Comment by sunnysingh** [comment]
I'm in the same pickle as @andynoelker where I need access to my form's props (for appState and actions) within the submit function, thus I am configuring it within a method of my form component class. However, it doesn't seem to possible to be able to do this as well as have a way to remotely submit a form, or is anyone familiar with a workaround?

**Comment by andynoelker** [comment]
@sunnysingh I have discovered that there is a way to fire off an actionCreator from an external function here. If you check out the [reduxForm docs](http://redux-form.com/6.2.0/docs/api/ReduxForm.md/) and look at the `onSubmit` function parameters you will see that the second param that is passed in is the Redux `dispatch` function. So if you want to use an action for an external function, you could do something like this:
```
import * as actionCreators from './actionCreators';

function externalSubmit (values, dispatch, props) {
  dispatch(actionCreators.submitAction(values));
}

export default reduxForm({
  form: 'remote',
  onSubmit: externalSubmit
})(MyComponent);
```
Unfortunately I still don't know a great way to get your general Redux state props in that function. The third `props` parameter appears to only contain props specific to Redux Form and not everything passed into the connected component (like the docs seem to imply). Hopefully that helps you!

**Comment by andynoelker** [comment]
@erikras is the remote submit documentation wrong when it says that you can pass the submit function as "*either* a config value passed to reduxForm() **or via a prop**". It looks like it is only the config value passed to `reduxForm()` that works. I have even built the remote submit example directly and found the same results if I tried to use the `handleSubmit` property on the form instead of a static config value. I am happy to submit a PR for a change in the docs if that is the case!

**Comment by erikras** [comment]
This sounds like a bug. Investigating... 🔍

**Comment by erikras** [comment]
Good news. I've reproduced this in a test. 🎉

**Comment by erikras** [comment]
Okay, I've figured it out. If you are using this way of handling your form submission:
```jsx
<form onSubmit ={handleSubmit(this.mySubmitFunction)}>
```
...calling either the [Instance API `submit()`](http://redux-form.com/6.3.1/docs/api/ReduxForm.md/#-submit-promise-) or submitting via an action, **_cannot_** call the `onSubmit` provided to the `<form>` element inside your `reduxForm()`-decorated component.

We have three options to proceed from here, and two of them are fairly disgusting and the other disappointing:

1. Somehow scan the tree of React elements inside the redux-form component to find the `<form>` element, get its DOM instance, and call `onSubmit()` on it. (I'm not 100% sure how to even do this.) Okay, so my "_cannot_" above might have been not entirely true.
2. Check to see if the decorated redux form component has a method called `submit()`, and call that. An alternative would be to have a config param name the function, i.e. `submitMethod: 'mySubmitFunction'`.
3. Just change the docs to specify that you must provide the `onSubmit` function as a prop or config setting if you want to use either the instance API or the submission via action.

Thoughts?

**Comment by davidkpiano** [comment]
4th option: a `<Form>` component that's just a shallow wrapper for `<form>`, which will already know what is passed to its `onSubmit` so you can use your `redux-dead-drop` strategy to listen for dispatched `submit` actions and call submit?

E.g. `<Form onSubmit={handleSubmit(...)}>`

**Comment by erikras** [comment]
I don't care what they say; you've got a good head on your shoulders, @davidkpiano. 😄

**Comment by davidkpiano** [comment]
Happy to help in any way!

**Comment by andynoelker** [comment]
@davidkpiano I love option 4! @erikras should someone open a `<Form>` feature request issue that references this one and then I close this out?

**Comment by erikras** [comment]
Fix published in [`v6.4.0`](https://github.com/erikras/redux-form/releases/tag/v6.4.0).

**Comment by dqhendricks** [comment]
@erikras I am having this same problem in version 6.6.3. I do not understand the suggested fix. Just change the <form> to <Form>?? I tried that and still, dispatching submit does not work. Whatever the fix is, can you please add it to the remote submit example documentation, or a more thorough explanation here?

**Comment by dqhendricks** [comment]
never mind. the problem was elsewhere. sorry!

**Comment by dbelchev** [comment]
Actually, there's no need to add onSubmit function to the constructor and indeed you CAN pass the onSubmit function to handleSubmit. 
For React users <form onSubmit={...}> is a good solution, but for react-native you can use this approach:
`<Button
  onPress={() => handleSubmit(this.props.onSubmit)()} />`

**Comment by boon4376** [comment]
I struggled with this for a few hours. And it was as simple as including "Form" in the redux-form import statement
```
import { Form, Field, reduxForm, SubmissionError } from 'redux-form';
```
And changing to an uppercase "Form" for my form tag.
```
<Form name={formName} id={formName} onSubmit={handleSubmit((() => this.submitForm()))}>
```
And I can now remotely submit the form from an action
```
// Submit the form
dispatch(submit(formName));
```
I agree that the documentation should be updated to include an example like this.
