### ISSUE TITLE
Disable validation on keypress event?

### ISSUE THREAD

**Issue by nguyenbathanh** [erikras/redux-form#2240]
Currently when user is typing on a field, the validation is triggered automatically.

Is there any option to disable this? I want the validation is only triggered when user click out of those fields.

**Comment by MikeBarnhardt** [comment]
Have you tried the [`shouldValidate()`](http://redux-form.com/6.3.1/docs/api/ReduxForm.md/#-shouldvalidate-params-boolean-optional-) function?

**Comment by nguyenbathanh** [comment]
@MikeBarnhardt Your suggestion is confused to me. My purpose is prevent validate triggered automatically on `keypress` event.

**Comment by MikeBarnhardt** [comment]
I don't know. Maybe you could use only `asyncValidation` since it runs `onBlur`. You could use `submitValidation` to ensure values are correct. You will need to immediately resolve the promises in the `asyncValidation`.

**Comment by cdaringe** [comment]
hmm. ya--in one of the older APIs you could get the state of whether it was focused or not.  it may be worth dropping a PR to add `shouldValidate` at the field level as well as the form level.  that would help ya, iff you could also get the focus state.  another strategy would be to do `<Field onClick={maybeValidate} />`, and you could `_.throttle` your validations?  not exactly what you're looking for. shucks.  this should definitely be a thing.  of course, using `{touched && error}` as inputs to whether or not to show the error in most cases is enough.  that of course assume your validation isn't _too_ heavy of lifting :)

**Comment by danielrob** [comment]
Closing this due to non-response. If you want to clarify the issue, feel free. 

Another option would be to use an instance variable on your renderField class, and in your onChange function update the instance variable to 'was keypress'. Then your validate method could switch on this instance variable. Pseudocode:

```
onChange = (e) => {
  this.wasKeyPress = !!e.keyCode
}

validate = (values, props) => {
  if (this.wasKeyPress && !props.submitting) {
    // validate
  }
} 
```
