### ISSUE TITLE
Submit validation doesn't trigger

### ISSUE THREAD

**Issue by likerRr** [erikras/redux-form#2244]
Here example code https://jsbin.com/guxoqiqevo/edit?js,console,output

Code above should trigger validation every time when "Push me" button is clicked. But actual result is that validation triggers only once. Just open dev tools and look to output. Every time validation triggers `console.log()` should be handled (but it doesn't).

What's wrong with this? I use this code in production, so I would appreciate for your asap response. 

P.S. Yes, I need to call `handleSubmit` function outside of render method (but actually it doesn't matter). It's my an informed choice.

Thx

**Comment by erikras** [comment]
It doesn't try to submit if your form is invalid, and it already knows that it is invalid. If you were to change a field, it would submit again.

Do you want it to try again because of some state that might no longer be the case on the server?

**Comment by likerRr** [comment]
@erikras thank you very much. I also came to the reasons and I think my case is quite specific. I have three Fields (`video`, `image`, `imageOrVideo`) on the form. `video` and `image` are inputs and `imageOrVideo` just Field with `div`, that prints value of `meta.error`. And my validation should resolve only if `video` or `image` has a value. In case when they both are empty I throw SubmitionError with object with key `imageOrVideo`. And as the result, when I finally choose video or image, the error doesn't disaper, vecause `imageOrVideo` wasn't changed.

So as you can see I use `imageOrVideo` just to print the error. I need to do so, because I display an error outside of two of these components. Also I can't use `_error` key, because it need for other purposes.

I hope you understood me case. Ask me questions if not. 

Could you please advise something for my case? The only thing I found is to manually trigger `props.change('imageOrVideo', null)`. May be there are better variants?

**Comment by erikras** [comment]
Fix published in [`v6.3.1`](https://github.com/erikras/redux-form/releases/tag/v6.3.1).
