### ISSUE TITLE
current values?

### ISSUE THREAD

**Issue by arolson101** [erikras/redux-form#2253]
Previous versions of redux-form injected a 'values' property that you could use to inspect the form's current values.  Is there any way to get that in the new version?

**Comment by jole78** [comment]
could you use formValueSelector in combo with connect...??

**Comment by mokone91** [comment]
Hi, I use formValueSelector, but in this case i should pass extra property with this value  to form.

I think its will be nice, if we will can get value of form inside the form and skip extra property

Thanks!
Eldar.

**Comment by Aaronius** [comment]
@mokone91 I think v6 of redux-form intentially doesn't provide you the values without using `formValueSelector` due to performance reasons. Always providing the current value of the fields is expensive with large forms. The performance benefit of not doing that is one of the "features" of v6, though inconvenient at times.

**Comment by jole78** [comment]
@arolson101 could you perhaps give a use case for wanting all the values in your form and we can advise on an alternative perhaps?

**Comment by esseswann** [comment]
@jole78 simplest example - your select field options depend on another field value

**Comment by jole78** [comment]
@esseswann so basically you need to use the formValueSelector to "listen" to state changes on the dependent field and use that value as input into another field for selection?
something like this....?? (or tell me more what you need)

```javascript
const mapStateToProps = (state, ownProps) => {
  const selector = formValueSelector('THE_FORM')
  return {
    somefield: selector(state, 'some_field')
  }
}
...// and in the form
<Field
  name="some_other_field"
  component={SomeOtherComponent}
  somefield={this.props.some_field} />

const SomeOtherComponent = (props) {
   if(props.somefield) {
    // ....do whaterever
  }
}
```

**Comment by arolson101** [comment]
My use case is to conditionally change form values based on an event.  Specifically, choosing a select value will auto-fill some form fields unless the user has changed them.

The values don't need to be properties, specifically; just having a function I could call to get the values would be sufficient.

**Comment by mokone91** [comment]
@jole78 i my case, i trying to write reusable form, so the idea is - make so independent form as it possible,
so if i can get access to value inside form, then i cant forgot about this dependency at all.

for example: color picker which can change self color dependent on selected value. to use it across the app i should pass the selected property from each parent component.

Thanks!

**Comment by cdaringe** [comment]
@arolson101, i have the same need.  i'm sure we can find a better way to do this in the future, however, i did write https://www.npmjs.com/package/reduxify-form for this same issue.

**Comment by gustavohenke** [comment]
Most of these use cases may be resolved by using the [`Fields` component](http://redux-form.com/6.5.0/docs/api/Fields.md/).
Take a look, try some stuff, and if you still have questions, please ask it over StackOverflow.

**Comment by afraser** [comment]
I have a form that has a button that's supposed to show the whole form in a json structure. The current implementation makes this extremely awkward.

**Comment by xurei** [comment]
I came across this problem several times, and using `Fields` feels overcomplicated to me.
So I made this helper component to deal with that.
I'm really interested in your reviews, guys. It would be wonderful to have that in the official API.
@erikras What's your opinion ?

```javascript
import React from 'react';
import PropTypes from 'prop-types';
import deepEqual from 'deep-eql';

/**
 * Used in conjunction with redux-form. Allow to watch some current values in a form, 
 * to ease conditional rendering
 */
class CurrentValues extends React.Component {
    static propTypes = {
        names: PropTypes.array.isRequired,
    };
    static contextTypes = {
        _reduxForm: PropTypes.object
    };
    
    render() {
        // Note: the useful data is extracted from the Context and sent to CurrentValueSub,
        // to avoid useless re-rendering
        const props = this.props;
        const names = props.names;
        const contextValues = this.context._reduxForm.values || {};
        const valueObj = {};
        names.forEach(key => {
            valueObj[key] = contextValues[key];
        });
        const childProps = Object.assign({}, props, {names:undefined});
        
        return (
            <CurrentValueSub values={valueObj} {...childProps}/>
        );
    }
    
    shouldComponentUpdate() {
        //TODO check only required things in context, if possible
        return true;
    }
}

class CurrentValueSub extends React.Component {
    static propTypes = {
        values: PropTypes.object.isRequired,
    };
    
    render() {
        const props = this.props;
        return (
            <div className={props.className}>
                {this.props.children(props)}
            </div>
        );
    }
    
    shouldComponentUpdate(nextProps) {
        // Only re-renders if the 
        return !deepEqual(this.props, nextProps);
    }
}

export { CurrentValues };
```

Usage:
```javascript
{/* business as usual */}
<Field name="myfield" component="input"/>

{/* watch myfield */}
<CurrentValues names={['myfield']} {...props}>
    {props => (
        <div>
            {/* should contain {values: {myfield: '...'}} */}
            <pre>{JSON.stringify(props, null, '  ')}</pre>
        </div>
    )}
</CurrentValues>
```

**Comment by scottdickerson** [comment]
This is pretty frustrating because the documentation still points to the values as an embedded prop: https://redux-form.com/8.2.2/docs/api/reduxform.md/
