### ISSUE TITLE
Setting input values after async action completion

### ISSUE THREAD

**Issue by fmr** [erikras/redux-form#226]
I'm sure it has been discussed before, but I can't seem to get my head around how to programmatically set input values in a form *after* an async action completes. I trigger this async "fetch" action from the parent component's `componentWillMount` method.

The problem I'm having is that I can't seem to figure out how to set field values based on the data received from the API fetch call.

When the state already contains relevant values for input elements, the inputs render with their respective `defaultValue` values (using the `initialValues` attribute of the form). However, if the state is currently empty, and I dispatch an async action to populate the state, the fields remain empty.

If I add a `value` attribute and pass the value of `defaultValue` for an input, the field will not be empty, but I won't be able to make changes to it (and because you shouldn't be doing that, apparently).

I have tried looking into the `initialize` and `change` actions from `redux-form`, but neither of them seem to update field values - at least I don't see any visible change, as the fields remain empty.

**Comment by bs1180** [comment]
It looks like this has been addressed in v.3 final, since you can now [initialise from state](http://erikras.github.io/redux-form/#/examples/initializing-from-state) within the form itself. Make sure your reducer updates the relevant slice of state when the async action completes, and you should be in business.

**Comment by erikras** [comment]
Yep. I've been meaning to go through and notify the open issues that their problems have been addressed in v3.

Thank you, @fmr. Your question influenced the design of v3.

**Comment by fmr** [comment]
@bs1180 thanks for pointing me in the right direction. @erikras, thank you for making those changes!
