### ISSUE TITLE
If onSubmit return promise - store it.

### ISSUE THREAD

**Issue by theKashey** [erikras/redux-form#2261]
Where is no (normal) way to do `remote submit` to a form with onSubmitHandler returning promise, and wait for it.
If one will store that promise in form state – it would be not a great, but expected.

**Comment by gustavohenke** [comment]
[Redux state must be serializable](http://redux.js.org/docs/introduction/ThreePrinciples.html), so you can'
Promises are heavily based on functions, so you can't do this.

Another way to do what you is.. use promises themselves!
Call whatever you want when the promise gets resolved/rejected.
