### ISSUE TITLE
isPristine / isDirty does not change for array of values

### ISSUE THREAD

**Issue by d-winter** [erikras/redux-form#2264]
Hi.
I have a form with an array as one value:

```
myForm: 
  --> values
    --> myArray
      0: 'foo'
      1: 'bar'
```

When I add or remove a value within this array, the return values of isPristine and isDirty are not changing.
Is there a way to detect the change?

**Comment by Aaronius** [comment]
With Redux you typically treat the state as immutable. So, in this case, you would typically do `myArray.slice()` to make a new copy and then modify the new copy.

I don't know of any other way to make redux-form see the change.

**Comment by d-winter** [comment]
@Aaronius sorry, your totally right. I missed to use the action creator arrayPush/arrayRemove of redux-form.
Thanks for your help!

**Comment by Aaronius** [comment]
No problem. I happened to fix the same bug at work the same day I answered.
