### ISSUE TITLE
remote submit in componentWillUnmount

### ISSUE THREAD

**Issue by rszczypka** [erikras/redux-form#2266]
My idea is to save a form in componentWillUnmount method just in case the user forgot to do it on their own. 
I'm using the remote submit like here: http://redux-form.com/6.3.1/examples/remoteSubmit/
It works perfectly on button click but when I do 
```
componentWillUnmount() {
    this.props.dispatch(submit('positionGeneral'));
  }
```
nothing happens.

Any ideas what can be wrong?

**Comment by gustavohenke** [comment]
This type of issue is probably more suited to StackOverflow :)

But since you asked here...
Perhaps your instance of redux-form is unmounting before you have a chance to dispatch that action?

**Comment by gustavohenke** [comment]
Oh, and if you're not using it already, [Redux DevTools](https://github.com/gaearon/redux-devtools/) is a great way to understand what's going on in your store.

**Comment by rszczypka** [comment]
Thanks, I'll check that soon.

**Comment by gustavohenke** [comment]
Any news here, @rszczypka?

**Comment by rszczypka** [comment]
Hi @gustavohenke, you were right of course. 
I can just do 
```
componentWillUnmount() {
    if(this.props.valid && this.props.dirty) {
      this.props.handleSubmit();
    }
  }
```
in my form component and it works.

Thank you again for your suggestion!

**Comment by gustavohenke** [comment]
Great!
