### ISSUE TITLE
How to show errors on initial render?

### ISSUE THREAD

**Issue by rajanand02** [erikras/redux-form#2267]
I have a redux form in which I need to show error on initial render itself. I get the error messages object from the server api request. I am already using `syncErrors`, `syncWarning` and also `submitErrors` on `POST` request. On `POST` returning a promise with `SubmissionError` works perfectly fine but I would like to know if there a possibility to update the `syncErrors` using the `errors` object from api `GET` request.

**Comment by cdaringe** [comment]
hey @rajanand02, i think there may be a misunderstanding.  `syncErrors` are never intended to be updated with a bogus network request.

`syncErrors` ==> `clientSideErrors`
`SubmissionError({ ...fields })` ==> `serverSideErrors`

if you want to handle them both the same way, you could do `finalErrors = Object.assign(syncErrors, whateverPropHoldsTheSubmissionErrorsThatImBlankingOutOnAtTheMoment)`

**Comment by danielrob** [comment]
Closing due to lack of response from OP. 

Note as well another way to _have_ errors on initial render is to set invalid initialValues.
