### ISSUE TITLE
Cannon read property '_error' of undefined

### ISSUE THREAD

**Issue by reznord** [erikras/redux-form#2272]
So, I had to set `enableReinitalize ` to `true` for  solving the issue mentioned in https://github.com/erikras/redux-form/issues/621 . 

Now when I set the `enableReinitalize: true` , the validate function doesn't work for some reason. It throws an error saying `Cannot read property '_error' of undefined` which prevents from opening the form where we enabled `enableReinitalize: true`.

The screenshot of the error - 
<img width="1280" alt="error after setting enableReinitalize: true" src="https://cloud.githubusercontent.com/assets/3415488/21114669/dca4a098-c0d3-11e6-89ab-9c9eeee69262.png">

The example code for the form page is https://gist.github.com/reznord/eb0e50539dc72484b7d446f7b8141280

Any ideas on how to fix this?

**Comment by erikras** [comment]
You're gonna kick yourself.

.

.

Ready?

.

.

You can't return `undefined` from `validate()`. You need to swap lines 98 and 99, so the `return errors` is outside of the `if` block.

That said, it would behoove the library itself to default `undefined` to `{}` as a response from `validate()`. So I will look into that....

**Comment by reznord** [comment]
@erikras cool, thanks for that. That was a silly mistake !! 😅

**Comment by erikras** [comment]
Fix published in [`v6.4.0`](https://github.com/erikras/redux-form/releases/tag/v6.4.0).
