### ISSUE TITLE
Allow react-redux@5.0.0 peer dependency

### ISSUE THREAD

**Issue by ArcanisCz** [erikras/redux-form#2279]
It would be cool to have redux-form updated its peer deps of react redux. It seems, there are no real api changes aside some event order issues.
https://github.com/reactjs/react-redux/releases

**Comment by erikras** [comment]
`^5.0.0-beta` doesn't match `5.0.0`?

**Comment by ArcanisCz** [comment]
probably sufficient, didnt notice its already in place in master, nice work!
