### ISSUE TITLE
[v6.3.0] Trying to understand why async validation is not included in Field Level Validation

### ISSUE THREAD

**Issue by adrianbon** [erikras/redux-form#2280]
Any ideas why async validation is not included in the field level validation, since there is now another major inconsistency in the library when it comes to validation. 

Would appreciate a reply @erikras, as I am slowly starting to loose any confidence in this library.

**Comment by cdaringe** [comment]
@adrianbon, i cordially recommend you [give this a read](https://medium.com/@thejameskyle/dear-javascript-7e14ffcae36c#.12vjhp546).

with that said, there are a lot of open issues.  perhaps the lead maintainer could open the doors to a core dev team and working group.

**Comment by diegohaz** [comment]
Being a maintainer of a huge project like this is hard. The amazing thing on open source projects, though, is that you can be the guy that actively contributes to increase the project's quality. If Field level async validation is a common need and it isn't implemented yet, there's an opportunity for you to **create** that confidence.

**Comment by adrianbon** [comment]
@diegohaz and @cdaringe you totally have a point and that is why I have decided to coding my own version of redux form
