### ISSUE TITLE
[Question] How can I check if form was submitted inside my custom input component?

### ISSUE THREAD

**Issue by alexeybondarenko** [erikras/redux-form#2281]
I need display error message only if an input is dirty and not focused, or if a form was submitted.

I've tried to use `_reduxForm` context, but It doesn't update.

```
const Component = ({ component = Input, input, meta, children, ...props }, { _reduxForm }) => (
    React.createElement(component, {
      value: input.value,
      onChange: input.onChange,
      onBlur: input.onBlur,
      onFocus: input.onFocus,
      active: meta.active,
      error: (_reduxForm.submitFailed || (meta.dirty && !meta.active)) && meta.error,
      ...props,
    }, children)
  );
```

**Comment by gustavohenke** [comment]
> I've tried to use _reduxForm context, but It doesn't update.

Don't do that. This is undocumented, so you should not rely on it. See [Libary internals do not exist](https://medium.com/@fagnerbrack/library-internals-do-not-exist-1ff50a30e3b0).

Anyway, `meta.submitFailed` was added by #2346. This very likely will solve your problem.
