### ISSUE TITLE
integrating react-bootstrap with redux form

### ISSUE THREAD

**Issue by jaybe78** [erikras/redux-form#2282]
Hi guys,

I'm currently evaluating redux form. I've seen that's possible to integrate redux form with material ui and react-widgets. Is it as easy with react-bootstrap ?

Also I can see 500 tickets open, is redux form a good choice to use in production environement ? is that stable enough ?

Thanks

**Comment by cdaringe** [comment]
yes, you can do it.  the docs already sufficiently explain how redux-form is agnostic to _whatever_ components you want to use. 

here's an example that i've done w/ it: https://github.com/MRN-Code/coinstac/blob/master/packages/coinstac-ui/app/render/components/form-signup.js#L29

**Comment by jaybe78** [comment]
I don't think your solution would still work if I want to use let's say a react bootstrap dropdown or any other widget from an external library !? The documentation uses property component to do so

**Comment by MeterSoft** [comment]
are also interested in this issue, I do not understand how to use the react-bootstrap with redux-form

this is not working
<FormGroup controlId="formTitle">
          <Col componentClass={ControlLabel} sm={2}>
            Title
          </Col>
          <Col sm={10}>
            <Field name="firstName" component="input" type="text"/>
          </Col>
        </FormGroup>

**Comment by gustavohenke** [comment]
@jaybe78 @MeterSoft 
A good way to use React Bootstrap components is by creating a component yourself.
Here's an example of what I do in my own project, encapsulating almost all features of the Bootstrap forms:

```js
class Input extends Component {
    render () {
        const {
            feedbackIcon,
            input,
            label,
            type,
            meta: { error, warning, touched },
            ...props
        } = this.props;

        let message;
        const validationState = touched && ( error && "error" ) || ( warning && "warning" ) || null;

        if ( touched && ( error || warning ) ) {
            message = <span className="help-block">{ error || warning }</span>;
        }

        return (
            <FormGroup validationState={ validationState }>
                <ControlLabel>{ label }</ControlLabel>
                <FormControl { ...input }
                             type={ type }
                             { ...props } />
                { feedbackIcon ? <FormControl.Feedback>{ feedbackIcon }</FormControl.Feedback> : null }
                { message }
            </FormGroup>
        );
    }
}
```

Perhaps adding an example to the docs would be a good idea.

---

> I can see 500 tickets open, is redux form a good choice to use in production environement ? is that stable enough ?

Yes, it's very stable, most of these issues here are questions asked at the wrong place that @erikras can't handle on its own.
Questions are better suited for StackOverflow. GitHub issues are for tracking enhancements and bugs mainly.

**Comment by jaybe78** [comment]
Thanks a lot for your post, I'm going to test that.
Cheers

**Comment by jaybe78** [comment]
That generic component does not work for select and textarea
It should be componentClass instead of type.

**Comment by MeterSoft** [comment]
`<Field name="category_id" component={Input} label="Category" componentClass="select">`

**Comment by gustavohenke** [comment]
@jaybe78 feel free to adapt the code however you want.
@MeterSoft gave an idea in the previous comment.

**Comment by vasek123** [comment]
Hello @gustavohenke, I am trying to implement your example into my app, but every time I want to change the text field value by writing something into it, all of the fields get unregistered.

My component looks like this:
```javascript
class FormTextInput extends Component {
  render() {
    const { column, input, ...props } = this.props;
    return (
      <FormGroup>
        <ControlLabel>{column.label}</ControlLabel>
        <FormControl type="text" { ...input } />
      </FormGroup>
    )
  }
}
```

and this is how I intend to use it

```javascript
import FormTextInput from './FormTextInput';
import { Field } from 'redux-form';

columns.map((column) => (
  <Field name={column.key} component={FormTextInput} />
))
```

Am I doing something wrong? Thanks for your help.

**Comment by vasek123** [comment]
@gustavohenke I was able to get this working, I think it was a problem with the key generated using shortid, I removed it and now it seems to be working.

**Comment by gustavohenke** [comment]
Yes, this is possibly the reason @vasek123. #2564 reported it.
