### ISSUE TITLE
Render Fieldarray Redux-form values without LOOSING FOCUS of the TextField making it usable?

### ISSUE THREAD

**Issue by Anounemous** [erikras/redux-form#2286]
http://redux-form.com/6.0.0-alpha.7/examples/fieldArrays/
Is there a way in React js to get the Redux-form values having a Field array without LOOSING FOCUS of the TextField making it usable for just rendering the values? eg - http://redux-form.com/6.0.0-alpha.7/examples/fieldArrays/ In the above eg the member textfields of the field array LOOSE focus while getting changed, is there a way to update formvalues without LOOSING the focus??

**Comment by alirezavalizade** [comment]
can you show me your code ?

**Comment by danielrob** [comment]
Closing due to non response.

**Comment by Anounemous** [comment]
it was not an issue with the redux-form hence did not shared anything,
really appreciate you guys responding (y)
