### ISSUE TITLE
Invariant Violation: Could not find "store"

### ISSUE THREAD

**Issue by JoaoCnh** [erikras/redux-form#229]
Hey I'm relatively new to all of this React and Redux and I wanted to try this out.

I followed the docs and when I try to go to the form this error appears:

Invariant Violation: Could not find "store" in either the context or props of "Connect(ReduxForm(MyComponent))". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(ReduxForm(MyComponent))".

I don't know what I'm doing wrong since I'm basically following the docs

**Comment by erikras** [comment]
You need to go look at the `react-redux` docs and make sure that your components are wrapped in `<Provider>`.
