### ISSUE TITLE
no access to required state, even with `reduxForm(...)` + `connect(...)` wrapping

### ISSUE THREAD

**Issue by cdaringe** [erikras/redux-form#2299]
# problem statement

- cannot access field `syncErrors` or `values` in same component that is `reduxForm` wrapped.

# context

- i need field values & sync errors in the `reduxForm` wrapped component
  - field values are _not_ provided to this component by default.  it would be **great** to make this an option pass all of that state through. `<Field>`'s instead are tied to the store, and the root connected component just gets _some_ state.
- there is a guide on how to get access to _other state_, [here, `selectingFormValues`](http://redux-form.com/6.3.1/examples/selectingFormValues/).  this, however, **does _not_ work with generic selectors.**
  - this is easily demonstrable by modifying the examples `connect(...)` call, and by adding some validation to a field.  for example:

```js
// update connect call in example
SelectingFormValuesForm = connect(
  state => {
    return {
      syncErrors: getFormSyncErrors('selectingFormValues')(state)
    }
  }
)(SelectingFormValuesForm)
```

```jsx
// update last name field with some validation
<Field name="lastName" component={renderField} type="text"
  placeholder="Last Name" required validate={[v => v ? null : 'required']} />
```

sure enough, **syncErrors** never show up in `props` passed to the component :(

**Comment by cdaringe** [comment]
here's some additional information. it is evident that `reduxForm` is **stripping** valueable keys.

get this.  suppose i have TWO components: `Parent` and `Child`

suppose that we `reduxForm({ form: 'blah' })(Child)`

now, if we `connect( ... getSyncErrors ...)(Parent)`, then have something like

```jsx
// Parent.js
render () {
  const { syncErrors } = this.props
  console.log(syncErrors) // <== is an object! is defined!
  return <Child syncErrors={syncErrors} />
}
```

```jsx
// Child.js
render () {
  const { syncErrors } = this.props
  console.log(syncErrors) // <== is `undefined`
  return <Form > { ... } </Form>
}
```

it's evident that `reduxForm` is preventing me access to those keys.  if, in my example above, change `syncErrors` to `errorz` or something, the props get passed per expectation.

💣

**Comment by cdaringe** [comment]
released [reduxify-form](https://www.npmjs.com/package/reduxify-form) as a helper to get me what i need for now!  if i return those values i want under a nested key, it all works.  this little package makes the dual connecting a single call, and provides some nice default state data that I always need in my app!

**Comment by huan086** [comment]
Name collision is a problem with Higher Order Component in general. I think what's needed is to document the list of props names that must not be used on reduxForm, Field, Fields and FieldArray.

From initial looks, your library is connecting the whole form state and that isn't a good idea. The move to v6 is to connect as little as possible, so that state changes will cause minimum amount of re-renders. This avoided the performance issue with large form as seen in v5.

If you need to display errors, connect just the component that displays errors, NOT the whole form. Alternatively, what I do is to have a Fields specifying all the names which I want to display errors for. I get the errors from meta prop.

**Comment by cdaringe** [comment]
> Name collision is a problem ... in general. ... what's needed is to document ... that must not be used on reduxForm

interesting.  good to know.

>  your library is connecting the whole form state and that isn't a good idea

not all of it, _just_ values and errors for _just_ the specified form.  [ref](https://github.com/cdaringe/reduxify-form/blob/master/src/index.js#L10)

> ... get the errors from meta prop

`meta` is undefined even when my form has fields with `syncErrors`.  using `<Fields .../>` could work for some circumstances, but in fact i need info on my `syncErrors` to tag my `<root>` component.

thank for your input! i still think the issue stands, however.  at the least the API could use some massaging to get what I need.  double `connect`ing (well ...counting `reduxForm` as one `connect`), seems like it could be dropped down to one, and adjusting property names could be eliminated entirely.

**Comment by danielrob** [comment]
@cdaringe I'm not sure how many selectors were available when you raised this issue, but would it be safe to say this entirely possible now based on the available [selectors](http://redux-form.com/7.0.3/docs/api/Selectors.md/)?

**Comment by cdaringe** [comment]
it would seem likely so!  i'll close this in hopes that _that_ 7.x resolves it, and open back up later as needed.  thx

**Comment by abdul-kowy** [comment]
7.x didn't resolved it.

**Comment by adamjarling** [comment]
If this helps anyone, here is a strategy that seems to work for me.  Since I was unable to make `getFormSyncErrors('timespan')(state)` work directly in my Redux form itself, I hooked this selector up to the parent, container component, where it works properly.  Then just pass the `syncErrors` down as a prop.   

Using this version of Redux-Form:  https://redux-form.com/7.0.3/docs/api/selectors.md/

```
import React, { Component } from 'react';
import TimespanForm from '../components/TimespanForm';
...
import { getFormSyncErrors } from 'redux-form';

class TimespanFormContainer extends Component {
 ...
  render() {
    return (
        <TimespanForm onSubmit={this.submit} mySyncErrors={this.props.syncErrors} />
    );
  }
}

const mapStateToProps = state => ({
  syncErrors: getFormSyncErrors('timespan')(state)
});

export default connect(
  mapStateToProps,
)(TimespanFormContainer);

```
