### ISSUE TITLE
Submit two forms in order

### ISSUE THREAD

**Issue by jgautheron** [erikras/redux-form#2302]
I have two forms that I validate from a parent container, each form is posting data in an API `onSubmit`. I need them to be posted in order.

I would like to be able to do something like that:

```javascript
dispatch(submit('billing'))
  .then(() => dispatch(submit('payment'))
    .then(() => console.log('All good!'))
  )
```

Any other way I could do the same?
Thanks.

**Comment by gustavohenke** [comment]
You could submit the `payment` form using `onSubmitSuccess` of the `billing` form.

**Comment by gustavohenke** [comment]
ping
