### ISSUE TITLE
Validate gets wrong arguments with FieldArray (6.3.2)

### ISSUE THREAD

**Issue by rubengrill** [erikras/redux-form#2311]
We noticed that at some point (not always) we got wrong values into the validator function.
The signature is `validate(values, props)`, but it seems that with a FieldArray we get `validate(currentValueOfArray, values)` (props are missing then).

This is part of the call stack:
- reduxForm.componentWillReceiveProps (https://github.com/erikras/redux-form/blob/v6.3.2/src/reduxForm.js#L237)
- reduxForm.validateIfNeeded (https://github.com/erikras/redux-form/blob/v6.3.2/src/reduxForm.js#L180)
- generateValidator.generateValidator (https://github.com/erikras/redux-form/blob/v6.3.2/src/generateValidator.js#L19)
- generateValidator.getErrors (https://github.com/erikras/redux-form/blob/v6.3.2/src/generateValidator.js#L7)
- FieldArray.wrapError (https://github.com/erikras/redux-form/blob/v6.3.2/src/FieldArray.js#L8)
- Our validator function

This currently breaks our app after migrating from 6.2.0 to 6.3.2 (We need the new `FieldArray.get()`, so the upgrade is important).

**Comment by erikras** [comment]
Wow! Fantastic reporting, @rubengrill!

**Comment by erikras** [comment]
The signature for field-level validation is `validate(value, allValues)` for both [`Field`](http://redux-form.com/6.4.3/docs/api/Field.md/#-validate-value-allvalues-error-optional-) and [`FieldArray`](http://redux-form.com/6.4.3/docs/api/FieldArray.md/#-validate-value-allvalues-error-optional-). You were looking at the [`validate`](-validate-values-object-props-object-errors-object-optional-) config parameter for the whole form.

**Comment by callihiggins** [comment]
I'm currently experience this same issue, where my form level validation function is called twice- once with the arguments of `values, props` and then a second time with `values, value, props`. I'm sure this is specific to my environment and not a bug, I'm just wondering if you can explain the answer above in more detail?
