### ISSUE TITLE
Please add support for button with name and value.

### ISSUE THREAD

**Issue by 0rangeT1ger** [erikras/redux-form#2314]
Tried this in a Field but didn't work.
```
<button type='submit' name='action' value='save' />
```

Now I'm using 
```
let action_ = 'save'
.
.
.
<button
  onClick={() => {
    action_ = 'submit'
    handleSubmit()
  }}
>submit</button>
.
.
.
connect(_, {
  onSubmit: (form, dispatch) => handlePostInfo({...form, action: action_}, dispatch),
})(SomeForm)
```

**Comment by gustavohenke** [comment]
In the first example, what exactly is the expected behavior?

**Comment by 0rangeT1ger** [comment]
Suppose we have two submit button, one for remote save, one for actual submit.
Both submit actions use one URL and backend distinguish them by a field named 'action'.
If you click the button above in my example, the form submit data with a field named 'action' and its value is 'save'.

**Comment by 0rangeT1ger** [comment]
If you try that in a html form, you'll know the use of a button's name and value.

**Comment by erikras** [comment]
Does [this answer](http://stackoverflow.com/a/37173842/103690) help?

**Comment by 0rangeT1ger** [comment]
But wouldn't be better if redux-form support button with name and value?
It will look better and more clean.

**Comment by gustavohenke** [comment]
Duplicate of #3622
