### ISSUE TITLE
IntialValues are not cleared when we reused the same redux-form component .

### ISSUE THREAD

**Issue by bairisuresh** [erikras/redux-form#2318]
Hi @erikras ,
I have requirement like,
i have to load the Redux- form when i click on the list, i am doing this
`<FormComponent initialValues={mydata} />` i am using this same form on each list click and passing the mydata object (this will change based on the list clicked).
i am able to load the initialValues into the redux-form for the first list click only.
2nd,3rd........ i am unable to load the data as per the list click becoz the intialValues data will be there(unable to reset/unable to remove)
suggest me how would i achieve my requirement.

Thanks
suresh

**Comment by gustavohenke** [comment]
It's very likely that your form isn't unmounted as you click in the 2nd item, 3rd item, and so on.

You could try using `enableReinitialize` option when using the [`reduxForm` HOC](http://redux-form.com/6.3.1/docs/api/ReduxForm.md/).
This way, whenever `initialValues` change, the form is reinitialized 😮, and you'll see the changes.

**Comment by bairisuresh** [comment]
@gustavohenke ,
Thank you for your quick replay...
it worked like a charm :)

**Comment by gustavohenke** [comment]
Awesome!
We'll close here.
