### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by tomasztomys** [erikras/redux-form#2322]
Could you make new release to npm? I want to have new changes about error if enableReinitialization is true.

**Comment by iyn** [comment]
@tomasztomys you can always install the package directly from github (master, specific branch, even specific commit).

more info:
https://stackoverflow.com/questions/17509669/how-to-install-nodejs-package-from-github-directly
https://docs.npmjs.com/cli/install

**Comment by tomasztomys** [comment]
But version in package.json is still 6.3.2 so npm thinks that it's the same with local version

**Comment by gustavohenke** [comment]
@tomasztomys installing things from GitHub will work even though the `version` key in `package.json` didn't change.

**Comment by swp44744** [comment]
Does anyone know how `arrayRemoveAll(form:String, field:String)` works? I tried but not able to remove fieldarray. any help is appreciated

**Comment by erikras** [comment]
Let's just say you'll get what you want for Christmas. 🎅

**Comment by swp44744** [comment]
a new release of redux form ;)

**Comment by erikras** [comment]
Look kids!! Santa came!!! [`v6.4.0`](https://github.com/erikras/redux-form/releases/tag/v6.4.0)

**Comment by ruanyl** [comment]
@erikras Hi, is there any kind of release 'schedule' ? For example, a planned release every other Friday. So that we know when we will get the fixes & features. I don't know if this will work in reality.
