### ISSUE TITLE
How to tackle logic between fields

### ISSUE THREAD

**Issue by rszczypka** [erikras/redux-form#2327]
I think it's not a very unusual thing I'm trying to do but I couldn't find a solution.

I have 2 select fields:
Status: with options: In Process, Rejected, Accepted
Reason: the options here depend on the option selected in Status
if Status is In Process then Reason field is disabled and it's value reset
if Status is Rejected then Reason gets rejected options 'Lack of funds', 'Other issues'
if Status is Accepted then Reason gets  accepted options 'Done according to spec', 'Accepted by manager'

The code below isn't working but it might give an idea of what I currently have. I guess I need to prepare the options for reason depending on the status.
I also need to somehow cancel the value of the reason when status changes.

How do you approach dependencies like that?

```
    let wrriReasonOptions = <MenuItem value={null} primaryText=""/>

    if (status === 3) {
      wrriReasonOptions = wrriAccepted && wrriAccepted.map((row, index) => (
          <MenuItem key={index} value={row.id} primaryText={row.reason}/>
        ));
    }
    else if (status === 2) {
      wrriReasonOptions = wrriRejected && wrriRejected.map((row, index) => (
          <MenuItem key={index} value={row.id} primaryText={row.reason}/>
        ));
    }

          <Field
            name="wrriUsage.wrriStatus.id"
            component={SelectField}
            floatingLabelText='Status'
            fullWidth={true}
          >
            {statuses && statuses .map((row, index) => (
              <MenuItem key={index} value={row.id} primaryText={row.name}/>
            ))}
          </Field>
          <Field
            required
            name="wrriUsage.wrriReason.id"
            component={SelectField}
            fullWidth={true}
            floatingLabelText='Reason'
          >
            {reasonOptions}
         </Field>
```

**Comment by dtipson** [comment]
Complicated mixed state outcomes/calculations can go into reducer.plugin, which would allow you to sort out the proper state to translate the original values into.

**Comment by rszczypka** [comment]
Thanks @dtipson,
in the end I got it working with this approach: https://github.com/erikras/redux-form/issues/1500#issuecomment-238624882

**Comment by gustavohenke** [comment]
`Fields` is also a good place to do this.

```js
const renderFields = ({ status, reason }) => {
  const inProcess = status.input.value === "in process";
  // TODO build options according to status.input.value
  const options = [];

  return (
    <SelectField { ...status } />
    <SelectField
      { ...reason }
      input={{ ...reason.input, value: inProcess ? null : reason.input.value }}
      options={ options }
      disabled={ inProcess } />
  );
};

<Fields names={[ 'status', 'reason' ]} component={renderFields} />
```

I hope this helps you, @rszczypka!
