### ISSUE TITLE
Specifying initialValues causes onChange events to not fire

### ISSUE THREAD

**Issue by HorizonXP** [erikras/redux-form#233]
This is with version 3.0.1 which was just released.

If I specify an object array with initial values for my fields, either via properties or the new mapStateToProps, none of the expected state changes occur when I type into my form. This means that no change/blur/focus events fire, no synchronous validation occurs, and the submitted values when handleSubmit is called are the initial values, not what's currently entered in the form. 

I'm still investigating the redux-form code to see where the issue might be, or where I may have gone wrong, but this was working yesterday with the 3.0.0 beta, so it may be a bug.

**Comment by erikras** [comment]
Hmm... [The example](http://erikras.github.io/redux-form/#/examples/initializing-from-state) is working fine.

**Comment by HorizonXP** [comment]
Yup, I know, so I'm trying to figure out what I'm doing wrong. Here's what I've written:

```javascript
@reduxForm({
  form: 'profileEditor',
  fields,
  validate
},
state => ({
  initialValues: state.user.get("user")
}),
{ updateUserProfile } // mapDispatchToProps
)
class ProfileEditor extends React.Component {
...
```

Where `state.user` is a Immutable-JS Map, hence why I'm calling `.get("user")` on it to get the `user` object.

**Comment by erikras** [comment]
It's doing a "deep equal" check on the `initialValues` prop, so if ImmutableJS is giving you a unique version every time you call `get("user")`, that could be a problem. Is what you're getting a json object, or some immutablejs map?

**Comment by HorizonXP** [comment]
`get("user")` returns a JSON object with fields `first_name`, `last_name`, `email`, all of which correspond to the form's field names. 

I've somewhat identified the issue. It looks like it has to do with how I'm handling server-side rendering. 

If I login and navigate through my app to the form, everything works as expected, with all of the events/validation firing. Great!

However, if I enter the URL for the form into my browser, it goes to the server and requests the rendered version. This mostly works fine, except the `redux-form/INITIALIZE` action is fired after the `@@reduxReactRouter/routerDidChange` event, so the initial state sent down with the rendered HTML doesn't match what React expects, so React throws an Invariant violation about the checksum being invalid between the server and client versions of the document. 

It is here that form doesn't work as expected.

I think I have to figure out how to get the server-side to wait for all actions to complete before this can be solved.

**Comment by erikras** [comment]
Yep. Sounds like you're on top of it, and that it's not really a redux-form bug.

**Comment by HorizonXP** [comment]
Agreed.
