### ISSUE TITLE
Please upgrade peerDependencies to latest react & redux 

### ISSUE THREAD

**Issue by jasongonzales23** [erikras/redux-form#2330]
redux-form is literally the only thing keeping me from 15.4.1 and 3.6.0

also why the strict lock on the peer dep, when your internal dep allows dot upgrades?

**Comment by gustavohenke** [comment]
Commit that introduced this: c790172c56ba308f09724fa62947fe1dff9c16f8

**Comment by gustavohenke** [comment]
Fix submitted in #2331.

**Comment by erikras** [comment]
Published fix in [`v6.4.1`](https://github.com/erikras/redux-form/releases/tag/v6.4.1).

**Comment by jasongonzales23** [comment]
Thanks for the fast fix @erikras ! Merry Christmas and Happy New Year to you!
