### ISSUE TITLE
Prop type fails with the prop `name` in Field component

### ISSUE THREAD

**Issue by Grmiade** [erikras/redux-form#2332]
I have this error with the last version `6.4.0`. With `6.3.2` version, this warning doesn't appear.
<img width="581" alt="capture d ecran 2016-12-24 a 11 27 00" src="https://cloud.githubusercontent.com/assets/11244106/21466435/faea3b70-c9cb-11e6-9d3c-f94bcbcc6b6d.png">

My form:
```
<Form onSubmit={handleSubmit(this._createUser)}>
  <Form.Group widths="equal">
    <Img src={pictureUrl} alt="" onError={this._handleImageError} />
    <Field name="picture" label="Picture" component={SemanticField} />
  </Form.Group>
  <Field name="username" label="Username" component={SemanticField} />
  <Button type="submit" fluid>Sign up</Button>
</Form>
```

**Comment by alvelig** [comment]
As far as I see, it was moved to input. :/

**Comment by Grmiade** [comment]
Fixed! My bad :/
My code before fix:
```
const Field = ({ input, label, meta: { touched, error }, name, ...rest }) => (
  <Form.Field>
    {label && <label htmlFor={name}>{label}</label>}
    <Input {...input} {...rest} name={name} error={touched && error} />
  </Form.Field>
)
```

After fix: 
```
const Field = ({ input, label, meta: { touched, error }, ...rest }) => (
  <Form.Field>
    {label && <label htmlFor={input.name}>{label}</label>}
    <Input {...input} {...rest} error={touched && error} />
  </Form.Field>
)
```

**Comment by likerRr** [comment]
Also faced this issue. Very strange that there are no mentions in changelog about this, but in fact it's a breaking change @erikras

**Comment by erikras** [comment]
It was a breaking change to something that was undocumented. It was never part of the API contract.

As stated above, the name can be found under `input.name`.

**Comment by likerRr** [comment]
Probably I agree with you. It wasn't documented anywhere.
