### ISSUE TITLE
Failed prop type: Invalid prop `form` of type `object` supplied to `Form(App)`, expected `string`

### ISSUE THREAD

**Issue by gyarasu** [erikras/redux-form#2333]
I have the following form:
It's almost same as Simple Form.
```
import React from 'react'
import { Field, reduxForm } from 'redux-form'

const App = (props) => {
  const { handleSubmit, pristine, reset, submitting } = props
  return (
    <form onSubmit={handleSubmit}>
      <div>
        <label>First Name</label>
        <div>
          <Field name="firstName" component="input" type="text" placeholder="First Name"/>
        </div>
      </div>
      <div>
        <label>Last Name</label>
        <div>
          <Field name="lastName" component="input" type="text" placeholder="Last Name"/>
        </div>
      </div>
      <div>
        <label>Email</label>
        <div>
          <Field name="email" component="input" type="email" placeholder="Email"/>
        </div>
      </div>
      <div>
        <label>Sex</label>
        <div>
          <label><Field name="sex" component="input" type="radio" value="male"/> Male</label>
          <label><Field name="sex" component="input" type="radio" value="female"/> Female</label>
        </div>
      </div>
      <div>
        <label>Favorite Color</label>
        <div>
          <Field name="favoriteColor" component="select">
            <option></option>
            <option value="ff0000">Red</option>
            <option value="00ff00">Green</option>
            <option value="0000ff">Blue</option>
          </Field>
        </div>
      </div>
      <div>
        <label htmlFor="employed">Employed</label>
        <div>
          <Field name="employed" id="employed" component="input" type="checkbox"/>
        </div>
      </div>
      <div>
        <label>Notes</label>
        <div>
          <Field name="notes" component="textarea"/>
        </div>
      </div>
      <div>
        <button type="submit" disabled={pristine || submitting}>Submit</button>
        <button type="button" disabled={pristine || submitting} onClick={reset}>Clear Values</button>
      </div>
    </form>
  )
}

export default reduxForm({
  form: 'app'  // a unique identifier for this form
})(App)
```

I get the following error: 
```
warning.js:36Warning: Failed prop type: Invalid prop `form` of type `object` supplied to `Form(App)`, expected `string`.
    in Form(App) (created by Connect(Form(App)))
    in Connect(Form(App)) (created by ReduxForm)
    in ReduxForm (created by Connect(ReduxForm))
    in Connect(ReduxForm) (at index.js:12)
    in Provider (at index.js:11)
```

I checked the prop of the Connect(Form(App)).
![2016-12-25 12 04 56](https://cloud.githubusercontent.com/assets/4948588/21469552/6ebfbc40-ca9a-11e6-9bf0-e9892f95ae59.png)

Why is the prop 'form' recognized as Object (not string)?
And I want to know how to solve this problem.

**Comment by erikras** [comment]
I don't see anything wrong with the code you've shared. So the problem must be elsewhere. Like how you are setting up the reducer or in the `render()` method of the container of this component.

**Comment by chanan** [comment]
@gyarasu Did you solve this issue? Running into the same problem.

**Comment by chanan** [comment]
Never mind, found the answer :) in my case one of my props was also named "form", renamed it to something else.

**Comment by honpery** [comment]
@chanan  thanks, change reducer's name, not named 'form', is fixed!

**Comment by honpery** [comment]
if using follow code, remove {...this.props}
```
<AppForm {...this.props}></AppForm>
```

**Comment by gyarasu** [comment]
Thanks, I'll try it later:)

**Comment by OksanaKovalchuk** [comment]
same issue was in such case:
====in component====
class NewBuilding extends React.Component {
....
}

NewBuilding = reduxForm({
  form: 'building',
})(NewBuilding);

const mapStateToProps = ({ building, form }) => ({
  building,
  form,
});
====

=====
form reducer was exported such way:
import { reducer as form } from 'redux-form';
=======

fixed part:
=====
const mapStateToProps = ({ building, form }) => ({
  building,
  formReducer: form,
});

=====

**Comment by gustavohenke** [comment]
Since folks are finding their way around this issue, I will close it.
Feel free to keep the discussion going.

**Comment by fbownz** [comment]
I had the same issue.

I found a way around it by using a different property name other than 'form' on mapStatetoProps
```
const mapStateToProps = state => {
	return {
		neworderdata: state.neworderdata,
		default_paper_type: state.prospect.prospect_paper_type,
		page: state.neworder_page,
		ordercost: state.ordercost,
		auth: state.auth,
		top_writers: state.topwriters,
		neworder: state.neworder
		// form: state.form 
               //Changed this to a different name from form and it worked
	};
};
```

**Comment by aeciolevy** [comment]
Just to contribute.

I had the same problem because one of my fields had the same name as the form.

```js
export default reduxForm({
   form: 'example',
  initialValues: { example: 'Testing'},
})
```

**Comment by zilan830** [comment]
I met this issue also. I make another component wrapper form in the end , then it works.
example:
form.js
`class TestForm extends Component{...}
TestForm = reduxForm({ form: 'test', validate, initialValues })(TestForm)
export default TestForm;
`
connect.js
`class Connect extends Component{...}
const mapStateToProps = state => {
  console.log("getState", state);
  return state
};
export default connect(mapStateToProps)(Connect);
`

**Comment by javascriptHustler** [comment]
Renaming didn't work for me, but the following did
`js
const mapStateToProps = function(state) {
    delete state.form; // hack
    return state
};
`

**Comment by sashberd** [comment]
For those who use next.js and redux form
I have create.js in pages folder that called component with redux form
`<Component {...props}/>`
In some cases you props could hold form property as object `form:{}`
And redux form will use this passed prop from next.js
So just do not pass all props to you redux from component, pass only what you need. (Took me hakf a day to recognise it) :(
