### ISSUE TITLE
Dynamic forms documentation - fields object

### ISSUE THREAD

**Issue by mattkrick** [erikras/redux-form#234]
In the container component, I see: 
```
fields={Object
            .keys(this.state)
            .reduce((accumulator, field) =>
              this.state[field] ? accumulator.concat(field) : accumulator, [])
```
this should return an array, right?

But in the `DynamicForm` I see: `fields: PropTypes.object.isRequired`
and `Object.keys(fields).map(name => {...`
It should suffice to just pass fields, right?

PS I can't believe how fast you got these modules up, this package is amazing!

**Comment by erikras** [comment]
Excellent point of confusion you've just discovered! Might be worth putting into the FAQ.

[The `fields` prop that you pass into your decorated component](http://erikras.github.io/redux-form/#/api/reduxForm) is an array, but [the `fields` prop that the redux-form HOC passes into your wrapped component](http://erikras.github.io/redux-form/#/api/props) is an object.

Make sense? It's an unfortunate naming collision, for sure.

**Comment by mattkrick** [comment]
OK I'm still confused then, if my HOC looks like this `reduxForm({ form: 'dynamic'})(EditableContainer);` where is it getting the fields prop from?

**Comment by erikras** [comment]
The container is giving the fields array.
```js
<DynamicForm
  onSubmit={this.props.onSubmit}
  fields={Object  // <------- yes, this is an array
    .keys(this.state)
    .reduce((accumulator, field) =>
      this.state[field] ? accumulator.concat(field) : accumulator, [])}/>
```

**Comment by mattkrick** [comment]
I'm with you so far, where I get lost is the HOC for `DynamicForm`, since the object I'm passing to `reduxForm` doesn't have a fields property & it throws a warning that it's missing.

**Comment by erikras** [comment]
If you look at the React devtools for the example, you'll see this.

![redux form 2015-11-05 21-00-26](https://cloud.githubusercontent.com/assets/4396759/10980097/7cf6cf92-8400-11e5-9aa3-c973d60051b2.jpg)

Does that help?

**Comment by mattkrick** [comment]
Yep! Thanks for sticking with me. Fault was all at my end, was trying to do a multirecord-dynamic form and goofed up. Nice API, It's really helpful that I can also pass in a dynamic `form` field :+1:

**Comment by erikras** [comment]
[This](http://erikras.github.io/redux-form/#/api/reduxForm) wasn't clear enough?
> IMPORTANT: All of these configuration options may be passed into reduxForm() at "design time" or passed in as props to your component at runtime.

How would you document it?

Glad you got your problem resolved. Happy coding!

**Comment by mattkrick** [comment]
OH. Well that shut me up :-). I was looking for something on the example,
but that makes it plenty clear.
