### ISSUE TITLE
Not able to initialise the values in forms????

### ISSUE THREAD

**Issue by ExtremeRights** [erikras/redux-form#2341]

**Comment by gustavohenke** [comment]
What is your issue?

**Comment by theturboboy** [comment]
I think I have the same issue at version 6.4.1
`
<Field
  name="test"
  component={MyComponent}
  value="test"
/>
`
in MyComponent in props the initial value `this.props.input.value` is empty string

**Comment by theturboboy** [comment]
@gustavohenke so ok, I pass it with `initialValues` and use it in `MyComponent`. But on validation, or submit, there are no my values, till I call `onChange` there. Did I miss something?

I have similar issue with `redux-form-material-ui`, how can I pass current value to `SelectField` for instance?

**Comment by kolpav** [comment]
@theturboboy Take a look [here](http://redux-form.com/6.4.1/examples/initializeFromState/) you need to use `connect` you can't just do `<Field component={MyComponent} initialValues='foo' />` which I assume you are doing now.

**Comment by erikras** [comment]
> was this feature ever supported? eg doing `<Field value="bla" />`?

No, that has never been a feature.
