### ISSUE TITLE
access redux store within asyncValidate

### ISSUE THREAD

**Issue by stevenmusumeche** [erikras/redux-form#2345]
Is it possible to access the redux store within asyncValidate or have some other data passed as parameters into it?

**Comment by gustavohenke** [comment]
According [to the docs](http://redux-form.com/6.4.1/docs/api/ReduxForm.md/), the `asyncValidate` accepts a `props` argument.
So you can use `connect` from react-redux, eg

```js
let MyForm = () => { ... };
MyForm = connect( state => ({
  someValue: state.someValue
}))( MyForm );
MyForm = reduxForm({
  form: "formName",
  asyncValidate ( values, dispatch, props ) {
    console.log( props.someValue );
    return doSomethingAsync();
  }
})( MyForm );
```

**Comment by stevenmusumeche** [comment]
Thank you @gustavohenke! I had no idea I could pass asyncValidate as a prop from the container vs at "design time".
