### ISSUE TITLE
Unable to add default element in FieldArray

### ISSUE THREAD

**Issue by satyaki20** [erikras/redux-form#2349]
Hi,

I am unable to add an default element to fieledArray. I am using a dumb control and trying to add default value to fields pseudo array and always I am getting exception.

**Comment by gustavohenke** [comment]
You need to show some code in order for us to help.

**Comment by swp44744** [comment]
@gustavohenke @satyaki20  I am trying to achieve this by initialize Fields & FieldArray but below behavior I am observing:
1. initial shows the value that I initialized for Fields as well as FieldArray.
2. But values sections shows initialized values of Fields only and FieldArray shows empty array. below is the sample code:

`export default reduxForm ({`
  `form: 'productForm',`
  `enableReinitialize: true,`
  `validate,`
  `initialValues: {`
   ` someField1: 'This is first field',`
   ` someField2: 'This is second field',`
   ` myFieldArray:[{name: 'django'}]`
  `}`
`})(ProductClassName);`

myFieldArray shows empty array[] in values.

**Comment by satyaki20** [comment]
@gustavohenke @swp44744 , Finally I was able to do this by action creators. On the componentdidmout I am calling arrayInsert action and passing all the parameters. But I had to make this call using setTimeout.

**Comment by swp44744** [comment]
@satyaki20, yes I used arrayPush. that works too!!! I guess you can close the topic. :) Cheers

@gustavohenke: sorry for bothering you buddy ;)

**Comment by ziogaschr** [comment]
I have the same issue. @swp44744, I am happy that there is a workaround, but I would expect that this issue has to be resolved before closing it. :)

**Comment by ziogaschr** [comment]
Works fine after I add `enableReinitialize: true`, my mistake, as the form resides already in a hidden modal.

**Comment by satyaki20** [comment]
Closing this as we have a workaround :) :+1:  Thanks to every one
