### ISSUE TITLE
Redux form widgets onChange

### ISSUE THREAD

**Issue by bairisuresh** [erikras/redux-form#2351]
Hi ,
I am using redux form widgets in my project. In redux-from site we have onBlur() example.
I want to use OnChange event instead of blur.
Is it possible? if yes Please provide syntax for onChange.
`<Field
          name="hobbies"
          component={Multiselect}
          defaultValue={[]}
          onBlur={() => props.onBlur()}
          data={[ 'Guitar', 'Cycling', 'Hiking' ]}/>`

**Comment by MichalZalecki** [comment]
You can use `change` for that: http://redux-form.com/6.4.3/docs/api/ActionCreators.md/#-change-form-string-field-string-value-any-

**Comment by gustavohenke** [comment]
👆 what @MichalZalecki said
