### ISSUE TITLE
FieldArray fields.get does not reflect redux state

### ISSUE THREAD

**Issue by chris-verclytte** [erikras/redux-form#2355]
I am having trouble with fields API provided by FieldArray.
When I add an element to FieldArray (with fields.push({})) and then set a property (say foo: "bar") in the new element created, redux state is updated but fields.get(1).foo returns undefined.
If I add another element again, fields.get(1) is defined with the property foo: "bar" set but fields.get(2) is undefined.
The problem is the same with getAll API.

**Comment by chris-verclytte** [comment]
After some investigation, it seems that ConnectedFieldArray only calls createFieldArrayProps when a field array is created (see https://github.com/erikras/redux-form/blob/428e9f06b8f6e5deace99eb6ab17b61739cb31d9/src/ConnectedFieldArray.js#L61) 
and then when one of the array object is updated the props are not "refreshed". This cause the get API from fields props to reference to a value that is not in sync with the Redux state.

**Comment by gustavohenke** [comment]
> redux state is updated but fields.get(1).foo returns undefined.

Are you doing both operations sequentially?

Because the [docs on `fields.push()`](http://redux-form.com/6.4.2/docs/api/FieldArray.md/#-fields-push-value-any-function-) state the following:

> This is not a mutator; it dispatches an action which updates the state in Redux, which will cause your component to rerender.

**Comment by chris-verclytte** [comment]
@gustavohenke No I am not, I am calling fields.push({}) on click event and then trying to access to fields.get(1) in the render (that should have fresh props after update).

**Comment by erikras** [comment]
> After some investigation, it seems that ConnectedFieldArray only calls createFieldArrayProps when a field array is created and then when one of the array object is updated the props are not "refreshed". This cause the get API from fields props to reference to a value that is not in sync with the Redux state.

This very well could be a bug. What you state sounds true to me. I will investigate. 🔍

**Comment by erikras** [comment]
Published fix in [`v6.4.3`](https://github.com/erikras/redux-form/releases/tag/v6.4.3).
