### ISSUE TITLE
parse is embedded in Field's custom prop

### ISSUE THREAD

**Issue by chris-verclytte** [erikras/redux-form#2356]
I think there is a regression with field's custom prop. In version 6.4.1, the "parse" property is passed to the wrapped component in custom prop. This causes error when spreading custom prop in, for example, a basic input. 
I just verified with 6.2.1 and parse was not passed into custom.

**Comment by stunaz** [comment]
indeed`(unknown) Warning: Unknown prop `parse` on <input> tag. Remove this prop `

**Comment by erikras** [comment]
Confirmed.

**Comment by erikras** [comment]
Published fix in [`v6.4.3`](https://github.com/erikras/redux-form/releases/tag/v6.4.3).
