### ISSUE TITLE
Initialize form for dynamic fields

### ISSUE THREAD

**Issue by idoo** [erikras/redux-form#2359]
I have form with some field A depends of field B
I put `  componentWillMount() { this.props.load(formData); }` to form component and field B has correct value.

But when I change field B and show field A, this field didn't have default values but I have it in `formData`.

Does somebody had such case? or maybe you know good solution?

**Comment by erikras** [comment]
Make sure the name for A matches the path to its value in the initial values.

In theory, you should be able to initialize many values, and then, at some later time, render the `Field`s and they should have the values that were initialized. It sounds like something might be wrong in your setup.

Feel free to post a more concrete example of your code.

**Comment by idoo** [comment]
@erikras tank you for your help, you are right, I started create a snippet for you and found that I assigned default values for field in wrong place :)

Take this opportunity to say — thank you for your great work and Happy New Year! 🎄
