### ISSUE TITLE
Possible to have errors which are not specifically attached to fields?

### ISSUE THREAD

**Issue by ianks** [erikras/redux-form#236]
When I return a login error, I return a generic error which is not specific to a single field. This is to prevent malicious users from gaining information about my users. Is there currently a way to have errors which are not specific to fields?

**Comment by erikras** [comment]
Yes. There's a special `_error` key, which will end up in `this.props.error` passed to your component. See `error` entry [here](http://erikras.github.io/redux-form/#/api/props).
