### ISSUE TITLE
Set focus in first faulty field

### ISSUE THREAD

**Issue by semy** [erikras/redux-form#2365]
Hi,

is there a way to always set the focus to the first faulty field?

I tried to implement a solution in my render field component:
```
componentDidUpdate() {
    const { meta: { submitting, touched, error } } = this.props;
    const field = this.refs['field' + this.props.name];

    ...

    if (!submitting && touched && error) {
      field.select();
    }
}
```

This works partially, but...

If I enter one char in the first faulty field, the validation is at this moment valid for the field and the next faulty field steals my focus.

How can I prevent this or is there already a built-in solution?

Thanks for your help!

**Comment by Katu360** [comment]
Use [onSubmitFail](http://redux-form.com/6.3.1/docs/api/ReduxForm.md/#-onsubmitfail-function-optional-) at reduxForm decorator.
Take a look at https://github.com/erikras/redux-form/issues/1336, instead of scroll you can use dispatch(focus(form:String, field:String))

**Comment by erikras** [comment]
> Use `onSubmitFail` at reduxForm decorator.

✅  Yes.

> Take a look at #1336, instead of scroll you can use `dispatch(focus(form:String, field:String))`

❌  No.

Dispatching `FOCUS` will not focus your field; it will merely mark it as "active" in `redux-form`. To put it another way, `FOCUS` is what is dispatched automatically from the `onFocus` event handler.

To actually put the cursor in a field, you have to have access to the DOM element itself and call `.focus()` on it. There is no way for `redux-form` to do this for you without making too many assumptions about your component structure.

Using `onSubmitFail` and the `document.querySelectorAll(`[name="${fieldName}"]`)` method proposed in #1336 is probably the most elegant solution.

The next release will give each field access to the `submitFailed` to use in your calculations, which could make your in-field-component strategy more viable. #2346

**Comment by semy** [comment]
Hi @Katu360 and @erikras,

seems to be working. But I will wait until the next release. When can we expect it?

**Comment by semy** [comment]
Hi @erikras,

I see your release, many thanks.

But the meta `submitFailed` do not help me, because after the first try to submit the form I get always `submitFailed: true`, so I have no indicator if somebody press enter or submit the form again.

The `onSubmitFail` event would be perfect, but I can not access the event from the field component. Do you have another idea?

Yes I could handle this by each parent form of a field but I find that quite uncomfortable.

Maybe you have another idea :-)

**Comment by erikras** [comment]
You have both `meta.submitting` and `meta.submitFailed`, so you should be able to tell:

```jsx
componentDidUpdate(prevProps) {
  const submitJustNowFailed = prevProps.submitting && 
                              !this.props.submitting &&
                              this.props.submitFailed
  if (submitJustNowFailed) {
    // do stuff
  }
}
```

**Comment by semy** [comment]
Hey Erikras,

I tested this, but `prevProps.meta.submitting` is always `false` although `this.props.meta.submitting` is sometimes `true`.

Other idea?

Thanks for your help!

**Comment by erikras** [comment]
It must be getting updated twice, so the exact previous props were not with `submitting` `true`. You might have to remember it yourself.
```jsx
if (this.props.meta.submitting && !this.state.submitting) {
  this.setState({ submitting: true })
}
if (this.state.submitting && !this.props.meta.submitting && this.props.meta.submitFailed) {
  this.setState({ submitting: false }) // reset state
  // submit just now failed
}
```
Some combination like that might work. I didn't give it too much thought, but I was just illustrating how you could keep a memory of if you have been submitting _recently_.

**Comment by oampo** [comment]
I've been working on this today and found a solution which I think is a bit more elegant than using `document.querySelectorAll`, and (with limited testing) seems to work well.  In the `onSubmitFail` method I dispatch the `focus` action so the `active` prop of the first failing field is set:

```js
export default reduxForm({
    form: 'contact',
    onSubmitFail: (errors, dispatch) =>
        dispatch(focus('contact', Object.keys(errors)[0]))
})(ContactForm);
```

Then in the component I pass to `Field`, I set the focus on the `<input>` tag in `componentDidUpdate` via a ref:

```js
export default class Input extends React.Component {
    componentDidUpdate(prevProps) {
        if (!prevProps.meta.active && this.props.meta.active) {
            this.input.focus();
        }
    }
    render() {
        let error;
        if (this.props.meta.touched && this.props.meta.error) {
            error = <div className="form-error">{this.props.meta.error}</div>;
        }

        let warning;
        if (this.props.meta.touched && this.props.meta.warning) {
            warning = (
                <div className="form-warning">{this.props.meta.warning}</div>
            );
        }

        return (
            <div className="form-input">
                <label htmlFor={this.props.input.name}>
                    {this.props.label}
                    {error}
                    {warning}
                </label>
                <input
                    {...this.props.input}
                    id={this.props.input.name}
                    type={this.props.type}
                    ref={input => (this.input = input)}
                />
            </div>
        );
    }
}
```
If that looks useful and works for other folks then I can put in a PR with some documentation on how to do this.

**Comment by rluiten** [comment]
Just a note @oampo `object.keys(errors)[0]` will not work for a form that contains an array of other values.

**Comment by AubreyHewes** [comment]
All suggestions (in all corresponding/found issues) for implementing focusing the first field error were failing for me.. then I worked out why.. when using `redux-form/immutable` the `onSubmitFail` `errors` object does not contain the fields in registration order (possibly requires an ordered list reviver when setting/getting fields?).

So I solved it with a pure DOM query:

In `onSubmitFail` Get all the error'ed fields and query them using `querySelector`. This is the most workable as `querySelector` _"Returns the **first Element within the document that matches** the specified selector, or group of selectors."_ .. so even if the selector is not in `registeredField` order.. it still returns the first error'ed field in the document, then just `focus()` it.

Could possibly also `scrollIntoView()` though in my case this failed as the site has a fixed/floating header.

````javascript
onSubmitFail: (errors) => {
  // # Focus on first error

  // When Immutable:
  // The errors are _not_ in `REGISTER_FIELD` order so we cant just "use" the first one..
  // (possibly requires an ordered list reviver when getting errors?)

  // so we try to get the first error element in another way, using a DOM query:

  // Note: You can't query a possible error class in `onSubmitFail` as the `render` may not have yet happened.

  // We do this using a DOM selector of all the fields that have error'ed and use `querySelector` which
  // Returns the first Element within the document that matches the specified selector, or group of selectors.
  const errorEl = document.querySelector(
    // flattenObject: https://github.com/hughsk/flat/issues/52
    Object.keys(flattenObject(errors)).map(fieldName => `[name="${fieldName}"]`).join(',')
  );
  if (errorEl && errorEl.focus) { // npe
    // if (errorEl.scrollIntoView) {
    //   errorEl.scrollIntoView(); // fails as the site has a fixed/floating header
    // }
    errorEl.focus(); // this scrolls without visible scroll
  }
}
````

_Note: the form this is used for does not contain arrays, so I haven't checked the `flattenObject` actually creates correct field names_

#1336

**Comment by gustavohenke** [comment]
Thanks for the details, @AubreyHewes!

Since this issue is very UI specific, it's not a concern of Redux Form, therefore I'm closing it.
Feel free to continue the discussion, though.

**Comment by gwendall** [comment]
@AubreyHewes Thanks !

**Comment by shendepu** [comment]
@AubreyHewes I found using window.scrollTo can scroll the the errorEl

```
if (errorEl && window.scrollTo) {
  window.scrollTo(0, errorEl.offsetTop)
}
```

**Comment by dhurlburtusa** [comment]
I just recently started using `redux-forms`.  I am working on an existing project that is using version 6.8.0. (Based on the implementation and the v7 docs, I think it will work in v7 too.)

This solution uses 2 utility functions and the `onSubmitFail` callback.

```js
// ReduxFormUtils.js
/**
 * Flattens the hierarchical error generated by `redux-form`.
 *
 * @param {object} error - Error object as passed to `onSubmitFail`.
 */
export function flattenError(error) {
  let outErr, outErrs = []

  _flattenError(outErrs, error, '')

  outErr = {}
  outErrs.forEach((err) => {
    outErr[err[0]] = err[1]
  });

  return outErr
}

const _flattenError = (outErrs, error, prefix) => {
  for (let name in error) {
    let value = error[name]
    if (typeof value === 'string') {
      outErrs.push([ prefix + name, value ])
    }
    else if (value instanceof Array) {
      for (let i = 0, iLen = value.length; i < iLen; ++i) {
        _flattenError(outErrs, value[i], prefix + name + '[' + i + '].')
      }
    }
    else {
      _flattenError(outErrs, value, prefix + name + '.')
    }
  }
}

export default {
  flattenError,
}
```

```js
// FormUtils.js
/**
 * @param {string} formName - The name of the form which may have invalid input
 *   controls.
 * @param {object} error - An object where each key is the name of an invalid
 *   input control in the form with the specified name.
 */
export const focusFirstInvalidControl = (formName, error) => {
  let elmts, form

  form = document.forms[formName]
  elmts = (form || {}).elements || []
  for (let i = 0, iLen = elmts.length; i < iLen; ++i) {
    let elmt = elmts[i]
    if (elmt.name in error) {
      elmt.focus()
      break
    }
  }
}

export default {
  focusFirstInvalidControl,
}
```

```jsx
import { reduxForm } from 'redux-form'

import { focusFirstInvalidControl } from './FormUtils'
import { flattenError } from './ReduxFormUtils'
...
const FORM_NAME = 'MyForm'

class MyFormComponent extends React.Component {
  ...
  render() {
    return (
      ...
      <form name={FORM_NAME} ...>
      ...
    )
  }
  ...
}
...

MyFormComponent = reduxForm({
  form: FORM_NAME,
  onSubmitFail: (error, dispatch, submitError, props) => {
    focusFirstInvalidControl(FORM_NAME, flattenError(error))
  },
  ...
})(MyFormComponent)
```

There are two main steps that need to be done for each form:
1. Add a `name` attribute to the `form` element (just reuse the unique one you give to `reduxForm`)
2. Call the utility functions in the `onSubmitFail` callback as illustrated above.

This solution solves all the issues I believe have been plaguing everyone.

* Scoped to just one form (just in case you have multiple forms in the DOM with an invalid input control with the same name.)
* Focuses the first invalid input element found in the form.
* No need to try to scroll the element into view. The focusing should take care of that.
* Handles the possibly hierarchical error object created by `redux-form`.

**Notes:**

* I have not tested this with checkboxes or radio button controls (but I believe it should work).
* I have not tested it in v7 of `redux-forms` (but I am pretty sure it should work).
* The two utility functions could be combined into one, but I kept them separate because `focusFirstInvalidControl` can be used in any HTML document regardless of it being generated by React.

Please let me know if these utilities already exist in an npm package somewhere. If not and you have a cleaner implementation (maybe one that doesn't use recursion), then please let me know.

**Comment by jedwards1211** [comment]
@dhurlburtusa just a suggestion if you weren't already aware -- npm supports scoped package names like `@qc/dom_utils`, `@qc/redux-form_utils` etc. (it's free for public packages AFAIK) which you might want to look into using.  With unscoped names if someone had happened to publish a package named `qc-dom_utils` before you, you would have had to pick another name, whereas no one can publish `@qc/` anything once you've claimed the `qc` organization name.
