### ISSUE TITLE
How to initialize an FieldArray?

### ISSUE THREAD

**Issue by zkx34** [erikras/redux-form#2366]
hi erikras,  
    i got an sort of datas, array object, but when i try to initialize the FieldArray, i found the FieldArray passed 'fields' props to it's component,and manage the array of fields through 'fields' ,like push() and remove() methods. so i confused, how can i passed my datas to FieldArray and initialize the component , also manage those datas using 'fields' methods(remove() and push()...etc...) ?

**Comment by swp44744** [comment]
I dint get your question correctly, but see if this is what you are looking for. You can pass your custom array as a prop in FieldArray.

`myPersonalArray =['red', 'blue','green']`
`<FieldArray `
`name="FieldArrayName" `
`myPersonalArrayProp={myPersonalArray} `
`component={this.yourComponentName} `
`/>`

you can access your personal array as below in stateless fun:
`yourComponentName= ({fields, myPersonalArrayProp}) => {`
`console.log('where is my personal array??', myPersonalArrayProp);`
`}`

For push and remove, you need to provide a button in your component function and onClick either push or remove from field like `fields.push({})`

hope this helps. for more details refer to the FieldArray example in redux-form documentation

**Comment by swp44744** [comment]
I do have a question though, if I have my custom array and I want to control rendering FieldArray based on length of my custom array, how would I do that? I tried to push into fields until the length of my custom array like below but my code went in infinite loop:

`yourComponentName= ({fields, myPersonalArrayProp}) => {`
`myPersonalArrayProp.map((element, index)=>{`
`fields.push({});`
`})`
`}`

any thoughts???

**Comment by zkx34** [comment]
@swp44744 thanks for answer.
I have some thoughts now, i'll try it.

**Comment by swp44744** [comment]
Thank you Senhor, I will try it

**Comment by swp44744** [comment]
@gustavohenke I think I can use `componentWillReceiveProps` but is there a way to access fields outside the FieldArray component??

**Comment by erikras** [comment]
> is there a way to access fields outside the FieldArray component??

* You can _read_ the value with a [`formValueSelector()`](http://redux-form.com/6.4.3/docs/api/FormValueSelector.md/)
* You can _write_ the value by dispatching [actions](http://redux-form.com/6.4.3/docs/api/ActionCreators.md/)

**Comment by swp44744** [comment]
Thanks for the response @erikras. I tried doing something like below:

`const selector = formValueSelector('formName');`

`function mapStateToProps(state) {`
`  let fieldArrayObject = selector(state,'fieldArrayName');`

`  return {`
`    fieldArrayObject`
`  }`
`}`

But as FieldArray's `fields` does not have any element in it. formValueSelector returns undefined. I can initialize the fieldArray with an empty object to begin with, but for some reasons I didn't wanted to do that, as I want to render FieldArray exact times as my custom array length. let me try though.

**Comment by swp44744** [comment]
This question can be closed!!!

**Comment by rodpatulski** [comment]
@swp44744 Did you ever figure this out?

**Comment by Tiega91** [comment]
@swp44744 Yeah i wonder too, running at the same issue while init a select in FieldArray

**Comment by rodpatulski** [comment]
@Tiega91 I figured out the problem in my case. It was because I was using fields.map (also known as fields.forEeach) thinking I was actually using the plain old javascript map function but I was in fact using this http://redux-form.com/7.0.4/docs/api/FieldArray.md/#iteration

I first had to use fields.getAll() to receive a regular array and then loop through it normally. In essence, if you're trying to just render your fields, it seems to me like fields.map is an easy way of doing that, but if you're trying to loop through your values to do something other than render the <Field>s in your <FieldArray>, then make sure to use fields.getAll()

**Comment by Tiega91** [comment]
@rodpatulski Holy Moly 

> fields.map (also known as fields.forEeach) thinking I was actually using the plain old javascript map function but I was in fact using this http://redux-form.com/7.0.4/docs/api/FieldArray.md/#iteration

haha, this should be a big warning somewhere it was also my mistake. Now i have the issue that the "input.name" is not set correct.


```
const CommunicationCategories = props => {
    const { input, meta, communicationCategories, ...rest } = props;
    return (
       <select className="form-control" {...input} {...rest} {...meta}>
           {communicationCategories.fetched &&
               communicationCategories.communicationCategories.map(function (cc, ccindex) {
                   return <option value={cc.ID} key={ccindex}>{cc.Name}</option>
               })
           }
       </select>
    )
};

let Communications = ({fields, communicationCategories}) => {
    let cF = [];
    if(fields.length > 0) {
        cF = fields.getAll();
        return (
            <div>
                {
                    cF.map(function (com, index) {
                        return (
                            <div className="form-group row" key={index}>
                                <div className="col-3">
                                    <Field component={CommunicationCategories} communicationCategories={communicationCategories} className="form-control" name={`${com}.CategoryID`} >

                                    </Field>
                                </div>
                                <div className="col-5">
                                    <Field component="input" className="form-control" name={`${com}.Value`} />
                                </div>
                                <div className="col-3">
                                    <Field component="input" className="form-control" name={`${com}.Note`} />
                                </div>
                            </div>
                        )
                    })
                }
            </div>
        )
    } else {
        return (
            <div></div>
        )
    }

};
```

This is how i do it. BUT the select aka "CommunicationCategories" have now ALL the name:
> name="[object Object].CategoryID"

:(

**Comment by swp44744** [comment]
Sorry for late reply... glad it worked for you.. let me know if you still have issues I will try to help.

**Comment by rodpatulski** [comment]
@Tiega91 

> Did it as follow:
<Field component="input" className="form-control" name={fields.name+"["+index+"].Value"} />

I found that all I had to do was 

`<FieldArray name={`${curInventory}.nightlyInventoryAmt`} component={renderAmounts} key={index} containerName={`${curInventory}.containerName`}/>`

`{fields.map((curAmount, index) =>
	<td key={index}>
		<Field component={SimpleField} name={curAmount} type="number"/>
	</td>
)}`

within my fields.map iterator as you said, the output of which was '<input type="number" name="inventories[0].nightlyInventoryAmt[2]" value="0">'. I have run into trouble before trying to mimick the naming structure of what a <FieldArray> outputs without actually using a <FieldArray> as a side note.

**Comment by Tiega91** [comment]
@rodpatulski yeah you are right, don't know why it didn't work like that on the first try. 

@swp44744 But now i have the issue that the values from the dynamic filled selects within an FieldArray are not changing. Its selecting the correct value with initValues but not changing the value afterwards and when adding a new Array the value from the select stay 0.

I know this is not a stackoverflow but i hope you still can help me >.<
This i how i create the select:

```
 fields.map(function (com, index) {
                        return (
                            <div className="form-row" key={index}>
                                <div className="form-group col-3">
                                    <Field component="select" className="form-control" name={`${com}.Category.ID`} >
                                        {communicationCategories.fetched &&
                                            communicationCategories.communicationCategories.map(function (cc, ccindex) {
                                                return <option value={cc.ID} key={ccindex}>{cc.Name}</option>
                                            })
                                        }
                                    </Field>
                                </div>
```


This is also how i create "dynamic" selects outside of FieldArrays but they are working.

**Comment by sasajib** [comment]
For those who is searching for solution to add fields dynamically, I was able to do, but huge boilerplate codes is there and may be not efficient . There maybe better ways...

My use case is, when user select countries, it should load players with some form fields.
![SampleData](https://user-images.githubusercontent.com/110824/30666083-06f2b4dc-9e75-11e7-93d3-12f522ccdb07.png)

### component
```
import React, { Component } from 'react';
import { connect } from 'react-redux';
import _ from 'lodash';


class TeamFormComponent extends Component {

    constructor(props, context) {
        super(props, context);
    }

    findIndex(arr, key, value) {
        return _.findIndex(arr, o => o[key] === value);
    }

    update(value) {
        const fieldLength = this.props.fields.length;
        if (fieldLength > 0) {
            const hasValue = this.findIndex(this.props.fields.getAll(), 'index', value.index);
            if (hasValue === -1) {
                this.props.fields.insert(value.index, value);
            }
        }
        else {
            this.props.fields.insert(value.index, value);
        }
    }

    componentWillReceiveProps(nextProps) {
        if (nextProps.selectedTeams !== this.props.selectedTeams) {
            const selectedTeamWithIndex = nextProps.selectedTeams.map((data, index) => {
                return { ...data, ...{ index } };
            });

            if (this.props.fields.length > selectedTeamWithIndex.length) {
                this.props.fields.getAll().map((data, index) => {
                    if (selectedTeamWithIndex[index] === undefined) {
                        this.props.fields.remove(index);
                    }
                    else if (selectedTeamWithIndex[index].index !== index) {
                        this.props.fields.remove(index);
                        this.update(data);
                    }
                });
            } else {
                selectedTeamWithIndex.forEach(data => this.update(data));
            }
        }
    }

    render() {
        return (
            <h2>Total Fields Item {this.props.fields.length}</h2>
        );
    }

}

function mapStateToProps(state) {
    return {
        teams: state.teamPlayers
    };
}

TeamFormComponent = connect(mapStateToProps)(TeamFormComponent);

export default TeamFormComponent;

```
### usage
```
<FieldArray
        name="teams"
        component={TeamForm}
        props={{selectedTeams: selectedTeams}}
/>
```

hope it helps others, thx
