### ISSUE TITLE
Is it possible to use a different name in store, except form?

### ISSUE THREAD

**Issue by diki** [erikras/redux-form#2367]
Hi,

Thanks for your efforts and great tool. We already have a "form" reducer in our stores, can I use a different name instead of form while registering formReducer.

Thanks.

**Comment by gustavohenke** [comment]
Yes, you can.

It's [in the docs](http://redux-form.com/6.4.3/docs/api/Reducer.md/):

> If you absolutely must mount it somewhere other than form, you may provide a `getFormState(state)` function to the `reduxForm()` decorator, to get the slice of the Redux state where you have mounted the redux-form reducer.
