### ISSUE TITLE
initialValues in FormWizard do not work with FieldArray

### ISSUE THREAD

**Issue by kaufmo** [erikras/redux-form#2370]
Hello,

I hope I can explain my problem understandably. I wanted to use redux-form(wizard) for a shop cart.

At the beginning I dispatch the initialize action with the data for the cart, these looks like:
`kitchens: [{"id": "2-1-1-1-5-9-2", "deliveryOption": "selfservice"},{"id": "2-1-6-1-5-9-2","deliveryOption": "selfservice"}]`
In my Wizard I render the FieldArray with name "kitchens" but in this fields prop is always empty? I also tried to add an "Add-Button" where i use fields.push()?
Now an new Kitchen is added in values but also fields is empty.

Can somebody help me?

Here is a simply Overview of my code: https://jsbin.com/pawezu/33/edit?js,output

**Comment by swp44744** [comment]
Hey I am facing the same issue..! were you able to resolve this? 
After initializing, In my redux state:
1. initial shows the value that I initialized.
2. But values shows empty.

**Comment by kaufmo** [comment]
Hey yes my Problem was the form reducer. I initialized it as "formReducer" but the key for the store has to be "form". After I changed that it worked.

before:

    combineReducers({
        formReducer
    })

after:

    combineReducers({
        form: formReducer
    })

**Comment by swp44744** [comment]
Hi @kaufmo - Yes I am using `form: formReducer` only. After initializing the FieldArray I had to use action arrayPush('fieldArrayName',{}) inside the componentDidMount. 

Cool we can close this topic!! thanks though. Happy coding
