### ISSUE TITLE
v6.4.1 (React-Native 0.39.2) Dirty flag is not set on iOS 

### ISSUE THREAD

**Issue by ooicl** [erikras/redux-form#2372]
Hi,

I'm trying to show a "Save" button on the NavBar when the form is "dirty". So I use "this.props.dirty" to check that and show the state of the form ("Clean" or "Dirty"). But "this.props.dirty" is never set on iOS simulator, however working fine on Android simulator. Any idea?

```
componentDidMount() {
    Actions.refresh({ renderRightButton: this.renderRightButton });
  }

  renderRightButton = () => {
    if (this.props.dirty) {
      return (
        <TouchableOpacity onPress={this.onAddAccount}>
          <Text>Dirty</Text>
        </TouchableOpacity>
      );
    }

    return (
      <TouchableOpacity onPress={this.onAddAccount}>
        <Text>Clean</Text>
      </TouchableOpacity>
    );
 }

```
![screen shot 2017-01-02 at 10 10 47 pm](https://cloud.githubusercontent.com/assets/19430854/21590740/589f0c0e-d139-11e6-9e15-7c94a964fe5f.png)
![screen shot 2017-01-02 at 10 11 15 pm](https://cloud.githubusercontent.com/assets/19430854/21590745/5fb52e88-d139-11e6-92c4-c2d7f040c7a5.png)

**Comment by erikras** [comment]
I don't have any experience with React Native. Any help debugging this would be appreciated.

Can you examine/log the Redux store?

**Comment by ooicl** [comment]
The redux store for the Form seems identical but I don't know where the "dirty" flag is stored... 

![screen shot 2017-01-02 at 10 59 49 pm](https://cloud.githubusercontent.com/assets/19430854/21591477/6b188cf6-d13f-11e6-8b62-0cd3ecd0f060.png)
![screen shot 2017-01-02 at 11 01 08 pm](https://cloud.githubusercontent.com/assets/19430854/21591479/726cebb4-d13f-11e6-87d6-675b5b86a05f.png)

**Comment by erikras** [comment]
```jsx
dirty = deepEqual(initial, values)
```
Where `deepEqual()`, if you are not using ImmutableJS, is defined [here](https://github.com/erikras/redux-form/blob/37adcbeed35d24a7d02e10ed8267e89992263920/src/structure/plain/deepEqual.js#L12). Clearly `"Cow" !== ""`, so something's up.

**Comment by ooicl** [comment]
I try accessing "this.props.dirty" within the form itself and it was set correctly. So, the problem is not with Redux Form. It probably has to do with React Native Router Flux not rendering the NavBar again when the component state changes. 

Sorry for the trouble. 

![screen shot 2017-01-03 at 7 39 34 am](https://cloud.githubusercontent.com/assets/19430854/21597589/d8cdea0a-d187-11e6-8bb3-866576f71fac.png)

**Comment by ooicl** [comment]
I solved it by forcing the NavBar to re-render when the component is updated.

```
  componentDidMount() {
    Actions.refresh({ renderRightButton: this.renderRightButton });
  }

  componentDidUpdate() {
    Actions.refresh({ renderRightButton: this.renderRightButton });
  }
```

**Comment by erikras** [comment]
No worries. I appreciate seeing how `redux-form` is being used on mobile. Rock on!

---

P.S. I also use three-letter animal names when testing forms... 😆

**Comment by ooicl** [comment]
Very funny...
