### ISSUE TITLE
Access form props in onSubmit

### ISSUE THREAD

**Issue by arb** [erikras/redux-form#2378]
**Version 4.2.0**

I'd like to use the form props in my `onSubmit` property I am passing into the `reduxForm` constructor. Looking at the code (*/src/handleSubmit.js*), it looks like the only arguments that get passed in are `values` and `dispatch`. Is there a way to get a handle to the form props in that function?

*component code*
```js
render () {
    const {
      handleSubmit,
    } = this.props;

    return (
      <div>
        <form
          method="POST"
          onSubmit={handleSubmit}
        >
       ...
```

*decoration code*
```js
const PaymentOptions = {
  initialValues: {},
  form: 'payment-form',
  onSubmit (values, dispatch) {
    // I want access to the form props here
  }
};
```

**Comment by eligolding** [comment]
One option you have is to use the other way of setting your `onSubmit`, which is to use a function from within your form component.

As per [the docs](http://redux-form.com/4.2.0/#/api/props?_k=mp10ht):
> Optionally, you may also pass your onSubmit function to handleSubmit which will take the place of the onSubmit prop.

So you code might look something like this:

_component code_
```
submit(values, dispatch) {
  // here you can access all the form props from this.props
}
render () {
    const {
      handleSubmit,
    } = this.props;

    return (
      <div>
        <form
          method="POST"
          onSubmit={handleSubmit(this.submit.bind(this))}
        >
       ...
```
_decoration code_
```
const PaymentOptions = {
  initialValues: {},
  form: 'payment-form',
  // leave out the onSubmit function from here
};
```

Hope that helps.

**Comment by arb** [comment]
That's not ideal but should help me get around the issue I'm having. Thanks for the suggestion! 

I've always found this part of the API to be extremely confusing.
