### ISSUE TITLE
input value can't be  edit

### ISSUE THREAD

**Issue by wd2010** [erikras/redux-form#2379]
```jsx
import React,{Component} from 'react';
import { Field, reduxForm } from 'redux-form';

const renderInput = field =>{
	return (
    	<input {...field.input} type={field.type}/> 
	)
} 
const ContactPage =(props)=>(
	<div>
		<Field  
		name="otherMoney" 
		component={renderInput} 
		type="text"
		/>
	</div>
)

export default reduxForm({
	form: 'recharge-form'
})(ContactPage);

```

My Component successfully renders and I can see all the actions being dispatched inside the Redux Dev tools window, but when I try to enter text into the fields it won't do any thing, however the actions are dispatched like I said.

**Comment by eligolding** [comment]
Make sure you are mounting your reducer in the right place. It must be under `form` in your redux state.
```
const store = createStore(combineReducers({ form: reducer }))
```

**Comment by erikras** [comment]
Yep. What @eligolding said. This code looks okay.

**Comment by wd2010** [comment]
Thank you @eligolding ,the fields is OK.
# **before:**
   reducers.jsx
```jsx
import { reducer as form  } from 'redux-form';

const rootReducer=combineReducers({user,goods,chart, form,})

export default rootReducer
```
  index.jsx
```jsx
import app from './reducers/reducers.js';
const reducers=combineReducers({app ,routing: routerReducer})

let store = createStore(reducers,composeEnhancers(applyMiddleware(...middleware)))

```

# **after:**
   reducers.jsx
```jsx

const rootReducer=combineReducers({user,goods,chart})

export default rootReducer
```
  index.jsx
```jsx
import app from './reducers/reducers.js';
import { reducer as form  } from 'redux-form';

const reducers=combineReducers({app ,routing: routerReducer, form})

let store = createStore(reducers,composeEnhancers(applyMiddleware(...middleware)))

```

The form reducer must be under the state(state->form), can't the state->app(state->app->form),so it can't work.

**this can't work!**
[
![b](https://cloud.githubusercontent.com/assets/16284915/21666511/feeb5dac-d32c-11e6-863f-bd0f6097f482.png)
](url)


**this can work!**
[
![a](https://cloud.githubusercontent.com/assets/16284915/21666516/07b995d4-d32d-11e6-8c5f-6ced2d03d623.png)
](url)

**Comment by erikras** [comment]
Whilst it is strongly discouraged, you _can_ mount the `redux-form` reducer anywhere you like, but you need to tell `redux-form` how to find it.

If you really want it under `state.app.form`, you can provide a [`getFormState`](http://redux-form.com/6.4.3/docs/api/ReduxForm.md/#-getformstate-function-optional-) config parameter that is `state => state.app.form` (it defaults to `state => state.form`).

**Comment by xavifuefer** [comment]
Hi, I'm sorry for commenting in a closed issue, but it still happens to me... Apparently the form state is mounted correctly

<img width="237" alt="screen shot 2017-02-12 at 02 17 30" src="https://cloud.githubusercontent.com/assets/2145631/22859108/833b1e62-f0c9-11e6-8a22-6037b0d58b95.png">

but it still refuses to show any text even though the actions are being dispatched!! :( don't know what else to try..

```
import React from 'react';
import { Field, reduxForm } from 'redux-form';

const beforeSubmit = (values) => {
  console.log(values);
};

const renderField = ({ input, label, type, meta: { touched, error } }) => (
  <div>
    <label>{label}</label>
    <div>
      <input {...input} placeholder={label} type={type}/>
      {touched && error && <span>{error}</span>}
    </div>
  </div>
);

const SignInForm = ({ error, handleSubmit, pristine, reset, submitting }) => (
  <form onSubmit={handleSubmit(beforeSubmit)}>
    <div>
      <Field name="email" type="text" component={renderField} label="Email" />
      <Field name="password" type="password" component={renderField} label="Password"/>
    </div>

    {error && <strong>{error}</strong>}

    <div>
      <button type="submit" disabled={submitting}>Sign In</button>
      <button type="button" disabled={pristine || submitting} onClick={reset}>Clear Values</button>
    </div>
  </form>
);

SignInForm.propTypes = {
  error: React.PropTypes.any,
  handleSubmit: React.PropTypes.func,
  pristine: React.PropTypes.bool,
  reset: React.PropTypes.func,
  submitting: React.PropTypes.bool,
};

export default reduxForm({
  form: 'signin',
})(SignInForm);
```

**Comment by gustavohenke** [comment]
Hi @xavifuefer, it's better if you can provide us a minimal reproducible demo.
Start from here: https://jsfiddle.net/gustavohenke/48814zsq/

**Comment by xavifuefer** [comment]
Hi @gustavohenke can't reproduce it with jsfiddle. All I did was cloning [https://github.com/react-boilerplate/react-boilerplate](react-boilerplate) and creating that simple form element from my previous post.. :(

**Comment by xavifuefer** [comment]
I can see now that the problem is that I'm trying to use `redux-form` and I should use `redux-form/immutable` instead. From [https://github.com/react-boilerplate/react-boilerplate/issues/1244](here)

**Comment by sdu6342** [comment]
I spent almost 10 hours to find the solution of this problem. 
I finally read @xavifuefe's solution!
Yeah!, @xavifuefer has perfect solution. Thank you!

**Comment by aanchan** [comment]
Can someone explain to my as to why the solution with the immutable import works? What is going on under the hood?

I'm running into a similar problem when integrating Redux forms with PouchDB. [redux-pouchdb](https://github.com/vicentedealencar/redux-pouchdb) requires one to wrap the reducers using a proxy reducer. The form is non-functional as mentioned above.

**Comment by el-rotny** [comment]
@aanchan and in case anyone comes back to this. Make sure you just your reducer directly to your rootReducer with a `form` key.  I can see your reducer is wrapped using pouchDB, It should still work.

```javascript
import { combineReducers } from 'redux';
import { reduxTokenAuthReducer } from 'redux-token-auth';
import { reducer as reduxFormReducer } from 'redux-form';

export default combineReducers({
  form: reduxFormReducer,
  reduxTokenAuth: reduxTokenAuthReducer
});

```

In your case `form: formReducer`:

``` javascript
import { combineReducers } from 'redux';
import formReducer from './wrappedReducers';
import { routerReducer } from 'react-router-redux';

export default function createReducer(extraReducerObjects = {}) {
  return combineReducers({
    routing: routerReducer,
    form: formReducer,
    ...extraReducerObjects
  });
}
```
