### ISSUE TITLE
Field name cannot be a number

### ISSUE THREAD

**Issue by eligolding** [erikras/redux-form#2388]
I am trying to set a `Field`'s name prop as a number (e.g. `<Field name="123" component="input" />`). 

The problem is that when the `fields` key in state is created, instead of creating an object with the key "123", it creates an array with a length of 124, filled with nulls except the last index.

The issue I believe is that the [`setIn`](https://github.com/erikras/redux-form/blob/a36253295a68c1fbe21bc567d3351205887daafc/src/structure/plain/setIn.js) function, which is what creates the state, does not differentiate between dot and bracket syntax. [If it sees a number, it creates an array](https://github.com/erikras/redux-form/blob/a36253295a68c1fbe21bc567d3351205887daafc/src/structure/plain/setIn.js#L12). So even though it is being called as `setIn(result, 'fields.123.visited', true)`, it is being considered as `setIn(result, 'fields[123].visited', true)`.

The solution would probably be to have this function account for whether or not dot notation was used when encountering a number. The other solution would be to just not use numbers as names, but I feel that since this is valid in the DOM, it should be able to be done here as well.

I already wrote a [failing test](https://github.com/eligolding/redux-form/blob/88c99437f0e1e01beea6875a4e5712c801dca418/src/structure/plain/__tests__/setIn.spec.js#L26), but don't have a working solution yet.

I'm curious to know if I am understanding the problem correctly, and if this functionality is something that should be supported.

Thanks

**Comment by gustavohenke** [comment]
First of all: please send a PR even though all you have is a failing test 👍 
Second: it's better to use a permalink when linking code in GitHub (eg a commit or a tag), because the `master` branch moves and the code we're looking at now may not be the same in the future :)

Now... the syntax for these object paths usually follow the JS syntax, so you can't have something like `a.1` because you can't have a variable that starts with a number.

The behavior that I saw in the code is that if the preceding path already exists, then the numeric key will be set in the object.
This is probably because the container of field values doesn't exist yet, so in your example `123` creates an array instead of an object.

**Comment by eligolding** [comment]
TIL what a permalink is 😉 

So basically this "bug" is a result of the initial state being empty (resulting `fields` not existing yet) instead of defaulting to the top level structure with `field` and `values` being empty objects.

Was this design intentional? Why can't the initial state be something like:
```
form-name: {
  registeredFields: {},
  fields: {},
  values: {}
}
```

**Comment by erikras** [comment]
😆 😆  What a funny side effect of this silly language we write in and `setIn`.

**Comment by eligolding** [comment]
So what's the plan with this?
Should we add logic to `setIn` to detect dot vs bracket notation? It will mean that the function will no longer be obeying true JS syntax, because `foo.123` will be considered valid.
I don't mind giving this a shot, just want to make sure everyone is on board.

**Comment by erikras** [comment]
I just spent an hour investigating this.

In `v5`, I had quite a bit of code that was parsing the dot-vs-bracket notation, and it was a veritable mess, and a source of very many bugs. It was a very conscious decision to switch to use [`_.toPath()`](https://lodash.com/docs#toPath) in `v6` to avoid that headache.

So I think the answer is that numeric field names are not supported. Prefix it with something. e.g. `'field_123'`.

If you wrote a _very thoroughly tested_ implementation of `setIn`, for both plain and immutable structures, I might consider a change of this policy.

**Comment by eligolding** [comment]
Thank you so much for taking the time to look into this. 

I will see if I can come up with something worth the headache. Totally understand that it's not trivial.

Thanks again for an amazing lib!
