### ISSUE TITLE
values prop is not present on component decorated with reduxForm

### ISSUE THREAD

**Issue by sslotsky** [erikras/redux-form#2389]
Hi @erikras ,

Currently upgrading my project to 6.4.3 and loving the new features. But it looks like, contrary to [the docs](http://redux-form.com/6.4.3/docs/api/ReduxForm.md/), the `values` prop is not available to my decorated component. Looks like everything else is there. Any idea why it would be missing?

![image](https://cloud.githubusercontent.com/assets/374078/21660019/2b2e4144-d293-11e6-9c76-d53b032d73e0.png)

**Comment by gustavohenke** [comment]
#2387 is willing to remove it from the docs 😉

**Comment by timhwang21** [comment]
https://github.com/erikras/redux-form/issues/1658
