### ISSUE TITLE
Rejecting promise with non-errors

### ISSUE THREAD

**Issue by ianks** [erikras/redux-form#239]
I have been using Bluebird as my Promise lib, and when rejecting a promise without an error type, it issues a warning. It is explained here: http://bluebirdjs.com/docs/warning-explanations.html#warning-a-promise-was-rejected-with-a-non-error

In the documentation, it is encouraged to reject without errors. Should we reconsider this behavior for future releases?

**Comment by erikras** [comment]
Interesting. This is news to me. I wonder if we could stuff the validation errors json object into the `message` parameter? e.g.
```js
Promise.reject(new Error({name: 'Required'}));
```
And then `redux-form` could do a:
```js
whatever()
  .then(() => {
    // success
  }, rejectedValue => {
    const errors = rejectedValue instanceof Error ? rejectedValue.message : rejectedValue;
    // do stuff with errors
  })
```
Does that seem reasonable?

**Comment by ianks** [comment]
I think we would have to serialize the message to JSON, then deserialize. Which seems like a 'meh' solution to me. I can't think of a way off the top of my head that makes sense. So I will have to think on it a bit.

**Comment by ianks** [comment]
The general pattern I like would be to always resolve, then do something like this:

```js
Promise.resolve({errors: {name: 'required'}})
```

Things are very explicit this way, and then redux-form could just check for properties in the `errors` key. Unfortunately, this is not backwards compatible in any way I imagine :disappointed:

**Comment by erikras** [comment]
pre-v3 expected the errors to be resolved, but people were complaining.

What a silly requirement from Bluebird. :angry: I suppose that redux-form _could_ check for an `errors` key in the resolution result...

**Comment by dflynn15** [comment]
I recently ran into the same warning 😕. Would we want to move forward with having an option such as `errors` or `promiseErrors`(in case someone has a field called errors :cry:) as the object key? I'm not seeing any better alternative at the moment either.

**Comment by ooflorent** [comment]
This behavior has been implemented in v6: [`SubmissionError`](http://redux-form.com/6.0.0-alpha.5/docs/api/SubmissionError.md/).
Thank you for warning us about this use case!
