### ISSUE TITLE
Use redux form without form element

### ISSUE THREAD

**Issue by pegiadise** [erikras/redux-form#2392]
Thanks for the amazing tool. In our product due to some legacy code the whole app is in a `<form>` element. Therefore, a form inside a form is not allowed and results in the production of invalid html. Could redux-form be used without it?

**Comment by kevinzwhuang** [comment]
Yes @pegiadise you don't even need to use a `<form>` node inside your redux-form component if you don't have to.

Just as an example of this, this should work just fine: 
```es6
const FormWithoutForm = React.createClass({
  render() {
    return (
      <div>
          //
          //..... input form fields here
          //
        <button onClick={ this.props.handleSubmit } />
      </div>
  }
});

export default reduxForm({ form: 'FormlessForm' })(FormWithoutForm);
```
Hope this helps!

**Comment by pegiadise** [comment]
Thank you.

**Comment by erikras** [comment]
@kevinzwhuang's answer is correct. Using a `<form>` is completely optional.
