### ISSUE TITLE
How to clear errors of field when the field's disabled?

### ISSUE THREAD

**Issue by piya23300** [erikras/redux-form#2398]
I use [Field-Level Validation](http://redux-form.com/6.4.3/examples/fieldLevelValidation/).

My use case is

the field is invalid and then I disabled the field but it still be invalid.
How to clear errors of the disabled field?

Thank you in advance.

**Comment by erikras** [comment]
Seems like you could just only pass the `validate` prop when the field is enabled, no?

**Comment by piya23300** [comment]
@erikras I did it like your example. it still is invalid fields.

when the field's disabled, the validate of the field will be `undefined` and then I submit the form. the validate still work and `meta.valid` still is `false`.

if you have more information, you can tell me.

**Comment by danielrob** [comment]
Yes, more information please, perhaps a sandbox? If the validation function is undefined, it should not matter whether it is a submit validation or a change validation.

**Comment by cristianfraser** [comment]
I would like this also.

I prefer using a validate function passed to `reduxForm`. If that function ignores Fields that are not rendered, I find it natural for it to ignore disabled Fields too, even if they are rendered.

**Comment by StalkAlex** [comment]
This variant `validate={myFieldEnabled ? [ required, minLength ] : undefined}` is not working, fields are still validating on submit.

**Comment by Luckygirlllll** [comment]
@StalkAlex that solution works  for me as well!

**Comment by danielrob** [comment]
This issue appears to have been duplicated by #3012 and then fixed. @erikras's solution above would not have worked at the time of writing due to this. @StalkAlex that fix should have solved your problem in `7.0.0` depending on your exact situation. See #4017 for the full run-down. 

Close as this issue is likely resolved.
