### ISSUE TITLE
Replacing regular form components with reduxForm Field

### ISSUE THREAD

**Issue by icetronics** [erikras/redux-form#2404]
Hi,
I'm planning to create a low-level HOC which would wrap a form component that contains regular html5 inputs (or mui components) and on render it would traverse through the wrapped form's child tree and replace all the inputs with <Field> elements. This way I could make the presentational form component independent from redux-form. Is this something that can be done?

Thanks!

(question @ SO: https://stackoverflow.com/questions/41523340/react-replace-child-component-in-props-children)

**Comment by gustavohenke** [comment]
Sure, it can be done.

This is the API for recursive iteration that you asked at StackOverflow:
http://stackoverflow.com/a/33206831/2083599
