### ISSUE TITLE
Preserving form state between 2 pages

### ISSUE THREAD

**Issue by mpmlj** [erikras/redux-form#2408]
Hi,

I'm working on a 2-step signup process, each page being a new form, and a second form should have access to the values entered into the first form.

First form, in its onSubmit() function is doing a redirect:

    browserHistory.push('/signup/step2');

However, when second page/component is loaded, state of the first form becomes empty: visible via react dev tools and also access to values via formValueSelector is empty:

    const selector = formValueSelector('SignupForm');
    console.log(selector(state, 'email'));

Please advise on the best practice to solve this.

In my understanding, redux should serve as s datastore here, and I would just load initial values via formValueSelector, but maybe i'm just doing redirect incorrectly?
Any help is appreciated!

**Comment by gustavohenke** [comment]
Set `destroyOnUnmount ` option to `false` in your `reduxForm` HOC and let us know if it works for you! 😉

**Comment by mpmlj** [comment]
@gustavohenke 
Thank you, it worked!!
I.e. I changed the approach from submitting a form "from a page to a page", to having a multi-panel form within one page, based on the docs above.

P.S.
One note though: I'm always getting "Warning: Failed prop type: The prop `onSubmit` is marked as required in `SignupForm`, but its value is `undefined`."
I see discussions in the "Issues" section, but honestly - no clarity why why this warning is thrown, as as onSubmit property IS provided. Any insights are greatly appreciated as well!

**Comment by mpmlj** [comment]
OK. "onSubmit" Solved.
For those who may be looking for a solution, here's how I'm doing this:

In the parent component ( corresponding to WizardForm.js from http://redux-form.com/6.4.3/examples/wizard/ ):
- You declare 
```
  handleSubmit(data) {
    // your action on form submission
  }
```

- Your child component declarations look like:

```
                  {page === 1 && <FirstStep onSubmit={this.nextPage} />}
                  {page === 2 && <FinalStep
                    previousPage={this.previousPage}
                    onSubmit={this.handleSubmit}
                  />}
```
