### ISSUE TITLE
Submit a form from parent or owner component

### ISSUE THREAD

**Issue by nuschk** [erikras/redux-form#241]
I have a use case where I'd like to use a form in a wizard like component. The wizard stuff is re-usable and implements the prev/next buttons. The wizard's next button should trigger the form submission on a specific screen. 

I'm no expert on redux-form, but it seems to me I can only access handleSubmit from within the form itself (or one of its children, if I pass it on).

Now, in order to keep the wizard components clean and simple, I can't really nest them into the form. I need to trigger handleSubmit from the form's parent component or owner.

Redux has a very simple concept for stuff like that: it provides a getWrappedInstance() method on the Connect component. Would this be available for redux-form, I'd be able to provide and call a submit() method on the form instance myself.

Might also be I'm missing something obvious here...

**Comment by erikras** [comment]
You almost got the headline exactly from #202. It's still an issue that doesn't have a great solution yet, but I'm closing this as a dupe.

**Comment by nuschk** [comment]
Oh my, sorry for that, I didn't see that issue. Thank you.

**Comment by erikras** [comment]
[`v4.2.0`](https://github.com/erikras/redux-form/releases/tag/v4.2.0)

**Comment by nuschk** [comment]
You're the man, thanks a lot!

**Comment by anandrikka** [comment]
Cool thank you @erikras
