### ISSUE TITLE
Make API sections easily linkable in the docs

### ISSUE THREAD

**Issue by gustavohenke** [erikras/redux-form#2411]
Usually I need to copy the URL for some API section while replying some issues.

It's better if I could easily get the hash of the current section by clicking some icon over the API section, eg

![](http://i.imgur.com/a7pqkkg.png)

P.S.: I know the section IDs are already there because I inspected the code, but we developers are lazy!

**Comment by erikras** [comment]
Yes, this has been a pain point for me, as well. As I'm using a self-built doc generation system, it would require some manipulation either before or after the markdown-to-html step.

**Comment by erikras** [comment]
Being able to link to anchors is the main reason that I switched away from the react-router-based docs that `v5` had (GitHub Pages will only serve actual static html files, so you can't use the HTML5 react-router history trickery).

**Comment by gustavohenke** [comment]
What's the name of the doc generator? I couldn't find it in the npm scripts.
