### ISSUE TITLE
FieldArray re-registering field

### ISSUE THREAD

**Issue by cristiansarov** [erikras/redux-form#2412]
I've been searching / debugging for days, and I can't find a solution.

Using the latest version of redux form, the code given on documentation.

When I type in a text input:
- I am blurred out of the input;
- The FieldArray passed component re-renders;
- In redux console, I get "@@redux-form/UNREGISTER_FIELD" x number of fields in FieldArray, then "@@redux-form/REGISTER_FIELD" x number of fields in FieldArray.

This issue makes typing in a Field in a FieldArray impossible. 

If I remove the FieldArray and bind the Field to root Form, the issue disappears.

Is this a bug? Can you help me?

**Comment by gustavohenke** [comment]
You should post some code that reproduces the issue.
Even better if you can use http://webpackbin.com for this.

The [Field arrays example](http://redux-form.com/6.4.3/examples/fieldArrays/) works, so it must be related to something you changed in your project.

**Comment by cristiansarov** [comment]
Trying to simplify the code to give it to you, I came across this:

PollEditComponent = reduxForm({form: 'PollEditComponent'})(PollEditComponent);
export default connect(state => ({
  initialValues: state.community.poll.pollDetails,
  formData: state.form.PollEditComponent && state.form.PollEditComponent.values
}))(PollEditComponent);


... if I remove the formData row, it all works. It doesn't make any sense.

**Comment by sslotsky** [comment]
I have a similar issue. In my case, the `UNREGISTER_FIELD` occurs as soon as my input goes from invalid to valid. The `UNREGISTER` and subsequent `REGISTER` calls cause my input to lose focus.

```javascript
import React, { PropTypes } from 'react';
import { Field } from 'redux-form';
import Frequency from './Frequency';
import Recipient from './Recipient';

export default function NotificationFields({ fields, destroy }) {
  const renderNotification = (member, index, fields) => {
    const names = [`${ member }.frequency`, `${ member }.recipient`];
    const remove = () => {
      if (fields.get(index).id) {
        destroy(id);
      }

      fields.remove(index);
    }

    return (
      <div className='row performance-notification' key={index}>
        <span className='form-label settings-text'>
          {I18n.t('settings.notification.performance.send')}
        </span>
        <Field
          name={`${ member }.frequency`}
          component={Frequency}
        />
        <span className='form-label settings-text'>
          {I18n.t('settings.notification.performance.updates_to')}
        </span>
        <Field
          name={`${ member }.recipient`}
          component={Recipient}
        />
        <Field
          name={`${ member }.id`}
          component='input'
          type='hidden'
        />
        <button type='button' className='m-l-1 btn btn-secondary' onClick={remove} >
          <span className='glyphicon glyphicon-trash' />
        </button>
      </div>
    );
  };

  return (
    <div>
      {fields.map(renderNotification)}
    </div>
  );
}
```

![image](https://cloud.githubusercontent.com/assets/374078/21776102/770ecd94-d65e-11e6-8a60-8ac2b1db2b5b.png)

**Comment by sslotsky** [comment]
Including a video in case that's helpful. The `UNREGISTER` and subsequent `REGISTER` calls do not fire if I remove the validation. Also tried using field level validation, same result.

![unregister fields](https://cloud.githubusercontent.com/assets/374078/21777580/076990c6-d665-11e6-91a8-f015ea1d3c65.gif)

**Comment by sslotsky** [comment]
Slight correction: `UNREGISTER` and `REGISTER` calls happen as soon as the entire form's valid state changes. Changing a single field's valid state won't cause this, unless it is the only field on the form being validated.

So far no luck reproducing this on the example in the docs. There are no differences that stand out to me. If you're unable to reproduce the issue, I will see about spinning up a simple repo and linking to it, since the project I'm working on currently is private.

**Comment by sslotsky** [comment]
Workaround identified. I was previously rendering my `NotificationFields` like this

```javascript
    const renderFields = ({ fields }) => (
      <NotificationFields fields={fields} destroy={destroyNotification} />
    );

    return (
      <form handleSubmit={handleSubmit}>
        <div>
          <FieldArray
            name='notifications'
            component={renderFields}
            validate={validateEmails}
          />
```

To make it work I changed the `renderFields` function into a component class:

```javascript
export default class extends Component {
  render() {
    return (
      <NotificationFields {...this.props} />
    );
  }
}
```

and then

```javascript
  render() {
    const { anyTouched, valid, reset, handleSubmit, destroyNotification } = this.props;

    return (
      <form handleSubmit={handleSubmit}>
        <div>
          <FieldArray
            name='notifications'
            component={NotificationFields}
            destroy={destroyNotification}
            validate={validateEmails}
          />
```

**Comment by sslotsky** [comment]
Aha! In fact, it doesn't even need to be a component class. It just need to be defined _outside_ of the component that's rendering it. When my parent component was re-rendering, it was recalculating the `renderFields` function altogether, and that always results in re-rendering the field array.

**Comment by cristiansarov** [comment]
My case doesn't work in any situation. I've externalized every render function, a have used Redux Form selectors for selecting the form values (http://redux-form.com/6.4.3/docs/api/Selectors.md/), still the same problem.

Every time I connect the component with the form state, the FieldArray stops working properly... :(

**Comment by sslotsky** [comment]
@cristiansarov I would expect that in your case, because every time you update a field in your form, it's going to cause a re-render of the decorated component since the props are changing. Why exactly do you need your form values injected? If you need them, could you inject them into a child of your connected component? For example:

```javascript
export function MyDecoratedForm(props) {
  return (
    <Field name="foo" component="input" />
    <FieldArray name="bars" component={renderBars} />
    <ChildComponentWithFormValuesInjected />
  );
}
```

**Comment by cristiansarov** [comment]
@sslotsky Thank you, I think I understand the concept of re-rendering, thank you, I will try to externalise the form values.

**Comment by cristiansarov** [comment]
Here I reproduced the problem

http://www.webpackbin.com/4J60qekLf

**Comment by cristiansarov** [comment]
And this is the solution for me

http://www.webpackbin.com/V11Q_fkIG

**Comment by Rendalf** [comment]
@cristiansarov Could you please reincarnate your links?

**Comment by marnusw** [comment]
What caught me was:

```javascript
<Field ... validate={[required, minLength(6)]}/>
```

Every time the form was rendered a new `minLength` instance would be created which caused the field to `UNREGISTER_FIELD` and then `REGISTER_FIELD` again.

The `minLength` instance should be created once outside of the render function:

```javascript
const minLength6 = minLength(6)

<Field ... validate={[required, minLength6]}/>
```

**Comment by simonmarton** [comment]
Using an inline validate function triggers `UNREGISTER_FIELD` and `REGISTER_FIELD` in 7.0.3.
It works fine in 6.8.0.

**Comment by strongui** [comment]
If anyone comes across this problem again in V 7 + make sure you look at @marnusw  answer! I had the same issue, and initializing the validations function OUTSIDE of the render method solved the problem.

**Comment by KasperOlesen** [comment]
Experiencing the samme exact issue and tried following @marnusw answer, but I have structured my code a bit differently and couldn't quite grasp how to initialize my validation outside of the render method. If anyone wants to take a look and lend a hand, please see: [my post on SO](https://stackoverflow.com/questions/49134463/fieldarray-re-registering-fields-after-each-char-input)

**Comment by cborboni** [comment]
@cristiansarov can you post some code of your solution about map() inside field array? I have the same problem but I can't understand how to solve it, and the link you posted is no more available. Thank you.

**Comment by cristiansarov** [comment]
If I don't use inline validation on trigger re-rendering of the FieldArray, I don't get the re-registering issue. Check if you don't re-render the FieldArray, this makes the map inside to re-render and so each field of the map re-register.

**Comment by lukejsimonetti** [comment]
For me it was initing the validation function inside the render method causing the multiple unregister/register of my Field components. Initing the functions outside the render was the solution.

Does anyone know of any updates to redux-form since this problem was discovered? Or maybe a warning that can be displayed? It took me awhile to figure out why my fields were registering/unregistering several times until I stumbled upon this post.

**Comment by danielrob** [comment]
Please see #4017
