### ISSUE TITLE
Validate onSubmit, but don't validate onChange or onBlur

### ISSUE THREAD

**Issue by fedosejev** [erikras/redux-form#2413]
After exploring the API, the examples and reading through the similar issues, I still don't have a straight forward solution for this problem, so I am asking for your help.

I don't want to validate each input field `onChange` or `onBlur`, but I want to validate all input fields `onSubmit`. What would be the best way to approach this problem?

The form validation is _synchronous_ and I am using version `6.3.2`.

**Comment by andynoelker** [comment]
Redux Form will run the validation function against any touched Fields. You need to configure Redux Form to not touch fields on a blur event by setting `touchOnBlur` to `false` in the Redux Form config. (By default, this is already false for change events).

```
export default reduxForm({ form: 'myForm', touchOnBlur: false })(MyForm);
```

**Comment by cristian-eriomenco** [comment]
@andynoelker I have the same issue. And the suggested change to config didn't make any difference unfortunately.

Suppose we have an ```EditForm```, with ```initialValues={{email: "wrong?email.com"}}```, if you click submit, the email validation rule won't kick-in. It requires you to do one of the following:
a) Trigger a touch by blurring the field
b) Mutate the values

What kind of optimisation is being made to the validators? Wouldn't it make sense to simply invoke the validation function on submit without taking into account any touches, comparison against initialValues etc

```
// Naive Pseudo code
handleSubmit() { 
   if (this.requiresValidation()) {
      const errors = this.config.validate(this.form.values);
      if (errors) {
         this.showErrors(errors);
      } else {
        this.clearErrors();
        this.config.onSubmit(this.form.values);
      }
   }
}
```

Validation Related issues:
https://github.com/erikras/redux-form/issues/2427
https://github.com/erikras/redux-form/issues/2428

**Comment by zettadam** [comment]
If you want to validate onSubmit, then perhaps you could call the same `validate` function inside your form onSubmit handler (and not pass `validate` property in your reduxForm() option object).

```
const sleep = ms => new Promise(resolve => setTimeout(resolve, ms))

class SampleForm extends Component {

  submit (values) {
    const { actions } = this.props

    return sleep(1000)
      .then(() => {
        return validate(values, this.props)
      })
      .then(errors => {
        if (hasErrors(errors)) {
          throw new SubmissionError(errors)
        } else {
          // process form values
        }
      })
  }

  render () {
    const { handleSubmit } = this.props

    return (
      <form onSubmit={ handleSubmit(this.submit) } noValidate>
        ...
      </form>
  }
}

export default reduxForm({
  form: 'sample'
})
```

Seems like one approach, based on [Submit Validation Example](http://redux-form.com/6.5.0/examples/submitValidation/).

**Comment by fedosejev** [comment]
@zettadam sounds promising, thanks!  @erikras would this be a recommended approach?

**Comment by danielrob** [comment]
Why not use [`shouldValidate` config property](http://redux-form.com/7.0.3/docs/api/ReduxForm.md/) and return false unless props.submitting is true?

**Comment by lgerndt** [comment]
@andynoelker's solution works for me:  

`export default reduxForm({ form: 'myForm', touchOnBlur: false })(MyForm);`

**Comment by gustavohenke** [comment]
@danielrob suggestion is probably the cleanest; I don't think we would ever change this behaviour.
