### ISSUE TITLE
webapp is reloading on submit

### ISSUE THREAD

**Issue by plexigras** [erikras/redux-form#2414]
when pressing the submit button to submit the form the whole webapp reloads while what i want is only a event to be dispatched and the onSubmit function to be triggered.

is that intended?

happens in both 5.3.4 and 6.4.3

**Comment by gustavohenke** [comment]
Make sure your form has `onSubmit={handleSubmit}`.

**Comment by plexigras** [comment]
thanks a lot i finally got it all to work

**Comment by FKSI** [comment]
Sorry reopen that topic. But event with the whole `onSubmit={handleSumit}` explanation I didn't managed to make it work. 

BUT

I found the solution when look at the [example](https://github.com/erikras/redux-form/blob/master/examples/submitValidation/src/SubmitValidationForm.js#L18)

```
const SubmitValidationForm = (props) => {
  const { error, handleSubmit, pristine, reset, submitting } = props
  return (
    <form onSubmit={handleSubmit(submit)}>
        ...
    </form>
 )
