### ISSUE TITLE
asyncValidate error on blur

### ISSUE THREAD

**Issue by m1m6** [erikras/redux-form#2420]
Hello,

I am getting the following error for one of my fields whenever it is being blurred:

Uncaught Error: asyncValidate function passed to reduxForm must return a promise
This is surprising to me as I am not using async validation anywhere in my code and I'm not passing any asyncValidate function to reduxForm().

**Comment by mdramos** [comment]
I am getting this same error, on a field that isn't configured at all to use async validation:

```
const renderChoice = fieldDefinition => (
  <span>
    {fieldDefinition.get("label")}
    <Field
      name={fieldDefinition.get("name")}
      component="input"
      type="radio"
      value="true"
    />
    {" "}Yes
    <Field
      name={fieldDefinition.get("name")}
      component="input"
      type="radio"
      value="false"
    />
    {" "}No
  </span>
);
```

**Comment by steve-taylor** [comment]
That's a weird solution. I worked around it by adding `asyncBlurFields: []` to the object passed to `reduxForm`.

**Comment by dbroadhurst** [comment]
I've just run into the same issue even though other projects are working as expected. The difference is I'm explicitly calling reduxForm because I wanted to set up some initial values

Old Code
````
export default connect(mapStatetoProps, mapDispatchToProps)(MyComponent)
````

New Code
````
let Form = connect(mapStatetoProps, mapDispatchToProps)(MyComponent)

let Form = reduxForm({
  form: 'myform',
  // asyncBlurFields: [], // Adding this fixes the error messages
  initialValues: { priority: 'medium' }
})(Form)

export default Form
````

I'm confused how to add reduxForm to a component that already needs to be connected to the redux store

**Comment by dbroadhurst** [comment]
Did some more digging and I always get the error without asyncBlurFields: []

No Error
````
Form = reduxForm({
  form: 'myform',
  asyncBlurFields: [],
  initialValues: { priority: 'medium' }
})(Form)
````
Error
````
Form = reduxForm({
  form: 'myform',
  //asyncBlurFields: [], // Adding this fixes the error messages
  initialValues: { priority: 'medium' }
})(Form)
````

**Comment by CaitlinWeb** [comment]
I encountered this with some existing code in a project and figured out why: the parent component was wrapped with a `reduxForm` without any validation and the child component (the one I was working on) was also wrapped in `reduxForm` but with a `validation` prop (synchronous).

Removing `reduxForm` from the parent component resolved the issue. I suspect that `asyncValidation` is the default and probably required unless you use the synchronous `validate`, so then you get the error if neither are defined. 

I'm still pretty new to Redux Form but I thought I would share my findings in case anyone else ran into the same issue.
