### ISSUE TITLE
v5.3.4 is full of 6.x changes

### ISSUE THREAD

**Issue by alagos** [erikras/redux-form#2421]
I guess is an error, but it has all the commits until 4 days ago
https://github.com/erikras/redux-form/commits/v5.3.4

**Comment by gustavohenke** [comment]
Yep, probably `master` was tagged as v5.3.4 instead of `v5`:  https://github.com/erikras/redux-form/commits/v5

cc @erikras

**Comment by gustavohenke** [comment]
@erikras, do you mind if we delete and re-create that tag?
