### ISSUE TITLE
6.4.3 submits unregistered initial values

### ISSUE THREAD

**Issue by sslotsky** [erikras/redux-form#2422]
I'm not sure if this is a bug or intended behavior, but I'm quite sure it's a change from 5.x and I'm not sure of the best way to deal with it.

Previously, when editing a record, I would often supply the initial values with: 

```javascript
initialValues={record.toJS()}
```

Only the fields that I specified in the `fields` property to `reduxForm` would show up in the payload, and I counted on this behavior. However, now when I submit my form, I'm getting every property that's in the `initialValues` object. I expected that only the fields that received a `REGISTER` call would be present.

**Comment by sslotsky** [comment]
Came up with this workaround but would still like to know if this is intended behavior and if so, suggest that only registered fields should be submitted.

```javascript
    const fields = [
      'first_name',
      'last_name',
      'title',
      'company',
      'phone_work',
      'phone_home',
      'phone_mobile',
      'email',
      'address1',
      'address2',
      'city',
      'state',
      'postal',
      'country'
    ];

    const initialValues = contact.filter((v, k) => fields.includes(k)).toJS();
```

**Comment by gustavohenke** [comment]
Curiously, today I learned about [mass assign vulnerability](https://www.owasp.org/index.php/Mass_Assignment_Cheat_Sheet), while providing support for another lib I maintain, express-validator 🤓 

IMO this vulnerability must definitely be fixed in the server, but if it's not a problem in regards to the other features of Redux Form, then why not fixing it here as well..?

What are your thoughts, @erikras?

**Comment by erikras** [comment]
This is intended behavior. The most common reason is that you have a primary key for the record that you are editing, but obviously you don't need/want a field with that primary key, but you _do_ need to submit it.

@gustavohenke is correct in that submitted values should be scrubbed on the server.

You can either filter your data before initialization or before submission (or both if you wish). As well as on the server. In fact, if you're using node on the server, you could even share the `onlyContactFormFields()` function between the client and server.

**Comment by sslotsky** [comment]
It seems to me that your most common use case can be solved with a 

```javascript
  <Field name="id" component="hidden" />
```

Where as blacklisting or whitelisting params actually requires more code. I don't disagree that the server should do this, but I don't find the use case for submitting all `initialValues` very compelling. Just my two cents of course. Thanks for listening :)
