### ISSUE TITLE
Form validation on dynamic multistep forms

### ISSUE THREAD

**Issue by RT-TL** [erikras/redux-form#2428]
I have an issue with validating a multi-step form (wizard). My form consists of a variable number of steps and each step is dynamically created based on data I initially load from remote. I am not very experienced in React and Redux, so please don't hate me for not following a lot of conventions which I try to learn while building.

My issue: I managed to create the multi step form but the form validation is acting weird and I can not figure out why. 

**Redux Form Render Questions**
```
import React from 'react'
import { Field, reduxForm } from 'redux-form'
import Navigation from '../components/Navigation'
import Header from '../components/Header'
import * as validator from '../components/Validation'

import renderField from '../components/renderField'

//Import question types
import QuestionClosure from '../questions/Closure_q'
import ImageMultiCheck from '../questions/ImageMultiCheck'

var renderQuestion = function(question) {

    //Set header values
    const questionHeader = <Header title={question.title} description={question.description}/>

    //Set question identifier
    //const questionName = String("Question" + question.id)
    const questionName = String("$" + question.id)

    //Select which question component to render
    switch (question.type) {

        case "ImageMultiCheck":
            return <div>
                    {questionHeader}
                    <Field component={ImageMultiCheck}
                           name={questionName}
                           options={question.Option}
                           multiple={question.multiple}
                           validate={validator[question.type]}
                    />
                </div>

        case "Colors":
            return <Field name="color" type="text" component={renderField} label="Color" validate={validator['color']}/>

        case "Closure":
            return <div>
                {questionHeader}
                <QuestionClosure name="Customer" question={question} validate={validator[question.type]}/>
            </div>
}

const Questions = (props) => {
    const { handleSubmit } = props
    return (
        <form onSubmit={handleSubmit}>
            {renderQuestion(props.question)}
            <Navigation length={props.length}
                        page={props.page}
                        previousPage={props.previousPage}

                        />
        </form>
    )
}

export default reduxForm({
    form: 'wizard',              
    destroyOnUnmount: false, 
    forceUnregisterOnUnmount: true, 
})(Questions)
```

So basically I use the renderQuestion-function to render whatever the question type tells me. Each question has its own component/way to be rendered. Matching this each question also has its own validation rules. All of them are combined in in a single file Validation that is imported as validator. 

**Validation.js**
```
var required = function(value) {
    if (typeof value == 'undefined' || value == 0) {
        return 'Bitte wähle aus'
    }
}

/** VALIDATION SETS FOR FORM FIELDS **/
export const color = value => {
    console.log(value)
    return required(value)
}

//ImageMultiCheckValidation
export const ImageMultiCheck = value => {
    return required(value);
}
```

In my test case I have 3 questions. The first one is of the ImageMultiCheck-Type. It renders and validates successful.

The second one is of the color-type. It renders well but inputs are not validated at all. When I move to the third question and then back to the second validation kicks in. In this case I can not proceed to the third question again. 

I am not sure if this is some misunderstanding in the way validation works or if there is some constraint to use dynamic validation rules on dynamic forms?

I appreciate your help :-)

**Comment by danielrob** [comment]
@RT-TL sorry that no one got back to you. Noones going to hate you for your code, honestly, I'm actually impressed with your setup! You understand the nature of dynamic form generation with alternate validators quite well. 

Everything here looks pretty good, I can only think that this was a specific issue to `renderField`... 

Or perhaps you managed to figure it out?

**Comment by danielrob** [comment]
Closing due to non-response, and that it is a support request. Please feel free to provide an update even so.
