### ISSUE TITLE
Disabled Fields not getting initialValues; formatting does not work

### ISSUE THREAD

**Issue by hannahjin** [erikras/redux-form#2429]
Hi, as I was using redux-form to create a connected component for my form. I struggled with the following 2 issues. 

1. Disabled Fields not getting initialValues
In my form, I have 
``` 
<Field
   name="abc"
   label="ABC"
   component={FormField}
   input={{
       disabled: true,
   }}
   required
/>
```
`FormField` takes input and add all the props to `<input {...input}>`
However, no initial value is shown when the input field is disabled. When I took out the input disabled prop, the correct value shows up. From network response, I see that the value is there. It is just not getting displayed when the field is disabled for some reason.

2. format
I passed in both functions and anonymous arrow functions to the format prop but nothing worked, even when I had a dummy function that return a hard coded default value.
```
const formatField = (value, name) => {
     switch (name) {
        case '1':
             return 'something'
        case default:
             return 'default'
     }
}
```
or a simpler function 
`format={(v) => v.toLocaleString('en')}`

Thank you!

**Comment by charlesrochati** [comment]
Are you sure that you're disabling the correctly? 

I would use something like this:

`<Field
                name={name}
                label={label}
                id={id}
                onBlur={onBlur}
                onClick={onClick}
                onFocus={onFocus}
                onChange={onChange}
                component={component}
                customInputLinkHelper={customInputLinkHelper}
                type={type}
                className={className}
                required={required}
                readOnly={readOnly}
                disabled={disabled}
                placeholder={placeholder}
            />`

**Comment by catsky** [comment]
same problem

**Comment by elhachimi** [comment]
@hannahjin & @catsky had the same issue ended up using 
```
   {disabled && <input {...input} placeholder={label} type={type} disabled/>}
   {!disabled && <input  {...input} placeholder={label} type={type} />}
```

inside `renderInput`
and passed disabled as a prop in `Field` component

**Comment by danielrob** [comment]
Will need a clearer description of each problem as this seems to be working:
https://codesandbox.io/s/oQ0qYqX3j

```
<Field
  name="firstName"
  component="input"
  type="text"
  placeholder="First Name"
  format={value => value === 1 ? "I'm disabled" : value}
  disabled
/>
// ...
  initialValues: { firstName: 1 },
// ...
```

**Comment by hannahjin** [comment]
This is from a long time ago, so the details of the problem is not clear to me any more. But I believe it works, at least for my case.

**Comment by rayronvictor** [comment]
@hannahjin here is the solution:
https://codesandbox.io/s/kk0lwn16y3

Basically, you have to pass the other props (rest) to your input.

```javascript
const renderField = ({
  input,
  label,
  type,
  meta: {
    touched,
    error,
    warning
  },
  ...rest
}) => {

  return (
    <div>
      <label>{label}</label>
      <div>
        <input {...input} {...rest} type={type} placeholder={label} className="form-control" />
      </div>
    </div>
  );
};

const SimpleForm = props => {
  const { handleSubmit, pristine, reset, submitting } = props;
  return (
    <form onSubmit={handleSubmit}>
      <Field
        label="First Name"
        name="firstName"
        component={renderField}
        type="text"
        placeholder="First Name"
        format={value => value === 1 ? 'I\'m disabled' : value}
        disabled
      />
      <div>
        <button type="submit" disabled={pristine || submitting}>Submit</button>
        <button type="button" disabled={pristine || submitting} onClick={reset}>
          Clear Values
        </button>
      </div>
    </form>
  );
};

export default reduxForm({
  form: 'simple', // a unique identifier for this form
  initialValues: { firstName: 1 },
})(SimpleForm);
```
