### ISSUE TITLE
npm install -D serve-static

### ISSUE THREAD

**Issue by joeshub** [erikras/redux-form#243]
gh-pages branch is missing serve-static

**Comment by erikras** [comment]
Hmmm... `express` is grabbing that for me when I run `npm install`.
```
├─┬ express@4.13.3 
│ ├─┬ accepts@1.2.13 
│ │ ├─┬ mime-types@2.1.7 
│ │ │ └── mime-db@1.19.0 
│ │ └── negotiator@0.5.3 
│ ├── array-flatten@1.1.1 
│ ├── content-disposition@0.5.0 
│ ├── content-type@1.0.1 
│ ├── cookie@0.1.3 
│ ├── cookie-signature@1.0.6 
│ ├── depd@1.0.1 
│ ├── escape-html@1.0.2 
│ ├── etag@1.7.0 
│ ├─┬ finalhandler@0.4.0 
│ │ └── unpipe@1.0.0 
│ ├── fresh@0.3.0 
│ ├── merge-descriptors@1.0.0 
│ ├── methods@1.1.1 
│ ├─┬ on-finished@2.3.0 
│ │ └── ee-first@1.1.1 
│ ├── parseurl@1.3.0 
│ ├── path-to-regexp@0.1.7 
│ ├─┬ proxy-addr@1.0.8 
│ │ ├── forwarded@0.1.0 
│ │ └── ipaddr.js@1.0.1 
│ ├── qs@4.0.0 
│ ├── range-parser@1.0.3 
│ ├─┬ send@0.13.0 
│ │ ├── destroy@1.0.3 
│ │ ├── http-errors@1.3.1 
│ │ └── statuses@1.2.1 
│ ├── serve-static@1.10.0  <------------------- THERE
│ ├─┬ type-is@1.6.9 
│ │ └── media-typer@0.3.0 
│ ├── utils-merge@1.0.0 
│ └── vary@1.0.1 
```
What version of `express` is getting installed for you?

**Comment by joeshub** [comment]
Yea, same express version as you. Issue comes up with `node run dev` since the webpack-dev-server is requiring `serve-static` on line 4. 

btw I'm on node v0.12.7 and npm 2.11.3 on this machine.

**Comment by erikras** [comment]
I'm on `node 4.1.1` and `npm 3.3.6`.

**Comment by joeshub** [comment]
That explains it, I wonder if the `engines` directive could somehow help point out dependencies? I haven't used it much myself.

**Comment by erikras** [comment]
I'm gonna close this, since it's not _really_ a problem for this library, and someone using an older version of `node` or `npm` can probably figure out what they need to do to fix it.

**Comment by erikras** [comment]
I apologize. This is a silly thing to take a stand over. I'll add it. No harm in doing so.
