### ISSUE TITLE
Suggestion: Provide validation functions with access to form props

### ISSUE THREAD

**Issue by timhwang21** [erikras/redux-form#2430]
Currently, validation rules are provided (field value, object of all form values) as arguments. It would be nice if they were also given access to the props passed to the form. 

My use case is that I have several external props that are used in my validation functions. Normally, I can just write my validation functions inside my form and access `this.props.myStuff`, but there is an edge case where the props passed change. Currently `validateIfNeeded()` seems to happen before my component renders (and my rules recalculated based on the new props), so I'm getting incorrect results from my rules. (Worth noting: I'm using field-level rules).

I could solve this by writing a custom `shouldValidate()` which checks if the props in question change, and if so validate; however, my form is quite large, and I would be needlessly running validation if everything is based in `shouldValidate()`. It would be much easier to handle if rules had direct access to props.

Alternatively, an action dispatcher to run validation and to run warnings would also solve my issue.

**Comment by gustavohenke** [comment]
If I'm not mistaken, this was fixed by #2431!

**Comment by timhwang21** [comment]
You are not, that's my PR :)

**Comment by erikras** [comment]
Fix released as [`v6.5.0`](https://github.com/erikras/redux-form/releases/tag/v6.5.0).
