### ISSUE TITLE
onChange is not being executed in version 6.4.3

### ISSUE THREAD

**Issue by yanv1991** [erikras/redux-form#2434]
<Field onChange={this.onChange} ....
                  </Field>

I needed to downgrade the version to v6.3.0 and it is working again, not really sure from which version the issue is present.

**Comment by ruanyl** [comment]
Having the same issue, but I guess it will be fixed in next release by checking the code on `master`

**Comment by aderushev** [comment]
The same for me

**Comment by gustavohenke** [comment]
Fixed by #2385. Let's wait for a new release.
