### ISSUE TITLE
5.3.3: Clear submit errors on field change?

### ISSUE THREAD

**Issue by jonathan-stone** [erikras/redux-form#2436]
Thanks for this great library!

Is there a way to clear the form-level submit error when field data changes? 

The submit error no longer applies once the user has changed their entry, so I want to stop showing it to the user until they've tried submitting again. I haven't been able to find out how to do that.

Note, this code might be slightly off since I edited it for posting here, but any fix that would work for this would work for my site code.

Sample container code:
````
function mapDispatchToProps(dispatch, ownProps)
{
  return {
    mySubmitHandler: (values) =>{      
      return dispatch(asyncSubmit(values.name, values.email))
      .catch(err=>{
        return Promise.reject({_error: err.message});
      });
    }
  };
}
````

Sample component code:

````
const RegistrationDialog = (props) => {
  const { fields: {name, email},
    handleSubmit,
    mySubmitHandler,
    submitting,
    error  } = props;

return (
<form onSubmit={ handleSubmit((values)=>{return mySubmitHandler(values)}) }>
    <input type="text" {...name}/>
    <input type="text" {...email}/>
    { error && <ErrorMessageView message={ error }/> }
    <button>Submit</button>
</form>
);
````

Alternatively, is there a property to check whether any field data has changed since the submit error happened, that I can use to hide the error message component?

**Comment by gustavohenke** [comment]
You could try mapping the form values to your props, and when `componentWillReceiveProps` gets called:
- check if you have an error and the form values changed
- if yes, dispatch `reset` and `initialize` actions

Feels hacky? I know.

**Comment by jonathan-stone** [comment]
That would delete the user's entry, wouldn't it? If they only wanted to change one character, they'd have to retype the whole thing. That would not be acceptable.

**Comment by gustavohenke** [comment]
You can capture the form data before dispatching `reset`.

**Comment by jonathan-stone** [comment]
Thanks for your reply, I appreciate it. I ended up working around this issue by not using the form-level error at all, so I'm not sure if I will ever change the code back and implement your suggestion.

**Comment by Didericis** [comment]
In 7.1.2 there's a [`clearSubmitErrors`](https://redux-form.com/7.1.2/docs/api/actioncreators.md/#-code-clearsubmiterrors-form-string-code-) action creator that you can call in the `onChange` handler for your form:

```js
export default reduxForm({ 
  form: 'login',
  onChange: (values, dispatch, props) => {
    if (props.error) dispatch(clearSubmitErrors('login'));
  }
})
```

**Comment by saurishkar** [comment]
@jonathan-stone 
I was using _error prop to show errors for each field instead of directly mapping every field.
If you want to clear the field that is being changed, just dispatch stopSubmit action creator with the errors omitting the error for that particular field.

Ex: 
``
onChange: (values, dispatch, props) => {
    if(props.error) {
      const { error } = props;
      let omitErrors = [];
      if(error.field_name && values.order && values.order.field_name) {
        omitErrors = omitErrors.concat(['field_name']);
      }
      if(error.another_field && values.order && values.order.another_field) {
        omitErrors = omitErrors.concat(['another_field']);
      }
     
      if(omitErrors.length > 0) {
        dispatch(stopSubmit('GeneralDetails', {_error: _.omit(props.error, omitErrors)}));
      }
    }
  }
``

**Comment by The-Code-Monkey** [comment]
@Didericis that doesn't seem to do anything for me as my component i have rendered under a props.submitFailed condition doesnt disappear
