### ISSUE TITLE
[5.2.5] on submit validation - errors not returned properly

### ISSUE THREAD

**Issue by mir3z** [erikras/redux-form#2437]
I'm using submit validation as in [the example](http://redux-form.com/5.2.4/#/examples/submit-validation?_k=0t5fl4). I'm returning rejected promised:

```
return Promise.reject({ foo: ["bar1", "bar2"] });
```

but `foo` input `error` prop contains only `"bar1"` string whereas I expect `error` to by the array.

**Comment by danielrob** [comment]
Closing with bulk close of v5 issues. If this issue still requires action and/or also affects v6/7, please request a reopen with details or raise a new issue. v5 PR's are still welcomed.
