### ISSUE TITLE
Using keepDirtyOnReinitialize fails to update fields on successful submit

### ISSUE THREAD

**Issue by sslotsky** [erikras/redux-form#2438]
Version 6.4.3

My form is a `FieldArray` of notifications that can be removed with the trash can icon, as seen below. There is also a cancel button that resets the form.

![image](https://cloud.githubusercontent.com/assets/374078/21850966/c7934c2a-d7d2-11e6-8576-75c6e814525d.png)

The form's initial values come from a list of notifications from the server. I need to use `keepDirtyOnReinitialize`, because otherwise, if I destroy a saved notification and then click the cancel button, the destroyed notification will reappear.

While using `keepDirtyOnReinitialize` fixes this, it causes a new problem: when I add a new notification to the form and submit, the `id` field for the newly created notification does _not_ get updated on reinitialize.

The payload for the `INITIALIZE` action _does_ look correct, as you can see below. 

![image](https://cloud.githubusercontent.com/assets/374078/21851283/002b555e-d7d4-11e6-880a-ca84f15ce753.png)

The payload contains the `id`, so I expect that my hidden input will be updated, but as you can see below, the input has no value. 

![image](https://cloud.githubusercontent.com/assets/374078/21851388/8878696a-d7d4-11e6-86ac-86a831226120.png)

Therefore, if I click the trash can icon to destroy that item, the `id` is not present so the `destroy` call is never made:

```javascript
const renderNotification = (member, index, fields, destroy) => {
  const remove = () => {
    const { id } = fields.get(index);

    if (id) {
      destroy(id);
    }

    fields.remove(index);
  };
```

If I turn `keepDirtyOnReinitialize` back to false, then my `id` fields update as expected, but as I stated earlier, I need this flag to be `true` so that resetting the form does not revive destroyed items.

I can't link to the repo and it might be too much to post _all_ of the code, so let me know if there are specific areas you'd like to see. It would take some effort to create a smaller, shareable example that reproduces this.

**Comment by sslotsky** [comment]
Slight correction to the above.

I also tried simply using `enableReinitialize`, which _does_ prevent destroyed items from reappearing. However, this is not quite sufficient because if I have any unsaved notifications and then I delete a saved one, the unsaved ones disappear. This is the more accurate reason why I need to use `keepDirtyOnReinitialize`.

**Comment by sslotsky** [comment]
A little bit more evidence in case it's helpful. Below you can see that after the submit & reinitialize, my form re-renders with an `initialValues` prop which correctly contains the `id` of my newly created record.

![image](https://cloud.githubusercontent.com/assets/374078/21854143/463f2056-d7df-11e6-95bd-f9fab5c9aee0.png)

Now fast forward to the rendering of the rows. You can see below that `fields.get(3)`, which was created before the initial render, has the `id` property, but the newly created `fields.get(4)` is missing the `id` despite it being present in the `initialValues` when the form re-rendered.

![image](https://cloud.githubusercontent.com/assets/374078/21854237/ab96420e-d7df-11e6-9503-f39fe9bfcdc6.png)

**Comment by sslotsky** [comment]
I was able to reproduce this problem [in an example app](https://github.com/sslotsky/react-violet-forms/tree/redux-form-bug/examples/redux-form). 

If you comment out [this line](https://github.com/sslotsky/react-violet-forms/blob/redux-form-bug/examples/redux-form/app/Notifications/Form.jsx#L48), the hidden id input gets updated with the new value. But if the line is left in, then the hidden id input does not get updated.

I recorded a short video demonstrating what happens in both cases. [Please have a look](https://app.box.com/s/ckwusgm23i74my33o68kjet84j28wqx3)

**Comment by sslotsky** [comment]
Also in case it's not obvious please note that to run the example app you must be on the `redux-form-bug` branch and you must start it from the `examples/redux-form` folder.

**Comment by sslotsky** [comment]
@erikras I feel for some reason like I'm talking to myself in here :)

Hoping at least for some acknowledgement that somebody has read through the issue.

**Comment by gustavohenke** [comment]
Hey @sslotsky, thanks for your very descriptive issue :)

Unfortunately the Redux Form team is me and @erikras.
I went on a trip and now that I'm back I got 70+ notifications, so I'm still looping thru them.
Now imagine Erik which maintains other popular repos as well. It's not easy to stay up-to-date with the existing issues and new ones.

I'll make sure to try your demo later.

**Comment by erikras** [comment]
I would _love_ to be a full time OSS maintainer, but that doesn't really pay the bills, so this has only ever been a side project. And as the popularity and issue count have snowballed, there are too many for me to attend to personally. @gustavohenke, please let me know what you find.

**Comment by sslotsky** [comment]
Thanks guys! I totally get it. I've seen the issue count and I can only imagine. Just wanted to make sure it was seen. Every bit of effort you guys make is vastly appreciated.

**Comment by eladlevy** [comment]
@sslotsky I had issues with using keepDirtyOnReinitialize && enableReinitialize as well. Instead i'm 
initializing my form manually on every successful network request.
this assumes your'e working with REST api that returns the updated state of the entity on each request and the entity should be synced with the form.
```javascript

componentWillReceiveProps(nextProps) {
     //initializing form only when network request has finished
      if(this.props.entity.isFetching && !nextProps.entity.isFetching) {
          this.props.initialize('myEntityForm', nextProps.entity);
      }
 }
```

Let me know if it helps

**Comment by sslotsky** [comment]
@eladlevy I really appreciate the suggestion and it sounds like it could work. @gustavohenke in the meantime I just want to make sure the issue doesn't go stale. If you want to give me an idea where to look I'd be glad to start debugging it and gather more clues.

**Comment by gustavohenke** [comment]
Hi @sslotsky, I'm sorry for this delay.
Probably this issue went out of sight after a few days and I forgot about it.

If I understood your (long) issue is that you have problems when you delete an item, that's why you're using `keepDirtyOnReinitialize`, but this causes problems with just added items...

Fortunately, we may share some experience here, as I recently implemented a similar form.
- I'm not using `keepDirtyOnReinitialize`
- To add a new item, I just `array.push( field, data )` (just like you're doing in your example)
- To remove an item, an action is dispatched to do the server process and filter the list + `array.remove( index )` is used in case the item was never persisted
- After a successful submit, I reload the list, replacing the items that were added/changed.

I hope this helps you a little bit.

**Comment by sslotsky** [comment]
Thanks for the reply @gustavohenke. That sounds exactly like what I'm doing, with one notable exception: I have a `Cancel` button that calls `reset()`. Using the setup that you describe, when I reset the form, items that I've deleted will _reappear_ on the form. Switching `keepDirtyOnInitialize` fixes that, but causes another problem that I described above.

Most of what I've posted previously was meant to be evidence that could help guide the investigation. My apologies if it seems verbose and obscures the real issue.

**Comment by gustavohenke** [comment]
How does your removal code look like?

**Comment by sslotsky** [comment]
As posted above:

```javascript
const renderNotification = (member, index, fields, destroy) => {
  const remove = () => {
    const { id } = fields.get(index);

    if (id) {
      destroy(id);
    }

    fields.remove(index);
  };
```

The `destroy(id)` call is an action creator that deletes the item from the server. Now that I review that action creator, however, I see that it's not removing the `notification` from the _store_. I updated that and it seems to work now. Can't believe I missed it before. Of course I feel silly now.

Thanks so much for talking through this with me and leading me to my error!

**Comment by gustavohenke** [comment]
D'oh! I missed your removal code back in the OP as well 😁
