### ISSUE TITLE
Call success callbacks through form props

### ISSUE THREAD

**Issue by andynoelker** [erikras/redux-form#2439]
Right now, you need to pass the `onSubmitSuccess` and `onSubmitFail` callbacks to the reduxForm config object - it would be really cool if we could set it on the form itself itself also. I am at least attempting to do so with the new `<Form />` component and remote submit but it does not work - I assume this is a feature that would need to be added. So it would look something like this:

```
class MyForm extends Component {
  submitSuccess = () => {
    // party!
  }

  submitFail = () => {
    // cry
  }

  render() {
    return (
      <Form 
        onSubmit={handleSubmit(foo)} 
        onSubmitSuccess={this.submitSuccess} 
        onSubmitFail={this.submitFail}
      >
        <Field ... />
      </Form>
    );
  }
```
Thoughts?

**Comment by gustavohenke** [comment]
Your function is able to decide on its own what to do after it finishes, eg

```js
class MyForm extends Component {
  foo () {
    return triggerRequest(...).then(() => {
      // party!
   }, () => {
      // cry :'(
   });
  }

  render() {
    return (
      <Form onSubmit={foo}>
        <Field ... />
      </Form>
    );
  }
}
```

**Comment by andynoelker** [comment]
@gustavohenke thanks for the response. I'm aware of that behavior, just making a feature request for those new props to be added as an alternative way of specifying the callbacks. I think it would line up nicely with the current API and make that process look cleaner. However, if the maintainers of this project disagree that it would be a good addition, then it's fair enough.
