### ISSUE TITLE
Error with onSubmit using action creator

### ISSUE THREAD

**Issue by nealoke** [erikras/redux-form#2441]
**Simplified code**
```
import { Field, reduxForm } from 'redux-form';

class Property extends Component {
	constructor(props) {
		super(props);
		
		this.saveOnChange = this.saveOnChange.bind(this);
		this.handleSubmit = this.handleSubmit.bind(this);
	}

	handleSubmit() {
		console.log('form submitting');
	}

	saveOnChange() {
		console.log('should auto save');
		this.props.dispatch(this.props.submit('propertySettings'));
	}

	render() {
		const { handleSubmit } = this.props;

		return(
			<form onSubmit={handleSubmit(this.handleSubmit)}>
				// Stuff goes here

				<div onClick={this.saveOnChange}>(just for example it is with a div)</div> // <-- Get's errors
				<button type='submit'>Via button</button> // <-- Work's fine
			</form>
		);
	}
}
```

Gives me the following **errors** when submitting via the div

![errors](https://cloud.githubusercontent.com/assets/17417414/21862583/1ee6a654-d83a-11e6-8c94-66756dc517e5.png)

**Comment by mpmlj** [comment]
@nealoke 
Maybe my comment from https://github.com/erikras/redux-form/issues/2408 can help (last comment).

Cheers

**Comment by nealoke** [comment]
@mpmlj Thanks, but i'm not sure how it helps my case. Could you maybe explain how?

**Comment by nealoke** [comment]
After updating from 6.3.x to 6.4.3 (latest atm), the issue was resolved. Was also documented in the [release's doc](https://github.com/erikras/redux-form/releases/tag/v6.4.0)

**Comment by keenondrums** [comment]
@nealoke I'm having the same issue with 7.2.0
