### ISSUE TITLE
Incompatibility with ESLint's "no-throw-literal" rule

### ISSUE THREAD

**Issue by mpmlj** [erikras/redux-form#2442]
Hi,

Async validation example ( http://redux-form.com/6.4.3/examples/asyncValidation/ ) advises to throw an object on error, however eslint's "no-throw-literal" (ex. part of AirBnb's eslint rules) will return an error in this case, expecting an Error object only. However, when trying to throw an Error obj.  from the async validator, the validator fails (uncaught exception).

For now, as a workaround I have to use 
```
      /* eslint no-throw-literal: "off" */
      throw { email: 'Unknown error :(' };
```

Please advise if it is possible to throw an Error?
If not, please consider this to be a feature request.

Thanks
D

P.S.
Sorry for several words "error" on every line ;-P

**Comment by gustavohenke** [comment]
You could do this instead:

```js
return Promise.reject({ foo: "bar" });
```

**Comment by mpmlj** [comment]
@gustavohenke 
That worked! Thank you.

Closing the ticket as the issue is resolved, just 2 notes: 
- Should this be considered a workaround and thus, something that can be broken in the future?
- If this is just one another official approach without any downsides as compared to throw {} , then worth adding to the docs as there's at least one obvious benefit - compliance with http://eslint.org/docs/rules/no-throw-literal (part of airbnb's rule-set as well).

Thanks again!

**Comment by gustavohenke** [comment]
`Promise.reject()` is just like `throw`, but it creates a new promise.
So, it isn't a workaround IMO.

**Comment by danielrob** [comment]
@idangozlan call that `AsyncValidationError` and off the top of my head I think PR's to clean this up are 🚀.
