### ISSUE TITLE
Incomplete value in redux side

### ISSUE THREAD

**Issue by aimarjs** [erikras/redux-form#2443]
Hi,

I have an issue. I'm trying to use [react-google-places-suggest](https://github.com/xuopled/react-google-places-suggest) in Redux-Form as component inside Field. If i start typing location, i'll get the suggestions and if i choose one from the list, it will be selected to the Field. If i check from Redux DevTool, i'll see that in redux-form/FOCUS I get the value but only the part i typed and not the full location name i have chosen from the list of suggestions. If i Focus back to this Field and Blur out, i'll get the full name of the location in redux-form/BLUR. See the screencast.. 

![buh2](https://cloud.githubusercontent.com/assets/25065245/21865112/0060c934-d845-11e6-8932-9396d9d727aa.gif)

Is this known issue or am i doing something wrong?

**Comment by erikras** [comment]
You must not be managing the mappings to `onChange` and `onBlur` properly. Both can just pass the currently selected value.

**Comment by aimarjs** [comment]
Not quite sure if i understood what you mean, @. I'm not managing onChange or onBlur more than what Redux-Form is doing by default. I have pretty basic setup. I have ContactForm.js where are all the redux-form logic and i attach react-google-places-suggest as a component.

<div className="form-group" style={styles.autoCompleteStyle}>
    <Field
       name="endLocation"
       component={Autocomplete}
     />
 </div>

Autocomplete is actually basic react-google-places-suggest setup like suggested here: https://github.com/xuopled/react-google-places-suggest

Can you please elaborate a bit? Much appreciated!

Sorry for closing by mistake. I'm new here.. a bit lost :)

**Comment by aimarjs** [comment]
Managed to fix it by changing {...input} props as last inside <input />

`        <GooglePlacesSuggest
          googleMaps={googleMaps}
          onSelectSuggest={this.handleSelectSuggest}
          search={search}
        >
            <div className={formClass}>
              <label>{label}</label>
              <input
                className="form-control"
                value={search}
                placeholder={label}
                onChange={this.handleSearchChange}
                {...input}
              />
            </div>
        </GooglePlacesSuggest>`
