### ISSUE TITLE
blur on a radio cause redux-form to set incorrect value

### ISSUE THREAD

**Issue by ruanyl** [erikras/redux-form#2444]
Steps to reproduce: take the `Simple` example

```
1. set a default focused element
<label><Field ref={this.setFocus} name="sex" component="input" type="radio" value="female"/> Female</label>

setFocus(el) {
  const found = findDOMNode(el)
  if(found) {
    found.focus()
  }
}

2. click anywhere else to make the radio to lose focus
3. the value of field changed unexpected
```

See the screenshot:

![redux-form](https://cloud.githubusercontent.com/assets/486382/21865782/34cd9264-d850-11e6-99c9-465fe41456b7.gif)

The reason: `blur event` of a radio has the value property of the element. `<Field value="female' type="radio">` which will be used to update the form value state when blur.

I did a quick fix to it because this small issue bugs me a lot. Will make a pull request later.

**Comment by erikras** [comment]
Fix released as [`v6.5.0`](https://github.com/erikras/redux-form/releases/tag/v6.5.0).
