### ISSUE TITLE
Render multiple independant redux-form inside parent-form

### ISSUE THREAD

**Issue by m1m6** [erikras/redux-form#2446]
I would like to render multiple redux-forms inside parent form which will be responsible on submitting the form,

So for example i have:

- Parent form
-- first form
-- second form

the three above forms are redux-forms, the first and second forms are independent and work perfectly alone, However if tried to render the first and second forms inside the parent form

I got the following: 
![forms](https://cloud.githubusercontent.com/assets/9281675/21868715/d5dede22-d85c-11e6-854a-8e2cd93e55c9.png)

What i expect to see is all fields of the first and the second forms are merged into the parent form, and the parent form will be responsible on submitting the form when all fields are filled,

I tried to solve this problem by passing the props of parent form to the first and second form, and this what i got !!
![parent](https://cloud.githubusercontent.com/assets/9281675/21868997/1ff8ce90-d85e-11e6-8ebe-2de4d9927a4e.png)

Wow, That's what i want!!, but here i have a small issue! when onBlur occur on any field an 
`asyncValidate function passed to reduxForm must return a promise` exception is thrown although i'm not used asyncValidation anywhere in my App!!

Here's my code: 

`class ParentForm extends React.Component {
  render(){
    let props=this.props;
    console.log(props);
      const {handleSubmit,handleSubmit2 ,afterSubmit,handleSubmitCallBack,signupHandler, pristine,   reset, submitting } = props
      return (
          <form onSubmit={handleSubmit(handleSubmit2)} >
            <div className="forms-wrapper">
              <div>
                <Row>
                  <Col md={6} >

                    <FirstForm
                      {...props}
                      hasParent={true}
                      />
                  </Col>
                </Row>
              </div>
              <div>
                <div>
                  <SecondForm hasParent={true} {...props} />
                </div>
              </div>
              <button type="submit" disabled={submitting} onClick={handleSubmit(handleSubmit2)}        >Submit</button>
            </div>
          </form>
            )
  }
}
`
Any help plZ!!

**Comment by m1m6** [comment]
@erikras  can u please advise?

**Comment by erikras** [comment]
Form nesting, whilst discussed as a possible future feature, is not currently supported.

Why not abstract away _just the fields_ of the sub-forms into a [`<FormSection/>`](http://redux-form.com/6.4.3/docs/api/FormSection.md/)? Then, if they need to be used separately (not inside the `ParentForm`), they could be individually decorated with `reduxForm()`, and they can also exist inside the `ParentForm`.

**Comment by m1m6** [comment]
@erikras Thanks for your reply, Actually i tried that, but what if i need validation on fields of subforms ? initial values, which needed to be supplied by redux-form ? 


https://github.com/erikras/redux-form/pull/1942#issuecomment-272483671

**Comment by gustavohenke** [comment]
Hi @m1m6, I see your issue here is the same we discussed over #1942.
Is there anything else we could help with?

**Comment by gustavohenke** [comment]
ping @m1m6

**Comment by m1m6** [comment]
No, Thanks i found the answer in your reply there 💯  :)

**Comment by nguyenchauhuyen** [comment]
the same problem
