### ISSUE TITLE
Is there a PropTypes validation shape for the FieldArray fields prop?

### ISSUE THREAD

**Issue by vdh** [erikras/redux-form#2447]
[In the docs for `FieldArray`](http://redux-form.com/6.4.3/docs/api/FieldArray.md/#fields-props), the `fields` object is described as a "pseudo-array". Is there a `PropTypes` validation shape available for this object?

I spotted `array` already in `src/propTypes.js`, but it doesn't include all the actions (and includes one not in the docs for `fields`, called `splice`). I'm not sure how that one relates to `FieldArray`.

I'd imagine it would look something like this:
```js
const { /* ... */ number, func, shape } = PropTypes
// ...
  fields: shape({
    forEach: func.isRequired,
    get: func.isRequired,
    getAll: func.isRequired,
    insert: func.isRequired,
    length: number.isRequired,
    map: func.isRequired,
    move: func.isRequired,
    pop: func.isRequired,
    push: func.isRequired,
    remove: func.isRequired,
    removeAll: func.isRequired,
    shift: func.isRequired,
    swap: func.isRequired,
    unshift: func.isRequired
  }),
// ...
```

**Comment by erikras** [comment]
Published fix in [`v7.1.0`](https://github.com/erikras/redux-form/releases/tag/v7.1.0).
