### ISSUE TITLE
Question about async validate on submit

### ISSUE THREAD

**Issue by x1a0** [erikras/redux-form#245]
Hi,

For example I have a signup form. After user click `signup` I submit the form by firing a `SIGNUP` async action. Then I need to use the returned promise from `dispatch()` to know if anything goes wrong for showing form errors.

According to [doc of `redux`](http://rackt.org/redux/docs/advanced/AsyncActions.html) it seems the good patten to handle async action failure in this case is firing a `SIGNUP_FAILURE` action when the api call fails. So component should not rely on the return of `dispatch`, instead it should listen on state change.

Is the `redux-form` way of handling submit validation anti-patten here?

**Comment by smashercosmo** [comment]
That was the first question, that came into my mind when I first saw redux-form API. That looks like not a redux way of doing things.

**Comment by erikras** [comment]
My intent was to make `redux-form` as unopinionated as possible about _how_ you are doing your async validation.

However, let's explore this. What would the API look like with a more redux-y approach? You would provide `asyncSuccess`, `asyncFailure`, `submitSuccess`, and `submitFailure` action types to the `redux-form` reducer for each of your forms?

**Comment by x1a0** [comment]
> You would provide asyncSuccess, asyncFailure, submitSuccess, and submitFailure action types to the redux-form reducer for each of your forms? As well as dictate that validation errors be at a certain key in the action?

@erikras Yes that's basically what I have in mind. Instead of using returned promise, the form reducer should be configured to listen on certain actions and get error data from there.

**Comment by x1a0** [comment]
@erikras Today I gave the idea a try by using the `plugin` API:

#### Reducer:

```
export default combineReducers({
  ...,
  form: formReducer.plugin({
    login: (state, action) => { // login form error reducer
      switch (action.type) {
        case LOGIN_FAILED:
          const copy = { ...state };
          copy.password.error = 'wrong password'; // <-- this does not work - this.props.password.error is undefined in render()
          copy._error = 'login failed'; // <-- this works - this.props.error is the error set here in render()
          return copy;

        default:
          return state;
      }
    }
  }),
  ...,
});

I got stuck here - cannot figure out how to make the error property on a filed passed down.

**Comment by chriserik** [comment]
@x1a0 Currently, field-level validation errors are not retrieved from the Redux store. Therefore your example will not work unfortunately.

**Comment by x1a0** [comment]
@chriserik Thanks. Does that mean if i set some custom property in state it will work? For example instead of setting `state.fieldFoo.error`, set `state.fieldFoo.myError`.

**Comment by ooflorent** [comment]
I'm closing this issue because we try to use the issue tracker for bug reports and feature requests.
