### ISSUE TITLE
component={renderField} no longer triggers change

### ISSUE THREAD

**Issue by MrRoyce** [erikras/redux-form#2455]
I think this may be related to the other issues regarding the new? changes to the  onChange handler, but 'all of a sudden', the fields on all my forms stopped working.  

I'm using the renderField for synchronous validation and if I change the atttribute back to component="text", it works fine.

Here is my renderField function:

```javascript
    const renderField = ({ input, opts, type, placeholder, className, meta: { touched, error } }) => (
        <div>
          <input {...input} {...opts} type={type} placeholder={placeholder} className={className}/>
          {touched && ( error && <span className="gt-error"><i className="fa fa-exclamation-circle" /> {error}</span>)}
        </div>
    );
```

And I call it with:
```javascript
<Field opts={opts} name={props.controlId} component={renderField} type={type} className="form-control" placeholder={props.placeholder}/>
```

**Comment by MrRoyce** [comment]
Also, I just noticed that when I remove  {...input} from the <input..> the field is editable, but the passed initial values aren't loaded.

**Comment by erikras** [comment]
> I'm using the renderField for synchronous validation and if I change the atttribute back to component="text", it works fine.

Presumably you really mean `component="input"`.

I don't see anything obviously wrong with your `renderField()` function. You don't have a `value` key in your `opts` value, do you?

Try swapping the order: put `{...opts}` before `{...input}`.

**Comment by MrRoyce** [comment]
Yes, sorry, that was a typo, I meant component="input".

The opts object only has a 'disabled' attribute that is set from a parent.  I tried swapping the opts and input, but it's still not working.  

Is there anything else I can check?

**Comment by MrRoyce** [comment]
The problem was I had renderField defined as a constant inside a generic reusable 'Text' component.  When I moved the renderField out of the component. It works fine.  Closing.

**Comment by kylanhurt** [comment]
Edit: @MrRoyce, nevermind, I figured out what you meant by your solution. I had to bring the renderField function **outside** of my class. Not sure why but oh well. I will keep my post below in here in case anyone else stumbles upon the same issue.

@MrRoyce , can you elaborate a bit? I have a similar set up and I do not believe that I am using a generic "text" component. If I change the <Field component={renderField}... to <Field component="input", then my generic renderField function will apply the <Field> element to the renderField template (making renderField more or less useless).

When I remove the {...input} part from renderField, then it appears that I lose any onChange, focus, and blur Redux actions (which I assume come with redux-form).

Here is my relevant code:

`
	const renderField = ({ input, label, type, placeholder, className, meta: { touched, error, warning } }) => (
	  <div className="form-group">
	    <label htmlFor={label}>{label}:</label>
	    <div>
	      <input type={type} placeholder={placeholder} className={className} {...input} />
	      {touched && ((error && <span>{error}</span>) || (warning && <span>{warning}</span>))}
	    </div>
	  </div>
	)

    if (!this.props.auth.authenticated) {
    	return(
			<div className="jumbotron" style={{overflow: 'hidden'}}>
			    <div className="col-lg-4 col-sm-12" id="home-signup-form">
			        <form onSubmit={handleSubmit(loginUser)}>
			            <p>Please fill out the fields below to create an account:</p>			            
		                <Field className="form-control" name="email" label="Email" component={renderField}  id="login-email" type="email"  placeholder="user@example.com" />
						<Field className="form-control" name="password" label="Password" component={renderField} type="password"  id="login-password" placeholder="*******" />			                
						{error && <strong>{error}</strong>}
			            <button type="submit" className="btn btn-primary" disabled={this.pristine || this.submitting}>Login</button>
			            <button type="button" className="btn btn-secondary" disabled={this.pristine || this.submitting} onClick={this.registerUser.bind(this)}>Register</button>
			            <input type="hidden" name="_token" value="{{_token}}"></input>
			        </form>
			    </div>
			</div>
		)
	}
`

Right now when the page first loads (and before Chrome inserts an email and password value that is saved to my browser) I cannot insert any text into either field. Once Chrome inserts the saved email and password pair, it will not let me change the value. Any help would be appreciated.

**Comment by adred** [comment]
You can make `renderfield` a static method of your class then in your render method you do:
```
<Field
        name={this.props.name}
        type='{this.props.type}
        component={(field) => MyCustomField.renderField(field, this.props)} />
```
