### ISSUE TITLE
Typescript Usage - Compiler Error

### ISSUE THREAD

**Issue by LukeSheard** [erikras/redux-form#2457]
I'm trying to setup a new boilerplate working with typescript, but when I import `redux-form` I get errors from the typescript compiler:

```
ERROR in ./~/lodash-es/_cloneBuffer.js
4:25-32 exports is not allowed in EcmaScript module: This module was detected as EcmaScript module (import or export syntax was used). In such a module using 'exports' is not allowed.
```

I have @types/{redux,redux-form,lodash-es} installed. Has anyone seen this before?

**Comment by gustavohenke** [comment]
[The TypeScript definition is currently hosted at DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/redux-form).

**Comment by gustavohenke** [comment]
Some context: #1211
