### ISSUE TITLE
Array values are null after the first one( V 5.2.3 )

### ISSUE THREAD

**Issue by pushqin** [erikras/redux-form#2458]
Hi, i am using version 5.2.3 and have the following problem.

I am using a table with button that adds new rows, each row consist of 'name', 'address'
All of the fields are mandatory and the table must have at least one row filled.
The validation work fine.

Here is all my setup.

I want that one row will be visible to user on first page load.
```
export const initialValues = {
	myFieldArray: [{}]
};
```

I am adding new row with the following code.
`myFieldArray.addField()`

The first object in myFieldArray, is looks loke following

```
{
  "name": {
    "_isFieldValue": true,
    "visited": true,
    "value": "asd",
    "touched": true
  },
  "address": {
    "_isFieldValue": true,
    "visited": true,
    "value": "asd",
    "touched": true
  }
}

```

But the second one that added with myFieldArray.addField() looks as following
```
{
  "_isFieldValue": true,
  "name": {
    "visited": true,
    "_isFieldValue": true,
    "value": "sdf",
    "touched": true
  },
  "address": {
    "visited": true,
    "_isFieldValue": true,
    "value": "sdfsdfs",
    "touched": true
  }
}

```

It has the   **"_isFieldValue": true**  at the array level,then when i click on submit the code goes to 

`function getValuesFromState(state)`

that return me array with one normal object and the second one is null because of following line of code

`(0, _fieldValue.isFieldValue)(arrayField) ? arrayField.value : getValuesFromState(arrayField);`

that returns **arrayField.value**  that is always null for all the array items except the first one.

Any help here appriciated.

Thanks.

**Comment by danielrob** [comment]
Closing with bulk close of v5 issues. If this issue still requires action and/or also affects v6/7, please request a reopen with details or raise a new issue. v5 PR's are still welcomed.
