### ISSUE TITLE
How to check that Async blur validation was successful?

### ISSUE THREAD

**Issue by michaelrambeau** [erikras/redux-form#246]
Hello Erik and all other contributors, thank you for you great work.
I use the "Async blur validation" feature to check if a username already exists.
If the validation succeeds, I'd like to display something like a check mark icon inside the field.

But I cannot find any flag that tells me that the validation on the username field succeeded.

I may have missed it but is there a way to know that async valid was successful ?
This request seems to be related to #244
Thank you in advance!

**Comment by olimsaidov** [comment]
You can use form's `asyncValidating` prop with `touched` and `valid` props of username field.

**Comment by erikras** [comment]
Yes, @olimsaidov is correct.
```js
const {fields: {username}, asyncValidating} = this.props;
const usernameHasValidated =
  username.touched && // field has been visited and blurred
  username.valid &&   // field has no error
  !asyncValidating;   // not currently validating
```
This _should_ never be true before async validation has be run, since the same `onBlur` event that triggers `touched` to be true will also trigger `asyncValidating` to be true.

**Comment by michaelrambeau** [comment]
Thank you very much, it works.
What I was missing was that point: 
`username.touched` means `field has been visited and blurred`,

Thank you for the explanation!
