### ISSUE TITLE
Hydrating on client with errors from the server

### ISSUE THREAD

**Issue by Limess** [erikras/redux-form#2463]
Hello, 

We're trying to migrate a project which previously used vanillaJS form handling to `redux-form`.

We're constrained by having to support non-js submissions (variety of reasons, has to fallback for all devices and we need to enforce redirects after submission). As such, we currently use the default actions of forms, rather than AJAX. We also do _not_ disable form submission due to UX decisions based around accessibility.

This means we need to rehydrate our forms with errors on fields, as well as errors on specific fields from the server.

Is there any way to hydrate a form using the `reduxForm` HoC with a `SubmissionError`, and an object of per-field errors, which are then persisted until the user blurs the relevant field? e.g. something like

```js
state.signIn.errors = {
    displayName: someError,
    password: someError
    _error: someServerSubmissionError
};

connect((state) => ({
    initialValues: state.signIn.data, 
    initialErrors: state.signIn.errors
})(
    reduxForm({name: 'signIn'})(
        SignInForm
    )
)
```

 Something similar to `initialValues` but for errors? If this were available, we would use it, continue to use our exisiting server-side validation, and disable server-side validation in `redux-form`.

Alternatively, is there a sensible way of using the actions available from `redux-form` to do this on both client and server?

Happy to provide further information and examples if that'll help.

**Comment by gustavohenke** [comment]
One thing you could is to use the `stopSubmit` action creator:

> #### `stopSubmit(form:String, errors:Object)`
> Flips the submitting flag false and populates submitError for each field.

http://redux-form.com/6.4.3/docs/api/ActionCreators.md/

**Comment by Limess** [comment]
@gustavohenke I just tried this, however `submitError` seems to be private except for the `reduxForm` HoC wrapped component, and even then it only seems to be provided with the `_error` property.

**Comment by Limess** [comment]
In case this helps anyone else:

We ended up leaving our server hydrated errors _outside_ of `redux-form`, passing an `initialErrors` object to each `Field` input component.

This then took precident based on `redux-form` props:

```js
const TextInput = (props) => {
    ...
    const {initialError, error, pristine, touched} = props;
    const shownError = (pristine && typeof initialError !== 'undefined') && (initialError !== true)
        ? initialError
        : touched && error;

   return (
      ...
     <FormError error={shownError} />
   );
};
```

Attempting to keep the error in `redux-form` state didn't make sense for us, as there's no way for the errors to occur on the client (they occur on normal form posts and are returned in a separate object managed by a separate reducer), so they get overwritten by validation.
