### ISSUE TITLE
props.input.onChange doesn't update value of element first time if component is inline

### ISSUE THREAD

**Issue by notgiorgi** [erikras/redux-form#2468]
If I do this:

```javascript
let MyInput = props => <input onChange={e => props.input.onChange(e.target.value)} />

let Form = ({
	handleSubmit
}) => (
	<form onSubmit={handleSubmit}>
		<Field 
			name="choice_gr"
			component={MyInput}
		/>
	</form>
)
```

It works fine, but if I do this:

```javascript
let Form = ({
	handleSubmit
}) => (
	<form onSubmit={handleSubmit}>
		<Field 
			name="choice_gr"
			component={props => <input onChange={e => props.input.onChange(e.target.value)} />}
		/>
	</form>
)
```

The first time I type something, even though the store updates, the value in the input box stays blank.

JSBins to reproduce:

- Working example: https://jsbin.com/towavex/edit?js,output
- Bugged example: https://jsbin.com/kugibi/edit?js,console,output

You can track the store using redux devtools extension.

**Comment by eligolding** [comment]
Seem like what's happening here is actually warned about [in the docs:](http://redux-form.com/6.4.3/docs/api/Field.md/#2-a-stateless-function)
> **You must define the stateless function outside of your render() method, or else it will be recreated on every render and will force the Field to rerender because its component prop will be different.** If you are defining your stateless function inside of render(), it will not only be slower, but your input will lose focus whenever the entire form component rerenders.

**Comment by gustavohenke** [comment]
It's quite what @eligolding said.

The first time you type, the form changes from pristine to dirty, and your `<Field>` gets assigned a new component - different function with same contents = re-rendering.
The second time you type, there's no form-level re-rendering; so it's the same component, same input, so you're keeping the `value` already there.
