### ISSUE TITLE
Wraping Field in custom element.

### ISSUE THREAD

**Issue by Morkowski** [erikras/redux-form#2472]
I want to create Checkbox component which uses redux-form and react-toolbox. I also want to hide libraries details.

So instead:
```
import { Checkbox } from 'react-toolbox/lib/checkbox'; // or toolbox checkbox with mapped props
import { Field } from 'redux-form';

<form>
    <Field component={Checkbox} name="myCheckbox" />
</form>
```

I want wrap it in separate Checkbox component and use it like that:

```
import { Checkbox } from 'myCheckbox';

<form>
    <Checkbox name="myCheckbox" />
</form>
```

But I couldn't find how redux-form parse form and register its fields. Is it even possible to wrap Field component in diffrent component?

**Comment by gustavohenke** [comment]
Just create your own field wrapper component.

See [this example](http://redux-form.com/6.4.3/examples/material-ui/), it's very close to what you want, but with Material UI instead of React Toolbox 😉

**Comment by jacobk** [comment]
The example linked doesn't answer the question. The MUI example uses the first approach outlined in the asked question. i.e. directly use `Field` everywhere and pass the wrapper in the `component` prop - compared with hiding the usage of `Field` inside the wrapping component.

It would probably look something like
```javascript
# CustomField

import { Field } from 'redux-form';

const CustomInput = (props) => ( ... );

export default CustomField = (props) => <Field component={CustomInput} {...props} />
```

I was thinking about the same thing recently and haven't had time to read the code yet. But `reduxForm` needs to be able to detect the component as a `Field`.

Anyway, maybe it's a Q for stackoverflow.

**Comment by jacobk** [comment]
Seems like field registration is done using context and not scanning and cloning `children` which means it should work at arbitrary depth of wrapping.

I'll give it a try.
