### ISSUE TITLE
Automatically capture onChange and value props

### ISSUE THREAD

**Issue by notgiorgi** [erikras/redux-form#2476]
In order to use some custom input component with `Field` I have to create a wrapper component like this

```javascript
const CustomTextField = ({ input }) => {
     return (
        <TextField
            value={input.value}
            onChange={(e, newVal) => input.onChange(newVal)}
        />
    )
}

/* and then: */
<Field component={CustomTextField} name="foobar" />
```

It'd be very convenient if redux-form automatically mapped those props for me, so that I could do

```javascript
<Field comoponent={TextField} name="foobar" />
```

That would be like a default interface for the component passed to `Field`'s component prop

**Comment by gustavohenke** [comment]
We don't know what your custom component will look like, so this cannot be done.

For example, in a React Bootstrap project I'm developing, I prefer to wrap all its possibilities inside my custom field component:
- label
- feedback icon
- help block
- validation state
- and the input itself.

By doing what you suggest, I would lose such freedom, as the root element needs to be the input itself.

Also, most times you can just spread the props:

```js
const CustomTextField = ({ input, meta, ...rest }) => (
  <TextField
    { ...input }
    { ...rest }
    error={ meta.touched && meta.error } />
);
```

Simple, huh?

**Comment by notgiorgi** [comment]
@gustavohenke fair point.

So is wrapping and spreading `input` prop recommended way to do it? Are there any caveats you can describe?

Also do you wrap every component from form library? How you structure them?

I'd appreciate recommendations very much!
