### ISSUE TITLE
Outdated ESLint rules

### ISSUE THREAD

**Issue by huan086** [erikras/redux-form#2480]
The `eslint-config-rackt` repo is gone, and it looks like `eslint-config-airbnb` is the recommended rules now.

The `eslint-config-rackt` rules did not include `guard-for-in`, and did not catch the flawed logic in structure/immutable/setIn, which loops through an array with `for-in` instead of `for`. The index is thus a string and subsequently added by one, then used in a comparison that would always return true.

I think it's time to switch to `eslint-config-airbnb` to catch more bugs.

@Reanmachine take note of the difference between `for` and `for-in`

**Comment by gustavohenke** [comment]
It seems like this was solved by #2680, which switched to `react-app` config.
