### ISSUE TITLE
Empty values not producing a payload

### ISSUE THREAD

**Issue by jetpackjarrett** [erikras/redux-form#2485]
When I try and delete a value from a field, the empty value does not produce a payload which causes the form values not to update, resulting in the final value after blurring the field is the last state.

Example, if the value is 123 and I backspace 3 times, then a blur is triggered, the value is now 1. If I focus the field again and backspace once, then blur, the value is still 1.

![screenshot 2017-01-20 13 59 57](https://cloud.githubusercontent.com/assets/38572/22161557/e052c7fc-df18-11e6-89cb-0eb95d5a40c2.png)

**Comment by danielrob** [comment]
@jetpackjarrett please provide a runnable example of your issue.

**Comment by danielrob** [comment]
Closing this due to non-response. I don't think there is enough actionable information in this report to identify a bug with redux-form.
