### ISSUE TITLE
Add `formName` to `props.meta` in wrapped components

### ISSUE THREAD

**Issue by nktssh** [erikras/redux-form#2489]
Is it ok to add `formName` to `props.meta`?

I have identical `Field`s which i can reuse in different forms. They laying on the same key in form so idea and few `Field`s are connected with each other so it will be good to extract them into separate components. But they are not only shared the same functionality - output from one field is dependent from another field (e.g. complex autocomplete by few fields). So I need to connect this component with store. But in that case I need to provide `formName` manually.

It will cost nothing since `form ` parameter in `redux-form` decorator is just a string,

**Comment by gustavohenke** [comment]
This will be possible starting with the next version. See #2400.
