### ISSUE TITLE
key prop in field when using radio buttons

### ISSUE THREAD

**Issue by tamagokun** [erikras/redux-form#249]
Using v3.0.5

![screen shot 2015-11-09 at 10 57 00 am](https://cloud.githubusercontent.com/assets/487333/11038376/a56c8eda-86d0-11e5-8eb9-47e53d419788.png)

Getting a key passed is generally ok, but in this case the field is a set of radio buttons, and each radio button input is getting passed the same key, throwing a React error:

```js
<div>
  <input type='radio' {...alignment} value='left' checked={alignment.value == 'left'} />
  <input type='radio' {...alignment} value='center' checked={alignment.value == 'center'} />
  <input type='radio' {...alignment} value='right' checked={alignment.value == 'right'} />
</div>
```

```
Warning: flattenChildren(...): Encountered two children with the same key, `.$alignment1447084163136`. Child keys must be unique; when two children share a key, only the first child will be used.
```

I should note that I am passing `formKey` into `reduxForm`.

**Comment by erikras** [comment]
Ooh, good bug! Thanks. :+1:
