### ISSUE TITLE
Selected option will be restore to unselected status

### ISSUE THREAD

**Issue by weichenghsu** [erikras/redux-form#2494]
As title, the selected option will be restored to unselected status
![image](https://cloud.githubusercontent.com/assets/23323373/22237424/90547174-e1c0-11e6-9236-96d1630c84a3.png)

And `onChange` method has no effect for the official tutorial example.

My use case is that when a user picks a value from the dropdown. It should fire an action to fetch other data and render on another form

        const chooseTable = ({items, meta:{touched, error}}) => (
                <select
                    onChange={event => {
                        console.log(this.props.fields);
                        this.props.tableNameOnChange(event.target.value);
              }}>
                    <option value="">Select</option>
                    {

                        items.map((item :any, i: integer) =>
                            <option key={item.id} value={item.id}>{item.name}</option>
                        )
                    }
                </select>
        )

                        <Field component={chooseTable}
                               items={schemaData.tableList}
                               name="tableName"

                        >
                            {/*<option value="#ff0000">Red</option>*/}
                            {/*<option value="#00ff00">Green</option>*/}
                            {/*<option value="#0000ff">Blue</option>*/}
                        </Field>

                UIBuilderForm = reduxForm({
                    form: 'dashbaordUiBuilderForm',
                    fields: ['tableName']
                }
                })
                (UIBuilderForm as any);

                // Decorate with connect to read form values
                const selector = formValueSelector('dashbaordUiBuilderForm')

                // export default connect(mapStateToProps, mapDispatchToProps)(UIBuilderForm);
                export default connect(state => {
                    const TableSchemaName = selector(state, 'TableSchemaName')
                    return {
                        TableSchemaName
                    }
                }

**Comment by gustavohenke** [comment]
As it seems like [you asked at StackOverflow as well](http://stackoverflow.com/questions/41822159/the-selected-option-will-be-restored-to-unselected-status), I'll close here.
