### ISSUE TITLE
Json value with redux-form?

### ISSUE THREAD

**Issue by dmr** [erikras/redux-form#2504]
I have a requirement for a field that is plain JSON.
I can use a textarea for input, and use this as a component but as a result I get a string value.

In the documentation I found "normalize" as a way to change the value afterwards.
It kind of does what I want but now I have another problem:

If I change the value of a field normalize changes my value and the textarea updates which causes my text cursor to jump to the end.

--> Is there a way to do normalize but only in the background? I want to store the value like it is after normalize but not see the result immediately.

Thanks for building redux-form, it's a great library!

**Comment by huan086** [comment]
Not specific to redux form, the general solution I use is to have `shouldComponentUpdate` compare the refs.theTextArea.value against the nextProps.value and choose not to update if they are the same.

**Comment by gustavohenke** [comment]
@huan086 solution is probably the ideal thing to do.

Or, you could provide your field a `format` function, so you can transform your JSON object back to a string, like this:

```js
<Field name="json" format={value => JSON.stringify(value, null, 2) } parse={value => JSON.parse(value)} />
```

This would work as long as the user types the JSON the same way the `format` function formats.
This is not the best thing UX-wise, though.
