### ISSUE TITLE
initialValues and invalid form on field

### ISSUE THREAD

**Issue by teod** [erikras/redux-form#2513]
I have a form with a mandatory field, with a required rule applied as a field level validation. This field should display an initial value, but at the same time it should throw an error if the user deletes that initial value from it and does not add anything back. The problem is that it throws a validation when submitting for that field if the user does not interact in any way with the field (eg. focusing and blurring it). Is there a workaround around this without solutions like calling onBlur on the Field's component componentDidMount ?

```
const required = (value) => value ? undefined : 'required'

const Form = (props) => (
  ...
 <form onSubmit={props.handleSubmit(props.onSubmit)}>
   ....
   <Field name="myField" component="input" validate={[required]}
  ...
)

const RForm = reduxForm({
  form: 'myForm',
  initialValues: { myField: 'myInitialValue' }
})
``` 

Edit:
I resolved this issue, actually I have been passing an integer number to the myField, passing a string seems to work.

**Comment by SpainTrain** [comment]
@teod close issue? :-)
