### ISSUE TITLE
v6.5.0 - getFormNames not exposed

### ISSUE THREAD

**Issue by lundn** [erikras/redux-form#2517]
Hi!

Looking forward to using the 6.5.0 version! And especially the getFormNames() selector.
However, after updating, it doesn't seem to me that getFormNames is exposed?

**Comment by gustavohenke** [comment]
You're right! Seems like this was missed in #2402.

Do you want to create a PR for this? Should be pretty easy.

**Comment by erikras** [comment]
Fix published in [`v6.6.0`](https://github.com/erikras/redux-form/releases/tag/v6.6.0).
