### ISSUE TITLE
destroyOnUnmount: false, doesn't keep the form in redux

### ISSUE THREAD

**Issue by DWboutin** [erikras/redux-form#2518]
Hi!

When i set `destroyOnUnmount: false` on my form, it's destroyed anyway when i change page. I work with version 5.2.4.

Here's how i set my redux-form:

```javascript
StatisticsFiltersContainer = reduxForm({
  form: 'statisticsFilters',
  fields: filtersFields,
  destroyOnUnmount: false,
}, state => ({
  initialValues: {
    startDateFilter: state.statistics.date_start,
    endDateFilter: state.statistics.date_end,
    timezone: state.statistics.timezone,
    vertical: [],
    brand: [],
    offer: [],
    offerUrl: [],
    goals: [],
    country: [],
    niche: [],
    browser: [],
    payoutType: [],
  },
}))(StatisticsFiltersContainer);
```

Is everything ok? I tried to remove the initialValues, but it don't changes anything.

**Comment by gsccheng** [comment]
I just want to say that destroyOnUnmount works for me on 6.4.3.

**Comment by danielrob** [comment]
Closing with bulk close of v5 issues. If this issue still requires action and/or also affects v6/7, please request a reopen with details or raise a new issue. v5 PR's are still welcomed.
