### ISSUE TITLE
Ctrl-F on documentation site!

### ISSUE THREAD

**Issue by dmwyatt** [erikras/redux-form#252]
I'm irritated by this daily as I've been learning the ins and out of redux-form.

I haven't dived into the source to figure out what is doing it, but something on the docs site is blocking the use of Ctrl-F to find text in the page and it's maddening!

**Comment by olimsaidov** [comment]
+1 Really annoying. All `ctrl` key shortcuts are blocked.

**Comment by olimsaidov** [comment]
It seems related to [redux-devtools-dock-monitor bug](https://github.com/gaearon/redux-devtools-dock-monitor/issues/9)

**Comment by erikras** [comment]
Yep. Not redux-form's problem, unfortunately. Go pester @gaearon on the other issue. :-)

**Comment by gaearon** [comment]
I'll release an update to DevTools in a week or so. Please be patient in the meantime.

**Comment by dmwyatt** [comment]
Ah, the perils of living on the cutting edge.
