### ISSUE TITLE
The dispatch action can not be used in onChange event

### ISSUE THREAD

**Issue by weichenghsu** [erikras/redux-form#2523]
https://www.youtube.com/watch?v=bo2nNQXbhI8&feature=youtu.be

https://gist.github.com/weichenghsu/407a8862f3382a425fb531b3dedcd6f5

        const selectTableScheme = ({input, label, type, items, meta: {touched, error}}) => (
            <select
                onChange={event => {
                        console.log(input);
                        console.log(this.props);
                        console.log(this.props.fields);
                        this.props.tableNameOnChange(event.target.value);
              }}
            >
                <option value={input.value}>Select</option>
                {
                    items.map((item:any, i:integer) =>
                        <option key={item.id} value={item.id}>{item.name}</option>
                    )
                }
            </select>
        )

        

        <Field component={selectTableScheme}
               items={schemaData.tableList}
               name="tableName"
               onBlur={() => console.log('bug squashed!')}
        >

        UIBuilderForm = reduxForm({
            form: 'dashbaordUiBuilderForm',
            fields: ['tableName']
        }
        })
        (UIBuilderForm as any);

        export default connect(mapStateToProps, mapDispatchToProps, null, {} )(UIBuilderForm);

**Comment by ruanyl** [comment]
If you are using `v6.5.0`, put `onChange` to `Field`. Otherwise you will have to combine your `onChange` with `input.onChange`

**Comment by danielrob** [comment]
Closing due to non-response.
