### ISSUE TITLE
Getting values from an Immutable form state

### ISSUE THREAD

**Issue by declanelcocks** [erikras/redux-form#2525]
I'm using `redux-form/immutable` to add the `form` state to my store. It works well, but in the docs I only see examples of how to fetch values from the `form` using `formValueSelector`. Are there any methods or guides on setting values in the `form`? (`state.set(...)`)

Long story short, below is my test that I'm trying to run.

```js
describe('makeSelectEmail', () => {
  const emailSelector = makeSelectEmail();

  it('should select the email', () => {
    const email = 'test@test.com';
    const mockedState = fromJS({
      loginPage: {
        email,
      },
    });

    expect(emailSelector(mockedState)).toEqual(email);
  });
});
```

Before using `redux-form`, I would set the `email` value and update that value in the state when a user changed it. Now, using `redux-form` I need to be able to "set" a `mockedState` so that I can test this selector to make sure it is setting/fetching the correct values.

```js
import { formValueSelector } from 'redux-form/immutable';
const loginFormSelector = formValueSelector('loginForm');
const makeSelectEmail = () => (state) => loginFormSelector(state, 'email');
```

**Comment by gustavohenke** [comment]
The only way to actually change the state of a Redux store is by dispatching actions.

Therefore, you may use `change` or `initialize` action creators. [Docs](http://redux-form.com/6.5.0/docs/api/ActionCreators.md/)

**Comment by declanelcocks** [comment]
Thanks, I should've thought to look into the Action Creators section for something like a manual change.
