### ISSUE TITLE
Radio element can not be checked

### ISSUE THREAD

**Issue by weichenghsu** [erikras/redux-form#2526]
# The sample from the official example can work

        <label>Favorite Color</label>
        <div>
        <Field name="favoriteColor" component="select">
            <option></option>
            <option value="ff0000">Red</option>
            <option value="00ff00">Green</option>
        </Field>
        </div>

# The following example won't work. 

The radio option can not be checked at all,
When I clicked any of the radio item, the checked status will be restore in a flash. That is, I could not select any item.

![inline](https://i.imgur.com/1Lx1NGK.png=300x "Title")

## ui_builder_form.tsx

        schemaData.tableList = [
            {
                name: "AcceptedEventRelation",
                value: "ff0000"
            },
            {
                name: "Account",
                value: "00ff00"
            }
        ]

        <MyCheckBox
            items = {schemaData.tableList}
        />

       
        UIBuilderForm = reduxForm({
            form: 'dashbaordUiBuilderForm'
        })
        (UIBuilderForm as any);

# my_check_box.tsx

        export class MyCheckBox extends React.Component<any, any> {
            render() {
                let {items} = this.props;
                return (<div>
                        <h1>table name</h1>
                        {items.map((item:any, i:number)=> {
                            return (
                                <label key={item.value}>
                                    <Field
                                        key={item.value} name={item.name} component="input" type="radio"
                                        value={item.value}/> {item.name}
                                </label>
                            )
                        })}

                    </div>
                );
            }
        }

**Comment by ruanyl** [comment]
can you paste `ui_builder_form.tsx` in more detail?

**Comment by pcgilday** [comment]
Have you provided the redux-form reducer to redux like shown in the docs [here](http://redux-form.com/6.5.0/docs/GettingStarted.md/)?

Also, it is worth noting that all radio inputs in the same group need to have the same `name` attribute. Once you fix your current issue, you will see that you can select each option at the same time, which I am assuming is not your intention.

**Comment by danielrob** [comment]
Closing due to non-response from OP.
