### ISSUE TITLE
Field error triggering in other Field as well?

### ISSUE THREAD

**Issue by nealoke** [erikras/redux-form#2534]
Currently seeing weird behavior when using the following code. Field component errors are being influenced by each other? Looking at the form while submitting returns everything as expected. 

**The bug / behaviour in action**
![error triggering on other field](https://cloud.githubusercontent.com/assets/17417414/22434635/1f9df8ee-e71d-11e6-82f6-61f80c68f785.gif)

**Simplified code**
```
// In render method of FieldArray component
{fields.map((multiAnswer, index) => {
	return (
		<div>
			{languages.map((language) => 
				<Field 
					name={`${multiAnswer}.answers.${language}`}
					className='FORM__field--50' 
					label={supportedLanguages[language] + ' translation'} 
					placeholder={'Answer in ' + supportedLanguages[language]}
					type='text'
					validate={required}
					component={formField}
					key={`${multiAnswer}-${language}`}
				/>
			)}
		</div>
	);
})}
```

**Information**
Redux-form version: 6.4.3
[View full code on gist](https://gist.github.com/nealoke/476bd03cea183780c09465e5ad08cba2)

**Comment by huan086** [comment]
Looks like a JavaScript error in your code. `multiAnswer` is captured from the outermost function. Thus, `multiAnswer` would get changed. You need to capture the `multiAnswer` in the innermost function

```jsx
// In render method of FieldArray component
{fields.map((multiAnswer, index) => {
	return (
		<div>
			{languages.map((language) => {
				const capturedMultiAnswer = multiAnswer
				return <Field 
					name={`${capturedMultiAnswer}.answers.${language}`}
					className='FORM__field--50' 
					label={supportedLanguages[language] + ' translation'} 
					placeholder={'Answer in ' + supportedLanguages[language]}
					type='text'
					validate={required}
					component={formField}
					key={`${capturedMultiAnswer}-${language}`}
				/>
			})}
		</div>
	);
})}
```

**Comment by nealoke** [comment]
@huan086 Using the code provided still yields the same result. Any other ideas? :(

**Comment by huan086** [comment]
follow the Stackoverflow example and create the self executing function

**Comment by nealoke** [comment]
@huan086 are you sure this is the problem, tried the SO answers but same behavior. Also when doing a `console log` of the `multiAnswer` & `language` in the `languages.map()` returns the correct things.

```
{fields.map((multiAnswer, index) => {

	return (
		<div className={classnames({'---hidden': this.state.activeMultiAnswer !== multiAnswer})} key={`multiAnswer-${index}`}>
			{languages.map((language) => {

				console.log(multiAnswer, language);

				return (
					<Field 
						name={`${multiAnswer}.answers.${language}`}
						className='FORM__field--50' 
						label={supportedLanguages[language] + ' translation'} 
						placeholder={'Answer in ' + supportedLanguages[language]}
						type='text'
						validate={required}
						component={formField}
						key={`${multiAnswer}-${language}`}
					/>
				);
			})}
		</div>
	);
})}
```



![image](https://cloud.githubusercontent.com/assets/17417414/22458527/3436eb8c-e79d-11e6-88d3-7ed43e0ddc07.png)

**Comment by nealoke** [comment]
@huan086 check [this gist](https://gist.github.com/nealoke/476bd03cea183780c09465e5ad08cba2#file-reduxformstate-js) to see the initial state (via redux inspector) and when the behaviour occurs.

**Comment by nealoke** [comment]
Found the issue, don't ever connect a child component of a form to that form with a selector.
