### ISSUE TITLE
Why form is not Re-Initilized when initial values changing?

### ISSUE THREAD

**Issue by Shadowman4205** [erikras/redux-form#2539]
Hello,
i have component with select-> with dispatch action on change of select value.
After that i get the form with initial values depend on selected value.
But if i select new option, this same form do not get Initilized.

> The actions tha happening is this:
> "SELECT_SUCCESS"
> "@@redux-form/INITIALIZE"
> "@@redux-form/REGISTER_FIELD"
> "SELECT_SUCCESS" 
> //on select again nothing happened while i was waiting for "@@redux-form/INITIALIZE"

any suggestions?

**Comment by gustavohenke** [comment]
Specify `enableReinitialize: true` in your `reduxForm` HOC.
