### ISSUE TITLE
Radio button always with checked = false

### ISSUE THREAD

**Issue by BrunoQuaresma** [erikras/redux-form#2542]
I have this code

```
             <FormGroup label="Sistema Operacional">
                  <Field
                    label="Android"
                    value="android"
                    name="operational_system"
                    type="radio"
                    component={Radio}
                  />

                  <Field
                    label="iOS"
                    value="iOS"
                    name="operational_system"
                    type="radio"
                    component={Radio}
                  />
                </FormGroup>
```

Radio is

`const Radio = ({ input, label }) => { ...some radio here... }`

When i click in one of this radios the value is changed in the form but the checked attribute (input.checked) always is false. Why?

**Comment by andresalves** [comment]
Hi,

Inside Radio component you have access to input 
const {input, meta} = this.props;

The value of radio button is in input.value.

**Comment by BrunoQuaresma** [comment]
I found the problem. In the radio component I pass a number as value but when is updated the value become a string instead a number.
