### ISSUE TITLE
adding additional object on form submit?

### ISSUE THREAD

**Issue by harrythedev** [erikras/redux-form#2545]
Please excuse my ignorance.
I'm trying to submit a simple form with two different field.
if you want to patch more information from your reducer to the form, what would you do?
should i make additional invisible html field or dynamically patch them to initialValues?
or is there different approach?

**Comment by gustavohenke** [comment]
I usually prefer to do this with `initialValues`.

**Comment by harrythedev** [comment]
@gustavohenke thanks for sharing your knowledge.
however, i want to attach an metadata object from reducer to ```initialValues``` outside of the class like this `body.metadata`.
how does that exactly work? its definitely mapStateToProps function...

**Comment by pcgilday** [comment]
Using `initialValues` is a pretty good approach for attaching extra data. This could be done in `mergeProps` if `mapStateToProps` doesn't make sense in your situation. However, if you could post some sample code, it would be possible to provide a more detailed response.

**Comment by gustavohenke** [comment]
Okay, so this is pretty much an usage question.
My suggestion (and @pcgilday's as well) is to use `initialValues`. StackOverflow is usually the best place for this instead of GitHub issue tracker; so please ask there, including some code that demonstrates what you tried and why it didn't work.
