### ISSUE TITLE
Trying to reuse a redux-form with functional component

### ISSUE THREAD

**Issue by klausetgeton** [erikras/redux-form#2547]
I'm trying to build a reusable component to create simple forms, having validation and handling submit actions. I able to use it by it self, but when I try to make a functional component to inject props I got stuck in this error.

![image](https://cloud.githubusercontent.com/assets/9425599/22597486/f08a1b26-ea16-11e6-9f65-a5fd2d486d77.png)

For more details, please check out the the code:
Stackoverflow Link question: 
http://stackoverflow.com/questions/42025895/trying-to-reuse-a-redux-form-with-functional-component

Thanks for your time!

**Comment by gustavohenke** [comment]
Thanks for pointing us to your question.
If the outcome of it is a bug/enhancement, I'll reopen it.
