### ISSUE TITLE
Missing Field-Level Validation menu item from Docs

### ISSUE THREAD

**Issue by gsccheng** [erikras/redux-form#2548]
If I go to this page: http://redux-form.com/6.4.3/examples/react-widgets/
I will see that "Field-Level Validation" is missing from the side menu. I haven't checked if there are other items that are missing. Is this happening for others too?

**Comment by mqklin** [comment]
You can use the latest docs http://redux-form.com/6.5.0/docs/api/

**Comment by gsccheng** [comment]
Yeah, it's a minor bug, but I'm still seeing "Field-Level Validation" missing at v6.5.0: [http://redux-form.com/6.5.0/examples/react-widgets/](http://redux-form.com/6.5.0/examples/react-widgets/)

**Comment by mqklin** [comment]
Ah yes, sorry. Weird

**Comment by gustavohenke** [comment]
It seems like this is no longer a problem.
