### ISSUE TITLE
Unable to submit redux-form from <input> OnChange event

### ISSUE THREAD

**Issue by gsccheng** [erikras/redux-form#2549]
I want to submit a form, which should be done through the form's `handleSubmit` prop. I can do this properly when the chain of events are triggered by pressing a button. However, I am unable to do this from an `onChange` event from a form. More specifically, I want the user to be able to paste a url link into an input text field and have it automatically be submitted. For example:

    import React, {PureComponent, PropTypes} from 'react';
    import {Field, reduxForm} from 'redux-form';
    import Promise from 'bluebird';
    
    @reduxForm({
      form: 'test'
    })
    export default class TestForm extends PureComponent {
      static propTypes = {
        handleSubmit: PropTypes.func.isRequired
      }
    
      constructor() {
        super();
        this.handleChange = this.handleChange.bind(this);
        this.renderField = this.renderField.bind(this);
        this.isValidUrl = this.isValidUrl.bind(this);
      }
    
      isValidUrl(value) {
        // Some validation logic to be inserted
        return undefined;
      }
    
      handleChange(onChange, err, value) {
        const {handleSubmit} = this.props;
        console.log('err', err);
        console.log('value', value);
    
        return Promise.resolve(onChange(value))
          .then(() => {
            console.log('in then');
            return handleSubmit((values, dispatch, props) => {
              console.log('in handleSubmit');
              console.log('values', values);
              console.log('props', props);
              return Promise.resolve(values);
            });
          }).then(() => {
            console.log('in after');
          });
      }
    
      renderField({ input, label, type, meta: {error} }) {
        const {handleChange} = this;
    
        return (<div>
          <label>{label}</label>
          <div>
            <input {...input} onChange={handleChange.bind(this, input.onChange, error)} placeholder={label} type={type}/>
            {(error && <p>{error}</p>)}
          </div>
        </div>);
      }
    
      render() {
        const { renderField, isValidUrl } = this;
    
        return (
          <form>
            <Field name="url" type="text"
              component={renderField}
              label="Paste the url"
              validate={[ isValidUrl ]} />
          </form>
        );
      }
    }

Pasting in a URL in this field will give the following in the console:

    err undefined
    value Proxy {dispatchConfig: Object, _targetInst: ReactDOMComponent, Event, type: "change", target: input…}
    in then
    in after

It looks like the onSubmit function that I am passing into `handleSubmit` never gets called (I don't see the output statements). Why is that? I am using `redux-form@6.4.3`

If I instead set the `onSubmit` config property in the `reduxForm` decorator, and instead call `handleSubmit` without passing in arguments (i.e. `handleSubmit()`), my submit process works. I still don't know why the original method does not work though. Again, my original method works when I call `handleChange` triggered from a button (whether explicitly from `onClick` or a form's `onSubmit`).

**Comment by gustavohenke** [comment]
When given a function as a parameter, `handleSubmit` creates an `onSubmit` handler.

> ### `onSubmit`
> The function to call with the form data when the `handleSubmit()` is fired from within the form component. **If you do not specify it as a prop here, you must pass it as a parameter to `handleSubmit()` inside your form component.**

http://redux-form.com/6.5.0/docs/api/ReduxForm.md/#-onsubmit-function-optional-

I recommend you to use `<form onSubmit={ handleSubmit( yourSubmitHandler ) }>`, then follow [the remote submit example](http://redux-form.com/6.5.0/examples/remoteSubmit/).
