### ISSUE TITLE
Calling onChange manually does not set `touched`

### ISSUE THREAD

**Issue by dsteinbach** [erikras/redux-form#255]
I am firing onChange manually like so:

```
this.props.fields.dropdown.onChange(selectedValue);
```
But `touched` remains false. I need to know when it's touched so I can display the error to the user when they have validation issues.

**Comment by erikras** [comment]
By default, `touched` is flagged by `onBlur`. But there is a `touchOnChange` flag that you can pass to `reduxForm()` if you want 'onChange' to flag 'touched'. [See docs](http://erikras.github.io/redux-form/#/api/reduxForm).
