### ISSUE TITLE
JEST Snapshot Testing always creates a unique identifier for the ID and htmlFor

### ISSUE THREAD

**Issue by rholliger** [erikras/redux-form#2551]
Hi Guys

I'm using redux-form and Jest snapshot testing in our application. Unfortunately there is a problem regarding the snapshot creation. Every time the snapshot is created the ID and the htmlFor attribute on the form field changed to a different unique ID. 

Am i doing something wrong, or is that a known problem?

I'm running the following test for a Login component, that consists of two redux-form fields.

    `describe('Login Component', () = {
        it('renders correctly', () = {
            const props = {
                onLogin: jest.fn(),
            };

            const locale = 'de';

            const store = mockStore({
                i18n: {
                    locale,
                    locales,
                },
                form: {},
            });

            const tree = renderer.create(
                <Provider store={store}>
                    <I18n locales={locales} locale={locale}>
                        <ThemeProvider theme={theme}>
                            <Login {...props} />
                        </ThemeProvider>
                    </I18n>
                </Provider>
            ).toJSON();

            expect(tree).toMatchSnapshot();
        });
    });`

`<Field component={TextInputWrapper} className={this.props.theme.textInput} name="email" type="email" caption={this.props.t('E-Mail')}/>`

After running the test and updating the snapshot it fails because of the following problem:

![ohne_titel](https://cloud.githubusercontent.com/assets/6562926/22640303/51b5b300-ec52-11e6-8cc7-0755011ebf04.png)

There is someone on stackoverflow, which has the same problem.
http://stackoverflow.com/questions/41167981/how-to-stop-redux-form-or-react-from-changing-htmlfor-and-id-when-creating-jest

Can someone provide some answers regarding this problem?

**Comment by gustavohenke** [comment]
I never used Jest, but I kinda know about this snapshot testing feature.
The best I can say is that we don't modify either of those props, so it must be something related to the way Jest creates those snapshots...

**Comment by rholliger** [comment]
@gustavohenke Thank you for the fast reply. So I'll check with the guys at jest. Maybe they have an answer.

**Comment by anubhavDaffodil** [comment]
@rholliger Did you find the solution?

**Comment by rholliger** [comment]
no @anubhavDaffodil I also did the same by providing a constant ID to each Field. I think thats a reasonable way to do it :-)
