### ISSUE TITLE
Form is not pristine after submit

### ISSUE THREAD

**Issue by tomasztomys** [erikras/redux-form#2553]
I have form with reinitialize set as true.
When I submit form, the form is not pristine... But if i return all inputs to initial values, the form will be pristine (but it's now not pristine, it was pristine on start).

**Comment by idrumgood** [comment]
If you're passing `initialValues` to the form, those must be set to the updated values. That, along with `reinitialized: true` will put the form back in a pristine state.

**Comment by gustavohenke** [comment]
> If you're passing `initialValues` to the form, those must be set to the updated values.

Precisely. Redux Form cannot know what is the right thing to do.
