### ISSUE TITLE
Submit validation failed

### ISSUE THREAD

**Issue by kristian-puccio** [erikras/redux-form#256]
Is it possible to be notified when a form submit is made and didn't pass validation?

Maybe even just have the promise that handleSubmit returns call catch or resolve the promise with some errors.

I'd like to be able to do a couple of things with this, 1 is to track a hasSubmitted status about the form so I can show more intense errors if they have and 2 scroll to the first input with an error.

**Comment by kristian-puccio** [comment]
The other option would be to have handleSubmit always call a function and allow that function to manually call the relevant validation functions. That way the end user has totally control.

**Comment by erikras** [comment]
The current system provides enough control, I think. How about something like this?
```js
<form onSubmit={handleSubmit(() =>
  mySubmitAction()
    .then(() => {
        // submission was successful
      }, () => {
        // submission was unsuccessful
        // set showIntenseErrors and scroll to first invalid input
      }))}>
  // render inputs
</form>
```

**Comment by kristian-puccio** [comment]
yep perfect

**Comment by kristian-puccio** [comment]
Sorry I'm a little confused. On validation failure (I'm using async) the
function passed into handleSubmit never gets called so I don't get a chance
to return a promise.

Am I missing something? Should the .then tack on to handleSubmit ?

**Comment by kristian-puccio** [comment]
Here is my code: 
```
				<form
					autoComplete={false}
					onSubmit={
						handleSubmit( () => {
							console.log('NEVER CALLED');
						})
					}>
```

**Comment by erikras** [comment]
You're using the `asyncValidate` option of redux-form? If that fails, your submit will not be called.

[Read through this](http://erikras.github.io/redux-form/#/examples/asynchronous-blur-validation).

**Comment by kristian-puccio** [comment]
Yep got that. I'm also using asyncBlurFields so I can't tell in my
validation function if it is a blur or submit that has triggered the
validation.

So I was wondering how do you feel about an onSubmitFailed prop(erty)? or
even maybe a second function as a parameter to handleSubmit?
That way you get an easy way of being notified when someone fails to submit
the form.

If your into the idea I'll try to send you a pull request.

**Comment by erikras** [comment]
`handleSubmit` returns the promise, though. Seems like you could do something similar to above:
```js
<form onSubmit={event =>
  handleSubmit(mySubmitAction)(event) // <---- this is the promise returned from handleSubmit()
    .then(() => {
        // submission was successful
      }, errors => {
        // submission was unsuccessful
      }))}>
  // render inputs
</form>
```
You will always get to one of those two code branches if the user clicks submit.

**Comment by kristian-puccio** [comment]
Unfortunately I'm not seeing that.

handleSubmit(mySubmitAction) returns a promise, where the catch
function is never called but the success always is. Not the page will
refresh here.

handleSubmit(mySubmitAction)(event) throws an handleSubmit(...) is not
a function error.

If I change it to handleSubmit(event) I always get the success
function in the then called the same as handleSubmit(mySubmitAction)
but the page doesn't refresh.

**Comment by erikras** [comment]
Will your use case be fixed by #276?

**Comment by kristian-puccio** [comment]
No it's a different use case.
I would like to trigger an action of submitFailed with this.
So if the failed promise function that handleSubmit returns was called with
errors that would be perfect.

Am I missing something that the catch function isn't called? Are you seeing
it?

**Comment by erikras** [comment]
Aha! This is a legit bug.

**Comment by erikras** [comment]
There used to be an undocumented boolean flag you could pass to get this behavior, but I could find no reference to _why_ that was not the default behavior. Fixed in `v3.0.9`.

**Comment by kristian-puccio** [comment]
Awesome the catch func is now being called, thanks so much for your
responsiveness!

One small thing the catch is being called with no params, it's fine as I
can grab the errors off the props but not sure if it's what your expecting.

**Comment by erikras** [comment]
I would expect that it would be rejected with whatever the `onSubmit` function's returned promise was rejected with. It is in the tests.

**Comment by erikras** [comment]
@kristian-puccio #291 reminded me why the behavior was as it was. You will need to use the `returnRejectedSubmitPromise` config prop to get the rejected promise that I had given you in `v3.0.9`.

**Comment by kristian-puccio** [comment]
Great thanks @erikras.

**Comment by erikras** [comment]
You guys might be interested in [`v5.1.0`](https://github.com/erikras/redux-form/releases/tag/v5.1.0).

**Comment by anhldbk** [comment]
@erikras for `redux-form` v6.x.x, how to properly handle rejections? I've created a related issue: https://github.com/mhssmnn/redux-form-saga/issues/19

Certainly I can use your code above to fix that:
```js
<form onSubmit={event =>
  handleSubmit(mySubmitAction)(event) // <---- this is the promise returned from handleSubmit()
    .then(() => {
        // submission was successful
      }, errors => {
        // submission was unsuccessful
      }))}>
  // render inputs
</form>
```

**Comment by Abhijeetjaiswalit** [comment]
@erikras  I'm using the asyncValidate option of redux-form? If that fails, error is shown but when it passes the validation, after that I'm unable to submit my form. Can you tell me what could be the reason behind that? Here is my aysnc validate method: 


 import * as api from './tools/apiConfig';
import axios from 'axios';

function asyncValidate(values) {
  const data = {
    ktp: values.KTP.replace(/ /g, '')
  }
  if (!values.KTP) {
    return Promise.resolve({})
  }
  return new Promise((values, reject) => {
    return axios.post(api.VERIFY_KTP, data).then((response) => {
      if (response.data == false) {
       reject({ KTP: message })
      }
      else {
        Promise.resolve({})
      }
    })
  })
}
export default asyncValidate;
