### ISSUE TITLE
How to mutate the default form state alias ? 

### ISSUE THREAD

**Issue by be-next-hotdog** [erikras/redux-form#2560]
Hello, Guys, 
Just a simple question as topic, the default redux form state alias remains as 'form', is there a way to redefine ? 

Thanks a lot ;)

**Comment by mqklin** [comment]
I guess this is what you want: http://redux-form.com/6.5.0/docs/api/ReduxForm.md/#-getformstate-function-optional-

**Comment by gustavohenke** [comment]
Thanks @mqklin.

@be-next-hotdog, please note that it's better that you ask question at StackOverflow, our GitHub issue tracker is not the proper place for this.
