### ISSUE TITLE
Using Custom Component (Semantic UI - Dropdown & co )

### ISSUE THREAD

**Issue by GreGGus** [erikras/redux-form#2562]
Hey,

In the first place, thanks for this awesome libs.

Everything works well.

I'm trying to use React-Semantic-UI Component with redux-form. 
I searched inside the docs how about integrate custom component with redux form, and here we go : 
http://redux-form.com/6.5.0/docs/faq/CustomComponent.md/
Seems perfect.

But when i integrate Semantic and this, it doenst work.

This is my simple test : 

```
const TestComponent = props => (
<Form>
     <Field name="dropdownTest" component={ TestSelect } />
</Form>
)

```

and here my CustomComponent using Dropdown. You can found the dropdown documentation & props  (onChange & value ) here : 

http://react.semantic-ui.com/modules/dropdown

```
import Form , Dropdown from 'semantic-ui-react'
import {myOption from './myOption'

const TestSelect = field = (
   <Form.Field>
            <label> Test dropdown </label>
             <Dropdown option={myOption} selection 
                                   value={{val : field.input.value}}
                                   onChange={ param => field.input.onChange(param.val)} />
     </Form.Field>
)


```

As in the documentation, I added value & onChange props on my Custom Component.

I clearly miss something here.

Thanks for helping.

**Comment by GreGGus** [comment]
Ok I succed, you can close this issue.


```
const TestComponent = props => (
<Form>
     <Field name="dropdownName" component={ DropdownFormField}
            label="Dropdown Test" 
      />

</Form>
)



const DropdownFormField = props => (
 <Form.Field>
   <Dropdown selection {...props.input}
             value={props.input.value}
             onChange={(param,data) => props.input.onChange(data.value)}
             placeholder={props.label} 
    />
  </Form.Field>
)
```

**Comment by JohnHour89** [comment]
hi, @GreGGus , may I know do you know how to get the selected value for the Dropdown field? Thank you

**Comment by akhilaudable** [comment]
Please answer for @JohnHour89 question. Thank you.

**Comment by niksmac** [comment]
Adding `onChange={(param,data) => props.input.onChange(data.value)}` will show the value

**Comment by natalia-alfaro-coderoad-com** [comment]
This is not working when you add the search param
