### ISSUE TITLE
How do I instantiate and use a set of the same form?

### ISSUE THREAD

**Issue by pfaffle** [erikras/redux-form#2565]
I'm trying to create a form which takes a username and password, but I want to be able to have multiple unique instances of this form mapped to a different set, e.g.
```
// i want many of these!
const FormInstance = reduxForm({
    form: `credentials-${uniqueKey}`,
  })(Credentials)
```

How do I generate a FormInstance for each key?

My first approach was to create a factory method which generated a new FormInstance for each uniqueKey - however, on every render of the parent component, React is unmounting my Forms and creating new FormInstances. A side effect of React doing this is that it's dispatching `redux-form/DESTROY`, clearing the form and all its state.

How do I do this correctly?
Thanks!

**Comment by pfaffle** [comment]
Never mind, I realized I was making this way more complicated than it needed to be. Instead of using a factory, I just changed the parent component to pass in a unique form name as a prop.

**Comment by Dartanjan** [comment]
Hi @pfaffle, can you elaborate your approach a bit? I have a similar use case – I have multiple "posts" and I need to edit all of them inline, so when editing, each form needs to be unique, likely by post ID.

How do you pass the ID, if at the moment of creating the form via `reduxForm({ form: 'form-name' })(EventForm);` the ID isn't available. Can it be done on `constructor` or `componentWillMount`? Any help appreciated :)

**Comment by Dartanjan** [comment]
Ah, scratch that. I got it – dynamic form name can be passed as a prop to the decorated element, like so: `<FormComponent form={'something-' + props.id} />`.
