### ISSUE TITLE
pure prop passed to a redux form at runtime not working.

### ISSUE THREAD

**Issue by d-leeg** [erikras/redux-form#2567]
The documentation states:

> IMPORTANT: All of these configuration options may be passed into reduxForm() at "design time" or passed in as props to your component at runtime.

However, the `shouldComponentUpdate` method of Form (line 241 in [reduxForm.js](https://github.com/erikras/redux-form/blob/master/src/reduxForm.js) in version 6.5.0)
reads: `if (!config.pure) return true;`, completely ignoring the pure prop.

**Comment by gustavohenke** [comment]
Feel free to send us a PR to either fix this sentence in the docs or to fix the behavior of the code.

**Comment by d-leeg** [comment]
I believe fixing the code is best

**Comment by d-leeg** [comment]
Sorry, inadvertent click...

**Comment by erikras** [comment]
Fix published in [`v6.6.0`](https://github.com/erikras/redux-form/releases/tag/v6.6.0).
