### ISSUE TITLE
redux-form does not re-render when receiving new initialProps and enableReinitialize is true

### ISSUE THREAD

**Issue by d-leeg** [erikras/redux-form#2568]
When sending a new `initialValues` prop to a redux-form with an `enableReinitialize` prop that is `true` (say given in the config object to `reduxForm()`), the wrapped form should re-render.

However, this is not working since the `shouldComponentUpdate` method of Form (line 247 in [reduxForm.js](https://github.com/erikras/redux-form/blob/master/src/reduxForm.js), of version 6.5.0)  consults the array `propsToNotUpdateFor` (which contains the string `'initialValues'`) without any regard to the value of `enableReinitialize`.

**Comment by gustavohenke** [comment]
> When sending a new `initialValues` prop to a redux-form with an `enableReinitialize` prop that is `true` (say given in the config object to `reduxForm()`), the wrapped form should re-render.

`enableReinitialize` controls *whether the form should initialize again*, and not when it should re-render.

Some examples of re-renders include, but are not limited to:
- values change, so the form goes from pristine to dirty
- validation error is un/set, so the form is marked in/valid

**Comment by d-leeg** [comment]
However, the current `shouldComponentUpdate` behavior has the effect of preventing the wrapped form component from receiving the new `initialValues` prop altogether; thus causing the `initialValues` prop  of the wrapped component to be different than the `initialValues` prop of the reduxForm component (as well as the value in the redux store), which is in contradiction with the documentation of this prop.
