### ISSUE TITLE
Child redux-form component handleSubmit error.

### ISSUE THREAD

**Issue by gshyperion** [erikras/redux-form#2571]
Hello everyone! I am facing an issue and whenever I try to render a redux form child component inside a parent component I get the error "handleSubmit is not a function". 

I am guessing that this could be caused because I am doing something wrong with the containers but let me describe the situation I am facing and maybe someone can help me.

I have a Parent component that includes 2 child components. One of the child components is a redux-form and the other one is a stateless functional component.

```
const Parent = ({ inputList }) => (
  <div>
    <MyForm />
    <MyList inputList={inputList} />
  </div>
);
export default Parent;
```

As I mentioned the MyList component is stateless so it has no container and I am just passing a prop to render a list. The Parent Component has a container ParentContainer like the following:

```
const mapStateToProps = state => (
  {
    inputList: state.get('inputList')
  }
);

const ParentContainer  = connect(mapStateToProps)(Parent);
export default ParentContainer;
```

The Form component is the following (don't pay attention to the form tags since I am using reactstrap and that is not the issue): 

```
const MyForm= ({ handleSubmit, submitSearch, submitting }) => (
  <span>
    <Form onSubmit={handleSubmit(submitSearch)}>
      <FormGroup row>
        <Col sm={2}>
          <Field
            id="itemCode"
            name="itemCode"
            component={inputField}
            type="text"
            placeholder="Search for Item"
          />
        </Col>
        <Col sm={2}>
          <Label for="dateFrom" sm={2}>Date From</Label>
          <Field
            id="dateFrom"
            name="dateFrom"
            component={inputField}
            type="text"
            placeholder="1/1/2016"
          />
        </Col>
        <Col sm={{ size: 2, offset: 1 }}>
          <Button type="submit" color="primary" disabled={submitting}>
            Search
          </Button>
        </Col>
      </FormGroup>
    </Form>
  </span>
);

export default MyForm;
```

The Form component also has a FormContainer:
```import MyForm from '../../components/MyForm';

const mapDispatchToProps = dispatch => (
  {
    submitSearch: (formSearchData) => {
      dispatch(searchItems(formSearchData));
    }
  }
);

const MySearchForm = reduxForm({
  form: 'mySearchForm'  // a unique identifier for this form
})(MyForm);

const MyFormContainer =
  connect(null, mapDispatchToProps)(MySearchForm);

export default MyFormContainer;
```

Now whenever I try to navigate to the Parent Component I get the error: 
"Uncaught TypeError: handleSubmit is not a function at MyForm (index.js:17)"

Any help would be really appreciated since I am stuck with this for some hours now...

**Comment by gustavohenke** [comment]
You're using `<MyForm />`, but your wrapped form is `<MySearchForm>`/`<MyFormContainer>`.
Please check whether this is the problem.

**Comment by gshyperion** [comment]
Thank you for your response but this unfortunately does not solve my issue. With your change I get the error "Maximum call stack size exceeded".

P.S. I have added export statements in the initial sample I provided.

**Comment by gustavohenke** [comment]
Then please provide an reproducible demo. Start here: https://jsfiddle.net/gustavohenke/48814zsq/

**Comment by gshyperion** [comment]
Thank you for your intentions to help, but my files layout is complicated and I cannot simply create a jsfiddle without dedicating too much time right now.

I am certain that it is an issue of nesting the MyForm component inside the Parent one. I have extracted MyForm to be a standalone (just to test) without a parent and the form renders fine. I am missing something in the setup of my parent component and the way that the communication with the child takes place.

**Comment by gshyperion** [comment]
I am closing this issue since it was after all what gustavohenke had mentioned. Thank you for your help.
