### ISSUE TITLE
FieldArray: new values update only after input blur, but should after each change

### ISSUE THREAD

**Issue by mqklin** [erikras/redux-form#2577]
### Are you submitting a **bug report** or a **feature request**?
bug report

### What is the current behavior?
http://www.webpackbin.com/N1djS5vOz
props in FieldArray component update only after input blur
Steps: 1) click "Add person" 2) type something inside input (list should update immediately) 3) make blur (list updates, but should at step 2)

### What is the expected behavior?
they should update after every input change

One possible workaround is to connect some selector to `People` component and pass it as a prop to `FieldArray`

**Comment by mqklin** [comment]
Seems like it fixed, I'll check it soon.

**Comment by dtipson** [comment]
I think that fix is merged but not released.  I'm still seeing the same sort of issue: implausibly I have an _error about an empty field array but in the syncErrors in the store but... at the same time, the field is not empty.  ¯\_(ツ)_/¯

**Comment by mqklin** [comment]
Fixed now in v6.6.2

**Comment by mqklin** [comment]
No, it isn't fixed. It just became harder to reproduce. I get very strange behaviour, I'll create a bin to reproduce it later.

**Comment by mqklin** [comment]
Yes, it's fixed, but now there is another problem with FieldArray https://github.com/erikras/redux-form/pull/2465#issuecomment-293481665
