### ISSUE TITLE
Cannot access to fields from previous steps in wizard form

### ISSUE THREAD

**Issue by indapublic** [erikras/redux-form#2579]
I have wizard form with two subforms

```
export default reduxForm({
  form: 'userRegister',
  destroyOnUnmount: false,
  validate: validateUserRegisterStep1,
  fields: ['email', 'password', 'passwordConfirmation'],
})(UserRegisterFormStep1)

export default reduxForm({
  form: 'userRegister',
  destroyOnUnmount: false,
  forceUnregisterOnUnmount: true,
  validate: validateUserRegisterStep2,
  fields: ['type', 'firstName', 'lastName'],
  initialValues: {
    type: 'user'
  }
})(UserRegisterFormStep2)
```

But when I submit on second step, I only see values of second form:

```
values:Object
firstName:"xx"
lastName:"x"
type:"user"
```
Cannot find a reason.

**Comment by indapublic** [comment]
I moved 

```
initialValues: {
    type: 'user'
  }
```

in UserRegisterFormStep1 and all is fine.
So I cannot initialize values (e.g. hidden fields) in another step except first?

**Comment by alexis1990** [comment]
+1

**Comment by gustavohenke** [comment]
> So I cannot initialize values (e.g. hidden fields) in another step except first?

Yep. The form state is not going away when you move to the 2nd step, so no need to reinitialize it.

Oh, and by the way, `fields` is not a form config anymore in v6.
