### ISSUE TITLE
stopSubmit or setSubmitFailed should delete submitPromise

### ISSUE THREAD

**Issue by ghola** [erikras/redux-form#2591]
**bug report**

When using with redux-saga a good trick is to return an empty Promise from the onSubmit function, like so:
```javascript
const mapDispatchToProps = (dispatch) => {
    return {
        onSubmit: (value) => {
            dispatch({type: 'LOGIN_WITH_EMAIL', payload: {email: value.email, password: value.password}});

            return new Promise(() => { }); // sets form state to SUBMITTING
        }
    }
}
```

Then in the saga, if the api call on the server fails, one would simply dispatch `stopSubmit('LoginForm', { _error: error})`.

All of this works for one submit. Subsequent attempts to submit are ignored because the submit promise returned by onSubmit remains undeleted (https://github.com/erikras/redux-form/blob/master/src/reduxForm.js#L407). Since the submit has stopped, shouldn't the submitPromise be cleared too?

This happens in any redux-form 6.* version.

**Comment by erikras** [comment]
Fix published in [`v6.6.1`](https://github.com/erikras/redux-form/releases/tag/v6.6.1).
