### ISSUE TITLE
Failed prop type: Invalid prop `fields` of type `array` supplied to `SampleForm`, expected `object`.

### ISSUE THREAD

**Issue by hariram302** [erikras/redux-form#2593]
import React from 'react';
import FormFieldsControl from "../../../modules/controls/formControl/formFieldsControl";
import { Field, reduxForm } from 'redux-form';

const validateForm = values => {
    const errors = {};
    if (values.txtPhoneNumber && values.txtPhoneNumber.length != 10) {
        errors.txtPhoneNumber = 'Please enter valid phone number';
    }
    return errors;
};

class SampleForm extends React.Component {

    render() {

        const {  fields: { txtPhoneNumber }, handleSubmit } = this.props;

        return (
            <form>
                <FormFieldsControl id="txtPhoneNumber" {...txtPhoneNumber} className="twolineTextAndLabel" displayText="PHONE NUMBER" type="text" />
            </form>
        );
    }
}

export default reduxForm({
    form: 'FormValidate',
    validate: validateForm,
    fields: ['txtPhoneNumber']
})(SampleForm);

SampleForm.propTypes = {
    pristine: React.PropTypes.bool,
    handleSubmit: React.PropTypes.func,
    reset: React.PropTypes.func,
    submitting: React.PropTypes.bool,
    fields: React.PropTypes.object.isRequired
};

I;m not able to pass custom field, If I use Redux Field it is working any reason behind

**Comment by gustavohenke** [comment]
You should not pass `fields` to the form.
I'm pretty sure there's a duplicate for this, in case you find it, you should definitely go vote for it.

**Comment by hariram302** [comment]
I don't see anything similar,

If I didn't define fields how can i use that in props.

**Comment by gustavohenke** [comment]
Name it something else.

**Comment by hariram302** [comment]
I need field property so that I can pass to Custom Control. I found an answer thanks

https://github.com/hariram302/react-kickstart/blob/master/client/CustomerPage.js
