### ISSUE TITLE
Allow modification of 'valid' conditional to accomodate convention

### ISSUE THREAD

**Issue by Limess** [erikras/redux-form#2594]
### Are you submitting a **bug report** or a **feature request**?
A **feature request**.

### What is the current behavior?
Falsey values are considered to be valid, truthy values are invalid

### What is the expected behavior?
To allow the unmodified use of validators conforming to other APIs.

E.G. 
* https://www.npmjs.com/package/validator
`true` is valid, falsey values are invalid
* https://github.com/jquense/yup and https://github.com/hapijs/joi
`true` is valid, falsey values are invalid

### Use case
We already have an existing set of validators which we planned on continuing to use alongside a `redux-form` migration. To do this we've found we're going to have to reduce over the output to return falsey values. and update a large amount of code/tests to do so. I suspect a number of people would take an 'off-the-shelf' lib such as validator to do most of their validation heavy lifting.

**Comment by gustavohenke** [comment]
Could you please provide an example of code you'll need to refactor because of the way Redux Form works?

**Comment by Limess** [comment]
Hi @gustavohenke, the refactoring would consist of:

Changing our server side validation predicate to check for the alternative validation result:
`const isObjectValid = (result) => return Object.keys(result).some((value) => (object[value] !== true));`

Either changing all of our validators to return `undefined` rather than `true`, updating stubs to do this in ~40 test classes (I'm aware this suggests our implementation is rather brittle here):
e.g `stubValidateTvPin = sinon.stub(tvPinValidator, 'validate').returns(true)`

Change our server side logic for checking whether a field has been validated (we previously initialised as `null` but this is seen as valid in `redux-form`)

We could alternatively write and use a mapper from our existing functions to the redux-form predicates, only on in our react code - however we have some 'validators' which return objects (e.g day/month/year fields), which would result in a recursive mapping being needed.
