### ISSUE TITLE
Errors reseting after SubmissionError

### ISSUE THREAD

**Issue by thgala** [erikras/redux-form#2599]
### Are you submitting a **bug report** or a **feature request**?
_Sounds like a feature._

Can I manually dispatch an error for a field (using redux-form actions) or manually call sync validation function or reset the errors after throwing SubmissionError?

### What is the current behavior?
As I see sync validation doesn't work for a field if the value hasn't been changed after SubmissionError.

### What is the expected behavior?
I would like to reset (remove) errors after passing them to SubmissionError by changing any of my form value.

### What's your environment?
6.5.0

### Other informations
-

**Comment by Merri** [comment]
Can you be more specific on why you would need this? This sounds like you are throwing error to a field that is not related to the error, or throwing one error to multiple fields.

1. If error is only specific to a single field, return error specific to that field.
2. If error targets multiple fields, use a global _error.

**Comment by thgala** [comment]
I would like to highlight each field it case of global _error and reset each firld on any form field change.

**Comment by Lukavyi** [comment]
I have the same error, would love such a feature, cause after SubmissionError i need to validate the whole form on each onChange, but only the changed input gets validated

**Comment by danielrob** [comment]
Closing as you can now use `clearSubmitErrors` to achieve this. Added documentation.
