### ISSUE TITLE
How do you handle multi-step, route-based forms?

### ISSUE THREAD

**Issue by egmanoj** [erikras/redux-form#260]
I'm trying to figure out how to best handle multi-step, route-based forms. Each step of the form is associated with a route, and each step is validated independently. Ideally I'd like a single form, with partial validation per step. Is this possible? Does anyone here have experience with such a case?

**Comment by hairychris** [comment]
There is another library called Winterfell that might be worth looking at: https://github.com/andrewhathaway/Winterfell

As for redux-form I don't know sorry buddy.

**Comment by egmanoj** [comment]
@hairychris Thanks, I've seen Winterfell. I'd like to go with Redux(-form) as much as possible.

**Comment by erikras** [comment]
That seems doable. How about something like this?
```js
@reduxForm({
  form: 'myBigForm',
  fields: [/* fields on first page */],
  validate: validateFirstPage // <------ only validate fields on first page
})
class FirstPage extends Component {
  // render first page of inputs
  // handleSubmit forwards to next page
}

@reduxForm({
  form: 'myBigForm',           // <------ same form name
  fields: [/* fields on second page */],
  validate: validateSecondPage // <------ only validate fields on second page
})
class SecondPage extends Component {
  // render second page of inputs
  // handleSubmit forwards to next page
}

@reduxForm({
  form: 'myBigForm',           // <------ same form name
  fields: [/* all fields */],
  validate: validateAll        // <------ validate all fields
})
class FinalPage extends Component {
  // render last page of inputs
  // handle submit actually submits data
}
```

**Comment by egmanoj** [comment]
@erikras That looks very promising. Will try it out. Thanks.

**Comment by erikras** [comment]
Great. Please report back.

**Comment by egmanoj** [comment]
@erikras: Yes! This worked, and nicely :+1:

**Comment by erikras** [comment]
Awesome!

**Comment by erikras** [comment]
FYI, for anyone reading this ticket in the future. Here's a working example of my suggestion above: [Wizard Form](http://erikras.github.io/redux-form/#/examples/wizard).

**Comment by egmanoj** [comment]
This is awesome. Thanks!

**Comment by dankoknad** [comment]
@erikras Thank you for an [example](http://redux-form.com/6.7.0/examples/wizard/) (a link url has been changed).

**Comment by kktam** [comment]
update. the latest link for Wizard form example is now located here [http://redux-form.com/6.8.0/examples/wizard/](url)
