### ISSUE TITLE
Possibility to reset form errors (_error) in redux-form 6.5.0

### ISSUE THREAD

**Issue by skleeschulte** [erikras/redux-form#2604]
### Are you submitting a **bug report** or a **feature request**?
If I understood the docs correctly, this is currently not possible. Thus a *feature request*.

### What is the current behavior?
A form error can be set in `onSubmit` with

    throw new SubmissionError({ _error: 'My form error message.' });

When changing a value or re-submitting the form, the form error does not disappear, and there does not seem to be a way to (only) remove the form error manually (e.g. in `onSubmit`).

### What is the expected behavior?
It should be possible to remove/reset the form error message (`_error`).

### What's your environment?
redux-form 6.5.0

### Other informations
http://stackoverflow.com/questions/42288445/redux-form-6-5-0-how-to-clear-form-error-error

**Comment by Merri** [comment]
I'm a bit lazy to test this myself right now, but throwing as an idea what happens if you call `this.props.change('_error', null)`?

**Comment by Nickman87** [comment]
We are having the same problem. We need control over when the submission error is removed, so for now I have added a custom wrapper with it's own reducer to keep track of wether or not we want to hide the submission error. I'm going to look into making a PR, introducing a new action to just delete the submission error. Seems like a pretty common usecase.

**Comment by Nickman87** [comment]
See my pull request: https://github.com/erikras/redux-form/pull/2615

**Comment by eaardal** [comment]
Hi. We have the same issue, but found that dispatching the `stopSubmit` action with an empty errors object will clear it: 
```
import { stopSubmit } from 'redux-form';
dispatch(stopSubmit('myFormName', {}))
```
https://github.com/erikras/redux-form/blob/e9bcc1b54e211071f0cefc644c1ab7b2e93b9d78/src/__tests__/reducer.stopSubmit.spec.js#L291

**Comment by danielrob** [comment]
Closing due to @Nickman87's PR which tackled this issue (clearSubmitErrors action). Thanks @Nickman87!

**Comment by jamesseanwright** [comment]
If submission is being blocked by async validation errors, then one can clear them with the `stopAsyncValidation` action creator:

```js
dispatch(stopAsyncValidation(FORM_NAME, { clear: true }));
```

Why the `clear` property? The reducer branch for the `STOP_ASYNC_VALIDATION` action will only clear errors associated with a form [if the payload has at least one key](https://github.com/erikras/redux-form/blob/066e75356cc1e43ce22755337c48d80bc16a49af/src/createReducer.js#L378). It would be great if this behaviour could be changed in a backwards-compatible manner, but admittedly the codebase on which I'm currently working uses async validation in lieu of submission validation; I have no idea why...
