### ISSUE TITLE
[feature request] `formValueSelector` to return all form values if names weren't defined

### ISSUE THREAD

**Issue by mqklin** [erikras/redux-form#2608]
### feature request

`formValueSelector` to return all form values, if names weren't defined.

For example:

```
  const selector = formValueSelector(FORM_NAME);
  const allValues = selector(store.getState()); // alias for store.getState().form[FORM_NAME].values;
```

Sometimes it's useful, for example, when you need all form values as object:

```
const FORM_NAME = 'my-form';
const selector = formValueSelector(FORM_NAME);
@connect(
  state => ({ allValues: selector(state) }),
)
@reduxForm({ form: FORM_NAME })
class MyFormComponent extends Component {
  render() {
    const { allValues } = this.props;
    return (
       // some fields
       <button onClick={() => fetch('/server', { method: 'POST', body: JSON.stringify(allValues) })} />
    );
  }
}
```

**Comment by gustavohenke** [comment]
You can use [`getFormValues` selector](http://redux-form.com/6.5.0/docs/api/Selectors.md/#-getformvalues-formname-string-returns-state-formvalues-object-) for this exact behavior.

@erikras, why do we have two selectors that behave almost the same way?

**Comment by mqklin** [comment]
Damn, right. Thanks.

**Comment by tnrich** [comment]
@gustavohenke  @erikras , yes, this does seem like it should be encompassed by the regular selector: `formValueSelector(FORM_NAME);`
