### ISSUE TITLE
[React Native] Validations not triggered when submitting?

### ISSUE THREAD

**Issue by julien-rodrigues** [erikras/redux-form#2611]
### React Native does not validate when submitting.
The steps I'm explaining below worked properly when using the v5 of the lib.

Currently it doesn't trigger any validation on the `press` of the submit button. 
When triggering an error on a field, like a `required`, the error appears on the field, suggesting the validation code is working. But when pressing submit, the submit method is executed even tho the error is here.

![screen shot 2017-02-20 at 3 34 16 pm](https://cloud.githubusercontent.com/assets/4670971/23141696/1274f59a-f786-11e6-9c1a-e84deae16ca3.png)

I debugged the thing and the validation methods are simply not called when `redux-form` executes `handleSubmit`.

I saw that on the Web we can use a `<Form />` component. But I looked at the code and it returns a `<form />` HTML tag. So not really working on native envs.

Plus, if that helps, this line in `handleSubmit` always returns `true` (actually it's `valid` that is always `true`):
```javascript
if (valid || persistentSubmitErrors) {
```

Here is my code:

```javascript
// Form.js
function Form({handleSubmit}) {
  return (
    <Container>
      <Field
        name="email"
        component={TextInput}
      />
      <Field
        name="password"
        component={TextInput}
      />
      <Button onPress={handleSubmit}>
        Submit
      </Button>
    </Container>
  );
}

export default reduxForm({
  form: 'signIn',
  validate
})(Form);
```
```javascript
// validate.js 
// Using a custom lib for validations
export default validations({
  email: required({message: 'yolo'})
});
```
```javascript
// SignIn.js
function onSubmit(data) {
  alert('submitted');
}

function SignIn() {
  return (
    <ScrollView>
      <Form onSubmit={onSubmit} />
    </ScrollView>
  );
}
```

Pretty simple code. 

### What is the current behavior?
The submit action submits without triggering a validation.

### What is the expected behavior?
Having the validation triggered when I press the submit button.

### What's your environment?
React Native

### Other informations
But v6 changed a lot of things and I don't know what's happening and I find this new version terribly difficult to grasp compared to previous versions and the doc doesn't help much. So I probably miss something important.

**Comment by gustavohenke** [comment]
The `validate` function of a Redux Form config is a simple function that, when given an object of field/value pairs, returns an object of field/error pairs.
Check your validation function, make sure it's returning something like that.

Also give a look at the various examples available at http://redux-form.com.
They contain various examples of how validation works in v6.

So, because this feels like a question/usage issue, I'll close it.

**Comment by gustavohenke** [comment]
And @esbenp made [a great post](http://esbenp.github.io/2017/01/06/react-native-redux-form-immutable-styled-components/) about how to integrate React Native and Redux Form.
You should take a little time to read it as well.

**Comment by julien-rodrigues** [comment]
I already read the post and the docs and nothing solves my problem. The problem is that the validation is not fired when submitting. My validation method works because it is raising errors when an input is changed. 
I even changed my code to use the code from the blog post and I have the exact same problem. Shouldn't the validate method be called on submit?

```javascript
import React from 'react';
import {TextInput, Text, View, TouchableOpacity} from 'react-native';
import {reduxForm, Field} from 'redux-form';

const submit = values => {
  console.log('submitting form', values);
};

const renderInput = ({ input: { onChange, ...restInput }}) => {
  return <TextInput onChangeText={onChange} {...restInput} />
};

function Form({handleSubmit}) {
  return (
    <View>
      <Field
        name="email"
        component={renderInput}
      />
      <Field
        name="password"
        component={renderInput}
      />
      <TouchableOpacity onPress={handleSubmit(submit)}>
        <Text>Submit</Text>
      </TouchableOpacity>
    </View>
  );
}

export default reduxForm({
  form: 'signIn',
  validate: values => {
    const errors = {};

    console.log('validate called');

    if (!values.email) {
      errors.email = 'Email is required.'
    }

    if (!values.password) {
      errors.email = 'Email is required.'
    }

    return errors
  }
})(Form);
```

The validate method is called on each render, change of an input, but NOT when submitting. The gif below is this code running (sorry the frame of the gif is really slow): 

![untitled 1](https://cloud.githubusercontent.com/assets/4670971/23347914/b72b782e-fc73-11e6-9389-dc62854c0c40.gif)
