### ISSUE TITLE
Field onBlur callback has newValue always equal to previousValue

### ISSUE THREAD

**Issue by diwakar-s-maurya** [erikras/redux-form#2618]
version 6.5.0

`<Feild 
    onBlur={(e, newValue, previousValue) => {
        console.log(newValue === previousValue) />` <---always evaluates to true

**Comment by charlesrochati** [comment]
`<Feild` -> There is a typo here.

Is this rendering correctly?

**Comment by gustavohenke** [comment]
@diwakar-s-maurya, please provide a minimal, working example. Start from here: https://jsfiddle.net/gustavohenke/48814zsq/

And also please follow the template issue.

**Comment by gustavohenke** [comment]
ping @diwakar-s-maurya
