### ISSUE TITLE
How to reset `submitSucceed` to `false` when submitSucceed

### ISSUE THREAD

**Issue by loveholly** [erikras/redux-form#2625]
How to reset `submitSucceed` to `false` when submitSucceed?
I'm wondering if there existed a action creator to set this props to `false` or `true`, so that I can do something like this
```javascript
const AlipaySettings = reduxForm({
  form: 'alipaySettings',
  onSubmitSuccess(rst, dispatch, props) {
    setTimeout(() => {
      dispatch(resetSubmitSucceed())
    }, 3000);
  },
  onSubmitFail(error, dispatch, props) {
    // todo
  },
})(<SomeComponent />)
``` 
Or maybe we can do it like this:
```javascript
setTimeout(() => {
      dispatch(initialize('alipaySettings', {
        submitSucceeded: false,
      }))
    }, 3000);
```
However, it doesn't work because `initialize` only change the values, not other props.

**Comment by eriksape** [comment]
http://redux-form.com/6.5.0/docs/faq/HowToClear.md

Hi I am using the option D.

**Comment by gustavohenke** [comment]
@eriksape is right. If you want to keep the submitted values on the screen, update your `initialValues`.

Small demo: https://jsfiddle.net/cy07t8od/

**Comment by loveholly** [comment]
@erikras @gustavohenke thx!

**Comment by slavab89** [comment]
Did you manage to do that correctly?
I mean, `reset` also restores all your form values to their original values, so if you were to make some changes before that timeout triggers. You'll end up with other values.
I'm also looking for a way to change only the `submitSucceed` flag back to false.

My flow: After a user submits the form, show him an indication for X seconds, and then hide that indication.
I thought its best to use the `submitSucceed` as well but dont know if its the easiest way.
