### ISSUE TITLE
SubmissionError from onSubmit is dropping all fields except '_error'

### ISSUE THREAD

**Issue by guinnesscode** [erikras/redux-form#2627]
Hi,

I am attempting to pass a custom object of field errors to SubmissionError when onSubmit fails. When my component re-renders, the 'error' prop is only populated by the string I pass to '_error' instead of by an object mapping fields to errors like I would expect. Even why I try to pass a dummy field in addition to _error, all I get back is the single string.

Here is what my onSubmit looks like:

```javascript
const mapDispatchToProps = dispatch =>
    ({  
        onSubmit: (data) => {
            return dispatch(submitData(data))
            .catch(function(error) {
                dispatch(errorSubmitting());
                throw new SubmissionError({error_field_one: 'error', _error: 'There was an error.'});                
            }); 
        },  
    });
```

And from my wrapped component:

```javascript
const myComponent = function ({
    handleSubmit,
    error
}) {
    console.log(error);
    return (...)
}
```

From the logging statement, I can see that my error only contains the string I passed to '_error'. If I try passing in just my error object or an individual field without _error included, my error is undefined. What can I do to pass all of my errors to my component so I can work with them?

**Comment by kel-amg** [comment]
@guinnesscode As far as I know, the '_error' key is the one redux-form uses to populate the field errors (asyncValidation) being an exception.

**Comment by gustavohenke** [comment]
@kel-amg is right.

Docs:
- http://redux-form.com/6.5.0/docs/api/Props.md/#-error-any-
- http://redux-form.com/6.5.0/docs/api/Field.md/#-meta-error-string-optional-

Example:
https://jsfiddle.net/eftsysk9/
