### ISSUE TITLE
Manually update store then trigger form submission synchronously

### ISSUE THREAD

**Issue by TrevorHinesley** [erikras/redux-form#2634]
It would be great if there was a way to add/update a value manually on the form, then submit the form right after. For instance, in a form that tokenizes a credit card token for Stripe, I'd like to handle the Stripe response by setting the token ID in the callback then triggering form submit. Something like this:

```
stripeResponseHandler = (status, response, values) => {
    if(response.error) {
      // Stuff
      this.setState({
        error: response.error.message
      })
    } else { // Token created
      this.clearError()
      // These next two lines would need to happen syncronously, the submit would need to wait for the change.
      this.props.change('customer.stripe_token', response.id)
      this.onSubmit() // Whatever function I'd normally pass to the form's handleSubmit prop
    }
  }
```

This is pretty standard in regular forms, and it may very well be possible with redux-form, but I've looked through similar issues and don't see anything that would work.

**Comment by gustavohenke** [comment]
I'm unsure about what's the matter with the `change` prop, however you can use [the `submit` action creator](http://redux-form.com/6.5.0/docs/api/ActionCreators.md/#-submit-form-string-) to submit the form.

[Further example on remote submission](http://redux-form.com/6.5.0/examples/remoteSubmit/)

**Comment by TrevorHinesley** [comment]
My current workaround is to use componentDidUpdate, and if the value I'm manually setting exists in the values, I submit the form. There's gotta be a better way though.

**Comment by vnctaing** [comment]
Like @gustavohenke said, you could 

import the actions creators :
`import {  submit } from "redux-form";`

inject it to your component with the `connect()` function from react-redux
`connect(mapStateToProps, {
    submit,
  })(Component)`

and finally use it in your component like this : 

```
stripeResponseHandler = (status, response, values) => {
    if(response.error) {
      // ...
    } else { 
     // ...
      this.props.submit() // submit is injected via connect(), it will dispatch a submit action and manually submit your form when your stripe token will be set
    }
  }
```

**Comment by TrevorHinesley** [comment]
@vnctaing technically I could just call this.props.handleSubmit() without needing to pass the submit action creator at all. Again, my issue isn't how to submit the form though. It's how to wait for the change('customer.stripe_token', response.id) to complete before submitting.

**Comment by charlesrochati** [comment]
Well, that's doesn't seem to be wrong..

`this.props.change()` refer to the action creator you've just imported from `import {change} from 'redux-form';` right (async action)?  If so, i do that a lot without facing any problems.

**Comment by gustavohenke** [comment]
Hi @charlesrochati, if you could provide him [a working example](https://github.com/erikras/redux-form/issues/2618) it would be awesome, so we can close the issue.

**Comment by vnctaing** [comment]
@TrevorHinesley  Sorry, I've misunderstood the question. I'm confused why do we have to wait for change() result ? Isn't an a synchronous action ?

**Comment by TrevorHinesley** [comment]
@vnctaing change is async. Actions being dispatched are asynchronous.

**Comment by charlesrochati** [comment]
Check this out #1020, it's probably your solution, there's a discussion too.

@vnctaing change is an sync action, if you [take a look](https://github.com/evgenyrodionov/redux-logger) at the state, it gets updated correctly but redux-form somehow doesn't "see" it.

The solution (more likely a workaround) provided by the owner of this project is the following:

`<form onSubmit={this.props.handleSubmit(values =>
    this.props.actions.signUp({
      ...values,
      phoneNumber: '1231231234'
    })
  )}/>`

I ran this test to verify:

* Case 1:
`onSubmit(formValues) {
        this.props.changeValue('submit custom value');
        this.props.formValues;
    }`

`this.props.formValues;` doesn't get updated

* Case 2:
`updateField() {
        this.props.changeValue('some value');
        this.props.formValues;
    }`

`this.props.formValues;` gets UPDATED!

**Comment by charlesrochati** [comment]
try the mentioned solution, let us know if it works.

**Comment by TrevorHinesley** [comment]
Interesting, I'm not sure how that's synchronous if it's dispatching an action, but glad to hear it.

Either way, I wrote a modified version of a util I found prior:

```
const SubmitUtils = {
  submitOnChange: (nextProps, val, nextVal, submitOnBlank = false) => {
    if (nextProps.dirty && nextProps.valid) {
      let doubleDirty = false;
      if (nextVal !== val) {
        if(nextVal != undefined) {
          // If it's not undefined, submit it
          doubleDirty = true;
        } else if(nextVal == undefined && submitOnBlank) {
          // If it's null or undefined, but submitOnBlank is true, submit it
          doubleDirty = true;
        }
      }
      if (doubleDirty) {
        console.log("submitted")
        nextProps.handleSubmit()
      }
    }
  }
}

export default SubmitUtils
```

Then I just call it from the form's componentWillReceiveProps like so:

```
  componentWillReceiveProps = nextProps => {
    const nextCustomer = (nextProps.customer && nextProps.customer.toJS()) || {}
    const customer = (this.props.customer && this.props.customer.toJS()) || {}
    SubmitUtils.submitOnChange(nextProps, customer.stripe_token, nextCustomer.stripe_token)
  }
```

**Comment by charlesrochati** [comment]
Too much work for something very simple, but if it works, it works, right?!

For isolated cases, i still think that this is the best solution:

`<form onSubmit={this.props.handleSubmit(values =>`
  `  this.props.actions.signUp({`
 `     ...values,`
 `     phoneNumber: '1231231234'`
 `   })`
`  )}/>`

**Comment by TrevorHinesley** [comment]
http://stackoverflow.com/a/36070293/981177 <-- still not convinced change is synchronous...

But yes your method could work as well!

**Comment by charlesrochati** [comment]
Didn't know about this: "setState() does not immediately mutate this.state but creates a pending state transition. ... "

That's why they're appending the json directly.

**Comment by charlesrochati** [comment]
@gustavohenke I think it's ready to close.
