### ISSUE TITLE
On Hover Field

### ISSUE THREAD

**Issue by Kronenberg** [erikras/redux-form#2636]
Hello guys! In my application i am used the latest redux forms and i want to trigger on hover effect on my field ( i am not use fields i am use ONE FIELD Template for all my app) and u have a lot of events and they are working nice like as touched, untouch, errror e.t.c. Question is:  i want for example show and hide my Tooltip onMouseEnter event and onMouseLeave and when i create my custom events and send them to the my Field via props, they are not unique and all my fields are triggerd. Can somebody help me with this issue! Thx a lot and sorry for my english! 

`export const renderField = ({ id, errorClass, input, type, placeholder, meta: { touched, error, warning } })` `=> (`
  `<div>`
   `<div>`
      `<input className={touched && error ? errorClass : ''} id={id} {...input} placeholder={placeholder}` `type={type} />`
      `{touched && ((error && <ToolTip active={!!error} position="right" arrow="center" parent={`#${id}`}>`
        `<div>`
          `<p>{error}</p>`
        `</div>`
     `</ToolTip>) || (warning && <ToolTip active={!!error} position="right" arrow="center" 
`parent={#${id}`}>`
        `<div>`
          `<p>{error}</p>`
        `</div>`
      `</ToolTip>))}`
    `</div>`
  `</div>`
`);`

That is a little bit dirty but here i want to show my Tooltip not on error but on hover! 
Dear Redux Form Founders can you add those events to your library! Thx a lot and have a nice day!

**Comment by gustavohenke** [comment]
It seems to work just fine: https://jsfiddle.net/ux2e356r/

If the above doesn't help you, please move it to StackOverflow, as this is an usage question.
Thanks for using Redux Form.
