### ISSUE TITLE
getFormValues returns undefined even if initialValues have been passed

### ISSUE THREAD

**Issue by mqklin** [erikras/redux-form#2637]
**bug report**

I need form values inside form and use `getFormValues` selector for this. The problem is that `getFormValues` selector returns undefined until 2nd render cycle, but should `initialValues`:

http://www.webpackbin.com/NyGF1Q0KG

```
import React, { Component } from 'react';
import { reduxForm, getFormValues } from 'redux-form';
import { connect } from 'react-redux';

class App extends Component {
  render() {
    const { formValues: { test } } = this.props; // ERROR: cannot read property 'test' of undefined
    return (
      <div>
        {test}
      </div>
    );
  }
}

const FORM_NAME = 'MY_FORM';
const formSelector = getFormValues(FORM_NAME);
export default connect(state => ({
  formValues: formSelector(state)
}))(reduxForm({ form: FORM_NAME, initialValues: { test: 'SOME_TEXT' } })(App));
```

One possible workaround is to make `(state, ownProps) => formValues: formSelector(state) || ownProps.initialValues`, but I think `formSelector` should return `initialValues` if `formSelector(state)` returns undefined.

**Comment by gustavohenke** [comment]
It's not really possible to do something about this.
`formSelector` is called before the form has a chance to initialize, so the selector is only going to return something in the second round.
This means you won't be able to do `|| ownProps.initialize` in the first call to your `mapStateToProps` function.

I recommend you to keep your mapper with `formSelector(state) || {}`, or even to move your `initialValues` to inside the mapper (could save you one render cycle...)

**Comment by mqklin** [comment]
Thank you.
