### ISSUE TITLE
Proposal: Library of Redux Form Components

### ISSUE THREAD

**Issue by karthikiyengar** [erikras/redux-form#2640]
I've seen myself using redux-form extensively for many projects, thanks for the awesome efforts!

I was wondering if there would be any interest in creating a library of customizable components that would use redux-form. By now, I pretty much have components for most use cases written in a way that would be compatible with using redux-form. I'm thinking about open-sourcing it.

Had a couple of questions before I can go ahead and do that:

1. I'm internally using css-modules in my implementations. What would be the best way to keep the styling customizable by the user?
2. Should the components be stateless, or should it be possible for the user to use it even outside the context of redux-form component (thus being able to manage it's own state)? 

Would appreciate any other observations or suggestions that you might have around this.

**Comment by karthikiyengar** [comment]
Okay - I seem to have missed https://github.com/erikras/redux-form-material-ui

Maybe that can be extended with some other components that might be useful.

**Comment by devarsh** [comment]
Have a look at react-toolbox

**Comment by VladShcherbin** [comment]
@karthikiyengar if you'll decide to open-source it, please don't use material ui as default styling. It's ugly as hell.

**Comment by karthikiyengar** [comment]
@devarsh - Sounds like a reasonable way to do it. Thanks - this was exactly what I was looking for.

@VladShcherbin - I'm thinking more on the lines of a collection of custom and battle-tested components (react-select, for instance) made compatible with redux-form. Takes into account most use cases like validation errors, tooltips and so on.

**Comment by karthikiyengar** [comment]
Working on this at: https://github.com/karthikiyengar/react-component-libs

Do contribute if it seems interesting.
Thanks for all of your suggestions.
