### ISSUE TITLE
Missing convenience function for retrieving syncwarnings

### ISSUE THREAD

**Issue by thaylin79** [erikras/redux-form#2642]
I noticed there doesn't seem to be a convenience function for pulling the warnings like there is for pulling syncerrors. Any intention on adding this? Alternatively, I can add it in and do a pull request if you're swamped.

**Comment by gustavohenke** [comment]
#2624 is waiting to be merged

**Comment by gustavohenke** [comment]
I'll close as a duplicate of #2176.

**Comment by thaylin79** [comment]
Ok great! Thanks!
