### ISSUE TITLE
FieldArray not working properly inside FormSection

### ISSUE THREAD

**Issue by antoniomadonna** [erikras/redux-form#2643]
### What is the current behavior?
Add 3 fields, enter A, B and C as values, try to delete B. 
C will be deleted. (I think redux form is ignoring the section prefix)
http://www.webpackbin.com/Vk_r5kZ5z

### What is the expected behavior?
B should be deleted

### What's your environment?
redux-form@6.5.0
OS X/Chrome
Node 6.9.4

**Comment by bmv437** [comment]
I couldn't seem to replicate the issue you're seeing.
I've setup a JS fiddle here:
https://jsfiddle.net/bmv437/fffhLn5b/

See if you can tweak that to break in the same way you're describing.

**Comment by antoniomadonna** [comment]
The problem seems to be related to react-redux. I was using 4.4.5 but works fine with 5.0.3.

**Comment by bmv437** [comment]
Glad you got it working! Please close this issue if you can.
