### ISSUE TITLE
New comer here. How to inspect the example?

### ISSUE THREAD

**Issue by TrashPanda** [erikras/redux-form#2644]
Hi, I just started trying out redux-form, and couldn't find out how to handle submit function on the website. When I try to run the example to examine the code, it doesn't allow me to use console.log. Could someone help me?

**Comment by vnctaing** [comment]
Can you provide some code and ask the same question on Stackoverflow and send me the link, I'll be happy to help ? That would we easier for other people to find the answer in the future.

**Comment by gustavohenke** [comment]
@vnctaing is right. If you can provide evidence of a documentation problem, feature request or bug report, please open a new issue.

And, if you do this, please follow the issue template.
