### ISSUE TITLE
Docs `getFormNames` Outdated?

### ISSUE THREAD

**Issue by rizedr** [erikras/redux-form#2650]
### What is the current behavior?
The current [selector's docs](http://redux-form.com/6.5.0/docs/api/Selectors.md/) state that `getFormNames` has the following definition: `getFormNames() returns (state) => formNames:Array`.

However, the example shows otherwise:
```
MyComponent = connect(
  state => ({
    ...
    names: getFormNames('myForm')(state),
    ...
  })
)(MyComponent)
```

### What is the expected behavior?
The example should reflect the definition of the selector.

### Other informations
I know it's not a jaw-dropping bug, but some fellow developers might find that confusing when going the first time through it.

While we are at the selector's doc, I would add up one more info piece to that doc page: **How to use those selectors if you are passing the form name as a prop to your component?** Which would go something like this, for example let's take the `getFormValues`:
```
import {
  getFormValues,
} from 'redux-form'

const myGetFormValues = (form, state) => (getFormValues(form))(state);

MyComponent = connect(
  (state, initialProps) => ({
    values: myGetFormValues(initialProps.form, state),
  })
)(MyComponent)
```

**Comment by aikeru** [comment]
Is there a prescribed way to get all of the names for a given form?
It would seem you could just walk over the fields on 
```<form reducer state>.<form name>.registeredFields```

...but a blurb in the docs saying so would be really helpful.

**Comment by PavelPolyakov** [comment]
There is no `getFormNames` at all in `6.5.0`.
Just tried as seems I need it :)

What is the alternative?

**Comment by danielrob** [comment]
I'm quite sure it would have been faster to raise a [PR](https://github.com/erikras/redux-form/issues/3291) than raise this bug! Regarding your second issue, it's not really up to redux-form to document `connect()`'s `ownProps`, at least not in api docs... maybe implicitly from guide docs or examples. I'll leave that PR to you :). 

Eagerly closing as PR opened.

**Comment by danielrob** [comment]
P.S. Thanks for reporting!
