### ISSUE TITLE
Error not removed when async validate resolve is called

### ISSUE THREAD

**Issue by sattaman** [erikras/redux-form#266]
When doing async validation, the error state is not getting removed when resolve is called. 

    const asyncValidate = (values/*, dispatch */) => {
      return new Promise((resolve, reject) => {
       setTimeout(() => {
         if (['john', 'paul', 'george', 'ringo'].includes(values.username)) {
            reject({username: 'That username is taken'});
          } else {
           resolve(); //<--- This does not remove the error added above
          }
        }, 1000); // simulate server latency
      });
    };

**Comment by elmeister** [comment]
Please check react-redux-universal-hot-example [Survey Form validation implementation](https://github.com/erikras/react-redux-universal-hot-example/blob/master/src/components/SurveyForm/SurveyForm.js#L5) - it works, [here is the demo server](https://react-redux.herokuapp.com/survey).

**Comment by erikras** [comment]
You're absolutely right, @sattaman. It should. _Normally_ this is not an issue, because the `CHANGE` action unsets the async errors. Will fix.

**Comment by erikras** [comment]
Fixed in [`v3.0.7`](https://github.com/erikras/redux-form/releases/tag/v3.0.7).
