### ISSUE TITLE
Default radio button onBlur behaviour

### ISSUE THREAD

**Issue by ryanVincent** [erikras/redux-form#2660]
### Are you submitting a **bug report** or a **feature request**?
Bug Report

OnBlur does not adhere to default behaviour of a radio button list. Value is set to first item in radio button list when an onBlur event occurs.

![actual](https://cloud.githubusercontent.com/assets/1391731/23661388/89dd34f2-0344-11e7-966c-969b79841cf8.gif)

### What is the current behavior?
When tabbing through a form and tabbing over a radio button list, value is set to first item in radio button list when you tab out of radio button list.
[example](http://redux-form.com/6.0.1/examples/simple/)

### What is the expected behavior?
No radio item selected when you tab over a radio button list.
[example](https://jsfiddle.net/yeecLecm/)

### What's your environment?
redux-form: 6.2.0
browser: Chrome latest

**Comment by gustavohenke** [comment]
[v6.5.0 doesn't have this problem](http://redux-form.com/6.5.0/examples/simple)

See #2444 and #2445
