### ISSUE TITLE
meta.form missing for FieldArray

### ISSUE THREAD

**Issue by gustavohenke** [erikras/redux-form#2661]
### Are you submitting a **bug report** or a **feature request**?

Bug

### What is the current behavior?

`meta.form`, introduced by #2400, is not available within `FieldArray` component.

### What is the expected behavior?
`meta.form` should be available within `FieldArray` component.

### What's your environment?

Redux Form v6.5.0

### Other informations

![](http://i.imgur.com/9AZBNxv.png)

**Comment by ryerh** [comment]
The [`FieldArray`](http://redux-form.com/6.5.0/docs/api/FieldArray.md/)'s doc didn't say any thing about `meta.form` neither, seems like it's an unsupported feature by design.
