### ISSUE TITLE
Provide dirty values in `onSubmit`?

### ISSUE THREAD

**Issue by wmertens** [erikras/redux-form#2665]
### What is the current behavior?

`onSubmit` is called with `values` and `props`

### What is the desired behavior?

Also provide only the `dirtyValues`, so you know which values are different from the initial values without having to resort to object diffing.

That way, I can make forms with elements that show editable current values, but only send changes to the server.

**Comment by erikras** [comment]
So you'd like the `redux-form` library to do the object diffing for you? :smile:

**Comment by gustavohenke** [comment]
I'm against adding this to the API; it's probably not going to be very helpful, and could lead to some weird behavior when dealing with arrays (what happens when index 1 of the array changed, but index 0 didn't?).

But, let's give some time to the users to appreciate (or not) this suggestion.

**Comment by wmertens** [comment]
But… doesn't r-f only keep dirty fields in redux? Those are the values I'd
like to have. No?

**Comment by wmertens** [comment]
I now realized that r-f keeps the full value in the state, not just the set of changed values versus `initialState`. Changing that seems a bit extreme, so closing.
