### ISSUE TITLE
FieldArray fields.remove() - popping instead of removing.

### ISSUE THREAD

**Issue by Madebyfen** [erikras/redux-form#2666]
Potential bug, potential feature request; unclear of intended implementation/behaviour:

I have written a custom 'combo-field' component - comprising a text field and an autocomplete/live search; the container component (rendered using `<Field .../>` is implemented very similarly to the `react-rte` example [here](https://gist.github.com/erikras/5ca8dc618bae5dbc8faf7d2324585d01) (but contains 2 inputs instead of 1) while the `FieldArray` is implemented as in the [docs example](http://redux-form.com/6.5.0/examples/fieldArrays/), including the method of adding new fields dynamically.

I have followed [this](https://github.com/erikras/redux-form/issues/2291) thread, which mentions the behaviour I am experiencing: when using `fields.remove(index)`, the index appears to be ignored and the last item in the array is popped. Unfortunately the fix is eluding me.

I can add fields successfully; using `fields.push({})` inside a button `onClick` handler fires the `ARRAY_PUSH` action, adding an empty object to the correct `form.formName.values` index in the store. A `REGISTER_FIELD` action is fired, adding a named object to `form.formName.registeredFields` with `name`/`type`/`count` properties. Updating the values of any input works as intended/expected.

When using `fields.remove()`, an `ARRAY_REMOVE` action is fired with the correct index of the array item in the payload. Subsequently, an `UNREGISTER_FIELD` action is fired, however, **the payload for this action contains the `name` of the last field in the collection. The last field is then removed.**

~~When swapping out the combo-field component for a (either class based or stateless) component containing a single input, this doesn't happen.~~

When rendering a simple text `<input>` either inside the container component's `render()` method, or supplied directly to the `Field`'s `component` prop, this doesn't happen.

***
A repeated combo field seems like a straight-forward use-case, but I could be tackling this the wrong way; perhaps I should be splitting out the input components and not using the container for both as I am? I am open to suggestions, but in case this is actually a bug, there's the report :)
***

### Environment
`React 15.3.2`, `Redux 3.6.0`, `Redux Form 6.5.0`

***
**Edit:** I'm starting to think this crux of this issue has something to do with my desire to save multiple values from one conceptual 'input' (I wrongly presumed redux-form's `input.onChange` could handle objects, but the docs indicate strings only :/)

**Comment by gustavohenke** [comment]
Please provide a working example. Start from here: jsfiddle.net/gustavohenke/48814zsq/

**Comment by teldosas** [comment]
Hello @gustavohenke I'm having the same problem. So I wrote a working example here: https://jsfiddle.net/teldosas/vochka1L/ 

* Try clicking add 3 times then add values 1, 2 and 3 in the text fields.
* Then click the Delete button next to the first or second text field

The last field will be removed and not the one next to the button clicked

@Madebyfen have you found a work around for this?

**Comment by kjg531** [comment]
I'm also having this issue. If you copy/paste the FieldArray example in the docs this comes up.

**Comment by samuelg0rd0n** [comment]
I'm having the same issue. Any solution? I've been tearing my hair out about this for the last 2 days.

**Comment by gustavohenke** [comment]
I'm sorry for the delay here, folks.
I recreated @teldosas example here: https://codesandbox.io/s/BB1y62232
...and couldn't reproduce the issue 😕 

Any further ideas?

**Comment by gustavohenke** [comment]
If any of you could compare your solution with mine, and check what's different, it would be awesome, so we can have a better scope of the problem.

**Comment by Misiur** [comment]
If someone stumbles upon this issue, I think I've found the cause: in @teldosas example the culprit is this:
```
<input name={`${props.name}.sth`} type="text" />
```

If the name of the input is not exactly the value you get from the iterator, the result is popping instead of removing.

Cheers

**Comment by kesiena115** [comment]
@gustavohenke  I am having the same problem. I've compared my code with yours. I can see that in line 15 you have `name={field}`. I noticed that if I do this, it works as expected. However, if you change name to anything else, fields.remove() pops the last element instead of removing the current index. You can see this error by changing that line to:
    name={\`field-${index}\`}
Is there any special reason why we must pass in the object as name?

**Comment by erikras** [comment]
> Is there any special reason why we must pass in the field object as name?

@kesiena115 It's important because `FieldArray` gives you the proper way to address that element in the array, i.e. with bracket syntax: `'myField[1]'`. If you put `field-1`, it's not going to know how to read or write the value in the overall object (`{}`) that is holding all of the form's values. Make sense?

**Comment by asliwinski** [comment]
@Madebyfen I've just encountered the same problem. Have you figured out what was the source of the bug?

**Comment by Madebyfen** [comment]
I am so sorry for abandoning this thread; I'm afraid I didn't get to look at it much deeper, but will have a play around soon if it's still a thing. I've been working with Angular for the past few months 😬

**Comment by lbrewi** [comment]
I've been having the same problem when working with radio buttons. In @gustavohenke's working example, if you change the input type from text to radio in renderField (as in https://codesandbox.io/s/0mv0o3pjln), then the issue is still there.

**Comment by dtuyenle** [comment]
I am having the same issue here. Not sure what is the root cause. I do have a dropdown that dispatch a change for a field though not sure if that is the reason

**Comment by an4morph** [comment]
have the same issue
anybody find a solution?

**Comment by an4morph** [comment]
I had to use this temporary solution
If you have another please let me know

`const handleRemove = (array, index) => {
      const lastIndex = array.length - 1

      for (let i = index; i < lastIndex; i += 1) {
        fields.swap(i, i + 1)
      }

      fields.remove(lastIndex)
    }
`

and

`return (
        <div>
          {
            fields.map((field, index) => (
              <FieldsBlock
                key={index}
                onRemoveItem={() => handleRemove(fields, index)}
              />
            ))
          }
        </div>
)`

**Comment by an4morph** [comment]
I had to use this temporary solution
If you have another please let me know

`const handleRemove = (array, index) => {
      const lastIndex = array.length - 1
      for (let i = index; i < lastIndex; i += 1) {
        fields.swap(i, i + 1)
      }
      fields.remove(lastIndex)
    }
`

and

`return (
        <div>
          { fields.map((field, index) => (
              <FieldsBlock
                key={index}
                onRemoveItem={() => handleRemove(fields, index)}
              />
            ))  }
        </div>
)`

**Comment by an4morph** [comment]
I had to use this temporary solution
If you have another please let me know

```
const handleRemove = (array, index) => {
      const lastIndex = array.length - 1
      for (let i = index; i < lastIndex; i += 1) {
        fields.swap(i, i + 1)
      }
      fields.remove(lastIndex)
    }
```
and

```   
return (
        <div>
          { fields.map((field, index) => (
              <FieldsBlock
                key={index}
                onRemoveItem={() => handleRemove(fields, index)}<br>
              />
            ))  }
        </div>
)
```

**Comment by Madebyfen** [comment]
Hey guys, I haven't used Redux Form in a while, but I'm getting notifications, and I've been seeing indexes used for component keys -- have any of you tried using more 'stable' values for this (as [recommended](https://reactjs.org/docs/lists-and-keys.html#keys))? I seem to remember this fixed my problem. Sorry I can't expand further, hope it helps.

**Comment by ekeyur** [comment]
I am having the same issue with removing custom Dropdowns from a FieldArray. When tried to remove a particular index, It's popping instead of removing that particular index. It works as desired, when changed the component to an input field. Any suggestions? Has anyone found a solution?

**Comment by Madebyfen** [comment]
Did you try using a stable key other than a changeable index?

**Comment by ekeyur** [comment]
@Madebyfen : I don't understand what you are talking about. Can you update the example at https://codesandbox.io/s/rloymvrxpp and let me know exactly what do you mean by that. Thank you very much for taking a look at the issue.
 -- @dtuyenle : How did you solve this issue?

**Comment by dtuyenle** [comment]
@ekeyur  its the "key" in my case

**Comment by aakashkhatter1296** [comment]
@ekeyur change your key to key={${index}_${fields.length}}

**Comment by Aldizh** [comment]
@erikras 

> It's important because FieldArray gives you the proper way to address that element in the array, i.e. with bracket syntax: 'myField[1]'. If you put field-1, it's not going to know how to read or write the value in the overall object ({}) that is holding all of the form's values. Make sense?

This makes perfect sense. But there is a use case when this gets a little more complicated. Say within a row you have multiple inputs. (e.g a textfield and a date). How can you differentiate between the two fields? In the previous versions you simply append the an identifier for the field like 'myField[1].inputFiled' or 'myField[1].expirationDate'

Can the same thing be achieved with the newest version of redux forms?

**Comment by albertolive** [comment]
I'm having the same issue. And If I do what @aakashkhatter1296 say, all the values of the other inputs dissapear :/

**Comment by ekeyur** [comment]
@albertolive, I am pushing a randomly generated id field into field. Like, fields.push({ id: uuid() }). Then use that id as the value for key when iterating over to render the fields and it then deletes the right index. key={field.id}. depending on the number of things you can add in the fields array i would use a random number generator of the uuid package from npm. Hope this helps.

**Comment by eleventhaus** [comment]
In my case, this issue presents if I have any type of field that is not an `input type=text`. I have a field that is a photo upload component and `fields.remove` is popping instead of removing.

**Comment by ekeyur** [comment]
@eleventhaus : Check out this example @ https://codesandbox.io/s/rloymvrxpp. Although it is using input field, basically the structure should work if you plug in your custom component. If not, send me a private link to your repo or a chunk in codeSandbox and I would take a look at it.

**Comment by eleventhaus** [comment]
The input type I'm trying to integrate into the form is `type=file`. Using the example you linked, I changed the input type to file and it's not working.

**Comment by ekeyur** [comment]
I don't understand what you are trying to do exactly, but maybe this thread might help. It talks about file inputs
https://github.com/erikras/redux-form/issues/71

**Comment by eleventhaus** [comment]
I'm trying to create a Field Array with file type inputs.

**Comment by Wgil** [comment]
@ekeyur solution worked for me.

Possible workaround for: https://github.com/erikras/redux-form/issues/2735

**Comment by LeshemNoa** [comment]
I still have this bug, for the developers' consideration.

**Comment by LeshemNoa** [comment]
I am still facing this issue.

**Comment by u17zl** [comment]
> @ekeyur change your key to key={${index}_${fields.length}}

it works for me, huge thanks for you

**Comment by NorfeldtAbtion** [comment]
> key={${index}_${fields.length}}

this works like a charm 
```
key={`${index}_${fields.length}`}
```

but wonder if it will work `swap`... 🤔

**Comment by AlexexDenimus** [comment]
`setTimeout(() => fields.remove(index), 0); ` That kludge helped me.
