### ISSUE TITLE
getFormValues didn't work for me

### ISSUE THREAD

**Issue by hannahjin** [erikras/redux-form#2669]
I did the typical 
```
@connect((state, ownProps) => ({
    values: getFormValues(ownProps.form)(state),
}))
class MyForm extends React.Component {
   ...
}
```
However. This did not work.`values` is undefined inside my class. I was able to get the values from `state.get('form').get(ownProps.form).get('values')`.

I looked at the [source code](https://github.com/erikras/redux-form/blob/e9bcc1b54e211071f0cefc644c1ab7b2e93b9d78/src/selectors/getFormValues.js) for `getFormValues` and I am not sure why it didn't work.

**Comment by ntucker** [comment]
I use [formValueSelector](http://redux-form.com/6.5.0/examples/selectingFormValues/) myself ;)

**Comment by hannahjin** [comment]
It was an immutable issue. I was using immutable JS
