### ISSUE TITLE
Input Array

### ISSUE THREAD

**Issue by lemonCMS** [erikras/redux-form#267]
I thought is was possible to have an input array, but is cannot figure it out..

What is need is the following

````jsx
@reduxForm({
      form: formName,
      fields: ['box']
    })
````
````jsx
<input type="checkbox" name="box[1]" {...this.props.fields['box']} />
<input type="checkbox" name="box[2]" {...this.props.fields['box']} />
<input type="checkbox" name="box[3]" {...this.props.fields['box']} />
````
 I know that this will not work, i would just like to know if there is a possibility.

The closest i got was
````jsx
@reduxForm({
      form: formName,
      fields: ['box[1]','box[2]','box[3]',]
    })
````
````jsx
<input type="checkbox" name="box[1]" {...this.props.fields['box[1]']} />
<input type="checkbox" name="box[2]" {...this.props.fields['box[2]']} />
<input type="checkbox" name="box[3]" {...this.props.fields['box[3]']} />
````

But then this will not be submitted as an array.

Kind Regards,
Raymond

**Comment by lemonCMS** [comment]
right now i am busy using the change() function and that looks promission, so for now this is not an issue anymore.

**Comment by erikras** [comment]
No, this is not currently supported. What I've done in my project is create a faux-input `RadioList` component that will either generate "select one" radio buttons or "select multiple" checkboxes (both are really fake inputs, styled with check icons on `div`s), and then `RadioList` provides support for `value` and `onChange`, which is all that `redux-form` really needs for an input component to work.

**Comment by lemonCMS** [comment]
thx for your response.

I have done this with real checkboxes and the ````change```` action.

I have implemented it in [redux-form-generator](https://github.com/lemonCMS/redux-form-generator) package.

Take a look at the file [/src/types/checkboxList.js](https://github.com/lemonCMS/redux-form-generator/blob/master/src/types/checkboxList.js) on how i implemented this.

I believe this is a good way to go, but any input would be welcome if you have some :)

**Comment by thomasdavis** [comment]
I'm confused, was this issue closed before the introduction of these docs -> http://erikras.github.io/redux-form/#/examples/complex?_k=8ayeza ?

**Comment by erikras** [comment]
I thinks so, yes.

**Comment by thomasdavis** [comment]
Yep, never mind got it working.

Loving redux!

**Comment by matt-mcdaniel** [comment]
@thomasdavis could you point to the specific part of the docs that satisfy this use case? Having trouble implementing it.

**Comment by markau** [comment]
I am struggling to find a documented example of how to handle multiple checkboxes. I would really appreciate a hint! :weary:

**Comment by chuckweinberger** [comment]
@markau +1
