### ISSUE TITLE
FieldArray indexOf on fields props?

### ISSUE THREAD

**Issue by dehrax** [erikras/redux-form#2670]
### Are you submitting a **bug report** or a **feature request**?

Feature request

### What is the current behavior?

http://redux-form.com/6.5.0/docs/api/FieldArray.md/#fields-props
All methods reference an index. But what if you do not know the index? FieldArray assumes that you loop through fields and provide an input to each field. I do not.

```javascript
<FieldArray name='traits' component={renderTraits}/>
```

```javascript
const renderTraits = connect(mapStateToProps)((props) => {

	return (
		<div>
			{
			Object.keys(props.traits).map((member, index) => (
				<TextCheckbox key={index}
					onChange={val => val ? props.fields.push(member) : props.fields.remove(?????)} // <-------
					label={props.traits[member]}
					checked={props.fields.get(member) ? true : false}
				/>
			))}
		</div>
	);
});

```

### What is the expected behavior?

This is because I fetch some data from the Redux store. The objects are supposed to act like checkboxes, and when they are checked, the id should be added to the `fields` "array". When they are unchecked the id should be removed from `fields`.

I have roughly 100 items, and I expect them to change

Is there some nifty feature I have completely missed, is there a good built in way to do this or should a indexOf method be added to `fields`?

**Comment by gustavohenke** [comment]
Easy:

```js
fields.getAll().indexOf( value );
```
