### ISSUE TITLE
Field Array syncErrors NOt Updated onRemove

### ISSUE THREAD

**Issue by khpatel4991** [erikras/redux-form#2673]
### Are you submitting a **bug report** or a **feature request**?

**Bug Report**

### What is the current behavior?

I have a simple field array field, which on remove should remove the syncErrors array element when I do fields.remove(index), but is not
### What is the expected behavior?
The syncErrors of field array field should be removed on removing the field itself. 

### What's your environment?

Using Redux Form v6.5.0

**Comment by erikras** [comment]
Bug confirmed. 👍
