### ISSUE TITLE
Rename Field's 'name' prop

### ISSUE THREAD

**Issue by buscemrx** [erikras/redux-form#2674]
When using some controls with redux-form, ie. DateTimePicker. I have noticed that any control using "name" as a prop interferes with the Field element wrapper so Redux-form never finds the control and always gives an error, "Encountered a form control node without a name attribute."

Is possible to rename this required name attribute to be more unique( reduxformName, etc) for the Field element? That way controls with an existing "name" prop would not interfere with Redux-form.

**Comment by gustavohenke** [comment]
- Create a wrapper around your component, and rename the prop internally
- [Use the documented `props` prop](http://redux-form.com/6.5.0/docs/api/Field.md/#-props-object-optional-)

**Comment by buscemrx** [comment]
I am learning redux-forms and tried every variation using wrappers. Can you give me an example of using DateTimePicker with the Field wrapper. I cannot get this to work in redux-forms.          

<Field  name="testDate"  component={RenderCalanderFormControl}
                                       placeholder="mm/dd/yyyy" />


export const RenderCalanderFormControl = (props) => {

    return (
        <div>
            <DateTimePicker  className={props.className} time={false} placeholder={props.placeholder}
                                     defaultValue={props.defaultValue} format={"MMM dd, yyyy"}
                                     />
        </div>    );

};

**Comment by buscemrx** [comment]
Got it figured out. Thanks for you help
