### ISSUE TITLE
upgrading from v5, questions on best practices

### ISSUE THREAD

**Issue by realbugger** [erikras/redux-form#2676]
v6 has been out for a while but I haven't got chance to upgrade from v5 until now. One of the major motivation for the upgrade is that I have a huge form and re-rendering is killing the performance. But I do have a few questions in terms of design choices and best practices when moving from v5 to v6. I did a quick search but didn't find much discussion. If there is, please point me to the right direction.

* dynamically generated fields. In v5, I create dynamic fields by generating an array of field names and pass it to the redux-form component. In v6, it looks like I can do the same with `Fields`. But it also warns that doing so will cause all the fields to re-render whenever field value changes, which sounds very much the same as v5 behavior.  
An alternative approach is to, instead of using `Fields` component, dynamically generate a list of `Field` components (likely based on the same array of field names). Would this method given me better performance, or have the same re-rendering issue as using Fields?

* where is the formKey? In v5, I can pass a formKey to redux-form component, which essentially creates a nested object in redux form state. This is very useful as we pretty much only need one redux-form component and use it everywhere by passing different formKeys and dynamically generated fields to it (hence the dynamic field question above). I don't see formKey in v6. What should I do with v6? Should I pass a dynamically generated form name to the redux-form component. If so, would the name overwrites the default name come with redux-form decorator (see below)  
```
export default reduxForm({
  // Looks like I have to give it a name here. 
  // would this name be overwritten if I pass a different name as prop to the form component?
  form: 'simple'  
})(SimpleForm)
```
* about formValueSelector. Just to confirm, if I use it, the form would only re-render when the field I select changes, not when any field changes, right?

Thanks a lot!

**Comment by erikras** [comment]
> An alternative approach is to, instead of using Fields component, dynamically generate a list of Field components (likely based on the same array of field names). Would this method given me better performance, or have the same re-rendering issue as using Fields?

Yes, that should be fine, performance-wise, especially if you use the field name as the [`key` prop](https://facebook.github.io/react/docs/lists-and-keys.html#keys), so it won't have to rerender all the fields when you add a new one.

> where is the formKey?

Your guess is correct. [From the docs](http://redux-form.com/6.5.0/docs/api/ReduxForm.md/): **IMPORTANT: All of these configuration options may be passed into reduxForm() at "design time" or passed in as props to your component at runtime.** That includes `form` itself.

> about formValueSelector. Just to confirm, if I use it, the form would only re-render when the field I select changes, not when any field changes, right?

Yes. You're three for three! 💯
