### ISSUE TITLE
Update docs to show an example of initializing values without requiring redux

### ISSUE THREAD

**Issue by inostia** [erikras/redux-form#2678]
### Are you submitting a **bug report** or a **feature request**?
Feature request.

### What is the current behavior?
Current documentation of asynchronous setting of initialValues requires separate redux implementation.

### What is the expected behavior?
Not all users want/need to use a separate redux implementation in addition to redux-form.

### Other informations
See this SO question by myself: http://stackoverflow.com/questions/42742576/update-initialvalues-in-redux-form-asyncronously-without-using-redux.

It's possible to use `this.props.initialize` in an asynchronous `componentDidMount` to initialize values, rather than connecting a separate redux store and setting that to `initialValues` in in the `reduxForm` connector.

**Comment by michaelryancaputo** [comment]
This is how I did it:

```SettingsForm = connect((state, ownProps) => {
  return {
    initialValues: ownProps.initialValues,
  };
})(SettingsForm);

export default SettingsForm;
```

**Comment by davidfurlong** [comment]
even easier: 

```
<App>
<LoginForm initialValues={props.values} />
</App>
```

```
const LoginForm = (props) => (<Field/>);

export reduxForm({form: 'login'})(LoginForm);
```

I think this can be closed

**Comment by inostia** [comment]
Yep. for various reasons i ended up dispatching `initialize` rather than passing a prop... but yeah there's a bunch of ways
