### ISSUE TITLE
Website Fonts

### ISSUE THREAD

**Issue by damassi** [erikras/redux-form#268]
This is probably just me, but I thought I would throw in my two cents. When looking through the docs I'm finding the text somewhat hard to read. The font family is not a conventional "code" font (sharp edges, strange sizes) and the line spacing and font sizing throughout could be a adjusted so that its not so jarring when you read. Too much variation / contrast, leading to a less than gentle experience.

**Comment by erikras** [comment]
Thank you for your feedback. The code is rendered with [Google Prettify's Desert theme](http://google-code-prettify.googlecode.com/svn/trunk/styles/index.html). What would you suggest? A lighter background?

**Comment by damassi** [comment]
Its less the code snippets and more the contrast between sizing and fonts and colors. I would recommend simplifying your font selection and sticking to something that is sans serif, maybe swapping the black code viewers for something that is light, keeping the colors within a particular range, and reducing the font-size overall within the section delineators. With some of headers you really have to scan rather than just absorb on glance. 

I know this is a whole different beast, but the Ember.js docs are a really beautiful example of balance: http://guides.emberjs.com/v2.1.0/routing/rendering-a-template/

**Comment by erikras** [comment]
I agree that the ember docs look nice. The only web font I'm using is for the headers (`h1`, `h2`, etc.). Everything else is coming from Bootstrap.

**Comment by erikras** [comment]
I'm certainly not a big fan of the red inline code.
