### ISSUE TITLE
Documentation fix for resetForm FAQ

### ISSUE THREAD

**Issue by kenzanboo** [erikras/redux-form#2684]
### Are you submitting a **bug report** or a **feature request**?
Documentation fix for resetForm FAQ
http://redux-form.com/6.0.0-alpha.4/docs/faq/HowToClear.md/

### What is the current behavior?
resetForm is undefined

### What is the expected behavior?
calling this should reset the form

### What's your environment?
latest at this time, "redux-form": "^6.5.0",

### Other informations
looks like the functionality works if i call this.props.reset()
Should update docs to just show reset.

**Comment by erikras** [comment]
This is already fixed in the modern version of the docs. You're looking at the alpha docs.

http://redux-form.com/6.5.0/docs/faq/HowToClear.md/
