### ISSUE TITLE
Form not updating when re-render

### ISSUE THREAD

**Issue by francocorreasosa** [erikras/redux-form#2685]
Hi there, I have a form called named `SettingsForm` and when I get the settings from the server and re-render the parent container (`SettingsContainer`), changing the `initialValues` of the child form. The form doesn't do anything. (The new data is reaching the form component by the way...)

**Update 1:**
The form appears to be disconnected from the state, since I cannot change the values.

**Update 2:**
When I click the Submit button and the data reloads, all works.

### What's your environment?
```
redux-form: 6.5.0
node: 6.9.1
redux: 3.6.0
react: 15.4.2
```

**Comment by erikras** [comment]
You're going to need to share some more code. However, there's a chance that your problem can be fixed by setting [`enableReinitialize`](http://redux-form.com/6.5.0/docs/api/ReduxForm.md/#-enablereinitialize-boolean-optional-) to `true`.

**Comment by francocorreasosa** [comment]
I've tried enabling `enableReinitialize` to `true` but what I get is this working only when I change between routes (not if I go directly to the settings route).

**Comment by gustavohenke** [comment]
Hi @francocorreasosa, please provide us a working example. Start here: http://jsfiddle.net/gustavohenke/48814zsq/

**Comment by francocorreasosa** [comment]
I think this is also involved with routes, because when I go from `/` to `/settings` (where the form is), it works perfectly. But, when I go straight to the `/settings` route, this happens.

**Comment by danielrob** [comment]
@francocorreasosa it sounds like this is/was more an application specific problem rather than something pertaining to redux-form. If you think you have identified an issue with redux-form, please don't hesitate to provide an example and we'll re-open.
