### ISSUE TITLE
FieldArray Submission Setting Touched

### ISSUE THREAD

**Issue by andycanderson** [erikras/redux-form#2686]
On submit fields within a specified reduxForm are expected to be set to touched, however fieldArray does not get set to touched or re-rendered on submit. Is anyone else running to this problem?

I'm running Redux-Form 6.5.0 and following the example on http://redux-form.com/6.5.0/examples/fieldArrays/

**Comment by cjevning** [comment]
Yeah, I'm experiencing the same issue, and so is the live example.

**Comment by andycanderson** [comment]
Seems to be good as of Redux-Form 6.6.3 with following the sandbox example: https://codesandbox.io/s/Ww4QG1Wx
