### ISSUE TITLE
Problem with change object for md-radio-group

### ISSUE THREAD

**Issue by educc** [erikras/redux-form#2688]
**Information**
I have an array of objects with options and his selected value. When change the object for the radio group sometimes show the check.

**Reproduce bug**
Go to : [https://plnkr.co/edit/2qyiClwIeHQsZocDWVTa?p=preview](https://plnkr.co/edit/2qyiClwIeHQsZocDWVTa?p=preview)
1. Click on "opt1" radio.
2. Click on "Question 2" button
3. Click on "Question 1" button (doesn't show check on radio)
4. Click on "Question 2" button
4. Click on "Question 1" button (show check on radio)

**Angular Versions:**

Angular Version: 2.4.0
Angular Material Version: 2.0.0-beta.2

Help me, please

**Comment by gustavohenke** [comment]
Wrong library? 😄
