### ISSUE TITLE
Unable to resolve module redux-form/native

### ISSUE THREAD

**Issue by jshumakerpruitt** [erikras/redux-form#2689]
###  **bug report**

The native [docs](http://redux-form.com/6.5.0/docs/faq/ReactNative.md/) state that if your redux version is less than redux@4, you should import from redux-form/native.

### What is the current behavior?
`Unable to resolve module redux-form/native`

### What is the expected behavior?
Ability to `import {reduxForm} from 'redux-form/native'`

### What's your environment?

    "react-redux": "^4.4.6",
    "redux": "^3.6.0",
    "redux-form": "6.5.0",

node - v7.7.1
npm - 4.1.2
react-native - react-native-cli: 2.0.1 react-native: 0.38.0

### Other informations
If I use `import {reduxForm} from 'redux-form';` The app crashes on an android device but works on an android simulator

## Android errors when using `import {reduxForm} from 'redux-form'`

```E/ReactNativeJS( 6987): undefined is not a function (evaluating 'f(n)["fun
ction"==typeof Symbol?Symbol.iterator:"@@iterator"]()')
W/dalvikvm( 6987): threadid=16: thread exiting with uncaught exception (gr
oup=0x418bbda0)
E/AndroidRuntime( 6987): FATAL EXCEPTION: mqt_native_modules
E/AndroidRuntime( 6987): Process: com.reacttao, PID: 6987
E/AndroidRuntime( 6987): com.facebook.react.common.JavascriptException: un
defined is not a function (evaluating 'f(n)["function"==typeof Symbol?Symb
ol.iterator:"@@iterator"]()'), stack:```

**Comment by jshumakerpruitt** [comment]
I think there are typos in the docs listed above.  1) `redux@4` doesn't exist yet.  2) Are you supposed to import from 'react-redux/native'?

**Comment by gustavohenke** [comment]
This is probably an outdated FAQ that remained from v5.
And what's mentioned in there is `react-redux@4`, not `redux@4`.

**Comment by gustavohenke** [comment]
@jshumakerpruitt I created #2691 to fix this.

**Comment by jshumakerpruitt** [comment]
Awesome!  I tracked down the source of my error.  Field-level validation seems to fail on a real android device.
```
      const required = (value) => value ? undefined : 'Required'
      /* ...snip */
          <Field
            name='title'
            autoCapitalize='words'
            component={renderInput}
            validate={required}
          />
```
leads to the `Symbol.iterator` error posted above.  There was a similar issue with rxjs and react-native.  I'll try to gather the details and open a new issue.
