### ISSUE TITLE
anyTouched not changing after untouch action

### ISSUE THREAD

**Issue by gmlnchv** [erikras/redux-form#2698]
The `untouch` action doesn't seem to change the `anyTouched` prop in any way. One might expect `anyTouched` set back to `false` if none if the fields are currently `touched`. Keen to hear your thoughts on this @erikras.

**Comment by erikras** [comment]
Yep, this is a bug. Thanks!

**Comment by erikras** [comment]
Fix published in [`v6.6.0`](https://github.com/erikras/redux-form/releases/tag/v6.6.0).
