### ISSUE TITLE
Can validation depend on props?

### ISSUE THREAD

**Issue by janmarek** [erikras/redux-form#27]
Do you think it makes sense to change the validation function from `(data) => errors` to `(data, props) => errors`?

**Comment by erikras** [comment]
Why? Give me some of your reasoning.

**Comment by janmarek** [comment]
I wanted to add errors from server which I have in props to the other errors.

**Comment by erikras** [comment]
Could be done in your component's render() method, though.

```javascript
const errors = {
  ...this.props.errors, // from redux-form validation
  ...this.props.serverErrors // server validation errors
};
```

Is that not sufficient?

**Comment by janmarek** [comment]
It could, you're right. 

Other use case I can think of is to make the validation configurable (prop with minimum length of password etc.). But I don't need this one (yet).

**Comment by erikras** [comment]
Validation implementation is up to each developer, I think. Not part of redux-form. Personally, I think [this design](https://github.com/erikras/react-redux-universal-hot-example/blob/master/src/validation/surveyValidation.js) (mine) is pretty nice. Simple, but it works.
