### ISSUE TITLE
FieldArray meta.active

### ISSUE THREAD

**Issue by TrevorHinesley** [erikras/redux-form#2704]
Is there any reason FieldArray doesn't pass any kind of active flag? Any multi-select or similar elements could definitely benefit from this.

**Comment by danielrob** [comment]
There is a sort of reason...  opinionatedness: 

With `FieldArray` there is less an opinionated/standard way to fill the values of the array. Under the normal use case, `FieldArray` will be mapped to a bunch of `Field` components anyway. Under it's alternative use case where the field.<function> dispatchers are used to manage the array contents directly, it is sort of assumed the developer is truly in custom handling lands. Aka, there is no predictable final focusable destination in mind to attach an onFocus, and thus an active flag to. 

Compare this to `Field` which very often is mapped to an html input element which has a onFocus method, it make sense to provide a standard active prop. 

However, none of this is to say there isn't a valid use case for FieldArrays to have the concept of focus. Could you elaborate on your use case?

**Comment by danielrob** [comment]
Closing question due to non-response.

**Comment by TrevorHinesley** [comment]
Sorry, as I mentioned, a multi-select or similar component could benefit from know when it's active!

**Comment by danielrob** [comment]
Do you mean if any Fields which are children of the FieldArray are active, then the FieldArray is active? Please elaborate a little :D.

**Comment by TrevorHinesley** [comment]
Fields can be used within FieldArray, so those would have their own meta.active. It would be nice to have meta.active for the FieldArray itself. Honestly, this was a while back so I genuinely can't remember what the particular use case was :/
