### ISSUE TITLE
Change Field select background-color in safari browser.

### ISSUE THREAD

**Issue by nadalfederer** [erikras/redux-form#2706]
Bug report
How to change background-color of option inside <select> tag in safari.
https://jsfiddle.net/lebedevvladimir/vqskkgod

In chrome and firefox, it is working ok. The background of <option> is changing color inside select. But in safari browser, it has no effect. 

I tried like `*{background: rgba(0, 0, 0, 0.75)}` inside whole select, it has no effect as well. Is it some modal window, I don't know.

![github](https://cloud.githubusercontent.com/assets/6043510/24082585/1d7c3ce2-0cd9-11e7-8b71-0956c39df80b.png)

**Comment by gustavohenke** [comment]
This is unrelated to Redux Form. Ask at StackOverflow.
