### ISSUE TITLE
Normalizing values differently from the store

### ISSUE THREAD

**Issue by FacundoGFlores** [erikras/redux-form#2710]
Reading the docs I see that `normalizing` has the following behaviour: Store and Field values are the same, i.e: if I type `333-333-3333` for the phone field, in the store I get: 

```
form: {
    normalizing: {
      values: {
        min: 1,
        max: 10,
        phone: '333-333-3333'
      },
      ...
    }
} 
```

it would be great to know a way to store the value without the formatting. I know it would be easy to do this with just `react`, but, it would be useful when I have initial values in `redux-form`. Let's say I get from database the phone number as: '3333333333', then I put it in `initialValues` for the `redux-form`, it should be rendered correctly in the `Field` through `normalize`. The phone number is a simple case because I have some complex components that would benefit from the behavior I've described. 

Maybe I did not find the right concept for doing it. But the thing is I'd like to take the values from the store and send them to the API "normalized" or "well-formatted". 

Could it be achieved with `redux-form`?

**Comment by sbkn** [comment]
AFAIK there is `normalize` and there is `format`. `normalize` would take the input value and modify it before storing it, while `format` would take the stored value and modify before presenting it in the given field. Thus when retrieving a normalized value (f.e. "3333333333") from DB, same would be formatted using `format` before being presented to user (as f.e. "333-333-3333").

Does that help?

**Comment by FacundoGFlores** [comment]
The docs says: "One common use case is when you need a value to be in a certain format, like a phone number or a credit card." So I supposed the following:

1- Field phone has: 333-333-3333
2- Normalize
3- Store has: 3333333333

But the thing is:

![image](https://cloud.githubusercontent.com/assets/5167196/24146672/79dc8536-0e15-11e7-9fd6-5024ff88b56f.png)

both has the same "string", I would like to have two different values, one in the field an other in the store, so that's why I supposed using normalize would do the trick, but it seems it does not.

**Comment by sbkn** [comment]
The assumption is wrong, because all `normalize` does is modify the value before it gets stored. In this example user would type in only 3's (without the dash), but store would receive the normalized value, thus "333-333-3333". And this is also the value which the field displays to user, so though you've never typed in any dash, you're still seeing the value including the dash.

What I think you want is:

- User types in random input
- Input is being modified by a `normalize` method
- Normalized value is being stored
- Value is being presented to the user in a formatted state (`format`)

**Comment by FacundoGFlores** [comment]
I tried the format method from `Field`. As the docs says: 

> Formats the value **from** the Redux **store** to be displayed in the field input.

Ok, so giving the following function for `format`:

```
const format = (value) => {
  if (!value) {
    return value;
  }
  return `${value}_`;
};
```
The problem is that the formatted value is being stored in the redux store, I mean I have the following `Field`

![image](https://cloud.githubusercontent.com/assets/5167196/24200352/aebe2a30-0eeb-11e7-8d3a-52a79a8fc2e0.png)

And the store has:

![image](https://cloud.githubusercontent.com/assets/5167196/24200423/c80a949c-0eeb-11e7-9e42-1275daf8f11a.png)

according to the docs: shouldn't `format` (function) be applied to the field only and not to the redux store?

**Comment by sbkn** [comment]
Consider the following:
- Normalized value is in store (e.g. "33333")
- Field shall display value from store, thus stored value is being sent through the `format` function and formatted value is being put into field (e.g. "333-33")
- Field needs to save its current value in store, thus value from field is going through the `normalize` function and being saved to store afterwards (e.g. "33333")

All in all - the field is trying to save its current value to store, so your `normalize` function needs to remove all formatting which is applied by `format`
