### ISSUE TITLE
Form submits to server with page refresh

### ISSUE THREAD

**Issue by swils** [erikras/redux-form#2711]
(Sorry, I've never asked for this kind of help before. But this one is *really* driving me nuts. I've looked in other issues and in the code, but could not really find anything that helps.)

The problem: I hooked up ReduxForm as per the docs and the code examples, and it's quite simply not working. 

The symptoms, as far as I can see: 
- The form is submitting to the server. This means a page refresh, both when I click the submit button and when I press enter in a field. This should not happen and does not happen in the examples.
- The `NetworkForm` component (see below) does not receive a `values` prop. If I understood the docs properly, this prop should be there.
- The `handleSubmit` is called with what appears to be an event, not the form values.

Here are some relevant parts of the code:

    // ...
    import { Provider } from "react-redux";
    import { combineReducers, createStore } from "redux";
    import { Form, Field, reduxForm, reducer as reduxFormReducer } from "redux-form";

    const reducer = combineReducers({
      form: reduxFormReducer // mounted under "form"
    });
    const store = createStore(reducer);

    let NetworkForm = (props) => {
      const { handleSubmit, pristine, submitting } = props;
      return (
        <form onSubmit={handleSubmit}>
          <div className="form-group">
            <label htmlFor="name">Name</label>
            <Field name="name" type="text" component="input" />
          </div>
          <button type="submit" disabled={pristine || submitting}>Submit</button>
        </form>
      );
    };

    NetworkForm = reduxForm({
      form: 'network'  // a unique identifier for this form
    })(NetworkForm);

    class Network extends React.Component {
      render() {
        return (<NetworkForm handleSubmit={this.handleSubmit.bind(this)} />);
      }

      handleSubmit(values) {
        console.log(values);
      }
    }

    // ...
    ReactDOM.render(
      <Provider store={store}>
        <Network />
      </Provider>,
      document.getElementById("content")
    );

Versions:
- react: 15.4.1
- redux: 3.6.0
- react-redux: 5.0.3
- redux-form: 6.5.0

This should be very close to what is used in the examples, which btw are working properly on my system. 

I really hope somebody can help me, and that it's not something embarrassingly stupid ;-)

**Comment by erikras** [comment]
It's pretty subtle, and wasn't immediately obvious. We've all experienced bugs like these, so don't feel embarrassed...well, perhaps a soft forehead slap is warranted... 😜
```jsx
  render() {
    return (<NetworkForm handleSubmit={this.handleSubmit.bind(this)} />);
    //                   ^^^^^^^^^^^^
  }
```
should be
```jsx
  render() {
    return (<NetworkForm onSubmit={this.handleSubmit.bind(this)} />);
    //                   ^^^^^^^^
  }
```

There's a FAQ about this point of confusion: [`onSubmit` vs. `handleSubmit`](http://redux-form.com/6.5.0/docs/faq/HandleVsOn.md/)

---

Bonus React Tip: It's best if you avoid doing `bind(this)` in the `render()` method, since that will create a new function on every render of the parent, which is not `===` to the previous one, which will force the child to render. Your options are:
```jsx
constructor(props) {
  super(props)
  this.handleSubmit = this.handleSubmit.bind(this)
}
```
...or make handleSubmit an arrow function, which will have `this` implied as a closure.
```jsx
handleSubmit = (values) => {
  console.log(values)
}
```

**Comment by swils** [comment]
Thanks! 

(I actually read that (and the reduxForm docs) and still somehow overlooked its relevance for my problem. Soft slap applied.)

**Comment by rafaelcavalcante** [comment]
Thanks! :)
