### ISSUE TITLE
Focus on checkbox changing form value but not checkbox state

### ISSUE THREAD

**Issue by indapublic** [erikras/redux-form#2713]
### What is the current behavior?

```
export const renderCheckboxField = ({ input, meta: { touched, error, warning }, autoFocus }) => (
  <div className={classnames('form-group', touched && error ? 'has-danger' : '')}>
    <label className="form-switch pull-xs-left">
      <input {...input} type="checkbox" className="form-switch-input" autoFocus={autoFocus} />      
    </label>
  </div>
)

<Field
  name={`${item}.published`}
  component={renderCheckboxField}
/>
```

When I focused on any checkbox via Tab, form value is changed, but checkbox is still unchecked

![6-4uqzsk](https://cloud.githubusercontent.com/assets/856260/24130926/4bdd743e-0e37-11e7-9f1a-85abd915c5cc.png)
![83ds81_2](https://cloud.githubusercontent.com/assets/856260/24130929/4d9a676e-0e37-11e7-8dc7-2e60ebc857ca.png)

### What is the expected behavior?
Category has value in redux, validation is passed, but interface shows incorrect info

### What's your environment?

"redux-form": "^6.4.3"
OSX: 10.12.3
Chrome: Version 59.0.3046.0 (Official Build) canary (64-bit)

**Comment by danielrob** [comment]
@indapublic were you able to resolve this issue? If not could you verify it against a recent version of redux-form, and provide a sandbox reproduction if it is still existing? Thanks for using Redux-Form!
