### ISSUE TITLE
getting redux-form to update state when DOM fields are updated

### ISSUE THREAD

**Issue by dhcloud** [erikras/redux-form#2715]
Hi,

This is a redux-form question and I apologise if it should be on stackoverflow but I've tried there and found little help as yet. 

I've started using redux-form to validate a user details form. The form includes an [address-lookup service provider](http://www.pcapredict.com) that populates DOM input text fields after selecting an address.

When the service providers script populates the DOM with the selected address, is there a way to get redux-form to automatically respond and update the state or would it be better to have these fields separate from redux-form and updated in the state via a separate action/reducer.

Guidance on this greatly appreciated.

**Comment by djvern** [comment]
I have the exact same issue. Postcode Anywhere have created an [Angular directive](https://github.com/PostcodeAnywhere/angular-captureplus) but after speaking to their customer support there is no React/Redux equivalent.

**Comment by djvern** [comment]
In case this helps anyone I've got it working by using the [API version of the address lookup.](https://www.pcapredict.com/support/articles/article/captureplus-javascript-guide/) This creates a control object that provides a listener that can detect when a user selects and populates their address. I just hooked this up to the Redux form change action within my component's componentDidMount method:

```
componentDidMount() {

    let { dispatch } = this.props;

    window.control.load();

    window.control.listen('populate', function(address, variations) {
      dispatch(change('Form', 'address_line_1', address.Line1));
      dispatch(change('Form', 'address_line_2', address.Line2));
      dispatch(change('Form', 'address_line_3', address.Line3));
      dispatch(change('Form', 'address_line_4', address.Line4));
      dispatch(change('Form', 'city', address.City));
      dispatch(change('Form', 'post_code', address.PostalCode));
    });

  }
```

**Comment by gustavohenke** [comment]
Great to see a good example provided here - thanks, @djvern!

This question is strongly related to React itself, and not to Redux Form.
So another way you could do it is to use a [`MutationObserver`](https://developer.mozilla.org/en/docs/Web/API/MutationObserver).
But this seems a lot more complex than simply using an API.
