### ISSUE TITLE
Provide reducer in a way that can be split

### ISSUE THREAD

**Issue by wmertens** [erikras/redux-form#2722]
### **feature request**

I put redux-form's Field and redux-form behind asynchronously loading components, so that the app has a smaller initial download. However, I don't have on-the-fly reducer updating, and so I include the reducer from the start.

### What is the current behavior?

The entire redux-form module gets included.

### What is the expected behavior?

Only the reducer function should get loaded in the initial bundle. I would hope that just `import {reducer} from 'redux-form'` is sufficient, but `import reducer from 'redux-form/reducer` would also be ok.

### What's your environment?
R-F 6, Webpack 2 + tree shaking, babel.

### Other informations

I have a workaround: I require `redux-form/lib/reducer` and `redux-form/lib/structure/plain` and then create the reducer. Not great, since I'm using internal APIs.

The result is worth it though, 20KB less gzipped minified. On mobile, every KB of the initial download counts.

**Comment by wmertens** [comment]
Just a note that my workaround no longer works in 6.7.0

**Comment by wmertens** [comment]
Oooh - the reducer is available separately at `redux-form/es/reducer` or `redux-form/es/immutable/reducer` 🎉 

The only caveat is that to make this work on the server side you need to *not* declare redux-form/es as external, because Node doesn't support ES import syntax.

Not sure what the best way to proceed with this is…

* Document it somewhere?
* Make it so `redux-form/reducer` loads the appropriate es/non-es form for your environment?
* This is fine, close?

**Comment by gustavohenke** [comment]
[Do you want something like this?](http://redux-form.com/6.8.0/docs/faq/BundleSize.md/)

You can pull the same files from `redux-form/lib`.

**Comment by wmertens** [comment]
😍😍😍 ok I missed that. Excellent! No further action required, thank you!
