### ISSUE TITLE
Passing an array into Field level validate prop causes an "Invalid prop" error

### ISSUE THREAD

**Issue by dtipson** [erikras/redux-form#2726]
### Are you submitting a **bug report** or a **feature request**?
Bug Report

### What is the current behavior?
Passing an array into Field level validate prop causes "Invalid prop `validate` of type `array` supplied to `Field`, expected `function`." error to be thrown

### What is the expected behavior?
`validate` should accept an array of functions as well as a single function, at least per the example in the docs here:
http://redux-form.com/6.6.0/examples/fieldLevelValidation/

### What's your environment?
6.6.0, Chrome

### Other information
It looks like this is from recently adding prop types that didn't exist before: https://github.com/erikras/redux-form/commit/bd4d1fb3731dcb93e42ca787cbbbd23610aa507f

**Comment by ViggoV** [comment]
I am getting this error too, after updating to version 6.6.0.. The validation itself seems to work, though..

**Comment by jpmelnik** [comment]
+1

**Comment by davidfurlong** [comment]
https://github.com/erikras/redux-form/commit/08a377ead23ab34c3116c8e02782b1c292b5ebec

**Comment by dtipson** [comment]
Awesome, yep.
