### ISSUE TITLE
Soft Validation fails (Warning state)

### ISSUE THREAD

**Issue by Evanion** [erikras/redux-form#2727]
Feature request
### What is the current behavior?
If a validation fails, the field is considered invalid, and in turn the form is considered invalid.

### What is the expected behavior?
The ability to soft fail a field where it's still considered valid, but where there might be issues with the data.

One example where this would be useful is in complexity fields like passwords. Where the password meets the minimum requirements, but might not be complex enough to be considered safe.

Many CSS frameworks, like Material Design have state markers for this state.. Default, Warning, Danger and Success are states supported by many CSS frameworks.

**Comment by gustavohenke** [comment]
You can already do this 😉 

http://redux-form.com/6.6.0/docs/api/ReduxForm.md/#-warn-values-object-props-object-warnings-object-optional-
