### ISSUE TITLE
What to do with the new onChange option without the props ?

### ISSUE THREAD

**Issue by oallouch** [erikras/redux-form#2728]
Hi,
The new onChange option at the reduxForm level could be great, but how can I propagate the event up the component tree without the props ?
Btw, it would also be great to know which Field was changed, using another parameter like the name or the source event.

Thx in advance,
Olivier

**Comment by gustavohenke** [comment]
>  how can I propagate the event up the component tree without the props ?

The only way I see is to make use of `this`, which is not necessarily available to you (because you may be using functional components!).

Anyway, I agree with both changes 👍

**Comment by erikras** [comment]
Fix published in [`v6.6.1`](https://github.com/erikras/redux-form/releases/tag/v6.6.1).
