### ISSUE TITLE
Mounting form reducer to state which is Immutable.Map instance

### ISSUE THREAD

**Issue by janmarek** [erikras/redux-form#273]
Hi, we use Immutable.js for everything in our Redux app and there is a problem with mounting form reducer to `rootState.form`. To be clear - it is perfectly fine you use plain objects. We only need to customize redux form mounting point to `rootState.get('form')` instead of `rootState.form`. 

The problem in http://erikras.github.io/redux-form/#/examples/alternate-mount-point is somewhat similar. It could be done easily just by supporting functions in `reduxForm({form: 'alternateMountPoint'})`. But it is not very practical, because you need to repeat it in every form.

For this issue we have a solution for us. Unfortunately it is not very elegant either. We use Immutable.Record for state shape which supports getters for values so redux-form can access `state.form` without noticing it isn't plain object.

**Comment by erikras** [comment]
Covered by #110. Fix coming soon.

**Comment by janmarek** [comment]
Response time 3.5 minutes? Nice, thank you :)

**Comment by erikras** [comment]
Fixed in [`v3.0.7`](https://github.com/erikras/redux-form/releases/tag/v3.0.7).
