### ISSUE TITLE
issue after 6.6.0 update

### ISSUE THREAD

**Issue by matiishyn** [erikras/redux-form#2730]
### Are you submitting a **bug report** or a **feature request**?
looks like a bug, happened after updating to `6.6.0` version

### What is the current behavior?
inside my `form.js` file I have

```js
import {Field, reduxForm} from 'redux-form';
import {required, email} from '../../helpers/validation';
import {Input} from '../../components';
...
const LoginForm = (props) => {
  const {handleSubmit, submitting} = props;
  return (
    <form onSubmit={handleSubmit}>
      <Field
        name="email" type="email"
        component={Input}
        placeholder="Email"
        glyph="envelope"
        validate={[required, email]}    // <- error is here
      />
...
```
and an error in console:
> Warning: Failed prop type: Invalid prop `validate` of type `array` supplied to `Field`, expected `function`.

This is an example from here: http://redux-form.com/6.6.0/examples/fieldLevelValidation/

### What is the expected behavior?
If this (` validate={[required, email]}`) is not valid then tell me please how to set multiple validation, and why you still have the example with array here: http://redux-form.com/6.6.0/examples/fieldLevelValidation/

### What's your environment?
MacOS
node v6.10
    "react": "^15.4.2",
    "redux": "^3.6.0",
    "redux-form": "^6.6.0",

**Comment by mereskin** [comment]
+1

Looked into node_modules, src/Field has `validate: PropTypes.func`. 

Some issue with release?

**Comment by benhunt29** [comment]
Yep, I'm getting this error too. When I revert to 6.5, the error disappears

**Comment by davidfurlong** [comment]
duplicate to #2726 please close

**Comment by gustavohenke** [comment]
Thanks for the heads up, @davidfurlong!
