### ISSUE TITLE
Prop collision with Field and Reactstrap Input components

### ISSUE THREAD

**Issue by marekolszewski** [erikras/redux-form#2733]
Certain Reactstrap [form components](https://reactstrap.github.io/components/form/) (e.g. Input) expect a 'state' prop for highlighting error states (e.g. for input validation). Unfortunately, this makes it hard to combine Reactstrap with Redux-Form as it doesn't look like you can pass a 'state' prop via the Field component down to the Reactstrap Input component. Instead, the state prop gets overwritten by a competing state prop in the ConnectedField component, which appears to be used to store whether a field has been touched or visited.

Given that prop collisions like this are bound to happen, I'm wondering if it makes sense to create an 'extra-component-props' prop in the Field component that lets you explicitly pass props in cases of naming collisions.

Curious what you guys think.

**Comment by peshi** [comment]
Hm, what does your implementation look like?

**Comment by marekolszewski** [comment]
Sure, here's an example with the error state hardcoded. The thing of note is the 'state' prop on the password field. That prop is expected by the Input component to make it red, and to show the FormFeedback component below the field. Unfortunately, it doesn't make it down to the Input component as it's overwritten by a 'state' prop in ConnectedField.

```javascript
import { Button, Form, FormGroup, Label, Input, FormText } from 'reactstrap'
import { Field, reduxForm } from 'redux-form'

@reduxForm({ form: 'Signup' })
export default class SignupForm extends Component {
  render() {
    const { handleSubmit, submitting } = this.props
    return (
      <Form onSubmit={handleSubmit}>
        <FormGroup className='floating-label-form-group'>
          <label>Email</label>
          <Field className='form-control' name='email' component='Input' type="text" placeholder='Email' />
        </FormGroup>
        <FormGroup className='floating-label-form-group'>
          <label>Password</label>
          <Field className='form-control' name='password' component='Input' type='password' placeholder='Password' state='danger' />
          <FormFeedback>Email or password incorrect</FormFeedback >
        </FormGroup>
        <div>
          <Button color='primary' type='submit' disabled={submitting}>Sign Up</Button>
        </div>
      </Form>
    )
  }
}
```

**Comment by gustavohenke** [comment]
1. If you're not using it yet, add a validation function
2. Implement your own wrapper and make use of `meta.error` prop.

Idea on how to implement such wrapper component:
https://github.com/erikras/redux-form/issues/2282#issuecomment-270170347

**Comment by gustavohenke** [comment]
Ah, and regarding this...

> Given that prop collisions like this are bound to happen, I'm wondering if it makes sense to create an 'extra-component-props' prop in the Field component that lets you explicitly pass props in cases of naming collisions.

You can already do that - use `input` prop as an object.
Everything that gets passed into it is spread in the root level of the input component.

**Comment by marekolszewski** [comment]
> You can already do that - use input prop as an object.

Thanks. I just gave it a try but I don't think it's working as what I was suggesting. E.g. When I try this:

`<Field className='form-control' name='password' component='Input' type='password' placeholder='Password' input={{state: 'danger'}}/>`

I get an 'input' prop in my final Input component, not the 'state' prop that the Input component needs.

> If you're not using it yet, add a validation function

Yes, I'm using one. This was just a hard coded example to test out Reactstrap.

**Comment by gustavohenke** [comment]
Ah. I see that you have a small problem in your `Field` declaration.
You're passing `component='Input'`, while it should be `component={Input}`.

**Comment by gustavohenke** [comment]
> You can already do that - use `input` prop as an object.
Everything that gets passed into it is spread in the root level of the input component.

Oops! My mistake. Actually, it's [`props`](http://redux-form.com/6.6.0/docs/api/Field.md/#-props-object-optional-), not `input`! 😅

**Comment by marekolszewski** [comment]
Amazing! I can't believe I missed that. Sorry for the trouble. 

Rereading the docs I see my confusion. The three points at the top of the [Field docs](http://redux-form.com/6.6.0/docs/api/Field.md/) made it seem that all props other than 'name' and 'component' get passed to the wrapped component. It might make sense to call out things like 'props' and 'input' earlier so it's clearer that there are other optional Field specific props.

**Comment by peshi** [comment]
@marekolszewski I see you got some input already.
Based on your first input I tested a custom Field component which you could use like this.

Form
```
<Field name="firstname" component={renderInput} type="text" placeholder="First name" />
```

Component
```
import React from 'react';
import classNames from 'classnames';
import { FormGroup, Input, FormFeedback } from 'reactstrap';

export class renderInput extends React.PureComponent {
  static propTypes = {
    input: React.PropTypes.object,
    placeholder: React.PropTypes.string,
    type: React.PropTypes.string.isRequired,
    meta: React.PropTypes.shape({
      touched: React.PropTypes.bool,
      error: React.PropTypes.any,
    }),
  };

  render() {
    const {
      input,
      placeholder,
      type,
      meta: {
        touched,
        error,
      },
    } = this.props;

    const classes = classNames({
      success: touched && !error,
      danger: touched && error,
    });

    return (
      <FormGroup color={classes}>
        <Input {...input} type={type} placeholder={placeholder} state={classes} />
        {touched && error && <FormFeedback>{error}</FormFeedback>}
      </FormGroup>
    );
  }
}
```

**Comment by rahamin1** [comment]
Did it work? I would like to use redux-form with reactstrap, too...

**Comment by fdutey** [comment]
```javascript
const fieldWithErrors = Comp => props => {
  const { meta: { touched, error } } = props

  return (
    <>
      <Comp {...props} />

      {touched && error && (
        <FormFeedback>
          <FormattedMessage id={error}/>
        </FormFeedback>
      )}
    </>
  )
}
```

```javascript
const ReactStrapInput = (props) => {
  const { input: { value } } = props

  return <Input {...props} value={value} />
}
```

```javascript
<FormGroup>
  <Label>Foo</Label>
  <Field component={fieldWithErrors(ReactStrapInput)} type="whatever" name="foo" />
</FormGroup>
```

That might help
