### ISSUE TITLE
Array no longer supported as validate prop (Field)?

### ISSUE THREAD

**Issue by richardkall** [erikras/redux-form#2736]
### Are you submitting a **bug report** or a **feature request**?
Bug report.

### What is the current behavior?
Throws a proptype warning in development mode:

```
Warning: Failed prop type: Invalid prop `validate` of type `array` supplied to `Field`, expected `function`.
    in Field
```

### What is the expected behavior?
According to [the docs](http://redux-form.com/6.6.0/examples/fieldLevelValidation/) it should be allowed to pass an array of functions as the `validate` prop. This warning did not show up in v6.5.0.

### What's your environment?
redux-form@6.6.0

**Comment by davidfurlong** [comment]
duplicate to https://github.com/erikras/redux-form/commit/08a377ead23ab34c3116c8e02782b1c292b5ebec please close

**Comment by davidfurlong** [comment]
@richardkall new release fixes
