### ISSUE TITLE
Clean errors when focus field.

### ISSUE THREAD

**Issue by GaryChangCN** [erikras/redux-form#2739]
Is there have any methods to clean errors when focus field.

I try to use this way, but no errors when blur field.

```
form:form.plugin({
		regForm:(state,action)=>{
			var state=Object.assign({},state);
			switch (action.type) {
				case FOCUS:
					state.syncErrors[state.active]=null;
					return state;
				default:
					return state;
			}
		}
	}),
```

**Comment by danielrob** [comment]
Could you just do this in the UI wherever you're displaying the error? For example: 

```
{touched && !active && error}
```

**Comment by GaryChangCN** [comment]
I have solved this problem but forgot to close the issue, sorry
