### ISSUE TITLE
every is not a function

### ISSUE THREAD

**Issue by stjepan** [erikras/redux-form#2740]
### Are you submitting a **bug report** or a **feature request**?

bug

### Other informations

In ConnectedFieldArray.js, v6.5.0, you hade a method shouldComponentUpdate(nextProps)...defined as following:

    shouldComponentUpdate(nextProps) {
      const nextPropsKeys = Object.keys(nextProps)
      const thisPropsKeys = Object.keys(this.props)
      return nextPropsKeys.length !== thisPropsKeys.length || nextPropsKeys.some(prop => {
        // useful to debug rerenders
        // if (!plain.deepEqual(this.props[ prop ], nextProps[ prop ])) {
        //   console.info(prop, 'changed', this.props[ prop ], '==>', nextProps[ prop ])
        // }
        return !~propsToNotUpdateFor.indexOf(prop) && !deepEqual(this.props[ prop ], nextProps[ prop ])
      })
    }

With v6.6.0, you changed it to this:

    shouldComponentUpdate(nextProps) {
      // Update if the elements of the value array was updated.
      const thisValue = this.props.value
      const nextValue = nextProps.value

      if (thisValue && nextValue) {
        if (thisValue.length !== nextValue.length || thisValue.every(val => nextValue.some(next => deepEqual(val, next)))) {
          return true
        }
      }

      const nextPropsKeys = Object.keys(nextProps)
      const thisPropsKeys = Object.keys(this.props)
      return nextPropsKeys.length !== thisPropsKeys.length || nextPropsKeys.some(prop => {
        // useful to debug rerenders
        // if (!plain.deepEqual(this.props[ prop ], nextProps[ prop ])) {
        //   console.info(prop, 'changed', this.props[ prop ], '==>', nextProps[ prop ])
        // }
        return !~propsToNotUpdateFor.indexOf(prop) && !deepEqual(this.props[ prop ], nextProps[ prop ])
      })
    }

You introduced a bug, by not running first two lines,

      const thisValue = this.props.value
      const nextValue = nextProps.value

as following:

      const thisValue = Object.keys(this.props.value)
      const nextValue = Object.keys(nextProps.value)

They are not arrays, and once hitting .every, it will produce an error as stated in the subject of the issue.

**Comment by davidfurlong** [comment]
@stjepan I think you're mistaken. `this.props.value` is an array of objects, each object corresponding to one entry in the FieldArray. You may be initializing a FieldArray attribute with a non array value, like null or '', and this would explain `every` throwing an error.

if you took the time to read `if (thisValue.length !== nextValue.length || thisValue.every(val => nextValue.some(next => deepEqual(val, next)))` I think you'd find it quite strange to call a deepEqual on an object key.

**Comment by stjepan** [comment]
Since I can't find a CDN for redux-form, I'll post an example below, for you to reproduce it, which is based on your "Field Array" example, but slightly modified.

What I'm trying to do is render 5 checkboxes, with unique names, prefixed with "members" (in this example, as defined by FormSection). For ex. if I select monday and tuesday, I want my values-object (state object in redux-form's control) to be reflected as following:

```
testingFormArray: {
    values: {
        members: {
            e9bfd92c-e257-4a2b-8d8a-542036a5be1c: true,
            8c382d3f-b3f5-4f4f-ac9f-fe28cbbeb2ce: true
        }
    }
}
```

Here is example, that worked fine until changes made in 6.6.0, as initially stated:
```
import React from 'react';
import { Field, FieldArray, FormSection, reduxForm } from 'redux-form';

const renderOptions = ({ fields, meta: { error } }) => (
    <FormSection name="members">
        {fields.map(field => (
            <div key={field.id}>
                <label>
                    {field.text}
                    <Field type="checkbox" name={field.id} component="input" />
                </label>
            </div>
        ))}
        {error && <div className="error">{error}</div>}
    </FormSection>
);

const TestingFormArray = reduxForm({ form: 'testingFormArray' })(props => {

    const { handleSubmit, pristine, reset, submitting } = props;

    const options = [
        { id: 'e9bfd92c-e257-4a2b-8d8a-542036a5be1c', text: 'monday' },
        { id: '8c382d3f-b3f5-4f4f-ac9f-fe28cbbeb2ce', text: 'tuesday' },
        { id: '4a97916d-f2f7-422f-a69e-de1ad4e66cdb', text: 'wednesday' },
        { id: '9d4ddac6-095a-40ef-8b7a-7c49519b1aaf', text: 'thursday' },
        { id: '536abc64-20d3-4fad-b22b-8dc53c0074a7', text: 'friday' },
    ];

    return (
        <form onSubmit={handleSubmit}>
            <FieldArray name="members" fields={options} component={renderOptions} />
            <div>
                <button type="submit" disabled={submitting}>Submit</button>
                <button type="button" disabled={pristine || submitting} onClick={reset}>Clear Values</button>
            </div>
        </form>
    );

});

export default TestingFormArray;
```

Note: I leaved validate-function since it is not required to run the example, but in my complete example, I'm using validate to make sure at least ONE of the checkboxes is checked. That's why I need that meta: {error} object from props in renderOptions-function.

**Comment by davidfurlong** [comment]
> members: {
>             e9bfd92c-e257-4a2b-8d8a-542036a5be1c: true,
>             8c382d3f-b3f5-4f4f-ac9f-fe28cbbeb2ce: true
>         }



> <FieldArray name="members" fields={options} component={renderOptions} />

This is a terrible idea - using `fields` - use `props` prop for this if really needed.

> testingFormArray: {
>     values: {
>         members: {
>             e9bfd92c-e257-4a2b-8d8a-542036a5be1c: true,
>             8c382d3f-b3f5-4f4f-ac9f-fe28cbbeb2ce: true
>         }
>     }
> }

I think you mean for members to be an array

**Comment by stjepan** [comment]
Ok. I updated the code, by renaming fields to options, and then map through each option...and ended up with the same result.

Well, members could be an array as well, as long as it is an array all the time. This is nothing I made up, but was a result of the code from the example above.

When I started playing with example, the Field's name's where just the indices of map-ing function, and then members became an array **(!)**. But I needed them to be a GUID (string) value, and then it resulted in members being an object.

**Comment by stjepan** [comment]
Can you try yourself and confirm the bug?

**Comment by erikras** [comment]
It looks like the problem is that you are trying to use `FieldArray` to edit an object value, when only arrays are supported, as indicated by the name of the component.

**Comment by erikras** [comment]
If this had been working previously with objects, it was only because you did not run into other areas of the code where arrays are assumed, like calls to `splice()`. Editing objects with `FieldArray` was never officially supported functionality.

**Comment by helgefredheim** [comment]
Here's an example that reproduces this bug too - is it caused by the structure of the passed-in `fields` array?

`const thisWeekRenderer = ({ input, question, children }) => {
    return (<div>
        <h3>{question}</h3>
        <div>
            <input type="radio" {...input} id={`${input}-yes`} value="true" />
            <label htmlFor={`${input}-yes`}>Yes</label>
        </div>
        <div>
            <input type="radio" {...input} id={`${input}-no`} value="false" />
            <label htmlFor={`${input}-no`}>No</label>
        </div>
    </div>)
}
 
const checkboxRenderer = ({ input, label, children }) => {
    return (<div>
        <div>
            <input type="checkbox" {...input} id={input.name} />
            <label htmlFor={input.name}>{label}</label>
        </div>
        {
            input.value ? children : null
        }
    </div>)
}
 
const renderFruits = (props) => {
    const { fields, input } = props;
    const name = "fruits";
    return (<div>
        <h3>Which fruit do you prefer?</h3>
        {
            fields.map((field, index) => {
                return (<Field key={index} name={`${name}.${field}.checked`} component={checkboxRenderer} label={labels[field]}>
                    <Field name={`${name}.${field}.thisWeek`} question={`Did you have ${field} this month?`} component={thisWeekRenderer} />
                </Field>);
            })
        }
    </div>)
}

 const fields = ["apple", "banana", "orange"]
<FieldArray component={renderFruits} fields={fields} name="fruits" />`

**Comment by erikras** [comment]
@helgefredheim This is similar to the error that @stjepan was making above. Why would you be passing a `fields` prop to `FieldArray`? That's going to conflict with [the `fields` prop that it generates for you](http://redux-form.com/6.6.2/docs/api/FieldArray.md/#fields-props). What happens if you rename that to `options` or `fruits` or `literallyAnythingElse`?

**Comment by stjepan** [comment]
@erikras the error is still there, even when choosing something else, as I stated in comment 12 days ago "Ok. I updated the code, by renaming fields to options, and then map through each option...and ended up with the same result."

**Comment by stjepan** [comment]
I don't understand what you exactly mean by this: "It looks like the problem is that you are trying to use FieldArray to edit an object value, when only arrays are supported, as indicated by the name of the component."

I'm not trying to edit. I just want to render out list of checkboxes, prefixed with same name (by use of FormSection).

The format of value is irrelevant for me, it can be object, array, or whatever, as long as it is that all the time.

I'm still stating that above code is not working, even when I use options-attribute to pass it options-array...so, no "fields" anywhere in the code.

Can't you try it out? What should I change to make sure the value becomes an array all the time...so it can get pass that .every-function?

**Comment by michaelryancaputo** [comment]
@helgefredheim @stjepan Instead of using the FieldArray component to pass an 'array' list of fields, just map over your fields. Redux-forms doesn't need these components to create inputs, just the name attributes on inputs.

**Comment by stjepan** [comment]
Well, mapping directly would work, but I need to validate that at least one item is checked (otherwise show an error), then this was the only way I found it working, by following ["Field Arrays"-example](http://redux-form.com/6.6.2/examples/fieldArrays/). If I could achieve this without using FieldArray, then I would do it that way then for sure!

**Comment by davidfurlong** [comment]
> validate that at least one item is checked

you can do this pretty straightforwardly without using FieldArrays

**Comment by stjepan** [comment]
@davidfurlong How?

**Comment by davidfurlong** [comment]
@stjepan  from the docs.... 

`validate : (values:Object, props:Object) => errors:Object [optional]

a synchronous validation function that takes the form values and props passed into your component. If validation passes, it should return {}. If validation fails, it should return the validation errors in the form { field1: <String>, field2: <String> }. Defaults to (values, props) => ({}).
`

Worst case: you realize redux-form stores things in redux and you can connect to the store and access the redux-form objects and write your own logic?

**Comment by stjepan** [comment]
I do understand the redux pattern, React (state, props, etc) and how redux-form operate, I'm not newbie.

I have read the docs...I'm already using form and validation on several other places and everything works fine. Except the above example.

I understand that I can do what you propose, but I wan't to get meta-property with error property in it...as in examples. That cannot be done for my case scenario.

I'm still stating that there is a bug within redux-form and It is not any good long term solution for me to go around that bug with custom code, and always keep an eye on that any time I wan't to upgrade.

Please, if you want to help, then read through the code, and text, and then write a comment if you think it will help, in any kind of way. :)

**Comment by stjepan** [comment]
Can anyone just RUN the example and tell me WHY it behaves that way. What is the root cause of the problem...I really want to understand. *tired*

**Comment by michaelryancaputo** [comment]
@stjepan Happy to take a look at your code, but to do that i'm going to have to set up a project. if you want someone to look at your code, i suggest putting in into a plunkr, codepen, or codesandbox.

**Comment by stjepan** [comment]
There is a pen now showing of this error at [https://codepen.io/stjepan/pen/gWpNLO](url)
Fire up console, and then select Monday, and then select Tuesday, BOOM!
Ping @michaelryancaputo @erikras @davidfurlong

**Comment by michaelryancaputo** [comment]
I was able to submit data with the format of ```{
  536abc64-20d3-4fad-b22b-8dc53c0074a7: true,
  9d4ddac6-095a-40ef-8b7a-7c49519b1aaf: true
}
``` by removing the `FormSection` wrapper

**Comment by michaelryancaputo** [comment]
Was also able to do the same by adding a `name` attribute to the `FormSection` wrapper

**Comment by stjepan** [comment]
@michaelryancaputo So did you remove it or did you add a name to it? :)

The whole point of FormSection (with it's required name-attribute) is to prefix Fields (etc.) and by the group stuff together. The question with its options are just one of many other dynamically generated questions, so I really need that functionality, so that I can know which options belongs to which questions.

So removing FormSection is not an option (and yes, I also tried prefixing Fields with the same name, and by that removing FormSection, and that yield same error).

So, in provided example, FormSection has name set to "members". So in need my values to be:
```
values: {
  /* other values from other questions */
  members: {
    536abc64-20d3-4fad-b22b-8dc53c0074a7: true,
    9d4ddac6-095a-40ef-8b7a-7c49519b1aaf: true
  }
  /* some more values from other questions */
}
```

I need someone to tell me why the code from example all way above (which is what is linked in CodePen above) is generating an error (fire up console, and you will see!; the one from the subject of the issue) so that I can understand if there is a root couse for that or if the redux form is buggy (which is what I still state!) and doesn't handle the situation at all. When that is answered, finding a solution would be much easier. :)

Thanks in advance, and really thank you for you time!

**Comment by stjepan** [comment]
After some more research (trial n error) I can conclude that error is appearing when setting name attribute of the FieldArray to the same one as of the name of react-form's-what-ever component (ex. FormSection or Field) it is rendering. (Does anyone get's that line? LOL)

So in my code example from March 29th (scroll up) I was setting FieldArray's name to "members" and in the same time FormSection's name (which is rendered by FieldArray's specified renderOptions-function) also to "members". I guess that's why it "worked" for @michaelryancaputo 

I'm still saying this is BUG or "FEATURE" because there is no protection by the code nor anything in the documentation about it. I also did mention you a valid fix, but since I don't "know" all the code, I can't tell if it works "by coincidence" or some other reason. It is up to you how you handle this issue, but I'm glad I found "solution".

This prohibits fully dynamically created forms but for the current situation, I can live with it.

**Comment by michaelryancaputo** [comment]
Thanks, explains my comment previous to yours.

Agree, there should probably be a warning or something, instead of exploding.

**Comment by ChrisWphoto** [comment]
@stjepan thanks for your hard work finding the cause of the `nextvalue.every` error. 

I was getting the same error.
I had `<FieldArray name="notUnique" />`the name property was conflicting with one of it's child fields.
Changing the name to be unique removed the error. 

Thank you!

**Comment by aris-b** [comment]
I can confirm on what @ChrisWphoto said. The issue started after I updated to 7.1.2

**Comment by stjepan** [comment]
👍🏻

**Comment by JRigotti** [comment]
Oh what a nasty bug, I am glad to have found this thread. I've switched from 6.4.3 to 7.2.3 and suddenly my radiogroup stopped working. My scenario was exactly the same my <FieldArray> name was the same as it's <Field> children.

I changed the name of the outer component, which now it looks pretty irrelevant now, and it started working! 

BUT when I submit my form I see that the we don't flag this group as `touched` which just created me another problem and now I am trying to figure out another solution for it.

I love this library, it's open source and I find it amazing, but once you go outside the examples provided it just seems that everything needs a hacky solution.

**Comment by serut** [comment]
Just spent 10 hours on a large form that had the same exception in a very special usecase.  
In fact the issue was quite simple : the `FieldArray`, with the name `a.b`, consummed the default value created by the FormComponent above (using `initialize`). And that value was an empty object, not an array.  
```
a: {
   b: {},
}
```
I just replace the `b` value into an empty array and things works fine.
