### ISSUE TITLE
Can we remove `triggerSubmit: func.isRequired` from `src/propTypes.js`?

### ISSUE THREAD

**Issue by zettadam** [erikras/redux-form#2744]
`triggerSubmit` prop is undocumented ("// didn't find in the docs what is does"), but at the same time, it is marked as required. It is generating false warnings in the developer console since developers don't use this prop (at least I know of no actual, documented usage in the docs and no one mentioned it in the Issues yet.)

We should display no warnings for code developers can't do anything about. Perhaps we should remove `.isRequired` from props that are not required for the form to function properly.

My environment:
Redux-Form 6.5.0, 6.6.0, Chrome (OS X), node 7.7.4

**Comment by gustavohenke** [comment]
Yes. See #2738

**Comment by erikras** [comment]
Fix published in [`v6.6.1`](https://github.com/erikras/redux-form/releases/tag/v6.6.1).
