### ISSUE TITLE
`Getters` in redux-form props

### ISSUE THREAD

**Issue by theKashey** [erikras/redux-form#2746]
Redux form provide  wide list of props - http://redux-form.com/6.6.0/docs/api/Props.md/
One can find a lot of write commands, and a few constants one can read(ie `form`).

But there is not `build in` command to read value from or, for example, get current variable prefix from FormSection (to build name to read).
First case can be solved via Selectors, but it will not be easy, and clear - you should combine state and form name. And you dont know form name.
Second can can not be solved.

What about embedding selectors inside first-level props?

**Comment by erikras** [comment]
Can you give an example of what that syntax might look like?

**Comment by theKashey** [comment]
so:
 we have a `form`(string) prop. Lets have a `section`(string) as current section and `sections`(Array) as list of nested sections. 

 we have an `array` prop for actions. Lets have a `field` prop for getters.
 - field.get(fieldName) - returns current value
 - field.meta(fieldName) - returns meta information. Same as Field provide to a component.

In both cases fieldName is in dot notation, as their target names. And you have to know full path, ie in which sections they lay, to build it.

Also one can add field.list as list of all fields, but one can also divide them into different sections.

**Comment by theKashey** [comment]
Function like field.meta can solve https://github.com/erikras/redux-form/issues/2745

**Comment by dcporter44** [comment]
+1 

Something similar to `this.props.change(field, value)`. So something like `this.props.get(field)` to return the current value of that field.

**Comment by tstirrat15** [comment]
How does this differ from using `formValueSelector` to get the value of a field and then pass it in as a prop?

**Comment by theKashey** [comment]
@tstirrat15 for formValueSelector you need: state and form name. 
Ok - redux_form will provide a `form` prop, but next you have to pass state into component. So implementation details, that must not exists inside component.
Ok - you still can just wrap `formValueSelector` by some function, pass it inside mapStateToProps and use it. 
But I might do it? This is work for a source of problem - redux form.
PS: And you still cant get flags.

**Comment by prescottprue** [comment]
+1 for something like `this.props.get(fieldName)` (probably preferred) or `this.props.formValues.fieldName`.

**Comment by erikras** [comment]
The main reason why you need a selector rather than a `this.props.get(fieldName)` is that a selector will rerender your component, and the other won't.

One of the main design goals of `v6` was to allow individual inputs to be rerendered without necessarily having to rerender the entire form.

For a contrived example, let's say you want to print out "full name" in your form, so you do:
```js
<div>{`${this.props.get('firstName')} ${this.props.get('lastName')}`}</div>
```
As you type into the `firstName` field, you would expect the Full Name `<div>` to change, _**but it won't**_, because the form's `render()` method is not being called on every keypress.

Make sense?

**Comment by theKashey** [comment]
...and you still cant get field`s flags.

**Comment by tstirrat15** [comment]
@theKashey are you talking about a field's other attributes, such as syncError or dirty? There are other ways of obtaining that information, such as through [selectors](http://redux-form.com/6.6.2/docs/api/Selectors.md/).

**Comment by theKashey** [comment]
The only thing I want - get same meta information, as Field providing to a component inside it.
Even if you will try to get some flags via selectors - I cant get them all.
