### ISSUE TITLE
Field Level validation prop "validate" only accepts prop of type function

### ISSUE THREAD

**Issue by HarrisGri** [erikras/redux-form#2749]
Hi,
with the current version i'm getting a prop validation warning that "validate" only accepts prop of type *Function*, which is wrong when i look at you documentation and your implementation!

**Comment by davidfurlong** [comment]
this is a duplicate, and a fix is already committed to the codebase. Wait for the next release

**Comment by HarrisGri** [comment]
Sorry didn't saw that it was already posted! THX a lot!

**Comment by davidfurlong** [comment]
@HarrisGri new release fixes this
