### ISSUE TITLE
Using non-input Field Component

### ISSUE THREAD

**Issue by eduardomoroni** [erikras/redux-form#2751]
I have a Field that renders a non-input component. I'm using images instead of checkbox like picture below:
![image](https://cloud.githubusercontent.com/assets/823150/24407083/3ea5689e-13a0-11e7-83fd-bc6e52eb703a.png)
Once I click on the image I want to update the form state to reflect images on the screen.

My current implementations is:
On form component
```
<Field name='cardColors' component={ManaIconsBar} selectedColors={cardColor} />
// selectedColors is receiving an array of strings like ['black','blue'] which means that black and blue color are selected
```

On ManaIconsBarsComponent:

```
// IMPORTS AND mapDispatchToProps omitted
class ManaIconsBar extends Component {
  render () {
    const { selectedColors, updateColors } = this.props

    function toggleColor (color) {
      let updatedSelect = []

      if (selectedColors.includes(color)) {
        updatedSelect = _.without(selectedColors, color)
      } else {
        updatedSelect = _.concat(selectedColors, color)
      }

      updateColors(updatedSelect) // this is dispatch(change('CardSearchForm', 'cardColor', colors))
                                                       // import { change } from 'redux-form'
    }

    const renderManaSymbol = (color) => {
      const isSelected = selectedColors.includes(color)

      return (
        <TouchableOpacity key={color} onPressOut={() => toggleColor(color)} >
          <ManaSymbol color={color} style={[Styles.manaIcon, {opacity: isSelected ? 1 : 0.25}]} />
        </TouchableOpacity>
      )
    }

    return (
      <View style={Styles.container}>
        <Text style={Styles.text}>
          {I18n.t('color')}
        </Text>
        { ValidColors.map(renderManaSymbol) }
      </View>
    )
  }
}
```

I couldn't use `this.props.input.onChange`, since I don't have an event to send.
I've tried something like `this.props.input.onChange(undefined,newValue)` but This doesn't dispatch any action ([DOC](http://redux-form.com/6.6.0/docs/api/Field.md/)). The fashion I've implemented is working fine, but I want to have a dumb component being rendered by Field.

Is there a way to use `onChange` and faking an event?
Does anyone have a better solution?

**Comment by davidfurlong** [comment]
Hey @eduardomoroni 
http://redux-form.com/6.6.0/docs/api/Field.md/#props

`this.props.input.onChange` 

input.onChange(eventOrValue) : Function

A function to call when the form field is changed. It expects to either receive the React SyntheticEvent or the new value of the field.

=>>> Just do `this.props.input.onChange(newValue`

**Comment by eduardomoroni** [comment]
@davidfurlong Thanks so much, I'm using `input.onChange` my error was doing this `<Field name='cardColors' component={ManaIconsBar} selectedColors={cardColor} />` instead of getting selected colors from `input.value`. Now once I change values with `input.onChange` I can easily get changed values from `input.values` and now I can use a dumb component.
