### ISSUE TITLE
react-widgets example page doesn't load

### ISSUE THREAD

**Issue by smashercosmo** [erikras/redux-form#2753]
### Are you submitting a **bug report** or a **feature request**?
bug

### What is the current behavior?
http://redux-form.com/6.6.0/examples/react-widgets/ page doesn't load

### What is the expected behavior?
Page should load

**Comment by erikras** [comment]
Thanks. This will be fixed in the next version: v6.6.1

**Comment by erikras** [comment]
[Fixed](http://redux-form.com/6.6.1/examples/react-widgets/).
