### ISSUE TITLE
Warnings on multiple Field validations

### ISSUE THREAD

**Issue by ayaniv** [erikras/redux-form#2757]
In the docs you said that for multiple field validations, i.e: required & password, one should do: `<Field validate={[required, password]} />`.
that works perfectly. As described here: [documentation](http://redux-form.com/6.6.1/examples/fieldLevelValidation/)

but, my chrome console prints annoying warnings saying: 
```
Invalid prop `validate` of type `array` supplied to `Field`, expected `function`.
```

Looks like a bug to me. or am I missing something?

**Comment by MichaelDeBoey** [comment]
This is fixed in [`v6.6.1`](https://github.com/erikras/redux-form/releases/tag/v6.6.1) ([`08a377e`](https://github.com/erikras/redux-form/commit/08a377ead23ab34c3116c8e02782b1c292b5ebec)) :-)
