### ISSUE TITLE
Submited flag for the form property

### ISSUE THREAD

**Issue by kristian-puccio** [erikras/redux-form#276]
What do you think about having a hasSubmitted flag added to the form prop?

At the moment on submission all the fields are being 'touched' which allows you to know whether to show validation for that field. A more fine grained approach would be to have the error label check for touched on the field or submitted on the form. That way it's up to the user if they want to use either or both or even display different message for each state.

If your into the idea I'll look into getting a pull request for you.

**Comment by erikras** [comment]
Okay, I can see the value in this. It should be a boolean called `submitFailed`, which will default to `false`, be set to `false` on a successful submit, and set to `true` on a failed submit, no matter the cause of the failure. Does that sound, okay?

Don't bother with the PR unless you really want to get grease on your hands. It'll be pretty trivial for me to add.

**Comment by erikras** [comment]
Available in `v3.0.8`.

**Comment by kristian-puccio** [comment]
Awesome nice one! Thanks heaps

**Comment by oyeanuj** [comment]
@kristian-puccio @erikras How do you determine if the `submitFailed` field above is false because the submission failed or because submission didn't happen? Is the idea to use `touched` for each or for a specific field in conjunction with `submitFailed`?
