### ISSUE TITLE
Initialize complex objects in form

### ISSUE THREAD

**Issue by Sarvok** [erikras/redux-form#2767]
### What is the current behavior?

I am currently creating an edit page for an entity and while the creation works with complex objects I found myself unable to initialize the edition form with values.

Actually the values that do not appear are the one inside complex objects:

I also did not find a way to make the form value selector work with said objects.

```
id: 13,
title: 'test2',
quote_id: 13,
quote: {
  id: 13,
  content: 'dfgbvn',
  author_id: 12,
  author: {
    id: 12,
    first_name: 'testFN',
    last_name: 'testLN'
  }
}
```

Title appears in its field, however the quote elements do not.

Here is the render method of the form: https://plnkr.co/edit/YE8FSrvgcZeZxoyLyaaE

### What's your environment?

redux@3.6.0
redux-form@6.6.0

**Comment by gustavohenke** [comment]
This example is missing some parts... won't be of any help.
Do you mind start over from here? https://jsfiddle.net/gustavohenke/48814zsq/

Basically, I need to see how you're passing `initialValues`.

**Comment by kailashvele** [comment]
Any updates on this?

**Comment by gustavohenke** [comment]
@kailashvele, no, not really.
I completely forgot about this issue, and it would be hard to help anyway.

If you or @Sarvok can come up with a minimal, reproducible, live example of a bug or a feature that Redux Form is lacking, let us know by creating another issue.
Otherwise this seems a simple usage support question which is better suited to StackOverflow land.

Thanks for using Redux Form!

**Comment by kailashvele** [comment]
@gustavohenke hey sorry to bother you, I was able to populate the data using dot.

But I had one problem in populating selected radio option.

`{
    id: 0
}`
 if my object is like this having id as number the radio is not shown selected
and if it is string like this

`{
    id: '0'
}`

then the radio is shown selected

**Comment by danielrob** [comment]
This suggests your radio button has the value `'0'`. You may need to use `normalize={v => parsInt(v)}` on your Field for example.
