### ISSUE TITLE
Problem with UC Browser (Mobile)

### ISSUE THREAD

**Issue by povtasci** [erikras/redux-form#2770]
Guys I'm working on the Indian project and just knew that there are a lots of users with UC Mobile Browser (www.ucweb.com). So now I'm trying to type anything to input it is not updating input and it stays empty. do you have any suggestion how I can fix that ?

In the component `this.props.myForm.values.name` is showing only on char and as the input is continuing be empty after another type the value is being equal to the last typed char.

**Comment by jpdesigndev** [comment]
I'm seeing the same thing in Chrome, but I'm brand new to this project.

**Comment by jpdesigndev** [comment]
I'm getting this same issue in all major browsers, but I'm just trying redux-form for the first time.

**Comment by povtasci** [comment]
I found the solution for my issue here.
https://github.com/davezuko/react-redux-starter-kit/issues/785

@jpdesigndev, I think your issue is the just wrong using of the component. You can put the code here or create a new issue, I will try to have a look at.

**Comment by jpdesigndev** [comment]
Thanks @povtasci. I figured it was something silly... I was using `forms` as the key instead of `form`. Somehow I missed this in the docs.
