### ISSUE TITLE
Field Component not re rendering after calling input.onChange

### ISSUE THREAD

**Issue by nivek91** [erikras/redux-form#2773]
I have a Component, within a Field, I'm calling onChange on the Component, and it's not re rendering immediately, it may render afterwards (as you can see on the example).

The action @@redux-form/CHANGE is being dispatched, the value is being updated in the store (check the console log). And the next state (see screnshot). But the component is not re rendering on every CHANGE.

![not re rerender](https://cloud.githubusercontent.com/assets/4519660/24660721/a6afe730-1926-11e7-86a5-c53d8a325b07.gif)

![image](https://cloud.githubusercontent.com/assets/4519660/24660740/b4e6fe60-1926-11e7-946a-1ea772b92b63.png)

Here is the relevant part of the code:
![image](https://cloud.githubusercontent.com/assets/4519660/24660773/cd416504-1926-11e7-90df-acfb07308dcc.png)

![image](https://cloud.githubusercontent.com/assets/4519660/24660811/f30f436e-1926-11e7-83f4-eaf3e09036a8.png)

If needed I can update the whole code. Am I missing something? I read the docs, googled, but I can't make it work.

Thanks

**Comment by tstirrat15** [comment]
A couple of things:

Are you concerned that this is a bug, or are you wondering why your code in particular isn't working? If it's the former, you want to isolate the bug as much as possible - figure out exactly which portion of your code isn't working as expected, and describe why it's unexpected behavior. If it's the latter, posting to [StackOverflow](https://stackoverflow.com/questions/tagged/redux-form) is more appropriate than opening an issue.

Second thing is that a screenshot of your code really isn't useful for a person who's trying to debug it. [Post a gist](https://gist.github.com/) instead.

**Comment by nivek91** [comment]
@tstirrat15 I have no clue if its a bug or my code doesn't work.  I know that a gist might be more useful, I was posted like this just in case I was missing something very obvious.

**Comment by BTMPL** [comment]
I'm not going to read much into the code, but I can straight away say you're Doing It Wrong here:

```
const handleClick = (id, e) {	
	let inputValues = props.input.value | [];
	if(inputValues.indexOf(id) === -1) {
		inputValues.push(id);
	}
	else{
//...
```

for at least 2 reasons:

1. you are mutating the props! that's a biiiiiiiig no-no in React world!
2. you added a handler to a Stateles Function Component - this is probably not going to work out very well for you

**Comment by nivek91** [comment]
Hi @BTMPL thanks for your reply. I'm not mutating the props.. I'm calling the onChange callback, that is going to mutate it:  input.onChange(newArray);

**Comment by BTMPL** [comment]
@nivek91 on line #32 you are attaching the `handleClick` to the div. This will fire the `handleClick` from line 11, and get the `props` from the closure. It will then get the reference to `props.input.value` and mutate it (.push())

I'm talking about mutation of data, not calling a callback on the `props.input`

**Comment by nivek91** [comment]
Changed to this:
```
    let inputValues = props.input.value || [];
    let newArray = [];
    for (let i = 0; i < inputValues.length; i++) {
      newArray[i] = inputValues[i];
    }

    if (newArray.indexOf(id) === -1) {
      newArray.push(id);
    } else {
      newArray = newArray.filter(i => i !== id);
    }

    input.onChange(newArray);
```

 and It started working, still dont understand why, whats the matter if I mutate the prop, even though I call the callback (I'm not expecting the re render from mutating the prop)

**Comment by BTMPL** [comment]
If you are mutating a prop, React does not know that it has changed and will decide not to re-render a component. This (not mutating props / state) is one of the basics when working with Components.

**Comment by nivek91** [comment]
Thanks a lot @BTMPL
