### ISSUE TITLE
Retain form information after component unmounts

### ISSUE THREAD

**Issue by stphnlngdncoding** [erikras/redux-form#2777]
I have a redux-form in a modal.  It's great! It clears the data when the modal closes as intended.  Is there any built-in functionality to retain the information to repopulate the form in case the user transitions back to it? If not, what would be the best way of retaining the form information for repopulation?

**Comment by tstirrat15** [comment]
See the [destroyOnUnmount](http://redux-form.com/6.6.1/docs/api/ReduxForm.md/) flag. That together with `keepDirtyOnReinitialize` should let you get the behavior you're interested in.

**Comment by danielrob** [comment]
Thanks @tstirrat15, looks like this answered the question.
