### ISSUE TITLE
normalize should have access to props

### ISSUE THREAD

**Issue by AndyOGo** [erikras/redux-form#2778]
### Are you submitting a **bug report** or a **feature request**?

 **feature request**

### What is the current behavior?

`normalizer` does not receive all `props`

### What is the expected behavior?
`normalizer` receives all `props` so that stuff like `min`, `max` can be dealt with dynamically.

### What's your environment?

redux-forms version `6.5.0^`

**Comment by tstirrat15** [comment]
What's the use case?

I usually end up creating a closure for `normalize` if it depends somehow on `props` and it works pretty well.

**Comment by AndyOGo** [comment]
A generic normalize function which should be scope/closure agnostic.

**Comment by akomm** [comment]
What props do you talk about, the field or the input?

**Comment by gustavohenke** [comment]
This feature saw little or no interest from other users, so I'm closing it for now.
Feel free to continue the discussion.

**Comment by AndyOGo** [comment]
What a bummer, I would really like it to be there.

**Comment by gustavohenke** [comment]
Sorry about that @AndyOGo.
This project is quite opinionated, so attending all requests is quite difficult for a single-developer project. Most of the development time is being given to the sister library [Final Form](https://github.com/final-form/final-form) nowadays.

**Comment by AndyOGo** [comment]
Thank you for your response.
I see. Final Form sound interesting.
