### ISSUE TITLE
isPristine fails if object is a Date

### ISSUE THREAD

**Issue by box-turtle** [erikras/redux-form#278]
I believe that the isPristine() check fails if the passed initial and new values are both Dates. If both values are Dates it always returns true.

Object.keys(date) returns an empty array, and so the check to iterate the keys and compare them always returns true.

Maybe add another check for `initial instanceof Date`?

**Comment by erikras** [comment]
Good bug report. Thanks. Will address asap.

**Comment by erikras** [comment]
Fixed in [v3.0.8](https://github.com/erikras/redux-form/releases/tag/v3.0.8). Thanks again.

**Comment by box-turtle** [comment]
Thanks Erik!
