### ISSUE TITLE
wizard screen submission failing with no errors

### ISSUE THREAD

**Issue by mpham-r7** [erikras/redux-form#2785]
i have a redux-form@6.6.1 that implements the wizard pattern and i'm having an issue... when submitting a screen (no syncErrors present), submission fails... i think i've tracked down the issue to the submit function in reduxForm.js

it seems the problem is that the value for (the closed over variable) validExceptSubmit at https://github.com/erikras/redux-form/blob/master/src/reduxForm.js#L445 could be different from the ~equivalent value in this.props.validExceptSubmit https://github.com/erikras/redux-form/blob/master/src/reduxForm.js#L442 ... i find that this is the case /w my code

i haven't managed to reproduce the behavior in a (simplified) fiddle as i'm not exactly sure what the form state causing this is, but in terms of the code itself, the callback on line 445 should reference the current props, rather than the closed over variable (which over time could diverge from the current props) right?

**Comment by mpham-r7** [comment]
i tracked it down to here, looks like the intent was to refactor the code...

https://github.com/erikras/redux-form/commit/81ce486788bba5485b1d580c1c0fad359adc41cd#diff-d749bb1257f721af37259e0346e623beR403

**Comment by mpham-r7** [comment]
made a pr for this: #2786

**Comment by erikras** [comment]
Great 🕵️ work on this, @mpham-r7!

**Comment by erikras** [comment]
Fix published in [`v6.6.3`](https://github.com/erikras/redux-form/releases/tag/v6.6.3).
