### ISSUE TITLE
Passing submit callback directly in reduxForm

### ISSUE THREAD

**Issue by jaroslawr** [erikras/redux-form#279]
Is there any particular reason the callback for onSubmit has to be passed in as a prop to the decorated form component, when e.g. the validation callback is passed in as an argument to reduxForm?  I would like to put the whole form logic in a single separate file, and this makes it cumbersome, why not have this:

```javascript
// ReduxSignUpForm.jsx
export const ReduxSignUpForm = reduxForm({
  form: 'signUp',
  fields: ['gender', 'first_name', 'last_name'],
  validate: (data) => {
    const errors = {};
    return errors;
  },
  submit: (data, dispatch) => {
    console.log("Submit!");
  }
})(SignUpForm);

// SignUpRoute.jsx
export const SignUpRoute = () => {
  return <ReduxSignUpForm />;
}
```

Currently I would have to do:

```javascript
// ReduxSignUpForm.jsx
export const ReduxSignUpForm = reduxForm({
  form: 'signUp',
  fields: ['gender', 'first_name', 'last_name'],
  validate: (data) => {
    const errors = {};
    return errors;
  }
})(SignUpForm);

// SignUpRoute.jsx
const submit = (data, dispatch) => {
  console.log("Submit!");
}

export const SignUpRoute = () => {
  return <ReduxSignUpForm onSubmit={submit} />;
}
```

**Comment by erikras** [comment]
I think you missed this line from [the docs](http://erikras.github.io/redux-form/#/api/reduxForm).

> **IMPORTANT: All of these configuration options may be passed into reduxForm() at "design time" or passed in as props to your component at runtime.**

Both `validate` and `onSubmit` may be passed as props to the decorated component, or as config properties to the `reduxForm()` decorator.

**Comment by jaroslawr** [comment]
@erikas Cool, thank you!
