### ISSUE TITLE
[6.6.1] reducer function registers form when non-redux-form action type dispatched to store

### ISSUE THREAD

**Issue by ordoghl** [erikras/redux-form#2790]
### Are you submitting a **bug report** or a **feature request**?
bug report

### What is the current behavior?
We have our own specialized react form implementation but we also use redux-form in our app. Our form implementation uses `action.meta.form` (just like redux-form) to send our form's name to our reducer. When we dispatch our `ecrForm\INIT_FORM` action type to the redux store with `action.meta.form = 'generatedForm'` redux-form's reducer also "registers" `generatedForm` as its form in its 'form' state slice.

We think the problem is in `src/reducer.js` file's `byForm` method. It retrieves the form name from `action.meta.form` and in the last line it  sets `generatedForm` to an empty Map in redux-form's state because `result` is empty (because we dispatched non-redux-form action) and `formState` is `undefined`.
```
  const byForm = (reducer) =>
    (state = empty, action = {}) => {
      const form = action && action.meta && action.meta.form
      // ...
      const result = reducer(formState, action)
      return result === formState ? state : setIn(state, form, result)
    }
```

### What is the expected behavior?
Do not change state when non-redux-form action type dispatched to store.

### What's your environment?
Redux Form 6.6.1, Immutable store (3.8.1), React 15.4.2

**Comment by erikras** [comment]
How dare you keep form information in redux without `redux-form`!! 😀

Very interesting bug. Perhaps if the `redux-form` reducer checked the prefix of `action.type` to determine if it was an action for this library.

I will investigate. 👍
