### ISSUE TITLE
Receiving custom props with payload.

### ISSUE THREAD

**Issue by mdomasevicius** [erikras/redux-form#2794]
Instead of going through form reducers and adding/removing validations that could be passed as props e.g. 

`<Field ... required/>` or passing a match pattern...

It would be easier to have a set of predefined validators that would execute if a properties exists since some of them do the same thing. This could enhance [recommended approach](http://redux-form.com/6.0.0-alpha.4/examples/syncValidation/) and DRY up code.

**Comment by tstirrat15** [comment]
Are you on the most recent version of redux-form? The [current Field API](http://redux-form.com/6.6.1/docs/api/Field.md/) lets you pass a `validate` function as a prop which can do synchronous validation of that field. If you want to reuse validators across fields or compose them, it isn't too hard to do that with some mapping and reducing.
