### ISSUE TITLE
Remote submission (via dispatch(submit)) when using the Form component and onSubmit={handleSubmit(fn)}, allows submission with syncErrors present

### ISSUE THREAD

**Issue by mpham-r7** [erikras/redux-form#2799]
### Are you submitting a **bug report** or a **feature request**?
**bug report**

### What is the current behavior?
When using the ```Form``` component in the following manner: 
```<Form onSubmit={handleSubmit(this.localSubmitProcessor}>...</Form```
along with a form submission initiated by a parent component (i.e. via ```dispatch(submit(...))```),
submission handling for the form does not properly reflect the current success/failure state of the form (e.g. ```handleSubmit``` is called with a non accurate ```valid``` parameter)

Here is a fiddle implementing a slightly modified version of the wizard pattern (with the above described changes): http://jsfiddle.net/uujx0baw/ The issue is exemplified when moving out of the second wizard screen (in which sex is the input field)... the user can move to the third screen even without making a required input choice... after moving back from the third screen and making an input choice, the user cannot continue to the third screen even when a choice was made.

### What is the expected behavior?
After moving through the first screen, submitting next on the second screen without picking a sex should prevent the user from continuing to the next screen.

### What's your environment?

https://npmcdn.com/react@15.4.2/dist/react-with-addons.js
https://cdnjs.cloudflare.com/ajax/libs/redux/3.6.0/redux.min.js
https://cdnjs.cloudflare.com/ajax/libs/react-redux/4.4.6/react-redux.min.js
https://npmcdn.com/react-dom@15.4.2/dist/react-dom.js
https://cdnjs.cloudflare.com/ajax/libs/redux-form/6.6.2/redux-form.js
chrome: Version 56.0.2924.87 (64-bit)
macosx: sierra

i previously created a pr for this #2786 before knowing what the root cause was.

**Comment by erikras** [comment]
Well reported. 👍 JsFiddle is a godsend.

**Comment by erikras** [comment]
Merged fix #2786.

**Comment by erikras** [comment]
Fix published in [`v6.6.3`](https://github.com/erikras/redux-form/releases/tag/v6.6.3).
