### ISSUE TITLE
`timestamp` cause `checksum invalid Error`

### ISSUE THREAD

**Issue by xcatliu** [erikras/redux-form#280]
My project was using server rendering, and when I use `reduxForm()` with `initialValues` option, it threw an Error:

```
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) estamp.1">1447671517920</span></li><li s
 (server) estamp.1">1447671517228</span></li><li s
```

Which was caused by the different [`timestamp`](https://github.com/erikras/redux-form/blob/a242bff45e4d0b7d1ecb9f5cf9cb05f4c81cb19c/src/actions.js#L20) value that created by `Date.now()`.

Is there any way to prevent this error?

**Comment by xcatliu** [comment]
Oh, I forgot something.

This error only appeared when `redux-devtools` is opening. So `timestamp` is rendering in the devtools container. As a result, my project will not throw this error in the production environment.

I think this is not a problem at all. It's fine to close this issue now.

BTW, I read redux-form source, but cannot figure out what is the meaning of `timestamp` argument, can anybody tell me?

**Comment by erikras** [comment]
The `timestamp` argument is vestigial from a previous attempt at something. I'll remove it. Thanks.
