### ISSUE TITLE
onChange(values){console.log(values)} return: Proxy?

### ISSUE THREAD

**Issue by CyanChoi** [erikras/redux-form#2801]
hello there , my code is like this:
SearchForm = reduxForm({
  form:'searchForm',
  onChange(values){
    console.log('changing====>', values)
  }
})(SearchForm);

and the values is like this:
![image](https://cloud.githubusercontent.com/assets/3477631/24849453/7b2af8fc-1dfe-11e7-88be-370daa65fe4d.png)

before I change my root state, it is ok for me get the values.
that is like this:  { form:searchForm},
but today I change the root state, {data:{form:searchForm}},
I am not sure if it is the cause of the change values bug that return the Proxy...

**Comment by tstirrat15** [comment]
The `Proxy` that you're seeing is an event type. You're seeing the entire event object, not just the values.

Changing the shape of your store probably broke things, as `redux-form` expects to find the form state at the root of your store under a `form` key. It's possible to change that, but may I ask why you would want to do that?
