### ISSUE TITLE
React.propTypes deprecation warning still exists for es modules

### ISSUE THREAD

**Issue by rockchalkwushock** [erikras/redux-form#2802]
### Are you submitting a **bug report** or a **feature request**?
Bug

### What is the current behavior?
Receiving the warning message below for `React.propTypes` deprecation:
![screen shot 2017-04-10 at 8 46 17 am](https://cloud.githubusercontent.com/assets/19720404/24864569/32b08bf2-1dca-11e7-955c-e5249bb00c27.png)

### What is the expected behavior?
No error message, does not break functionality of package though.

### What's your environment?

```json
redux-form: ^6.6.2
```
```plaintext
macOS Sierra 10.12.4
Chrome: Version 57.0.2987.133
```
### Other information
I understand that `React.propTypes` needs to be swapped in lieu of the now external `prop-types` package, _which I see has been done in `./src`_; however, when looking at the error message and following that stack trace this is in build for `./es`. I'm personally not sure on where to begin with trying to fix this. I know that it probably deals with `webpack`. I just don't know why the `./es` directory would still be using `React.propTypes` when the build should be coming from `./src` which has already been amended for this deprecation.

**Comment by rockchalkwushock** [comment]
The only thing that comes to mind for me is maybe the `./es` was not rebuilt and shipped after the update?

**Comment by erikras** [comment]
#2800 has not yet been published.

Surely you are seeing this in almost every React lib you use, right?

**Comment by rockchalkwushock** [comment]
@erikras haven't had any issues with `react-redux` that's really the only other package with an `es` module I'm using that was using `propTypes` and had to make use of the update due to the deprecation. Thanks for the status update on it just not being published yet. Closing.

**Comment by andrevenancio** [comment]
any feedback on when it will be shipped? npmjs.org already has the 6.2.2 version, which I've been through github src folder and noticed you changed it. However I still have this errors on my local build.

I've removed node_modules, updated my package to include the correct version, did the git install and still get this error on your library.
