### ISSUE TITLE
Dot-separated field names are converted to object forcedly 

### ISSUE THREAD

**Issue by Eugenie21** [erikras/redux-form#2806]
I am trying to send request with field name like 'campaign.type'. The name is provided by API and I can't change it. Redux-form automatically converts it to nested object so I can't send it. Is there any possibility to turn off this feature?

**Comment by tstirrat15** [comment]
Not that I know of, but the submit function provides the values as an object with the name as the key, so it should be possible to name it something else at the field level and then change the name in your submit function.

**Comment by gustavohenke** [comment]
@tstirrat15 is correct.
