### ISSUE TITLE
Json Schema in Redux-form?

### ISSUE THREAD

**Issue by mglazer-cengage** [erikras/redux-form#281]
Hi, 

I'm getting familiar with redux-form and wondering if there are any examples with a Json-schema and or using a multi-page form (wizard) and lastly a page transition on successful async submit to say another route?

Thank you

**Comment by erikras** [comment]
No such examples so far, but you might want to look into https://github.com/erikras/redux-form/issues/179#issuecomment-151582022 about splitting your form up into pages.

In the service of being as unopinionated as possible, nothing has been done with schemas or with any other third party validation libraries.

**Comment by erikras** [comment]
See also: #260

**Comment by mglazer-cengage** [comment]
Thanks!

**Comment by mglazer-cengage** [comment]
How do I handle updating the form state for the current "step" i.e. 1, 2 ...

Is that a props.initialize, is it a redux action?

**Comment by erikras** [comment]
Redux action to your own reducer.

**Comment by willmcclellan** [comment]
@mglazer-cengage might not be what you want, but I wrote a schema helper module for redux-form https://github.com/inlight-media/redux-form-schema

**Comment by erikras** [comment]
Nice work, @mglazer-cengage!

**Comment by erikras** [comment]
FYI, @willmcclellan, I've listed your thing [here](https://github.com/erikras/redux-form/blob/master/tools.md). Help spread the word [by retweeting this](https://twitter.com/reduxform/status/666543527422271488).

**Comment by erikras** [comment]
Also, @lemonCMS, see previous comment.

**Comment by willmcclellan** [comment]
Thanks @erikras :+1:

**Comment by lemonCMS** [comment]
thx @erikras

**Comment by hooloovooo** [comment]
This would actually be a really good idea. @erikras json schema is not a validation library, it's a specification for how a json object should look and basically just contains a description for how you want your json to look.

http://json-schema.org/

**Comment by eduardoinnorway** [comment]
Confirmed working great with [AVJ ](https://github.com/epoberezkin/ajv) validation and [JSON schema](http://json-schema.org), you just need to handle the data to fit between redux-form and (JSON schema + AVJ). If I get some time soon I will put out an example.

**Comment by noahjohn9259** [comment]
@eduardoinnorway , do you have any example how you did manage to integrate ajv ..

**Comment by mthrm** [comment]
This is how we're validating redux-form schemas using ajv:

```js
import Ajv from 'ajv/dist/ajv.min';
import AddIf from 'ajv-keywords/keywords/if';

const makeValidator = (schema) => {
  const ajv = new Ajv({ allErrors: true, coerceTypes: true });

  // Add If-then-else from ajv-keywords package
  AddIf(ajv);

  // Add custom keyword
  ajv.addKeyword('customKeyword', {
    validate: (aSchema, value) => customValidationFunction(value),
    errors: false,
  });

  const validator = ajv.compile(schema);

  // Return a redux-form compatible validation function
  return (values) => {
    const errors = {};

    if (values.toJS) {
      validator(values.toJS());
      if (validator.errors) {
        validator.errors.forEach((obj) => {
          // Massage ajv errors to the { 'fieldName': 'errorMessage' } format expected by redux-form
          if (obj.keyword === 'required') {
            errors[obj.params.missingProperty] = obj.message;
          } else {
            errors[obj.dataPath.replace('.', '')] = obj.message;
          }
        });
      }
    }

    return errors;
  };
}
```

Usage with reduxForm:

```js
import { compose } from 'redux';
import { connect } from 'react-redux';
import { reduxForm } from 'redux-form/immutable';

const Form = ({ ...props }) => {
  // Awesome form goes here..
}

export default compose(
  connect(mapStateToProps),
  reduxForm({
    form: 'formName',
    validate: makeValidator(schema),
  }),
)(Form);
```

**Comment by gpietro** [comment]
@mtramm this is good for validation. Did you think of using the json schema also for creating the form?

**Comment by mtramm** [comment]
We have a function for extracting the relevant properties from the schema into a `fields` object, so we get code somewhat like this, where the Form component is only responsible for some wiring and the layout of the form:

```js
const Form = ({ ...props }) => {
const fields = getFieldsFromSchema(schema);

  return (
    <Field name='name' {...fields.name} />
  );
}
```
