### ISSUE TITLE
PropTypes is deprecated in React 15.5

### ISSUE THREAD

**Issue by ghidosoft** [erikras/redux-form#2810]
I'm using redux-form 6.6.2 with react 15.5.4 and I'm getting warnings about deprecation of `React.PropTypes` (https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.proptypes):
> Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

I'm getting the warning in https://github.com/erikras/redux-form/blob/master/src/Form.js#L22 but I'm not sure if it is used elsewhere.

**Comment by erikras** [comment]
This was fixed by #2800. Will publish soon.

**Comment by ghidosoft** [comment]
Sorry, I searched only in open tickets and didn't find it, thank you.

**Comment by erikras** [comment]
Fix published in [`v6.6.3`](https://github.com/erikras/redux-form/releases/tag/v6.6.3).

**Comment by missioeric** [comment]
See https://github.com/erikras/redux-form/issues/3419

Fixed in 7.1.0
