### ISSUE TITLE
throw  new SubmissionError Uncaught in Promise using axios, redux-thunk, and redux-form

### ISSUE THREAD

**Issue by cjdeleon62** [erikras/redux-form#2813]
Hi, I know there a lot of issues about this posted already but I was hoping someone would be able to point me in the right direction. I am prertty new to all of this so any help would be appreciated. I am getting an Uncaught in promise error when axios hits the catch block.

I am linking the function to the handleSubmit prop on redux-form

```js
<Signin onSubmit={this.submitSignin} closeModal={this.close}/>
```

I placed the action creator inside this function to be executed

```js
submitSignin({username, password}) {
    this.props.signinUser({username, password});
    console.log("inside signin");
  }
```

this is the action creator

```js
export function signinUser({ username, password }, dispatch, props) {
  return function(dispatch) {
    // Submit username/password to the server
    axios.post(`${ROOT_URL}/api/signin`, { username, password })
      .then(response => {
        // If request is good ...
        // - Update state to indicate user is authenticated
        dispatch({type: AUTH_USER, payload: username});

        // - Save the JWT Token
        sessionStorage.setItem('token', response.data.token);
        sessionStorage.setItem('username', username);

        // - redirect to the route '/feature'
        browserHistory.push('/');

      })
      .catch( (err) => {
        // If request is bad ...
        // - Show an error to the user
        // dispatch(authError('Bad login info.'));
        throw new SubmissionError({error: 'Bad Login'});
      });
  }
}
```

**Comment by gustavohenke** [comment]
I'm going with my usual suspect, and say that your thunk should be returning the promise.
Because it's not, probably no one is consuming your error, therefore you see it in the browser console.

[Example in Redux docs](http://redux.js.org/docs/advanced/AsyncActions.html#async-action-creators)
