### ISSUE TITLE
examples do not work for me

### ISSUE THREAD

**Issue by avloss** [erikras/redux-form#2819]
### Are you submitting a **bug report** or a **feature request**?
bug

### What is the current behavior?
checkout from master
`cd examples/simple`
`npm install`

### What is the expected behavior?
it would install successfully!

### What's your environment?
MacOS

### Other information

`npm install
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts will run only for `npm publish`.
npm WARN prepublish-on-install (In npm@4 and previous versions, it also runs for `npm install`.)
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> redux-form@6.6.3 prepublish /Users/avloss/home/repos/redux-form
> npm run test && npm run clean && npm run build

> redux-form@6.6.3 test /Users/avloss/home/repos/redux-form
> mocha --compilers js:babel-register --recursive --recursive "src/**/__tests__/*" --require src/__tests__/setup.js

sh: mocha: command not found

npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/Cellar/node/7.8.0/bin/node" "/usr/local/bin/npm" "run" "test"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! redux-form@6.6.3 test: `mocha --compilers js:babel-register --recursive --recursive "src/**/__tests__/*" --require src/__tests__/setup.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the redux-form@6.6.3 test script 'mocha --compilers js:babel-register --recursive --recursive "src/**/__tests__/*" --require src/__tests__/setup.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the redux-form package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mocha --compilers js:babel-register --recursive --recursive "src/**/__tests__/*" --require src/__tests__/setup.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs redux-form
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls redux-form
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/avloss/.npm/_logs/2017-04-16T06_13_57_225Z-debug.log
npm ERR! addLocal Could not install /Users/avloss/home/repos/redux-form
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/Cellar/node/7.8.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! redux-form@6.6.3 prepublish: `npm run test && npm run clean && npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the redux-form@6.6.3 prepublish script 'npm run test && npm run clean && npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the redux-form package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run test && npm run clean && npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs redux-form
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls redux-form
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/avloss/.npm/_logs/2017-04-16T06_13_57_392Z-debug.log`

**Comment by charlesrochati** [comment]
You have to download the entire project.

Once you're inside the project folder, just run `npm install` to install all the dependencies.

Then, still in the project folder (not inside examples, in the root directory), you will run the desired example by running something like `npm run example:fieldArrays`.

On the `package.json` file, on the key `scripts`, you'll find all the examples, just choose one and run.

I've just followed the steps below to run the `example:fieldArrays` example:

![steps](https://cloud.githubusercontent.com/assets/4968621/25158067/08993914-247c-11e7-829e-1cc43bebe4f8.png)


Then you pick an example to run (this is the `package.json`):
![examples](https://cloud.githubusercontent.com/assets/4968621/25158109/3ed3feba-247c-11e7-8c4a-742bf53a3942.png)

and then you run it:
`npm run example:fieldArrays`

and it's done, just navigate to [http://localhost:3030/](http://localhost:3030/):
![running-lol](https://cloud.githubusercontent.com/assets/4968621/25158225/1eea3b54-247d-11e7-9989-3a896986d37d.png)

**Comment by gustavohenke** [comment]
Thanks for the detailed info, @charlesrochati!
