### ISSUE TITLE
In FieldArry, Field can't be removed except the last one

### ISSUE THREAD

**Issue by summerinsect** [erikras/redux-form#2820]
```html
<div key={index}>
<Field  name="Filepic" component="input" type="file"/>
<FontIcon onClick={() => fields.remove(index)}>{'clear'}</FontIcon>
</div>
```

if type="file"
No matter what index is，only delete the last one.

**Comment by huan086** [comment]
Do not use `index` as key. Instead, uniquely identify the element, e.g. with an ever increasing ID. Using `index` as key causes all kinds of rendering issues, including yours.
