### ISSUE TITLE
Use PropTypes from 'prop-types' on v5 

### ISSUE THREAD

**Issue by elyobo** [erikras/redux-form#2822]
### Are you submitting a **bug report** or a **feature request**?

Bug report.

### What is the current behavior?

PropTypes are being imported from react.  This has been fixed in the v6 branch but not on v5.

### What is the expected behavior?

PropTypes should be imported from `prop-types` as it is in v6.

### What's your environment?

N/A

### Other information

Obviously there's a limit to how long you can continue to support the v5 branch, but hopefully this is a trivial enough change to do.  I'm happy to submit a PR against the `v5` branch if it's something that would be merged.  Unfortunately for us the migration to v6 is a massive task and we're still putting it off behind higher priority work.

**Comment by erikras** [comment]
Fix published in [`v5.3.5`](https://github.com/erikras/redux-form/releases/tag/v5.3.5).

**Comment by elyobo** [comment]
Thanks for such a quick turnaround!
