### ISSUE TITLE
Develop a library on top of redux-form. Uncaught Error: addComponentAsRefTo(...): Only a ReactOwner can have refs

### ISSUE THREAD

**Issue by muhanerd** [erikras/redux-form#2828]
I am trying to develop a separate library on top of redux-form, which should extend redux-form components (e.g., Field) and offer other components and functionality (e.g., undo, redo...). 

When linking (npm link) my new library with the client application I get the  very popular error: Uncaught Error: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).

My problem is: I don't know what to do with this error message! I don't use ref and I installed bundle-analyzer in order to check if somehow I use two copies of react but this is also not the case. 

In order to simplify things I reduced the code of my library now to only this:

```
// index.js
import {Field} from 'redux-form';

export { 
    Field
}

```

Is this a problem with redux-form? Should I create my own CustomField that wrapper Field? Or is this a problem with npm or webpack configuration?

Here is my **library's** package.json:

```
{
  "name": "undoable-redux-form-lib",
  "version": "0.1.0",
  "devDependencies": {
    "babel-core": "^6.24.1",
    "babel-loader": "^6.4.1",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-react-app": "^2.2.0",
    "babel-preset-stage-2": "^6.24.1",
    "webpack": "^2.4.1"
  },
  "dependencies": {
    "react": "^15.3.2",
    "react-dom": "^15.5.4",
    "react-redux": "^4.4.5",
    "redux": "^3.6.0",
    "redux-form": "^6.1.1"
  },
  "scripts": {
    "build": "webpack"
  },
  "files": [
    "build"
  ],
  "main": "./build/undoable-redux-form-lib.js"
}
```

And this is the **library's** webpack.config:

```
var webpack = require('webpack');
var path = require('path');
var libraryName = 'undoable-redux-form-lib';
var outputFile = libraryName + '.js';

var config = {
  entry: __dirname + '/src/index.js',
  devtool: 'source-map',
  output: {
    path: __dirname + '/build',
    filename: outputFile,
    library: libraryName,
    libraryTarget: 'umd',
    umdNamedDefine: true
  },
  module: {
    loaders: [
      {
        test: /(\.jsx|\.js)$/,
        loader: 'babel-loader',
        exclude: /(node_modules|bower_components)/,
        query: {
          presets: ['react', 'es2015', 'stage-2'],
          plugins: ['transform-class-properties']
        }
      }
    ]
  }
};

module.exports = config;
```

The package.json of the **consuming application** looks like this:

```
{
  "name": "undoable-redux-form",
  "version": "0.1.0",
  "devDependencies": {
    "react-scripts": "0.7.0",
    "redux-devtools-extension": "^1.0.0"
  },
  "dependencies": {
    "react": "^15.3.2",
    "react-dom": "^15.3.2",
    "react-redux": "^4.4.5",
    "redux": "^3.6.0",
    "redux-form": "^6.1.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}

```

In my application I use Field like this:
```
import React, {Component} from 'react';
import {Field} from 'undoable-redux-form-lib';
import UndoButton from '../UndoButton';
import RedoButton from '../RedoButton';
import {undoableForm} from '../../decorators/undoableForm';

class MainForm extends Component{
    render(){      
        const {redo, undo, redoable, undoable} = this.props;           
        return <form>
                <Field name='name' component='input' type="text" />
                <UndoButton undo={undo} undoable={undoable}/>
                <RedoButton redo={redo} redoable={redoable}/>
               </form>
    }
} 

export default undoableForm({
    form: 'mainForm'
})(MainForm)
```

I would appreciate any hint! 

**Note**: when I change the import to ```import {Field} from 'redux-form'; ``` everything works just fine! I don't really know what happens exactly when I provide Field from my library!?

**Comment by erikras** [comment]
I would recommend moving everything in your `dependencies` to `peerDependencies`, and then making the users of your lib install them. I don't fully understand _why_ that should help, but my intuition says that it should.

- [Peer Dependencies](https://nodejs.org/en/blog/npm/peer-dependencies/)
- [The problem peer dependencies solve](http://stackoverflow.com/a/34645112/103690)

**Comment by muhanerd** [comment]
As I know peerDependencies help if I am using two different versions of the same third-library in my lib and my app. Anyway I tried what you have recommended but this didn't help :(

I include my lib and my app code. I would appreciate it so much if you (or someone else) could have a look at it. Thanks!
[redux-form-lib.zip](https://github.com/erikras/redux-form/files/935590/redux-form-lib.zip)
[redux-form-app.zip](https://github.com/erikras/redux-form/files/935591/redux-form-app.zip)

**Comment by muhanerd** [comment]
My colleague pointed me that an public/index.html is not found in the redux-form-app.zip package. Here is the corrected version. Sorry!

[redux-form-app.zip](https://github.com/erikras/redux-form/files/954482/redux-form-app.zip)

**Comment by muhanerd** [comment]
Solution:

redux-form-lib's package.json

```
{
  "name": "redux-form-lib",
  "version": "0.1.0",
  "devDependencies": {
    "babel-core": "^6.24.1",
    "babel-loader": "^6.4.1",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-react-app": "^2.2.0",
    "babel-preset-stage-2": "^6.24.1",
    "webpack": "^2.4.1"
    "react": "^15.3.2",
    "react-redux": "^4.4.5",
    "redux": "^3.6.0",
    "redux-form": "^6.1.1"
  },
  "peerDependencies": {
    "react": "^15.3.2",
    "react-redux": "^4.4.5",
    "redux": "^3.6.0",
    "redux-form": "^6.1.1"
  },
  "scripts": {
    "build": "webpack"
  },
  "files": [
    "build"
  ],
  "main": "./build/redux-form-lib.js"
}
```
But also in webpack.config.js react should be declared as externals!

```
var webpack = require('webpack');
var path = require('path');
var libraryName = 'redux-form-lib';
var outputFile = libraryName + '.js';

var config = {
  entry: __dirname + '/src/index.js',
  output: {
    path: __dirname + '/build',
    filename: outputFile,
    library: libraryName,
    libraryTarget: 'umd'    
  },
  externals: [
    {
      react: {
        root: 'React',
        commonjs2: 'react',
        commonjs: 'react',
        amd: 'react'
      }
    }
  ]  
};

module.exports = config;
```

**Comment by muhanerd** [comment]
And very important. npm link doesn't seem to work! I had to add the lib as ad dependency in the app.

**Comment by danielrob** [comment]
@muhanerd thanks for that! If you think this ticket has something outstanding please update, otherwise close it? @erikas [+1's you regarding `npm link`](https://github.com/erikras/redux-form/issues/2948#issuecomment-319376089)... I used to have an npm install script in it's place too on an old project...

**Comment by jsbranco** [comment]
Actually, I having this same issue. My library wrapped existing forms that are using redux-form. However when I bundle it and use it in my app, I get the same issue as @muhanerd .

@erikras  I tried to move the dependencies to peerDependencies but that causes my App to failed to compile, it will say  claim redux-form is not found:

`Module not found: Error: Can't resolve 'redux-form' in '/Users/jbranco/IdeaProjects/redux-lib/target/dist'
`
