### ISSUE TITLE
Initialize form and show submission errors?

### ISSUE THREAD

**Issue by eventhough** [erikras/redux-form#283]
I'm working on a login form where I'd like to clear the password field after the user submits the form. The problem is, when the server returns errors I need to show those errors on the form, but initializing the form **also** resets all the `touch` fields. So basically no errors are shown because the form has been initialized again...but the error does show up in form state.

I'm doing this by calling `initialize` as a redux-form action creator...and I know this goes against your advice:

> However, it is highly recommended that you use the actions passed as props to your component for most of your needs.

I tried using the `initialValues` configuration but this seems to call the `initialize` action internally as well. I also looked into just calling `.onChange` inside my form before submission but this fires off validation again which is not what I want.

Any recommendations?

**Comment by erikras** [comment]
This is precisely the use case [documented here](http://erikras.github.io/redux-form/#/api/reducer/plugin).

**Comment by eventhough** [comment]
@erikras I just tried it out. Here's what I did - I replaced the default `formReducer` from redux-form by exporting it with my plugin attached:

```javascript
import { reducer as formReducer } from 'redux-form';

export default formReducer.plugin({
  login: (state, action) => {
    switch (action.type) {
    case LOG_IN:
      return {
        ...state,
        password: {
          ...state.password,
          value: '',
        },
      };
    default:
      return state;
    }
  },
});
```

But I am still seeing my sync validate error instead of the one from the server. If I remove sync validation, my server error comes through. I guess there's no way to have your cake and eat it too? Sync validation is run no matter what?

Thanks!

**Comment by erikras** [comment]
Oh, you've got a "required" sync validation. In that case, your error from the server should go into the `_error` key, which is global to the whole form.

```js
{
  _error: 'Login failed'
}
```

Then, in your form:
```js
render() {
  const {fields: {email, password}, error, handleSubmit} = this.props;
  return <form onSubmit={handleSubmit(login)}>
      <input type="email" {...email}/>
      {email.touched && email.error && <div>{email.error}</div>}
      <input type="password" {...password}/>
      {password.touched && password.error && <div>{password.error}</div>}

      {error && <div>{error}</div>} // <----- generic form-wide error

      <button onClick={handleSubmit(login)}/>
    </form>
}
```

**Comment by erikras** [comment]
I just added this to the [Submit Validation Example](http://erikras.github.io/redux-form/#/examples/submit-validation).

**Comment by eventhough** [comment]
@erikras Got it. What I do right now is I have my server return errors in the format `{ field1: 'foo', field2: 'bar' }` which I just pass directly to redux-form wrapped in a rejected Promise. That way server errors show up right next to their fields which is super user-friendly.

I guess this is not a big deal because clearing a field only applies to login forms and maybe sign up forms. My fear is that a user might accidentally leave a typo password in the login form then walk away to the bathroom or something. Someone could then copy the typo password and figure out what the user's actual password is.

I would say 95% of my forms do not need any fields to be "cleared'" for security reasons. What I'll do right now is use the plug-in to wipe clear the field and just let sync validation override the server one.

Thanks!

**Comment by erikras** [comment]
Yep! You got it. :+1: The "clearing with `plugin()`" situation is so rare, that I don't mind it being a little awkward.

**Comment by prabhjot-izap** [comment]
h

**Comment by BenLorantfy** [comment]
@erikras http://erikras.github.io/redux-form/#/api/reducer/plugin link is broken
