### ISSUE TITLE
Remove meta.touched from FieldArrays to avoid confusion since it's always false

### ISSUE THREAD

**Issue by EvilOatmeal** [erikras/redux-form#2830]
### Are you submitting a **bug report** or a **feature request**?

Bug.

### What is the current behavior?

`meta.touched` is included in FieldArrays even though `touched` is no longer set, which is confusing when debugging the application and you expect `touched` to behave just like it does in the Field component.

### What is the expected behavior?
`meta.touched` should not be included since it's always `false` anyway.

### What's your environment?

Applicable since Redux Form v6.5.0.

### Other information

`meta.touched` was added to FieldArrays in PR #1715 and released in v6.0.3, but then PR #2473 and release v6.5.0 stopped updating touched on FieldArray to fix a bug.

I spent an hour trying to figure out which regression caused touched to no longer be set when in fact it was a bug fix.

**Comment by erikras** [comment]
Published fix as [`v6.7.0`](https://github.com/erikras/redux-form/releases/tag/v6.7.0).
