### ISSUE TITLE
bug report > async validation has big problem

### ISSUE THREAD

**Issue by trazy** [erikras/redux-form#2831]
http://redux-form.com/6.6.3/examples/asyncValidation/

there is example page

step1. input any password
step2. 'george' copy to clipboard
step3. paste user name then click signup immediatelly

then -> submit ok and error thown ( unhandled promise )

submit must be blocking in async work.

and this problem need check in mobile device

**Comment by irvingv8** [comment]
Well, I'm not really sure if I'd call this a bug of the redux-form itself but a implementation issue, this is what's going on:

You are not able to submit in either of this cases:
1- username is empty
2- username is validated and it's been taken

What's happening is that you are clicking submit right after providing a username and before it's done with the validation.

Possible solution: Set a state indicating that the form is waiting for the validation and disable the submit button until it finish the validation.

**Comment by trazy** [comment]
in my opinion,

async validation is checking step of one.

i agree to disable submit button until done async validation, ( examply like your comment  )

but that's an redux-from's responsibility.

redux-form must be promise blocking submitting.

if don't promise blocking, that`s non of redux-form's feature.
