### ISSUE TITLE
Sync errors are lost for deep/nested fields in Immutable store

### ISSUE THREAD

**Issue by erikras** [erikras/redux-form#2834]
### Are you submitting a **bug report** or a **feature request**?

Bug. As reported to me by @hsz on Twitter.

### What is the current behavior?

Deep sync errors are getting lost when using an immutable store.

### Sandbox Link

[![Edit Redux Form  - Deep Immutable Validation](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/WnvNzMNnv)

Related to #2779.

**Comment by erikras** [comment]
Update. Initial sandbox had a bug in the validation function. Seems to be working as expected now.

[![Edit Redux Form  - Deep Immutable Validation](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/Xrv56pWg)

**Comment by hsz** [comment]
@erikras Finally I had a time to investigate this problem again. It appeared that I had misconfigured my reducers. I was importing:

```
import { reducer } from 'redux-form';
```

instead of
```
import { reducer } from 'redux-form/immutable';
```

It's fine now. Sorry for all this noise I did. ;)
