### ISSUE TITLE
Async Blur fields swollows event

### ISSUE THREAD

**Issue by kristian-puccio** [erikras/redux-form#284]
When blurring or leaving a field (say clicking on the submit button) that has asyncBlurFields turned on I have to click twice to get my click to register.

When I turn off asyncBlurFields then I only have to click once.

**Comment by erikras** [comment]
Hmm.. I'm not seeing that. Does it happen for you on the [Async Example](http://erikras.github.io/redux-form/#/examples/asynchronous-blur-validation)?

**Comment by kristian-puccio** [comment]
No it doesn't happen for me there.
Grr must be doing something weird.
I'll look into it and post what I find here so it might help others.

**Comment by kristian-puccio** [comment]
Ok I worked this out. My form submit button render was disabling the button when asyncValidating was set to true.

So in the moment the blur happened the button was disabled and the click disappeared.

Anyway maybe this is helpful to someone!

**Comment by erikras** [comment]
Thanks for reporting back. :+1:
