### ISSUE TITLE
why 'value' in propsToNotUpdateFor

### ISSUE THREAD

**Issue by DongCai008** [erikras/redux-form#2840]
### What is the current behavior?

if any update made in the 'value', ConnectedFieldArray's 'shouldComponentUpdate' returns false which leads the render() won't be called

### What is the expected behavior?
I want the shouldComponentUpdate() return true if any single change in the value. since 'value' contains all latest state of view. if it has been changed, why view didn't be refreshed.
I solved this issue by remove 'value' from propsToNotUpdateFor.

**Comment by danielrob** [comment]
This is how I found the answer:

1. Search 'propsToNotUpdateFor' 
2. Open ConnectedFieldArray.js
3. Click blame
4. Go back in time once
5. Find #1590 which refers to #1578 

Et voila :).
