### ISSUE TITLE
Remove peerDependencies with `react@^15.0.0`

### ISSUE THREAD

**Issue by giautm** [erikras/redux-form#2842]
Because i using `react@16.0.0-alpha.6`, peer dependency with v15 make a copied of react and cause a problem.
Current workaground is remove `node_modules/redux-form/react`
https://github.com/erikras/redux-form/blob/master/package.json#L109

Please move react to `dependencies` or set `peerDependencies` to `"react": "^15.0.0 || 16.0.0-alpha.6"`

**Comment by gustavohenke** [comment]
👍 for the second alternative

**Comment by giautm** [comment]
Workaround steps:
Step 1:
```
yarn add rimraf -D
```

Step 2: Add following script to `package.json` under `scripts`
```
    "postinstall": "rimraf ./node_modules/redux-form/node_modules/react"
```
Now, after install any module, `./node_modules/redux-form/node_modules/react` will auto remove.

<img width="455" alt="screen shot 2017-05-05 at 23 23 31" src="https://cloud.githubusercontent.com/assets/12751435/25754687/5da3c3ae-31ea-11e7-8b14-e1965013a104.png">
