### ISSUE TITLE
Can not change the name 'form' in the reducer

### ISSUE THREAD

**Issue by adamwuyu** [erikras/redux-form#2845]
### What is the current behavior?

If I change the name 'form' in the reducer, the redux and form input can not be correctly updated. 

### What is the expected behavior?
Can change the name 'form' in the reducer, like:
`var dataForm = formReducer.plugin({
  data_dimension_add: (state = {}, action) => {
    switch (action.type) {
      default:
        return state
    }
  },
})`

### What's your environment?

Redux-3.6.0, redux-form-6.6.3 , MacOS-10.12.4, Safari-10.1/Chrome-58.0.3029.81

**Comment by gustavohenke** [comment]
Can you be clearer on what you want?
Perhaps it's a combination of renaming the reducer key + using [`getFormState`](http://redux-form.com/6.6.3/docs/api/ReduxForm.md/#-getformstate-function-optional-)?

I can't see what reducer plugins have to do here.

**Comment by adamwuyu** [comment]
@gustavohenke Thank you for your reply. In our project there are many forms. If we put all state into reducer->form, it will be hard to maintain. It is better to divide into reducer->dataForm, reducer->structureForm and so on. But if change 'form' to 'xxxForm', reducer doesn't update as expected. Any idea?

**Comment by gustavohenke** [comment]
I linked it above.

**Comment by adamwuyu** [comment]
@gustavohenke thank you for your confirmation.
