### ISSUE TITLE
Initialize from state with different keys

### ISSUE THREAD

**Issue by Sashkan** [erikras/redux-form#2846]
Following [the documentation](http://redux-form.com/6.6.3/examples/initializeFromState/), I managed to prefill a form with data from my application state, using ```initialValues```

Unfortunately, so far, if my data is called user.profile.firstName, I have to make sure that my Field is named user.profile.firstName. Is there a way to configure my Field so that I can name it as I want, and then just map it to the matching data ?

**Comment by gustavohenke** [comment]
No way to do this currently.

You may customize the data before it reaches the `initialValues` prop, and customize it before you send requests in your `onSubmit`.
This way you have both ways covered: data entering, data leaving.
