### ISSUE TITLE
Get name of changed field in onChange

### ISSUE THREAD

**Issue by TungAng** [erikras/redux-form#2849]
I cannot think of any way to get the name of the field being changed when onChange is fired. Is it impossible? or is there any way I can achieve the same result (get the name of the field being changed) with other methods?

**Comment by ericbiewener** [comment]
Agreed. I currently have to keep a cache of all the previous form values and compare each field to determine which one has changed.

**Comment by sanohin** [comment]
Why don't you use actions dispatched with type `@@redux-form/CHANGE`? There you can get the field name and the new value.

**Comment by ericbiewener** [comment]
@sanohin That would require writing some custom middleware, no?

**Comment by sanohin** [comment]
@ericbiewener Well, yeah, just that "onChange" logic would be in that middleware. Could you please explain in what case you would like to use this feature? Maybe curried function can solve this problem?

**Comment by ericbiewener** [comment]
Redux Form currently only supports async validation on blur. I have a use case that requires this validation to run on change instead. While middleware would work, as does the current solution I'm using as described in my first comment in this thread, providing the changed field name in the `onChange` event would eliminate the need for such manual approaches.

**Comment by kalebwalton** [comment]
I'd like to do some data loads when the value of a field changes, but I don't know the name of the field so I can't make it nice and generic :(

**Comment by ericbiewener** [comment]
I have opened up a trivial PR [here](https://github.com/erikras/redux-form/pull/3520) to do this. Rather than providing the name of the changed field, it simply passes along the form's previous values. Redux Form therefore doesn't have to do any additional work beyond just adding an argument to the function call.

**Comment by kevva** [comment]
As described in `https://github.com/erikras/redux-form/issues/3854#issue-299298108`, I think we could add it to `event.target.name` as a native DOM element would behave.

It'd definitely be useful.
