### ISSUE TITLE
Coerce initialValues to string?

### ISSUE THREAD

**Issue by willmcclellan** [erikras/redux-form#285]
I came across a bug in a validator I wrote, which arose from the way initialValues are set - the validator broken when the value wasn't a string. When we get JSON data from our API, we might have other values than strings: numbers, dates etc and these will be set as initialValues when used.

But `input` elements `value` property always returns a string, so as soon as you touch a field, the value returned (and passed to validation) is a string. I'm wondering whether initialValues should be coerced to a string so the behaviour is consistent, as it was a bit strange to see validation behaving differently after the field is touched.

Happy to submit a PR, just wanted to make sure it was worthwhile first?

**Comment by erikras** [comment]
I gave my opinion on this in #105, but I'm not dogmatic about it, so feel free to persuade me otherwise.

The main problem is that I don't think we can assume that _all_ inputs both take and give strings, just because the standard html inputs do.

**Comment by willmcclellan** [comment]
Yeh that's a good point, I was assuming all fields would be html inputs. I suppose the only niggling point is the different behaviour with initialValues and after a touch. It's fine, but a bit frustrating when debugging the behaviour. I'll close this and maybe see if the many others have the same the issue
