### ISSUE TITLE
React Native FormSection is work  ?

### ISSUE THREAD

**Issue by melihberberolu** [erikras/redux-form#2865]
I have multiple dynamic form. I'm wanna submit with one button. Anyone help me!

```
return <form onsubmit={...}>
            <FormSection name="buyer">
                <Party/>
            </FormSection>
            <FormSection name="recipient">
                <Party/>
            </FormSection>
        </form>
```

React native doesn't have form so how can i use FormSection for multiple form

**Comment by erikras** [comment]
All `FormSection` does is add a prefix to all the `name` props of any `Field`s inside it.

As for how to use `redux-form` with `react-native`, I'd recommend [this article](https://medium.com/wolox-driving-innovation/https-medium-com-wolox-driving-innovation-easy-forms-in-react-native-with-redux-form-1cdc16a9a889).
