### ISSUE TITLE
Redux-form semantic UI with AsyncValidation

### ISSUE THREAD

**Issue by viiiprock** [erikras/redux-form#2869]
### **Need help**
I followed this example http://redux-form.com/6.6.3/examples/submitValidation/
and http://redux-form.com/6.6.3/examples/asyncValidation/

I use Semanitic-UI & made a loading state Redux-form component as code below: 

Loading state of the semantic Input is: 
`<Input loading icon='user' placeholder='Whatever...' />`
You could find it [here](https://react.semantic-ui.com/elements/input#input-example-loading)

And the render Field component is: 
```js
...
const ReduxFormInput = ({ input, label, placeholder, checkboxLabel, type, meta: { asyncValidate, touched, error } }) => {
  const errorMessage = (<div style={{ color: '#E20000', paddingTop: '.3rem', fontSize: '12px' }} >
    <Icon name="warning" />
    {error}
  </div>);

  return (
    <div>
      <Label>{label}</Label>
      <Input
        {...input}
        type={type}
        placeholder={placeholder}
        error={error ? true : null}
        loading={asyncValidate ? true : undefined} // load loading state when submitting 
        icon={asyncValidate ? 'user' : undefined} // load icon state when submitting
      />
      {touched && error && errorMessage}
    </div>
  );
};

export default ReduxFormInput;
```
The form work perfectly instead of Async Loading state within semantic-ui component.

**My expect** is the icon loading when submitting form 

Thank you so much.

**Comment by vitbokisch** [comment]
@viiiprock do you mean you need an example of how to validate an input length or how to set mag-length to that field? Or you don't know how to make working semantic-ui-react components with redux-form?

**Comment by vitbokisch** [comment]
@viiiprock I am actually not sure if I got your point... could you be more specific?

**Comment by viiiprock** [comment]
Thanks @vitbokisch ,  I edited my post, hope it is more clearer.

**Comment by vitbokisch** [comment]
@viiiprock if you want to show loading when submitting form, there is another boolean prop meta.submitting, just extend your meta props with this meta: { asyncValidate, submitting, touched, error }. Hope this helps ;)

**Comment by viiiprock** [comment]
@vitbokisch yes, I did it at
`const ReduxFormInput = ({ input, label, placeholder, checkboxLabel, type, meta: { asyncValidate, touched, error } }) => ...`
then I add behavior in component
```js
<Input
  {...input}
  type={type}
  placeholder={placeholder}
  error={error ? true : null}
  loading={asyncValidate ? true : undefined} // ---> semantic-ui-react loading prop, state when submitting 
  icon={asyncValidate ? 'user' : undefined} // ---> semantic-ui-react icon prop, load icon when submitting
/>
```
then I use this component to the main form as the `<Field/>` component.

But it not works, I'm trying to figure it out...

**Comment by vitbokisch** [comment]
`const ReduxFormInput = ({ input, label, placeholder, checkboxLabel, type, meta: { submitting, asyncValidate, touched, error } }) => ...`

```
<Input
  {...input}
  type={type}
  placeholder={placeholder}
  error={error ? true : null}
  loading={submitting|| asyncValidate ? true : undefined} // ---> semantic-ui-react loading prop, state when submitting 
  icon={submitting|| asyncValidate ? 'user' : undefined} // ---> semantic-ui-react icon prop, load icon when submitting
/>
```

What about like this?

**Comment by viiiprock** [comment]
That's correct, ... may be I don't really understand all the docs or the docs is hard to me :D 
thanks @vitbokisch  so much

**Comment by vitbokisch** [comment]
@viiiprock you are welcome, btw console.log() will help you to understand what props are passed ;)
