### ISSUE TITLE
_error key inaccessible outside of form

### ISSUE THREAD

**Issue by TrevorHinesley** [erikras/redux-form#2872]
As the title suggests, if stopSubmit is called, I can call it like:

`stopSubmit(FORM, {_error: err.message})`

The form will receive the error in its props, but the wrapper component of my form (which uses the selector `getFormSubmitErrors`), will be undefined. If I change the key from `_error` to anything else, it will work properly.

**Comment by mitas1** [comment]
Can you send a pull request @tgallacher please?

**Comment by gustavohenke** [comment]
Duplicate of #3325
