### ISSUE TITLE
"Invalid Keypath" error when editing FieldArray after submit has failed.

### ISSUE THREAD

**Issue by dagstuan** [erikras/redux-form#2875]
### Are you submitting a **bug report** or a **feature request**?
Bug report

### What is the current behavior?
https://codesandbox.io/s/MPzRZV21

If you submit the form, and then (after the submit has failed) try to add/delete members and edit their fields. An "Invalid KeyPath" error will be logged to the console.  This is only while using the immutable.js-version of redux-form.

### What is the expected behavior?
No "invalid keypath"-message

### Other information
I have narrowed this problem down to the code for `ArraySplice` which inserts `undefined` into the state for `submitErrors` and `asyncErrors`. When editing one of the fields inside a FieldArray the code `deleteInWithCleanUp(result, `submitErrors.${field}`)` is called, which tries to update the submit errors for the field inside the array, however, the array element is set to "undefined" in the state, and a call to immutable.js such as `state.updateIn(['form', 'formName', 'submitErrors', '0', 'fieldName'], /*  rest */)` fails with the "Invalid KeyPath" error.

**Comment by erikras** [comment]
Published fix as [`v6.7.0`](https://github.com/erikras/redux-form/releases/tag/v6.7.0).
