### ISSUE TITLE
Uncaught SubmissionError after ajax request 

### ISSUE THREAD

**Issue by KrifaYounes** [erikras/redux-form#2879]
When I try to throw new SubmissionError after ajax request I got this message on console 'UNCAUGHT SubmissionError'

It's work when I use fetch request.

### What's your environment?

node version : 4

### Other information

import { SubmissionError } from 'redux-form'

const openShop = (values, sellerId) => {
    var submitUrl = `/seller/sellerOpenShop/submission/${sellerId}`
    
    return $.ajax({
            type: 'POST',
            url: submitUrl,
            contentType: 'application/json',
            data: values
        })

            .then(function (response) {

                const errors = getErrorsFromResponse(response);
                throw new SubmissionError(errors)

            });
}

**Comment by nchery** [comment]
it should be more something like
`
return $.ajax({
        type: 'POST',
        url: submitUrl,
        contentType: 'application/json',
        data: values, 
       success: (response) => resolve(response)
    })
.then(response =>(doWhatever))
`

**Comment by danielrob** [comment]
> Hi, thanks for coming by.
> 
> Please use StackOverflow for usage questions. This is the only way to ensure the same question doesn’t get asked many times in a row, and that folks who have the same question in the future will be able to find it. It will also attract more help than this issue tracker which is for tracking bugs and feature requests. 

You need to return the promise in the reject() call from a promised passed as your onSubmit function. Here you are simply throwing an error in a promise chain which has no catch.
