### ISSUE TITLE
syncErrors still persist in state after fields have been unmounted and unregistered

### ISSUE THREAD

**Issue by ArjanJ** [erikras/redux-form#2884]
### What is the current behavior?
I have required fields that only get mounted when a checkbox field is true.
When the checkbox is checked, `syncErrors` are now present in state (makes sense)
When the checkbox is then unchecked, `syncErrors` are still there even though the fields are not in `registeredFields`

### What is the expected behavior?
When the fields are unmounted and unregistered, they should also be removed from `syncErrors` because they stop the form from being submitted successfully.

### What's your environment?

v6.6.3
Chrome latest
Mac OS X 10.11.4
Node v7.2.0

If a code example is required please let me know. I'm working in a private codebase so I'd have to something up.

Thank you

**Comment by holzru** [comment]
Same issue, we have a FieldArray with object fields. They use a formatValue and parseValue for validation in order to validate the correct property on the object. When a field is deleted from the fieldArray using fields.remove(index), the validation is fired again after the object has been deleted from the fieldArray and validate tries to validate an undefined object still using the format and parseValues which clearly leads to a horrendous error

**Comment by ArjanJ** [comment]
@holzru I also have that issue with FieldArrays, I figured it's closely related to this issue so I didn't create another ticket.

**Comment by holzru** [comment]
@ArjanJ if you're interested found a temporary work around for this issue until bug is fixed 
`shouldValidate: (params) => {
      const { values, nextProps } = params;
      const nextValues = nextProps.values;
      if (nextValues.FieldArray.length < values.FieldArray.length) {
        return false;
      }
      return true;
    }
`

**Comment by erikras** [comment]
> If a code example is required please let me know. I'm working in a private codebase so I'd have to something up.

That's what [the sandboxes](https://github.com/erikras/redux-form#-code-sandboxes-) are for! 😀 However, you explained it so well that I understand the problem exactly.

**Comment by erikras** [comment]
Fix published as [`v6.7.0`](https://github.com/erikras/redux-form/releases/tag/v6.7.0).
