### ISSUE TITLE
React Native -  focus is not a function when getRenderedComponent

### ISSUE THREAD

**Issue by stefensuhat** [erikras/redux-form#2896]
Here is my code:

    componentDidMount = () => {
        console.log(this.refs.lastName.getRenderedComponent());
        this.refs.lastName.getRenderedComponent().focus();

    }

    render() {
        return (
            <Grid containerStyle={{backgroundColor: '#fff'}}>
                
                <Row size={3.5} containerStyle={styles.topContainer}>
                    <View>
                        <Field type="text" returnKeyType={"next"} ref="firstName" withRef
                               name="firstName" label="First Name" component={RenderField}/>

                        <Field last type="text" name="lastName" label="Last Name"
                               ref="lastName" withRef component={RenderField}/>

                    </View>
                </Row>

            </Grid>
        )
    }

     // Render Field

    import React from 'react';
    import PropTypes from 'prop-types';
    import {Text} from 'react-native';
    import {Item, Input, Label} from 'native-base';

    class RenderField extends React.Component {
        render() {
            const {input, label, type, meta: {touched, error, invalid, warning}, custom} = this.props;

            let hasError = false;
            if (error !== undefined) {
                hasError = true;
            }
            return (
                <Item floatingLabel error={hasError} style={{marginBottom: 20}}>
                    <Label>{label}</Label>
                    <Input {...input} {...custom}/>
                    {hasError ? <Text>{error}</Text> : <Text />}
                </Item>
            )
        }
    }

    export default RenderField;

The console.log return properly but at `this.refs.lastName.getRenderedComponent().focus();` it always return this error `_this.refs.lastName.getRenderedComponent().focus is not a function`. 

I'm using Redux Form v6 and Native Base v2

Thanks.

**Comment by erikras** [comment]
What sort of object is `this.refs.lastName.getRenderedComponent()`? From your error message, it's clearly not `undefined`, so it must be some RN element.

How do you set focus to an input in RN?

**Comment by stefensuhat** [comment]
@erikras 
![error](https://cloud.githubusercontent.com/assets/10653041/25845279/88449c06-34d7-11e7-8edb-c12f2b5c4e6b.png)

Here i uploaded the console.log this.refs.lastName.getRenderedComponent()

**Comment by erikras** [comment]
It sounds like this is not a Redux Form problem. Redux Form is giving you the rendered component just fine. You'll have to figure out how to give it focus. I don't know anything about React Native, so I can't really help you. It's certainly not obvious how in the [NativeBase docs](https://docs.nativebase.io/Components.html#Components). ?? Wish I could be of more help.

**Comment by stefensuhat** [comment]
@erikras it still happen even I change it to original react native text input. can't solve this problem.

**Comment by stefensuhat** [comment]
![untitled](https://cloud.githubusercontent.com/assets/10653041/25994048/77f4e980-3736-11e7-9119-6084a218661f.png)

```
<TextInput ref="lastName"/>

<Field
    name="firstName"
    component={RenderField}
    ref='firstName'
    withRef
    type="text"
    placeholder="First Name"
/>
```

At console.log the result is so much different as especially without `Field` method there is `focus()` function.

**Comment by dittmarconsulting** [comment]
I found a solution @stefensuhat. I posted it on StackOverflow
http://stackoverflow.com/questions/43917795/react-native-redux-form-use-keyboard-next-button-to-go-to-next-textinput-fie/43952870#43952870

Please up-vote if this was helpful

**Comment by nschurmann** [comment]
Does not work with native base

**Comment by kidnapkin** [comment]
@nschurmann, works with nativebase as well, first check nativebase docs [Ref to Components](https://docs.nativebase.io/Components.html#ref-components-headref)
The way it works for me:
```Javascript
<Form>
  <Field
    withRef
    ref={(c) => this.email = c}
    refField='email'
    returnKeyType='next'
    label='email'
    name='email'
    component={RenderInput}
    onSubmitEditing={() => this.password.getRenderedComponent().refs.password._root.focus()}
  />
  <Field
    withRef
    ref={(c) => this.password = c}
    refField='password'
    secureTextEntry
    returnKeyType='go'
    label='password'
    name='password'
    component={RenderInput}
    onSubmitEditing={handleSubmit(this.submit)}
  />
</Form>
```
