### ISSUE TITLE
unable to set syncErrors in connect mapStateToProps 

### ISSUE THREAD

**Issue by sckoh** [erikras/redux-form#2899]
**bug report**

### What is the current behavior?
unable to set syncErrors in connect mapStateToProps 
syncErrors will lost in component props.
It works if I change the prop name to other than 'syncErrors'

```
export default connect(state => ({
  syncErrors: getFormSyncErrors('syncValidation')(state), // not working
  formSyncErrors: getFormSyncErrors('syncValidation')(state), // working
}))(SyncValidationForm);
```

### What is the expected behavior?
able to set syncErrors in connect mapStateToProps 

### Sandbox Link

https://codesandbox.io/s/qjm0V2n7y

### What's your environment?
tried on https://github.com/erikras/redux-form/tree/master/examples/syncValidation
redux-form 6.6.3

**Comment by erikras** [comment]
Yes, this is because `syncErrors` is the key that `redux-form` uses internally. You'll have to call your prop something else.

**Comment by zijian-etc** [comment]
The doc here is confusing as it uses `syncErrors` as the key: https://github.com/erikras/redux-form/blob/master/docs/api/Selectors.md

```syncErrors: getFormSyncErrors('myForm')(state),```

**Comment by naniantero** [comment]
@zijian-etc Yes, just spent a day debugging this issue and all I did was follow the instructions :)

**Comment by cristygrant** [comment]
Me too! I was following instructions here https://redux-form.com/7.0.1/docs/api/selectors.md/ and they used `syncErrors` as the key! should change documentation. Glad I found this issue.
