### ISSUE TITLE
weird validation behavior

### ISSUE THREAD

**Issue by luisrudge** [erikras/redux-form#29]
![asyncvalidation](https://cloud.githubusercontent.com/assets/941075/9370007/807a7e88-46a3-11e5-9ece-a427794f6cd4.gif)

This is the timeline of events

```
sync rule: email is required
async rule: email can't be invalid@email.com

user selects input
user types invalid@email.com
[form is valid, since async rule has not started yet]
user selects another input
[async validation starts]
[async validation ends]
form is invalid
```

The problem is my email input is my last input, so instead of `user selects another input` the user will click submit and this will not trigger the async validation at all. Well, it will after the submit happens.

Can we find a way to solve this scenario?

**Comment by erikras** [comment]
I've seen something similar on my own project. I see three unsatisfactory solutions:

1. Put another input after `email`. :smile_cat: 
2. Don't change your submit button's `disabled` state based on `valid`, and accept the two async calls (one from `onBlur` and another from `onSubmit`).
3. Turn off `onBlur` async validation and only do it `onSubmit`

**Comment by luisrudge** [comment]
What if, once sync validation is ok, we trigger async validation right away?

**Comment by luisrudge** [comment]
I'm currently doing this:

```js
  onSubmit = (e) => {
    e.preventDefault();
    validations.validateAsync({email: this.props.data.email})
    .then(result => {
      if(result.valid) {
        //really submit form
      } else {
        //nooooope
      }
    });
  };
```

Not sure what's the best way to handle this scenario

**Comment by erikras** [comment]
That's pretty much exactly what the built-in [`handleSubmit`](https://github.com/erikras/react-redux-universal-hot-example/issues/63), introduced in [v0.2.0](https://github.com/erikras/redux-form/releases/tag/v0.2.0), is doing, except that it's also managing the "are we currently async validating?" state.

**Comment by luisrudge** [comment]
ohhh. nifty! I'll check that out. thanks!

**Comment by luisrudge** [comment]
Thanks. That solves my issue!
