### ISSUE TITLE
How can I submit a form programmatically in componentDidMount (or componentWillMount)?

### ISSUE THREAD

**Issue by xcatliu** [erikras/redux-form#290]
I have a problem to submitting a form programmatically, passing defaultValues as arguments.

Below is the code sample:

```js
import React, {Component, PropTypes} from 'react';
import {reduxForm} from 'redux-form';

class SimpleForm extends Component {
  static propTypes = {
    fields: PropTypes.object.isRequired,
    handleSubmit: PropTypes.func.isRequired
  };
  componentDidMount() {
    // How can I pass the defalutValues to handeSubmit
    this.props.handleSubmit();
  }
  render() {
    const { fields: { name }, handleSubmit } = this.props;
    return (
      <form onSubmit={handleSubmit}>
        <input type="text" placeholder="name" {...name}/>
      </form>
    );
  }
}

export default reduxForm({
  form: 'simple',
  fields: [ 'name' ],
  defaultValues: {
    name: 'Jack'
  }
})(SimpleForm);
```

I can only find `this.props.values` which is related to values, but got `{ name: undefined }` unexpectedly.

**Comment by xcatliu** [comment]
Perhaps the same problem: https://github.com/erikras/redux-form/issues/152#issuecomment-157662993

**Comment by erikras** [comment]
`defaultValues` does not exist (yet, #176). You need `initialValues`.

**Comment by xcatliu** [comment]
I tried `initialValues`, but in `componentDidMount` or `componentWillMount` lifecycle, values seems not initialized yet.
I used setTimeout to fix this problem:
```js
import React, {Component, PropTypes} from 'react';
import {reduxForm} from 'redux-form';

class SimpleForm extends Component {
  static propTypes = {
    fields: PropTypes.object.isRequired,
    handleSubmit: PropTypes.func.isRequired
  };
  componentDidMount() {
    setTimeout(() => {
      this.props.handleSubmit();
    }, 1000 / 60);
  }
  render() {
    const { fields: { name }, handleSubmit } = this.props;
    return (
      <form onSubmit={handleSubmit}>
        <input type="text" placeholder="name" {...name}/>
      </form>
    );
  }
}

export default reduxForm({
  form: 'simple',
  fields: [ 'name' ],
  initialValues: {
    name: 'Jack'
  }
})(SimpleForm);
```

**Comment by gabrielenosso** [comment]
Up.
this.props.initialValues is undefined in the method componentDidMount.
Then in the first componentDidUpdate it results correct.

But why it's like that?
How can I read the initial param values in componentDidMount?

**Comment by ooflorent** [comment]
@xcatliu You can submit a form progammatically using `this.refs.childform.submit(). There is an example using it: [Submit from parent](http://redux-form.com/5.2.1/#/examples/submit-from-parent?_k=ya0axe)

---

Hi @gabrielenosso, thanks for coming by.

Please use StackOverflow for usage questions. This is the only way to ensure the same question doesn’t get asked many times in a row, and that folks who have the same question in the future will be able to find it. (Github search is pretty much useless.)

Sorry we couldn’t answer your question here. Please feel free to post a link to the StackOverflow question, and I’ll be happy to try to answer it.
