### ISSUE TITLE
Calling initialize(values) does not set props.initialized to true

### ISSUE THREAD

**Issue by marekjalovec** [erikras/redux-form#2901]
### **Bug report**
version: 6.6.0

### What is the current behavior?
Calling initialize(values) does not set props.initialized to true

### What is the expected behavior?
this.props.initialized === true

**Comment by erikras** [comment]
`this.props.initialized` is not part of [the documented API](http://redux-form.com/6.6.3/docs/api/Props.md/). It is used internally and does not cause a form rerender. It will be set to `true` once you touch a field, though. (Focus and blur a field after initializing)

[![Edit Redux Form - Initialize From State](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/lWpJWp8J)

I suppose it could be added, but I'm very hesitant to add props that cause a form rerender.

**Comment by marekjalovec** [comment]
hm true. but now to know if i initialized the form somewhere i have to keep the record by myself. i would love to have something in the form itself. probably just long term question, than urgent feature request. maybe you'll find some way :)

**Comment by erikras** [comment]
Actually, after some thought, I'm leaning towards allowing it to cause a rerender. It will literally only ever happen once.

**Comment by erikras** [comment]
Published fix as [`v6.7.0`](https://github.com/erikras/redux-form/releases/tag/v6.7.0).
