### ISSUE TITLE
How to handle React Routing using store

### ISSUE THREAD

**Issue by chandan7193** [erikras/redux-form#2902]
I want that user should not be able to enter certain URL like http:localhost:3000/error or http:localhost:3000/message by himself and this page should be visible only if a user enters submit button on the contact page.
'
import React, {Component} from 'react';
import {Router, Route, IndexRoute} from 'react-router';
import {history} from './redux/store';
import App from './App';

import Home from './modules/home/Home';
import Contact from './modules/contact-us/Contact';
import Collaborate from './modules/collaborate-us/Collaborate';
import Message from './modules/message/Message';
import Error  from './modules/error/Error';
import NotFound from './modules/404/NotFound';

class Routes extends Component{
	withMessage=(<Router history={history}>
			<Route path='/' component={App}>
			<IndexRoute component={Home}></IndexRoute>
			<Route path="/contact" identifier="contact" component={Contact}></Route>
			<Route path="/collaborate" identifier="collaborate" component={Collaborate}></Route>
			<Route path="/message" component={Message}></Route>
			<Route path="/error" component={Error}></Route>
			<Route path="/*" component={NotFound}></Route>
			</Route>
			</Router>)

	withoutMessage=(<Router history={history}>
			<Route path='/' component={App}>
			<IndexRoute component={Home}></IndexRoute>
			<Route path="/contact" identifier="contact" component={Contact}></Route>
			<Route path="/collaborate" identifier="collaborate" component={Collaborate}></Route>	
			<Route path="/*" component={NotFound}></Route>
			</Route>
			</Router>)

		render(){

			return(
			this.messageVisible ? this.withMessage : this.withoutMessage
			);

		}
	}

	export default Routes;
`
My Route page, I hope this will give some Idea

**Comment by chandan7193** [comment]
withMessage=(<Router history={history}>
			<Route path='/' component={App}>
			<IndexRoute component={Home}></IndexRoute>
			<Route path="/contact" identifier="contact" component={Contact}></Route>
			<Route path="/collaborate" identifier="collaborate" component={Collaborate}></Route>
			<Route path="/message" component={Message}></Route>
			<Route path="/error" component={Error}></Route>
			<Route path="/*" component={NotFound}></Route>
			</Route>
			</Router>)

**Comment by erikras** [comment]
This is not about this library.
