### ISSUE TITLE
Clarify documentation for reducing redux-form size

### ISSUE THREAD

**Issue by moimael** [erikras/redux-form#2908]
Hi,

I'm trying the new recommended way to shrink redux form 6.7.0 size according to the documentation.

It works except for actions. It complains that there is no default export.

`334:22-29 "export 'default' (imported as 'actions') was not found in 'redux-form/es/actions'`

I'm using the babel plugin.

Thanks !

**Comment by umidbekkarimov** [comment]
Thats right, it should be:
```js
import * as actions from 'redux-form/es/actions';
```

**Comment by moimael** [comment]
Yes that makes a lot more sense, thank you :)

**Comment by umidbekkarimov** [comment]
Also you should be able to import like that:

```js
import { change, destroy } from 'redux-form/es/actions';
```

But i'm not sure how plugin will handle it, i'm using webpack 2 and it's doing its job with tree shaking without issues.

**Comment by moimael** [comment]
Ah that might be an even better solution, I'll try it out. Thanks !
