### ISSUE TITLE
"Unhandled promise rejection" only in 3.0.9 

### ISSUE THREAD

**Issue by approots** [erikras/redux-form#291]
My "submitHandler" returns a rejected Promise when the server responds with an error due to an invalid field. When this happens, I see this error in the console "Unhandled promise rejection". I'm still able to display the error message in my form though. The console error doesn't occur in 3.0.8.

Maybe I'm not handling the Promise correctly? Here's my submit handler:

    handleSubmit(values) {
        const postData = {method: 'post',body: {...values}};

        return new Promise((resolve, reject) => {
            return fetch.json('/api/signup', postData)
                .then((json) => {
                    return resolve();
                })
                .catch((error) => {
                    switch (error.json.message) {
                        case 'signup_code_not_exists' :
                            return reject({signupCode: 'The code does not exist'});
                        default :
                            return reject({_error: 'Error'});
                    }
                });
        });
    },

This is the exact error I see:

    Unhandled promise rejection Object {signupCode: "The code does not exist"}

The error occurs in the Babel es6.promise.js file.

**Comment by erikras** [comment]
Aha! _That's why_! https://github.com/erikras/redux-form/issues/256#issuecomment-157192563

**Comment by erikras** [comment]
Fixed in `v3.0.10`.

**Comment by approots** [comment]
Thanks!

**Comment by ntdb** [comment]
@approots @erikras Just found this after a half hour of confusion. Thank you! :+1:

**Comment by oyeanuj** [comment]
@ntdb @approots Did upgrading it resolve it for you? I have run into a similar problem but can't seem to resolve it.

**Comment by rkbrewer** [comment]
Just FYI @oyeanuj, I'm using Babel Polyfill 6.3.14 and saw the Error until I chained a catch with an actual function parameter in it (solving exactly what the error was complaining I wasn't doing).

Just my 2 cents, but I'd rather this come across as a Warning in the console than an Error.

**Comment by erikras** [comment]
You guys might be interested in [`v5.1.0`](https://github.com/erikras/redux-form/releases/tag/v5.1.0).
