### ISSUE TITLE
Documentation page for 5.3.3 spins forever w/out render

### ISSUE THREAD

**Issue by rnicholus** [erikras/redux-form#2916]
### Are you submitting a **bug report** or a **feature request**?
bug

### What is the current behavior?
spinner

### What is the expected behavior?
docs

### Sandbox Link
http://redux-form.com/5.3.3/

### What's your environment?
Chrome - MacOS

### Other information
<img width="1220" alt="screen shot 2017-05-11 at 12 07 18 pm" src="https://cloud.githubusercontent.com/assets/593312/25962188/6b83e52e-3642-11e7-8301-4f3adaeb319b.png">

**Comment by xiankai** [comment]
Seems like this is related to #2824.

https://github.com/erikras/redux-form/blob/gh-pages/5.3.3/package.json#L56

Can we upgrade the v5 branch to use 5.3.6 instead of 5.3.5?

**Comment by rnicholus** [comment]
Is there any way I can help out here? Docs have been down for a month now.

**Comment by rnicholus** [comment]
Almost 3 months later, docs are _still_ broken. Can someone at least respond to this?

**Comment by erikras** [comment]
Hmm.. I've been trying to remember how I used to generate those docs....

[45 minutes later]

Okay, I've published [`v5.3.6` docs](https://redux-form.com/5.3.6/). That should satisfy you `v5`ers, right?
