### ISSUE TITLE
Using react-bootstrap with React-Form

### ISSUE THREAD

**Issue by DrYSG** [erikras/redux-form#2917]
am trying to use "redux-form": "^6.7.0" with "react-bootstrap": "^0.31.0"

I have added the Field to the form as follows:

```
    class Config extends Component {
        render() {
            const { ServerPort, UserID, PortNumber, WWWUrl, SourcePath, FMEPath, pickFile, pickFolder, handleSubmit } = this.props;
            return (
                <Form horizontal onSubmit={handleSubmit}>
                    <FormGroup controlId="serverPortBox">
                        <Col componentClass={ControlLabel} sm={2}>Watson Port:</Col>
                        <Col sm={10}>
                            <OverlayTrigger placement="left" overlay={(<Tooltip id="tt1">TCP port for Watson to use</Tooltip>)}>
                                <Field name="WatsonPort" component={FormControl}
                                    type="number" min="1024" max="65535" placeholder={ServerPort} />
                            </OverlayTrigger>
                        </Col>
                    </FormGroup>
```

but I am getting the warning:
```
    Warning: Unknown props `input`, `meta` on <input> tag. Remove these props from the element. 
        in input (created by FormControl)
        in FormControl (created by ConnectedField)
        in ConnectedField (created by Connect(ConnectedField))
        in Connect(ConnectedField) (created by Field)
```

If I change the Field to not use an JS Object for the component, I do not get the warning, but I also do not see the FormControl appearing.

```
    <Field name="WatsonPort" component="FormControl" type="number" min="1024" max="65535" placeholder={ServerPort} />
```

**Comment by DrYSG** [comment]
The reason tried changing {FormControl} to "FormControl" was https://github.com/erikras/redux-form/issues/1249 but it did not seem to help.

**Comment by DrYSG** [comment]
Oh, this is a great mystery. I followed the advice in https://github.com/react-bootstrap/react-bootstrap/issues/2210 and both the warning about additional props and the empty submit stopped.

and this works, except for one odd thing. When the mouse enters the field the first time, and the field gets selected, then I can press one key, and then field looses the selected state. If I reselect, and continue typing it works fine. It is only the first key press that causes the loss of "selected" or is it focus? 


**Update**
and then I tried converting the component to a stateless functional component, and moved the FieldInput of there, and put it in as an independent SFC. And now it select and focus work fine.

Go figure.

```
        const FieldInput = ({ input, meta, type, placeholder, min, max }) => {
            return (
                <FormControl
                    type={type}
                    placeholder={placeholder}
                    min={min}
                    max={max}
                    value={input.value}
                    onChange={input.onChange} />
            )
        }
```

and I invoke it like this:

```
<Field name="ServerPort" type='number' component={FieldInput} placeholder={ServerPort} min="1024" max="65535" />
```


see also: https://github.com/erikras/redux-form/issues/1750

**Comment by szerintedmi** [comment]
Minor question for @DrYSG 's solution . 
Would it make sense to add Field name prop as id to the Component? Like:

```
const FieldInput = ({ input, meta, type, placeholder, min, max}) => {
    return (
        <FormControl
            id={input.name}
            type={type}
            placeholder={placeholder}
            min={min}
            max={max}
            value={input.value}
            onChange={input.onChange} />
    )
}
```
(with react-forms 7.03 & react-bootstrap 0.31.1)

**Comment by DrYSG** [comment]
@szerintedmi  I got pulled into a different project, and don't plan to be using react for a while. So I can't really respond to this since my mind is elsewhere.

**Comment by rafkhan-wg** [comment]
@DrYSG your solution worked for me, thanks! :)
