### ISSUE TITLE
How to know the form is dirty or not outside?

### ISSUE THREAD

**Issue by leozdgao** [erikras/redux-form#292]
Here is my code:

```javascript
// A container component
@connect(
  ({ post }) => ({ post })
)
@reactMixin.decorate(Lifecycle)
@reactMixin.decorate(autobind([ 'routerWillLeave' ]))
class NewPost extends Component {
  routerWillLeave () { // react router lifecycle
    const isDirty = this.refs.form.isDirty
    ...
    return !isDirty
  }

  render () {
    ...
    return (
      // render my form here with a refs
    )
  }
}
```

```javascript
// form HOC
@reduxForm({
  form: 'editPost',
  fields: [ 'title', 'tags', 'content' ],
  validate: (values) => {
    const errors = {}

    if (!values.title) errors.title = 'It is required.'
    if (!values.content) errors.content = 'It is required.'

    return errors
  },
  touchOnBlur: false
})
class EditPostForm extends Component {
  get isDirty () {
    return this.props.dirty
  }

  ...
}
```

Since HOC actually return a new Class, my custom property `isDirty` could not be invoked. I check the state in redux store, and could not find a value to represent the form dirty or not. 

So I try to plug it in:

```javascript
const editPostActionMap = {
  "redux-form/CHANGE" ( state, action ) {
    return {
      ...state,
      isDirty: true
    }
  }
}
```

Is there a more official way or I just miss something?

**Comment by erikras** [comment]
No, there is no more official way. The best/only way is to `reduxForm()` decorate whatever other component – presumably a submit button? – with the same form name and use the prop it is given.

**Comment by leozdgao** [comment]
@erikras I am curious about the performance. If we decorate a component which already contains a decorated component, every time we change the value of input, will there be redundant calculation for react to spread state to wrapped component? Because these two component always be mounted at the same time, I mean it may need do the spead thing twice?

**Comment by erikras** [comment]
Something similar is being done to display the `Values` section in [the examples](http://erikras.github.io/redux-form/#/examples/simple). The performance seems pretty good. And it will be even better in production where the `redux-devtools` are disabled (they are enabled on the examples site).
