### ISSUE TITLE
How set value to Field?

### ISSUE THREAD

**Issue by borm** [erikras/redux-form#2930]
Subj, 

I am try add value property to Field, but input value is empty
I am try add defaultValue property, but see react error by controlled and uncontrolled component
```jsx
const Form = () => (
  <Field name='firstName' component='input' value="test" />
)
```

[demo not worked](https://jsfiddle.net/75rh036o/22/)

**Comment by gustavohenke** [comment]
http://redux-form.com/6.7.0/examples/initializeFromState/
http://redux-form.com/6.7.0/docs/api/ReduxForm.md/#-initialvalues-object-string-string-optional-

**Comment by borm** [comment]
I am need paste value from route params, i am do not can use state or initialStates
