### ISSUE TITLE
How set value to Field?#2

### ISSUE THREAD

**Issue by borm** [erikras/redux-form#2931]
https://github.com/erikras/redux-form/issues/2930

I am need paste value from route params, i am do not can use state or initialStates, why i must use reducer?

I want paste value as prop value, why i do not can do it?

P.S. It is not good to close a issue without asking helped me or not

**Comment by gustavohenke** [comment]
You don't need to use a reducer. You can build your `initialValues` option however you want.

P.S.: Thanks for using Redux Form, but here is not the place to ask questions. You should have read the issue template before posting your issue.
