### ISSUE TITLE
Not correct example on site

### ISSUE THREAD

**Issue by borm** [erikras/redux-form#2933]
Subj,

http://redux-form.com/6.0.0-alpha.4/examples/submitValidation/

in SubmitValidationForm.js you are missing 
```
import submit from 'submit';
```

and it to 
```html
<form onSubmit={handleSubmit}>
```

**Comment by gustavohenke** [comment]
This is a very old doc page for an unstable version of Redux Form.

If you think something is unclear in newer docs (eg v6.3.0 onwards), please let us know by opening a new issue (or even better, open a PR directly!).
