### ISSUE TITLE
Type definition for 'getFormNames' selector is incorrect

### ISSUE THREAD

**Issue by TAGC** [erikras/redux-form#2937]
### Are you submitting a **bug report** or a **feature request**?

Bug report.

### What is the current behavior?

Trying to use `getFormState` as described [in the docs](http://redux-form.com/6.7.0/docs/api/Selectors.md/) results in Typescript compiler error TS2346 ("Supplied parameters do not match any signature of call target"):

```js
const state = yield select();
const formNames: string[] = getFormNames()(state);
```

Suppressing these errors and running this code anyway works as expected.

### What is the expected behavior?

The Typescript compiler should flag up no warnings or errors for the code presented above.

### What's your environment?

- Redux Form 6.7.0
- Windows 7 64-bit
- Typescript 2.3.2
- Electron 1.6.8
  - Node: >=7.4.0
  - Chromium: >=56.0.2924.87
  - V8: >=5.6.326.50

### Other information

The source of this error is this incorrect type definition at `@types/redux-form/lib/selectors.d.ts`:

```js
/**
 * Gets the names of all the forms currently managed by Redux-Form.
 *
 * The reason that this is a function that returns a function is twofold:
 *   1. symmetry with the other selectors
 *   2. to allow for the getFormState parameter described at the top of this page.
 *
 * If you are using ImmutableJS, it will return a List.
 */
export const getFormNames: <State>(state: State) => string[];
```

This issue may relate to #2650.

**Comment by gustavohenke** [comment]
`@types/redux-form` is maintained by DefinitelyTyped, so unfortunately, there's nothing we can do at the moment.

P.S.: It would be amazing to have it maintained on our side (see #1211), because TypeScript is the most well-adopted typing variation of JS.
