### ISSUE TITLE
submit values to dispatch

### ISSUE THREAD

**Issue by mynameisbams** [erikras/redux-form#2942]
whats wrong wit my code? i want pass the submit values, it give me error 'undefined is not a function (evaluating '_this.onLogin(values)')'

    import React from 'react'
    import {
        StyleSheet,
        Text,
        TextInput,
        TouchableOpacity,
        View
    } from 'react-native'
    import { Field, reduxForm } from 'redux-form'
    import { login } from './action'

    import { connect,  } from 'react-redux'

    const submit = values => {
        //login: ()=> login(values.email)
        this.onLogin(values);
        console.log('submitting form', values)
    }

    const renderInput = ({ input: { onChange, ...restInput }}) => {
        return <TextInput style={styles.input} onChangeText={onChange} {...restInput} />
    }

    const Form = props => {
        const { handleSubmit } = props

        return (
            <View style={styles.container}>
                <Text>Email:</Text>
                <Field name="email" component={renderInput} />
                    <TouchableOpacity onPress={handleSubmit(submit)}>
                        <Text style={styles.button}>Submit</Text>
                    </TouchableOpacity>
            </View>
        )
    }
    const myReduxForm = reduxForm({
        form: 'MyReduxForm', // required by reduxForm()
        //warn: (values, pFormrops) => { ... }, // optional
        //error: (values, props) => { ... } // optional
    })(Form)
    export default connect(
        state => ({
            user: state.user
            // optional. grab values to fill the form from somewhere.
            //initialValues: state.foo.bar
        }),
        dispatch => ({
            onLogin: (email) => { dispatch(login(email)); },

            //submit:(values) => {dispatch(login(values))}

            // reduxForm() expects the component to have an onSubmit
            // prop. You could also pass this from a parent component.
            // I want to dispatch a redux action.
            //onSubmit: data => dispatch(myActionToDoStuff(data))
        })
    )(myReduxForm)
    // export default reduxForm({
    //     form: 'test'
    // })(Form)
    // export default reduxForm({
    //     form: 'test'
    // })(Form)

    const styles = StyleSheet.create({
        button: {
            backgroundColor: 'blue',
            color: 'white',
            height: 30,
            lineHeight: 30,
            marginTop: 10,
            textAlign: 'center',
            width: 250
        },
        container: {

        },
        input: {
            borderColor: 'black',
            borderWidth: 1,
            height: 37,
            width: 250
        }
    })

**Comment by gustavohenke** [comment]
You're trying to use it from the wrong place. It should be `this.props.onLogin`, no `this.onLogin`.

Thanks for using Redux Form! In the future please ask questions like this on StackOverflow.

**Comment by saturito** [comment]
hi @gustavohenke I have a similar case, I am trying to print the values, but it only prints an object without properties
