### ISSUE TITLE
how to get notified if remote submit finished

### ISSUE THREAD

**Issue by mtiger2k** [erikras/redux-form#2946]
I want to do something after the remote submit finished.
I get the submit form redux-form, and dispatch(submit(formName)).

How can I achieve it?
thanks.

**Comment by gustavohenke** [comment]
Some options:
1. Dispatch an action of yours from within your remote submit function
2. Use `componentWillReceiveProps` method, and check whether `submitting` changed from `true` to `false`

In the future, please ask questions at StackOverflow, as our GitHub issue tracker is better suited for bug reporting and feature requests.
