### ISSUE TITLE
resetFrom does not function with textarea

### ISSUE THREAD

**Issue by Amdingo** [erikras/redux-form#295]
Example can be seen in the Simple Form @ http://erikras.github.io/redux-form/#/examples/simple?_k=cfv3n7

**Comment by erikras** [comment]
Thanks for that! This has been a long-running complication. See #145 and https://github.com/facebook/react/issues/2533.

Fixed on example now.

**Comment by Amdingo** [comment]
Ha!  Figures I should have tested out a standard textarea outside of redux-form first...thanks sir.
