### ISSUE TITLE
Bug: STOP_ASYNC_VALIDATION erases previous asyncErrors if currently blurred field passes validation

### ISSUE THREAD

**Issue by davedx** [erikras/redux-form#2953]
### Are you submitting a **bug report** or a **feature request**?

Bug report

### What is the current behavior?

1. Build a form with two inputs with asyncValidation
2. Invalid one of the inputs
3. Enter something in the second input that is valid (causes no errors)
4. STOP_ASYNC_VALIDATION does this: result = deleteIn(result, 'asyncErrors') https://github.com/erikras/redux-form/blob/master/src/createReducer.js#L341

### What is the expected behavior?

asyncErrors still contains the error from the first input so the form can continue showing this field is invalid.

### What's your environment?

Redux Form 6.6.3

### Other information

I'm opening this as a bug report to start a discussion to at least confirm this behaviour is a bug. If so I'm happy to help work on a PR to fix it once I understand it properly. Is asyncErrors *supposed* to be state shared between fields like this?

**Comment by nktssh** [comment]
Any updates on this?

**Comment by davedx** [comment]
Funny you should ask, I just made a PR. Looking forward to feedback.

**Comment by nktssh** [comment]
@davedx you can find workaround for this here: https://github.com/erikras/redux-form/issues/980#issuecomment-278360610

Just merge previous errors and current error (or delete the key, if no errors for current input)

**Comment by erikras** [comment]
Fix published in [`v7.0.0`](https://github.com/erikras/redux-form/releases/tag/v7.0.0).

**Comment by davedx** [comment]
I made a PR that was merged
