### ISSUE TITLE
Submit not called

### ISSUE THREAD

**Issue by DrYSG** [erikras/redux-form#2955]
redux form: 6.7 reudux version 3.6

I made some changes in the form below, and you can see that handleChanges is wrapped with an alert, but that alert is not even getting called when I press submit.  

When I inspect with Redux-tools I see the values on form.configuration.values are changing, and all seems correct, but why is the submit not getting called?

The onClick hack on the SUBMIT button is the only way I can get the values. I can remove it and then the form will never submit!

I have removed a lot of the fields, to simplify the issue.
**Configuration.jsx**
```
const { remote } = require('electron')
import React, { Component } from 'react'
import { Field, reduxForm, reset } from 'redux-form'
import { connect } from 'react-redux'
import { Form, FormControl, FormGroup, ControlLabel, Col, Button, Tooltip, OverlayTrigger } from 'react-bootstrap'
import * as Act from '../dash/actions.js'
import FaFolderOpen from 'react-icons/lib/fa/folder-open'
import { FieldInput, FolderFieldInput } from "./FieldInputs.js"


const Config = ({ 
    SourcePath,
    FMEPath,
    pickFile,
    pickFolder,
    handleSubmit,
    doSubmit,
    resetForm,
    isUpdating,
    ...props }) => {
    COMPONENTS["Configuration"] = props // Register this component in the Dash Components list (so we can get the change() function)
    return (
        <Form horizontal onSubmit={(e) => {alert('foobar'); handleSubmit(doSubmit)}}>
            <FieldInput
                cid="serverPortBox"
                nameString="ServerPort"
                label="Watson Port:"
                valid={null}
                type="number"
                min="0"
                max="1024"
                tip="TCP Port for Watson to use"
            />
            <FieldInput
                cid="userIDBox"
                nameString="UserID"
                label="Database User ID:"
                valid={null}
                type="text"
                tip="User ID for PostgreSQL DB"
            />
            <FormGroup>
                <OverlayTrigger placement="bottom" overlay={(<Tooltip id="tt8">Write Configuration file with new form values</Tooltip>)}>
                    <Button
                        type="submit"
                        onClick={(e) => {doSubmit(STORE.getState().form.configuration.values)}}
                        disabled={isUpdating}
                        bsStyle="primary"
                        block>{isUpdating ? 'Updating...' : 'Update Configuration'}
                    </Button>
                </OverlayTrigger>
            </FormGroup>
            <FormGroup>
                <OverlayTrigger placement="bottom" overlay={(<Tooltip id="tt8">Restore form to original settings</Tooltip>)}>
                    <Button type="button" bsStyle="success" block onClick={(e) => resetForm(e)}>Reset Configuration</Button>
                </OverlayTrigger>
            </FormGroup>
        </Form>
    )
}

const mapDispatchToProps = (dispatch, ownProps) => {
    return {
        doSubmit: (config) => {
            dispatch(Act.writeConfig(config))
            return null // no errors with submit
        },
        resetForm: (e) => {
            e.preventDefault()
            dispatch(reset('configuration'))
        }
    }
}

const mapStateToProps = (state) => {
    return {
        ServerPort: state.ServerConfig.ServerPort,
        UserID: state.ServerConfig.UserID,
        PortNumber: state.ServerConfig.PortNumber,
        WWWUrl: state.ServerConfig.WWWUrl,
        SourcePath: state.ServerConfig.SourcePath,
        FMEPath: state.ServerConfig.FMEPath,
        isUpdating: state.UX.isUpdating
    }
}

//  initialConfig = remote.getGlobal('DASH').config

let config = remote.getGlobal('DASH').config

const CForm = reduxForm({
    form: 'configuration', // a unique nameString for this form
    initialValues: config
})(Config);
const Configuration = connect(mapStateToProps, mapDispatchToProps)(CForm)

export default Configuration
```

**FieldInput.jsx**

```
import React from 'react'
import { Field, reduxForm, reset } from 'redux-form'
import { Form, FormControl, FormGroup, ControlLabel, Col, Button, Tooltip, OverlayTrigger, Glyphicon, InputGroup } from 'react-bootstrap'
import FaFolderOpen from 'react-icons/lib/fa/folder-open'

const FieldControl = ({ input, meta, type, placeholder, min, max, tip, cid }) => {
    return (
        <OverlayTrigger placement="left" overlay={(<Tooltip id={cid + "-tip"}>{tip}</Tooltip>)}>
            <FormControl
                type={type}
                placeholder={placeholder}
                min={min}
                max={max}
                value={input.value}
                onChange={input.onChange} />
        </OverlayTrigger>
    )
}

export const FieldInput = ({ cid, nameString, valid, label, type, placeholder, min, max, tip }) => {
    return (
        <FormGroup controlId={cid} validationState={valid}>
            <Col xs={2}>
                <ControlLabel>{label}</ControlLabel>
            </Col>
            <Col xs={10}>
                <Field name={nameString} type={type}
                    label={label} tip={tip}
                    min={min} max={max}
                    component={FieldControl} placeholder={placeholder} />
            </Col>
        </FormGroup>
    )
}

export const FolderFieldInput = ({ cid, nameString, valid, label, type, placeholder, min, max, tip, action }) => {
    return (
        <FormGroup controlId={cid} validationState={valid}>
            <Col xs={2}>
                <ControlLabel>{label}</ControlLabel>
            </Col>
            <Col xs={10}>
                <InputGroup >
                    <InputGroup.Addon className="hoverButton">
                        <FaFolderOpen size={18} onClick={action} />
                    </InputGroup.Addon>
                    <Field name={nameString}
                        type={type}
                        label={label} tip={tip}
                        min={min} max={max}
                        component={FieldControl} placeholder={placeholder} />
                </InputGroup>
            </Col>
        </FormGroup>

    )
}

```

**Comment by DrYSG** [comment]
in the screen shot below, You can see I changed the ServerPort value from the initial, but the submit button is firing handleSubmit()

![image](https://cloud.githubusercontent.com/assets/2865368/26373369/451e4348-3fcf-11e7-8f4a-86aecc29950f.png)

**Comment by tstirrat15** [comment]
If your `doSubmit` function is the one that is doing all of the handling of transforming values and submitting them to the backend, the easier way to do this is to pass `onSubmit={handleSubmit}` to your `Form` element, and pass `onSubmit: doSubmit` as part of your `reduxForm` configuration object. Redux-form will take care of making sure that `doSubmit` is called.

This is something that I also find confusing about redux-form. There's some [reading on the subject](http://redux-form.com/6.7.0/docs/faq/HandleVsOn.md/) if you're interested.

Also, heads up, for these kinds of questions, [the Discord channel](https://discordapp.com/channels/102860784329052160/105736485537374208) is a better place to get answers than opening an issue here.

**Comment by DrYSG** [comment]
Thank you @tstirrat15 

The reason for not passing the doSubmit from the above as part of the reduxForm config infomation was I wanted to encapsulate all issues about form submittal in the configuration.jsx object. The higher level containers don't know about doSubmit() which is defined as a mapDispatchToProps contained int he configuration.jsx. Hence I found the handleSubmit( ...) to be useful. I think what I need to do is create a CodePen to show you what is happening. As I hinted, this was working until i factored out the InputField.jsx to its own file. Go figure. Also, I do get the handleSubmit() to fire if I change the *name* property in the <FIeld > object. I.e. If instead of ServerPort as the name for the field. I set it to ServerPort1, then I do get to see the doSubmit call. Of course, this breaks other things, since I am now adding new values to the form every time I change things.

We have firewall issues with the discordapp. I cannot get there.

**Comment by tstirrat15** [comment]
Mmm. That's annoying about discord.

`doSubmit` doesn't need to be in mapDispatchToProps in most cases - the args passed to the `onSubmit` function are `(values, dispatch, props)`. You can put your action creators in there, outside of the component, and pass it to the `reduxForm` configuration object within the same file.

I can't speak to why it worked before you refactored nor why changing the name would have any effect, at least off the top of my head.

**Comment by DrYSG** [comment]
*SIGH*, Well I created a pen, and copied some of my code into it. The issue is now that it is all in one "file" it is working. Is there anything about the way I factored the FieldInput into a seperate file, that caused this failure. Because before I did that, it was also working.

CodePen: https://codepen.io/DrYSG/pen/YVggEW?editors=1111

**Comment by danielrob** [comment]
@DrYSG any reason to believe this was a redux-form issue in the end vs an application error?
