### ISSUE TITLE
reduxForm() Instance API

### ISSUE THREAD

**Issue by KnightOfHell** [erikras/redux-form#2957]
How can I access instance properties from another componets?

**Comment by tstirrat15** [comment]
You use [selectors](http://redux-form.com/6.7.0/docs/api/Selectors.md/) and [action creators](http://redux-form.com/6.7.0/docs/api/ActionCreators.md/).

Also, heads up, there's a [Discord channel](https://discordapp.com/channels/102860784329052160/105736485537374208) for these sorts of questions.
