### ISSUE TITLE
Double dispatch START_ASYNC_VALIDATION

### ISSUE THREAD

**Issue by nfort** [erikras/redux-form#2959]
### Are you submitting a **bug report** or a **feature request**?
bug report

### What is the current behavior?

1. Open [Redux Form - Async Blur Validation Example](http://redux-form.com/6.7.0/examples/asyncValidation/)
2. Enter value into field **Password**
3. Enter **paul** into field **Username**
4. Press Enter or click button "Submit"

Actions

```
@@redux-form/START_ASYNC_VALIDATION
@@redux-form/BLUR
@@redux-form/START_ASYNC_VALIDATION
@@redux-form/STOP_ASYNC_VALIDATION
@@redux-form/SET_SUBMIT_FAILED
@@redux-form/STOP_ASYNC_VALIDATION
```

Console

```
Uncaught (in promise) Object {username: "That username is taken"}
```

### What's your environment?

Redux Form version 6.7.0
Chrome with extension Redux Dev Tools

**Comment by Viral-Inc** [comment]
+1

**Comment by danielrob** [comment]
Thanks for the report. The uncaught submission error is a duplicate of #1297, and the 'double dispatch' is intended behaviour - once for the onBlur of the username field, and once as a pre-submit validation. This is covered [in the docs](http://redux-form.com/7.0.3/examples/asyncValidation/) as the first Important item. Does that explain things?

**Comment by nfort** [comment]
@danielrob 
Yeah, sure. Thank you
