### ISSUE TITLE
initial values taking last value 

### ISSUE THREAD

**Issue by gmchaturvedi1** [erikras/redux-form#2962]
Dear All,

i just initalize my redux form value in wizard through state and then different methods in issue.but when i initialize the value only last value is initialized only. kindly suggest where is my problme:

```js
const mapStateToProps=(state)=>{
 console.log(state)
  const { showResult,grading,certificate } = selector(state, 'showResult', 'grading','certificate')
  return{
    showResult,grading,certificate,initialValues:{
       displayResult:'Do Not Disclose',
       displaySolution:'No'
    }
  }
}
```

regards
gmchaturvedi

**Comment by gustavohenke** [comment]
Thanks for using Redux Form, but this is not the place to ask questions. Please migrate it to StackOverflow, as the GitHub issue tracker is better suited for bug reports and feature requests.
