### ISSUE TITLE
why handleSubmit value undefined?

### ISSUE THREAD

**Issue by mynameisbams** [erikras/redux-form#2963]
whats wrong with my code? its always give me error " undefined is not a function (evaluating 'handleSubmit(submit())' "

     import React, { PropTypes } from 'react';
     import {Button, StyleSheet, Text, View, TextInput, TouchableOpacity} from 'react-native';
     import { Field, reduxForm } from 'redux-form'

     const submit = values =>{
          console.log(values)
     }
     const renderInput = ({ input: { onChange, ...restInput }}) => {
         return <TextInput onChangeText={onChange} {...restInput} />
     }
     const XXX = props =>{
         const { handleSubmit } =  props
         console.log("value",handleSubmit);
         return(

         <View>
             <Text>Email:</Text>
             <Field name="email" component={renderInput} />
             <TouchableOpacity onPress={handleSubmit(submit)}>
                 <Text style={styles.button}>Submit</Text>
             </TouchableOpacity>
         </View>
     )}

     const LoginScreen = ({ navigation }) =>{

         //const { handleSubmit } =  props

         return(
         <View style={styles.container}>
             <XXX/>

             <Text style={styles.welcome}>
                 Screen A
             </Text>
             <Text style={styles.instructions}>
                 This is great
             </Text>
             <Button
                 onPress={() => navigation.dispatch({ type: 'Login' })}
                 title="Log in"
             />
         </View>
     )};

     LoginScreen.propTypes = {
         navigation: PropTypes.object.isRequired,
     };

     LoginScreen.navigationOptions = {
         title: 'Log In',
     };

     export default reduxForm({
         form: 'signIn'
     })(LoginScreen);

**Comment by gustavohenke** [comment]
`handleSubmit` is a function provided by Redux Form to the wrapped component.
You're only wrapping `LoginScreen`, therefore it's available there, but not inside `XXX`.

Now you have 2 options: either wrap `XXX` with `reduxForm`, or pass the desired props to `XXX` when using it.

In the case of choosing the 2nd option, you would do the following:

```js
<XXX {...props} />
```

Hope this helps you.
Thanks for using Redux Form! In the future, please ask questions on StackOverflow, as the issue tracker is better suited for bug reports and feature requests.
