### ISSUE TITLE
error on latest CRNA with Expo 17

### ISSUE THREAD

**Issue by kevinfez** [erikras/redux-form#2965]
### Are you submitting a **bug report** or a **feature request**?
bug report

### What is the current behavior?
![img_3940](https://cloud.githubusercontent.com/assets/7257376/26474369/7ce038ee-4165-11e7-8496-aca6b6e9c8b0.PNG)

### What is the expected behavior?
Support for react-native when using create-react-native-app (CRNA) and [expo 17](https://blog.expo.io/expo-sdk-v17-0-0-is-now-available-2c4f13362816).
(this was working, but after the recent expo update it is no longer working)

### Sandbox Link
[crna-redux-form.zip](https://github.com/erikras/redux-form/files/1030443/crna-redux-form.zip)
I ran create-react-native-app, added redux, redux-form, immutable, react-navigation, wrote a component and wrapped it with reduxForm and ran the project using exp.
To run the project just extract it wherever and run
```yarn install && exp r -c```

### What's your environment?
"expo": "^17.0.0",
"react": "16.0.0-alpha.6", **<- probably the most important one, doesn't have the ```^``` or ```~```**
"react-native": "https://github.com/expo/react-native/archive/sdk-17.0.0.tar.gz",
"react-navigation": "^1.0.0-beta.11",
"react-redux": "^5.0.5",
"redux": "^3.6.0",
"redux-form": "^6.7.0",
"redux-immutable": "^4.0.0",

exp 41.0.0
node v7.10.0

### Other information
[stacktrace.txt](https://github.com/erikras/redux-form/files/1030476/stacktrace.txt)

Like I mentioned above, this was working before I updated to expo 17, unfortunately it doesn't seem easy to go back to 16, something must be cached somewhere that's being tough to clear... would be great if this can be resolved on 17 though instead of having to rollback, hopefully it's something simple!

I also thought that perhaps react-navigation was having issue with reduxForm being the top-level component for the screen but even exporting a non-wrapped component as the route's screen and having a separate reduxForm component nested in its render was unsuccessful.

**Comment by EQuimper** [comment]
+1 get that me too

**Comment by sargant** [comment]
I've been having the exact same problem with CRNA. However, I've noticed that is is _not_ a problem when using Expo 17 directly, even though it uses `react 16.0.0-alpha.6`.

This code works fine:

```
import Expo from 'expo';
import React from 'react';
import { Text, TextInput, View } from 'react-native';
import { Field, reduxForm, reducer as formReducer } from 'redux-form'
import { createStore, combineReducers } from 'redux'
import { Provider } from 'react-redux'

const Form = () =>
  <View style={{ flex: 1, paddingTop: 100 }}>
    <Field
      name="testField"
      component={({ input: { onChange, value } }) =>
        <TextInput onChangeText={onChange} value={value} style={{ height: 30 }} />
      }
    />
  </View>

const store = createStore(combineReducers({ form: formReducer }), {})
const WrappedForm = reduxForm({ form: 'testForm' })(Form)

const App = () =>
  <Provider store={store}>
    <WrappedForm initialValues={{ testField: 'Hello world' }} />
  </Provider>

Expo.registerRootComponent(App);
```

and this is the `package.json` dependencies:

```
"expo": "17.0.0",
"react": "16.0.0-alpha.6",
"react-native": "https://github.com/expo/react-native/archive/sdk-17.0.0.tar.gz",
"react-redux": "^5.0.5",
"redux": "^3.6.0",
"redux-form": "^6.7.0"
```

**Comment by sargant** [comment]
Actually, on further investigation, the problem seems to be when I add 'react-navigation' to the mix, so there's some combination of 'redux-form',  'expo', and 'react-navigation' that isn't playing nicely.

Version being used:
* `react-navigation@1.0.0-beta.11`
* `expo@17.0.0`
* `redux-form@6.7.0`

**Comment by stevenyap** [comment]
I have the same problem and even though I removed `react-navigation`, I am still getting this error.

**Comment by stevenyap** [comment]
The main issue is that when I installed redux-form via `yarn add redux-form`, a copy of react is installed in `node_modules/redux-form/node_modules/react` which is very weird. This extra copy of react causes the multiple copies of react issue.

I have managed to isolate issue to:
```
// package.json
{
  "name": "clean",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "react-native-scripts": "0.0.30"
  },
  "dependencies": {
    "react": "16.0.0-alpha.6",
    "redux-form": "^6.7.0"
  }
}
```

Note that we need both `react-native-scripts` and `react` to reproduce this which is present in expo. I am running this on MacOS.

Interestingly, `npm install` does not create an additional react copy but `yarn add` does.
Is this an issue of redux-form or expo/react/react-native-scripts or yarn?

For now, the simply workaround is to delete the folder `node_modules/redux-form/node_modules`.

**Comment by stevenyap** [comment]
Actually this is related to #2842

**Comment by kevinfez** [comment]
thanks @stevenyap 
The workaround you said and referenced in #2842 works

**Comment by kevinfez** [comment]
I'm closing this issue since it seems to be directly tied to #2842 and not the other integration points covered here; thanks everyone!

**Comment by OKNoah** [comment]
Also noticed `react-navigation` loses the ability to have titles when `reduxForm` is used. Remove `reduxForm` and the title works, but with it, it doesn't.
