### ISSUE TITLE
unregister and RE-register a field keeps the value but clears the validation status

### ISSUE THREAD

**Issue by kromit** [erikras/redux-form#2966]
Bug report

Rendering of one `FieldArray` objects. (i.e Accordion widget)
When on object is displayed only its fields are registered. During the switch to another object the fields are unregistered and the new ones are registered. When we switch back, the values of the previous object are still there but the validation status is gone.

The validation status should not be modified when the value is not modified.

redux-form 6.7.0

**Comment by kromit** [comment]
This seems to be a general problem and not only in `FieldArray`:

I.e.: When some parent DOM elements are added and or removed, all form fields within this element are getting unregistered and registered again. This causes them to loose the validation status and all error messages.

**Comment by kromit** [comment]
this seems to be duplicated/related to #2979 and #2999

**Comment by danielrob** [comment]
@kromit #2979 is now closed as resolved due to [this PR](https://github.com/erikras/redux-form/pull/3064). Can you confirm if this is now resolved?

**Comment by kromit** [comment]
looks good
