### ISSUE TITLE
Add `anyFocused` prop to form

### ISSUE THREAD

**Issue by petrgazarov** [erikras/redux-form#2970]
### Feature request

Thanks so much for the work, the library is solid and really convenient in many use cases.

I have a use case when I need to know if a user has interacted with the form.
This helps implement animations inside of the form, that should be triggered by user interactions, and not on page load.

A part of my form:
```
      <form>
        <ToggleField
          {...fields.name}
        />
        <TransitionGroup>
          {
            hasName
            ? (
              <SlideDownAndUp>
                <TextField
                  {...fields.email}
                />
              </SlideDownAndUp>
            )
            : null
          }
        </TransitionGroup>
        // ...etc
```

Where:
- `hasName` is a prop obtained via `formValueSelector`
- `TransitionGroup` is from react
- `ToggleField`, `TextField` are just wrappers that delegate to `Field`
- `SlideDownAndUp` is an animations component I wrote, which implements `TransitionGroup`'s `componentDidEnter` and `componentWillLeave` to slide itself up and down.
- `fields` each have `name` and `validate` properties

I was _almost_ able to use `anyTouched` prop. However, it only becomes true after any one Field is blurred, which doesn't work with the first field interaction and works for all consecutive field interactions.

An example of my code with this usage of `anyTouched` was:
```
<SlideDownAndUp playAnimation={ this.props.anyTouched }>
  <TextField
    {...fields.email}
  />
</SlideDownAndUp>
```

After a little poking around, I got a version of my own custom `anyFocused` working, by passing a callback to all fields as `onFocus`, which set state of my form component, so I could use `this.state.anyFocused` and pass it to my animation component.

Am I missing something here or is it not possible to achieve this with redux form so that I don't have to pass callbacks?

**Comment by gustavohenke** [comment]
#2856 wanted to add this feature, but the inherent performance issues raise a red sign.
So, I'm sorry, but this feature will not be available within redux-form again.

> After a little poking around, I got a version of my own custom `anyFocused` working, by passing a callback to all fields as `onFocus`, which set state of my form component, so I could use `this.state.anyFocused` and pass it to my animation component.

This is definitely the way to go for now. 😞

**Comment by gustavohenke** [comment]
Thinking better about it, `anyFocused` would not add many renders.
Do you have thoughts, @erikras?
