### ISSUE TITLE
load is not a function

### ISSUE THREAD

**Issue by cescoferraro** [erikras/redux-form#2972]
load is not a prop on ˆ6.6 http://redux-form.com/6.6.3/docs/api/Props.md/
the example on the website still uses. https://codesandbox.io/s/MQnD536Km

I was expecting the form values to be updated when changing the value from the redux-form whilst using redux-form. `SET_HOME_STORE_ACTION({ add })` I can confirm on the devtools.

I can change them manually with the change prop. Field by field, but I would like to avoid that. 
Is there a way?

### code

```
export const InsertAdd = compose(
    connect((state) => ({
        reduxForm: state.form,
        home: state.home,
        initialValues: state.home.add
    })),
    reduxForm({
        form: "myForm"
    })
)(({ handleSubmit, load, SET_HOME_STORE_ACTION, change, home, pristine, submitting, reset }) => {
    const submit = (form: IAdd) => {
        console.log(form)
    }
    const randomADD = () => {
        const add: IAdd = {
            id: "rj923A",
            confirmed: true,
            paid: true,
            group: 33,
            category: 4562,
            title: "wfjnsdf",
            description: "sjdfmnjsandf",
            uf: 4
        }
        load(add)
        console.log(load)
        console.log(typeof load)
        /* change("title", add.title)*/
        /* change("description", add.description)*/
        /* change("id", add.id)*/
        /* change("uf", add.)*/
        SET_HOME_STORE_ACTION({ add })
    }
```

```
add.form.tsx:35 Uncaught TypeError: load is not a function
    at Object.randomADD [as onClick] (webpack:///./app/home/add.form.tsx?:35:9)
    at EnhancedButton._this.handleClick (webpack:///./~/material-ui/internal/EnhancedButton.js?:146:21)
    at Object.ReactErrorUtils.invokeGuardedCallback (webpack:///./~/react-dom/lib/ReactErrorUtils.js?:69:16)
    at executeDispatch (webpack:///./~/react-dom/lib/EventPluginUtils.js?:85:21)
    at Object.executeDispatchesInOrder (webpack:///./~/react-dom/lib/EventPluginUtils.js?:108:5)
    at executeDispatchesAndRelease (webpack:///./~/react-dom/lib/EventPluginHub.js?:43:22)
    at executeDispatchesAndReleaseTopLevel (webpack:///./~/react-dom/lib/EventPluginHub.js?:54:10)
    at Array.forEach (native)
    at forEachAccumulated (webpack:///./~/react-dom/lib/forEachAccumulated.js?:24:9)
    at Object.processEventQueue (webpack:///./~/react-dom/lib/EventPluginHub.js?:257:7)
```

**Comment by cescoferraro** [comment]
`enableReinitialize: true`solves my problem. But the docs are outdated in this matter

**Comment by gustavohenke** [comment]
I don't get what you're saying here.
- Where is `load` not a function? The code sandbox link you provided works.
- http://redux-form.com/6.6.3/examples/initializeFromState/ explicitly talks about using `enableReinitialize`

If you could get express yourself better, then perhaps I can help you.

**Comment by cescoferraro** [comment]
@gustavohenke 

> load is not a prop on ˆ6.6 http://redux-form.com/6.6.3/docs/api/Props.md/

load is not a prop anymore https://github.com/erikras/redux-form/blob/master/src/propTypes.js

> the example on the website still uses. https://codesandbox.io/s/MQnD536Km

but the docs still link to a sandbox that shows the usage of the load function.

> enableReinitialize: true solves my problem. But the docs are outdated in this matter

I dont have any issues anymore. Just left it open because the docs/website is out of sync with the lastest version of redux-form

**Comment by gustavohenke** [comment]
`load` was never a prop on Redux Form v6 AFAIK.

You're probably confusing because of this bit of code:

```js
InitializeFromStateForm = connect(
  state => ({
    initialValues: state.account.data // pull initial values from account reducer
  }),
  { load: loadAccount }               // bind account loading action creator
)(InitializeFromStateForm)
```

This is where `load` is coming from as a prop.
