### ISSUE TITLE
null and false values should not equal each other in deepEqual customizer

### ISSUE THREAD

**Issue by erikrestificar** [erikras/redux-form#2978]
null and false values should not equal each other in deepEqual customizer. see commit:
https://github.com/erikras/redux-form/commit/a4c1d9f0382d434402b55f5175c17b868fc6b2f5

For example, in a radio group.  an unselected radio group (null) is a completely different state from selecting the false option.

**Comment by gustavohenke** [comment]
In case all you're trying to do is to verify the selection status of a radio button: you can tell do that by using props such as `meta.dirty`/`meta.pristine` instead of checking the values.

**Comment by erikrestificar** [comment]
the issue is that /src/defaultShouldValidate.js uses the deepEqual customizer to determine whether it should validate.   For example lets say I have a form with boolean radio fields. 

1) initialValue is null and no radios are selected (invalid state)
2) user selects the false radio option (valid state)
3) validation is not triggered because null == false and no change is detected which is incorrect

I'm supplying my own shouldValidate function to get around this issue, but I don't think it makes sense for null == false to be the default behavior, that commit should be rolled back

**Comment by j-clark** [comment]
I've bumped into this as well and have a [sandbox](https://codesandbox.io/s/58nLmP7EX) reproducing the issue.

To reproduce:
* click on "No" first
* see that the radio button doesn't update
* click elsewhere to blur (it updates)

This doesn't happen when selecting yes first. Only when going from `null` to `false`.

**Comment by gustavohenke** [comment]
This is yet another case that led to the [v7.0.0 release](https://github.com/erikras/redux-form/releases/tag/v7.0.0):

> `undefined` and `false` are now treated as NOT equal. This will affect your dirty/pristine state, as well as whether or not a field is rerendered when the value goes from `undefined` to `false` (previously it did not).
