### ISSUE TITLE
Correct usage of "_error"

### ISSUE THREAD

**Issue by approots** [erikras/redux-form#298]
I'd like to show general, non-field-specific errors by adding `_error` to the object returned in a rejected Promise. I've tried to follow your example here: http://erikras.github.io/redux-form/#/examples/submit-validation?_k=8m8iq3. Unfortunately, `this.props.error` is always `undefined`. Here's the submit handler I've been using:

	handleSubmit(values) {
		const postData = {method: 'post',body: {...values}};

		return new Promise((resolve, reject) => {
			return fetch.json('/api/signup', postData)
				.then((json) => {
					return resolve();
				})
				.catch((error) => {
					switch (error.json.message) {
						case 'signup_code_not_exists' :
							return reject({signupCode: 'The code does not exist'});
						default :
							return reject({_error: 'Error'});
					}
				});
		});
	},

I wonder what I'm doing wrong?

**Comment by erikras** [comment]
That code looks pretty solid. Can you inspect the Redux state with redux-devtools? Is the `_error` key there?

![redux devtools 2015-11-19 13-27-54](https://cloud.githubusercontent.com/assets/4396759/11270705/79845142-8ec1-11e5-8680-ecd94385331a.jpg)

**Comment by approots** [comment]
I don't have redux devtools setup, but here is a screen of the redux-logger console output:

![redux_form_error](https://cloud.githubusercontent.com/assets/235342/11276142/a2fbc914-8e95-11e5-802f-b63df0ed7322.png)

Hope it helps. Thanks.

**Comment by erikras** [comment]
Did you mean to close this?

**Comment by approots** [comment]
Ahh. My fault. So sorry for wasting your time. I had wrapped the form in a container component and forgot to pass the error prop.

**Comment by erikras** [comment]
Aha! :+1: No worries. Happens to all of us.
