### ISSUE TITLE
Form is initialized and then destroyed when navigated to from another page with same form (using react router)

### ISSUE THREAD

**Issue by krisfields** [erikras/redux-form#2982]
I'm not sure if this is a bug or I am simply not understanding how to set initialValues every time a form component is mounted.  I have the same form component on two separate pages.  When the first page is loaded, the initial values set correctly.  If I navigate to the second page (using react router), the form doesn't initialize.  Also, if I navigate back to the original page, that form doesn't initialize, and thus there are no longer any initial values there either. 

EDIT: It looks like the form is initialized correctly upon componentWillMount, but is then immediately destroyed due to the previous page's form's componentWillUnmount firing immediately after.  What is the proper way of handling a form that is used on multiple pages?

**Comment by krisfields** [comment]
Ok, I finally solved my issue by using a different form name for each form.  For anyone else trying to do the same, this comment was very helpful: [https://github.com/erikras/redux-form/issues/603#issuecomment-295043224](url)

**Comment by denis-sokolov** [comment]
This is the sequence of Redux actions in my application under a particular set of circumstances: `redux-form/INITIALIZE`, `redux-form/INITIALIZE`, `redux-form/DESTROY`. My understanding is the destroy belongs in pair with the first init, and the ideal order is `INIT`, `DESTROY`, `INIT`. What happens in my app is the destroy blanks the store state, even though there is a form on the screen.

Between the unclear order of React component lifecycle events and general complexity of ordering async JavaScript, we have to handle the case when the events get re-ordered, but we don’t.

Here’s a [quote from @erikras](https://github.com/erikras/redux-form/issues/1825#issuecomment-248531066) I find relevant:
> Developers are used to their high level garbage collected languages that clean up after they are no longer using data.

I like this comparison between GC and redux-form state, but I shall note that developers are also used to their high level garbage collection not clean up while they are still using the data.

I think a reference counter is in order. Every piece of state in the store would have a counter with it and a mounting component increases the counter, while an un-mounting component decreases it. Then we only blank it if the counter is at 0.

I think this is still a bug in `redux-form`, though, and I would like it to be re-opened for discussion. Thoughts?

**Comment by shawnmclean** [comment]
After upgrading from 6 to 7, I think I'm experiencing this issue. I have a few forms on the same page, a page that multiple routes will point to. When my route changes, all my forms are destroyed. Is there a way I can prevent this kind of GC behavior that is tied to routes?

**Comment by avalla** [comment]
@denis-sokolov I had similar problem and I had to move to final-form to avoid that...

**Comment by diegorodriguesvieira** [comment]
Any updates about this issue?

**Comment by Zhuvikin** [comment]
The same issue for me

**Comment by lucas-issa** [comment]
Based on the comments from @gaearon on the issue https://github.com/facebook/react/issues/11106, I came to the conclusion that it will no longer be possible to use the same form name for different instances of components if they are created one after another.

I ended up reaching the following solution:

Simple use:
```
const MyFormComponentWithReduxForm = compose(
  withDynamicFormName({ formNamePrefix: 'myFormName' }),
  reduxForm(),
)(MyFormComponent);
```

If you need to access some form values:

```
const MyFormComponentWithReduxForm = compose(
  withDynamicFormName({ formNamePrefix: 'myFormName' }),
  connect((state, ownProps) => {
    const selector = formValueSelector(ownProps.form);
    let fieldXxx = selector(state, 'fieldXxx');
    return {
      fieldXxx,
    };
  }),
  reduxForm(),
)(MyFormComponent);
```

**withDynamicFormName** code:

```
import React from 'react';
import { connect } from 'react-redux';
import { destroy } from 'redux-form';

/**
 * Automatically generate a new form name every time the component is created.
 *
 * @param formNamePrefix The prefix that will be used to generate the form name.
 */
export const withDynamicFormName = ({ formNamePrefix }) => ComponentWithReduxForm =>
  connect(
    null,
    { destroy },
  )(class WithDynamicFormName extends React.Component {
    static idCounter = 1;

    id;
    formName;

    constructor(props) {
      super(props);
      this.id = WithDynamicFormName.idCounter++;
      this.formName = `${formNamePrefix}-${this.id}`;
    }

    /**
     * It is necessary to destroy the form again because the "submitSucceeded" property is left
     * if the form is submitted and the component is destroyed right after.
     */
    componentWillUnmount() {
      // It is necessary to use the "setTimeout" so the form destruction can occur after
      // "submitSucceeded" is set. Otherwise, this garbage will be left in the redux store.
      setTimeout(() => {
        this.props.destroy(this.formName);
      }, 0);
    }

    render() {
      return (
        <ComponentWithReduxForm
          {...this.props}
          form={this.formName}
        />
      );
    }
  });

```

**Comment by asotog** [comment]
@krisfields thanks so much @krisfields , i also forgot to use different name for the other form i'm using, that fixed my issue
