### ISSUE TITLE
Documentation about clearing form

### ISSUE THREAD

**Issue by neverfox** [erikras/redux-form#299]
In the FAQ about clearing a form after submission, you give four options, the last of which you don't recommend. However, other than (C), which isn't always the correct use case, *only* the last one feels to me like it fits with the Redux philosophy. (A) seems to be to revert back to the world where you have listeners doing things somewhere in your component tree in response to something else (in your case a Promise resolving). Isn't avoiding that kind of thing the reason people use Redux in the first place? Of course, its a common pattern in Redux for async actions to trigger other actions but it done *inside* the action creators rather than the components.

I'm not trying to be critical but really just trying to understand why that can be considered idiomatic Redux, and why option (D) isn't recommended (since it doesn't strike me as really needing to know more about the internals of redux-form than you otherwise have to know to use it in the first place).

**Comment by erikras** [comment]
You have made an excellent point. I think you've convinced me to reword that.

Thank you.
