### ISSUE TITLE
Feature Proposal: formValues() HOC decorator that works inside a form component

### ISSUE THREAD

**Issue by erikras** [erikras/redux-form#2996]
From discussion on #2852 with @wmertens. The problem being solved is that [`formValueSelector()`](http://redux-form.com/6.7.0/docs/api/FormValueSelector.md/) cannot be used in a reusable way inside a [`<FormSection>`](http://redux-form.com/6.7.0/docs/api/FormSection.md/) because it doesn't know what the prefix defined in the `<FormSection>` is. General API syntax would look like:

```jsx
@formValues({
  destProp: 'nameOfField'
})
class MyReusableFields extends Component {
  render() {
    const { destProp } = this.props
    // destProp is the value of the field called 'nameOfField'
    return (
      <div>
        <Field name="nameOfField" component="input"/>
        ... other fields

        ... some logic involving value of nameOfField:
        {destProp === 'specialValue' && <div>Value is SPECIAL!!</div>}
      </div>
    )
  }
}
```
There might also be an alternative syntax where, if your keys and values were all going to be the same, rather than pass...
```jsx
@formValues({
  firstField: 'firstField',    // key and value are ===
  secondField: 'secondField'   // key and value are ===
})
class MyReusableFields extends Component {
  ...
}
```
...you could just pass a list of strings. e.g.
```jsx
@formValues('firstField', 'secondField')
class MyReusableFields extends Component {
  ...
}
```

**Comment by wmertens** [comment]
Alright, I took a stab at implementing it. It's using `@connect` to listen to store updates, but it uses the `getValues()` from `context._reduxForm` to get at the values. See #3011

**Comment by erikras** [comment]
Merged #3011. Will comment again when released.

**Comment by erikras** [comment]
Fix published in [`v6.8.0`](https://github.com/erikras/redux-form/releases/tag/v6.8.0).

**Comment by jasan-s** [comment]
I am sure I'm using the feature incorrectly. Instead of  reading from Redux directly I thought I could use `Values = formValues('email','password')(Auth)`  the` Auth` is the form name and the Field names are `email `and `password`.

**Comment by jasan-s** [comment]
I wanted to access forms values within the component.  I know I can pass it down by using connect but though this may be cleaner.

**Comment by wmertens** [comment]
No, what you did there is create a component named Values that gives
`email` and `password` as props to the Auth component

**Comment by jasan-s** [comment]
@wmertens  so, what is the recommended way to accesses the form field values within the same form component?

**Comment by wmertens** [comment]
Exactly this. Use <Value/> instead of <Auth/> and you will have the current
field values as props.

**Comment by wmertens** [comment]
Note that @formValues simply creates the @connect function that you need to
get the values

**Comment by gleb-lobastov** [comment]
@erikras I face some strange behaviour with formValues: values lagging behind the state at the time of reading. getValues retun { flag: false } when it actually true in the state. They syncs only on next mapStateToProps calculation, which might be performed only at next user interaction.

So formValuesSelector works for me, but formValues does not =(

**Comment by wmertens** [comment]
@gleb-lobastov can you share the code where you are using it? The `@formValues` just creates a redux listener with `connect`, so it should be updating when the store is updating, like all other connected components. Try looking at the redux and react devtools to see what the redux state is and what the react components get for props?

**Comment by gleb-lobastov** [comment]
@wmertens finally I reproduce the issue:
https://codesandbox.io/s/Vrn7MZov

And root of problem was in my react-redux version: 4.4.5
if you change react-redux to latest 5^ then problem will gone

**Comment by wmertens** [comment]
@gleb-lobastov wow, that's surprising! Good that you were able to fix it!
