### ISSUE TITLE
Memoize validation

### ISSUE THREAD

**Issue by erikras** [erikras/redux-form#3]
Look to [`reselect`](https://github.com/faassen/reselect) for inspiration.

**Comment by johanneslumpe** [comment]
Haven't looked at reselect, but couldn't we just check whether the passed in `data` object is a new one? And if it's not just return the last error state.

**Comment by erikras** [comment]
I think so. I don't know if reselect is doing anything smarter than `===` or not.

**Comment by johanneslumpe** [comment]
It seems that by default they do just that - `===`. But they allow passing of a custom function. So maybe the first step could be to just use `===`.

**Comment by erikras** [comment]
PRs accepted. ;-)

**Comment by johanneslumpe** [comment]
I thought so ;) Will try to do something tomorrow morning :)

**Comment by johanneslumpe** [comment]
@erikras sorry didn't have the time yet, did not forget about this!

**Comment by erikras** [comment]
I've decided that this is not in the scope of this project. It's the job of the person passing the validation function to memoize it. I've written a library called [`lru-memoize`](https://github.com/erikras/lru-memoize) to enable this in [react-redux-universal-hot-example](https://github.com/erikras/react-redux-universal-hot-example).

**Comment by johanneslumpe** [comment]
Oh ok, also cool :+1:
