### ISSUE TITLE
Form's state is null by default

### ISSUE THREAD

**Issue by suevalov** [erikras/redux-form#30]
I'm trying to jump from 0.1.3 to 0.2.4 and found a pitfall which I couldn't get rid of.

The form is rendered within bootstrap popup. 

![form](https://cloud.githubusercontent.com/assets/3672221/9423670/d3af14bc-48d6-11e5-8856-67608b9236f9.png)

I'm using [reselect](https://github.com/faassen/reselect) for lazy evaluations and in this particular case to define whether user can add widget or not.

```js
import { createSelector } from 'reselect';
const widgetNameSelector = state => state.addWidgetForm.data.name;
const widgetTypeSelector = state => state.addWidgetForm.data.type;
const canAddSelector = createSelector(
  [widgetNameSelector, widgetTypeSelector],
  (name, type) => !!name && !!type  // both fields should not be empty
);

@connect(
  (state) => {
    return {
      form: state.addWidgetForm
      canAdd: canAddSelector(state)
    };
  }
)
class AddWidgetForm extends Component { ... }
```

`addWidgetForm`  wasn't equal `null` at start in redux-from@0.1.3, so I could rely on the structure in reselect `state.addWidgetForm.data.name`.

In redux-form@0.2.4 it equals `null`.
![devtools](https://cloud.githubusercontent.com/assets/3672221/9423689/0bfb0e4c-48d8-11e5-93a4-d6a71eddbd9f.png)

Of course I have error in this function:
```js
const widgetNameSelector = state => state.addWidgetForm.data.name;
```

Any suggestions? Is it correct behaviour?

**Comment by erikras** [comment]
First of all, brilliantly presented issue. Thank you.

Yes, that changed just now in v0.2.4, that the state objects are lazily initiated on the first action received. This is what allows the reducer to figure out if it is a [multi-reducer](https://github.com/erikras/redux-form#editing-multiple-records) or not. My [ridiculous destructuring](https://github.com/erikras/react-redux-universal-hot-example/blob/master/src/components/SurveyForm.js#L45-L47) on my example was masking this issue.

I see two solutions:

1. Force people to do null checks.
2. Force people wanting to use multi-reducers to _tell the reducer that_ in `createFormReducer()`.

I prefer the latter. Thoughts? @janmarek?

**Comment by suevalov** [comment]
In this specific case I'd go with null check, but in general I'd prefer more intuitive solution. Is there any chance to implement optional lazy initialization only for multiple records?

**Comment by erikras** [comment]
[v0.3.0](https://github.com/erikras/redux-form/releases/tag/v0.3.0) provides a solution to this. Or, rather, defers a solution to this to another library. See [Calculating `props` from Form Data](https://github.com/erikras/redux-form#calculating-props-from-form-data).

**Comment by suevalov** [comment]
Thanks, awesome work!
