### ISSUE TITLE
Cannot Use Stateless Function as Component in in <Field />

### ISSUE THREAD

**Issue by abrad45** [erikras/redux-form#3003]
### Are you submitting a **bug report** or a **feature request**?

Bug Report

### What is the current behavior?

Unless I am gravely mistaken about how this plugin works, I cannot create a stateless function and use it in the `component` prop for `<Field />`, specifically when trying to render a checkbox. The checkbox renders but the value in the store doesn't update when toggling it on / off.

### What is the expected behavior?

I'd expect that clicking the checkbox would update the value in the redux-store under the key for my form, OR (in the event that I made a simple mistake) that the documentation would more clearly indicate how to create a custom component that renders a non-`type="text"` input.

### Sandbox Link

https://codesandbox.io/s/OyAo2l1gE

### What's your environment?

* Redux-Form 6.7.0
* Chrome Version 58.0.3029.110 (64-bit) on macOS 10.11.6
* Node v6.3.0

### Other information

I'm wondering if this is me not understanding a property that I need to add to the `<input type="checkbox" />` tag in my stateless function, but the output of the tag in the console doesn't look very different from the inline component (`<Field type="checkbox" component="input" />`) so I'm not sure what I'm missing, if anything.

**Comment by vladimirbuskin** [comment]
i 've changed your example, you need to move all props which came as input into your input, because there are onChange, onFocus, onBlur and others are comming as well, 
https://codesandbox.io/s/r0JAq7p02

so instead of 
`const CheckboxField = ({ input: { name }, labelTextt }) => (
  <div>
    <label className="label" htmlFor={name}>{labelTextt}</label>
    <div>
      <input type="checkbox" className="checkbox" name={name} id={name} />
    </div>
  </div>
);
`
you make 
`const CheckboxField = (props) => {
  
  var { input, labelTextt } = props
  
  
  return (
  <div>
    <label className="label" htmlFor={name}>{labelTextt}</label>
    <div>
      <input type="checkbox" className="checkbox" name={name} id={name} {...input} />
    </div>
  </div>
)};
`

**Comment by gustavohenke** [comment]
Yep. Precisely what @vladimirbuskin said - thanks!

**Comment by abrad45** [comment]
@vladimirbuskin I've surely felt smarter than I do right now 😳 

Thanks for this. Not the simplest to debug from the console, but should have recalled those handlers being attached to the inputs in other examples through the spread operator. Thanks!
