### ISSUE TITLE
Add a message to older redux form pages, indicating outdated status

### ISSUE THREAD

**Issue by samcarlinone** [erikras/redux-form#3007]
It is possible to get to outdated redux form docs (e.g. through Google, forum links, etc.) and have no idea one is not on the latest version. I think a message or warning with a link of some sort would be helpful to people using the latest version of redux form to find the information they are looking for.

**Comment by gustavohenke** [comment]
Good idea!

**Comment by gustavohenke** [comment]
Closing in favor of #3166, which is more detailed than this one.
