### ISSUE TITLE
Initializing form with an object from the DB

### ISSUE THREAD

**Issue by roytz** [erikras/redux-form#3010]
Hi,
I know this is an issue that was discussed many times before and also appears on the redux-form guide (I read it of course), but I tried so many approaches and still couldn't get it right..
I have a container where I use redux-form and want to initialize it with an object I get from the DB.
The thing is, that when the initialization happens, the object is not yet available on the redux store..
I used the connect function like this - 
`connect(state => ({ initialValues: state.myObject }), { getMyObject })(MyObject);`
where `getMyObject` is an action that has a corresponding reducer that saves the object on the redux store under the name of `myObject` and `MyObject` is my container.
What happens is that the initialization of the form occurs before the reducer updates the state so if I look at the state after the container was rendered I see `myObject` with the correct data (from the DB) but the `initial` field (inside the relevant form object) is still empty.
I'd appreciate your help.
Thanks

**Comment by gustavohenke** [comment]
Use `enableReinitialize` option in your `reduxForm` wrapped component.

Thanks for using Redux Form, but in the future please open questions at StackOverflow, which is proper place for them, not our GitHub issue tracker.

**Comment by roytz** [comment]
Thanks @gustavohenke !
