### ISSUE TITLE
[v6] Typescript and redux-form/immutable

### ISSUE THREAD

**Issue by romanantl-flexiana** [erikras/redux-form#3013]
Hello,
i'm using packages:

```
"@types/redux-form": "^6.6.2",
"redux-form": "^6.6.2",
```

If i'm using in tsx file 
```
import * as ReduxForms from 'redux-form'
```
all is good, but can't use it as
```
import * as ReduxForms from 'redux-form/immutable'
```

i get error: Could not find a declaration file

Please, any ideas how to solve that? Is that problem of redux-form or https://github.com/DefinitelyTyped/DefinitelyTyped
? 
Thx for reply

**Comment by gustavohenke** [comment]
It's definitely a problem of DefinitelyTyped 😉 

It would be amazing to have those typings maintained on our side (see #1211), because TypeScript is the most well-adopted typing variation of JS, but unfortunately we don't have the workforce for this at the moment.

**Comment by romanantl-flexiana** [comment]
Thx for reply @gustavohenke

**Comment by dumorango** [comment]
Hi @romanantl-flexiana, @gustavohenke.

Even after the 6.6.3 version being merged [https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15136]. I'm still having the same issue. 

Do you guys think that the 'redux-form/immutable' should be added to the typings in order to solve this issue?

Thanks.

**Comment by gustavohenke** [comment]
Probably, it's part of Redux Form.

**Comment by dumorango** [comment]
Thanks, @gustavohenke. I'm working on it.

**Comment by dumorango** [comment]
Here it is. Looks like it needs an OK from the authors ( @CarsonF @aikoven @LKay) before it gets merged.
