### ISSUE TITLE
Only one Field exists, press 'enter' trigger submit

### ISSUE THREAD

**Issue by highalps** [erikras/redux-form#3015]
for example, 
``` 
<form className={styles.wrapper} onSubmit={handleSubmit(this.handleSubmit)}> 
   <Field ............................................. >
</form>
```
tag, press 'enter' resulting execute this.handleSubmit
but when more than one Field component exist, press 'enter' not fire this.handleSubmit

is it possible disable 'enter' for submit when one Field exists?

i saw the same issue, but can't find answer

* i'm using redux-form 6.5.0 version

**Comment by gustavohenke** [comment]
If you could provide a working example of both, it would be awesome.

By the way, the deal with the enter key is more like coming from the browser, and not from Redux Form.

**Comment by highalps** [comment]
@gustavohenke

for example, there is component for input

```
 one(field) {
    const { input, meta } = field
    return (
      <Input
        type="text"
        value={input.value}
        onChange={input.onChange}>
      </Input>
    )
  }

```

case 1.
```
<form className={styles.wrapper} onSubmit={handleSubmit(this.handleSubmit)}> 
   <Field name="one" component={this.one} />
   { if (this.props.dirty) {<button type="submit" value="button" /> }
</form>
```

case 2.

```
<form className={styles.wrapper} onSubmit={handleSubmit(this.handleSubmit)}> 
    <Field name="one" component={this.one} />
    <Field name="two" component={this.two} /> // 'two' component same as 'one' component
     { if (this.props.dirty) {<button type="submit" value="button" /> }
</form>
```

for case 1, no input value changed but when press the enter, form value submitted
(not dirty, so button not rendering)

otherwise for case 2, nothing happened when press the enter

**Comment by highalps** [comment]
i'm sorry. it's about W3C Specs.

**Comment by OKNoah** [comment]
@highalps I believe you can put a hidden `<button>` :)

**Comment by musbaig** [comment]
One way to disable submitting the `form` on enter and instead have your field changes trigger the submit is as follows:
```
<form className={styles.wrapper} onSubmit={this.props.handleSubmit(() => {})}> 
   <Field ............................................. >
</form>
```
Then, the `Field` can use `onChange` to submit data.

**Comment by highalps** [comment]
@musbaig oh... that's another way i didn't know.. :)
