### ISSUE TITLE
How to invalidate form if FieldArray length is 0?

### ISSUE THREAD

**Issue by AshCoolman** [erikras/redux-form#3016]
I'm trying to invalidate a form based on the length of the field array. 

So if the validate function returns `{}` to signify that the form is valid, and it returns `{itemSupplier: 'Whoops'}` if `itemSupplier` is wrong, I assumed Id be able to do something like:

    const validate = formData => {
      return formData.list.length === 0
      ? {list: 'Min length is 0'}
      : {}
    }

I've tried a few other things, including:

    const validate = formData => {
      return formData.list.length === 0
      ? {list: ['Min length is 0']}
      : {}
    }

and

    const validate = formData => {
      return formData.list.length === 0
      ? {list: [{itemName: 'Min length is 0']}
      : {}
    }

Any help would be appreciated

**Comment by gustavohenke** [comment]
[According to the docs, you need to report errors of the whole array in the `_error` key](http://redux-form.com/6.7.0/docs/api/FieldArray.md/#-meta-error-string-optional-).

```js
const validate = data => {
    const errors = {};
    
    if ( data.list.length ) {
        // apply validation to each item individually
    } else {
       // or perhaps make it an array, so you can use both per-item errors and array errors
        errors.list = {
            _error: "bla"
        };
    }
}
```
