### ISSUE TITLE
UPDATE_SYNC_ERRORS sets all field errors on load

### ISSUE THREAD

**Issue by robhadfield** [erikras/redux-form#3017]
### What is the current behavior?
Recently updated and all fields have error on load.

### What is the expected behavior?
For the fields to have error only after validation fails - after touch.

### What's your environment?
```
    "react": "^15.4.1",
    "redux-form": "^6.7.0",
    "redux-form-material-ui": "^4.2.0",
```

### Other information
On load of the empty form component `@@redux-form/UPDATE_SYNC_ERRORS` runs and sets an error on each field that has validation set. The validation is a simple required func `const required = value => value ? undefined : 'Required';`

I'm not sure how this is being set when the field has no value? It's a new form so no initial values.

Any idea why this validation is failing on load? Any help appreciated :)

**Comment by timhwang21** [comment]
Are you saying that the field has an error prop passed to it, or the field is being marked as touched, and the error is showing?

Receiving an error is intended behavior even before touching. If you look in the examples, the field is set to only render the error conditionally based on touched state.

If I'm misunderstanding your question please let me know!

**Comment by robhadfield** [comment]
Hey @timhwang21 - thanks for the reply. When a clean form loads it displays the required error and the object is attached. Is this desired behaviour?

![image](https://user-images.githubusercontent.com/477344/27070356-91eeabc6-5010-11e7-917b-30a69b4b9596.png)

```
{
  "registeredFields": {
    "name": {
      "name": "name",
      "type": "Field",
      "count": 1
    },
    "typeid": {
      "name": "typeid",
      "type": "Field",
      "count": 1
    },
    "image": {
      "name": "image",
      "type": "Field",
      "count": 1
    }
  },
  "syncErrors": {
    "name": "Required",
    "typeid": "Required"
  }
}
```

**Comment by timhwang21** [comment]
What's your code to display errors? If you're display them without checking for touched status, yes this is intended.

**Comment by robhadfield** [comment]
Thanks @timhwang21 - I think it may be related to the way that I'm aliasing the onBlur event and also the way Material-UI handles the touched prop.

Anyway - working now, so thanks!
