### ISSUE TITLE
shouldAsyncValidate/asyncValidate not called if form is pristine on submit

### ISSUE THREAD

**Issue by inostia** [erikras/redux-form#3020]
### Are you submitting a **bug report** or a **feature request**?
Bug

### What is the current behavior?
`shouldAsyncValidate` does not get called if no fields have been touched.

### What is the expected behavior?
If the form is pristine and user submits, asyncValidation should be called. I tried to override the behavior with `shouldAsyncValidate` but that also does not get called if the form is pristine and a user hits submit. As soon as I touch a field, however, all of the async errors are displayed. Any thoughts?

### What's your environment?
redux-form 6.7.0

**Comment by gustavohenke** [comment]
Since you didn't attach any examples/code sandbox, I'll need to investigate; but for now, I'm tagging this as a bug anyway.

**Comment by inostia** [comment]
Was not able to reproduce on codesandbox (see https://codesandbox.io/s/VG4Y6vpX). I'm not sure why it doesn't fire for me locally, but I will investigate. Closing for now.
