### ISSUE TITLE
Use radio button with React Native & Native Base

### ISSUE THREAD

**Issue by ckim16** [erikras/redux-form#3021]
Hi, I want to use Redux Form with React Native and Native Base but I'm having trouble with rendering a radio button in my app and I was hoping  that someone can guide me into right direction for it.

```
renderRadio({ input, type, options, meta: { touched, error } }) {
    const hasError = touched && error;
    return (
      <Form>
        <Grid>
          <Row>
            {options.map(o => <Item key={o.value}>
              <FontAwesome name={o.value === "M" ? "male" : "female"} size={25}/>
              <Label>{o.title}</Label>
              <Input {...input} type={type} value={o.value} checked={o.value === input.value}/>
              {hasError && <Text>{error}</Text>}
            </Item>)}
          </Row>
        </Grid>
      </Form>
    );
  }

render() {
    const { handleSubmit, fields: { email, password, passwordConfirm, gender } } = this.props;
    return (
      <Container style={styles.container}>
        <Content>
          <Form>
            <Field name="email" component={this.renderField} label="Email"/>
            <Field name="password" component={this.renderField} label="Password"/>
            <Field name="passwordConfirm" component={this.renderField} label="Password Confirm"/>
            <Field name="gender" type="radio" component={this.renderRadio} options={[
                {title: 'Male', value: "M"},
                {title: 'Female', value: "F"}
              ]}/>
            {this.renderAlert()}
            <Button
              style={styles.button} block
              action="submit"
              onPress={handleSubmit(this.handleFormSubmit.bind(this))}
            >
              <Text>Signup</Text>
            </Button>
          </Form>
        </Content>
      </Container>
    );
  }
```

In my code, I do not see any type of radio button (neither any check sign) and get my input value from `renderRadio` method as undefined.
<img width="586" alt="screen shot 2017-06-05 at 3 56 53 pm" src="https://cloud.githubusercontent.com/assets/15335445/26806797/a5057fe6-4a07-11e7-8348-d5c86f31d122.png">

Can anyone please help me with this?

**Comment by gustavohenke** [comment]
Hi @ckim16, this is a tricky one. See #2292 why.

When you use a `<Field type="radio" />`, Redux Form _requires_ that you set `value` too.
So you are basically not allowed to have a radio group this way; either remove the `type` or spread the radios in the component that will render them.

Example:
https://codesandbox.io/s/EkggLy6m

**Comment by Geczy** [comment]
Thank you @gustavohenke was running into this issue for a while. Appreciate the sandbox, extremely helpful

**Comment by indrawanadjie** [comment]
@gustavohenke Hi Gusta, thanks for help. I still confuse use radio buton with react native. I done try you example, but not work in react native.

**Comment by swa158** [comment]
I'm not sure if this helps with the radio button but I got the Native Base checkbox working using
const renderCheckBox = ({ input, checked, label, meta: {touched, error}, children, ...custom }) => (
    <CheckBox
        style={{height: 20, width: 20}}
        checked={input.value}
        onPress={() => {
            input.value ? input.value = false: input.value = true;
            input.onChange(input.value)
        }}
        {...custom}
    />
);

Hope it helps someone else battling with the check box 😃
