### ISSUE TITLE
Is ther eway to find out field's dirty value outside of it ?

### ISSUE THREAD

**Issue by martlaboloa** [erikras/redux-form#3026]
I know selectors can select form's dirty value (isDirty), but is there way to know if specific field is dirty or not, outside of that field ?

**Comment by KevinGorjan** [comment]
+1, struggling with the same question...

**Comment by STEVEOO6** [comment]
I'm also trying to identify the same; surprised this isn't exposed in the store.

**Comment by erikras** [comment]
Well, you have two options.

### Option 1
Inside a `connect()` call:
```jsx
const value = getFormValues('myForm')(state).myField
const initial = getFormInitialValues('myForm')(state).myField
const dirty = value !== initial
```

### Option 2
Just use another `<Field/>` component. There's no rule that says that a `<Field/>` component _must_ render an input.

```jsx
const renderButton = ({ meta: { dirty } }) =>
  <button style={{ background: dirty ? 'blue' : 'green' }}>Green When Pristine</button>

...

<Field name="myField" renderComponent={renderButton}/>
```

**Comment by gustavohenke** [comment]
For those of you who commented here... is the solution @erikras proposed enough?

**Comment by gustavohenke** [comment]
Will consider that as done.
In case you still have problems - please let us know.

**Comment by spyl94** [comment]
What do you think of adding an optional `field: String` parameter to the selector `isDirty` to provide this feature ? (Could also apply to isPristine, isValid, etc...).

**Comment by lauramontemayor** [comment]
FYI - I'm using `redux-form v7.4.2`

Is `isDirty("formName")(state, ["fieldName"])` the correct syntax? 

It doesn't seem to work for me.

**Comment by thomassvensen** [comment]
I have the same issue as @lauramontemayor - calling `isDirty("formName")(state, ["fieldName"])` seems to return whether the whole form is dirty, not specifically the "fieldName" field.
