### ISSUE TITLE
Does redux form material ui work in react native?

### ISSUE THREAD

**Issue by ckim16** [erikras/redux-form#3029]
I wanted to use `import { RadioButton, RadioButtonGroup } from 'redux-form-material-ui';` but it gives me an error saying `Unable to resolve module 'react-dom' from 'file/path/material-ui/AutoComplete/AutoComplete.js'....`. Can I use redux form material ui in reant native or do I have to install more modules to be able to use it?

Please let me know if anyone has had similar issue as mine.

Thank you,

**Comment by gustavohenke** [comment]
[redux-form-material-ui is in another repository](https://github.com/erikras/redux-form-material-ui) 😉
