### ISSUE TITLE
Uncaught TypeError: Cannot read property 'text' of null

### ISSUE THREAD

**Issue by slybridges** [erikras/redux-form#303]
Hello :wave:

I'm currently integrating the `DateTimePicker` from [react-widgets](https://github.com/jquense/react-widgets) to `redux-form` in a very standard way but I get this error when the DateTime input field losses focus:
`Uncaught TypeError: Cannot read property 'text' of null`

It's coming from https://github.com/erikras/redux-form/blob/master/src/events/getValue.js#L18
```javascript
if (!isReactNative && event.nativeEvent !== undefined && event.nativeEvent.text !== undefined)
```
(Unsure how I ended up there, it's only happening with the `DateTimePicker` widget. I can provide the code I'm running but I don't think this is where the problem comes from.)

So, for me, `event.nativeEvent == null` (instead of `undefined`) and `null !== undefined` being `true`, it throws at the next test.

Shouldn't the test ` if (event.nativeEvent !== undefined)` (and the likes) be replaced by `if (!event.nativeEvent)` ?

Cheers!

**Comment by erikras** [comment]
Should be fixed in `v3.0.11`.

**Comment by slybridges** [comment]
Thanks ~~Flash Gordon~~ @erikras !

I can see other `if` tests that are testing for `undefined` as well (the one just below in the same source file for instance).

Shouldn't we try and update all these tests ? Or are there any edge side-effect that might arise you think ?
In the former, happy to make a code review and PR.

**Comment by erikras** [comment]
The reason for the `!== undefined` checks is because sometimes `null` and `false` and `0` can be valid values, even though they are falsy.
