### ISSUE TITLE
Stateless function components cannot be given refs

### ISSUE THREAD

**Issue by zelikfr** [erikras/redux-form#3035]
Can you clean input props from ConnectedField to prevent "unexpected" props ?

**Comment by erikras** [comment]
Can you explain which props are "unexpected"?

**Comment by zelikfr** [comment]
All props whose aren't a DOM attributes supported by react. Example, when I'm testing my connected components, I'm using a middleware who pass to all component a props store, then input received a props store. As store isn't a known props, react is displaying a warning. (React unknown props)

**Comment by gustavohenke** [comment]
So, is this a problem with Redux Form? Can you show any code which demonstrates your problem?

**Comment by zelikfr** [comment]
I've been updated this issue because unknown props provide from our jest mock system which pass a props store to all connected component then it add a store props to your input component. I fix this unexpected behavior by replace component="input" to component={customInput}. That's not the best thing I wanted to do but that's solve this warning.
Anyway, I have another warning from react whose I'm not able to fix. Because I guess that's provide from your lib. The unexpected warning is the warning below : 
``` Warning: Stateless function components cannot be given refs (See ref "wrapped" in Connect(Form(Stopwords)) created by ReduxForm). Attempts to access this ref will fail.```
Let me know if you can fix it or if you know a way to avoid these warning or if I've to find on my own.
Thanks

**Comment by gustavohenke** [comment]
> Can you show any code which demonstrates your problem?
