### ISSUE TITLE
Simple Form example fails to build locally 

### ISSUE THREAD

**Issue by milliechan** [erikras/redux-form#3038]
Simple Form never loads after installing dependencies. I get this error on localhost:3030
```
Uncaught Error: Cannot find module "./App.scss"
    at eval (bundle.js:1)
    at Object.o (bundle.js:1)
    at t (bundle.js:1)
    at Object.defineProperty.value (bundle.js:22)
    at t (bundle.js:1)
    at Object.e.exports (bundle.js:1)
    at t (bundle.js:1)
    at eval (bundle.js:1)
    at eval (bundle.js:1)
    at eval (bundle.js:1)

```

I also had to manually install webpack-dev-middleware as that seemed to be missing.. 
Looks like that file is coming from the website-template module and that might be the reason why it's failing 

Steps to reproduce:
cd examples/simple 
npm i 
npm start

**Comment by timhwang21** [comment]
Ran into this just now as well, for what it's worth, using the scripts at the root `package.json` works: `npm example:immutable`

**Comment by erikras** [comment]
This is a known problem, thanks. I'm working on it.

Some webpack upgrade broke it, I think.

**Comment by erikras** [comment]
This should be fixed now. Thanks!
