### ISSUE TITLE
Field transforms number to string

### ISSUE THREAD

**Issue by nealoke** [erikras/redux-form#3040]
### Are you submitting a **bug report** or a **feature request**?
Bug

### What is the current behavior?
Currently when having a `number` input, it transforms it to a string value.

### What is the expected behavior?
Should not change number inputs to strings.

### Sandbox Link
[Sandbox link](https://codesandbox.io/s/BBzJmMgEN)

### What's your environment?
(unchanged from simple example)
react `15.5.3`
react-dom `15.5.3`
react-redux `5.0.4`
redux `3.6.0`
redux-form `6.6.3`
redux-form-website-template `0.0.41`

**Comment by erikras** [comment]
Redux Form just uses the value that comes from `event.target.value`, which is a string. You can get a number by putting a

```jsx
parse={Number}
```

prop onto your `Field`.

[![Edit Redux Form - Simple Example](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/v2lW2kzrn)

[How `parse` works](http://redux-form.com/6.8.0/docs/ValueLifecycle.md/).

**Comment by nealoke** [comment]
These code sandboxes really make it a breeze, thanks @erikras
