### ISSUE TITLE
Documentation (Live Web)  Immutable JS Example v6.8.0 Webpack Bundle Error 

### ISSUE THREAD

**Issue by N0taN3rd** [erikras/redux-form#3041]
### Are you submitting a **bug report** or a **feature request**?

**Bug Report**

### What is the current behavior?
![reduxformexamplesimmutablebundleerror](https://user-images.githubusercontent.com/8648317/27005330-8110de82-4dea-11e7-8d93-58c04c534aa2.png)

### What is the expected behavior?
![reduxformimuttableexpected](https://user-images.githubusercontent.com/8648317/27005354-2ea66ec2-4deb-11e7-8065-a53cefcef6e2.png)

### Sandbox Link
http://redux-form.com/6.8.0/examples/immutable/

### What's your environment?

Firefox 53.0.3 and Chrome 59.0.3071.86 (Official Build), Ubuntu 16.04 

### Other information
Just saw that you updated the project to 6.8.0 and added ``immutableProps`` to the form config :+1: 
So I went to the Immutable JS example to see if it was updated (habitual check if examples changed when the docs have changed) thus this issue.

Hope this helps in bringing a quick fix. But if no time is available to give to it I would be more than happy to address it when I myself get some time later today or tomorrow.

Love the project, thank you @erikras and contributors for the continued development

**Comment by erikras** [comment]
Yep, working on it. Same as #3038.

That's what I get for releasing late on a Friday. 🤦‍♂️
