### ISSUE TITLE
I could not find any good examples using react-bootstrap so I wrote one

### ISSUE THREAD

**Issue by aikidoshi** [erikras/redux-form#3046]
I love redux-form, but it frustrated me that I could not get a complete set of fields working properly with react-bootstrap, so when I finally did work it all out I created Steve's Opinionated React Project - https://github.com/aikidoshi/Opinionated

It is a starter kit with all of the necessary tools in place in the form of a real-world application complete with SQL Server database and a Web API as well.

It showcases beautiful redux forms, with every field type fully working.

I hope it is of use to someone, but I'm not sure how to get the word out.

**Comment by gustavohenke** [comment]
Thank you, @aikidoshi! I added it to our tools page: https://github.com/erikras/redux-form/blob/master/tools.md

P.S.: This needs to be more visible 🤔
