### ISSUE TITLE
field level validation not firing validate inside field array

### ISSUE THREAD

**Issue by mathianasj** [erikras/redux-form#3047]
### What is the current behavior?
The validate function is not called on the field level when inside a field array

```jsx
const validate = value => {
console.log(validate);
return ""
}

const renderSubFields = (member, index, fields) => (
    <li key={index}>
      <Field
        name={`${member}.firstName`}
        type="text"
        component={renderField}
        valide={validate}
        label="First Name"/>
    </li>
)
const renderMembers = ({ fields }) => (
  <ul>
    {fields.map(renderSubFields)}
  </ul>
)
```

### What is the expected behavior?
I expect validate to be called to be able to validate each of the members of a field array

### What's your environment?
Chrome

**Comment by erikras** [comment]
Well, for one, your prop is called `valide` and it should be `validate`.

**Comment by mathianasj** [comment]
My actual code is correct, the sample I wrote up is incorrect

**Comment by gustavohenke** [comment]
It seems to work just fine: https://codesandbox.io/s/58j9kxPkY

Can you provide a working example? Perhaps fork from that one or from [this template](https://codesandbox.io/s/gJjDoKYWl).

**Comment by swp44744** [comment]
Hey @gustavohenke, I am still facing the issue. a normal Field level validation works fine but if the Field is part of FieldArray then field level validation does not get triggered

I tried above sandbox link you provided above: https://codesandbox.io/s/58j9kxPkY, even there I could not see validation error on screen. I tried it on chrome, firefox and safari.

**Comment by swp44744** [comment]
Nevermind I learnt from other thread where @erikras mentioned its on known bug post 6.8.0. I downgraded to 6.8.0 and its working fine now.
