### ISSUE TITLE
Cannot read property 'immutableProps' of undefined

### ISSUE THREAD

**Issue by paulocesarpcfj** [erikras/redux-form#3048]
I don't know why i'm getting this error. Someone could help how to track the problem?

Cannot read property 'immutableProps' of undefined

Thanks!

**Comment by sunnyvempati** [comment]
I have the same issue +1

**Comment by gustavohenke** [comment]
@paulocesarpcfj @sunnyvempati I assume you're doing something like this:

```js
reduxForm()(MyForm)
```

If that's the case, until a fix gets released, can you try at least do `reduxForm({})`? It should fix.

**Comment by gustavohenke** [comment]
Possible fix in #3052

**Comment by Maxilver** [comment]
> If that's the case, until a fix gets released, can you try at least do `reduxForm({})`? It should fix.

Works for me. Thanks!

**Comment by sunnyvempati** [comment]
@gustavohenke thank you!

**Comment by paulocesarpcfj** [comment]
@gustavohenke It worked for me too! Thank you very much. Should I close the issue, then or maintain opened cause of the bug?

**Comment by gustavohenke** [comment]
@paulocesarpcfj the PR #3052 closed it! But rest assured that @erikras will post an update here as soon as the fix gets released.

**Comment by MichaelDeBoey** [comment]
@erikras Any idea when this will be released? 🙂

**Comment by MichaelDeBoey** [comment]
@erikras Any idea when this will be released? 🙂

**Comment by gustavohenke** [comment]
@MichaelDeBoey I'm pretty sure that this is going to be soon. For now you can simply change your calls from `reduxForm()` to `reduxForm({})`.

**Comment by wlingke** [comment]
Any idea when this will be released? It's been almost a month

**Comment by erikras** [comment]
Fix published in [`v7.0.0`](https://github.com/erikras/redux-form/releases/tag/v7.0.0).
