### ISSUE TITLE
Form field validation based on field type

### ISSUE THREAD

**Issue by jimmccarthy** [erikras/redux-form#305]
I am fairly new to Redux and have a question on how to set up validation so that it can be reused across multiple forms.  My application will have lots of different types of forms and I would like to set up a global validator function to handle common field types like email, phone numbers, min/max length validations, dates and a bunch of other custom validations based on business login in my application (employee, contact, client type fields, etc).

I currently have an example set up where I pass in a global validation method to the form, but the only thing I have access to is the field name and value.  Is there a better way to do this where I could assign some kind of property to a form field and do the validation based on the field type rather than the field name? 

    import globalValidator from '../utils/globalValidator';
    export default reduxForm({
      form: 'testForm',
      fields: ['name', 'email', 'createDate'],
      validate: globalValidator
    })(SimpleForm); 

**globalValidator.jsx file**

    export default function globalValidator(values, props) {
    const errors = {};
          
          if (!/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i.test(values['email'])) {
            errors['email'] = 'Invalid email address';
          }
          
          //other validations
          
I would like to make this generic if possible so I could reuse it across lots of forms.

**Comment by erikras** [comment]
[This is how I do it](https://github.com/erikras/react-redux-universal-hot-example/blob/master/src/utils/validation.js).

**Comment by erikras** [comment]
[Usage here](https://github.com/erikras/react-redux-universal-hot-example/blob/master/src/components/SurveyForm/surveyValidation.js)

**Comment by jimmccarthy** [comment]
awesome, thanks.
