### ISSUE TITLE
initialValues with unregistered fields causing form dirty

### ISSUE THREAD

**Issue by aaronincincy** [erikras/redux-form#3054]
Using the latest version of Redux-Form (6.8.0) I'm experiencing an issue where if I have a form that is set to enableReinitialize = true and keepDirtyOnInitialize = true, and I have a property in my initialValues that isn't actually a registered field in the form (lets say meta1), and initialValues updates to say meta1 = 'bar' from 'foo', the form is considered dirty.  In previous versions, because the field had never been touched or changed (it wasn't even a registered field) when initialValues would update it would just update the values and the form would remain pristine.  Is this an intended change?

**Comment by danielrob** [comment]
Reproduction sandbox/steps against 7.x?

**Comment by gustavohenke** [comment]
Closing due to no response.
