### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'setIn' of undefined

### ISSUE THREAD

**Issue by iliesalex89** [erikras/redux-form#3056]
In the last release, 6.8.0, after fixing #3033( Fixed bug with INITIALIZE setting null values for deleted indices.), when I'm using the action creator for initialize with keepDirty true paramete.

 I'm receiving this error on this section of code when the newValues are reassigned

        keys(registeredFields).forEach(function (name) {
          var previousInitialValue = getIn(previousInitialValues, name);
          var previousValue = getIn(previousValues, name);

          if (deepEqual(previousValue, previousInitialValue)) {
            // Overwrite the old pristine value with the new pristine value
            var newInitialValue = getIn(newInitialValues, name);
            **newValues = setIn(newValues, name, newInitialValue);**
          }
        });

Can someone help me or the only option is to keep 6.7.0 for the moment?

**Comment by gustavohenke** [comment]
Can you please create a working version of your problem, so I can have a look?

**Comment by iliesalex89** [comment]
This will happen every time when newValues is undefined because in setIn method you call state.setIn and if newValues is null or undefined this error will apear. I think the main problem is that the code reaches this step with undefined newValues, but I don't know at this moment why or how to avoid this.

**Comment by sbeam** [comment]
also got this on existing app just after upgrade to 6.8.0 with `keepDirtyOnReinitialize`, during first render of form with no values.

**Comment by anthonator** [comment]
Did anybody figure this out? We're also having this problem with 7.0.3.

**Comment by anthonator** [comment]
We're using `keepDirty`

**Comment by gustavohenke** [comment]
~1.5 years without a comment here, so I'm closing!
If the issue persists, please open a new one while still providing as much context as possible. Thanks!

**Comment by cpopeDudley** [comment]
We are having the same issue. Was this ever addressed? We get an error when using keepDirty and perhaps on the first pass when there is no data yet.
