### ISSUE TITLE
Undocumented: Not providing an asyncBlurFields value to reduxForm() causes all fields to validate on blur

### ISSUE THREAD

**Issue by ericbiewener** [erikras/redux-form#3058]
The documentation should clarify that not providing an `asyncBlurFields` property to `reduxForm()` will cause blur events on all fields to run the `asyncValidate` function.

**Comment by gustavohenke** [comment]
If you would like to tackle this one, go ahead.

**Comment by danielrob** [comment]
Closing as the fix has been merged! Thanks!
