### ISSUE TITLE
Clearing out AutoComplete's textbox with backspace doesn't update state

### ISSUE THREAD

**Issue by kwingat** [erikras/redux-form#3059]
1. AutoComplete:
2. Make a selection => Redux state value is updated.
3. Select AutoComplete textbox.
4. Backspace values out.
5. Click anywhere else on the form => Redux state value was not updated and remains the same as the previous selection.

Because the state doesn't change syncErrors aren't added back to the component, and a user is able to submit the form with a blank AutoComplete textbox and the wrong value for that textbox.

Is this expected behavior? Is there a way around this?

**Comment by kwingat** [comment]
I just wanted to add, the example at erikras.github.io/redix-form-material-ui has two AutoComplete components on it. The first is called "cheese" and the second is "referral".

I test them and when following the steps above, "cheese" updates state when changed. However, "referral" does not.

**Comment by gustavohenke** [comment]
Can you please open your issue over the redux-form-material-ui repo, please? This doesn't seem to be directly related to Redux Form.

Thanks in advance!

**Comment by crabicode** [comment]
@gustavohenke that correct, just check the examples. It is impossible to clear the autocomplete textfield on backspace.

**Comment by crabicode** [comment]
@gustavohenke look at https://github.com/erikras/redux-form-material-ui/blob/master/src/AutoComplete.js#L28
