### ISSUE TITLE
Docs are broken with 3.0.11

### ISSUE THREAD

**Issue by joearasin** [erikras/redux-form#306]
To replicate:

Update `redux-form` dependency to 3.0.11 in gh-pages branch.
`npm install`
`npm run dev`

Getting `TypeError: undefined is not an object (evaluating 'allValues.max')` in the redux devtools.

**Comment by joearasin** [comment]
If I were to guess, in the "remove spread operators", something is probably returning undefined where it used to return an empty array or object.

**Comment by erikras** [comment]
I'm afraid I don't have time to look at this today. @yesmeck

**Comment by yesmeck** [comment]
I'll look at this.

**Comment by yesmeck** [comment]
Sorry, it't my fault, this should be fixed by PR #309.

**Comment by erikras** [comment]
I'm on a plane all day. Just stick with 3.0.10.

**Comment by joearasin** [comment]
Thanks y'all!

**Comment by erikras** [comment]
[`v3.0.12` released](https://github.com/erikras/redux-form/releases/tag/v3.0.12).
