### ISSUE TITLE
Uncaught TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by mischa-saunders** [erikras/redux-form#3066]
Rookie Dev. First time raising an issue. Apologise in advance.

Thanks for this module. Have been using for a few months and enjoying greatly. I upgraded to 6.8.0 today and got a "Uncaught TypeError: Cannot read property 'name' of undefined". Dug around and found it was erroring in /src/structure/plain/keys.js.

The relevant code is: 
```       <form onSubmit={this.props.handleSubmit(this.nextClicked.bind(this))}>
            {_.map(currentQuestions(questions, currentQuestionNumber), (question) => {
                return (
                  <div className='eachAssessmentQuestion' key={question.id}>
                    {question.text}
                    <div className='assessmentQuestionInputs'>
                      strongly disagree
                      {values.map((value) => (
                        <label key={value}>
                          <Field name={question.id.toString()}
                            component='input'type='radio' value={value} />
                          {value}
                        </label>
                      ))
                    }
                    strongly agree
                    </div>
                  </div>
                )
              }
            )}
            <button type='submit'>Next</button>
          </form>
```
A peculiarity of the behaviour is it does not happen on the first load of the form. I can answer one set of the questions but after successfully submitting and moving to the next set of questions, and then hitting submit, the error occurs (on submit but before handleClick is called). Watching it in the debugger, the first questions are received as objects but then value receives an array with a lot of undefined's in it. On 6.7.0 gets handled by getFieldList, but I don't understand the code deeply enough understand the addition made in https://github.com/erikras/redux-form/commit/0f15f932dc8865cd34e6e7212317250608c226f5 so that * keys now works with arrays* Maybe the error is just in my code, but I've reverted to 6.7.0 for now and am leaving this here for anybody else who might hit this problem, and will update if I am able to make more sense of it

**Comment by mischa-saunders** [comment]
Solution found with the help of an awesome friend! I was using numbers as the field names (`question.id.toString()`) so redux form interpreted these as array values but my numbers were database id's (not sequential) so the array contained mostly undefined values. To solve this we changed the names to `'q' + question.id` and then removed the q's for data processing later using `results = _.mapKeys(results, (value, key) => key.substring(1))`.

**Comment by ahdinosaur** [comment]
@mischa-saunders i found this today [in the docs](http://redux-form.com/6.8.0/docs/api/Field.md/), see last line below:

![redux-form-field-indexes](https://user-images.githubusercontent.com/719605/27462180-e450fe32-5812-11e7-950a-6379f2dc28ad.png)

:smile_cat:

**Comment by mischa-saunders** [comment]
Ah thanks @ahdinosaur  that makes sense now!
