### ISSUE TITLE
Show Errors on initial population from initialValues

### ISSUE THREAD

**Issue by natdm** [erikras/redux-form#3073]
I have a use case where the user is uploading data via a spreadsheet. Each column is a field, and each row is an entry in FieldArray.

I need to be able to run the `validate` function on initial load to show what was wrong on their spreadsheet after import. How can I do that?

**Comment by gustavohenke** [comment]
Just use the validation as-is.
See: https://codesandbox.io/s/Z4XYpXyJ6

In the future, please don't open usage support questions here. The GitHub should be a place for feature requests and bug reporting only.

**Comment by natdm** [comment]
Where would I post the question then?

**Comment by gustavohenke** [comment]
StackOverflow. This is written in the issue template when you click to create a new one.
