### ISSUE TITLE
Examples not working properly (6.8.0)

### ISSUE THREAD

**Issue by AlesMenzel** [erikras/redux-form#3079]
### Are you submitting a **bug report** or a **feature request**?
Bug report

### What is the current behavior?
Examples in http://redux-form.com/6.8.0/examples/simple/ does not seem to be working - values are "undefined" and when submitting the form with some values, only the 'firstName' field is alerted.

### What is the expected behavior?
Displaying selected values and getting all values upon submitting.

### Sandbox Link
http://redux-form.com/6.8.0/examples/simple/

### What's your environment?
http://redux-form.com/6.8.0/examples/simple/

### Other information
There is also a react error in the console:
<img width="1905" alt="redux-forms" src="https://user-images.githubusercontent.com/8976542/27264131-a830a418-5478-11e7-8bbc-2a300826aa6a.png">

System: Win10, Chrome 58

**Comment by erikras** [comment]
Yes. @gustavohenke, can you look into this. I spent several hours on this last week. I think it has to do with there being two copies of React imported, one from `redux-form-website-template` and the other from the example itself. I'm not sure what changed to break this. Maybe a webpack upgrade?

**Comment by gustavohenke** [comment]
v6.8.0 examples unfortunately bugged very badly.
At the time Erik tagged me here I tried to find the issue, but I couldn't 😥

I'm closing since we have newer releases whose examples work just fine.
