### ISSUE TITLE
Re-render a Field based on another Field change

### ISSUE THREAD

**Issue by filipercastro** [erikras/redux-form#3080]
Hi,

I've decided to open this issue here as the behavior does look like a bug

Background is: I need some text inputs to be visible depending on a given value of my state. This value is bound to a checkbox Field and I used its onChange listener to update the reducer.

This is my checkbox:
```
<Field
   name = "fwd"
   type = "checkbox"
   component = {this.renderField}
   onChange = {event => this.props.toggleFwd(event.target.checked)}
/>
```
And this is one of the text fields I'd like to show/hide based on the 'fwd' value:
```
<Field
  name="fwdInfo.name"
  type="text"
  component={this.renderField}
  className="fwdField"
/>
```
In the beginning of the 'renderField' helper method I have:

```
    let className = `form-group ${field.className}`;
    if (className.includes("fwdField")) {
      if (this.props.patient.fwd) {
        className.replace("hidden").trim();
      } else {
        className += " hidden";
      }
```

What's happening:
- If the page loads with the 'fwd' == false (i.e. the text fields are hidden), even if I tick the checkbox, the fields won't appear - the render method is not called!
- If the page loads with 'fwd' == true, when I uncheck the checkbox, the fields won't disappear - the render method is no called. *However*, if I focus on the text input, the render message is called and they disappear as expected. After that, if I check the checkbox again, all the fields correctly reappear, as expected.

Maybe I should not expect a Field component that is not bound to a given value to re-render when it changes - however, this behavior of rendering after I focus the text input made me wonder if there is a bug here.

actionCreator and reducer apparently are working fine:
```
export function toggleFwd(fwd) {
  return {type: TOGGLE_FWD, fwd};
}
```
```
case TOGGLE_FWD:
      return {...state, fwd: action.fwd};
```

**Comment by shengnian** [comment]
hi, did you solved? i have same problem. i have two forms on page, use the tabs to switch them, the tabs component has a 'isActived'  inner state, when click the hidden tab, the component will re-render and the 'isActived' be reset to init value, so can't show the tab panel.

**Comment by gustavohenke** [comment]
Hi @filipercastro, can you take a look whether the following example helps you?
https://codesandbox.io/s/G6klJ830J

cc @shengnian

**Comment by filipercastro** [comment]
Hi @gustavohenke, that did work! I was not aware of the formValues decorator (it seems to be new in 6.8, I was using 6.7 so far).

Sorry, should have looked a bit more into the API before raising this as a bug.

Thanks very much for your help!

**Comment by gustavohenke** [comment]
Indeed, `formValues` is a handy decorator!

But you can do it with its selector counterpart as well, `formValueSelector`, or with the selector `getFormValues` - they are just a little bit more difficult to setup via `connect()`, etc.

**Comment by shengnian** [comment]
@gustavohenke 
thanks, my scene is:

```loginForm.jsx```

```
class LoginForm extends PureComponent {

  render () {
    const { pristine } = this.props
    return (
      <div>
        <form>
          <Field
            name='email'
            label='email'
            component='input'
            validate={[required, maxLen15, minLen4]}
          />
          <Field
            name='password'
            type='password'
            label='Password'
            component='input'
            validate={[required, maxLen15, minLen4]}
          />
          <div>
            <button
              type='button'
              className='btn btn-submit btn-block'
              onClick={() => this.props.login()}
              disabled={pristine}>Login
            </button>
          </div>
        </form>
      </div>
    )
  }
}

export default reduxForm({
  form: 'LoginForm',
})(connect(
  state => ({
    ...
  }),
  {
    login
  }
)(withRouter(LoginForm)))
```



```OtherForm.jsx```

```
class OtherForm extends PureComponent {

  render () {
    const { pristine } = this.props
    return (
      <div>
        <form>
          <Field
            name='email'
            label='Email'
            component='input'
            validate={[required, maxLen15, minLen4]}
          />
          ...
          <div>
            <button
              type='button'
              className='btn btn-submit btn-block'
              onClick={() => this.props.go()}
              disabled={pristine}>Submit
            </button>
          </div>
        </form>
      </div>
    )
  }
}

export default reduxForm({
  form: 'OtherForm',
})(connect(
  state => ({
  ....
  }),
  {
    submit
  }
)(withRouter(OtheForm)))
```

the tabs component install with yarn :

```
yarn add https://github.com/freeranger/react-bootstrap-tabs
```
and the `react-bootstrap-tabs` has a inner state 'selected'

```layout.jsx```
```
class Account extends React.Component {
  render () {
        return (<Tabs
              headerClass='tab-header-bold'
              activeHeaderClass='tab-header-brand'
              onSelect={(index, title) => {
                console.log(index, title)
              }}
              className='app-main-tabs'>
              <Tab label='Login' >
                <LoginForm />
              </Tab>
              <Tab label='Other'>
                <OtherForm />
              </Tab>
              </Tabs>
        )      
```

When I click the 'Other' tab, Redux Devtools's log twice render, and the `react-bootstrap-tabs` 
inner state `selected` will be reset. if i remove the `<LoginForm />` and `<OtherForm />` worked fine
click the 'Other' tab the Redux Devtools's log d@@redux-form/REGISTER_FIELD... UPDATE_SYNC_ERRORS DESTROY
am i using is wrong?

**Comment by gustavohenke** [comment]
I could not understand your issue very well, @shengnian.

But you should check whether the tabs aren't destroying the contents - it's not because you wrote your code like that the `Tab` is actually mounting `LoginForm`/`OtherForm`.
Anyway, you can keep your state without destroying: check the [wizard example](http://redux-form.com/6.8.0/examples/wizard/).

**Comment by shengnian** [comment]
ok, i tried the wizard example,  that's a little different, two form have different redux-form name and same input form name.  i'll trying to try other solutions.  
Thank you for your help.

**Comment by gustavohenke** [comment]
Okay, closing since initial request was fulfilled.
