### ISSUE TITLE
Breaking change in 6.8.0: "Cannot read property 'immutableProps' of undefined"

### ISSUE THREAD

**Issue by MilllerTime** [erikras/redux-form#3083]
I just upgraded from `6.7.0` to `6.8.0`, and looking at the [release](https://github.com/erikras/redux-form/releases/tag/v6.8.0) I expected a seamless upgrade.

However, I am now seeing the following error on some forms, with no changes to my code following the upgrade:

```
createReduxForm.js:317 Uncaught TypeError: Cannot read property 'immutableProps' of undefined
    at Form.shouldComponentUpdate (createReduxForm.js:317)
    at [...Lots of React internals]
```

Seems the new `immutableProps` feature introduced this issue. The error is coming from [Line 308 in createReduxForm.js](https://github.com/erikras/redux-form/blob/v6.8.0/src/createReduxForm.js#L308):

```ES6
const { immutableProps = [] } = initialConfig
```

This is the only line of code in that file which relies on `initialConfig` not being `undefined`. I'm seeing the error on a form in which I'm passing all redux-form config at runtime as props instead of at "design-time". As a result, my form creator looks like this:

```ES6
// Error starting in 6.8.0
const ReduxFormContainer = reduxForm()(InnerForm);
```

If I pass in an empty object as the config, the error goes away but this shouldn't be required.
```ES6
const ReduxFormContainer = reduxForm({})(InnerForm);
```

This appears to be a breaking change.

Would changing [line 84](https://github.com/erikras/redux-form/blob/v6.8.0/src/createReduxForm.js#L84) from `return initialConfig => {` to `return (initialConfig={}) => {` be a proper fix?

**Comment by MilllerTime** [comment]
I see this has been fixed on `master`! Closing as this should no longer be an issue one a patch version is released 🙂

**Comment by petermikitsh** [comment]
Adding the empty object to the reduxForm (e.g., `reduxForm({})(...)`) worked for me. Hopefully @erikras will put out a new patch / minor release soon containing the fix :)
