### ISSUE TITLE
[v5] Redux bindActionCreators warning triggered by import * as ... when importing actions

### ISSUE THREAD

**Issue by raulmatei** [erikras/redux-form#3084]
### Are you submitting a **bug report** or a **feature request**?
Bug

### What is the current behavior?
![image](https://user-images.githubusercontent.com/1718341/27320527-5c1fc8e2-559f-11e7-90b7-d381f781636a.png)

### What is the expected behavior?
No warning from `bindActionCreators`

### What's your environment?
React 15.6.1
Redux Form 5.3.6

### Other information
See: https://github.com/reactjs/redux/pull/2279

I think the problem starts from here https://github.com/erikras/redux-form/blob/v5/src/createHigherOrderComponent.js#L2 - `__esModule` is present in the actions object.

Thanks,
Raul

**Comment by davidspiess** [comment]
Same here. A fix for 5.3.6 would be really appreciated.

**Comment by thom-nic** [comment]
I'm seeing the same behavior on redux-form v5.2.5.  
It appears this warning was introduced in redux v3.7.0: reactjs/redux@1b154e0ba79ff
Downgrading redux removes the warning.

This technically isn't a redux-form issue, babel + es6 imports is what adds the `__esModule` key into the object when its transpiled.  And redux own documentation suggests using `import * as actionCreators from 'someModule'` in this context.

**Comment by timdorr** [comment]
Reverted and pushed out in 3.7.1!

**Comment by gustavohenke** [comment]
Thanks for letting us know, @timdorr!

**Comment by raulmatei** [comment]
@timdorr thanks, confirm is fixed

**Comment by thom-nic** [comment]
Hey thanks!  I actually would not mind the warning, if it were either disabled in when `NODE_ENV=production` (like react does) or if it specifically ignored `_esModule`
