### ISSUE TITLE
Initialize from state does not work correctly anymore in 6.8.0

### ISSUE THREAD

**Issue by dg-grow-virgiliu-ratoi** [erikras/redux-form#3088]
### Are you submitting a **bug report** or a **feature request**?

Bug report

### What is the current behavior?

The example at http://redux-form.com/6.8.0/examples/initializeFromState/ does not load all the fields  when the 'Load Account' button is pressed. It works fine in version 6.7.0. We have the same behaviour in our application after we upgraded to 6.8.0.

### What is the expected behavior?
The values for all the displayed fields should be properly loaded.

### Sandbox Link

http://redux-form.com/6.8.0/examples/initializeFromState/

### What's your environment?

React: 15.6.0
Redux-Form: 6.8.0
Webpack: 2.6.1
OS: Red Hat Enterprise 7
Browser: Firefox 52.2, Chrome 58.0, IE 11.09600
Node: 7.5.0

### Other information

There is an error in the browser console when the page is loaded:
Error: Minified React error #119; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=119 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.   bundle.js:1:2466

**Comment by klk1010** [comment]
I'm still able to set `initialValues` in 6.8.0 without any issues. It must be specific to your implementation. Can you post some code snippets?

**Comment by sckoh** [comment]
I have this problem too after I updated to 6.8.0
6.7.0 is working well

**Comment by rpkrause** [comment]
I'm having similar issue after moving to 6.8.
[#3057](https://github.com/erikras/redux-form/issues/3057)

**Comment by bbenezech** [comment]
@erikras Same here. Sadly 6.8 `initializeFromState` is broken. I reverted to 6.7
Can you have a look?

**Comment by ncphillips** [comment]
I looked at the 6.8.0 example that @LachlanStuart mentioned. Looks like the build process isn't properly converting the object spread syntax

![image](https://user-images.githubusercontent.com/824015/28083693-979ed5b2-664c-11e7-81f1-434c23ef27b7.png)

**Comment by sebastienfi** [comment]
Same here !

**Comment by gustavohenke** [comment]
Anyone here mentioning about v6.8.0: can you try v7.0.1 (the last one)?
The docs seem to be working just fine now, and the jump to v7 should be painless, but I recommend you to read [the release notes](https://github.com/erikras/redux-form/releases/tag/v7.0.0) anyway.

**Comment by gustavohenke** [comment]
Since no one replied, I'll close this issue, but please let us know in case you still have bugs.

**Comment by fsmaia** [comment]
@gustavohenke I tried and the problem still exists in v7 (tried with 7.0.3).

However my problem is a little different: it happens when form is initialized but some asynchronously loaded fields still aren't mounted/registered, and when they do (initialized from state), they are loaded empty and dirty, instead of properly loaded from state.
