### ISSUE TITLE
FieldArray - field.get(index) not getting called on change

### ISSUE THREAD

**Issue by rossfishkind** [erikras/redux-form#3096]
In my example below, which is rendered as the component of a `FieldArray`, it seems that `field.get(index)` is not getting called on each input change, only some input changes.

If I change the value of one of the fields from it's original value to something new, nothing happens. However, if I change the value back to its original value (if there was one from `initialValues`), it gets called. Any ideas? Is this expected behavior? Thanks!

```
const { fields } = this.props;
    
fields.map((field, index) => {
  const values = fields.get(index);

  return (
    <div className="fields">
      <Field
        name={`${field}.units`}
        type="text"
        component={renderField}
      />

      <Field
        name={`${field}.amount`}
        type="text"
        component={renderField}
      />

      {values.units * values.amount}
    </div>
  );
});
```

**Comment by gustavohenke** [comment]
Hi @rossfishkind! Thanks for the report.
The case here is that arrays are not re-rendered "on the fly" by default.

However, v6.8.0 introduced a flag to help you in this: `rerenderOnEveryChange`. Take a look at this CodeSandbox I created for you: https://codesandbox.io/s/qDjw3zGG

Beware that this may cause performance problems, though.
In the example above I used a `PureComponent` to keep track of the real number of renderizations the component is performing.

If for some reason you can't update to v6.8.0, you can get the same result by connecting the row component with usage of the [`formValueSelector` selector](http://redux-form.com/6.8.0/docs/api/FormValueSelector.md/).

I hope I helped you!

**Comment by rossfishkind** [comment]
Ah, gotcha. Thanks @gustavohenke!
