### ISSUE TITLE
Bug related to Immutable 

### ISSUE THREAD

**Issue by uaNikita** [erikras/redux-form#3098]
### Are you submitting a **bug report** or a **feature request**?
bug report

### What is the current behavior?
With immutable array.push right now insert string "List [ ]"

### What is the expected behavior?
Example: Instead of "List [ 2, 2, 2 ]" should be "2, 2, 2".
array.push(field:String, value:Any) : Function - must work like in description in API docs

### Sandbox Link
Just type something  in any of the fields here:
https://codesandbox.io/s/Zx1DJ8Bv

**Comment by gustavohenke** [comment]
So you think that an array operation on a string is an expected behaviour?

**Comment by uaNikita** [comment]
No. This is my mistake. Thanks. I updated question.

**Comment by gustavohenke** [comment]
If you want to have the right string representation of immutable list, you should bug the Immutable.js maintainers.
Even though your example is unusual, it works the way it should. If you use plain JS instead of Immutable, the output will be the one you want.

**Comment by uaNikita** [comment]
@gustavohenke Thanks for answer.

Could you please explain why you think that this is Immutable.js bug not redux-form. Could you provide some example?

I faced this problem when I tried to change one field when user type on another. I often need to do similar things in my forms. As I understand it is exist only one way to do this - using pre-bound action creators. But in case that with Immutable.js it isn't possible to do this, is there another way to do the same thing?

**Comment by gustavohenke** [comment]
For me, what you're trying to do is to convert an Immutable list into an string.
If that's not what you wanted, then you should explain yourself better.

**Comment by uaNikita** [comment]
@gustavohenke I apologize for the long answer. And maybe I wrote the wrong question.

So I need to change one text input when user type in another. For example in one input user type "Bob" and I want copy this value to other redux-form text input in real time. 

How I can do this with redux-form when I use Immutable?
