### ISSUE TITLE
Access to field.initialValue

### ISSUE THREAD

**Issue by eventhough** [erikras/redux-form#310]
Is there any way to access the initialValue of a field? I have a situation where I re-use a form for multiple records and I need to know if the initialValue has changed or not. I know we can have multiple forms using `formKey` but I never display more than one form at a time...instead I just use initialize to swap values.

Alternatively - is there a way for a field to know when it has been initialized?

**Comment by Pegase745** [comment]
You can get easily the initial value of a field like this, however it's true that it's unclear in the API doc

```javascript
// Container.js

import Form from './Form';

export default class Container extends Component {
  render() {
    const props = {
      initialValues: {firstName: 'toto'},
    };

    return (
      <Form {...props} />
    );
  }
}
```

```javascript
// Form.js

const fields = ['firstName', 'lastName'];

@reduxForm({
  form: 'simple',
  fields,
})
export default class Form extends Component {
  static propTypes = {
    fields: PropTypes.object.isRequired,
    resetForm: PropTypes.func.isRequired,
  };

  render() {
    const {
      fields: {
        firstName, lastName,
      },
    } = this.props;

    console.log(firstName.defaultValue); // --> prints 'toto'
    console.log(firstName.value); // --> prints what you write

    return (
      <form>...</form>
    );
  }
}
```

On ```resetForm```, the initial value _toto_ is reloaded.

**Comment by eventhough** [comment]
@Pegase745 Strange I am not seeing `.defaultValue` prop on my field. Has this been tested with the latest version of redux-form? I'm on `3.0.11`.

**Comment by eventhough** [comment]
It doesn't look like we have access to the initial or default value. I've decided to go with the `formKey` route instead which generates an entirely new form + fields based on the id of my record. This seems to work fine. Plus, forms now get destroyed on unmount so there shouldn't be too many wasted resources.

**Comment by Pegase745** [comment]
although it seems possible enough here [readFields.js#L31-L32](https://github.com/erikras/redux-form/blob/51376ef32d0118a517cfa843142de4900bc758b4/src/readFields.js#L31-L32), with ```defaultValue``` telling you if the field was initialized.

**Comment by eventhough** [comment]
@Pegase745 When I tried to access `field.defaultValue` I got `undefined` back. If this isn't documented in the API, maybe it wasn't meant to be used?

**Comment by Pegase745** [comment]
I don't know, I just updated to 3.0.11 and still working for me. surely @erikras or someone else has a better explanation

**Comment by erikras** [comment]
Seems like the suggested way should work, but it would be easy enough to provide a `this.props.fields.firstName.initialValue`. I'll consider it in some field enhancement I'm working on.

**Comment by erikras** [comment]
`v3.1.0` now supports `initialValue` as stated in my previous comment.

**Comment by jole78** [comment]
@erikras  has this been removed again (v6)? I really need access to the initial value of the field as it was when the form was mounted.
