### ISSUE TITLE
deepEqual says 2 != "2"

### ISSUE THREAD

**Issue by dbraynard** [erikras/redux-form#3101]
Redux-form version: 6.8.0

deepEqual returns false for (2, "2"), or number and string that are equal.

This is causing `pristine == false` on rendering after BLUR action because the value for the field blurred has a string version of the value written.

**Comment by bessey** [comment]
well, those are indeed not equal! If you want a number to be stored in Redux, you need to [normalize  the value return by the Field](http://redux-form.com/6.8.0/examples/normalizing/)

**Comment by gustavohenke** [comment]
@bessey is correct.

**Comment by dbraynard** [comment]
@bessey, thanks for the help. I guess it makes sense for redux-form to not perform type conversions when making a comparison.
