### ISSUE TITLE
Example selectingFormValues does not work in 6.8.0

### ISSUE THREAD

**Issue by tkvw** [erikras/redux-form#3102]
Chrome Version 59.0.3071.109 (Official Build) (64-bit)
Windows 10
url: http://redux-form.com/6.8.0/examples/selectingFormValues/

![2017-06-23_18-14-58](https://user-images.githubusercontent.com/621098/27492927-3f57ce3e-5848-11e7-8ca9-59bc8e520e4c.gif)
The example does not return the expected value. See screenshot. 6.7.0 does work (http://redux-form.com/6.7.0/examples/selectingFormValues/)

**Comment by gustavohenke** [comment]
Thanks for the report.
This is likely the same as #3079; if you the CodeSandbox link, it will work as expected.
