### ISSUE TITLE
Docs feature request: When should Fields be used? 

### ISSUE THREAD

**Issue by danielrob** [erikras/redux-form#3103]
Fields is the only part of the documentation I've noticed, where the use case is not particularly explained - it is mostly clear this feature shouldn't be used! 

It is perhaps this non-clarity that led a developer on my project to use Fields to achieve conditional disabling of form fields even though this use case alone can be covered by formValueSelector as mentioned in #1960, or in the docs example. (Further, they also looped to render a bunch of Field components inside Fields - that's another story, but) I do think the documentation could be more clear here about the 'raison d'être' for Fields. 

If I understand correctly, I'd wonder if for many people, the following may be a sufficient Fields-like implementation: 
```
connect(state, ownProps) => ( 
  ownProps.names.reduce((acc, name) => {
    acc[name] = selector(state, name)
    return acc
  }, 
  {})
)
// (+ corresponding lifecycle methods). 
```

Why does Fields exist? How (often) does it differ in practice from providing inter-field value-awareness as in the above example? Might the above case be worthwhile to add to the docs (essentially a props configurable version of the [existing example](http://redux-form.com/6.8.0/examples/selectingFormValues/))?

**Comment by danielrob** [comment]
Going to close this one out. To anyone searching the issues, this would be my advice: 

`Fields` is powerful because it gives you everything. This is ok for small, trivial cases, e.g. combining 2 fields and one error label, but generally, if the use cases are larger than that, the problem can most likely be re-expressed in another way and you should re-architect your components.

Examples: 
If you are looking to `Fields` because you want:
 - to do conditional field disabling => use getFormValues selector and `Field` instead. 
 - you want all your fields to have similar wrapping (which requires meta) => use an HOC to wrap all your components (outside of the component definition). 
 - One small area of your form has say 2 input values, but otherwise is essentially one input component (e.g. say departure date, return date) => Fields can be a great option here. The performance won't be an issue.

**Comment by gustavohenke** [comment]
Thanks for that, @danielrob!
