### ISSUE TITLE
values prop not passed to form instance

### ISSUE THREAD

**Issue by wichert** [erikras/redux-form#3107]
The reduxForm() documentation states a `value` prop is passed to all instances of the decorated form component. As far as I can see that is not true. [WrapperComponent.render() explicitly removes the values prop](https://github.com/erikras/redux-form/blob/master/src/createReduxForm.js#L604) from `rest` before passing it to the decorated form.

I added a quick [codepen example](https://codepen.io/wichert/pen/wermZq) showing the issue.

**Comment by glorp47** [comment]
+1 on this

**Comment by gustavohenke** [comment]
You're making confusion around the meaning of instance vs props in React world.

Please see this amazing explanation by @martinhorsky [here](https://github.com/erikras/redux-form/issues/2101#issuecomment-261253199).
