### ISSUE TITLE
Value is missing while using Dynamic forms

### ISSUE THREAD

**Issue by Lonelind** [erikras/redux-form#311]
This was a comment to issue #261, but I decided to make a new issue from it.

I have form with two inputs that represent ```min``` and ```max``` amount. And I should generate ```(max - min + 1)``` fields when any of those two changed. The problem is that I need to get values from this field and pass correct amount of dynamic fields inside form component. It looks like this:

```jsx
// reducer.jsx
// The structure is important because I have multiple forms in my App and there will be
// three different forms inside view.form simultaneously. Alongside I must have some
// non-form data for this view and have a reducer for it.

import { reducer } from 'redux-form';

export default combineReducers({
    /* ... */
    view: combineReducers({
        form: reducer.normalize({
            generalInfo: {
                min: minNormalizer,
                max: maxNormalizer,
            },
        }),
        data: someDataReducer,
    }),
});
```

```jsx
// FormContainer

@connect((state) => ({ 
    min: parseInt(state.view.form.generalInfo.min.value, 10),
    max: parseInt(state.view.form.generalInfo.max.value, 10),
})
export default class FormContainer extends React.Component {
    render() {
        let fields = [ 'min', 'max' ];

        // fill up fields array with proper field names (the index really matters)
        Array(this.props.max - this.props.min + 1).fill(0)
            .forEach((item, index) => {
                fields.push('dynamicField' + (index + this.props.min));
            });

        return (
            <DynamicForm
                fields={fields}
            />
        );
    }
}
```

Nothing seems difficult here. 
And the next code block is where I'm not sure that I made it correctly:
 
```jsx
// DynamicForm

import { reduxForm } from 'redux-form';

@reduxForm({ form: 'generalInfo', reduxMountPoint: 'view' })
export default class DynamicForm extends React.Component {
    render() {
        const {
            fields: {
                min,
                max,
            },
            handleSubmit,
        } = this.props,

        minAmount = parseInt(min.value, 10);
        maxAmount = parseInt(max.value, 10);

        // Below I do the same trick with Array.fill to render fields
        return (
            <form onSubmit={handleSubmit}>
                Min: <input {...min} />
                Max: <input {...max} />
                {Array(maxAmount - minAmount + 1).fill(0)
                    .map((item, index) => {
                        <div key={index}>
                            <input {...this.props.fields['dynamicField' + (index + minAmount)]} />
                        </div>
                    })}
            </form>
        );
    }
}
```

The form renders successfully. I simplified the code, but default values for min and max are ```1```. And yes, I have one dynamic field. I change ```min``` and ```max``` fields and read this changes inside ```FormContainer```, so ```fields``` array is correct and I get all of them inside ```DynamicForm``` component. But I still have only one field rendered. 

Tried to fix this I've got that ```this.props.fields.max.value``` is ```undefined``` inside ```DynamicForm```. I logged ```props``` on render and on every change I get normal values from ```FormContainer``` and default ones from ```DynamicForm```. So, this means, that ```onChange``` handler works correctly and passes values to the store, and stores ```value``` prop to ```<input>```. This is how React works. But when I try to get value prop from field object I don't have it at all. ```this.props.values``` doesn't change too: it has all fields names as keys, that initialized with ```undefined```.

**Comment by Lonelind** [comment]
Found a mistake in my code: I needed to apply reducers as
```jsx
{
    view: reducer.plugin({
        generalInfo: {
            /* ... */
        },
        data: someDataReducer,
    }),
}
```

But I stiil wonder, if I can combine ```plugin``` and ```normalize``` functionality.

**Comment by erikras** [comment]
Yes, you can use both `plugin` and `normalize`.

**Comment by Lonelind** [comment]
But how? Can you provide any workaround?

**Comment by erikras** [comment]
Sorry, I scrolled to the bottom and saw that you had found a mistake and asked a simple question I could answer. :-)

Array fields is something I am working on for the next version of redux-form. So, no I can't suggest a better workaround at the moment, but your desire to do this adds to the pile of evidence that array fields are an important feature to be added.

**Comment by Lonelind** [comment]
Thanks, I asked about how to combine ```plugin``` and ```normalize```. I think, I made a solution that is applicable for me in this case. But I think, this is possible that I would need to apply both reducers to one form sometimes.

**Comment by erikras** [comment]
Can you elaborate on "apply both reducers to one form"?

**Comment by ashwinvandijk** [comment]
For future readers, I've done it this way:

`import { reducer as formReducer } from 'redux-form';
import normalizers from 'redux/normalizers';

const MY_ACTION = 'app/form/MY_ACTION';

export default formReducer.plugin({
  formdata: (state, action) => {
    switch (action.type) {
      case MY_ACTION:
        return state;

      default:
        return state;
    }
  }
})
.normalize(normalizers);`

`normalizers` is just an object with keys and their normalizers:

`import zipcode from './zipcode';
import number from './number';

const normalizers = {
  userdata: {
    user_zipcode: zipcode,
    field_for_number: number,
};

export default normalizers;`

Hope this helps someone!
