### ISSUE TITLE
formValueSelector values not updated as fields change

### ISSUE THREAD

**Issue by softweave** [erikras/redux-form#3110]
**bug report**

### What is the current behavior?
In both 6.8.0 and 6.7.0, the values returned by a formValueSelector do not change  as field values are changed.

### What is the expected behavior?
Following the formValueSelector example usage should result in selector values that get updated as their source field values change. 

For example, this code:
	GameSettingsForm = reduxForm({
	    form: 'gamesettingsForm'
	})(GameSettingsForm);

	const selector = formValueSelector('gamesettingsForm');
	GameSettingsForm = connect(
	    state => {
	        let openDateValue = selector(state, 'openDate');
	        let dueDateValue = selector(state, 'dueDate');
	        return {
	            openDateValue,
	            dueDateValue
	        }
	    }
	)(GameSettingsForm);

	export default GameSettingsForm;

results in openDateValue and dueDateValue props that always match the initial values for openDate and dueDate fields.

I need access to the current values of the openDate and dueDate fields and expected the selector would provide the in the openDateValue and dueDateValue props.

**Comment by gustavohenke** [comment]
You are probably doing something wrong. Can you show us a working example?

See, this works: https://codesandbox.io/s/r2yR3O0E

**Comment by softweave** [comment]
Your example works nicely. However, my form component is a React.Component and my code does not have a similar structure.

What did finally work for me is to invoke getFormValues in the form container's mapStateToProps function and return the resulting formValues as a property. I got the idea from the solution to this question: https://stackoverflow.com/questions/39878035/using-redux-formv-6-0-5-getformvalues-does-not-add-values-to-props

```
// component
class GameSettingsForm extends React.Component {
    render() {
        const openDate = this.props.formValues.openDate;
		...
    }
}

GameSettingsForm.propTypes = {
    initialValues: PropTypes.object.isRequired,
    formValues: PropTypes.object.isRequired,
};

export default reduxForm({
    form: 'gamesettingsForm'
})(GameSettingsForm);

// container
function mapStateToProps(state, ownProps) {
    const initialValues = {
        openDate: new Date()
    };
    const formValues = getFormValues("gamesettingsForm")(state) || {};
    return {
        initialValues,
        formValues,
    };
}

const GameSettingsFormContainer = connect(
    mapStateToProps,
    mapDispatchToProps
)(GameSettingsForm);

export default withRouter(GameSettingsFormContainer);
```

I tried doing something similar using formValueSelector, but it's value becomes undefined after the field value is changed. So, I cannot show you a working example of that.

**Comment by danielrob** [comment]
I would suggest providing a fully runnable not working example.

**Comment by softweave** [comment]
Hmm, my fully runnable example works: https://codesandbox.io/s/DkWGnrG4y
so the fault was in my code rather than redux-form.
