### ISSUE TITLE
[Multi-Select] Select and deselect remain dirty

### ISSUE THREAD

**Issue by misterbridge** [erikras/redux-form#3113]
### Are you submitting a **bug report** or a **feature request**?
Bug

### What is the current behavior?
Using a multi select 

### What is the expected behavior?
Using a multiple select (I'm using material-ui's):
1. Default form values are empty object `{}`
2. Selecting options in a multi-select put them in an array `{multiselect: [a, b]}`
3. Removing those options leave the array (empty) `{multielect: []}`

The problem is that this empty array makes the form dirty.

I tried to normalized my field returning null: well that puts a null value.
I tried to normalized my field returning undefined: onChange is not fired anymore.

I found how to fix this myself by normalizing like that:
`normalize={value => (_.isEmpty(value) ? '' : value)}`
(Got the hint from looking at how text fields handle this)

But IMO that should be in the lib.

**Comment by danielrob** [comment]
This issue relates to the adaptation of two libraries, and isn't really a bug with redux form. An empty array could be a valid value to other projects/developers. [The docs](http://redux-form.com/7.0.3/examples/material-ui/) seem to me to do a reasonable job of explaining that some adaptation might be required, and pointing to `redux-form-material-ui` which is a library for this adaptation. 

I'd suggest either propose a documentation improvement if that would help, or take a look at `redux-form-material-ui` where you could raise any adaptation issues if you found any. Your thoughts?

**Comment by gustavohenke** [comment]
I'm closing this issue since it saw no responses. 
Feel free to continue the discussion.
