### ISSUE TITLE
Feature Request: Allow `form` option to be a function

### ISSUE THREAD

**Issue by ThisIsMissEm** [erikras/redux-form#3116]
This is a feature request, and I'd be happy to write the PR for it.

At present, you can only specify the form name as a static string. This becomes awkward in some cases where you may have a base form, which is reused (e.g., a newsletter signup form), where you really have multiple different forms, but the view logic is all the same: just the onSubmit/Success and form name change.

I'd like to propose allowing `form` to be a function, so you can derive the form name from props.

E.g.,

```js
export default reduxForm({
        form: (props) => props.form,
        validate: createValidator(VALIDATION_CONSTRAINTS),
        onSubmit: (values, dispatch, { onSubmit }) => onSubmit(values),
        onSubmitSuccess: (result, dispatch, { onSubmitSuccess }) => onSubmitSuccess(result)
})(RemoteForm);
```

This way we can share the one connected component, which has all the same validation and rendering logic, but plug-in different handlers or names.

The only change here is:

```
  form: PropTypes.string.isRequired,
```

to:

```
  form: PropTypes.oneOfType([
    PropTypes.string,
    PropTypes.func
  ]).isRequired
```

And then when the `form` value is first used, use it to calculate the form name.

This would be a backwards compatible change.

At present to achieve this, you need to manually wrap ReduxForm in another HOC to dynamically pass name.

**Comment by ThisIsMissEm** [comment]
Okay, this may not be needed, I missed the note in the documentation about this:

> IMPORTANT: All of these configuration options may be passed into reduxForm() at "design time" or passed in as props to your component at runtime.

**Comment by gustavohenke** [comment]
So can we close it?

**Comment by ThisIsMissEm** [comment]
Yes, I think so.

Perhaps the only take away is to change the styling of that alert in the docs to make it more visible.
