### ISSUE TITLE
Nested field names with initialValues

### ISSUE THREAD

**Issue by damian** [erikras/redux-form#3117]
### What is the current behavior?
I want to be able to have nested field names and set their value on page load using the intialValues prop, however, the input value is not being set at all.

```
<input name="user[first_name]" type="text" value="" />
```

```
const mapStateToProps = (state) => {
  initialValues: { "user[first_name]": "Dave" }
}
```

### What is the expected behavior?
I expect the input to contain "Dave" and when the user changes this, the input to update accordingly.

```
<input name="user[first_name]" type="text" value="Dave" />
```

```
const mapStateToProps = (state) => {
  initialValues: { "user[first_name]": "Dave" }
}
```

### Sandbox Link
https://codesandbox.io/embed/j25k451xR

### What's your environment?
redux-form 6.8.0

### Other information
See above sandbox link.

**Comment by chrisborrowdale** [comment]
You'll need to format your `initialValues` correctly, as you would any other object.  For example:

``` javascript
const mapStateToProps = (state) => {
  initialValues: {
    user: {
      first_name: 'Dave'
    }
  }
}
```

You can keep your `Field` name in the same format but personally I think the dot notation looks a bit cleaner, e.g.

``` jsx 
<Field name="user.first_name" component="input" type="text" placeholder="First name" />
```

I've forked your example [here](https://codesandbox.io/s/BBvgYEMwY)

**Comment by danielrob** [comment]
Thanks @chrisborrowdale! Please also note the answer on the duplicate issue, which points out that you should use dot notation for your fieldNames.
