### ISSUE TITLE
Uncaught SubmissionError

### ISSUE THREAD

**Issue by oennen** [erikras/redux-form#3118]
### Are you submitting a **bug report** or a **feature request**?
Bug report

### What is the current behavior?
When validating on submit by throwing a SubmissionError when validation fails, I get an uncaught SubmissionError Exception in the browser console.

It seems to be an issue with redux-forms/immutable. I forked the "Submit Validation" example and modified it a bit (submit function is passed via onSubmit config property of the reduxForm decorator like option 1 described in introduction of example "Submit Validation"). It works fine when not using immutable:

https://codesandbox.io/s/R19j46ZR

But when using immutable, you´ll receive the uncaught Submission Error:

https://codesandbox.io/s/nrABwPDME

To reproduce the error, just click "Log in" without any values for username and password. All works fine using the first link without immutable and breaks in the second one.

### What is the expected behavior?
When submitting he form without any value for username and password, errors should be displayed below the field for username ("username is required.") and password ("password is required.").

### What's your environment?
react 15.5.3
react-dom 15.5.3
redux 3.6.0
react-redux 5.0.4
redux-form 6.6.3
immutable 3.8.1
redux-immutable 0.0.8

### Other information
Uncaught (in promise)
SubmissionError {errors: Object, message: "Submit Validation Failed", name: "SubmissionError", stack: "SubmissionError: Submit Validation Failed
    at e…1:1310375), <anonymous>:14:13)
    at <anonymous>"}errors: Objectmessage: "Submit Validation Failed"name: "SubmissionError"stack: "SubmissionError: Submit Validation Failed
    at eval (eval at evaluate (https://codesandbox.io/static/js/sandbox.546b6723.js:1:1310375), <anonymous>:14:13)
    at <anonymous>"__proto__: ExtendableError

**Comment by dkniffin** [comment]
I think you have to return the result of 'validate`

**Comment by oennen** [comment]
It seems that the issue has nothing to do with the upgrade from 6.6.3 to 6.8.0.

It seems to be an issue with redux-forms/immutable. I forked the "Submit validation" example and modified it a bit (submit function is passed via onSubmit config property of the reduxForm decorator). It works fine when not using immutable:

https://codesandbox.io/s/R19j46ZR

But when using immutable, you´ll receive the uncaught Submission Error:

https://codesandbox.io/s/nrABwPDME

To reproduce the error, just click "Log in" without any values for username and password.

**Comment by gustavohenke** [comment]
Yeah, this is indeed a bug - one of them works and the other don't!
Thanks for reporting it, @oennen.

**Comment by rob19xx** [comment]
Hello. We had recently the same issue. You import the submissionError from 'redux-form'.

correct and working for me (by adjusting your code) would be:

`import { SubmissionError } from 'redux-form/immutable';`

**Comment by oennen** [comment]
You´re right, I missed that point.

Thanks a lot!
