### ISSUE TITLE
Initial Values Issue When Export Component Inline

### ISSUE THREAD

**Issue by richardenelson** [erikras/redux-form#3119]
Hi,

Found a possible bug in Redux Form (v6.8.0) when trying to use initial values.  Apparently when I try and export my form component as a single inline statement, the initial values don't work.  If I take the [example](http://redux-form.com/6.4.3/examples/initializeFromState/) from the documentation, that would look like the following:

```
export default reduxForm({
  form: 'initializeFromState'
})(connect(
  state => ({
    initialValues: state.account.data
  }),
  { load: loadAccount }
)(InitializeFromStateForm))
```

The original example has it as follows:
```
// Decorate with reduxForm(). It will read the initialValues prop provided by connect()
InitializeFromStateForm = reduxForm({
  form: 'initializeFromState'  // a unique identifier for this form
})(InitializeFromStateForm)

// You have to connect() to any reducers that you wish to connect to yourself
InitializeFromStateForm = connect(
  state => ({
    initialValues: state.account.data // pull initial values from account reducer
  }),
  { load: loadAccount }               // bind account loading action creator
)(InitializeFromStateForm)

export default InitializeFromStateForm
```

Admittedly, I'm new to React/Redux, but this inline syntax was how it was taught in a top rated Udemy [course](https://github.com/StephenGrider/ReduxCasts/blob/master/blog/src/components/posts_new.js).  I don't know if this is a bug, or if you just shouldn't be doing things this way.

If this isn't enough information on the issue, please let me know and I will try provide what is needed.

**Comment by rileylnapier** [comment]
i was having the same issue... but reading through your issue made me realize what happened.

its the order of operation.

it should be this way.  you need to use redux-connect to pass the props into the form

```
export default connect(
  state => ({
    initialValues: state.account.data
  }),
  { load: loadAccount }
)(
  reduxForm({
    form: 'initializeFromState'
  })(InitializeFromStateForm)
)
```

**Comment by richardenelson** [comment]
OMG!  It's so obvious now that you point it out.  Thanks!
