### ISSUE TITLE
getRenderedComponent() method returns TextField instead of <input />

### ISSUE THREAD

**Issue by nichesoftgh04** [erikras/redux-form#3120]
When i am trying to get rendered component by using method getRenderedComponent() it returns TextField which is passed as component to Field as follows-

`<Field type="text" onKeyUp={this.focusNextField} ref="dateFieldRef" withRef maxLength="2" className="form-control zero-padding background-yellow-white" component={TextField} id="date" name="date" placeholder={Strings.day}/>`  While i pass 'input' as component in this upper snippet it just works fine since getRenderedComponent() returns input element.

I tried to access the focus method as follows-
`this.refs.monthFieldRef.getRenderedComponent().getRenderedComponent().focus();` but it fails with following error-
`Uncaught TypeError: this.refs.monthFieldRef.getRenderedComponent(...).getRenderedComponent is not a function`

I want to access the focus() method of the underlying input element.  How am i suppose to call focus() on this TextField component or i am missing something? I am using redux-form v6.6.3

**Comment by gustavohenke** [comment]
This is the correct behaviour.
Redux Form provides access to the instance of `TextField` built by `Field`.

Since we don't know about the internal structure of your component, you must add methods/properties that provide access to what you want to do.

**Comment by romseguy** [comment]
I struggled a bit with this so here's the full solution:

```
@reduxForm({...})
class Form extends Component {
  focus() {
    this.foo.getRenderedComponent().focusInput()
  }

  render() {
    return (
      <Field
        name="foo"
        component={CustomField}
        type="text"
        ref={node => { this.foo = node }}
        withRef
      />
    )
  }
}
```
and
```
class CustomField extends Component {
  focusInput() {
    this.input.focus()
  }

  render() {
    const {
      input,
      type
    } = this.props

    return (
      <UIForm.Field error={error !== undefined}>
        <input {...input} ref={node => this.input = node} type={type}/>
      </UIForm.Field>
    )
  }
}
```

**Comment by gear54rus** [comment]
@gustavohenke the thing above needs to be in docs, it really puts things into perspective.

@romseguy thanks!

**Comment by gustavohenke** [comment]
Can you come up with a good idea on how to do this? If so, please submit a PR!

It is difficult for me to understand how the docs around refs could be improved -- I don't remember having the [surprise moment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) when I first needed to use them *because I knew how they worked*.

**Comment by havinhthai** [comment]
@romseguy 
It toggle keyboard while move from TextInput 1 to TextInput 2 and make bad UX.
I tried a lot of way but can fix this issue
