### ISSUE TITLE
props.change(fieldName, newValue) doesn't work on array field

### ISSUE THREAD

**Issue by fyang1024** [erikras/redux-form#3122]
The use case is I want to change Field B's value when Field A's value gets changed. Both Field A and B holds a value of an object in an array.  Say, Field A's name is "person[0].id", Field B's name is "person[0].firstName". When "person[0].id" Field value is changed to 1, in the onChange handler I call props.change("person[0].firstName", "Sam") 

### What is the current behavior?

Current behavior is the "person[0].firstName" Field value is not changed to "Sam"

### What is the expected behavior?

"person[0].firstName" Field value is changed to "Sam", 
and { person: [ { id: 1, firstName:"Sam" } ] } should be in the values object

**Comment by danielrob** [comment]
Could you provide a sandbox reproduction of this issue?

**Comment by fyang1024** [comment]
Hi Daniel, somehow I have got it work now. It was probably my own bug. Sorry about that. This issue can be closed
