### ISSUE TITLE
Touched on field array not set when touching a field

### ISSUE THREAD

**Issue by terencechow** [erikras/redux-form#3123]
### Are you submitting a **bug report** or a **feature request**?
**bug** ?

### What is the current behavior?
Touching a field on the field array sets the field to be touched but the `meta.touched` for the `renderArray` stays false. For example, go to [the example page](http://redux-form.com/6.6.3/examples/fieldArrays/) and click Add Member, then click a member field.

Looking in the redux state you can see member 0 has `firstName` touched.

However the code says that if `touched` is true on the `renderMembers` function then it should display the error message: `At least one member must be entered`.

Hence touched is staying false in the `renderMembers` function.

### What is the expected behavior?

I want it touched to be true on the `props.meta.touched` of the `renderMembers` function because intuitively if a fieldArray has been touched, the touched field should be true. For my use case I want to display a `members._error` when the user has touched a field. 

### What's your environment?
redux form 6.6.3, chrome, osx,

**Comment by gustavohenke** [comment]
`meta.touched` isn't a [documented prop of `FieldArray`](http://redux-form.com/6.8.0/docs/api/FieldArray.md/#meta-props).

Also, if you try to submit the form without adding a member, that message will appear (well... not exactly in v6.8.0, but that version has its own bugs).

**Comment by eladlevy** [comment]
I have encountered the same issue, seems like using `submitFailed` field that passed on `meta` do the trick.

It's not documented yet, but it is used in the [fieldArrays](http://redux-form.com/6.8.0/examples/fieldArrays/) example

**Comment by danielrob** [comment]
@eladlevy thanks, I've raised a PR for the docs update. It seems unclear that there is any outstanding work to do with this issue. Feel free to clarify otherwise, I'll close in the meantime.

**Comment by t3h2mas** [comment]
I wanted to use `touched` on a field array to show a 'at least one field required' message.


My workaround was using the `pristine` (you could use `dirty`) of the parent element so the error message only shows if the user starts editing the form.

`<FieldArray ... parentPristine={pristine} component={renderStuff} />`
and
```
const renderStuff = ({ ... parentPristine, meta: { error }}) => (
...
    {(!parentPristine && error) ? <span>{error}</span> : null}
...
)

**Comment by danielpowell4** [comment]
The [7.4.2](https://redux-form.com/7.4.2/examples/fieldarrays/) example suggests using the combo of `meta: { submitFailed, error }` rather than touched

Depending on your use case, using the `rerenderOnEveryChange` prop may also help get the behavior you are after!
