### ISSUE TITLE
Problem with initialValues, empty input controls on form initialization

### ISSUE THREAD

**Issue by ikresoft** [erikras/redux-form#3126]
### What is the current behavior?

http://jsbin.com/xaqamomiku/edit?html,js,console,output

### What is the expected behavior?
Default values into input controls from initialValues

### What's your environment?

JSbin example have included scripts with versions

**Comment by danielrob** [comment]
Mount the form reducer under 'form'. 

http://jsbin.com/wewiguxoqe/5/edit?html,js,console,output
