### ISSUE TITLE
Input file not work

### ISSUE THREAD

**Issue by marlonmleite** [erikras/redux-form#3127]
I'm trying to create input type="file" and it does not work at all.

I have already tried several implementations, i already visualized several issues and apparently this latest version is in trouble. Here's a simple example:

```javascript
import React from 'react'
import { Field, reduxForm } from 'redux-form'

export const FileUpload = (props) => {
  const { handleSubmit } = props
  const onFormSubmit = (data) => {
    console.log(data)
  }

  return (
    <form onSubmit={handleSubmit(onFormSubmit)}>
      <div>
        <label>Name</label>
        <Field name="name" component="input" type="text" />
      </div>
      <div>
        <label>Profile Picture</label>
        <Field name="profile_pic" component="input" type="file" />
      </div>
      <button type="submit">Submit</button>
    </form>
  )
}

export default reduxForm({
  form: 'fileupload'
})(FileUpload)
```

Can anyone use it?

It's needing example in the documentation.

**Comment by marlonmleite** [comment]
My problem was with Redux DevTools which was not showing the state of the file information. Now it's working :)

**Comment by LawynnJana** [comment]
I'm having an issue with very similar implementation of Field with component="input" type="file. I get a DomException: Failed to set the value property... Did you encounter this issue, and if so how'd you go about solving it? 

Thanks
