### ISSUE TITLE
Why error prop is undefined when fieldLevelValidation

### ISSUE THREAD

**Issue by borm** [erikras/redux-form#3129]
http://redux-form.com/6.5.0/examples/fieldLevelValidation/

Open https://codesandbox.io/s/2WP4BgjA
open console
submit form with empty values

![2017-06-29 18 12 07](https://user-images.githubusercontent.com/4027842/27695050-86447f1a-5cf6-11e7-8a28-b67c417f1443.png)

How get all errors?

**Comment by gustavohenke** [comment]
This is how it's supposed to work. `error` prop only contains _a general error of the form itself_.
[Source for this](http://redux-form.com/6.8.0/docs/api/Props.md/#-error-any-)

To do what you want, you'll need to use the selectors `getFormSyncErrors`, `getFormAsyncErrors` or `getFormSubmitErrors`, depending on the source of errors you want.
[Selectors docs](http://redux-form.com/6.8.0/docs/api/Selectors.md/)

In case you need all errors from all sources, combine them all, eg

```js
export default connect(state => ({
  allErrors: Object.assign(
    {},
    getFormSyncErrors(...),
    getFormAsyncErrors(...),
    getFormSubmitErrors(...)
  )
})(MyForm)
```

**Comment by borm** [comment]
@gustavohenke, it is great, thank
but
i want merge allErrors with default error props and get it 
https://github.com/erikras/redux-form/issues/2997
```
componentWillReceiveProps(props) {
      console.log(props.error);
```

in all forms, it is possible?
