### ISSUE TITLE
Wrong handling of initial values for input names like "photo[front]", "photo[back]"...

### ISSUE THREAD

**Issue by xenongattz** [erikras/redux-form#3130]
### What is the current behavior?
```
// Somewhere in render()
<Field name='measurement[weight]' component={FormInput} />

// ...

// Set initial value for field 'measurement[weight]'
const reduxFormHOC = reduxForm({
  form: 'instructionsDayZero',
  initialValues: {
    'measurement[weight]': 62
  }
})
```

### What is the expected behavior?
Init this field with the value I set

### What's your environment?
"react-redux": "^5.0.4",

**Comment by bmv437** [comment]
redux form supports dot notation within the field name prop. that means that `measurement[weight]` will get interpreted as `measurement.weight`

I whipped up a codesandbox to show how it works. it's one of the core principles of redux form.
Screenshot:
![image](https://user-images.githubusercontent.com/1403707/27713836-89dc4464-5cfb-11e7-91a5-b6877b4adf8e.png)

CodeSandbox -> https://codesandbox.io/s/jk88gkml

**Comment by gustavohenke** [comment]
Your issue is the *exact same one as #3117*, which was opened just 2 days ago...
