### ISSUE TITLE
Why is valid = true when value is empty and required attribute is set?

### ISSUE THREAD

**Issue by binarykitchen** [erikras/redux-form#3135]
Pretty self explanatory. IMO meta.valid shoudn't be true when input value is an empty string and its required html attribute is set.

**Comment by binarykitchen** [comment]
To be exact, it only happens when form is rendered for first time. After that, it works fine.

**Comment by gustavohenke** [comment]
The `required` attribute doesn't really matter to Redux Form at the moment (see #1723 - still open!).
All validation runs using either form-level `validate` function or field-level `validate` prop.

Also, the validation should be one of the very first things to run on the Redux store; therefore, your setup must have something wrong to be causing the issue you state.

**Comment by binarykitchen** [comment]
ah, good, thanks - also have found the cause of the issue i stated in my own code. all good.
