### ISSUE TITLE
👉 HELP WANTED: Flow Debugging 👈

### ISSUE THREAD

**Issue by erikras** [erikras/redux-form#3142]
This issue is for feedback and collaboration to figure out how to get Flow working with `redux-form`.

If you'd like to help, install the latest alpha version, see what problems arise and suggest a solution.

## `7.0.0-alpha.1`

I'm using `flow-copy-source` to copy all the `src/**/*.js` files into `lib/**/*.js.flow`, but it's not working great from what I can tell, and I need suggestions of what to do.

I took great pains to write `index.js.flow` and `immutable.js.flow` with `declare export var` syntax, but that seems incompatible with `flow-copy-source`. Help!

**Comment by gustavohenke** [comment]
Any chance of making TypeScript folks happy with this one as well?

I never saw anyone complaining about redux-form not having Flow typings, but TS...

**Comment by erikras** [comment]
@gustavohenke I, personally, don't feel like investing the time in TS, but the work I've done in Flow should make it very easy for a TS expert to come along and copy the types.

**Comment by jorrit** [comment]
A quick Google search results a number of TS to Flow converters but none the other way around.

**Comment by erikras** [comment]
@jorrit Yes, that was the sense that I got, and the basis for my position on the matter.

**Comment by kristian-puccio** [comment]
thejameskyle wrote a flow to ts converter I think...

But I know both to some degree and they are so similar it wouldn't take long at all to convert. I'll give it a go when this stabilises.

**Comment by erikras** [comment]
Heh, and here's the other reason I chose to prioritize Flow.

[![adopting-flow-and-typescript-graph](https://user-images.githubusercontent.com/4396759/27786164-5dbb33d0-5fe0-11e7-9e89-f1843dedf7cc.png)](http://thejameskyle.com/adopting-flow-and-typescript.html)

**Comment by stunaz** [comment]
types for typescript already exists: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/redux-form

**Comment by erikras** [comment]
@stunaz 😡 That would've come in handy as a reference when I was doing the Flow stuff. 🤦‍♂️

**Comment by erikras** [comment]
[`v7.0.0`](https://github.com/erikras/redux-form/releases/tag/v7.0.0) has been released.

**Comment by stunaz** [comment]
Well, how can we than import those types?
I tried `import type { FormProps } from 'redux-form';`, but it is not there.
