### ISSUE TITLE
throw Error when using onChange in ReactNative

### ISSUE THREAD

**Issue by hoangnm** [erikras/redux-form#3153]
### Are you submitting a **bug report** or a **feature request**?
**bug report**

### What is the current behavior?

When using onChange like this:

```
const CustomComponent = (props) => {
  const value = props.input.value;
   return (
      <Text>{value}</Text>
      <Button onPress={() => props.input.onChange(value + 1)} />
   );
};
```

```
<Field
  name='field1'
  component{CustomComponent}
  onChange={() => {}}
/>
```
It will show error in react-native:
![simulator screen shot jul 6 2017 7 04 32 am](https://user-images.githubusercontent.com/3433611/27889949-fc21d14c-6219-11e7-9cf3-bad1316fa53a.png)

Although it works fine in web.

### What is the expected behavior?
It should work fine in both react-native and web.

### What's your environment?
* redux-form: v6.8.0.
* react-native: v0.42.3.

### Other information
From what i see in redux-form source code, the handleChange function in ConnectedField.js is trying to merge the event to the object.
```
if (onChange) {
        onChange(
          {
            ...event,
            preventDefault: () => {
              defaultPrevented = true
              return event.preventDefault()
            }
          },
          newValue,
          previousValue
        )
      }
```
but if the **event** param is a primitive value, then it can not be merged on react-native and will throw the error.

**Comment by ahwatts** [comment]
I'm also seeing a similar error using `onBlur`:

<img width="144" alt="android_emulator_-_nexus_6p_api_25_nougat__5554" src="https://user-images.githubusercontent.com/308758/28180808-45cbd454-67d4-11e7-857c-456f52de3c21.png">

Which ultimately is because in this case, the `event` parameter is a proxy, and React Native's polyfills don't allow that.

**Comment by erikras** [comment]
Published fix in [`v7.1.0`](https://github.com/erikras/redux-form/releases/tag/v7.1.0).

**Comment by Vishal1419** [comment]
I got the same error when using redux: 3.7.2 and redux-form 7.3.0

**Comment by gustavohenke** [comment]
@Vishal1419 please open a new issue with a sandbox that reproduces it.
