### ISSUE TITLE
How to make localisation for validation errors?

### ISSUE THREAD

**Issue by RomanSarder** [erikras/redux-form#3155]
Guys, just curious about possibility to somehow pass language option to redux-form validator in order to make them throw errors on different languages depending on language. I hold language in my redux state. Is it possible?

**Comment by danielrob** [comment]
The developer provides both the `validate` function either at the [form level](http://redux-form.com/6.8.0/docs/api/ReduxForm.md/#-validate-values-object-props-object-errors-object-optional-) or at the [field level](http://redux-form.com/6.8.0/docs/api/Field.md/#-validate-value-allvalues-props-error-optional-) and controls the way that the output error is rendered through the component / renderFunction provided to one of the connecters (`Fields` / `Field`).

Thus the developer has full control to treat the returned validation strings as i18n keys, and resolve the required translations using their chosen i18n system inside their field. 

Here is a sandbox example: 
https://codesandbox.io/s/QW3WJOko7

**Comment by erikras** [comment]
Closing this based on @danielrob's excellent explanation.
