### ISSUE TITLE
Material UI example doesn't work, please make it clear there is a redux-form-material-ui repo available

### ISSUE THREAD

**Issue by fallanic** [erikras/redux-form#3156]
### Are you submitting a **bug report** or a **feature request**?
Both I guess

### What is the current behavior?
The Material UI example in the doc doesn't work, and would lead to unnecessary boilerplate code anyway since you guys created `redux-form-material-ui`.
Please point to https://github.com/erikras/redux-form-material-ui#usage instead

### What is the expected behavior?
The example should work, *and* we should point to the helper package in any case.

### Sandbox Link
http://redux-form.com/6.8.0/examples/material-ui/
Click on the select input to chose a color, it won't work.

### What's your environment?
Whatever is used in the doc, 6.8.0 I'd assume.

### Other information
I was almost able to create my own SelectField wrapper for my project but I still had a super weird issue with the `onChange` prop, and it's only after a couple hours that I noticed there was an existing `redux-form-material-ui` repo. 
With `redux-form-material-ui` it took me 5 minutes to set it up, I wish I saw that right away, I wouldn't even have tried to develop my own.

Thanks, and thanks for developing these material-ui helpers, it was  a great idea.

**Comment by danielrob** [comment]
As far as I can tell [the material ui example now works](http://redux-form.com/7.0.3/examples/material-ui/) against 7.0.3, and has for some time pointed to `redux-form-material-ui` at the end of the third paragraph. 

Perhaps you could suggest (ideally with a PR) an appropriate place where you might've found it much clearer to see the reference?

Note there is the desire to separate concerns. The redux-form example acts as an example for how to write the adaptors in the case that people would choose not to use `redux-form-material-ui`.

**Comment by fallanic** [comment]
Indeed the example works with 7.0.4 now 👍

I'm sure the end of the third paragraph would be good enough, maybe we can restore this?

Totally agree with your last point, we need both an example of custom implementation and a link to the [ready-to-go helpers](https://github.com/erikras/redux-form-material-ui#usage).

**Comment by LeoLozes** [comment]
It would be nice to update the example of material-ui, right now it's using the version 0.17 that is now probably 2 years old. 
Material-UI was overhauled last year and now it's on v1 (currently 1.4.0). 
Redux-form-material-ui seems quite abandoned, so at least a working example here would be useful.
