### ISSUE TITLE
redux-form/examples/wizard requires Node.js >= v8.0.0

### ISSUE THREAD

**Issue by ltfschoen** [erikras/redux-form#3157]
### Are you submitting a **bug report** or a **feature request**?

**bug report**

### What is the current behavior?

I cloned redux-form repo, changed into the examples/wizard directory, used Node Version Manager (NVM) to switch to Node.js version v6.6.0, and tried to install the dependencies following the instructions in the wizard Readme.md

```
$ git clone https://github.com/erikras/redux-form/
$ cd redux-form/examples/wizard/
$ nvm install v6.6.0
$ nvm use v6.6.0
$ npm install
```

but doing so returns errors:
```
...

> redux-form@6.8.0 test /Users/Me/code/clones/redux-form
> mocha --compilers js:babel-register --recursive --recursive "src/**/__tests__/*" --require src/__tests__/setup.js

module.js:457
    throw err;
    ^

Error: Cannot find module 'babel-register'
```

So switching to a newer version like 6.9.1 or 7.1.0

```
$ nvm install v6.9.1
$ nvm use v6.9.1
$ npm install
```

doing so returns error:
```
> redux-form@6.8.0 test:flow /Users/Me/code/clones/redux-form
> flow check

sh: flow: command not found
```

Only when I use v8.0.0 does it compile correctly and I can run the server:

```
$ nvm install v6.9.1
$ nvm use v6.9.1
$ npm install
```

```
 [814] multi babel-polyfill ./src/index 40 bytes {0} [built]
    + 800 hidden modules
up to date in 57.486s
```

```
$ npm start
```

```
> @ start /Users/Me/code/clones/redux-form/examples/wizard
> node devServer.js

Listening at http://localhost:3030
webpack built fa65b9d2a8fcd393dad3 in 7902ms
```

### What is the expected behavior?

For a new user following the Readme instructions, it shouldn't result in error. Some users may not realise how to overcome the error.
Currently the Readme does not specify that a minimum Node.js version is required.
If the Readme instructions included an additional step of requesting the user to install minimum Node.js version 8.0.0 and giving them the option of installing NVM and using it to install and switch to Node.js v8.0.0, then users would likely be up an running without errors.

A good **solution** would be to recommend users use NVM, and then just include a .nvmrc file in the project root directory that contains the minimum version required (i.e. `8.0.0`), so that way it will automatically install Node.js 8.0.0 when the user runs `npm install`.
This may be a good practice to adopt for all the other example repositories.

Alternatively you could just add to package.json `"engines" : { "node" : ">=8.0.0" },`, but this doesn't seem to help guide the user automatically.

### What's your environment?

macOS v10.11.5
Node v6.6.0
Node v6.9.1
Node
Node v8.0.0

**Comment by gustavohenke** [comment]
Since the PR #3159 was meant to close this issue, I'll do that now :)
