### ISSUE TITLE
Checkbox unchecked state has empty string value when initialValues is set

### ISSUE THREAD

**Issue by lightwave** [erikras/redux-form#3162]
### Are you submitting a **bug report** or a **feature request**?

This is a bug report.

### What is the current behavior?

When initialValues is set for a form's checkbox field, the uncheck state will have an empty string value. You can see the example at https://codesandbox.io/s/mQovglORR

Uncheck the "employed" checkbox in the sandbox demo and you'd see the value become an empty string.

### What is the expected behavior?

The expected behavior is to have false as the value when the check box is uncheck. It works when no initialValues is set.

### Sandbox Link

https://codesandbox.io/s/mQovglORR

### What's your environment?

redux-form 6.7.0 and 6.8.0 are both broken.

**Comment by klk1010** [comment]
I'm seeing the same thing when I copy over the [example from the docs](http://redux-form.com/6.8.0/examples/simple/) - defaults to v6.6.3. It seems to work as expected in v6.6.3, but not in v6.7.0 or v6.8.0.

**Comment by kinyat** [comment]
I also noticed this issue.
The current work around is the use parse to do `parse={value => !!value}`.

**Comment by davidgomes** [comment]
I can confirm to be able to reproduce this issue.

**Comment by danielrob** [comment]
This is the direct result of #2857.

**Comment by danielrob** [comment]
[![Edit Redux Form - Simple Example](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kZvpkml0X) - 7.0.3 sandbox.

**Comment by lightwave** [comment]
7.0.3 is still broken.

**Comment by pmg103** [comment]
7.0.4 is still broken

**Comment by erikras** [comment]
Fixed by #3482.

**Comment by erikras** [comment]
Published fix in [`v7.1.0`](https://github.com/erikras/redux-form/releases/tag/v7.1.0).
