### ISSUE TITLE
embedded examples in doc (v6.8.0) not working

### ISSUE THREAD

**Issue by wesley6j** [erikras/redux-form#3165]
Examples in current(6.8.0) doc does not work. 

For instance, this [page](http://redux-form.com/6.8.0/examples/simple/) outputs an error in the console:

![image](https://user-images.githubusercontent.com/4378997/27989267-5c712320-640b-11e7-8994-b140f8e7e4ff.png)

**Comment by LouisJS** [comment]
Bump. It still an issue. 👍

**Comment by gustavohenke** [comment]
We're very likely not going back on this issue. It's difficult to rebuild the docs/examples.

Please use the "Open in sandbox" link on each example page, as these seem to work.
