### ISSUE TITLE
Verbose Older Doc Version Warning Banner

### ISSUE THREAD

**Issue by MikeShi42** [erikras/redux-form#3166]
### Are you submitting a **bug report** or a **feature request**?
**Feature Request**

### What is the current behavior?
Browsing older versions of docs does not display a banner warning the user that they're reading an outdated version of Redux Form.

### What is the expected behavior?
When landing on a version of docs that is not the latest release, warn the user with a banner on the top prominently telling them that this version of the doc is out of date, and that they can check out the latest docs for the page they're looking at.

### Sandbox Link
http://redux-form.com/6.0.0-alpha.4/examples/syncValidation/

This was the first link surfaced when googling for redux form sync validation.

### What's your environment?
N/A

### Other information
N/A

**Comment by gustavohenke** [comment]
Thanks for the suggestion! This was already suggested before in #3007, but I believe this one is more detailed 👍

**Comment by MikeShi42** [comment]
Thanks for pointing that out! I tried to do a cursory search but nothing surfaced unfortunately (I guess I'm not looking hard enough). 

Was curious what would be a reasonable technical implementation for this, was considering a PR but didn't even know where I'd start with this.

**Comment by gustavohenke** [comment]
I don't know what the "cool docs" are doing these days regarding the banner itself... but the branch to change is definitely `gh-pages`.

You'll see directories for every version released since `4.2.0`. Those should probably be changed manually, but you can also try to do something with the script that automates the docs generation:
https://github.com/erikras/redux-form/blob/gh-pages/src/publish.js

**Comment by MikeShi42** [comment]
I don't think I'll have the bandwidth right now but if anyone happens to come across this (or notes for future self) my thinking right now is to.

Pass on the current version somewhere around here, so it can be referenced inside the webpage rendering code: https://github.com/erikras/redux-form/blob/8dcec7241f11e38ab760c527cc223a75ee6d4a35/src/publish.js#L49-L55

I'd imagine as a hacky MVP, to hard code what "current" means.

Render the banner with some associated logic around this line: https://github.com/erikras/redux-form/blob/0c1333f835653962bdc4c2d90ff9a6e72c0bf947/src/components/App.js#L25

**Comment by gustavohenke** [comment]
This was implemented and the docs were published with the banner for a few months now 🎉
