### ISSUE TITLE
Custom onChange event doesn't trigger Field instance api update

### ISSUE THREAD

**Issue by ManyStylez** [erikras/redux-form#3167]
### Are you submitting a **bug report** or a **feature request**?

**bug report**

### What is the current behavior?

With the following Field component code below wired up to a redux-form instance the Field instance api isn't updated as you interact with the field component.

Checking the props passed to the wrapping component on each render the props, 'dirty', 'pristine' are not updated as you would expect.

If i remove my custom onChange function the behaviour returns as expected.

With or without the custom onChange event, the redux store is updated and the redux-form actions crreators FOCUS, BLUR and CHANGE are firing as you would expect with the correct values.

```
<Field
  name='name'
  id='name'
  placeholder='Name'
  label='Stuido user name'
  onChange={(event) => {
    updateName(event.target.value);
  }}
  component={this.textField}
/>
```

### What is the expected behavior?
I would expect the forms condition flags to be updated to reflect the users interaction with the form.

### What's your environment?

N/A

### Other information

N/A

**Comment by danielrob** [comment]
Thanks for taking an interest in redux form! 

It looks like you're not quite using the api in the intended fashion. An `onChange` prop put on the `Field` will simply become a standard passthrough prop, passed to `this.textField`. 

If you wish to intercept the `onChange` function in the `Field` connector, then you'd do something like this in `this.textField`:

```
let myName = 'Daniel'

const updateName = (name) => { 
  myName = name 
}

this.textField = ({ input, meta, ...custom }) => (
   <input onChange={e => {
     input.onChange() // call the onChange function passed to you by `Field` this will update pristine, dirty values. 
     updateName(e.target.value) // call your other side effect function
   }}
)
```
Please refer to http://redux-form.com/6.8.0/docs/api/Field.md/#props

**Comment by ManyStylez** [comment]
Thanks for the point in the right direction, helped a lot!

When triggering the ```input.onChange()``` you do need to pass the original ```event```

**Comment by gustavohenke** [comment]
@danielrob is right. The `onChange` prop in a `Field` won't make a difference to the Redux Form behaviour.

Also, since you gave no further input, I'm closing the issue due to inactivity.

**Comment by ManyStylez** [comment]
@danielrob thanks for the update, I have this working as expected now. Doc's a little unclear.

**Comment by pawarvijay** [comment]
Thanks @danielrob 

This is how i used fully

```
const renderTextField = ({
                         input,
                         label,
                         type,
                         meta: {touched, error, warning}
                     }) =>
                        <div>
                            <label>
                                {label}
                            </label>
                            <div>
                                <input {...input} placeholder={label} type={type}/>
                                {touched &&
                                ((error &&
                                <span>
                                {error}
                              </span>) ||
                                (warning &&
                                <span>
                                  {warning}
                                </span>))}
                            </div>
                        </div>


class FieldLevelValidationForm extends React.Component {

    constructor(props) {
        super(props);
        this.state = {}
    }

    submit = (values) => console.log(values)

    handleOnChange(propertyName, event) {
        if (event && event.target) {
            this.setState({[propertyName]: event.target.value}); //For Input And Radio
        }
        else {
            this.setState({[propertyName]: event});//For Date
        }
    }

    render() {
        const {handleSubmit, pristine, reset, submitting} = this.props

        return (

            <form onSubmit={handleSubmit(this.submit)}>
                <pre>{JSON.stringify(this.state , null , 2)}</pre>
                <Field
                    name="username"
                    type="text"
                    component={renderTextField}
                    label="Username"
                    validate={[required, maxLength15, minLength2]}
                    warn={alphaNumeric}
                    onChange={(e) => this.handleOnChange('postalCode', e)}

                />
                <div>
                    <button type="submit" disabled={submitting}>
                        Submit
                    </button>
                    <button type="button" disabled={pristine || submitting} onClick={reset}>
                        Clear Values
                    </button>
                </div>
            </form>
        )
    }
}

export default reduxForm({
    form: 'fieldLevelValidation' // a unique identifier for this form
})(FieldLevelValidationForm)
```

**Comment by CristhianUNSa** [comment]
@gustavohenke Has this changed in v7.0.3 ? I can't pass "onChange" prop to an external library... I may pass "onChangee" for example and it works, it will be a prop on the custom component, but library is expecting to be onChange prop. How can I make it work ? It's a simple component https://github.com/n49/react-stars . Thanks

**Comment by webmobiles** [comment]
onFocus, in normal input works ok, but in the Field redux-form,  onFocus does not work, same with  "                  input.onFocus(e);" or not, i can't see on the  console 'onFocus'
```
          <input
            onFocus={
              (e) =>  {
                  input.onFocus(e);
                  console.log('onFocus:');
              }
            }
```

maybe i'm doing something wrong ?

**Comment by webmobiles** [comment]
my problem was using {input...} and onFocus there overwritten my onFocus,  I've found the solution separating in 'myInput' all the  properties from input, except onFocus and onBlur:

[  render() {
    const {
      input,
      type,
      meta: { touched, error, warning },
    } = this.props;
    const {onFocus, onBlur, ...myInput } = input;

          <input
            onFocus={
              (e) => {
                onFocus(e);
                this.setFocus(true);
              }
            }
            onBlur={
              (e) => {
                onBlur(e);
                this.setFocus(false);
              }
            }
            {...myInput}
            type={type}
          />](url)
