### ISSUE TITLE
[Question]: redux-optimistic-ui + redux-form

### ISSUE THREAD

**Issue by olegkalyta** [erikras/redux-form#3177]
redux-optistim-ui wraps `reducer's` content into `current` entity, so my redux state looks like:
```
{
 current: {
   form
 }
}
```
That's why `redux-form` does not work from the box there. After reading some docs, i tried:
`reduxForm({ form: 'myForm', getFormState: state => state.current.form /*.myForm */ }` but it does not work. 
Did you guys experience similar situations? How do you change the path to state for redux-form?
P.S. I experimented with other project and saw, if formReducer is in the root of reducer even with random name, redux-form still works. But it does not, if reduxForm reducer is not in root.

**UPDATE:**

```
const PropertyInformationForm = reduxForm({
  form: 'loanRequestPropertyInfo',
  getFormState: state => {
    const { formReducer } = state.get('current')
    return formReducer
  }
})
```
In this way it works, as expected.

**Comment by mrsufgi** [comment]
Hey, I'm trying to integrate redux-optimistic-ui with redux-form but can't get it to work :( 
would you mind sharing your solution?

**Comment by NathanCH** [comment]
@mrsufgi were you able to solve this problem? First ensure you have you have redux-form/immutable implemented and in a working state. You'll have to remove optimistic from wrapping your combineReducers() to do this.

Next add back optimistic()

```
optimistic(combineReducers({
  form: formReducer,
}));
```

And in your reduxForm object, do what OP suggests. All you need to do here is get() the nested 'form' key. Can be simplified to this:

```
reduxForm({
  form: 'myForm',
  getFormState: (state) => {
    return state.get('current').get('form');
  },
});
```

I'm looking for a tidier solution, or considering removing redux-optimistic-ui all together though.
