### ISSUE TITLE
Stateless function rendered radio buttons are not initialized

### ISSUE THREAD

**Issue by lothisoft** [erikras/redux-form#3181]
### Are you submitting a **bug report** or a **feature request**?
Bug

### What is the current behavior?
I'm trying to initialize a radio button which uses a stateless function to render the Field.
In this sandbox below, the form is initialized using initialValues:{ sex:"male", mood:"sad"}
The radio button "male", using the Field component, is selected as expected.  The radio button "sad" which is rendered using a stateless function is not selected.

### What is the expected behavior?
Both radio buttons "male" and "sad" are selected when the form renders.

### Sandbox Link
https://codesandbox.io/s/Jq3M8pA6g

### What's your environment?
Any

### Other information
N/A

**Comment by danielrob** [comment]
You need to control the checked state. Adding: `checked={radioButtonValue === field.input.value}` prop to your input will give you what you want. (updated sandbox 
 here https://codesandbox.io/s/y8vB0DLyP)

When using simply component="input", if the type is radio, then there is a built in control much like the one above, but when providing your own component you need to manage this yourself. There is actually one exception to this: if you pass Field a `value` prop and the value is a boolean - then checked will be automatically determined for you, but this is not your case. 

Closing as the current behavior was expected given that the checked prop was absent.

**Comment by lothisoft** [comment]
In hindsight, that's an almost obvious solution.  Thank you so much for your support!
