### ISSUE TITLE
Feature request: allow props access in formValues

### ISSUE THREAD

**Issue by tyscorp** [erikras/redux-form#3182]
### What is the current behavior?
`formValues` accepts a list of strings or an object with key/value mapping.

### What is the expected behavior?
I would like for `formValues` to accept a function that takes props and returns either an array of strings or a key/value mapping.

The use case for this is in cases of using `FieldArray` where you need to prepend the keys to the field names.

This can be accomplished in user-land by doing the following:
(this implementation doesn't support multiple strings)

```js
const formValuesWithProps = (mapper) => (Component) => (props) => React.createElement(formValues(mapper(props))(Component), props);
```

And can be used like this:
```
const ComponentWithShowVat = formValuesWithProps((props) => ({
  showVat: `${props.name}.withVat`
}))(Component);
```

I think this might be worth adding to the library itself, though.

**Comment by gustavohenke** [comment]
You can already do this in a much simpler way, go with [`formValueSelector`](http://redux-form.com/7.0.0/docs/api/FormValueSelector.md/):

```js
const selector = formValueSelector('formName');
export default connect(( state, props ) => {
  const values = selector( state );
  return {
    showVat: values[ props.name ].withVat
  };
})( MyForm );
```

I don't think making `formValues` decorator more complex is something we would like to do 🤔

**Comment by tyscorp** [comment]
This is in the context of a subform using `FormSection` that can appear in many different contexts and forms. To do it like you suggest I'll have to pass the form name though many levels of components in many difference places.

**Comment by gustavohenke** [comment]
Alright, leaving open to reconsider.

**Comment by danielrob** [comment]
+1 from #3168

**Comment by danielrob** [comment]
Related #2096

**Comment by gustavohenke** [comment]
Support for this was added in [v7.1.0](https://github.com/erikras/redux-form/releases/tag/v7.1.0) 🎉
