### ISSUE TITLE
UNREGISTER_FIELD resetting entire application state.

### ISSUE THREAD

**Issue by nialloc9** [erikras/redux-form#3185]
When I submit a form and return a new promise that is resolved after validation I can see my custom action being called and setting my state. However after this I see another action called UNREGISTER_FIELD is called that resets not just  the form part of the store but all the other parts too. So instead of just resetting form it also resets register and all other state. Has anyone else seen this behaviour? 

I'm using redux-form v 6.70 with next.js.

**Comment by danielrob** [comment]
Thanks for closing this out @nialloc9!
