### ISSUE TITLE
Field-Level Validation of non-integer numbers fails in MacOS Firefox and Safari

### ISSUE THREAD

**Issue by softweave** [erikras/redux-form#3190]
### What is the current behavior?   

Open http://redux-form.com/6.7.0/examples/fieldLevelValidation/ in Mac OS Firefox (54.0.1) and enter a username and enter 22.5 in the age field. Click Submit and get a confusing validation error (see attached screenshot)   

Open http://redux-form.com/6.7.0/examples/fieldLevelValidation/ in Mac OS Safari (10.1.1 and enter a username and enter 22.5 in the age field. Click Submit and get an error message "Enter a valid value"   

### What is the expected behavior?   

Since 22.5 is a valid number within range, the submit should succeed in Safari and Firefox.

### What's your environment?   
Mac OS 10.12.5

### Other information   
When these steps are repeated in Mac OS Chrome (59.0.3071.115) the form submit succeeds.   

<img width="459" alt="firfox" src="https://user-images.githubusercontent.com/2711933/28269326-9f3c31fc-6acf-11e7-9a9d-9e211c2f2f29.png">

**Comment by gustavohenke** [comment]
That's the browser validator kicking in, and it seems like their behaviour is consistent (while Chrome allows you to use a wrong value):
https://stackoverflow.com/a/19012837/2083599

What we could is add `noValidate` prop to the `form` tag. At least this would disable browser validation, then we let redux-form deal with it.
Would that make sense?

**Comment by softweave** [comment]
Adding step="any" to my number field fixed these problems in the app I'm working on. I'm okay with closing this ticket without any redux-form changes. It might be helpful to add step="any" to your example though.
