### ISSUE TITLE
getFormNames selector does not work

### ISSUE THREAD

**Issue by achepey** [erikras/redux-form#3193]
### Are you submitting a **bug report** or a **feature request**?

bug report

### What is the current behavior?

I'm attempting to use the getFormNames selector, however I am getting a console error stating "nonNullGetFormState is not a function". 

I am using:
`myContainer = connect(state => {names: getFormNames('form')(state)})(myComponent)`

and inside my component's render function:
`console.log(this.props.names);`

### What is the expected behavior?
The names property should be available in my component. However, an error is thrown instead.

### What's your environment?

Redux Form: 7.0.0
OS: Mac OS X El Capitan (10.11.6)
Browser: Chrome 58.0.3029.110 (64-bit)
Node Version: 7.7.3

### Other information

Attached is the screen shot of my error in the console.

![image](https://user-images.githubusercontent.com/5083380/28292730-0193704a-6b16-11e7-9f53-22c5d6d90642.png)

As well, the documentation is pretty spotty when it comes to this selector. It is mentioned that we do not need to give a form name when using this selector; however, the examples in the documentation show the usage of the selector with a form name.

**Comment by achepey** [comment]
Fixed... the use case should be:

`names: getFormNames()(state)` without passing an argument to the selector for the form name... Please change this in the documentation.

Thanks

**Comment by gustavohenke** [comment]
You can do this yourself, @achepey
