### ISSUE TITLE
BUG: Unexpected CHANGE action being dispatched.

### ISSUE THREAD

**Issue by chrstntdd** [erikras/redux-form#3195]
### Are you submitting a **bug report** or a **feature request**?
**BUG REPORT**

### What is the current behavior?
Change action is being dispatched after a separate action id dispatched.

### What is the expected behavior?
Change action is not called after the action is dispatched.

### What's your environment?

+ ` "redux-form": "^6.8.0"`
+ `node v8.1.4`
+ `Chrome 59 on Windows 10`

### Other information
I'm attempting to reset a form after a condition is met. I'm going for the approach offered by [this page in the docs](http://redux-form.com/7.0.0/docs/faq/HowToClear.md/#a-you-can-use-a-href-api-reducer-plugin-the-code-plugin-code-api-a-to-teach-the-code-redux-form-code-reducer-to-respond-to-the-action-dispatched-when-your-submission-succeeds-). On one case: `POST_UPC`, the behavior is as expected, the input value clears, and all is well. However, I'm also checking for another action type, `INCREMENT_PRODUCT_QUANTITY`.  I noticed, that only on this action, Redux Form dispatches another `CHANGE` action that seems to reinitialize the value within the form field and cause the form field not to be reset. I have included the history log from the redux dev tools below. In that log, I started with an empty array, entered in a UPC, dispatching the `POST_UPC` action, the form was cleared after, then I entered in the same UPC to dispatch the `INCREMENT_PRODUCT_QUANTITY` action and for some reason a `CHANGE` event was fired.

I also have a sneaking suspicion that the `CHANGE` event in question is being fired before the `INCREMENT_PRODUCT_QUANTITY` for some reason. 

After I drilled down into the debugger a bit more I'm finding that the `INCREMENT_PRODUCT_QUANTITY` action does indeed trigger the form to be reset, but the `CHANGE` action rehydrates the form with the previous value.

![capture](https://user-images.githubusercontent.com/17863654/28296066-d9c494fe-6b33-11e7-864b-416b7260ea7a.PNG)

```javascript
// root reducer
const rootReducer = combineReducers({
  auth: authReducer,
  form: formReducer.plugin({
    // CLEAR INPUT AFTER FORM SUBMIT SUCCEEDS
    postUPC: (state, action) => {
      switch (action.type) {
        case POST_UPC:
          return undefined;
        case INCREMENT_PRODUCT_QUANTITY:
          return undefined;
        default:
          return state;
      }
    }
  })
});
```

```javascript
// other reducer
export default function(state = INITIAL_STATE, action) {
  switch (action.type) {
    case POST_UPC:
      // ADD IN NEW PRODUCT AT THE TOP OF THE ARRAY
      return Object.assign({}, state, {
        ...state,
        products: [action.payload, ...state.products]
      });
    case INCREMENT_PRODUCT_QUANTITY:
      // INCREMENT QUANTITY AND CALCULATE NEW VALUE BASED ON UPDATED QTY
      return {
        ...state,
        products: state.products.map(
          product =>
            action.payload === product.upc
              ? {
                  ...product,
                  quantity: product.quantity + 1,
                  totalValue: Math.round((product.quantity + 1) * product.value)
                }
              : product
        )
      };

```

```javascript
// action creator
export const getProductDetails = upc => (dispatch, getState) => {
  const state = getState();
  const products = state.table.products;
  if (_find(products, upc) !== undefined) {
    // IF THE PRODUCT EXISTS ALREADY
    dispatch({ type: INCREMENT_PRODUCT_QUANTITY, payload: upc.upc });
  } else {
    // IF THE PRODUCT IS UNIQUE AND DOESN'T EXIST WITHIN THE ARRAY
    axios
      .post(/**/)
      .then(res => {
        dispatch({ type: POST_UPC, payload: res.data });
      })
      .catch(err => {
        errorHandler(dispatch, err.response, AUTH_ERROR);
      });
  }
};

```

```javascript
// field component
import React from 'react';
import { connect } from 'react-redux';
import { Field, reduxForm } from 'redux-form';
import { withRouter } from 'react-router-dom';
import { getProductDetails} from '../actions';


const form = reduxForm({
  form: 'postUPC'
});

export class SearchBar extends React.Component {
  handleInputChange(formProps) {
    const inputValue = formProps.currentTarget.value;

    if (!isNaN(Number(inputValue)) && inputValue.length == 12) {
      // IF VALID UPC
      this.handleFormSubmit(inputValue);
    } else if (isNaN(Number(inputValue))) {
      // IF ANY OF THE VALUES ARE NOT NUMBERS
      alert(`Looks like you didn't quite scan the UPC. Please scan again.`);
    } else if (inputValue.length < 12) {
      // IF THE INPUT LENGTH IS SHORTER THAN 12
      console.log(`Looks too short to be a UPC. Please scan again.`);
    }
  }

  handleFormSubmit(inputValue) {
    this.props.getProductDetails({ upc: inputValue.toString() });
  }


  renderAlert() {
    if (this.props.errorMessage) {
      return (
        <div>
          <span>
            <strong>Error!</strong>
            {this.props.errorMessage}
          </span>
        </div>
      );
    }
  }
  render() {
    const { onChange } = this.props;
    return (
      <section>
        <form>
          {this.renderAlert()}
          <div className="input-group">
            <Field
              id="upcInput"
              onChange={this.handleInputChange.bind(this)}
              autoComplete="false"
              name="upc"
              component="input"
              placeholder="UPC"
            />
          </div>
        </form>
      </section>
    );
  }
}

const mapStateToProps = state => ({
  products: state.table.products
});

export default withRouter(
  connect(mapStateToProps, {
    getProductDetails
  })(form(SearchBar))
);

```

**Comment by chrstntdd** [comment]
Just to be clear, this is still an issue. I even tried a successive `dispatch(reset('formName'))` after both dispatches I switch on in the `formReducer` plugin and am experiencing the same behavior. Change events keep getting dispatched after my call to reset the form and the fields don't reset, specifically in regards to the `INCREMENT_PRODUCT_QUANTITY` action. Surely there is something I'm missing.

**Comment by chrstntdd** [comment]
For whatever reason I overlooked the possibility of a race condition causing this issue, but alas, that was the case. With a `setTimeout()` delaying the dispatch of `INCREMENT_PRODUCT_QUANTITY `, the actions are dispatched in the right order and the form resets as needed. Closing the issue now.

**Comment by erikras** [comment]
Fantastic issue reporting, though! 👍❤️

I've debugged many a problem using GH issue as [a rubber duck](https://en.wikipedia.org/wiki/Rubber_duck_debugging).
