### ISSUE TITLE
Many of the examples use a renderField helper fuction which forwards the named "label" attribute to the "placeholder" attribute

### ISSUE THREAD

**Issue by bradywatkinson** [erikras/redux-form#3197]
If the renderField component is in a different file and the developer is not familiar with this attribute forwarding, it makes it hard to debug why certain attributes (specifically placeholder) seem to not be set.

example from: http://redux-form.com/7.0.0/examples/fieldLevelValidation/
```
const renderField = ({
  input,
  label,
  type,
  meta: { touched, error, warning }
}) =>
  <div>
    <label>
      {label}
    </label>
    <div>
      <input {...input} placeholder={label} type={type} />
      {touched &&
        ((error &&
          <span>
            {error}
          </span>) ||
          (warning &&
            <span>
              {warning}
            </span>))}
    </div>
  </div>
```

**Comment by danielrob** [comment]
I think understanding props and how they get passed falls into the [first comment in the getting started guide](http://redux-form.com/7.0.0/docs/GettingStarted.md/#getting-started-with-code-redux-form-code-) - "it's recommended to have basic knowledge of React". 

Also, it seems a useful default that the label is the placeholder. 

An alternate option would be to have the placeholder prop with it's default parameter assignment to label: 

```
const renderField = ({
  input,
  label,
  placeholder = label,
  type,
  meta: { touched, error, warning }
}) =>
```
but I'm not convinced that beginners would be any more clear on a default param behaviour than they would be on understanding props? 

If I've misunderstood, or you feel like the documentation should be updated in some specific way, please feel free to provide more information.
