### ISSUE TITLE
sync Errors does not get updated after reinitialize

### ISSUE THREAD

**Issue by bardiainjast** [erikras/redux-form#3198]
### Are you submitting a **bug report** or a **feature request**?
bug

### What is the current behavior?
i have a form which initializes with initialValues props . by default it has sync errors in form reducer, after reinitializing errors still remain in my form so on submit (remote submit) it shows validation errors under my fields .

component did mount and everything in very begining

![download 1](https://user-images.githubusercontent.com/20615964/28306350-3b89de6c-6bb4-11e7-82a2-e007eeaa8e8c.png)

form reinitialized using initialize action creator (also tried blur and change and the same issue)
![download 2](https://user-images.githubusercontent.com/20615964/28306400-653baa6a-6bb4-11e7-92b8-b6ee65c3fd5a.png)

remote submit using another form and errors appear

![download 3](https://user-images.githubusercontent.com/20615964/28306458-9d06161a-6bb4-11e7-86df-854d6a28bdfd.png)

changed only one field and all validation errors are gone ! and form in store does not have a sync errors field
![download 4](https://user-images.githubusercontent.com/20615964/28306536-e0e9afea-6bb4-11e7-9a9f-bef0bfe5919f.png)

i've spent hours and tried enableReinitialize, keepDirtyOnReinitialize (both as props and reduxForm() function way), initializing form using action creator and initialValues as props both ways but still not working  :-(((((

### What's your environment?

node: 6.10.2
npm: 3.10.10
yarn: 0.18.1
redux-form: 6.6.1
os: ubuntu 16.10
browser: chromium 59

**Comment by joshjconlin** [comment]
+1

**Comment by bardiainjast** [comment]
just to let everybody know, in my case the problem was because i was mutating my form props by array.fill so i'm gonna close this issue.
@joshjconlin
