### ISSUE TITLE
Is there any guide for upgrading to Redux-Form 7? My Field-Level validations stopped working when I upgraded from 6.8.0 to 7.0.0

### ISSUE THREAD

**Issue by andrerpena** [erikras/redux-form#3207]
My Field-Level Validations stopped working, so I'm wondering, is there any place stating the breaking changes from 6.X to 7.X? I can't find it.

Thank you very much.

**Comment by andrerpena** [comment]
Nevermind. 7.0.1 fixed it. Thanks.

**Comment by erikras** [comment]
Yep. Literally just released the fix. :-)

**Comment by andrerpena** [comment]
Thanks @erikras !
