### ISSUE TITLE
Field validation still broken in 7.0.1

### ISSUE THREAD

**Issue by SBRK** [erikras/redux-form#3218]
The validate function is correctly called, but even if it returns a string, the `meta.valid`, `meta.invalid` and `meta.error` are not updated.

It is working in 6.8.0, not working in 7.0.0 and 7.0.1

EDIT: I'm seeing `@@redux-form/UNREGISTER_FIELD` / `@@redux-form/REGISTER_FIELD` actions passing when I unfocus the field. I don't see them in 6.8.0. The problem is probably coming from there

**Comment by karlshea** [comment]
Possibly more information here: [#3172]

**Comment by SBRK** [comment]
I found the solution to the problem in #3211. The validate function needs to stay the same accross renders (ie: not a lambda generated in the render function, not an array formed directly in the render function).

**Comment by PavelPolyakov** [comment]
hi @erikras ,

is this a final decision?

In our code we have a function which return the validation per field, like:
```jsx
<Field  validate={[validate('gender')]} />
```

After the changes in v7 this doesn't work properly, as on each render the validation is updated.  In case we want to go with v7, this forces us to define validation in the `componentWillMount`, which will make it looks less prettier.

Any chance that the project would go to the old behaviour?

Regards,

**Comment by danielrob** [comment]
@PavelPolyakov see https://github.com/erikras/redux-form/issues/3211#issuecomment-318420350.  You could also memoize this function.

**Comment by PavelPolyakov** [comment]
@danielrob
thanks for the answer.
so it means it is final. And you suggest to cache the results it in the `validate` function?

**Comment by danielrob** [comment]
@PavelPolyakov not sure I follow. Memoize will cache the resulting validate function yes, as long as 'gender' doesn't change in your case. But the result of the resulting validation function each time the value changes certainly shouldn't be cached!

**Comment by m19** [comment]
I have fix it by declaring my validation function outside my React Component like this:

```
const validateName = [isRequired, isAlpha, minLength(2), maxLength(20)]

...

<Field
  id='firstName'
  name='firstName'
  component={Input}
  type='text'
  placeholder='First Name'
  validate={validateName}
/>
```

The following did NOT work in v7.0.3 and resulted in UNREGISTER_FIELD / REGISTER_FIELD actions being dispatched:

```
<Field
  id='firstName'
  name='firstName'
  component={Input}
  type='text'
  placeholder='First Name'
  validate=[isRequired, isAlpha, minLength(2), maxLength(20)]
/>
```

**Comment by PavelPolyakov** [comment]
@m19 
I imagine this happens because
![image](https://user-images.githubusercontent.com/839290/28957772-c8285d66-78f3-11e7-9f98-8c746bb09210.png)

@danielrob 
Do you think this is correct/expected behaviour?

**Comment by danielrob** [comment]
@PavelPolyakov At first I thought it was probably because `minLength(2) === minLength(2) // false`, which would break deepEquals, but I think you might be right.

**Comment by jedwards1211** [comment]
I find myself wishing that there were a way to determine if two JS functions have all the same closure variables.  It would solve this problem

**Comment by danielrob** [comment]
Not sure how this didn't already get linked to #4017
