### ISSUE TITLE
Question: How to set programmatically error in field.

### ISSUE THREAD

**Issue by joanoso** [erikras/redux-form#3220]
Is there a way to change in my custom onChange method, the invalid and error meta of a field?

**Comment by danielrob** [comment]
The short answer is no. `onChange` is for updating the value of the Field. Even if you could change redux-forms state through whatever means to update the invalid or error meta, the next time validators are/onSubmit is run, they will overwrite this information. If you're question is more nuanced than this, then please feel free to elaborate :).

**Comment by gustavohenke** [comment]
Adding more to it: if you have `initialValues` that are invalid, then you'll have your errors, because the validator should be running when the form is mounted.
