### ISSUE TITLE
Website broken at http://redux-form.com/7.0.1/examples/material-ui/

### ISSUE THREAD

**Issue by jforaker** [erikras/redux-form#3221]
Navigate to  http://redux-form.com/7.0.1/examples/material-ui/

Page does not load, this error in console:

![image](https://user-images.githubusercontent.com/2042031/28443848-d51ad602-6d86-11e7-8283-f22906aeedc5.png)

**Comment by HelloEdit** [comment]
For the moment, use http://redux-form.com/7.0.0/examples/material-ui/

**Comment by erikras** [comment]
This has been fixed. Thanks for reporting it!
