### ISSUE TITLE
there is a bug when use anonymous function in validate array

### ISSUE THREAD

**Issue by taven-liu** [erikras/redux-form#3225]
redux-form is a awesome lib, I use it a long time, and when i upgrade to v7 there will be a small problem like this.

render function
```
<Field
	name="count"
	type="number"
	theme={style}
	component={this.renderInputField}
	validate={[required, value => { // has a bug 
	  const maxNum = getMaxResourc(siteValue, netValue)
	  value = parseInt(value, 0)
	  console.log('error', value > maxNum)
	  return value > maxNum ? `can not greater than ${maxNum}` : undefined
	}]}
/>
```

renderInputField function

```
renderInputField = props => {
    const {
      input,
      type,
      meta: { touched, error, warning },
      ...others
    } = props
    console.log('input props', props)
    return (
      <Input 
        type={type}
        error={touched && error}
        {...input}
        {...others}
      />
    )
  }
```

when i change the input value first, the validate function will be called and return `error msg`, and then i  focus out the input then `renderInputField` will be called again, I find then `error` property is `undefine`  in the `meta` of `renderInputField`,  but I repeat again it will works normal

**Comment by SBRK** [comment]
This is intended behaviour, you should not use an anonymous function. See #3211

**Comment by danielrob** [comment]
Another way to say this is if your validate props changes, the field will now re-register to reflect the new changes. This is a feature that does require you to move your validate function definitions outside of the render method. 

Thanks @SBRK!
