### ISSUE TITLE
Ignore validations when one button is clicked and apply them when another is clicked

### ISSUE THREAD

**Issue by dagda1** [erikras/redux-form#3231]
I have a layout component that uses a redux-form remote button:
```
    <div>
      <div>
        {children}
      </div>
      <div>
        <Link to={previousLink}>Back</Link>
      </div>
      <div>
        <RemoteSubmitButton form={formName} />
      </div>
    </div>
```
The actual redux-form will be in a component that uses the layout component, e.g.
```
    export const Form = ({
      handleSubmit,
      pristine,
      submitSucceeded
    }) =>
      <form onSubmit={handleSubmit}>
        <ApplicationLayout
          previousLink="/previous"
          nextLink="/next"
          formName={formName}
          submitSucceeded={submitSucceeded}
        >
          <Field
            name="name"
            component={renderFormInput}
            maxLength={maxNameLength}
          />
          <h1>Form</h1>
        </ApplicationLayout>
      </form>;
    
    const form = reduxForm({
      form: formName,
      onSubmit: submit,
      validate,
      shouldValidate: () => {
        // how do I know which button triggered submit
        // return false for back button click
        // return true for next button click?
      }
    })(Form);
```
The question is, how I can tell which button triggered the submit inside `shouldValidate`?

Or is there a way for the validations to be ignored when the back button is clicked but be applied when the next button is clicked?

**Comment by danielrob** [comment]
Can you clarify what is important to you here? For example, one way to not validate would be to not submit the form...? The values will remain in the store. To do this you could wire up the buttons differently, one to trigger onSubmit, and then proceed if it's valid, the other to simply change what components are mounted without submitting.

**Comment by dagda1** [comment]
I have a wizard like form and all works good when the user clicks next, the validation runs and the user can only proceed when the data is valid.

Going back is a problem, say I have a text box and the user enters some data, if he clicks back to the previous page and then clicks next there is no text in the text box.

I want the user's input or state to remain when they click back whether it is valid or not.  Having it disappear is not usable.  

I'm not sure what you mean by mounting without submitting

**Comment by dagda1** [comment]
I don't think it is possible to use `shouldValidate` in the way I suggested because validation runs after every `onChange` event and by the time submit is triggered, the form is already in an invalid or valid state.

**Comment by danielrob** [comment]
Replying to your first comment... that behaviour is suggests something is not configured/set up how you want it. Off the top of my head it sounds like your form state is somehow being destroyed... it is a standard use case to reconnect a field to a previously edited value in a (wizard) form and have it's value re-appear.

**Comment by dagda1** [comment]
OK, if i change my form to this:

```
  const form = reduxForm({
    form: options.formName,
    onSubmit: submit,
    validate: options.validate,
    destroyOnUnmount: false,
    forceUnregisterOnUnmount: true
  })(Parent);
```

It seems to work, the problem I have, is, props like `submitSucceeded` appear to be true and remembered also.

Is this the case, and if so, how can I clear `submitSucceeded` when I return to a view?

**Comment by dagda1** [comment]
The reason I ask, is because am redirecting like this when a form successfully submits:
```
    </div>
    {submitSucceeded && <Redirect to={nextLink} />}
  </div>;
```

I can't think of a better way to achieve this

**Comment by danielrob** [comment]
I'll point out that the developer has full control over what happens to their application when the onSubmit function is called. This included going off and setting some transition state (i.e. some other variable to force the transition based on the fact that the onSubmit has been called), rather than relying on the submitSucceeded flag. Thus this is possibly more of a 'how you want to write your application' problem. On my current project, we were using sagas which made our state transitions in response to onSubmit pretty flexible. 

I'm not right at this moment well acquainted with the submitSucceeded flag (I've always ignored it for reasons you've run into) but there is a stopSubmit action generator, which allow you to force the form back to unsubmitted as well. Some manual management of this could be another avenue. 

Going to see if that triggers some ideas for you, or see if someone else chimes in, but I'll keep thinking on it regardless.

**Comment by dagda1** [comment]
I ended up managing the state my self, I have a `FormMaker` component that creates a form for each step in the wizard with a remote button which made my requirements a bit more complicated:

```

export const FormMaker = (
  Comp: any,
  options: {
    formName: string,
    heading: string,
    validate: Function,
    previousLink: string,
    nextLink: string
  }
) => {
  class Parent extends Component {
    props: {
      handleSubmit: Function,
      pristine: boolean,
      submitSucceeded: boolean,
      rest: any
    };

    state: {
      successfulSubmit: boolean
    };

    constructor(props) {
      super(props);

      this.state = {
        successfulSubmit: false
      };
    }

    submitForm = (values, dispatch, meta) => {
      dispatch(setApplicantState(values));

      this.setState({
        successfulSubmit: true
      });
    };

    render() {
      const { handleSubmit, pristine, ...rest } = this.props;
      const { successfulSubmit } = this.state;

      return (
        <Form onSubmit={handleSubmit(this.submitForm)}>
          <ApplicationLayout
            heading={options.heading}
            previousLink={options.previousLink}
            nextLink={options.nextLink}
            formName={options.formName}
            submitSucceeded={successfulSubmit}
          >
            <Comp {...rest} />
          </ApplicationLayout>
        </Form>
      );
    }
  }

  const form = reduxForm({
    form: options.formName,
    validate: options.validate,
    destroyOnUnmount: false,
    keepDirtyOnReinitialize: true,
    forceUnregisterOnUnmount: true
  })(Parent);

  return connect(state => ({
    initialValues: state.application.applicant,
    api: {
      countries: state.api.countries.data
    }
  }))(form);
};
```
So using the new `Form` component and managing the `submitSucceeded` myself appears to have fixed my woes.

Thank you for your help @danielrob

**Comment by danielrob** [comment]
Thanks @dagda1!

**Comment by antoinerousseau** [comment]
what I do is that clicking one button or another calls `this.props.change('mode', '<submit mode>')` and I make the validation on submit (in `onSubmit`) instead of on change using the form's `validate` prop:

```js
const onSubmit = (values, dispatch) => {
  if (values.mode === 'publish') {
    const errors = {}
    REQUIRED_FIELDS.forEach((field) => {
      if (!values[field]) {
        errors[field] = 'missing.' + field
      }
    })
    if (Object.keys(errors).length > 0) {
      throw new SubmissionError(errors)
    }
  }

  // your submit code here
}
```
