### ISSUE TITLE
can't type in text field 

### ISSUE THREAD

**Issue by kwekuboateng** [erikras/redux-form#3233]
this is my code

import React from 'react';
import '../Shared/css/separate/pages/login.min.css';
import avatar from './../Shared/img/avatar-sign.png';
import { connect } from 'react-redux';
import { NavLink, Link } from 'react-router-dom';
import { Field, reduxForm, formValueSelector } from 'redux-form';

        let Login = (props) => {
        const { store_name, password, handleSubmit, pristine, submitting, isProcessing } = props;

        return(
            <div className="page-center bodybackground">
                <div className="page-center-in">
                    <div className="container-fluid">
                        <form className="sign-box" onSubmit={handleSubmit}>
                            <div className="sign-avatar">
                                <img src={avatar} />
                                </div>
                            <header className="sign-title">Enter your details to sign in</header>
                            <div className="login__block__body">
                                <div className="form-group form-group--float form-group--centered">
                                    <Field type="text"
                                           className={ store_name?
                                               'form-control form-control--active':
                                               'form-control'}
                                           autoComplete="off"
                                           component="input"
                                           tabIndex="1"
                                           name="store_name"
                                           autoFocus
                                           placeholder="Store Name"/>
                                </div>
                                <div className="form-group form-group--float form-group--centered">
                                    <Field type="password"
                                           tabIndex="2"
                                           className={ password?
                                               'form-control':
                                               'form-control'}
                                           autoComplete="off"
                                           component="input"
                                           name="password"
                                           placeholder="Password"
                                    />
                                </div>

                                <div className="form-group">
                                    <button type="submit"
                                            tabIndex="3"
                                            disabled={ !store_name || !password || pristine || submitting}
                                            className="btn btn-rounded">
                                        { isProcessing? 'Processing...' : 'Login'}
                                    </button>
                                </div>
                                <div className="form-group">
                                    <div className="checkbox float-left">
                                        <input type="checkbox" id="signed-in" />
                                        <label htmlFor="signed-in">Keep me signed in</label>
                                    </div>
                                    <div className="float-right reset">
                                        <Link to="/resetPassword">Reset Password</Link>
                                    </div>
                                </div>
                                <p className="sign-note">New to Aidah? <NavLink to="/signUp">Sign up</NavLink></p>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        )
}

Login = reduxForm({
    form: 'login'
})(Login);
const selector = formValueSelector('login');
Login = connect(state => {
    const { store_name, password } = selector(state, 'store_name', 'password');
    return {
        store_name,
        password
    }
})(Login);

export default Login;

import React, { Component } from 'react';
import Login from './login';
import { connect} from 'react-redux'
import PropTypes from 'prop-types';
import { Redirect } from 'react-router-dom';
import SweetAlert from 'sweetalert-react';
// import loginAction from '../Actions/Account';
import {merchantSignIn, accountSignInFail} from '../Actions/Account';

class LoginPage extends Component{

    render(){
        const { accountSignInLoading,
            accountSignInFail,
            accountSignInErrors,
            accountSignInSuccess } = this.props.Account;
        return(
            <div>
                <SweetAlert
                    show={accountSignInFail}
                    type="warning"
                    title='Ooops!'
                    text={accountSignInErrors && accountSignInErrors.message}
                    onConfirm={() => this.props.accountSignInFail(false) }
                />
                { accountSignInSuccess ?
                    <Redirect to="/d/dashboard" /> :
                    null
                }
                <div>
                <Login
                    isProcessing={accountSignInLoading}
                    onSubmit={this.props.merchantSignIn} />
                </div>
            </div>
        )
    }
}

LoginPage.propTypes = {
    Account: PropTypes.object.isRequired
};

Login.propTypes = {
    isProcessing: PropTypes.bool.isRequired,
    onSubmit: PropTypes.func.isRequired
};

const mapStateToProps = (state) => {
    return {
        Account: state.Account
    }
};

const mapDispatchToProps = (dispatch) => {
    return {
        merchantSignIn: (values) => {
            dispatch(
                merchantSignIn(values)
            );
        },
        accountSignInFail: (bool) => {
            dispatch(accountSignInFail(bool))
        }
    }
};

export default connect(mapStateToProps, mapDispatchToProps)(LoginPage);

**Comment by gustavohenke** [comment]
Make sure that you're using the redux-form reducer.

In case you're, please create a minimal, reproducible example using this CodeSandbox template:
https://codesandbox.io/s/gJjDoKYWl
