### ISSUE TITLE
@@redux-form/UNREGISTER_FIELD deleting form's data from redux store

### ISSUE THREAD

**Issue by LearningNerdd** [erikras/redux-form#3234]
I have props called total_count and one `FieldArray`
`FieldArray` consists of 8 input Fields
name,address,zipcode - mandatory
date_of_birth,birth_place,city,country,contact_number - optional (condition based rendering)

Now coming to my issue:-
I am rendering `FieldArray` component for total_count times
I have total_count = 3
`Field` details for the 3 arrays:-
1-->name,address,zipcode
2-->name,address,zipcode,date_of_birth
3-->name,address,zipcode,date_of_birth

Now the UI is rendering fine and whenever I change values in any of the above fields, it is storing properly in redux store

But once I click on submit button, as expected it starts `@@redux-form/UNREGISTER_FIELD` actions and once it starts unregistering date_of_birth for 2nd element, it is completely removing 2nd and 3rd element's data from redux store.

Below is my redux-form configuration:-
```
reduxForm({
 form: "AddressForm"
  destroyOnUnmount: false,
})(MyComponent)
```

Apart from that, I am facing one strange issue. Once the above mentioned issue occurs i.e once the 2nd and 3rd elements get deleted from redux-store after dispatching @@`redux-form/UNREGISTER_FIELD`, if you go and look at previously stored form values in console output, it is showing current state instead of previous state. Dont know whether it is redux logger issue or redux form issue.

Any help in these above two issues?

**Comment by erikras** [comment]
It would help a _lot_ if you could reproduce this in a sandbox. Perhaps from cloning [the `FieldArray` one](https://codesandbox.io/s/Ww4QG1Wx)?

**Comment by LearningNerdd** [comment]
Hi @erikras  I would love to reproduce this but it is intermittent

**Comment by danielrob** [comment]
@LearningNerdd it's fairly difficult to provide support for this issue in it's current state. Even if it's an intermittent issue, could you try to isolate some reproduction steps or a setup that will produce this issue some of the time?

**Comment by LearningNerdd** [comment]
@danielrob  okay.. Give me few days. I will loo ad try to reproduce this issue.

**Comment by danielrob** [comment]
@LearningNerdd once we have a reproduction, we can re-open this issue.

**Comment by xurshid29** [comment]
Same issue here:

(before clicking submit button):
![rf-1](https://user-images.githubusercontent.com/5887811/37278674-4684eeea-260a-11e8-8155-35c06dc628af.png)
Here, there is a `variations` key under `form` -> `product` -> `values` key, with 4 elements;

(after clicking submit button):
![rf-2](https://user-images.githubusercontent.com/5887811/37278753-8b956082-260a-11e8-8a03-dc0255e13a2a.png)
Here, the `variations` element has been removed somehow, and its only element (`variationBarcode`) has been placed directly inside `values`

**Comment by lepczynski** [comment]
I have the same issue it is NOT intermittent but unfortunately I can't share the code : /
