### ISSUE TITLE
Grammar issues in Reducer.md

### ISSUE THREAD

**Issue by qbolec** [erikras/redux-form#3237]
I'm not a native speaker, so perhaps the following phrase from Reducer.md is in fact correct:

> Should be given to mounted to your Redux state at form.

but it is really difficult to comprehend for me and the Grammarly plugin:) 

Sorry for not being constructive in my critique, bu I don't even know what it was supposed to mean, so I can not propose any correction :(

**Comment by gustavohenke** [comment]
I think the correct would be

> Should be mounted to your Redux state at `form`

Would you like to send a PR to fix that? 😃
