### ISSUE TITLE
Feature Request: Some way to access errors on field properties

### ISSUE THREAD

**Issue by dkniffin** [erikras/redux-form#3242]
Most of the time, redux-form fields represent a single value. eg: `<Field name="username" />` would have a value of something like `"dkniffin"`. 

However, they don't have to be like that. They could represent objects, like `<Field name="address" />` which might be autocompleted from google, and have a value like `{ line1: '123 Main street', city: 'Durham', state: 'NC' }`. 

In the latter cases, if the server throws an error for `address.line1`, and we map that to a `SubmissionError`, it will not be passed into that field, because the key won't be `address`, it'll be `address.line1`.

It'd be nice to have a way to access those properties in this case.

Hopefully that makes sense. Let me know if you want clarification.

**Comment by erikras** [comment]
For complex objects like this, I might recommend having a special `AddressInput` component that knew how to deal with the entire `{ line1, city, state }` object.

I used to live in Durham. 😄

**Comment by dkniffin** [comment]
I have built a component for this field (called `GooglePlacesSearchBox`), and it works fine for accessing and displaying the actual value, but as far as I can tell, there's no way to access all the errors related to the field.

**Comment by danielrob** [comment]
I believe there's nothing stopping you from doing e.g. `new SubmissionError({ address: YourDeepErrorObject })` where `GooglePlacesSearchBox` knows how to handle `YourDeepErrorObject` - it would be available in the `meta` prop. 

In saying that it sounds like your server and your front end form model aren't really in agreement about what the atomic input data is. An adaptor may be required to make them talk.

**Comment by dkniffin** [comment]
I guess what I was hoping for is something that would allow me to do `new SubmissionError({ 'address.line1': 'error' })` and access that error in my component.

**Comment by danielrob** [comment]
Right! Gotcha! Yes! We have that :). Sorry didn't quite click at first. You can access form errors using the http://redux-form.com/7.0.1/docs/api/Selectors.md/ 

I put together a little sandbox here: https://codesandbox.io/s/qxk3qmED0

It will allow you to pass through errors for keys that were never registered fields. Then you can access the submit errors by connecting your component.

**Comment by dkniffin** [comment]
Hmm, that might work. I'll give it a shot and reply here

**Comment by dkniffin** [comment]
Alright, I took a stab at it. It might work, but it feels a little hacky. I'd have to either A: connect my field to redux, which feels a bit weird and doesn't really work anyways because I'd have to hard-code the form name or B: do the selector up at my "smart" component and pass all the errors down, but that also feels quite messy.

What I'd like is for a new prop to be passed into my Field component called `childErrors` or something. If I made a PR for that, would you guys accept it?

**Comment by danielrob** [comment]
Regarding hard-coding form name, you were the tipping point and I've added #3246. There is something strange about this library that makes people afraid to connect their components despite custom connectors being provided. If you could enlighten me 💡? In fact I do understand... most of the time, Field, FieldArray, Fields do a reasonable job, I think there is often hesitation to move beyond this. I diverge. 

Regarding the PR that's beyond my paygrade, but I would certainly be interested to see your implementation. Would this give every Field, FieldArray, Fields component every error that is a subKey of it's own current name? One trouble I can forsee with this is is performance. Perfomance is actually (one of) the main reason(s) in my understanding that the Field* components mostly keep to themselves by default, and then the library provides extra selectors for the cases where the developer explicitly needs the payoff of a small performance loss that allows them to fetch the information they want. If you think this won't in practice affect what you have in mind, we certainly welcome a PR!

**Comment by dkniffin** [comment]
Your point about Field, FieldArray, and Fields is half of it I think. The other half is a general reluctance to use [smart components inside dumb components](https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0). I usually like to  have one smart component at the top level, and everything under it be dumb. However, I know the components provided by this library are connected behind the scenes, so perhaps this reluctance isn't a valid concern.

That's a good point about performance. I'm typically of the mindset of build it first, make it perform well later, but I can definitely see why it'd be important to think otherwise in a library like this. I'll take a look and see if I can take a stab at what implementation would look like for this, and get back to you.

**Comment by danielrob** [comment]
Well said :) Great! Thanks!

**Comment by dkniffin** [comment]
I'm trying to make a PR for this, but I'm having issues. How do you point a react app (or the examples) at a local version of the library? As a side-note, it might be good to have a markdown file describing how to develop for this project.

**Comment by danielrob** [comment]
Admitting how little I know in this regard (:() currently... in general terms I think https://docs.npmjs.com/cli/link or doing a manual `npm install package.zip` from a built zip package of the lib are the two ways I've locally tested an npm module in a consumer app. The local examples should just run relatively to your updated repo?

**Comment by dkniffin** [comment]
Thanks. I figured it out shortly after I posted. The examples run off of the latest published version. But `cd examples/fieldArrays && npm install --save ../..` did it.

**Comment by dkniffin** [comment]
Alright, after quite a bit of messing around, I realized this problem _is_ specific to our application, I think. I had two separate problems, both of which I thought would be solved by this, but I found 
different solutions for. I'm going to post them below, just for reference in case anyone else stumbles upon this.

### Nested SubmissionError key

The first problem was that our backend was was returning things in a little bit of a strange way. Continuing the example from above, if there was an error on `address.line1`, instead of returning
```
{ 
  address: { 
    line1: "Something is wrong with line 1"
  }
}
```
it would return
```
{
  address.line1: "Something is wrong with line 1"
}
```
This is a little odd, but I think it's standard for Rails, so I decided to fix it on the frontend, with this bit of code (which uses [lodash set](https://lodash.com/docs/4.17.4#set):

```
const fieldErrors = reduce(errorsFromBackend, (acc, value, key) => {
  set(acc, key, value);
  return acc;
}, {});

throw new SubmissionError({
  ...fieldErrors,
  _error: baseErrors
});
```

### Accessing children validation errors

The other issue I had was when I wanted to access to sub-field sync errors inside a field component. To expand on the example above, it'd be something like (somewhat contrived):

```
function GooglePlacesSearchBox(props) {
  return (
    <Field
      component="input"
      name="address.line1"
      validation={(val) => val == '123 Main street' && "That's not a real address!" }
    />
   )
}

export default GooglePlacesSearchBox;
```
```
<Field
  name="address"
  component={GooglePlacesSearchBox}
/>
```

Then I wanted to access the validation error on `address.line1` from inside `address`.

I ended up solving this one by just connecting the component:

```
export default connect(
  (state, ownProps) => {
    const childErrors = get(getFormSyncErrors(ownProps.meta.form)(state), ownProps.input.name);
    return {
      childErrors
    };
  }
)(GooglePlacesSearchBox);
```

This second part might still be feasible as a built-in solution, but I'm not motivated enough to make a PR now 😛

So, I'm gonna close the issue.

**Comment by danielrob** [comment]
Dommage! Thanks for providing an excellent follow up to this issue, and "come again soon" :).
