### ISSUE TITLE
data submitted differs when instantly change data and submit

### ISSUE THREAD

**Issue by kevinluvian** [erikras/redux-form#3245]
### Are you submitting a **bug report** or a **feature request**?

bug report

### What is the current behavior?

it is pretty hard to reproduce, but basically:
if I change my form the redux will dispatch change action,
however, it takes time for my form to re-render itself,
if before my form re-render with the new data, I submit the form, it will use the old data, instead of the new one

### What is the expected behavior?
the form should submit the new data

### What's your environment?

redux-form: 7.0.1

### Other information

is there any way to submit form from redux store instead of from props?

**Comment by kevinluvian** [comment]
currently my workaround is to use setTimeout when submitting the form

**Comment by danielrob** [comment]
Could you confirm if this is a dupl.icate of #2818?
