### ISSUE TITLE
Can't type correctly on Chrome Canary

### ISSUE THREAD

**Issue by po-jo** [erikras/redux-form#3250]
Hi,
A strange comportment on [Chrome Canary](https://www.google.fr/chrome/browser/canary.html) : when you want to enter text in a redux form field (for exemple in [the exemple from the doc](http://redux-form.com/7.0.1/examples/simple/)), you can type one letter, sometimes two, then focus is lost.

Not sure wether it's a real bug since it appears only on Chrome Canary and not 'real' Chrome, but since features of Canary are mostly finishing in Chrome, it's a little scary. Any thoughts on what's happening here ?

**Comment by erikras** [comment]
Canary is really living up to its name! Scary!

Can you try a regular "state kept in this.state" implementation as well?

**Comment by po-jo** [comment]
Hi @erikras, thanks for your answer. This bug appears in all implementation I have tested (my app and all the exemples directly from redux-form website), just for fields where the prop component is set to "textarea". Not sure what you mean by  "state kept in this.state" ?

**Comment by danielrob** [comment]
@po-jo Are you still able to reproduce? I am unable to avec `Version 62.0.3178.0 (Official Build) canary (64-bit)`

**Comment by danielrob** [comment]
Closing cannot-reproduce.
