### ISSUE TITLE
Support for new options in react-redux connect

### ISSUE THREAD

**Issue by duro** [erikras/redux-form#326]
With the new version of react-redux, it seems the API has changed a bit, and there are new options in `connect`

https://github.com/rackt/react-redux/blob/master/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options

Has redux-form been updated to support these?

**Comment by duro** [comment]
I am most specifically interested in the `options.withRef` feature which makes `getWrappedComponent()` work.

**Comment by travisbloom** [comment]
in line with this request, was wondering if the third mergeProps optional function could be added (looking to grab props passed from React Router and use it to generate initialValues)
