### ISSUE TITLE
Cannot find module 'eslint-config-react-app'

### ISSUE THREAD

**Issue by pkoziol** [erikras/redux-form#3268]
### Are you submitting a **bug report** or a **feature request**?
Bug report

### What is the current behavior?
1. Download ZIP with sources. I have downloaded current master which was https://github.com/erikras/redux-form/commit/1c4f1e786ddd0c5252c982e26c9eee440360f80d at the time.
2. Unzip and go to `redux-form-master/examples/submitValidation`
3. Run `npm install`
4. Linting fails with `Cannot find module 'eslint-config-react-app'`

### What is the expected behavior?
Linting should not fail and all dependecies should be installed.

### What's your environment?
Windows 10
node v6.2.0
npm  v3.8.9
redux-form 7.0.3 (1c4f1e786ddd0c5252c982e26c9eee440360f80d)

### Other information
Most likely I am missing some global dependecy, but I do not known which exactly. If it is true then there should be appropriate information in README.

**Comment by gustavohenke** [comment]
That's not how you run examples.

> Each example is its own standalone web app with hot reloading. To prepare for running the examples locally, clone the redux-form repository and run `npm install` to install the necessary dependencies for redux-form. Then you can run the examples locally using either two methods:
>
> 1. Run `npm run example:EXAMPLE_FOLDER` (Remember to replace EXAMPLE_FOLDER with the name of the folder for the example you want to run like `npm run example:simple` or `npm run example:material-ui`)
> 2. Manually run the following commands:
> ```
> # Remember to replace EXAMPLE_FOLDER with the name of the example's folder
> cd ./examples/EXAMPLE_FOLDER
> npm install
> npm start
> ```

This is documented [here](http://redux-form.com/7.0.3/examples/) and in every other example page in similar ways.

**Comment by pkoziol** [comment]
Thanks! I read only `examples/submitValidation/README.md` which does not mention anything about running `npm install` in main directory.

**Comment by gustavohenke** [comment]
It's there:

> # Running this example locally
> 
> To run this example locally on your machine clone the redux-form repository, then `cd redux-form` to change to the repo directory, and run `npm install`.
> 
> Then run `npm run example:submitValidation` or manually run the following commands:
> ```
> cd ./examples/submitValidation
> npm install
> npm start
> ```
