### ISSUE TITLE
error prop does not exist

### ISSUE THREAD

**Issue by gillisd** [erikras/redux-form#3272]
I'm running v7.0.3 (and have also tried this on v6.8.0). The docs state that there is an `error` prop for the entire form that contains a key called `_error` with a value equal to what the`validate` function returns, but this prop does not seem to exist. My errors are indeed being created as `syncErrors` in the reducer contains them.

**Comment by danielrob** [comment]
>  called _error with a value equal to what the validate function returns
Nearly correct

It has a value equal to what the validation function assigns to the `_error`  property in the errors object.

**Comment by gillisd** [comment]
Ahhh thank you
