### ISSUE TITLE
validate function "props" argument may not contain all props

### ISSUE THREAD

**Issue by L-u-k-e** [erikras/redux-form#3273]
### Are you submitting a **bug report** or a **feature request**?

I am submitting a bug report

### What is the current behavior?

The `validate` function's `props` argument does not contain all of the component props (sometimes).

More precisely, when `reduxForm` is used in conjunction with other decorators (e.g. react-redux's `connect`), any props added by other decorators will not show up in the `validate` function's second positional argument (`props`). The props are available in the render callback however. 

For clarity this will only happen if the redux form decorator is called with the `connected` component as it's argument. (In other words, if the `reduxForm` decorator is called last). 

### What is the expected behavior?
Unless I'm mistaken, the `props` argument should contain all of the props. 

### Sandbox Link

Check the console log in the sandbox linked below. You'll see that the property: `TEST` is available in `render` but not in `validate`. If you switch the order in which the decorators are applied (call `reduxForm` first with the form as its input, and then `connect` second with the decorated form as its input) the issue is resolved. 

https://codesandbox.io/s/ElRNvDNWg

### What's your environment?

I originally ran into this bug on 6.5. (I don't know how long this bug has existed). I've since updated to 7.3 and am still seeing the bug. I have only tested on Chrome. 

### Other information

N/A

**Comment by danielrob** [comment]
Thank you for the sandbox! ❤️. The behaviour you're getting makes sense. `validate` passes in the `props` all props that `reduxForm` receives. 

But you're passing a connected component to `reduxForm()` instead of injecting `reduxForm` with extra props by connecting it, so it never actually receives the `TEST` prop. See https://codesandbox.io/s/2RJ9nAW9z

**Comment by L-u-k-e** [comment]
OK right. I saw earlier that switching the order as you did in your sandbox fixed the issue. But I was having trouble reasoning through why.

Now, I see why. As you said, `TEST` is not a prop that belongs to the component that I decorated with `reduxForm`, so it's not passed to `validate`. The code closed over by the `reduxForm` function which invokes `validate` doesn't know about that prop.  

To reiterate:
**validate will be passed all of the props that belong to the component which was decorated with `reduxForm`. This component may or may not be the same component that renders the form, calls `submit` etc.** 

The implication here is that if you're decorating a component with multiple HOC's and you need some props for use in `validate` that come from said HOC's, you need to make sure that the HOC's which provide the props you need are rendered above the `reduxForm` HOC in the render tree.
