### ISSUE TITLE
Multiselect open/close on removing an item

### ISSUE THREAD

**Issue by ManyStylez** [erikras/redux-form#3285]
### Are you submitting a **bug report** or a **feature request**?

**feature request**

### What is the current behavior?

Using the multi select widget when removing a selected item, the full list is opened to display available sections.

### What is the expected behavior?
It would be great to either specify a prop to stop this behaviour, or extend the ```onToggle``` event to include the action which triggered the toggle so I could handle the open/close status manually.

### Sandbox Link

n/a

### What's your environment?

n/a

### Other information

n/a

**Comment by danielrob** [comment]
Thanks for swinging by. I don't believe this is an issue pertaining to redux-form (or it lacks sufficient clarity), perhaps you meant https://github.com/jquense/react-widgets?

**Comment by ManyStylez** [comment]
yup my bad wrong repo!
