### ISSUE TITLE
Reset after save bug - Not restoring to correct initialValues

### ISSUE THREAD

**Issue by Noitidart** [erikras/redux-form#3293]
### Are you submitting a **bug report** or a **feature request**?

Bug report. I think this is a bug because I posted on Stackoverflow but no one knows - https://stackoverflow.com/q/45516908/1828637

### What is the current behavior?

Screencast of the sandbox here - https://youtu.be/iILiFieO-gk - it seems `this.props.reset()` is restoring values to the `initialValues` on mount.

### What is the expected behavior?
`this.props.reset()` should restore values to whatever is currently in `initialValues`.

### Sandbox Link

Reproduced perfectly here in its simplest form - https://codesandbox.io/s/PNyPwyWP2

### What's your environment?

```
    "redux": "^3.7.2",
    "redux-form": "^7.0.3",
```

Node - 7.5.0
npm - 5.3.0

Only tried it in Browser of Firefox 55.0 on OS of Windows 10

### Other information

My goal is that I have a form with a single field, a button "Reset" and a button "Save". Clicking "Save" saves the form values into a reducer in my `store` called `save`. Clicking "Reset" should reset the form values to the last "pristine" values (the values in `initialValues`).

However my issue is,  after saving the form, the "Reset" button should reset it to the "pristine" value (the newly saved value, the value in initialValues) but it is reseting it to the "old pristine value".

**Comment by danielrob** [comment]
Thanks for the very detailed report. 

Unfortunately this time [this is documented behaviour](http://redux-form.com/7.0.3/examples/initializeFromState/): 

> By default, you may only initialize a form component once via initialValues. There are two methods to reinitialize the form component with new "pristine" values:
> 
> 1. Pass a enableReinitialize prop or reduxForm() config parameter set to true... 

I tried adding enableReinitialize: true to your sandbox, and it gave the desired result. Please close this if it answers your question.

**Comment by Noitidart** [comment]
Oh my gosh, thanks very much sir @danielrob for the fast help!

**Comment by Noitidart** [comment]
Thanks very much for leaving this open for me to close. I really am discovering the amazing power of redux-form, is there anyway to make a contribution to this module to motivate its future development?

**Comment by danielrob** [comment]
Hi! Love the enthusiasm :). Definitely many ways to help - providing support is probably the lightest way to start, but docs improvements, examples development, and then diving into library improvements are all avenues available :)

**Comment by Noitidart** [comment]
Oh ok thank you sir!
