### ISSUE TITLE
Inline declaration of validate and warn props broken after 7.0.0 release

### ISSUE THREAD

**Issue by umidbekkarimov** [erikras/redux-form#3294]
### Are you submitting a **bug report** or a **feature request**?

Feature Request.

### What is the current behavior?

* Open [Sandbox](https://codesandbox.io/s/p41Ymlly)
* Open redux dev tools
* Type something to the Last Name or First Name fields
* Each type will reregister field

### What is the expected behavior?
Additional props like `pureValidate` and `pureWarn` should be provided to change reregister logic. 

### Sandbox Link
https://codesandbox.io/s/p41Ymlly

### Other information
https://github.com/erikras/redux-form/issues/3012#issuecomment-319396514

**Comment by danielrob** [comment]
Sorry, but I think [this](https://github.com/erikras/redux-form/issues/3288#issuecomment-320729482) puts this issue to rest.
