### ISSUE TITLE
Make the `handleChange` prop work with checkboxes/radios

### ISSUE THREAD

**Issue by bernharduw** [erikras/redux-form#33]
Right now `handleChange` doesn't work out of the box with checkboxes/radio buttons. In my form, I wrote a small wrapper function like this:

```es6
// An expression to handle checkboxes.
const handleCheckboxChanged = name => event => handleChange(name, !!event.target.changed)(event);
```

But it would be nicer and easier to avoid errors if handleChange supported checkboxes by default.

Additionally, `handleBlur` doesn't check for `undefined` explicitly, so it doesn't work at all with the `changed`property.

**Comment by erikras** [comment]
Excellently presented ticket. Thank you.

I've never heard of this `event.target.changed` property. It's always `undefined` for me in my javascript console. What I've done is `if(event.target.type === 'checkbox') { return event.target.checked; }`, which is always a boolean.

**Comment by bernharduw** [comment]
Thanks a lot for the quick fix! Now it works great!

According to the [React documentation about forms](https://facebook.github.io/react/docs/forms.html), also `type=radio` uses the `checked` attribute. I haven't yet used radio buttons in my React forms, but it would make sense to me to also check for those: `if(event.target.type === 'checkbox' || event.target.type === 'radio') { return event.target.checked; }`

**Comment by erikras** [comment]
I checked radio buttons. React also populates `event.target.value` properly for those.
