### ISSUE TITLE
touchedSinceLastSubmit selector

### ISSUE THREAD

**Issue by dkniffin** [erikras/redux-form#3307]
### Feature request

I'd like to request a new selector (or prop or something...not really sure how it'd be implemented), which would return a boolean indicating whether any fields have been touched/changed since the last submit. `isDirty` almost gets me what I want, but `initialValues` doesn't update after a submit

**Comment by dkniffin** [comment]
Right now, I'm doing this via a form plugin:

```
import {
  actionTypes as reduxFormActionTypes
} from 'redux-form';

function isUntouchedPlugin(state, action) {
  if (!action || !action.meta || !action.meta.form) {
    return state;
  }

  switch (action.type) {
  case reduxFormActionTypes.CHANGE:
    return {
      ...state,
      isUntouched: false
    };

  case reduxFormActionTypes.INITIALIZE: // intentionally fall through to reduxFormActionTypes.SET_SUBMIT_SUCCEEDED
  case reduxFormActionTypes.SET_SUBMIT_SUCCEEDED:
    return {
      ...state,
      isUntouched: true
    };

  default:
    return state;
  }
}

export default isUntouchedPlugin;
```

And then I have to pass it through my state in my container:

```
import {
  formValueSelector
} from 'redux-form';

const formSelector = formValueSelector('formName');

function mapStateToProps(state) {
  return {
    isUntouched: formSelector(state, 'formName')
  };
}
```

It'd be nice if it was just available as a prop in each form, and have it passed in like `anyTouched`, etc.

**Comment by gustavohenke** [comment]
> `isDirty` almost gets me what I want, but `initialValues` doesn't update after a submit

Yes, how would redux-form know what is the new `initialValues`?
You may, however, update it yourself. Then `isDirty` will work for you 😃 

Or, you can control this somehow in your component, etc.
