### ISSUE TITLE
Field-Level Validation - React Native - Field not receiving meta:error

### ISSUE THREAD

**Issue by oatssss** [erikras/redux-form#3309]
### What is the current behavior?

In react native, `Field`s with field-level validators specified don't receive error messages through `meta:error`

In the example provided below (sandbox link), there are 3 validators (required, max-length, and email). Their respective error messages are shown under the input via `Text` components where the 4th and last message is what the `Field` receives as an error. The received error never changes from `undefined`.

### What is the expected behavior?

A validation function returning anything other than `undefined` should have its message passed to the `Field` through `meta:error`

In the example provided, the 4th error message should show an error whenever any of the preceding 3 messages show an error.

### Sandbox Link

https://github.com/oatssss/rn-redux-form-field-level-validation

![redux-form-field-validation](https://user-images.githubusercontent.com/7298535/29200819-8999b62a-7e26-11e7-9a0f-53208fced4dc.gif)

### What's your environment?

``` json
"engines": {
  "node": "6.11.2"
},
"dependencies": {
  "react": "16.0.0-alpha.12",
  "react-native": "0.47.1",
  "react-redux": "5.0.6",
  "redux": "3.7.2",
  "redux-form": "7.0.3"
},
"devDependencies": {
  "babel-jest": "20.0.3",
  "babel-preset-react-native": "2.1.0",
  "jest": "20.0.4",
  "react-test-renderer": "16.0.0-alpha.12"
}
```

### Other information

What I think are the key parts of the example:
``` javascript
let reqError;
let maxError;
let emailError;

// Field-level validators
const validationRequired = value => {
  let result = reqError = value ? undefined : `This can't be empty`;
  return result;
};

const validationMaxLength = max => value => {
  let result = maxError = value && value.length > max
    ? `Must be ${max} characters or less`
    : undefined;
  return result;
};

const validationEmail = value => {
  let result = emailError = value && !/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i.test(value)
    ? 'Invalid email address'
    : undefined;
  return result;
};

// Component we'll use as the input field
const InputField = ({
  input: {
    onChange,
    ...restInput
  },
  meta: {
    error
    ...restMeta
  },
  ...restProps
}) => (
  <View>
    <TextInput
      onChangeText={onChange}
      {...restInput}
      {...restProps}
    />
    <Text>{`Required error: ${reqError}`}</Text>
    <Text>{`Max length (8 chars) error: ${maxError}`}</Text>
    <Text>{`Email error: ${emailError}`}</Text>
    <Text>{`Actual received error message: ${error}`}</Text>
  </View>
);

// The actual form
let SimpleForm = ({
  handleSubmit
}) => (
  <View>
    <Field
      name="email"
      component={InputField}
      validate={[
        validationRequired,
        validationMaxLength(8),
        validationEmail
      ]}
    />
    <Button
      title={'Submit'}
      onPress={handleSubmit(values => console.log(values))}
    />
  </View>
);
```

**Comment by oatssss** [comment]
I found out that if an array of validators is created outside the form instead of specifying them in-line, then the fields at least receive a `meta:error` message. I haven't yet tested it thoroughly to determine if they're displaying the right messages in the right cases though.

``` javascript
const emailValidators = [
  validationRequired,
  validationMaxLength(8),
  validationEmail
];

let SimpleForm = ({
  handleSubmit
}) => (
  <View>
    <Field
      name="email"
      component={InputField}
      validate={emailValidators}
    />
    <Button
      title={'Submit'}
      onPress={handleSubmit(values => console.log(values))}
    />
  </View>
);
```

**Comment by dongyuwei** [comment]
run into the same issue.

**Comment by stinodes** [comment]
I also ran into this issue.  
In my case, however, I was seeing how having decorated forms with the same `form`-props would work out.  
Not sure if that's related though.

**Comment by oatssss** [comment]
Up to now, I could use the workaround I described to get the errors, but now I believe I'm running into a problem because I need to validate a field against the value of another field (for example a Confirm Password field). So I tried something like

``` javascript
const valdiationEquals = comparison => value => comparison === value ? undefined : 'Not the same'
const confirmValidators = passField => [
  valdiationEquals(passField)
];

...

<Field
    name="email"
    component={InputField}
    validate={confirmValidators(/* Value of passField given here */)}
/>
```

But I think that because it's now a function that returns an array instead of just being an array itself, it doesn't work.

**Comment by dongyuwei** [comment]
I have a work-across for this issue, just change my pure-function component to a component which extends PureComponent.

@oatssss if you refactor your `InputField ` to a component like `class InputField extends PureComponent`, it should be ok.

**Comment by oatssss** [comment]
@dongyuwei Thanks for the tip! I didn't think of using PureComponent. However, I tried it with the _confirm password_ scenario I described in my previous comment, and although it works better than a pure-function component, it still doesn't display the error message sometimes.

**Comment by jsonmaur** [comment]
I'm having this same problem, and just like @oatssss, it's solved by not using an inline validation function. This works: `validate={this.checkEmail}`, but this does not work: `validate={() => this.checkEmail()}`. I'm using `Component` for the form component, and a `PureComponent` for the input component.

This is definitely a bug, as it shouldn't matter whether the validation function is inline or not. Side note: this is also an issue with `warn`, but not `format` or `normalize`.

**Comment by talolard** [comment]
+1 for this problem and solution, e.g. solved by defining validator functions and array of them explicitly vs inline. 
Not proud of this code 
```js
 validateContentFieldIsString(value) {

        const res = typeof(this.props.dataExample[value]) !== 'string' ? 'The content field must be a string' : undefined
        debugger;
        return res
    }
    constructor(props){
        super(props);
        this.validators =[required, this.validateContentFieldIsString.bind(this)]
    }
````

**Comment by RobinClowers** [comment]
I don't understand why this bug hasn't gotten more attention, it's a really severe issue. I have fields that need to be validated based on metadata that's in my props, so I was using a function that takes some props and returns a validation function, but once I upgraded redux-form, it just quietly stopped working. I'm not even sure how to fix this without splitting up my component.

**Comment by RobinClowers** [comment]
After some head scratching I realized this can be solved with lodash memoize: https://lodash.com/docs/4.17.4#memoize. The issue here is that the validation functions are compared using deepEqual: https://github.com/erikras/redux-form/blob/cf4b7c13ee5d2b97daa553d2ca6329371cd2c9a2/src/createField.js#L56

**Comment by oatssss** [comment]
I'm not familiar with `_.memoize`. Is the problem that when validators are passed in-line, completely new instances of the validators are created with each invocation of `componentWillReceiveProps` causing the `deepEqual` to fail...

then likewise, if a function that returns a validator is used instead of a validator directly, the invocation of the original function spawns a new instance of the validator each time, so memoizing the function will cause it to pull a cached validator and allow it to pass the equality check?

**Comment by RobinClowers** [comment]
@oatssss yes, that's the idea.

**Comment by RobinClowers** [comment]
But to be clear, you need to call memoize outside your render function.

**Comment by RobinClowers** [comment]
One gotcha, if you have multiple parameters, you will have to specify the cache key:


```js
const validator1 = (a, b) => valueToValidate => { /* 1st validator, can use param in here */ }
const validator2 = (a, b) => valueToValidate => { /* 2nd validator, can also use param in here */ }

const validators = _.memoize((a, b) => [
  validator1(a, b),
  validator2(a, b)
], (...args) => JSON.stringify(arg));

<Field
    // ...other stuff to configure the Field
    validate={validators(/* the param I need to dynamically change the validators */)}
/>
```

The second argument to `memoize` is a resolver function, which should return the cache key. The `JSON.stringify` is because `[1,2] !== [1,2]`

**Comment by oatssss** [comment]
Ah I get it, the resolver is basically a hash function, useful knowledge. Thanks for the tip! :)

**Comment by jasperkuperus** [comment]
Okay, so what's the current status on this? I can work around it by defining my validators outside of my component, but is there a plan to fix this?

**Comment by m1m6** [comment]
Same issue

**Comment by gustavoteodoro** [comment]
Same issue

**Comment by Shadymination** [comment]
Same issue

**Comment by douglasjunior** [comment]
Same here, meta object is aways empty.

```
"redux-form": "7.3.0",
"react": "16.2.0",
"react-native": "0.53.3",
```

**Comment by netocp** [comment]
Same issue here
`"react": "^16.3.0-alpha.1",
    "react-native": "^0.54.3",
"redux-form": "7.3.0"
`

**Comment by danielrob** [comment]
>  `validationMaxLength(8)`

Please see #4017

Agreed, this caused a lot of pain / headaches.
