### ISSUE TITLE
Namespacing inside props?

### ISSUE THREAD

**Issue by mattkrick** [erikras/redux-form#331]
Any thoughts on putting everything inside a `this.props.form` namespace? There are a few things like `error` that probably exist in other code/package decorators & silent fails (writing over the `error` value) that depend on decorator ordering is a hard bug to track down. I know it'd blow up the API, but it'd keep props clean :+1:

**Comment by erikras** [comment]
I had not considered that, no. Perhaps there could be a `propPrefix` or `propNamespace` config parameter to allow such a thing...

...but then the other libraries could do that, too! :stuck_out_tongue_winking_eye: 

I'll consider it.

**Comment by mattkrick** [comment]
Haha very true! The other libraries don't dump 30 new items into the `props` though :wink: 

My case for the nested object is first for debugging: my `PropTypes` static is easy to create & it makes it easy to see which props are the ones I added vs. which ones redux-form added. Second, if i need to send all my non-redux-form props down to a child, I could exclude all the form props super easily with a rest operator, which really cleans up the code.

**Comment by erikras** [comment]
Released in [`v3.1.2`](https://github.com/erikras/redux-form/releases/tag/v3.1.2).
