### ISSUE TITLE
Field validation with 7.0.3

### ISSUE THREAD

**Issue by Puneetbh** [erikras/redux-form#3310]
i am using redux-form 7.0.3 for field level validation.

i have created validation component i.e. required

export const required = value => (value ? undefined : 'Please enter .')

Here i want to pass field name so i can use this component with all form fields and error should show based on field name

like Please enter First name, Please enter last name, Please enter Middle name

I have used this type of validation in 6.6.3 version

in that my component was like 

export const required = (field) => (value) => (value ? undefined : 'Please enter ${field}');

<Field
              name="title"
              type="text"
              maxLength="100"
              placeholder="Middle Name"
              component={renderInputField}
              validate={[required(First Name)]}
            />
<Field
              name="title"
              type="text"
              maxLength="100"
              placeholder="Middle Name"
              component={renderInputField}
              validate={[required(Last Name)]}
            />

Now i am not able to make this type of component, when i do this it gives error that "Errortext" prop passed does not contain value.

**Comment by tstirrat15** [comment]
Is this the same problem as #3288 ?

**Comment by danielrob** [comment]
Closing as duplicate.
