### ISSUE TITLE
Disable <Field type="" ... /> messing with values when custom input provided.

### ISSUE THREAD

**Issue by ilyadoroshin** [erikras/redux-form#3312]
### Are you submitting a **bug report** or a **feature request**?

**Feature request**

### What is the current behavior?

Currently if we pass type="radio" input.value would be undefined, but checked = true/false. And thats ok, if component="input"

### What is the expected behavior?
If component is set to custom, type shouldn't mess with the whole input.value workflow.

### Sandbox Link

https://codesandbox.io/s/wBENp92X
As you can see, I've created one custom input on top of material-UI RadioButton. I didn't want the form to be coupled with the options rendering (since i've got a lot of forms like this across the app, and if anything changes I would need to change it everywhere across the app). So I've bumped into a problem, that if I set type="radio" (checkbox as well) the Field works like <input type="radio" /> returning checked instead of value that I'm setting with onChange. 

### What's your environment?

redux-form 6+

**Comment by danielrob** [comment]
Redux-Form has it's API, and Material-UI has it's API, and just because they don't directly talk doesn't necessarily imply either of them are wrong... For your feature suggestion to be convincing I think it'd need to state why "messing with the flow" in this way is just wrong in general, not just for integrating two libraries, for which a [documented adaptor is available](https://github.com/erikras/redux-form-material-ui/blob/master/src/RadioButtonGroup.js).

**Comment by ilyadoroshin** [comment]
@danielrob I don't imply that redux-form is wrong, it's great! it just took me a couple of hours to realise, that even when you pass your own component renderer to "component" property, redux-form tends to work with this component as it's still <input />. 

Btw, this has nothing to do with MaterialUI, in this case it's just copy-pasted example.

**Comment by danielrob** [comment]
@ilyadoroshin ok so it seems like this is a documentation issue. A workaround might be using 
```
<Field
  component={component}
  props={{
    type="radio"
  }} 
/>
```
if you want to avoid the behaviour.

**Comment by ilyadoroshin** [comment]
@danielrob I've managed to get rid of type="radio" in the end, and of course there's plenty of ways to workaround :) it's just logical to disable out-of-the-box behaviour if you're creating your own renderer, isn't it? 

thanks anyways

**Comment by danielrob** [comment]
@ilyadoroshin the issue you raise is right, but not right on the money ;). Even for custom components, type=radio is currently how you can ask Field to give you the right props to render a controlled radio button. It just happens in your case that those aren't the right props for material-ui which presumably manages it's own checked state.

**Comment by ilyadoroshin** [comment]
@danielrob that's why it's not an issue but feature request :) 
closing then
