### ISSUE TITLE
Would be nice if it had isChanging property sent to the renderField also

### ISSUE THREAD

**Issue by adred** [erikras/redux-form#3313]
Currently, the only event related properties `renderField` receives are `asyncValidating`, `submitting`, `touched`, etc. It would be nice if there was `isChanging` for text fields. Something like this:
```
import React from 'react'
import { Field } from 'redux-form/immutable'
import CheckMark from '../CheckMark'

function renderField (field) {
  const {
    input, type, placeholder, 
    meta: {asyncValidating, isChanging, touched, error}
  } = field
  return (
    <div>
      <input {...input} placeholder={placeholder} type={type}  />
      {touched && !error && !asyncValidating && !isChanging && <CheckMark />}
    </div>
  )
}

export default function InputField (props) {
  const { name, type, placeholder } = props
  return (
    <Field name={name} type={type} component={renderField}
      placeholder={placeholder}  />
  )
}

```
My problem is, without `isChanging`, when there's a value in the textfield already, and when the user starts changing text(e.g using backspace), `<CheckMark />` shows up because all conditions are satisfied in this line
```
{touched && !error && !asyncValidating && <CheckMark />}
```
Ideally, it shouldn't show up until `onBlur` is triggered.

**Comment by timhwang21** [comment]
Just add `!focused` or whatever the prop is called to your check conditional render.

**Comment by adred** [comment]
@timhwang21 there's no `focused` property! But that's a good name.

**Comment by adred** [comment]
So there's an `active` property passed in the `meta` object. It solves the problem for me.
