### ISSUE TITLE
Cascade untouch on FieldArrays

### ISSUE THREAD

**Issue by Jakst** [erikras/redux-form#3314]
### Are you submitting a **bug report** or a **feature request**?
Feature request

### What is the current behavior?
Error is thrown. See #2623 

### What is the expected behavior?
Recursive untouch, meaning if I send untouch on 'members', it will untouch all fields in all rows of the fieldArray.

For example untouch('members') would remove touched status of all the following fields:
members[0].firstName members[0].lastName members[1].firstName members[1].lastName members[2].firstName members[2].lastName

And untouch('members[0]') would remove touched status of all the following fields:
members[0].firstName members[0].lastName

**Comment by gustavohenke** [comment]
~1.5 years without a comment here, so I'm closing!
If the issue persists, please open a new one while still providing as much context as possible. Thanks!
