### ISSUE TITLE
Please add asyncValidatingAndSubmitting property

### ISSUE THREAD

**Issue by adred** [erikras/redux-form#3316]
Right now, I can't immediately show the loader once the submit button is clicked because `asyncValidate` runs before it submits the form. I wish there's something that's passed to my decorated component that informs it that reduxForm is in the process of asyncValidating and, right after, submitting. I can't use the condition `{(submitting || asyncValidating) && <Loader />}` because it'll also be satisfied when an async validated field somewhere is triggered. So `asyncValidatingAndSubmitting` might be good solution?

Or is there a way I can stop `asyncValidate` on form submit? I think it's redundant in my case since I don't allow submission when there are errors in my form anyway.

Thanks for the awesome library.

**Comment by gustavohenke** [comment]
> I can't use the condition `{(submitting || asyncValidating) && <Loader />}` because it'll also be satisfied when an async validated field somewhere is triggered

Can you clarify what you meant by this?

Redux Form doesn't have a condition that both `asyncValidating` and `submitting` will be true.
The example you wrote and I quoted above _should work_.

**Comment by adred** [comment]
```
// InputField.js
function renderField (field) {
  const { input, type, placeholder, meta: {asyncValidating, error} } = field
  return (
    <div>
      <input {...input} placeholder={placeholder} type={type} />
      {(asyncValidating && !error) && <Loader />}
    </div>
  )
}

export default function InputField (props) {
  const { name, type, placeholder } = props
  return (
    <Field name={name} type={type} component={renderField} placeholder={placeholder} />
  )
}


// AuthForm.js
function asyncValidate (values) {
  return validateUsername(values.get('username')).then((valid) => {
    if (!valid) {
      return { username: 'Invalid username' }
    }
  })
  .catch((reason) => {
    return { exception: reason }
  })
}

function handleFormSubmit (values) {
  return authByApi(values.get('username'), values.get('password'))
  .catch(error => {
    throw new SubmissionError({
      password: error,
      _error: 'Login failed!',
    })
  })
}

function AuthForm(props) {
  return (
		<form onSubmit={props.handleSubmit(handleFormSubmit)}>
		  <InputField name='username' type='text' placeholder='Username' />
		  <InputField name='password' type='password' placeholder='Password' />
      <SubmitButton type='submit' label='Log In' />
      {(props.submitting || props.asyncValidating) && <Loader />}
		</form>
  )
}

export default reduxForm({
  form: 'authForm',
  validate: validate,
  asyncValidate: asyncValidate,
  asyncBlurFields: ['username'],
})(AuthForm)

```

As you can see, component `<Loader />` is used in both `<AuthForm />` and `<InputField />` component. So when the username field is `asyncValidating`, the `<Loader />` component will show up in the username field and beside the `<SubmitButton />` component. Hope that makes sense.

**Comment by mtramm** [comment]
> Or is there a way I can stop asyncValidate on form submit? I think it's redundant in my case since I don't allow submission when there are errors in my form anyway.

You can disable async validation on submit using [shouldAsyncValidate](http://redux-form.com/7.0.3/docs/api/ReduxForm.md/#-code-shouldasyncvalidate-params-boolean-code-optional-)

**Comment by gustavohenke** [comment]
Hm, sorry for the confusion!
You can do what @mtramm kindly remembered us is possible (and sincerely I missed when first reading your question).

..or you can also do some CSS and hide fields' `Loader` by adding a class to the form when `submitting` is true.

I hope one of these works for you!

**Comment by adred** [comment]
@mtramm @gustavohenke thanks for the fast reply. I will try it later.

**Comment by gustavohenke** [comment]
Since the prop proposed here is not going to be added - the situation of both `asyncValidating` and `submitting` never happens -, I'm closing this issue.

Feel free to keep the discussion going on.
