### ISSUE TITLE
reduxForm() wrapper not adding all props to wrapped component

### ISSUE THREAD

**Issue by nealoke** [erikras/redux-form#3318]
### Are you submitting a **bug report** or a **feature request**?
Bug

### What is the current behavior?
Currently the component that is wrapped by `reduxForm` does not receive all the props mentioned in the [`reduxForm`](http://redux-form.com/7.0.3/docs/api/ReduxForm.md/#instance-api) docs. It does not receive the `values`, `registeredFields` and `wrappedInstance` props.

### What is the expected behavior?
I expected that the `simpleForm.js` component would receive the `values` props as it is wrapped by the [`reduxForm`](http://redux-form.com/7.0.3/docs/api/ReduxForm.md/#instance-api) HOC

### Sandbox Link
[Simple form example](https://codesandbox.io/s/1wnwDQzRP)

### What's your environment?
(Unchanged from the simple form example)
react: `15.5.3`
react-dom: `15.5.3`
react-redux: `5.0.4`
redux: `3.6.0`
redux-form: `6.6.3` (in my project I am on `7.0.3`)
redux-form-website-template: `0.0.41`

**Comment by nealoke** [comment]
This is a `console.log(this.props)` of my wrapped component by `reduxForm`. The whitespace are props that I removed from the image just because they are custom props and not relevant.

![props](https://user-images.githubusercontent.com/17417414/29270490-5bbb367e-80f7-11e7-875f-8fff8f4a1b1f.png)

**Comment by gustavohenke** [comment]
Hi @nealoke, that's a classic error :)

You're looking at the component instance properties, and not at React props. _The component instance_ is what you get when you use `ref` in some component, while the props are like HTML attributes.

If you used `ref` in a component decorated by `reduxForm()`, what you would get is an object with those properties such as `values`, `registeredFields`, etc.

You can have access to the form values via [`formValues()` decorator](http://redux-form.com/7.0.3/docs/api/FormValues.md/) or selectors such as [`formValueSelector`](http://redux-form.com/7.0.3/docs/api/FormValueSelector.md/).

**Comment by nealoke** [comment]
@gustavohenke aah, that was not really clear to me. But how would you go about getting all values of a form? Or getting dynamic field values? Currently you explicitly need to write which fields you want but how do you select a dynamic field name field?

**Comment by nealoke** [comment]
For example I have a form called `myForm`. In that form an array creates the fields required `field_1`, `field_2`, `field_3`. How can I use the `formValueSelector` to select these values in each component?

**Comment by nealoke** [comment]
Nevermind I've finaly realised that the `mapStateToProps` also takes a second argument namely the `props`. So from there I can make it work 👍
