### ISSUE TITLE
For redux design perspective, redux-form should be the containers or presentational components?

### ISSUE THREAD

**Issue by CrisLi** [erikras/redux-form#332]
For redux design perspective, a redux-form component should be the container or presentational component?

According to the redux doc, react component can be classified as `Container Components` and `Presentational Components`. As my understanding, the `Presentational Components` are some pure stateless react components and can be reused in the application. As the beginning, I thought a redux-form should be `Presentational Component` since a form can be reused in the whole application. For example, the user form can be used in UserNew container and UserEdit container. But if I use redux-form, the form data is bind to the `state`, how should we design redux-form in a real world application?

**Comment by erikras** [comment]
I can tell you that I have used `redux-form`-decorated components in both scenarios. I don't believe that there is One Right Way on this; it depends on your specific use case.

**Comment by dtmunir** [comment]
@CrisLi how did you end up dealing with the UserNew and UserEdit containers?

**Comment by rosendi** [comment]
@CrisLi I'm also intersted

**Comment by CrisLi** [comment]
@dtmunir @rosendi Right now, I am using redux-form as `Presentational Component` , so there is a UseForm component, and then I have UserNew and UserEdit containers.

**Comment by rosendi** [comment]
@CrisLi yes, right but let's say each component has a different form config, i.e UserEdit has an extra name field with a custom validator and its MapDispatchToProps dispatches an instruction to send a PUT request while UserNew sends a POST request. How would you implement a container here?

**Comment by CrisLi** [comment]
@rosendi I'am passing the `handleSubmit` function as props to the **UseForm** component. In the **UserNew** container, the `handleSubmit` function will call POST API.  I'm only apply `mapDispatchToProps` in the container.
