### ISSUE TITLE
Null values in initialValues converted to empty string

### ISSUE THREAD

**Issue by rtymchyk** [erikras/redux-form#3320]
### What is the current behavior?
Setting an initial value of a field to `null` in `initialValues` of a form sets `input.value` to the empty string, but `meta.initial` is `null`.

### What is the expected behavior?
`input.value` is `null`. I think `null` should be treated differently than `undefined`.

**Comment by rtymchyk** [comment]
Actually, I guess the real issue is that `null` is treated as an invalid value, and is always converted to an empty string?

**Comment by rtymchyk** [comment]
The solution is to use `format={null}` on the `Field`. A bit obscure but I guess it works.

**Comment by davidfurlong** [comment]
Yeah I agree this is kindof strange. relevant docs for the next person: https://redux-form.com/7.1.1/docs/api/field.md/
