### ISSUE TITLE
Update es6-error to (at least) 4.0.1

### ISSUE THREAD

**Issue by pkoziol** [erikras/redux-form#3323]
Recently I had a problem with returning validation errors on submit by throwing `SubmissionError`. It turned out that instances of SubmissionError didn't have correct prototype.

es6-error 4.0.1 fixed that by adding some Babel magic to ES/jsnext build (see bjyoungblood/es6-error/pull/27 for details), but somehow I had version 4.0.0... You should probably bump version of es6-error to `^4.0.1` to prevent such a situation in the future.

I would create pull request instead opening issue, but I see that you have `package-lock.json` in your repo. That means I should use npm >= 5, right? Unfortunately I'm on npm 3 and don't want to break something in my project by upgrading it now.

**Comment by gustavohenke** [comment]
It's on `^4.1.1` now 🙂
