### ISSUE TITLE
Change getEventValue method to check the value property for checkboxes

### ISSUE THREAD

**Issue by jmzagorski** [erikras/redux-form#3327]
### Are you submitting a **bug report** or a **feature request**?
feature request

### What is the current behavior?
When a value is changed in a checkbox, the checked value is used in the `CHANGE` event

### What is the expected behavior?
When a value is changed and the input type is checkbox, `getEventValue` should check the value property first to allow for custom values. For example. . . `<input name="someProperty" type="checkbox" value="{fooValue}" checked="{!!fooValue}" >`. So if fooValue was "fooBar", my form state would have `someProperty="foobar"` instead of `someProperty=true`.

**Comment by gustavohenke** [comment]
~1.5 years without a comment here, so I'm closing!
