### ISSUE TITLE
syncValidation overrides submitError

### ISSUE THREAD

**Issue by mattkrick** [erikras/redux-form#333]
In a login form, when a user enters an incorrect password, I'd like the password's `submitError` to be "Incorrect password" and then I'd like to clear the field, basically a combo of your plugins example + submit validation example. 
```
form: formReducer.plugin({
      authForm: (state, action) => {
        switch(action.type) {
          case 'redux-form/STOP_SUBMIT':
            return {
              ...state,
              password: Object.assign({}, state.password, {value: ''})
            };
          default:
            return state;
        }
      }
    })(state.form, action)
```
When I try to do this, I see `Required` which is my syncValidation error message. Is there a way to get the `submitError` to override the `syncValidation` error?

**Comment by erikras** [comment]
No, the sync validation error always takes precedent. What you _can_ do is to use the form-wide error, the special error key `_error` to display your "Incorrect password" message like the Submit Validation example does. There is currently no way to have a field-specific submit error override the sync error.
