### ISSUE TITLE
[Question] Do not invoke asyncValidation if field value was not changed

### ISSUE THREAD

**Issue by enheit** [erikras/redux-form#3331]
I have field on the form which has asyncValidation (onBlur & onSubmit) on uniqueness. Is it possible to not invoke asyncValidate function onBlur event if field value was not changed?

I would like to do something like this:
```
shouldAsyncValidate: ({initialValues, values, blurredField}) => initialValues[blurredField] !== values[blurredField];
```

**Comment by gustavohenke** [comment]
You probably can do this in the `asyncValidate` function itself:

```js
asyncValidate (values, dispatch, props, blurredField) {
  if (values[blurredField] === props.initialValues[blurredField]) {
    return Promise.resolve();
  }

  // go ahead and do the validation
}
```

This is probably not intuitive *at all*, and it should work with `shouldAsyncValidate`too.
Let me know if it works for you.

**Comment by enheit** [comment]
@gustavohenke Thank you! That was exactly what I need. I have found almost the same solution but your looks simpler.
