### ISSUE TITLE
[v7]fields losing focus after first onChange

### ISSUE THREAD

**Issue by iTonyYo** [erikras/redux-form#3332]
Do you know how to solve this problem? Fields losing focus after first onChange, so I stopped using class & `render()`, then got this problem... I tried to use `prop-types`, but it dosen't work.

![image](https://user-images.githubusercontent.com/5499703/29411442-7021a84e-831a-11e7-830a-ab94362062ad.png)

```json
"react": "^15.6.1",
"redux": "^3.7.2",
"redux-form": "^7.0.3",
```

**./src/view/ViewSignin/FormSignin.js**

```javascript
'use strict';

import React, { Component } from 'react';
import Radium from 'radium';
import { Link } from 'react-router-dom';
import {
  Field,
  reduxForm
} from 'redux-form';

const renderField = ({
  input,
  type,
  label
}) => (
  <div>
    <input { ...input } type={ type } placeholder={ label } />
  </div>
);

const FormSignin = (props) => {
  const { handleSubmit } = props;
  return (
    <form className='frm-signin' onSubmit={ handleSubmit }>

      <div className='border-box xy-center row field-area'>
        <div className='fields'>
          <Field
          name="userAccount"
          component={ renderField }
          type="text"
          label='电子邮件 / 手机号'/>

          <i></i>

          <Field
          name="userPassword"
          component={ renderField }
          type="password"
          label='密码'/>
        </div>
      </div>

      <div className='border-box xy-center row button-area'>
        <div>
          <button
            type="submit">
            <span className='xy-center'>
              登录
            </span>
          </button>
        </div>
      </div>

      <div className='border-box row others-area'>
        <Field
          className='chk-keep-signin'
          name="keepSignin"
          id="keep-signin"
          component="input"
          type="checkbox"
        />

        <label className='lbl-keep-signin' htmlFor="keep-signin">
          保持登录
        </label>

        <Link className='right btn-signup'
              to='signin'>
          立即注册
        </Link>

        <Link className='right clean-link btn-forget-password'
              to='signin'>
          忘记密码
        </Link>
      </div>

    </form>
  );
}

export default reduxForm({
  form: 'signin'
})(FormSignin);
```

**Comment by iTonyYo** [comment]
Solved this problem after reading [Fields losing focus on change/blur, Form Re Registering fields #1609](https://github.com/erikras/redux-form/issues/1609) & [this twitter](https://twitter.com/andrestaltz/status/768087662557274112)。

**Comment by softwarefactory1** [comment]
I had the same problem with an html table in which I have input text lines in a column. inside a loop I read a json object and I create rows in particular I have a column with inputtext.

            http://reactkungfu.com/2015/09/react-js-loses-input-focus-on-typing/

            I managed to solve it in the following way


        import { InputTextComponent } from './InputTextComponent';
        //import my  inputTextComponent 
        ...

var trElementList = (function (list, tableComponent) {

    var trList = [],
        trElement = undefined,
        trElementCreator = trElementCreator,
        employeeElement = undefined;



    // iterating through employee list and
    // creating row for each employee
    for (var x = 0; x < list.length; x++) {

        employeeElement = list[x];

        var trNomeImpatto = React.createElement('tr', null, <td rowSpan="4"><strong>{employeeElement['NomeTipologiaImpatto'].toUpperCase()}</strong></td>);
        trList.push(trNomeImpatto);

        trList.push(trElementCreator(employeeElement, 0, x));
        trList.push(trElementCreator(employeeElement, 1, x));
        trList.push(trElementCreator(employeeElement, 2, x));

    } // end of for  

    return trList; // returns row list

    function trElementCreator(obj, field, index) {
        var tdList = [],
            tdElement = undefined;

        //my input text
        var inputTextarea = <InputTextComponent
            idImpatto={obj['TipologiaImpattoId']}//index
            value={obj[columns[field].nota]}//initial value of the input I read from my json data source
            noteType={columns[field].nota}
            impattiComposite={tableComponent.state.impattiComposite}
            //updateImpactCompositeNote={tableComponent.updateImpactCompositeNote}
        />

        tdElement = React.createElement('td', { style: null }, inputTextarea);
        tdList.push(tdElement);


        var trComponent = createClass({

            render: function () {
                return React.createElement('tr', null, tdList);
            }
        });
        return React.createElement(trComponent);
    } // end of trElementCreator

});
...    
    //my tableComponent
    var tableComponent = createClass({
        // initial component states will be here
        // initialize values
        getInitialState: function () {
            return {
                impattiComposite: [],
                serviceId: window.sessionStorage.getItem('serviceId'),
                serviceName: window.sessionStorage.getItem('serviceName'),
                form_data: [],
                successCreation: null,
            };
        },

        //read a json data soure of the web api url
        componentDidMount: function () {
            this.serverRequest =
                $.ajax({
                    url: Url,
                    type: 'GET',
                    contentType: 'application/json',
                    data: JSON.stringify({ id: this.state.serviceId }),
                    cache: false,
                    success: function (response) {
                        this.setState({ impattiComposite: response.data });
                    }.bind(this),

                    error: function (xhr, resp, text) {
                        // show error to console
                        console.error('Error', xhr, resp, text)
                        alert(xhr, resp, text);
                    }
                });
        },

        render: function () {
    ...
    React.createElement('table', {style:null}, React.createElement('tbody', null,trElementList(this.state.impattiComposite, this),))
    ...
    }



            //my input text
            var inputTextarea = <InputTextComponent
                        idImpatto={obj['TipologiaImpattoId']}//index
                        value={obj[columns[field].nota]}//initial value of the input I read //from my json data source
                        noteType={columns[field].nota}
                        impattiComposite={tableComponent.state.impattiComposite}//impattiComposite  = my json data source

                    />//end my input text

                    tdElement = React.createElement('td', { style: null }, inputTextarea);
                    tdList.push(tdElement);//add a component

        //./InputTextComponent.js
        import React from 'react';

        export class InputTextComponent extends React.Component {
          constructor(props) {
            super(props);
            this.state = {
              idImpatto: props.idImpatto,
              value: props.value,
              noteType: props.noteType,
              _impattiComposite: props.impattiComposite,
            };
            this.updateNote = this.updateNote.bind(this);
          }

        //Update a inpute text with new value insert of the user

          updateNote(event) {
            this.setState({ value: event.target.value });//update a state of the local componet inputText
            var impattiComposite = this.state._impattiComposite;
            var index = this.state.idImpatto - 1;
            var impatto = impattiComposite[index];
            impatto[this.state.noteType] = event.target.value;
            this.setState({ _impattiComposite: impattiComposite });//update of the state of the father component (tableComponet)

          }

          render() {
            return (
              <input
                className="Form-input"
                type='text'
                value={this.state.value}
                onChange={this.updateNote}>
              </input>
            );
          }
        }

**Comment by blazestudios23** [comment]
I'm having the same issue of losing focus onChange. I've tried several recommended solutions to no avail. 

Below is my code:

`import React, { Component } from 'react';
import { connect } from 'react-redux';
import { compose } from 'redux';
import { Field, reduxForm, change, untouch, formValueSelector } from 'redux-form';
import { Row, Col, Label, Input, FormFeedback, FormGroup } from 'reactstrap';
import { Typeahead } from 'react-bootstrap-typeahead';
import 'react-bootstrap-typeahead/css/Typeahead.css';
import 'react-bootstrap-typeahead/css/Typeahead-bs4.css';
import uuidv1 from 'uuid/v1';

class dynamicField extends Component {

  renderField = (fieldData) => {
      switch (fieldData.type) {
      case 'typeahead':
        return this.renderTypeAheadField(fieldData);
      case 'radio':
        return this.renderRadioField(fieldData);
      case 'checkbox':
        return this.renderCheckBox(fieldData);
      case 'select':
        return this.renderSelectField(fieldData);
      default:
        return this.renderDefault(fieldData);
    }
    };

  renderTypeAheadField = ({ input, meta, ...rest }) => (
    <span>
      <Typeahead
        className={meta.touched && meta.error ? 'alert-danger' : ''}
        {...input}
        {...rest}
        labelKey="value"
        clearButton
        selected={this.props.jobSpec ? this.props.jobSpec : []}
        minLength={2}
      />
      { meta.touched && meta.error && <FormFeedback tooltip >{meta.error}</FormFeedback>}
    </span>
  );

  renderRadioField = ({ input, options, meta, required, label, ...rest }) => (
    <FormGroup row>
      <Col><strong className="col-sm-2" >{label} </strong></Col>
      {options.map((option) => <Col key={'col' + uuidv1()} >
        <Label key={'label' + uuidv1()} >
          <Input type="radio"
          {...input} {...rest}
          value={option.value}
        className={meta.error && required ? 'alert-danger' : ''}
        checked={option.value === this.props.scheduleTypeValue}
        key={'option' + uuidv1()} />
        {option.label}</Label>
      </Col>
      )}
    { meta.error && required &&
      <FormFeedback tooltip >{meta.error}</FormFeedback>}
    </FormGroup>
  );

  renderSelectField = ({ input, options, meta, required, id, label, ...rest }) => (
    <FormGroup>
      <Label for={id} ><strong>{label}</strong></Label>
      <Input type="radio"
        id={id}
        {...input}
        {...rest}
        className={meta.error && required ? 'alert-danger' : ''}
        >
      {options.map((option) => <option key={'option' + uuidv1()} >{option.label}</option>)}
    </Input>
    { meta.error && required &&
      <FormFeedback tooltip >{meta.error}</FormFeedback>}
    </FormGroup>
  );

  renderCheckBox = ({ input, meta, required, label, ...rest }) => (
    <FormGroup check inline key={'col' + uuidv1()} >
        <Label check key={'label' + uuidv1()} >
          <Input type="checkbox"
          {...input}
          {...rest}
          className={meta.error && required ? 'alert-danger' : ''}
          key={'option' + uuidv1()} />
        {label}</Label>
      { meta.error && required &&
      <FormFeedback tooltip >{meta.error}</FormFeedback>}
    </FormGroup>
  );

  renderDefault = ({ input, id, meta, required, label, ...rest }) => (
    <FormGroup>
      <Label for={id} >{label}</Label>
         <Input
           className={meta.touched && meta.error && required ? 'alert-danger' : ''}
           {...input}
           {...rest}
           id={id}
          />
          { meta.touched && meta.error && required &&
      <FormFeedback tooltip >{meta.error}</FormFeedback>}
    </FormGroup>
  );

  render () {
    return (
      <Field
        options={this.props.options}
        label={this.props.label}
        name={this.props.name}
        type={this.props.type}
        key={this.props.key}
        required={this.props.required}
        id={this.props.id}
        placeholder={this.props.placeholder}
        component={this.renderField}
      />
    );
  }
};

const mapStateToProps = (state) => ({
    jobSpec: selector(state, 'jobSpec'),
    scheduleTypeValue: selector(state, 'collectorSchedule'),
  });

const selector = formValueSelector('formWizard');

export default compose(
  connect(mapStateToProps),
  reduxForm({
    form: 'formWizard',
    destroyOnUnmount: false,
  })
)(dynamicField);
`
