### ISSUE TITLE
registeredFields prop is not passed on to the decorated form component.

### ISSUE THREAD

**Issue by mtramm** [erikras/redux-form#3337]
### Are you submitting a **bug report** or a **feature request**?

Bug report

### What is the current behavior?

The registeredFields property is not passed on to the form component.

### What is the expected behavior?

The registeredFields property on the form component should contain the registered fields according to the [documentation](http://redux-form.com/7.0.3/docs/api/ReduxForm.md/#-code-registeredfields-array-code-)

### Sandbox Link

https://codesandbox.io/s/wk7m404kvk

### What's your environment?

redux-form v7.0.3

### Other information

Simply adding ```registeredFields: registeredFields,``` to reduxFormProps in createReduxForm.js solves the issue.

**Comment by gustavohenke** [comment]
`registeredFields` is a Redux Form instance property, and it *is not* a [React component prop](http://redux-form.com/7.0.3/docs/api/Props.md/).
These are different. Have a look here for some explanation: https://github.com/erikras/redux-form/issues/3318#issuecomment-322172141
