### ISSUE TITLE
checkbox doesn't set `checked`, changes value between true/false

### ISSUE THREAD

**Issue by bendiy** [erikras/redux-form#334]
I'm a little confused by how checkboxes and radio buttons work in the example. On the simple example:
https://erikras.github.io/redux-form/#/examples/simple

Checking `Employed` checkbox just sets the input's `value="true"`. Unchecking sets it to `value="false"`. I believe it should leave `value` alone and instead add the `checked` property to the input. On the radio buttons, `checked` is never set.

**Comment by erikras** [comment]
The `checked` is being set in the code.
```js
<input type="radio" {...sex} value="male" checked={sex.value === 'male'}/> 
```

You might have a good argument against setting `value` for a checkbox, but `redux-form` can't know what kind of input it is until it receives an event. However, is there really a use case for needing a non-boolean `value` on a checkbox?

**Comment by bendiy** [comment]
The problem I'm having is that the state of the checkbox being checked is based on the `value="true"` or `"false"` instead of `checked`.

My use case is trying to use redux-form with the material-ui library:
http://material-ui.com/#/components/switches

It supports the `defaultChecked={true}` prop. I think I'm going to have to look a little deeper into integrating redux-form with material-ui. Input `type="text"` is working fine, but I think there are enough differences with `checkbox`, `radio` and their `DatePicker` to break compatibility between the two libraries.

**Comment by erikras** [comment]
Keep in mind that you have complete control over how the values are passed from the redux-form field to your input component. i.e. you don't have to do `{...myField}`, but you can pass each attribute separately, as long as you pass `value` and `onChange`, that's all that redux-form cares about. For example, say you had a bizarre checkbox component that insisted on using the string values `'yes'` and `'no'`, but you wanted a boolean in Redux, you could do
```js
<WeirdSwitch
  value={myField.value ? 'yes' : 'no'}
  onChange={value => myField.onChange(value === 'yes')}/>
```

**Comment by dexwiz** [comment]
I agree that checking boxes should flip the checked property, not the value. In normal HTML posts, having a value of true or false has no bearing on if the form is submitted. Its the checked property that determines this.

Also groups of checkboxes are pretty common. Instead of each checkbox having its own name, they should be able to share a name. (group:option1, group:option2 over option1:true, option2:false). This can already be done with radio groups. But since the value is overwritten with true/false, this is impossible.

Finally, using true/false to determine checked/unchecked makes using the intermediate property awkward.

**Comment by dexwiz** [comment]
Upon further consideration, I realized a group of checkboxes would require and array of sort sort to store values. Radio groups work because only one button is ever selected. 

But when passing an array of values for a group of checkboxes, you have append [] to the name to get servers to parse them correctly (like group[]). This solution is already inelegant. Also you couldn't create variable names with [] in them, so this should be avoided. 

So it looks like creating a field for each checkbox is the way to go.

**Comment by dbismut** [comment]
This is how I handled this with `material-ui` checkbox element:

```javascript
<Checkbox checked={terms.value} onCheck={(e, checked) => terms.onChange(checked)} />
```

**Comment by olmg-mike** [comment]
Thanks! @dbismut  I was using a much worse hack to get Checkbox to work.  Your solution was much simpler.

**Comment by glennr** [comment]
+1 for the answer from @dbismut . Nice one bruv.

**Comment by tobice** [comment]
Also +1 for the answer from @dbismut. In case anyone was interested, I wrapped the Material UI checkbox by my own component:

```javascript
import React from 'react';
import MaterialCheckbox from 'material-ui/lib/checkbox';

export default (props) => {
  let newProps = Object.assign({}, props, {
    value: null,
    checked: props.value,
    onCheck: (e, checked) => props.onChange(checked)
  });
  return <MaterialCheckbox {...newProps} />
};
```

You can use this component the same way like other inputs:

```javascript
<Checkbox label="Terms & conditions" {...terms} />
```

**Comment by GuillaumeCisco** [comment]
Hello everybody.
Thank you @tobice for your comment!
I've manage to successfully make it work with v6 API.
For people interested:
```javascript
import React, {Component, PropTypes} from 'react';
import Checkbox from 'material-ui/Checkbox';

class CheckboxInput extends Component {

    onCheck (e, checked) {
        this.props.input.onChange(checked);
    }

    render() {
        return <Checkbox
            label="check it"
            {...this.props.input}
            checked={this.props.input.checked}
            onCheck={this.onCheck.bind(this)}
        />;
    }
}

export default CheckboxInput;
```

**Comment by erikras** [comment]
Thanks for that, @GuillaumeCisco. You might find [`redux-form-material-ui`](https://github.com/erikras/redux-form-material-ui) interesting. It does this for you for many types of Material UI components.

**Comment by GuillaumeCisco** [comment]
Thank you @erikras :)
I'd like to bring attention on this line:
```javascript
checked={this.props.input.checked}
```

Because before, I used:
```javascript
checked={this.props.input.value}
```
It was working well in development mode, but not in production mode (minimified code, no webpack server, with webpack dll plugin). Still don't know why, But using `props.input.checked` and `OnChange` binding made it work...
I think more investigation is needed here...

**Comment by littleindianboy** [comment]
sex value is always true

**Comment by jingxinxin** [comment]
Maybe MaterialCheckbox component has the function of onCheck to change the value,
but other's DIY Checkbox does't work.

for example, like semantic-ui-react 
<Checkbox
      label={rest.label}
      checked={!!input.value}
      onClick={(e, { checked }) => input.onChange(!checked)}
/>
the checked's value should change

**Comment by viiiprock** [comment]
For semantic-ui-react, what I have done is 
```js
      <Checkbox
        {...input}
        value={input.value ? 'on' : 'off'}
        onChange={(e, { checked }) => input.onChange(checked)}
        {...custom}
      />
```
The `values` change to `true` or `false` state.

**Comment by roytz** [comment]
@viiiprock @dbismut 
I did the same but the object I get after I submit the form is `""` instead of `false`..
Any ideas why?

**Comment by viiiprock** [comment]
@roytz 
You should post your code here, I've never used material-ui, I have just take a look at that component and thing you should try `toggled` for `value` and the `onToggle` for `onClick`

**Comment by roytz** [comment]
Here is my code -
```
const renderToggle = ({ input, ...props }) => (<Toggle
      toggled={!!input.value}
      onToggle={(event, value) => input.onChange(value)}
      {...props}
    />);
```

I will try to change the `toggled` to `value` and also the `onToggle` to `onClick` (though the material-ui docs suggest I would use `toggled` and `onToggle`) and update.

Thank you @viiiprock

**Comment by viiiprock** [comment]
@roytz  no, you did right, don't change it. I will try material-ui and reply later.

**Comment by viiiprock** [comment]
hey @roytz , sorry I didn't have time to test, but did you take a look at this example?
http://redux-form.com/6.7.0/examples/material-ui/
please try
```
const renderToggle = ({ input, ...props }) => (
<Toggle
 {...input}
 toggled={input.value ? true : false}
 onToggle={(event, value) => input.onChange(value)}
 {...props}
/>);
```

**Comment by roytz** [comment]
Thanks @viiiprock but I still get the same result.. The state changes as I would expect (showing the value as `true`/`false`) but when I submit the form I get the value as "" (when it should be `false`)

**Comment by roytz** [comment]
I found [this](https://github.com/erikras/redux-form/issues/2922) issue and added the attribute `normalize={value => !!value}` to my `Field` tag and it seems to solve it.

**Comment by viiiprock** [comment]
Yeah may be, found the last sentence in the API docs, `Other properties (not documented) are applied to the root element.`

**Comment by kcthota** [comment]
Here's is what I did with Semantic UI checkbox.

1) Initialize the form field value as boolean.
reduxForm({
    form:'RegisterForm',
    initialValues: {
        acceptedTerms:false
    }
}
2) Defined the checkbox component as below:

<Form.Field error={field.meta.invalid}>
            <Checkbox checked={field.input.value ? true : false} onChange={(e,item) => field.input.onChange(item.checked)} label={field.label} />            
        </Form.Field>

**Comment by kimfucious** [comment]
I know this is an old closed thread, but Google kept sending me here as I was trying to find a solution of working with checkboxes, Redux Form, and Material UI.

As I read the posts from @bendiy I think he was suffering from the fact that (without touching anything) Redux Form will set the value of a checkbox field to the boolean of true when it is checked.  And Material UI is expecting (with props validation) on its FormControlLabel element value to be a string.  So it throws warnings when it receives a boolean.

Another complicating--confusing may be a better word--factor is that (when a filed is of type=checkbox) this does not work the other way around (i.e. value is controlled by checked), in that you cannot set the initial value of the checkbox field to "false" (using initialValues) and expect that checked will become false as a result.  In fact, anything put there in initial values will have the field thinking it's checked, except for the boolean, false, which you don't need as the default value is already false.

If you want to set the default value of the checkbox to true, you can use initialValues, putting anything as a value for the checkbox, except boolean, false, as this will actually work as expected.

That said, I only needed to implement one line of code on the FormControlLabel element in order for the checked param to affect the value param, setting it to a string.  This is similar to what @erikras suggested in his post on 27 Nov 2015.

The below represents the return of a  (reusable) component (renderField) that is called from a form via a `component={renderField}` param.  There's some logic in there to determine if the field is a checkbox or not and render an appropriate FormControlLabel based on passed in props.

The gist of this is that all I needed to do was add `value={input.checked ? "true" : "false"}` to the FormControlLabel to take the boolean from checked and set the value of value as a string of either "true" or "false".

I hope this might help someone looking for a similar answer.

```
return (
    <div>
      {(type === "text" || type === "date") && (
        <FormControl
          className={classes.formControl}
          required={required}
          fullWidth
        >
          <InputLabel htmlFor={htmlFor}>{label}</InputLabel>
          <Input
            {...input}
            autoFocus={autoFocus}
            placeholder={placeholder}
            type={type}
            multiline={multiline}
            endAdornment={endAdornment}
            startAdornment={startAdornment}
          />
          {multiline && (
            <FormHelperText>
              {input.value.length} / {maxLength}
            </FormHelperText>
          )}
          {touched && error && <FormHelperText>{error}</FormHelperText>}
        </FormControl>
      )}
      {type === "checkbox" && (
        <FormControlLabel
          {...input}
          **value={input.checked ? "true" : "false"}**
          htmlFor={htmlFor}
          control={isSwitch ? <Switch /> : <Checkbox />}
          label={label}
        />
      )}
    </div>
```

**Comment by jesusruizlopez** [comment]
For me, this work perfect!
`
<Checkbox
    color="primary"
    onClick={ (event) => { this.handleCheckbox('checkbox-1', event) }}
/>

handleCheckbox(name, event) {
    console.log(name);
    console.log(event.target.checked);
};
`

**Comment by ArtemBernatskyy** [comment]
If someone comes to find an answer for custom checkbox then you need to initialize your value in this way https://redux-form.com/7.0.2/examples/initializefromstate/

**Comment by shiraze** [comment]
I was also struggling with getting the 'value' of my field data to determine whether the checkbox should be checked or not, and making sure form submissions included the 'value' rather than a boolean checked status.

My underlying datasource has a value of 0/1 to determine whether a checkbox is unchecked/checked respectively.
The following worked for me:
`
          <Checkbox
            checked={input.value === "1"}
            onChange={(e, checked) => input.onChange(checked ? "1" : "0")}
          />
`
Where `input` is the props supplied by redux-form. I've used the `onChange` handler to update the value associated with the control.
Without the onChange handler I couldn't change the state of the checkbox - it would either stay selected/deselected. Without the checked property my checkboxes were always initially checked (as both "0" and "1" values from my datasource are truthy)
