### ISSUE TITLE
Question: Sync validate error show other position 

### ISSUE THREAD

**Issue by flyking** [erikras/redux-form#3344]
A form has many Field, sync validate will give some errors,the error position is not after this input.
eg: A B C Field,  I want to show A's error and B's error after C Field.how to do this? thank you

**Comment by flyking** [comment]
My code like this:

renderInput({
    input,
    label,
    type,
    maxLength,
    meta: {
      touched,
      error
    }
  }) {
    let errors = this.state.errors
    if (!error) {
      delete errors[input.name]
    } else {
      errors[input.name] = error;
    }
    return (
      <div>
        <input {...input} placeholder={label} maxLength={maxLength} type={type}/>
      </div>
    )
  }

<Field name='userName' component={this.renderInput.bind(this)} type='text' label='持卡人姓名'  maxLength='8' />
<Field name='credentialNum' component={this.renderInput.bind(this)} type='text' label='证件号码' maxLength='18'/>
<Field name='validityDate' component={this.renderInput.bind(this)} type='text' label='月份/年份' maxLength='4'/>
<div className={classnames('input-err', this.state.errors.userName
          ? 'visible'
          : 'hidden')}>
          <p>{this.state.errors.userName}</p>
        </div>
<div className={classnames('input-err', this.state.errors.credentialNum
          ? 'visible'
          : 'hidden')}>
          <p>{this.state.errors.credentialNum}</p>
        </div>

<div className={classnames('input-err', this.state.errors.validityDate
          ? 'visible'
          : 'hidden')}>
          <p>{this.state.errors.validityDate}</p>
        </div>

**Comment by flyking** [comment]
I use  this example http://redux-form.com/7.0.3/examples/syncValidation/

**Comment by gustavohenke** [comment]
You can do this by using the [`getFormSyncErrors` selector](http://redux-form.com/7.0.3/docs/api/Selectors.md/#-code-getformsyncerrors-formname-string-code-returns-code-state-gt-formsyncerrors-object-code-).

Select the errors in your form component, then render them right after your C field.

**Comment by flyking** [comment]
thank you very much,I use your method resolve this problem
