### ISSUE TITLE
Rerender list of toggle buttons not working

### ISSUE THREAD

**Issue by digitaledge** [erikras/redux-form#3347]
Hi,
i created a toggle button form component using redux form and reactstrap.
Actually the buttons do not re-render on changes, wich affects the class that isnt updating. 

I posted the code earlier on Stackoverflow here: https://stackoverflow.com/questions/45823539/how-to-create-bootstrap-toggle-buttons-with-react-and-redux-form

Is this a bug or am i missing something?

**Comment by gustavohenke** [comment]
I answered your StackOverflow question. Let's keep the discussion there.
