### ISSUE TITLE
getFormState side-effects

### ISSUE THREAD

**Issue by snhasani** [erikras/redux-form#3349]
I have many forms in my app. I created a single form reducer for each of them under its parent reducer and combined them. For fetching theirs data I am using `getFormState`, Everything is okay in fetching form states side, but in redux state active form duplicated in all redux-form reducers!!!

![image](https://user-images.githubusercontent.com/23160/29632103-1f1e96fe-8857-11e7-97a4-77b206610799.png)

P.S: when I use a single `form` reducer in my root reducer without use `getFormState` everything working well.

P.S: [I created a question about this issue on stackoverflow with additional information like source code
](https://stackoverflow.com/questions/45893574/redux-form-getformstate-side-effects)
```bash
    OS: Mac,
    node: 8.3.0,
    react: 15.4.2,
    redux: 3.6.0,
    redux-form: 7.0.0,
    browser: 60.0.3112.101 (Official Build) (64-bit)
```

**Comment by gustavohenke** [comment]
I replied to your questions in StackOverflow: https://stackoverflow.com/a/46130915/2083599
