### ISSUE TITLE
Validate form only when submit button is pressed 

### ISSUE THREAD

**Issue by limpbrains** [erikras/redux-form#335]
How can I create form which sync validation function runs ONLY when user tries to submit it?
`touchOnBlur` is part of the solution, but when field is touched, form starts to show erros on every change, I'm trying to avoid this.

I still want to hide errors when onChange or onBlur fires.

#81 looks like as a solution.
or new property `validateOnSumbitOnly`

**Comment by erikras** [comment]
The sync validation is going to run on every change no matter what. How you decide to show the errors is up to you. If you only want them to show up on submit, then yes, turning `touchOnBlur` to `false` will leave them untouched, and then you can use the `touched` flag to only show when submit has failed for validation reasons.

**Comment by limpbrains** [comment]
Problem appears after first unsuccessfull submit.
I'm starting to editing field to fix error, it has touched flag so validate show error on every change.

I've just understood that I can do validation in onSubmit callback. Looks like like hack, but I can achive the behaviour that I need.

Thanks for the great lib!
