### ISSUE TITLE
change(form:String, field:String, value:any) causes unknown error

### ISSUE THREAD

**Issue by emmareardon1** [erikras/redux-form#3353]
I’m using redux form and want to use an action creator to call change() on my form to update a field value.
I wondered why my implementation doesn’t work?

Implementation:
```js
export default connect(state => ({
  cardNumber: get(state.form,  ${CARD_DETAILS_FORM_ID}.values.${CARD_NUMBER.name}),
}), {
  refresh: value => change(‘cardDetailsForm’, ‘number’, value),
})(AddCardDetails);
```
   
Thanks, Emma

**Comment by emmareardon1** [comment]
When I call this.props.refresh(123456) from within my connected AddCardDetails component. I get the following error...

_reactForm.change) is not a function
    at refresh (AddCardDetails.jsx:93)

**Comment by peterfairfield** [comment]
@emmareardon1 the docs are behind. These have the API documented properly:

https://davidkpiano.github.io/react-redux-form/docs/api/actions.html#actions-change

change now only takes change('number', value) now

these docs (linked from the front page of react-redux) are incorrect:

https://redux-form.com/7.0.4/docs/api/actioncreators.md/

about your second issue, are you importing change properly?

**Comment by gustavohenke** [comment]
This was more of a usage support question, not a real bug or feature request.
Please reopen it as one if you feel that it needs further improvement. Otherwise, please use StackOverflow.
