### ISSUE TITLE
type="search" not supported?

### ISSUE THREAD

**Issue by rlueder** [erikras/redux-form#3355]
### Are you submitting a **bug report** or a **feature request**?
Would it be possible to add support to type="search" and other HTML5 [input types](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#Form_<input>_types)?

### What is the current behavior?
I'm trying to set the _type_ attribute of my Field components to "search" but noticed when inspecting the rendered components that the attribute is replaced by _type="text"_.

### What is the expected behavior?
I was hoping to save time by using the built-in clear icon displayed inside input fields when type is set to "search" in modern browsers: [\<input type="search"\>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/search)

Thanks!

**Comment by gustavohenke** [comment]
Can you show some example?
Setting the `type` shouldn't be a problem, you can check this throughout the Redux Form examples.

Also, since this is more of a usage question, please note that it's usually better suited for StackOverflow, and not the GitHub issue tracker.

Thanks for using Redux Form!
