### ISSUE TITLE
structure/immutable/deepEqual should use === (or better?)

### ISSUE THREAD

**Issue by aliu-d3d** [erikras/redux-form#3357]
### Are you submitting a **bug report** or a **feature request**?
Bug Report

### What is the current behavior?
When using a custom field that coerces strings into numbers, immutable/deepEqual will return true when comparing string "1." vs numeric 1.  This is because it uses ==, which will coerce "1." to 1 before doing the comparison.  This causes problems with onChange handlers, where redux-form doesn't think anything changed.

### What is the expected behavior?
immutable/deepEqual should at the minimum be using === to do comparisons.  Theoretically, it seems like immutable/deepEqual should be satisfied by merely doing a reference comparison between the two values.  That's what using immutablejs is supposed to buy us anyway.

### Sandbox Link
See: https://codesandbox.io/s/8x3kox4949
Enter "1." and then try to backspace

### What's your environment?
redux-form: 6.7.0
Chrome: 61.0.3163.59
OS: macOS 10.12.5
Node: v6.10.2

This problem has existed since commit bd4cd9e

### Other information
The plain version is doing the right thing.

**Comment by timhwang21** [comment]
Isn't this intentional? Can this be solved from your end by making the input have `type="number"` or with the `parse` prop?

**Comment by aliu-d3d** [comment]
Pretty sure this is not intentional, since structure/plain/deepEqual uses === for the exact same thing.

How would you propose this be solved by the `parse` prop? My code is already telling redux-form exactly what it wants, it's just that redux-form doesn't think it's a change due to type coercion. (I don't think `parse` can fix this.)

In my particular case, using `type="number"` is also inappropriate, because the form is auto-saving and re-initializing.  Using a number field would cause the user to be unable to enter decimal points, if they couldn't beat the auto-save debounce window.

e.g.:
1. User types "1." into empty number field
2. number field coerces "1." into 1
3. auto-save triggers, and re-initializes form.
4. form value is now 1 again, eating the decimal point.

**Comment by aliu-d3d** [comment]
Any updates on this?  The fix is really quite simple, and would make the immutable side have the same behavior as the plain side.

**Comment by gustavohenke** [comment]
Hi @aliu-d3d, the best way to get things done is to make a PR providing at least a failing test case, or even provide a full solution.
Since most code decisions are made exclusively by @erikras, it gets way easier for him to see your proposal if you submit a PR - it's usually 5 open PRs to see against 400+ open issues!

**Comment by erikras** [comment]
Ah, the old `'1.'` problem... it comes up in so many ways.

@aliu-d3d In your sandbox, you are replicating the `parse` functionality that `redux-form` already provides for you. But you should always have a complimentary `format` function to convert it back into a string. See [Value Lifecycle Hooks](https://redux-form.com/7.0.4/docs/valuelifecycle.md/).

However, you are still very correct that `immutable/deepEqual` should be using `===`. Changing it broke none of the tests, so I made one that _would_ be broken with `==` but not with `===` when values change from `1` to `'1.'` to `1.2`, as your sandbox was doing.

**Comment by erikras** [comment]
Published fix in [`v7.1.0`](https://github.com/erikras/redux-form/releases/tag/v7.1.0).
