### ISSUE TITLE
Normalizing question

### ISSUE THREAD

**Issue by ReactGirl** [erikras/redux-form#3358]
How can I change the number that user type in the : "100.000" and sent it to the Object only as a number only "100000" but still displaying what user typed in the form?

**Comment by b0gok** [comment]
You can create two fields:

```js
<Field name="normalizeUserValue" type="hidden" />
<Field name="userValue" onChange={(event, newValue) => this.props.change('normalizeUserValue', value.replace(/[^\d.-]/g, ''))} />
```

In this case you will have normalize value and original value.

**Comment by ReactGirl** [comment]
@b0gok Sorry I might not get it. I could not have your solution work.

**Comment by b0gok** [comment]
@ReactGirl you can manage your values in onSubmit function before submitting to API here
https://github.com/ReactGirl/ReactReduxFormExample/blob/master/src/components/App.js#L31
```js
const onSubmit = (values, dispatch, props) => {
  dispatch(someAction({
    ...values,
    valueWithoutDots: valueWithDots.replace(/[^\d.-]/g, '')
  }));
};
const form = reduxForm({
  form: FORM_NAME,
  onSubmit
  validate
})(App)
```

**Comment by ReactGirl** [comment]
@b0gok Then the values will be normalized only before the submit. What I'm thinking is a way to normalize in the same time you type, not relying in a function that you only discover if was working well when you submit. This way you can add a input mask that displays what you want in the UI but the backend will receive the raw value without need to deal with for example: "$100,000,00" and only with "100000". Does it make sense?

**Comment by ReactGirl** [comment]
@b0gok I see your point, but it is not ideal. Would be much better a way to type and have it already normalized only in the values.
