### ISSUE TITLE
How to make a default active/focused field?

### ISSUE THREAD

**Issue by tokenvolt** [erikras/redux-form#336]
I'm struggling to make the field focused by default. According to the docs http://erikras.github.io/redux-form/#/api/props?_k=0xp7pg there is an active prop to be passed, but it doesn't work. I also tried dispatching focus action on mounting the form, but still no success.

````jsx
<MyForm initialValues={ { token, content, id } }
        formKey={ id.toString() }
        active="content"
        onCancel={ this._handleCancelForm } />
````

I'm using v3.0.6

**Comment by erikras** [comment]
No, the `active` prop is readonly and informational to the wrapped component. Nor does the `FOCUS` action affect the DOM.

You'll have to manipulate the DOM yourself.
```js
componentDidMount() {
  this.refs.contentInput.focus();
}
```

**Comment by tokenvolt** [comment]
@erikras thank you for quick response!
