### ISSUE TITLE
Handling actions instead of passing callback

### ISSUE THREAD

**Issue by smoliji** [erikras/redux-form#3361]
Supposing I have a form for submitting data to server, the typical usage is
 - connect to redux, bind action, e.g. `dispatchRequestCreateRecord`.
 - wrap reduxForm, pass handleSubmit a callback function, which when called, dispatches our bound action `dispatchRequestCreateRecord`.

But as it is an server request, it may fail and according to doc, I could return a Promise in the redux-form's `handleSubmit`. And I found this a bit ugly, as the flow here goes from the component out - the form submission - and then back - the resolving Promise.

I should say I am using redux-saga as a middleware for handling (async) sideeffects. And what I'd really like is to listen on a form submission and react to that accordingly (from the docs, there are exposed actions and selectors, to get the data, submit the form etc.)

If it would be possible, I would't have to bother the component with any action it should dispatch, I would be using only redux-form's `handleSubmit`, in saga, I would react to the X-form-submitted action, here I'd dispatched `dispatchRequestCreateRecord`, on success, I'd notified the form of the result (dispatch an exposed action perhaps?), otherwise dispatch fail with errors. 

Are there any redux-forms realiable (=documented) means to do that?

I know of these solutions https://github.com/redux-saga/redux-saga/issues/161#issuecomment-191312502, or this one https://github.com/mhssmnn/redux-form-saga.

**Comment by gustavohenke** [comment]
Right below on that issue, you have this solution, which I have used extensively in the past 😃 
https://github.com/redux-saga/redux-saga/issues/161#issuecomment-254939672

**Comment by smoliji** [comment]
@gustavohenke Ok, this shows the use of `startSubmit`/`stopSubmit` and that's what I am doing right now. 

But how do I know in the saga which form is being submitted? I still need to create a custom action which I'll dispatch when the redux-forms calls the optional `handleSubmit`'s callback, correct?

I'd like to react on an redux action, instead of an eventCallback function. Wouldn't that make sense to have an action for that, when there are actions for all the blur, on change, and there is none for the form submission? 🤔 An action that would basically dispatch when `handleSubmit` will call the passed callback.
