### ISSUE TITLE
initialValues not working, React Native

### ISSUE THREAD

**Issue by royrijkers** [erikras/redux-form#3363]
Hi,

When I try to use this component to edit a post the form fields are not populated.

I console logged initialValues and it gave me the right data for in the form fields.

I checked my reducers and I hooked up the formReducer properly. When I submit the form it works properly. Only the initialValues don't. Am I doing something wrong? 
```

import React, { Component } from 'react';
import { connect } from 'react-redux';
import { Field, reduxForm } from 'redux-form';
import { View, ScrollView, Image } from 'react-native';
import { ImagePicker } from 'expo';
import { FormLabel, Icon, FormInput, FormField, FormValidationMessage, Button } from 'react-native-elements';
import FullWidthImage from '../../common/FullWidthImage';
import * as actions from '../../actions';

const validate = values => {
  const errors = {};
  if (!values.title) {
    errors.title = 'Required';
  }
  if (!values.category) {
    errors.category = 'Required';
  }
  if (!values.description) {
    errors.description = 'Required';
  }
  return errors;
};

@wrapComponent
@reduxForm({
  form: 'editArt',
  validate,
  enableReinitialize: true
})
@connect((state) => {
  return { initialValues: state.art.artPiece.properties, errorMessage: state.art.error };
}, actions)
class EditArtScreen extends Component {

  componentWillMount() {
    const { id } = this.props.navigation.state.params;
    this.props.fetchArtPiece(id);
  }

  state = {
    image: null
  };

  handleOnSubmit({ title, category, description }) {
    const { navigate } = this.props.navigation;
    this.props.createArt({ title, category, description, image: this.state.image }, () => navigate('accountHome'));
  }

  renderAlert() {
    if (this.props.errorMessage) {
      return (
        <View>
        <FormValidationMessage>{this.props.errorMessage}</FormValidationMessage>
      </View>
      );
    }
  }

  pickImage = async () => {
    let result = await ImagePicker.launchImageLibraryAsync({
      allowsEditting: true,
      aspect: [4,4]
    });

    if (!result.cancelled) {
      this.setState({ image: result.uri });
    }
  }

  takePicture = async () => {
    let result = await ImagePicker.launchCameraAsync({
      allowsEditting: true,
      aspect: [4,4]
    });

    if (!result.cancelled) {
      this.setState({ image: result.uri });
    }
  }

  renderImage = () => {
    const ROOT_URL = 'http://localhost:3000';

    if (this.state.image) {
      return (
        <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
          <Image style={{ width: 200, height: 200, margin: 10 }} source={{ uri: this.state.image }} />
        </View>
      );
    } else if (this.props.initialValues.image) {
      return (
        <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
          <Image style={{ width: 200, height: 200, margin: 10 }} source={{ uri: `${ROOT_URL}/art-images/${this.props.initialValues.image}` }} />
        </View>
      );
    }
    return (
      <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
        <View style={{ width: 200, height: 200, margin: 10, backgroundColor: '#ddd' }} />
      </View>
    );
  }

  render() {
    if(!this.props.initialValues.title){
      return null
    }
    const { handleSubmit, submitting } = this.props;
    
    console.log(this.props.initialValues)
    
    return (
      <ScrollView>
        <FormLabel>
          Picture
        </FormLabel>
        {this.renderImage()}
        <View style={{ flexDirection: 'row', flex: 1, justifyContent: 'center' }}>
          <Button style={{ flex: 1 }} onPress={this.pickImage} title="Select Image" />
          <Button style={{ flex: 1 }} onPress={this.takePicture} title="Take Picture" />
        </View>
          <Field name="title" component={renderField} label="Title" />
          <Field name="category" component={renderField} label="Category" />
          <Field name="description" component={renderField} label="Description" />
          <View>
            {this.renderAlert()}
            <Button title="Submit" onPress={handleSubmit(this.handleOnSubmit.bind(this))}/>
          </View>
      </ScrollView>
    );
  }
}

function wrapComponent(ComposedComponent){
  return class extends Component {
    static navigationOptions = ({ navigation }) => ({
      title: 'Edit',
      tabBarIcon: ({ tintColor }) => <Icon name="person" size={30} color={tintColor} />,
    })
    render() {
      return (
        <ComposedComponent {...this.props} />
      )
    }
  }
}

const renderField = ({
  input,
  label,
  type,
  meta: { touched, error }
}) =>
  <View>
    <FormLabel>
      {label}
    </FormLabel>
    <View>
      <FormInput {...input} placeholder={label} />
      {touched &&
        ((error &&
          <FormValidationMessage>
            {error}
          </FormValidationMessage>) )}
    </View>
  </View>

export { EditArtScreen };

```

**Comment by royrijkers** [comment]
:)

I found a solution for this:

I wrapped instead of the component itself, the reduxForm HOC with a component that was connected to the redux store:

`import React, { Component } from 'react';
import { connect } from 'react-redux';
import { Field, reduxForm } from 'redux-form';
import { View, ScrollView, Image } from 'react-native';
import { ImagePicker } from 'expo';
import { FormLabel, Icon, FormInput, FormField, FormValidationMessage, Button } from 'react-native-elements';
import FullWidthImage from '../../common/FullWidthImage';
import * as actions from '../../actions';

const validate = values => {
  const errors = {};
  if (!values.title) {
    errors.title = 'Required';
  }
  if (!values.category) {
    errors.category = 'Required';
  }
  if (!values.description) {
    errors.description = 'Required';
  }
  return errors;
};

@connect((state) => {
  return { initialValues: state.art.artPiece.properties, errorMessage: state.art.error };
}, actions)
@wrapComponent
@reduxForm({
  form: 'editArt',
  validate,
  enableReinitialize: true
})
class EditArtScreen extends Component {

  componentWillMount() {
    const { id } = this.props.navigation.state.params;
    this.props.fetchArtPiece(id);
  }

  state = {
    image: null
  };

  handleOnSubmit({ title, category, description }) {
    const { _id } = this.props.initialValues;
    const { navigate } = this.props.navigation;
    this.props.editArt({ 
      title, category, description, 
      image: this.state.image }, 
      _id, () => navigate('singleArt', { id: _id })
    );
  }

  renderAlert() {
    if (this.props.errorMessage) {
      return (
        <View>
        <FormValidationMessage>{this.props.errorMessage}</FormValidationMessage>
      </View>
      );
    }
  }

  pickImage = async () => {
    let result = await ImagePicker.launchImageLibraryAsync({
      allowsEditting: true,
      aspect: [4,4]
    });

    if (!result.cancelled) {
      this.setState({ image: result.uri });
    }
  }

  takePicture = async () => {
    let result = await ImagePicker.launchCameraAsync({
      allowsEditting: true,
      aspect: [4,4]
    });

    if (!result.cancelled) {
      this.setState({ image: result.uri });
    }
  }

  renderImage = () => {
    const ROOT_URL = 'http://localhost:3000';

    if (this.state.image) {
      return (
        <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
          <Image style={{ width: 200, height: 200, margin: 10 }} source={{ uri: this.state.image }} />
        </View>
      );
    } else if (this.props.initialValues.image) {
      return (
        <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
          <Image style={{ width: 200, height: 200, margin: 10 }} source={{ uri: `${ROOT_URL}/art-images/${this.props.initialValues.image}` }} />
        </View>
      );
    }
    return (
      <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
        <View style={{ width: 200, height: 200, margin: 10, backgroundColor: '#ddd' }} />
      </View>
    );
  }

  render() {
    if(!this.props.initialValues.title){
      return null
    }
    const { handleSubmit, submitting } = this.props;

    console.log(this.props.initialValues)

    return (
      <ScrollView>
        <FormLabel>
          Picture
        </FormLabel>
        {this.renderImage()}
        <View style={{ flexDirection: 'row', flex: 1, justifyContent: 'center' }}>
          <Button style={{ flex: 1 }} onPress={this.pickImage} title="Select Image" />
          <Button style={{ flex: 1 }} onPress={this.takePicture} title="Take Picture" />
        </View>
          <Field name="title" component={renderField} label="Title" />
          <Field name="category" component={renderField} label="Category" />
          <Field name="description" component={renderField} label="Description" />
          <View>
            {this.renderAlert()}
            <Button title="Submit" onPress={handleSubmit(this.handleOnSubmit.bind(this))}/>
          </View>
      </ScrollView>
    );
  }
}

function wrapComponent(ComposedComponent){
  return class extends Component {
    static navigationOptions = ({ navigation }) => ({
      title: 'Edit',
      tabBarIcon: ({ tintColor }) => <Icon name="person" size={30} color={tintColor} />,
    })
    render() {
      return (
        <ComposedComponent {...this.props} />
      )
    }
  }
}

const renderField = ({
  input,
  label,
  type,
  meta: { touched, error }
}) =>
  <View>
    <FormLabel>
      {label}
    </FormLabel>
    <View>
      <FormInput {...input} placeholder={label} />
      {touched &&
        ((error &&
          <FormValidationMessage>
            {error}
          </FormValidationMessage>) )}
    </View>
  </View>

export { EditArtScreen };
`

**Comment by gustavohenke** [comment]
Closing as the OP found the solution itself 😄
