### ISSUE TITLE
Reset button triggers onSubmit handler function.

### ISSUE THREAD

**Issue by maotora** [erikras/redux-form#3368]
Hi,

When I click `reset` button on my form it, does reset the form but then it triggers the onSubmit action which is something I expect my `submit` button to do.

Here is my form component.

```jsx
let AddPropertyForm = props => {
    const {handleSubmit, reset} = props

    return (
        <Row style={styles.container}>
            <Row>
                <form onSubmit={handleSubmit} className="form-group">
                    <label htmlFor="name">Property Name</label>
                    <Field
                        name="name"
                        placeholder="Property Name"
                        component="input"
                        type="text"
                        className="form-control"
                    />

                    <label htmlFor="location">Property Location</label>
                    <Field
                        name="location"
                        placeholder="Property Location"
                        component="input"
                        type="text"
                        className="form-control"
                    />

                    <Row style={{marginTop: 10}}>
						<Col md={6}>
							<View width="100%" horizontalAlignment="center">
								<button className="btn btn-primary" type="submit">
									Submit
								</button>
							</View>
						</Col>
						<Col md={6}>
							<View width="100%" horizontalAlignment="center">
								<button className="btn btn-danger" onClick={reset}>
									Reset
								</button>
							</View>
						</Col>
                    </Row>
                </form>
            </Row>
        </Row>
    )
}
```

When I click submit it submits, but reset clears everything up then triggers a `onSubmit` handler.

**However** I've come to notice when I make an `onReset={reset}` handler then give reset button `type="reset"` and not an `onClick` handle it works!

**Like this**

```jsx
let AddPropertyForm = props => {
    const {handleSubmit, reset} = props

    return (
        <Row style={styles.container}>
            <Row>
                <form onReset={reset} onSubmit={handleSubmit} className="form-group">
                    <label htmlFor="name">Property Name</label>
                    <Field
                        name="name"
                        placeholder="Property Name"
                        component="input"
                        type="text"
                        className="form-control"
                    />
                    <Row style={{marginTop: 10}}>
						<Col md={6}>
							<View width="100%" horizontalAlignment="center">
								<button className="btn btn-primary" type="submit">
									Submit
								</button>
							</View>
						</Col>
						<Col md={6}>
							<View width="100%" horizontalAlignment="center">
								<button className="btn btn-danger" type="reset">
									Reset
								</button>
							</View>
						</Col>
                    </Row>
                </form>
            </Row>
        </Row>
    )
}
```
I'm on redux-form 7.0.3 and wonders if this is a common behaviour or I'm just doing something wrong?

Thanks.

**Comment by timhwang21** [comment]
change button type to "button" as I believe it defaults to "submit"?

**Comment by maotora** [comment]
@timhwang21 hehe that worked!

Thanks.

**Comment by erikras** [comment]
@maotora This burned me _so many_ times when I first started React form programming.

**Comment by timhwang21** [comment]
Burned me and several coworkers as well, even though it's not strictly a redux form issue, might it be worth including in the docs? If I remember correctly (and I may be entirely wrong) this behavior only occurs when the button is within a `<form/>`, and it doesn't seem to be common knowledge at all.

**Comment by gustavohenke** [comment]
@timhwang21 you're right, this only happens within a `form` tag, and it's a W3C spec actually.

It could happen if you used jQuery, it could happen if you used Angular, whatever.
I think people/tutorials/courses that teach HTML should emphasize on this *very* common problem.

**Comment by maotora** [comment]
While I do agree with @gustavohenke but this should be included in the docs/examples at least the `<button type="button" onClick={reset}>` line.

**Comment by timhwang21** [comment]
I've filed #3420, in case the maintainers think it's worth documenting. Personally, I can say that this exact issue has wasted enough hours of me + my coworkers time that it would be valuable to have 😄
