### ISSUE TITLE
Struggling with <input type="radio" /> and booleans.

### ISSUE THREAD

**Issue by antoinerey** [erikras/redux-form#337]
Hey 

I'm struggling with an `<input type="radio" />` where values are booleans.

My code looks like this : 

```jsx
<form onSubmit={ handleSubmit((data) => { console.log(data); }) }>

  { ... }

  <input type="radio" name="isPrivate" value={ true } />
  <input type="radio" name="isPrivate" value={ false } />

  { ... }

  <input type="submit" />
</form>
```

And I'm unable to fetch `isPrivate` as a boolean. It's always a string `"true"`. I could use `"true"` and `"false"` instead of booleans, but I find this messy. Is there any solution I missed ? :)

**Comment by erikras** [comment]
The fact that they are strings is due to how React generates the `SyntheticEvent`, so I don't think there's a great way around that. You are, however, setting `checked` incorrectly. See [Simple Example](https://erikras.github.io/redux-form/#/examples/simple).
```js
<input type="radio" {...sex} value="male" checked={sex.value === 'male'}/> 
```

**Comment by antoinerey** [comment]
Oops ! Yeah, I wanted to simplify my code, but I forgot the `checked` part. 

Thank you for your answer. I'll keep it like that for now.
