### ISSUE TITLE
Form data disappears on going back when using React Navigation with React Native

### ISSUE THREAD

**Issue by nikhilag** [erikras/redux-form#3372]
In my react native app, I have two form screens connected with the same redux form. When I go back from screen 2 to screen 1 (using react navigation), all redux data is still there except for the form data. `state.form` becomes an empty object for me in `mapStateToProps` for screen 1 component on coming back from screen 2. 

I thought it was a navigation issue but on changing the library to react-native-navigation, I am seeing the same issue again. So clearly there's some issue with redux-form here. Please let me know what to do.

Please see the following similar question:-
https://stackoverflow.com/questions/45939493/react-navigation-goback-issue

**Comment by gustavohenke** [comment]
Try setting option [`destroyOnUnmount` to `true`](http://redux-form.com/7.0.3/docs/api/ReduxForm.md/#-code-destroyonunmount-boolean-code-optional-).

**Comment by nikhilag** [comment]
I believe you meant setting it to `false` and that worked for me. Thanks a lot @gustavohenke !

**Comment by gustavohenke** [comment]
That's right!

![homer-doh](https://user-images.githubusercontent.com/826553/29996573-94564a0c-8fd7-11e7-8cfb-7b23f1ecfc8e.png)
