### ISSUE TITLE
Field would return undefined instead of error after first submit.

### ISSUE THREAD

**Issue by willshu2049** [erikras/redux-form#3379]
### Are you submitting a **bug report** or a **feature request**?
Bug report

### What is the current behavior?
I put the redux form inside a modal. After opening the modal, if I submitted right away, the field would return error. However, after I completed the form and submitted the first form, and re-opened the modal, the field would alway return 'undefined' instead of error, even if I had not typed in anything in the input box. Therefore the error message will not show up.

### What is the expected behavior?
The field will return errors as long as the input field is empty.

### What's your environment?

OS X.

**Comment by erikras** [comment]
My default, your form data will be destroyed in the Redux store when your form is unmounted. You can disable this by passing [`destroyOnUnmount: true`](http://redux-form.com/7.0.4/docs/api/ReduxForm.md/#-code-destroyonunmount-boolean-code-optional-).

**Comment by willshu2049** [comment]
@erikras You mean destroyOnUnmount: false? Yes it works! Thank you.
