### ISSUE TITLE
action on checkbox check

### ISSUE THREAD

**Issue by jonathanasquier** [erikras/redux-form#338]
Hi,
I'm doing a list filtering form.
Right now I filter my list on the go while typing in a field and calling `onKeyUp={ handleSubmit(action) }` (if it's meant to be done this way) but I can't manage to do the same on checkbox checked (without clicking any submit button). I believe I overwrite the form reducer to make API calls in a thunk but It seems a bit overkill.
Am I missing something ?

Thanks a lot for the great work :)

**Comment by erikras** [comment]
You'll have to let the `onChange` go through to Redux, and then call submit.
```js
<input
  type="checkbox"
  {...onlyGoodOnes} // field name
  onChange={event => { // placed after destructured field to override onChange
    onlyGoodOnes.onChange(event); // send value to Redux
    setTimeout(handleSubmit(action)); // submit on next process tick
  }}/>
```

**Comment by jonathanasquier** [comment]
Ha "placed after destructured field to override onChange" of course!
I did it this way otherwise I was 1 dispatch late:

```
onlyGoodOnes.onChange(e);
action({onlyGoodOnes : e.target.checked}, dispatch);
```
Thanks!
