### ISSUE TITLE
5.3.2 Event data is object with multiple entries and has a key "value"

### ISSUE THREAD

**Issue by danikkks** [erikras/redux-form#3381]
### Are you submitting a **bug report** or a **feature request**?

It`s a **bug report**

### What is the current behavior?

Widget return data to onChange funciton in format:

```
{
  includeUnknown: false,
  value: 123,
}
```

but getValue function in redux-form return only 123

### What is the expected behavior?

when value has more than 1 key return all object

### What's your environment?

"redux-form": "^5.3.2"

### Other information

https://www.evernote.com/l/AeJriOylJrhPF4K7a2wiolhL0jMAKbbkq3Y
https://www.evernote.com/l/AeJuYqM43DBJC5TDkpIQYVySr_0PTMcN1PE

**Comment by gustavohenke** [comment]
Will close as the PR that fixed it was merged
