### ISSUE TITLE
Field component provided as inline function re-renders on form change

### ISSUE THREAD

**Issue by hubgit** [erikras/redux-form#3388]
### Are you submitting a **bug report** or a **feature request**?

bug

### What is the current behavior?

When a Field's component is provided as a inline function, it re-renders and loses focus whenever a form prop changes.

    <Field name="foo" component={props => <input {...props.input}/>}/>
    
If the component is defined separately, it doesn't re-render.

    const MyInput = props => <input {...props.input}/>

    <Field name="bar" component={MyInput}/>

### What is the expected behavior?

A component declared as an inline function should behave the same as a component defined separately: it shouldn't re-render when a form prop changes.

### Sandbox Link

https://codepen.io/invisiblecomma/pen/wqLaZQ

### What's your environment?

redux-form 7.0.3, Chrome 60

**Comment by hubgit** [comment]
This may be similar to https://github.com/erikras/redux-form/issues/2412#issuecomment-322431972 where validators provided as inline functions cause fields to be unregistered + re-rendered.

**Comment by noahjohn9259** [comment]
I am experiencing this behavior also. Though this only occurs on production build.

**Comment by gustavohenke** [comment]
@noahjohn9259 @hubgit 
Please read this post from redux-form own's @erikras:
https://medium.com/netscape/react-performance-anti-pattern-creating-functions-in-render-ddeb5ebd2933

This is a classic error of redux-form users.
AFAIC, there's nothing we can do about it at the moment.

<sub>* ☝️ Contribution opportunity: write a FAQ about it</sub>

**Comment by hubgit** [comment]
Thanks @gustavohenke - I'd just realised that the difference was whether the inputs were created inside the render function or outside, rather than whether they were inline or not, which makes much more sense.

**Comment by hubgit** [comment]
For reference, a link to the relevant documentation:
https://redux-form.com/7.0.4/docs/api/field.md/#2-a-stateless-function

**Comment by valorize** [comment]
I had to save the return values of my renderField function. I guess there is no more elegant solution right?

```
const cache = {};
const renderField = (WrappedComponent) => {
    if(cache[WrappedComponent]) { return cache[WrappedComponent]; }

    const EnhancedInputField = ({
         input, label, type, meta: { touched, error, warning }
    }) => (
        <div>
            <WrappedComponent {...input} placeholder={label} type={type} />
        </div>
    );

    cache[WrappedComponent] = EnhancedInputField;
    return EnhancedInputField;
};

const TextInput = (props) => {
    const {
        name,
        component = 'input',
    } = props;

    return (
            <Field
                name={name}
                component={renderField(component)}
            />
    )
};

export default TextInput
export const TextArea = (props) => <TextInput {...props} component="textarea"/>;
```
