### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by iliesalex89** [erikras/redux-form#3395]
I'm trying to dispatch a field array change and the new value is an immutable List with over 50 items(each item is a Map with 4 or 5 keys) or more, depends from case to case. The problem is that calling this action creator takes more than 11 seconds and if we are trying to change the field array value with a list that is let's say over 100 items, the browser will crash. 

Can you help me please with any advice or fresh idea, cause I really don't have a workaround at this moment?

One more thing....if I'm trying arrayPush to put values one by one, the things are even worse.

**Comment by gustavohenke** [comment]
I'm sorry that we didn't got back to you! 😰 
Some tweaking could definitely make it better -- in which case StackOverflow might be better. From your words, it could be unrelated to redux-form issue.

If you can come up with more details on the culprit and open a new issue, I'll be happy to look at it again.
