### ISSUE TITLE
registeredFields is missing from the instance api

### ISSUE THREAD

**Issue by mmerickel** [erikras/redux-form#3396]
### Are you submitting a **bug report** or a **feature request**?

Bug

### What is the current behavior?

```js
@reduxForm
class Form extends Component {
  render() {}
}

class Foo extends Component {
  handleSubmit = () => {
    console.log(this.form.registeredFields); // undefined
  }

  render() {
    return (
        <Form form="foo" ref={c => this.form = c} onSubmit={this.handleSubmit} />
    );
  }
}
```

### What is the expected behavior?

`this.form.registeredFields` should return the list of field objects with type/name properties as described in the `reduxForm` documentation.

Currently `this.form.fieldList` is exposed as an array of names, but this does not line up with the documentation.

### What's your environment?

redux-form 7.0.4

**Comment by gustavohenke** [comment]
Thanks for the heads up. See #3398.

**Comment by mmerickel** [comment]
Sounds good to me. `fieldList` satisfies my requirements. Thanks!

**Comment by janzenz** [comment]
@gustavohenke I'm using `registeredFields` via props. Is `fieldList` going to be the new name? If so, how come I couldn't see it on the redux store? In fact, in your [SimpleForm](https://redux-form.com/7.1.2/examples/simple/) example it's not listed there either, instead it still uses `registeredFields`:

![screen shot 2017-11-23 at 9 39 44 am](https://user-images.githubusercontent.com/1410147/33149027-f68938a6-d032-11e7-9361-8f8720312e90.png)

@mmerickel I'm not familiar with `@reduxForm` is that a pseudocode for referring to a decorated component?

**Comment by gustavohenke** [comment]
- `reduxForm` is usually the main decorator function of the library. [Docs](https://redux-form.com/7.1.2/docs/api/reduxform.md/)
- `fieldList` is the name of [a property made available in the instance](https://redux-form.com/7.1.2/docs/api/reduxform.md/#-code-fieldlist-array-code-) of a `reduxForm` decorated component.
- `registeredFields` is simply the key used internally by the Redux Form reducer. Don't mess with it as it's not documented.

**Comment by janzenz** [comment]
Thanks @gustavohenke yeah I know about `reduxForm` being the decorator. I was just curious about the code snippet and the usage of `@reduxForm` by @mmerickel in the issue.
