### ISSUE TITLE
Issue with FAQ documentation - How can I clear my form after my submission succeeds?

### ISSUE THREAD

**Issue by breakpoint25** [erikras/redux-form#3397]
This is a documentation error in the FAQ

http://redux-form.com/6.0.0-alpha.4/docs/faq/HowToClear.md/

It says an option to reset form is to use this.props.resetForm()

It appears the prop is now renamed to this.props.reset()

**Comment by gustavohenke** [comment]
It's always a good idea to check up-to-date versions of the docs :)
You were looking at `v6.0.0-alpha.4` docs.

**Comment by breakpoint25** [comment]
sorry my mistake, I followed the first link from google and didn't realize the docs were versioned

**Comment by gustavohenke** [comment]
I understand, no worries. This is quite common.

**Comment by erikras** [comment]
This issue prompted me to implement something I've been meaning to do for a while.

![redux form - api 2017-09-11 17-43-26](https://user-images.githubusercontent.com/4396759/30283568-bfc28708-9718-11e7-9b9d-8a886ce3eac9.jpg)

It works on all the doc versions _except_ `6.0.0-alpha.4`, which is what this ticket is about. _sigh..._

**Comment by gustavohenke** [comment]
@erikras that's amazing! We have another ticket for this: #3166. And the case is for the *same problematic version*...
