### ISSUE TITLE
Indicate you had filled in all the required fields

### ISSUE THREAD

**Issue by Olivr3** [erikras/redux-form#3401]
### Are you submitting a **bug report** or a **feature request**?

feature request

### What is the current behavior?

There is no indication after the user has filled the required field that the value is valid. 

### What is the expected behavior?

it would be nice if the tick changed colour or animated in some way to indicate you had filled in all the required fields and could complete this section

![lee_img](https://user-images.githubusercontent.com/20702895/30271975-3e1a61cc-96ea-11e7-9147-9ea264d40de0.png)

### What's your environment?

React-Redux project

**Comment by gustavohenke** [comment]
Use the [`valid` prop](http://redux-form.com/7.0.3/docs/api/Props.md/#-code-valid-boolean-code-) given to your wrapped form component.
