### ISSUE TITLE
Doc is not loading, rollbar sponsoring ?

### ISSUE THREAD

**Issue by nihaux** [erikras/redux-form#3402]
The doc does not load anymore.
I have nothing against sponsoring or ads but as it is, it seems to prevent correct use of the doc.
![capture d ecran 2017-09-11 a 14 10 15](https://user-images.githubusercontent.com/3429327/30273881-2c4ac99e-96fb-11e7-82d6-08805c50d811.png)

**Comment by werg27** [comment]
Documentation appears and then disappears quickly :/

**Comment by erikras** [comment]
I'm working on this. Thanks.

**Comment by nihaux** [comment]
@erikras you're welcome, and thx for this awesome lib 👍

**Comment by banciur** [comment]
Just disable javascript in your browser then its working fine :D

**Comment by erikras** [comment]
Fixed now.
