### ISSUE TITLE
The field is unregistered when sync error triggered

### ISSUE THREAD

**Issue by m1m6** [erikras/redux-form#3405]
Hi , 
I have a change password form, in the following structure 
```jsx
    <Field name={FORM_FIELDS.OLD_PASSWORD}
           component={FInputField}
           type="password"
           validate={[Validation.required]}
    />
    <Field name={FORM_FIELDS.NEW_PASSWORD}
           component={FInputField}
           type="password"
           validate={[Validation.required]}
    />
    <Field name={FORM_FIELDS.CONFIRM_PASSWORD}
           component={FInputField}
           type="password"
           validate={[ Validation.shouldMatch(password)]}
    />
```

```jsx
export const shouldMatch = (matchValue) => {
  return (value) => {
    return value !== matchValue ? t('common/validationNotMatch') : undefined
  }
};
```

When i input a mismatch in the CONFIRM_PASSWORD field, i got the following actions which is right

```jsx
{
  type: '@@redux-form/UPDATE_SYNC_ERRORS',
  meta: {
    form: 'changePassword'
  },
  payload: {
    syncErrors: {
      confirmPassword: 'common/validationNotMatch'
    }
  }
}
```

but after this action, an UNREGISTER_FIELD action occur, which make the form to clear the sync error object

```jsx
{
  type: '@@redux-form/UNREGISTER_FIELD',
  meta: {
    form: 'changePassword'
  },
  payload: {
    name: 'confirmPassword',
    destroyOnUnmount: true
  }
}
```

then the field is registered again
```jsx
{
  type: '@@redux-form/REGISTER_FIELD',
  meta: {
    form: 'changePassword'
  },
  payload: {
    name: 'confirmPassword',
    type: 'Field'
  }
}
```

any help, why the UNREGISTER_FIELD action occur here? and how could i make the validation message appear always when there's a mismatch.

**Comment by m1m6** [comment]
@erikras

**Comment by stefan-dimitrov** [comment]
Having the same issue here.
I have a reducer plugin that clears the values of unregistered fields, and this is now causing a bug, forcing me to write a workaround for my logic.

**Comment by piotr-oles** [comment]
The same issue in my project :/

**Comment by basia-scibior-c** [comment]
The same issue in my friends project :/

**Comment by erikras** [comment]
Here's your problem.
```jsx
<Field name={FORM_FIELDS.CONFIRM_PASSWORD}
  component={FInputField}
  type="password"
  validate={[ Validation.shouldMatch(password) ]}
  //          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^---- PROBLEM
/>
```

This is generating a new function on every render, which means that the Field has to re-register this new set of validation functions with the form. You're going to need to save the results of `Validation.shouldMatch(password)` into a member variable or something, so that you are not creating a new function on every render.

Here's an example of the right and wrong way side by side:

[![Edit Redux Form - Field-Level Validation](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/64j6r605ok)

**Comment by stefan-dimitrov** [comment]
Thank you @erikras for the solution and explanation. :+1:

**Comment by williamdclt** [comment]
@erikras it does make sense that the field is unregistered then reregistered, but I don't understand why the validation is not ran again when the field is reregistered?
