### ISSUE TITLE
How can I turn off/on any validation at runtime?

### ISSUE THREAD

**Issue by corsa15** [erikras/redux-form#341]
I'm new in redux-form. I want to use the same form for insert/update and query. I need for validations (sync, async) in insert/update mode, but I don't need in query mode.  
Can I turn off or on the validations at runtime?

**Comment by erikras** [comment]
Yes. From [the docs](http://erikras.github.io/redux-form/#/api/reduxForm):

> IMPORTANT: All of these configuration options may be passed into reduxForm() at "design time" or passed in as props to your component at runtime.

In other words, you can pass in sync or async validation functions as props at runtime.
