### ISSUE TITLE
Incorrect flow types on action creators

### ISSUE THREAD

**Issue by jackmellis** [erikras/redux-form#3412]
### What is the current behavior?

It looks like the flow types for redux-form's action creators are the actual action signatures instead of the creators, meaning if I dispatch an action flow thinks I'm trying to call on a plan object.

Example error message:
```
  Error:
   41:         reset(form),
               ^^^^^^^^^^^ function call. Callable signature not found in
  165: export type ResetAction = { type: string, meta: { form: string } } & Action
                                                                            ^^^^^^ object type. See: node_modules/redux-form/lib/actions.types.js.flow:165
```
This appears to be the case on every actionCreator I have used (reset, stopSubmit, change) but I'm sure it reaches further than this.

### What is the expected behavior?
The action creators should be associated with function types that return the action type. i.e.
```js
export type ResetActionCreator = (form: string) => ResetAction;
```

### What's your environment?

redux-form: 7.0.3

**Comment by gustavohenke** [comment]
Can you please try v7.0.4? It has some updates for Flow.
I still don't fully grasp it, so I can't tell if it's going to fix your issue  😕

**Comment by gustavohenke** [comment]
Closing due to no response
