### ISSUE TITLE
`change` function documentation is incorrect. Missing a parameter

### ISSUE THREAD

**Issue by wwlacy6** [erikras/redux-form#3416]
The documentation [here](http://redux-form.com/7.0.4/docs/api/props.md/#-code-change-field-string-value-any-function-code-) specifies that the `change` function has 2 parameters, field and value. However, this function actually requires 3 parameters. Form, field, and value. If someone could update the documentation, I'm sure it would be helpful for others using the change function for the first time.

**Comment by timhwang21** [comment]
It's confusing, but you're confusing `props.change` with the [`change()` action creator](https://redux-form.com/7.0.4/docs/api/actioncreators.md/#-code-change-form-string-field-string-value-any-code-). The prop function can be thought of as the action creator with form partially applied.

**Comment by gustavohenke** [comment]
Precisely what @timhwang21 said.
