### ISSUE TITLE
Handling the meta for a Component which has input + button

### ISSUE THREAD

**Issue by bharadwajsampath** [erikras/redux-form#3417]
We are having a Password component which has an Input and a toggle button which shows/hides password on click and also a validation Img which would trigger on blur.

At the moment when we click on the toggle button , we lose the focus on the input which would dispatch a field level validation and shows the Validation Image rather than toggling the show/hide.

Request is to have a meta for the entire Field component rather than having it only for the input inside the Field.

![password](https://user-images.githubusercontent.com/13538284/30463328-59727fb4-9a0e-11e7-8685-a21f051618ae.gif)

**Comment by hubgit** [comment]
It should be possible to prevent the input from losing focus when the button is clicked - perhaps with a `mousedown` event handler on the button instead of a `click` handler?

**Comment by danielrob** [comment]
> meta for the entire Field

see #1748 / #1855 / #3289

**Comment by bharadwajsampath** [comment]
Thanks @danielrob and @hubgit 

@hubgit  This problem is for react native so I cant do a mousedown.

I solved this issue by having keyboardShouldPersisTaps={'handled'}, which was allowing the childrens onClick to pass through not calling the blur method on tap of the show/hide toggle button on side of the keyboard.
