### ISSUE TITLE
Npm install of redux form not working

### ISSUE THREAD

**Issue by Debanjan05** [erikras/redux-form#3423]
I am trying to install redux-form & redux-form-material-ui using npm install, but its showing you need to install peer dependencies first, which I am doing but these modules are still not available under node modules folder.

I am running 'npm install' in git bash as an administrator but its showing run as a root/administrator. However its running when I am using 'npm install -g', I am not getting the reason for this odd behavior.
However still after using -g those modules are not getting installed - Error of module not found is coming.

### What's your environment?
Node version - 8.0.0 ( Even tried with v6)
npm - 5.4.0
Redux form -latest
OS- Windows 10

**Logs**-

$ npm install redux-form
npm ERR! path D:\ABC\template\node_modules\fsevents\node_modules\aproba\package.json
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'D:\ABC\template\node_modules\fsevents\node_modules\aproba\package.json'
npm ERR!  { Error: EPERM: operation not permitted, unlink 'D:\ABC\template\node_modules\fsevents\node_modules\aproba\package.json'
npm ERR!   stack: 'Error: EPERM: operation not permitted, unlink \'D:\\ABC\\template\\node_modules\\fsevents\\node_modules\\aproba\\package.json\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: 'D:\\ABC\\template\\node_modules\\fsevents\\node_modules\\aproba\\package.json' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dbhowmick.ABC\AppData\Roaming\npm-cache\_logs\2017-09-18T13_03_31_862Z-debug.log

For only npm install same error is coming, even if I am running as administrator.
-------------------------------------------------------------------------------------------------------------------

$ npm install -g redux-form
npm WARN redux-form@7.0.4 requires a peer of react@^15.0.0-0 || ^16.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN redux-form@7.0.4 requires a peer of react-redux@^4.3.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN redux-form@7.0.4 requires a peer of redux@^3.0.0 but none is installed. You must install peer dependencies yourself.

+ redux-form@7.0.4
added 24 packages in 14.599s

Its showing added but no folder created under node modules, & redux form module not found is coming.
-------------------------------------------------------------------------------------------------------------------
For installing redux-form-material-ui same  error is coming

$ npm install -g redux-form-material-ui
npm WARN redux-form-material-ui@4.2.0 requires a peer of react@15 but none is installed. You must install peer dependencies yourself.
npm WARN redux-form-material-ui@4.2.0 requires a peer of redux-form@6 but none is installed. You must install peer dependencies yourself.

+ redux-form-material-ui@4.2.0
added 1 package in 1.509s

**Comment by gustavohenke** [comment]
`npm install -g` is not the same as running as administrator.

When you use `npm install -g`, you are installing the packages globally (what may require admin permissions in Unix systems), therefore the directory used to install the packages is no longer located within your project. This means redux-form and redux-form-material-ui won't be accessible within your project code.

The first log you sampled has this error:

> npm ERR! Error: EPERM: operation not permitted, unlink 'D:\ABC\template\node_modules\fsevents\node_modules\aproba\package.json'

From my own Windows experience, this line tells me *some* process is using this file, therefore npm is not able to remove it.
You should work out the situation of your `node_modules` directory, *perhaps* remove it altogether then reinstall everything from scratch.

In the 2nd and 3rd logs you pasted, the installation worked, in both cases. No other process seems to be using any files there.
However, because you are installing those packages globally, **npm is warning you, not throwing an error**, saying that those peer dependencies are not available in the global context.

**Comment by Debanjan05** [comment]
But when I am doing a just 'npm install' after opening git bash as administrator. This error is still showing, I have closed all processes that are using package.json. Even deleted node_modules folder.

$ npm install
npm WARN deprecated babel-preset-latest@6.16.0: 💥  preset-latest accomplishes the same task as babel-preset-env. 🙏  Please install it with 'npm install babel-preset-env --save-dev'. '{ "presets": ["latest"] }' to '{ "presets": ["env"] }'. For more info, please check the docs: http://babeljs.io/docs/plugins/preset-env 👌. And let us know how you're liking Babel at @babeljs on 🐦
npm WARN deprecated babel-preset-es2016@6.24.1: We're really excited that you're trying to use ES2016 syntax, but instead of making more yearly presets, Babel has a better preset that we recommend you use instead: npm install babel-preset-env --save-dev. Give us a follow @babeljs to get more updates
npm WARN deprecated babel-preset-es2017@6.24.1: We're really excited that you're trying to use ES2017 syntax, but instead of making more yearly presets, Babel has a better preset that we recommend you use instead: npm install babel-preset-env --save-dev. Give us a follow @babeljs to get more updates
npm ERR! path D:\ABC\template\node_modules\nan\package.json
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'D:\ABC\template\node_modules\nan\package.json'
npm ERR!  { Error: EPERM: operation not permitted, unlink 'D:\ABC\template\node_modules\nan\package.json'
npm ERR!   stack: 'Error: EPERM: operation not permitted, unlink \'D:\\ABC\\template\\node_modules\\nan\\package.json\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: 'D:\\ABC\\template\\node_modules\\nan\\package.json' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

**Comment by Debanjan05** [comment]
Even I have created a new directory checked out the code there & tried doing a npm install after deleting the node modules, still nothing helped the cause.

**Comment by gustavohenke** [comment]
Can you try following this thread, please?
https://github.com/npm/npm/issues/18380

I didn't read the whole thread, but it seems like it's a common problem with npm v5.4.0 running on Windows machines.
