### ISSUE TITLE
Changing the field value synchronously

### ISSUE THREAD

**Issue by sushant23** [erikras/redux-form#3428]
I want to change the field value of form synchronously. But [change](https://redux-form.com/7.0.4/docs/api/props.md/#-code-change-field-string-value-any-function-code-) is changing it asynchronously is there any to do so?

**Comment by gabrielmicko** [comment]
I don't think there is an option for that, why would you do that?

**Comment by sushant23** [comment]
My particular use case is I have to change step of wizard form on changing the field value

**Comment by gabrielmicko** [comment]
I think it doesn't mean that it has to be async. The update can happen super-fast and you can use the data for your wizard.

**Comment by gustavohenke** [comment]
Yes, @gabrielmicko is right. There's no way around it, as calls to `setState` are async, and this is what react-redux uses under the hood.

In the future, please open questions like this on StackOverflow first.

**Comment by sushant23** [comment]
@gabrielmicko you mean I should be listening for data change in parent component and when data changes I should be changing the step? like listening for changed props in `componentWillReceiveprops` method?
