### ISSUE TITLE
Form doesn't reinitialize when replaced

### ISSUE THREAD

**Issue by eliseumds** [erikras/redux-form#3435]
### Are you submitting a **bug report** or a **feature request**?

Bug report. I'm seeing React lifecycle methods being called in a different order with React 16 which breaks the forms (leaving them destroyed). 

### Expected order

* componentWillUnmount
* componentWillMount
* componentDidMount

### Actual order

* componentWillMount
* componentWillUnmount
* componentDidMount

It looks like it's an [expected behaviour](https://twitter.com/dan_abramov/status/843822280132190208) but it leads to issues because the forms don't reinitialize.

**Comment by kjanoudi** [comment]
This also is the case after a form submission using a pure component with `initialValues`. After the form is submitted, and the new data is passed to the wrapper component via props, the redux form will `DESTROY` after registering all the new fields. In react 15, it would `DESTROY`, `INITIALIZE`, then register all the fields.

### React 15

![](https://files.slack.com/files-pri/T04CXPZ4L-F7A6RBRJ8/pasted_image_at_2017_09_28_04_41_am.png)


### React 16

![](https://files.slack.com/files-pri/T04CXPZ4L-F79FDE6PJ/pasted_image_at_2017_09_28_04_40_am.png)

**Comment by eliseumds** [comment]
@kjanoudi same thing here :( It's good to know that someone else is having the same problems. This was such a massive change from React that breaks so much stuff and not only with *redux-form*:

**Comment by blord-fullscreen** [comment]
React 16 compatilbility is crucial. Would love to see this made a high priority.

**Comment by kjanoudi** [comment]
Shocked this isn't getting more attention. Guess I'll be waiting to upgrade to React 16

**Comment by erikras** [comment]
Is it obvious to anyone how to solve this? It isn't to me.

`redux-form` doesn't behave all that well under dev hot reloading in my experience. I usually turn `destroyOnUnmount: false` for the duration of the development of my form. Does that make any difference here?

**Comment by kjanoudi** [comment]
@erikras I'm less concerned with the behavior or hot reloading as opposed to in production. I'm experiencing the scenario I outlined above on a production build of my app. After saving the form and remaining on the same screen, previously the form would not clear. Presently, it clears.

**Comment by eliseumds** [comment]
@erikras sorry for the confusion. I edited the title and description. It happens every time the form instance gets replaced.

**Comment by eliseumds** [comment]
And it's also not clear to me how to solve this. Maybe by initializing the form on didMount as well? If only React passed a parameter to `componentWillMount` telling us if it's bring replaced by another component (including its props).

**Comment by tyscorp** [comment]
Can we move the initialization logic from `componentWillMount` to `componentDidMount`? That would require rendering twice, though. (once again after the mount) I'm not sure what other side effects this would have.

**Comment by janpe** [comment]
Any progress on this? This issue prevents me from upgrading to React 16 and forces me to still use Redux-form 6.6.3.

**Comment by bstro** [comment]
This is a bit of a dealbreaker on my project. Any word on when/if this will be fixed?

**Comment by bstro** [comment]
Should there be an announcement on the README.md that lets people know this library doesn't quite work with React 16? I got really far down the Redux-Form rabbithole and now have to redo my form architecture.

**Comment by janpe** [comment]
Isn't this fixed in 7.1.2? Seems like the problem I was having doesn't occur anymore.

**Comment by bstro** [comment]
@janpe I missed that release!!! It does solve this problem for me. Thanks for the heads up!

**Comment by gustavohenke** [comment]
Nice!! @eliseumds can you also confirm v7.1.2 fixes it for you?

**Comment by eliseumds** [comment]
@gustavohenke unfortunately it doesn't :S On hot reload, forms still end up destroyed.

**Comment by stevenmusumeche** [comment]
This is not fixed in 7.1.2 and was a nasty surprise for me. DESTROY is being called after INITIALIZE of the new form.

**Comment by brucewpaul** [comment]
is there any progress on addressing these issues @erikras ?

**Comment by brucewpaul** [comment]
it seems like moving the logic into `componentWillMount` might work, but there are def perf implications of that. By doing that, II'm seeing:

initialize
register_field
destroy
initialize
register_field

React ensuring the order of events really screws with the logic in redux-form. Is there a way to only destroy the form if not being replaced?

**Comment by tyscorp** [comment]
Just a quick thought: I wonder if in the meantime until this is fixed, a user-land fix would be to use React's key prop to force (or not) mounting and unmounting? Does the same lifecycle order persist? I haven't tested anything, it's just an idea.

**Comment by brucewpaul** [comment]
While this is still being figured out on the redux-form side, we have a solution that we think solves this. Basically we created a HOC that is meant to be a temporary replacement for reduxForm() that wraps it and calls `this.props.destroy(this.props.form)` on cWM. We do this in conjunction with setting `destroyOnUnmount: false`. This is not the most ideal, but seems to be working for us at the moment

**Comment by erikras** [comment]
Fix published in [`v7.2.0`](https://github.com/erikras/redux-form/releases/tag/v7.2.0).

**Comment by giedriusvickus** [comment]
7.2.0 did not fix this issue for me :/

**Comment by mickykebe** [comment]
Not fixed on 7.2.0
![image](https://user-images.githubusercontent.com/3784089/33661847-a4e7ef48-da9a-11e7-8718-925b8472ab1d.png)

**Comment by serajam** [comment]
same here

**Comment by VasiliKubarka** [comment]
The same problem with REGISTER_FIELD and UNREGISTER_FIELD for one form when mounted and unmounted components has Field with the same name
![image](https://user-images.githubusercontent.com/19685464/34050648-a775bd4c-e1cc-11e7-88c1-4848dd4bfe73.png)

v7.2.0.
@erikras Are you going to fix this in the nearest future?

**Comment by AlexanderTserkovniy** [comment]
As well here with the same issue, please help at least with temporary workaround.

**Comment by rockneverdies55** [comment]
Any update on this? Why is the issue closed?

**Comment by kjanoudi** [comment]
Still broken for me with 7.2.0, i have the same behavior of it being destroyed as the last step after being initialized properly.

**Comment by BrendonEarl** [comment]
I came across this funny behaviour a wee bit ago too using `v7.2.0`.
In particular, it arose when using a ternary expression in the return statement to conditionally render the top level element; replacing it with a conditional statement containing separate returns fixed it for me. 

Original code causing bad behaviour:
```js
class MyComponent extends Component {
  render() {
    return (
      {
        props.someBool === true
          ? (
            <MyReduxForm1 />
          ) : (
            <MyReduxForm2 />
          )
    )
  }
}
```

Modified code which no longer demonstrates the bad behaviour:
```js
class MyComponent extends Component {
  render() {
    if (props.someBool === true)
      return (
        <MyReduxForm1 />
    else
      return (
        <MyReduxForm2 />
      )
  }
}
```

**Comment by AlexanderTserkovniy** [comment]
Okay guys, I had opportunity to avoid this issue. That's kind of sucks, but it works and form is not destroyed in the end.

In my case it occured because of `react-router` and I used `render` method instead of `component`, that fixed the issue.

BAD Example (**destroy** in the end):
```jsx
<Route
        path={`${props.match.url}/step-0`}
        component={compProps => <GetStartedScreen base={props.match.url} {...compProps} />}
/>
```

GOOD Example (NO destroy in the end):
```jsx
<Route
        path={`${props.match.url}/step-0`}
        render={compProps => <GetStartedScreen base={props.match.url} {...compProps} />}
/>
```

So in my case this small change helped me to resolve the issue.

**Comment by kjanoudi** [comment]
Adding enableReinitialize made things work for me

**Comment by diegorodriguesvieira** [comment]
@kjanoudi but are the validations still working?

**Comment by kjanoudi** [comment]
I haven't had any issues with validations.

**Comment by tkvw** [comment]
I'm not very happy with the solution, here are my 2 cents: 

The lifecycle events of react are to setup and cleanup *component* state. Currently redux-form binds redux state to the component using a `form` identifier only. This no longer works with React 16, because of the new lifecycle handling. So to bind the redux state more closely to the component rendered I think the way to go is to keep a local state identifier on the form component which is reduced in the redux form state. This identifier can be created with the `initialize` action creator and should be passed as an (optional) argument with the `destroy` action creator so the reducer can check if the identifier is stale/outdated. 

As a workaround I'm using a redux middleware, which makes sure to drop the `DESTROY` action if the form's `INITIALIZE` was called already: 
```
import { actionTypes } from 'redux-form';

const state = {};
export default () => next => action => {
    switch (action.type) {
        case actionTypes.DESTROY:
            state[action.meta.form] = (state[action.meta.form] || 0) - 1;
            if (state[action.meta.form] <= 0) {
                return next(action);
            } else {
                // Drop the action
                return false;
            }
        case actionTypes.INITIALIZE:
            state[action.meta.form] = (state[action.meta.form] || 0) + 1;
            return next(action);
        default:
            return next(action);
    }
};
```

**Comment by tapesec** [comment]
@tkvw Thanks so much dude, it works for me.

**Comment by ZizhangAi** [comment]
Other than @tkvw 's middleware, I also have to set `enableReinitialize` true

**Comment by eliseumds** [comment]
@tkvw @tapesec @ZizhangAi keep in mind that you can't increment the counter on reinitilization (which is INITIALIZE itself). Ideally we'd have a proper flag indicating that the action is for reinitilization, but all I could find was `lastInitialValues`:

```js
case actionTypes.INITIALIZE:
  // bypass reinitialization
  if ('lastInitialValues' in action.meta) {
    return next(action);
  }

  state[action.meta.form] = (state[action.meta.form] || 0) + 1;

  return next(action);
```
