### ISSUE TITLE
Field value after initialize works strange

### ISSUE THREAD

**Issue by meuwka** [erikras/redux-form#3437]
### Are you submitting a **bug report** or a **feature request**?
Probably a bug

### Description
I have component with 3 states: 'yes', 'no', 'unknown'.
I use this way to change value to 'unknown' :
```
input.onChange('')
```
And it works good. 
![screenshot from 2017-09-21 14-52-44](https://user-images.githubusercontent.com/2752193/30694418-9553aee0-9edc-11e7-80c2-c85faa4a5d7a.png)

But after form `initialize` plus `input.onChange('')` value is set to `''`. Also `onChange` stop work for 'unknown' -> 'no' and vice versa

![screenshot from 2017-09-21 14-56-08](https://user-images.githubusercontent.com/2752193/30694523-09a526f2-9edd-11e7-9059-8493ba6a7932.png)

### What is the current behavior?
After initialize `onChange('')` set value `''`

### What is the expected behavior?
Delete value of field after `onChange('')` like it works without `initialize`.
I expect that there should be one behavior with initialization and without it

### What's your environment?
redux-form@7.0.4

### Other information
You can view code here https://github.com/meuwka/redux-form-issue-test
It works good on another project with redux-form@5.3.6

**Comment by erikras** [comment]
Fixed by #3482.

**Comment by erikras** [comment]
Published fix in [`v7.1.0`](https://github.com/erikras/redux-form/releases/tag/v7.1.0).
