### ISSUE TITLE
Send data form via redux-form and reducer and action creator

### ISSUE THREAD

**Issue by tamyfabius** [erikras/redux-form#3439]
**Hello, How send the value of fields of my redux form ? Indeed, I need to send the values of fields of my form in database with a reducer and actionCreator.**

**_My form :_**
```
import React, {PropTypes} from 'react';

class myformClass extends React.Component {
 render(){
  return(
    <form>
      <Field
        name="inputName"
        ref="inputName"
        hintText="Le nom du flux" 
        floatingLabelText="Nom du input" 
        component={renderTextField} 
        fullWidth={true}
      />
      <Field
        label="inputComment" 
        name="inputComment"
        ref="inputComment"
        hintText="La description du input"
        floatingLabelText="Commentaire" 
        component={renderTextareaField} 
      />
    </form>
  )
 }
}

export default withRouter(reduxForm({
    form: 'myForm'
})(myformClass))
```
**_In my index app, I imported "reducer in redux-form":_**
`import { reducer as reduxFormReducer } from 'redux-form'`

**_I combined the reducers :_**
`let allReducers = combineReducers({form: reduxFormReducer })`

**_I created a action type :_**
`export const FORM_ADD = 'FORM_ADD'`

**_I created too a action creator :_**
```
export function addForm(dataForm) {
  return {
     type: types.FORM_ADD ,
     data: {
       INPUT_NAME: dataForm.inputName, 
       INPUT_COMMENT: dataForm.inputComment
     }
  }
}
```
**But Now, i don't know, how should I retrieve and send the value of my form with my action creator and the reducer. I know that I have to recover the value of my form and then send it.**

**_For information, I was able to recover the value of my redux-form by doing this :_**
```
import React, {PropTypes} from 'react';

class myformClass extends React.Component {

  static contextTypes = {store: PropTypes.object}

  getValMyForm = () => {
    const { store } = this.context
    const state = store.getState()
    let valueFormFLow = getFormValues('myForm')(state)
    return valueFormFLow;
  }
}

export default withRouter(reduxForm({
    form: 'myForm'
})(myformClass))
```

**I need Your HELP PLEASEEEEEE and I'm sorry for my english!!! :)**

**Comment by gustavohenke** [comment]
We have some examples on our site https://redux-form.com/7.0.4/examples/ and you can probably find good resources by searching a  little bit.

In case you still have issues, please migrate your question to StackOverflow.

**Comment by wsfuller** [comment]
Going through all the examples I can't find an example where Redux-Form is exported using React-Router's `withRouter()`.
