### ISSUE TITLE
Dynamic forms with props vs state

### ISSUE THREAD

**Issue by patrickheeney** [erikras/redux-form#344]
In all of the dynamic examples, it looks to be is using state. I have an application that receives json field schema using reflux via props. Because of this, when I dynamically add more fields to the schema, the entire form re-renders and loses the values. What would be the best way to get this working with props?

```
export class DynamicForm extends React.Component {
  static propTypes = {
    actions: React.PropTypes.object,
    fields: React.PropTypes.array
  }

  componentWillMount() {
    this.props.actions.fetchFields();
  }

  render() {
    const RenderForm = reduxForm({
      form: 'dynamicForm',
      fields: this.props.fields.map(item => "field_"+item.id),
      fieldMap: this.props.fields
    })(DynamicFormRender);

    return (
      <div className='container'>
            <RenderForm />
      </div>
    );
  }
}

class DynamicFormRender extends React.Component {
  static propTypes = {
    handleSubmit: React.PropTypes.func.isRequired,
    fields: React.PropTypes.array
  }

  renderField(item) {
    const name = 'field_'+item.id;
    const props = this.props.fields[name];
    return (
      <div key={name}>
        <label htmlFor={name+"_control"}>{item.name}</label>
        <input id={name+"_control"} type={'text'} {...props} />
      </div>
    );
  }

  render() {
    return (
      <form onSubmit={this.props.handleSubmit}>
        {this.props.fieldMap.map(this.renderField)}
        <button onClick={this.props.handleSubmit}>Submit</button>
      </form>
    );
  }
}
```

**Comment by erikras** [comment]
You should be able to add a field to the `fields` array and have the existing fields maintain their data, just like in the [Dynamic Example](http://erikras.github.io/redux-form/#/examples/dynamic). The Dynamic Example is only using React component state to manage the `fields` array, not for anything else.

`fieldMap` isn't a config property, by the way.

**Comment by patrickheeney** [comment]
Thanks. It seems the problem was creating reduxForm() within the render function during my quick test. Moving that to a separate import seems to have solved the issue. I was using `fieldMap` to pass in my full schema definition to render the form, since the field parameter is just an array of ids.
