### ISSUE TITLE
changedSinceLastSubmit

### ISSUE THREAD

**Issue by mschipperheyn** [erikras/redux-form#3443]
I have four states in my form:

- sync invalid but not yet submitted: don't show a general error message such as: please correct the form
- sync invalid and submitted: show a general error message: please correct the form
- sync valid with no async submitError: don't show any general message
- sync valid and async submitError: show: something went wrong submitting (server could be offline, or perhaps the username is already taken etc)

So, whenever, a person starts entering data, things will be initially async invalid. I don't want to show a general form error yet because that just confuses the user.

The person submits. If there are sync errors: now they will be shown based on `if (!valid && submitFailed)`.

The person fixes the errors and submits. The username is already taken. So there is a general error visible based on `if (submitFailed)` and the email field is red. 

The user fixes the email. No field is red, but the general error is still visible because of the submitFailed boolean. I don't want that. I want the general error to disappear as soon as the user starts changing a field again bc it's no longer applicable. 

I can do this using the general onChange event, using states etc, but, it would be much more convenient if there just wa a general instance value for that: changedSinceLastSubmit or something of that nature. Kind of a pristine boolean that gets reset with every submit. WDYT?

**Comment by gustavohenke** [comment]
Due to low users' interest on this issue, I'll close it.
