### ISSUE TITLE
ReduxForm keepDirtyOnReinitialize and enableReinitialize not updates arrays if they where empty by the first initialization

### ISSUE THREAD

**Issue by eugen35** [erikras/redux-form#3447]
### What is the current behavior?
ReduxForm keepDirtyOnReinitialize and enableReinitialize **not updates arrays** by reinitialization if they where empty by the first initialization.

`export const ActionPlan = props => {  
  return (
    <div>                 
      { Array.isArray(props.entity.prop1)  ?  props.entity.prop1.map((el, index) => <Field key={index} name={`entity.prop1[${index}]`} component="input" type="text" />) : null }
    </div>
  )
}`

If by the initialization we have: 
  ` {entity: {prop2:'repa'} }` or  ` {entity: {prop1:undefined, prop2:'repa'} }` or  ` {entity: {prop1:null, prop2:'repa'} }`
And by the reinitialization we have
  ` {entity: {prop1:[10, 15], prop2:'repa'} }`

After reinitialization in the form we will see **2 EMPTY fields**.

### What is the expected behavior?
After reinitialization in the form we will see **2 fields: one input with value 10 and another input with value 15**

###Environment
Windows 10, node v8.4.0, "redux-form": "6.8.0".

**Comment by gustavohenke** [comment]
1.5 years without a comment here, so I'm closing!
If the issue persists, please open a new one while still providing as much context as possible. Thanks!
