### ISSUE TITLE
Bug empty props.input.value when using multiselect

### ISSUE THREAD

**Issue by JozefBiros** [erikras/redux-form#3448]
### What is the current behavior?
Hello I am using multiselect from ant library with props which are passed from Field from redux-form v7.0.4
```
<Field
  name='productIds'
  component={MySelect}
/>

<MySelect
   multiple={true}
   value={props.input.value}
   onChange={value => props.input.onChange(val)}
   onBlur={() => props.input.onBlur()}
/>
```

Values provided by onChange props into props.input.onChange is a array of selected values. (for example ["1", "4"] and like so)

I assume this works as expected because feed values are store in redux-store
<img width="726" alt="sketch" src="https://user-images.githubusercontent.com/9303703/30781992-c5a0db64-a129-11e7-901e-a94e9f8eb6e1.png">

But "this.props.value" always return empty string.
<img width="441" alt="props input" src="https://user-images.githubusercontent.com/9303703/30782019-3d2333e4-a12a-11e7-934e-6017f9e3566f.png">

### What is the expected behavior?
props.input.value should return values stored in redux form when using multiselect

When I tried to debug in redux-form library a little bit this code is undefined with my use case
```
const value = getIn(formState, `values.${name}`)
```

**Comment by koriguy** [comment]
@JozefBiros did u find what was the issue?

**Comment by JozefBiros** [comment]
Yes I did it was my mistake, I am using immutable state and i had messed up imports...I have forgotten to import "Field" from "redux-form/immutable"

**Comment by koriguy** [comment]
Got it. not exactly my issue but thanks

**Comment by JozefBiros** [comment]
Happy to help. :)
