### ISSUE TITLE
Deep Forms: array.forEach is not a function when using initialValues ?

### ISSUE THREAD

**Issue by slybridges** [erikras/redux-form#345]
Hi @erikras 

First of all thanks for the support of Deep Nested fields in v3.1.0 ! :+1:

I am facing an issue for which I'm not sure whether it is a bug or whether I'm doing it wrong.
I have deep form for which I want to initialize it with 2 elements by default. 

I did something along those lines:
```javascript
@reduxForm(
  { form: 'foo',
    fields: [ 'children[].bar' ],
    validate: validateFoo
  },
  (state, props) => ({
    initialValues: { children: [ {bar: null}, {bar: null} ] }
  })
)
```

This throws with `array.forEach is not a function` coming from https://github.com/erikras/redux-form/blob/develop/src/getValues.js#L20

When I inspect `array`, indeed i have:

```javascript
array: Object
   initial: Array[2]
      0: Object
      1: Object
   value: Array[2]
      0: Object
      1: Object
```

I also tried to check for the` length` of `children` in `render()` and call `children.addField()` twice if `length==0` . That doesn't work either because by the time my component is rendered, the changes have not yet been updated in the reducer and `children[0].bar` is still undefined.

How to initialize a deep field with a default number of element ?

**Comment by erikras** [comment]
It's a bug. I've replicated it in a test. :+1:

**Comment by tomduncalf** [comment]
See also my report in https://github.com/erikras/redux-form/issues/55#issuecomment-160598445, cheers

**Comment by erikras** [comment]
I had totally forgotten about initialization for the deep fields. Fixed in `v3.1.1`.

**Comment by tomduncalf** [comment]
Fantastic, looks good to me, many thanks for such a quick fix!

**Comment by markuso** [comment]
This also happens when calling `resetForm()` while having deep fields on `v3.1.3` still.

**Comment by erikras** [comment]
Doh. Will fix...

**Comment by erikras** [comment]
@markuso Deep resetting fixed in `v3.1.4`.

**Comment by rogeriochaves** [comment]
@erikras This also happens when calling `change` for deep fields

**Comment by rhythnic** [comment]
I'm getting this error as well when I use the mapStateToProps function, v4.0.3.

```
export default reduxForm({
  form: 'ServiceSiteForm',
  fields
},
state => {
  const organization = state.organization.current;
  return {initialValues: {organization}};
})(MyForm);
```

Error:
```
Uncaught TypeError: array.forEach is not a function
```

I also get the error when returning simple string values
```
export default reduxForm({
  form: 'ServiceSiteForm',
  fields
},
state => {
  return {initialValues: {name: 'Test Name'}};
})(MyForm);
```

If I remove the mapStateToProps function, it works fine.

**Comment by jonnolen** [comment]
i'm on 4.2.0, i have a mult-page/wizard form, my deep fields are on page 3, when page 3 renders I am still passing initial values into the form but they are not rendering.  If i load page three directly with initialValues it does render correctly.

resolution is to manually dispatch initialize before the first form is loaded/connected. using the initialValues and fields for all steps.
