### ISSUE TITLE
Wizard form is not saving states from pages

### ISSUE THREAD

**Issue by moisesnandres** [erikras/redux-form#3452]
When I want to go to a previous page which have a state, it's not saved.

**Comment by erikras** [comment]
Are you setting [`destroyOnUnmount: false`](https://redux-form.com/7.0.4/docs/api/reduxform.md/#-code-destroyonunmount-boolean-code-optional-)?

**Comment by moisesnandres** [comment]
yes

**Comment by gustavohenke** [comment]
Hi @moisesnandres, please provide evidence that redux-form may have a bug, otherwise please migrate it to StackOverflow.

**Comment by moisesnandres** [comment]
I found a similar [question](https://stackoverflow.com/questions/39343125/why-redux-form-wizard-form-cant-save-state) on stackoverflow . I will try to figure it out.
