### ISSUE TITLE
how to add different error to redux-form field on different action

### ISSUE THREAD

**Issue by sundar505** [erikras/redux-form#3457]
I have 2 actions "openforgotform"(onclick) and "onsubmit", I have to do different validation on a different action. I am new to redux form. can you please explain how to do this

@erikras 

![bfd4da82-0cb4-42c5-b846-7f3e4b8826b6](https://user-images.githubusercontent.com/8457647/30867739-66f80fce-a2fa-11e7-854f-662835e71b3e.png)

**Comment by gustavohenke** [comment]
Thanks for using Redux Form! Unfortunately your question doesn't belong to our issue tracker. We recommend you to use StackOverflow instead.
