### ISSUE TITLE
exporting change action with formKey

### ISSUE THREAD

**Issue by haradakunihiko** [erikras/redux-form#346]
Hi, @erikras 
 Is there any reason why only 'initialize' action for each formKey is exported as 'initializeWithKey' ?
 In my page, there are buttons to complete all input and to reset all values, and I guess I need 'changeWithKey' action or something like that. 
 Or am I supposed to use plugin feature?

**Comment by erikras** [comment]
Added in `v3.1.1`.

**Comment by haradakunihiko** [comment]
Wow, really first! Thanks!!
