### ISSUE TITLE
Performance issue (crash) in large apps when using Field with children in React v16

### ISSUE THREAD

**Issue by flut1** [erikras/redux-form#3461]
### Are you submitting a **bug report** or a **feature request**?
bug

### What is the current behavior?
Reproduction:
 - Use redux-form with React v16 in a large application (a page with a lot of different nested React components)
 - Add a field with children:  
```
<Field component={SomeCustomInput} ...>
   <SomeChild \>
   <SomeChild \>
   <SomeChild \>
</Field>
```
 - The page becomes so slow that the browser becomes unresponsive and crashes

What seems to happen is that `<ConnectedField />` will execute `shouldComponentUpdate`, which will call lodash `isEqual` on its props. The `children` prop in react v16 contains `FiberNode` objects, which seem to have references to a lot (if not all) other `FiberNode` on the page. Because of this, lodash `isEqual` will take a very very long time recursively traversing through these objects. 

### Sandbox Link
Unfortunately I haven't been able to reproduce this in stand-alone example. If I create a `<Field>` with children in one of the examples of this repo, I can see lodash `baseIsEqualDeep` being called with very long call stacks. However, it is not enough to visually slow down the page.

### What's your environment?
All browsers
React v16
redux-form v7.0.4

**Comment by gaearon** [comment]
Please don't try to do deep equality checks on React data structures. It was never intentionally supported. The only way you can get to `FiberNode`s is via `_owner` property on an element. It is considered internal, and you should never traverse it. It happened to work in 15 but even in 15 it was very inefficient because you compared internal instances. In 16, there are more potential paths between nodes so this is how you encounter it.

**Comment by erikras** [comment]
... when the calculation to decide _not_ to render takes up more time than actually doing the render ... 🤦‍♂️

**Comment by gaearon** [comment]
Yeah, this is why we don't recommend deep equality checks 😛

**Comment by oieduardorabelo** [comment]
doing consulting, often I see:

```
shouldComponentUpdate(nextProps) {
  if (JSON.stringify(nextProps) !== JSON.stringify(this.props) {
    ....
  }
}
```

can be as bad as this one, I suppose?

this issue will be another good argument for this scenario 😅

**Comment by gaearon** [comment]
Oh god.

**Comment by erikras** [comment]
@oieduardorabelo How inefficient! You could cache those strings! 😆
```jsx
shouldComponentUpdate(nextProps) {
  const next = JSON.stringify(nextProps)
  const different = !this.lastProps || next !== this.lastProps
  this.lastProps = next
  return different
}
```
🤣 🤣 🤣

**Comment by umidbekkarimov** [comment]
Or just check react elements in deepEqual 

```diff
// @flow
+ import React from 'react'
import { isEqualWith } from 'lodash'

const customizer = (obj: any, other: any) => {
  if (obj === other) return true
  if (
    (obj == null || obj === '' || obj === false) &&
    (other == null || other === '' || other === false)
  ) {
    return !(
      (obj === undefined && other === false) ||
      (obj === false && other === undefined)
    )
  }

  if (obj && other && obj._error !== other._error) return false
  if (obj && other && obj._warning !== other._warning) return false
+  if (React.isValidElement(obj) || React.isValidElement(other)) return false
}

const deepEqual = (a: any, b: any) => isEqualWith(a, b, customizer)

export default deepEqual
```

**Comment by erikras** [comment]
@umidbekkarimov Interesting approach, but I'm pretty happy with my solution in #3480. If there are (or were) `children`, `shouldComponentUpdate()` _must_ return `true`.

**Comment by gaearon** [comment]
What if the prop is not called children? Custom component could receive another prop with React elements, e.g. `<Input placeholder={<span />} />`.

**Comment by gaearon** [comment]
Why can't this be a simple shallow equality check?

**Comment by iamtommcc** [comment]
@gaearon In the example you provided (`<Input placeholder={<span />} />`), wouldn't a shallow equality never work since `createElement` is being called every render for that span? Or have I totally misunderstood?

**Comment by Andarist** [comment]
I think @gaearon meant that no deep equality check should happen, regardless the prop name. If you want to preserve identities - just cache ur complex data structures (like `<span/>`) in ur example, so they can be shallowly equaled between renders.

**Comment by gaearon** [comment]
Yes. I'm saying that, unless it is *your* component and you're in control of its API, you shouldn't assume that the only place where React elements can appear is `this.props.children`. They could be in any prop (or in some nested data structure inside a prop).

To me, it seems like it is never safe to do deep equality checks on props.

**Comment by erikras** [comment]
Good arguments, @gaearon. Implemented @umidbekkarimov's idea in #3481.

**Comment by erikras** [comment]
Published fix in [`v7.1.0`](https://github.com/erikras/redux-form/releases/tag/v7.1.0).

**Comment by kamleshchandnani** [comment]
If deep comparision or JSON.stringify() is not a good approach then how can we do an equality check? It's not necessary that everytime by shallow compare we can decide whether to update the component from shouldComponentUpdate()

**Comment by Andarist** [comment]
Why shallow comparison would not be good enough? If you prefer immutability (and I think you should, it's also rather preferred way in React's ecosystem), you can easily rely on shallow comparisons.

**Comment by kamleshchandnani** [comment]
Assuming if my object on which the react component depends is of the form ```themeObj:{theme:{"header":{"leftHeaderColor":"red","rightHeaderColor":"black"}}}``` and I have to return true only when ```rightHeaderColor``` is changed, but this will fail in shallow compare
