### ISSUE TITLE
Cannot select "error" value of form

### ISSUE THREAD

**Issue by Noitidart** [erikras/redux-form#3463]
### Are you submitting a **bug report** or a **feature request**?
Bug report

### What is the current behavior?

We are able to use selectors to get all kinds of values, except for the "error" value when we `throw new SubmissionError({ _error:'...' })`.

### What is the expected behavior?
Some way to get taht `error` value.

### What's your environment?

redux-form - 7.0.3
os: all
node: all

### Other information

I posted a stackoverflow topic here 10 days ago but no word - https://stackoverflow.com/q/46310282/1828637 - so I think it is a missing feature/bug.

Quote of my SO post:

> I am trying to get the `error` prop of a form. When a form throws `throw new SubmissionError({ _error:'hi' })` the `this.props.error` value is set to `"hi"`. However I tried all the selectors here - https://redux-form.com/7.0.4/docs/api/selectors.md/
>
> I expected `getFormSubmitErrors` to give me the `error` prop, but it doesn't. Is there a way to get this? I even tried: `getFormSyncErrors`, `getFormAsyncErrors`, `getFormSubmitErrors`, `getFormSyncWarnings`, `getFormMeta`.
>
> I am using v7.0.3.

**Comment by gustavohenke** [comment]
Thanks for the heads up, @Noitidart.
As a proof of the bug, I created this CodeSandbox: https://codesandbox.io/s/vqqxjwkqo7

**Comment by Noitidart** [comment]
Thank you sir very much.

**Comment by erikras** [comment]
Okay, but what key should it be under in the errors? `_error`?

**Comment by gustavohenke** [comment]
@erikras I would say  `_error`, since that's what you set in `SubmissionError`

**Comment by faizrr** [comment]
It's not a bug. `_error` prop may be set in different ways, not only via SubmissionError. And it's logical not to put this "global" error into syncErrors, asyncErrors etc. Check out my PR that adds one more selector.

**Comment by erikras** [comment]
Published fix in [`v7.1.0`](https://github.com/erikras/redux-form/releases/tag/v7.1.0).

**Comment by Noitidart** [comment]
Wow super fast release, thank you all involved!
