### ISSUE TITLE
Async - Promise Redux-Form

### ISSUE THREAD

**Issue by tamyfabius** [erikras/redux-form#3465]
Hello, I need to get the answer returned by my server after inserting data from redux form
Indeed, I have websocket that allows me to communicate with the database. So, when submitting the form, the data is saved in the database and my websocket sends me a message like "ITEM_ADD_SUCCESS", to tell me that the insertion was done well.
And by creating an action with this type of message I manage to recover the id of the item that has just been created.
But the problem is that I can not retrieve from my frontend neither the id nor the message returned by the server after insertion.

So, I would like to know if you can help me so that I can retrieve the message and the id returned by the server after insertion. PLEASEE

**Comment by gustavohenke** [comment]
I recommend you to look at [redux-saga](https://github.com/redux-saga/redux-saga).

But, this type of question is better suited for StackOverflow. Please ask it there.
