### ISSUE TITLE
Generating form values

### ISSUE THREAD

**Issue by jonathanasquier** [erikras/redux-form#347]
Hey, I have a password field and a "generate random" button next to it.
I tried 2 things :
1)
`this.props.password.value = this.props.newuser.password;`
(newuser is not a redux form generated state, but mine which contains only the password field, to be in the redux flow on button click);
this populates the form field but the state stays empty, until I focus the field for example. 
2)
    ```state => ({
        initialValues: state.newuser
    })```
Which works for the password, but obviously empties the rest of the form state.
How could I get the best of both worlds? Is there a way to compute new initial values based on the current form state?

Thanks!

**Comment by erikras** [comment]
Is it a server-side call to do the generation, or on the client side? If it's just on the client side, I think using Redux is overkill, you could have:
```js
<button onClick={() => {
  this.props.fields.password.onChange(genPassword());
}}>Generate Password</button>
```
Using "initialize" is only useful if you care about the `dirty` state changing if the value is modified, which doesn't make _too_ much sense for this use case. Calling `field.onChange()` will just set the value for your field, which I believe is what you are looking for.

If you are doing the password generation on the server side, I might recommend using the [`plugin()` API](http://erikras.github.io/redux-form/#/api/reducer/plugin) to listen to your `GENERATE_PASSWORD_SUCCESS` action and set the value in the form.

**Comment by jonathanasquier** [comment]
Cool,
I did it that way :
```
onClick={(e) =>{
    e.preventDefault();
    password.onChange(generatePassword(dispatch));
}}
```
and `password.value = user.password` in the render function as I donc have access to the form reducer. `generatePassword` is handled in the user reducer.
It's not server side password generation.
Seems to work!

**Comment by jonathanasquier** [comment]
Hey, my input is working properly, but i still have to focus/blur to resync the validation on the input.
Ex : 
- I focus and blur the input --> "This field is required"
- click on generate password (which sets a password in the user state)
```
<button onClick={function(e){
    e.preventDefault();
    password.onChange(generatePassword(dispatch));
}}>Genererate password</button>
```
- The error display logic is `password.touched && password.error`
- Before the render function : `password.value = user.password;`

BUT I have to re focus/blur the field so that the validation syncs properly.
Any idea ?

Thanks!

**Comment by jonathanasquier** [comment]
```
<button onClick={function(e){
    e.preventDefault();
     generatePassword(dispatch);
}}>
```
Fixed it, for the record!
