### ISSUE TITLE
Please Release Latest Version

### ISSUE THREAD

**Issue by bdwain** [erikras/redux-form#3474]
I would like to use the latest version of Redux-Form to avoid the bugs that it has fixed, but it is giving me the warnings that were fixed in #3387. Is there any reason a 7.0.5 can't be released with the fix? I know I'm not alone in having spent a bunch of time trying to track down where the warnings came from and since the problem has already been solved it seems like a waste not to release the fix.

**Comment by gustavohenke** [comment]
Some PRs were merged containing not only bugs, but features as well, so a 7.1.0 release is more appropriate.

If @erikras didn't release anything yet, there is a very high chance that some things still need to be done.

**Comment by erikras** [comment]
A release is coming soon, but I've been fighting with React 16 lately. Moreso with the deprecation of `expect`, which required migrating _all_ the tests over to `jest`.

**Comment by bdwain** [comment]
ah got it. alright.
