### ISSUE TITLE
Import of react-redux is breaking redux-form on React Native

### ISSUE THREAD

**Issue by dbanck** [erikras/redux-form#348]
redux-form is still using version `3.1.0` of `react-redux`. This requires the import of `connect` from `react-redux/native` for React Native applications.

In your rewrite for redux-form 3 you removed the extra import for the native part in commit: 0511eae9a9f8c5c8e2cc4e45d5e833407244d127

As long React Native is still depending on a fork of React (see: https://github.com/facebook/react-native/issues/2985). We have to keep using `3.1.0` of react-redux instead of `4.0.0` and need to import `connect` twice.

**Comment by erikras** [comment]
Excellent catch! :+1:

**Comment by dbanck** [comment]
Should I do a PR for this?

**Comment by erikras** [comment]
Fixed in `v3.1.1`. I don't have a RN dev environment, so please verify that it's working and let me know.

**Comment by dbanck** [comment]
Yes, it's working now. Thanks a lot :clap:
