### ISSUE TITLE
Custom associative array of fields + immutable + unset problem

### ISSUE THREAD

**Issue by tonoslav** [erikras/redux-form#3487]
### Are you submitting a **bug report** or a **feature request**?
Question / bug report

### What is the current behavior?
I have more components where I use more fields for example
Fields with name: address[street], address[number], address[zip], address[city]
And I need to **unset** all values on **unmount** but I need to be just **empty object** or **nothing** at all in **address** variable

So I have 

```
componentWillUnmount() {
        this.props.dispatch(change(
            this.props.formSelector,
            this.props.field,
            {}
        ))
}
```

And as it should, it unset all, but than when I remount it back (withing the same form, not remounted)  and try to type anything in any of the fields, I get error "immutable.js invalid keyPath"

### What's your environment?
Redux form: 7.0.4
React: 16.0.0
Immutable: 3.8.1
redux-immutable: 4.0.0
node: 8.6.0

### Other information
I have always some problem with fields which are arrays, I have to always do some workarounds for them

**Comment by erikras** [comment]
Can you figure out what the `keyPath` it's trying to use is?

**Comment by tonoslav** [comment]
Probably this 
![image](https://user-images.githubusercontent.com/3399021/31288306-a33a0aba-aac4-11e7-93d9-fda8d0ef47d3.png)

but every field of them when I try to edit them I keep getting this error 

Maybe it should really help if you could add some actionCreator for unseting value from values?

```
{
    name: 'test',
    surname: 'nice',
    address: {
       street: 'Top blvd',
       num: '15'
   }
}
```

and on calling dispatch(**unset**(form, 'address'));

it would be 

```
{
   name: 'test',
   surname: 'nice',
}
```

**Comment by erikras** [comment]
If you could reconstruct this in the [Immutable Sandbox](https://codesandbox.io/s/ZVGJQBJMw), that would be most awesome.

**Comment by tonoslav** [comment]
@erikras 
https://codesandbox.io/s/746rjmvl51

1. Write values for example , **UserName**: Test, **Age**: 33, 
2. New field **Test** will appear
3. Write anything in it for example **test** again
4. Remove age (empty field)
5. Type age again **33**
6. Type anything in **Test field**
7. **Magic**

![image](https://user-images.githubusercontent.com/3399021/31308117-1857fc9c-ab71-11e7-90c5-11cbcb175e47.png)

**Comment by erikras** [comment]
Thanks! A reproducible sandbox makes bugs _so_ much easier to track down.

**Comment by erikras** [comment]
Your problem is that Redux Form expects its `values` structure to be Immutable objects, and you have placed `{}` in there, so when it goes to `setIn(['values', 'test', 'more'], 'whatever)`, it dies because `test` is not a `Map`.

Here's the fix: (see line 14)

[![Edit Redux Form  - Immutable JS Example](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/rw04q1n5v4?module=%2FImmutableForm.js)
