### ISSUE TITLE
Async validation, login

### ISSUE THREAD

**Issue by allantatter** [erikras/redux-form#349]
Not sure how I should handle form submission and server-side errors when submitting Login form. My `handleSubmit` looks like this atm (FYI `handleSubmit` is called on submit `onSubmit={handleSubmit}`):

```
  parseErrors(response) {
    return response.error;
  }

  handleSubmit(data) {
    return new Promise((resolve, reject) => {
      this.props.login(data.email, data.password).then((result) => {
        if (result.type === 'redux/auth/LOGIN_SUCCESS') {
          this.props.dispatch(initialize('login', {})); // clear form
          resolve();
        } else {
          reject(::this.parseErrors(result));
        }
      });
    });
  }
```

I'm quite new to Redux but `if (result.type === 'redux/auth/LOGIN_SUCCESS') {` seems really odd and wrong.

**Comment by erikras** [comment]
Ideally...

1. You would clear your form [like this](http://erikras.github.io/redux-form/#/faq/how-to-clear) (A or B).
2. Your server would return an [error code 401](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#4xx_Client_Error), which would already end up in your rejection branch.

```js
handleSubmit(data) {
  return this.props.login(data.email, data.password)
    .then(result => {
      // do something like navigate to another page
    })
    .catch(::this.parseErrors);
}
```

But if you don't have control over the server, then you will need to check something in the `result` to figure out if it was successful or not.

**Comment by allantatter** [comment]
Cool, thanks for the guidance!
