### ISSUE TITLE
Possible regression with custom reducers

### ISSUE THREAD

**Issue by chrissnyder** [erikras/redux-form#3490]
### Are you submitting a **bug report** or a **feature request**?

Bug

### What is the current behavior?

I think there was a regression in the latest release. Prior to 7.1.0, custom reducers defined by `reducer.plugin` would receive app actions. In 7.1.0, they only receive redux-form actions.

### What is the expected behavior?
That custom reducers provided through reducer.plugin receive app actions, like `AUTH_LOGIN_FAIL` in the example on https://redux-form.com/7.1.0/docs/api/reducerplugin.md/

### What's your environment?

redux-form 7.1.0

### Other information

Many thanks for the library. Always a pleasure to work with.

**Comment by erikras** [comment]
Excellently described. Thanks!

**Comment by erikras** [comment]
Published fix in [`v7.1.1`](https://github.com/erikras/redux-form/releases/tag/v7.1.1).
