### ISSUE TITLE
Get InitialValues by connecting mapStateToProps

### ISSUE THREAD

**Issue by pinkynrg** [erikras/redux-form#3491]
I'm trying to get the initialValues of the form setup as follows but it doesn't work:

```javascript
const mapStateToProps = (state, props) => ({   
  initialValues: state.charts[props.resourceId], 
});  

const mapDispatchToProps = ...  

export default reduxForm({    
  form: 'ChartForm', 
})(connect(mapStateToProps, mapDispatchToProps)(ChartForm)); 
```

Of course if I do something like this will work:

```javascript
export default reduxForm({        
  form: 'ChartForm',       
  initialValues: {           
    title: "Some Title",           
    ...       
  } 
})(connect(mapStateToProps, mapDispatchToProps)(ChartForm)); 
```

That is not what I need though. I need to get the initial values from a resource in my store that has 
`id == this.props.resourceId`

Could anybody point out what is wrong with the first solution?

**Comment by artnos** [comment]
I ran into the exact same problem, I wish this was on stackoverflow so i can get some credit. :) 

Anyway what you have to do is switch the order of your export default call connect first then redux form. Here is a snippet from my code.

     function mapStateToProps(state) {

        return {
            initialValues :state.updateFormDefaultValues
         }
    }

    export default connect( mapStateToProps,actions )(
        reduxForm({
            form: 'UpdateSection',
            enableReinitialize : true
        })(UpdateSection)
     );

**Comment by pinkynrg** [comment]
It is actually https://stackoverflow.com/questions/46623620/reduxform-passing-initialvalues-from-mapstatetoprops. I posted it in both places. Someone else already answered though... (I could give you a +1, don't say it to anyone though...)

**Comment by artnos** [comment]
It's okay, he answered it 51 mins ago i answered it 28 mins ago. I'll say he is the winner. The next hurdle i faced with redux form is understanding the plugin api in the reducer. And getting into the redux dev tools. After that i felt like I mastered redux forms. Good luck with your development.

**Comment by pinkynrg** [comment]
Thanks :)

**Comment by charlie-axsy** [comment]
@pinkynrg @artnos you might want to consider using a `compose` function to compose higher-order components.  Compose is already available from redux.  In my opinion it looks neater and it easier to follow the flow of props down the HOCs.

```jsx
import { compose } from 'redux'

export default compose(
  connect((state, props) => ({
    initialValues: state.charts[props.resourceId]
  })),
  reduxForm({
    form: 'ChartForm'
  })
)(ChartForm)
```
