### ISSUE TITLE
Why is babel-jest a dependency?

### ISSUE THREAD

**Issue by oliviertassinari** [erikras/redux-form#3498]
### Are you submitting a **bug report** or a **feature request**?

Bug

### What is the current behavior?

babel-jest is a dependency

https://github.com/erikras/redux-form/blob/524d1cdf5179bb9ce5e227d19cfe87aa6be97731/package.json#L59-L61

### What is the expected behavior?

babel-jest is not a dependency

### What's your environment?

v7.1.0

**Comment by oliviertassinari** [comment]
I have noticed it with the following side effect on all my jest tests:
>   ● Test suite failed to run

    TypeError: Path must be a string. Received undefined
      
      at assertPath (path.js:28:11)
      at Object.relative (path.js:1247:5)

It's related to https://github.com/facebook/jest/issues/4562

**Comment by derekschneider** [comment]
I'm also having the same issue as @oliviertassinari, no problems so far in actual application though.

**Comment by erikras** [comment]
That was a mistake during the jest migration. Thanks. `jest` was also in the `dependencies` before.

**Comment by erikras** [comment]
Fix published in [`v7.1.2`](https://github.com/erikras/redux-form/releases/tag/v7.1.2).

**Comment by oliviertassinari** [comment]
🎉
