### ISSUE TITLE
Adding custom property to a field via a plugin

### ISSUE THREAD

**Issue by jdudek** [erikras/redux-form#350]
I have slightly different logic for presenting validation errors than redux-form defaults. Specifically, I want to display errors only after a form has been submitted, but hide it when a field is blurred. There’s also a summary of errors displayed after clicking submit, but only until the user focuses any field.

So I thought about having my own state for these features: `displayFormErrors` flag for the whole form and `displayError` flag for each field. Then I can easily maintain this state as I need, without trying to map it to existing `touched` flags (which work differently than what I need).

I tried to implement it via reducer plugin and it’s not hard to extend the state when actions happen. However, the additional state does not get included in props passed to the component. The only way I’ve found is to implement `mapStateToProps` and merge the additional state, which seems a bit complex. Is there a simpler way for a plugin to add some props to a field?

**Comment by erikras** [comment]
It sounds like your use case is complex enough that you might just want to have your own reducer for managing this state. Trying to jury-rig the `touched`, `submitFailed`, and `errors` props into what you want will be too messy and prone to possibly breaking in the future.

**Comment by jdudek** [comment]
Thanks for very quick response!

I see. Would you recommend having a totally separate reducer with its own subtree in state? I guess it could still intercept redux-form’s actions. The downside is that I’ll also need to maintain code for multiple forms in that state, possibly indexed by keys (just like redux-form maintains multiple forms at `form` key in state).

With the reducer plugin approach, it’s quite easy to add any state within redux-form’s state, but it’s a bit harder to extract it to props.

**Comment by jdudek** [comment]
Hi @erikras,

In the last few days I’ve been experimenting with an alternative approach. I’ve implemented my own “library” for forms and I’m curious what you think.

The main differences are:
* Instead of `fields` prop with all the input props you need, I return functions like `inputProps` that return what you need (e.g. `inputProps('firstName')`).
* You can decorate the above with your own functions, e.g. `inputProps('firstName')` can return `name` and `id` attributes, or you can add `labelProps` with props for `<label>`—or any other derived data that you need, even things very specific to your components.
* The state shape allows arbitrary nesting, e.g. `values.address.street`. Metadata is stored separately, e.g. `errors.address.street`.
* You can decorate the default reducer to maintain any additional state you need or handle your own actions. It’s similar to redux-form plugins, but I think the simpler state shape makes it easier to use. Typical use cases are adding a row in nested form or resetting additional data when `RESET` action happened.
* There’s no need to pre-configure the form with `fields` array (thus it saves user from some repetition)
* There is no required mount point. I haven’t figured it out completely (yet), there’s a `formName` argument in actions, but I think I may need more configuration in order to support forms mounted at arbitrary place in the tree.

Here’s a gist with code and some more explanations: https://gist.github.com/jdudek/03fbbddb0f80392385e2

It’s definitely very immature code, but I’m wondering if some of the API ideas could be useful for redux-form.
