### ISSUE TITLE
Form gets submitted on push and unregister and register field inside my console

### ISSUE THREAD

**Issue by waleedbk** [erikras/redux-form#3501]
Hi, I'm using redux-from 7.1.0. When i try to push field inside my field array, my form gets submitted and my console shows submit_succeeded, unregister_field, register_field (again and again). I'm suffering from last two weeks to fix this. Please let me know how to fix it as soon as possible. 

`
import React from 'react'
import { connect } from "react-redux"
import { Field, FieldArray, reduxForm } from 'redux-form'
import validate from './validate'
import { Button, Grid, Row, Col, Icon, Modal, Table, Tr, Td, Input } from "react-materialize";
import * as storeActions from "../actions/storeActions";

@connect((store) => {
  return {
    // storeDemandForm: store.form.storeDemand,
    section: store.store.section,
    person: store.store.person,
    items: store.store.items,
  }
})

// @reduxForm({
//   form: 'storeDemand', // a unique identifier for this form
//   validate
// })

// export default class StoreDemand extends React.Component {
class StoreDemand extends React.Component {

  constructor(props) {
    super(props);
    this.state = {}
  }

  componentWillMount() {
    console.log("component will mount");
    this.props.dispatch(storeActions.fetchStoreDemand());
  }

  createDemand = (values) => {
    //const data = this.props.storeDemandForm.values;
    //this.props.dispatch(storeActions.createStoreDemand(data));
    console.log(values);
    //this.props.reset();
  }

  render () {
    const { handleSubmit, pristine, reset, submitting, section, person, items } = this.props

    const renderField = ({ input, label, type, col, meta: { touched, error } }) =>
      <Input s={2} type={type} {...input} label={label} error={touched && error} />

    const renderSection = section.map((item, index) => {
      return(
        <option key={index} value={item.id}>{item.name}</option>
      )
    });
    const renderSectionField = ({ input, label, type, meta: { touched, error } }) =>
      <Input s={6} {...input} type={type} label={label} error={touched && error}>
        <option value="" disabled>Choose section</option>
        {renderSection}
      </Input>

    const renderPerson = person.map((item, index) => {
      return(
        <option key={index} value={item.id}>{item.name}</option>
      )
    });
    const renderPersonField = ({ input, label, type, meta: { touched, error } }) =>
      <Input s={6} {...input} type={type} label={label} error={touched && error}>
        <option value="" disabled>Choose Person</option>
        {renderPerson}
      </Input>

    const renderItem = items.map((item, index) => {
      return(
        <option key={index} value={item.id}>{item.name}</option>
      )
    });
    const renderItemField = ({ input, label, type, meta: { touched, error } }) =>
      <Input s={3} {...input} type={type} label={label} error={touched && error}>
        <option value="" disabled>Choose Item</option>
        {renderItem}
      </Input>

    const renderItems = ({ fields, meta: { error, submitFailed } }) =>
      <div>
        {fields.map((item, index) =>
          <div key={index}>
            <Field
              name={`${item}.item`}
              type="select"
              component={renderItemField}
              label="Item"
            />
            <Field
              name={`${item}.accountingUnit`}
              type="select"
              component={({ input, label, type, meta: { touched, error } }) =>
                <Input s={2} {...input} type={type} label={label} error={touched && error}>
                <option value="" disabled>Choose AU</option>
                  <option value="weight">Weight</option>
                  <option value="volume">Volume</option>
                  <option value="nos"><Button waves="light" value="Nos" onClick={() => fields.push({})} s={2} /></option>
                  <Button waves="light" value="Nos" onClick={() => fields.push({})} s={2} />

                </Input>
              }
              label="Accounting Unit"
            />
            <Field
              name={`${item}.quantity`}
              type="number"
              component={({ input, label, type, meta: { touched, error } }) =>
                <Input s={2} {...input} type={type} label={label} error={touched && error} />
              }
              label="Quantity"
            />
            <Field
              name={`${item}.rate`}
              type="number"
              component={renderField}
              label="Rate"
            />
            <Field
              name={`${item}.cost`}
              type="number"
              component={({ input, label, type, meta: { touched, error } }) =>
                <Input s={2} {...input} type={type} label={label} error={touched && error} />
              }
              label="Cost"
            />
            <Col s={1}>
              <Button floating small style={{top: '20px'}} className="red center" waves="light" icon="remove" onClick={() => fields.remove(index)} />
            </Col>
          </div>
        )}
        <Col s={12}>
          <Button floating small className="light-blue accent-3 center" waves="light" icon="add" onClick={() => fields.push()} s={2} />
        </Col>
        {
          submitFailed &&
          error &&
          <span className="red-text">
            {error}
          </span>
        }
      </div>

      return (
        <Row>
          <Col s={12} className="z-depth-1">
            <h5 className="center-align">Store Demand</h5>
            <form onSubmit={handleSubmit(this.createDemand)}>
              <Row className="center-align">
                <Field
                  name="section"
                  type="select"
                  component={renderSectionField}
                  label="Section"
                />
                <Field
                  name="person"
                  type="select"
                  component={renderPersonField}
                  label="Person"
                />
                <FieldArray name="items" component={renderItems} />
                <Col s={12} >
                  <Button medium className="right light-blue accent-3" waves="light" s={2}>Create</Button>
                </Col>
              </Row>
            </form>
          </Col>
        </Row>
      )
    }
}
//
export default reduxForm({
  form: 'storeDemand', // a unique identifier for this form
  //validate
})(StoreDemand)

`

action @@redux-form/SET_SUBMIT_SUCCEEDED @ 13:51:21.675
redux-logger.js:1  prev state {store: {…}, item: {…}, section: {…}, person: {…}, seller: {…}, …}
redux-logger.js:1  action     {type: "@@redux-form/SET_SUBMIT_SUCCEEDED", meta: {…}, error: false}
redux-logger.js:1  next state {store: {…}, item: {…}, section: {…}, person: {…}, seller: {…}, …}
redux-logger.js:1  action @@redux-form/UNREGISTER_FIELD @ 13:51:21.684
redux-logger.js:1  prev state {store: {…}, item: {…}, section: {…}, person: {…}, seller: {…}, …}
redux-logger.js:1  action     {type: "@@redux-form/UNREGISTER_FIELD", meta: {…}, payload: {…}}
redux-logger.js:1  next state {store: {…}, item: {…}, section: {…}, person: {…}, seller: {…}, …}
redux-logger.js:1  action @@redux-form/UNREGISTER_FIELD @ 13:51:21.691
redux-logger.js:1  prev state {store: {…}, item: {…}, section: {…}, person: {…}, seller: {…}, …}
redux-logger.js:1  action     {type: "@@redux-form/UNREGISTER_FIELD", meta: {…}, payload: {…}}
redux-logger.js:1  next state {store: {…}, item: {…}, section: {…}, person: {…}, seller: {…}, …}
`

**Comment by ljones87** [comment]
@waleedbk Were you able to fix this? I have the same issue. When I hit 'add member' it de-registers members[0] and registers members[1] and when I type in one field it types in all fields with same .name

**Comment by waleedbk** [comment]
@ljones87 yes i had fixed this. I just putted all the functions outside the render method and it worked fine. When you add something in an array field, render() method just try to re-render everything so that's why you've to put your method that is used for arrayField outside from it.
