### ISSUE TITLE
Allow access to WrappedComponent

### ISSUE THREAD

**Issue by NullDivision** [erikras/redux-form#3503]
For a while now it's been standard practice to have the WrappedComponent static as part of HOCs. This doesn't seem to be the case. From what I can see the `Form` component that contains the wrapped component is nested inside a `ReduxForm` component.

It would be really nice to have this as part of the export statics.

**Comment by gustavohenke** [comment]
You *can* do this.

- For `reduxForm()` decorator, use [`wrappedInstance`](https://redux-form.com/7.1.1/docs/api/reduxform.md/#-code-wrappedinstance-reactelement-code-);
- For `<Field>`, `<FieldArray>`, `<Fields>` components, [use the `withRef` prop together with the `getRenderedComponent()` method](https://redux-form.com/7.1.1/docs/api/field.md/#-code-withref-boolean-code-optional-).

**Comment by NullDivision** [comment]
As far as I know you actually have to render the form to get `wrappedInstance`. I need it without instancing.

**Comment by gustavohenke** [comment]
@erikras - what do you think?
