### ISSUE TITLE
Can't use with React-Native 4.8.+

### ISSUE THREAD

**Issue by LouisJS** [erikras/redux-form#3505]
### What is the current behavior?

Can't setup a project using React 16.0.0, React-Native 0.49.0 and Redux Form 7.x.x
using react-native CLI

### What is the expected behavior?

https://redux-form.com/7.1.1/docs/faq/reactnative.md/
https://esbenp.github.io/2017/01/06/react-native-redux-form-immutable-styled-components/

The project of @esbenp is deprecated and so is your documentation then.
I haven't seen any single project coupling the dependencies at these versions work.

### What's your environment?

Environment:
  OS:  macOS Sierra 10.12.6
  Node:  8.3.0
  Yarn:  1.1.0
  npm:  4.6.1
  Watchman:  4.9.0
  Xcode:  Xcode 9.0 Build version 9A235
  Android Studio:  2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0-beta.5 => 16.0.0-beta.5
  react-native: 0.49.1 => 0.49.1

### Other information

https://stackoverflow.com/questions/46664693/redux-form-doesnt-work-with-react-native

Any response, snippet or suggestions is welcome.

**Comment by blindbox** [comment]
@LouisJS 
Did you manage to solve it? I noticed that you're using `onChange={props.input.onChange}` but the guide wants you to use `onChangeText={props.input.onChange}`.
