### ISSUE TITLE
Values not being passed to reduxForm decorated component

### ISSUE THREAD

**Issue by dobryanskyy** [erikras/redux-form#3513]
### Are you submitting a **bug report** or a **feature request**?

bug report

### What is the current behavior?

values is not passed to decorated component

### What is the expected behavior?
According to https://redux-form.com/7.1.1/docs/api/reduxform.md/#instance-api values should be passed to decorated component

**Comment by gustavohenke** [comment]
Hi @dobryanskyy, you understood the instance API incorrectly.
Please see this amazing explanation: https://github.com/erikras/redux-form/issues/2101#issuecomment-261253199

**Comment by dobryanskyy** [comment]
Thanks for explanation.
