### ISSUE TITLE
blur unexpectedly changes values because input.OnBlur uses context wrong way

### ISSUE THREAD

**Issue by adambisek** [erikras/redux-form#3517]
Using node v6.9.1, redux-form 7.1.1, React 16, webpack 3.

**Current behaviour:**
This code does not work properly, cause onBlur has **wrong context and it causes redux action "blur", that modifies form values**:
```
export const InputDateRenderer = (
  {input: {onChange, onBlur, ...rest},
) => {
  return (
    <DateInput
      {...rest}
      onBlur={onBlur}
      onChange={e => console.log("hi")}
    />
  )
}
```
-> produces this redux action:
```
meta: {form: "exchangeRatesFilter", field: "date", touch: true}
payload:Moment {_isAMomentObject: true, _i: Fri Oct 13 2017 14:06:07 GMT+0200 (CEST), _strict: true, _isUTC: false, _pf: {…}, …}
type:"@@redux-form/BLUR"
```

**This works great, cause arrow function applies the right context:**
```
export const InputDateRenderer = (
  {input: {onChange, onBlur, ...rest},
) => {
  return (
    <DateInput
      {...rest}
      onBlur={() => onBlur()}
      onChange={e => console.log("hi")}
    />
  )
}
```
-> produces this redux action:
```
meta: {form: "exchangeRatesFilter", field: "date", touch: true}
payload: undefined
type:"@@redux-form/BLUR"
```

**Expected behaviour:**
This should work properly if onBlur function would be properly bound.
```
export const InputDateRenderer = (
  {input: {onChange, onBlur, ...rest},
) => {
  return (
    <DateInput
      {...rest}
      onBlur={onBlur}
      onChange={e => console.log("ahoj")}
    />
  )
}
```

**Comment by gustavohenke** [comment]
It *is* expected behaviour. It's documented [here](https://redux-form.com/7.1.1/docs/api/field.md/#-code-onblur-event-newvalue-previousvalue-gt-void-code-optional-) and [here](https://redux-form.com/7.1.1/docs/api/field.md/#-code-input-onblur-eventorvalue-function-code-).

Calling `onBlur` the way you demonstrated is likely changing the input's value to `undefined`, or something else 🤔

**Comment by adambisek** [comment]
Well, this is renderer is used with react-datetime, maybe there is the cause.
