### ISSUE TITLE
No values obtained from fields

### ISSUE THREAD

**Issue by stackninigi** [erikras/redux-form#3518]
Hi! I'm getting started with redux-forms. I have an issue.

**My issue:** using basic example I was able to get redux-form displayed. But in my `submit` function I'm making a `console.log` to check if values which I typed are passed. And when I click `submit` button all seems to work fine - I see in Redux `redux-form/TOUCH` and `redux-form/SET-SUBMIT-SUCCESS`. The issue is that no values are logged, jut an empty object. 

**redux**: 3.7.2
**redux-form**: 7.1.0

Code:
```
import React, {Component} from 'react';
import PropTypes from 'prop-types';
import {reduxForm} from 'redux-form';

class LoginForm extends Component {
    submit = (values) => {
        console.log('submit inside form');
        console.log(values);
    };

    render() {
        const {fields: {firstName, lastName, email}} = this.props;
        return (
            <form onSubmit={this.props.handleSubmit(this.submit)}>
                <div>
                    <label>First Name</label>
                    <input type="text" placeholder="First Name" {...firstName}/>
                </div>
                <div>
                    <label>Last Name</label>
                    <input type="text" placeholder="Last Name" {...lastName}/>
                </div>
                <div>
                    <label>Email</label>
                    <input type="email" placeholder="Email" {...email}/>
                </div>
                <button type="submit">Submit</button>
            </form>
        );
    }
}

LoginForm = reduxForm({
    form: 'login',
    fields: ['firstName', 'lastName', 'email']
})(LoginForm);
export default LoginForm;
```

**Comment by gustavohenke** [comment]
Hi @stackninigi, you're using Redux Form just like you would on v5 and previous versions, but using v6+. Redux Form v6+ doesn't take a `fields` configuration.

Please see the examples of your version here:
https://redux-form.com/7.1.0/examples

In case you still need help with these, please ask on StackOverflow.
