### ISSUE TITLE
First input change loose focus when bundling with NODE_ENV = production (with webpack.DefinePlugin)

### ISSUE THREAD

**Issue by rina-andria** [erikras/redux-form#3519]
Hello,
When rerendering the form after submit:
- in DEV environment, the form is working when editing back the input => the following events FOCUS, CHANGE occurs
- in STAGING environment , the code is bundled with webpack (setting NODE_ENV = production), i got the following events FOCUS, CHANGE, INITIALIZE => i dont know why the additional INITIALIZE is raised.

The only difference is the fact the code is bundled or not.

Anyone has an idea where could the issue come from OR has encountered the same issue?

Config:
react-redux - 4.4.6
redux-form - 7.1.1
redux-form-material-ui - 4.3.0
react - 15.4.2

Thanks,

**Comment by gustavohenke** [comment]
Can you please provide a reproduction repository (including the build steps)?

**Comment by rina-andria** [comment]
hi @gustavohenke. sorry for the late reply. i tried to build up a repository with th ereproduction of the issue but could not manage. i tried to reproduce with the sample provided here https://github.com/erikras/redux-form-material-ui/tree/master/example without success.
just for the submit, i have an action creator with a POST Rest API call.
Just wondering if there is a place in redux-form which is dependant to the NODE_ENV ?

**Comment by rina-andria** [comment]
Nevermind @gustavohenke , it was my bad. I had another action creator that causes rerendering.
This though I dont know why it worked with 'development' but not 'production'. Will check on my side...
Thanks
