### ISSUE TITLE
How to validate deep forms

### ISSUE THREAD

**Issue by webmasterkai** [erikras/redux-form#352]
If validation fails, it should return the validation errors in the form `{ "field1": <String> }`. What about deep forms? Should it be `{ "field1.foo": <String> }` or `{ "field1": { "foo": <String> } }`?

**Comment by erikras** [comment]
The latter. The errors should be deep.

I added sync validation to the [Deep Example](http://erikras.github.io/redux-form/#/examples/deep), but didn't have time to format the errors, so they are just `title` attributes.

**Comment by webmasterkai** [comment]
If it's an error on a specific item in an array, should I include null values for the array items that do not have errors?

**Comment by erikras** [comment]
`undefined` is probably more accurate, but `null` might work.
