### ISSUE TITLE
touched works only when lost focus, example in web is wrong

### ISSUE THREAD

**Issue by webmobiles** [erikras/redux-form#3524]
'touched' is true only when i've lost the focus, that is very bad, the example does not work well , because while you are typing if you don't lost the focus you never will realize there are errors. 
here the code in 

```
const renderField = ({
  input,
  label,
  type,
  meta: { touched, error, warning }
}) =>
  <div>
    <label>
      {label}
    </label>
    <div>
      <input {...input} placeholder={label} type={type} />
      {touched &&
        ((error &&
          <span>
            {error}
          </span>) ||
          (warning &&
            <span>
              {warning}
            </span>))}
    </div>
  </div>
```
my render Field has:

`      { touched && <span>Touched</span> }`

but give no "touched" in true when I type one letter:
<img width="433" alt="screen shot 2017-10-15 at 08 41 50" src="https://user-images.githubusercontent.com/21120559/31582491-c41292a4-b184-11e7-9e9a-d0aed1fd59e6.png">

when i move to another field, touched is ok, but it's too late:
<img width="423" alt="screen shot 2017-10-15 at 08 43 14" src="https://user-images.githubusercontent.com/21120559/31582499-eddb96d0-b184-11e7-9c81-7a07addefe87.png">
 

all in reac system works better than angular 4, just the forms are the problems, in angular4 is very clean, validators, errors,etc. that is pity.

Here how works in angular 4:

![angular4-control-state-transitions-anim](https://user-images.githubusercontent.com/21120559/31582480-6cd60034-b184-11e7-85be-59631535a3d3.gif)

ng-touched: Control has been visited
ng-untouched: Control has not been visited
ng-dirty: Control's value has been changed
ng-pristine: Control's value hasn't been changed
ng-valid: Control's value is valid
ng-invalid: Control's value isn't valid

Same for form
```
        <Button type="submit" disabled={invalid || submitting} primary >
          {t('form.submit')}
        </Button>
```
on the example if you type nothing and try to submit,  button will never be disabled because 'invalid' is false, i did not understand very this logic, need to enter every field to get errors in the submit action or i'm doing something wrong ?

**Comment by gustavohenke** [comment]
> the example does not work well , because while you are typing if you don't lost the focus you never will realize there are errors.

This is subjective. If you don't like the example... then don't write your apps like that!

> on the example if you type nothing and try to submit, button will never be disabled because 'invalid' is false

I don't know which example you're using.
I assumed it was the [sync validation example](https://redux-form.com/7.1.1/examples/syncvalidation/), which doesn't even have such code in the `disabled` prop.

Anyway, the `invalid` prop seems to work though. I extended the above example to show it working:
https://codesandbox.io/s/y07m42vqwx

**Comment by webmobiles** [comment]
thanks for your example, it's working well and the form is not submitted same if  delete invalid  in:

 `      <button type="submit" disabled={invalid || submitting}>Submit</button>
 `
that is what looking for, that submit don't send data if there are errors, and show the errors when I visit the fields or try to do submit.

I took this example to write my form: (really i was just needing to test any form with redux-form, so by the moment don't need be sync) 

https://redux-form.com/7.0.4/examples/fieldlevelvalidation/

in that example there is no 'validata':
```
export default reduxForm({
  form: 'fieldLevelValidation' // a unique identifier for this form
})(FieldLevelValidationForm)
```


like in your example:

```
export default reduxForm({
  form: 'syncValidation',  // a unique identifier for this form
  validate,                // <--- validation function given to redux-form
  warn                     // <--- warning function given to redux-form
})(SyncValidationForm)


```
so for validate my form how i need, the example I took is the wrong for my case? need 'validate' to get errors when I try to submit ? thanks
