### ISSUE TITLE
FAQ section on how to use redux-connect is wrong.

### ISSUE THREAD

**Issue by Stralos** [erikras/redux-form#3525]
### Are you submitting a **bug report** or a **feature request**?
Documentation bug.

### What is the current behavior?
A FAQ station in redux-form for using connect with the form, has a code example that shows how to use the connect functionality: 

```
...
Example = connect(
    mapStateToProps,
    mapDispatchToProps
)(Example);

export default reduxForm({
    form: 'example' // a unique name for this form
})(Example);
...
```
link: https://redux-form.com/7.1.1/docs/faq/howtoconnect.md/

While in your example for using `initializefromstate` the using connect wrapper is done differently 
```
InitializeFromStateForm = reduxForm({
  form: 'initializeFromState' // a unique identifier for this form
})(InitializeFromStateForm)

// You have to connect() to any reducers that you wish to connect to yourself
InitializeFromStateForm = connect(
  state => ({
    initialValues: state.account.data // pull initial values from account reducer
  }),
  { load: loadAccount } // bind account loading action creator
)(InitializeFromStateForm)

export default InitializeFromStateForm
```

### What is the expected behavior?
The correct way should be firstly wrapping your component in reduxForm wrapper and then pass it to the connect function. The example given in FAQ will not work.

**Comment by gustavohenke** [comment]
Well, this is quite subjective, not a bug. Check the discussion on #3424 for some explanation.
