### ISSUE TITLE
Select elements must be either controlled or uncontrolled. Error

### ISSUE THREAD

**Issue by waleedbk** [erikras/redux-form#3526]
I am struggling from last two weeks and didn't found any solution yet. I have a form in which i'm initializing states customly by calling componentDidMount() please see the code below. And also if i uncomment  this (//storeReceivedForm: store.form.storeReceived,) my form doesn't work properly. 

`
import React from 'react'
import { connect } from "react-redux"
import { Field, FieldArray, reduxForm } from 'redux-form'
import validate from './validate'
import { Button, Grid, Row, Col, Icon, Modal, Table, Tr, Td, Input } from "react-materialize";
import * as storeActions from "../actions/storeActions";
import { renderField } from "./FormConfig";
import { Link } from "react-router";

@connect((store) => {
  return {
    //storeReceivedForm: store.form.storeReceived,
   sellers: store.storeReceived.sellers,
    items: store.storeReceived.items,
    person: store.store.person,
  }
})

class StoreReceived extends React.Component {
  componentDidMount() {
    console.log("component will mount");
    this.props.dispatch(storeActions.fetchStoreReceived());
  }

  createStoreReceived(values){
    const data = values;
    this.props.dispatch(storeActions.createStoreReceived(data));
    console.log(data);
    this.props.reset();
  }

  render () {
    const { handleSubmit, pristine, reset, submitting, sellers, person, items } = this.props
    const renderSeller = sellers.map((item, index) => {
      return(
        <option key={index} value={item.id}>{item.name} - {item.type}</option>
      )
    });
    const renderSellerField = ({ input, label, type, meta: { touched, error } }) =>
      <Input defaultValue="" s={6} {...input} type={type} label={label} error={touched && error}>
        <option value="" disabled>Choose seller</option>
        {renderSeller}
      </Input>

    const renderPerson = person.map((item, index) => {
      return(
        <option key={index} value={item.name}>{item.name}</option>
      )
    });
    const renderPersonField = ({ input, label, type, meta: { touched, error } }) =>
      <Input s={6} {...input} type={type} label={label} error={touched && error}>
        <option value="" disabled>Choose Item</option>
        {renderPerson}
      </Input>

    const renderItem = items.map((item, index) => {
      return(
        <option key={index} value={item.id}>{item.name}</option>
      )
    });
    const renderItemField = ({ input, label, type, meta: { touched, error } }) =>
      <Input s={3} {...input} type={type} label={label} error={touched && error}>
        <option value="" disabled>Choose Item</option>
        {renderItem}
      </Input>

    const renderItems = ({ fields, meta: { error, submitFailed } }) =>
      <div>
        {fields.map((item, index) =>
          <div key={index}>
            <Field
              name={`${item}.item`}
              type="select"
              component={renderItemField}
              label="Item"
            />
            <Field
              name={`${item}.accountingUnit`}
              type="select"
              component={({ input, label, type, meta: { touched, error } }) =>
                <Input s={2} {...input} type={type} label={label} error={touched && error} onselect={(event) => this.checkNos(event)}>
                  <option value="" disabled>Choose AU</option>
                  <option value="weight">Weight</option>
                  <option value="volume">Volume</option>
                  <option value="nos">Nos</option>
                </Input>
              }
              label="Accounting Unit"
            />
            <Field
              name={`${item}.quantity`}
              type="number"
              parse={(value) => (parseInt(value))}
              component={renderField}
              label="Qunatity"
            />
            <Field
              name={`${item}.rate`}
              type="number"
              parse={(value) => (parseInt(value))}
              component={renderField}
              label="Rate"
            />
            <Field
              name={`${item}.cost`}
              type="number"
              parse={(value) => (parseInt(value))}
              component={renderField}
              label="Cost"
            />
            <Col s={1}>
              <Button type="button" floating small style={{top: '20px'}} className="red center" waves="light" icon="remove" onClick={() => fields.remove(index)} />
            </Col>
          </div>
        )}
        <Col s={12}>
          <Button type="button" floating small className="light-blue accent-3 center" waves="light" icon="add" onClick={() => fields.push({})} s={2} />
        </Col>
        {
          submitFailed &&
          error &&
          <span className="red-text">
            {error}
          </span>
        }
      </div>

      return (
        <Row>
          <Col s={12} className="z-depth-1">
            <div s={12}>
              <h5 className="center-align">Store Received</h5>
              <Link to="storereceived/history" className="right">View History</Link>
            </div>
            <Row></Row>
            <form onSubmit={handleSubmit(this.createStoreReceived)}>
              <Row className="center-align">
                <Field
                  name="seller"
                  type="select"
                  component={renderSellerField}
                  label="Seller"
                />
                <Field
                  name="payment"
                  type="select"
                  component={({ input, label, type, meta: {touched, error} }) =>
                  <Input s={3} {...input} type={type} label={label} error={touched && error}>
                  <option value="" disabled>Choose Payment</option>
                    <option value="cash">Cash</option>
                    <option value="credit">Credit</option>
                  </Input>
                }
                  label="Payment"
                />
                <Field
                  name="invoiceNumber"
                  type="text"
                  component={({ input, label, type, meta: {touched, error} }) =>
                  <Input s={3} disabled {...input} type={type} label={label} error={touched && error}/>
                }
                  label="Invoice No"
                />
                <FieldArray name="items" component={renderItems} />
                <Col s={12} >
                  <Button type="submit" medium className="right light-blue accent-3" waves="light" s={2}>Create</Button>
                </Col>
              </Row>
            </form>
          </Col>
        </Row>
      )
    }
}
export default reduxForm({
  form: 'storeReceived', // a unique identifier for this form
  validate
})(StoreReceived)

`
My form field losing his focus and in my console i'm getting (unregister and register field)

@erikras @sholden  Please help me to solve this issue it's too important for me. I've just started working on react-redux  this year so please don't mind if i'm doing something wrong with react and redux. thanks!

**Comment by gustavohenke** [comment]
Please use StackOverflow for usage support.
