### ISSUE TITLE
`array` convenience prop not getting added to `propNamespace`

### ISSUE THREAD

**Issue by jeremyosborne-xactly** [erikras/redux-form#3529]
### Are you submitting a **bug report** or a **feature request**?
bug report

### What is the current behavior?
the `array` property that provides bound actions for working with FieldArrays does not get added to the`propNamespace` object if declared.

### What is the expected behavior?
If I use `propNamespace: 'reduxForm',` in my `reduxForm` decorator, I should be able to access `this.props.reduxForm.array` like i can with other correctly namespaced props, but instead I need to use `this.props.array` (e.g. `this.props.array.push({...some data});`).

### Sandbox Link
see: https://codesandbox.io/s/045x946yj0 in the SimpleForm.js file

### What's your environment?
Sandbox uses 7.0.4, app uses 6.7.0. Behavior seems same in sandbox version and my app.

**Comment by gustavohenke** [comment]
Thanks for the report!

**Comment by erikras** [comment]
This should be an easy PR for newbies.

**Comment by vnctaing** [comment]
I've been trying to investigate and open my first PR, but I haven't been lucky so far. I've looked into [createReduxForm](https://github.com/erikras/redux-form/blob/master/src/createReduxForm.js#L842-L846) file, it seems correctly passing the propNameSpace and I also looked into the passing [test](https://github.com/erikras/redux-form/blob/master/src/__tests__/reduxForm.spec.js#L426-L430) that looks also fine to me, does anyone has thought on where the problem could come from ?

**Comment by gustavohenke** [comment]
@vnctaing that test is not checking whether `array` is there.
If you add a expectation for this, it will likely break the test.
