### ISSUE TITLE
ConnectedFieldArray.js uses "includes" which is unsupported in IE11

### ISSUE THREAD

**Issue by andokai** [erikras/redux-form#3533]
### What is the current behavior?

IE11 blows up when visiting a form that uses a FieldArray

### What is the expected behavior?
IE11 shouldn't blow up

### What's your environment?

Form v7.1.1
IE11

### Other information

`TypeError: Object doesn't support property or method 'includes'`

**Comment by andokai** [comment]
Swapping in `thisValue.indexOf(val) !== -1` for `thisValue.includes(val)` and IE11 no longer blows up.

**Comment by gustavohenke** [comment]
Thanks for the report! Would you like to send a PR to fix this?

**Comment by andokai** [comment]
Will do it tomorrow, cheers!

**Comment by erikras** [comment]
Fix published in [`v7.1.2`](https://github.com/erikras/redux-form/releases/tag/v7.1.2).
