### ISSUE TITLE
Form is removed from state when leaving the page.

### ISSUE THREAD

**Issue by mustafamamun** [erikras/redux-form#3534]
I have a form for customer complain. I want it to work in such way so that the user can fill up some filed and navigate to other tab and come back and recover the last state of the form. However now the form is getting removed from the redux state when user navigate to other tab.

My code is as follows `export default reduxForm({form: 'new_complain', destroyOnUnmount: false})(ComplainNew);`
What I am missing?

Redux form version 7.04

**Comment by gustavohenke** [comment]
It's difficult to know what's wrong with your form without seeing it in action.

Can you please provide a sandbox showcasing your issue?
You might want to use [this CodeSandbox template](https://codesandbox.io/s/gJjDoKYWl).

**Comment by gustavohenke** [comment]
Closing due to no response.

**Comment by mustafamamun** [comment]
Sorry for not answering in time. The  form was declared in two place my mistake. Thats why it was behaving that way. Its not a bug in Redux form.
