### ISSUE TITLE
Normalize mask

### ISSUE THREAD

**Issue by vladhd93** [erikras/redux-form#3536]
Hello, thanks for great product !!!
 i have question, how  i can do mask for input with normalizing ? 
for example i nee to add thousand separator to input type number, but i redux-store i don't need this dots in number.
example - i put value 60000 to input, in input it shows as 60.000, but in store i have 60000.
Thanks

**Comment by gustavohenke** [comment]
Please use StackOverflow for usage support.

**Comment by vladhd93** [comment]
do you have any link for some branch on stackoverflow that according to redux-form ?

**Comment by bertho-zero** [comment]
https://stackoverflow.com/questions/tagged/redux-form
