### ISSUE TITLE
isPristine date test confusion

### ISSUE THREAD

**Issue by joshgagnon** [erikras/redux-form#354]
In isPristine.spec.js, there is 
    `const date1 = new Date();`
   `const date2 = new Date(date1.getDate());`

But getDate returns the day of the month, and as it is the first of December here, this sets the time to 1ms past epoch for BOTH dates, failing the test.

Shouldn't the test do 
   `tryBothWays({date: date1}, {date: date2}, true);`
once this is fixed?

I can add a pull request.

**Comment by erikras** [comment]
Ahahaha!!! That's hilarious. I love Y2K-style date manipulation bugs. I'll get it.

**Comment by erikras** [comment]
https://github.com/erikras/redux-form/commit/b88386434d56b663601131c9e7e2896b6e1781b6
