### ISSUE TITLE
BUG - onSubmitFail props do not follow formatting of onSubmitSuccess

### ISSUE THREAD

**Issue by patientplatypus** [erikras/redux-form#3543]
So very simply if I have the following

```
onSubmitSuccess: (result, dispatch, props) => {
  console.log("props: ", props); 
},
```

It will work correctly and output props. However if I have 

```
onSubmitFail: (result, dispatch, props) => {
  console.log("props: ", props); 
},
```

props is undefined. 

Is there documentation on this? If the syntax is indeed different it should probably be changed to reflect the intuitive approach one would expect. 

Thanks.

**Comment by gustavohenke** [comment]
Yes, the docs exist:
- [`onSubmitSuccess`](https://redux-form.com/7.1.1/docs/api/reduxform.md/#-code-onsubmitsuccess-function-code-optional-)
- [`onSubmitFail`](https://redux-form.com/7.1.1/docs/api/reduxform.md/#-code-onsubmitfail-function-code-optional-)
