### ISSUE TITLE
babel-jest being added as dependency in 7.1.1

### ISSUE THREAD

**Issue by brucewpaul** [erikras/redux-form#3546]
### Are you submitting a **bug report** or a **feature request**?
bug report

### What is the current behavior?
babel-jest is a dependency in 7.1.1

### What is the expected behavior?
babel-jest should be a devDep

it seems updated in the repo, but in the release, it's a dependency in the release

**Comment by lencioni** [comment]
Duplicate? https://github.com/erikras/redux-form/issues/3498

**Comment by brucewpaul** [comment]
yup, leaving open until a release

**Comment by brucewpaul** [comment]
going to leave this open until a new release

**Comment by carlosrberto** [comment]
this dependency is breaking my tests environment!
please publish a new release without this

**Comment by erikras** [comment]
Fix published in [`v7.1.2`](https://github.com/erikras/redux-form/releases/tag/v7.1.2).
