### ISSUE TITLE
Normalization of nested fields

### ISSUE THREAD

**Issue by joshgagnon** [erikras/redux-form#355]
Are there any plans to implement normalization of nested fields?  I'm currently using a very hacky custom implementation of nested forms where each subform is formKeyed with a path, but it means that normalization can occur as normal.  I would prefer to migrate over to the new style, but would like to be able to normalize a field of arbitrary depth concisely.

**Comment by erikras** [comment]
I might be misunderstanding you, but it should "just work". The values passed to your normalizer should be the proper "deep" values from the form, which should allow you to reuse normalizer code for similar parts of your data tree.

**Comment by joshgagnon** [comment]
Oh great, will have a play.

**Comment by trashgenerator** [comment]
Seems it doesn't work or I didn't get how to use it.
For example I have a form:
```
export default reduxForm({
    form: 'MyForm',
    fields: [
       'nestedFieldParent.nestedFieldChild',
    ],
  }
)(MyComponent);
```
I want `nestedFieldChild` to be normalized.
I'm trying those reducer but normalization function is not called correctly:
```
export default combineReducers({
  form: formReducer.normalize({
    MyForm: {
      'nestedFieldParent.nestedFieldChild': value => 'normalized'
    },
  }),
});
```
