### ISSUE TITLE
Endless Loop when Field's component throws an error 

### ISSUE THREAD

**Issue by TMaszko** [erikras/redux-form#3550]
### Are you submitting a **bug report** or a **feature request**?

bug
### What is the current behavior?

https://www.webpackbin.com/bins/-KwyQxBsNZTetkk26LUk

### What is the expected behavior?
No endless loop
Component should throw error  from render and stop executction

### What's your environment?

redux-form 7.1.1/chrome node 8.6.0

### Other information
 all is in the webpack bin

**Comment by gustavohenke** [comment]
~1.5 years without a comment here, so I'm closing!
If the issue persists, please open a new one while still providing as much context as possible. Thanks!
