### ISSUE TITLE
7.1.1 material ui example doesn't load (endless spinner)

### ISSUE THREAD

**Issue by ask007learning** [erikras/redux-form#3557]
### Are you submitting a **bug report** or a **feature request**?

bug report

### What is the current behavior?

https://redux-form.com/7.1.1/examples/material-ui/

### What is the expected behavior?
https://redux-form.com/7.1.1/examples/material-ui/

### Sandbox Link

https://redux-form.com/7.1.1/examples/material-ui/

### What's your environment?

7.1.1

**Comment by erikras** [comment]
Yeah, this was fixed, but only [in the 7.1.2 docs](https://redux-form.com/7.1.2/examples/material-ui/). Going back to re-publish the fix to 7.1.1 would be more trouble than I think it's worth.
