### ISSUE TITLE
Touch isn't being called on deep form fields.

### ISSUE THREAD

**Issue by joearasin** [erikras/redux-form#357]
When I attempt to submit a form, the deep fields are not being touched as part of the submission/validation.

**Comment by joearasin** [comment]
Here's the failing case: https://github.com/joearasin/redux-form/tree/nestedTouch

**Comment by joearasin** [comment]
```
  it('should mark nested fields touched on touch', () => {
    const state = reducer({
      foo: {
        myField: {
          mySubField: {
            value: 'initialValue'
          }
        },
        myOtherField: {
          value: 'otherInitialValue',
          touched: true
        },
        _active: 'myOtherField',
        _asyncValidating: false,
        _error: undefined,
        _submitting: false,
        _submitFailed: false
      }
    }, {
      ...touch('myField.mySubField'),
      form: 'foo'
    });
    expect(state.foo)
      .toEqual({
        myField: {
          mySubField: {
            value: 'initialValue',
            touched: true
          }
        },
        myOtherField: {
          value: 'otherInitialValue',
          touched: true
        },
        _active: 'myOtherField',
        _asyncValidating: false,
        _error: undefined,
        _submitting: false,
        _submitFailed: false
      });
  });
```

**Comment by joearasin** [comment]
Test output:

```Diff
      + expected - actual

         "_submitFailed": false
         "_submitting": false
         "myField": {
           "mySubField": {
      +      "touched": true
             "value": "initialValue"
           }
         }
      -  "myField.mySubField": {
      -    "touched": true
      -  }
         "myOtherField": {
           "touched": true
           "value": "otherInitialValue"
         }
```

**Comment by szymonmichalak** [comment]
+1 I have the same problem.

I tested my code (calling `this.props.touchAll()`) on simple, not-nested field and it works fine. Yet, fields that are nested are not touched.

**Comment by erikras** [comment]
:see_no_evil: I apologize for overlooking this action. Fix on the way shortly.

**Comment by erikras** [comment]
Published fix under `v3.1.6`.

**Comment by szymonmichalak** [comment]
Works fantastic! Thanks @erikras :+1:

**Comment by hnordt** [comment]
Same problem here even after upgrading to v3.1.6

**Comment by hnordt** [comment]
@erikras 

![captura_de_tela_120115_061004_pm](https://cloud.githubusercontent.com/assets/1625399/11512727/b4511d5c-9856-11e5-95b9-dd0f1fd76add.jpg)

**Comment by hnordt** [comment]
@erikras 

![captura_de_tela_120115_061236_pm](https://cloud.githubusercontent.com/assets/1625399/11512797/0e6c7b4c-9857-11e5-82eb-c264eda3249c.jpg)

**Comment by hnordt** [comment]
@joearasin 

For me it's working only after BLUR, if I don't touch any field and submit, the touch doesn't happens for deep fields even after v3.1.6.

**Comment by joearasin** [comment]
For me, the don't touch and submit didn't work in 3.1.5 and does work in 3.1.6. But my test case was nested-in-an-object, not nested-in-an-array.
