### ISSUE TITLE
Fields losing focus on change, Form Re-Registering fields. whats wronge with the code?

### ISSUE THREAD

**Issue by waleedbk** [erikras/redux-form#3572]
@erikras  please don't close this issue i'm trying to solve this from past month and didn't get any solution and you're my last hope please take a look at code please. It's too important for me. I tried stackoverflow but no one is answering me. thanks!
Also i'm getting this warning 
`warning.js:35 Warning: Input contains an input of type text with both value and defaultValue props. Input elements must be either controlled or uncontrolled (specify either the value prop, or the defaultValue prop, but not both). Decide between using a controlled or uncontrolled input element and remove one of these props`
is this is the issue my form gets out of focus after onChange?
`
<pre>
import React from 'react'
import { connect } from "react-redux"
import { Link } from "react-router";
import { Field, FieldArray, reduxForm } from 'redux-form'
import validate from './validate'
import { Button, Grid, Row, Col, Icon, Modal, Table, Tr, Td, Input } from "react-materialize";
import * as storeActions from "../actions/storeActions";

@connect((store) => {
  return {
    // storeDemandForm: store.form.storeDemand, // if i comment this form will stop working why?
    section: store.store.section,
    person: store.store.person,
    items: store.store.items,
  }
})

class StoreDemand extends React.Component {

  constructor(props) {
    super(props);
  }

  componentDidMount() {
    console.log("component will mount");
    this.props.dispatch(storeActions.fetchStoreDemand());
  }

  createDemand = (values) => {
    this.props.dispatch(storeActions.createStoreDemand(values));
    this.props.reset();
  }

  render () {
    const { handleSubmit, pristine, reset, submitting, section, person, items } = this.props  </pre>

    const renderField = ({ input, label, type, meta: { touched, error } }) =>
      <Input s={2} type={type} {...input} label={label} error={touched && error} />

    const renderSection = section.map((item, index) => {
      return(
        <option key={index} value={item.id}>{item.name}</option>
      )
    });
    const renderSectionField = ({ input, label, type, meta: { touched, error } }) =>
      <Input s={6} {...input} type={type} label={label} error={touched && error}>
        <option value="" disabled>Choose section</option>
        {renderSection}
      </Input>

    const renderPerson = person.map((item, index) => {
      return(
        <option key={index} value={item.id}>{item.name}</option>
      )
    });
    const renderPersonField = ({ input, label, type, meta: { touched, error } }) =>
      <Input s={6} {...input} type={type} label={label} error={touched && error}>
        <option value="" disabled>Choose Person</option>
        {renderPerson}
      </Input>

    const renderItem = items.map((item, index) => {
      return(
        <option key={index} value={item.id}>{item.name}</option>
      )
    });
    const renderItemField = ({ input, label, type, meta: { touched, error } }) =>
      <Input s={3} {...input} type={type} label={label} error={touched && error}>
        <option value="" disabled>Choose Item</option>
        {renderItem}
      </Input>

    const renderItems = ({ fields, meta: { error, submitFailed } }) =>
      <div>
        {fields.map((item, index) =>
          <div key={index}>
            <Field
              name={`${item}.item`}
              type="select"
              component={renderItemField}
              label="Item"
            />
            <Field
              name={`${item}.accountingUnit`}
              type="select"
              component={({ input, label, type, meta: { touched, error } }) =>
                <Input s={2} {...input} type={type} label={label} error={touched && error}>
                  <option value="" disabled>Choose AU</option>
                  <option value="weight">Weight</option>
                  <option value="volume">Volume</option>
                  <Button waves="light" value="Nos" onClick={() => fields.push({})} s={2} />
                </Input>
              }
              label="Accounting Unit"
            />
            <Field
              name={`${item}.quantity`}
              type="number"
              component={renderField}
              parse={(value) => (parseInt(value))}
              label="Quantity"
            />
            <Field
              name={`${item}.rate`}
              type="number"
              component={renderField}
              parse={(value) => (parseInt(value))}
              label="Rate"
            />
            <Field
              name={`${item}.cost`}
              type="number"
              component={({ input, label, type, meta: { touched, error } }) =>
                <Input s={2} {...input} type={type} label={label} error={touched && error} />
              }
              parse={(value) => (parseInt(value))}
              label="Cost"
            />
            <Col s={1}>
              <Button floating small style={{top: '20px'}} className="red center" waves="light" icon="remove" onClick={() => fields.remove(index)} />
            </Col>
          </div>
        )}
        <Col s={12}>
          <Button type="button" floating small className="light-blue accent-3 center" waves="light" icon="add" onClick={() => fields.push()} s={2} />
        </Col>
        {
          submitFailed &&
          error &&
          <span className="red-text">
            {error}
          </span>
        }
      </div>

      return (
        <Row>
          <Col s={12} className="z-depth-1">
            <div>
              <h5 className="center-align">Store Demand</h5>
              <Link to="/storedemand/history" className="right">View History</Link>
            </div>
            <Row></Row>
            <form onSubmit={handleSubmit(this.createDemand)}>
              <Row className="center-align">
                <Field
                  name="section"
                  type="select"
                  component={renderSectionField}
                  label="Section"
                />
                <Field
                  name="person"
                  type="select"
                  component={renderPersonField}
                  label="Person"
                />
                <FieldArray name="items" component={renderItems} />
                <Col s={12} >
                  <Button type="submit" medium className="right light-blue accent-3" waves="light" s={2}>Create</Button>
                </Col>
              </Row>
            </form>
          </Col>
        </Row>
      )
    }
}
//
export default reduxForm({
  form: 'storeDemand', // a unique identifier for this form
  validate
})(StoreDemand)
</pre>
`

**Comment by waleedbk** [comment]
Just putted all the initialization outside the render method and it worked!

**Comment by chaddjohnson** [comment]
@waleedbk Confirmed. Moving initialization outside the `render()` method worked for me as well.
