### ISSUE TITLE
Last Field inside form disappears when submitting

### ISSUE THREAD

**Issue by Jahans3** [erikras/redux-form#3574]
Hi, firstly thanks for the great library. It really helps. I however have an issue with Fields disappearing.

### Are you submitting a **bug report** or a **feature request**?
Bug report

### What is the current behavior?
Tested on versions 6.5.0 and 7.1.2. When I submit a form, the last Field in the form disappears from the screen. If the validation fails and the user has to return to the page they are unable to amend the values as the Field will not rerender.

### What is the expected behavior?
When the form is submitted, the Fields do not derender.

### Sandbox Link
I am unfortunately unable to replicate this in one of the example sandboxes.

### What's your environment?
redux-form v6.5.0 and v7.1.2, react-native 0.44.2, problem mostly seems to happen on slower Android devices.

**Comment by gustavohenke** [comment]
This seems a lot like some custom behaviour of your own form, and you can't replicate, there's not much we can do about it atm.

**Comment by Jahans3** [comment]
The behaviour only happens to elements contained within Field components and the render method of the component we pass to Field is not called, so the problem surely must lie within Field? If I were to put any other element within the form it will always stay on the screen, since this behaviour is tied to submitting a form via redux-form it leads me to believe the problem is to do with redux-form

**Comment by gustavohenke** [comment]
Please isolate the problem and create a Sandbox. Or at least show part of your code.

**Comment by erikras** [comment]
Ooh, I love the "needs sandbox" tag. Nice one, @gustavohenke!

**Comment by gustavohenke** [comment]
Closing due to no response.
