### ISSUE TITLE
Typescript Issue with Component Prop

### ISSUE THREAD

**Issue by andigu** [erikras/redux-form#3579]
- I tried using the types/redux-form package and had problems.
- I tried using the latest stable version of tsc.
- I have a question that is inappropriate for StackOverflow.
- Mention the authors so they can respond.
- Authors: @CarsonF , @aikoven , @LKay , @bancek

Passing in a function for component in Field causes a typescript compile error:
```
const {handleSubmit} = this.props;

const renderField = (field: WrappedFieldProps) => {
    return (
    <div className="input-row">
        <input {...field.input} type="text"/>
        {field.meta.touched && field.meta.error &&
        <span className="error">{field.meta.error}</span>}
    </div>
)};
return <div>
    <form onSubmit={handleSubmit}>
        <Field name="Email" component={renderField}/>
    </form>
</div>;
```
The error says that `Type '(field: WrappedFieldProps) => Element' is not assignable to type 'StatelessComponent<GenericFieldHTMLAttributes>'`.

**Comment by gustavohenke** [comment]
Unfortunately we have no official support for TypeScript.

You should have opened this issue on the [DefinitelyTyped repository](https://github.com/DefinitelyTyped/DefinitelyTyped), as they are the ones taking care of what is under the `@types` npm scope.
