### ISSUE TITLE
SubmissionError with FieldArray remove only after add new field

### ISSUE THREAD

**Issue by tomasztomys** [erikras/redux-form#3580]
I have a problem with SubmissionError with FieldArray. I add two the same values to two Fields in FieldArray and send them to API. Then API send me response: "Values not unique" and I throw SubmissionError and set values._error.. So I change one of value, or remove one of value and click Send one more time. But error doesn't disappear after this changes and I can't send request to API.
Error disappears only after add new value to FieldArray.

**Comment by tomasztomys** [comment]
please reopen

**Comment by erikras** [comment]
Fix released in [`v7.4.0`](https://github.com/erikras/redux-form/releases/tag/v7.4.0).
