### ISSUE TITLE
Form destroy infinite loop.

### ISSUE THREAD

**Issue by vladluca** [erikras/redux-form#3581]
Hello,

I encounter a strange issue. My form is being destroyed and reinitialized in an infinite loop. You can see the redux-logger output here:
![ceas](https://user-images.githubusercontent.com/7210423/32369889-bde23f74-c093-11e7-8f68-ecdc853cfc79.png)

And I get this error: ``Maximum update depth exceeded. This can happen when a component repeatedly
calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of
nested updates to prevent infinite loops.``

My stack trace here:
The above error occurred in the <Form(EditEmailForm)> component:
    in Form(EditEmailForm) (created by Connect(Form(EditEmailForm)))
    in Connect(Form(EditEmailForm)) (created by ReduxForm)
    in ReduxForm (at ClientEditEmailFormContainer.js:41)
    in ClientEditEmailFormContainer (created by InjectIntl(ClientEditEmailFormContainer))
    in InjectIntl(ClientEditEmailFormContainer) (created by Connect(InjectIntl(ClientEditEmailFormContainer)))
    in Connect(InjectIntl(ClientEditEmailFormContainer)) (created by Apollo(Connect(InjectIntl(ClientEditEmailFormContainer))))
    in Apollo(Connect(InjectIntl(ClientEditEmailFormContainer))) (at ClientAccountSettings.js:9)
    in div (at ClientAccountSettings.js:8)
    in ClientAccountSettings (at ClientUserSettings.js:18)
    in div (created by TabPanel)
    in TabPanel (at ClientUserSettings.js:17)
    in div (created by UncontrolledTabs)
    in UncontrolledTabs (created by Tabs)
    in Tabs (at ClientUserSettings.js:11)
    in ClientUserSettings (at ClientUserSettingsContainer.js:26)
    in ClientUserSettingsContainer (at Authorization.js:21)
    in WithAuthorization (created by Route)
    in Route (at index.js:22)
    in Switch (at index.js:20)
    in MainRoutes (at index.js:30)
    in main (at App.js:57)
    in div (at App.js:38)
    in IntlProvider (at App.js:37)
    in App (created by Connect(App))
    in Connect(App) (at index.js:29)
    in Router (created by BrowserRouter)
    in BrowserRouter (at index.js:28)
    in QueryRecyclerProvider (created by ApolloProvider)
    in ApolloProvider (at index.js:27)

I'm using redux-form: 7.1.2, react-router 4.2.0 and React 16.0.0.

I have a HOC over my form wrapper for authorization and I use it like this:

![index](https://user-images.githubusercontent.com/7210423/32370504-00477fee-c096-11e7-9424-0e23342e7c2e.png)

Here is my HOC:
![hoc](https://user-images.githubusercontent.com/7210423/32370551-3592562e-c096-11e7-944a-de16de15ba98.png)

I mention that the form works just good when the form wrapper is not passed to the HOC, but I do not understand why the form is destroyed and reinitialized in an infinite loop when using the HOC.

I encounter the same behavior also when using with redux-auth-wrapper.

**Comment by gustavohenke** [comment]
Can you please isolate the issue using [CodeSandbox](https://codesandbox.io/s/gJjDoKYWl)?

Something on your component hierarchy may be causing too many prop changes.
You can also find what the culprit is with [why-did-you-update](https://github.com/maicki/why-did-you-update).

**Comment by jonbcampos** [comment]
+1 seeing this same issue with:
```
"dependencies": {
    "immutable": "^3.8.1",
    "moment": "^2.19.1",
    "prop-types": "^15.5.10",
    "react": "16.0.0-alpha.12",
    "react-native": "0.48.1",
    "react-native-i18n": "^2.0.5",
    "react-native-linear-gradient": "^2.3.0",
    "react-native-vector-icons": "^4.3.0",
    "react-navigation": "^1.0.0-beta.11",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "redux-form": "^7.0.4",
    "redux-immutable": "^4.0.0",
    "redux-logger": "^3.0.6",
    "redux-persist-immutable": "^4.3.1",
    "redux-saga": "^0.15.6",
    "redux-saga-routines": "^1.1.2"
  }
```

**Comment by gustavohenke** [comment]
Hi @jonbcampos, instead of simply saying that you have the same error, please provide further details.
See what I asked the OP right before your comment.

**Comment by jonbcampos** [comment]
@gustavohenke will do what I can. You'll have to forgive the shortness. It was late and a long coding day.

**Comment by jonbcampos** [comment]
<img width="1229" alt="screen shot 2017-11-05 at 10 03 35 am" src="https://user-images.githubusercontent.com/139469/32417591-a06cd692-c210-11e7-800f-40d468ecf96f.png">

**Comment by jonbcampos** [comment]
As some more information. The next two screen shots include the segment that I see repeat over and over again till eventually the final failure and then the view moves forward.

**Comment by jonbcampos** [comment]
<img width="1115" alt="screen shot 2017-11-05 at 10 04 43 am" src="https://user-images.githubusercontent.com/139469/32417656-70ad5200-c211-11e7-9bf6-9e1344662798.png">

**Comment by jonbcampos** [comment]
<img width="1117" alt="screen shot 2017-11-05 at 10 07 39 am" src="https://user-images.githubusercontent.com/139469/32417658-7aa19a50-c211-11e7-9113-2164b7979bfd.png">

**Comment by jonbcampos** [comment]
hold please. this might be a react-navigation issue more than a redux-form issue. Been working with this all day.

**Comment by vladluca** [comment]
I finally manage to fix it by moving the react-router ``Switch`` into the ``ReactDOM.render()`` as child to the App component, and do not use anymore the MainRoutes component, like so:
![fix](https://user-images.githubusercontent.com/7210423/32428876-ba3ab31c-c2d0-11e7-93b1-4f0781d22f73.png)
 Since it looks that is not a redux-form issue, I will close it.
