### ISSUE TITLE
Numeric field names are assumed to be array elements

### ISSUE THREAD

**Issue by MilllerTime** [erikras/redux-form#3582]
### Are you submitting a **bug report** or a **feature request**?
Bug Report

### What is the current behavior?
Deep fields with a `name` prop containing digits are assumed to be array elements. For example, if you place a field with `name="5"` in a `<FormSection name="foo">`, `foo` is assumed to be an array, not a standard object. The field's value will also be stored at index 5, instead of on an object property named "5".

### What is the expected behavior?
A `<FormSection>` would represent a plain object, not an array. Any nested field names would show up as properties on that object.

### Sandbox Link
https://codesandbox.io/s/81rpy6q1l

### What's your environment?
Testing in Chrome using redux-form 7.0.4

### Other information
This scenario may be related to the issue described in PR #3308. My use case is the same at least, I'm using entity IDs as field names in a specific form, and the IDs are strings containing all digits.

There are a couple quirky aspects of the current behavior. You can test this with the CodeSandbox link.

- A FormSection containing a field of `name="5"` creates an array with indexes 0-4 set to `null`, and index 5 set to the field value. This is not ideal if the field name is "9999999999".
- If you have two populated fields, say "1" and "2", and you clear the value of field "1", it will inherit the value from field "2". This is because index 1 was simply filtered out of the array, leaving the value previously at index 2 now at index 1.

**Comment by leroy0211** [comment]
duplicate of mine? #3431

**Comment by MilllerTime** [comment]
Indeed, I missed your issue! Thanks, I'll close this one and add my findings to yours.
