### ISSUE TITLE
Broken link in documentation (FAQ section) for version 7.1.2

### ISSUE THREAD

**Issue by edward-hong** [erikras/redux-form#3583]
Currently the FAQ that answers the question "How can I clear my form after my submission succeeds?" has a link in the answer that is talking about the plugin API. The link is pointing towards https://redux-form.com/7.1.2/docs/faq/api/ReducerPlugin.md. This leads to the Page Not Found page. if the link's href is changed to https://redux-form.com/7.1.2/docs/api/reducerplugin.md/ instead, then the work works correctly as expected.

**Comment by erikras** [comment]
Thanks, @edward-hong!
