### ISSUE TITLE
Field level validation not working as expected

### ISSUE THREAD

**Issue by MamesPalmero** [erikras/redux-form#3584]
### Are you submitting a **bug report** or a **feature request**?

Bug report

### What is the current behavior?

1 Open https://codesandbox.io/s/qqw30k56r9
2 The character counter and validation should be displayed from the beginning but they do not
3 Fill in username (so the warning shows up)
4 Delete username (so the warning disappears and should not, apart from this, the error still does not appear)
5 Click on submit button (so the alert shows up, skipping the validation)

### What is the expected behavior?
The warning should appear from the beginning and not disappear at any time. The error should appear at the beginning and disappear when completing the field, it should also be validated when submitting the form

### Sandbox Link

https://codesandbox.io/s/qqw30k56r9

### What's your environment?

```
react -------- 16.0.0
react-dom ---- 16.0.0
react-redux -- 5.0.6
redux -------- 3.7.2
redux-form --- 7.1.2
```

### Other information

I've noticed that the field level validation behavior works fine until version 6.8.0. As of version 7.0.0 it does not work as expected

**Comment by timacs12** [comment]
try to override sync updation manually  below code i have to write for synce error proper updation
-----------------------------------------------------------------------------------------------------------------------------------
import * as phenomicReducers from "phenomic/lib/redux/modules";
import { reducer as formReducer } from "redux-form";
import { combineReducers } from "redux";
import selectedApplyForm from "./SelectedApplyForm";
function callUpdateSyncErrors(state, action) {
  console.log("formReducer is called", state, action.type);
  // action.type === "@@redux-form/CHANGE" &&
  // action.meta.field === "select_your_profession1";
  if (state && action.type) {
    console.log("state>>>>>>>>>>>>", state);
    let flag = 0;
    let { registeredFields, syncErrors, values } = state;
    if (syncErrors && registeredFields) {
      let regFieldKeys = Object.keys(syncErrors);
      regFieldKeys.map(key => {
        flag = 1;
        console.log("key>>>>>>>>,", key, registeredFields);
        if (!registeredFields[key]) delete syncErrors[key];
      });
    }
    if (registeredFields) {
      flag = 1;
      syncErrors = {};
    }

    let new_synError = [];
    let new_registeredField = [];
    let difference = [];
    if (registeredFields)
      new_registeredField = Object.keys(registeredFields);
    if (syncErrors)
      new_synError = Object.keys(syncErrors);
    difference = new_registeredField.filter(x => new_synError.indexOf(x) === -1);
    difference.map((key) => {
      if (!values[key])
        if (syncErrors)
          syncErrors[key] = "Required *";
        else {
          syncErrors = {};
          syncErrors[key] = "Required *";
        }
    })


    if (difference.length !== 0 || flag === 1)
      return {
        ...state,
        syncErrors: {
          ...syncErrors
        }
      };
    return state;
  }
  else return { ...state };
}
const rootReducer = combineReducers({
  ...phenomicReducers,
  selectedApplyForm,
  form: formReducer.plugin({
    iBLeadApplyForm: (state, action) => {
      return callUpdateSyncErrors(state, action);
    }
    ,
    IotBootcampThankyouform: (state, action) => {
      return callUpdateSyncErrors(state, action);
    }
  })
});
// const rootReducer = combineReducers({
//   ...phenomicReducers,
//   form: formReducer,
//   selectedApplyForm
// })
export default rootReducer;

**Comment by MamesPalmero** [comment]
Ups, closing as duplicate https://github.com/erikras/redux-form/issues/3288
Solution: https://github.com/erikras/redux-form/issues/3288#issuecomment-320709952
