### ISSUE TITLE
asyncValidation causes delay on form submission

### ISSUE THREAD

**Issue by klasver** [erikras/redux-form#3585]
During a form submission with asyncValidation the form submission actually waits before the asyncValidation has been finished before starting the submission. This causes a problem in the most early stage of the form submission which results in a delay of disabling or showing a spinner on the form submission button. I can understand this behaviour but it the interface/uit it look likes there is a delay in the form submission, this can be reproduced in the asyncValidation example from the docs as well.

[https://redux-form.com/6.6.1/examples/asyncvalidation/](url)

Did someone get to a workaround or found a good solution to solve this issue? Spinner shouldn't be shown on the submit button when the validation is triggered just by field onBlur event.

**Comment by gustavohenke** [comment]
You can implement [`shouldAsyncValidate`](https://redux-form.com/7.1.2/docs/api/reduxform.md/#-code-shouldasyncvalidate-params-boolean-code-optional-) and return `false` when the trigger is `submit`.
