### ISSUE TITLE
Website breaks browser shortcuts

### ISSUE THREAD

**Issue by tiberiuana** [erikras/redux-form#359]
The website application (documentation, examples) disables/breaks browser shortcuts (e.g. CTRL-f, CTRL-s).

To reproduce: 

* http://erikras.github.io/redux-form
* CTRL-f, CTRL-s

Expected: browser's find dialog and save dialog

Instead: nothing happens.

**Comment by erikras** [comment]
#252

**Comment by tiberiuana** [comment]
Ah, missed it. Thanks!
