### ISSUE TITLE
Field component rendered via HOC

### ISSUE THREAD

**Issue by arnavyagnik** [erikras/redux-form#3591]
I have been going around an issue which is pretty much painful to debug.
i have been using my custom Input field to pass to Field's component prop which accepts label, addon , errors and render them which i have hooked to redux form errors.
was working all fine.
now i want to integrate react-intl with it and to localise all label addons i have to use injectIntl which is a HOC itself.
Form : 

```
<form style={{ width: "100%" }}  onSubmit = {handleSubmit}>
   <Field name="phone" component = {injectIntl(getPhoneInput)} />
</form>
```

Decorator

```
Login = reduxForm({
  form: "LoginForm",
  validate: validations
})(Login);
```

getPhoneInput : 

```
const getPhoneInput = props => {
  return (
    <Input
      {...props}
      label={props.intl.formatMessage(messages.phoneLabel)}
      addon={props.intl.formatMessage(messages.phoneAddon)}
      placeholder={props.intl.formatMessage(messages.phoneInputPlaceHolder)}
      hasError={props.meta.touched && props.meta.invalid}
      error={props.meta.touched && props.meta.error}
    />
  );
};
`


**The problem is all render fine but the input behaves disabled, even on clicking the input FOCUS action is dispatched i cannot type in anything.**

**Comment by gustavohenke** [comment]
Hi, thanks for using Redux Form, but this sounds like an usage issue.
In this case, please use StackOverflow to ask for what's wrong with it.

If you manage to find a bug in Redux Form, please open another issue describing what the issue is and providing all steps to reproduce it.
