### ISSUE TITLE
Can't post route param along with the form data.

### ISSUE THREAD

**Issue by Karthik6345** [erikras/redux-form#3595]
My application has dynamic routes (dynamic route param), in which it contains redux form .In order to distinguish the form data,I need to post redux form data along with the react route param .

I have passed the react route param as props from the parent component to the child component having the redux form i.e,initialvalues in props has the param value.I want to initialize the route param to the input fied with hidden type.But the resultant data is as below.Help is much appreciated.Thanks in advance

![capture](https://user-images.githubusercontent.com/13297851/32645703-a4aa71d6-c60e-11e7-89fe-81b4a35199da.PNG)

**Comment by gustavohenke** [comment]
Please ask for usage support on StackOverflow.

**Comment by ernani** [comment]
I like the idea of a community based forum for questions, it seems that StackOverflow is not that active, nor the Gitter channel, a lot of users are sensing that and I am trying to help as much as I can. Where is everyone? I've heard there is also a Slack channel, are there more traction there? Thanks!

**Comment by gustavohenke** [comment]
Sorry @ernani, we don't have any official channels actually.

We just prefer to keep usage support isolated from enhancements suggestions/bug fixing.
The usual suggestion of StackOverflow is one most people know about and is quite popular, so you *could* get a good answer there.
