### ISSUE TITLE
onBlur event is not working on Label

### ISSUE THREAD

**Issue by GSatishKumar** [erikras/redux-form#3599]
<label
      key={key}
      id={key}
      data-criteriaName={dataCriteriaName}
      style={{...labelStyle, ...style}}
      onMouseOver={(e) => { hanleMouseHover(e) }}
      onMouseLeave={(e) => { handleOnMouseLeave(e) }}
      onClick={(e) => { handleOnClick(e) }}
      onBlur={() => { handleBlur(event) }}
      className={labelType}>{labelValue}
</label>

export const handleBlur = (event) => {
  console.log('blur', event)
}

**Comment by pfftdammitchris** [comment]
Can you show more code surrounding that component lol
