### ISSUE TITLE
Disable all fields on submitting

### ISSUE THREAD

**Issue by vslinko** [erikras/redux-form#36]
I think it would be useful if `fields[key].disabled` will depend on `form.submitting`.
What are you think?

**Comment by erikras** [comment]
I think that is too opinionated. It's pretty easy to add `disabled={submitting}`, but harder to remove the value for those that don't want that behavior. Perhaps if I get a lot of demand for it, it could be a config option.

**Comment by luisrudge** [comment]
:-1: on doing this by default.

**Comment by jonathanasquier** [comment]
Hey, I get only false values for submitting. (console.log(submitting) on render)
I use `disabled={submitting}` on a button or input type=submit, I use handleSubmit onClick
any advice?
thanks!

**Comment by erikras** [comment]
@jonathanasquier Is your `onSubmit` returning a Promise?

**Comment by jonathanasquier** [comment]
I'm using `onSubmit={ handleSubmit(stripeCardCreateToken) }`
`stripeCardCreateToken` is a thunk that dispatches success/errors actions on resolve/reject.

**Comment by erikras** [comment]
At the moment, the only way for the `submitting` flag to change is for the `onSubmit` (`stripeCardCreateToken`, in your case) to return a Promise. When calling Redux actions directly, this usually requires some sort of [promise middleware](https://github.com/erikras/react-redux-universal-hot-example/blob/master/src/redux/middleware/clientMiddleware.js).

If/when someone comes up with a good way for the redux-form reducer to be informed about actions to listen to for `submitting`, another "more Reduxy" method might become available.

**Comment by jonathanasquier** [comment]
Works well with promise middleware.
I have nested thunks so I could not just return a promise, I ended up hacking it in another state property. Thanks!
