### ISSUE TITLE
Cannot seem to use ES6 method for the <Field> validate and Custom props don't work

### ISSUE THREAD

**Issue by stephenwil** [erikras/redux-form#3601]
I cannot get the return from an implicit es6 function, or even using a class method to work properly for the validate fuction.

E.g. even doing the attached code below, will not make the component invalid (i.e. returning a string).
In my real code, I'm trying to use class method as the validator, and valid is always true.
Also, in the props that are passed to the validator method, any custom props (also see below), never appear in the props list.

 let customprops: any = {sw: 1};
<Field validate={(value) => "3"}
          props={...customprops}
/>

**Comment by gustavohenke** [comment]
Hello @stephenwil,
Please provide an actual running code that demonstrates your issue.

**Comment by eranhirs** [comment]
I had the same problem.
In my case, it was because my logout reducer cleaned the `form` key from the redux store.
Make sure you don't mess with the `form` key in the store.

**Comment by gustavohenke** [comment]
Closing due to no response from OP.
