### ISSUE TITLE
BUG - FieldArray "required" unable to invalidate form

### ISSUE THREAD

**Issue by michaelryancaputo** [erikras/redux-form#3604]
### What is the current behavior?
Currently can not invalidate a form containing a FieldArray that is required (not empty).

### What is the expected behavior?
I should require FieldArray to have content, if it is empty and it is a required field, it should invalidate the form.

### What's your environment?
```
    "redux-form": "^7.1.2",
    "react-redux": "^5.0.6",
    "react": "15.6.2",
```

**Comment by gustavohenke** [comment]
Please provide an actual running code that demonstrates your issue.
You can start from this template: https://codesandbox.io/s/gJjDoKYWl

**Comment by michaelryancaputo** [comment]
Interesting, I wasn't able to reproduce here: https://codesandbox.io/s/8lqo78r29l

Will close for now and re-open if I can reproduce. Thank you.
