### ISSUE TITLE
function validate, "FieldArray" field.push empty is considered error  

### ISSUE THREAD

**Issue by cdac901** [erikras/redux-form#3605]
### What is the current behavior?
We make this example [https://codesandbox.io/s/vor1y51y7](https://codesandbox.io/s/vor1y51y7) in the reflected a test field, when clicking the submit button does considered error and no show alert with object result

### What is the expected behavior?
test has no validation in the function, it should do the submit correctly

**Comment by pfftdammitchris** [comment]
Can you explain with further detail? I have a hard time understanding your current behavior

**Comment by cdac901** [comment]
When I push an empty object to a fields array and submit, it fail validation

**Comment by pfftdammitchris** [comment]
Try removing {...props} from the <Test /> component. You are passing the redux-form decorated component prop "onSubmit" onto that component which is giving it bugs.

**Comment by pfftdammitchris** [comment]
## Change:

```javascript
const SyncValidationForm = (props) => {
  const { handleSubmit, pristine, reset, submitting } = props
  return (
    <form onSubmit={handleSubmit}>
      <Test {...props} />
      <div>
        <button type="submit" disabled={submitting}>Submit</button>
        <button type="button" disabled={pristine || submitting} onClick={reset}>Clear Values</button>
      </div>
    </form>
  )
}
```

## To:
```javascript
const SyncValidationForm = (props) => {
  const { handleSubmit, pristine, reset, submitting } = props
  return (
    <form onSubmit={handleSubmit}>
      <Test {...props} />
      <div>
        <button type="submit" disabled={submitting}>Submit</button>
        <button type="button" disabled={pristine || submitting} onClick={reset}>Clear Values</button>
      </div>
    </form>
  )
}
```

#### Your passing your ```onSubmit``` prop all the way from your ```index.js``` file:
```javascript

ReactDOM.render(
  <Provider store={store}>
    <div style={{ padding: 15 }}>
      <h2>Synchronous Validation</h2> 
      <SyncValidationForm onSubmit={showResults} />
      <Values form="syncValidation" />
    </div>
  </Provider>,
  rootEl
);
```

**Comment by cdac901** [comment]
Thanks, it works!
