### ISSUE TITLE
Render Select that is not form factor

### ISSUE THREAD

**Issue by jackiepark** [erikras/redux-form#3607]
I made select input in form and tried to control two form fields.

```
<Select
  onChange={(value) => handleChange(value)}
/>
handleChange = (value) => {
const splitedValue = value.split('|')
newObj = {
  a: splitedValue[0],
  b: splitedValue[1]
}
change('targetName', newObj)
}
```

This rendered two form fields but didn't render Select after rendering once.
How could I re-render Select?

**Comment by gustavohenke** [comment]
Please use StackOverflow for usage support questions.
