### ISSUE TITLE
`errors` and `valid` props are incorrect

### ISSUE THREAD

**Issue by szymonmichalak** [erikras/redux-form#361]
Great work @erikras ! Thanks for developing `redux-form` :+1: 

After upgrading from `3.1.0` to `3.1.6` or even `3.1.1` I keep getting wrong `props` values in the component that is decorated by `reduxForm()`. It works okay with the `3.1.0` version, but I cannot find any breaking change here: https://github.com/erikras/redux-form/compare/v3.1.1...master

By "wrong" I mean that `valid` prop is always `true`, even though the errors are set in each invalid field and global `errors` prop array is empty.

**Comment by erikras** [comment]
[Published in `v3.1.7`](https://github.com/erikras/redux-form/releases/tag/v3.1.7).

**Comment by erikras** [comment]
[Published in `v3.1.7`](https://github.com/erikras/redux-form/releases/tag/v3.1.7).
