### ISSUE TITLE
ImmutableJS and initialValues does not populate field value, despite changed values in redux store

### ISSUE THREAD

**Issue by tpinne** [erikras/redux-form#3610]
### Are you submitting a **bug report** or a **feature request**?
Bug

### What is the current behavior?
In the past our code base used REST to communicate with the server and the data was stored in an immutableJS redux store. We initialised the forms with data from the store which maybe had to be loaded from the server first. That all worked great.

Now we want to switch to Apollo GraphQL (currently with InMemory storage) and the same code base doesn't work anymore. The only thing that has changed is the way that the data for the props for the Form are fetched, nothing else.

The initial values are set in the redux store but aren't populated into the fields. When I change something the values in the store get updated and also the corresponding field.

I created a stripped down version of how we have implemented redux-form in a codesandbox forked form the "Initialize from state" example, which demonstrates the behaviour. Strangely though it does work, if the initialValues are set directly in the reduxForm() function.

### What is the expected behavior?
Have the input field populated with the initial values like it does if the sandbox example is changed to not use immutablejs.

### Sandbox Link
https://codesandbox.io/s/m7omxyjv38

### What's your environment?
Current redux version, but could reproduce it in 6.8 in the sandbox.

### Other information
Maybe there have been changes in the past we didn't recognize. So I wouldn't rule out that there is a missing piece in the puzzle.

**Comment by tyscorp** [comment]
I think this issue is that you're importing the reducer from `'redux-form'` and not `'redux-form/immutable'`.

**Comment by gustavohenke** [comment]
Yep, that's the reason. Thanks, @tyscorp!

**Comment by tpinne** [comment]
Oh bummer. Of course that's the reason... This is what happens if you copy all the components from your old codebase but re-add the reducer manually via copy/paste from web examples.
Sorry for bothering. But great thanks for pointing this out @tyscorp.

And keep up the good work!

**Comment by gustavohenke** [comment]
btw, nice avatar, @tpinne... looks a lot like your reaction after reading this! 😄 

<img width="179" alt="screen shot 2017-11-15 at 20 59 25" src="https://user-images.githubusercontent.com/826553/32829994-ed1eb7a0-ca47-11e7-8ac6-46ab77e72591.png">
