### ISSUE TITLE
Passing a key-value pair in SubmissionError?

### ISSUE THREAD

**Issue by Hiroki1116** [erikras/redux-form#3616]
According to the doc, `SubmissionError` accepts key-value pairs, as well as the `_error` filed.

> If it is rejected in the form of { field1: 'error', field2: 'error' } then the submission errors will be added to each field (to the error prop) just like async validation errors are.

However,  [unless I put the error message next to the input field](https://redux-form.com/7.1.2/examples/submitvalidation/), I don't see those custom error fields in `this.props` on the decorated component.

To clarify the point, here is a example...

    export default class Container extends React.Component {
	    //constructor here

		onSubmit(values) {
			return axios.post('/posts', {/* parameters */ }
			// .then function here
			}).catch((error) => {			
				throw new SubmissionError({
					cause1:"This error happened because blah blah...",
                        	        cause2:"This is another reason blah blah...",
					_error: "error!"
				});
			});
		}

		render() {
			return (
				<div>				
					<Form onSubmit={values=> this.onSubmit(values)}/>
				</div>
			);
		}
    }

In the form, you have something like...

	render() {
		const {error, handleSubmit} = this.props;
		return (
			<div>
				<form onSubmit={handleSubmit}>
	        		 {error && <p>{error}</p>}
                                  // input fields here
                                 
                                  //Where are the cause1 and cause2? 
	    		              //this.props doesn't have them
				</form>
			</div>
		);
	}

How do we get `cause1` and `2` in the form? 
### What is the current behavior?
Messages associated with `_error` can be retrieved, but other can't.

### What is the expected behavior?
All key-value pairs from `SubmissionError` are retrieved on the decorated component through this.props.

### What's your environment?

7.1.2

**Comment by gustavohenke** [comment]
The other errors are available as `meta.error` within your fields instances.

If you would like to retrieve all errors in any other component - such as your form -, you have to use some selector, eg [`getFormSyncErrors`](https://redux-form.com/7.0.3/docs/api/selectors.md/#-code-getformsyncerrors-formname-string-code-returns-code-state-gt-formsyncerrors-object-code-).
