### ISSUE TITLE
Form inside component passed to Field

### ISSUE THREAD

**Issue by alexxmde** [erikras/redux-form#3627]
Hey there, I'm trying to have a form inside a component passed to Field, but I can't have a form inside another form. Is there an alternative to achieve this behavior?

**Comment by gustavohenke** [comment]
You don't need to give Redux Form form components a `<form>` tag, which I imagine is your problem. It can simply be a div with `<Field>`s and buttons.
Then you can just have a normal button within that 2nd level form that triggers `handleSubmit`... and *voila*.
