### ISSUE TITLE
focus is not getting dispatched

### ISSUE THREAD

**Issue by sachin9891** [erikras/redux-form#3629]
### Are you submitting a **bug report** or a **feature request**?

bug 

### What is the current behavior?

I am using react-autosuggest when I click on input field no action is dispatched in redux dev tools 
because of which redux-form is not working in that field 

### What is the expected behavior?
@ redux-form/Focus should be dispatched and other on onChange and further function

### Sandbox Link

I dont have sandbox link right now 
but I will provide if needed

### What's your environment?

redux-form ver - 7.1.2
mac os / chrome
node: '6.11.0'
npm: '5.5.1'

**Comment by gustavohenke** [comment]
> I dont have sandbox link right now
> but I will provide if needed

Yes, it is needed 😉

**Comment by gustavohenke** [comment]
Closing due to no response.
