### ISSUE TITLE
[BUG] Swallowed errors in onSubmitSuccess when onSubmit returns a Promise

### ISSUE THREAD

**Issue by ClementParis016** [erikras/redux-form#3636]
### Are you submitting a **bug report** or a **feature request**?
Bug Report

### What is the current behavior?
When returning a Promise from `onSubmit` handler, errors happening in `onSubmitSuccess` get swallowed.

### What is the expected behavior?
Expect errors happening in `onSubmitSuccess` to be logged to the console.

### Sandbox Link
Here is a CodeSandbox to reproduce the error: https://codesandbox.io/s/18yk8rpn54

### What's your environment?
redux-form@7.1.1
react@16.0.0
redux@3.7.2
react-redux@5.0.6
Chromium@62

I ran into this issue while trying to redirect on successful form submission. My `onSubmit` handler successfully made a network request and returned a Promise (through redux-thunk), but then I had a `TypeError` in my `onSubmitHandler` that I couldn't even know about because it wasn't bubbling up to reach the console :disappointed:

**Comment by erikras** [comment]
Published fix in [`v7.2.1`](https://github.com/erikras/redux-form/releases/tag/v7.2.1).
