### ISSUE TITLE
Redux form incarnation for Angular JS => 1.5x

### ISSUE THREAD

**Issue by rajatvijay** [erikras/redux-form#3638]
### Are you submitting a **bug report** or a **feature request**?

Feature Request

### What is the current behavior?

The current library can only be used with react, there are many incarnations for angular but none for angular JS.

### What is the expected behavior?
Angular JS is still popular. A lot of enterprises are using angular JS may it be in legacy or new code. So a minor incarnation for angular JS would help.

### What's your environment?

Angular JS => 1.5

### Other information

So saving your form state in a reducer is a brilliant idea. It solves many major issues of which two most prominent are (IMHO)

1. Predictable form validations. Form validations are no longer a black box.
2. Testing form validations are a possibility now. (actually a simpler one)

I have started recently seeing people using redux with Angular. So this might be a good opportunity. 
Even the Angular team has backported its component library to Angular JS 1.5x.

**Comment by gustavohenke** [comment]
Oh well.. 
I'm not really deciding anything here, but rather just throwing my thoughts:

While I do agree Angular.js is still popular, I don't think this is going to happen at all.

The codebase is quite coupled to React environment. So it won't happen here.
Some work could definitely be done to extract the Redux logic into another library, but I don't believe @erikras would be willing to do so.

Now finally there is the port itself; I'm pretty sure that someone else would need to do this one.

Obviously this opens redux-form to be used with other libs as well eg Vue or whatever emerges tomorrow, but this is quite some work to be done.

**Comment by gustavohenke** [comment]
Okay, so I shut my mouth 🤐 

https://twitter.com/erikras/status/935210968811999232
