### ISSUE TITLE
Creating new Field components dynamically

### ISSUE THREAD

**Issue by wesharehoodies** [erikras/redux-form#3639]
Hello!

Whenever I create a new form component dynamically, they share the same state. Which is expected since they both have the same name. How could I name these dynamically?

Example: https://i.imgur.com/YaSIRov.gifv

what are the possible ways to solve this the redux form way?

**Comment by wesharehoodies** [comment]
Solved it thanks to `node-uuid`.

Example:

```js
import React, { Component } from 'react';
import { Field, reduxForm } from 'redux-form';
import { connect } from 'react-redux'
import BoardTitleInput from './../boardCreation/BoardTitleInput';
import { v4 } from 'node-uuid';

class CreateCardContainer extends Component {

    submit = values => {
        console.log(values)
    }

    render() {
        const { handleSubmit } = this.props;
        return (
        <form onSubmit={handleSubmit(this.submit)}>
            <label>
                <Field
                    type="text"
                    component={BoardTitleInput}
                    name={`cardName-${v4()}`}
                />
            </label>
        </form>
        )
    }
}

function validate(values) {
    const error = {};

    return error;
}

export default reduxForm({
    validate,
    form: `cardName-${v4()}`
})(connect(null)(CreateCardContainer));
```

**Comment by gustavohenke** [comment]
Hi, @wesharehoodies, indeed you need to randomise the form name, but you don't need to do so with the field names. They are unique within a given form.

**Comment by wesharehoodies** [comment]
So how would you go on randomising the name? node-uuid seems kinda clunky.

**Comment by gustavohenke** [comment]
You can randomise using whatever you like, eg [`_.uniqueId`](https://lodash.com/docs/4.17.4#uniqueId), or you can implement a function like this yourself.

This is a quite subjective point, though. In this cases we suggest that you ask on StackOverflow, as it is more appropriate for usage support.
