### ISSUE TITLE
Working with material-ui

### ISSUE THREAD

**Issue by tracker1** [erikras/redux-form#364]
Does this work with [material-ui](https://github.com/callemall/material-ui)?  If so, would be nice to see an example integrating the two.

**Comment by erikras** [comment]
Examples with common input component libraries is on the todo list. PRs welcome, of course.

In the meantime, I would direct you here: [Will `react-form` work with a my custom input component?](http://erikras.github.io/redux-form/#/faq/custom-component)

**Comment by panozzaj** [comment]
We are using redux-form and material-ui on a project. They seem to play well together.

**Comment by luisrudge** [comment]
Yep. Me too. It works great :)

**Comment by alinseba** [comment]
@panozzaj Can you please provide an example of how you hook material ui component to redux form? Thanks.

**Comment by ingshtrom** [comment]
The only problem I had was mapping the `error` property given by redux-form to `errorText`, which is what material-ui uses.

@alinseba here is an example:
```
import { TextField } from 'material-ui';
...
// use a decorator or wrap your component class with redux-form
// this will give you the `fields` prop type that will be used in the render method
...
render() {
  // normalizeReduxFormFieldObj just does the `error` to `errorText` mapping explained above
  const [email, username, password] = [fields.email, fields.username, fields.password].map(normalizeReduxFormFieldObj);

  return (
    ...
    <TextField {...username} fullWidth hintText='Username' />
    ...
  );
}
...
```

**Comment by ahmedNY** [comment]
Material ui DatePicker didn't work for me, so i set the date manually
`<DatePicker onChange={(e,d) => this.props.fields.invoiceDate.onChange(d) }/>`
is there is better solution?

**Comment by panozzaj** [comment]
We also needed to fire the `onChange` event manually. (`onBlur` I think, as
well?)

**Comment by ooflorent** [comment]
I'm closing this issue since it is an usage question, and we encourage you to ask it on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

**Comment by zibs** [comment]
@ahmedNY helped me, thanks!
