### ISSUE TITLE
Initializing FieldArray with multiple fields

### ISSUE THREAD

**Issue by boriskogan81** [erikras/redux-form#3640]
The (excellent) example in the documentation has the fields object start off empty and then we push to it programmatically. What if we want the component to initialize with several fields already in existence? Is there an API for this?

**Comment by gustavohenke** [comment]
There you go: https://codesandbox.io/s/74z39y55wq

In the future please post usage question on StackOveflow. Thank you

**Comment by boriskogan81** [comment]
Thank you. I had [a StackOverflow question open for almost a week](https://stackoverflow.com/questions/47457793/redux-form-field-arrays-initializing-a-field-array-with-a-specific-length). I really appreciate your help.
