### ISSUE TITLE
DOM's “value” property not working

### ISSUE THREAD

**Issue by sant527** [erikras/redux-form#3641]
### The Problem

I am trying to render the below in reactjs: I am trying to set the initial value. But the output shows empty.
I am just following the tutorial https://youtu.be/ey7H8h4ERHg

```
const createRenderer = input => 
    <label className="form-control-label">
       Rate<span className="asteriskField">*</span>
    </label>
    <input className="numberinput form-control" value="10" type="number" {...input} />
)

let IngredientForm = props => {
   const { handleSubmit } = props
   return (
    <form onSubmit={ handleSubmit(submit) }>
        <Field name="name" component={createRenderer} />
    </form>
}


IngredientForm = reduxForm({
  form: 'ingredient',
})(IngredientForm)
```

![screenshot from 2017-11-27 18-25-33](https://user-images.githubusercontent.com/6462531/33269834-11fd149a-d3a8-11e7-9212-a1462fce13ec.png)

### Expected Behavior
The form should be showing the initial value set by the DOM's value property

**Comment by gustavohenke** [comment]
Please ask for usage support on StackOverflow.
