### ISSUE TITLE
feature request - SubmissionWarning or action creator to update warning

### ISSUE THREAD

**Issue by eddywashere** [erikras/redux-form#3644]
It could be helpful to set the `warning` prop on the form or field inputs in `onSubmit` by throwing a `SubmissionWarning` similar to the `SubmissionError` functionality. That or allow `_warn` on `SubmissionError` and pass that through. I was also hoping that there was an action creator available to update warning.

Use case: A form could still be valid if the onSubmit code experiences a network issue or some unexpected error. It's problematic when form submission is disabled when the form is `invalid`. That makes using `SubmissionError` less useful. It would be convenient to expose what non invalidating error happened via redux-form `warning` on the form or field that was impacted.

This might also help out https://github.com/erikras/redux-form/issues/2290

**Comment by gustavohenke** [comment]
This feature saw little or no interest from other users, so I'm closing it for now.
Feel free to continue the discussion.
