### ISSUE TITLE
redux-form: enableReinitialize is not working

### ISSUE THREAD

**Issue by sant527** [erikras/redux-form#3656]
In my form I am passing the initialvalues through the below code. The initialvalues are being set. The initialization works only one time. After that wheneve i submit the form successfully the initialization values are not changing. The reason is the state.ingredients.formcomb.form.data is not changing because when the form is successfully submitted it returns the same initialvalues. Because there seems to be no change in the state even after form is submitted it does not trigger the INITIALIZE action. Because of which the values dont get reset.

So how to tell the redux-form that the form have been successsully submitted so reset the values to initialValues 
```
const mapStateToProps1 = (state) => {
        return {
            initialValues : getValues(state.ingredients.formcomb.form.data)
         }
    }

const mapDispatchToProps1 = (dispatch) => {
    return {
        fetchData: (url) => dispatch(itemsFetchData(url)),
    };
};

 IngredientForm = connect( mapStateToProps1,mapDispatchToProps1 )(
      reduxForm(
      {
        form: 'ingredient',
        enableReinitialize: true,
        //validate,
      }
      )(IngredientForm)
 );
```
![screenshot_20171202_095258](https://user-images.githubusercontent.com/6462531/33511739-9e1324f0-d746-11e7-8dbb-23505ac0d9dc.png)

the values array is different from init array

**Comment by gustavohenke** [comment]
This is the expected behaviour.
Redux Form can't tell what the new `initialValues` are after a submission.

It should be pretty straightforward to do this in user land though, as `onSubmit` receives `dispatch` (so that you can dispatch any action).

**Comment by sant527** [comment]
I have found the solution. basically after the form is submitted without any errors i want the form values to reset.

So i have done this.props.reset() if there are no errors in my incoming form api. then it worked. But to understand why INITIALIZE action is not being called took me lot of time.
