### ISSUE TITLE
Touch isn't being called on deep form array fields on submit

### ISSUE THREAD

**Issue by hnordt** [erikras/redux-form#366]
Related to #357.

I'm using v3.1.6.

When I submit form, deep array fields aren't touched, only if I blur them.

![captura_de_tela_120115_061004_pm](https://cloud.githubusercontent.com/assets/1625399/11512727/b4511d5c-9856-11e5-95b9-dd0f1fd76add.jpg)

![captura_de_tela_120115_061236_pm](https://cloud.githubusercontent.com/assets/1625399/11512797/0e6c7b4c-9857-11e5-82eb-c264eda3249c.jpg)

**Comment by erikras** [comment]
Aha! Great bug report, thanks. Will investigate. :mag:

**Comment by erikras** [comment]
[Published in `v3.1.7`](https://github.com/erikras/redux-form/releases/tag/v3.1.7).
