### ISSUE TITLE
Integrating redux-form with redux-saga for SubmissionError or alternative

### ISSUE THREAD

**Issue by brianh20** [erikras/redux-form#3660]
Hi! Thanks for your awesome work. Here is my question:

I am working on a project where:
- Form is in a component
- handleSubmit is in a container of that component
- api call is made by redux-saga

Which means, I can't use (or haven't been able to figure out how) SubmissionError to trigger the error show on the form. I am currently using 'submitFailed' but again, that doesn't let me (not directly/neatly) set the error for the form field.

There is a 'similar' situation in a github repo I made yesterday (it's awful but it shows the picture):
www.github.com/brianh20/redux-saga-test

**Comment by liitfr** [comment]
Hi ! there's a related discussion here #161.
I particulary liked this [answer](https://github.com/redux-saga/redux-saga/issues/161#issuecomment-254939672)

**Comment by erikras** [comment]
For all of you using `redux-saga`, perhaps [check out this tool I just built](https://medium.com/@erikras/getting-a-promise-from-redux-actions-d92787894368) to convert actions into a `Promise` for libraries like `redux-form`.

**Comment by gustavohenke** [comment]
Due to the aspect "find the solution that best suits you", I'm closing this issue.
I recommend looking at the links already provided here.
