### ISSUE TITLE
Field validation page of documentation is not working

### ISSUE THREAD

**Issue by vovkvlad** [erikras/redux-form#3661]
Hi!
I was just starting with the redux-form library, and when I tried to open documentation for field level validation, the page shows preloader forever.
In the console, there is next error showing up:

![image](https://user-images.githubusercontent.com/6311961/33562132-1a234994-d91d-11e7-8f97-83fbe79bc1f8.png)

This is the issue to basically notify you guys, as I did not find similar issues among the open.
If any additional info is needed - will be glad to provide it.

Thanks in advance

**Comment by dtnmr** [comment]
I know it's not a fix, but in the meantime you can have a look at an [older version](https://redux-form.com/7.1.2/examples/fieldlevelvalidation/) of the page.

And also check the validate prop on the [Field component](https://redux-form.com/7.2.0/docs/api/field.md/). :smile:

**Comment by danielrob** [comment]
I'm guessing this is fixed, if not it's a browser issue / something that is not affecting me, in which case please re-open with further details! 

Thanks for the heads up at the time!
