### ISSUE TITLE
Form doesn't submit without a button

### ISSUE THREAD

**Issue by barraponto** [erikras/redux-form#3664]
### What is the current behavior?
Form doesn't submit if the user just presses enter on an input element.
It does if a button is added to the form (even if the button is not selected).

### What is the expected behavior?
Text inputs should submit the form if the user presses enter while it is focused

### Sandbox Link
https://codesandbox.io/s/1rkv5povyq

### What's your environment?
React 16.2, Redux 3.7.2, Redux-Form 7.2.0
Firefox 57 on Linux

**Comment by flanamacca** [comment]
thats actually a browser quirk.  If you create a form and hit enter, the browser will look for a submit button and hit that.  If no button, no submit

**Comment by gustavohenke** [comment]
Thanks for the information @flanamacca.
If you remember reading this somewhere, can you please post the links here? Cheers!
