### ISSUE TITLE
SubmissionErrors persist after form has been destroyed

### ISSUE THREAD

**Issue by klase** [erikras/redux-form#3666]
### What is the current behavior?
When a submission error has been thrown the error and submitFailed properties of the form lingers in the redux state even after the form has been destroyed on unmount, leading to the error still showing next time the form is mounted.

### What is the expected behavior?
error and submitFailed should be cleared along with the rest of the form's state when form is destroyed.

**Comment by gustavohenke** [comment]
Can you please share a snippet of code that replicates your issue?

You may want to use use [this template](https://codesandbox.io/s/gJjDoKYWl) to get started faster.
