### ISSUE TITLE
Flow: initialize function call. Called with too few arguments

### ISSUE THREAD

**Issue by aij** [erikras/redux-form#3668]
### Bug

The [type declaration](https://github.com/erikras/redux-form/blob/f23a36efb81bc18e2f98f155a4924084539d7fc6/src/actions.types.js.flow#L166) for the `initialize` action creator is inconsistent with the [documentation](https://redux-form.com/7.2.0/docs/api/actioncreators.md/#-code-initialize-form-string-data-object-keepdirty-boolean-options-keepdirty-boolean-keepsubmitsucceeded-boolean-updateunregisteredfields-boolean-code-). In particular, note that the documentation makes the `keepDirty` and `options` arguments *optional* whereas the type declaration makes all 4 arguments *required*.

I will be happy to submit a PR, but just wanted to check that the documentation is considered canonical and the type should be updated to match, right?

### What is the current behavior?

```
 59:   dispatch(initialize('feePurchase', { ...defaults, fees }));
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function call. Called with too few arguments
         v
  150:   (
  151:     form: string,
  152:     values: Object,
  ...:
  155:   ): InitializeAction
         ------------------^ function type expects more arguments. See: node_modules/redux-form/lib/actions.types.js.flow:150


```

### What is the expected behavior?

`No errors!`

### What's your environment?
redux-form: 7.1.2 (the type definition has not yet changed in master)
flow: 0.59.0

### Other information

#3444 might be related.

**Comment by erikras** [comment]
Fix released in [`v7.4.0`](https://github.com/erikras/redux-form/releases/tag/v7.4.0).
