### ISSUE TITLE
Normalizers when using a multiple record form?

### ISSUE THREAD

**Issue by Plummat** [erikras/redux-form#367]
Hey, it seems when I have a multiple record form, the normalizers no longer I apply when there is more than one form present. I scanned the docs but didn't see this issue mentioned anywhere.

**Comment by erikras** [comment]
#323 addressed this. It has not yet been released.

**Comment by erikras** [comment]
[Published in `v3.1.7`](https://github.com/erikras/redux-form/releases/tag/v3.1.7).
