### ISSUE TITLE
@@redux-form/DESTROY is thrown when bundling the application with NODE_ENV=production

### ISSUE THREAD

**Issue by tokenvolt** [erikras/redux-form#3671]
### What is the current behavior?
Using webpack as a module bundler and building with
```
...
  new webpack.DefinePlugin({
    'process.env': {
      'NODE_ENV': JSON.stringify("production")
    }
  }),
...
```
causes registering fields twice and `@@redux-form/DESTROY` action to be dispatched.

### What is the expected behavior?
Registering fields once and not dispatching a destroy event.

### What's your environment?
redux-form@6.8.0
nodejs 6.9.1
NODE_ENV=production

**Comment by gustavohenke** [comment]
Can you please share a repo that reproduces your issue?

**Comment by tokenvolt** [comment]
@gustavohenke sorry, it seems that it was a very tricky mistake on my side and not a redux-form issue.
