### ISSUE TITLE
Issue with array field structure when initializing form state 

### ISSUE THREAD

**Issue by smanne** [erikras/redux-form#368]
I am using array field structure, if I dont initialize then I dont get any error. If I initialize I got error.

Uncaught (in promise) TypeError: array.map is not a function(…)       getValues.js?e501:31

Here is what I found when I am debugging. Its getting object instead of array.

![screenshot 2015-12-02 10 52 16](https://cloud.githubusercontent.com/assets/953832/11523028/254471e8-98e4-11e5-9cf7-d20ae76b460f.png)

**Comment by erikras** [comment]
More discussion on this in #360.

**Comment by erikras** [comment]
This should be fixed in [`v4.0.0`](https://github.com/erikras/redux-form/releases/tag/v4.0.0). Come and get it!
