### ISSUE TITLE
Dispatch not triggered in onBlur

### ISSUE THREAD

**Issue by yeezysallonyoursofa** [erikras/redux-form#3683]
Inside of a form `AskQuestion`, when a user clicks out of an input field I want to reset the field.

```
<Field
   name="company"
   type="text"
   keyUp={this.renderCompanyList}
   onBlur={this.onClearSearch}
   component={renderField}
   label="Choose Company..."/>
```

the `onClearSearch` callback however does not dispatch an action to reset the field despite the following. I have also correctly bound the function's `this` binding to the component.
```
  onClearSearch(e){
    this.props.dispatch(change('AskQuestion','company',''));
  }
```

How do I reset the field programmatically after a user clicks out?

**Comment by gustavohenke** [comment]
Hello,
Since you didn't show how your `renderField` looks like, I assume the problem lies there. In this case please open a StackOverflow question asking for help to debug the issue.
Thanks for using Redux Form.

**Comment by yeezysallonyoursofa** [comment]
ok, I edited my response, not sure why you rushed so fast to close this. i searched other issues before including this (including mentioning to put custom `onBlur` after `...input` and this did not work).

**Comment by gustavohenke** [comment]
Sorry for that. You're asking a question here, not requesting a feature to be added or a bug to be fixed. That's why StackOverflow is better anyway.
