### ISSUE TITLE
Cannot dispatch from within onBlur

### ISSUE THREAD

**Issue by yeezysallonyoursofa** [erikras/redux-form#3684]
Inside of a form AskQuestion, when a user clicks out of an input field I want to reset the field.

**I have uploaded this again because a moderator closed this without letting me edit**. I have already tried to reference this in other posts but the instructions have not helped me so far.

```
<Field
   name="company"
   type="text"
   keyUp={this.renderCompanyList}
   onBlur={this.onClearSearch}
   component={renderField}
   label="Choose Company..."/>
```
and this is my renderField

```
 function renderField(field) {
    const { meta: {touched, error} } = field;
    return(
    <div>
      <input type={field.type}
             placeholder={field.label}
             onKeyUp={field.keyUp ? () => {field.keyUp(field.input.value)} : ""}
             onBlur={field.onBlur ? () =>{field.onBlur()} : ""}
             {...field.input}
             // I also tried putting in after ...input
             onBlur={field.onBlur ? () =>{field.onBlur()} : ""}
           />
           <div className="text-danger">
             {touched ? error : ''}
           </div>
    </div>
  );
}
```
the onClearSearch callback however does not dispatch an action to reset the field despite the following. I have also correctly bound the function's this binding to the component.

 ```
 onClearSearch(e){
    this.props.dispatch(change('AskQuestion','company',''));
  }
```
How do I reset the field programmatically after a user clicks out?

**Comment by gustavohenke** [comment]
> I have uploaded this again because a moderator closed this without letting me edit.

Sorry about that, but I closed #3683 because you should ask questions like this on StackOverflow, it's the best place for usage support, not our issue tracker.
Please don't insist by opening another issue.

You may just spread `...input` on your `<input>` element, that's all you need to have your custom `onBlur` invoked.
