### ISSUE TITLE
File Upload

### ISSUE THREAD

**Issue by DarkBitz** [erikras/redux-form#3686]
### Are you submitting a **bug report** or a **feature request**?
**bug report**

### What is the current behavior?
File Upload throw Errors and I get a blank page after selecting

Component

```

import React from 'react'
import { Field, reduxForm } from 'redux-form';

export const FileUpload = (props) => {
    const { handleSubmit } = props;
    const onFormSubmit = (data) => {
        console.log(data);
    }
    return (
          <form onSubmit={handleSubmit(onFormSubmit)}>
            <div>
              <label>Attachment</label>
              <Field name="attachment" component="input" type="file"/>
            </div>
            <button type="submit">Submit</button>
          </form>
    )
}

export default reduxForm({
    form: 'fileupload'
})(FileUpload)

```

Console log:
`Warning: A component is changing an uncontrolled input of type file to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components`

### What is the expected behavior?
File upload/selecting works as expected.

### Sandbox Link
no

### What's your environment?
```
"dependencies": {
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-redux": "^5.0.6",
    "react-scripts": "1.0.17",
    "redux": "^3.7.2",
    "redux-form": "^7.2.0"
  },
```

### Other information
no

**Comment by Adiqq** [comment]
Yes, it crashes on react >= 16.0.0. 
Last working version:
```
"react": "15.6.2",
"react-dom": "15.6.2"
```

**Comment by irvingv8** [comment]
Any updates on this? Some guidance on where to look for in order to fix it would be nice

**Comment by stephencarr** [comment]
Having the same issue here. I've read a bunch about the problem and none of the workarounds I've seen actually result in success.

Others seem to be using a dropzone component to bypass the problem, but that's not really suitable for my UI. Thinking of how to use an uncontrolled component here and using refs to get the value and push it into the store /shrug.

**Comment by DarkBitz** [comment]
@stephencarr try that for as long

```
import React from 'react'
import { Field, reduxForm } from 'redux-form';

const adaptFileEventToValue = delegate => e => delegate(e.target.files[0]);

const FileInput = ({ 
  input: { value: omitValue, onChange, onBlur, ...inputProps }, 
  meta: omitMeta, 
  ...props 
}) => {
  return (
    <input
      onChange={adaptFileEventToValue(onChange)}
      onBlur={adaptFileEventToValue(onBlur)}
      type="file"
      {...props.input}
      {...props}
    />
  );
};

export const FileUpload = (props) => {
    const { handleSubmit } = props;
    const onFormSubmit = (data) => {
        console.log(data);
    }
    return (
          <form onSubmit={handleSubmit(onFormSubmit)}>
            <div>
              <label>Attachment</label>
              <Field name="attachment" component={FileInput} type="file"/>
            </div>
            <button type="submit">Submit</button>
          </form>
    )
}

export default reduxForm({
    form: 'fileupload'
})(FileUpload)
```

**Comment by stephencarr** [comment]
Thanks @DarkBitz. I only just found a similar solution here: https://github.com/erikras/redux-form/issues/1989#issuecomment-339839015

They actually work which solves my problem, I hope Google can surface these solutions - if I understood better why this works I'd be happy to document it.
