### ISSUE TITLE
INITIALIZE action is called twice when initialValues is presented

### ISSUE THREAD

**Issue by martinhorsky** [erikras/redux-form#3690]
### Are you submitting a **bug report** or a **feature request**?
**Bug** introduced by https://github.com/erikras/redux-form/pull/3615

### What is the current behavior?
`INITIALIZE` action is called twice when `initialValues` prop is used. This behaviour can cause problems with reinitializing props for the second time after values could be already changed (in `componentWillMount` of children of the form).

### What is the expected behavior?
Call `INITIALIZE` once. 

Do not call for the second time in `componentDidMount` or handle properly `initialized` in `this.initIfNeeded`, which is `false` after the first initialization in `componentWillMount`.

### What's your environment?
Redux Form 7.2.0 

### Other information
Bug was introduced in https://github.com/erikras/redux-form/releases/tag/v7.2.0 in bug fix called "Fixed hot reloading problem with React 16" https://github.com/erikras/redux-form/pull/3615

**Comment by jason-whitted** [comment]
Here are some working examples illustrating the issue:
- Not Working
  - [redux-form@7.2.0 - INITIALIZE is called after componentDidMount](https://stackblitz.com/edit/react-t2ydt1)
- Working
  - [redux-form@7.1.2 - INITITIALIZE is called before componentWillMount](https://stackblitz.com/edit/react-unyzfx)

**Comment by mikecit22** [comment]
Hi, I am having the same issue. The redux form called @@redux-form/INITIALIZE 2 times.

**Comment by aarosil** [comment]
I could confirm this introduced in 7.2, not happening in 7.1.2.

Thanks for the killer library!!!

**Comment by erikras** [comment]
Published fix in [`v7.2.2`](https://github.com/erikras/redux-form/releases/tag/v7.2.2).

**Comment by heavenlypeach** [comment]
I'm still having the same issue on v7.2.2
