### ISSUE TITLE
REMOTE SUBMIT relation to "<form onSubmit={handleSubmit}>"

### ISSUE THREAD

**Issue by martlaboloa** [erikras/redux-form#3691]
what is the point of writing `<form onSubmit={handleSubmit}>` if you have ONLY remote submit? if you already given your submit function to _reduxForm_, what does giving  handle submit to `form` component do?

**Comment by gustavohenke** [comment]
You are mixing concepts. But let's break the question down in two:

> if you already given your submit function to reduxForm, what does giving handle submit to form component do?

Redux Form only manages the many state changes of a form and its fields.

It doesn't iterate the render tree injecting any event handlers, which are necessary to know about such state changes. If it did this, it would not work with the composability of React.

> if you have ONLY remote submit?
Remote submit is what we call a dispatch of the [`submit` action](https://redux-form.com/7.2.0/docs/api/actioncreators.md/#-code-submit-form-string-code-).

Sometimes you need to trigger the submission from outside your form, and for these cases you can use the `submit` action. Normal submissions would use the `handleSubmit` within the `reduxForm` decorated component, eg from the click event of a button, or from the `submit` event of a form, etc.

I hope that answers your question.
