### ISSUE TITLE
Form value missing one step when initialized second time.

### ISSUE THREAD

**Issue by EroticCode** [erikras/redux-form#3695]
I have Form for Edit Item category , when i navigation for edit first time it's work great but second times form initialized always slow 1 step .

for example : click 1 : ok  , click 2 : value of click 1 , click 3: value of click 2.
i follow example code and who can say something wrong here.
Sr my ENG is stuied

`/* @flow */

// React
import React, { Component } from 'react';

//React Native
import {
  View
} from 'react-native';

//Navite Base
import { Item, Button, Text , Input } from 'native-base';

//Redux
import { Field,reduxForm } from 'redux-form';
import { connect } from 'react-redux'

//Style
import styles from '../styles';

//Child Component
import renderPicker from './renderPicker';
import renderInput from './renderInput';

//action Edit
import {load} from './defaultEdit';

//HandleSubmit
const submit = values => {
  this.props.onSubmit(values);
}
var index = 0 ;
class EditFormCat extends Component {
  constructor(props) {
    super(props);
  }
  componentWillMount() {
    console.log(index = index + 1);
    this.props.load(this.props.defaultData);
  }
  render() {

    const { handleSubmit, pristine, reset, submitting , onSubmit , CategoryData , defaultData } = this.props;
    return (
      <View>
        {/* Feild: name: variable in Redux , Component Layout Render */}
        <Field
          name="name"
          component={renderInput}
          label="Name"
        />
        <Field
          name="note"
          component={renderInput}
          label="Description"
        />
        <Field name="catParent" component={ renderPicker }>
          <Item label={"Chọn Category Cha"}/>
          {
            CategoryData.map( (item , index) => {
              return(
                <Item key={index} label={item.name} value={item._id} />
              );
            })
          }
        </Field>

        <View style={styles.coverBtn}>

          {/* Submit Form */}
          <Button
            onPress={handleSubmit}
            disabled={ pristine || submitting}
            style={styles.submitBtn}
          >
            <Text> Submit Form </Text>
          </Button>
          {/* Submit Form */}

          {/* Reset Form */}
          <Button
             light
             onPress={ () => reset() }>
             <Text >Reset Form</Text>
          </Button>
          {/* Reset Form */}

        </View>
      </View>
    );
  }
}

InitializeFromStateForm = reduxForm({
  form: 'EditFormCat' // a unique identifier for this form
})(EditFormCat)

InitializeFromStateForm = connect(
  state => ({
    initialValues: state.reducerCatDefault.data
  }),
  { load }
)(InitializeFromStateForm)

export default InitializeFromStateForm
`

**Comment by danielrob** [comment]
Sorry you never got an answer. It is challenging for me to understand your issue, and thus to treat it as an identifiable issue in redux-form. I will close since it has been six months, but feel free to try to re-explain your issue if you still have it.
