### ISSUE TITLE
form-wide onChange doesn't work on custom components

### ISSUE THREAD

**Issue by mrsufgi** [erikras/redux-form#3698]
### Are you submitting a **bug report** or a **feature request**?

Bug Report:

### What is the current behavior?

form-wide onChange doesn't fire when used with custom elements 

### What is the expected behavior?
custom elements should be able to trigger form-wide onChange 

### Sandbox Link

```js
 <form
        onChange={() => {
          console.log('hello');}}>
     <Field name="myField" component={renderField}/>
</form>
  ...
```

 this component implementation does trigger the onChange
```js 
const renderField = field => (
  <div className="input-row">
    <input {...field.input} type="text" />
    {field.meta.touched && field.meta.error && <span className="error">{field.meta.error}</span>}
  </div>
);
```

This doesn't 
```js 
const renderField = field => (
  <div className="input-row">
    <button
      {...field.input}
      onClick={() => {
        field.input.onChange(Math.random());
      }} type="button"/>
    {field.meta.touched && field.meta.error && <span className="error">{field.meta.error}</span>}
  </div>
);
```

I also checked the tests and it pass them with input, textarea and select but not with custom onChange calls. 

related to https://github.com/erikras/redux-form/pull/2576
Thank you so much for this package! amazing work!

**Comment by gustavohenke** [comment]
This is not the form-wide onChange we support 😄 
Please use it like this: https://codesandbox.io/s/771no3q7q

Also, [see the docs](https://redux-form.com/7.2.0/docs/api/reduxform.md/#-code-onchange-function-code-optional-)

**Comment by mrsufgi** [comment]
Hey! thanks for your help, 
I've been trying to create a form that saves on every change in any form field without needing to add specific onChange function to every field.

I've read other issues discussing that and they all pointed out that ``` <form onChange={onChange} ...>``` should solve it.  It does work with input/select/textarea like I mentioned earlier, but how will I can be able to use only one onChange handler in my form?

a workaround idea I had might be adding a hidden input component to the custom component and it will trigger the form-wide onChange (not really sure that will work though :P)

maybe I got it wrong, but by saying 'form-wide onChange' do you mean 'onChange callback for every field component' or 'onChange callback for the form element'

Thanks again!

**Comment by gustavohenke** [comment]
See my sandbox above.
The `onChange` handler is passed as a setting to the `reduxForm()` decorator.

**Comment by mrsufgi** [comment]
Oh! thank you so much! it works! <3

**Comment by marcboehret** [comment]
@gustavohenke can you tell me how i can call handleSubmit from inside the onChange function? i get access to the props, but there is no handleSubmit available.

**Comment by harrisrobin** [comment]
@marcboehret 

What i did is simply import my store and dispatch the action in there, like so:

```js
export default compose(
  connect(mapStateToProps, null),
  reduxForm({
    form: "schedulerWizard",
    destroyOnUnmount: false,
    forceUnregisterOnUnmount: true,
    onChange(values) {
      store.dispatch(SchedulerActions.fetchScheduledRequest())
    }
  })
)(WizardFormFirstPage)
```
