### ISSUE TITLE
formValues names with dash issue

### ISSUE THREAD

**Issue by AlexanderTserkovniy** [erikras/redux-form#3702]
### Are you submitting a **bug report** or a **feature request**?

**bug report**

### What is the current behavior?

`formValues('name', 'name-with-dash')` `name` is ok, but cannot be get `name-with-dash` anyhow...
tried `formValues({name: 'name', 'name-with-dash': 'nameWithDash'})` did not work.

### What is the expected behavior?

some of the way to work.

### What's your environment?

React 16.
React form 7.2.0.

**Comment by gustavohenke** [comment]
Please provide a sandbox that reproduces your issue.

This sandbox here works fine: https://codesandbox.io/s/j4plwr93kw

**Comment by AlexanderTserkovniy** [comment]
@gustavohenke thanks for the sandbox, I do not know why but it just started working... I would not write here if it worked.
