### ISSUE TITLE
Issue on plug redux-form with react native

### ISSUE THREAD

**Issue by mbdry** [erikras/redux-form#3707]
I got an issue when I try to plug redux-Form Field with a text input component in react native. The input form is empty each time I try to write in it.

here is my code :

````
import React, { Component } from 'react'
import { View, Text, TextInput, TouchableOpacity } from 'react-native'
import { reduxForm, Field } from 'redux-form'

import Styles from '../../Themes/Containers/Create'
import FormStyles from '../../Themes/Containers/Form'

let CreateScreen = class CreateScreen extends Component {
  onSubmit = (formData) => {
    console.log('formData', formData)
  }

  renderInput = ({input}) => {
    return <TextInput style={FormStyles.input} onChange={input.onChange} {...input} />
  }

  render () {
    const { handleSubmit } = this.props

    return (
      <View style={Styles.container}>
        <Text style={FormStyles.label}>Nom du support</Text>
        <View style={FormStyles.inputContainer}>
          <Field name='name' component={this.renderInput} />
        </View>
        <TouchableOpacity onPress={handleSubmit(this.onSubmit)}>
          <Text>Submit</Text>
        </TouchableOpacity>
      </View>
    )
  }
}

CreateScreen = reduxForm({ form: 'create' })(CreateScreen)

export default CreateScreen
````

Here is the behavior:

![issue](https://user-images.githubusercontent.com/32486006/34264825-64b727d2-e674-11e7-9753-aae628173eec.gif)

It seems it's the property value that reset the current state of the input form when I write in the input form. Furthermore, when I submit my form, there is no data in it... empty object. I tried to replace onChange by onChangeText but the problem is the same.

Thanks a lot !

**Comment by gustavohenke** [comment]
There's nothing wrong with your form code, so I assume it must have something to do with how your reducer was set up.

**Comment by mbdry** [comment]
I'm a beginner with react native. How reducer can influence how the form work ? For the moment, that's a simple view with one input, where I want to get the value on click submit. There is no binding with reducer.

Thanks for your help :)

**Comment by gouxlord** [comment]
@mbdry Did you actually plug redux-form into redux?

**Comment by mbdry** [comment]
Damn it ! You save my day guys ! I found my problem in the reducers config !

Thanks a lot !
