### ISSUE TITLE
clearAsyncError export and documentation are missing

### ISSUE THREAD

**Issue by keenondrums** [erikras/redux-form#3708]
### What is the current behavior?
clearAsyncError documentation is missing at https://redux-form.com/7.2.0/docs/api/actioncreators.md/
clearAsyncError export is missing at lib/index.js

### What is the expected behavior?
clearAsyncError documentation is present at https://redux-form.com/7.2.0/docs/api/actioncreators.md/
clearAsyncError export is present at lib/index.js

**Comment by keenondrums** [comment]
Created a PR for it https://github.com/erikras/redux-form/pull/3709

**Comment by erikras** [comment]
Published fix in [`v7.2.1`](https://github.com/erikras/redux-form/releases/tag/v7.2.1).
