### ISSUE TITLE
InitialValues isn't working.

### ISSUE THREAD

**Issue by juliano-barros** [erikras/redux-form#3714]
### Are you submitting a **bug report** or a **feature request**?
Bug Report or something goes wrong.

### What is the current behavior?
I'm using mapStateToProp to set some variables from redux, in this case, I'm trying to fill initialValues on that, and it isn't working, I'll paste the code here. I'd like to say that if I put a constant on initialValues it works so well. So, I don't know what is going on. Probably it is working only when you get values on the first entered, because firstly my values come empty, but after a couble of ms the reducer catch new values and initialValues it is modified by mapStateToProps.

```js
import React, { Component } from 'react';
import { connect } from 'react-redux';
import { Link } from 'react-router-dom';
import { Field, reduxForm, formValueSelector } from 'redux-form';
import { profileRequest } from '../../actions/profile_actions';

class ProfileIndex extends Component {

	onSubmit(values){
	}

 	renderField(field){

	    const { meta: { touched, error } } = field;
	    const className=`form-group ${ touched && error ? 'has-error' : ''} has-feedback`;

 		return( 
  		    <div className={className}>
                  <label >{field.placeholder}</label>
  		    	<input className="form-control" type={field.type} {...field.input} />
        		<div className ="help-block">
          			{ touched ? error : '' }
        		</div>
  		    </div>
		);

 	}

	render(){
		const {handleSubmit} = this.props;
		return (

			<div>
			    <section className="content-header">
			      <h1>
			        Profile
			        <small>Profile</small>
			      </h1>
			      <ol className="breadcrumb">
			        <li><i className="fa fa-dashboard"></i> profile</li>
			        <li className="active">profile</li>
			      </ol>
			    </section>
				<div className="row">
					<form onSubmit={handleSubmit(this.onSubmit.bind(this))}>
						<div className="col-sm-6">
						</div>
						<div className="col-sm-6">
				          	<Field
			            	  name="name"
				              component ={this.renderField}
				              type="text"
				              placeholder="Nome"
				            />
				          	<Field
			            	  name="email"
				              component ={this.renderField}
				              type="text"
				              placeholder="E-mail"
				            />
						</div>
			            <button type="submit" className="btn btn-primary pull-right"> Salvar </button>
					</form>
				</div>
			</div>

		)
	}
}

function mapStateToProps({profile}){
        console.log(profile);
	return { profile, initialValues: profile };	
}

function validate(values){

	const errors ={};

	return errors;
}

ProfileIndex =  connect(mapStateToProps, {profileRequest})(ProfileIndex)

export default reduxForm({	
	validate, 
	form: 'profile_form_index'
})(ProfileIndex) 
```

if I change mapStateToProps for the code below works fine.

function mapStateToProps({profile}){
        console.log(profile);
	return { profile, initialValues: {name: 'teste 1', email: 'teste 2' } };	
}

I'll paste here console log picure about variable profile on mapStateToProps to see what is comming from reducer

![image](https://user-images.githubusercontent.com/22324139/34343781-157b7f62-e9ba-11e7-936d-42db263910f5.png)

### What is the expected behavior?
Form starts with default values that is load by reducer.

**Comment by gustavohenke** [comment]
Hello @juliano-barros,
There's nothing wrong with your code. It's likely something else in your set up, as the docs examples work fine.
In this case, please migrate your question to StackOverflow, as we don't provide support in our GitHub issue tracker. Don't forget to provide a working example!

*Feliz Natal* 🎅

**Comment by juliano-barros** [comment]
Hey Gustavo, Merry Christmas, I created a sandbox project and even doesn't work properly, I don't know why. I have tried to figure it out at least 2 entire days and I didn't find any solution. I'll put the link to sandbox below if someone could help me I'd really appreciated that. I'll put on StackOverflow as well, thanx anyway.

https://codesandbox.io/s/6k85yv8k3
