### ISSUE TITLE
formReducer can't be accessed

### ISSUE THREAD

**Issue by Hiroki1116** [erikras/redux-form#3716]
The current behavior

When I try to get a value in form reducer, it disappears and becomes undefined.

Here is a component which has `Redux-Form`.

    class Form extends React.Component {
        render() {
            return (
            <div>
                <form onSubmit={handleSubmit}>
                <Field name="title"
                       component="input"
                        type="text"/>
                </form>
            </div>
            )
        }
    }

    Form = reduxForm({
        form: 'PostEditor',
        enableReinitialize: true,
    })(Form);

    Form = connect(
        state => ({
            initialValues: state.post.post,
            enableReinitialize: true,
        }),
    )(Form)

    export default Form;

And here is a container of it.

    class PostEditor extends React.Component {
        render() {
            console.log("form", this.props.PostEditor);//This results in "undefined"
            return (<Form onSubmit={data=> this.handleSubmit(data, push)}/>);
        }
    }

    const mapStateToProps = (state) => {
        return {
            PostEditor: state.form
        }
    }
    export default connect(mapStateToProps, null)(PostEditor);

The expected behavior

There should be the form reducer's values displayed in console.log, but the result is the following.

![console](https://user-images.githubusercontent.com/9676341/34353237-b567d81e-ea72-11e7-80a3-33b7ed7cdac1.png)

As you can see, the value becomes `undefined`, even though it was there.

How can we get a value from the form reducer in another component while you're editing the form?

Any advice will be appreciated.

**Comment by gustavohenke** [comment]
Make sure your reducer is properly set up.
Check the [getting started guide](https://redux-form.com/7.2.0/docs/gettingstarted.md/) in case you need help with it, or ask on StackOverflow.

Thanks for using Redux Form!
