### ISSUE TITLE
Can I get values from store directly?

### ISSUE THREAD

**Issue by xcatliu** [erikras/redux-form#372]
Is there anyway to get `values` from `store`, not from `onSubmit`?

**Comment by erikras** [comment]
Your component is given a `values` prop with all of them.

**Comment by xcatliu** [comment]
What if I want to get `values` out of the component? For example:

```js
const FormCreatedByRedux = reduxForm({
  form: 'simple',
  fields
})(SimpleForm);

class ParentComponent extends Component {
  render() {
    return (
      <FormCreatedByRedux/>
    );
  }
}

// action creator
export function submitForm() {
  return (dispatch, getState) => {
    // Can I get values here?
  }
}
```

**Comment by erikras** [comment]
That is not currently supported, no, but it might be in the future.

**Comment by xcatliu** [comment]
Thanks for answering me, I have written an util function to do this, paste here if someone need.

```js
/**
 * A tool to get values from store directly.
 *
 * Warning, currently not support Deep Forms format.
 * For more information, visit https://github.com/erikras/redux-form/issues/372
 *
 * @param {Object in Store} the form object in store,
 * usually use `getState().form.formName` to get it.
 *
 * @returns {Object} the form values, same format with redux-form's values.
 *
 */
export default function getFormValues(form) {
  if (!form) return {};
  return Object.keys(form).filter((key) => !key.startsWith('_')).reduce((prev, key) => {
    prev[key] = form[key].value;
    return prev;
  }, {});
}
```

**Comment by erikras** [comment]
[Published in `v3.1.7`](https://github.com/erikras/redux-form/releases/tag/v3.1.7).

**Comment by yanndinendal** [comment]
@erikras it is droped in v6, correct?

**Comment by darkyen** [comment]
Since this is dropped in v6 what is the v6 way of previewing things on the client? I have a form that accepts html I render the html on client (side by side). I don't want the client to submit everytime, get it straight from the store?

**Comment by Olliebaba** [comment]
@erikras - I have a huge form which needs a custom auto complete component.  Since docs states that the formValueSelector forces the entire form to re-render I looked for an alternative. A work-around I found for this is creating an inputCurrentValue property in the container's state. This is fed down,  through the form and to the auto complete component. The input's normalize function updates inputCurrentValue.

Can you see any issue with this approach?

**Comment by ravindraranwala** [comment]
This can be done. Check out my answer [here ](http://stackoverflow.com/questions/43999623/how-to-provide-validations-for-react-js-form/44005986#44005986)in stackoverflow.

**Comment by Nopzen** [comment]
@ravindraranwala solutiomns worked for me :)

**Comment by finom** [comment]
Guys I've used the following solution when needed to get values without direct accessing to store: https://gist.github.com/finom/909e1162003e6b1214d907e04143d56f

**Comment by emjaksa** [comment]
If you are worried about unnecessary re-renders you can get the form values like so.

```
...
import { getFormValues } from 'redux-form'
...

class MyComponent extends Component  {
  // Access store by defining context types
  static contextTypes = {
    store: PropTypes.object,
  }

  // Getter function
  get values() {
    // Get the redux store from context
    const { store } = this.context
    const state = store.getState()
    // Get the form values using the redux-forms getFormValues selector function
    return getFormValues('form-id')(state)
  }

  render() {
    const formValues = this.values
    // Do what you want with the values
    ...
  }
}
```

I have only tested this using v7 of redux-form

**Comment by golestanirad** [comment]
@ravindraranwala     I am trying to access the value of my form in another component, any idea how to do that? https://stackoverflow.com/questions/49591409/how-to-access-redux-form-values-in-another-component
