### ISSUE TITLE
Using connect and redux-form throws ref error

### ISSUE THREAD

**Issue by garstikaitis** [erikras/redux-form#3721]
Hello to you, redux-form community,

I am experiencing weird issue with using redux connect and reduxForm in my components. The error is saying: <br> ``Element ref was specified as a string (wrapped) but no owner was set. You may have multiple copies of React loaded``<br>
My export statement looks like this: <br>
```
LoginPage = reduxForm({
  form: 'loginForm',
})(LoginPage);
export default connect(state => ({ authentication: state.authentication }), {
  login,
})(LoginPage);
```
Since it is FAQ, that is weird that I have this issue: [FAQ reference](https://redux-form.com/7.2.0/docs/faq/howtoconnect.md/ )

Anyone has experienced it? If so, any fix for it?

**Comment by gustavohenke** [comment]
Your use of `connect` and `reduxForm` is correct, so the problem must be somewhere else.
Also note that our GitHub issue tracker is not the right place to ask for usage support questions. Please use StackOverflow for that.
