### ISSUE TITLE
Pass props to children

### ISSUE THREAD

**Issue by theaqua** [erikras/redux-form#373]
Hi!
I have 1 container (for example, `Contact.jsx`) and multiple components (`About.jsx` and etc).
When I trying pass props to children (`<About {...props} />` or using react-router and `{props.children}`), they have gone, children doesn't have `redux-form`'s props (but `react-router`'s or `redux`'s works well). 
Why? It will be super-useful if we can pass props to children — we don't need to create multiple forms, just have 1 in container.

**Comment by erikras** [comment]
Which component is decorated with `reduxForm()`?

Props that you pass to a decorated redux-form component _are_ passed down to the wrapped component, so I'm confused as to your component structure.

**Comment by theaqua** [comment]
@erikras container is decorated with `reduxForm`. Children don't.

**Comment by erikras** [comment]
I need to see an example to understand what you are trying to accomplish. In React, props don't filter down to all the `props.children` unless they are passed.

**Comment by theaqua** [comment]
It's React's problem.

If we have
```
props == { foo: `bar`, bar: `foo` };
<div>
  <Child {…props}>
    <ChildOfChild />
  </Child>
</div>
```

Where
```
Child = <div>{props.children}</div>
```

React lose props for `ChildOfChild`, but in `Child` everything is ok. Very strange behavior, but I solved it with `{React.cloneElement(children, props)}`.

Sorry for your time and thanks for redux-form, it's works like magic ❤️
