### ISSUE TITLE
Allow extra custom metadata when registering a field

### ISSUE THREAD

**Issue by alexanthony** [erikras/redux-form#3730]
### Are you submitting a **bug report** or a **feature request**?
Feature Request

### What is the current behavior?
The REGISTER_FIELD action has the following data:

- type: REGISTER_FIELD
- meta: form name
- payload: field name and type

### What is the expected behavior?
Allow specifying extra metadata that gets included on the action.

For example:
```
<Field
  name="forename"
  component="input"
  meta={{section: 'personalDetails'}}
/>
```

would give an action of something like this when mounted:
```
{
  type: '@@redux-form/REGISTER_FIELD',
  meta: {
    form: 'myForm',
    custom: {section: 'personalDetails'}
  },
  payload: {
    name: 'forename',
    type: 'Field'
  }
}
```

The custom meta could either be included in the registeredFields section of the reducer, or just be ignored by the redux-form reducer and we would listen for it separately.

Our use case is to have runtime information on which fields are in which sections of the form, but there would probably be other uses. (We can't change our API structure, and we don't want to have to maintain a mapping between a UI data structure and an API data structure). Other workaround would be to do this on mount of our own wrapper component, but it seems like duplication.

It's pretty simple to implement, non-breaking. I'd be happy to implement it if the PR would be accepted.

**Comment by Syynth** [comment]
Having something like this would be a huge help for us as well. The other thing that would need to go along with this is a selector to allow access to the registered fields data, which I believe doesn't currently exist. I fiddled with implementing this myself and 90% of the work was just updating tests, but like the opening comment says, if there's any signal this would be accepted I'd be happy to share.

**Comment by gustavohenke** [comment]
Using Redux Form API to store data that has nothing to do with the rest of the library doesn't sound right.

One could simply write a reducer that listens to `REGISTER_FIELD` actions. It's the same thing while not adding complexity to this already complex library.

**Comment by alexanthony** [comment]
@gustavohenke There's another side to this too - allowing adding extra metadata onto the REGISTER_FIELD action. I'm happy to store the extra data in a separate reducer, but we can't currently add the extra metadata to the action.

**Comment by Syynth** [comment]
That's exactly the issue for me. I would like to generate a checklist for each form, but I need a way to mark the fields as required/etc.
