### ISSUE TITLE
Keyup, how do I prevent submit form the default behavior of the enter key?

### ISSUE THREAD

**Issue by nghiepit** [erikras/redux-form#3732]
Hi guys,

I have a problem with the input field.

Sometimes, I want to prevent submit form when I press enter on the input field.

I'm trired, but any not work.
```
event.preventDefault();
event.stopPropagation();
event.nativeEvent.stopImmediatePropagation();
```

Thank in advance.

**Comment by oscarlnetoo** [comment]
Hi @nghiepit,

I am having the same issue. 
Did you resolve the problem?
