### ISSUE TITLE
v5 remove array field by predicate function

### ISSUE THREAD

**Issue by danikkks** [erikras/redux-form#3738]
### Are you submitting a **bug report** or a **feature request**?

**feature request**

### What is the current behavior?

User can delete array value only by index

### What is the expected behavior?
User can delete array value by predicate function

### Other information

In some large forms with lot of array fields order of fields mapped to component is different from fields in store, and you can`t delete right field by index

**Comment by gustavohenke** [comment]
Since your PR was merged, I'll close this.
