### ISSUE TITLE
How not to disable submitting form when form submission fails because of server-side validation?

### ISSUE THREAD

**Issue by allantatter** [erikras/redux-form#374]
Let's say we have a login form, you provide the credentials and try to submit the form. Then the server responds with some kind of error, for example "User not activated yet, check your inbox.", and form submission is then disabled until the field is changed which was invalid. I'd like the form not to be disabled in any case, when server-side validation fails.

How to accomplish that?

**Comment by erikras** [comment]
Nothing about `redux-form` is disabling your form. If you have a `disabled={invalid}` on your submit button, you could remove that, but how you display errors and process them is up to you.

**Comment by allantatter** [comment]
Weird, nothing on my side looks like disabling the form. BTW, I'm using `redux-form` v2.*.

This is my component:

```
import React, {Component, PropTypes} from 'react';
import {connectReduxForm} from 'redux-form';
import validateLogin from 'forms/validation/validateLogin';
import Input from 'forms/fields/Input';

class Login extends Component {
  static propTypes = {
    fields: PropTypes.object.isRequired,
    handleSubmit: PropTypes.func.isRequired,
    submitting: PropTypes.bool.isRequired
  }

  render() {
    const { fields: {email, password}, handleSubmit } = this.props;

    return (
      <form className="login-form" onSubmit={handleSubmit} method="post" noValidate>
        <Input type="email" label="Email" field={email}/>
        <Input type="password" label="Password" field={password}/>

        <button className="btn btn-success">Login</button>
      </form>
    );
  }
}

Login = connectReduxForm({
  form: 'login',
  fields: ['email', 'password'],
  //validate: validateLogin
})(Login);

export default Login;
```

Where `handleSubmit()` returns rejected promise with errors. I commented out the validate mehtod in order to be sure, that it's not related to front-end validation.

Also, `Input` component:

```
class Input extends Component {
  static propTypes = {
    label: PropTypes.string.isRequired,
    type: PropTypes.string.isRequired,
    field: PropTypes.object.isRequired
  }

  render() {
    const { label, type, field } = this.props;

    return (
      <div className="form-group">
        <label className="form-field">
          <span className="label">{label}</span>
          <input type={type} {...field} className="form-control"/>
        </label>
        {field.error && field.touched && <div className="field-error">{field.error}</div>}
      </div>
    );
  }
}
```

**Comment by ooflorent** [comment]
I'm closing this issue since it is an usage question, and we encourage you to ask it on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

**Comment by mikeengland** [comment]
I am also running into the same issue. If a promise returns an error during submission, you cannot re-submit the form unless you have made a change to a field. This can be confusing if a server error is returned by the promise and not an error with the form that has been handled server side. I believe this is what @allantatter was experiencing?

**Comment by joegalley** [comment]
@mikeengland @allantatter Yes I'm experience the same thing also.
