### ISSUE TITLE
Manually trigger onSubmitFail

### ISSUE THREAD

**Issue by foxCanFly** [erikras/redux-form#3740]
Hi guys,
The problem was appeared when we started using `redux-saga` with `redux-form`. Because of Saga manage all side-effects I can't simply return a promise from `submit` function. In case if I return promise from `submit` function everything works fine. 
And when we get errors from the server we simply dispatch `stopSubmit` action which doesn't trigger `onSubmitFail` callback but set `submitFailed: true`. 
Could you give me any piece of advice how to solve this problem...

```
submit = (values) => {
   this.props.createSomethingRequest(values);
};
```

My `submit` just dispatch action. And then Saga get this action and start doing all async stuff.

If some errors:
```
yield put(stopSubmit(FORM_NAME, { ...errors }));
```
But `stopSubmit` doesn't trigger `onSubmitFail` callback... Is there any way to trigger this callback?

**Comment by gustavohenke** [comment]
There are some workarounds available if you search either in the redux-saga or redux-form repos.

For now, I'll close this issue in favor of #3235. Feel free to continue the discussion.
