### ISSUE TITLE
values of number inputs are being stored as strings in the state 

### ISSUE THREAD

**Issue by femto11** [erikras/redux-form#3752]
The following was seen with redux-form 7.2.0: 

Values of number inputs are being stored in the as strings in the form's state.

This caused me some headache when applying some mathematical opaerations on these values. Even typescript couldn't detect this problem.

The work around I'm using now involves multiplying any value comning from the state that should be number by 1. It works but it is some kind of ugly.

**Comment by x2764tech** [comment]
@femto11 the usual(?) way of (unsafely) converting a string to a number is using `+`, eg:
    
    var aNumberAsAString = "5";
    console.log(+aNumberAsAString  + 6)

Also, see the [`normalize`][normalize] property of a `Field`:

    <Field 
        name="something" 
        normalize={(value) => +value} 
        validate={(value) => isNaN(+value) ? "Please enter a number" : undefined} />
(I haven't tested this, and it isn't from production code)

However, you probably want some checking in case the browser doesn't support `<input type=number>` or doesn't enforce the value is a number 

[normalize]: https://redux-form.com/7.2.0/docs/api/field.md/#-code-normalize-value-previousvalue-allvalues-previousallvalues-gt-nextvalue-code-optional-

**Comment by femto11** [comment]
Thank you! It works but still feels a bit redundant. At least for the case of Inputs of type number. I had another case of a select where the key was numeric. I agree that an automatic would not be so easy there.

**Comment by x2764tech** [comment]
> It works but still feels a bit redundant

Unless you tell it to, redux-forms doesn't do any processing of what the component's `value` - and the `value` of an `input` is always of type `string` (see [NumbersState] and probably some other bits)

You could create an NumericInput component, something like (DO NOT USE THIS IN PRODUCTION)

    const NumericInput = ({props, onChange, value}) => /*DO NOT USE THIS IN PRODUCTION*/
      <input type="number" {...props} value={+value} onChange={({target}) => onChange(target.valueAsNumber)} />;

and then use that, something like:

    <Field name="something" component="NumericInput" />

If you take this route, I'd suggest a thorough reading of the [Field Docs][Fields]

[Fields]: https://redux-form.com/7.2.1/docs/api/field.md/

**Comment by danielrob** [comment]
Thanks @x2764tech.
