### ISSUE TITLE
Input Masking

### ISSUE THREAD

**Issue by dawidvdh** [erikras/redux-form#376]
Hi, I was just wondering if there would be any way to do input masking, like spacing numbers out etc?

**Comment by iNikNik** [comment]
This is called `normalization` -> http://erikras.github.io/redux-form/#/examples/normalizing?_k=3d2f7v

**Comment by dawidvdh** [comment]
yes fair enough thank you, but then the data itself will contain spaces and such in the store? i need it to be purely visual, for example a number i need to be displayed as "000 000 0000" but in the store i need it to be "0000000000" as i need to send that data off. or am i really just mistaken at this point and it is really only visual?

**Comment by erikras** [comment]
The normalizing _does_ change the data in the store, but if you really want to strip spaces or parse a currency or something, you can do that in your `onSubmit` function before actually sending the data to the server.

**Comment by dawidvdh** [comment]
awesome thank you, was my reasoning as well just wanted to know if there was a better way. awesome project btw!

**Comment by msafi** [comment]
I think a better design would be to have the ability to provide a masking function on the input field directly that is for presentational purposes and doesn't change the data.

**Comment by erikras** [comment]
@msafi It would not be too difficult to make a function...
```js
const {fields: {phone}} = this.props;
const normalizedPhone = normalize(phone, formatPhone, parsePhone);
return <input type="text" {...normalizedPhone}/>;
```
...that would take a formatter/parser pair and wrap the `onChange`, `onBlur`, and `value` props with that logic.

**Comment by ernani** [comment]
My normalize are declared via JSX and they are somewhat slow when typing, doing some date masking. Perhaps there is a better alternative to do so that is triggered in onBlur instead of onChange. Any help? Thanks!

**Comment by stilllife00** [comment]
@erikras Could you please elaborate on the `normalize` function example ? my scenario is to always show an input text containing a date formatted DD/MM/YYYY but store it in redux always as ISO valid date (YYYY-MM-DD). In this case I would like to avoid the `onSubmit` because I want this conversion done automatically for any Date field of my forms

**Comment by clindsey** [comment]
@stilllife00 maybe something like this - 
```javascript
const normalize = (field, parseFn, formatFn) => ({
  ...field,
  value: formatFn(field.value),
  onChange: value => field.onChange(parseFn(value)),
  onBlur: () => field.onBlur(parseFn(field.value))
})
```

I recommend using [moment.js](https://momentjs.com/) to work with dates in javascript, it'll make writing `parseFn` and `formatFn` very simple -

```javascript
const parseFn = value => moment(value, 'DD/MM/YYYY').format('YYYY-MM-DD') // store format

const formatFn = value => moment(value, 'YYYY-MM-DD').format('DD/MM/YYYY') // presentation format
```

The initial value of the date will also need to be valid.

**Comment by renato-bohler** [comment]
Just for the record, if there's anyone out there wanting to create input masks using redux-form, I've made a library specifically to solve this problem.

Take a look at [`redux-form-input-masks`](https://github.com/renato-bohler/redux-form-input-masks) ([API documentation here](https://renato-bohler.github.io/redux-form-input-masks/#/)).

**Comment by nbkhope** [comment]
@erikras @clindsey thank you for the example. There is still an issue when you go onBlur that the normalization is not applied. Could you guys elaborate on that event?

**Comment by danielrob** [comment]
@nbkhope onBlur does the default onChange action by default. You will need to update it the same way you did with onChange: 
```
  onBlur: value => field.onChange(parseFn(value))
```
