### ISSUE TITLE
React Bootstrap select dropdown

### ISSUE THREAD

**Issue by AdoniRakesh5420** [erikras/redux-form#3762]
I'm unable to get dropdown data that im passing. The html is not built with option lists only input field is coming.

My code looks like:

import  React from 'react';
import PropTypes from 'prop-types';
import { FormWithConstraints, FieldFeedback } from 'react-form-with-constraints';
import { FieldFeedbacks, FormGroup, FormControlLabel, FormControlInput } from 'react-form-with-constraints-bootstrap4';

class Select extends  React.Component{

    handleChange(event) {
        //event.target.value
        //do required changes
    }

    render(){
        return(
                <FormGroup for={this.props.name}>
                    <FormControlLabel htmlFor={this.props.name} style={styles.lableStyle}>{this.props.label}{this.props.required?<b
                        style={{color: "#2c3d4d"}}>*</b>:null}</FormControlLabel>
                    <FormControlInput
                        id={"Source"}
                        label={this.props.label}
                        placeholder="Select Country"
                        type="text"
                        // value={this.props.value}
                        onChange={this.handleChange}
                            // (event)=>{
                            // this.handleChange(event);
                            // this.props.onChange(event);

                        // }}
                        options={this.props.dropDownList}
                        required={this.props.required}
                        className="form-control"
                        optionsKey="name"
                        optionsValue="id"
                        // readOnly={this.props.readOnly}
                        // onClick={this.props.onClick}
                    />
                    <FieldFeedbacks for={this.props.name} className="form-control-feedback"
                                    style={styles.errorStyle}>
                        <FieldFeedback when="valueMissing" />
                        {(this.props.required)?
                        <FieldFeedback when={value => /^ *$/.test(value)}>Please enter valid text</FieldFeedback>:null}
                    </FieldFeedbacks>
                </FormGroup>

        );
    }
}

and the drop data looks like
dropDownList=[
        {name: "NAme",id:1,key:"Key"}];

**Comment by Madao088** [comment]
You are not using redux-form

**Comment by AdoniRakesh5420** [comment]
Why redux-form is required? I'm using react-form-with-constraints-bootstrap4 which is solving my input field validation

**Comment by Madao088** [comment]
options is redux-form property

**Comment by Madao088** [comment]
You've posted this issue in the wrong forum. You are mixing two completely different things,redux-form and react bootstrap. options is a property used in redux-form.
