### ISSUE TITLE
redux-form v7 and type="file"

### ISSUE THREAD

**Issue by wapgear** [erikras/redux-form#3763]
In v5 I remember examples and methods to work with _type="file"_, but in v7 I dont see anything about that, I tried to just use it as-is, I mean <input type="file" but without results.

Can somebody send me examples with type="file" for version 7?

**Comment by Madao088** [comment]
html field->
<Field name="picture" component={file_upload} type="file" className='form-control' />

file_upload component->
const file_upload= ({ input, type, meta: { touched, error, warning } }) => {
  delete input.value

  return (
    <div>
      <label htmlFor={input.name}>
        <input {...input} type={type}/>
      </label>
    </div>
  )
}

**Comment by wapgear** [comment]
My bad. I found example.

[Here](https://github.com/erikras/redux-form/issues/1989#issuecomment-287552919)
