### ISSUE TITLE
Data grids in forms

### ISSUE THREAD

**Issue by ydsood** [erikras/redux-form#3765]
### Are you submitting a **bug report** or a **feature request**?

Possibly a feature request, although might be an already existing feature

### Other information
A frequent requirement from forms in the application I am building is supporting One to Many type of related objects to the primary resource being created via the form. For example, adding multiple addresses to a customer information form. What would be the preferred UI construct/component for supporting something like this when using a redux form.

In the existing application this has been supported via data grids that load previously existing information for this form (saved forms) that is available for editing and also allow adding new records at the same time. This grids come with a lot of additional features like resizable columns, sorting data in columns etc.

Is there a preferred way to support this. If so, can someone please point me to a reusable component.

**Comment by gustavohenke** [comment]
You probably want to have a look at the [Field Array example](https://redux-form.com/7.2.1/examples/fieldarrays/).

For more usage support, please ask on StackOverflow.

**Comment by ydsood** [comment]
Thanks for your response. I was able to create a grid implementation that allows for injection of custom field types. Shared the implementation with MIT license [here](https://github.com/ydsood/grid).
