### ISSUE TITLE
add multiple forms in the same page 

### ISSUE THREAD

**Issue by ilkerceng** [erikras/redux-form#3769]
i have worked around [this fieldsarray example](https://redux-form.com/6.5.0/examples/fieldarrays/). I understand how members added multiple times in the same page. But what about if i want to add each new member separately. The current page should keep list of members. And each member should be added as a separate form. And i want to show the current members in redux state in a list in the same page to be able to edit on click on the member item. Like a todo list example.
The scenario: 
'add member' -> open the form-> fill the form -> click 'save' -> as a result: add member to list of members in redux state.
'add member' -> open the form-> fill the form -> click 'cancel' -> as a result: the member is not added to list of members in redux state.

**Comment by ilkerceng** [comment]
And i think it can be great to have todo list example in the docs.

**Comment by gustavohenke** [comment]
That's quite a specific example. Won't be a good addition to the docs.
