### ISSUE TITLE
push new item to field array from parent field array

### ISSUE THREAD

**Issue by tsamsiyu** [erikras/redux-form#3770]
### Description

Hi, I have form with following format of fields:

    { groups: [ { words: [{}] } ] }

At now when I'm working with FieldArray component 

    <FieldArray name="groups" component={myGroupRenderer}/>

in `myGroupRenderer` function, library passes me the `fields` of groups and I can manipulate them (push, remove). It would be nice to have possibility to manipulate also the child `words` like this:

    function myGroupRenderer ({fields}) {
        return <button onClick={ () => fields.at(0).child('words').push({}) } />
    }

As I understand to add groups outside of `myGroupRenderer` function, I can do `this.props.array.push('groups', {})` and it's work fine, but if I want to push new item that requires specifying index of its parent - I don't have ability to do this.

### Are you submitting a **bug report** or a **feature request**?
feature request

### What's your environment?
redux-form: 7.2.1

**Comment by gustavohenke** [comment]
Probably not a feature we would add.

A few ways you could work around this are:
- Use [`change` action creator](https://redux-form.com/7.3.0/docs/api/actioncreators.md/#-code-change-form-string-field-string-value-any-code-)
- Get the value at that index, remove it, change the value however you want, and insert it at the same index

There are certainly more ways, but I can't think of them now.
