### ISSUE TITLE
Snapshot testing in my project getting failed after upgrading to v7.2.1

### ISSUE THREAD

**Issue by sharvit** [erikras/redux-form#3771]
### Bug report

After upgrading from `v7.2.0` to `v7.2.1` one of our snapshot testings in [foreman](https://github.com/theforeman/foreman) is getting failed.

Test result:
https://travis-ci.org/theforeman/foreman/jobs/330761776#L4877

Test code:
https://github.com/theforeman/foreman/blob/develop/webpack/assets/javascripts/react_app/components/bookmarks/form/form.test.js#L35

I am still investigating how the upgrade is affecting my project, but, nothing is getting break when running the app, **only when running tests with jest**.

**Are there any breaking changes in this patch?**
* I can see you migrated from `return error` to `throw error` in this version, can it be the reason?

##### Travic CI
node versions: v8, v6.10, v6

##### Fedora
node version 8 (lts)

Thanks!

**Comment by gustavohenke** [comment]
Can you test with newer versions?

Also please take into account that a patch update means a bug fix.
If a prop value was incorrect because of bug, then we can't do nothing about it. We wouldn't release a major version because a bug was fixed and a prop value changed.
