### ISSUE TITLE
Input loses focus after first type

### ISSUE THREAD

**Issue by stilllife00** [erikras/redux-form#3778]
### Are you submitting a **bug report** or a **feature request**?
**bug report**

### What is the current behavior?
When I start typing on a input using a custom component, after the first character typed the input looses focus.

### What is the expected behavior?
I should be able to keep typing without loosing focus

### Sandbox Link
https://codesandbox.io/s/nwj3220qmp

### What's your environment?
See the sandbox, tested on latest Chrome on Windows

### Other information
Reproducible also with 7.2.0, it seems related with the custom component implementation but I don't get what the problem is.
Might not be a bug but I am not sure

**Comment by gustavohenke** [comment]
https://github.com/erikras/redux-form/issues/1836#issuecomment-335556963

**Comment by stilllife00** [comment]
@gustavohenke What I got is that the issue is due to rendering the component inside of an arrow function instead of just passing the component name:

```
// bad
<Field
    component={(fieldProps) =>
    <ValidatedFormInput {...fieldProps} /> }
/>

// good
<Field
    ... <- put the custom props here
    component={ValidatedFormInput}
/>

There is a reason though why I was using the "bad" version.
Typescript (specifically the [definition provided by DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/redux-form) does not accept custom props on the Field object.

So the question is: are the type definitions wrong ? is the documentation of Redux Form misleading on this part ? Can you suggest a way to overcome this ?

**Comment by gustavohenke** [comment]
We don't support TypeScript officially.
You may however open an issue in the DefinitelyTyped repo suggesting the fix.

**Comment by stilllife00** [comment]
Thanks, in the meantime I found this workaround: https://stackoverflow.com/questions/46111325/pass-custom-props-to-redux-form-field-in-typescript
