### ISSUE TITLE
On SubmissionError section nested fields aren't highlighted as error

### ISSUE THREAD

**Issue by HarrisGri** [erikras/redux-form#3779]
### What is the current behavior?
With the current 7.2.1 version SubmissionErrors that happen after server responds with invalid set of action -> field, the invalid fields aren't updated and highlighted as invalid!
*In case if i move the fields out of the section (remove the section) the errors that came from server validation are highlighted correctly. (https://codesandbox.io/s/2zzry94pp)*

### What is the expected behavior?
I expect that after handleSubmit is getting a `throw SubmissionError({ section1: { field1: 'error happend'}})` error the corresponding field is highlighted as invalid!

### Sandbox Link (Fields wrapped within section are not highlighted)
https://codesandbox.io/s/l9k27jky1m

If you enter a username (which is required) and press on the submit button i expect that 
`{
      applicant: { username: 'User does not exist 3333' }
    }` is getting highlighted with `User does not exist 3333`

**Comment by sergeyfedotov** [comment]
A BC break was introduced in the https://github.com/erikras/redux-form/pull/3755

**Comment by boba-keyost** [comment]
It's not changed completely. For example, ConnectedFieldArray still uses nested error structure.
Maybe there should be option to use nested error structure?

**Comment by HarrisGri** [comment]
👍 : SyncErrors are still nested as well!

**Comment by dagstuan** [comment]
I made a PR that, while it keeps the breaking change, at least should make it consistent now. #3802

**Comment by marlonmleite** [comment]
Could they generate a release? This is affecting me.
