### ISSUE TITLE
Support objects for deeply nested fields

### ISSUE THREAD

**Issue by andynoelker** [erikras/redux-form#378]
Deep nesting for fields is a wonderful feature, but at the moment if you want to list all data from one source, that source must be an array. If you want to list from nested objects, you have to specify each property manually. It would be super helpful to have a way to list every property from an object without explicitly declaring it. I propose using a `{}` in the `fields` array. For instance:

Given this data source
```
var foo = {
    bar: 'a value',
    baz: 'another value'
};
```
You could access all of these properties simply by setting the `fields` array to
```
const fields = [
    'foo{}'
];
```
This would essentially be shorthand for
```
const fields = [
    'foo.bar',
    'foo.baz'
];
```
Only it wouldn't require any explicit property declarations - just loop through all object keys and return the corresponding properties. This would really be helpful when populating fields with `initialValues`.

Does that sound like a good feature? Or is there something I'm overlooking?

**Comment by trevorr** [comment]
FWIW, I manage the complexity of deep fields (and keep [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)) by exporting the sub-form field names as a static property and then mapping the names in the containing form. For example, here's how a CRM form might look:

```
ContactForm.fields = [
  'firstName',
  'lastName',
  'company',
  ...AddressSubform.fields.map(f => 'addresses[].' + f),
  ...PhoneNumberSubform.fields.map(f => 'phoneNumbers[].' + f),
  ...EmailAddressSubform.fields.map(f => 'emailAddresses[].' + f),
]
```

**Comment by andynoelker** [comment]
@trevorr That's not a bad way to handle things! 

Since Redux-form is moving away from having you create an array of field names, this proposed change has become somewhat pointless so I'll go ahead and close it now.
