### ISSUE TITLE
Examples broken in 7.2.1

### ISSUE THREAD

**Issue by SteveRuble** [erikras/redux-form#3780]
### Are you submitting a **bug report** or a **feature request**?
This is a bug.

### What is the current behavior?

The page at https://redux-form.com/7.2.1/examples/initializefromstate/ is broken (it logs "Cannot read property 'parentNode' of undefined", the least helpful React error).

### What is the expected behavior?

It should look like the page at https://redux-form.com/7.2.0/examples/initializefromstate/ 

### What's your environment?
Ubuntu 17.10 using Chrome or Firefox

**Comment by evanstern** [comment]
This appears to be happening on all the examples from my tests.

**Comment by fivetwentysix** [comment]
Pretty sure it's broken in the website-template, but there website-template branch doesn't have any way to run the code that I can see.

**Comment by TomPradat** [comment]
I'm having the problem here too on Google Chrome 63

<img width="1255" alt="capture d ecran 2018-01-25 a 10 22 47" src="https://user-images.githubusercontent.com/16164512/35380568-f365be52-01b9-11e8-9475-0e89362884b8.png">

**Comment by gustavohenke** [comment]
All examples should be loading now.
