### ISSUE TITLE
[BUG]: Async validation sets error on form but not on field when using sections (v7.2.1)

### ISSUE THREAD

**Issue by Ciogmi** [erikras/redux-form#3784]
### What is the current behavior?
For version 7.2.1 async validation only sets error on form and not at field level when the field is part of a form section

### What is the expected behavior?
Error is set both on field and form.

### Sandbox Link
I updated the async validation sandbox example to demonstrate the issue.
[sandbox with 7.2.1 bug](https://codesandbox.io/s/3xj978n385)
[sandbox with 7.1.0 with expected behaviour](https://codesandbox.io/s/k0p966lkl3)

**Comment by dagstuan** [comment]
I believe this was introduced with #3755 which is a breaking change in how `asyncErrors` and `submitErrors` should be structured. I'm not sure if it was intended to be a breaking change yet, but #3802 should make it consistent at least.

**Comment by dagstuan** [comment]
@Ciogmi this is fixed in `7.2.3`: https://codesandbox.io/s/0y0qqq5v4n

**Comment by Ciogmi** [comment]
It works, great

**Comment by taschetto** [comment]
I can confirm it still occurs in 8.1.0 (current latest).

**Comment by taschetto** [comment]
Managed to solve this throwing a error object considering the FormSection name.

Instead of...

```
throw new SubmissionError({
    field1: 'error 1 description',
    field2: 'error 2 description',
})
```

I've used:

```
throw new SubmissionError({
    section_name: {
        field1: 'error 1 description',
        field2: 'error 2 description',
    }
})
```
