### ISSUE TITLE
FieldArray: Event object is saved instead of related value.

### ISSUE THREAD

**Issue by mmartyniuk** [erikras/redux-form#3790]
### Current
Event object is saved into form instead of related value if you add fields to fieldArray

### What is the expected behavior?
Correct value is saved

[https://codesandbox.io/s/3qkwzwr3m6](https://codesandbox.io/s/3qkwzwr3m6)
redux-form: "7.2.1", chrome/mozilla/edge, node - v8.9.1

**Comment by gustavohenke** [comment]
You're doing `onClick={fields.push}`, what means every time that div is clicked you're pushing the event object.
Please refer to the [Field Arrays example](https://redux-form.com/7.2.1/examples/fieldarrays/) for an.. example (that works)!

**Comment by mmartyniuk** [comment]
Thank you!
