### ISSUE TITLE
[Bug]Changes to items in FieldArray cause whole list of items to update

### ISSUE THREAD

**Issue by jarekb84** [erikras/redux-form#3791]
### Are you submitting a **bug report** or a **feature request**?
Bug

### What is the current behavior?
Changing a single item in a FieldArray causes whole list to be resorted. Inspecting actions and state diff using Redux dev tools shows an action dispatched where payload updates the correct item (via index key), but the difference in state includes changes to all items in the list.

### What is the expected behavior?
Changing a single item only updates that item's state in the redux store.

### Sandbox Link
Attempted to create sandbox with scenario, but there are issues with the current sandbox setup with 7.2.1
https://codesandbox.io/s/811pjkq2y9

### What's your environment?
"redux-form": "7.2.1"
"redux": "^3.5.2"
"immutable": "^3.8.1"
"react-redux": "^5.0.1",
Chrome  63.0.3239.132 
Node 8.9.1

### Other information
Note this does not happen in version 7.0.4/7.1.2 and when number of items provided to FieldArray is less than 32.

**Comment by erikras** [comment]
Published fix in [`v7.2.2`](https://github.com/erikras/redux-form/releases/tag/v7.2.2).
