### ISSUE TITLE
Accessing props mapped from connect(mapDispatchToProps) as well as syncErrors in the child component

### ISSUE THREAD

**Issue by mtg5014** [erikras/redux-form#3798]
This is a question - please see the stackoverflow post here:
https://stackoverflow.com/questions/48533355/redux-form-ordering-connect-and-reduxform-calls-cant-access-store-props-and

Specifically, I'm wondering about the recommendations (to which I commented) here: 
#3424 

Much apologies if I'm not following protocol for the question, and thanks in advance for any help.

**Comment by gustavohenke** [comment]
I tried answering it over StackOverflow. Closing the issue now.
