### ISSUE TITLE
[BUG] onSubmitFail not called anymore on submitHandler promise rejection in v7.2.1

### ISSUE THREAD

**Issue by felixhayashi** [erikras/redux-form#3801]
Hi,

### Are you submitting a **bug report** or a **feature request**?

bug report

### What is the current behavior?

after moving from **v7.2.0** to **v7.2.1** the registered `onSubmitFail` handler is not called anymore if `submitHandler` rejects the promise.

### What is the expected behavior?

`onSubmitFail` should be called if an an async submitHandler rejects the promise.

> **onSubmitFail**
> A callback function that will be called when a submission fails **for whatever reason.** It will be called with the following parameters:
> https://redux-form.com/7.2.1/docs/api/reduxform.md/#-code-onsubmitfail-function-code-optional-

### What's your environment?

Chrome

**Comment by AlimovSV** [comment]
https://github.com/erikras/redux-form/blob/master/src/handleSubmit.js#L79

**Comment by felixhayashi** [comment]
@AlimovSV Yeah, that's the spot in the code that introduced this new behaviour.

In the latest change on the file, as you pointed out, `error` has been newly added to the boolean expression as a prerequisite for `onSubmitFail` being called (https://github.com/erikras/redux-form/commit/1a0660c3477024c094f1906ddab0984a386a45f0#diff-28d8f38ee02f29d2bc406450f6c0d870).

The problem is that the error in our forms do not extend `SubmissionError` but are of a different type so redux form as of 7.2.3 doesn't count them as error anymore :(

The docs clearly state:

> **onSubmitFail**
> A callback function that will be called when a submission fails **for whatever reason.** It will be called with the following parameters:
> https://redux-form.com/7.2.3/docs/api/reduxform.md/#-code-onsubmitfail-function-code-optional-

So I suggest reverting the line change that was introduced in `v7.2.3` (i.e. `if (error && onSubmitFail)` back to `if (onSubmitFail)`).

Regards

**Comment by felixhayashi** [comment]
@erikras would you be fine with a patch that changes [this](https://github.com/erikras/redux-form/commit/1a0660c3477024c094f1906ddab0984a386a45f0#diff-28d8f38ee02f29d2bc406450f6c0d870R79) behaviour back to allowing any error to be thrown in order to trigger submitFailed (as it was in pre v7.2.1)? Otherwise, this would be quite a breaking change and I don't see much of a benefit of this restriction either.

**Comment by naw** [comment]
Yes, I agree this change (from https://github.com/erikras/redux-form/pull/3723) should be reverted. It doesn't seem to have been a good PR for more than one reason. Also see https://github.com/erikras/redux-form/issues/3821

**Comment by naw** [comment]
@felixhayashi perhaps the test suite could be improved to cover your situation, as I agree this is a breaking change in the expected behavior around `onSubmitFail`

**Comment by erikras** [comment]
Published fix in [`v7.3.0`](https://github.com/erikras/redux-form/releases/tag/v7.3.0).
