### ISSUE TITLE
Bug: FieldArray not updating when child Fields update

### ISSUE THREAD

**Issue by ihorml** [erikras/redux-form#3816]
### What is the current behavior?

When I start to type something on the first input the FieldsArray(Streams) updates only first time. The console logs present it well:

```
FieldArray updates {name: "so"}
Fields update {name: "so"}
Fields update {name: "b", money: 500}
Fields update {name: "c", money: 400}

Fields update {name: "soo"}
Fields update {name: "b", money: 500}
Fields update {name: "c", money: 400}

Fields update {name: "sooo"}
Fields update {name: "b", money: 500}
Fields update {name: "c", money: 400}
```

https://codesandbox.io/s/m43q5q614j

### What is the expected behavior?

I want FieldsArray receive up-to-date props. 

### Sandbox Link

https://codesandbox.io/s/m43q5q614j

### What's your environment?

Latest

**Comment by ihorml** [comment]
Please don't ask me why I have this structure. It's a little sample which presents issue. I should have this structure because I have so so deep form on my project.

**Comment by gustavohenke** [comment]
This is not a bug.
You can use [`rerenderOnEveryChange`](https://redux-form.com/7.2.3/docs/api/fieldarray.md/#-code-rerenderoneverychange-boolean-code-optional-) to mitigate your problem.

Some explanation is here: https://github.com/erikras/redux-form/issues/3008#issuecomment-305874086
