### ISSUE TITLE
Please stop use <div> as wrapper in Field

### ISSUE THREAD

**Issue by gormonn** [erikras/redux-form#3829]
For example:
http://prntscr.com/idfh9g

Use this:
```
export const Aux = props => props.children;
```
https://medium.com/@gajus/using-react-v16-to-create-self-destructing-components-de8e4eb61d0f

**Comment by gustavohenke** [comment]
Redux Form doesn't wrap `Field`s in DOM elements.
Also you can change your component implementation to stop using `div`s if you want.
