### ISSUE TITLE
Field Validation doesn't work

### ISSUE THREAD

**Issue by goodbomb** [erikras/redux-form#3832]
I can't seem to get Field validation working, no matter what I try. Nothing seems to work.

I am using Material UI Next (1.0.0-beta.33), but I wouldn't think that would impact this.

```
renderMyComponent = (field) => {
   console.log(field); // field.meta.valid always returns true, no matter what

   return (
      <TextField
          {...field.input}
      />
   );
};

<Field
   component={this.renderMyComponent}
   name="myComponent"
   normalize={value => stripSpaces(value)}
   validate={value => value.length > 5} // this is just to test the validation
/>
```

### What is the current behavior?
The `field.meta` object always returns `valid: true` no matter how many characters have been entered.

### What is the expected behavior?
Validation should work based on the function passed into the "validate" prop.

### Other information
Redux-Form version: 7.2.3
Material-ui version: 1.0.0-beta.33

**Comment by mitchvoll** [comment]
The validate function should return an error string for invalid input and undefined otherwise.

https://redux-form.com/7.2.3/docs/api/field.md/#-code-validate-value-allvalues-props-name-gt-error-code-optional-

**Comment by asaarnak** [comment]
@mitchvoll This is from docs: `Note: if the validate prop changes the field will be re-registered.`
Does this mean that field is revalidated when validate prop changes ? Currently i have a issue where i change my validate function in component state, but after re-register validation is not triggered.

**Comment by goodbomb** [comment]
@mitchvoll even when I do this: `validate={value => value.length > 5 ? 'Error' : null}` it doesn't make a difference. The error property for `field.meta` is always `error: undefined` and `valid: true` even when the length of the value exceeds 5 characters.

**Comment by goodbomb** [comment]
Furthermore, when I do this: 
```
validate={value => value.length > 5 ? console.log('Error') : console.log('no error')}
```

`Error` is logged out to the console, so it should in fact be an error, but the `error` and `valid` properties never change.

**Comment by raulsebastianmihaila** [comment]
@goodbomb You have to define the validation function outside of the rendering process so that the function is not recreated every time. This indeed sucks. Firstly because it sucks in terms of API. And secondly, people generally use Redux for a more functional approach, and this behavior is a violation of referential transparency.

**Comment by asaarnak** [comment]
@raulsebastianmihaila 
Yes i already created the `Field validate prop` outside the render function. 
I have defined the `Field validate prop` in component state and i change it in `componentWillReceiveProps`.
In `componentWillReceiveProps` i use `setState` to create new(not mutating state) `Field validate prop`. Note: In my case, very often the `Field value ` stays the same and `Field validate prop` is changed often.

Tested with debugger seems like the `Field validate` is not called after re-register.
This is from docs: 
> `Note: if the validate prop changes the field will be re-registered.`

**Comment by asaarnak** [comment]
@raulsebastianmihaila 
Any workaround or existing issue for this exists?
I currently couldn't find a way to fix this.
> `is a genuine bug and your use case shows it clearly.`

**Comment by raulsebastianmihaila** [comment]
@asaarnak Unfortunately I'm not aware of any.

**Comment by asaarnak** [comment]
Found something. Looks like here is the same topic:
https://github.com/erikras/redux-form/issues/3757
https://github.com/erikras/redux-form/issues/3566

**Comment by goodbomb** [comment]
Thanks @raulsebastianmihaila. Move the validation function out of the render function did the trick. That is indeed rather counter-intuitive and should probably be mentioned in the docs.

**Comment by goodbomb** [comment]
Going to close this issue since there appears to be issues already raised for @asaarnak's issue
