### ISSUE TITLE
Redux From isValid and isInvalid are not working.

### ISSUE THREAD

**Issue by gbaasch** [erikras/redux-form#3847]
BUG REPORT Redux Form version 7.0.4

isValid function returns true when the form is inValid. Specifically, the form has sync errors which I can get from the store with getFormSyncErrors,  but isValid returns true and isInvalid returns false.

![image](https://user-images.githubusercontent.com/2358060/36392103-799ff20a-155e-11e8-9d62-5bf047c37d74.png)

**Comment by gustavohenke** [comment]
Please provide a reproducible sandbox.

**Comment by gbaasch** [comment]
I'm struggling to reproduce this in sandbox but I'm getting the same error elsewhere in my application ...

<img width="260" alt="screen shot 2018-02-23 at 12 08 11 pm" src="https://user-images.githubusercontent.com/2358060/36614682-51278a40-1892-11e8-8cb0-45b73a764c07.png">
