### ISSUE TITLE
Reinitialize redux form state from saved state

### ISSUE THREAD

**Issue by michaelspeed** [erikras/redux-form#3848]
/* ENHANCEMENT */
I am creating a dynamic form where users can add fields and then later someone else can add data to them.

i have successfully saved the whole form state into a database,

now i need to load the whole state into the form

![screenshot at feb 20 15-38-37](https://user-images.githubusercontent.com/1447958/36421607-1e191fa4-165f-11e8-8c9f-6d810fa66f55.png)

> i am not trying to load the initial values from the state. the from does not have any fields etc. i am trying to load all those from the database

is there some functionality to do this or this could be an enhancement

**Comment by gustavohenke** [comment]
From your question, you seem to be building a form builder.

I recommend against storing internal reducer data that could change from version to version, thus breaking your app, or that could make no sense to different users.
If you absolutely must, rebuild those via selectors/action creators.

Also rebuilding UI structure from redux state is probably far beyond the scope of redux-form at the moment, so we aren't adding this feature.
