### ISSUE TITLE
Evaluating multiple fields as one value

### ISSUE THREAD

**Issue by alanbuchanan** [erikras/redux-form#3850]
How do you handle form elements which require multiple form fields to evaluate a single value?

For example, if I have a date of birth field, I am going to get a `day`, `month`, and `year` value from the user, but I want to validate a single `Date` object from these values and also save a `dateOfBirth` value in my db.

What's the best practise for treating multiple fields as one?

**Comment by gustavohenke** [comment]
For now I could think of these ways:

1. Have a component that combines the values internally, as already suggested in [this answer to your SO's question](https://stackoverflow.com/a/48919605/2083599)
2. Have all the fields separated and build the date at some point. Fo example in the `onSubmit` function itself
