### ISSUE TITLE
**Bug report** Field of type='number' allows you to type 'e'

### ISSUE THREAD

**Issue by rpanczer** [erikras/redux-form#3857]
### Bug Report: Field of type='number' allows you to type 'e'
1. Type 'e' character in any 'number' field.
2. The 'e' character will display in the input field

### What is the expected behavior?
Input field type='number' will display only numbers.

### Sandbox Link
Can see this in:
https://redux-form.com/6.7.0/examples/syncvalidation/
Specifically in the 'Age' field.

### What's your environment?
Redux Form Version: 7.0
Browser: Chrome 64.0.3282.167 (Official Build) (64-bit)
OS: Mac High Sierra 10.13.3

**Comment by gustavohenke** [comment]
Browsers probably allow this because [`e` is a scientific notation](https://math.stackexchange.com/a/6276/534270).

So it's not redux-form related.
