### ISSUE TITLE
7.2.2 vanishes initial values

### ISSUE THREAD

**Issue by evserykh** [erikras/redux-form#3858]
First at all, thanks for the great lib 👍

### Are you submitting a **bug report** or a **feature request**?
bug report

### What is the current and expected behavior?

In my app I have some nodes on the page, a user can select a node by clicking on it. Every node has some settings, for example a button node has a caption and a url,  an image node has a url and an alt, etc. When a node is clicked in sidebar appears a form with appropriate settings. 

I upgraded today from 7.2.1 to 7.2.3 and noticed that when I click on a node which definitely has filled settings the form opens but the inputs are empty. I never had this behaviour before upgrading. 

I downgraded from 7.2.3 to 7.2.2 and the issue remained, I downgraded to 7.2.1 and the issue disappeared. I've read that 7.2.2 has some changes regarding initialization. 

### Sandbox Link
todo

### What's your environment?
React 16.2.0
Redux 3.7.2

**Comment by gustavohenke** [comment]
Repro link?

**Comment by evserykh** [comment]
Sorry, I wasn't able to extract this part from my app
