### ISSUE TITLE
FormSection propType doesn't allow React 16 Fragment

### ISSUE THREAD

**Issue by alexanthony** [erikras/redux-form#3859]
### Are you submitting a **bug report** or a **feature request**?
Bug report

### What is the current behavior?
FormSection prop type doesn't allow React 16 Fragment

### What is the expected behavior?
FormSection prop type allows React 16 Fragment to be used (PropTypes.node)

### Sandbox Link
https://codesandbox.io/s/l6nx50r3m
Open the console

### What's your environment?
React 16.2.0
Redux form 7.2.3

### Workaround
Wrap Fragment in a Stateless Functional Component
(Everything works, it just adds a console warning)

**Comment by gustavohenke** [comment]
Thanks for the report! Issue up for grabs, shouldn't be difficult to fix.

**Comment by gustavohenke** [comment]
@shulcsm it would definitely break many people's code.

**Comment by erikras** [comment]
Fix released in [`v7.4.0`](https://github.com/erikras/redux-form/releases/tag/v7.4.0).
