### ISSUE TITLE
Best way to sort deep form array

### ISSUE THREAD

**Issue by webmasterkai** [erikras/redux-form#386]
On the example http://erikras.github.io/redux-form/#/examples/deep it's possible to create an array of children. What's the best way to sort or change the order of the children?

**Comment by erikras** [comment]
Man, you give your followers some bread, and they ask for butter to spread on it. :smiley: 

At the moment, all you have is the ability to remove elements from a specific index and add them at a specific index. So you _could_ remove them all and add them back in order, but that's pretty inelegant. 

Sorting will have to be a future feature.

**Comment by webmasterkai** [comment]
Bread without easy butter spreading abilities? I love me some fresh bread and butter. :bread: :yum:

**Comment by ooflorent** [comment]
Currently the only available option is to implement a quicksort using `swapArrayValues` which would be really expensive. v6 may include a `moveArrayValue`. It would allow you to move a record to another index. Thus a possible way to sort the fields would be:

- create a new list of sorted records containing their indices
- call `moveArrayValue` to move each record to their new position

I don't think a sorting API would be added to Redux Form.

**Comment by grovesNL** [comment]
@erikras @ooflorent What is the recommended way to perform sort/reorder large lists when

1. just for the purpose of display (not setting dirty state), or
2. updating the order in the store

We've come up with a number of different approaches but they each have various limitations. For example, sorting in the store by dispatching a large number of actions to move each element in the array. We also tried sorting the elements as they're being rendered and struggling to keep the index of each element in sync with the store. Is it not possible to have an action creator like `fields.sort(callback)` or something?

**Comment by mikeinsf** [comment]
I solved my issue with this using the redux-form change action. Get the current array, sort it in your code, and dispatch the change action on the field, passing it your sorted array.

**Comment by mikeinsf** [comment]
Also, to address #1 in @grovesNL's post above, for display purposes, had to jump through a few hoops but came up with this...

```
    componentDidUpdate = (prevProps, prevState) => {
        // sorts tags for presentation
        const {isDirty, valuesTags, setTags} = this.props;
        if (valuesTags.length > 0) {
            const sortedTags = valuesTags.slice(0).sort(alphabetical);
            if (!_.isEqual(valuesTags, sortedTags) & !this.state.tagsSorted) {
                setTags(sortedTags);
                this.setState({
                    tagsSorted: true
                });
            }
        }
    }

    render() {
        const {isDirty, initialTags, valuesTags} = this.props;
        const isDirty_TagsAlso = isDirty && !_.isEqual(initialTags.slice(0).sort(alphabetical), valuesTags.slice(0).sort(alphabetical));
        
        .... remaining code not pertinent
    }

function mapStateToProps(state) {
    const form = state.form && state.form['my-form'];
    return {
        isDirty: form && form.values && form.initial && form.values !== form.initial,
        initialTags: (form && form.initial && form.initial.tags) || [],
        valuesTags: (form && form.values && form.values.tags) || []
    };
}
```

**Comment by mrchief** [comment]
@mikeinsf Is the existing state of the fields maintained when you dispatch the new sort order? E..g, if I enter values in various tags, then sort; does it preserve the values after re-rendering with new order?

**Comment by giarocks** [comment]
What about when you require the same thing for a fieldarray .. ?
 @mikeinsf would you please happen to have a codepen/jsfiddle showing the same in action with a fieldArr?
new to react/redux and redux-forms .. constantly facing batchnumber/reference/mutation errors trying to sort the fieldArray

**Comment by mrchief** [comment]
I was able to do it outside of redux form - it re-renders the form when sort order changes - but redux-form is smart enough to preserve the state (or maybe its a side effect as I'm just changing the order and not destroying/mutating anything that would cause the state to change).

https://codesandbox.io/s/6zxjpv31pn

**Comment by giarocks** [comment]
Redux form maintains the state and preserves the values .. but detects the state mutation when rendering the fields of the fieldArray giving those errors i mentioned.. 
one of the suggestions based on the above inputs from mike could be to removeAll and reassign the 'values.fieldArrayNameProperty' in reduxform .. but thats again a mutation. the methods dont allow for a setstate without a breakage either : ( 

My case : 
I was actually attempting this in the redux-form wizard .. say im on step2 where i have dynamically added the fieldArrays .. and on step3 render a list with those added field arrays from step2..

Sorting in step3- after the addition of fields-  fails the step3 form miserably :D 
Sorting in step2 while the dynamic field arrays are still getting added one by one beautifully re-renders the screen ... but its sadness in user experience due to the focused field getting lost 

And ofcourse smart redux-forms detect what you are doing and console error it out too 🗡 
I feel like its ember all over again
