### ISSUE TITLE
redux-form initialValues via config doesn't work v7.1.2+

### ISSUE THREAD

**Issue by gustavohenke** [erikras/redux-form#3867]
### Are you submitting a **bug report** or a **feature request**?

Bug report

### What is the current behavior?

Statically providing `initialValues` to `reduxForm()` decorator doesn't work since v7.1.2.

### What is the expected behavior?
There should be no difference between using `initialValues` like this or by triggering some redux action, like in the ["Initialize from state" example](https://redux-form.com/7.2.3/examples/initializefromstate/).

### Sandbox Link

https://codesandbox.io/s/p2ppwo1wj7

### What's your environment?

redux-form v7.1.2+

### Other information

Some debug from [this related SO question](https://stackoverflow.com/questions/48969341/initialvalues-arent-populating-redux-form?noredirect=1#comment84945438_48969341)

**Comment by gustavohenke** [comment]
cc @erikras -- this should definitely be fixed ASAP.

**Comment by crokobit** [comment]
+1 QQ

**Comment by machour** [comment]
@gustavohenke weird thing, if I download your sandbox and execute locally, it works as expected. Also tested on a newly created form, it works as expected, using `7.2.3`

**Comment by gustavohenke** [comment]
That's interesting, @machour.

So CodeSandbox seems to have something in its runtime libs that screws with redux-form `INITIALIZE` action. I wrapped react-dom's `render(<App/>)` call with `setTimeout` and it worked as well.

Will close the issue for now.

**Comment by AdamBCo** [comment]
@gustavohenke I noticed you closed the issue, but I am still experiencing this problem outside of the codesandbox example you created. Could you please share your exact solution to fix this issue? Thank you.

**Comment by gustavohenke** [comment]
Have a look at the small hint I gave you: you need to spread `props.input` into `<input>`, instead of `props` 😉 
If it still doesn't work even outside of CodeSandbox, let's debug it!

**Comment by AdamBCo** [comment]
@gustavohenke Thanks for the help on this. I have created another code sandbox that is not working locally as well. Could you please tell me what's going on? This is example is a little easier than the one I created earlier.

https://codesandbox.io/s/ojvjn6mpmz

**Comment by AdamBCo** [comment]
@gustavohenke I'v also created a simplified version of the example [online](https://redux-form.com/7.2.3/examples/initializefromstate/).   
 
    import React from 'react'
    import { connect } from 'react-redux'
    import { Field, reduxForm } from 'redux-form'

    let InitializeFromStateForm = props => {
      const { handleSubmit, pristine, reset, submitting } = props
      return (
        <form onSubmit={handleSubmit}>
          <div>
            <label>First Name</label>
            <div>
              <Field
                name="firstName"
                component="input"
                type="text"
                placeholder="First Name"
              />
            </div>
          </div>
        </form>
      )
    }

    // Decorate with reduxForm(). It will read the initialValues prop provided by connect()
    InitializeFromStateForm = reduxForm({
      form: 'initializeFromState' // a unique identifier for this form
    })(InitializeFromStateForm)

    // You have to connect() to any reducers that you wish to connect to yourself
    InitializeFromStateForm = connect(
      state => ({
        initialValues: {firstName: 'Adam'}
      }),
    )(InitializeFromStateForm)

    export default InitializeFromStateForm
