### ISSUE TITLE
Redux Form on refresh doesn't load data from state

### ISSUE THREAD

**Issue by Ivanito86** [erikras/redux-form#3869]
### Are you submitting a **bug report** or a **feature request**?

bug report

### What is the current behavior?

I connected redux-form with state and when I visit edit form everything is working fine , but when I refresh the browser redux form can't load data from state (even though the state has been filled with data).

1. picture shows redux form when I visit edit form
http://prntscr.com/ijlqvb
2. picture shows when I refresh form 
http://prntscr.com/ijltl9

### What's your environment?

redux-form: 7.2.3

**Comment by gustavohenke** [comment]
Please provide a reproducible sandbox.

**Comment by Ivanito86** [comment]
EditContact.js

`import React, { Component } from 'react';
import { connect } from 'react-redux';
import { withRouter } from 'react-router-dom';
import { reduxForm } from 'redux-form';
import * as actionCreators from '../store/actions/index';
import * as Icon from '../components/UI/Icon/index';
import ContactForm from '../components/Form/ContactFormTemp';
import Aux from '../hoc/Aux/Aux';
import Modal from '../components/UI/Modal/Modal';
import Spinner from '../components/UI/Spinner/Spinner';

const validate = values => {
  const errors = {}
  if (!values.fullName) {
    errors.fullName = true
  }
  if (!values.email) {
    errors.email = true
  } else if (!/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i.test(values.email)) {
    errors.email = true
  }
  return errors
}

class EditContact extends Component {
  state = {
    isEdit: true,
    showModal: false
  }
   
  submitEditHandler = (values) => {
    (values.userImg && values.userImg.preview) ?
      this.props.onUpdateProfileImg(values, this.props.match.params.id, this.props.history)
      : this.props.onUpdateContact(values, this.props.match.params.id, this.props.history)
  }
  backHandler = (e) => {
    e.preventDefault();
    this.props.history.goBack();
  };

  deleteContactHandler = () => {
    this.setState({ showModal: true });
    let contactId = this.props.match.params.id;
    this.props.onDispatchContactId(contactId);
  };
  cancelDeleteContact = () => {
    this.setState({ showModal: false });
  }
  continueDeleteContact = () => {
    this.props.onContactDeleted(this.props.contactId, this.props.history);
    this.setState({ showModal: false });
  }

  componentWillReceiveProps(nextProps) {
    console.log('[Edit Contact] inside componentWillReceiveProps()');
    console.log(nextProps);
    if (this.props.match.params.id !== nextProps.match.params.id) {
      if (nextProps.match.params.id) {
        this.props.onUnload();
        return this.props.onLoad(this.props.match.params.id);
      }
      this.props.onLoad(null);
    }
  }

  componentWillMount() {
    console.log('[Edit Contact] inside WillMount()');
    if (this.props.match.params.id) {
      return this.props.onLoad(this.props.match.params.id);
    }
    this.props.onLoad(null);
  }

  componentWillUnmount() {
    console.log('[Edit Contact] inside WillUnMount()');
    this.props.onUnload();
  }

  render() {
    console.log('[Edit Contact] inside Render()');
    let editForm = (
      <div className="add-contact">
        <div className="back-handler__mobile">
          <a href="" onClick={this.backHandler}>
            <Icon.BackIcon />
          </a>
        </div>
        <ContactForm
          initialValues={this.props.initialValues}
          onSubmit={this.submitEditHandler}
          handleSubmit={this.props.handleSubmit}
          isEdit={this.state.isEdit}
          delete={this.deleteContactHandler}
          history={this.props.history}
          loading={this.props.loading} />
      </div>
    );
    if (this.props.loading) {
      editForm = <Spinner />;
    }
    return (
      <Aux>
        <Modal show={this.state.showModal}>
          <div className="modal__header">
            <h3>Delete</h3>
          </div>
          <div className="modal__body">
            <p>
              Are you sure you want to delete this contact?
            </p>
          </div>
          <div className="modal__footer">
            <button className="modal__footer__btn button button--cancel" onClick={() => this.cancelDeleteContact()}>
              Cancel
            </button>
            <button className="modal__footer__btn button button--delete " onClick={() => this.continueDeleteContact()} >
              Delete
           </button>
          </div>
        </Modal>
        {editForm}
      </Aux>
    );
  }
}

const mapStateToProps = state => {
  const initialValues = state.contactDetails.contactDetailsData;
  const loading = state.contacts.loading;
  // const userImg = state.contactDetails.contactDetailsData.userImg ? state.contactDetails.contactDetailsData.userImg : '';
  return {
    initialValues: initialValues,
    loading: loading,
    contactId: state.contacts.contactId
  };
}

const mapDispatchToProps = dispatch => {
  return {
    onLoad: (contactId) => dispatch(actionCreators.fetchContactDetails(contactId)),
    onUnload: () => dispatch(actionCreators.unloadContactDetails()),
    onContactDeleted: (contactId, history) => dispatch(actionCreators.deleteContact(contactId, history)),
    onDispatchContactId: (contactId) => dispatch(actionCreators.dispatchContactId(contactId)),
    onUpdateProfileImg: (data, contactId, history) => dispatch(actionCreators.updateProfileImg(data, contactId, history)),
    onUpdateContact: (data, contactId, history) => dispatch(actionCreators.updateContact(data, contactId, history))
  };
}

EditContact = reduxForm({
  form: 'editForm',
  enableReinitialize: true
})(EditContact);

export default withRouter(connect(mapStateToProps, mapDispatchToProps)(EditContact));`

ContactForm.js
`import React from 'react';
import { Field, Form, FieldArray } from 'redux-form';
import * as Icon from '../UI/Icon/index';
import FieldDropzone from './FieldDropzone';
import Aux from '../../hoc/Aux/Aux';

const renderField = ({ input, className, placeholder, type, meta: { touched, error } }) => (
  <div>
    <div>
      <input {...input} placeholder={placeholder} className={touched && error ? className + " error" : className} type={type} />
    </div>
  </div>
);

const renderNumbers = ({ fields, meta: { error, submitFailed } }) => (
  <div>
    {fields.map((el, index) => (
      <div className="add-contact__numbers" key={index}>
        <Field
          className="add-contact__input"
          name={`${el}.number`}
          type="number"
          component={renderField}
          placeholder="Number"
        />
        <Field
          className="add-contact__input add-contact__input--small"
          name={`${el}.label`}
          type="text"
          component={renderField}
          placeholder="Label"
        />
        <button
          className="add-contact__remove-number"
          type="button"
          title="Remove Member"
          onClick={() => fields.remove(index)}>
          <Icon.DeleteNumIcon classname="add-contact__icon--delete" />
        </button>
      </div>
    ))}
    <div>
      <button className="add-contact__add-number" type="button" onClick={() => fields.push({})}>
        <Icon.AddIcon classname="add-contact__icon--add" /> Add number
      </button>
      {submitFailed && error && <span>{error}</span>}
    </div>
  </div>
);

const ContactForm = (props) => {
  const backHandler = (e) => {
    e.preventDefault();
    props.isEdit ? props.history.goBack() : props.history.push('/');
  };

  let userImg = props.isEdit ?
    ((props.initialValues && props.initialValues.userImg) ? props.initialValues.userImg : '')
    : '';

  let contactForm = (
    <Form className="add-contact__form add-contact__form--flex" onSubmit={props.handleSubmit(props.onSubmit)}>
      <div className="add-contact__image-upload-wrapper">
        <Field
          name="userImg"
          component={FieldDropzone}
          userImg={userImg}
        />
      </div>
      <div className="add-contact__input-wrapper">
        <div className="add-contact__options">
          <a className="add-contact__back-handler" onClick={backHandler} >
            <Icon.BackIcon />
          </a>

          {props.isEdit && (
            <a
              onClick={props.delete}
              className="add-contact__edit-delete-btn"
            ><Icon.EraseIcon classname="add-contact__icon--edit-delete" /> Delete
              </a>
          )}
        </div>
        <div>
          <div className="add-contact__input-block">
            <label className="add-contact__label">
              <Icon.UserIcon classname="add-contact__icon" />full name
              </label>
            <Field
              className="add-contact__input"
              name="fullName"
              type="text"
              component={renderField}
              placeholder="Full Name"
            />
          </div>
          <div className="add-contact__input-block">
            <label className="add-contact__label">
              <Icon.EmailIcon classname="add-contact__icon" />email
              </label>
            <Field
              className="add-contact__input"
              name="email"
              type="text"
              component={renderField}
              placeholder="Email"
            />
          </div>
          <div className="add-contact__input-block">
            <label className="add-contact__label">
              <Icon.PhoneIcon classname="add-contact__icon" /> numbers
              </label>
            <FieldArray className="add-contact__numbers" name="numbers" component={renderNumbers} />
          </div>
        </div>
        <div className="add-contact__btn-wrapper">
          <button className="button button--cancel" onClick={backHandler}>
            Cancel
            </button>
          <button type="submit" disabled={props.submitting} className="button button--submit">
            Save
            </button>
        </div>
      </div>
    </Form>
  );

  return (
    <Aux>
      {contactForm}
    </Aux>
  );
}

export default ContactForm;`

**Comment by Ivanito86** [comment]
I solved this using selectors. Please mark as solved.
