### ISSUE TITLE
map form to custom model stored in redux

### ISSUE THREAD

**Issue by greaber** [erikras/redux-form#387]
I just started using redux-form, and I am following the examples "Initializing From State" and "Deep Forms" to initialize the values in a form from some redux state.  Is there some way to achieve two-way binding so that when the user changes the form fields it will dispatch an action to update redux?  Or is this the wrong way to do things?  If it helps to understand my use case, I am using a form as an editor for a structured document.

By the way, I first tried to use the Discord channel, but the link on the github.io page didn't seem to take me directly to the redux-form channel.  I had to set up an account and get a "server," and even after I did that I couldn't figure out how to connect to the channel.  The Discord UI is really complicated!

**Comment by ooflorent** [comment]
This is a usage question, and we encourage you to ask it on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

This is the only way to ensure the same question doesn’t get asked many times in a row, and that folks who have the same question in the future will be able to find it.

I’m closing for these reasons.
