### ISSUE TITLE
validate props can't work

### ISSUE THREAD

**Issue by pssgo** [erikras/redux-form#3876]
**bug report**

### What is the current behavior?

validate props can't work

### What is the expected behavior?

validate props can validate

### What's your environment?

```javascript
{
    "redux": "^3.7.2",
    "redux-form": "^7.2.1",
    "redux-form-material-ui": "^5.0.0-beta.2"
}

```

### Other information

![image](https://user-images.githubusercontent.com/16378134/36773510-f17e1058-1c94-11e8-8c78-ebd2e3d0e973.png)

required function  can't validate

**Comment by zonr** [comment]
Try creating the validation function outside of `render()` function. I.e.,

```
const require = () => value => ...

const requireEmail = required()

class Node extends React.Compinent {
  ...
  render() {
    ...
    return (
      ...
          <Field
            component={TextField}
            name="email"
            label="email"
            placeholder="please input"
            validate={requireEmail}
          />
    );
  }
}
```

See #3832.

**Comment by pssgo** [comment]
@zonr I see ！if the validate prop changes the field will be re-registered.
