### ISSUE TITLE
Route based wizard form example

### ISSUE THREAD

**Issue by mfish0005** [erikras/redux-form#3887]
Hello.  I'm using redux-form in a project and so far it's been great to work with.  The wizard form is exactly what I'm looking for except I need each page to be route based.

I've read through the docs and searched the interwebs but I can't seem to find an example for this.  I need to split a form into 9 pages.  I'm using react-router v4.  I need access to the browser's forward/back buttons, the ability to generate unique urls for certain pages, and add slide-in slide-out animated transitions for each page.

The only example I can find is an answer from @erikras in [#260](https://github.com/erikras/redux-form/issues/260)  

Is it possible to achieve this with redux-form?  If so is this a common enough use case to add an example to the docs?

**Comment by gustavohenke** [comment]
I think this could get too complex to demonstrate in just a few bytes in a web page.
What you could do is create an example repo and share it here, then others might find it as well.

**Comment by mfish0005** [comment]
@gustavohenke Thanks for getting back to me.  Sounds like a plan.  If I get it working I'll put together an example repo.   

Might try splitting the wizard up into separate forms and rendering them on their own page.  When each form is submitted the values could be sent to a `FormContainer`.  The container component would wait to send the values to the server until the final form is submitted. 

Still a little fuzzy on working with values in redux-form though.  I've been using `formValueSelector()` but I'm not sure that's the best method.  As mentioned in the docs it triggers a re-render each time a value changes.  Maybe it would be best to POST each form's values individually.

**Comment by gustavohenke** [comment]
I found the list of friendly libs/tools here: https://github.com/erikras/redux-form/blob/master/tools.md

When you're done you can send a PR to add it there :)
