### ISSUE TITLE
Custom component with complex objects as values?

### ISSUE THREAD

**Issue by tlrobinson** [erikras/redux-form#389]
I'd like to have a custom component that edits an complex object but is treated as a single field by redux-form (i.e. not "deep forms")

Is this possible? It seems like if the value of the field is an object it's not being passed to the custom component. It works if I JSON encode/decode the object to/from a string though.

**Comment by xcatliu** [comment]
It's fine to have complex objects as values, but currently(v3.1.7) there might have some bugs if you are using `initialValues` with complex objects.

You may have a look at this issue https://github.com/erikras/redux-form/issues/360

**Comment by tlrobinson** [comment]
Ah, yeah, reverting to v3.1.0 resolved this for me.

**Comment by erikras** [comment]
This should be fixed in [`v4.0.0`](https://github.com/erikras/redux-form/releases/tag/v4.0.0). Come and get it!
