### ISSUE TITLE
undefined error within props

### ISSUE THREAD

**Issue by Kay2dan** [erikras/redux-form#3893]
### Are you submitting a **bug report** or a **feature request**?
A Bug Report

### What is the current behavior?
The form component does not inherit the error props from redux form component (the smart component). The error value within props is `undefined`, inspite of form validation function being passed to the redux form component & functioning correct (i.e., field errors are visible & shown alongside the fields).

The code:
```
const LoginFormComponent = props => {
  return (
    <div className="formContainer">
      <form>
        <Field name="email" label="Email" type="text" placeholder="email" component={InputComponent} />
        <Field name="password" label="Password" type="password" placeholder="password" component={InputComponent} />
        <button className="btn" type="submit">
          Submit
        </button>
      </form>
    </div>
  );
};

const LoginForm = reduxForm({
  form: 'loginForm',
  validate: validateLoginForm
})(LoginFormComponent);

export default LoginForm;
```
validateLoginForm function returns an object in the form of:
```{ email : "Required", password : "Required" }```

### What is the expected behavior?
As per my understanding, upon error, the `props.error` should hold the error within the form. 

### What's your environment?
Webpack3, React 16, Redux 3.7, Redux-Forms 7.3. 

### Other information
[I raised the issue on Stackoverflow here.](https://stackoverflow.com/questions/49067175/redux-forms-errors-prop-is-undefined)

**Comment by tomslutsky** [comment]
as for my understanding the errors are passed inside the meta prop. you should try
`props.meta.error`

**Comment by gustavohenke** [comment]
Use [`getFormSyncErrors`](https://redux-form.com/7.3.0/docs/api/selectors.md/#-code-getformsyncerrors-formname-string-code-returns-code-state-gt-formsyncerrors-object-code-) selector.
