### ISSUE TITLE
Async Validation on FieldArray

### ISSUE THREAD

**Issue by danielesalvatore** [erikras/redux-form#3903]
Dear all,
this is to notify an unexpected behaviour for async validation and FieldArray. 
I have a form that contains one input text Field ('slug') and one FieldArray field ('addresses'). 
I would like to trigger the async validation for both fields on blur of 'slug' and any item 'addresses' array.
Both fields are registered in the same way:
```javasceript
export default reduxForm({
    form: FORM_NAME,
    enableReinitialize: true,
    keepDirtyOnReinitialize: true,
    validate,
    asyncValidate,
    asyncBlurFields: ['slug', 'addresses']
})(ProfilePublicForm);
```

### What is the current behavior?
The async validation is triggered only on blur of the input text Field. Nothing happens if I interact with the FieldArray (push, remove, edit an item of the array).

### What is the expected behavior?
The async validation is triggered after the onblur of any item of the FieldArray

### Libs version
```
 "redux-form": "^7.3.0",
 "redux": "^3.7.2",
```

**Comment by filipposarzana** [comment]
Hi @danielesalvatore 

```
export default reduxForm({
    form: FORM_NAME,
    enableReinitialize: true,
    keepDirtyOnReinitialize: true,
    validate,
    asyncValidate,
    asyncBlurFields: ['slug', 'addresses[]']
})(ProfilePublicForm);
```

You should change `addresses` to `addresses[]` because redux-form makes detect of `[]` to catch if it's field-array :+1:

**Comment by danielesalvatore** [comment]
Hi @filipposarzana thank you for your reply and sorry for my late one.

I tried what you just suggested but unfortunately with no success...

[Here](https://github.com/gianlucadelgobbo/AVnode.net/blob/master/app/redux/components/common/form/components.js#L245) is how I create the render component and [here](https://github.com/gianlucadelgobbo/AVnode.net/blob/master/app/redux/components/profile/public/form.js#L95) how the form is initialised. The async validation is triggered correctly on blur of the 'slug' field but nothing happen on blur of the 'address' field. 

I even tried to have the render component of the 'address' field to be a FieldArray that uses internally the same render component of the 'slug' component but unfortunately it did work (to see if I did something wrong with the render component itself).

**Comment by filipposarzana** [comment]
Hi @danielesalvatore what I've done so far when I need to asyncValidate arrayField is using the code above and inside `asyncValidate` function having something like this:

```
export const asyncValidate = (values, _, props, fieldName) => {
  const fieldMatch = fieldName.match(/(addresses)\[(\d)\]/
  if (!!fieldMatch) {
    const value = values[fieldMatch[1]][2]
    ...
  }
}
```

Then I'd use `value` to asyncValidate it.
Unfortunately I did not found anything out-of-the-box from redux-form to handle asyncValidation on fieldArray, so you need to customize it a little.
After months of discovery we found this solution which I think is probably the most safe one

Let me know :wink:

**Comment by danielesalvatore** [comment]
Ciao @filipposarzana !
Thanks again for your reply.

The code above makes perfectly sense to me but I have a question: does your redux-form trigger the `asyncValidation` on blur for the fields of the `FieldArray`?
In my case this is exactly the problem: I registered two fields on `asyncBlurFields: ['slug', 'addresses[]']` as you suggested but the async validation is still called only on blur of the first one :(

I tried adding the `[]` on `asyncBlurFields: ['slug', 'addresses[]']`, the name of the FieldArray and the combination of them but the validation is not triggered. And when I set the FieldArray's name to `address[]` it is even prevented the dynamic addition of new item to the array ( i click on my + button to add new address to the list but nothing happens)

**Comment by filipposarzana** [comment]
@danielesalvatore we validate on `change`, if you want that you need to set them on `asyncChangeFields` which has the same api of `asyncBlurFields`.
Moreover you can use `shouldAsyncValidate` to decide on which conditions trigger `asyncValidation`.

Let me know if it's clear enough :+1:

**Comment by danielesalvatore** [comment]
It worked!! 🥇 

This did the trick for the async validation of FieldArray on Blur:

`
asyncBlurFields: ['users[].email']
`

Thank you @abair91 and @filipposarzana for you help!!

**Comment by AlfredoQT** [comment]
Hello!!

@danielesalvatore Your post helped me a lot, I am currently having the same issue. How do you throw the error for that specific email though?

**Comment by AlfredoQT** [comment]
How would you throw an error to the specific email?

**Comment by sebastienva** [comment]
throw { users: { 0: { email: 'cool' } } };

**Comment by canotech** [comment]
How I can do for not what will erase msg error another field of field array with the same name but index different??

**Comment by sandrasoueid** [comment]
Having the same problem as canotech. How can I maintain errors from a field array in previousErrors (asyncErrors)?

**Comment by canotech** [comment]
@sandrasoueid  That I did it was into my parent component what is a redux form, I configured that next

 
```
export default connect(mapStateToProps, { getQuotationData, saveInsureds, getCountries,
  changePlanInfo, createQuotation, leaveQuote, getPostalCodesAction, setQuoteToPurchase })(reduxForm({
  form: 'InsuredsForm',
  asyncValidate,
  persistentSubmitErrors:true,
  asyncBlurFields: ['insureds[].postalCode'],
  asyncChangeFields: ['insureds[].postalCode'],
})(InsuredsFormArray));
```


and the magic is it  into my function asyncValidate,  it is works fine for one field, the logic is the same for more input fields


```
const asyncValidate = function(values, fn, props, index){
    let indexNumber;
  if(index){
    indexNumber = index.substr(9,1);
  }
  if(indexNumber){
    if(values.insureds[indexNumber].postalCode && values.insureds[indexNumber].country === 'MX'){
      return props.getPostalCodesAction(values.insureds[indexNumber].postalCode).then((resp)=>{
        
        if(resp.payload){
          if(resp.payload.response){
            if(resp.payload.response.status === 404){
              throw {
                insureds: {
                  [indexNumber]: { postalCode: 'El código postal no existe' }
                }
              };
            }
          }
        }
      });
    }else{
      return new Promise((resolver)=> {
        resolver();
      });
    }
  }else{
    return new Promise( async(resolver,reject)=> {
      let errors = {};
      if(values.insureds){
        for (let i=0; i < values.insureds.length;i++){
          if(values.insureds[i].country === 'MX'){
            const promise = await props.getPostalCodesAction(values.insureds[i].postalCode);
            if(promise.payload){
              if(promise.payload.response){
                if(promise.payload.response.status === 404){
                  errors[i] = {
                    postalCode: 'El código postal no existe'
                  };
                }
              }
            }
          }
        }
      }
      const length = Object.keys(errors).length;
      if(length > 0){
        reject({insureds: errors});
      }else{
        if(props.syncErrors){
          if(props.syncErrors.insureds){
            
            if(Object.keys(props.syncErrors.insureds).length > 0){
              const errorsSync = {};
              for(let j = 0 ; j < props.syncErrors.insureds.length ; j++){
            
                if(_.size(props.syncErrors.insureds[j]) > 0){
                  errorsSync[j] = props.syncErrors.insureds[j];
                }
              }
              if(Object.keys(errorsSync).length > 0){
                reject({insureds: props.syncErrors.insureds});
              }else{
                resolver();
              }
            }else{
              resolver();
            }
          }else{
            resolver();
          }
        }else{
          resolver();
        }
      }
    });
  }
  
};```

I hope that help for you!
