### ISSUE TITLE
Provide way to access component state in onSubmitSuccess

### ISSUE THREAD

**Issue by madisvain** [erikras/redux-form#3914]
This is a feature request to provide a way to change component state in onSubmitSuccess method for reduxForm decorator.

The current reduxForm provides access to result, dispatch and props:
https://redux-form.com/7.3.0/docs/api/reduxform.md/#-code-onsubmitsuccess-function-code-optional-

So it would be possible to do something like this:
```javascript
export default compose(
  connect((state) => ({
    rates: state.rates
  })),
  reduxForm({
    form: 'rate',
    onSubmit: (data, dispatch) => {
      ...
    },
    onSubmitSuccess: (result, dispatch, props) => {
      // This is the current part you can not do.
      // You can not setState for local component.
      this.setState({ modalVisible: false })
    }
  })
)(Rates)
```

There is a way of doing this for onSubmit when using the Form component. So maybe the other option would be to add onSubmitSuccess as props you can pass to Form?
https://redux-form.com/7.3.0/docs/api/form.md/

**Comment by gustavohenke** [comment]
Functional components don't have a ref, so this wouldn't work.

You can however work around this by providing the state from components up in the hierarchy.
Suggestion: [recompose's `withState()` HOC](https://github.com/acdlite/recompose/blob/master/docs/API.md#withstate).

**Comment by madisvain** [comment]
@gustavohenke this is definitely the correct answer. appreciate the time - recompose works wonders here.
