### ISSUE TITLE
Feature: Add example code to render custom field components

### ISSUE THREAD

**Issue by c0d3x** [erikras/redux-form#3915]
Could you provide an example page that shows how to make custom markup for all the supported field types?

I was only able to find how to render a input field.
And I need to override the "select, radio, checkbox, ++" with bootstrap classNames and our custom validation/error handling.

Example of my fields.js file and the input I want to export to use in forms:
```
import React, { Component } from 'react';

export const renderInput = (field) => (
    <div className={'input-group ' + (field.meta.touched && field.meta.error && 'input-error')}>
        <label htmlFor={field.name} className="control-label input-label">{field.label}</label>
        <input {...field.input} placeholder={field.label} type={field.type} className="form-control" />
        {field.meta.touched && field.meta.error &&
            <span className="input-error-message">
                <i class="fa fa-info" />
                {field.meta.error}
            </span>
        }
    </div>
);
```

**Comment by gustavohenke** [comment]
The examples are everywhere in the docs.

[Here is the Material UI one](https://redux-form.com/7.3.0/examples/material-ui/), which should help you get started.
You can also search around the closed issues to find some about Bootstrap itself.
