### ISSUE TITLE
Allow disabling of change actions

### ISSUE THREAD

**Issue by DannyRyman** [erikras/redux-form#3917]
For forms that have a large number of fields, there is a very noticeable lag when typing into input boxes. If you have over 30 fields then capturing notes in a text area becomes unreasonably slow. It would be great to have the option of disabling the change action so that the store is updated on blur only.

**Comment by timhwang21** [comment]
You can already do this with prevent default on the event.

You are also probably connecting to the entire form value object in your parent which is what's killing your performance. One fields updates shouldn't make other fields rerender.

**Comment by gustavohenke** [comment]
Thanks for the helping with that, @timhwang21.
Add throttling/debouncing to the change actions is not something I see Redux Form getting any time soon.
