### ISSUE TITLE
Validation : multiple errors on one field ?

### ISSUE THREAD

**Issue by k4st0r42** [erikras/redux-form#3921]
Hello,

Is it possible to have multiple errors on one field (or on global form error) using validate() function of reduxForm() and validate() function of Field ? 

I want to aggregate the results of theses different validation method (form and fields) in order to have an array of validation messages for each fields of my form, and for the global error.

Is it possible ?

Thank you

**Comment by timhwang21** [comment]
Yeah, just write your validation function to return an array, and in add logic to your component to display the array as a list.

**Comment by k4st0r42** [comment]
And using field level validation with an array of functions, is it possible?

Ex:

<Field name="xxx" component={renderField} validate={[ onlyNumber, minLength3 ]} />

**Comment by k4st0r42** [comment]
Another solution could be add line break in error message
But it is not possible to use JSX in error messages, isn't it ?

**Comment by danielrob** [comment]
@k4st0r42 you got this exactly as @timhwang21 suggested. I can't remember, but it might be that this only returns one error message at a time. If you want to combine error strings, you may need to write a combining validator which calls the other validators and adds their messages together. It should return an array and your JSX can loop over that array adding a <br> after each.
