### ISSUE TITLE
asyncValidate does not pass error

### ISSUE THREAD

**Issue by NikolaiSemenov** [erikras/redux-form#3924]
i try to do example
https://redux-form.com/6.4.3/examples/asyncvalidation/
```js
const isValidEmail = value => {
  const endpoint = process.env.REACT_APP_EMAIL_VALIDATION;
  const url = `${endpoint}&email=${value.currentAddressemail}`;
  return axios.get(url).then(result => {
    const isValid = result.data.format_valid;
    if (isValid === false) {
      const err = {};
      err["currentAddress.email"] = "That email is taken";
      throw { ...err };
    }
  });
```
but if isValid = false asyncValidate does not pass error
i not understand 'why'
help me, please

**Comment by gustavohenke** [comment]
Hello @NikolaiSemenov, that's not enough code for us to see why it's not working.

Please also note that we reserve our GitHub issue tracker for bug reports and feature requests; support requests should be made [on StackOverflow](https://stackoverflow.com/questions/tagged/redux-form), where more people are likely to help (and answers will be more visible).

Thanks for using Redux Form!

**Comment by NikolaiSemenov** [comment]
Hello @gustavohenke, I moved this question [on StackOverflow](https://stackoverflow.com/questions/49356651/why-asyncvalidate-does-not-pass-error-in-redux-form), and add more information. Thank you
