### ISSUE TITLE
ResetForm function does not clear all values

### ISSUE THREAD

**Issue by ala85** [erikras/redux-form#393]
This can be reproduced here : http://erikras.github.io/redux-form/#/examples/simple?_k=4lzvyx

Fill the Favorite Color with an option and click 'Clear Values',: The option will still be visible.

Calling a forceUpdate() wont work.

**Comment by j-clark** [comment]
I'm able to reproduce this for fields that are being normalized. If they're being normalized, when the values get to the `resetForm` function, they're missing the `_isFieldValue` flag, but if I remove the normalizer completely, the flag is set and `resetForm` works

**Comment by erikras** [comment]
The original issue here was solved by doing this, but #562 is still a good PR.

![redux form 2016-02-11 08-42-02](https://cloud.githubusercontent.com/assets/4396759/12977862/61f9f2e0-d09b-11e5-8876-4112770bd3a4.jpg)
