### ISSUE TITLE
Can we use office-ui fabric components in redux-form <Field>

### ISSUE THREAD

**Issue by ahamedfazil** [erikras/redux-form#3933]
Hi,
I am trying to use office-ui fabric component in redux-form. 

Let's say I have a field and I want that component to be rendered from office ui fabric component - <TextField />

```
import { TextField } from "office-ui-fabric-react/lib/TextField";
import { Field } from "redux-form";

const renderField = () => (
  <div>
    <TextField value="testValue" />
  </div>
);

<Field name="projectName" component={renderField} type="text" />
```

It just renders the component but it does not act with redux-form functionality. Please suggest me how could we use office-ui fabric component in redux-form. Thank you in advance.

**Comment by gustavohenke** [comment]
There are [examples using Material UI](https://redux-form.com/7.3.0/examples/material-ui/). You can try following that.
