### ISSUE TITLE
Await async validation before submit

### ISSUE THREAD

**Issue by dontub** [erikras/redux-form#3934]
### Are you submitting a **bug report** or a **feature request**?
bug report

### What is the current behavior?
If a form is submitted when no async validation has been performed (no field was entered or changed), an async validation is initiated, but the end of the validation is not awaited and the form is submitted.

### What is the expected behavior?
On submit an async validation should be awaited and the submit should only be executed if the validation succeeded.

**Comment by gustavohenke** [comment]
I couldn't replicate with this sandbox: https://codesandbox.io/s/6zlj83l1wz
Please provide one that replicates your issue.

**Comment by dontub** [comment]
Found the issue. It happened because of some extra code that is used to keep the error if a previous submission failed and the form isn't changed afterwards. Sorry for the falsely bug report.
