### ISSUE TITLE
Error: Given action "@@redux-form/SET_SUBMIT_FAILED", reducer "error" returned undefined.

### ISSUE THREAD

**Issue by tsm91** [erikras/redux-form#3939]
### Are you submitting a **bug report** or a **feature request**?
A bug

### What is the current behavior?

Application fails when reducer which handles `@@redux-form/SET_SUBMIT_FAILED` returns with undefined.

```
Error: Given action "@@redux-form/SET_SUBMIT_FAILED", reducer "error" returned undefined. To ignore an action, you must explicitly return the previous state. If you want this reducer to hold no value, you can return null instead of undefined.
```

### What is the expected behavior?
For the reducer to return `null` maybe to get rid of this redux error.

### Other information

<img width="1276" alt="screen shot 2018-03-27 at 13 14 21" src="https://user-images.githubusercontent.com/4459551/37964235-10fdacb8-31c1-11e8-876a-a4cb8c2b965a.png">

P.S: excuse me if this is not a bug but and expected behaviour. I am pretty new to `redux-form`

**Comment by tsm91** [comment]
In my case this happens when validation fails (returns with non-empty object).

```js
export default compose(
  ...
  reduxForm({
    form: 'message',
    validate: values => {
      const errors = {}

      if (!values.message || (values.message && values.message.trim().length === 0)) {
        errors.message = 'required'
      }

      return errors
    },
  }),
)(ChatInput)
```

**Comment by gustavohenke** [comment]
Please provide a reproducible sandbox.

**Comment by tsm91** [comment]
@gustavohenke during the process of creating a sandbox i realised the problem is in my general purpose error reducer... 😅 Which basically was looking for any action with an `error: true` however it wasn't prepared to handle `undefined` as payload

sorry for my mistake, i am closing this as the bug was in my code
