### ISSUE TITLE
Textarea Not Cleared when Blowing Away Form Data

### ISSUE THREAD

**Issue by adailey14** [erikras/redux-form#394]
Following the first suggestion here: http://erikras.github.io/redux-form/#/faq/how-to-clear, I am blowing away my form data after the form is submitted (and on certain other events). I've found that this will not clear the value in a textarea, while it will clear values in a text input. I think this is because the value goes from being a string, to being null, so react treats the textarea as 'uncontrolled' and doesn't clear its value. If that's the case though, not sure why it's different than a normal input.

My workaround is to do this:
```
<textarea value={this.props.value || ''} />
```

**Comment by bryce-larson** [comment]
+1

**Comment by erikras** [comment]
Yep. https://github.com/facebook/react/issues/2533

From [Simple Example](http://erikras.github.io/redux-form/#/examples/simple):

![redux form 2016-01-05 18-13-10](https://cloud.githubusercontent.com/assets/4396759/12121872/0e5acd6a-b3d8-11e5-8863-14c4ff4825a8.jpg)

Perhaps this warrants a FAQ all to itself...
