### ISSUE TITLE
Field-Level Validation & error translation

### ISSUE THREAD

**Issue by k4st0r42** [erikras/redux-form#3940]
I try to use Field-Level Validation with i18n.
I'm using react-intl (https://github.com/yahoo/react-intl), so I tried this:

`<Field name="Label"  component={renderField} validate={[required(this.props.intl)]}`

With validation function : 

`const required = (intl) => (value) => {return value ? undefined : intl.formatMessage({id:"Required"})};`

The issue : When I have an error in my field Label, if I change language, the state of my field is lost and my error message disappear.

How can I integrate correctly react-intl for validation messages in Field-Level Validation?

**Comment by gustavohenke** [comment]
Please request usage support on StackOverflow.

**Comment by k4st0r42** [comment]
It seems to be the same issue than #3757

**Comment by danielrob** [comment]
@k4st0r42 #4017 should explain the field-level-validation part. For internationalisation please see #3155
