### ISSUE TITLE
Providing initial values doesn't seem to work

### ISSUE THREAD

**Issue by christian8287** [erikras/redux-form#3942]
### Are you submitting a **bug report** or a **feature request**?

Bug report

### What is the current behavior?

https://plnkr.co/edit/8rSWX6GAtf50jGx0CSNM?p=preview

In this plunkr you can try to dispatch "LOAD VALUES" action which should set the initial values of the form, but this is **not** the case. Form still stays empty.

### What is the expected behavior?
Initial Values should be set in the form when the "LOAD VALUES" Button is clicked, but this is not the case. The React Component updates, but the form values are still the same.

### What's your environment?

Redux Form version 7.3.0
Chromium Version 64.0.3282.167 running on Ubuntu 17.10

### Other information

No Stacktraces, initial Values are not set correctly.

**Comment by gustavohenke** [comment]
You didn't add the redux form reducer.
