### ISSUE TITLE
Any thoughts on making lodash and lodash-es a peer dependency? 

### ISSUE THREAD

**Issue by dchhetri** [erikras/redux-form#3945]
### Are you submitting a **bug report** or a **feature request**?
Feature

### What is the current behavior?
lodash is listed as dependency

### What is the expected behavior?
For debate.

### Other information
Wondering if it make sense to list lodash and lodash-es as peerDependency to avoid having multiple lodash copies? Asking specifically for those two because lodash is a very common library that clients will most likely have when using redux-form.

**Comment by danielrob** [comment]
I'm not sure it does. We don't expect/need the user to work with lodash as well. See https://nodejs.org/en/blog/npm/peer-dependencies/
