### ISSUE TITLE
redux-form/INITIALIZE called after handlesubmit resets form values

### ISSUE THREAD

**Issue by jonathanasquier** [erikras/redux-form#395]
Hi, I have a toggle checkbox to display/hide fields in a form which is not part of the saved model.
On handlesubmit  redux-form/INITIALIZE is dispatched and my value is reseted.
Hi can I prevent that?

Thanks!

**Comment by erikras** [comment]
#370. It's a known issue. Working on it....

**Comment by erikras** [comment]
This should be fixed in [`v4.0.0`](https://github.com/erikras/redux-form/releases/tag/v4.0.0). Come and get it!
