### ISSUE TITLE
how to avoid 'e' in input type NUMBER

### ISSUE THREAD

**Issue by pvaritta** [erikras/redux-form#3952]
Now, I'm using  redux-form : "^7.2.0" version

In the input type 'number' when I type 'e', the values in redux state be blank( ' ' ). I wonder that why in redux-state blank when I type 'e' BUT in UI I still see 'e' letters. 
I just want to know that redux-form allowed to type 'e' in input number or not. If not, should we have enabled type 'e' in UI? or how to find the way why when type 'e' the values in state will blank.

Thank you

**Comment by bstil22** [comment]
have a google:  https://stackoverflow.com/questions/31706611/why-does-the-html-input-with-type-number-allow-the-letter-e-to-be-entered-in
