### ISSUE TITLE
Autocomplete doesn't work in Firefox

### ISSUE THREAD

**Issue by steplerbox** [erikras/redux-form#3953]
### Are you submitting a **bug report** or a **feature request**?
This is a bug report

### What is the current behavior?
Sandbox: https://codesandbox.io/s/mZRjw05yp

How to reproduce:
0. open Firefox
1. input first name
2. click submit
3. try to input first name again

### What is the expected behavior?
autocomplete should work, but in Firefox it doesn't work, in Chrome works.

### Sandbox Link
https://codesandbox.io/s/mZRjw05yp

### What's your environment?
windows 10, Firefox 59.0.2 (64-bit)

**Comment by kiknag** [comment]
Still not fixed. I have the same problem.

**Comment by sylenien** [comment]
Same thing but with password saving prompt.

**Comment by renatoagds** [comment]
Autocomplete is not related with the library, since we don't implemente `autocomplete` attribute in any part of the code. Please check if your browser doesn't turn off this feature.
