### ISSUE TITLE
The api page is broken

### ISSUE THREAD

**Issue by abhatia-lix** [erikras/redux-form#3955]
When i tried to access the Field API doc today, i am getting the following page.

![image](https://user-images.githubusercontent.com/28400428/38206914-28e97434-367a-11e8-8a2c-9dc2de5e160b.png)

**Comment by gustavohenke** [comment]
Looks like it was something temporary 😃 it no longer happens.

**Comment by erikras** [comment]
Yes, there were some JS updates to the docs yesterday. Thanks for the reporting!
