### ISSUE TITLE
It appears that redux-form.com website is not working now.

### ISSUE THREAD

**Issue by binshu2013** [erikras/redux-form#3958]
I just went to https://redux-form.com and got some black/white page (see attachment).
![redux-form](https://user-images.githubusercontent.com/5490041/38225168-346cf968-36b9-11e8-8ee5-92365e91daa6.png)

**Comment by gustavohenke** [comment]
Some issue with CDN, perhaps? 

![screen shot 2018-04-03 at 12 08 24](https://user-images.githubusercontent.com/826553/38225327-c0538e5a-3737-11e8-8a84-fabf1352c21d.png)

**Comment by binshu2013** [comment]
Weird, I can see previous version api though. 
<img width="1621" alt="screen shot 2018-04-02 at 9 11 12 pm" src="https://user-images.githubusercontent.com/5490041/38225429-7f61d9ce-36ba-11e8-8b51-98bf1d8daded.png">

**Comment by erikras** [comment]
Yes, there were some JS updates to the docs yesterday. Should be okay now. Thanks for the reporting!
