### ISSUE TITLE
Accessing form errors 

### ISSUE THREAD

**Issue by dawidvdh** [erikras/redux-form#396]
how I can access a forms error in another component?

Currently have a situation where all my form errors need to display in a header component.

Any help would be greatly appreciate.

**Comment by justinbutt3r** [comment]
Having a similar issue. Been struggling a bit.

**Comment by djvistasa** [comment]
Same here, still no solution to this?

**Comment by tstavinoha** [comment]
Can't you just @connect state.form.formname? It should contain errors

**Comment by dawidvdh** [comment]
@tstavinoha it doesn't contain the validation, unless i am entirely wrong... but as far as i can see errors don't change the accessible 'state' of the form.

**Comment by kevana** [comment]
I'm not seeing the validation results or error messages in the state tree on the [synchronous-validation example](http://erikras.github.io/redux-form/#/examples/synchronous-validation).

<img width="426" alt="screenshot 2015-12-22 01 35 09" src="https://cloud.githubusercontent.com/assets/981551/11950250/48812634-a84c-11e5-8f14-5ed29a4c7685.png">

**Comment by erikras** [comment]
The sync validation errors are not kept in the state. If you want them in another component, you will need to `reduxForm()` that other component with the same form name, fields and validation function.

From https://github.com/erikras/redux-form/issues/45#issuecomment-137027739:

> **If you can calculate it from the state, don't store it in the state.**

**Comment by gustavjf** [comment]
> you will need to reduxForm() that other component with the same form name

Is this also the case if you want to access form errors in a child component that does not have a separate form? For example, `ParentComponent` contains a form, and all inputs for that form are rendered in the child components of `ParentComponent`.

**Comment by erikras** [comment]
@gustavjf I'm not 100% sure what you mean. You can always pass the errors down from parent to child.

The architecture I've been using is (in incredibly rough pseudo code):

```js
@reduxForm()
class MyForm {
  render() {
    return <MyFormFields fields={this.props.fields}/>;
  }
}

class MyFormFields {
  render() {
    // return inputs
  }
}
```
That way my fields are in a component that doesn't care where its fields objects came from, and several `<WhateverFields>` components can be displayed together, or apart or however.

Not sure if that helps you...

**Comment by gustavjf** [comment]
@erikras 

Right! That has been my approach as well. I can see the changes in state given the `fields` const being passed as props but the errors don't seem to be present.

I am trying to build a multi-step form where the form is in a wrapping parent component, and each step in the form is a "step" component. However, when I try to conditionally set a class (`bsStyle`) in the step component's input field, based on the rule in `validate`, `inputA.errors` does not exist. 

Here is a hastily put together example. Hopefully I didn't leave anything out, my eyes are a bit dry :)

```
// MultiStepForm.js

import React, { Component, PropTypes } from 'react'
import { reduxForm } from 'redux-form'
import { Input } from 'react-bootstrap'

import FormStep1 from './FormStep1'
import FormStep2 from './FormStep2'

export const fields = [
    'step1.inputA',
    'step1.inputB',
    'step2.inputC',
    'step2.inputD',
}

const validate = values => {
    const errors = {}
    if ( !values.inputA ) {
        errors.inputA = 'Required'
    }
    return errors
}

class MultiStepForm extends Component {

    static PropTypes = {
        fields: PropTypes.object.isRequired,
        handleSubmit: PropTypes.func.isRequired,
        resetForm: PropTypes.func.isRequired,
        submitting: PropTypes.bool.isRequired
    }

    state = {
        step: 1
    }

    renderFormSteps = () => {
        switch ( this.state.step ) {
            case 1:
                return (
                    <FormStep1
                        nextStep={ this.nextStep }
                        fields={{ ...this.props.fields.step1 }}
                    />
                )
            case 2:
                return (
                    <FormStep2
                        nextStep={ this.nextStep }
                        previousStep={ this.previousStep }
                        fields={{ ...this.props.fields.step2 }}
                    />
                )
            // case 3 and so on
        }
    }

    nextStep = () => {
        this.setState({
            step: this.state.step + 1
        })
    }

    previousStep = () => {
        this.setState({
            step: this.state.step - 1
        })
    }

    render() {
        const { handleSubmit } = this.props

        return (
            <form
                name="form"
                onSubmit={ handleSubmit }
            >
                { this.renderFormSteps() }
            </form>
            // the submit button is in a step component not included here
        )
    }
}

MutliStepForm = reduxForm({
    form: 'MultiStepForm',
    fields,
    validate
})( MultiStepForm )

export default MultiStepForm;
```

```
// FormStep1

import React, { Component, PropTypes } from 'react'
import { Input } from 'react-bootstrap'

export default class FormStep1 extends Component {

    static propTypes = {
        previousStep: PropTypes.func.isRequired,
        nextStep    : PropTypes.func.isRequired,
        fields      : PropTypes.object.isRequired
    }

    state = {
        startDate: moment()
    }

    render() {
        const {
            fields: {
                inputA,
                inputB
            }
        } = this.props

        return (
            <Input
                type="text"
                name="inputA"
                label="Input A"
                { ...inputA }
                bsStyle={ inputA.touched && inputA.error ? 'error' : null }
            />
            <Input
                type="text"
                name="inputB"
                label="Input B "
                { ...inputB }
                bsStyle={ inputB.touched && inputB.error ? 'error' : null }
            />
        )
    }
}
```

```
// FormStep2.js

import React, { Component, PropTypes } from 'react'
import { Input } from 'react-bootstrap'

export default class FormStep2 extends Component {

    static propTypes = {
        previousStep: PropTypes.func.isRequired,
        nextStep    : PropTypes.func.isRequired,
        fields      : PropTypes.object.isRequired
    }

    state = {
        startDate: moment()
    }

    render() {
        const {
            fields: {
                inputC,
                inputD
            }
        } = this.props

        return (
            <Input
                type="text"
                name="inputC"
                label="Input C"
                { ...inputC }
                bsStyle={ inputC.touched && inputC.error ? 'error' : null }
            />
            <Input
                type="text"
                name="inputD"
                label="Input D"
                { ...inputD }
                bsStyle={ inputD.touched && inputD.error ? 'error' : null }
            />
        )
    }
}
```

Do you mean to decorate the step components with `reduxForm()` the same way as in the parent component?
