### ISSUE TITLE
Documentation is ahead of latest published version 

### ISSUE THREAD

**Issue by BenLorantfy** [erikras/redux-form#3963]
### Are you submitting a **bug report** or a **feature request**?

bug

### What is the current behavior?

Latest documentation is out of sync with published version. The latest documentation has changes that haven't been published to npm yet. 

### What is the expected behavior?
Documentation should be in-sync with the published version.

### Sandbox Link

For example, the immutableProps prop was added to the Field component 13 days ago.
See: https://github.com/erikras/redux-form/pull/3849/files#diff-bc25b68496ace911720ffd29530b6888R137
This change to the documentation is now live here (note the 7.3.0 in the url): https://redux-form.com/7.3.0/docs/api/field.md/#-code-immutableprops-array-lt-string-gt-code-optional-

However, the latest version is 7.3.0, which was last published a month ago, and does not actually have this feature.

**Comment by markewallace** [comment]
Also the new documentation contains broken links e.g. https://redux-form.com/7.3.0/docs/faq/ButtonType.md

**Comment by mgreystone** [comment]
Afraid is the same with the [`isDirty`](https://redux-form.com/7.3.0/docs/api/selectors.md/#-code-isdirty-formname-string-code-returns-code-state-fields-string-gt-dirty-boolean-code-) & [`isPristine`](https://redux-form.com/7.3.0/docs/api/selectors.md/#-code-ispristine-formname-string-code-returns-code-state-fields-string-gt-pristine-boolean-code-) selectors. Those selectors do not accept `...fields` in 7.3.0, but it looks like those features were added in #3900

**Comment by BenLorantfy** [comment]
So this is just gonna get buried eh? That's great...

**Comment by gustavohenke** [comment]
Sorry @BenLorantfy, we don't really have a workforce to deal with code changes nowadays. Mostly every recent change is external contributor made.

**Comment by danielrob** [comment]
@BenLorantfy it's great to see the documentation is making you more informed of the latest codebase changes, it seems to be doing it's job! 

The specific items you raised seem repaired with the `7.4.x` release. 

Normally merging and releasing are quite closely tied, in this case there was a bit of a gap. Merges appear to update the documentation ahead of a release. It's good to be reminded that these things actually matter to tangible people in tangible ways, thanks for pointing that out.
