### ISSUE TITLE
How to derive and set a field value from other fields

### ISSUE THREAD

**Issue by baj84** [erikras/redux-form#3965]
Hi,

I have two date fields and one 'duration' field on my form, when either of the date fields change I need to run some logic to determine the duration between the two dates and then update the 'duration' field with the value.

My initial idea was to use the normalize api, but i am not quite sure how I can actually update the 'duration' value in the redux-form reducer.

Any help is appreciated.

**Comment by michaelryancaputo** [comment]
I'm looking to do a similar thing - I have one field which is a "title" and another that should be derived from the title that needs to be parsed into a slug type format automatically.

I'm thinking using the `change` action creator, but that doesn't seem right to me really. Would love some other ideas.

**Comment by baj84** [comment]
Hi, I ended up doing exactly as you said. I just listen to the changes and check the field then update the store as required. e.g.

```		case '@@redux-form/CHANGE':
			if (action.meta.form === 'myForm' && action.meta.field) {
				let newState = { ...state };
				const field = action.meta.field;

				newState[field] = action.payload;

				if (field == 'lease_end_date') {
					newState.lease_expiry_date = action.payload;
				}

				return newState;
			}
			return state;

**Comment by danielrob** [comment]
- `Fields` would be probably be your go to solution here - render the two date fields, and in onChange of either them you can call onChange of the third field. 
 - You could also update the duration value onSubmit if it doesn't need to be displayed to the user.
 - You can use the [raw change action creator](https://redux-form.com/7.4.2/docs/api/actioncreators.md/#-code-change-form-string-field-string-value-any-code-) (not provided by field) to update any form value too, and you could do this individually in each onChange if you need to use `Field`. 
 - Hacking the reducer is pretty heavy handed, wouldn't recommend it.
