### ISSUE TITLE
Update Sync Error Manually

### ISSUE THREAD

**Issue by boy-techy** [erikras/redux-form#3966]
Hi Team,
I need an urgent Support regarding SyncErrors. I am conditionally rendering a component and subcomponent and need destroyOnMount to persistent errors and values. Is there any way that i can update Syncerrors of that subComponent while subcomponent being umounting or unmounted.

**Comment by gustavohenke** [comment]
In your urgency, you seem to have skipped the issue template, which states we don't do support on our issue tracker. Please use StackOverflow for this.
