### ISSUE TITLE
Populating select list asynchronously

### ISSUE THREAD

**Issue by thj-dk** [erikras/redux-form#397]
New at redux and redux-form here, so please bear over with me if I missed the obvious...

I have a simple form where I need to populate a select list asynchronosly. When my container mounts, it dispatches an action that loads the data. A reducer returns the new state with the data. The container passes this data to a `realms` prop of my form component.

I generate the select list like this:

    <select {...realm}>
        {realms.map(r => (<option key={r.url} value={r.url}>{r.name}</option>))}
    </select>

So far so good. The select control is displayed correctly, with the first element in the array selected.
But when I press the submit button, the `realm` form property remains undefined. If I give focus to the select list and submit the form, the property correctly displays the selected value.

What am I missing?

**Comment by xcatliu** [comment]
> The select control is displayed correctly, with the first element in the array selected.

At this moment, you have not initialize the `realm` value in redux-form, it's just the browser's behavior that make the first element being selected.

This might help you: http://stackoverflow.com/questions/6223865/blank-html-select-without-blank-item-in-dropdown-list

**Comment by thj-dk** [comment]
> At this moment, you have not initialize the realm value in redux-form, it's just the browser's behavior that make the first element being selected.

That makes sense. How can I initialize the realm value in redux-form when the data is fetched?

The link you're showing, suggest adding an empty option, as far as I can see. That is an option as well, but I'd like `realms[0]` to be the first selected item, not an empty option.

**Comment by xcatliu** [comment]
> How can I initialize the realm value in redux-form when the data is fetched?

You can call `this.props.fields.xxx.onChange()` when the data is fetched.

For more information, see https://github.com/erikras/redux-form/issues/152

**Comment by thj-dk** [comment]
That seems less than ideal. The form component doesn't know anything about how the data is fetched, and when to call the onChange method. That means the parent containing component should know about the redux-form state, and call onChange with the default selected value?

**Comment by cableray** [comment]
I agree, this isn't intuitive. But I think this is a violation of one-way data flow because of the way selects work. The problem with calling  `x.onChange()` is that it changes this forms pristine state, which is not the desired behavior. There needs to be a better way to deal with this, but I'm thinking it would require a custom select component to handle the details. Any other ideas you think might work, like a callback that ties into the right lifestyle methods, or something?

**Comment by cableray** [comment]
this seems to work:
```javascript
class SyncronizedSelect extends Component {
  static propTypes = {
    onValueMismatch: PropTypes.func.isRequired,
    value: PropTypes.string.isRequired
  }

  checkSelect () {
    const {
      refs: {select},
      props: {
        value: propsValue,
        onValueMismatch
      }
    } = this
    const selectValue = select.value

    console.log('select ref value', selectValue, propsValue)
    if (selectValue !== propsValue) onValueMismatch(selectValue, select)
  }

  componentDidMount () {
    this.checkSelect()
  }

  componentDidUpdate () {
    this.checkSelect()
  }

  render () {
    const {onValueMismatch: _, ...props} = this.props

    return (<select {...props} ref='select' />)
  }
}
```
and the use as follows:
```javascript
<SyncronizedSelect onValueMismatch={(value) => { fieldProps.onChange(value) }}  {...fieldProps}>
# ... options set here
</SyncronizedSelect>
```

although this still has the issue of messing up the pristine state, so ideally there would be a `onValueMismatch` property on `fieldProps` built for just such a case.
 What's the workaround, then, to keep the pristine state the same?
