### ISSUE TITLE
Material UI Select Field Issue while using redux Form

### ISSUE THREAD

**Issue by dasarathvishnu** [erikras/redux-form#3975]
The problem is while performing key board operations on the select field material UI.On pressing any alphabet say ;'G' to select the color green listen in the dropdown of the select field.

Expected behavior is on press of enter the selected field should appear instead none of the field is selected and validation is triggered

Attached the link of bug : https://redux-form.com/7.2.3/examples/material-ui/

on click on enter the select field should display the selected / highlighted value
expected behaviour : http://www.material-ui.com/#/components/select-field

**Comment by anandcgopal** [comment]
I am facing the same problem. Do we have a fix for this?

**Comment by mraj947** [comment]
Even i am also facing same issue.. please suggest solution fr this

**Comment by RamkumarRaman** [comment]
Am also facing the same problem.

**Comment by gustavohenke** [comment]
Use [redux-form-material-ui](https://github.com/erikras/redux-form-material-ui)
