### ISSUE TITLE
Form freezes or unselects the first textfield

### ISSUE THREAD

**Issue by matejm91** [erikras/redux-form#3978]
Possible bug

When ever I try to edit a first text field I created in redux form, frontend just freezes, or I have to click again to continue typing. Also if there are some inital values set, they reset after that happens.

I'm using react 16.2 with redux form 6.6.3 and redux-form-material-ui 4.3.3.

The form is created with https://redux-form.com/7.3.0/examples/material-ui/ as a guideline.

Thank you in advance :)

**Comment by gustavohenke** [comment]
Please provide a sandbox that reproduces your issue.

**Comment by matejm91** [comment]
Fixed it, the prop I was sending to the component that had nothing to do with that particular field was  changing for some reason.
