### ISSUE TITLE
Add src folder to npm package

### ISSUE THREAD

**Issue by mctep** [erikras/redux-form#398]
Hello! Thank you for your job.

After commit https://github.com/erikras/redux-form/commit/1bcf9b2f4edd669f640f3fb0b60f6d116eb0cf1d [eslint import plugin](https://github.com/benmosher/eslint-plugin-import/) began throwing errors by default. It happens because there are no main script in folder.

**Comment by erikras** [comment]
An oversight. Good catch. Thanks. :+1:

**Comment by erikras** [comment]
It's unclear exactly how to do this. Any idea what the [the `npmFileMap` value](https://github.com/erikras/redux-form/blob/master/package.json#L68-L74) should be?

**Comment by theaqua** [comment]
Why not just `files`? It works well.

```
files: [
  "lib",
  "dist",
  "src"
]
```

**Comment by erikras** [comment]
I think what was more important was removing `src` from `.npmignore`. :smile:

Worked on another library I have. I'll close this when I do the next release and verify that the `src` dir is published. Thanks.
