### ISSUE TITLE
Error in "Submit Validation" example, and a question

### ISSUE THREAD

**Issue by bmueller-sykes** [erikras/redux-form#399]
Hi,

I'm trying to get redux-form to work in my app, and as I'm working through your examples (bless you for those), i think I've found a bug.  In this example:

http://erikras.github.io/redux-form/#/examples/submit-validation?_k=50jqgi

...you have this:

`<form onSubmit={handleSubmit(submit)}>`

...but then this:

`<button type="submit" onClick={handleSubmit}>`

I couldn't get things to work until I ripped out the `onClick` event from the submit button.

So first, the fact that those event handlers are different seems like a bug.  

Second, is it necessary to have an `onClick` handler on the submit button when you already have an `onSubmit` handler on the form?  Seems like the `onSubmit` would be sufficient, unless there's something I don't understand about redux-form in general (which is entirely possible).

Thanks, and I hope this helps!
Ben

**Comment by jonathanasquier** [comment]
I don't know if it's related, but hitting enter in any form field triggers a click on the first button of the form (regardless of its type) intead of triggering the onSubmit function on the form element (as it should I believe)
Should I create a new issue?

**Comment by bmueller-sykes** [comment]
In the form you're working with, do you have onClick events on the button(s)? If so, then perhaps "enter" first looks for an onClick even on a button, and then bubbles up to look for an onSubmit at the form level?  Regardless, @erikras will certainly want to see a code sample which demonstrates the issue.

**Comment by jonathanasquier** [comment]
```In the form you're working with, do you have onClick events on the button(s)?```
exactly
```If so, then perhaps "enter" first looks for an onClick even on a button```
absolutely
```and then bubbles up to look for an onSubmit at the form level? ```
Shouldn't it only care about onSubmits ?

**Comment by erikras** [comment]
I thought that `enter` triggered the form submission, not the first button. Regardless, that example has been fixed since the original post. I'm confused. Is there something broken?

**Comment by bmueller-sykes** [comment]
@erikras I think @jonathanasquier is talking about a different issue than my original issue.  I think we'd need to see a code sample to figure out exactly what's going on (or at least I'm too dense to figure it out without seeing some code).

Also, and forgive me if I'm missing something, but if I look here:

http://erikras.github.io/redux-form/#/examples/submit-validation?_k=50jqgi

...I still see `onClick={handleSubmit(submit)}` on the submit button, in addition to the `onSubmit={handleSubmit(submit)}` on the form element itself. My original question was whether both were needed--it seems like you'd only want the `onSubmit` version, and nothing on the submit button itself, right?

**Comment by jonathanasquier** [comment]
Oops I was using version 3.0.* I'm updating and trying again
@bmueller-sykes sorry i've high jacked your issue ^^

**Comment by bmueller-sykes** [comment]
I will never forgive you.

**Comment by erikras** [comment]
> My original question was whether both were needed--it seems like you'd only want the onSubmit version, and nothing on the submit button itself, right?

Oh! No, probably they are not both needed. But the event is silenced, so they don't both fire. The submit button could also be an `<input type="submit"/>`. HTML forms are so dumb...

**Comment by bmueller-sykes** [comment]
That's what I thought, but I couldn't be sure in the brave new world of React.

**Comment by jonathanasquier** [comment]
So I've tested with v4.1.0 and pressing "enter" still submits the first button in the form, whether it is a onClick or a submit. I believe it should trigger only onSubmit functions, on the submit button or on the form (and both shouldn't be needed). So yes @erikras I humbly believe something is broken unless PEBKAC on my side !

**Comment by erikras** [comment]
You are very correct, @jonathanasquier.
```
'Pressing [enter] in a form field is the same as clicking the first <button>' == true
```
So.... what to do about it?

1. Put your submit button first. In which case, yes, the `onSubmit` on the `<form>` is superfluous. You can style it to appear second if you wish.
2. Put an `onKeyDown` listener on every damn input, in which case even the `<form>` tag itself becomes superfluous.
3. ......ummm.... I'm out of ideas.

Forms are the worst part of HTML. Why did I build a form library??

**Comment by bmueller-sykes** [comment]
I may not understand the code under the hood, but could you have it look for the first `<button type="submit">` (or, I suppose, `<input type="submit">` on pressing `[enter]`? Does that help at all? I mean, technically a button that isn't a submit button should not submit a form, right?

**Comment by jonathanasquier** [comment]
Hmm I'd rather prevent the whole form from submitting on enter!
Too bad then...
``` Why did I build a form library??``` How could you think leaving us all alone without it??
@bmueller-sykes +1

**Comment by erikras** [comment]
Depends on your values for "technically" and "should". :smile: 

Nothing about redux-form is causing this behavior. It's the default browser behavior. You can test it with a  static html file.

Searching the DOM for buttons is the old jQuery way. React makes that difficult on purpose.

**Comment by bmueller-sykes** [comment]
wait...[enter] triggers the first button in a form, regardless of what that button type is? Completely outside of React and Redux? So if I had a "clear form" button first, enter would clear the form?  huh.

The worst part about forms is that an unchecked checkbox passes nothing along. That. Is. The. Worst.

**Comment by jonathanasquier** [comment]
That quite a shitty behaviour indeed... :(

**Comment by SpainTrain** [comment]
I think you can avoid this by using `type="submit"` for the submit button and `type="button"` for others.  That just worked in this jsfiddle in Chrome 48 http://jsfiddle.net/s9Ugr/601/ 

See also http://stackoverflow.com/a/16462846/278891

**Comment by erikras** [comment]
Nice one, :es::train:! I might add a FAQ about this.
