### ISSUE TITLE
onSubmitSuccess initialValues prop is not updated to latest

### ISSUE THREAD

**Issue by Noitidart** [erikras/redux-form#3994]
### Are you submitting a **bug report** or a **feature request**?
bug report

### What is the current behavior?
1. Set onSubmit and console log initialValues
2. Set onSubmitSuccess and console log initialValues

### What is the expected behavior?

After submit, initialValues in onSubmitSuccess should have the latest initialValues. It does not.
### Other information

Here is my code simplified:

```
class DomainFormDumb extends Component<Props> {
    render() {
        return (
            <View style={styles.form}>
                <Field component={FieldText} name="domain" label="Domain" />
            </View>
        )
    }
}

const DomainFormControlled = reduxForm({
    form: 'domain-form',
    // enableReinitialize: true, // because domain gets fixed up to properDomain
    validate,
    onSubmit: async (values, dispatch, { initialValues }) => {
        const errors = await dispatch(submitDomain(values.domain)).promise;
        if (errors) throw new SubmissionError(errors);

        console.log('initialValues from onSubmit:', initialValues);
    },
    onSubmitSuccess: async (result, dispatch, { initialValues }) => {
        console.log('initialValues from onSubmitSuccess:', initialValues);
    }
})

const DomainFormConnected = connect(
    function({ domain }: AppShape) {
        return {
            initialValues: {
                domain
            }
        }
    }
)

const DomainForm = DomainFormConnected(DomainFormControlled(DomainFormDumb))

export default DomainForm

```

**Comment by gustavohenke** [comment]
This is app specific logic. It was asked a few times before, for example in #3230.
It's a won't fix.

**Comment by Noitidart** [comment]
Darn. Thanks for fast reply!

**Comment by gustavohenke** [comment]
You can use [`initialize` action creator](https://redux-form.com/7.3.0/docs/api/actioncreators.md/#-code-initialize-form-string-data-object-keepdirty-boolean-options-keepdirty-boolean-keepsubmitsucceeded-boolean-updateunregisteredfields-boolean-keepvalues-boolean-code-):

```js
import { reduxForm, initialize } from 'redux-form';

reduxForm({
  form: 'bla',
  onSubmitSuccess({ result, dispatch }) {
    dispatch(initialize('bla', result));
  }
})
```

**Comment by Noitidart** [comment]
Thanks so much for your fast replies!! Really appreciate it!

I thought `result` is whatever is returned by `onSubmit`. And the `initialValues` in `onSubmit` is not updated. :(
