### ISSUE TITLE
Invalid prop is automatically set to false

### ISSUE THREAD

**Issue by napatwongchr** [erikras/redux-form#3997]
### Are you submitting a **bug report** or a **feature request**?
I'm submitting bug report

### What is the current behavior?
Invalid prop in Login component is automatically set to false even the form doesn't pass the validation rules, when I try to set the layout in App component on Sync validation. (The code is below)

### What is the expected behavior?
Invalid prop should set to true when the form doesn't pass the validation rules, and false when it does.

### What's your environment?
"react": "^16.2.0",
"redux": "^3.7.2",
"redux-form": "^7.3.0",

### Other information
**App Component**
```
class App extends Component {
  constructor() {
     super()
     history.listen((location, action) => {
     this.setLayout(location.pathname)
    })
 }

  componentDidMount()  {
    this.setLayout(history.location.pathname)
  }

  setLayout(url) {
    const emptyLayoutArray = ['/login', '/error-page', '/registration',
    '/verification']
    let isEmpty = indexOf(emptyLayoutArray, url) !== -1 ? true : false
    if (isEmpty) {
      this.props.setEmptyLayout(true, null)
    } else {
      this.props.setEmptyLayout(false, null)
    }
  }

  render() {
    return (
      <Router history={history}>
        <div>
          <NotificationsSystem theme={theme}/>
          { this.props.emptyLayout ? <div className='login-wrapper'><Routes /></div> : <div className='wrapper'>
            <SideBarContainer />
            <div id='content'>
              <Routes />
            </div>
          </div> }
        </div>
      </Router>

    );
  }
}

const mapStateToProps = ({ navigation }) => {
  const { emptyLayout, selectedMenu } = navigation
  return { emptyLayout, selectedMenu }
}

export default connect(mapStateToProps, { setEmptyLayout, selectMenu })(App);
```
**Login Component in Routes**
```
class Login extends Component {
  submit (data) {
    const { loginWithEmailAndPassword, history } = this.props
    loginWithEmailAndPassword(data, () => {
      history.push('/')
    })
  }

  renderButton () {
    const {  invalid, history } = this.props
    return <Button type='submit' disabled={invalid} className='mt-3' color='primary'>
        Submit
      </Button>
  }

  render() {
    return (
      <div id='login-box'>
        <h3 className='mb-4'>
          Login
        </h3>
        <form onSubmit={this.props.handleSubmit(data => this.submit(data))}>
          <Field
            inputClass='form-control mb-3'
            iconClass='fas fa-user mr-2'
            errorClass='error-text'
            name='email'
            type='email'
            component={RenderField}
            label='Email' />
          <Field
            inputClass='form-control mb-3'
            iconClass='fas fa-key mr-2'
            errorClass='error-text'
            name='password'
            type='password'
            component={RenderField}
            label='Password' />
          { this.renderButton() }
        </form>
      </div>
    )
  }
}

const mapStateToProps = ({ auth }) => {
  const { loading, status } = auth
  return { loading, status }
}

export default reduxForm({
  form: 'loginForm',
  validate
})(connect(mapStateToProps, { loginWithEmailAndPassword })(Login))
```

**Comment by gustavohenke** [comment]
> Invalid prop in Login component is automatically set to false even the form doesn't pass the validation rules

That sounds right.
You may be interested in using the [`dirty`](https://redux-form.com/7.3.0/docs/api/props.md/#-code-dirty-boolean-code-)/`pristine`](https://redux-form.com/7.3.0/docs/api/props.md/#-code-pristine-boolean-code-) props to complement disabling your submit button though.

**Comment by napatwongchr** [comment]
Thanks for responding. I attempted to use pristine and dirty, but they are not related to validation rules. They can only check that the form is dirty or not, so I can still click the button even the form doesn't pass the validation rules. Is my understanding correct or am I still confused at some point?Can you explain more.

**Comment by gustavohenke** [comment]
I don't follow your question. Your form will be validated at mount time, and if it fails, then it gets `invalid` prop set to `true` from the start.

I mentioned `pristine`/`dirty` props because they help you leverage the validity of the form, allowing you to check if it's invalid because of a empty state, or because of a user change, etc.

**Comment by napatwongchr** [comment]
I see your point. The problem is that when my login component re-rendered, invalid prop is set to false even the form fails the validation Once it passes still not set to true. Any suggestion on this?

**Comment by gustavohenke** [comment]
If you provide a sandbox that reproduces your issue that would be great, as it's pretty cryptic to me what's going on.

I don't currently see this issue as a bug, so it might be even better if you ask about it on StackOverflow, so that others can chime in and help more effectively.
