### ISSUE TITLE
Can slice name depend on props?

### ISSUE THREAD

**Issue by gaearon** [erikras/redux-form#4]
Apologies if I missed this. Can the slice name depend on props? This could be useful for forms "bound" to specific IDs. For example imagine an address book where every item is editable at the same time. Its key could be a function: `props => `contacts/${props.id}`. Makes any sense?

**Comment by erikras** [comment]
I'm not following. Rephrase?

**Comment by gaearon** [comment]
The decorator assumes I know the state slice name for a particular component when declaring it.
I want it to be dynamic and depend on component props.

**Comment by erikras** [comment]
That did it. I understand now. Certainly seems possible.
