### ISSUE TITLE
Processing errors for deeply nested elements after submit validation

### ISSUE THREAD

**Issue by bvdgraaf** [erikras/redux-form#400]
Hi,

I'm having a hard time processing errors for deeply nested element after a submit validation. Non-nested elements work as expected and their form state in the Redux store is property updated with the error (submitError with a proper exception value).

As far as I can tell it's not possible in version 3.1.7 to process an exception for a deeply nested element. The 'problem' appears to be in the reducer.js implementation, namely:

```javascript
[STOP_SUBMIT](state, {errors}) {
    return {
      ...state,
      ...(errors ? mapValues(errors, (error, key) => ({
        ...state[key],
        submitError: error
      })) : {}),
      _error: errors && errors._error,
      _submitting: false,
      _submitFailed: !!(errors && Object.keys(errors).length)
    };
  },
```

Using a key such as 'userAddresses[0].address' obviously doesn't work as expected.

What would be the right way to process an exception for such an element after submit validation?

**Comment by jsheetzati** [comment]
We also came across this issue when using deep nested forms.

**Comment by travisbloom** [comment]
having the same issues. Returning errors from async validation are not properly being appended to nested form elements

**Comment by twhitledgeati** [comment]
I am using Redux-Form 4.0.3 and am still experiencing the issue.

Here are my fields:

<code> 
	fields: [
                       'userName',
			'addresses[]',
			'addresses[].city,
			'addresses[].state,
			'addresses[].zip
		]
</code>

and this is my promise reject syntax:

<code>
...
 Promise.reject({ 'addresses[0].city: 'this is an error message' }));
</code>

Like @bvdgraaf mentioned, Non-nested elements work as expected:

<code>
...
 Promise.reject({ 'userName': 'this is an error message' }));
</code>

**Comment by erikras** [comment]
Thanks, @twhitledgeati. Good reporting. Will investigate. :mag:

**Comment by cgwyllie** [comment]
We ran in to a similar problem with this.

It wasn't clear, but when we change our validation output to use nested objects instead of keys with object paths in them, it started working.

For example:

```
fields = [
    ...
    'database.port'
    ...
];

...

// Did not work
Promise.reject({
    'database.port': 'Invalid port'
});

// Did work
Promise.reject({
    database: {
        port: 'Invalid port'
    }
});
```

redux-form 4.1.1

**Comment by newsiberian** [comment]
Hi, faced with the same problem. My field is `emails.0.address`. Is there any progress with that?

**Comment by dinonomnom** [comment]
I am facing the same issue. Is there any work being done on this issue, or a work around that could be used to place an error on a single field inside deep nested form?

**Comment by ooflorent** [comment]
Errors must not represent the path but the form structure:

```js
// Bad
{
  "addresses[0].city": "this is an error message"
}

// Good
{
  addresses: {
    0: {
      city: "this is an error message"
    }
  }
}
