### ISSUE TITLE
how to write test to form-values-selector function

### ISSUE THREAD

**Issue by bife1** [erikras/redux-form#4005]
I would like to know how to test redux-form `form-values-selector` function?

my Selectrs.js file
```
import { formValueSelector } from 'redux-form';

export const formSelector = formValueSelector('params');

const getSummParam = state => formSelector(state, 'summ');

export default getSummParam;
```
and here is my testing file Selectrs.test.js
```
import getSummParam, { formSelector } from './Selectors';

describe('selectors test', () => {
  const state = {
    form: {
      params: {
        values: {
            summ: '12',
        }
      }
    }
  };

  it('should return formSelector value', () => {
        expect(formSelector(state)).toEqual(state.form.params);
    });
  it('should return getSummParam value', () => {
    const expectedResult = state.form.params.summ;

        expect(getSummParam(state)).toEqual(expectedResult);
    })
});
```
I have got an error:

`Invariant Violation: No fields specified`

**Comment by gustavohenke** [comment]
`formSelector` wants you to specify a list of fields to retrieve the value.
You aren't doing this in the `should return formSelector value` test.

If you don't want that behaviour, you should use [`getFormValues`](https://redux-form.com/7.3.0/docs/api/selectors.md/#-code-getformvalues-formname-string-code-returns-code-state-gt-formvalues-object-code-) instead -- yeah, I know, two selectors for pretty much the same thing!

**Comment by bife1** [comment]
Ok, BIG THANKS, i feel so stupid...
