### ISSUE TITLE
Redux 4.0 incorrect peer dependency

### ISSUE THREAD

**Issue by MisterKort** [erikras/redux-form#4009]
Hi,

Since Redux 4.0 has been released after installing redux-form got an warning:
`redux-form@7.3.0" has incorrect peer dependency "redux@^3.0.0"`.

Don't forget to update it in the future.

**Comment by gustavohenke** [comment]
#3986 with the support for Redux v4 has been merged.
Look forward to the next release.

**Comment by thehig** [comment]
This error has returned
`warning " > redux-form@7.3.0" has incorrect peer dependency "redux@^3.0.0".`

**Comment by burtek** [comment]
@thehig this has nothing to do with `yarn`'s version. We're all just waiting for #3986 release... Two weeks now

**Comment by thu-sama** [comment]
Same here.

**Comment by erikras** [comment]
Fix released in [`v7.4.0`](https://github.com/erikras/redux-form/releases/tag/v7.4.0).
