### ISSUE TITLE
get input name on normalize

### ISSUE THREAD

**Issue by Gtosta96** [erikras/redux-form#4023]
I would like to request the name attribute on normalize function... I mean, it is possible to get the value, but no the name...
I'm requesting it because I have a very specific case...
I'm rendering multiples Fields through a map, and most of the times I'm not aware of what question's name is changing...

That would be possible?

**Comment by danielrob** [comment]
@Gtosta96 It sounds like you should be using an `FieldArray` with which you can declaratively creating the normalize functions along with rendering the `Field` components. Could you please clarify your use case with some code?
