### ISSUE TITLE
getValuesFromState can cause an error in IE11

### ISSUE THREAD

**Issue by Plummat** [erikras/redux-form#403]
In some cases, the boolean "true" gets passed to getValuesFromState. While this returns an empty array in Chrome and Edge, it returns an error in IE11. This added check with prevent the error(and thusly, the form exploding) in IE11.

I have opened a [pull request](https://github.com/erikras/redux-form/pull/402) to fix this.

**Comment by Plummat** [comment]
Also, if you were wondering when this happens, it's when you check a checkbox - it seems the value, true, leaks it's way into there.

**Comment by ooflorent** [comment]
Fixed by 1317101d5938652a50601eeda6a240ea311ad1b0
