### ISSUE TITLE
defaultProps for a Component do not show up in validate function props argument

### ISSUE THREAD

**Issue by chetnashah** [erikras/redux-form#4036]
### Are you submitting a **bug report** or a **feature request**?
Bug report.

### What is the current behavior?

When a Component is given defaultProps, they do not show up in props argument of validate function.

### What is the expected behavior?
defaultProps should show up validate function's props argument. (see SimpleForm component in codesandbox example)

### Sandbox Link
https://codesandbox.io/s/mm3xx3pvmp

### What's your environment?

All redux form versions

### Other information

logs included in codesandbox example

**Comment by danielrob** [comment]
You're adding default props to your `SimpleForm` component. You need to instead pass them to your redux form component, otherwise redux-form has no way of knowing they exist. e.g. 

```
const ReduxSimpleForm = reduxForm({ ...config }, SimpleForm)

ReduxSimpleForm.defaultProps = { extra: "extra" }
```

See https://codesandbox.io/s/21z150n640
