### ISSUE TITLE
Binding the initial value of a datepicker

### ISSUE THREAD

**Issue by sattaman** [erikras/redux-form#404]
I have had issues binding an initial state to a date picker (react-datepicker). 

The datepicker requires the value as a moment. I tried setting the initial value through initialvalues, but I couldn't get this to work.  

In the end I have had to store the date in another prop and then in componentWillReceiveProps trigger an onChange of the field passing in moment(this.prop.mydate). This feels very hacky though.

**Comment by erikras** [comment]
This might be better in `v4.0`, which allows for more complex values.

**Comment by sattaman** [comment]
HI, thanks for your response. I've just tested it and it still does not get set when passed into initialValues.

**Comment by ryross** [comment]
@sattaman did you get anywhere with this? I think I've hit a similar issue with react-datepicker. I'm using 4.1.5

**Comment by simpixelated** [comment]
Here's what I'm doing, using react-datepicker and redux-form 4.1.2:
```js
const FormDatepicker = props => {
  const selected = props.value ? moment(props.value) : null;
  return (
    <DatePicker {...props} placeholderText={props.placeholder} className="form-control" selected={selected} />
  );
}
```
`props` is the `field` object from redux-form

**Comment by ryross** [comment]
Nice @simpixelated. This is how I did it without needing a wrapper


`<DatePicker {...timespan.date} selected={timespan.date.value ? moment(timespan.date.value, 'MM/DD/YY') : null } onChange={param => timespan.date.onChange(param)} />`

**Comment by erikras** [comment]
Nice examples, guys.

@ryross Your `onChange={param => timespan.date.onChange(param)}` is redundant, as the `{...timespan.date}` is providing that.

**Comment by ryross** [comment]
Thanks for that @erikras I'm still new to react & redux :)

**Comment by erikras** [comment]
Here to help. :smile:

**Comment by jschuman** [comment]
I've implemented @ryross's solution as follows:
```
<DatePicker
  {...birthday}
  selected={birthday && birthday.value ? moment(birthday.value, 'MM/DD/YY') : null }
/>
```

But the problem I'm seeing now is as soon as I tab away from the DatePicker input, the input changes to 'Invalid date'.  Any ideas what I'm doing wrong?

**Comment by znamilya** [comment]
@jschuman, try it
```
<DatePicker
  {...birthday}
  dateFormat='MM/DD/YY'
  selected={birthday.value ? moment(birthday.value) : null }
/>
```

**Comment by Aldizh** [comment]
This seems to be an issue with Material-UI itself. defaultValue as of v0.15.4 does not accept dates other than today's. Use value instead. That did it for me.
Regards!

**Comment by GautierT** [comment]
To avoid 'Invalide date' error on focus loose you should set the date format for moment : 

```
render() {
        const {input, meta, dateFormat, label, startDate, ...rest} = this.props;
        // FYI : dateFormat = 'DD/MM/YYYY';
        return (
            <Form.Field>
                <label>{label}</label>
                <DatePicker
                    {...input}
                    dateFormat={dateFormat}
                    selected={input.value ? moment(input.value, dateFormat) : moment(startDate, dateFormat)}
                    {...rest}
                />
            </Form.Field>
        );
    }
```

**Comment by RajPratim21** [comment]
Can you share your code with using store and recuers with Date-picker. will be a great help.

**Comment by Abhijeetjaiswalit** [comment]
To avoid 'Invalid date' error try following on onChange : 

```
  handleChange(date) {
    if (date._d) {
      this.setState({
        startDate: date,
      });
    }
    else {
      this.setState({
        startDate: '',
      });
    }
  }
```

along with : 

```
return (
            <div className={className}>
                <DatePicker
                    dateFormat={field.dateFormat}
                    maxDate={field.maxDate}
                    selected={field.selected ? moment(field.selected, field.dateFormat) : null}
                    onChange={field.input.onChange}
                    placeholderText={placeholder}
                    isClearable={true}
                    showMonthDropdown
                    showYearDropdown
                    scrollableMonthDropdown
                    scrollableYearDropdown
                />
                <div className="help-block help-block-error">
                    {touched ? error : ''}
                </div>
            </div>
        )
```

**Comment by saurishkar** [comment]
I am seeing exactly the opposite scenario here. 
When i use dateFormat="DD/MM/YYYY", my datepicker gives invalid date error on loosing focus.
If i don't explicitly set the dateFormat prop, it works fine.
Any Suggestions ?
