### ISSUE TITLE
Field-level sync validations are occurring after the user input has been parsed

### ISSUE THREAD

**Issue by swellingt0n** [erikras/redux-form#4042]
### Are you submitting a **bug report** or a **feature request**?

Bug

### What is the current behavior?

When providing parse and format functions to a text field, field-level sync validations are occurring after the user input has been parsed. This will result in a failed validation even though the user input is correct.

### What is the expected behavior?

Field level sync validations should happen before the parse step is invoked, or there should be some way to structure the flow.

### Sandbox Link
https://codesandbox.io/s/0x0v687830

### What's your environment?

RF@7.1.2, OSX 10.12.6, Chrome, Node v8.9.1

### Other information
#3736

**Comment by danielrob** [comment]
What are you currently not able to achieve with validations being run against the store? I.e. why is this unexpected? I'd think validations should be run against the stored value as this ensures the integrity of the actual form state.

**Comment by danielrob** [comment]
Closing as expected behaviour / non-response.
