### ISSUE TITLE
Values not being passed to handleSubmit - form POSTing it's contents in URL

### ISSUE THREAD

**Issue by aikidoshi** [erikras/redux-form#4045]
Hi all,
I have created a form (stateless) that - as usual - has a handleSubmit handler passed in. Done it many times before. Form itself functions perfectly, state, validation, initialValues etc. all fine
_This form is my first that has material-ui components on it with wrappers based on the example on your website, tweaked for material-ui v1.0._
When the submit button is pressed the handleSubmit function receives 'undefined' for all the values passed to it from the form, and the form POSTS itself to a URL showing all of the field contents.
http://localhost:3000/?firstName=Steven&lastName=Bond&email=aikidoshi%40hotmail.com&password=blahdeblah

Very embarrassing!

Any suggestions welcome please. Driving me crazy.

**Comment by gustavohenke** [comment]
Please ask for help on StackOverflow. Also remember to provide your source code.
