### ISSUE TITLE
Reset Custom Component

### ISSUE THREAD

**Issue by smwhit** [erikras/redux-form#4057]
Hi. Is it currently possible to reset the value of a custom component? For example, we have created a wrapper around react-autosuggest. So far, we have not been able to reset the value on the input when redux-form reset is called.

If not, could a mechanism be added?

Thanks

Simon

**Comment by gustavohenke** [comment]
What have you tried?

**Comment by smwhit** [comment]
So we have a redux form wrapper around the react autosuggest component which is nearly identical to the one detailed at #https://github.com/moroshko/react-autosuggest/issues/314

When the form is reset, we can see in the redux developer tools that the form values have been reset to their initial values. Not sure what the convention is to flow the initial value down to the component. We tried to figure out how the native html controls get reset, but didn't make progress.

I can try and create a sandbox with a reproduction, but it might take some time due to privacy issues, in the meantime, is there any docs that I haven't found detailing how to achieve this, or an explanation about how it should work? 
Thanks

**Comment by smwhit** [comment]
Ok so we managed to get this to work. We just needed to pass redux-form "value" prop into the into the component like:

```
render() {
  const { input, value, ...custom } = this.props;
  return (<div>
    <AutoComplete valueOverride={value} 
                               onSuggestionSelected={(_, x) => {
                                  input.onChange(x.suggestion);
                               }} {...custom} />
  </div>
 );
}
```

and then in the auto-suggest-component, we use UNSAFE_componentWillReceiveProps to check if the value has change. If it has, we dispatch an update action.

We were stumped for a while, but it's working perfectly now.
Thanks

Simon
