### ISSUE TITLE
Add option to inject redux-form props as a single object

### ISSUE THREAD

**Issue by ThiefMaster** [erikras/redux-form#4059]
Currently all props from redux-form are injected as top-level props, so if I'm writing a form that deals with error reporting, I might have a naming problem since I might want to call one of my own props `error`, but that prop name is already used by redux-form.

Also, inspecting the `this.props` for debugging purposes will hide my own props between all the redux-form props.

My suggestion is to add an option to `reduxForm()` that specifies a single prop name where all the props  will be injected. So instead of receiving `{anyTouched: ..., handleSubmit: ..., someCustomProp: ..., ...}` the component would instead receive `{[customPropName]: {anyTouched: ..., handleSubmit: ..., ...}, someCustomProp: ...}`

**Comment by gustavohenke** [comment]
Use [`propNamespace`](https://redux-form.com/7.3.0/docs/api/reduxform.md/#-code-propnamespace-string-code-optional-).

**Comment by ThiefMaster** [comment]
Exactly what I was looking for, thanks! Might make a useful FAQ entry!
