### ISSUE TITLE
Adding initalValue to dynamic Field component

### ISSUE THREAD

**Issue by knynkwl** [erikras/redux-form#4060]
I have a custom field range slider, and the field has a defualtValue of 100, but when submitting the values don't get stored. But of course it works and stores the data when a user scrolls the handle.

This field component is dynamically being rendered from an api, so there is no way to just set the initalValue in the store from the container.

What's the best way to accomplish this?

```import React from 'react';
import {Field} from 'redux-form';
import Slider from 'rc-slider';
import { validate } from '../../../Helpers'

const RangerSlider = (props) => ({

  constructor() {
    this.slider = this.slider.bind(this)
  },

  slider(props) {

    const {
      field: { required, titleText, min, max, defaultValue },
      input,
      meta: { touched, error, valid }
    } = props;

    const Handle = Slider.Handle;

    const handle = (props) => {
      const { value, dragging, index, ...restProps } = props;
      
      let val = max == value ? `${value}+` : value;

      return (
        <Handle value={value} {...restProps}>
          <div className='tooltip'>{val}{titleText && ` ${titleText}`}</div>
        </Handle>
      );
    }

    const errorClass = touched ? (error && 'required-error') || (valid && 'validated') : ''
    const classes = `${props.classes} ${errorClass} ${required == 0 ? 'not-required' : ''}`

    return(
      <div className={classes}>
        <Slider
          value={input.value}
          onChange={input.onChange}
          min={Number(min)}
          max={Number(max)}
          defaultValue={Number(defaultValue)}
          handle={handle} />
        {touched && (error && (error && <span className="field-error">{error}</span>))}
      </div>
    )
  },

  render() {
    console.log(props, this)
    return (
      <Field
        {...this.props}
        name={`fields[${props.field.name}]`}
        type={props.type}
        component={this.slider}
        validate={props.required ? validate.required : null}
        format={value => value} />
    )
  }
})

export default RangerSlider
```

<img width="900" alt="screenshot 2018-06-06 at 11 18 31 pm" src="https://user-images.githubusercontent.com/4225771/41076496-f2f31c06-69df-11e8-85a2-29445c17165c.png">

**Comment by danielrob** [comment]
`initialValues` is the mechanism for setting initial / default values on the form. 

Outside of this it's really up to you, you can use `change` actions in `componentDidMount`, or intercept form submission and fill in default values before sending to the server. 

I'm closing this because it doesn't appear to represent a bug or feature request.

**Comment by knynkwl** [comment]
@danielrob There isn't that great of documentation on how I can store a default value in the store on componentDidMount. 

Can you give an example of how this is done, given my example above.

**Comment by danielrob** [comment]
Just with e.g.
```
componentDidMount() {
  this.props.input.onChange('defaultValue')
} 
```

Right, but how do you know the appropriate default value for these dynamically generated fields? Is it truly uncoupled from the field name? At some stage you know both the name and initial value you want to pass in to the Field.... i.e. they are coupled at this level, so why not at the initialValues level? It can take some rework for sure. componentDidMount + onChange is an escape hatch to that.
