### ISSUE TITLE
Progamatically blur active field (plus misleading docs)

### ISSUE THREAD

**Issue by RSpicer** [erikras/redux-form#4063]
Right now, I think the docs have a typo in them. On the "Action Creators" page, blur has the following content:

https://redux-form.com/6.7.0/docs/api/actioncreators.md/

blur(form:String, field:String, value:any)
Saves the value to the field.

I can't imagine that's right. It leads me to a followup question, how do you use this action creator, and is it possible to use it without the field being given to it, essentially blurring whatever field is focused?

If not, is there a way to get the currently focused field programatically?

Cheers! Great product!

**Comment by danielrob** [comment]
`blur` is not dissimilar to the `change` action, so the docs are not incorrect even if not entirely helpful. However unlike `change` action it will remove the `meta.active` flag on the field. 

A fields `meta` state is not expected to be reflected in the DOM in the same way that e.g. the value is. In [particular you'll notice that the](https://redux-form.com/7.3.0/docs/api/field.md/#-code-meta-active-boolean-code-) `meta.active` flag only works if you are calling `focus` on focus and `blur` on blur. 

If you want to work with the focused element, you can do that with native dom api, but it's not something redux-form manages for you.

**Comment by danielrob** [comment]
Closing due to lack of response, but I should started with the fact that `document.activeElement.blur()` will possibly do what you want :).
