### ISSUE TITLE
[v7.4.0] initialValues not working

### ISSUE THREAD

**Issue by albermav** [erikras/redux-form#4069]
### Are you submitting a **bug report** or a **feature request**?
bug report

### What is the current behavior?
initialValues prop is not working on initial mount after update to 7.4.0

### Sandbox Link
I've modified the **Initialize from state** demo just to show the issue. I've just change:
```
 state => ({
    initialValues: data
 }),
```
to get values directly from the variable instead after clicking the button.

https://codesandbox.io/s/ox3p66023q

As you can see the fields are empty. If you change the redux-form version to 7.3.0 it works.

### What's your environment?
redux-form 7.4.0

**Comment by lhtdesignde** [comment]
just updated from 7.3 to 7.4 and seeing the same thing. all our initial values are gone. seeing no errors.

**Comment by cwallervand** [comment]
Same issue here. Using redux v 3.x.x. Had to downgrade to v.7.3to make things work again

**Comment by lhtdesignde** [comment]
I updated to react 16.4 and that seemed to have fixed it. I was using 15.4 before.

**Comment by gustavohenke** [comment]
Thanks for the confirmation, folks.
If you can look at this issue and find a proper fix, we'll be able to get this released sooner.

**Comment by vladhd93** [comment]
also i have a lot of bugs with 7.4.0, in general form init and validators not working at all (react 15.6.2 and redux-form 7.4.0). now i'm looking where is problem

**Comment by JoshMock** [comment]
I just spent a couple hours trying to diagnose this as well. Pinning to version 7.3.0 in your package.json will fix the issue.

It appears that, [in `createReduxForm`, `componentWillMount` is no longer being called](https://github.com/erikras/redux-form/blob/fd7d952522238d33e456292af1110916a25616f7/src/createReduxForm.js#L524), and thus `initIfNeeded` is not hitting [its first pass at initialization](https://github.com/erikras/redux-form/blob/v7.4.0/src/createReduxForm.js#L350-L352) because a `nextProps` argument is always passed by `componentDidMount` (the next lifecycle method that calls `initIfNeeded`).

This is because the method name changed to `UNSAFE_componentWillMount` in order to support [React 16's unsafe versions of deprecated lifecycle methods](https://reactjs.org/docs/react-component.html#unsafe_componentwillmount). By doing so, support for React v15 is now broken in v7.4.0.

I would imagine that having two methods, `UNSAFE_componentWillMount` and `componentWillMount`, living side by side doing the same work, would guarantee full support for React 15 and 16, but I haven't tried yet.

Maintainers, please let me know if you'd like a PR with my proposed solution!

**Comment by andrewnaeve** [comment]
I'm just glad to see the Redux Forms authors have as tough a time testing their library as I do.

**Comment by jpdesigndev** [comment]
Adding to @JoshMock's point, it appears that `react-final-form` [has a dependency](https://github.com/final-form/react-final-form/blob/21453d3c3764d65968afd5d4babf306d01810d12/package.json#L100) on `react-lifecycles-compat` for this reason. Perhaps this is the simply fix? I'm not sure, but will try to test later this afternoon if someone doesn't get to it before I do.

**Comment by gustavohenke** [comment]
Hello folks, thanks for looking at this issue with a magnifying glass.
We don't really have workforce to deal with code changes nowadays (most recent changes are from you, dear users), so if any of you could make the PR, that would be great.
I think @jpdesigndev's idea is simple enough to require little review, so that's a faster way to get the fix in.

**Comment by danielrob** [comment]
@gustavohenke, @jpdesigndev, @JoshMock 
Let's be clear: 
 - The hotfix should be to revert to the straight `cWM`, `cWRP`, and `cWU`. See #4078.
 - The actual fix is to migrate all uses of these old life cycle methods, when doing so we use `react-lifecycles-compat` to continue support for React 15. Until then we cannot avoid the deprecation warnings that come with `StrictMode` in React 16.4. 
 - Use of `UNSAFE_` methods are only appropriate when the React version is known to be 16+. 

See: [open-source-project-maintainers](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html#open-source-project-maintainers) & [gradual-migration-path](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html#gradual-migration-path) sections of the [react blogs update-on-async-rendering](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html)

**Comment by erikras** [comment]
Published fix in [`v4.7.1`](https://github.com/erikras/redux-form/releases/tag/v7.4.1). Please confirm.

**Comment by albermav** [comment]
Thank you guys for the follow up!. You are awesome. I'm afraid i've got some bad news. Just update to v4.7.1 but it's still not working. I've updated the redux-form version in codesandbox and the problem persist.

**Comment by erikras** [comment]
Published _ACTUAL_ fix in [`v7.4.2`](https://github.com/erikras/redux-form/releases/tag/v7.4.2).

**Comment by albermav** [comment]
It is working now. BIG thanks!

**Comment by jedwards1211** [comment]
I thought I was having this issue but after I upgraded I realized that the issue is https://github.com/erikras/redux-form/issues/3879 (`reduxForm` just passes through the `initialValues` prop, calling `initialize()` doesn't affect the `initialValues` it passes to the wrapped component 😱 )

**Comment by jedwards1211** [comment]
Actually, I finally found an issue someone already filed for what I'm talking about: #3459

**Comment by dwjohnston** [comment]
^^ Here's a sandbox: https://codesandbox.io/s/ryo81qz60q

**Comment by ThaiVanLoiDN** [comment]
I use `this.props.initialize()` in `componentDidMount()`, it's OK.
However, if I use it in `componentWillReceiveProps`, it not working.

**Comment by nileshkikani** [comment]
I have tried above solution but still its not working. It's not updating initial value of props.

redux state and everything is fine but rerender is not being called.

**Comment by karpovich-philip** [comment]
> I believe this is still a bug, my solution is to call `this.props.initialize()` in `componentDidMount()`;

One more option:
componentDidMount {
  this.props.initialize(this.props.myFormData)
}

**Comment by blopa** [comment]
I'm having the same problem with `"redux-form": "^8.2.3",` and `"react": "^16.8.6",`.

Calling `this.props.initialize()` in `componentDidMount();` worked for me!

**Comment by m1m6** [comment]
> I'm having the same problem with `"redux-form": "^8.2.3",` and `"react": "^16.8.6",`.
> 
> Calling `this.props.initialize()` in `componentDidMount();` worked for me!

Same here

**Comment by goodwin64** [comment]
Bug still can be reproduced under `"redux-form": "8.2.2"` and `"react": "^16.8.6"`. The issue has to be reopened.

**Comment by abeMedia** [comment]
I can confirm this is still an issue (`redux-form@8.2.6` & `react@16.10.2`).

**Comment by made-in-nz** [comment]
I have a slightly different work around.
I want to keep my component functional, so don't want to call initialize() in a lifecycle method.  The work around I have for setting initial values from state is to call change() in a useEffect hook.  In my case I am wanting to set a form value to some state that is not changing:
```
  /* Workaround to be able to call change in useEffect
     regtype here is a prop mapped to some state in mapStateToProps.
   */      
  const latestChange = useRef(change);
  useEffect(() => {
    latestChange.current = change;
  }, [change]);

  useEffect(() => {
    latestChange.current('RecordType', regtype);
  }, [regtype]);
```
The first useEffect() is required so that we don't need to add change as a dependency in the second (which would cause the useEffect function to execute continuosly).

I'm sure there are better ways to do this..

**Comment by jedwards1211** [comment]
@made-in-nz FWIW you don't need that first `useEffect`, you can just do this
```js
const latestChange = useRef(change);
latestChange.current = change;
```
And really, you can probably just get away with
```js
  useEffect(() => {
    change('RecordType', regtype);
  }, [regtype]);
```
because the closure of that function always comes from a single render, so `change` and `regtype` will be equally up-to-date.

**Comment by made-in-nz** [comment]
Thanks @jedwards1211 for the first suggestion, that makes sense.
The second suggestion is what I started with, however I am then getting the warnings:

>  React Hook useEffect has a missing dependency: 'change'. Either include it or remove the dependency array. If 'change' changes too often, find the parent component that defines it and wrap that definition in useCallback  react-hooks/exhaustive-deps

The behaviour is fine though.

**Comment by jedwards1211** [comment]
Yeah, that's a linting rule designed to make sure you don't accidentally leave out necessary dependencies...it can be nice to intentionally omit something in cases like this, but having the linting rule can also help 🤷‍♂

**Comment by andrew-aladev** [comment]
This issue can be easily reproduced by providing same `initialValues` twice.

**Comment by treavis** [comment]
> This issue can be easily reproduced by providing same `initialValues` twice.

Can confirm, for me this was the reason the form values did not update. Thank you @andrew-aladev for pointing this out 🙏

**Comment by andrew-aladev** [comment]
Something is completely wrong with the [following lines of code](https://github.com/redux-form/redux-form/blob/master/src/createReduxForm.js#L1009-L1030).

It is hard to understand this logic. I am reproducing issue with the following env:
```
const stateInitial ... // undefined
const initialized ... // false
const shouldUpdateInitialValues ... // false
const shouldResetValues ... // false
let initial ... // { ... good data }
initial = stateInitial || empty // { empty object }
```

So it looks like logic is broken here:

```
if (!shouldUpdateInitialValues) {
  initial = stateInitial || empty
}
```

We don't need to update initial values, but why we are resetting it with empty object? See here [the following blame](https://github.com/redux-form/redux-form/blame/master/src/createReduxForm.js#L1009-L1030).

Everything except `if (!shouldUpdateInitialValues) {` was updated 3 years ago, but this code is only 1 year ago. So there was some legacy code and people [failed to fix it](https://github.com/redux-form/redux-form/commit/8ab0ac546055a637180bf5b499a04ee41695d3c3).

**Comment by andrew-aladev** [comment]
[This small commit](https://github.com/redux-form/redux-form/commit/8ab0ac546055a637180bf5b499a04ee41695d3c3) was related to #4020 and it is wrong. We need to fix this issue in another way.

**Comment by andrew-aladev** [comment]
I've updated this code with the following:

```
const stateInitial = getIn(formState, 'initial')
const stateValues = getIn(formState, 'values')

const initialized = !!stateInitial
const valuesInitialized = !!stateValues

const shouldReinitialize =
  initialized && enableReinitialize &&
  !deepEqual(stateInitial, initialValues)
const shouldUpdateInitial =
  !initialized || shouldReinitialize
const shouldUpdateValues =
  (!valuesInitialized || shouldUpdateInitial) &&
  !keepDirtyOnReinitialize

const initial = shouldUpdateInitial ? initialValues : stateInitial
const values = shouldUpdateValues ? initial : stateValues

const pristine = shouldUpdateValues || deepEqual(initial, values)
```

Now both `initial` and `values` are right, but issue is not fixed, there is bug in another code too.

**Comment by andrew-aladev** [comment]
[The following code](https://github.com/redux-form/redux-form/blob/master/src/createReduxForm.js#L333-L361) `initIfNeeded` is broken too.

**Comment by andrew-aladev** [comment]
The line above should be the following:
```
if (nextProps.initialValues && (!nextProps.initialized || (nextProps.enableReinitialize && !deepEqual(this.props.initialValues, nextProps.initialValues)))) {
```

I've tested it in our current project and it works perfect.

**Comment by andrew-aladev** [comment]
Unfortunately it is not enough. 30% of tests are failing. Initialization and reinitialization are working perfect, but `keepValues` is broken too, so any reinitialization breaks values keeping.
