### ISSUE TITLE
[v7.4.0] Field-level validation not working

### ISSUE THREAD

**Issue by patrikmolsson** [erikras/redux-form#4070]
### Are you submitting a **bug report** or a **feature request**?

Bug report

### What is the current behavior?

I forked the sandbox presented here: https://redux-form.com/7.4.0/examples/fieldlevelvalidation/ and updated the redux-form version, please see https://codesandbox.io/s/vmvkqnox2y.

In the new update field-level validation functions are not triggered.

### What is the expected behavior?

The validation functions are supposed to trigger.

### Sandbox Link

https://codesandbox.io/s/vmvkqnox2y

### What's your environment?

Chrome 65.0.3325.181, 
redux-forms 7.4.0

**Comment by shamanking** [comment]
I have some issue!

**Comment by h0wXD** [comment]
Me too!

**Comment by gustavohenke** [comment]
Okay folks, no need to comment like this, please just react with 👍 to @patrikmolsson's opening post and it's enough for us to know how many of you have been affected.

**Comment by danielrob** [comment]
Please see #4069, the root cause is the same which is the lifecycle methods were updated inappropriately to their UNSAFE counterparts. Will leave this open for now for this specific symptom to be tested after the fix.

**Comment by erikras** [comment]
Published fix in [`v4.7.1`](https://github.com/erikras/redux-form/releases/tag/v7.4.1). Please confirm.

**Comment by erikras** [comment]
NOT fixed. Looking into it....

**Comment by erikras** [comment]
Published _ACTUAL_ fix in [`v7.4.2`](https://github.com/erikras/redux-form/releases/tag/v7.4.2).
