### ISSUE TITLE
Bug? Missing node_modules/redux-form/node_modules/hoist-non-react-statics/index.js

### ISSUE THREAD

**Issue by turfdoggle** [erikras/redux-form#4073]
I just updated my node_modules and pulled in yesterday's new version. I'm getting and error on compile now...

./node_modules/redux-form/node_modules/hoist-non-react-statics/index.js
Module build failed: Error: ENOENT: no such file or directory, open '/Users/<mypath>/node_modules/redux-form/node_modules/hoist-non-react-statics/index.js'

**Comment by gustavohenke** [comment]
Sounds like a clean install can fix it.
