### ISSUE TITLE
Adding the "checked" attribute to checkbox Field in HTML DOM

### ISSUE THREAD

**Issue by fredp96** [erikras/redux-form#4077]
### Are you submitting a **bug report** or a **feature request**?
Feature request

### What is the current behavior?
I came accross a shortcoming of the Field component while working on a project that requires me to print a form. I simply pass the HTML content of the form to an Iframe and call the print function on it. However I am experiencing an issue with the Field component when used as a checkbox. Since the state of the checkbox (checked or unchecked) is defined in the "value" attribute. 

This is an example of one of my checkbox innerHTML at print. 
`<input type="checkbox" name="FiveToTwelveYears" value="true" id="FiveToTwelveYears" style="margin-right: 15px; transform: scale(1.5); float: left;">`

HTML interpreters won't show the checkbox as checked since it's missing the "checked" attribute.

### What is the expected behavior?

I would like to know if it was possible to add the "checked" attribute to Fields of checkbox type when the Field value is set to true. I wouldn't mind trying to work on this feature myself if someone would be kind enough to help me get started.

I came to ask for this feature since I haven't found a way of accessing the Field value to inject this behavior myself in my application.

### Sandbox Link
https://codesandbox.io/s/l9llp7zqwm

**Comment by danielrob** [comment]
Passing `type="checkbox"` to a `Field` component will get it to provide you the `checked` prop.  https://github.com/erikras/redux-form/blob/master/src/createFieldProps.js#L58

It would be great if you did a review of documentation in this area, and PR any suggested improvements. I'll close this, but I'll monitor for any further questions you might have. Thanks!

**Comment by fredp96** [comment]
I think I might be experiencing a bug then. 


Here is the Checkbox in the React Virtual DOM (taken with the help of react-dev-tools and chrome console).
![reactdevtoolsprint](https://user-images.githubusercontent.com/26230367/41476531-cdd0b120-708f-11e8-98f3-3a185cba7e9c.PNG)

Here is the Field rendered in HTML DOM : 

`<label for="EighteenMonthsToTwelveYears" class="control-label"><input type="checkbox" name="EighteenMonthsToTwelveYears" value="true" id="EighteenMonthsToTwelveYears" style="margin-right: 15px; transform: scale(1.5); float: left;"><span style="text-align: center;">18 months to 12 years</span></label>
`

The component never has the "checked" prop.

I updated my version of redux-form to 7.4.2 to make sure I wasn't experiencing an issue with an old version but so far I had no luck.

Thanks for your time

**Comment by danielrob** [comment]
Create a pure checkbox.html file with the following contents:
```
<input id="checkbox" type="checkbox">

<script>
  document.getElementById('checkbox').checked = true
</script>
```
And inspect it in your devtools. 

Now change it to 
```
<input id="checkbox" type="checkbox" checked>
```

React internals probably does the first option, so it's not possible to see if the `checked` attribute has been assigned in devtools / view page source (in Chrome).

**Comment by fredp96** [comment]
Thanks for the clarification. I was able to find a workaround to my issue by checking every input and manually adding the checked attribute.
