### ISSUE TITLE
PropTypes and createReactClass warning

### ISSUE THREAD

**Issue by piuccio** [erikras/redux-form#4083]
### Are you submitting a **bug report** or a **feature request**?
Bug

### What is the current behavior?

```
Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs
lowPriorityWarning.js:38:7
Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class
```

### What is the expected behavior?

No warnings 

### What's your environment?

redux-form 7.4.2
react 15

### Other information

It's because of [this import](https://github.com/erikras/redux-form/blob/ca02205ea339398d157c933bbc7355ce0ab23a1d/src/FormName.js#L3) please add some linting rules to prevent that because this problem keeps happening over and over.

**Comment by danielrob** [comment]
Good spotting / tracing, thanks.

**Comment by westn** [comment]
Is this issue solved in any 7.x.x version?
