### ISSUE TITLE
Release 5.3.7

### ISSUE THREAD

**Issue by vkrol** [erikras/redux-form#4088]
Hello.

Please, can you release the new version in 5.x branch (5.3.7)?
We need the following changes:
https://github.com/erikras/redux-form/commit/396fb71331e4abcabaa45c39a6d6ff8818574cb4
https://github.com/erikras/redux-form/commit/402647e09705df413dcd02cf762d755474f1ad70

Thank you!

**Comment by gustavohenke** [comment]
cc @erikras

**Comment by vkrol** [comment]
@erikras Friendly ping 😃

**Comment by vkrol** [comment]
5.4.0 was released.
