### ISSUE TITLE
What's a good way to handle repeating steps when combined with routes?

### ISSUE THREAD

**Issue by egmanoj** [erikras/redux-form#409]
This is related to #260. Suppose a particular step of a form can be repeated. Say, something like "add another address". After reading the documentation I think this can be handled as a Multirecord Form. How does one combine this with routes? Thanks.

**Comment by ooflorent** [comment]
This is a usage question, and we encourage you to ask it on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

This is the only way to ensure the same question doesn’t get asked many times in a row, and that folks who have the same question in the future will be able to find it.

I’m closing for these reasons.
