### ISSUE TITLE
redux-form/immutable handleSubmit function breaks react-native apps

### ISSUE THREAD

**Issue by dapids** [erikras/redux-form#4094]
### What is the current behavior?
- I have a `redux-form/immutable` form with **async validation** in a react-native app
- I submit the form
- The `handleSubmit` function tries to merge `syncErrors` and `asyncErrors`. Unfortunately the former is a plain object and the latter is an immutable Map.
- The app crashes

### What is the expected behavior?
- The `handleSubmit` function should properly handle the merge

### What's your environment?
- redux-form version: `7.3.0`
- react-native version: `0.55.4`
- OS affected: `iOS`, `android`

### Other information
Here is the stacktrace.
![image](https://user-images.githubusercontent.com/1473240/41775644-0b9d3b64-7625-11e8-9361-5f9966b8a74a.png)

**Comment by dapids** [comment]
Probably related to https://github.com/erikras/redux-form/issues/3532.

**Comment by erikras** [comment]
Published fix in [`v8.0.0`](https://github.com/erikras/redux-form/releases/tag/v8.0.0).
