### ISSUE TITLE
Field Component of type number accepts alphanumeric characters

### ISSUE THREAD

**Issue by slim-hmidi** [erikras/redux-form#4096]
### Are you submitting a **bug report** or a **feature request**?
BUG

### What is the current behavior?

I'm using a field of type Number.
The field accepts characters other than digits such as `test` or `11dsf`.

### What is the expected behavior?
The field should only accepts digits characters.
### Sandbox Link

 [https://codesandbox.io/s/rj751ml9zo](https://codesandbox.io/s/rj751ml9zo).

### What's your environment?

Redux-Form: 7.2.3
OS: ubuntu 18.04LTS (64bit)

**Comment by gustavohenke** [comment]
That's a browser problem.

Redux Form doesn't limit in any way what you can input, therefore you should add validators to make sure the data is valid.

Also see related issue #2940
