### ISSUE TITLE
resetForm doesn't reset value @ input[type=file]

### ISSUE THREAD

**Issue by theaqua** [erikras/redux-form#410]
Another fields (input or even react-select) reset fine, but input[type=file] no. Maybe anyone know workaround for it?

**Comment by erikras** [comment]
File inputs are pretty special-case. :frowning: #329

**Comment by theaqua** [comment]
Meh.

**Comment by ooflorent** [comment]
Please see https://github.com/erikras/redux-form/issues/769#issuecomment-215411743
