### ISSUE TITLE
Es export breaks webpack sideEffects in production 

### ISSUE THREAD

**Issue by dlebedynskyi** [erikras/redux-form#4104]
### What is the current behavior?
Redux-form es export is breaking with webpack@^4.10.0 sideEffects optimizations on production build 
see https://github.com/webpack/webpack/issues/7499 for more details

 
### What is the expected behavior?

not breaking production optimizations

### Sandbox Link

does not apply 

### What's your environment?
node 8.11.3
webpack 4.12.1
https://github.com/webpack/webpack/issues/7499

**Comment by danielrob** [comment]
It appears this was fixed upstream.
