### ISSUE TITLE
When using form-level validate and field-level validate at same time, field-level validate not working as expected.

### ISSUE THREAD

**Issue by rangerch** [erikras/redux-form#4108]
### Are you submitting a **bug report** or a **feature request**?
It seems to be a bug.

### What is the current behavior?
When field-level validate return a error message, this.props.invalid still equal to false.

### What is the expected behavior?
I think this.props.invalid should equal true.

### Sandbox Link
https://codesandbox.io/s/1jwzzn74q

I think the problem is I used a wrapperComponent of FormFactory trigger this bug, if i insert the 'Field' directly, everything is ok.

### What's your environment?
"chrome":  "67.0.3396.99"
"react": "15.6.2",
"redux": "4.0.0",
"redux-form": "7.3.0",

**Comment by danielrob** [comment]
Updated documentation is pending, but you've hit the what not to do of case 1 at #4017 . 

```
const email = value =>
  value && !/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i.test(value)
    ? "Invalid email address"
    : undefined;

export default () => {
  // don't define the validator within the render. 
  return (
    <Field
      name="randomName"
      component="input"
      placeholder="email"
      validate={email}
    />
  );
};
```
Seems to fix your error - https://codesandbox.io/s/l7ow218w87.

Sorry for the confusion.

**Comment by rangerch** [comment]
@danielrob You are right, And thank you very much!
