### ISSUE TITLE
Does it work with material-ui 1.3.x?

### ISSUE THREAD

**Issue by vladimirvorobiev** [erikras/redux-form#4116]
**I have a  form** 
`                <Form className={classes.form} onSubmit={handleSubmit(loginAction)}>`
`                  <CardHeader color="primary" className={classes.cardHeader}>`
`                   <h4>{<FormattedMessage id={messages.login} />}</h4>`
`                </CardHeader>`
`               <CardBody>`
`                <Field`
`                 labelText={<FormattedMessage id={messages.username} />}`
`                required={true}`
`               component={TextInput2}`
`              formControlProps={{`
`               fullWidth: true,`
`            }}`
`           InputProps={{`
`            type: 'text',`
`                        name: 'username',`
`                      }}`
`                    />`
`                    <Field`
`                      labelText={<FormattedMessage id={messages.password} />}`
`                      component={TextInput2}`
`                      required={true}`
`                      formControlProps={{`
`                        fullWidth: true,`
`                      }}`
`                      InputProps={{`
`                        type: 'password',`
`                        name: 'password',`
`                      }}`
`                    />`
`                  </CardBody>`
`                  <CardFooter className={classes.cardFooter}>`
`                    <Button simple color="primary" type="submit">`
`                      {<FormattedMessage id={messages.login} />}`
`                    </Button>`
`                  </CardFooter>`
`                </Form>`
 

**end TextInpot2 control**

import React from 'react';
import { withStyles, FormControl, TextField } from '@material-ui/core';
import classNames from 'classnames';

import { styles } from 'src/components/input/text-field/styles';

type Props = {
  classes: Object,
  formControlProps: Object,
  labelText: React.Node,
  labelProps: Object,
  InputProps: Object,
  inputRootCustomClasses: string,
  required: boolean,
  name: string,
};

export const TextInpuComponent = ({
  classes,
  formControlProps,
  labelText,
  labelProps,
  InputProps,
  inputRootCustomClasses,
  required,
  name,
}: Props) => {
  const formControlClasses = classNames({
    [classes.formControl]: true,
    [classes.formControlLabel]: labelText !== undefined,
    [formControlProps.className]: formControlProps.className !== undefined,
  });
  return (
    <FormControl
      {...formControlProps}
      className={formControlClasses}
    >
      <TextField
        label={labelText}
        name={name}
        required={required}
        {...InputProps}
      />
    </FormControl>
  );
};

export const TextInput2 = withStyles(styles)(TextInpuComponent);

**On submit username and password values are empty**

**Comment by gustavohenke** [comment]
Redux Form by itself doesn't provide out of the box support for any 3rd party lib, you'll have to wire them independently, or use another lib that does that, like https://github.com/erikras/redux-form-material-ui.
