### ISSUE TITLE
Dynamic form example doesn't remove fields once added

### ISSUE THREAD

**Issue by neverfox** [erikras/redux-form#412]
I would expect that unchecking a box would remove the field, just as checking it adds a field, but that's not the behavior in the example. Note the fields prop of the inner `<t>` on the right, despite the correct array in the immediate parent's props:

![](https://dl.dropboxusercontent.com/u/32153964/Screen%20Shot%202015-12-11%20at%2011.30.35%20AM.png)

I imagine it's there because you say "Note that when you remove a field, its value is not removed from the Redux store, so it will retain its value when you add it back" but I would expect it to know not to render it if it's not in the fields array.

**Comment by erikras** [comment]
Good catch.

**Comment by neverfox** [comment]
Sorry to hear that it was actually a problem. Is it a bug in redux-form or the example code?

**Comment by erikras** [comment]
In redux-form, unfortunately. :cry:  Hence it being so good of you to notice. :+1:

**Comment by neverfox** [comment]
Hopefully you have your eye on a solution. Anything I can do? I may need dynamic forms here in short order, so I'm motivated.

**Comment by erikras** [comment]
I've got something in mind. Thanks.

**Comment by erikras** [comment]
Fixed in [`v4.0.1`](https://github.com/erikras/redux-form/releases/tag/v4.0.1). Thanks again.
