### ISSUE TITLE
Synchronous Validation: Include initialValues

### ISSUE THREAD

**Issue by abrad45** [erikras/redux-form#4129]
### Are you submitting a **bug report** or a **feature request**?

Feature Request

### What is the current behavior?

The signature for synchronous validation is currently `validate(values)`

### What is the expected behavior?

I'd like to see initial values, for comparison's sake, when performing synchronous validation. This would allow me to, for instance, compare a field's value with what it was when the form was loaded and cause an error if the data changed in an undesirable way (either, changed at all, decremented if we only want the number to increment, etc.)

The signature for synchronous validation would, if this was implemented, be something like `validate(values, initialValues)` where `initialValues` are the initial values passed to the form when it was initialized.

### What's your environment?

* macOS 10.12.6
* `node` v9.7.0
* `redux-form` 7.4.2
* `react` 16.3.1

### Other information

It seems like https://github.com/erikras/redux-form/issues/2881 could help as well if validation functions had access to the`input` and `meta` props (`input` provides the field's `name` and `meta` contains the initial value in `initial`).

I don't see a way to do this, but perhaps there is one that I'm missing.

**Comment by danielrob** [comment]
[The signature is](
https://redux-form.com/7.4.2/docs/api/reduxform.md/) 
`validate(values, formProps)`

and [one of the form props](https://redux-form.com/7.4.2/docs/api/props.md/) is `initialValues`.

**Comment by abrad45** [comment]
@danielrob damn. missed that. thanks!
