### ISSUE TITLE
Invalid date value in redux-form - Date picker

### ISSUE THREAD

**Issue by DunDealRN** [erikras/redux-form#4139]
### Are you submitting a **bug report** or a **feature request**?

It is surely a bug because we can reproduce in the form available in website here =>
https://redux-form.com/7.4.2/examples/react-widgets/

### What is the current behavior?
 

I was able to reproduce the bug in ReactNative and the the form that contains a datepicker from the "React Widget" section of the website.

For example: I select the date of 21/07/2017 since the datepicker but the date recovered in Redux is 20/07/2017.

There is always one day less in the date.

I use the datepicker from the NativeBase library => http://docs.nativebase.io/Components.html#date-picker-def-headref

### What is the expected behavior?

The date must be correct

### What's your environment?

Redux Form version : "^7.4.2"
OS/Browser : Windows 10/Google Chrome
Node version : 6.1.0

**Comment by DunDealRN** [comment]
Hello, so I tested the form, and it looks like the problem occurs when we erase the field manually date picker otherwise the date is correct if we do not do it so I do not know if the do erases the value of the text fields of the picker date causes this problem, yet i correctly set the locale with native base.

Then I try with another date picker than native base and this time the date is correct.

**Comment by patrikmolsson** [comment]
@DunDealRN 

I don't really follow you. As you say, when you type the date in [the example](https://redux-form.com/7.4.2/examples/react-widgets/), the time is set to midnight (and then in my example, `...22:00:00Z`, which looks like the day before, but it is not).

Can you provide a codepen or similar?

**Comment by DunDealRN** [comment]
I think I got myself by the time shift, I guess you have to adjust the location?

Yet I had it indicated the location in the date picker of native base

It is by changing picker date that I was able to solve this problem.

Do we have to indicate the time zones with another bookseller as "moment"?

**Comment by danielrob** [comment]
Redux-form simply stores the value it's provided `onChange` - there's no special date munging handling. It's either timezones or a problem at the [react-widgets](https://github.com/jquense/react-widgets) level.
