### ISSUE TITLE
Conditionally show/hide wizard pages based on previous selection

### ISSUE THREAD

**Issue by stefanlesik** [erikras/redux-form#4151]
I'd like to conditionally show and hide pages using the wizard depending on the answers of previous questions. Can anyone tell me if this is possible with Redux Form?
Eg.
Page 1
- option 1 (allows user to complete Page 2, 4, 5)
- option 2 (allows user to complete Page 3, 4, 6)
Thanks

**Comment by gustavohenke** [comment]
Yes, it is possible. For this you must use one of the selectors that give you the form values.

For help on implementing this, please ask on StackOverflow, but don't forget to show them what you've tried!
