### ISSUE TITLE
redux-form.com is down

### ISSUE THREAD

**Issue by serhalp** [erikras/redux-form#4157]
This probably isn't the best place to report this but FYI redux-form.com appears to be down.

<img width="1433" alt="screen shot 2018-08-01 at 13 34 24" src="https://user-images.githubusercontent.com/1377702/43547321-cb77b30e-958f-11e8-9b2e-c04a1d5b4305.png">

**Comment by gustavohenke** [comment]
Probably just a temporary thing. No longer happens.
