### ISSUE TITLE
Field throw away 'value' prop

### ISSUE THREAD

**Issue by pavel-sindelka** [erikras/redux-form#4159]
Hello guys! When I want to use Field component from Redux-Form v7.4.2 with `value` prop then Field throw away this prop. Is it bug?!

NOT WORKS:
```
<label>
    <Field name="sex" component="{Radio}"  value="male" /> Male
</label>
```

WORKS:
```
<label>
	<Field
		name="sex"
		component={(props) => <Radio {...props} name="sex" value="male" />}
	/>
	Male
</label>
```

WORKS:
```
<label>
    <Field name="sex" component="{Radio}"  radioValue="male" /> Male
</label>
```

**Comment by jakoandersen** [comment]
If you want to make sure props are not picked up by Field, but passed through, use the `props` prop.
https://redux-form.com/7.4.2/docs/api/field.md/#-code-props-object-code-optional-
