### ISSUE TITLE
Form switching from pristine to dirty with object field

### ISSUE THREAD

**Issue by duro** [erikras/redux-form#416]
I have a field that represents an image upload. Since native image fields do not allow values to be applied to them, I pretty much use the suggested method of just using a virtual field in redux-form to store the values I need for that field.

I am running into an issue when using `initialValues` on release > 3.1.0.

My initial values structure looks like this

```
{
  name: 'This is the name',
  logo: {
    key: '/this/is/the/key.png',
    url: 'http://bucket.s3.amazon.com/this/is/the/key.png'
  }
}
```

When my Dropzone based Image field goes through its `componentWillMount` it makes an `onChange` call for the `logo` field. I then see the props on the form go from pristine to dirty, even though the value is exactly the same as the initialValue.

In 3.1.0, the exact same code works just fine and the form does not go from pristine to dirty.

3.1.1 and up, same code forces a pristine -> dirty change.

**Comment by erikras** [comment]
Is this still a problem with v4?

**Comment by ooflorent** [comment]
I'm closing this issue since it is inactive for a while.
Feel free to reopen it if the bug is reproducible in v5.
