### ISSUE TITLE
Any support coming for @material-ui/core

### ISSUE THREAD

**Issue by angaaron** [erikras/redux-form#4163]
Form seems to support the material-ui@next version but i've updated to /core and now cannot get any labels to show.

`<Field name="delivery" component={RadioGroup}>
                    <Radio label="Pickup" value="pickup" />
                    <Radio label="Delivery" value="delivery" />
              </Field>`

Returns an output of the image below
![screen shot 2018-08-09 at 11 47 57 am](https://user-images.githubusercontent.com/22182876/43870126-19798fc4-9bca-11e8-88c8-7869a9cfde69.png)

**Comment by gustavohenke** [comment]
I think you meant to ask this to the [redux-form-material-ui project](https://github.com/erikras/redux-form-material-ui). Head over there for Material UI v1 support.

If you didn't, Redux Form surely supports whatever UI library you're using. Please refer to examples like [the old Material UI one](https://redux-form.com/7.4.2/examples/material-ui) or the [React Widgets one](https://redux-form.com/7.4.2/examples/react-widgets) to better understand how to integrate a UI library with Redux Form.
