### ISSUE TITLE
mutate props anti pattern in field arrays example?

### ISSUE THREAD

**Issue by eldyvoon** [erikras/redux-form#4167]
In this example, https://redux-form.com/7.4.2/examples/fieldarrays/ why there's a mutate prop like so
`<button type="button" onClick={() => fields.push({})}>`
Isn't in react we discourage mutation?

**Comment by gustavohenke** [comment]
There's no mutation going on.
[`fields` prop](https://redux-form.com/7.4.2/docs/api/fieldarray.md/#props) is a **pseudo array**. Whenever you call `push` (or `move`, or `remove`, etc), all you are doing is dispatching an action to Redux, which then does its magic.

**Comment by eldyvoon** [comment]
@gustavohenke thanks for the clarification. One more question, using the arrow function on the onClick won't create a new function on every rerender? Should I move it outside of the render? like 
`const fieldRemoveHandler = index => e => this.props.removeField(index)

// ...

<MyComponent onClick={fieldRemoveHandler(index)} />`
