### ISSUE TITLE
Inconsistent handling of whitespace between Firefox and Chrome

### ISSUE THREAD

**Issue by sblask** [erikras/redux-form#417]
I've got several forms with email field which fails validation if there are leading or trailing whitespaces under Firefox, but not under Chrome. Seems like the whitespace doesn't even make it into the state under Chrome. Is it Chrome doing something special, or a bug in redux-form? I would like to never have the whitespace. I know I should be able to fix this with a normalizer, but having to configure this for all the forms is not very appealing - I would not mind to have a reducer that does the same thing for all the fields called `email`, but having to have the form name in the configuration is a bummer. Anything else I can do?

**Comment by erikras** [comment]
Can you inspect exactly what the value in `event.target.value` is on both browsers?
```js
<input type="email" {...emailField} onChange={event => {
  console.log('"' + event.target.value + '"');
  emailField.onChange(event);
}}/>
```

**Comment by sblask** [comment]
Firefox gives the exact same value that I can see and copy-paste from the text field. Chrome seems to trim whitespace. This is only true for inputs with `type=email` though. To get rid of this inconsistency, I would generally have to trim whitespace on ALL email inputs, which is not possible with a normalizer(as I'd have to configure it per form).

**Comment by erikras** [comment]
This sucks, but it isn't really `redux-form`'s fault.

I'd recommend that, if possible, you loosen your validation to accommodate untrimmed whitespace, and then do the trimming on reading and writing to wherever the data is.

**Comment by wmertens** [comment]
The easy way out is to make an input component that calls onChange with the
trimmed value. You can then also add a "clear field" button, aria settings
etc…

On Sun, Jan 17, 2016, 10:48 AM Erik Rasmussen <notifications@github.com>
wrote:

> This sucks, but it isn't really redux-form's fault.
>
> I'd recommend that, if possible, you loosen your validation to accommodate
> untrimmed whitespace, and then do the trimming on reading and writing to
> wherever the data is.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/erikras/redux-form/issues/417#issuecomment-172306492>.
>
-- 

Wout.
(typed on mobile, excuse terseness)
