### ISSUE TITLE
formsection with reduxform

### ISSUE THREAD

**Issue by nagarakesh4** [erikras/redux-form#4181]
(edit) Might not be a bug
### What is the current behavior?
```
ParentForm.js
<FormSection name="ChildRequestForm">
   <ChildForm />
</FormSection
```
on form submission in ParentForm, it should get values from ChildForm component, this works fine.

But once the ChildForm component has a reduxForm connected 
ex:
```
ChildForm = reduxForm({
    form: 'ChildRequestForm'
})(ChildForm);
```

then the parent form will no longer able to retrieve values of the child form on submit.

### What is the expected behavior?
the parent form should be able to retrieve values from child form

### Sandbox Link
https://codesandbox.io/s/jj1mk114n5

### What's your environment?
redux form: 7.3.0
node: v8.11.1
npm: v6.1.0

**Comment by gustavohenke** [comment]
Not a bug -- that's the correct behaviour, as `ChildForm`'s fields have a new boundary form, which is not `ParentForm` anymore.

What are you trying to achieve by doing this?

**Comment by nagarakesh4** [comment]
i am trying out a simple form where i have a reusable form component (child component) using formsection. It all works fine as long as this child form is a stateless or not connected to reduxform.

I had to wrap the child component with reduxForm as it requires to dispatch 'change' function and requires access to formvalueSelector.

**Comment by nagarakesh4** [comment]
looks like i have to reuse the same parent form name in child class, in which case using the formSection never matters. With this i am confused how to use the formSection with a redux form component and when to use it exactly?

**Comment by gustavohenke** [comment]
You shouldn't expect that a component wrapped with `reduxForm` will talk to the external `FormSection`.

What I can suggest you to do instead is to provide the component the form name via props, like this:

```js
const SomeReduxFormWrappedComponent = ({ form }) => (
  <form>
    <FormSection name="address" component={AddressForm} formName={form}>
  </form>
);
```

Then, you wrap your `AddressForm` with the right selectors/action creators:

```js
import { change } from 'redux-form';

const AddressForm = connect((state, ownProps) => ({
  someFieldValue: formValueSelector(ownProps.formName)(state, 'aField')
}), (dispatch, ownProps) => ({
  changeForm: (field, value) => dispatch(change(ownProps.formName, field, value))
}))(AddressFormComponent);
```

**Comment by nagarakesh4** [comment]
got it thanks!
