### ISSUE TITLE
Actions spam redux dev tools

### ISSUE THREAD

**Issue by gurbraj** [erikras/redux-form#4183]
First off, thank you very much for an excellent library.

During development, I often use redux dev tools. When interacting with a form, a lot of "library-actions" are dispatched, and it becomes difficult to see my "app-actions" getting dispatched.

From a dev perspective, I'm thinking that library-implementation details should not leak out to the consuming app.

1) Is this a problem anyone else recognizes and would like to have solved as well?
2) Anyone know of an obvious solution? I'm willing to make a PR if I can get pointed in the right direction.

**Comment by gustavohenke** [comment]
Hi @gurbraj, what are you worried with, exactly?

I could say you would like to see less/no `@@redux-form/` actions among yours.
If that is the case, this would be a pretty major breaking change, and if you are to incorporate any other Redux library, it would bring the same problem.

I'm happy to see similar issues/solutions with any other libraries, though.

**Comment by gurbraj** [comment]
Hey @gustavohenke, 

> I could say you would like to see less/no @@redux-form/ actions among yours.

Yes, that is correct.

And I agree with you, if anything, this type of disabling functionality should come from the redux-dev-tools library, I'll have a look over there.

**Comment by gustavohenke** [comment]
Okay, thanks @gurbraj. Let us know if you find something interesting. I'm always happy to learn more!

**Comment by iamandrewluca** [comment]
https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md#actionsblacklist--actionswhitelist
