### ISSUE TITLE
Copy/Paste and Find keyboard functions don't work on redux-form website

### ISSUE THREAD

**Issue by jpierson** [erikras/redux-form#419]
The [documentation for redux-form](http://erikras.github.io/redux-form/) is nice to look at but I've noticed that it's not very usable from a keyboard perspective as common commands such as Ctrl+c, Ctrl+p, and Ctrl+f do not work at least in Chrome.

**Comment by erikras** [comment]
I _just_ published the fix for this (moments ago). Please check again. #418.

**Comment by jpierson** [comment]
Awesome, works great now. I know it seems small but this will be a big help to me and hopefully others. Thank you and Cheers!
