### ISSUE TITLE
Storing array of data instead of array of object.

### ISSUE THREAD

**Issue by FantasticSWT** [erikras/redux-form#4193]
I wish to store an array of input from the user. I tried the FieldArray example and I notice this syntax. 
![image](https://user-images.githubusercontent.com/38369131/45032844-594a9880-b085-11e8-91f3-f7f9fc55530d.png)

Is it possible to store in this way? 
Which is 
"members": ["ABC", "DEF", "GHI"] where I do not want an array of object. Could it simply be done through Field component?

**Comment by gustavohenke** [comment]
Yes. If you observe right below on the [Field Arrays example page](https://redux-form.com/7.4.2/examples/fieldarrays/), there is a list of hobbies, which is stored like that.

```json
{
  "members": [
    {
      "firstName": "foo",
      "lastName": "bar",
      "hobbies": [
        "A",
        "B"
      ]
    }
  ]
}
```
