### ISSUE TITLE
success message after submission the form

### ISSUE THREAD

**Issue by evs376nisar** [erikras/redux-form#4196]
i am actually trying to pass the success sms after the submission the form i am just learning react-redux . so i really dont know how can i figure this out

**Comment by evs376nisar** [comment]
import React from 'react';
import {connect} from 'react-redux';
import { bindActionCreators } from "redux";
import { Formik } from 'formik';
import {formSubmission } from "../actions/action"

const BookingForm = ({}) => (

        <Formik
            initialValues={{
                form:'',
                postcode: '',
                dropCode: '',
                whenMoving:'',
                move:'',
                customerName:'',
                customerPhone:'',
                customerEmail:'',
                selectVan:'',
                menRequired:'',
                stairs:'',
                loadingUnlaodingtime:'',

            }}

            validate={values =>
            {
                let errors = {};
                   if (!values.postcode) {
                        errors.postcode = 'Please Provide a valid post code';
                    }
                    if (!values.dropCode) {
                        errors.dropCode = 'Please Provide a valid Drop off code';
                    }

                     if (!values.whenMoving) {
                        errors.whenMoving = 'When Moving?';
                    }
                     if (!values.move) {
                        errors.move = 'Describe your Move';
                    }

                     if (!values.customerName) {
                        errors.customerName = 'Customer Name is Required'
                    } else if (values.customerName.length < 3) {
                        errors.customerName = 'Name should be 3 or more'
                    }


                     if (!values.customerPhone) {
                        errors.customerPhone = 'Customer Phone Number is Required';
                    }
                     if (!values.customerEmail) {
                        errors.customerEmail = 'Customer Email is Required';
                    } else if (
                        !/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i.test(values.customerEmail)
                    ) {
                        errors.customerEmail = 'Please provide valid email address';
                    }
                     if (!values.selectVan) {
                        errors.selectVan = 'Please select the Van';
                    }
                     if (!values.menRequired) {
                        errors.menRequired = 'Please select the Men';
                    }
                     if (!values.stairs) {
                        errors.stairs = 'Please select the Stairs';
                    }
                     if (!values.loadingUnlaodingtime) {
                        errors.loadingUnlaodingtime = 'Please select the Loading_Unlaoding_Time';
                    }






                return errors;
            }}
            onSubmit={(
                values,
                { setSubmitting, setErrors  }
            ) => {
                formSubmission(values)
            }}
            render={({
                         fullName,
                         pristine,
                         values,
                         errors,
                         touched,
                         handleChange,
                         handleBlur,
                         handleSubmit,
                         isSubmitting,
                         submitting
                     }) => (
                <div className="container">
                    <form onSubmit={handleSubmit}  >
                        <div className="row">

                            <div className="col-md-4">
                                <input
                                    type="text"
                                    name="postcode"
                                    onChange={handleChange}
                                    onBlur={handleBlur}
                                    value={values.postcode}
                                    className="form-control"
                                    placeholder="Pickup PostCode"
                                />
                                <div style={{width:'100%', marginTop: '0.25rem', fontSize: '80%', color: '#dc3545'}}>{touched.postcode ? errors.postcode : ''}</div>
                            </div>
                            <div className="col-md-4">
                                <input
                                    type="text"
                                    name="dropCode"
                                    onChange={handleChange}
                                    onBlur={handleBlur}
                                    value={values.dropCode}
                                    className="form-control"
                                    placeholder="Drop off PostCode"
                                />
                                <div style={{width:'100%', marginTop: '0.25rem', fontSize: '80%', color: '#dc3545'}}>{touched.dropCode ? errors.dropCode : ''}</div>
                            </div>
                        </div>

                        <div className="row mt-2">
                            <div className="col-md-4 ">
                                <input
                                    type="text"
                                    name="whenMoving"
                                    onChange={handleChange}
                                    onBlur={handleBlur}
                                    value={values.whenMoving}
                                    className="form-control"
                                    placeholder="When Moving?"
                                />
                                <div style={{width:'100%', marginTop: '0.25rem', fontSize: '80%', color: '#dc3545'}}>{touched.whenMoving ? errors.whenMoving : ''}</div>
                            </div>
                            <div className="col-md-4 ">
                                <input
                                    type="text"
                                    name="move"
                                    onChange={handleChange}
                                    onBlur={handleBlur}
                                    value={values.move}
                                    className="form-control"
                                    placeholder="Describe your Movie"
                                />
                                <div style={{width:'100%', marginTop: '0.25rem', fontSize: '80%', color: '#dc3545'}}>{touched.move ? errors.move : ''}</div>
                            </div>
                        </div>
                        <div className="row mt-4">
                            <div className="col-md-4">
                                <select className="form-control" name="selectVan"  onChange={handleChange} onBlur={handleBlur} value={values.selectVan}>
                                    <option value=" ">select van</option>
                                    <option value="1">1 van</option>
                                    <option value="2">2 van</option>
                                    <option value="3">3 van</option>
                                </select>
                                <div style={{width:'100%', marginTop: '0.25rem', fontSize: '80%', color: '#dc3545'}}>{touched.selectVan ? errors.selectVan : ''}</div>
                            </div>
                            <div className="col-md-4">
                                <select className="form-control " name="menRequired"  onChange={handleChange} onBlur={handleBlur} value={values.menRequired}>
                                    <option value=" ">Men required ?</option>
                                    <option value="1">1 Men</option>
                                    <option value="2">2 Men</option>
                                    <option value="3">3 Men</option>
                                </select>
                                <div style={{width:'100%', marginTop: '0.25rem', fontSize: '80%', color: '#dc3545'}}>{touched.menRequired ? errors.menRequired : ''}</div>
                            </div>
                        </div>
                        <div className="row mt-2">
                            <div className="col-md-4">
                                <select className="form-control" name="stairs"  onChange={handleChange} onBlur={handleBlur} value={values.stairs}>
                                    <option value=" ">Flight of stairs</option>
                                    <option value="1">1 stairs</option>
                                    <option value="2">2 stairs</option>
                                    <option value="3">3 stairs</option>
                                </select>
                                <div style={{width:'100%', marginTop: '0.25rem', fontSize: '80%', color: '#dc3545'}}>{touched.stairs ? errors.stairs : ''}</div>

                            </div>
                            <div className="col-md-4">
                                <select className="form-control " name="loadingUnlaodingtime"  onChange={handleChange} onBlur={handleBlur} value={values.loadingUnlaodingtime}>
                                    <option value="">Loading/Unlaoding Time</option>
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                </select>
                                <div style={{width:'100%', marginTop: '0.25rem', fontSize: '80%', color: '#dc3545'}}>{touched.loadingUnlaodingtime ? errors.loadingUnlaodingtime : ''}</div>
                            </div>
                        </div>

                        <div className="row mt-3">
                            <div className="col-md-4">
                                <input
                                    type="text"
                                    name="customerName"
                                    onChange={handleChange}
                                    onBlur={handleBlur}
                                    value={values.customerName}
                                    className="form-control"
                                    placeholder="Customer Name"
                                />
                                <div style={{width:'100%', marginTop: '0.25rem', fontSize: '80%', color: '#dc3545'}}>{touched.customerName ? errors.customerName : ''}</div>
                            </div>
                            <div className="col-md-4">
                                <input
                                    type="text"
                                    name="customerPhone"
                                    onChange={handleChange}
                                    onBlur={handleBlur}
                                    value={values.customerPhone}
                                    className="form-control"
                                    placeholder="Customer Phone"
                                />
                                <div style={{width:'100%', marginTop: '0.25rem', fontSize: '80%', color: '#dc3545'}}>{touched.customerPhone ? errors.customerPhone : ''}</div>
                            </div>
                        </div>
                        <div className="row mt-3">
                            <div className="col-md-4 ">
                                <input
                                    type="text"
                                    name="customerEmail"
                                    onChange={handleChange}
                                    onBlur={handleBlur}
                                    value={values.customerEmail}
                                    className="form-control"
                                    placeholder="Customer Email"
                                />
                                <div style={{width:'100%', marginTop: '0.25rem', fontSize: '80%', color: '#dc3545'}}>{touched.customerEmail ? errors.customerEmail : ''}</div>
                            </div>
                        </div>

                        {/*</div>*/}

                        <div className="form-row">
                            <div className="col-md-4 ">
                                <button type="submit"  disabled={submitting} className="btn btn-primary mb-2">Create Lead</button>

                            </div>
                        </div>

                    </form>

                </div>
            )}
        />

);

const mapStateToProps = (state, props) => {
    return{

    }
};

const mapDispatchToProps = dispatch => bindActionCreators({
    formSubmission,





}, dispatch);

export default connect(
    mapStateToProps,
    mapDispatchToProps,

)(BookingForm)

**Comment by evs376nisar** [comment]
this is my form code

**Comment by valorize** [comment]
Such questions are best asked on www.stackoverflow.com

**Comment by gustavohenke** [comment]
Please ask on StackOverflow about Redux Form usage.
It's a good idea to turn your code into a small piece that runs on its own, while reproducing the issue you have.
