### ISSUE TITLE
An auto-save example would be helpful

### ISSUE THREAD

**Issue by jpierson** [erikras/redux-form#420]
Forms that auto-save as the user changes fields seems to be gaining popularity on the web and although such a feature isn't exactly the responsibility for redux-form to tackle it would be helpful if there was some guidance on how this can be done with redux-form. I'm mainly thinking about a few aspects that may be likely to arise in an auto-save form scenario.

Concerns related to auto-save:
- How to efficiently throttle/denounce or at least tap into existing libraries that provide this capability. I would think that this concern also [applies to validation](https://github.com/erikras/redux-form/issues/41).
- Which signal should be listened to for when a field has changed (ex. onBlur, onChanged, ...).
- Only submitting dirty fields.
- Submitting field changes as a group. Doing this with a shared throttle/debounce may also be interesting.
- Resetting the dirty state of individual fields. It would be assumed that this may happen for example after persisting changes to particular fields.

Many of these aspects may have already been discussed but consider this my vote of interest in an example that specifically addresses these concerns. I'll be attempting to implement something that takes does most of the above so if I gain any insight I'd be glad to share. Thanks again to all of those who have contributed to this library!

**Comment by erikras** [comment]
This is an excellent, well written, suggestion.

I am of two minds on this design approach. I recently wrote a form _not_ using redux-form that did autosaving like this, but, having decided it is a bad/confusing UI, am currently converting it to a `displayMode vs. editMode` approach using redux-form submitting groups of fields at once.

I look forward to future insights by you or others who venture down this path.

**Comment by erikras** [comment]
Possibly relevant. https://github.com/erikras/redux-form/issues/362#issuecomment-164013479

**Comment by Iuriy-Budnikov** [comment]
+1

**Comment by remiremi** [comment]
Looks like using async validation (http://redux-form.com/6.0.2/examples/asyncValidation/) together with debounce (https://www.npmjs.com/package/debounce) would work well. I'm also interested in a full example. Maybe one that auto-saves the state to local storage for simplicity.

**Comment by oyeanuj** [comment]
@jpierson @remiremi Did you all end up with a particular approach for auto-saving forms?

**Comment by bradwestfall** [comment]
Also looking to see approaches

**Comment by nealoke** [comment]
Interested as well

**Comment by NickCain** [comment]
I applied the handleSubmit using onBlur which does submit the form but when adding validation to this it caused all sorts of problems by validating a field that hasnt been touched yet.

I also would be interested in seeing what is the recommended way is to do auto save on a redux form.

**Comment by oyeanuj** [comment]
@bradwestfall @nealoke @NickCain Hello all!  Here is how I ended up making this work. For more context and background on the discussion, I recommend reading the conversation in #2169 (and chiming in with your learnings, etc).

So, as per the conversation there, I tried the 'many little forms' approach. I am sharing both my approach as well as an abstracted-out gist that can hopefully help out y'all.

Essentially, with this approach:
1. You want to use **each field as a little form** which submits **debounced `onChange`**. 
2. For **each field as a little form**, you want to abstract that into a component which can be provided an input, as much as possible.
3. Set `autofocus` for the first form.
4. For **debounced `onChange`**, I used `react-debounced-input`.
5. You can also use components which are not forms, as long as you control and can compute submit, onChange, error states, etc.
6. Many little forms also meant, that there is **no parent form**, at least in my case. 
7. The implication of that is that you **have to compute `submitting` state and/or `error` state yourself**. 
8. When #2289 (#2173) make it to a release, computing the `submitting` would get a bit easier. Until then, I would recommend storing that in your Redux state when you make the XHR call.
9. My recommendation would be to set up a **selector that aggregates all of your `SingleFieldForm` states into a single prop**, in a similar fashion to how Redux setups the `values` props, or state of a larger form.

In my case, where there are a handful of fields, it works well. With larger forms, YMMV. 

--
Finally, a few assumptions to know while looking at the Gist - 
1. My error rendering requirements were slightly more indepth than typical forms. I'm trying to show errors both around the submit button as well as near the field.
2. The gist is simplified but works for all kind of components. In my form, there was a dropdown form, deletable fields, textareas, and it worked well.
3. Sprinkling of lodash function for simplicity.

--

**The Gist**: https://gist.github.com/oyeanuj/2f69ebe1004e2ff47d7550d957bf05cf

Hope this helps folks - if you have better approaches, do share. Personally, I am confident that as soon as one can do field level submission (#2169), this would become much more trivial. But, for now, this works :)

cc: @erikras, let me know if this implementation lines up with how you were thinking of many-little-forms approach.

**Comment by nealoke** [comment]
@oyeanuj Thank you for the amazing effort here! Also I'm a bit confused as to whether the field level submission will be created or not, please shed some light here!

**Comment by oyeanuj** [comment]
@nealoke Sorry, didn't get to this sooner. Glad you found it helpful :)

 To answer your questions,
> whether the field level submission will be created or not, please shed some light here!

You'll get the submitting flag for each of the `SingleFieldForm` as soon is the debounced `onChange` event happens. Is that what you meant?

> Also, can we create something similar with the provided meta props already? I can see the meta.submitting already

I am not entirely sure what `meta.submitting` does TBH. There isn't a way to actually do field level submission, so my guess was that it was true if the form itself was being submitted (based on [this](https://github.com/erikras/redux-form/issues/567)). Maybe @erikras can confirm, or if you've given it a shot, let me know!

**Comment by slavab89** [comment]
Sorry for bringing it up once more 😄 
I've just started trying to do something like this on my project.
I like the idea of having a lot of small single field forms that and wonder if there is something even more simpler with the latest versions? Like you've previously said it takes quite the maintenance out of redux-form itself to manage it all.

For example, utilize the `onChange` of the form (only 1 main form) and throttle/debounce that function to activate only every specific time. And on that trigger, do the actual action to start updating the form?

**Comment by jpierson** [comment]
Sorry, it's been a while since I've worked with redux-form and React in general but I've been following along. If I happen to dig in again and find something useful I'll share what I find.

**Comment by gustavohenke** [comment]
Hello folks, it's been a while since the last activity of this issue, so if you happen to come back and have the energy to write the requested example, please go ahead and send us a PR!
