### ISSUE TITLE
Simple field value is not getting updated on UI

### ISSUE THREAD

**Issue by avinash8526** [erikras/redux-form#4210]
This may be stupid on my part but I am unable to see updated value of field on UI..
I spend 6hrs now version is latest .

code is also taken from simple form. It seems the form is controlled by default

```
<div className="box">
                    <form onSubmit={(e) => {
                        e.preventDefault();
                        console.log('Submitted')
                    }
                    }>


                        <Field
                            name="firstName"
                            component="input"
                            type="text"
                            placeholder="First Name"
                            value="Avinash"

                        />




                        <button type="submit">
                            Submit
                        </button>

                    </form>
                </div>
export default reduxForm({
    form: 'test'
})(ProfileBasic);
```

**Comment by gustavohenke** [comment]
You very likely forgot to plug the Redux Form reducer.

Please note that examples like these don't outline the whole problem, so we can't really help, only guess where the problem lies. It is also better if you ask these kind of questions on StackOverflow.

Thanks for using Redux Form!

**Comment by avinash8526** [comment]
Thanks @gustavohenke for your reply  I plugged into reducer, but the problem was that I was using ES6 object notation, I was not knowing that redux-form explicitly require form key.

## Before
const rootReducer = combineReducers({
    searchReducer,
    profileReducer,
    formReducer
});

### After

const rootReducer = combineReducers({
    searchReducer,
    profileReducer,
    form: formReducer
});

**Comment by avinash8526** [comment]
I think you should fix this as my reducer looks ugly now

**Comment by VyvIT** [comment]
@avinash8526 You can 
```
import { reducer as form } from 'redux-form';
```
to make it prettier.
