### ISSUE TITLE
Question regarding nested forms with dynamic objects in array fields

### ISSUE THREAD

**Issue by iamyardem** [erikras/redux-form#422]
Hi all, as I found out, nested form has declarative way of initialization and it requires you always store objects of the same structure within array fields.

For example this is a good config for nested form

```javascript
const fields = [
  'user',
  'contacts[].type',
  'contacts[].phoneNumber'
]
```

but what if I need to store items of various structure within contacts array? How can I configure such form then? Let say I would like to store both address and phone objects within contacts array field.

```javascript
{
  type: 'address',
  zipCode: 010101,
  country: 'some country',
  city: 'some city',
  street: 'some street'
},
{
  type: 'phone',
  phoneNumber: '123456789'
}
```

Thanks in advance! :)

**Comment by trashgenerator** [comment]
As far as I know you can put all possible fields in `fields` but in your form component show just fields you want depending on the value in `type` field. Also you have to check this value in validation function to do different validations for different `type`'s

**Comment by erikras** [comment]
Yes, @trashgenerator's answer is correct. You will need to specify all the possible values in the `fields` array.
