### ISSUE TITLE
Field is dispatching 3 actions (focus > blur > focus) on focus

### ISSUE THREAD

**Issue by guilhermeoholz** [erikras/redux-form#4220]
### What is the current behavior?
I've created 2 forms to update some basic user info (name, e-mail and password) - one form is responsible for name and e-mail and the other, that is nested in a component under the first one, is responsible for the password update.

However, on the dialog where I want to handle the password update, whenever I click on one of the fields redux-form dispatches 3 actions: focus, then blur and focus again... this behavior happens only on Firefox and the problem is that it triggers the field validation even if the nothing was typed.

### What is the expected behavior?
It should dispatch only one focus action, as the others Fields usually do.

### Sandbox Link
Here is the code that replicates the behavior: https://codesandbox.io/s/mz2z13w88p

### What's your environment?
redux-form version: 7.4.2
OS: Ubuntu 18.04.1 LTS
browser affected: Firefox Quantum 62.0 (64-bit)

**Comment by JonathanTR** [comment]
Would love to hear some input on this one. In my project it makes it difficult to animate the focus state without a flash in between.

**Comment by guilhermeoholz** [comment]
@pmninh91 now it is working just as expected...

Try to update the dependency and Firefox - that's the only thing I did, so unfortunately I can't provide any further assistance.
