### ISSUE TITLE
Support for a custom react-redux storeKey

### ISSUE THREAD

**Issue by davidfurlong** [erikras/redux-form#4244]
### Are you submitting a **bug report** or a **feature request**?

**feature request**

### What is the current behavior?

Theres no way to pass through a custom store key (see https://github.com/reduxjs/react-redux/blob/master/docs/api.md#arguments). If your app has multiple redux stores, you need a custom store key. We are in the unfortunate position of using a library which uses redux, and we render children into this library, so we need this functionality.

### What is the expected behavior?

a `reduxForm` option `storeKey`. This is then passed into the `connect` options wherever used in redux-form

### Other information

https://medium.com/@azizhk/create-multiple-redux-stores-b77b7359375f

**Comment by gustavohenke** [comment]
Such feature exists, actually.
Use [`getFormState` option](https://redux-form.com/7.4.2/docs/api/reduxform.md/#-code-getformstate-function-code-optional-).

Then [all selectors](https://redux-form.com/7.4.2/docs/api/selectors.md/) accept that as well:
> They also all take an undocumented final parameter `getFormState()` that is used to select the mount point of the redux-form reducer from the root Redux reducer (it defaults to `state => state.form`, assuming that you have mounted the redux-form reducer under `form`.

**Comment by davidfurlong** [comment]
Thanks @gustavohenke !

**Comment by AnaRobynn** [comment]
Same issue. I'm migrating to a different store and currently using two stores side-by-side, everything except redux-forms works, because redux-forms is doing some magic behind the scenes and doesn't give an option to configure the storeKey.

**Comment by davidfurlong** [comment]
Might be worth reopening an issue kevin, since it seems we can't reopen
this one.
