### ISSUE TITLE
Losing focus on fieldarray when I try to connect with formReducer or using formValueSelector

### ISSUE THREAD

**Issue by vab777** [erikras/redux-form#4255]
Hi, I'm getting confused when trying to implement fieldarray with formValueSelector, whenever I use formValueSelector or connect to Form app state, I lose focus whenever I type in fieldarray. It's like refreshing the component whenever I type something.

Here's my code :
`
import React, { Component } from 'react';
import { connect } from 'react-redux';
import { bindActionCreators } from 'redux';
import { Field, FieldArray, reduxForm, change, formValueSelector } from 'redux-form';
import Card from '../../../components/card';
import Label from '../../../components/Label';
import Button from '../../../components/uielements/button';
import ReduxFormTextField from '../../../components/form/ReduxFormTextField';
import ReduxFormNominalField from '../../../components/form/ReduxFormNominalField';
import ReduxFormDatePicker from '../../../components/form/ReduxFormDatePicker';
import ReduxFormReactSelect from '../../../components/form/ReduxFormReactSelect';
import { fetchCustomerList } from '../../master/customer/modules/actions';
import { fetchFreightList } from '../../master/freight/modules/actions';
import { fetchWarehouseList } from '../../master/freight/modules/actions';
import { fetchServiceTypeList, fetchContainerTypeList } from '../../general/modules/actions';

class MyForm extends Component {
    constructor(props) {
        super(props);
        this.state = {
            'loading': false,
            'error': [],
        }
    }

    componentDidMount() {
        this.props.fetchCustomerList();
        this.props.fetchFreightList();
        this.props.fetchServiceTypeList();
        this.props.fetchContainerTypeList();
    }
    
    onSubmit(values) {
        console.log(values);
    }

    onChangeContainerType = (detail, index) => {
        //I would like to fetch API using each fieldarray values here
        //But when using formValueSelector or using this.props.form.... input in fieldarray keep losing focus
    }

    onRenderForm() {
        const { handleSubmit } = this.props;
        const customerList = this.props.customer ? this.props.customer.customerList : [];
        const freightList = this.props.freight ? this.props.freight.freightList : [];
        const serviceTypeList = this.props.general ? this.props.general.serviceTypeList : [];
        const containerTypeList = this.props.general ? this.props.general.containerTypeList : [];
        
        const renderDetails = ({ fields, meta: { error } }) =>
            <tbody>
                {fields.map((detail, index) =>
                    <tr key={index}>
                        <td>
                            <div className="row">
                                <div className="col-sm-12">
                                    <Field
                                        name={`${detail}.description`}
                                        type="text"
                                        component={ReduxFormTextField}
                                        label="Description"
                                        />
                                </div>
                            </div>
                            <div className="row">
                                <div className="col-sm-12">
                                    <Field
                                        name={`${detail}.container_type_id`}
                                        label="Container Type"
                                        component={ReduxFormReactSelect}
                                        valueField={(containerTypeList) => containerTypeList.id}
                                        textField={(containerTypeList) => containerTypeList.term}
                                        options={containerTypeList}
                                        onChange={(e) => this.onChangeContainerType(e, index)}
                                    />
                                </div>
                            </div>
                        </td>
                        <td>
                            <div className="row">
                                <div className="col-sm-6">
                                    <Field
                                        name={`${detail}.freight_cost`}
                                        type="text"
                                        component={ReduxFormNominalField}
                                        label="Freight Cost"
                                        />
                                </div>
                                <div className="col-sm-6">
                                    <Field
                                        name={`${detail}.other_cost`}
                                        type="text"
                                        component={ReduxFormNominalField}
                                        label="Premi Cost"
                                        />
                                </div>
                            </div>
                        </td>
                        <td>
                            <div className="row">
                                <div className="col-sm-12">
                                    <Field
                                        name={`${detail}.total_price`}
                                        type="text"
                                        disabled={true}
                                        component={ReduxFormNominalField}
                                        label="Total Base Price"
                                        />
                                </div>
                            </div>

                        </td>
                        <td>
                            <button
                                type="button"
                                title="Remove"
                                onClick={() => {
                                                   fields.remove(index);
                                               }
                                />
                        </td>
                    </tr>
                )}
                {error && <li className="error">{error}</li>}
                <tr>
                    <td colSpan="4">
                        <button type="button" onClick={() => {
                                                                fields.push();
                                                                console.log("pushed");
                                                             }
                                                      }>
                            Add New
                        </button>
                    </td>
                </tr>
            </tbody>

        return (
            <div className="row">
                <div className="col-sm-12">
                    <form onSubmit={handleSubmit(this.onSubmit.bind(this))}>
                        <div className="row">
                            <div className="col-sm-6">
                                <Field
                                    name="date"
                                    label="Date"
                                    component={ReduxFormDatePicker}
                                />
                            </div>
                            <div className="col-sm-6">
                                <Field
                                    name="freight_id"
                                    label="Freight"
                                    component={ReduxFormReactSelect}
                                    valueField={(freightList) => freightList.id}
                                    textField={(freightList) => freightList.name}
                                    options={freightList}
                                />
                            </div>
                        </div>
                        <div className="row">
                            <div className="col-sm-6">
                                <Field
                                    name="service_type_id"
                                    label="Service Type"
                                    component={ReduxFormReactSelect}
                                    valueField={(serviceTypeList) => serviceTypeList.id}
                                    textField={(serviceTypeList) => serviceTypeList.term}
                                    options={serviceTypeList}
                                />
                            </div>
                            
                        </div>
                        
                        <div className="row">
                            <div className="col-sm-12">
                                <div className="table-responsive mt48">
                                    <table className="table table-hover">
                                        <thead>
                                            <tr>
                                                <td width="200px"><Label tblHeader>Description</Label></td>
                                                <td width="350px"><Label tblHeader>Price</Label></td>
                                                <td width="150px"><Label tblHeader>Total</Label></td>
                                                <td width="50px"><Label tblHeader></Label></td>
                                            </tr>
                                        </thead>
                                        <FieldArray name="details" component={renderDetails} />
                                        <tfoot>
                                            <tr>
                                                <td colSpan="2">Total Price</td>
                                                <td colSpan="2">
                                                    <Field
                                                        name="grand_total"
                                                        label=""
                                                        type="text"
                                                        component={ReduxFormNominalField}
                                                        disabled={true}
                                                    />
                                                </td>
                                            </tr>
                                        </tfoot>
                                    </table>
                                </div>
                            </div>
                        </div>

                        <div className="row">
                            <div className="col-sm-12">
                                <div className="pull-right">
                                    <Button htmlType="submit" type="primary" size="large" onClick={handleSubmit(this.onSubmit.bind(this))}>Save</Button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        );
    }

    render() {
        return (
            <div className="wrapper">
                <Card bordered={false} title="New Quotation">
                    {this.onRenderForm()}
                </Card>
            </div>
        )
    }
}

function mapStateToProps(state) {
    return {
        customer: state.customer,
        freight: state.freight,
        general: state.general,
        form: state.form,
    };
}

function mapDispatchToProps(dispatch) {
    return bindActionCreators({
        fetchCustomerList,
        fetchFreightList,
        fetchServiceTypeList,
        fetchContainerTypeList
    }, dispatch);
}

export default connect(mapStateToProps, mapDispatchToProps)(reduxForm({
    form: 'MyForm',
    enableReinitialize: true,
    destroyOnUnmount: true,
})(MyForm));

`

**Comment by gustavohenke** [comment]
Sorry, but we don't do usage support on our issue tracker.
Please open a new issue with the exact problem you are facing.
