### ISSUE TITLE
Should trigger validation on props change

### ISSUE THREAD

**Issue by zlk89** [erikras/redux-form#4262]
### Are you submitting a **bug report** or a **feature request**?

bug report

### What is the current behavior?

Validation doesn't get triggered when props changes.

### What is the expected behavior?

Redux form trigger validations when props change.

### Sandbox Link

https://codesandbox.io/s/mmlv584j2p
![nov-07-2018 21-11-12](https://user-images.githubusercontent.com/7234480/48179002-bc4ceb80-e2d1-11e8-9523-2ed3ced65907.gif)

See the giphy, the validate basically just checks if both values.name and props.copyOfName are the same.

### What's your environment?

Redux Form version: 7.4.2
see codesandbox reproducible example. It should apply for all envs.

**Comment by lexanth** [comment]
By default, it only validates if values change. You could implement [shouldError](https://redux-form.com/7.4.2/docs/api/reduxform.md/#-code-shoulderror-params-boolean-code-optional-) to compare copyOfName prop as well as values:
```
const shouldError = ({
  values,
  nextProps,
  props,
  initialRender,
  structure,
  lastFieldValidatorKeys,
  fieldValidatorKeys,
}) => {
  if (initialRender) {
    return true
  }
  return (
    !structure.deepEqual(values, nextProps && nextProps.values) ||
    !structure.deepEqual(lastFieldValidatorKeys, fieldValidatorKeys) ||
    nextProps.copyOfName !== props.copyOfName
  )
}
```

**Comment by srishtinanda** [comment]
UPDATE_SYNC_ERRORS not invoked when unregistering Field #3189 still not fixed even in the latest version of redux-form 7.4.2. 
https://github.com/erikras/redux-form/issues/2979
https://github.com/erikras/redux-form/issues/3433 
When these are expected to be fixed?
