### ISSUE TITLE
Change withRef -> forwardRef to adhere to changes in react-redux@6

### ISSUE THREAD

**Issue by LKay** [erikras/redux-form#4270]
**feature request**?

New version of redux binding for React (`react-redux`) are getting some update with version 6 (https://github.com/reduxjs/react-redux/releases/tag/v6.0.0-beta.1). There are however few breaking changes and one of them affecting `redux-form`. Currently `withRef` is passed down somewhere (I couldn't pin point the place in the code) which results in error. This should be changed to `forwardRef` .

**Comment by rhys-vdw** [comment]
Why is this closed? This is blocking me from updating react-redux.

**Comment by rhys-vdw** [comment]
Duplicated here anyway: #4286
