### ISSUE TITLE
Unnecessary call of render due update of prop values

### ISSUE THREAD

**Issue by ViktorAksionov** [erikras/redux-form#4271]
### Are you submitting a **bug report** or a **feature request**?
Bug report

### What is the current behavior?
https://github.com/erikras/redux-form/blob/master/src/createReduxForm.js#L275
On each update of field prop `values` also will be updated as result the `render` will be called.
If we need form values then we can use `formValues `, so why prop `values` was added as mandatory prop?

### What is the expected behavior?
I expect, that there should be no `values` prop.

### Sandbox Link
No need, see source code here https://github.com/erikras/redux-form/blob/master/src/createReduxForm.js#L275

### What's your environment?
react@15.6.2 (legacy project :-( )
redux@3.7.2
redux-form@7.4.2
Chrome@70

**Comment by gustavohenke** [comment]
I'm not sure where that prop is coming from, but there's a list of props that should be ignored when updating.
https://github.com/erikras/redux-form/blob/v7.4.2/src/createReduxForm.js#L79-L88
