### ISSUE TITLE
redux form field with select input type not changing

### ISSUE THREAD

**Issue by shorif2000** [erikras/redux-form#4276]
not sure if this is a bug or code is not working. but the `onchange` event for a select box is not updating the gui. 

https://codesandbox.io/s/24x376j98n

It seems like after the change event a re-render is not triggered to update the value on the from end. however it holds the correct value in props

**Comment by gustavohenke** [comment]
I have a strong suspect that it is because you mounted the reducer on the wrong key.
I could not verify it because your example breaks when I change it and you have a 3k SLOC sandbox that I'm not poking with.

So the reducer's default is `form`. If you wanna mount it on `forms` (like you did), then you should apply some work-arounds when applying the `reduxForm` decorator to your components.

See https://redux-form.com/7.4.2/docs/api/reducer.md/ for details.

**Comment by shorif2000** [comment]
@gustavohenke you can access sandbox here https://codesandbox.io/s/24x376j98n?autoresize=1&codemirror=1&eslint=1&expanddevtools=1&hidenavigation=1&moduleview=1&previewwindow=tests

**Comment by shorif2000** [comment]
@gustavohenke the way it is documenting is throwing me the following error

`Warning: Failed prop type: Invalid prop `form` of type `object` supplied to `Form(IAMSubnetForm)`, expected `string`.`

and the output of `this.props.form` is `{"object Object":{"values":{"type_of_subnet_id":"","subnet_type":"","location":"","security_zone":"","seczone":"","routing_domain":"","zone_confirm":"No","subnet_size":"","subnet_confirm":"No","iam_addressing_type_id":"","address_space":"","allocation_range":"","new_subnet":"","desc_vr":"","desc_vr_confirm":"","l2env":"","l2env_confirm":"","l3dev":"","l3dev_confirm":"","zone_platform":"","wo":"","iam_network_diagram_id":"","subnet_class":"","project":"","justification":"","project_confirm":""},"initial":{"type_of_subnet_id":"","subnet_type":"","location":"","security_zone":"","seczone":"","routing_domain":"","zone_confirm":"No","subnet_size":"","subnet_confirm":"No","iam_addressing_type_id":"","address_space":"","allocation_range":"","new_subnet":"","desc_vr":"","desc_vr_confirm":"","l2env":"","l2env_confirm":"","l3dev":"","l3dev_confirm":"","zone_platform":"","wo":"","iam_network_diagram_id":"","subnet_class":"","project":"","justification":"","project_confirm":""}}} `

**Comment by gustavohenke** [comment]
Hmm your sandbox is huge. There's no way I'm going to debug a 3k SLOC.
The most I can do is to recommend you to take a look at your `mapStateToProps` function. You are giving the whole Redux state to the form, so maybe that's the source of your issues.

**Comment by gustavohenke** [comment]
Also, since we don't do issue support on StackOverflow, I'm closing this issue now.
