### ISSUE TITLE
Wrapped component does not receive changed context immediately

### ISSUE THREAD

**Issue by pristas-peter** [erikras/redux-form#428]
Hi, I have a problem when component is wrapped in redux-form decorator, it stops receiving changed context from parent, it only changes on next render (when one of the props change...).

When component is not wrapped and parent calls setState, which is also affecting its propagated context to children, all children are re-rendered immediately.

**Comment by kristian-puccio** [comment]
see issue #436  but a temp workaround is this: 
`export default connect(select, null, null, {pure: false})(TeamContainer);`

**Comment by danielrob** [comment]
Related #2026?

**Comment by gustavohenke** [comment]
Since this is a very old issue with no responses... I'll close it.

Let us know in case you're still experiencing problems with newer versions of Redux Form.
