### ISSUE TITLE
Updated to 8.0.1, metro bundler encountering error finding index.js

### ISSUE THREAD

**Issue by dereknelson** [erikras/redux-form#4294]
### What is the current behavior?

Installing redux-form via `yarn add redux-form` and importing `import { form } from 'redux-form` breaks metro, giving the following error: 

> While trying to resolve module `redux-form` from file `...myProject/src/redux/reducers.js`, the package `.../node_modules/redux-form/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`.../node_modules/redux-form/index.js`. Indeed, none of these files exist:
[17:25:13]   * `.../node_modules/redux-form/index.js(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`
[17:25:13]   * `.../node_modules/redux-form/index.js/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`

I dug into the node modules folder and there is no index.js, just index.js.flow. Do I need to have flow configured for it? 

### What is the expected behavior?
Importing it to use it as it was used with the previous version - I relied heavily on redux-form in its previous versions and it worked great. 

### What's your environment?

Node: 8.9.4
React: 16.5.0
React-Native: 57.0
```
"react-redux": "^6.0.0",
"redux": "^4.0.1",
"redux-form": "^8.0.1",
```

**Comment by gustavohenke** [comment]
Hmm likely related to #4293 then 🤔

**Comment by dereknelson** [comment]
@gustavohenke it worked in codesandbox but I assumed that was because of the way that bundler worked.

**Comment by dereknelson** [comment]
I just find it interesting that on the repo all the files are .js but when they're downloaded they turn into .js.flow which I think is what the issue stems from

**Comment by dereknelson** [comment]
In the package.json I changed main from `"main": "./index.js",` to `"main": "./es/index.js",` and now it works as expected.

**Comment by merildev** [comment]
That error is still occuring for Flow:

```
Error -------------------------------- node_modules/redux-form/index.js.flow:41:44

Cannot resolve module ./selectors/isSubmitting.types.
```

The Flow `index.js` file should probably be in `es/` too and not the root.
