### ISSUE TITLE
What is it with FormName?

### ISSUE THREAD

**Issue by smithyj** [erikras/redux-form#4297]
I don't know how to use this.
Document without example

**Comment by gustavohenke** [comment]
Did you mean [`FormName`](https://redux-form.com/8.0.1/docs/api/formname.md/)?

**Comment by smithyj** [comment]
@gustavohenke yes

**Comment by gustavohenke** [comment]
It's a component to pass the current form's name down via render props.

Its usage would look like this:

```
<FormName>
{( form } => (
  <span>you are editing {form} form</span>
)}
</FormName>
```

For more details please look at #4037/#4038.

**Comment by smithyj** [comment]
That's well，thanks
