### ISSUE TITLE
[8.0.4] normalize throws an error

### ISSUE THREAD

**Issue by NSLS** [erikras/redux-form#4303]
### Are you submitting a **bug report** or a **feature request**?
Bug report

### What is the current behavior?
Normalize throws an error: `Uncaught TypeError: this.ref.current.getValue is not a function`

### What is the expected behavior?
Normalize should work as in v7

### Sandbox Link
Here is the sandbox for v7, which works:
https://codesandbox.io/s/4z9y7z01l9

Here is the sandbox for the latest version, which breaks:
https://codesandbox.io/s/nr3080orz0

### What's your environment?
redux-form: 8.0.4

### Other information
It seems like this is brought by the introduction of the `forwardRef` API.

Maybe related to this:
https://github.com/erikras/redux-form/commit/7b75f1b71ace0bb4805f754347dbeb7ef96a812f#diff-e22d664cbd78ed0741febe44dcadbd90

**Comment by storesbuzz** [comment]
Hey, @NSLS have you got a solution for this? I am also getting the same error with normalize.

**Comment by NSLS** [comment]
@storesbuzz Not really, we had to downgrade to v7 for now, till this is fixed. 

I believe there is also an issue with the new Context API, so I would recommend to stick with v7 for now, as there are no major benefits of v8.

We only wanted to upgrade to get rid of the annoying PropTypes errors from the `component` props, which are caused by the new `ForwardRef` API not being detected as a React.Node.

@erikras Maybe we should merge the PropTypes fix to the v7 branch and release a new 7.x.x version?

This would be very useful until v8 is fixed

**Comment by jacekkolasa** [comment]
@NSLS your example had improper `react-redux` version (it has to be @6). i've modified your example by updating `react-redux` and by changing normalizer arguments to just `(value) =>` - and it works. Do you still see the error after updating `react-redux`?
cc @storesbuzz

**Comment by NSLS** [comment]
Yeah, upgrading react-redux solves the issue.

Thanks!

**Comment by kylebebak** [comment]
But it doesn't work with with react-redux v7... Jeeeeeez =(
