### ISSUE TITLE
[v8.0.4] Could not find "store" in a popover component

### ISSUE THREAD

**Issue by microdou** [erikras/redux-form#4312]
### Are you submitting a **bug report** or a **feature request**?
Bug Report

### What is the current behavior?
See codesandbox, the form contained in a popover component (`reactstrap`) cannot get access to the `store`, after upgrading to `redux-form` version `8`.

`Uncaught Error: Could not find "store" in the context of "Connect(Component)". Either wrap the root component in a <Provider>, or pass a custom React context provider to <Provider> and the corresponding React context consumer to Connect(Component) in connect options.`

### What is the expected behavior?
Form contained in a popover component (`reactstrap`) should be able to get access to the `store`, as in all prior versions of `redux-form`. And my Popover Counter example works under `react-redux 6.0.0`, in the absence of `redux-form`.

### Sandbox Link
`redux-form 8.0.4, react-redux 6.0.0` (Not working): https://codesandbox.io/s/8ploq71969
`redux-form 7.4.2, react-redux 5.1.0` (Working): https://codesandbox.io/s/2vn79o4p

`react-redux 6.0.0` (Popover Counter works): https://stackblitz.com/edit/reactstrap-v6-f8vkhd

### What's your environment?

- Redux related:
```
redux-form: 8.0.4
react-redux: 6.0.0
redux: 4.0.1
```

- React related:
```
react: 16.6.3
react-dom: 16.6.3
```

- Bootstrap related:
```
reactstrap: 6.5.0
bootstrap: 4.1.3
jquery: 3.3.1
popper.js: 1.14.6
```

### Other information
I've been struggling after the `version 8` upgrade.
It seems like the `Popover` component from `reactstrap` is added to the stage only after the trigger button is clicked, which likely makes `store` unrecoverable.
However, I believe the issue is from `redux-form 8`, not from `react-redux 6.0.0`, because my Popover Counter example works in `react-redux 6.0.0`.

**Comment by microdou** [comment]
@jacekkolasa Thank you for looking into it. I still believe the issue is from `redux-form`...
`redux-form` is still used in your example (https://codesandbox.io/s/k787kn763).
`Popover` is a connected component in the working example (https://stackblitz.com/edit/reactstrap-v6-f8vkhd) where both `redux` and `react-redux` are updated. By removing `PopoverBody` wrapper out, the example still works. So looks like `redux`, `react-redux` and `reactstrap` have no issue.

**Comment by jacekkolasa** [comment]
@microdou i'm sorry but i still think it's not redux-form :) Here's the example without redux-form, which was working, but now it doesn't because i've wrapped the `Popover` child into `connect()`: https://reactstrap-v6-wqxfs2.stackblitz.io

And here https://codesandbox.io/s/xv654jo8z4 is the first example where i've removed the rest of `redux-form`, ie. reducer and also the library. It shows the same error. I hope it does make sense

**Comment by pgrodrigues** [comment]
I think I'm having a similar issue after upgrading `react-redux` to 6.0.0 and `redux-form` to both 8.0.4 / 8.1.0. Somehow, all my connected components work well except the ones using reduxForm decorator. I'm not using anything bootstrap related.

**Comment by microdou** [comment]
@jacekkolasa Wow, thank you! Indeed! It's not a `redux-form` issue, although it appeared to be one in my original post.

It was likely an issue of `reactstrap` instead.

I just found `reactstrap 7.0` is out. It solves the issue completely. Here is an example of a working connected form in `react-redux 6.0` and `reactstrap 7.0`, without `redux-form`. https://codesandbox.io/s/mz6pjqvlkj

@pgrodrigues
