### ISSUE TITLE
reduxForm(configs)(Component) is returning an object, not a function

### ISSUE THREAD

**Issue by godlike0108** [erikras/redux-form#4318]
### Are you submitting a **bug report** or a **feature request**?

Bug Report

### What is the current behavior?

For version 8.0.4,  the result of `reduxForm(configs)(Component)` is a object, not a function.
This will induce errors when combining with `react-router`, because `react-router` expect the passed in component to be a function.

### What is the expected behavior?

It should be a function.

### Sandbox Link

https://codesandbox.io/s/03q9pwo7o0

### What's your environment?

redux-form version: v8.0.4

**Comment by DOCS-kdu3** [comment]
I inherited a React project at my workplace and this is a bug I would love to solve. Props to godlike0108 for the writeup. Commenting for additional visibility.

**Comment by gustavohenke** [comment]
Technically a function is an object :trollface: 

redux-form v8 started using `React.forwardRef`, and react-router 4.3 is not ready for it yet. https://github.com/ReactTraining/react-router/issues/4354#issuecomment-439580576

Quick solution for you guys:
- Use react-router v4.4 beta
- Wrap redux-form components in a stateless component
