### ISSUE TITLE
Editing one form causes another on the same page to re-render

### ISSUE THREAD

**Issue by tomduncalf** [erikras/redux-form#432]
I'm currently debugging some performance issues related to forms on an application I am building, and one in particular seems very strange.

At some points there are two forms on the page - one for search filters, another for a data entry form in a modal. Typing in the data entry modal is noticeably sluggish, and the main culprit seems to be the ReduxFormConnector component - which makes some sense for the form in which I am typing, but there is no reason for the other form to be re-rendering.

Below is Perf.printInclusive() output while typing into the `InfluencerDetailView` form - as you can see, most of the time is spent rendering the `SearchFilters` form, even though that form isn't changing at all (and is not subscribed to any parts of the state that may change).

![image](https://cloud.githubusercontent.com/assets/5458070/11845802/6f7d841e-a40d-11e5-803b-f4a150588a7e.png)

Digging deeper, I added the pure render decorator to the SearchFilters component (which is wrapped in reduxForm - BTW, is it best practice to implement `shouldComponentUpdate` or should redux-form do it itself?) and added some debug to the `shallowEqual` check on the props, and the props which are causing it to re-render are all the functions passed in by redux-form ('asyncValidate', 'destroyForm', 'initializeForm', 'resetForm', 'touch', 'touchAll', 'untouch', 'untouchAll').

I tried ignoring these when doing the pure render comparison but that breaks the form.

Any ideas?

Cheers,
Tom

**Comment by erikras** [comment]
Are the two forms attached to the same form slice? i.e. is the `form` parameter to `reduxForm()` the same for both of them?

**Comment by tomduncalf** [comment]
No, one has `form: 'search'` and the other `form: 'influencer'`

**Comment by beeant** [comment]
same thing happens to me :(

**Comment by gustavohenke** [comment]
Hi @beeant, do you mind opening a new issue with a reproducible example, please?

This issue probably referred to some really old version like v3 or v4, so I'll close it.
