### ISSUE TITLE
[Feature Request] Add @babel/plugin-transform-runtime

### ISSUE THREAD

**Issue by vtaits** [erikras/redux-form#4324]
### Are you submitting a **bug report** or a **feature request**?

feature request

### Other information

https://babeljs.io/docs/en/next/babel-plugin-transform-runtime.html

Remove trash from builds for decrease package size, e.g. `es/createField.js`:

Before:
![image](https://user-images.githubusercontent.com/4801414/50364955-523b8d80-0583-11e9-8d14-c6d3035ea462.png)

After:
![image](https://user-images.githubusercontent.com/4801414/50364992-857e1c80-0583-11e9-9963-1f51544a29c1.png)

**Comment by erikras** [comment]
Published fix in [`v8.1.0`](https://github.com/erikras/redux-form/releases/tag/v8.1.0).
