### ISSUE TITLE
__tests__ in es and lib directories

### ISSUE THREAD

**Issue by vtaits** [erikras/redux-form#4325]
### Are you submitting a **bug report** or a **feature request**?
bug report

### What is the current behavior?
```
$ find lib es -type d -name __tests__

lib/selectors/__tests__
lib/structure/plain/__tests__
lib/structure/immutable/__tests__
lib/events/__tests__
lib/__tests__
lib/util/__tests__
es/selectors/__tests__
es/structure/plain/__tests__
es/structure/immutable/__tests__
es/events/__tests__
es/__tests__
es/util/__tests__
```

### What is the expected behavior?

No `__tests__` directories in `lib` and `es`

### What's your environment?
- redux-form: master branch
- node: 10.14.2
- npm: 6.4.1
- os: Ubuntu 16.04.5 LTS

### Other information

Looks like bug in `build:lib` and `build:es` scripts. `--ignore __tests__` is old format. New format is `--ignore \"src/**/__tests__\"`.

**Comment by gustavohenke** [comment]
Thanks for the report.
Since you already seem to know how to fix this, would you like to send us a PR? 🙂
