### ISSUE TITLE
SubmissionError is not working with dropdwon field using redux-form

### ISSUE THREAD

**Issue by saurabhmit06** [erikras/redux-form#4340]
i am working on scenario where i need to show server side validation on field (like textbox and dropdrop type of field) to integrate the same i am using redux-form. but after integration i found Error is not shown on dropdown type of field .

### What is the current behavior?
After debugging i found component render two time. first time with error and second time without error. unexpected behavior in case of dropdown.

### What is the expected behavior?
i expected SubmissionError fire on dropdown type field

https://codesandbox.io/s/143mj36nrl

### What's your environment?
redux-form 8v

**Comment by gustavohenke** [comment]
Your dropdown implementation is the default one (`component="select"`), which doesn't show any errors.
You should implement something like `renderField`, used by the username and password fields in that example.
