### ISSUE TITLE
External FieldArray change doesn't re-render it

### ISSUE THREAD

**Issue by shmilyoo** [erikras/redux-form#4346]
### Are you submitting a **bug report** or a **feature request**?

I think it maybe a bug.

### What is the current behavior?

Suppose there are some rows in the fieldArray, I want one or more specific row to be hidden when I do something, such as click the delete button, set the value of type field to 'delete' .    
I already set the row style's display css attribute to 'none' if the row given 'type' field's value is 'delete'. When I click the first row delete button , the row disppeared as I wish . But when I click the another row's delete button , nothing happens. But if I focus/click something,such as the input, in the fieldarray, the deleted row disppeared. 
So I manually dispatch a focus action whenever the click handle function is invoked, to make the behavior correct. You can find it in the sandbox, Form.js component file.

### What is the expected behavior?
When I click any row to delete, it should be disappeared.

### Sandbox Link

[https://codesandbox.io/s/jl4nn0k33](https://codesandbox.io/s/jl4nn0k33)
if uncomment the line in the form.js, the behavior will be correct. 

### What's your environment?

node: 8.11.1
os: ubuntu 16.04
redux-form: 7.4.2 - 8.1.0(sandbox)

**Comment by gustavohenke** [comment]
This isn't a bug.

Each Redux Form component is implemented in a way that it only re-renders when something concerning its own state changes, eg in the `FieldArray` case, the addition/deletion of an item. The value of a `Field` inside a `FieldArray` isn't a concern of the array, but of the field.

You can definitely fix it by passing [`rerenderOnEveryChange`](https://redux-form.com/8.1.0/docs/api/fieldarray.md/#-code-rerenderoneverychange-boolean-code-optional-) to `FieldArray`.

**Comment by shmilyoo** [comment]
@gustavohenke  thanks for your reply.
I try it with your way. But it still does not work. 
1. I add a Field like <Field name={`${work}.type`} component="input" /> in the Form.  It does not work
2. I add rerenderOnEveryChange prop , and it still not work. 

please check the sandbox [https://codesandbox.io/s/jl4nn0k33](https://codesandbox.io/s/jl4nn0k33), I have modify it .
