### ISSUE TITLE
Redux-form does not pass some props to form component from redux

### ISSUE THREAD

**Issue by pauldmps** [erikras/redux-form#4348]
### Are you submitting a **bug report** or a **feature request**?
Bug Report

### What is the current behavior?

Redux state has a variable called 'warning' with an string as value.

It is available in components using mapStateToProps but for components with reduxForm HOC added, it shows up as undefined.

Surprisingly, other state values show up fine. Renaming the variable also fixes the issue.

### What is the expected behavior?
this.props.warning should not be undefined inside a component with reduxForm as its HOC.

### Sandbox Link
[https://codesandbox.io/s/1vnokw0w84](https://codesandbox.io/s/1vnokw0w84)

In the above sandbox, the warning string should show up twice - Once in PlainComponent and once in FormComponent but it shows up only once because, it is undefined in FormComponent.

### What's your environment?
React 16.2.0
Redux 3.7.2
Redux form 8.1.0
Node 8.9.4

**Comment by gustavohenke** [comment]
That's a documented prop that the `reduxForm` decorator passes to the wrapped component.
[Docs](https://redux-form.com/8.1.0/docs/api/props.md/#-code-warning-any-code-)
