### ISSUE TITLE
Validator fails with limited field set

### ISSUE THREAD

**Issue by kpdecker** [erikras/redux-form#435]
When trying to construct a form that utilizes a fields list that is a subset of those specified by the validator, 
errors returned for non-applied fields are still examined.

Ex:
```
export function validate(data, props) {
  let errors = {};

  if (!data.email) {
    errors.email = 'Required';
  } else if (!(/^[^\s@]+@[^\s@]*[^\s@.]$/.test(data.email))) {
    errors.email = 'Must be a valid email address';
  }
  if (!data.password) {
    errors.password = 'Required';
  } else if (data.password.length < 4) {
    errors.password = 'Password must be at least 4 characters';
  }

  return errors;
}
```

```
      <form className="form-horizontal" onSubmit={handleSubmit((params) => this.onSubmit(params))}>
        <TextInput
            label="Email Address"
            type="email"
            disabled={submitting}
            {... fields.email}
        />
      </form>
...
export default reduxForm({
    form: 'user',

    fields: ['email'],
    destroyOnUnmount: true,
    validate
  })(EmailForm);
```

Will silently fail the form submission due to the password validator failing. This is a change in behavior between 2.x and 3.x+ and can be worked around by checking the `props` argument in the validator, but it seems like there's some room for having the library handle this.

**Comment by erikras** [comment]
Yeah, this has bitten me enough times that I made it the [very first FAQ](http://erikras.github.io/redux-form/#/faq/submit-function). I'll think about ways to solve this.

**Comment by kpdecker** [comment]
Doh, I completely missed that FAQ.

Regarding solutions, my naive first attempt would be to pass in the fields object to the root call of [this](https://github.com/erikras/redux-form/blob/master/src/isValid.js#L1) method and filter on that, but I don't feel like I'm comfortable enough with all of the features this project has to actually say that is a 100% safe change to make or not.

**Comment by kpdecker** [comment]
Going to force application code to handle this or was there a change at the library level somewhere?

**Comment by ooflorent** [comment]
It should be handled in the application code.

**Comment by kpdecker** [comment]
Was it not technically feasible to check this in the library? This forces a quite a bit of boilerplate in the validators that could be removed if the library implemented this. Ex:

```
  if (fields.indexOf('title') >= 0) {
    if (!data.title) {
      errors.title = 'Required';
    }
  }
```

Also the FAQ in question no longer addresses this case.

**Comment by ooflorent** [comment]
> Was it not technically feasible to check this in the library?

I guess it is a design decision. According to the documentation: if `validate` does not return an empty object, then there is submission errors.

If you don't want undefined fields to raise errors, then you must not include them. You could reduce the boilerplate by wrapping your `validate` function to omit unknown fields.

```js
function filterValidator(validate) {
  return (values, {fields}) => {
    const errors = validate(values)
    return _.omitBy(errors, (value, field) => fields.indexOf(field) === -1)
  }
}

reduxForm({
  fields: ["foo", "bar"],
  validate: filterValidator(myValidator),
})
```

The above snippet will omit errors that are not on `foo` or `bar`.

**Comment by kpdecker** [comment]
Seems simple enough to include in the library :)

Note that the implementation that I'm requesting was the active one under 2.0, so there is a precedent for the behavior. Given that the library also requires that fields be declared, I don't see a down side to doing this.

Is there a use case where a user may want to return a validation error on a non-field that this behavior would prevent? What would error handling for those cases look like?

**Comment by ooflorent** [comment]
Changing this would result in a major breaking change because this is a long time bug and some codebase may depend on this clumsy behavior.

v6 introduces a completely new validation system and should be the one where this is fixed. cc @erikras

**Comment by erikras** [comment]
`v6` was designed with this in mind. `v6` will only validate the fields that appear in your form.

For example, in the [`v5` Wizard Example](http://redux-form.com/5.2.3/#/examples/wizard), it was important that each page of the wizard only validate the fields that appeared on it, but on the [`v6` Wizard Example](http://redux-form.com/6.0.0-alpha.13/examples/wizard/), there is one form-wide validation function, and each wizard page _knows_ which fields are on it.

**Comment by kpdecker** [comment]
Perfect, thank you! I completely understand not doing this in non-breaking change.
