### ISSUE TITLE
Fields unregistered when destroyOnUnmount and forceUnregisterOnUnmount are false

### ISSUE THREAD

**Issue by gknapp** [erikras/redux-form#4350]
### Are you submitting a **bug report** or a **feature request**?
Bug report

### What is the current behavior?
I have a tabbed dialog, each tab containing a form. When a tab is selected, that form is rendered (the previous form is not rendered / unmounted). I have set `destroyOnUnmount: false` to preserve the form state. The Save button submits the form via remote submit (as it's not part of the form but on the dialog, outside the tab). When clicking Save `@@redux-form/SUBMIT` is dispatched. However, submit doesn't call the `onSubmit` handler, as you cannot prevent `@@redux-form/UNREGISTER_FIELD` from being dispatch when a form is unmounted. The `UNREGISTER_FIELD` action sets the `count` to `0` in the redux store (seems to prevent `onSubmit` being called).

Redux form options:

```js
const form = reduxForm({
  destroyOnUnmount: false,
  forceUnregisterOnUnmount: false, // unnecessary as this is the default?
  form: "myForm",
  onSubmit: (values) => {
    console.log("I cannot be called via remoteSubmit as field(s) unregistered");
  }
});
```

### What is the expected behavior?
I expect `@@redux-form/UNREGISTER_FIELD` not to be dispatched if `destroyOnUnmount` and `forceUnregisterOnUnmount` are **false**.

### Sandbox Link
Complete on demand (not trivial).

### What's your environment?

Redux Form 7.4.2
Windows 10
Chrome 71
node.js 8.11.4

**Comment by ViktorAksionov** [comment]
You cannot expect that onSubmit can be called if form is unmounted.
You can remotely call submit function if form is still mounted, so in this case sync validation will happen.
If you need accumulate data from all forms from many places, then you need to read its state using `getFormValues` function.

**Comment by gknapp** [comment]
What is the purpose of maintaining the form state in the store after unmount if it cannot be submitted? To prevent a data fetch from the backend on subsequent mounts? (essentially a cache)

**Comment by ViktorAksionov** [comment]
Example: wizard form, where each step has own form and real submission you will do on final step.

**Comment by gknapp** [comment]
I'll re-write my multi-tab component to use the wizard form approach.
