### ISSUE TITLE
handleSubmit type declaration is incorrect (too strict)

### ISSUE THREAD

**Issue by asazernik** [erikras/redux-form#4351]
### What is the current behavior?

`handleSubmit` can be used in two ways: `<SomeElement onClick={handleSubmit} />` or `<SomeElement onClick={handleSubmit(innerCallback)} />`. The current type `(eventOrSubmit: any) => void | Promise<*>`, despite having made the parameter `any` to handle both cases, has the proper return type only for the former case. In the latter case, calling `handleSubmit` returns a function rather than `void | Promise`.

### Sandbox Link

Example is contrived to have my submit handler passed to a type-checked child component.

https://codesandbox.io/s/j4vjj6n2nv

You'll have to download it and run `npm install; npx flow` to see the errors, because Flow doesn't run in codesandbox.

### What's your environment?
Redux-form 7.1.2 and 8.1.0.

**Comment by erikras** [comment]
Published fix in [`v8.2.0`](https://github.com/erikras/redux-form/releases/tag/v8.2.0).
