### ISSUE TITLE
fields need be deep cloned when readFields

### ISSUE THREAD

**Issue by yesmeck** [erikras/redux-form#436]
Currently, fields is just a shallow copy of previous fields in these lines https://github.com/erikras/redux-form/blob/master/src/readFields.js#L27-L29 

Mutating fields directly will make follwing code failure:

``` javascript
componentWillReceiveProps(nextProps) {
  if (this.props.fields.phone.value !== nextProps.fields.phone.value) {
    // blah blah
  }
}
```

**Comment by kristian-puccio** [comment]
this is the reason #428 is happening.

Be create if the reference to the field object changed if the value changed. That way PureRenderMixin would work

**Comment by kristian-puccio** [comment]
I wonder how many issues would disappear if this change was made.

**Comment by kristian-puccio** [comment]
this fixes it in the meantime: ```export default connect(select, null, null, {pure: false})(TeamContainer);```

**Comment by sgtpepper43** [comment]
I've been trying to figure this out for hours. HOURS. Setting the component to not be pure works, but it'd be great if I could use the purerender mixin. But so, are you saying the reference to the field object _doesn't_ change? As in the state is _mutated_, which is expressly _[forbidden](http://redux.js.org/docs/Troubleshooting.html)_?

**Comment by erikras** [comment]
If someone could write a test that fails because of this, that would be most beneficial. Or if not a test, provide some sample code for a component that demonstrates the problem. I'm not 100% sure that I understand the issue.

**Comment by sgtpepper43** [comment]
What did it for me was having a component wrapped using `connect` as a child of a component wrapped with `redux-form`, with the fields being fairly deep.

I'll try to come up with a code sample or something later, but at the least, this was my form (with some stuff removed):
```javascript
[
  'locations[].id',
  'locations[].search',
  'locations[].urls[].siteName',
  'locations[].urls[].url'
]
```

The location data is filled out on one page, and the urls on another. The component `<VerifyUrlsForm>` is wrapped with `redux-form`, locations are mapped over to another component, `locations[].urls[]` is sent to `<UrlList>`, which is wrapped with `connect` so that I can make an api call access the inner component by setting `{ withRef: true }`.

The `<UrlListContainer>` would never update because `connect` only shallowly compares when it decides to update, and since the references to the `urls` array and its immediate children don't seem to change, it doesn't update.

**Comment by yesmeck** [comment]
@erikras I wrote a testcase for this issue https://github.com/yesmeck/redux-form/commit/ae9199b9a87576bd30985887ec62fd7673619304

**Comment by erikras** [comment]
@yesmeck Thank you for that. Please have a look at the commit above.

All of those tests pass except for your
```js
expect(lastPrevBarValue).toNotEqual(lastNextBarValue)
```
I am very confused as to why the props, when examined in the `stub` are correct, but the props as passed to `componentWillReceiveProps` are wrong. :question: :question: :question: 

Also, the `readFields` test is testing the specific code that is manipulating the `fields` tree, and it is also working as expected, mutating each node in the tree down to the change.

Any ideas, anyone?

**Comment by yesmeck** [comment]
@erikras You should compare values by object, string values are passing by  value https://github.com/yesmeck/redux-form/commit/2ee3c051313c7016c0a22c8eb186dc77644d73d0

**Comment by yesmeck** [comment]
![229 pic_hd](https://cloud.githubusercontent.com/assets/465125/13904560/eb5a5e96-eedf-11e5-87b8-609670cb4b3d.jpg)

It's weird, I use node-inspector inspect the previousFields.foo.bar value, it shows `next`.

**Comment by erikras** [comment]
It's like it's a temporal phenomenon, depending on when you observe the value. The whole reason we are using React and Redux is to have determinism. 😟

**Comment by yesmeck** [comment]
@erikras https://github.com/yesmeck/redux-form/commit/1fef8b8dd25bdfc817c50e9acffc2312060b4340 Check this.

**Comment by yesmeck** [comment]
:no_mouth: https://github.com/yesmeck/redux-form/commit/d3023a310b634853feec01045ac7347ad7dba95a

**Comment by yesmeck** [comment]
@erikras I thinks I figured it out, see commit above.

**Comment by yesmeck** [comment]
I'm worried, if fields are deep cloned, huge forms would run into worse performance.

**Comment by erikras** [comment]
That's disturbing. Can you submit a PR that fixes the problem?

We already know that the current way of generating the field tree is suboptimal for performance.

**Comment by yesmeck** [comment]
Ok, I'll be back look at this issue later this week.

**Comment by danielrob** [comment]
This v5 issue has expired. Closing :).
