### ISSUE TITLE
Field must be inside a component decorated with reduxForm()

### ISSUE THREAD

**Issue by javi10823** [erikras/redux-form#4363]
BUG REPORT

### What is the current behavior?
I receive a crash.

### What is the expected behavior?
No receive an crash error

### What's your environment?

Redux Forms version: 
    "redux-form": "^7.4.2",

    "react-navigation": "^2.18.2",
    "react-redux": "^5.1.1",
    "redux": "^4.0.1",

React Native Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
      Memory: 1.48 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 9.11.1 - ~/.nvm/versions/node/v9.11.1/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.1.0 - ~/.nvm/versions/node/v9.11.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

TRACE
[11:17:03] Error: Error: Error: Error: Field must be inside a component decorated with reduxForm()

This error is located at:
    in Field (at SignUp.js:61)
    in RCTView (at View.js:44)
    in KeyboardAvoidingView (at SignUp.js:57)
    in ExponentLinearGradient (at NativeLinearGradient.ios.js:6)
    in NativeLinearGradient (at LinearGradient.js:12)
    in LinearGradient (at SignUp.js:32)
    in RCTView (at View.js:44)
    in SignUp (at SceneView.js:9)
    in SceneView (at StackViewLayout.js:483)
    in RCTView (at View.js:44)
    in AnimatedComponent (at screens.native.js:58)
    in Screen (at StackViewCard.js:42)
    in Card (at createPointerEventsContainer.js:26)
    in Container (at StackViewLayout.js:507)
    in RCTView (at View.js:44)
    in ScreenContainer (at StackViewLayout.js:401)
    in RCTView (at View.js:44)
    in StackViewLayout (at withOrientation.js:30)
    in withOrientation (at StackView.js:49)
    in RCTView (at View.js:44)
    in Transitioner (at StackView.js:19)
    in StackView (at createNavigator.js:57)
    in Navigator (at createKeyboardAwareNavigator.js:11)
    in KeyboardAwareNavigator (at createNavigationContainer.js:376)
    in NavigationContainer (at SceneView.js:9)
    in SceneView (at createTabNavigator.js:39)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in ResourceSavingScene (at createBottomTabNavigator.js:108)
    in RCTView (at View.js:44)
    in ScreenContainer (at createBottomTabNavigator.js:98)
    in RCTView (at View.js:44)
    in TabNavigationView (at createTabNavigator.js:178)
    in NavigationView (at createNavigator.js:57)
    in Navigator (at createNavigationContainer.js:376)
    in NavigationContainer (at SceneView.js:9)
    in SceneView (at SwitchView.js:12)
    in SwitchView (at createNavigator.js:57)
    in Navigator (at createNavigationContainer.js:376)
    in NavigationContainer (at SplitGym.js:54)
    in Provider (at SplitGym.js:51)
    in RCTView (at View.js:44)
    in SplitGym (at App.js:58)
    in App (at registerRootComponent.js:17)
    in RootErrorBoundary (at registerRootComponent.js:16)
    in ExpoRootComponent (at renderApplication.js:34)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in AppContainer (at renderApplication.js:33)

This error is located at:
    in NavigationContainer (at SceneView.js:9)
    in SceneView (at createTabNavigator.js:39)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in ResourceSavingScene (at createBottomTabNavigator.js:108)
    in RCTView (at View.js:44)
    in ScreenContainer (at createBottomTabNavigator.js:98)
    in RCTView (at View.js:44)
    in TabNavigationView (at createTabNavigator.js:178)
    in NavigationView (at createNavigator.js:57)
    in Navigator (at createNavigationContainer.js:376)
    in NavigationContainer (at SceneView.js:9)
    in SceneView (at SwitchView.js:12)
    in SwitchView (at createNavigator.js:57)
    in Navigator (at createNavigationContainer.js:376)
    in NavigationContainer (at SplitGym.js:54)
    in Provider (at SplitGym.js:51)
    in RCTView (at View.js:44)
    in SplitGym (at App.js:58)
    in App (at registerRootComponent.js:17)
    in RootErrorBoundary (at registerRootComponent.js:16)
    in ExpoRootComponent (at renderApplication.js:34)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in AppContainer (at renderApplication.js:33)

This error is located at:
    in NavigationContainer (at SceneView.js:9)
    in SceneView (at SwitchView.js:12)
    in SwitchView (at createNavigator.js:57)
    in Navigator (at createNavigationContainer.js:376)
    in NavigationContainer (at SplitGym.js:54)
    in Provider (at SplitGym.js:51)
    in RCTView (at View.js:44)
    in SplitGym (at App.js:58)
    in App (at registerRootComponent.js:17)
    in RootErrorBoundary (at registerRootComponent.js:16)
    in ExpoRootComponent (at renderApplication.js:34)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in AppContainer (at renderApplication.js:33)

This error is located at:
    in NavigationContainer (at SplitGym.js:54)
    in Provider (at SplitGym.js:51)
    in RCTView (at View.js:44)
    in SplitGym (at App.js:58)
    in App (at registerRootComponent.js:17)
    in RootErrorBoundary (at registerRootComponent.js:16)
    in ExpoRootComponent (at renderApplication.js:34)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in AppContainer (at renderApplication.js:33)
- node_modules/redux-form/lib/createField.js:79:14 in new
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:8039:17 in constructClassInstance
- ... 9 more stack frames from framework internals

**Comment by revoltaxz** [comment]
Your form component must wrapped with reduxForm decorator

```
const AnyForm = () => {
     return (
       <form onSubmit={handleSubmit}>
           <div>
             <label htmlFor="firstName">First Name</label>
             <Field name="firstName" component="input" type="text" />
           </div>
           <div>
             <label htmlFor="lastName">Last Name</label>
             <Field name="lastName" component="input" type="text" />
           </div> 
         <button type="submit">Submit</button>
       </form>
      )
} 

AnyForm = reduxForm({
  form: 'formname'
})(AnyForm)

```

**Comment by gustavohenke** [comment]
Thanks @revoltaxz
