### ISSUE TITLE
Form Field change is not firing UPDATE_SYNC_ERRORS when editing existing values, but works with new values

### ISSUE THREAD

**Issue by mcupito** [erikras/redux-form#4364]
Using Redux-form 7.4.2

I'm experiencing some behavior that I cannot seem to figure out. My data model and component setup looks like this. (Note: I trimmed down a lot of code to try to get to the root cause, if more detail is needed please let me know)

```
class Accr extends Component {
 constructor(props) {
     super(props)
}

<Accr>
    <form>
        <FieldArray {Rule} />
    </form>
</Accr>

Accr= reduxForm({
    form: 'timeOffPlanAccrualForm',
    onSubmit: mySubmit,
    enableReinitialize: true,     
    validate: validateTimeOffPlanAccrualForm,
    touchOnBlur: true,
    touchOnChange: true
})(Accr)

}
   <Rule>  //I'm referencing components like this for brevity but this is essentially class Rule extends Component, etc
         <FieldArray {Milestones} />
   </Rule>

          <Milestones>
                 <Milestone> //if user is adding or editing
          </Milestones>

               <Milestone>
                              //path is the path to this element via the root, e.g : rules[0].milestones[1]
                                       <Field
                                            name={`${path}.accrueAfterTimeIncrement`}
                                            id='accrueAfterTimeIncrement'
                                            label='After'
                                            component={SlimNumberBox}
                                            type='text'
                                            min={this.state.min}
                                            max={this.state.max}
                                        >
                                        </Field>
                </Milestone>
```

When Adding a new Milestone, we are directly interacting with the `fields` prop, but when editing we are strictly dealing with the existing data model and using the `path` for those changes, which I see both updating in the state tree when making changes.

The issue is validation is not firing for Edits, but it is for Adds. I can see the `CHANGE` event firing for both, and they look identical, but I need the validation to fire for the Edits as well.

Working: 
<img width="275" alt="2019-01-18_10h49_50" src="https://user-images.githubusercontent.com/6664457/51398095-ac8f2600-1b10-11e9-966f-4396ce6e90b6.png">

Not Working : 
<img width="275" alt="2019-01-18_10h48_38" src="https://user-images.githubusercontent.com/6664457/51398108-b3b63400-1b10-11e9-943d-4f97fc39c2c6.png">

### What is the expected behavior?

I am expecting the Edits to have triggered the Validation as well.

**Comment by polezhaevao** [comment]
@mcupito Hi. you resolve this problem ?
