### ISSUE TITLE
Time to DEPRECATE

### ISSUE THREAD

**Issue by lytc** [erikras/redux-form#4376]
For the first, THANK YOU for your efforts to maintenance this package!

I've use this package for years and I'm happy with it until l ask a question to myself "Why we put forms in Redux?" and the answer is that unnecessary!

Redux-form was a best package that I found a few years ago but today it's a wrong choice and I don't want any new devs have the same mistake like me!

As a developer perspective please DEPRECATE this package or at least noticed people considering before choosing this package and suggest to use another react form (w/o Redux) like [Formik](https://jaredpalmer.com/formik) instead.

**Comment by silltho** [comment]
I tried over 4 hours to get the "new" material-ui v1 work with redux-form and couldn't do it. So i think you are right and i will have a look at Formik now.

**Comment by erikras** [comment]
If you're interested in a nearly identical API with [an MUIv1 example](https://github.com/final-form/react-final-form#material-ui-10), you might try [React Final Form](https://github.com/final-form/react-final-form#-react-final-form), by the same author as Redux-Form.
