### ISSUE TITLE
structure/deepEqual invalid equality for undefined/null/NaN/0 value

### ISSUE THREAD

**Issue by tomasztomys** [erikras/redux-form#4378]
### Are you submitting a **bug report** or a **feature request**?
bug

### What is the current behavior?
eg.
NaN is equal to 0
undefined is equal to null

### What is the expected behavior?
NaN is not equal to 0
undefined is not equal to null (I think so)

### Sandbox Link
doesn't matter

### What's your environment?
doesn't matter

### Other information
deepEqual is using to compare if redux-form should reinitialize form on initialValues change.

If first initialValues are {a: NaN}, and next {a: 0}, it doesn't reinitialize form (even if enableReinitialize is set to true).

probably related to https://github.com/erikras/redux-form/issues/3796

**Comment by sanex3339** [comment]
Same thing

**Comment by erikras** [comment]
Published fix in [`v8.2.0`](https://github.com/erikras/redux-form/releases/tag/v8.2.0).
