### ISSUE TITLE
getFormMeta returning empty object for Form fields with display: none

### ISSUE THREAD

**Issue by chirag-auto1** [erikras/redux-form#4387]
### Are you submitting a **bug report** or a **feature request**?
Bug report

### What is the current behavior?
In my Redux Form, I have an `onChanged` handler added to the form, which triggers an action for some tracking purpose as shown below

```
@reduxForm({
  form: FORM_NAME,
  touchOnBlur: false,
  onChange: autoSaveAndTrackChanges,
})
```
In the `autoSaveAndTrackChanges` method, I am calling `getFormMeta` method, to find the field which has `{ active: true }` just to find which field was changed.

It works fine for all the fields, except for one of my custom Checkbox component which has the actual `<input>` element hidden with styling `{ display: none }` because it shows a fancy checkbox instead of the regular one. `getFormMeta` returns an empty object when this checkbox is checked.
However, when I remove `display: none` from the `<input>` element, `getFormMeta` works fine and returns the actual object with all the required meta values.

### What is the expected behaviour?
`getFormMeta` should work fine even if the form field is hidden with `display: none`

### What's your environment?
`"redux-form": "7.2.3"`

**Comment by gustavohenke** [comment]
That's probably not a redux-form issue.
Hidden elements can't be focused -- you didn't show your field implementation, but from your question I assume you must be spreading the `input` props on that hidden input.
