### ISSUE TITLE
Invariant Violation You must pass a component to the function returned by connect

### ISSUE THREAD

**Issue by wanggewg1** [erikras/redux-form#4388]

**Comment by wanggewg1** [comment]
in Redux form example:
https://codesandbox.io/s/MQnD536Km
If I change package.json to the following, I got this error:
Invariant Violation
You must pass a component to the function returned by connect. Instead received {"displayName":"ReduxForm","defaultProps":{"touchOnBlur":true,"touchOnChange":false,"persistentSubmitErrors":false,"destroyOnUnmount":true,"enableReinitialize":false,"keepDirtyOnReinitialize":false,"updateUnregisteredFields":false,"pure":true,"forceUnregisterOnUnmount":false,"form":"initializeFromState"}}

my package.json file is as the following:
{
  "name": "redux-form-initialize-from-state",
  "version": "1.0.0",
  "description": "Initialization From State Example using Redux Form",
  "keywords": [],
  "main": "index.js",
  "dependencies": {
    "react": "16.4.1",
    "react-dom": "16.4.1",
    "react-redux": "5.0.7",
    "redux": "4.0.0",
    "redux-form": "8.1.0",
    "redux-form-website-template": "0.0.41"
  }
}
Please help me out.

Best regards
Johnny Wang

**Comment by gustavohenke** [comment]
Make sure you use react-redux 6. Also remove the `redux-form-website-template` dependency, I'm afraid it isn't working with react 16/redux-form 8 yet.

**Comment by kurtt** [comment]
Thx @gustavohenke , it works with react-redux 6 !

**Comment by tbrisker** [comment]
For anyone from the future hitting this as well - looks like it was fixed in react-redux 5.1.0 with https://github.com/reduxjs/react-redux/commit/1b43eaa86d89144bfe2ef72db095f69bf7944cf2#diff-4a561361865a8e6d0758088bf7cded8dR92.

**Comment by luky1984** [comment]
I fixed it by upgrading "react-redux":  5.0.7 to  5.1.1

**Comment by ChocPanda** [comment]
@gustavohenke I think I am seeing the same error in react-redux 7.1.0. Is this a known regression?

**Comment by CodeMeNatalie** [comment]
@ChocPanda I don't know if this is regression but I found a solution though and described it here: [Link](codemenatalie.com/blog/connecting-redux-form-and-connect/). I hope it will help you fix and understand the problem 👍

**Comment by ChocPanda** [comment]
Thanks @CodeMeNatalie. That has helped, onto the next bug

**Comment by tanmay-cs13** [comment]
@CodeMeNatalie Will you please let me know the problem? The given link is not working.

**Comment by CodeMeNatalie** [comment]
@tanmay-cs13 it should be working again. Please [read the full description of how to connect redux form and connect](https://codemenatalie.com/blog/connecting-redux-form-and-connect/) :)

**Comment by tanmay-cs13** [comment]
@CodeMeNatalie Thank You for your reply.

We have figured out the problem it was related to the polyfill package for IE Browser.

**Comment by lostrowski-travelist** [comment]
Hi @tanmay-cs13 I've got similar issue reproducible only on IE11 and only locally, could you please let me know what was the issue with the polyfill that caused this problem in your case?
