### ISSUE TITLE
Is there a way to pass initial value inside the render function ? I pass 'value' property to Field

### ISSUE THREAD

**Issue by vishnukalakota** [erikras/redux-form#4394]
Help Required
Is there a way to pass initial value inside the render function ? I pass 'value' property to Field.

**Comment by airen29** [comment]
Good question, solution would also help me :)

**Comment by xStoneriderx** [comment]
Something like this?
`import React, { Component } from 'react';
import { change } from 'redux-form';

class ReduxFormInputContainer extends Component {
  componentDidMount() {
    const { defaultValue, meta } = this.props;
    if (defaultValue === undefined || meta.initial !== undefined || meta.dirty)
      return;
    const {
      meta: { form, dispatch },
      input: { name }
    } = this.props;
    dispatch(change(form, name, defaultValue));
  }
  render() {
    const { defaultValue, component: Compo, ...fieldProps } = this.props;
    return <Compo {...fieldProps} />;
  }
}

function reduxFormInputContainer(component) {
  return function(props) {
    return <ReduxFormInputContainer {...props} component={component} />;
  };
}

export default reduxFormInputContainer;
`

**Comment by Asday** [comment]
Am I right in thinking that would set `dirty === true`?  If so, that's no good, 'cause it breaks `enableReinitialize && keepDirtyOnReinitialize`.

**Comment by renatoagds** [comment]
@vishnukalakota You could pass initialValues to `reduxForm` HOC or as props to wrapped component.  So, if you want to pass initial values in render method, it needs to be in the render method of who's rendering the wrapped component (https://redux-form.com/8.2.2/docs/api/reduxform.md/#config-properties)

**Comment by Asday** [comment]
I would still like to be able to specify a default on a field, though...
