### ISSUE TITLE
It says Uncaught ReferenceError: dispatch is not defined

### ISSUE THREAD

**Issue by shreyaagarg** [erikras/redux-form#4396]
It says Uncaught ReferenceError: dispatch is not defined

Using it as this.props.dispatch gives error : - Cannot read property 'props' of undefined
_Originally posted by @dukedougal in https://github.com/erikras/redux-form/issues/622#issuecomment-180200525_

**Comment by gustavohenke** [comment]
That's an issue dating back from v5 times.
Just use [`this.props.change`](https://redux-form.com/8.1.0/docs/api/props.md/#-code-change-field-string-value-any-function-code-) directly these days.
