### ISSUE TITLE
Edit Form FieldArray with Mutliple Sections and Group Not Initializing

### ISSUE THREAD

**Issue by rasheedqadar** [erikras/redux-form#4403]
I have Data structure as bellow, with array of Sections and Group.
form{
	formName:"",
	...
	Sections[
			sectionName:"",
			...
			groups[
				groupName:""
			]
	]
}

Form is submitted successfully. But while editing the same Redux Form, form level attributes are initializing but sections and groups are not initializing in EDIT. 

Can anyone help me the solution for Edit, how we can initialize form with existing data. I have given the sandbox link for working Redux-Form example fieldArray, but I dont have bug sandbox.
https://redux-form.com/7.0.4/examples/fieldarrays/

Below Is code snippet on Edit.
***********************************************************************************************
componentDidMount() {

 const initData = {
	formName: this.props.loadData.form.name,
	formDescription: this.props.loadData.form.description,		
	sections: this.props.loadData.form.body.sections
 };
	this.props.initialize(initData);
 }
***********************************************************************************************

**Comment by gustavohenke** [comment]
Please head to StackOverflow for usage help. We don't do this on the GitHub issue tracker.
