### ISSUE TITLE
5.4.0 was marked as latest by mistake?

### ISSUE THREAD

**Issue by vkrol** [erikras/redux-form#4405]
### Are you submitting a **bug report** or a **feature request**?
Bug.

### What is the current behavior?
`5.4.0` is marked as `latest`.
```
$ yarn -s info redux-form dist-tags
{ latest:
   '5.4.0',
  rc:
   '8.0.0-0',
  old:
   '5.3.6',
  alpha:
   '7.0.0-alpha.9' }
```

### What is the expected behavior?
`8.1.0` is marked as `latest`.

### Sandbox Link
N/A.

### What's your environment?
N/A.

### Other information
N/A.

**Comment by gustavohenke** [comment]
Woops @erikras 😅

**Comment by erikras** [comment]
Oops.

[![docs](https://user-images.githubusercontent.com/4396759/55010612-cb180e80-4fe4-11e9-9106-d1607748ba43.jpg)](https://twitter.com/erikras/status/1110563993750593536)
