### ISSUE TITLE
React Native : after installed 5.4.0 , 8.1.0 version examples throws error

### ISSUE THREAD

**Issue by Nandha91** [erikras/redux-form#4407]
### Are you submitting a **bug report** or a **feature request**?

new version installed, 8.10 version examples not working throws  error (fields must be passed when ), even not working in ur official site

https://redux-form.com/8.1.0/examples/initializefromstate/

how to upgrade the form to new version, cant find new link or documentation

Pls reply ASAP

**Comment by Acnesense** [comment]
same to me  
when connect component with redux-form  
get the error **'Fields must be passed when initializing state'**

I don`t know why get this error

**Comment by ResioSoftware** [comment]
some to me, i get the error 'Fields must be passed when initializing state' too
i'm try use in web application

**Comment by erikras** [comment]
I messed this up. Sorry.

[![docs](https://user-images.githubusercontent.com/4396759/55010612-cb180e80-4fe4-11e9-9106-d1607748ba43.jpg)](https://twitter.com/erikras/status/1110563993750593536)

**Comment by Nandha91** [comment]
Thanks for the reply
