### ISSUE TITLE
Doc pages not opening.

### ISSUE THREAD

**Issue by mishsom** [erikras/redux-form#4408]
https://redux-form.com/8.1.0/examples/fieldlevelvalidation/

The page is not opening. There are other broken pages in the doc.

I can see the console as bloody red.
Uncaught Invariant Violation: Could not find "store" in either the context or props of "Connect(ReduxForm(b))". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(ReduxForm(b))".

Is there an alternate way I can access the docs till the issue is fixed.

**Comment by airen29** [comment]
@mishsom I do use https://redux-form.com/6.8.0/examples/fieldlevelvalidation/ till the problem is not fixed

**Comment by erikras** [comment]
Oops.

[![docs](https://user-images.githubusercontent.com/4396759/55010612-cb180e80-4fe4-11e9-9106-d1607748ba43.jpg)](https://twitter.com/erikras/status/1110563993750593536)

**Comment by gustavohenke** [comment]
Duplicate of #4410
