### ISSUE TITLE
getValues (getValuesFromState) returns `{touched: true}` if a field has no initial value.

### ISSUE THREAD

**Issue by latentflip** [erikras/redux-form#441]
If I have a form field, that I don't change while editing the form, and that has no initial value (or an undefined initial value). getValues as exported by redux-form (getValuesFromState) returns `{ touched: true }` instead of not setting that key at all.

It seems to happen because:

1. after initialize, the form is an empty object: `foo: {}`
2. after touch, the form is an object with `touched: true`: `foo: { touched: true }`
3. getValuesFromState, doesn't think it's a "value" field since it has no value property, so it hits this line: https://github.com/erikras/redux-form/blob/0b2b59ef93819f7f1f1e1c7ced852ccaa9683845/src/getValuesFromState.js#L22 which then ends up treating it like a nested object value.

Not sure where to handle this best? Trying to set a `value: undefined/null` during initialize, not sure if that'll work? Not setting `touched: true` in touch if there's no value? Checking `hasOwnProperty: touched` in this line: https://github.com/erikras/redux-form/blob/0b2b59ef93819f7f1f1e1c7ced852ccaa9683845/src/getValuesFromState.js#L22?

**Comment by latentflip** [comment]
Removing the conditional here: https://github.com/erikras/redux-form/blob/master/src/initializeState.js#L5 and changing it to `return { initialValue: value, value }` seems to fix it FWIW.

**Comment by latentflip** [comment]
> Not setting touched: true in touch if there's no value?

Just realised this won't work, as it'll just mean that we return an empty object, instead of undefined/no key set.

**Comment by latentflip** [comment]
Failing test (modifying src/__tests__/getValuesFromState.js)

```javascript
  it('should get simple values from state', () => {
    const state = {
      foo: {value: 'bar', touched: true},
      catLives: {value: 9, touched: true},
      alive: {value: true, touched: true},
      notSet: {touched: true}
    };
    expect(getValuesFromState(state))
      .toBeA('object')
      .toEqual({
        foo: 'bar',
        catLives: 9,
        alive: true
      });
  });
```

```patch
1) getValuesFromState should get simple values from state:

Error: Expected { alive: true, catLives: 9, foo: 'bar', notSet: { touched: undefined } } to equal { alive: true, catLives: 9, foo: 'bar' }
+ expected
- actual

 {
   "alive": true
   "catLives": 9
   "foo": "bar"
-  "notSet": {
-    "touched": [undefined]
-  }
 }

at Object.assert [as default] (node_modules/expect/lib/assert.js:20:9)
at Expectation.toEqual (node_modules/expect/lib/Expectation.js:69:26)
at Context.<anonymous> (src/__tests__/getValuesFromState.spec.js:14:8)

```

**Comment by erikras** [comment]
Excellent explanatory work here. I think it got fixed already. Look at the test I just committed. Isn't that the expected behavior?

**Comment by latentflip** [comment]
Test lgtm

**Comment by erikras** [comment]
lgtm == legitimate?

**Comment by latentflip** [comment]
Sorry, "looks good to me" ;)
