### ISSUE TITLE
Is there any way to hook fieldArray onChange?

### ISSUE THREAD

**Issue by kkseven07** [erikras/redux-form#4418]
I know there is feature to know when Field is changed. But I also need to hook when FieldArray is changed(items added/deleted). I asked on stackoverflow, but no one answered. So I guess it should be added as feature? If I'm wrong, tell the solution please.

**Comment by acollazomayer** [comment]
@kkseven07  did you find a solution for this?

**Comment by iamandrewluca** [comment]
#4531
