### ISSUE TITLE
Is that right that building project just only with Redux-form???

### ISSUE THREAD

**Issue by ZhaoTim** [erikras/redux-form#4424]
my workmate tells me :  he will build project only with Redux-form, there is no store , no reducer, no action.....He wants to put his data into initialValues, then anything with data ,he will wrapped width Field component .I just want to know ,is this right?

**Comment by gustavohenke** [comment]
Is it possible? Yeah, definitely.
But is it right? Maybe. Each project is different.

**Comment by ZhaoTim** [comment]
thank u , i think i got it！
