### ISSUE TITLE
Problem passing down fields in dynamic form

### ISSUE THREAD

**Issue by feesjah** [erikras/redux-form#443]
This is my component:
```
import React, {Component, PropTypes} from 'react';
import {reduxForm} from 'redux-form';

@reduxForm({
  form: 'problem'
})
export default class ProblemForm extends Component {
  static propTypes = {
    fields: PropTypes.object.isRequired,
    handleSubmit: PropTypes.func.isRequired,
    specs: PropTypes.array.isRequired
  }

  render() {
    const {handleSubmit, fields, specs} = this.props;
    const styles = require('./ProblemForm.scss');
    const fieldsarr = Object.keys(fields);
    console.log(fieldsarr);
    return (
      <div className={styles.problemform}>
        <form className="form-horizontal" onSubmit={handleSubmit}>
          {fieldsarr.map((name, index) => {
            return (<div className="form-group" key={index}>
              <label htmlFor={name} className="col-sm-2">{specs[index].label}</label>
              <div className={'col-sm-5 ' + styles.inputGroup}>
                <input type="text" className="form-control" placeholder={specs[index].placeholder} {...name} />
              </div>
            </div>);
          })}
          <div className="form-group">
            <div className="col-sm-offset-2 col-sm-10">
              <button className="btn btn-success" onClick={handleSubmit}>
                Volgende <i className="fa fa-chevron-right"/>
              </button>
            </div>
          </div>
        </form>
      </div>
    );
  }
}

```

my console log  from the parent component shows that I'm passing in this array:
["make", "model", "serialnr", "info"]
this is what redux forms shows (this is still ok):
["make", "model", "serialnr", "info"]
When I click on another item in the parent component, this is the new array of fields that i pass:
["number", "size", "info"] 
yet this is what i get in my redux form:
["make", "model", "serialnr", "info", "number", "size"]

So this causes some problems. Am I doing something wrong ? If so, how can I solve this ? 
Thanks in advance

**Comment by ooflorent** [comment]
This is a usage question, and we encourage you to ask it on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

This is the only way to ensure the same question doesn’t get asked many times in a row, and that folks who have the same question in the future will be able to find it.

I’m closing for these reasons.
