### ISSUE TITLE
Would it be possible to change a value that's in different form state?

### ISSUE THREAD

**Issue by SeongwoonHong** [erikras/redux-form#4433]
my redux state looks like this
form
  -- form1
  -- form2
  -- form3

when i am in a component that's connected to form1, can i change a value that's in form2 or form3?
I tried using this.props.onChange('some path', value) but seems like this only works in the current scope of where i am.
Help is appreciated.

Thank you

**Comment by gustavohenke** [comment]
You might want to use the [`change` action creator](https://redux-form.com/8.1.0/docs/api/actioncreators.md/#-code-change-form-string-field-string-value-any-code-)
