### ISSUE TITLE
Keyboard closing on every change event

### ISSUE THREAD

**Issue by MrSucik** [erikras/redux-form#4440]
### What is the current behavior?
https://youtu.be/fOANXyv9kmk

The video shows two fields as you can see in the code below. One is autoclosing keyboard and one is working correctly.

import React from "react";
import { reduxForm, Field } from "redux-form/immutable"; // <---- LOOK HERE

const renderInput = ({ input }) => <TextInput {...input} />;

const Form = () => {
  return (
    <View>
      <Field
        name="sampleinput"
        component={({ input }) => <TextInput {...input} />}
      />
      <Field
        name="sampleinput2"
        component={renderInput}
      />
    </View>
  );
};

export default reduxForm({
  form: "SimpleForm"
})(Form);

### What is the expected behavior?
Both fields should act the same

### What's your environment?
"react": "^16.6.0-alpha.8af6728",
"react-native": "^0.57.4",
"redux-form": "^8.1.0",

**Comment by gustavohenke** [comment]
https://github.com/erikras/redux-form/issues/1836#issuecomment-328293635
https://github.com/erikras/redux-form/issues/1836#issuecomment-335556963
