### ISSUE TITLE
Lose Focus after typing a character in input field using Functional Component

### ISSUE THREAD

**Issue by jtaalmasco** [erikras/redux-form#4452]
### Are you submitting a **bug report** or a **feature request**?

Bug Report

### What is the current behavior?

After I enter the first character then it loses focus in the input element. I'm currently using functional component but after I transformed it into class based component then it works as expected

### Sandbox Link

https://codesandbox.io/s/646xyzj85w

**Comment by gustavohenke** [comment]
Please have a look at this issue:
https://github.com/erikras/redux-form/issues/1836#issuecomment-328293635
