### ISSUE TITLE
FieldArray validate with Immutable broken in v8.2.0 (working in v8.1.0)

### ISSUE THREAD

**Issue by aertmann** [erikras/redux-form#4457]
### Are you submitting a **bug report** or a **feature request**?
bug report

### What is the current behavior?
https://codesandbox.io/s/93qk7187lw

Click "Add member"

See "TypeError: Invalid attempt to spread non-iterable instance" error in console

### What is the expected behavior?
No error

Switch redux-form from v8.2.0 to v8.1.0

Or add a member ({}) to the default value ``initialValues: fromJS({ members: [{}]})``

Regression of #4337

**Comment by tomasztomys** [comment]
+1

**Comment by dmason30** [comment]
duplicate #4439

**Comment by renatoagds** [comment]
Hi all! Made the revert of the PR that caused this problem. Will release a new version in the next few hours. :)

**Comment by erikras** [comment]
Published fix in [`v8.2.1`](https://github.com/erikras/redux-form/releases/tag/v8.2.1).
