### ISSUE TITLE
Initialize FormSection (or reset FormSection completely not to initialValues)

### ISSUE THREAD

**Issue by milebza** [erikras/redux-form#4472]
### Are you submitting a **bug report** or a **feature request**?
Feature request

### What is the current behavior?
I'm building a search page composed by a `Form` with several `FormSections`. The Form gets populated with the page's url parameters if there are any, so I'm setting the Form's `initialValues` depending on that.

In each `FormSection` there's a clear button in case the user wants to clear that section's filters.

The problem is that if the Form has `initialValues`, `resetSection` will reset to the `initialValues`. It won't clear the section. Using `initialize` could solve the problem but it only works at `Form` level and not at `FormSection` :/
I want to clear the `FormSection` completely every time the user clicks the clear button.

### What is the expected behavior?
Make it possible for the `resetSection` function to receive an argument that will state if it's to reset the `FormSection` to the `initialValues` or reset completely.
Or
Make it possible to use the initialize function at `FormSection` level.

### What's your environment?

Redux Form 7.4.2

**Comment by milebza** [comment]
Solved the problem by using `change(formSectionName, {})`.
As stated here: https://github.com/erikras/redux-form/issues/2239

The docs should be updated with this info :)

**Comment by renatoagds** [comment]
@milebza can you open a PR updating our docs for that?
