### ISSUE TITLE
Possible error in the last release

### ISSUE THREAD

**Issue by kutaloweb** [erikras/redux-form#4473]
Please fix:

```
Failed to compile
./node_modules/redux-form/es/handleSubmit.js
Module not found: Can't resolve 'immutable' in '/var/www/faithmo-dev/node_modules/redux-form/es'
```

It works for `"redux-form": "8.2.0"` but fails for `"redux-form": "^8.2.0"` in my project.

**Comment by Speedrockracer** [comment]
+1 Also experiencing this issue!

**Comment by renatoagds** [comment]
@kutaloweb thanks! taking a look 👍

**Comment by renatoagds** [comment]
Hi all! Something got wrong into build phase. We'll release a new version soon. I put a message into the release to warn about this version. Sorry for that

**Comment by erikras** [comment]
I saw that, too, in publishing the docs. Looking into it...

**Comment by erikras** [comment]
Yeah, so only _some_ of the consumers of this library use `immutable`, so the data control structures have been abstracted away into [two identical APIs](https://github.com/erikras/redux-form/tree/master/src/structure), one that uses `immutable` and one that uses plain objects.

**Comment by erikras** [comment]
@esetnik can you take another run at this?

**Comment by esetnik** [comment]
Looks like the issue is that immutable is listed as a devDependency in the project but I need to use the immutable library to check whether the fields passed into handleSubmit are immutable types. We can either move immutable to a direct dependency or we can manually pull the List.isList() function into the project itself.

**Comment by renatoagds** [comment]
Published fix in [`v8.2.3`](https://github.com/erikras/redux-form/releases/tag/v8.2.3).

**Comment by esetnik** [comment]
@kutaloweb can you please test #4476 and see if it fixes issues for you. I'm assuming your project does not have a dependency on [immutable](https://github.com/immutable-js/immutable-js).

**Comment by kutaloweb** [comment]
@esetnik v.8.2.3 works fine for me. Thank you!

**Comment by esetnik** [comment]
But v8.2.3 has broken immutable support so it doesn’t work for me. Can you test #4476?

**Comment by kutaloweb** [comment]
@esetnik Sorry, I have no idea how to merge this pull request to node_modules package or even change it manually. I've never created packages. I can only test it after this is merged to a new release or if I have good instructions.

**Comment by mariocoloma** [comment]
I'm still getting this warning running `v8.2.4`. Any ideas?

**Comment by iamandrewluca** [comment]
@kutaloweb @mariocoloma do you have `immutable` declared as a dependency in your `package.json` ?

**Comment by mariocoloma** [comment]
@iamandrewluca no, since we only make use `redux-form`

**Comment by iamandrewluca** [comment]
@kutaloweb do you use `redux-form/immutable` ?

**Comment by seangolob** [comment]
I am still getting this on `v8.2.6`. Can we re open this issue?
