### ISSUE TITLE
[Bug] cursor jumping to the end of the input

### ISSUE THREAD

**Issue by kopax** [erikras/redux-form#4480]
### Related issues:

- https://github.com/bootstrap-styled/ra-ui/issues/15

### What is the current behavior?

When typing in an input, the caret jump to the end

### What is the expected behavior?

We expect when typing in an input to keep the caret position

### What's your environment?

- Node: 11.9.0
- Npm: 6.9.0
- react: 16.8.6
- react-redux: 5.0.7
- react-router: 4.2.0
- redux-form: 7.4.2

### Other information

These issues also seems to be related but doesn't bring any kind of solution and are quite old:

- https://stackoverflow.com/questions/44307014/redux-form-cursor-jumping-to-the-end-of-the-input-field
- https://github.com/reduxjs/react-redux/issues/525#issuecomment-307742629
- https://github.com/erikras/redux-form/issues/1094
- https://github.com/moroshko/react-autosuggest/issues/403
- https://github.com/erikras/redux-form/issues/3253
- https://github.com/erikras/redux-form/issues/2049

We are having this error in a react-admin application, and have no clue where to dig, because this error comes a lot with a bunch of supposed fix that would fix over the time

**Comment by renatoagds** [comment]
@kopax can you confirm if the problem happens in the last version, please?

**Comment by kopax** [comment]
No, it does happen with redux-form 7.4.0. It is the latest version supported by [react-admin](https://github.com/marmelab/react-admin), and it will be replaced later with [react-final-form](https://github.com/final-form/react-final-form) due to all the bugs.

we have tried to investigate and it was impossible yet to found why this is happening.

**Comment by renatoagds** [comment]
@kopax Based on that, I'll close the issue, since it's not happening in the last version.

**Comment by kopax** [comment]
How are you sure.

**Comment by ChrisCraig68** [comment]
@renatoagds 
Yeah, this is definitely still an issue with the latest redux-form. You can even see it on the normalizing example in the redux-form docs.

https://redux-form.com/8.2.2/examples/normalizing/

Enter a number into the phone field. Then try and change a number, the caret will jump to the end of the input. This also happens in the "Shout" field in the docs.

It really makes Normalizing useless when any formatting is happening to the value as it causes pretty bad UX issues.

**Comment by kopax** [comment]
Seems to be happening on last version. We had to replace redux form in all our app. I do not recommend this lib it is the worst one to use for form. Better use vanillajs

**Comment by iamandrewluca** [comment]
Good luck! :slightly_smiling_face:
