### ISSUE TITLE
How to access and use a value from a child component on redux-form to make a checkbox work and enable conditionally rendered extra options

### ISSUE THREAD

**Issue by char502** [erikras/redux-form#4485]
I'm using redux-form. I need to conditionally render extra options on user click of a checkbox in a child component.

I am able to do this on the parent file (in the SOW Type section of the form) using 'formValueSelector' (see sandbox: https://codesandbox.io/s/currying-cloud-isu8c) but on the third option in this section ('Custom Professional Services SOW') on clicking the checkbox I need to further condionally render some options on clicking the new checkbox that is exposed inside ('Customised Professional Services').

The file containing the code for the child component is 'CustomProfExtOptions'. What code do I need in this child component and/or the parent component in order to get this nested checkbox to work/enable conditional rendering on checking the box

I understand I need to access the value of the field in this child component on the form in order to manipulate it's state (mapStateToProps?) and allow the conditional rendering to work. I have done this successfully in the parent (as the sandbox shows) but I don't know how to get his working in the child component.

I have googled extensively on this for three days and tried to tweak other examples I have found to fit this specific problem (the greyed out text at the bottom of 'CustomProfExtOptions.js' where the child component code is held) but I've yet to find anything that works.

What is working so far:

The 'formValueSelector' code (as per the Redux-Form docs which allows access the values in the fields of the form) I am using in the parent container for the form (a file called 'PdfGenFormContainerRedux.js') is as follows:

```
PdfGenFormContainerRedux = reduxForm({
  form: "StatementOfWorkApplication"
})(PdfGenFormContainerRedux);

const selector = formValueSelector("StatementOfWorkApplication");
PdfGenFormContainerRedux = connect((state) => {
  const hasProductSowValue = selector(state, "productSOW");
  const hasTeradataExtOptionsValue = selector(state, "teradata");
  const hasCustomProfExtOptions = selector(state, "customExtOptions"); //selector created

  return {
    hasProductSowValue,
    hasTeradataExtOptionsValue,
    hasCustomProfExtOptions
  };
})(PdfGenFormContainerRedux);
```

export default PdfGenFormContainerRedux;
This allows me to conditionally render the second hidden field on the click of the checkbox by using a variable called props.hasCustomProfExtOptions as demonstrated below:

```
<div className="checkbox-group">
        <div>
          <label className="checkbox-group">
            <Field
              name="customExtOptions"
              className="form-checkbox"
              component="input"
              type="checkbox"
            />
            Custom Professional Services SOW
            {props.hasCustomProfExtOptions && ( //conditional rendering bit here
              <div>
                <Field
                  name="custProfServices"
                  type="input"
                  component={CustomProfExtOptions}
                  label="Custom Options Info"
                  placeholder="Location"
                  formId={formId}
                  /* hasProfServ={props.hasProfServ} */
                />
              </div>
            )}
          </label>
        </div>
      </div>
    </div>
```
This works fine on the parent container but how do I get it working on the checkbox labelled 'Customised Professional Services' in the child component? (the file called 'CustomProfExtOptions')

Just to add, i need any input from this nested section to be included in the final submission of the form.

This may be a simple question and i may be missing something but after three days of tearing my hair out it would be helpful if someone could clear this up for me?

Any help would be greatly appreciated

**Comment by Asday** [comment]
The same way.  Wrap your child component in a `connect()` with its own selectors.

**Comment by char502** [comment]
YESSSS it's working!!

Put the below at the bottom of my child component and it now working as expected.

Turns out I was also selecting the wrong field name (the one inside the conditional part rather than the outer one doh!)

Thanks for your help Asday, much appreciated

```
CustomProfExtOptions = reduxForm({
  form: "StatementOfWorkApplication"
})(CustomProfExtOptions);

const selector = formValueSelector("StatementOfWorkApplication");
CustomProfExtOptions = connect((state) => {
  const hasProfServ = selector(state, "customTwoCheckbox"); // was selecting "custProfServiceTwo" instead of "customTwoCheckbox"
  return {
    hasProfServ
  };
})(CustomProfExtOptions);

export default CustomProfExtOptions;
```

**Comment by Asday** [comment]
My pleasure, Charlotte.  Good luck with your project.
