### ISSUE TITLE
Unicode regex support

### ISSUE THREAD

**Issue by prakashpsde** [erikras/redux-form#4491]
### What is the current behavior?
IE11 doesn't support unicode regex constructor. For ex: new RegExp('[^\\p{L}\\p{N}\\p{Zs}_\\-]', 'u') or /[^\p{L}\p{N}\p{Zs}_\-]/u throws an error.

### What is the expected behavior?
Supporting unicode regex constructor in IE11

### What's your environment?
Internet Explorer 11

**Comment by renatoagds** [comment]
@prakashpsde Sorry, but looks like a problem directly in your application and not in redux-form. Try to polyfill `RegExp` in your application.
