### ISSUE TITLE
Required Help initializing Cascading Drop-down

### ISSUE THREAD

**Issue by sushantraje2000** [erikras/redux-form#4493]
I am looking for sample code for initializing 3 parameters
Criteria (left operant), Operator and value(right operant)
I am trying to implement React Query builder with react redux form in which I have 3 fields 
Criteria drop-down having 
[{id: 1 name:'city' ,type'dropdown'},{id: 2 name:'something' ,type'listbox'}]
on change I am loading Operator drop-down
which need to load data from API 
also loading type of components like text box or select or anything

I need help to initialize state and trigger change event for criteria for binding other components and finally loading dynamic components text box text area

**Comment by gustavohenke** [comment]
Hi @sushantraje2000, this kind of question is better suited to StackOverflow.

And since it will be helpful to ask there with some sample code: try using the `Fields` component, which should give you control over what happens to operator/value when criteria is changed.

**Comment by sushantraje2000** [comment]
will fields onchange event get auto trigger on initial state?
