### ISSUE TITLE
connect each child from children to reduxForm

### ISSUE THREAD

**Issue by acollazomayer** [erikras/redux-form#4495]
Hi I am trying to connect each component from the children prop dynamically to reduxForm. However this is not working.
```
renderSlides = () => {
    const { children } = this.props;
    return children.map((child, form) => {
      const Slide = reduxForm({ form })(React.cloneElement(child));
      return <Slide />;
    });
  }
```

I get this error Invariant Violation: Element type is invalid: expected a string or a class/function but got object.

Thanks

**Comment by gustavohenke** [comment]
Yeah, this happens because `child` at that point isn't a component (it's a node), and it should be.

This however doesn't look like a good idea. E.g. you will be creating new components and remounting each form every time the parent component re-renders.

Can you simply wrap them elsewhere?

**Comment by acollazomayer** [comment]
@gustavohenke I was wrapping them, however I encounter an issue that when i conect the parent to redux and pass an array as a prop all the reduxForms generated where provoking the parent to re-render till it crash.

**Comment by acollazomayer** [comment]
@gustavohenke Also I need this because this way I can handle onSubmitSucceed prop and can go to the next slide
