### ISSUE TITLE
Validation state in store

### ISSUE THREAD

**Issue by vkrol** [erikras/redux-form#45]
Hello!

Please, can you help me? I want to store the form validation state in the form reducer. How I can do this?

**Comment by erikras** [comment]
That's an anti-pattern. The general rule of thumb for Redux, and React in general, is:

##### If you can calculate it from the state, don't store it in the state.

The less state the better.

If you want to do it anyway, you'll need your own Redux reducer, [much like how this form keeps `saveError` separate](https://github.com/erikras/react-redux-universal-hot-example/blob/master/src/components/WidgetForm.js#L8-L19), to keep it. This library isn't going to support keeping validation state in the store.

**Comment by vkrol** [comment]
Thanks. But what if I need to show the form validation state (valid/invalid) in an another component?

**Comment by erikras** [comment]
Two options:

* `connect()` to the form data and `import` and run your validator in the other component.
* Just `connectReduxForm()` in the other component and read the props. It doesn't matter how many components connect to the same form.

**Comment by erikras** [comment]
#49 will help with this when it gets implemented.

**Comment by vkrol** [comment]
Thanks. So if I have async validation and i will connect two components to the same form, then the asynchronous validation will be performed twice?

**Comment by erikras** [comment]
Good question. No, the async validation will only be fired when the `BLUR` action is sent, so as long as you are only sending it from one of the components (which is necessarily the case), the async validation will only happen once, but will be displayed (available to) both components. Make sense?

**Comment by vkrol** [comment]
Thanks!

**Comment by anatoliyarkhipov** [comment]
Sorry, I still not understand.

Following the discussion, if I have two components which want to know about the validation state, then I should connect them both to the form and should pass the same validation function to `connectReduxForm`. Is it correct?

If it is, then it means, that the validation function will be called twice, during rendering of the first and the second components. How to avoid this?

**Comment by erikras** [comment]
@anatoliyarkhipov Your validation function should be quite fast, but if it isn't, then [memoize it](https://github.com/erikras/lru-memoize).
