### ISSUE TITLE
Deprecated lifecycle hooks are being used in redux-form

### ISSUE THREAD

**Issue by beqaweb** [erikras/redux-form#4510]
#### The issue:
Both componentWillReceiveProps and componentWillMount are deprecated and will be removed from the next major release of React while they are being used by Field, Form.

#### What is the current behavior?
Currently, react native shows yellow box warnings and it is very annoying having to dismiss those warning every time.
<img width="340" alt="Screen Shot 2019-07-23 at 11 38 46 AM" src="https://user-images.githubusercontent.com/9969713/61697557-29a98b00-ad40-11e9-8078-a39b48e790d5.png">

#### My environment
I'm using redux-form@^8.2.4 (react-native@0.60.3)

### The question is, are those lifecycle hooks going to be replaced with right api's provided by new react?
Because, I guess in the future, after those hooks will be removed from react, I will get errors from redux-form like "componentWillReceiveProps is not a function" or something similar.

Thanks for providing such a nice form library. Looking forward for your respond.

**Comment by vaclavnovotny** [comment]
Shall I send PR with all deprecated lifecycle methods renamed to `UNSAFE_...`, this will at least silences the warnings.

**Comment by tomek-f** [comment]
> Shall I send PR with all deprecated lifecycle methods renamed to `UNSAFE_...`, it will at least silence the warnings.

Yes, please :)

**Comment by renatoagds** [comment]
Published in [`v8.2.6`](https://github.com/erikras/redux-form/releases/tag/v8.2.6).
