### ISSUE TITLE
unable to change the input value (formatted value) while type

### ISSUE THREAD

**Issue by psaravanan** [erikras/redux-form#4515]
My "redux-form" npm version is 8.2.4 and I am trying to update the formatted value while user type into textbox but I am unable to update the formatted text, below is my code,

```tsx
<Field
  name="card_no"
  type="text"
  placeholder='Enter Card Number'
  component='input'
  label="Card Number"
  onChange={props => {
    this.props.change('card_no', "1234 5678 9876 5432")
  }}
/>
```

**Comment by psaravanan** [comment]
Got an answer :)
Early I tried on onChange event that's why I am unable to achieve, now I tried in onKeyUp event,

<Field
                            name="card_no"
                            type="text"
                            placeholder='Enter Card Number'
                            component='input'
                            label="Card Number"
                            onKeyUp={(e) => {
                                    this.props.change('card_no', '1234 5678 9876 5432')
                                }
                            }
/>

**Comment by iamandrewluca** [comment]
If you just want to get the value from field, you can use [onChange](https://redux-form.com/8.2.2/docs/api/field.md/#-code-onchange-event-newvalue-previousvalue-name-gt-void-code-optional-) only.  
If you want to put that formatter value back into input, you should take a look at [parse](https://redux-form.com/8.2.2/docs/api/field.md/#-code-parse-value-name-gt-parsedvalue-code-optional-), [format](https://redux-form.com/8.2.2/docs/api/field.md/#-code-format-value-name-gt-formattedvalue-code-optional-), and [normalize](https://redux-form.com/8.2.2/docs/api/field.md/#-code-normalize-value-previousvalue-allvalues-previousallvalues-name-gt-nextvalue-code-optional-)

If you solved your problem please close this issue.

**Comment by iamandrewluca** [comment]
@psaravanan solved your problem?

**Comment by iamandrewluca** [comment]
I'll close it for now.
