### ISSUE TITLE
componentWillUpdate and componentDidUpdate cause infinite loop when redux form action creators dispatched within them.

### ISSUE THREAD

**Issue by F-Adam-B** [erikras/redux-form#4516]
### Are you submitting a **bug report** or a **feature request**?
bug report

### What is the current behavior?
After upgrading to React 16 and redux-form V8+, action creators dispatched in componentWillUpdate, or the newer preferred lifecycle method componentDidUpdate, cause a infinite loops, even when a conditional is supplied.

### What is the expected behavior?

the change action creator should update the redux form field accordingly.

I'm attempting to perform a calculation across multiple redux form upon before the component is rendered. If the user selects 'grid' from the drop-down, the calculation is performed and the field values are updated. Before I would run the calculation method when using ```if(thetaDistribution === 'grid') { calculate() } ``` using componentWillUpdate(). 

After upgrading I understand why this might cause an infinite loop because if the thetaDistribution remains grid it would recalculate. Now when I use componentDidUpdate(), or componentWillUpdate(), and the conditional if(thetaDistribution === 'grid' && nextProps.thetaLowerBound !== this.props.thetaLowerBound) (one of the input fields I use to calculate) it loops infinitely. 

### Sandbox Link
https://codesandbox.io/embed/redux-form-template-jhrn7?fontsize=14

Select 'grid' in the dropdown and the page will break due to the infinite loop.

### What's your environment?
```
{
  "name": "redux-form-template",
  "version": "1.0.0",
  "description": "",
  "keywords": [],
  "homepage": "https://codesandbox.io/s/gJjDoKYWl",
  "main": "index.js",
  "dependencies": {
    "react": "16.8.6",
    "react-dom": "^16.8.6",
    "react-redux": "^6",
    "redux-form": "^8.2.0",
    "redux": "^4.0.1"
  }
}
```
iOS

**Comment by iamandrewluca** [comment]
> After upgrading to React 16 and redux-form V8+, action creators dispatched in componentWillUpdate, or the newer preferred lifecycle method componentDidUpdate, cause a infinite loops, even when a conditional is supplied.

Sorry but this is not true. Your example is not written correctly. You did a wrong export from `dataHandlers.js`
```
MyForm.js? [sm]:42 Uncaught TypeError: (0 , _dataHanders2.default) is not a function
    at MyForm.calculateThetaPointsAndTestTakers (VM1792 MyForm.js:98)
    at MyForm.componentWillUpdate (VM1792 MyForm.js:79)
    at updateClassInstance (react-dom.development.js:11694)
    at updateClassComponent (react-dom.development.js:14694)
    at beginWork (react-dom.development.js:15644)
    at performUnitOfWork (react-dom.development.js:19312)
    at workLoop (react-dom.development.js:19352)
    at HTMLUnknownElement.callCallback (react-dom.development.js:149)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:199)
    at invokeGuardedCallback (react-dom.development.js:256)
    at replayUnitOfWork (react-dom.development.js:18578)
    at renderRoot (react-dom.development.js:19468)
    at performWorkOnRoot (react-dom.development.js:20342)
    at performWork (react-dom.development.js:20254)
    at performSyncWork (react-dom.development.js:20228)
    at batchedUpdates$1 (react-dom.development.js:20443)
    at batchedUpdates (react-dom.development.js:2151)
    at dispatchEvent (react-dom.development.js:4905)
calculateThetaPointsAndTestTakers @ MyForm.js? [sm]:42
componentWillUpdate @ MyForm.js? [sm]:23
updateClassInstance @ react-dom.development.js:11694
updateClassComponent @ react-dom.development.js:14694
beginWork @ react-dom.development.js:15644
performUnitOfWork @ react-dom.development.js:19312
workLoop @ react-dom.development.js:19352
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
replayUnitOfWork @ react-dom.development.js:18578
renderRoot @ react-dom.development.js:19468
performWorkOnRoot @ react-dom.development.js:20342
performWork @ react-dom.development.js:20254
performSyncWork @ react-dom.development.js:20228
batchedUpdates$1 @ react-dom.development.js:20443
batchedUpdates @ react-dom.development.js:2151
dispatchEvent @ react-dom.development.js:4905
sandbox.9b5dc6d7.js:1 The above error occurred in the <MyForm> component:
    in MyForm (created by Form(MyForm))
    in Form(MyForm) (created by Context.Consumer)
    in Connect(Form(MyForm)) (created by Connect(Form(MyForm)))
    in Connect(Form(MyForm)) (created by ReduxForm)
    in ReduxForm (created by Context.Consumer)
    in Hoc (created by ReduxForm)
    in ReduxForm (created by Context.Consumer)
    in Connect(ReduxForm) (created by App)
    in Provider (created by App)
    in App
```

**Comment by F-Adam-B** [comment]
Oh you're right. Apologies, saw the page crash and figured it was reoccurring due to the loop. It's working in the sandbox and must be unrelated to redux-form.
