### ISSUE TITLE
componentWillMount, componentWillReceiveProps, componentWillUpdate have been renamed and are deprecated

### ISSUE THREAD

**Issue by tonysepia** [erikras/redux-form#4524]
### What is the current behavior?
react-dom.development.js:12029 Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details

### What is the expected behavior?
redux-form should ideally use non-deprecated methods

I am sure everyone is aware, but just wanted to open this formally, to register that changes may need to be made for future-proofing this wonderful component. Thanks!

**Comment by kelly-tock** [comment]
would a patch for ^5 be accepted with the code mod run on it to rename to unsafe?  would like to install from npm rather than fork this. we're not able to upgrade just yet.

**Comment by kelly-tock** [comment]
@renatoagds saw you just did this. if I did a rename for an older version, would we put a minor release out for it?

**Comment by renatoagds** [comment]
@kelly-tock yep! go ahead :)

**Comment by renatoagds** [comment]
@tonysepia We already release a version with this lifecycles renamed. If you're using an older version, you could go with @kelly-tock and open a pull request for it.
