### ISSUE TITLE
AsyncBlur Validation unhandled exception error when submit

### ISSUE THREAD

**Issue by acollazomayer** [erikras/redux-form#4536]
### What is the current behavior?
When press on onSubmit, the Async Validations run but I get an unhandled exception error.

### What is the expected behavior?
Run async validations before submiting and throw the errors in the form.

### What's your environment?
Redux form 8.2.2

**Comment by iamandrewluca** [comment]
@acollazomayer can you please provide a sandbox with the bug, or provide some code? we can't help you without any context.

**Comment by acollazomayer** [comment]
I can provide some code yes,

```
onSubmit = (values, dispatch, { registeredFields }) => {
    const { addMember } = this.props;
    const member = pick(values, ...Object.keys(registeredFields));
    addMember(normalize(member));
  }
```
```
addMember = (member) => {
    const { fields } = this.props;
    fields.push(member);
  }
```

```
export default compose(
  reduxForm({
    form: FORM,
    onSubmitSuccess: (result, dispatch, { componentId }) => {
      dismissModal(componentId);
    },
    asyncValidate: userValidation,
    asyncBlurFields: ['email'],
    enableReinitialize: true,
  }),
  connect(state => ({
    memberType: formValueSelector(FORM)(state, 'memberType'),
  })),
)(FamilyMember);
```

```
const userValidation = ({ email }) => new Promise((resolve, reject) => {
  apiV2.users.list({ email })
    .then(() => resolve())
    .catch(({ json: users }) => !isEmpty(users) && reject({ email: 'Email is already taken' }))
});
```

**Comment by acollazomayer** [comment]
@iamandrewluca I saw that if I do this,
```
onPress={() => {
  handleSubmit().catch(() => {});
}}
```

it works. But I feel that is like a hack

**Comment by iamandrewluca** [comment]
Try to make `catch` like this
```js
.catch(({ json: users }) => !isEmpty(users) && reject(new SubmissionError({ email: 'Email is already taken' })))
```

**Comment by acollazomayer** [comment]
@iamandrewluca Tried that but throwing the submission error dont show the error in the form

**Comment by iamandrewluca** [comment]
@acollazomayer would be better if you can create a codesandbox example with this problem.

**Comment by renatoagds** [comment]
@acollazomayer could you help us with the codesandbox example? with that we could more assertive in fix this.
