### ISSUE TITLE
Bug in only-numbers field validation

### ISSUE THREAD

**Issue by Daniela0106** [erikras/redux-form#4538]
**bug report**

### What is the current behavior?
https://redux-form.com/6.6.1/examples/fieldlevelvalidation/
As you see on the official documentation above ^ "Age" field, letter 'e' can be typed. Which is wrong.

There is an issue with the field itself. Not even a regex for only numbers can prevent the letter 'e' from being a valid input for the field

### What is the expected behavior?
That field is supposed to hold only numbers.

**Comment by iamandrewluca** [comment]
https://stackoverflow.com/a/31706796/4671932

**Comment by Daniela0106** [comment]
Thanks @iamandrewluca ! Do you know if there is a workaround this very lovely "feature"? I truly have tried it all to make the 'e' not be an entry...

**Comment by iamandrewluca** [comment]
see this answer https://stackoverflow.com/a/54163655/4671932
