### ISSUE TITLE
performance on large forms

### ISSUE THREAD

**Issue by rhythnic** [erikras/redux-form#454]
I've read the closed issues related to performance, but I've tried following the advise in those and I still have a problem, so I opened a new issue.

I'm using Redux Form for a work project and the nature of the data I'm dealing with is that the payload consists of about 50 fields in total, grouped into about 7-10 nested fieldsets that I'm writing according to the deep form example.

I'm not using redux dev tools.  Originally there was a very noticeable delay.  If I typed a word quickly, it might take about 1 second for the whole word to render.  I then started using shouldComponentUpdate on the nested entities, like address.
```
shouldComponentUpdate(nextProps) {
  return nextProps.value !== this.props.value;
}
```

That helped a lot, so now the form is usable, but there's still a small delay.

I've also swapped
```
<input {...myProp} />
```
to
```
<input value={myProp.value} onChange={myProp.onChange} />
```
for all text fields.  That helped a little too, but there's still a stutter when typing.

Is there anything else that I could do to make the typing smoother?

**Comment by kristian-puccio** [comment]
I wonder if you could add a debounce function to the onChange
https://lodash.com/docs#debounce ?

Though it is a controlled component so maybe you wouldn't see your typing...

**Comment by rhythnic** [comment]
@kristian-puccio  excellent suggestion.  That did the trick.

I made an input wrapper that keeps state locally and forwards changes via a debounced this.props.onChange.

```
import {Component} from 'react';
import {TextField} from 'material-ui';

class TextFieldWrapper extends Component {

  constructor(props) {
    super();
    this.state = {};
  }

  componentWillMount(props) {
    this.forwardChange = _.debounce(this.props.onChange, 300);
  }

  onChange(evt) {
    this.setState({value: evt.target.value});
    this.forwardChange(evt);
  }

  render() {
    return <TextField {...this.props} onChange={this.onChange.bind(this)} value={this.state.value} />
  }
}

export default TextFieldWrapper;
```

Thanks for the advice.

**Comment by erikras** [comment]
More debounce discussion in #41.

**Comment by rhythnic** [comment]
I ended up ditching the debounce method because the form was much more performant in production mode, also the debouncing interfered with the ability to initialize/reset the form.

**Comment by GlebDolzhikov** [comment]
use this part of code to optimize performance, thanks to author, also need to add  evt.persist(); to use event object in async way.
