### ISSUE TITLE
access app state within reducer.plugin slice

### ISSUE THREAD

**Issue by arolson101** [erikras/redux-form#456]
I have a select box in my form; its values are indices into a global state array.  I'd like to write a reducer.plugin to do things based on the select's value, but the state passed into my reducer is just the form slice.  How can I access the rest of the app state?  It's just for reading.

**Comment by frost555** [comment]
You can call Store.getState() to get the state.

**Comment by arolson101** [comment]
It requires having access to a global store, which is something I was avoiding.

I also found that in the plugin reducer the select's value had already changed (that is, the state passed in is the new state after the change action) which isn't incorrect, but sucks if you need to know the previous value.

I ended up overriding the select's onChange to do the logic before calling the field's onChange.  This way I'm within the form component and thus have access to everything I need.  It's not very clean but it avoids any hacks and keeps things encapsulated.
