### ISSUE TITLE
_error in initialValues

### ISSUE THREAD

**Issue by Ericat** [erikras/redux-form#457]
Hi there,

apologies for this, but I am new to redux-form and redux in general and I don’t understand what I am doing wrong. I am trying to pass the result of a server-side error to a component wrapped in a redux-form, through `initialValues`. My `reduxForm({})` looks like this:

```
export default reduxForm({
    form: 'user',
    fields
  },
  state => ({ initialValues: state.userReducer.user}),
  userActions.loadUser()
 )(UserForm);
```
My `state.userReducer` is composed by an object `user` and a string `error`, that gets returned in case the action fails. I have tried passing the error down via an extra field on the `user` called `_error`, but it doesn’t work.

This is what I usually do in a redux component (not a redux-form):

```
function mapStateToProps(state) {
  const { users, error } = state.userReducer;
  return { users, error };
}
export default connect(mapStateToProps)(Users);
```

So that, in case the action LOAD_USERS_FAILURE —> reducer returns an error (for example a 500 or a 401), I will pass it down to my component via `this.props.error`. 
I have tried something similar (see above), but I have no idea how to retrieve it in the render(). Thank you.

**Comment by abachuk** [comment]
Not sure if it answers your question. But it's related to this one
https://github.com/erikras/redux-form/issues/163

You can still do the way you did it before 

```
function mapStateToProps(state) {
  const { users, error } = state.userReducer;
  return { users, error };
}

UserForm = reduxForm({
    form: 'user',
    fields
 })(UserForm);

export default connect(mapStateToProps)(UserForm);
```

now you should be able to access `this.props.error` which was imported from `state.userReducer`

**Comment by Ericat** [comment]
@abachuk I somehow was not able to access `this.props.error` in the form. However, in the end I have realised I don't need to pass it to the form itself, but to the component that is wrapping the form.
Thanks!! I will close this
