### ISSUE TITLE
give priority to async validation?

### ISSUE THREAD

**Issue by frost555** [erikras/redux-form#459]
Hello. My example is captcha field that has required synchronous validation.
When i submit wrong captcha value - i get error from server and set error with "stopAsyncValidation" action.
Problem arises when i reset field value (because captcha picture changes on error). I'm doing it through redux-form plugin api. After that, synchronous validation message appears - "Field is required", but i would like to display "Captcha is wrong" that i got from server.

Any help please?

Right now i just disabled synchronous validation, but maybe i could combine sync+async validation and value reseting.

**Comment by ooflorent** [comment]
This is a usage question, and we encourage you to ask it on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

This is the only way to ensure the same question doesn’t get asked many times in a row, and that folks who have the same question in the future will be able to find it.

I’m closing for these reasons.
