### ISSUE TITLE
Possible to specify initialValues for deep form objects?

### ISSUE THREAD

**Issue by nathanielkornet** [erikras/redux-form#462]
I'm wondering if it's possible to specify initial values for specific fields in deep form objects. Using the following syntax does not accomplish what I am hoping to achieve (the values I try to specify are undefined when a new field is added). The goal here is to specify that a user's age is 27 anytime I add a new user.

```javascript

const fields = {
  'users[].name',
  'users[].age'
}
const initialValues = {
  users: [],
  'users[].age': 27
}
```
I would then pass ```users``` to a component which handles the addition and removal of user fields. The following method call... 

```javascript
users.addField({name: 'John'})
```

...will create an object that looks like this:

```javascript
[
 {
  name: 'John',
  age: undefined
 }
]
```

Am I just handling this wrong? I can certainly specify these defaults elsewhere and pass them into ```addField()``` as needed, but it would be great to be able to keep this logic within ```initialValues```.

**Comment by dlmanning** [comment]
I'm curious about this too. Is there supposed to be a way to initialize values in deep fields?

**Comment by erikras** [comment]
The initial values are in the same shape as the values you want out of the form. See example test committed above. Does that help?

**Comment by dlmanning** [comment]
@erikras : That will initialize the array with one subform(?) with the given values. What if one wanted any newly created subform to take on default values? Could we do something like:

`'users[].age': 27`

Does that make sense?

**Comment by erikras** [comment]
Ah, sorry. No. You'll have to pass them into `addField()` like you said in your original post. I had not considered this use case.

**Comment by dlmanning** [comment]
Yeah. I get that it messes everything up that those fields don't exist when the initialization action is fired. In our application we have a form that manages a variable number of subforms that are added or removed dynamically in response to a UI interaction elsewhere in the application. So our top level form is really just a shell for the dynamically added subform "children". It's odd.

I'd be happy to work on a PR if you think there's a natural way to handle the use case.

**Comment by erikras** [comment]
Thanks for the offer, but I don't think I'm quite ready to add that to the API just yet. We'll see if many others request similar features. For now, the rule is "you've got to use `addField(defaultValues)`".

**Comment by lauterry** [comment]
Hello

If I understood, you have to call ```addField(defaultValues)``` to initialize array fields values right ?

What is the best place to call ```addField(defaultValues)``` then ?

Best regards
