### ISSUE TITLE
Add ability to reorder deep array items.

### ISSUE THREAD

**Issue by Deiru2k** [erikras/redux-form#465]
I have an array, defined in fields like `array[].key1, array[].key2`.
Besides the usual operations on nested fields, I also need an ability to re-order items in array in a way I see fit.
Right now, I'm doing this using value copying and then doing `removeField(oldIndex)` `addField(item, newIndex)`, but `addField` behavior is very strange on me.
Instead of re-initializing nested values with values provided to `addField`, it adds a new item in the provided index, with only a field called `value` containing values object I have passed to `addField`.
I suggest either fixing this, or adding an explicit method called `reorder` that would accept old and new indexes for re-ordering.
Also, removing element from array somehow does not update form state, and form remains pristine.

**Comment by flaub** [comment]
Related to #391

**Comment by erikras** [comment]
There is a `swapFields(indexA, indexB)` function, but if you're doing complex sorting, that is potentially a lot of actions to dispatch for every swap.

I'll consider some sort of remapping option, but it might require thunk middleware...

**Comment by ooflorent** [comment]
See https://github.com/erikras/redux-form/issues/386#issuecomment-215758323
