### ISSUE TITLE
Dynamic form with dynamic validation

### ISSUE THREAD

**Issue by altaihero** [erikras/redux-form#466]
I am trying dynamic form with dynamic validation. Can i make validate from component props ?

**Comment by mauriciosoares** [comment]
I'm interested in this as well... :)

**Comment by jamesbillinger** [comment]
I store an array (formFields) of objects with 'field' properties - type, name, value, etc.  One property is 'required'.  This is how I do the validation:

```
const FormValidation = data => {
  const errors = {};
  errors.formFields = [];
  data.formFields.map((ff,fi) => {
    if (ff.required && !ff.value) {
      errors.formFields[fi] = {value: 'Required'};
    }
  });
  return errors;
};
```

I'm sure it could be fancily re-written with a reduce statement...this is much more readable IMO.

Hope that helps.

**Comment by altaihero** [comment]
thank you reply

**Comment by oyeanuj** [comment]
@jamesbillinger Could you provide a little more context on the usage of your code snippet? It might just be me, but I wasn't sure how it allowed one to use a component prop in the validation function?

**Comment by erikras** [comment]
@oyeanuj I can't tell what you're referencing, but `props` is the second parameter to `validate()`.

**Comment by jamesbillinger** [comment]
@erikras, I didn't know that...so I could do this?

```
const FormValidation = (data, props) => {
  const errors = {};
  return errors;
};
```

Very cool.

@oyeanuj, I am referencing `ff.required` in the above code - that is how I interpret using component props to validate.  Maybe that's not quite what you mean.  In my case, I have a "formtemplate" database model that allows the definition of dynamic fields:

```
formFields: [{
    name: { type: String },
    createText: { type: String },
    type: { type: String },
    required: { type: Boolean },
    step: { type: Number },
    order: { type: Number },
    style: { type: String },
    fieldOptions: { type: String }
}]
```

I create a form from the form template, and the formFields array is passed in to the "form form" as you would expect:

`'formFields[]._id', 'formFields[].value', 'formFields[].name', 'formFields[].step', 'formFields[].order', 'formFields[].required', 
      'formFields[].type', 'formFields[].createText', 'formFields[].style', 'formFields[].fieldOptions'`

With this, I can 'require' certain fields, but I can also reference `type` for more advanced validation (number, phone, currency, etc).

**Comment by lauterry** [comment]
Hi

Given the following config: 
```
const reduceFormConfig = {
	form: 'myform',
	fields: ['name', 'age', 'address'],
	validate: (values, props) => {
		if (props.type === "flightWithHotel") {
			return validateAddressOnly(values, props);
		}
		return validateAll(values, props);
	}
};
```

If ```type === flightWithHotel``` then I use ```validateAddressOnly```.

However, when the props.type changes, redux-form still use ```validateAddressOnly``` instead of validating all my field.

I can't see how to resolve this use case.

Best regards
