### ISSUE TITLE
Unexpected behaviour on removing nested field

### ISSUE THREAD

**Issue by svsool** [erikras/redux-form#467]
hi, redux-form version 4.0.5
I have field "urlParams" and child fields "name" and "value", when I pass initialValues, form correctly initialized and all is ok, but if I try remove child fields param1:value1 it will be replaced with fields param2:value2, expected only first child fields will be removed

http://codepen.io/anon/pen/rxMrdp

![untitled](https://cloud.githubusercontent.com/assets/1452141/12007407/0ce5d388-ac14-11e5-9f5c-edfa9e3ca913.gif)
another case, try to delete old field after add new field, but redux-form remove new field
![untitled](https://cloud.githubusercontent.com/assets/1452141/12007452/0d05ecac-ac16-11e5-9dd1-a60e5063df9a.gif)

**Comment by svsool** [comment]
This bug caused by field defaultValue, when we add new field, it has undefined value, but this chunk of code https://github.com/erikras/redux-form/blob/master/src/readField.js#L36-L53 not override defaultValue while replace old fields with new ones on removing, it's only replace value, pristine, etc... by calling updateField and don't keep in mind that we must remove old defaultValue

workaround: remove defaultValue of field if field.pristine === false

**Comment by svsool** [comment]
fixed in 4.1.0

**Comment by svsool** [comment]
this problem still exist in 4.2.0

**Comment by ousiri** [comment]
It seems like a React problem. This can be fixed by adding a value to `addField`
```
urlParams.addField({name:'', value:''});
```

**Comment by svsool** [comment]
thanks, that works
