### ISSUE TITLE
Clarify submit validation with action creators and XHR calls

### ISSUE THREAD

**Issue by oyeanuj** [erikras/redux-form#469]
Hi @erikras! Thanks for your great work on this and the universal-boilerplate, both of which I am using!

Maybe this is a n00b question but having gone through the documentation and searching for issues, it wasn't clear how to act based on server response when -
1. form is submitted
2. using an action creator
3. which makes the call to the server

Here is the code to my handleSubmit and actionCreator (following the style of the boilerplate). I can't figure out how to have the errors show up in the form itself.

More importantly, the flow of 
*start-submit -> promise reject/resolve -> stop-submit -> add to errors in the form*
isn't that clear from the documentation and I would love to understand that better.

Any help and clarification would be much appreciated, as I am sure this is a common case for us newbies.

**actionCreator**
    
```javascript
export function addRequest(userId) {

	return {
		userId: userId,
		types: [
			SUBMIT_FORM_REQUESTED,
			SUBMIT_FORM_REQUEST_SUCCESS,
			SUBMIT_FORM_REQUEST_FAIL
		],
		promise: (client) => client.post('/add_requests/', {
			data: {
				"add_request": {
					"user_id": userId
				}
			}
		})
		.then(response => normalize(response, requestSchema))
	};

}
```

**Form Component's `handleSubmit`**
```javascript

handleSubmit = (data) => {

	return new Promise((resolve, reject) => {
		return this.props.addRequest(
			data.userId
		)
		.then((action) => {
		
			if (action.type === SUBMIT_FORM_REQUEST_SUCCESS) {
				resolve();
			}
			else if (action.status === SUBMIT_FORM_REQUEST_FAIL) {
				reject({ _error: action.error });
			}
		})
		.catch((error) => {
			reject({ _error: error });
		});
	});
}

Thanks again for your work on these libraries!

**Comment by drouillard** [comment]
@oyeanuj have you looked at the submit validation example? It has submit / async validation / showing errors in the form.

http://erikras.github.io/redux-form/#/examples/submit-validation

Full source is on the gh-pages branch

https://github.com/erikras/redux-form/blob/gh-pages/src/examples/SubmitValidationForm.js
https://github.com/erikras/redux-form/blob/gh-pages/src/redux/modules/submission.js

Would the above flow work?

**Comment by erikras** [comment]
@oyeanuj If you are using the client middleware from the universal-boilerplate, dispatching the action will return a promise already.

```js
handleSubmit = (data) => {
  return this.props.addRequest(data.userId)
    .then(result => {
      // do something if you wish
    }, error => {
      return {_error: error};
    });
}
```
