### ISSUE TITLE
mocha test script failing on windows, file pattern matching issue

### ISSUE THREAD

**Issue by alecperkey** [erikras/redux-form#470]
Hello,

Seems the quotes are breaking the test script in my environment (Win7, Node:4.2.4, NPM:3.5.2 ). Works fine after removal. Maybe I am the only one using windows?

Documented here: 
http://stackoverflow.com/questions/34486437/why-cant-mocha-resolve-this-path-or-pattern

Here's my fork:
 https://github.com/alecperkey/redux-form/blob/gh-pages/package.json

Kind regards

**Comment by erikras** [comment]
I've had problems with removing the quotes in the past, but I've removed them and it still works on my Mac, so I'll make the change.

**Comment by chislon** [comment]
Trying to figure out why the quotes were added back into package.json. npm install on Windows is still broken as a result.

**Comment by erikras** [comment]
Surely there must be some popular, well maintained, libraries that are getting this right. I would love for someone to figure out a way to get the tests running in windows and mac and linux, even if it requires removing the `__tests__` folders and just having the tests live with the code that they test.
