### ISSUE TITLE
Undefined react-redux/native on react-redux 4.* on react-native

### ISSUE THREAD

**Issue by mattiamanzati** [erikras/redux-form#473]
Sorry for using issue, but I don't have the infrastructure to PR these days (holidays! :D) but react-redux/native seems to be deprechated and regular {connect} from 'react-redux' seems to work fine! :)

**Comment by erikras** [comment]
Excellent. Thanks.

**Comment by gaearon** [comment]
That's weird. Doesn't RN still ship with its own fork of React? https://github.com/facebook/react-native/issues/2985 is still open.

**Comment by gaearon** [comment]
Please note our README (nobody seems to read it, sigh):

https://github.com/rackt/react-redux#react-native

>Until React Native works on top of React instead of shipping a fork of React, you’ll need to keep using React Redux 3.x branch and documentation.

**Comment by mattiamanzati** [comment]
Yeah, I know that, but since I wanted to try functional components, and had issues time ago with 3.*, I tried to upgrade all packages, and it worked. Somehow. Can you reproduce this?

**Comment by gaearon** [comment]
Unfortunately I don't have time at the moment. Maybe it worked by some some lucky combination of factors. I can't guarantee it'll keep working, or that some edge cases are not broken.

**Comment by mattiamanzati** [comment]
Just updated my project with RN 0.18.0-rc, which claims (and in fact) to use react from NPM.
Changing the line mentioned on the issue seems to make everything work.
@gaearon will confirm that

**Comment by zxcpoiu** [comment]
just for update:

facebook/react-native#2985 has closed.
see also: rackt/react-redux#236

I modified the redux-form faq pages for react-native integration guide:
#605

**Comment by xiaobuu** [comment]
I have to add some code to make redux-form work in react-native with react-redux 4+
#608

**Comment by ooflorent** [comment]
Fixed by #897 #608
