### ISSUE TITLE
removing multiple Items from array

### ISSUE THREAD

**Issue by jsdmc** [erikras/redux-form#474]
Hello!

Let's say I have a list of indexes to remove from form field ```items```. If I will iterate through them I and call ```items.removeField``` each time - ```items``` field will be the same (still includes old items obviously) and next index for removing will be incorrect.
So basically we need to wait until form removes one item, and only after that call ```items.removeField``` again.

Is there any proper way to remove few items from the array using ```removeField()``` ?

Thanks!

**Comment by erikras** [comment]
Interesting. Perhaps `removeField()` should accept an array of indices?

**Comment by jsdmc** [comment]
@erikras That would be great feature. Either one index or array of indexes I'd say

**Comment by fl0cke** [comment]
So, i I've been tinkering with nested forms and found the api to be lacking some useful features.
But I don't think adding more and more functions (or optional parameters) is a good idea.

My proposal to keep the api clean: A single `updateFields()` function that works like the react immutability helper addon. See https://facebook.github.io/react/docs/update.html#available-commands for reference. The source code can be found [here](https://github.com/facebook/react/blob/master/src/addons/update.js).

What do you think?

**Comment by ooflorent** [comment]
You can use action creators to do this:

```js
function removeArrayValues(form, path, indices) {
  return dispatch => {
    indices
      .sort((a, b) => b - a) // Descending sort
      .forEach(index => {
        dispatch(removeArrayValue(form, path, index))
      })
  }
}
```

**Comment by dorthwein** [comment]
Just to clarify whats going on here - If you just iterate over an array of indexes, and call removeField or manipulate it in some other way, at each iteration the index for each of the values changes as you call remove fields.

What @ooflorent is saying to do to get around this is to first sort your indexes so that each iteration of remove is eliminating the furthest back item thus avoiding the next iteration from being out of position.

**Comment by mbeauchamp7** [comment]
Just go downwards the array
```
for (let i = this.props.fields.items.length - 1; i >= 0; i--) {
     this.props.fields.items.removeField(i);
}
```
