### ISSUE TITLE
setErrors transforms class of bignumber.js instance

### ISSUE THREAD

**Issue by yleclanche** [erikras/redux-form#476]
Hello, 

My form state contains BigNumber objects (from bignumber.js).
After the submit, my BigNumber objects are transformed into Object.

The problem is in setErrors :

```
if (state && typeof state === 'object') {
      return Object.keys(state)
        .reduce((accumulator, key) =>
            isMetaKey(key) ? accumulator : {
              ...accumulator,
              [key]: setErrors(state[key], errors && errors[key], destKey)
            },
          state);
    }
```

Not an ES5/6 expert, so not sure how to modify this code to keep the BigNumber class.
Any idea ?

**Comment by yleclanche** [comment]
It works with this code :

```
const oldPrototype = Object.getPrototypeOf(state);
let newState = Object.keys(state)
       .reduce((accumulator, key) =>
            isMetaKey(key) ? accumulator : {
              ...accumulator,
              [key]: setErrors(state[key], errors && errors[key], destKey)
            },
          state);
newState.__proto__ = oldPrototype;
return newState;
```

It looks a little bit hacky, so I'm not sure if I should write a pull request...

**Comment by ooflorent** [comment]
Hi,

This is a usage question, and we encourage you to ask it on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

This is the only way to ensure the same question doesn’t get asked many times in a row, and that folks who have the same question in the future will be able to find it.

I’m closing for these reasons.
