### ISSUE TITLE
New Form and Edit Form

### ISSUE THREAD

**Issue by risonsimon** [erikras/redux-form#480]
I've been trying really hard to find a solution for this. It is mostly a question than an issue. 

I want to use redux-form for new and edit forms. I'm using initialValues for loading edit form. But I'm facing following problems.

1. I'm using [react-geosuggest](https://github.com/ubilabs/react-geosuggest) for a field. The value is an object with google place information. Although I'm able to load the correct value using initialValue, when I click submit, the field is *undefined*. The value is coming correctly if I manually change the place, by selecting a suggestion. *(because `onSuggestSelect` is set)*

2. I cannot set an initial value for *select* field. How do I set a initial value for this?

Here's the code I'm using for react-geosuggest.
```javascript
const GeoSuggestWrapper = ({ 
  field 
}) => (
    <GeoSuggest placeholder="Search place" onSuggestSelect={field.onChange} {...field} initialValue={field.initialValue.name}/>
);
```
```javascript
<form onSubmit={handleSubmit}>
...
<div className="form-group">
          <label>Place</label>
          <GeoSuggestWrapper field={place} className="form-control"/>
 </div>
...
```

Here's the code for select.
```javascript
<select {...date} className="form-control">
            <option value="">Select Date</option>
            {options.map((day, index) => {
                return <option value={day} key={index}>{day}</option>;
              })
            }
</select>
```

I'm have been fiddling a lot with these types of forms. What is the right way to manage new and edit forms? Any guidance would be extremely helpful.

**Comment by erikras** [comment]
Hmmm... It seems like both of these should work. How are you passing in the values to your form?

**Comment by risonsimon** [comment]
I'm passing values using `initialValues` prop of the form.

**Comment by erikras** [comment]
One thing that worries me is the `initialValue={field.initialValue.name}`. Is the value for that field an object or a string. Does GeoSuggest really want to give you an object, but expect a string from you?

**Comment by erikras** [comment]
I've added a select box to the [Initializing From State Example](http://erikras.github.io/redux-form/#/examples/initializing-from-state) to confirm and demonstrate that initializing selects works. You might be doing something wrong like forgetting to add that field to your `fields` array or something.

**Comment by risonsimon** [comment]
sorry for late reply. This is working. Thanks for your time.
