### ISSUE TITLE
Focus lost on redux form input

### ISSUE THREAD

**Issue by JensDebergh** [erikras/redux-form#481]
I'm using `redux-form` for a simple registration form. I've run into this issue where redux does in fact store the state changes of the input field, but it keeps losing focus on key enter.
This means I'm only able to input 1 letter at a time before losing focus on that element.

Any idea how or why this happens?
Could this have something to do with following warning: 

<img width="1277" alt="screen shot 2015-12-29 at 10 22 28" src="https://cloud.githubusercontent.com/assets/6651506/12032224/29d672be-ae16-11e5-9769-6622e5227dfc.png">

Code snippet: https://github.com/JensDebergh/toggle-client/blob/j-toker-login/app/containers/RegistrationPage.js

**Comment by erikras** [comment]
Can you share the JSX where the inputs are?

**Comment by JensDebergh** [comment]
Sorry for not responding on this sooner. I've found the problem.

The problem was that I passed down the entire `state` of the redux store as `props` out of "laziness". I slimmed down the props I needed just for the form and it worked as intended.

**Comment by waffleau** [comment]
@JensDebergh thanks for replying with your solution, you've just saved me a lot of effort! People like you that respond with solutions for your own problems are what give me faith in humanity. =p

**Comment by rndstr** [comment]
A hero, indeed. Some more information (for the novice like myself):

I changed
```
export default connect(state => state)(form(MyFormPage));
```
into
```
export default connect(state => state.form.myformlabel)(form(MyFormPage));
```

This also fixed an issue for me where the input field was losing its value upon blur. 

Here the error message as text:
```
Warning: Failed propType: Invalid prop `form` of type `object` supplied to `ReduxFormConnector(MyFormPage)`, expected `string`. Check the render method of `ConnectedForm`.
```
