### ISSUE TITLE
Provide a way to override pristine value for a form

### ISSUE THREAD

**Issue by Deiru2k** [erikras/redux-form#484]
Exactly what it says. It would be nice to have a way of setting pristine and dirty manually on a whole form.

**Comment by erikras** [comment]
I'm not sure I understand the intent here.

You could just made other props, like `isPristine` and `isDirty` and pass them in with whatever values you wish.

**Comment by Misaka42** [comment]
We rely a lot on how redux form handles pristine and dirty, as those are really convenient, but sometimes, especially with complex forms, handling form state might be very difficult.
For one example, we have an array of photos in one form, handled via redux form's deep values 'images[].url' and et cetera, and if I remove the item - form will not become dirty, and thus we can't rely on redux form's pristine and dirty values to show/hide "save" button as we usually do, and we have to rely on dirty hacks.
And this is a very rough example from one of the recent problems we've run into. I wish I could go into more detail about other cases, but I'm afraid that would derail the conversation.
It might solve a lot of problems we have if we had a way to simply toggle pristine state on a form in a convenient way, without relying on additional props.

**Comment by erikras** [comment]
Okay, I got it. You want a `SET_DIRTY` action that would flip a boolean in the state that would then be `||`ed with what the current `dirty` logic is doing.

That's doable.

**Comment by andynoelker** [comment]
:+1: 

Related to #391, as right now deep form arrays elements do not change pristine/dirty it would be awesome to have a way to manually trigger a form to be dirty (and then it's dirty/pristine properties continue to operate normally after that). Right now I have to do some hackish stuff to make my form appear dirty when users dynamically add/delete form array elements.

**Comment by raygesualdo** [comment]
Just fired off PR #1611 to add a `setDirty` function that would accomplish what you're looking to do. The changes are against v6.

**Comment by MustardForBreakfast** [comment]
can I ask why #1611 was closed?

**Comment by himawan-r** [comment]
Maybe related to #391, case: if i set the form value from reducer the dirty attribute will change to false (i typed something but then set the redux state via reducer)? 
e.g i have autocomplete to choose patient, when type on it then i choose patient the other field is set to the redux state via reducer (then i find the dirty is changed several time though) but finally dirty state is false, is it a desired behavior?

**Comment by ethankong113** [comment]
is there any reason why this is closed instead of getting merged? Is there an alternative solution to this?

**Comment by mohammedzamakhan** [comment]
Same here, was trying to find setPristine or setDirty function in the API, didn't find one, and I see here that the PR was closed :/

**Comment by timhwang21** [comment]
@erikras help would be appreciated!

**Comment by erikras** [comment]
I don't recall exactly, but my best guess is that I closed that PR because it was against a branch that no longer existed. It must have been unluckily submitted right as `v6.0` was launching. I apologize for not explaining that at the time.

I'd be happy to accept a new one. Perhaps we should call it `setForceDirty()`. How about this?

```jsx
setForceDirty(true)      // dirty will always be true and pristine false
setForceDirty(false)     // dirty will always be false and pristine true
setForceDirty(undefined) // back to normal behavior
```

**Comment by gustavohenke** [comment]
Closing due to months of inactivity.
Please reopen accompanied by a PR if you still need this fixed.

**Comment by AdamZaczek** [comment]
There are valid cases for enforcing dirty, consider this:
You fetch form values from API
You want to populate with values based some condition, for example button click.
The new values come from some other source and you want to save them.
Your form is still pristine and you only allow saving on non pristine forms.
There are workarounds around lack of action enforcing pristine state in cases like this (for example setting a state informing about form actually not being pristine and using selectors to get this value) but they are far from elegant.
+1 for this feature

**Comment by kylebebak** [comment]
Just here to say I'd also like to see this feature.

It's too bad it was nearly ready to roll and got canned =/

**Comment by kylebebak** [comment]
@gustavohenke 
I think this should be reopened. Requiring a PR to reopen this is a big obstacle. I for one don't know the **redux-form** code base well enough to implement this feature, but I have an idea for how it could be implemented, and maybe others do to.

I think a good way to do it is an `isPristine` prop that can be passed to a redux-form `Field`. It's a function that takes `(initial, value)` and returns a boolean.

If the `isPristine` prop is passed, every time `onChange` is invoked and the updated `value` gets sent to redux, `isPristine` is invoked and determines whether `pristine` and `dirty` are updated for the field and its form.

@erikras 
Any chance this could be added to a future version?

**Comment by kaleem-elahi** [comment]
> I don't recall exactly, but my best guess is that I closed that PR because it was against a branch that no longer existed. It must have been unluckily submitted right as `v6.0` was launching. I apologize for not explaining that at the time.
> 
> I'd be happy to accept a new one. Perhaps we should call it `setForceDirty()`. How about this?
> 
> ```js-jsx
> setForceDirty(true)      // dirty will always be true and pristine false
> setForceDirty(false)     // dirty will always be false and pristine true
> setForceDirty(undefined) // back to normal behavior
> ```

@erikras  How to use this function ? pls help :)

**Comment by samism** [comment]
I would also like this feature!

**Comment by JNotelddim** [comment]
Yeah if there isn't a fix for this, would love at least to know the recommended interim fix 🙏

**Comment by jcubic** [comment]
I would also love to see how I can make Form pristine. Any way to make the form ignore something so it remains Pristine?
