### ISSUE TITLE
Changing focus removes data from other fields [Redux-from + ImmutableJS]

### ISSUE THREAD

**Issue by quangrau** [erikras/redux-form#487]
when you change focus between fields, the data I already typed in the previous field gets removed.

**Comment by erikras** [comment]
You should look at what's happening to the state in redux-devtools.

**Comment by mattkrick** [comment]
i'm running into this, too, kinda a show stopper. It even affects the demo repo: https://github.com/itaylor/redux-form-immutablejs-example
Repro steps:
 - Type something in the input
 - Blur the input
 - Focus the input
 - Your input value vanished!

Debugging & tracing the error leads you into React's internal `closeAll` method, which totally stumps me. From checking out devtools, it's apparent that it's not merging the previous & current state, but rather just overwriting the previous state. Not sure how where to look next...

**Comment by mattkrick** [comment]
I think this is actually a problem is redux-immutablejs, particularly in the `dirty` and `finalState` calculations, will update when i submit a PR

**Comment by mattkrick** [comment]
OK, there's 2 errors keeping this from working:
1. https://github.com/erikras/redux-form/blob/52b4772265e234a08058532c92f2a4ae1c0d5919/src/reducer.js#L196
`[form]: reducer(state[form], rest)` should be `[form]: reducer(state.get(form), rest)`

2. https://github.com/erikras/redux-form/blob/52b4772265e234a08058532c92f2a4ae1c0d5919/src/reducer.js#L63-L66
the reducer should simply be: `return state.set('_active',field);`

@erikras Any thoughts on how to cleanly make this work?

**Comment by erikras** [comment]
@itaylor?

**Comment by erikras** [comment]
Keep in mind that the redux-form reducer works on plain javascript objects. You will need to wrap it in something that converts from and to immutable js maps.

If you are looking at code inside `reducer.js` and your `state` is an immutable js map, you're doing it wrong.

**Comment by mattkrick** [comment]
when you refer to `state` are you talking about global redux state, or the `form` reducer state? The FAQ & the demo repo suffer from this error so I don't think it's my fault (for once! :laughing:)

**Comment by erikras** [comment]
I'm referring to the local variable you referred to in your comment, as seen in the debugger breaking on that line.

> the reducer should simply be: `return state.set('_active',field);`

Anywhere inside the redux-form reducer, starting from [here](https://github.com/erikras/redux-form/blob/52b4772265e234a08058532c92f2a4ae1c0d5919/src/reducer.js#L160), the `state` should be a plain js object.

**Comment by mattkrick** [comment]
that makes sense, so in that case I think `getFormState` is coming too late in the call stack to serve its purpose, yeah?

**Comment by erikras** [comment]
It doesn't seem like it. `getFormState` is used in the `mapStateToProps` that `redux-form` is giving to `connect()`. It can't happen earlier.

**Comment by itaylor** [comment]
@mattkrick,@lethanhquang I've updated the example with a fix for the issue you were seeing.  
There are multiple ways to solve the issue, see: https://github.com/itaylor/redux-form-immutablejs-example/issues/1 for more details.

**Comment by mattkrick** [comment]
hmmmm, so the preferred way to solve this is to have a mutable object inside an immutable? Feels dirty, but if I never directly edit it, I suppose that means I can't mess it up.

PS, for the googlers, you can keep using `redux-immutablejs`, just use this as your `getFormState`
```
export function getFormState(state, reduxMountPoint) {
  return state.get(reduxMountPoint);
}
```
and then set your initial state to be a mutable inside an immutable:
```
let initialState = Map([
  ['form', form]
]);
```

**Comment by itaylor** [comment]
Yeah, given that redux-form reducer needs to take in a normal, mutable JS object as its state parameter, there are two choices.  Either leave the redux-form object as a normal, mutable JS object inside of your immutable state object, or convert it `.toJS()` before passing it in to the redux-form reducer and then `.fromJS()` the output.

One way has the yuk factor of polluting the immutable object with mutable data, the other keeps your state object purely immutable but requires extra redundant processing work for the toJS and fromJS calls.

**Comment by ooflorent** [comment]
Since this issue is inactive for a while I'm closing it.

@erikras did a great job to make `redux-form@6` compatible with Immutable.js. You should definitively check it out!
