### ISSUE TITLE
Focus field after validation error

### ISSUE THREAD

**Issue by yleclanche** [erikras/redux-form#488]
Hello,

After a validation, I try to focus the first field with an error. 
Do you know a proper way to do this ?

Thanks.

**Comment by erikras** [comment]
You have to call `focus()` on the DOM node itself, which means you need a `ref={myField.name}` on all your inputs so that you can later do `this.refs.myField.focus()`. There's no other way, really.

**Comment by yleclanche** [comment]
The validate function is called from handleSubmit so where can I do the
focus ?


2015-12-31 17:02 GMT+01:00 Erik Rasmussen <notifications@github.com>:

**Comment by erikras** [comment]
You could monitor when `submitFailed` flips from `false` to `true` in `componentWillReceiveProps` and do the `focus()` there? But that will only work the first time.

**Comment by kristian-puccio** [comment]
or use returnRejectedSubmitPromise and catch it in the returned promise

**Comment by erikras** [comment]
Yes, @kristian-puccio's idea is better.

**Comment by yleclanche** [comment]
@kristian-puccio solution only works for async validation, right ? Or I am missing something ?
To be honest I don't really understand the `returnRejectedSubmitPromise` property.
handleSubmit already returns a promise, right ?

**Comment by erikras** [comment]
I'm about to implement something similar in my own projects. I'll share how it goes.

**Comment by erikras** [comment]
Followup: I used `returnRejectedSubmitPromise: true` and got back the errors in my promise `catch()` block just fine.

**Comment by yleclanche** [comment]
Can you provide an exemple on how to use it please ?

**Comment by kristian-puccio** [comment]
I can give you some sudo code:
```
<form
autoComplete={false}
onSubmit={ e => {
handleSubmit(e)
.catch(errors => {  // if the errors isn't passed here you can always grab
it from props.errors.
    // errors is map of field name to error string. so you'll need a way to
find the first field in the screen that errored.
  //  have an array of the fields so I do this:

const widget = this.props.widgets.find( w => errors[w.Name] );
// Scroll to it. useing: https://github.com/fisshy/react-scroll
scrollTo(`widget_${this.props.viewerReference}__${widget.Name}`);

})
}}>
```

**Comment by yleclanche** [comment]
Thanks (both of you :))

**Comment by tomduncalf** [comment]
FYI my solution for this looked like:

```
  componentWillReceiveProps(nextProps: Props): void {
    if (this.state.submitted && Object.keys(nextProps.errors).length) {
      // Force update so the errorMessage is definitely on the page
      this.forceUpdate(() => {
        ReactDOM.findDOMNode<HTMLElement>(this.refs.errorMessage).scrollIntoView()
        this.setState({ submitted: false })
      })
    }
  }

  handleSubmitClick(): void {
    this.setState({ submitted: true })
  }

....

 <SubmitButton label='Next step' onClick={this.handleSubmitClick} /> 
```

so basically keep track of whether the user has clicked submit with a flag, then in `componentWillReceiveProps`, check if the user has click submit and caused errors, and if so show the error message and reset the flag

**Comment by erikras** [comment]
You guys might be interested in [`v5.1.0`](https://github.com/erikras/redux-form/releases/tag/v5.1.0).

**Comment by tomduncalf** [comment]
Nice, thanks @erikras

**Comment by jcheroske** [comment]
I might be missing something, but it looks like `onSubmitFailed` is gone in v6. I'm looking for a way for my form to know there are submission errors, so that I can change field focus, but I'm not using the returned promise feature of `onSubmit`. Instead, I'm using the reducer plugin and creating the `submitErrors` state manually. The reason for this is that my `onSubmit` action creator is calling a saga that knows nothing about redux-form or promises, but does emit actions signalling success or failure. The reducer plugin is doing a wonderful job setting up the submission error state and clearing invalid field values as needed, and redux-form is displaying that modified state correctly. What I can't seem to do is set the field focus. Is the `onSubmit` promise mechanism the only callback currently implemented in v6?

**Comment by erikras** [comment]
@jcheroske You are correct that it is missing, but I plan on implementing it.

**Comment by jcheroske** [comment]
Fantastic!

**Comment by jcheroske** [comment]
A bit off-topic, but I'll sneak it in nonetheless... 

Has the `errors` prop been implemented yet in v6?

Does a global error (`_error`) go under the `submitErrors` key just like all the other submit errors?

**Comment by FuzzySockets** [comment]
Another quick and simple solution for anyone struggling with this:

`<Field name="email" className="emailField" type="text"/>`

... and when you need focus: 

`document.getElementsByClassName('emailField')[0].focus()`

or if you don't mind using jQuery... (if the shoe fits, wear it!)

`$('.emailField').focus();`

**Comment by erikras** [comment]
@FuzzySockets Additional information on #927.

**Comment by henrikra** [comment]
Where to use onSubmitFail?
I tried it like this and it did't fire my console.log.
`<form onSubmit={handleSubmit} onSubmitFail={() => console.log("failed")}>`

**Comment by gzhappysky** [comment]
@henrikra  I add onSubmitFail to reduxForm that did fire my console.log

```
export default reduxForm(
  {
    form: 'TaskEditForm',
    fields,
    validate,
    onSubmitFail:(errors)=>{console.log('failed')}
}
```

**Comment by bochen2014** [comment]
@kristian-puccio 
```
<form
autoComplete={false}
onSubmit={ e => {
handleSubmit(e)
.catch(errors => {  // if the errors isn't passed here you can always grab
it from props.errors.
    // errors is map of field name to error string. so you'll need a way to
find the first field in the screen that errored.
  //  have an array of the fields so I do this:
```

i'm confused. I thought we must pass onSubmit either through a property to redux-form, or , 
```
<form  onSubmit={handleSumbit(e=>{
   //whatever
})}
```
the way you setup onSubmit seems to be different from what erika said...

**Comment by kristian-puccio** [comment]
@bochen2014 In V5 the handleSubmit that get passed to your form component returned a promise. This isn't the onSubmit that you pass to reduxForm, it's what reduxForm gives you

**Comment by bochen2014** [comment]
@kristian-puccio  thanks for your explainatin. I'm using v6 and it seems a bit different ;-)

btw, when you have time, if you can help me with issue #1875      that would be really nice ;-)

**Comment by TheFullResolution** [comment]
I used following code to focus on element... is this a correct implementation? Or maybe there is better way of doing this?

```
let Create = reduxForm({
    form: 'create', // a unique identifier for this form
    validate,
    onSubmitFail() {
      CreateValidationForm.focusOnMessage;
    }
})(CreateValidationForm);
```

```
const CreateValidationForm = React.createClass({

    focusOnMessage() {
      this.refs.error_message.focus();
    },
```

**Comment by nktssh** [comment]
@tomduncalf @erikras any thoughts on implementing this behaviour as plugin to `redux-form` (or HOC, maybe)? Will be really useful! 😉

**Comment by joanrodriguez** [comment]
Here is how I scroll to the first element with an error:

```javascript
handleSubmitFail = (errors) => {
  // Scroll to first error
  let key = Object.keys(errors).reduce((k,l) => {
    return (document.getElementsByName(k)[0].offsetTop < document.getElementsByName(l)[0].offsetTop) ? k : l;
  });
  window.scrollTo(0, document.getElementsByName(key)[0].offsetTop - 100);
}
```

**Comment by lithin** [comment]
From more than a year ago, I want to give a huge shout-out to @tomduncalf whose solution I keep coming back to every single time :)

**Comment by ltfschoen** [comment]
I was using the Redux Form Wizard example [here](http://redux-form.com/6.8.0/examples/wizard/), where I split the form across multiple pages. So I had to tweak @joanrodriguez solution to first create a new object that only contained the erroneous fields that were in the current window.
Also, I ended up having to use `scrollIntoView` instead of `window.scrollTo`, since `window.scrollTo` wasn't working for me for some reason. 

```
export default reduxForm({
  form: 'wizard',
  fields: KEYS,
  destroyOnUnmount: false, // Preserve form data
  forceUnregisterOnUnmount: true, // Unregister fields on unmount
  validate,
  onSubmitFail: e => {
    /*
     * Filters error list to only those in current window.
     * Alternative of scrollIntoView used to scroll to input field that failed validation
     * 
     * Note: Since `window.scrollTo` does not work unable to implement scrollTo feature
     * Reference: https://github.com/erikras/redux-form/issues/488
     */
    let stageKeys = {};
    Object.keys(e).forEach(k => {
      if (document.getElementsByName(k).length) {
        stageKeys[k] = document.getElementsByName(k);
      }
    });
    let key = Object.keys(stageKeys).reduce((k,l) => {
      return (document.getElementsByName(k)[0].offsetTop < document.getElementsByName(l)[0].offsetTop) ? k : l;
    });
    // window.scrollTo(0, document.getElementsByName(key)[0].offsetTop - 100);
    document.getElementsByName(key)[0].scrollIntoView({block: 'start',  behaviour: 'smooth'});
  }

})(WizardFormFirstPage);
```

**Comment by metamp** [comment]
> Here is how I scroll to the first element with an error:

I modified the the function joanrodriguez posted like this:
`export const scrollToInvalid = (errors) => {
  if (errors) {
    const invalidInput = _.findKey(errors, key => key !== undefined);
    window.scrollTo(0, window.pageYOffset +
      (document.getElementsByName(invalidInput)[0].getBoundingClientRect().top - 100));
  }
};`


The `window.pageYOffset +
      document.getElementsByName(invalidInput)[0].getBoundingClientRect().top` part gets the accurate top position of the element


The in the component I do 
`import { scrollToInvalid } from '../../whateverFile';`
 
and in the form 
`export default compose(
  reduxForm({
    form: 'FormName', 
    validate: formValidator,
    onSubmitFail: errors => scrollToInvalid(errors),
  }),
)(ComponentName)`
