### ISSUE TITLE
pre-submit callback

### ISSUE THREAD

**Issue by simplyianm** [erikras/redux-form#489]
How could I call a function before onSubmit is called but after validation has taken place?

I want to display a message if there are errors upon submission.

**Comment by erikras** [comment]
The submit won't go through if there are errors, and the `submitFailed` prop will be `true`.

**Comment by simplyianm** [comment]
what function should I call? Could you give me an example?

**Comment by erikras** [comment]
Have you looked at the [Submit Validation example](http://erikras.github.io/redux-form/#/examples/submit-validation)?

**Comment by ooflorent** [comment]
This is a usage question, and we encourage you to ask it on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

This is the only way to ensure the same question doesn’t get asked many times in a row, and that folks who have the same question in the future will be able to find it.

I’m closing for these reasons.
