### ISSUE TITLE
Is it safe to use redux-form for password fields?

### ISSUE THREAD

**Issue by shanewho** [erikras/redux-form#490]
I want to use this for a login form but after login I don't want the password staying around in memory (in case of XSS or some other issue, I don't want it to be available to be stolen.) Is it safe to use redux-form for the password field? Or is there a way to clear the value from memory after the login call is made?

**Comment by erikras** [comment]
Yes. The form is destroyed by default when you unmount the form component. Alternatively, you may dispatch the DESTROY action yourself.

**Comment by shanewho** [comment]
:+1:
