### ISSUE TITLE
validation context

### ISSUE THREAD

**Issue by arolson101** [erikras/redux-form#494]
I have a validation function that needs access to form props to determine whether a field is valid (e.g., if the value is unique among global state).  It would be helpful if we could have a validate method on the form class, rather than forcing it to be a free function

**Comment by erikras** [comment]
The second parameter to the validation function is the `props`.

**Comment by arolson101** [comment]
I was wondering about that; I see it in the callstack, but it's not the same props as my component- the properties injected via react-redux ```@connect``` don't appear; it's like the props was cached before fully initialized.

I tried switching the order of the ```@reduxForm.reduxForm``` and ```@connect``` calls, but when I do I get:
```
Error: Could not find "store" in either the context or props of "Connect(ConnectedForm)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(ConnectedForm)"
```

**Comment by arolson101** [comment]
I see, the problem is ```@connect``` will create a new element with the merged properties rather than injecting them in componentWillReceiveProps, like redux-form does.  I have no idea how to use them both

**Comment by erikras** [comment]
You don't need to use `@connect` and `@reduxForm` on the same component. The second and third parameters to `reduxForm()` are `mapStateToProps` and `mapDispatchToProps` which behave just like `connect()`.

**Comment by arolson101** [comment]
That's it!  I didn't realize that I wouldn't need ```@connect```, but you're right- using all redux-form works and the props passed in are the ones I need.  Thanks!

**Comment by erikras** [comment]
:+1: Great!
