### ISSUE TITLE
'initializeForm' take affect only once

### ISSUE THREAD

**Issue by liqili** [erikras/redux-form#495]
I tried to use the function to reset form values,but it  had no affect except the first call.I note that the INITIALIZE action was dispatched.

**Comment by erikras** [comment]
You'll have to share some example code.

**Comment by liqili** [comment]
let initData = {}
class App extends React.Component{
 constructor(props) {
      super(props);
     ...
    }
  }
  componentWillMount() {
 ...
            initData = {
                            "appId":result.envDataMap.appIds[0].code,
                            "srcenv": result.envDataMap.envIds[0].code,
                            "destenv": result.envDataMap.envIds[0].code}
            this.props.initializeForm(initData);
 ...          
  }
   
 ...
  resetFormValue(){
        this.props.initializeForm(initData);             
     }

  render() {
    var {fields,formEnabled} = this.props
    var {fakeSaving, fakeSubmitted} = this.state
    return <div className="col-md-offset-1 col-md-10" >
      <Panel header={title}>
      <form className="form-horizontal"  onSubmit={this.props.handleSubmit(::this.handleSubmit)}>
        <Row>
           <Combobox
            disabled={!formEnabled}
            field={fields.appId}
            id="appId"
            label="appId:"
            data = {this.state.contentAreas}
            valueField='code' 
            textField='value'
          />
        </Row>
        <Row>
           <Combobox
            disabled={!formEnabled}
            field={fields.srcenv}
            id="srcenv"
            label="Source Environment:"
            data = {this.state.srcEnv}
            valueField='code' 
            textField='value'
          />
        </Row>
        <Row>
           <Combobox
            disabled={!formEnabled}
            field={fields.destenv}
            id="destenv"
            label="Destination Environment:"
            data = {this.state.destEnv}
            valueField='code' 
            textField='value'
          />
        </Row>
 <Row  className={formEnabled ? 'form-group':'form-group hidden'}>
          <div className="col-sm-offset-3 col-sm-4">
            <LoadingButton
              bsStyle="primary"
              label="Submit"
              loading={fakeSaving}
              loadingLabel="Submit"
              type="submit"
              
            />
             <Button bsStyle="primary" type="reset" style={{marginLeft: 15}}
             onClick={::this.resetFormValue}
             >
             Reset</Button>
          </div>
        </Row>
   
       </form>
       </Panel>
       {this.props.children}
    </div>
  }
}

let formApp = reduxForm({
  form: 'App',
  fields: ['appId','srcenv', 'destenv'], 
  touchOnChange: true, 
  validate(travel) {
    var errors = {}
     if (travel.appId == null) 
      errors.appId = 'Please select application.'
    if (travel.srcenv == null) 
      errors.srcenv = 'Please select source environment.'
    if (travel.destenv == null) 
      errors.destenv = 'Please select destination environment.'
    return errors
  }
})(App);
export default connect(mapStateToProps,mapDispatchToProps)(formApp)

The component 'Combobox' is defined as:
import React from 'react'
var {PropTypes} = React

import FormField from './FormField'
import {Combobox as ReactCombobox} from 'react-widgets'
export default class Combobox extends React.Component{
  constructor(props) {
    super(props);
    this.shouldComponentUpdate= FormField.shouldFormFieldUpdate;
  }
  static propTypes = {
    field: PropTypes.object.isRequired
  }
  render() {
   var {field, help, label, afterChange, data,...inputProps} = this.props
    var onChange = field.onChange
    if (afterChange) {
      onChange = function(...args) {
        field.onChange(...args)
        afterChange(...args)
      }
    }
    // console.log(field)
    return <FormField field={field} help={help} inputProps={inputProps} label={label}>
      <ReactCombobox
        {...inputProps}
        name={field.name}
        data = {data}
        onChange={onChange}
        value={field.value}
        // defaultValue={field.value}
      />
    </FormField>
  }
}

The component 'FormField ' is defined as:

import classNames from 'classnames'
import Col from 'react-bootstrap/lib/Col'
import React from 'react'
import Row from 'react-bootstrap/lib/Row'
var {PropTypes} = React
import Help from './Help'
import Loading from './Loading'

var FIELD_EVENT_HANDLER = /^(?:on|handle)[A-Z]/
function fieldShallowEquals(field, nextField) {
  for (var prop in field) {
    // Ignore event handlers, as they continually get recreated by redux-form
    if (!FIELD_EVENT_HANDLER.test(prop) && field[prop] !== nextField[prop]) {
      return false
    }
  }
  return true
}

export default class FormField extends React.Component{
  constructor(props) {
    super(props);
  }
  static propTypes = {
    field: PropTypes.object,
    help: PropTypes.string,
    inputClass: PropTypes.string,
    inputProps: PropTypes.object,
    label: PropTypes.string,
    loading: PropTypes.bool
  }

  static defaultProps = {
      field: {},
      inputProps: {}
    }
  static shouldFormFieldUpdate(nextProps){
      var keys = Object.keys(this.props)
      var nextKeys = Object.keys(nextProps)
      if (keys.length !== nextKeys.length) return true
      var nextHasOwnProperty = Object.prototype.hasOwnProperty.bind(nextProps)
      for (var i = 0; i < keys.length; i++) {
        var key = keys[i]
        if (!nextHasOwnProperty(key) ||
            key === 'field' ? !fieldShallowEquals(this.props[key], nextProps[key])
                            : this.props[key] !== nextProps[key]) {
          return true
        }
      }
      return false
    }
  
  render() {
    var {field, help, inputClass, inputProps, label, loading} = this.props
    var error = field.touched && field.error
    return <Col sm={10}>
      <Row className={classNames('form-group', {'has-error': error})}>
        <Col sm={4} className="control-label">
          {loading && <Loading inline/>} <label htmlFor={inputProps.id}>{label}</label>
          {help && <Help text={help}/>}
        </Col>
        <Col sm={8} className={inputClass}>
          {this.props.children}
          {error && <p className="help-block" style={{marginBottom: 0}}>{error}</p>}
        </Col>
      </Row>
    </Col>
  }
}

**Comment by liqili** [comment]
In the function 'componentWillMount',call function 'initializeForm'  like this:
            initData = {
                            "appId":result.envDataMap.appIds[0].code,
                            "srcenv": result.envDataMap.envIds[0].code,
                            "destenv": result.envDataMap.envIds[0].code}
            this.props.initializeForm(initData);
It take affect,However,when click the reset button, the code below can not refresh the DOM.I also note that the value of form item was changed.The form item I used is 'Combobox' in react-widgets.But I think it has nothing to do with the item type.It resulted the same when I used the 'input' tag as form item.
resetFormValue(){
        this.props.initializeForm(initData);             
     }

**Comment by erikras** [comment]
To reset back to what you initialized to, you should use `this.props.resetForm()`.

**Comment by liqili** [comment]
Thanks very much.If using the prop 'initialValues'  to initialize the form,this.props.resetForm() can reset form successfully.I want to initialize the form dynamically,unfortunately,I used function 'initializeForm' to initialize the form,then this.props.resetForm() can not reset form successfully.In addition,I also note that the property 'defaultValue' of form field value object is 'undefined' when call this.props.resetForm().

**Comment by erikras** [comment]
Setting `initialValues` does nothing different from `this.props.initializeForm()`. I'm not sure what you mean by "dynamically". I would recommend using redux-devtools to see what action is getting dispatched and how that is affecting the state.

**Comment by liqili** [comment]
I see,initialValues and this.props.initializeForm() will dispatch the same action.However,after 'action=redux-form/INITIALIZE',the fields objects are not the same in the two initial way.Please see the below('defaultValue' /'initialValue'  property is not the same):
1、By setting initialValues：
{active: false
checked: undefined
defaultChecked: false
defaultValue: "SFPB"
dirty: false
error: undefined
initialValue: "SFPB"
invalid: false
name: "appId"
onBlur: (event)
onChange: (event)
onDragStart: (event)
onDrop: (event)
onFocus: ()
onUpdate: (event)
pristine: true
touched: false
valid: true
value: "SFPB"
visited: false
__proto__: Object
}
2、By calling initializeForm() ：
{active: false
checked: undefined
defaultChecked: false
defaultValue: undefined
dirty: false
error: undefined
initialValue: undefined
invalid: false
name: "appId"
onBlur: (event)
onChange: (event)
onDragStart: (event)
onDrop: (event)
onFocus: ()
onUpdate: (event)
pristine: true
touched: false
valid: true
value: "SFPB"
visited: false
__proto__: Object
}

**Comment by erikras** [comment]
Yes, you are correct. I should probably fix that inconsistency.

**Comment by erikras** [comment]
Fix published in [`v4.1.1`](https://github.com/erikras/redux-form/releases/tag/v4.1.1).

**Comment by liqili** [comment]
Thanks erikras.

**Comment by linlinfly** [comment]
I got the same problems in v3.1.0

**Comment by gustavohenke** [comment]
@linlinfly It's been 2+ years since the last time this was an issue.
Please update Redux Form and try again.

**Comment by linlinfly** [comment]
@gustavohenke thank you.
