### ISSUE TITLE
Discord button not working

### ISSUE THREAD

**Issue by jimmybaker** [erikras/redux-form#496]
The discord link doesn't work anymore. Can someone please update it?

**Comment by erikras** [comment]
Hmm.. The one in the readme? Works for me. What does it do for you?

**Comment by drouillard** [comment]
Works for me. @jimmybaker what type of errors are you receiving?

**Comment by danielfalk** [comment]
It doesn't work for me either, but maybe I'm not doing it right?  I click on the link, and it takes me to the discord app.  I'm signed in, but it doesn't connect me to any server.  This is the url I'm on:

https://discordapp.com/channels/102860784329052160/105736485537374208

Which is the url of the #redux-form link afaict.

**Comment by mikkom** [comment]
I think the issue is that one needs to first join the Reactiflux server (see http://www.reactiflux.com/) before the #redux-form channel can be opened. Would be good to add a mention about that next to the Discord link.

**Comment by danielfalk** [comment]
Yes, that was the issue for me.  Thanks.

**Comment by ooflorent** [comment]
The button is gone. This issue is no longer relevant.
