### ISSUE TITLE
Use simple container component

### ISSUE THREAD

**Issue by hugobessaa** [erikras/redux-form#5]
What do you think about simply using a component that pass necessary functions to the it's children callback? Example implementation:

```es6
<Validate sliceName="foo">
  {(props) => {<Form {...props}>}}
</Validate>
```

I personally prefer to use components and children callbacks over blackbox decorators on classes. Redux also gives this options with the `<Provider>` and `<Connector>` components.

**Comment by gaearon** [comment]
To be fair Redux plans to remove `<Connector>` because it encourages too many smart components.

**Comment by hugobessaa** [comment]
Agree. So `@connector` decorator too? (probably not the best place to discuss this)

**Comment by gaearon** [comment]
Nah, connect stays (but changes a bit).
See 

https://github.com/gaearon/react-redux/issues/1
https://github.com/gaearon/react-redux/issues/1#issuecomment-120729921

**Comment by hugobessaa** [comment]
Just worry about what happens to the component passed as an argument to the function returned when `connect()`. I always avoid mixins because of this.

I didn't follow the whole discussion so I can be wrong.

**Comment by erikras** [comment]
In v0.0.7, I've removed the dependency on `react-redux`, so the `connect()` and `reduxForm()` are managed separately.
