### ISSUE TITLE
Validation function won't take select with jQuery plugin value

### ISSUE THREAD

**Issue by DWboutin** [erikras/redux-form#500]
Hi!

I try to validate my form with the form validation function, but it won't take the value. It didn't take it in the handleSubmit function too.

I can do `$('#country option:selected').val()` to retrieve it correctly in the console.

I use materializecss to set my select, checkboxes and radios.

**Comment by erikras** [comment]
It sounds like your `onChange` isn't set up properly on the select component. Can you use redux-devtools (or some logging middleware) to inspect what's in the store?

**Comment by DWboutin** [comment]
The `onChange` isn't provided with the field's variable? With redux-devtools it doesn't log any changes when i change my select. How can i set a proper `onChange` function for my select? The plugin transform the select into an UL list. You can see it there in action: http://materializecss.com/forms.html#select

Thank you for your awesome help as always!

**Comment by DWboutin** [comment]
I made the onChange event like this and it works now!

```javascript
componentDidMount() {
    const { id, reduxField } = this.props;

    $('#' + id)
      .on('change', reduxField.onChange)
      .material_select();
}
```

**Comment by erikras** [comment]
Okay. Mixing jQuery and React is always a bit scary, but if it's working for you, I'll close the issue.

**Comment by DWboutin** [comment]
I had to do this, because the materializecss works with jQuery, so i had to init the material_select plugin!
