### ISSUE TITLE
No clearForm method to clear the form without destroying it

### ISSUE THREAD

**Issue by gabrielenosso** [erikras/redux-form#504]
Hi, I have a problem:
I want to provide a method to clear all the values of the form, without using the initialValues defined.

Imagine that I have a form with 3 buttons:
1) Apply (which invokes handleSubmit),
2) Reset (which invokes resetForm, so it loads the initialValues)
3) Clear (which invokes destroyForm).

The problem is that destroyForm removes all the data, so after that the resetForm won't work anymore.

I think it would be a good idea to add a clearForm method that clears the "value" property in the redux store but not the "initial" property (which contains the initialValues).

**Comment by erikras** [comment]
This seems like a very strange use case to me. Can you explain why you would want this? What benefit this serves to the user?

**Comment by gabrielenosso** [comment]
It could be helpful in any case in which you want to give the opportunity to the user to clean the whole form without using the default values.

So for example you can have a form with an email field.
The email field is pre-filled with the user email loaded from the database.
Now if the user clicks the Clear button, it expects to "clean" it, not to reset it. So to delete every information in it.

In my specific case, my form values are loaded from the URL query, but I want to give the user the opportunity to clean them.

**Comment by neverfox** [comment]
Sounds like you just want to change the initial values to nothing and then reset. Can't you do that in your code?

**Comment by erikras** [comment]
Yeah. `initializeForm({})` might be what you want.
