### ISSUE TITLE
Field values changing types

### ISSUE THREAD

**Issue by jonathanasquier** [erikras/redux-form#505]
Hi!
I'm calculating a global dirty value on my form to display the "update" button if any field is modified (so dirty) but it failed on fields with numbers.
On both text or a number inputs, the initial is 100 (int, feeded by an API) and value is "100" (if modifing the field, then rolling back)
Is there a way to cast fields so that my number values stay ints, or anything that would ensure the consistency of types ?

Thanks!

**Comment by erikras** [comment]
You could potentially use [`normalize`](http://erikras.github.io/redux-form/#/examples/normalizing) to do your casting. The library itself does not have a strong opinion on type casting.

**Comment by jonathanasquier** [comment]
puuuurrrrr fect.
