### ISSUE TITLE
"Unhandled promise rejection"

### ISSUE THREAD

**Issue by shilpan** [erikras/redux-form#513]
When I call `asyncValidate()` to manually run the validation on a text input. I get the error `Unhandled promise rejection` every time the promise is rejected.

**Comment by shilpan** [comment]
Here is a sample code. Typing `ringoo` will throw the error.

```Javascript
import React, { Component, PropTypes } from 'react';
import { reduxForm } from 'redux-form';

export const fields = ['name'];

const asyncValidate = (values) => {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      console.log(values);
      if (['john', 'paul', 'george', 'ringo'].includes(values.name)) {
        reject({name: 'This name is taken'});
      } else {
        resolve();
      }
    }, 100); // simulate server latency
  });
};

class Overview extends Component {
  static propTypes = {
    asyncValidate: PropTypes.func.isRequired,
    fields: PropTypes.object.isRequired,
    handleSubmit: PropTypes.func.isRequired,
  };

  constructor(props) {
    super(props);

    this.validate = this.validate.bind(this);
  }

  validate(onChange) {
    return event => {
      onChange(event);
      this.props.asyncValidate();
    };
  }

  render() {
    const {
      fields: { name },
      handleSubmit,
    } = this.props;
    return (
      <div>
        <form onSubmit={handleSubmit}>
          <div>
            <div>
              <input type="text" placeholder="Name" {...name} onChange={this.validate(name.onChange)}/>
              {name.error && <div>{name.error}</div>}
            </div>
          </div>
        </form>
      </div>
    );
  }
}

export default reduxForm({
  form: 'form',
  fields,
  asyncValidate
})(Overview);
```

**Comment by erikras** [comment]
Yes, that's because you're not doing anything with the promise returned from `asyncValidate()`. You'd have to put a `asyncValidate().catch(() => {})` to avoid that error.

You really prefer running validation on a debounced `change` rather than just using the default `blur` behavior built into the library?

**Comment by thomasmery** [comment]
Hi there,

I'm a bit stuck with a similar issue

I'm trying to asyncValidate when a custom component changes value but calling the field onBlur does not seem to trigger async validation

the component is not an input per se:  [material-ui selectField](http://www.material-ui.com/#/components/select-field)

here is how I'm trying to do this

```js
<SelectField 
	{...role} // redux-form field props - contains 'value' which is updated by the field.onChange call below
	onChange={ (event, index, value) => { // onChange is the component's way of dealing with changing option
		role.onChange(value); // update redux-form state
		role.onBlur(event);// should trigger async validation?
		// this.props.asyncValidate(event);
	} }
>
	{this._renderRoles()} // render options
</SelectField>
```

I am missing a piece of the puzzle I guess - so any help on this would be ... great 

thanks

**Comment by erikras** [comment]
@thomasmery My best guess is that you are not listing `role` in in your `asyncBlurFields` config prop.

http://erikras.github.io/redux-form/#/api/reduxForm

**Comment by thomasmery** [comment]
...indeed
thanks!
getting closer 
but now asyncValidate triggers only on second change

both onChange and onBlur actions are triggered the same on both occasions but only on the second id asyncValidate called

**Comment by erikras** [comment]
You needn't call both `onChange()` and `onBlur()`, as `onBlur()` saves the value.

**Comment by thomasmery** [comment]
thanks,
I removed `onChange`
but the asyncValidate only triggers on second `onBlur`call

the other (regular) fields in the form behave as expected I'll investigate the component's internal but maybe you have an idea

**Comment by thomasmery** [comment]
I tried:
```js
setTimeout(() => role.onBlur(value), 100);
```
and as suspected it helped
don't know why right now but I guess it has to do with the component

thanks for your time!

**Comment by erikras** [comment]
Yeah, sounds like it might be the component's fault. Maybe sprinkle some `console.log()`s in your `onChange` function to check that it's being called? The async validation _should_ fire every time you call `role.onBlur(event)`.

**Comment by thomasmery** [comment]
I'll investigate and report here or in the material-ui thread I found here: https://github.com/erikras/redux-form/issues/542
