### ISSUE TITLE
Browser support?

### ISSUE THREAD

**Issue by gabrielpugliese-luizalabs** [erikras/redux-form#517]
I'm using reduxForm() on my app and it does not work on IE8 even with es3ify and all babel es3 transforms (I've tested removing it and it works like a charm). Are there any plans to have official browser support and maybe IE8 support?

**Comment by erikras** [comment]
Can you be more specific about "does not work"?

**Comment by gabrielpugliese-luizalabs** [comment]
Yes, sure. It is really hard to debug in IE8, specially on a transpiled code. The error thrown is:
`Exception thrown and not caught`. It occurs when I just add the decorator in the code below:
```
const React = require('react');
const { Component, PropTypes } = React;
const { reduxForm } = require('redux-form');
const { connect } = require('react-redux');

const Form = require('../components/Form');

const productActions = require('../actions/product');

const { func, shape, bool, object } = PropTypes;
const validate = values => {
  let errors = {};

  if (! /^[0-9]{7}$/.test(values.id)) {
    errors = Object.assign({}, errors, { id: 'Must be 7 numbers' });
  }

  return errors;
};

@connect(() => ({}), productActions)
@reduxForm({
  form: 'product',
  fields: ['id'],
  validate
})
class FormContainer extends Component {
  static propTypes = {
    getProduct: func.isRequired,
    fields: shape({ id: object.isRequired }).isRequired,
    handleSubmit: func.isRequired,
    submitting: bool.isRequired
  };

  render() {
    const {
      getProduct,
      fields: { id: idField },
      handleSubmit,
      submitting
    } = this.props;
    const childrenProps = { idField, submitting };

    return (
      <Form
        onSubmit={handleSubmit(({ id }) => getProduct(id))}
        {...childrenProps}
      />
    );
  }
}

module.exports = FormContainer;
```

This is my webpack.config.js
```
const path = require('path');
const bourbon = require('node-bourbon').includePaths;

module.exports = {
  entry: [
    'babel-polyfill',
    'es5-shim',
    'es5-shim/es5-sham',
    'console-polyfill',
    './index'
  ],
  resolve: {
    root: [
      path.join(__dirname, 'node_modules')
    ],
    extensions: ['', '.js', '.jsx', '.json']
  },
  output: {
    path: path.join(__dirname, 'dist'),
    filename: 'app.js'
  },
  module: {
    loaders: [
      { test: /\.json$/, loader: 'json' },
      { test: /\.scss$/, loader: `style!css!sass?includePaths[]=${bourbon}` },
      { test: /\.jsx?$/, exclude: /node_modules/, loader: 'babel' }
    ],
    postLoaders: [
      { test: /\.js$/, loader: 'es3ify' }
    ]
  }
};
```

And the .babelrc:
```
{
    "presets": ["es2015", "stage-0", "react"],
    "plugins": [
        ["transform-decorators-legacy"]
    ],
    "env": {
        "production": {
            "plugins": [
                ["babel-plugin-transform-es2015-modules-commonjs"],
                ["babel-plugin-transform-es3-member-expression-literals"],
                ["babel-plugin-transform-es3-property-literals"]
            ]
        }
    }
}
```

If we go to the line it raises the error on the transpiled code, it's a try...finally block that I have no clue what does (the first try raises):
```
	  /**
	   * Executes the function within a safety window. Use this for the top level
	   * methods that result in large amounts of computation/mutations that would
	   * need to be safety checked. The optional arguments helps prevent the need
	   * to bind in many cases.
	   *
	   * @param {function} method Member of scope to call.
	   * @param {Object} scope Scope to invoke from.
	   * @param {Object?=} a Argument to pass to the method.
	   * @param {Object?=} b Argument to pass to the method.
	   * @param {Object?=} c Argument to pass to the method.
	   * @param {Object?=} d Argument to pass to the method.
	   * @param {Object?=} e Argument to pass to the method.
	   * @param {Object?=} f Argument to pass to the method.
	   *
	   * @return {*} Return value from `method`.
	   */
	  perform: function (method, scope, a, b, c, d, e, f) {
	    !!this.isInTransaction() ? process.env.NODE_ENV !== 'production' ? invariant(false, 'Transaction.perform(...): Cannot initialize a transaction when there ' + 'is already an outstanding transaction.') : invariant(false) : undefined;
	    var errorThrown;
	    var ret;
	    try {
	      this._isInTransaction = true;
	      // Catching errors makes debugging more difficult, so we start with
	      // errorThrown set to true before setting it to false after calling
	      // close -- if it's still set to true in the finally block, it means
	      // one of these calls threw.
	      errorThrown = true;
	      this.initializeAll(0);
	      ret = method.call(scope, a, b, c, d, e, f);
	      errorThrown = false;
	    } finally {
	      try {
	        if (errorThrown) {
	          // If `method` throws, prefer to show that stack trace over any thrown
	          // by invoking `closeAll`.
	          try {
	            this.closeAll(0);
	          } catch (err) {}
	        } else {
	          // Since `method` didn't throw, we don't want to silence the exception
	          // here.
	          this.closeAll(0);
	        }
	      } finally {
	        this._isInTransaction = false;
	      }
	    }
	    return ret;
	  },
```

I will create a reproducible repo tomorrow to help.

**Comment by gabrielpugliese-luizalabs** [comment]
When I mean add the decorator, is the `reduxForm` decorator. The same symptom is seen when I just call as function `reduxForm(//params)(FormContainer);`

**Comment by slawek50** [comment]
I reproduced exactly the same problem on my app using redux-form.
For information, if I catch the exception before the finally block, I get the error message : "Accessors not supported!".
I'm also currently working on this.

**Comment by gabrielpugliese-luizalabs** [comment]
Here the reproducible repo: https://github.com/gabrielhpugliese/redux-form-ie8
I commited the `dist/` folder so you can just run `npm start` to run a python server on :8000 - if you need to compile again, just run `npm webpack`.
To see the working version without the decorator, just checkout to branch `without-redux-form` and run again.
The error is in line 14329

**Comment by gabrielpugliese-luizalabs** [comment]
I recommend using https://www.browserstack.com/start to test localhost (using Chrome's plugin)

**Comment by SimenB** [comment]
Core-js throws the error `throw TypeError('Accessors not supported!');`. Trying to dig up where the `get` or `set` is used

**Comment by SimenB** [comment]
It's `react-lazy-cache`.

https://github.com/erikras/react-lazy-cache/commit/69f720fd28abf11aa4f52d98d7d818e122d3b920

**Comment by erikras** [comment]
Thanks for that detective work, @SimenB.

**Comment by SimenB** [comment]
No problem.

Btw, FB announced today that they'll [drop support for IE8](http://facebook.github.io/react/blog/2016/01/12/discontinuing-ie8-support.html) in the next version. As 0.15 is not even announced yet though (probably right around the corner, but still), I'd still like to see this get fixed as 0.14 will of course be keeping the IE8 compat

**Comment by erikras** [comment]
I looked into this a little and discovered that I don't care enough about IE8. If someone would like to submit a tested PR to `react-lazy-cache`, I'll accept it.

**Comment by SimenB** [comment]
PR filed over there (erikras/react-lazy-cache#3). The change needed here would be negligible (add the new import, `new` keyword and a `get`-call).

Using the new (alternate I suppose is the better word) version, @gabrielpugliese-luizalabs's example runs fine in IE8

**Comment by erikras** [comment]
Go ahead and make the negligible change in a PR, @SimenB. And test it, of course. :smile:

**Comment by SimenB** [comment]
Done, see #558

**Comment by erikras** [comment]
I just realized that I'm using `defineProperty` in other parts of `redux-form`, so I'd be surprised if this works. Those of you burdened with IE8 support requirements might just need to make your own fork and use that until you can escape your shackles.

**Comment by SimenB** [comment]
Hmm, the simple example worked at least. I have no larger apps currently using `redux-form`, although we plan to use it at work when we port our current Backbone-implementation.

What parts currently use them?

**Comment by erikras** [comment]
Can you pop [object-define-property](https://github.com/tarruda/object-define-property) into your build somewhere and have it work?

**Comment by gabrielhpugliese** [comment]
It works on my example because I'm using es3ify. Just look at webpack
config postLoaders.

**Comment by SimenB** [comment]
@gabrielhpugliese Object.defineProperty isn't syntax, so es3ify doesn't matter.

@erikras I currently include the polyfill as that's required from React for IE < 9. By setting a quick breakpoint in chrome, the function is called, and it does seem to work now in IE8 (it doesn't crash).

I think it's jeg getters and setters that are not shimmable (as it's a magical function call to `get` or `set`). Actually defining properties does work, but they're not read-only

**Comment by erikras** [comment]
Ah, okay. None of my other usages are using `getters` like `react-lazy-cache` was, so you should be good.

**Comment by gabrielhpugliese** [comment]
Sorry, it's the es5shim polyfill @SimenB https://github.com/gabrielhpugliese/redux-form-ie8/blob/master/webpack.config.js#L6

**Comment by gabrielhpugliese** [comment]
Actually the sham :)

**Comment by SimenB** [comment]
Yup!

It should work now, which is great :smile:
