### ISSUE TITLE
How to dispatch action when form is dirty

### ISSUE THREAD

**Issue by asjmtz** [erikras/redux-form#520]
I keep a `pageDirty` in store to present a page's status of dirty, but cannot find a sufficient way to map dirty props in form to my `pageDirty`.

I have tried to dispatch a action in `componentWillReceiveProps`  , but it seems to cause a leg when i input text or change field value.

```
			componentWillReceiveProps(nextProps){

				if ( this.props.dirty !== nextProps.dirty ) {
					this.props.dispatch({
						type: ACTION.PAGE.UPDATE,
						dirty: nextProps.dirty
					})
				}
			}
```

Pls help

**Comment by erikras** [comment]
What is your goal, exactly? To save anytime anything changes?

**Comment by asjmtz** [comment]
Yep, i want to store a `dirty` mark, and all data changing in a page will trigger a `dispatch()` to set `{dirty: true}`. So, eventually i can prompt the user before leaving a route that depends on whether  `dirty` is true .

**Comment by max-mykhailenko** [comment]
@asjmtz Why you don't want to check dirty prop in `tryToClose` action and don't use the store?

**Comment by ooflorent** [comment]
This is a usage question, and we encourage you to ask it on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

This is the only way to ensure the same question doesn’t get asked many times in a row, and that folks who have the same question in the future will be able to find it.

I’m closing for these reasons.
