### ISSUE TITLE
Support for multiple validation errors

### ISSUE THREAD

**Issue by confiks** [erikras/redux-form#523]
I use a validation library that can return multiple validation errors per form field. I would want to display those errors in a list under the form field.

I initially assumed that you can let the `validate` function return an object with values that are arrays of strings, or empty arrays for no errors. It actually works for individual form fields. The [`isValid` function](https://github.com/erikras/redux-form/blob/c18736569ff7b9db8cea1968e6e0c340e9e8ff59/src/isValid.js) of `redux-form` correctly handles the empty array case, and the error array successfully appears in `this.props.fields[].error`. So I happily continued along this path.

`this.props.handleSubmit()` also works correctly, because it uses `isValid()` as well.

There is a problem however with the value of `this.props.valid`; the validity of the entire form. In 8068568, a fix was made to `readFields()`. [It now checks](https://github.com/erikras/redux-form/blob/c18736569ff7b9db8cea1968e6e0c340e9e8ff59/src/readFields.js#L19) if any field error is truthy, and if it is, it sets the `valid` prop for the entire form to false. An empty array is of course truthy.

Do you think it would be a good idea to also officially support the 'array of errors' approach?

**Comment by confiks** [comment]
To be a bit more clear: as far as I can see, the only change to 'officially support' this, would be changing readFields to check for an empty array, and updating the tests and documentation.

**Comment by trashgenerator** [comment]
I'm using array errors too but I'm not putting field error in object if array is empty. So in the end I have empty object if there is no errors and because of that `this.props.valid` working as expected

**Comment by confiks** [comment]
@trashgenerator Yes, I'm using the same workaround now as well.

**Comment by confiks** [comment]
Additionally, when setting errors on submit, the first error is always used due to [this line](https://github.com/erikras/redux-form/blob/e78c993aaa200cca2241fe0867932a2a492bd184/src/setErrors.js#L51) in setErrors. An ugly workaround is described in #639.

Just documenting the different breakages for multiple error in this issue.

**Comment by erikras** [comment]
Pasting a decision from another issue. https://github.com/erikras/redux-form/issues/639#issuecomment-196408277

> This is a way in which redux-form is opinionated, but where it should not be. It's only a one-line change, but I wonder how many people have been relying on this functionality, thus making this a breaking change. There is another more pressing breaking change, #735, that needs addressing. I might throw this one in with that one.
