### ISSUE TITLE
Setting value for input type hidden

### ISSUE THREAD

**Issue by antoaravinth** [erikras/redux-form#528]
Hi, 

I have a scenario in which on click of a `Button` I want to set the value to the `input` field of type `hidden`(list of users, from which one will be selected on click of a button). I have view like this:

```
<Button bsStyle="primary" bsSize="large" onClick={this.setInputHidden.bind(this,"UserSelecedText")} >
    Select User
</Button>
<input type="hidden" value={this.state.selectedUser} {...user} />
```

And in the method `setInputHidden`, I'm setting up the `selectedUser` state, which now becomes the value of `input[type=hidden]`. 

I could able to see the value is being set to `input[type=hidden]` in my console, however the redux-form, doesn't capture this an change! 

Any guess how should I solve this issue?

**Comment by drouillard** [comment]
@antoaravinth  Can you try calling the hidden fields onChange event directly? See #152. 

Something like this in one of your event handlers, or in componentWillReceiveProps, etc. depending on where it makes sense for your use case.

``` javascript
user.onChange('value'); // assuming user is a redux form field contained at this.props.fields.user
```
I had to do something similar to normalize deep fields which is not currently supported. I had to set the value of the input and call the inputs onChange method. Alternatively you can call just onChange and next time a render happens the value should be updated.

**Comment by erikras** [comment]
Unless you are using some other library that depends on it, there is no reason to have a `<input type="hidden"/>` in your page. You can still include it in the `fields` array and just never assign it to an input element. To set the value, just call its `onChange` like @drouillard suggested.

**Comment by antoaravinth** [comment]
@drouillard : Thanks for your response. I guess this way it works

@erikras: True, I guess I no need to assign it to an input element, rather directly handle in the `fields` array. I have one more question, in the console I often see "redux-form/DESTROY" action fired many times. I'm not sure, why this happens or when it should happen. 

For example on doing : 
```
user.onChange('value');
```

At times DESTROY event happens and at times it doesn't happen. Any help?

**Comment by ooflorent** [comment]
This is a usage question, and we encourage you to ask it on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

This is the only way to ensure the same question doesn’t get asked many times in a row, and that folks who have the same question in the future will be able to find it.

I’m closing for these reasons.

**Comment by tugberkugurlu** [comment]
> You can still include it in the fields array and just never assign it to an input element. To set the value, just call its onChange like @drouillard suggested.

@erikras what's the suggested way to do this on v6?

**Comment by therise3107** [comment]
you guy can use this.props.fields.name.onChange(nameValue)

**Comment by cyuxlif** [comment]
@tugberkugurlu   same question

**Comment by leoi11** [comment]
Came across the same issue, and I'm temporarily resolving with a hidden field. This is due to the new versions' `reduxForm` decorator doesn't take fields as a prop anymore.
