### ISSUE TITLE
Handling custom form elements

### ISSUE THREAD

**Issue by mattydoincode** [erikras/redux-form#53]
I'm curious how one would go about using this library against a custom form element (whatever that element may be). Specifically how does one plugin to the `onBlur` and `onChange` events which expect synthetic events. I'm not sure if it's possible to generate custom react synthetic events (my searching proved fruitless although I'm not yet an expert in all this). Perhaps an override could be added for custom elements that accepts a more minimal api?

**Comment by mattydoincode** [comment]
https://github.com/erikras/redux-form/blob/master/src/reduxForm.js#L26 it seems you might already support this?

**Comment by erikras** [comment]
Yes. You can call `handleChange('name', value)` or `fields.name.onChange(value)`.

**Comment by mattydoincode** [comment]
thanks! Probably worth documenting as that's actually a fabulous feature.

**Comment by woniesong92** [comment]
@erikras where is `handleChange` available? The form's `props` doesn't seem to contain it.

**Comment by rcholic** [comment]
@woniesong92 , as far as I know, the `handleChange` API has been phased out since release version 3.0.0
