### ISSUE TITLE
How is returnRejectedSubmitPromise supposed to work?

### ISSUE THREAD

**Issue by dbismut** [erikras/redux-form#530]
Hey - I don't understand why the below doesn't work.

```javascript
<form onSubmit={event => handleSubmit(submitSignup)(event).catch(errors => console.log('ERRORS', errors))}>
```

The browser shows the error `Uncaught TypeError: Cannot read property 'catch' of undefined`, and then `Uncaught (in promise) Object {email: "This email has been taken"}` which does show the correct error.

This is my submitSignup method:

```javascript
export function submitSignup(values, dispatch) {
  return dispatch => {
    return new Promise((resolve, reject) => {
      dispatch(signUp(values.email, values.username, values.password, values.captcha,
        () => {
          resolve();
        },
        (err) => {
          reject({_error: 'there has been an error'});
          }
        }
      ));
    });
  }
}
```

Sorry for being a pain and thanks in advance for the help.

**Comment by Misaka42** [comment]
I think it relies on then(success(){}, error(){}) rather than catch.

**Comment by dbismut** [comment]
Hm. Well, I'm sorry, my mistake. `submitSignup` should directly return the Promise, not `dispatch`. Sorry about this.
