### ISSUE TITLE
Array of Objects passed through initialValues is always empty

### ISSUE THREAD

**Issue by colinexl** [erikras/redux-form#531]
Hello All,

I'm not sure if this is a bug or am I just doing something wrong. But I'm trying to initialize a Redux Form using the following `initialValues`:

```javascript
initialValues = {
  id: "d776f1ef-f260-403a-83ea-138f59d178d0",
  links: [{
    id: "deef6eff-af62-4a5c-a1a1-7b3f1dae6d73"
    link: "http://www.google.com"
  }, {
    id: "803d71da-5a69-4a57-ba56-8373d336c246"
    link: "http://www.apple.com"
  }],
  name: "link1"
}
```

I'm passing the `initialValues` in as a prop to the a Redux Form component, something like:

```jsx
<Form
        key={link.get('id')}
        formKey={link.get('id').toString()}
        name={link.get('name')}
        initialValues={initialValues}
        onSubmit={this.handleSubmit} />
```

Inside the `Form` component, I defined the following `fields`:

```javascript
export const fields = [
  'id',
  'links[]'
];
```

However, when I checked the `props` inside my `render` function, the `links` array is always empty. In my `render` function I have:

```javascript
const {
      fields: {
        id,
        links, // this is always just empty array
      },
      handleSubmit
    } = this.props;
```

I'm also using ImmutableJS and before I pass the object to initialValues, I'm using the `.toJS()` function to convert the Immutable Map to a normal JS object. As far as I can tell, it shouldn't be an issue.

Also, if I don't use `links[]` inside the `fields` and just do `links`. I do get the links from the `props`, however, they show up as a Javascript Object rather than an Array.

Any help would be appreciated!

EDIT:

Found something interesting, the `render` function is called twice. The first time the array is empty but the second time it has data in it. Not sure why this is the case but still digging around. Looks very similar to another issue about render being called twice. This seems like a duplicate and can be closed.

**Comment by erikras** [comment]
Looks like a bug. Will investigate. :mag:

**Comment by erikras** [comment]
The problem is that you're not specifying the shape of the link objects. You have two options:

### 1) Array value
If you want the value of your field to be an array, like if you have a custom component that expects an array value and will write back an array value. In which case your `fields` array should be:
```js
export const fields = [
  'id',
  'links', // <----- no brackets
  'name'
];
```
`this.props.fields.links` will be an object. `this.props.fields.links.value` will be your array.

### 2) `redux-form`-managed fields inside your array
If you want `redux-form` to manage the fields in your array, you will need to specify the shape of the array elements.
```js
export const fields = [
  'id',
  'links[].id',
  'links[].link',
  'name'
];
```
`this.props.fields.links` will be an array. `this.props.fields.links[0].link` will be a field.
```js
this.props.fields.links[0].id.value   === 'deef6eff-af62-4a5c-a1a1-7b3f1dae6d73'
this.props.fields.links[0].link.value === 'http://www.google.com'
this.props.fields.links[1].id.value   === '803d71da-5a69-4a57-ba56-8373d336c246'
this.props.fields.links[0].link.value === 'http://www.apple.com'
```
Does that help?

**Comment by colinexl** [comment]
Hi Erik,

Sorry I forgot to close this issue when I figured it out. I ended up using method number 2 from your reply. It worked perfects so it was definitely user error on my part.

Thank you for the reply nonetheless!

-Colin
