### ISSUE TITLE
Q: apply bootstrap by default

### ISSUE THREAD

**Issue by okigan** [erikras/redux-form#532]
I noticed when I use simple form example, none of the elements have bootstrap style applied, but when elements are replaced to react bootstrap (ex. input to Input) then everything start to show up correctly.

So, how do you apply bootstrap styles without using react-bootstrap ?

**Comment by erikras** [comment]
As it says on all the example pages:

> Styling has been removed for clarity.

The styles are really there [in the code](https://github.com/erikras/redux-form/blob/gh-pages/src/examples/SimpleForm.js#L24), but are [stripped](https://github.com/erikras/redux-form/blob/gh-pages/src/util/stripStyling.js) to make the code more readable in the "Code" section of the example page.
