### ISSUE TITLE
Access to initial values in onSubmit and/or onChange

### ISSUE THREAD

**Issue by slybridges** [erikras/redux-form#533]
Hello :wave:

I have case where what I send to the server depends on the Initial values of the form. Namely, if the user removes an element from a deep array form, I have to add the flag `_destroy: true` to that element so that the server knows it has to remove it (this is a default convention for Ruby on Rails submitted forms with nested models).

Unless I missed something, only way to do this at the moment is to manually pull the initial values from the redux store, which seems a bit hacky to me.

I would much prefer to have the `onSubmit` function be passed with the `initialValues` as a second argument. This could also be done for the `onChange` function, although it would make it less performant for my use case.

Thoughts?

**Comment by erikras** [comment]
In your `onSubmit`, you don't/can't have a reference to the object you used to initialize the form?

**Comment by slybridges** [comment]
Oh my, of course I can.
Pfff, sorry about that @erikras (next beer on me if ever you're planning to spend some holidays on the Riviera :wink:) 
Closing !
