### ISSUE TITLE
Get values from a checkbox group

### ISSUE THREAD

**Issue by zpdm** [erikras/redux-form#534]
I have a checkbox group for a deep nested field, e.g.: ```fruits[ ]``` which gets some ```fruits: [apple, orange, cherry,...]``` as ```initialValues```. 

```
{fruits.map((fruit, index) =>
       <div key={index}>
            <input
                  type="checkbox"
                  {...fruit}
             />
       </div>
)}
```

The problem is that instead getting only the values of the checked checkboxes in the fruits field, e.g.: ```fruits => [apple,cherry]``` , i get this: ```fruits => [true, orange, true,....]```. 
Or if i check and uncheck orange after this i get: ```fruits => [true, false, true, ....]```.

So check/uncheck a checkbox overwrites the values and the information in the fruits field is gone.

It would be great if the nested field would store only the values from checked checkboxes on submit.

**Comment by TonyVeigel** [comment]
I had issues with this and just ended up doing this. There is probably an easier way but don't know.

```
onChange={e => e.target.checked ? values.addField(e.target.value) : values.removeField(values.indexOf(e.target.value))
```

**Comment by zpdm** [comment]
Thanks for your help! Ended up with your approach without using ```initialValue```. Clearly a better way then checking the true/false array against the initial values.

```
var fruitsArray = [apple, orange, cherry,...]

{fruitsArray.map((fruit, index) =>
       <div key={index}>
            <input
                  type="checkbox"
                  value={fruit}
                  onChange={e => e.target.checked ? fruits.addField(e.target.value) : fruits.removeField(fruits.indexOf(e.target.value))
             />
       </div>
)}
```


Still the checkbox behavior in redux-form with setting the value from checked to the field value seems kinda strange to me.

**Comment by erikras** [comment]
See also: https://github.com/erikras/redux-form/issues/434#issuecomment-169171734

**Comment by rmlevangelio** [comment]
is `.addField` part of redux form?

**Comment by zpdm** [comment]
yes @rmlevangelio

**Comment by elodszopos** [comment]
Not sure why I was copied, but yeah, it used to be part of redux-form. Not certain in 6.0+, don't think it is anymore.
