### ISSUE TITLE
Cursor jumps to the end of normalized input when changing it in the middle

### ISSUE THREAD

**Issue by frost555** [erikras/redux-form#536]
http://erikras.github.io/redux-form/#/examples/normalizing
say you have phone input with value
123-456-7890
then you set caret in the middle and press backspace
123-45|6-7890

you input would look like
123-467-890|

any way to preserve cursor position?

**Comment by erikras** [comment]
I think the only way to do that is via the DOM node itself, which means you'll have to give it a `ref` and wrap the `onChange` in something that saves it, and then, _after_ next render (when the value has changed) updates it. Pretty inelegant.

**Comment by ryancbarry** [comment]
What about going about normalizing the field value earlier, at the point of input, rather than doing it at the reducer stage?  For example:

```javascript
render() {
    const { fields: {upper} } = this.props;
    const normalizedUpper = NormalizeField(upper, value => value && value.toUpperCase());
    return (
      <form>
        <input type="text" placeholder="Uppercase" {...normalizedUpper}/>
      </form>
    );
  }
```

Where `redux-form` could hypothetically provide a NormalizedField transform such as this:
```javascript
function NormalizedField(field, normalizer) {
  return {...field, onChange:(e) => {
    field.onChange({...e, value:normalizer(e.currentTarget.value)});
  }};
}
```

I've started using this normalization strategy (instead of the one prescribed at http://erikras.github.io/redux-form/#/examples/normalizing), and it appears to be working for me.  One advantage is that it naturally co-locates the normalizer with the form.  Another advantage is that we don't see the problem mentioned above.

Thoughts?

**Comment by ingshtrom** [comment]
FWIW, this happens in apps all over the place using all sorts of different technologies. The problem (from what I've seen when I worked with AngularJS) is that when normalization happens, you actually end up replacing the whole value. There is no way to update only a port of an inputs value. Even if it looks like you add one character, the DOM/browser/something-else-outside-of-your-control see's it as a whole value change. 

What you can do, and I *think* this would need to be done in framework itself (or a plugin), is save the position of the cursor and then update it after the value has change--is that what you were saying @erikras? Either way, when I researched doing that I read about a lot of people reporting inconsistencies when trying to do this across browsers.

It all really boiled down to a whole lot of work for very minimal gain. The app I was working on switched to `onBlur` validation and just restricting the characters that a user can input (if you can tell that it is bad input before it is actually inputted, then you don't trigger an `onChange` on the DOM node).

**Comment by traumatic** [comment]
In case of toUpper or toLower I suggest applying css style to the underlying input control of Field. E.g.
`<input ... style={{textTransform: 'uppercase'}}/>`
No cursor problems.

**Comment by tyrsius** [comment]
This [stackoverflow answer](http://stackoverflow.com/questions/28922275/in-reactjs-why-does-setstate-behave-differently-when-called-synchronously/28922465#28922465) provides a component solution that works with redux form

**Comment by yairniz** [comment]
set value(val) { // Set by external method
        if(val != this.state.value) {
            this.setState({value: val, randKey: this.getKey()});
        }
    }

    getKey() {
        return 'input-key' + parseInt(Math.random() * 100000);
    }

    onBlur(e) {
        this.state.value = e.target.value; // Set by user
        if(this.props.blur) this.props.blur(e);
    }
    
    render() {
        return(
    <input className="te-input" type="text" defaultValue={this.state.value} onBlur={this.onBlur} key={this.state.randKey} />
        )
    }

If you need an Input that's both editable without cursor move and may be set from outside as well you should use default value and render the input with different key when the value is changed externally.
