### ISSUE TITLE
Submit form on every field change

### ISSUE THREAD

**Issue by max-mykhailenko** [erikras/redux-form#537]
I have a form with inputs and custom inputs and want on every change save form. In documentation for custom fields I see
```
<MyStrangeInput 
        currentValue={{val: myField.value}}
        thingsChanged={param => myField.onChange(param.val)}/>
```
But on every change I want change value in `form.store` and run handleSubmit. I try to do this in the next way
```
<input
     {...fields.name}
     onChange={(data) => {
         fields.name.onChange(data);
         setTimeout(()=> handleSubmit());
     }}
/>
```
If I remove `setTimeout` function I got previous not actual value in `onSubmit` function.
How I can do that in more pretty way?

**Comment by max-mykhailenko** [comment]
One more thing, after updating initialValues variable I got `action redux-form/INITIALIZE @ 16:35:10.924`, my form handle all changes (I see actions in console) but in `input field` I didn't see any changes.

**Comment by erikras** [comment]
Yes, that's because `handleSubmit()` submits the data that the `react-redux` connector has given your form as props from the Redux state, which is not available until the next render. You will have to merge the new value into the existing values yourself.
```js
<input
  {...fields.name}
  onChange={event => {
    fields.name.onChange(event); // takes event or value
    handleSubmit({
      ...this.props.values,
      name: event.target.value
    });
  }}
/>
```

**Comment by CosticaPuntaru** [comment]
i found a good way to get form values on every field change

```
componentWillReceiveProps(nextProps){
  if (nextProps.dirty && nextProps.valid && nextProps.values !== this.props.values) {
     this.onFormFieldChange(nextProps.values);
    }
}
```

**Comment by max-mykhailenko** [comment]
@CosticaPuntaru thanks!

**Comment by iNikNik** [comment]
@erikras it seems like "merging values by myself" not working anymore?

**Comment by erikras** [comment]
@iNikNik I'm going to need more information about exactly what is happening.

**Comment by iNikNik** [comment]
@erikras I believe API was changed and now handleSubmit look lile:
```javascript
 handleSubmit(eventOrSubmit) : Function
```
And I can't pass form values:
```javascript
handleSubmit({
      ...this.props.values,
      name: event.target.value
    })
```

**Comment by tutok** [comment]
Wy input `onChange` can not update store synchronously? I would like to attach `handleSubmit`  to `onBlur` event and there is only one way (proposed by @max-mykhailenko) to do this in case of having some level of abstraction.

    const onBlurHandler = (event: any) => {
        if (!input.value && defaultValueIfEmpty) {
            input.onChange(defaultValueIfEmpty);
        }
        if (field.onBlur) {
            setTimeout(() => field.onBlur(event));
        };
    };

    return (
        <input {...field.input} {...rest} className={cssClassName} onBlur={onBlurHandler} />
    );

**Comment by lokhmakov** [comment]
With `6.0.0-alpha.4` works something like that:

```
class YourComponent extends React.Component {
  componentWillReceiveProps(nextProps) {
    const { values, handleSubmit } = nextProps
    if (this.props.values !== values) {
      handleSubmit(this.onSubmit)()
    }
  }

  onSubmit = (values) => {
    // Here u can change values as u want
    if (this.props.onSubmit) this.props.onSubmit(values)
  }

  render() {
    const { handleSubmit } = this.props
    return (
      <form onSubmit={ handleSubmit(this.onSubmit) } }>
        ...
      </form>
    )
  }
}

const formName = 'YourForm'

function mapStateToProps(state) {
  return {
    values: _.get(state.form, `${ formName }.values`, {})
  }
}

export default compose(
  connect(mapStateToProps)
)(YourComponent)
```

**Comment by Dimon70007** [comment]
Hello there!
Thanks for your hard work!
How about 6.7 version of redux-form? I have this code: 
```
function renderCombobox({ input, meta, ...rest }) {
  return (<div>
    <Combobox
      {...input}
      placeholder={input.name}
      {...rest}
    />
    {meta.touched &&
      ((meta.error && <span style={{ color: '#999' }}>{meta.error}</span>)
          // || (warning && <span>{warning}</span>)
      )}
  </div>);
}
//somewhere in my form
            <Field
              name='repo'
              component={renderCombobox}
              data={['repo1', 'repo2', 'repo3', 'repo4', 'redux-app1']}
              required
              onSelect={(value) => {
                props.change('repo', value);
                props.submit('leftSearch');
              }}
              filter='startsWith'
              handleSubmit={props.handleSubmit}
            />
```
The problem that the form submits old values when call submit on onSelect of Combobox component.  How i should call submit to submitting actual values?
P.S. sorry for my bad english.

**Comment by Lube** [comment]
Is there any on the works for this? maybe a callback on onBlur, maybe a promise?

**Comment by Dimon70007** [comment]
))) i just use setTimeout. With it don't change value also. Because it updates before submit's invoke.

**Comment by jbschrades** [comment]
This is my implementation with the new form `onChange` prop.  Couldn't find this spelled out anywhere.

```
<form onChange={() => setTimeout(handleSubmit(params => yourHandler(params)))}>
```

**Comment by damianobarbati** [comment]
@jbschrades where did you find docs about `onChange` on <Form /> component?

**Comment by jbschrades** [comment]
@damianobarbati I don't remember honestly.  I think I was going off https://github.com/erikras/redux-form/pull/2576

**Comment by zlove** [comment]
In redux-form 7, I am passing an onChange callback to reduxForm which invokes props.submit(). This is working for my use case. You could use the values and previousValues parameters to only submit when certain fields are changed.

```javascript
export default reduxForm({
    form: 'myForm',
    onChange: (values, dispatch, props, previousValues) => {
        props.submit();
    },
})(MyFormComponent);
```

**Comment by noahjohn9259** [comment]
try to declare a variable outside of your form component and debounce on your reduxForm options

`let timeout = null;  // declare outside of your component`

`export default reduxForm({
  form: 'myForm',
  onChange: (values, dispatch, props) => {
    clearTimeout(timeout);
    timeout = setTimeout(() => props.submit(), 1500);
  },
})(MyForm);`

**Comment by zlove** [comment]
@HristoKolev - glad you got it sorted out. Just to confirm, this was working for me in 7.2.x and still works in 7.3.0.

**Comment by alvelig** [comment]
I believe this is an more idiomatic way to do that
```
const form = 'SystemControls';

SystemControls = reduxForm({
  form,
  onChange: (values, dispatch) => {
    dispatch(submit(form));
  },
  onSubmit
})(SystemControls);
```

**Comment by tommyalvarez** [comment]
If i do that i get: Uncaught Error: You must either pass handleSubmit() an onSubmit function or pass onSubmit as a prop

**Comment by LiamKlyneker** [comment]
> If i do that i get: Uncaught Error: You must either pass handleSubmit() an onSubmit function or pass onSubmit as a prop

same here :(

**Comment by LiamKlyneker** [comment]
> In redux-form 7, I am passing an onChange callback to reduxForm() which calls props.submit(). This is working for my use case. You could use the values and previousValues parameters to only submit when certain fields are changed.
> 
> ```js
> export default reduxForm({
>     form: 'myForm',
>     onChange: (values, dispatch, props, previousValues) => {
>         props.submit();
>     },
> })(MyFormComponent);
> ```


in this onChange func how can I call a function that is in my component?, I mean to do things in there, like update another field based in other value.

**Comment by The-Code-Monkey** [comment]
If your getting the error its because the `props.submit()` or `dispatch(submit(form))` both rely on you passing the onSubmit function as props and if your not it throws this error. I think this function should be changed to work the same way handleSubmit works if it has no params then use the passed prop else use the passed function

**Comment by Multihuntr** [comment]
I'm using 8.1.0, and doing it like this:

```
export default reduxForm({
   form: 'myForm',
   onChange: (values, dispatch, props) => {
       props.submit()
   }
})(MyFormComponent)
```

doesn't completely solve it. Since the `submit()` is synchronous, it performs the submission before onChange is complete, so your form gets submitted with old values.

My (awful) solution is to `setTimeout(() => props.submit(), 0)` to make sure it waits until onChange finishes. Is there a better way?

**Comment by BenAhlander** [comment]
Can be done with lodash

const createReduxForm = reduxForm({
    form: 'listingForm',
    onChange: Lodash.debounce(onChange, 500),
    validate: validation_all,
});
