### ISSUE TITLE
using touchOnChange for a subset of fields

### ISSUE THREAD

**Issue by VinSpee** [erikras/redux-form#539]
Hi! I'd like to set `touchOnChange` to `true` for a subset of fields. is this possible? I have text inputs which i'd like to touch on blur, but select inputs I'd like to touch on change.

**Comment by erikras** [comment]
It's a little hacky, but you could potentially use `onBlur` for `onChange`.
```js
<input type="text" {...field} onChange={field.onBlur}/>
```
Maybe?

**Comment by VinSpee** [comment]
this worked wonderfully! thanks!
