### ISSUE TITLE
Validation in submission handler

### ISSUE THREAD

**Issue by morgante** [erikras/redux-form#54]
First off, thanks for making this helpful library.

I'm running into a bit of difficulty with how to handle working with backends where validation and creation aren't necessarily separate steps.

Specifically, in the case of many user registration forms the only way to test if a username is taken is to try registering that user. So there is only a single backend API available.

As far as I can tell, there are two potential places for putting this logic:

1. In an asynchronous validation handler. This works for doing validation, but it doesn't seem to be possible to dispatch actions from there (and also feels slightly wrong). For example, I can't find a clear way of dispatching the server-provided ID into the Redux state when working through the async validator.

2. The submission handler. This works for submission and dispatching of state, but there doesn't seem to be any way of invalidating a form in case the submission failed.

Thanks for clarifying the best way to do this! (My natural instinct would be to allow the submission handler to return a validation object.)

**Comment by erikras** [comment]
Yes, this is an excellent use case. One that I've been meaning to implement. The submit should definitely be allowed to return validation errors. In fact, I also reuse the same client side validation on the server side to double check against ajax naughtiness (e.g. someone altering the request manually).

Expect this feature in the near future.

**Comment by erikras** [comment]
Fixed in [`v1.5.0`](https://github.com/erikras/redux-form/releases/tag/v1.5.0).

Thanks for your feedback, @morgante.
