### ISSUE TITLE
Rerendering when field is emptied

### ISSUE THREAD

**Issue by jonathanasquier** [erikras/redux-form#545]
hey,

I'm trying to save a password in a field and empty it in my reducer on success update.
When other fields are dirty the password is correctly emptied, the behavior is the one expected, but if only the password field is dirty (it is empty on form initialize) I believe redux-form (or is it react?) thinks there is nothing to update (as the form is identical, empty password at first, empty password then) so my password field stays populated, and dirty. It there a way to force re-render?

thanks!

**Comment by hnordt** [comment]
I'm almost sure it's related to #547

**Comment by jonathanasquier** [comment]
Couldn't make it work by setting the password to empty string, the state when the password is untouched is still the same as when it is emptied.

**Comment by erikras** [comment]
Let me see if I understand. The steps to test this are:

1. Set initial values to `{myPass: undefined}`
2. Render `<input type="password" {...myPass}/>`
3. Enter some value into the password field.
4. Call `resetForm()`
5. See that password field still has data in it even though it shouldn't.

Is that right?

**Comment by jonathanasquier** [comment]
Not exactly, on the 4) step i submit m'y form, i get a response of the
updated user, in which userpass is empty.
As the userpass is the only field changed, both states before and after
submitting are identic. So step 5) happens.
Le 20 janv. 2016 11:44 AM, "Erik Rasmussen" <notifications@github.com> a
écrit :

**Comment by erikras** [comment]
After you "get a response of the updated user, in which userpass is empty", what do you do with it? Call `initializeForm()` or pass it as an `initialValues` prop?

**Comment by jonathanasquier** [comment]
My form has my user model as initialvalues on load, so i bet on the user
state update that redux-form reinits the form with new initialvalues?
Le 20 janv. 2016 11:54 AM, "Erik Rasmussen" <notifications@github.com> a
écrit :

**Comment by erikras** [comment]
And you can't replicate the same behavior on any other form field that is not `type="password"`. Related, maybe, to https://github.com/erikras/redux-form/issues/370#issuecomment-166593091?

**Comment by jonathanasquier** [comment]
No it's a type="text" actually.

**Comment by erikras** [comment]
Per the comment I linked to in my previous comment, I think you might have to dispatch `initializeForm()` yourself the second time. For all the reasons discussed in that issue.

**Comment by jonathanasquier** [comment]
So I've dispached initializeForm as said:

```
//action
export function updateUser(userId){
    return function(values, dispatch){
        API.updateUser(userId, values)
            .then(function(data){
                dispatch({type : UPDATE_USER_SUCCESS, values : values});
                dispatch({
                    type : 'redux-form/INITIALIZE',
                    form : 'userform',
                    data : values,
                    fields : _.keys(values)
                })
            })
            .catch(function(error) {
                dispatch({type : UPDATE_USER_FAIL, error : error});
            });
    }
};
```
Not quite fond of it, but it works as expected :)
