### ISSUE TITLE
onBlur issue

### ISSUE THREAD

**Issue by russellholmes** [erikras/redux-form#546]
I have a form that has a text input, checkbox, hyperlink and a submit button.
I want the form to be able to automatically validate the contents of the text input when i tab (blue) off the text input.
The issues is that when i click the hyperlink, the input is also validated as the input form which has focus has now lost it. when i disable the onblur validation, the only way i can validate is with the user pressing the submit button. Is there any way i can tell it to ignore certain elements or alternatively, is there another way i can do the validation?

**Comment by unodgs** [comment]
Very good question. I have the same problem

**Comment by erikras** [comment]
The problem is that you're getting `event.preventDefault()` that is stopping your click on the link?

**Comment by russellholmes** [comment]
And how would we work around this then?

Regards

Russell

**Comment by erikras** [comment]
Doesn't clicking from one input to another thing fire two events?

**Comment by russellholmes** [comment]
Sorry, no.

What happens in that if you were to have a hyperlink included on the form just as a bit of info - as soon as you click on the link, the validation would trigger as the form is onBlur - i know i can take the onBlue off but its nice to validate form input to input.

**Comment by erikras** [comment]
Okay, I'm not sure that I understand your problem. Can you show me some example code?

**Comment by russellholmes** [comment]
this wireframe may help

**Comment by erikras** [comment]
That was an email attachment? Github said NOPE.

**Comment by unodgs** [comment]
Let's say this is the form:
```
Username: ########
Password: #######

[Forget password link]
                   [Login]
```
Initial focus is on the username input. But user don't remember credentials and clicks Forget password link. And what happens is that login input looses its focus and validation is triggered and the error appears (in my case next to the username field). 
Desired behaviour would be to fire onBlur action only if focus is changed within some group of controls (in this case within username and password inputs). It would be great if that could happen only if particular input had some kind of attribute like: <input type='checkbox' validatable/> or if inputs would be grouped in special tag like: <BlurGroup><input/><input/></BlurGroup>. Hope it shads some light on the problem :)

**Comment by russellholmes** [comment]
Fantastic explanation. 

Russell Holmes

**Comment by grossmail1** [comment]
We are currently having the same issue with a form that also has a "Cancel" button.  If you have clicked in just one of the forms and then try to immediately hit cancel that first click is ignored and the error is thrown.  You are then able to click the button.

**Comment by nmaves** [comment]
We are also seeing this on one of our projects.

**Comment by erikras** [comment]
One thing you could do is set [`touchOnBlur`](http://redux-form.com/5.0.1/#/api/reduxForm) to be `false`. That would prevent all your fields from being marked `touched` when they get blurred, but they would still all be marked `touched` (a.k.a. show errors) on a failed submit. For a simple login form, this should be sufficient, don't you think?

**Comment by grossmail1** [comment]
Yeah, we made some changes so that the form is only validated when you hit the submit button.  We would really like it to be dynamic but a fix to the bug is that we wait until submit.

**Comment by nmaves** [comment]
Closed without a resolution?

**Comment by ooflorent** [comment]
There is a resolution! Actually multiple ones.

- `touchOnBlur` set on `false` would prevent the issue
- Removing autofocus on the input would also prevent it

Validation could be manually run when `handleSubmit` receives a `noop` function:

```js
// Run validation
this.props.handleSubmit(() => {})
```

Finally, this is not a Redux Form bug but a usage question and we try restrict GitHub issue to bugs.
