### ISSUE TITLE
resetForm is broken

### ISSUE THREAD

**Issue by hnordt** [erikras/redux-form#547]
It's only for me or resetForm is broken?

After I call resetForm() (as a prop) the reset form action is dispatched, but the component isn't updated with the empty values.

**Comment by babsonmatt** [comment]
Works here with latest

**Comment by hnordt** [comment]
That's very wierd:

It works:

```jsx
<textarea {...note} value={note.value || ''} rows={5} />
```

It doesn`t work:

```jsx
<textarea {...note} value={note.value} rows={5} />
```

note.value is set to undefined when resetForm() is called, for some reason when note.value is undefined the <textarea /> value isnt updated.

**Comment by babsonmatt** [comment]
@hnordt I'm using the first method you described (as per the redux-form docs)

**Comment by erikras** [comment]
Yep. From [Simple Example](http://erikras.github.io/redux-form/#/examples/simple): (https://github.com/facebook/react/issues/2533)

![redux form 2016-01-17 11-44-24](https://cloud.githubusercontent.com/assets/4396759/12377068/bb9b1828-bd0f-11e5-868c-f7f8d3e9df48.jpg)

If it's broken on any other type of input, let me know.

**Comment by nschurmann** [comment]
as for me, the textarea value is ↵ instead of an empty string. I'm calling it like:
```````
p.handleSubmit()
p.resetForm()
````````

**Comment by anselmdk** [comment]
Seems to me it' the same issue on select boxes, this fixed it for me: `<select {...Subject} value={Subject.value || ''}>`
