### ISSUE TITLE
Capturing Invalid Submission

### ISSUE THREAD

**Issue by tylerevans** [erikras/redux-form#548]
Hi

I am using Synchronous Validation. However my form is quite long.

If the form is invalid, how can I automatically scroll the user back to the top of the page. Otherwise, the user may not immediately see what is wrong.

I need similar to  "handleSubmit"   such as  "handleInvalidSubmit".

I don't want to validate on the fly (async).

**Comment by damassi** [comment]
One simple way would be to create a error component helper that accepts props for a specific field and, if invalid, scrolls the window to itself.

**Comment by ooflorent** [comment]
This is a usage question, and we encourage you to ask it on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

This is the only way to ensure the same question doesn’t get asked many times in a row, and that folks who have the same question in the future will be able to find it.

I’m closing for these reasons.
