### ISSUE TITLE
Dragging text into form field

### ISSUE THREAD

**Issue by MitchWeiss** [erikras/redux-form#550]
When dragging text from one form field to another, the destination field value will always change to "undefined".

**Comment by erikras** [comment]
That's a bug. Thanks.

**Comment by ooflorent** [comment]
@markuso did an excellent screencast to highlight the issue:

![drag-drop-issue](https://cloud.githubusercontent.com/assets/56903/13341252/f849ebbe-dc04-11e5-86d5-42d911de0cdd.gif)

**Comment by MitchWeiss** [comment]
This issue is present in v6 alpha 4 too except now the text in the destination field changes to the field name rather than undefined

**Comment by erikras** [comment]
I'm not sure _when_ this got fixed, but it no longer does this in `v6.0.0-rc.4`.

The drag doesn't _work_, exactly, but it doesn't munge your data anymore.
