### ISSUE TITLE
Hitting enter in an input field triggers addField / removeField

### ISSUE THREAD

**Issue by mikkelwf** [erikras/redux-form#551]
I noticed that the form i build with a nested array behaves oddly. When i focus any text field within the form, the addField or removeField callbacks are run, and are array changes.

I cannot really see whats going on, but the problem is also present in the example
http://erikras.github.io/redux-form/#/examples/deep
The addField on the phone array is triggered when hitting enter in any of the fields.

**Comment by erikras** [comment]
Discussion about this in #399. Not really sure what can be done about it...
