### ISSUE TITLE
Getter/Setter for value

### ISSUE THREAD

**Issue by rosendi** [erikras/redux-form#554]
Is it possible to transform a value before validation? For example user inputs a comma delimited list of emails like `user1@mail.com, user2@mail.com` and right before validation the getter transforms this  string to the `['user1@mail.com', 'user2@mail.com'`] array and vice versa.

**Comment by erikras** [comment]
[Normalizing](http://erikras.github.io/redux-form/#/examples/normalizing)?

**Comment by rosendi** [comment]
@erikras nope :-) It shouldn't change the html input value attribute. A getter is a function that returns a representation of the value on the form serialization, and a setter is a function that returns a representation of the value on the form deserialization (onSubmit). 

Let's say we have a model  with the `subscribers` property which is a comma delimited list of emails like I mentioned previously `{ subscribers: ['user1@mail.com', 'user2@mail.com'] }` and the form input `<input type="text" {... subscribers} />`. 

The setter should join the subscribers list to a simple string `setter = (value) => value.join(',')`. User will see in the input `user1@mail.com, user2@mail.com`.

User changes the input value to `user1@mail.com, user2@mail.com, user3@mail.com`

The getter should split it back, so the data passed to the `handleSubmit` method would be `{ subscribers: ['email1...', 'email2...', 'email3'] }.

**Comment by erikras** [comment]
Okay. So you need to intercept the `values` passed to your `onSubmit` function and fix them up as you wish.

**Comment by erikras** [comment]
And, inversely, do whatever formatting you need done before giving the value to `initialValues`.

**Comment by rosendi** [comment]
Yes.

**Comment by erikras** [comment]
So you're good?

**Comment by rosendi** [comment]
@erikras but this I have to perform transformation two times:

```
@reduxForm({
  validate: (values) => {
    let subscribers = values.subscribers.split(',') // etc... 
  }
}
```

and when again `handleSubmit(data => { data.subscribers.split(',')... })`.

Another option that with TypeScript a have to implement two interfaces: 

```
interfaceModelAttr { subscribers: string[] } 
interface FormModelAttr { subscribers: string } // used in `validate: (values: ModelAttr)` and ` handleSubmit((values: ModelAttr) => { ... })

**Comment by rosendi** [comment]
@erikras but this way I have to perform transformation two times:

```
@reduxForm({
  validate: (values) => {
    let subscribers = values.subscribers.split(',') // etc... 
  }
}
```

and when again `handleSubmit(values => { values.subscribers.split(',')... })`.

Another option that with TypeScript a have to implement two interfaces: 

```
interface ModelAttr { subscribers: string[] } 

interface FormModelAttr { subscribers: string } // used in `validate: (values: FormModelAttr)` and ` handleSubmit((values: FormModelAttr) => { ... })
```

Maybe I wasn't clear enough.

**Comment by erikras** [comment]
I'm confused. Let me restate what I think you mean, and you tell me if I'm correct. You want the equivalent DOM of:
```js
<input type="text" name="subscribers" value="user1@mail.com, user2@mail.com"/>
```
To result in the value sent to the server to be:
```js
{
  subscribers: [
    'user1@mail.com',
    'user2@mail.com'
  ]
}
```
Yes?

**Comment by rosendi** [comment]
Yes. But I don't want to perform this transformation inside the `handleSubmit` method. I want to perform it right before validation.

P.S. In Angular1 it's called getter/setter, In Angular2 it's called accessors.

**Comment by erikras** [comment]
Okay, I understand you now. I had to do this for a multi [react-select](http://jedwatson.github.io/react-select/) component, which wanted a comma-delimited string as the value, but I wanted an array of strings in my store and database.

You need to wrap your input in a component that does the transformation from its `this.props.value` (a `join(',')`) and in its `onChange` (a `value.split(',')`). That way `redux-form` only ever gives and receives the array of strings.

That make sense?

**Comment by rosendi** [comment]
It does. I'll try... Thank you for your time!
