### ISSUE TITLE
change dispatch property getting removed

### ISSUE THREAD

**Issue by arolson101** [erikras/redux-form#555]
I have a reduxForm with a mapDispatchToProps that adds a method "change" (mapped to reduxForm.change), but it doesn't end up on this.props.  If I rename it to "props2" then it does.

```js
@reduxForm.reduxForm(
  ...
  (dispatch) => bindActionCreators({
    change: reduxForm.change
  }, dispatch)
)
```

this was working when I was using ```@connect``` with the mapDispatchToProps

**Comment by erikras** [comment]
I'm very confused.

1. Your `...` there is implying that the `mapDispatchToProps` is the _third_ parameter?
2. You needn't use `bindActionCreators` at all. Just `{change: reduxForm.change}` would do.
3. Why would you be binding the `change` action creator, when `redux-form` specifically gives you the `this.props.fields.whateverField.onChange` function?

**Comment by arolson101** [comment]
1) yes, 3rd parameter
2) I don't want the change action creator, I want the change bound to a dispatch
3) I want to change the value of a field programmaticaly

so if I change the above example to ```change2: reduxForm.change``` I can later do ```this.props.change2("myform", "fieldName", "new value")```.  If I leave it as ```change``` then ```this.props.change``` is undefined

**Comment by erikras** [comment]
2) Yes, of course. Bound to `dispatch`.

You should call `this.props.field.fieldName.onChange(`new value') to "change the value programmatically".

**Comment by arolson101** [comment]
I hadn't considered that.  It feels wrong to call an object's event handler directly, but I suppose that this is an event, of sorts.  I'll try it out.

**Comment by erikras** [comment]
It's wired _directly_ to the dispatch of the action. Worry not. :smile:

**Comment by vkrol** [comment]
@erikras Hello! Please, can you explain me, why ``{change: reduxForm.change}`` is not working?
