### ISSUE TITLE
syncBlurFields option

### ISSUE THREAD

**Issue by bdefore** [erikras/redux-form#56]
Would it be possible to have a `syncBlurFields` option akin to `asyncBlurFields` ?

**Comment by bdefore** [comment]
or i suppose `blurFields` is more in line with naming. `validateFieldsOnBlur` and `asyncValidateFieldsOnBlur`?

**Comment by bdefore** [comment]
Ah ha, I believe that this happens automatically as long as you have `onBlur={handleBlur(myVariable)}` set up, per the docs on `asyncBlurFields` ... perhaps that should be documented elsewhere too?

**Comment by erikras** [comment]
It sounds like you've worked this out, but yes, if you have `touchOnBlur` enabled (it defaults to enabled), then `handleBlur('myField')` will mark that field as `touched`. In reality, the validation happens _on every `render()`_, but if you follow the docs, the errors will only be shown when the field is `touched`, so it will _appear_ as though validation only happens on blur.

Does that clarify anything?

**Comment by bdefore** [comment]
yup, that works just fine for any case i can think of. fine to close this. thanks!

**Comment by erikras** [comment]
:+1:
