### ISSUE TITLE
reset to "latest" initialValues

### ISSUE THREAD

**Issue by rhythnic** [erikras/redux-form#561]
After updating initialValues and then resetting the form, the the form resets back to the original initialValues and not the latest initialValues.  Is this the intended behavior?

When a new user is selected, I'm using the form plugin to return undefined
```
UserForm: (state, action) => {
    switch(action.type) {
      case 'LOAD_TARGET_USER':
        return undefined;
      default:
        return state;
    }
  }
```

and loading initial values through mapStateToProps.
```
export default reduxForm({form: 'UserForm', fields},
(state) => { return {initialValues: state.user.target} })
(UserForm);
```

Both resetForm() and destroyForm()+initializeForm(targetUser) reset the user info to the first user that was selected, instead of the most recent.  Is there a better way to do this?

**Comment by rhythnic** [comment]
Fixed this issue by setting targetUser to null when a userId is selected then load selected user object in a following action.

**Comment by Aaronius** [comment]
This seems to be my problem as well. I'm not using a form plugin.

**Comment by Aaronius** [comment]
Nevermind, my problem was that when I resetting the form I was calling:

`store.dispatch(reset());`

Rather than passing the form name:

`store.dispatch(reset('formName'));`

**Comment by erikras** [comment]
> Is this the intended behavior?

Yes. https://github.com/erikras/redux-form/issues/370#issuecomment-166593091

**Comment by elisechant** [comment]
The "workaround" if anyone is wondering, is to use `enableReinitialize=true` on props.

**Comment by alllx** [comment]
To reset form from outside of ReduxForm component:
`
import { reset } from 'redux-form';
mapDispatchToProps(dispatch) {
  return {
    resetForm: dispatch(reset('FORM_NAME')),
  }
}
`
To reset form inside ReduxForm component:
`this.props.reset();`

**Comment by eaconde** [comment]
I'm not sure why but setting the enableReinitialize=true doesn't work on my case. However, manually triggering the reset on the form does.
