### ISSUE TITLE
How to handle custom `onClick` action?

### ISSUE THREAD

**Issue by colinexl** [erikras/redux-form#563]
Hello,

I'm using redux-form to display a list of objects so that I can edit all the objects on a single page. Since I'm using multiple forms on the same page, I'm utilizing each object's unique ID as the `formKey`.

The form itself is pretty basic but has a "Save" and a "Delete" button. I'm also using the `mapDispatchToProps` to map the action creators to the buttons. The "Save" button is straightforward and maps `handleSubmit` to the `onSubmit` action. The "Delete" button's `onClick` maps to a custom "delete" action.

When the "Delete" button is clicked, I want to delete the object with the unique ID that is used as the `formKey`. However, since I'm still new to react/redux/redux-form, I'm not sure what the best way is to get the `formKey` as arguments to the `onClick` handler.

One way I thought is to attach a `data-object-id` to the "Delete" button so that I can grab the ID using jQuery.data().

Another is to re-use the `handleSubmit` function and determine if "Save" or "Delete" was clicked and handle accordingly.

However, both methods seem hacky. I was wondering if there was a more "react" way to do this?

Thanks,
Colin Zhu

**Comment by colinexl** [comment]
I think I figured out a better way by binding the 'this' context to the click handler and was able to access the `formKey` directly from there.

**Comment by erikras** [comment]
Yep. You got it.
