### ISSUE TITLE
Allow to specify warnings as validation result

### ISSUE THREAD

**Issue by kromit** [erikras/redux-form#564]
It would be nice to have the ability to specify field props `warning` and evtl. `info` besides the `error` prop.

     validate(data)
         const errors = {};
         const warnings = {};

         doSomeValidation(data,errors,warnings)           

         return {errors,warnings}
     }

evtl. with some prebuild messages state so stay align with redux 

    validate(data,messages)
         
         messages = doSomeValidation(data,messages)  
         messages = doSomeOtherValidation(data,messages)             

         return messages; // {errors,warnings}
     }

**Comment by ooflorent** [comment]
You can add this kind of information to Redux Form using [`reduxFormReducer.plugin()`](http://redux-form.com/5.2.1/#/api/reducer/plugin?_k=y8h23g) API.
Unfortunately the document about it is not very detailed.
