### ISSUE TITLE
Dispatching async action after a field change

### ISSUE THREAD

**Issue by adros** [erikras/redux-form#566]
What is the best way to dispatch an async action (using thunk or promise middleware) after a field in (redux) form has changed?

E.g. I need to recalculate field `b` after field `a` has been changed. If the recalculation was synchronous, I wouldn't have this problem - I would add a reducer, which would check if current action is `redux-form/CHANGE` and if the `form` and `field` attributes matches what I need, and then set the new state (maybe this approach is not good as well, should I do it in another way?).

But how should I implement this logic if the recalculation is async (e.g. needs to be calculated on server)? I may not dispatch an async operation in reducer, which should be a pure function.. Should I add a store subsciption somewhere (where?) and check if field `b` the store has been changed and dispatch action? Or should I wrap onChange handler to dispatch another action beside the redux-form one?

**Comment by erikras** [comment]
> Or should I wrap `onChange` handler to dispatch another action beside the redux-form one?

That's the winner. :trophy:

**Comment by Amdingo** [comment]
Is there an example of this floating around somewhere?  Coming up with the same issue where I want to fire Relay's setVariables based on the onChange of a Select Component but...I'm lost.

**Comment by thomasmery** [comment]
Hi there,

I too am a bit lost with this

I'm trying to find out what's the best way to dispatch an async action (via thunk middleware action creator) from an onChange event on a form

I ended up 

- importing an action creator - updateUser - via the 3rd parameter of the reduxForm call
```js
export default reduxForm(
	{ 
	  form: 'user', // a unique name
	  fields: ['firstname', 'lastname', 'email', 'password'] // the fields	},
	state => {},
	{ updateUser }

)(UserForm);
```
- creating a wrapper function around the action creator dispatch
```js
let _handleUpdate = (e) => {
		updateUser(firstname, lastname, email, password) 
	}
````
- using this function as the form onChange handler 
```
<form onChange={_handleUpdate} >
```

so far so good I think but I'd like to know how to easily get form fields value from there (in the handler)

as for now I tried using the fields props (firstname ... ) but they're of course not updated as the component has re-rendered at that stage

any one can help on this?

I guess it's just a matter of collecting values but is there some function built in that I can use?

thanks for any help on this

**Comment by thomasmery** [comment]
update:

my `_handleUpdate` code has evolved to : 
```js
let _handleUpdate = (e) => {
  updateUser(_id, active, getValue(e));
};
```
where 
- `_id` is a custom id for my form (as I have several on the page)
- `active` is derived from `props.active` which is a string representing the active field (passed to my decorated form by redux-form)
- `getValue(e)` is using the `redux-form/lib/events/getValue`which nicely returns the value of the target field held by the event passed to the update handler

this seems to be working for me now

hope this helps

please correct/suggest

**Comment by erikras** [comment]
That all seems okay, @thomasmery.
