### ISSUE TITLE
Pass submitFailed option down to fields

### ISSUE THREAD

**Issue by adamalbrecht** [erikras/redux-form#567]
It would be nice if the `submitFailed` prop was passed down to the input fields so that we can have a bit more control over when validation messages are displayed. Right now my logic is `error && (touched || dirty)`, but ideally it would be `error && (submitFailed || dirty)`. This way, validation messages don't pop up just because a user tabs through a field or accidentally clicks outside the field, causing it to blur.

Anyway, thanks for the great library! I'd be happy to submit a pull request for this, but let me know what you think.

**Comment by adamalbrecht** [comment]
And actually now that I'm thinking about it, I don't think the current behavior of setting the `touched` flag for each field upon submit really makes sense. Because that isn't actually what happened. I didn't touch the field - the submit failed - so that's what I should be using to determine whether to show the error. Of course, this would be a bigger (and breaking) change.

**Comment by x1a0** [comment]
I am facing exactly same problem right now. @adamalbrecht Did you find out any elegant way for this?

**Comment by erikras** [comment]
> I don't think the current behavior of setting the touched flag for each field upon submit really makes sense. Because that isn't actually what happened.

Interesting. I agree that it would be more explicit to have a `submitFailed` boolean on all the fields.

**Comment by x1a0** [comment]
@erikras +1 on this. I am manually passing down `submitFailed` now :+1:

**Comment by adamalbrecht** [comment]
@x1a0 Yeah I'm just manually passing it down too

**Comment by JMacLulich** [comment]
Did this get actioned? I'm also manually passing down `submitFailed` on v6.1.1.

**Comment by erikras** [comment]
Published fix in [`v6.4.3`](https://github.com/erikras/redux-form/releases/tag/v6.4.3).
