### ISSUE TITLE
Multi-record forms 

### ISSUE THREAD

**Issue by TonyVeigel** [erikras/redux-form#569]
I setup a form, following the multi-record form example, but it seems that when I submit one of the forms and my store gets updated, some of the other forms on the multi-record  form update with the same information as the form that is filled out, not all, but some. I know this is not much information but wondering if anyone else has experienced this? I am using formKey and everything just like the multi-record form example but maybe I am misunderstanding what that is supposed to be used for? Any help is appreciated. Thanks!

**Comment by TonyVeigel** [comment]
Never mind own mistake. Great work by the way, makes complicated forms easier.

**Comment by erikras** [comment]
Thanks, @TonyVeigel!
