### ISSUE TITLE
Submit a form when user press enter.

### ISSUE THREAD

**Issue by nschurmann** [erikras/redux-form#572]
I have the following form:
``````````
/**
 * React component MessagesForm
 */

import React, { PropTypes } from 'react'
import {reduxForm} from 'redux-form'

const MessagesForm = p => {
  const {fields: {message}, handleSubmit} = p
  
  const addMessage = e => {
    if(e.keyCode == 13 && e.shiftKey == false) {
      handleSubmit()
    }
  }

  return (
    <form onSubmit={handleSubmit}>
      <div className="form-group">

        <textarea
          {...message}
          value={message.value || ''}
          rows="1"
          type="text"
          className="form-control"
          onKeyDown={addMessage}
          placeholder="Escribe tu mensaje y presiona Enter para enviar." />

      </div>
    </form>
  )
}

const form = reduxForm({
  form: 'message',
  fields: ['message'],
})(MessagesForm)

export default form
```````````````
How do i get the values in the handleSubmit function?

**Comment by erikras** [comment]
Read the `handleSubmit` section of [this docs page](http://erikras.github.io/redux-form/#/api/props), and let me know if you still have questions.

**Comment by erikras** [comment]
As for your `addMessage()` function...
```js
const addMessage = e => {
  if(e.keyCode == 13 && e.shiftKey == false) {
    handleSubmit(p.values); // <--- all the form values are in a prop
  }
}
```

**Comment by nschurmann** [comment]
thanks @erikras !!! checking it now...

**Comment by nschurmann** [comment]
@erikras what i still don't get is how, after the validations, i can call my thunk to do async tasks. Any pointer with this?

**Comment by nschurmann** [comment]
When y try to pass a custom function "handleSubmit" or "onSubmit" it seems that redux-form overwrite this methods. Should i avoid this names or there is something that i miss?

**Comment by erikras** [comment]
`onSubmit` is the prop you pass to your decorated form component.
`handleSubmit` is the prop that redux-form gives to your wrapped component to call from a button press or something.

**Comment by nschurmann** [comment]
thanks @erikras , but i'm still not sure how to call it, in the documentation doesn't says how it is supossed to be called the callback that i provide to actually do something with the validated data. Unless there is something that i'm missing?

**Comment by nschurmann** [comment]
Ok... so it seems that i figured out..

The function handleSubmit it seems to be used to run all the defined functions that you pass to the reduxForm function imported from redux-form. After all this functions are executed redux-form will execute the function that you passed to the handleSubmit function

`````````
return (
    <form onSubmit={handleSubmit(theFunctionYouWantToRun)}>      <--    HERE!!!
      <div className="form-group">

        <textarea
          {...message}
          value={message.value || ''}
          rows="1"
          type="text"
          className="form-control"
          onKeyDown={addMessage}
          placeholder="Escribe tu mensaje y presiona Enter para enviar." />

      </div>
    </form>
``````````
if you have a parent component, lets say Messages, and a child component (in this case MessagesForm) and you pass a prop called onSubmit like this:
`````````
<MessagesForm onSubmit={e => console.log(e)} />
``````````
and call onSubmit or handleSubmit, it WON'T log anything. So you need to pass it through a different prop.

**Comment by nschurmann** [comment]
nope, wrong, the API tells the correct use:
http://erikras.github.io/redux-form/#/api/reduxForm?_k=y64wh6

Please consider adding this to the examples.

**Comment by thg303** [comment]
broken links

**Comment by jameelahuq** [comment]
Hey! This was so helpful! This is what I ended up doing. It worked like a charm: 

```export class CreateMessage extends React.Component {

  handleKeyDown = function (e, cb) {
    if (e.key === 'Enter' && e.shiftKey === false) {
      e.preventDefault();
      cb();
    }
  };

  render() {
    const { handleSubmit } = this.props;
    const form = (
      <form
            onSubmit={handleSubmit}
            onKeyDown={(e) => { this.handleKeyDown(e, handleSubmit); }}
      >
          <textarea placeholder="Type your message..." autoComplete="off" {...text}  />
        </div>
        <button type="submit"><span>send</span></button>
      </form>
    );
    return form;
  }
}```

**Comment by hasSean** [comment]
For the poor soul who like me ended up here with a slightly different problem, I'll leave a note. If you want your form to NOT submit when someone hits enter in an input, but still allow your text inputs to do things on enter (like for example to apply a link to some text in a rich text editor), make sure you don't have any buttons with type="submit" and move your handleSubmit logic from the form to the button.

Here's an example of the transition I made in my code.

```
<form onSubmit={handleSubmit(this.whatIWantToRunOnSubmit)}>
  ...stuff

  <Button
    type="submit"
  >
    Create
  </Button>
</form>
```

turns to
```
<form>
  ...stuff

  <Button
    type="button"
    onClick={handleSubmit(this.whatIWantToRunOnSubmit)}
  >
    Create
  </Button>
</form>
```
