### ISSUE TITLE
Dev Tools monitor in documentation page does not render

### ISSUE THREAD

**Issue by gustavjf** [erikras/redux-form#573]
`bundle.js:41 Redux DevTools could not render. Did you forget to include DevTools.instrument() in your store enhancer chain before using createStore()?`

![screen shot 2016-01-20 at 5 21 06 pm 2](https://cloud.githubusercontent.com/assets/3981598/12455058/662e4e5e-bf9a-11e5-9267-4c1c93d9b0a7.png)

This was intermittent. At one point it was working today, then it was not. Eventually, I wasn't able to get it back to a working state.

**Comment by erikras** [comment]
Hmmm... It's not doing that for me... :frowning:

**Comment by gustavjf** [comment]
Restarting laptop, crossing fingers :)

**Comment by gustavjf** [comment]
Just tried it again, on multiple browsers and on a different computer. Same error, odd...

**Comment by erikras** [comment]
Aha! I'm using [redux-devtools-extension](https://github.com/zalmoxisus/redux-devtools-extension) (which I _highly_ recommend, btw), so I wasn't seeing it. Thanks! Will investigate... :mag:

**Comment by gustavjf** [comment]
Pleasure! Thanks for the quick fix.
