### ISSUE TITLE
Uncaught Invariant Violation: traverseParentPath(…): Cannot traverse from and to the same ID, ``

### ISSUE THREAD

**Issue by gfpacheco** [erikras/redux-form#575]
Would you please take a look at this: http://stackoverflow.com/questions/34914922/uncaught-invariant-violation-traverseparentpath-cannot-traverse-from-and ?

I'm facing an issue and I think one of these three libraries could be causing it: redux-form, material-ui and parse.

**Comment by ooflorent** [comment]
This is a usage question, and we try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

I’m closing for these reasons.
