### ISSUE TITLE
Setting field to object with value property

### ISSUE THREAD

**Issue by cjhveal** [erikras/redux-form#576]
Hello,

I currently have a form that uses [react-selectize](https://github.com/furqanZafar/react-selectize) to perform autocompleting select fields. That library expects values to take the form: `const item = {label: 'label', value: 'value'}`. However, when I call `field.onChange(item)` I get `'value'` as the updated state.

The field that I'm using is of the form: `'parent[].child'`.

My guess is that my value here mimics the shape of an event and when the onChange handler is called it tries to pull the value out, updating the state with the string under the `value` key.

Thank you for your awesome contribution to the redux ecosystem.

**Comment by erikras** [comment]
Please read https://github.com/erikras/redux-form/issues/82#issuecomment-142393045 and [Will redux-form work with my custom input component?](http://erikras.github.io/redux-form/#/faq/custom-component), and let me know if you still need help.

**Comment by cjhveal** [comment]
Hi Erik,

Thanks for the relevant resources. That certainly helped one piece of the puzzle that I was confused about (this library was calling onBlur without a value after a selection...). However, I'm still seeing the value being set to the string under the `value` key of the object I'm passing to `onChange`.

In other words -- I'm calling `onChange` with `{value: 'value', label: 'label'}` and I see in redux devtools that the `redux-form/CHANGE` action is fired with `'value'` instead of the object that I called `onChange` with.

**Comment by slybridges** [comment]
hi @cjhveal,

This is because of this: https://github.com/erikras/redux-form/blob/master/src/events/getValue.js#L37-L39
Same problem arises with any library sending objects with `value`keys like `react-select`

What I did is to wrap the library into a custom component like this (this is an example for `react-select`but I guess it would be similar for `react-selectize`):

```javascript
export default class CustomSelect extends Component {
  static propTypes = {
    onBlur:   PropTypes.func.isRequired,
    onChange: PropTypes.func.isRequired,
    value:    PropTypes.any
  };

  handleChange(value) {
    if (!value) return this.props.onChange(null)
    // if value has a value key, must wrap value and overwrite onChange because of
    // https://github.com/erikras/redux-form/blob/master/src/events/getValue.js#L37-L39
    return value.value ? this.props.onChange({ value }) : this.props.onChange(value)
  }

  handleBlur() {
    // https://github.com/JedWatson/react-select/issues/489
    const { value } = this.props
    if (!value) return this.props.onBlur(null)
    return value.value ? this.props.onBlur({ value }) : this.props.onBlur(value)
  }

  render() {
    const { value, onBlur, onChange, ...otherProps } = this.props
    return (
        <Select
          // see https://github.com/JedWatson/react-select/issues/488
          value={value || ''}
          onChange={::this.handleChange}
          onBlur={::this.handleBlur}
          {...otherProps}
        />
  )}
}
```

**Comment by cjhveal** [comment]
Awesome -- thanks for the help here.

I did try the value wrapper above but I was missing it in the custom blur handler too.

**Comment by cjhveal** [comment]
Even though that closes out my specific issue -- I'm just wondering if it says anywhere in the docs about complex values that passing in an object with a value key will behave like this? From the code it looks like it's for compatibility with the belle library (which I did see mentioned in the docs, but didn't realize that their `onUpdate` was any different than `onChange` besides the name).

I imagine this is a holdover from when form values were strings and booleans, but now that complex values are allowed, it does muddy the waters a bit. Perhaps `onUpdate` should unwrap value objects whereas `onChange` should simply accept the value? If I understand correctly, the belle library changed the name because it was no longer a consistent interface. Treating them as equal here and changing the implementation of `onChange` seems to go against the spirit of a separate interface.

I'd be happy to make a pull request that makes those interfaces more consistent with their original implementations. I understand that'd be a breaking change though, so I'd be equally happy to update the docs to be slightly more clear about how values passed in are handled.
