### ISSUE TITLE
initializeState does not accept object values

### ISSUE THREAD

**Issue by cdevienne** [erikras/redux-form#577]
Related to #576, setting a initial value with an object is not possible. The object will be handled as nested values no matter what.

I wanted to manipulate 'moment' objects in a form, and could not find a way to do so : I have to convert it to a string for redux-form.

It would be nice to be able to pass object as values. May be by passing the field list to initializeState so it can detect if an object is a value or nested values ?

If that makes sens I can try & submit a patch.

**Comment by erikras** [comment]
Can you please provide your `fields` array and the value of the `initialValues` prop.

**Comment by cdevienne** [comment]
I added a 'birthDate' field to the survey form of react-redux-universal-hot-example.
Here is a screen shot of the interesting parts for the INITIALIZE message handing:

![capture d ecran de 2016-01-22 10 28 20](https://cloud.githubusercontent.com/assets/547135/12506959/e3c9f22e-c0f2-11e5-83e4-3b7cbcec7159.png)

As you can see, the initialValue is a moment instance, but it gets splitted in nested values by the reducer.

Here are the modifications I made to react-redux-universal-hot-example:

```diff
diff --git a/src/components/SurveyForm/SurveyForm.js b/src/components/SurveyForm/SurveyForm.js
index 7bcc9bb..b5a131a 100644
--- a/src/components/SurveyForm/SurveyForm.js
+++ b/src/components/SurveyForm/SurveyForm.js
@@ -26,7 +26,7 @@ function asyncValidate(data) {
 
 @reduxForm({
   form: 'survey',
-  fields: ['name', 'email', 'occupation', 'currentlyEmployed', 'sex'],
+  fields: ['name', 'email', 'birthDate', 'occupation', 'currentlyEmployed', 'sex'],
   validate: surveyValidation,
   asyncValidate,
   asyncBlurFields: ['email']
diff --git a/src/containers/Survey/Survey.js b/src/containers/Survey/Survey.js
index 0473f87..1cf8f51 100644
--- a/src/containers/Survey/Survey.js
+++ b/src/containers/Survey/Survey.js
@@ -3,6 +3,7 @@ import {connect} from 'react-redux';
 import Helmet from 'react-helmet';
 import {initialize} from 'redux-form';
 import {SurveyForm} from 'components';
+import moment from 'moment';
 
 @connect(
   () => ({}),
@@ -21,6 +22,7 @@ export default class Survey extends Component {
     this.props.initialize('survey', {
       name: 'Little Bobby Tables',
       email: 'bobby@gmail.com',
+      birthDate: moment(),
       occupation: 'Redux Wizard',
       currentlyEmployed: true,
       sex: 'male'
```

**Comment by sattaman** [comment]
also related to #404

**Comment by cdevienne** [comment]
The issue is actually related to v3. The latest release works as expected.

Sorry for the noise.
