### ISSUE TITLE
initialValues no longer "syncs" data with state

### ISSUE THREAD

**Issue by andynoelker** [erikras/redux-form#578]
I just updated to `v4.1.5`. Previously when I set `initialValues` for a component, if the bit of state that informed `initialValues` ever changed, it would "sync" or overwrite the data for the redux form properties. Now, while it does initially load data from your state, it never updates anything again unless you force it to with a `resetForm()` call.

I have read all of #370 as well as the past few release notes and it appears that this change in behavior was intentional. I totally agree with everyone that calling that property `initialValues` when it did more than just initialize values was really confusing. **However**, I don't think that means we should completely drop the option to use that type of functionality. Could we keep `initialValues` working the same way that it does now (just initializes values, nothing more) but add something new that both initializes values and updates those values when the source piece of state changes. In essence it would link or sync your redux form component to a piece of state, just like how `initialValues` used to work.

At the moment, the only workaround I can see is to use `initialValues` and then find every place that its corresponding piece of state could change and add a `resetForm()` call. I can totally foresee an instance where this solution wouldn't work so well, if you had a component that modified that piece of state that was not connected to redux form at all, but you wanted the change reflected in your redux form component.

**Comment by frost555** [comment]
Maybe you should try to modify field values with reducer.plugin functionality?
http://erikras.github.io/redux-form/#/api/reducer/plugin

**Comment by andynoelker** [comment]
I don't think using `reducer.plugin` really works for this situation because I'd need to access other areas of the state outside of the `form` property. However even if I could do that, I would essentially be writing all of my reducers twice because I'd have one for the original state change and another that used those values to modify the form values.

I agree with everyone in #370 that calling that value `initialValues` was confusing. But just because something has a confusing name does not mean that whole piece of functionality should be nuked! It seems like that's precisely what a few people convinced @erikras to do though. So while I'm fine with the new `initialValues` working closer to what its name suggests, why can't we still have the old type of functionality with a new name? Being able to link a piece of state to a form component beyond initialization is really useful.

**Comment by morgante** [comment]
@andynoelker If you want to change the values of a form, shouldn't you be resetting it in the process?

`initialValues` serves an essential and useful purpose of providing default values for a form. It shouldn't be hacked into a way of *overwriting* values and I don't think any reasonable interpreter would see that as the intention. If you want to overwrite values, why not just explicitly overwrite or reset them?

**Comment by andynoelker** [comment]
@morgante Having a way to initialize the form with data from the state with default values is indeed useful and I am in no way arguing to take that piece of functionality away. Also I totally agree that if you use something called `initialValues` you wouldn't expect it to overwrite data after initialization.

What I *am* saying is that having a *different* property that works in the way `initialValues` used to work would be incredibly helpful. Maybe call it `syncValues` or something like that. I don't think the usage for that is any edge-case either, considering it took until #370 before anyone had any issues with the old usage. And check out #588 - I'm not the only one surprised that suddenly their app has broken and now we have to implement more tedious measures to accomplish the same thing. And sure, we can find every place that our state changes and manually reset the form there. But why add all of that extra work? And it gets more complicated if you can affect your piece of state in a separate component that doesn't touch Redux Form at all and want those changes reflected in your form. Sure, you can use `reducer.plugin` as pointed out above, but that just adds another level of verbosity to your code. I'd really love to hear if @erikras has any thoughts on this.

**Comment by aselbie** [comment]
Would like to toss in my two cents in favor of the type of functionality that @andynoelker is requesting. It's currently working for me to use ``.then( () => initializeForm(values) )`` in my submit function, but I can see there being limitations to this approach.

**Comment by morgante** [comment]
@andynoelker It does make sense to add that as a *new* prop, maybe something like `values` to indicate it will overwrite whatever is already there (whether existing initial values or user values).

**Comment by andynoelker** [comment]
@morgante and that's what I'm saying. I assume it wouldn't be too difficult to implement as `initialValues` used to work that way, so we could just copy and paste the code from an older version and give it a new name.

**Comment by erikras** [comment]
Does our new prop, we'll call it `values` for now, update just the values or does it update the `initial` values (what `resetForm()` goes back to and what is used to calculate `pristine`/`dirty`) as well?

**Comment by andynoelker** [comment]
The way I think it would work best (and the way I believe `initialValues` used to work) is that `values` would initialize the form data from a particular piece of state. If any data in that piece of state changes, it would overwrite the corresponding data in the Redux Form component. And this would change `pristine/dirty` as well. Essentially as soon as a change occurred on that original piece of state it would act as though you just called `resetForm()`.

**Comment by erikras** [comment]
Yes, that's how it used to work with `initialValues`. `componentWillUpdate()` did a `deepEqual()` on the `initialValues` prop and if it was different, an `INITIALIZE` action was dispatched.

Something like that sound good to you, @morgante?

**Comment by morgante** [comment]
@erikras Makes sense to me.

**Comment by mike-engel** [comment]
It would be great if INITIALIZE only changed the affected fields. I've got a case where two select elements are pre-filled using some bit of state. Changing one, changes that bit of state. However, when the state changes, other fields with values in them get reset when the state changes from the select element change.

**Comment by haradakunihiko** [comment]
I'm currently using v4.1.14 and when I pass different `initialValues` to redux-connected component as props, it seems `initialize` action is called and then, both `initial` and `value` itself are changed.
The code here https://github.com/erikras/redux-form/blob/master/src/createHigherOrderComponent.js#L53 also says, when the initialValues passed to the component changed, emit 'initialize' action. Which means what I described is correct.

However in the debate in #370 and this issue, I think changing `initialValues` no longer change `value` itself but only `initial` value. 

Do I misunderstand something?

**Comment by sidazhou** [comment]
Using 4.1.9 
I've read https://github.com/erikras/redux-form/issues/370 and I'm still confused. Is `initialValues` syncing with the state or not? What I see from my code is that it is still syncing with the state. 

How do i accomplish "not overwrite data after initialization" behavior as described by @andynoelker ? 
Do I need to use `initialize` from [here](http://erikras.github.io/redux-form/#/api/action-creators?_k=jslxdm) ?

**Comment by erikras** [comment]
> Do I need to use initialize from here?

Yes.

**Comment by silvenon** [comment]
I just put an `initializeForm` call (from [here](http://erikras.github.io/redux-form/#/api/props?_k=445a1z)) in `componentWillMount`, it seems to achieve the desired behavior.

**Comment by thomasmery** [comment]
Hi,

I have followed the discussion here and at #370 but I guess I still need help :)

I'm still very confused about how to change a form's values when it is not unmounted then recreated

I used to rely on `initialValues` to change the values of the form as I would get new data from the db (using Meteor)

I ended up adding a `data` prop & setting up 

```jsx
componentWillReceiveProps (nextProps) {

		if (nextProps.data !== this.props.data) {

			this.props.initializeForm(nextProps.data);

		}

	}
```

I also tried to access `initializeForm` from my container component but as I referenced the Connected Form with `ref`I could not access this prop

thanks for any advice on this

**Comment by aight8** [comment]
@thomasmery 

There are multiple ways:

```
return React.createElement(formComponent, {
   onSubmit: onUpdate,
   initialValues: selectedItem
});
```

or:

Use the **initialize** action creator and dispatch it to the store:
````
initialize(form:String, data:Object, fields:Array<String>)
```

or:

this.props.initializeForm(data:Object) **inside** your decorated form. (in v6 it's called initialize only)

---

but you can't update via ref. The first variant only works in redux-form 5 and not in v6 anymore. When I understand it correctly you have to to a little bit complicated way:
http://redux-form.com/6.0.0-alpha.4/examples/initializeFromState/

**Comment by thomasmery** [comment]
thanks 

I thought

`initialValues: selectedItem`

would not overwrite values anymore 

and that's why I resorted to calling `initializeForm` in the decorated component

and I thought I could do this from outside the component to avoid having to create a full component (and use a stateless one instead)

do I make sense?

thanks

**Comment by aight8** [comment]
Oh yes that's true, there was a change so you can't use initialValues for that case.

I think this feature would be necessary, because I see the problem. I think you should set the current initial values from the wrapper component without to dispatch an action.

Anyway the current solution for this is the redux way:
```
let mapDispatchToProps = (dispatch) => {
    return {
        initialize: data => {
            dispatch(initialize(data));
        }
    }
};

@connect(null, mapDispatchToProps)
```
Then in the componentDidUpdate or componentWillReceiveProps you can call this.props.initialize(formName, initData). So this way it works.

It's somehow clean but.. a direct method call on the redux-form decorator were nicer? Because in the container component I don't have the formName, I set it directly in the decorator props.

**Comment by thomasmery** [comment]
thanks,

at the moment I'm using the `initializeForm` prop that's available to the decorated component [see here](http://redux-form.com/5.1.3/#/api/props)

but I wonder why it is not made available to the container via `ref`like the `submit` method is

same goes for the `resetForm`that, it seems, I can't access from outside

**Comment by erikras** [comment]
FYI, [`v5.1.4`](https://github.com/erikras/redux-form/releases/tag/v5.1.4) might help with this.

**Comment by thomasmery** [comment]
thanks I'll update

**Comment by XoJIoD89** [comment]
Why is this closed? I see no elegant way to sync state and form still

**Comment by andynoelker** [comment]
@XoJIoD89 an elegant way has been added in v6 (multiple ways in fact!). Check out the [Initializing from State](http://redux-form.com/6.4.0/examples/initializeFromState/) example. The easiest way to get the behavior I describe in my post is to set `initialValues` in the connected state to whatever you want it to be and then set `enableReinitialize: true` in the reduxForm constructor. It is literally as simple as that. I don't believe a solution was ever implemented for v5 of the library but if you're able to do so, it really is worth the upgrade (v6 rocks).

**Comment by XoJIoD89** [comment]
Hello, @andynoelker, thanks for your response
I tried this approach with no success. Here is my code: http://paste.org.ru/?rirtsb
As you can see my Dialog component is visible only when open property in the state is set to true. I want to bind form to the user object in the same state. And if you uncomment componentWillReceiveProps method all works as expected. But using initialValues form fields keep old values after reopening this dialog with new user object

**Comment by andynoelker** [comment]
@XoJIoD89 `enableReinitialize` needs to go in the reduxForm config object, not as a prop passed down from state as you currently have it. Currently it is doing nothing and initialValues will only ever fire once immediately as the app loads, presumably with default empty data from your reducer. Simply move it to that config object.
```
export default connect(
    ({ user, header }) => ({ ...header.dialog, user, initialValues: user }),
    { update, hide, snack }
)(reduxForm({ form: 'profile',  enableReinitialize: true })(translate()(CSSModules(Dialog, styles))));
```

**Comment by XoJIoD89** [comment]
@andynoelker yes, sorry, I inserted that just to show you the case and did not pay enough attention to paramaters place. But I've tried the right version as well and it does not work too

**Comment by XoJIoD89** [comment]
Actually I think redux-form may somehow mark passed objects and does not do a deep equals on them. Because I test the form by cancelling it, so redux-form might be thinking that the object did not change though it was 'rollbacked' to its initial state after editing the form. Will figure that out tomorrow.

**Comment by XoJIoD89** [comment]
Hello once again
I've found the reason why this is happening. Redux-form checks passed initialValue object against previous one, not actual form data: http://paste.org.ru/?7nqkth
So if you pass the same initialValues to the form that was already edited, it will not update. Is this an intended behavior?

**Comment by XoJIoD89** [comment]
I believe it's intended indeed. But I have an Add/Edit dialog that can be cancelled and then revisited with the same values. And if it's in the Add state then initial value is {} / undefined. I fill in the form, cancel the dialog, then reopen it and initial value is {} / undefined again. Should I mark this objects somehow to make them different? :(
