### ISSUE TITLE
Decorating multiple components with the same form name

### ISSUE THREAD

**Issue by danielfalk** [erikras/redux-form#579]
This is a question, not an issue.

I've got a form where the flow works a little bit like a wizard with multiple steps.  The form in this case spans multiple pages and the user can navigate in between the steps.

My question is, is it reasonable to decorate different form sections with `@reduxFom()` but use the same form name?

E.g. in AddressPage.js:
```
@reduxForm({
  form: 'newProduct',
  fields: [
    'address',
    'city',
    'state',
    'zip'
  ]
})
export default class AddressPage extends Component {
 ....
}
```
And elsewhere:
```
@reduxForm({
  form: 'newProduct',
  fields: [
    'title',
    'description',
    ...
  ]
})
export default class ProductDetails extends Component {
 ....
}
```

I tried it briefly, and it does seem to work.  I'm just wondering if it's a bad idea in the long run.

**Comment by erikras** [comment]
Yes, very reasonable. :+1:
