### ISSUE TITLE
Can not get promise with calling handleSubmit

### ISSUE THREAD

**Issue by haradakunihiko** [erikras/redux-form#580]
I think it's related to #538. 
I'd like check the submit sync validation result so that user is alerted, but returnRejectedSubmitPromise does not work for me.

Maybe it's because I does not pass onSubmit props to redux-form-connected Component. 

Before, my code was like bellow.
```js

MyComponent extends Component {

  handleSave(values) {
    // do something.
  }

  render() {
    return <button onClick={this.handleSubmit(::this.handleSave)}></button>
  }
}
```

and I changed this so that I can check the validation result using Promise.
```js

MyComponent extends Component {

  handleSave(values) {
    // do something.
    return Promise.resolve();
  }

  handleOnClick(e){
    this.props.handleSubmit(::this.handleSave)(e) // => this does not return a promise.
    .then(() => {
    }, (errors) => {
      // => I'd like to get sync errors!
      showAlertSothatYouCanKnowWhatsGoingOn(errors );
    });
  }

  render() {
    return <button onClick={::this.handleOnClick}></button>
  }
}

```

I guess returning the result in the callback function would work. 
https://github.com/erikras/redux-form/blob/master/src/createHigherOrderComponent.js#L92

Also, is that possible to return syncErrors with Promise when it is rejected?
https://github.com/erikras/redux-form/blob/master/src/handleSubmit.js#L37

How do you think about this?

**Comment by kristian-puccio** [comment]
I just ran into this as well. I think what is going on is that a promise is being return but only when the validation fails and null when validation passes.

So you get a for me `Uncaught TypeError: Cannot read property 'catch' of undefined` error on success.

**Comment by kristian-puccio** [comment]
work around: 
```
		const x = handleSubmit(e);
		if (x) {
			x.catch(() => this.props.onSubmitFailed(this.props.errors));
		}
```

**Comment by erikras** [comment]
@haradakunihiko's fix published as [`v4.1.10`](https://github.com/erikras/redux-form/releases/tag/v4.1.10).

**Comment by erikras** [comment]
Please confirm that `v4.1.10` fixes this problem, @kristian-puccio.

**Comment by kristian-puccio** [comment]
No unfortunately :(

I looked quickly at the pull request and it looks like it should but I'm
still getting undefined error.

```
<form
autoComplete={false}
onSubmit={ this._handleSubmit }>
```

And here is  where I handle the submit, x print out as undefined when there
are no async errors.
When there are async errors I get: `Promise {_d: Object} "<<<<< x"`
```
_handleSubmit = (e) => {
const {handleSubmit} = this.props;

const x = handleSubmit(e);
console.log(x, '<<<<< x');
if (x) {
x.catch(() => this.props.onSubmitFailed(this.props.errors));
}
};
```

**Comment by 5an1ty** [comment]
I'm facing the same issue. When I have a component that I pass the following too:

```
onSubmit={(values) => values}
returnRejectedSubmitPromise={true}
```

I get a promise if my validation failed, or the values object if the validation succeeds.
That behavior is a bit inconsistent, don't you think?
