### ISSUE TITLE
Deep form example "Add Phone" doesn't work

### ISSUE THREAD

**Issue by danielfalk** [erikras/redux-form#583]
Thought you might want to know that the "Add Phone" button doesn't seem to do anything in the example:

http://erikras.github.io/redux-form/#/examples/deep?_k=t3sv8u

It does seem to add something to the state.  It adds null to the phones array, but nothing displays any differently.

**Comment by drouillard** [comment]
If you click add phone, then select into another field then it does seem to add the phone number field. Seems like it is waiting for another render to happen. 

Could be an issue with the Address component's shouldComponentUpdate? It looks OK on initial glance though. Will see if I have time to take a look later in next couple days.

**Comment by danielrob** [comment]
Closing, this issues relevancy has expired (unsupported).
