### ISSUE TITLE
How set initial value in React Plugins?

### ISSUE THREAD

**Issue by Xurma2** [erikras/redux-form#585]
I set initial value 
```
<Geosuggest
className={(this.setClass)("location")}
language={"en"}
country={"us"}
name="location"
types={['(regions)']}
{...location}
onSuggestSelect={function(suggest){
				location.value = suggest.label; \\ this
				this.setState({ inputLocation: suggest.label })
	          		}}
	initialValue={{initialValue : location.value}}
/>
```

But in validation i get 
```
{location : undefined}
```

And i get error when from select plugins (react-widget-combobox) focuses on other input. 
If I simply removed the focus, without having to switch to the next input, all works well

![bug](https://cloud.githubusercontent.com/assets/5157416/12527432/0925808a-c18c-11e5-99ea-42172dcd2615.gif)

**Comment by ooflorent** [comment]
This is a usage question, and we encourage you to ask it on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

This is the only way to ensure the same question doesn’t get asked many times in a row, and that folks who have the same question in the future will be able to find it.

I’m closing for these reasons.
