### ISSUE TITLE
redux-form's actions don't conform to FSA

### ISSUE THREAD

**Issue by stevengoldberg** [erikras/redux-form#586]
A [Flux Standard Action](https://github.com/acdlite/flux-standard-action) (FSA):

>MUST

>* be a plain JavaScript object.
>* have a `type` property.

>An action MAY

> * have a `error` property.
> * have a `payload` property.
> * have a `meta` property.

>An action MUST NOT include properties other than `type`, `payload`, and `error`, and `meta`.

`redux-form`'s [actions](https://github.com/erikras/redux-form/blob/master/src/actions.js) don't conform to this standard -- many of them have several additional properties, but no `payload`.

This caused me some confusion when I was trying to have one of my other reducers respond to a `redux-form` action, but I was getting an `undefined` parameter in my handler -- my `createReducer` function was only passing `action.payload` to the handler method, because I was expecting every action to follow FSA, as all of my app's internal actions do.

**Comment by erikras** [comment]
I would accept a PR if it's that important to you.

**Comment by ooflorent** [comment]
Addressed by #799

**Comment by erikras** [comment]
FSA compliance is now published in [`v6.0.0-alpha-7`](https://github.com/erikras/redux-form/releases/tag/v6.0.0-alpha.7).
