### ISSUE TITLE
access props in reducer

### ISSUE THREAD

**Issue by greaber** [erikras/redux-form#587]
Is it possible to get the props on a form (or really just whether the form is valid) in a reducer?  If not, is this something that could be supported?

I want to have an action that will set which of a group of forms is rendered ("active"), but it will not change the active form if the currently active form is not valid.  I was thinking to do something like the following, but I couldn't find the validity information in Redux Form's store.

```
// This isn't code I have actually tried to run.

function activeForm(globalState, action) {
    if (action.type !== TRY_TO_SET_ACTIVE_FORM) return globalState.activeForm
    if (globalState.activeForm && globalState.form.myForm[globalState.activeForm].props.invalid) {
        return globalState.activeForm
    }
    return action.payload
}

function mainReducer(state, action) {
    return {
        form: reduxFormReducer(state.form, action),
        activeForm: activeForm(state, action)
    }
}

// In some component's render method...
{activeForm && <MyForm formkey={activeForm}/>}
```

The alternative, I guess is to use two different actions, a "request set active form" action that anyone can fire and a "actually set active form" action that the active form could fire in `componentWillReceiveProps` when it detects the request action and it is valid.  Also, would have to set up something to Fire the "actually set active form" action also when there is no currently active form.  Or is there a cleaner way I am overlooking?

**Comment by frost555** [comment]
You can check for validity before dispatching your action. In a component handler.

**Comment by erikras** [comment]
See also: [Wizard Example](http://erikras.github.io/redux-form/#/examples/wizard)

**Comment by greaber** [comment]
OK, but won't it require some workaround for #202?  Also, this way seems a bit against the spirit of Redux as a functional single source of truth.

**Comment by greaber** [comment]
The comment I just wrote was directed at @erikras.  @frost555, I am not sure what you are suggesting.  Do you mean I would keep a reference to the active form component and call a method on it that would tell me if it is valid?  That might work although it seems like that kind of thing is generally regarded as an anti-pattern in React.  You are not supposed to have to access the state or props of a component from outside it or to imperatively signal components other than by changing their props.  Granted, I could arrange to signal the component by changing its props (by connecting it to Redux with react-redux and dispatching an action), but that seems overly complex and gratuitously imperative.  Maybe I am not understanding your suggestion though.

**Comment by ooflorent** [comment]
This is a usage question, and we encourage you to ask it on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

This is the only way to ensure the same question doesn’t get asked many times in a row, and that folks who have the same question in the future will be able to find it.

I’m closing for these reasons.
