### ISSUE TITLE
Textarea can be reset only be explicitly dispatching reset() when submitting form

### ISSUE THREAD

**Issue by adiachenko** [erikras/redux-form#588]
Textarea doesn't reset after submitting form even with the [known fix](https://github.com/erikras/redux-form/issues/547) below:

```
<textarea {...body} value={body.value || ''} />
```

Currently I am explicitly dispatching reset when resolving Promise in **onSubmit** callback. This works, but it's kinda ugly. There are no particular deviations in my code, it's pretty similar to what you can find in official examples.

**Comment by erikras** [comment]
Sounds like another unforeseen side effect of https://github.com/erikras/redux-form/issues/370#issuecomment-166593091. :frowning:

**Comment by adiachenko** [comment]
Wow, I never noticed it but it seems like other inputs work the same way. I'm wondering whether it's an expected behavior. Feel free to close this issue if that is the case. I may be missing something here.

**Comment by erikras** [comment]
It was a conscious decision taken in the previously linked issue, for all the reasons discussed there, to _not_ re-initialize based on the `initialValues` prop the second time. I'm not 100% sure that it was the right decision, because you are exactly right to expect it to behave as you expected it to.

**Comment by simonedavico** [comment]
@erikras  I'm struggling to understand what is the current behaviour of the library. With 6.5.0 I am observing that event if `destroyOnUnmount` is set to `false`, the `INITIALIZE` action gets called when the form is unmounted. I am trying to circumvent this by manually calling `initialize` in my submission callback, but unfortunately the `INITIALIZE` action ignores the new initial values and uses the one provided to the `reduxForm` configuration. 

Am I missing something here?
