### ISSUE TITLE
Submiting form with initial values on mount.

### ISSUE THREAD

**Issue by frost555** [erikras/redux-form#590]
I need to auto-submit my form on ComponentDidMount when initail values are valid according to validation function.
The problem is that all my fields are shown as invalid at this lifycycle method (Though initial values are valid)

Right now i found a workaround by wrapping function with setTimeout. Is there a better way to handle this?

    componentDidMount: function() {
      // this.props.fields.myField.invalid == true
      window.setTimeout(this.submitOnValid, 0)
    }

.

**Comment by erikras** [comment]
I'm curious. Why on earth would you want to submit your form on mount? What is the value of having the form if you're going to submit before anyone can edit the values?

**Comment by frost555** [comment]
Its a payment form. For example you can put money on your internet provider account through our service. Before you can pay, we need to verify that account with provided number exists - send a request. We also allow to pass initial values(in this example account number) through url parameter.  When initial values are provided it is desirable to start verifying as soon as page loads.

**Comment by erikras** [comment]
Why wouldn't you just try to submit the values first, and then, only on failure, render the form? Rendering the data all the way out to the DOM just to have it whisked away to the server seems pretty strange.

This use case is strange enough that I don't mind you using `setTimeout()` as a way to trigger the submission. You've done it right.
