### ISSUE TITLE
this.props.initialValues is `undefined`

### ISSUE THREAD

**Issue by stepankuzmin** [erikras/redux-form#591]
When I am initializing form component like this

```js
<LayerForm initialValues={layer} />
```

I am getting undefined `initialValues`, so I have to pass another prop to ensure that form was initialized with initialValues. Why removing `initialValues` from props?

**Comment by erikras** [comment]
Because it's proprietary to the library. No better reason than that.

**Comment by stepankuzmin** [comment]
I see, thanks for reply!
