### ISSUE TITLE
Declare Node/NPM Versions

### ISSUE THREAD

**Issue by solomonhawk** [erikras/redux-form#592]
To encourage more contributions, we should define the Node version needed to work on `redux-form`: either in a `CONTRIBUTING.md` or `engines` field of `package.json` or `.nvmrc` if you'd like.

**Comment by erikras** [comment]
Good idea. I'd love a PR with any or all of those solutions. We abandoned `0.12` back in https://github.com/erikras/redux-form/commit/408d10228ef41dfaefe9cc2ffb6c600074b159a6#diff-354f30a63fb0907d4ad57269548329e3.

I recently read the [`CONTRIBUTING.md` on `redux`](https://github.com/rackt/redux/blob/master/CONTRIBUTING.md) and liked it. I've been thinking about copying and trimming it.

**Comment by ooflorent** [comment]
Would be addressed by #884.
