### ISSUE TITLE
How to implement forms with fields which depend on each other?

### ISSUE THREAD

**Issue by arddor** [erikras/redux-form#594]
First of all thanks for the great library.
I have problems to find a way to implement a field in a form which has to change when another field changed in the same form.

e.g. I have a number input which says how many rows should be displayed. When that value is changed the rows should also change (the rows are in the form of an array of inputs). I saw the deep form example which has somewhat what I need but I would need to have a numeric field which does that.

My approach was to introduce a new action and add it to reducer.plugin but the value which I get there for state is an Object. The only other idea which I have would be to reproduce the CHANGE actions from 'redux-form' however I don't know how to approach that.

So what is the proper approach to have values change in response to another changed field in the same form?

**Comment by erikras** [comment]
:+1: for the excellent explanation, and you have clearly read the docs.

There is currently no way to `addNFields()`, so you're going to have to do that reconciliation yourself. I would recommend doing something like (disclaimer: handwritten code never linted):
```js
render() {
  const {fields: {rows}} = this.props;
  return (
    <div>
      Num Rows:
      <input
        type="number"
        value={rows.length}
        onBlur={event => {
          const numRows = Number(event.target.value);
          const toAdd = numRows - rows.length;
          if(toAdd > 0) {
            for(let index = 0; index < toAdd; index++) {
              rows.addField();
            }
          } else if(toAdd < 0) {
            for(let index = 0; index > toAdd; index--) {
              rows.removeField();
            }
          }
        }}/>
    </div>
  );
}
```
There really is no better solution to having a field where you can enter a number of rows. Let me know how that goes, please.

**Comment by arddor** [comment]
Thank you very much for your quick response. This is a solution to my problem, but it has the disadvantage that it will lead to *n* rerenders. 

I will check if it would be better to implement something on my own as I will have another case where I have to build a Matrix form (one input for rows and one for columns).
However I really like redux-form, you did a great job.

**Comment by erikras** [comment]
Hmm... All those actions are being dispatched in the same process tick, so, while my solution _will_ lead to `n` actions being dispatched, it will not lead to `n` _rerenders_. The rerender only happens after the event has been handled completely.
