### ISSUE TITLE
resetting normalized fields with resetForm is broken

### ISSUE THREAD

**Issue by blairio** [erikras/redux-form#595]
`resetForm` doesn't seem to work on form fields that I have normalized. Fields that are not normalized work fine.

eg.
```
{
        email: (value) => (value && value.toLowerCase().trim())
 }
```

The Normalizing Form Data example doesn't seem to reset when I press "Clear Values" either
http://erikras.github.io/redux-form/#/examples/normalizing?_k=1ec6qp

**Comment by erikras** [comment]
That's a bug! Thanks! :+1:

**Comment by erikras** [comment]
Fix published in [`v4.1.6`](https://github.com/erikras/redux-form/releases/tag/v4.1.6).

**Comment by blairio** [comment]
Thanks!

**Comment by znamilya** [comment]
But it still doesn`t work in version 5.2.3
