### ISSUE TITLE
async submit errors are swallowed

### ISSUE THREAD

**Issue by cdaringe** [erikras/redux-form#596]
hello:

```js
    submit(values, dispatch) {
        const { project } = this.props;
        return new Promise((res, rej) => {
            dispatch(saveProject(project), (err, rslt) => {
                if (err) {
                    return rej({
                        name: err.message
                    });
                }
                res();
            });
        });
    }
```

in the above, `saveProject` had a critical error in it, causing a sync `throw`.  my expectation was that my `uncaughtRejection` handler would catch it.  instead, the error was swallowed because i didn't have  [`returnRejectedPromise` enabled](https://github.com/erikras/redux-form/blob/master/src/handleSubmit.js#L18).  this seems risky, and in turn made it difficult to debug.

maybe we can come up with a more robust solution together?  thanks for making this lib! :)

**Comment by cdaringe** [comment]
perhaps if the promise that is rejected has some attr in it that is sniffable to determine that the error thrown is desired.  `{ fields: { field1: ..., field2: ... } }`.  that AND that it's not indeed an `Error` instance?

**Comment by ooflorent** [comment]
I'm closing the issue because it is inactive for a long time.
We would happily accept any PR (if not already done)!
