### ISSUE TITLE
formKey vs dynamically calling reduxForm

### ISSUE THREAD

**Issue by greaber** [erikras/redux-form#598]
I've been using `formKey`, and it hasn't caused me any problems, but I was just trying to get my head around the API design better, and it struck me that maybe `formKey` is not really necessary because every time you need a new instance of a form, you could just call `reduxForm` with a new `form` parameter.  Would this approach work fine or is `reduxForm` really slow or something?  Again, it's just curiosity that makes me ask, not any problem I'm having.

**Comment by erikras** [comment]
Yes, you are correct. That functionality dates back to a previous design.

One _possible_ advantage is that you could reuse a `normalizer` or `plugin` definition for many records of the same type.

It's not because of slowness at all. Great and insightful question.

**Comment by siemiatj** [comment]
That's what I did : 

```
const getMyForm = (formId, props) => {
  let MyForm = () => {
    return (
        <form onSubmit={props.handleSubmit}>
          <div>
            <Field name="text" component="text" />
          </div>
        </form>
    );
  };

  MyForm = reduxForm({
    form: `MyForm-${formId}`,
  })(MyForm);

  return <MyForm />
};
```

but then it's hard to get your form data using the selector :/

**Comment by pawarvijay** [comment]
[no need to pass form name in redux form if form is passed as prop ](https://stackoverflow.com/questions/40509754/how-do-you-pass-in-a-dynamic-form-name-in-redux-form)

```
var formId="SomeId"
<FormAddress form={formId} />

And in your FormAddress component have 
const form = reduxForm({
//no need to put form again here as we are sending form props.
});
```

**Comment by siemiatj** [comment]
Ok, but what is the name of the form ? Looking at your example it seems I have no control over it. So how do I reference this form in other places ?
