### ISSUE TITLE
Reducing dirty state in plugin

### ISSUE THREAD

**Issue by jonathanasquier** [erikras/redux-form#599]
Hi!
I used to compute the dirty state of a form by doing this in the render function : (using lodash)
```
var dirty = _.map(_.keys(fields), function(k){
            return fields[k]
        }).reduce(function(d, c){
            return d || (c && c.dirty);
        }, false);
```
But I wish I could reduce it in the state using the plugin API to access it elsewhere (disabling buttons toolbar if form is dirty...) 

But fields in the plugin state are pretty empty : 
```
_isFieldValue: true
initial: ""
value: ""
```
I have no access to all the props : 
```
active: false
checked: false
defaultChecked: false
defaultValue: false
dirty: false
initialValue: false
invalid: false
```
Sooo... I'm sad.

Shouldn't it be reduced by redux form the same way the other _props are?
```
_active: "thing"
_asyncValidating: false
_error: undefined
_initialized: true
_submitFailed: false
_submitting: false
``` 

Thanks!

**Comment by erikras** [comment]
Putting `_dirty` in the root state violates the holy **If it can be calculated from state, don't store it in the state** principal.

I think what you need is an `isDirty()` that is like [`getValues()`](http://erikras.github.io/redux-form/#/api/get-values).

**Comment by jonathanasquier** [comment]
Okay i'll investigate :)
Also I was to blind to see that 
```
_isFieldValue: true
initial: ""
value: ""
```
are just enough to calculate dirty, so I'm reducing it in a plugin reducer for now
```
_.map(_.filter(state, function(f){
    return _.isObject(f);
})).reduce(function(d, c){
    return d || !!(c && (c.value != c.initial));
}, false);
```
although it's anti-pattern... please don't judge me! :(
