### ISSUE TITLE
Support Redux 2.0

### ISSUE THREAD

**Issue by mattydoincode** [erikras/redux-form#60]
Can't use redux-form with latest redux and redux dev tools atm. Thanks!

**Comment by erikras** [comment]
Can you explain the problem a bit better? [react-redux-universal-hot-example](https://github.com/erikras/react-redux-universal-hot-example) seems to be doing it just fine.

**Comment by mattydoincode** [comment]
Just realized this more me than the library. I was able to update it fine with a little manual tweaking However it might be worth updating the package json to say ^2.0.0. Otherwise feel free to close!

**Comment by erikras** [comment]
I'm far from a semver expert, so I could be totally wrong, but it seems like if it still works with 1.0, the dep should still be `^1.0.0`. Or maybe I need to do something more fancy, e.g. `>=`, to include 2.0?

**Comment by mattydoincode** [comment]
I'm definitely not an expert either, I was just basing that off of https://stackoverflow.com/questions/22343224/difference-between-tilde-and-caret-in-package-json which says major versions don't auto update with ^ so you get a warning. Thoughts?

**Comment by wmertens** [comment]
@erikras see https://docs.npmjs.com/files/package.json#dependencies I'm guessing it should be "^1.0.0 ^2.0.0"

**Comment by erikras** [comment]
That didn't build. Actual solution was `>=1.0.0 >=2.0.0`. Not sure if that's wrong or not...

**Comment by rockingskier** [comment]
You don't need the `>=2.0.0`  Given that `2.0.0` is still `>=1.0.0`.

If you wanted to limited it at all with regard to `2` I would suggest `>=1.0.0 <=2.0.x` which says you don't claim to work with (the currently non-existent) Redux `2.1.x` and up.

**Comment by erikras** [comment]
That makes sense. Thanks, @rockingskier.
