### ISSUE TITLE
wrong submitting on <button>s, which creates a redux/TOUCH action

### ISSUE THREAD

**Issue by gabrielenosso** [erikras/redux-form#600]
Hi all, it seems that there is a problem in rendering <button> elements in a form.

If I create a <button> element inside the form, even without an "onClick" prop, it submits the form.
When clicked, it creates a "redux/TOUCH" action and, I don't know why, it submits the form.

If the <form> element has an "onSubmit" prop, it invokes it.
Otherwise it just goes to the same page URL with empty parameters
(the browser URL changes to http://mypage.com?param1=&param2=&param3=)

**Comment by frost555** [comment]
It is standard browser behaviour. You need to call preventDefault method on event that triggered submit.

**Comment by gabrielenosso** [comment]
Thank you, it's my fault I didn't think about it!

**Comment by erikras** [comment]
See also: http://erikras.github.io/redux-form/#/faq/enter-to-submit
