### ISSUE TITLE
Designing Wizards and Validations With Redux Form

### ISSUE THREAD

**Issue by antoaravinth** [erikras/redux-form#601]
Hi All, 

I have an form wizard, which contains three wizards `Wizard1`,`Wizard2`,`Wizard3`. And each of these wizards have been tied up with the reduxForm like this:

```
Wizard1 = reduxForm({
    form : 'create-form-1',
    fields : ['description']
})(Wizard1);

Wizard2 = reduxForm({
    form : 'create-form-2',
    fields : ['someField']
})(Wizard2);
```
Now each wizard needs to be validated before other wizard gets displayed. So there is a `WizardHandler` component, which does takes care of "rendering" from one wizard to another wizard. So in `WizardHandler` I need to validate `Wizard1` fields before it displays `Wizard2`.

On this use case I have couple of questions:
1. How do `WizardHandler` get the values from `create-form-*` form fields?
2. Is it a good design for solving the wizards with respect to React and Redux-Form?

Thanks for your help!

**Comment by cdaringe** [comment]
> How do WizardHandler get the values from create-form-* form fields?

in your connected component, in wire up `form` in `mapStateToProps`.  then you can ref `this.props.form['create-form-*']`

> Is it a good design for solving the wizards with respect to React and Redux-Form?

no red flags.  you tell us when you're done :).  it may be easier to change some other piece of state post-Wizard1 form submit that indicates that wizard2 be shown, _maybe_?  follow your heart.

**Comment by cdaringe** [comment]
oh, and http://erikras.github.io/redux-form/#/api/get-values?_k=eo04uv

**Comment by antoaravinth** [comment]
> in a connected component, wire up state.form in mapStateToProps. then you can ref this.props.form['create-form-*']

This one made it work. But the problem is then in order to get the value, I need to do this:

`this.form.fieldValue != undefined ? this.form.fieldValue.value : ""`

This looks like lot of work! Any other easier way to get?

**Comment by erikras** [comment]
Your other option is to use the same form name on multiple pages, as detailed here: https://github.com/erikras/redux-form/issues/260#issuecomment-155852315

**Comment by erikras** [comment]
Here's a new example just for you. [Wizard Form](http://erikras.github.io/redux-form/#/examples/wizard)

**Comment by antoaravinth** [comment]
@erikras : This is great! Thanks for your time!

**Comment by RT-TL** [comment]
A short question for better understanding redux form: Usually form fields are initialized by providing them as an array to reduxForm. In the wizard-example this is not the case. I tried to recreate this and add some more functionality and flexibility and ran into problems with accessing the form fields only being actually considered (e.g. in validation) after second render. I assume this relates to not providing a fields array. Can you explain?

**Comment by gustavohenke** [comment]
@RT-TL, what's your code and what's the version you're using?
As usual, an working demo is always better. I recommend http://webpackbin.com.

**Comment by RT-TL** [comment]
@gustavohenke Thanks for the hint to use webpackbin. Nice tool that I didn't know before. In the meantime I was able to solve my problem. It was caused by a wrong understanding of how the validation works. I was not aware that when using form-level-validation I allways need to validate not-rendered fields as well so that the whole form is not set to "validat:true".
