### ISSUE TITLE
Multiple records with radio buttons for each record

### ISSUE THREAD

**Issue by tamagokun** [erikras/redux-form#606]
Here's the situation:

Editing multiple form records at the same time. Form are set up properly using `formKey`. Each form has an `active` field which is rendered as two radio buttons (one Yes, one No).

The problem is that all the radio buttons will have the same `name` attribute of `active`, and the browser will think that they all belong to the same group of inputs even though they are intended to be two separate groups.

If you need more clarity I can set up an example.

**Comment by erikras** [comment]
No, I got it. Very interesting. So the name needs to be prefixed with the form key. Perhaps the library should be wise to this, but I can give you a work around until that day comes. What follows is pseudo code and may contain small errors.

```js
render() {
  const {formKey, fields: {active}} = this.props;
  return (
    <form>
      <label>
        <input type="checkbox" {...active}
          checked={active.value === true}
          name={formKey + '_active'}/>
          Yes
      </label>
      <label>
        <input type="checkbox" {...active}
          checked={active.value !== true}
          name={formKey + '_active'}/>
          No
      </label>
   </form>
  );
}
```
Any props that you specify _after_ the destructured field props will override them, so you can set a new unique `name` value based on the `formKey`.

That help?

**Comment by tamagokun** [comment]
Oh! Brilliant. I thought that perhaps name was used to identify the form field name, but not the case. Easy enough to do. Thanks!
