### ISSUE TITLE
Some feedback regarding documentation

### ISSUE THREAD

**Issue by dukedougal** [erikras/redux-form#609]
It would be great if the documentation was alot more clear and obvious about how to load data into a form, and how to get the data following submit.

I'm struggling to implement these two things which should be dead obvious but instead I'm trawling the Internet and github issues to find clues on how to do it.

**Comment by andynoelker** [comment]
Do you mean you think the documentation is unclear on how to initialize data in your form from the Redux state? That is covered by [an example](http://erikras.github.io/redux-form/#/examples/initializing-from-state?_k=jh958y) in the documentation. However, the  basic usage of this Redux Form is just to keep your form data in sync with your state in a very simple and straightforward way. Loading data from the state is not assumed to be default behavior so I imagine that's why its documentation was reserved for an example and not the first page.

What types of changes would suggest to make it easier for beginners to quickly pick up how to use this?

**Comment by dukedougal** [comment]
I think a form library should have two extremely obvious sections in its getting started documentation.

"How to get data into your form"
"How to get data out of your form"

It's the basic use case and it would be great if it explained it to me like I'm five how to do that.

Love the redux-form so far thanks for writing it!

**Comment by erikras** [comment]
Thank you for this feedback.

**Comment by alphashuro** [comment]
I strongly agree, I struggled to figure out how the form works and what the heck is going on with that 'handleSubmit' prop... I think the documentation is a bit oversimplified and left out many details of how the module actually works. I was so disappointed when the simple example read 'there is no step 3', isn't the process of hooking up a submit function worth adding a step 3?

For example, the documentation should explain that the handleSubmit function is actually a property passed by redux form, that calls the onSubmit prop on the wrapped component if it is not given an argument, or calls whatever argument you give to it. 

Furthermore it should explain that the function called by handleSubmit (whether the onSubmit prop or the argument given to it) will receive an argument of an object with the form's fields as its keys.

I have not looked at the validation stuff yet but please take a look there as well.

**Comment by arunkjn** [comment]
I agree too. In the examples its very well defined how to make a form component, but nowhere how to use it with actual data.

**Comment by erikras** [comment]
One of the goals of this library is to be completely unopinionated about where the data comes from or where it goes. However, I can see the benefit of an example that does load and save data as well.

Can anyone suggest a public API that said example could use? Many examples use the [GitHub API to load stargazers](https://developer.github.com/v3/activity/starring/#list-stargazers), but it wouldn't be able to write to that.

**Comment by rkoberg** [comment]
Using this for the first time today, and still evaluating whether to use or not. I was also confused about the "there is no step 3" -- thought I was doing something wrong -- was passing my own function and using it as the submit handler. It took a while to figure out how to pass/use the submit handler functions( mine and redux-form's). It also took a while to figure out how to set default values. One of the first things I did to see how things worked was to look at the examples, but where is the source for those examples? (found them in the gh-pages branch)

I think some explanation is needed for what you need to do to make submit handling work (step 3). Also, some different ways of setting up default values would be great (step 4 a, b, c,...).
