### ISSUE TITLE
Dynamic Form input can't get focus

### ISSUE THREAD

**Issue by rockingskier** [erikras/redux-form#61]
First off, loving this library, thanks for the hard work you've clearly put in.

I'm having some issues with the DynamicForm in the README.  Most of this code is stripped down versions from the examples.

I have a `<BaseForm>` that loops over and renders all inputs.

Firstly I create `<DefinedForm />` with `connectReduxForm` with hard coded fields.
Secondly I create `<DynamicForm />` that takes the list of fields and calls `connectReduxForm` to create a new `<Component />` with *dynamic* fields.

Finally I render both forms into one `<ContainerComponent />`.

I can happily fill in the `<DefinedForm />`.  I can type in the input and see all interacts appear in `<DevTools />`.

However when I click on the `<DynamicForm />` I cannot type anything.  In the `<DevTools />` I get a `redux-form/FOCUS` event but nothing more.  Focus is not actually given to the input (I added `style` to focused inputs).

Am I doing something wrong or missing something out here?

```javascript
import { connectReduxForm } from 'redux-form';
import React, { Component, PropTypes } from 'react';


class BaseForm extends Component {
  render() {
    const { fields } = this.props;
    return (
      <div formKey={this.props.formKey} >
        {Object.keys(fields).map(fieldName => <div key={fieldName}>
          <label>{fieldName}</label>
          <input type="text" {...fields[fieldName]}/>
        </div>)}
      </div>
    );
  }
}

var DefinedForm = connectReduxForm({
  form: 'contact',
  fields: ['name'],
  validate: (data) => { return {}; }
})(BaseForm);

class DynamicForm extends Component {
  render() {
    const { formName, fieldsNeeded } = this.props;
    var DynamicInnerForm = connectReduxForm({
      form: formName,
      fields: fieldsNeeded,
      validate: (data) => { return {}; }
    })(BaseForm);

    return <DynamicInnerForm formKey={this.props.formKey} />;
  }
}

class NestedDefinedForm extends Component {
  render() {
    return <DefinedForm />
  }
}

class ContainerComponent extends Component {
  render() {
    return (
      <div>
        <h1>DefinedForm</h1>
        <DefinedForm
          formKey={'DefinedForm'} />

        <h1>NestedDefinedForm</h1>
        <NestedDefinedForm
          formKey={'NestedDefinedForm'} />

        <h1>DynamicForm</h1>
        <DynamicForm
          formKey={'DynamicForm'}
          formName={'contact'}
          fieldsNeeded={['name']} />
      </div>
    );
  }
}


export default ContainerComponent;
```

**Comment by erikras** [comment]
I can't get this to work. `Warning: React.createElement: type should not be null or undefined. It should be a string (for DOM elements) or a ReactClass (for composite components).` Is there any way you could generate a jsfiddle or something?

**Comment by rockingskier** [comment]
I forgot just how much boilerplate was needed to get it running.

Anyway, I had a dig and it seems to be that when the parent `<Component>` is `@connect`ed it breaks.

I've put together a demo repo.  `npm i && npm start` should get you running.

https://github.com/rockingskier/redux-form-issue

**Comment by erikras** [comment]
Thanks for mocking that up. Made it a lot easier to debug.

[Here's a PR that fixes the problem](https://github.com/rockingskier/redux-form-issue/pull/1).

**Comment by rockingskier** [comment]
Ah of course! So stupid! Thank you for looking at that. I was only passing the whole state to start with but I should it should have been {...state} anyway.

**Comment by vincentfretin** [comment]
@erikras I actually have a similar issue with nested forms I'm currently trying to implement.
I guess the issue that @rockingskier have is that all the virtual-dom is recalculated because the state has changed and I think the DOM changed too, so the field you focus on is not actually the same.
I had a real performance issue (1s hang for each typed character) with a form with a nested form, because each field object
actually changed because of handleBlur function and other functions that are recreated each time, so they are not equal!
I fixed it by writing a shouldPureComponentUpdate function :

const IGNORE_FUNCTIONS = [
      'onChange', 'onBlur', 'onFocus',
      'handleChange', 'handleBlur', 'handleFocus']


    export function shallowEqual(objA, objB) {
      if (objA === objB) {
        return true
      }

      if (typeof objA !== 'object' || objA === null ||
          typeof objB !== 'object' || objB === null) {
        return false
      }

      const keysA = Object.keys(objA)
      const keysB = Object.keys(objB)

      if (keysA.length !== keysB.length) {
        return false
      }

      // Test for A's keys different from B.
      const bHasOwnProperty = Object.prototype.hasOwnProperty.bind(objB)
      for (let i = 0; i < keysA.length; i++) {
        if (!bHasOwnProperty(keysA[i])) {
          return false
        }
        if (keysA[i] === 'field') {
          if (!shallowEqual(objA[keysA[i]], objB[keysA[i]])) {
            return false
          }
        } else if (typeof objA[keysA[i]] === 'function' &&
          IGNORE_FUNCTIONS.indexOf(keysA[i]) > -1 ) {
          // don't compare onChange, onBlur, onFocus, handleChange,
          // handleBlur, handleFocus
          continue
        } else if (objA[keysA[i]] !== objB[keysA[i]]) {
          // console.log('rerender because of prop named:')
          // console.log(keysA[i])
          // console.log('before:')
          // console.log(objA[keysA[i]])
          // console.log('after:')
          // console.log(objB[keysA[i]])
          return false
        }
      }

      return true
    }

    export default function shouldPureComponentUpdate(nextProps, nextState) {
      return !shallowEqual(this.props, nextProps) ||
             !shallowEqual(this.state, nextState)
    }

that I assign to my Field component like this:

    class Field extends Component {
      static propTypes = {
        field: PropTypes.object.isRequired,
      }

      shouldComponentUpdate = shouldPureComponentUpdate

**Comment by damassi** [comment]
@erikras - I'm running into this problem now too (input wont accept content but do appear to be toggling focus when you touch them) and I can't for the life of me figure out why. What I have been able to figure out is on initial load, console.logging out `state.router` (via connect) returns an empty array (where the dynamically created form should have appeared) but on subsequent hot reload saves you see the forms there, but by that time the flow has broke and you still cant type.

**Comment by gzhappysky** [comment]
I actually have a similar issue with nested forms I'm currently use onSubmitFail to solved.

'reduxForm(
  {
    form: 'TaskEditForm',
    fields,
    validate,
    onSubmitFail: (errors) => {
      let keys = Object.keys(errors);
      for (let i = 0; i < keys.length; i++) {
        var key = keys[i];
        let index = 0;

        //数组处理,针对多个农资时的处理
        if (_.isArray(errors[key]) && errors[key].length > 0) {
          for (var j = 0; j < errors[key].length; j++) {
            let item = errors[key][j];
            let t;
            if ((t = Object.keys(item)).length > 1) {
              index = item.index;
              key = t[0] == 'index' ? t[1] : t[0];
              break;
            }
          }
        }

        let elements = document.getElementsByName(key);
        if (elements.length > 0) {
          elements[index].focus();
          break;
        }
      }
    }
  },)
)(TaskEditComponent)'
