### ISSUE TITLE
getValues not returning state post- CHANGE action deploy

### ISSUE THREAD

**Issue by cdaringe** [erikras/redux-form#610]
a short youtube video demonstrating the problem.  can be viewed at increased speed.  duration is 1.5 minutes :)

workflow:
- form value changed
- CHANGE action dispatched, and logged
- in `componentWillReceiveProps`, the form state is passed in, pre- re-render of the component
- `getValues(formState)` returns an empty object

interestingly, after another action occurs, e.g. a blur, the value appears as expected.

https://youtu.be/3C_PFYvR48Y

**Comment by cdaringe** [comment]
ultimately all that i'm trying to do is:

- use the form
- based on form state, conditionally dispatch more actions to set or remove other state immediately after a different value has been set in a field

what i'm finding is that something in is _off_ in the component lifecycle or the state isn't being updated as I anticipate it should be

**Comment by cdaringe** [comment]
i was referencing `this.props`, not `newProps`.  my mistake.

**Comment by erikras** [comment]
Wow, brilliant screencast, though. Glad you figured it out.

**Comment by cdaringe** [comment]
:) thanks.  a little video never hurt anybody!
