### ISSUE TITLE
asyncValidate not called when field empty (even when field has been touched)

### ISSUE THREAD

**Issue by tomduncalf** [erikras/redux-form#614]
I'm not sure if this behaviour is by design or not, but I have found that if I have a form field which is async validated, the validation function is not called when the field is empty - even if it has previously been touched/edited. This means that I can't perform "required string" validation async, as far as I can tell.

Steps to reproduce:
1. Create a redux-form with one field, with an `asyncValidate` function and the field in `asyncFields`
2. Enter some text in the field and blur it - the validation function will be called
3. Clear the text in the field and blur it - the validation function will not be called

I would expect the function to be called in 3 as I have previously touched the field, and I might for example want to check if a required value is present.

A tiny bit of debugging shows that at 3, `allPristine` in https://github.com/erikras/redux-form/blob/a53f22b816d72dca726d7a220b0e1428dbe522f8/src/createHigherOrderComponent.js#L72 is `true` - perhaps I've misunderstood what pristine refers to in this context, but I think perhaps `allPristine` should be false, as this field has been touched.

Any thoughts? At the minute this prevents me from using async validation for the form I am working on (trying to use https://github.com/jquense/yup to validate against a schema, but it only works with callbacks/promises, not synchronously)

Thanks!
Tom

**Comment by matt-tock** [comment]
I'm also running into this issue. I want to run async validations on a pristine form. The most recent change to check for `allPristine` prior to running async validations breaks my ability to do so.

One use case for this is something like a login form, where sync validations are overkill. I expect my users to understand they need to fill out the entire form to login. But I do want to show an error if they try to submit a blank form or if they accidentally click the button.

**Comment by tomduncalf** [comment]
Ah yes, rolling back to `4.1.5` fixes the issue for now :+1: Cheers!

**Comment by erikras** [comment]
This was introduced by #589, by @cwmanning. My reasoning there is that "require" validation should be "sync".

> One use case for this is something like a login form, where sync validations are overkill. I expect my users to understand they need to fill out the entire form to login. But I do want to show an error if they try to submit a blank form or if they accidentally click the button.

That makes some sense. What should be the correct default behavior, I wonder?

One option we have available is that `redux-form` knows whether or not a form has been initialized with values, so maybe we do the async validation if `syncValidationPasses && (!allPristine || !initialized)`?

**Comment by tomduncalf** [comment]
In my case, I am trying out the Yup library (https://github.com/jquense/yup) for validation against a schema, and all its validation is done async (I guess because you *can* have async validators, so they standardise on that), so I would like to be able to use it to validate required fields (rather than validating some stuff synchronously 'by hand' and some stuff async with the library).

Whether the `yup` approach will scale well or not is another question ;)

Was #589 introduced for performance reasons? For now I will stick to the previous release

**Comment by erikras** [comment]
> But I do want to show an error if they try to submit a blank form or if they accidentally click the button.

Well, that should be submit validation, not async validation. So that example isn't really convincing.

**Comment by erikras** [comment]
@tomduncalf The reason for #589 was given that you don't necessarily want to be firing off server requests if a user is tabbing around from field to field where the values have been loaded from the database, a known valid source. It makes sense to me.

If you're going to be doing whole-record validation, you might want to shift to submit validation (returning the errors when a submission is attempted) rather than async validation.

Oh, you're doing validation on the client side, but it has to be async because that's the API that Yup gives you? Hmm...

**Comment by tomduncalf** [comment]
> Oh, you're doing validation on the client side, but it has to be async because that's the API that Yup gives you? Hmm...

Yeah, exactly :(

**Comment by cwmanning** [comment]
> One option we have available is that redux-form knows whether or not a form has been initialized with values, so maybe we do the async validation if syncValidationPasses && (!allPristine || !initialized)?

That should still work well for the use case I was trying to address in #589. If it's a bigger issue than that, it might also be possible to address the problem by passing `pristine` along with the props in `asyncValidate`. Then you could bail out as needed before making a server request.

**Comment by matt-tock** [comment]
@erikras Submit validation should work for my purposes, thanks for the suggestion. It's a little confusing that the `onSubmit` I pass as a prop to the form component gets eaten when I use it, but that may just be misunderstanding how the redux-form magic works.

I do still think it's reasonable to be able to async validate a pristine form. It'd be nice to have the option, even if the default is to skip it.

**Comment by tomduncalf** [comment]
Was there any conclusion about whether it would be acceptable to async validate a pristine form (perhaps by specifying an option?). I'm stuck on 4.1.5 if not, as the validation library I'm using (which I would otherwise highly recommend! https://github.com/jquense/yup) is async only.

I'd be happy to have a crack at a PR for this, if @cwmanning and @erikras agree that it is desirable in some circumstances?

**Comment by erikras** [comment]
Fix published as [`v4.1.11`](https://github.com/erikras/redux-form/releases/tag/v4.1.11). @tomduncalf, please confirm that this fixes your problem.

**Comment by tomduncalf** [comment]
Thanks @erikras, I will test this out soon!

**Comment by tomduncalf** [comment]
Looks great to me, thank you for the quick response and again thanks for the great library @erikras :)

**Comment by tomduncalf** [comment]
Hey @erikras, afraid I think this bug (or a variant) has caught me again!

The scenario is that I have a form which can be partially populated with `initialValues`. It seems that if it is partially populated, this disables async validation for all fields (including the unpopulated ones) until I make a change in one of the fields. Does this sound like the same thing? Happy to open another issue if you like - I guess my ideal solution would be the ability to say *always* run async validation on blur, regardless of form state.

**Comment by tomduncalf** [comment]
I think this is the line that is causing me problems: https://github.com/erikras/redux-form/blob/master/src/createHigherOrderComponent.js#L78

The first two options that come to my mind are:
1) have an option that can be passed to always run async validation and change this line to:
`if (syncValidationPasses && (alwaysAsyncValidate || (isSubmitting || !allPristine || !initialized))) {` 
or
2) keep track of which form fields have been initialized and which haven't, and still run async validation on those which have not been initialized

Obviously 1 sounds quite a lot easier and would solve this for my use case ;) but I guess people with "heavy" async validation might disagree. I'd certainly be happy to put in a PR for 1 if you think it's a suitable fix (and would have a crack at 2!) - for now I might fork for my purposes.

Cheers

**Comment by erikras** [comment]
Sheesh! It's [whac-a-mole](https://en.wikipedia.org/wiki/Whac-A-Mole).

Sure, try option 2. Maybe with a `_initialized: true` [here](https://github.com/erikras/redux-form/blob/master/src/initializeState.js#L4).

**Comment by tomduncalf** [comment]
You know what, I realised when thinking it through that this isn't a huge issue for our use case. Basically the only issue it causes is that if a user touches one of the other (non-initialized) fields on the form but doesn't modify it, they won't see the validation message until they either modify a field or submit the form. However, it's pretty clear that they need to fill in the other fields, and even if they don't realise that initially, they will do when they submit.

As long as it validates on submit (which it does), it's probably not a huge deal, so I am going to leave it for now and maybe revisit it if it is raised during user testing :)

Cheers!

**Comment by erikras** [comment]
Published @tomduncalf's PR as [`v5.2.3`](https://github.com/erikras/redux-form/releases/tag/v5.2.3).
