### ISSUE TITLE
Callback when submit failed?

### ISSUE THREAD

**Issue by flyfy1** [erikras/redux-form#616]
What I want to achieve: upon clicking the `submit` button, and when we have error, move the screen to the occurrence of the first error.

Method I can come up with: when the submit fails, use jquery to search for error nodes, and `scrollIntoView` the first node.

Issue I am facing: I cannot find the callback when submit fails, from the ReduxForm api / source code.

**Comment by flyfy1** [comment]
Issue resolved (via a hack).

Here's how I solved it, based on the assumption that:

- I'm rendering all the errors using one component.
- I only have one form in my whole application (this restriction can be eliminated)


Basic Idea: manually trace each of the errors into an `error_registry`; when the form component updated after submit, check if there're any error (based on `error_registry`), and scroll to the top elements.


So here's my code:

### `error_registry`
    var error_registry = {}
    var should_scroll = false;

    export default {
      set_error: function(form_name, element){
        error_registry[form_name] = element
      },

      del_error: function(form_name){
        delete error_registry[form_name]
      },

      scroll_to_top_elment: function(){
        var top_ele = null, top_height = null;
        for(var k in error_registry){
          const v = error_registry[k];
          const box = v.getBoundingClientRect();

          if(top_ele == null){
            top_height = box.top;
            top_ele = v;
          } else if(top_height > v.top){
            top_height = v.top;
            top_ele = v;
          }
        }
        if(should_scroll && top_ele){
          top_ele.scrollIntoView();
          should_scroll = false;
        }
      },

      should_scroll: function(){
        should_scroll = true;
      }
    }


### ErrorField:

    export class ErrorField extends Component{
      render(){
        const {field} = this.props

        if(field){
          return (<div className="error-message">{error_from_field(field)}</div>)
        } else{
          return (<div/>)
        }
      }

      componentDidUpdate(){
        const {field} = this.props;
        const field_name = error_field_name(field);
        const error_msg = error_from_field(field);

        if(!field_name) return;

        if(error_msg) DarkMagic.set_error(field_name, ReactDOM.findDOMNode(this).parentNode);
        else DarkMagic.del_error(field_name);
      }
    }



### Form:

    function submit_wrapper(f){
      return function(){
        DarkMagic.should_scroll();
        f.apply(null, arguments);
      }
    }
    

    render: function(){
    ... some code ...
      <form
        onSubmit={ submit_wrapper(handleSubmit((values, dispatch) => dispatch({type: 'review-form-submit', payload: values, history: this.history})))}
      >
     .. form code ...
      </form>
    }

    componentDidUpdate: function(){
      DarkMagic.scroll_to_top_elment();
    }

**Comment by flyfy1** [comment]
How do u feel about this solution / if there're any other better way?

**Comment by erikras** [comment]
Have you looked at #488? Does that help?

**Comment by tomduncalf** [comment]
Funnily enough I was just about to open an issue on this same topic.

In my situation, my form is being async (on blur) validated (only async because I am using the Yup (https://github.com/jquense/yup) library which only supports async validation), which works great - all fields are async validated when submit is clicked, and my `handleSubmit` method does not get called if validation fails. 

However, I want to respond to the validation failure `onSubmit` in the same way as you - scrolling to the error message. I can't work out how to do this... my code looks like the following:

Redux form options:
```
  {
    form: 'signup',
    fields: formFields,
    asyncValidate: (values: any, dispatchFn: Function, props: Props): any => {
      return validateSchema(getSchema(props), values)
    },
    asyncBlurFields: formFields,
  }
```

The `validateSchema` function returns a Promise in the format expected by redux-form (i.e. empty resolved promise if no errors, rejected promise with object of errors if validation failed).

Submit method:

```
  submit(values: any): void {
    ReactDOM.findDOMNode<HTMLFormElement>(this.refs.form).submit()
  }
```

`<form>` tag in `render`:

```
<form method='POST'
          action='/signup'
          onSubmit={handleSubmit(this.submit.bind(this))}
          ref='form'
>
```

I've tried doing something like: `onSubmit={handleSubmit(this.submit.bind(this)).catch(x => console.log(x))}` to hook into failed validation on submit but I get `TypeError: handleSubmit(...).catch is not a function`.

Where would be the appropriate place to hook into this event to do the scroll back? I was wondering if it should be in the `asyncValidate` function but I am not sure how that would know if it is a validation onSubmit (which I want to scroll on failure for) vs onBlur (which I do not want to scroll on).

Any ideas?

Thanks!
Tom

**Comment by andrewmclagan** [comment]
As long the function `this.submit.bind(this)` on you component returns a rejected promise on error it will behave like you intend. 

e.g. `Promise.reject(error)`

or more complete:

```
//.. component code above

  submit = () => {
    const params = [
      this.refs.firstName.value,
      this.refs.lastName.value,
      this.refs.email.value,
      this.refs.password.value,
      this.refs.passwordConfirmation.value,
    ];

    return this.props.signup(...params).then(result => {
      this.setState({ success: result });
    }).catch(error => {
      this.setState({ error: error });
      return Promise.reject(error);
    });
  }

// ... component code below
```

**Comment by erikras** [comment]
@tomduncalf `handleSubmit` [*will* return a rejected promise](https://github.com/erikras/redux-form/blob/master/src/handleSubmit.js#L30) if async validation fails when `returnRejectedSubmitPromise` is set.

**Comment by tomduncalf** [comment]
Cool, thanks for the information, I will give it another go!

**Comment by tnrich** [comment]
Hey there, will handleSubmit return a rejected promise if there is only synchronous validation, and not async?

If not, how can I handle the case where validation fails?

Thanks for the help!

**Comment by lbdremy** [comment]
Yes I'm looking for a way to catch validation error, both sync and async.
In my case I have sync validation error coming the validate method given to reduxForm and async error coming from the method given to handleSubmit(myOnSubmitMethod).

Thanks for the help! :)

**Comment by erikras** [comment]
Well, if you click "submit" and the sync validation fails, you've got the following props:
```js
invalid: true
valid: false
submitFailed: true
errors: {} // all the errors
```
Also, if you have `returnRejectedSubmitPromise` set, as stated above, [it will reject with the sync errors](https://github.com/erikras/redux-form/blob/master/src/handleSubmit.js#L36-L38).

**Comment by pcgilday** [comment]
This does in fact work as @erikras mentions; however, there appears to be some confusion around this as there are a few issues that are at least _somewhat_ related to this (#488, #256, #291), as well as this [stackoverflow](http://stackoverflow.com/questions/35096904/cannot-get-returnrejectedsubmitpromise-to-work) question that I think nails the confusion people are having. 

You need to have the `returnRejectedSubmitPromise` set, docs on that are [here](http://redux-form.com/5.0.1/#/api/reduxForm?_k=7c4drb). 

When calling `handleSubmit()` within the connected form, it returns a function to be called `onSubmit` like this.

```js
const submitFn = handleSubmit(mySubmitFn) // submitFn is a function

<button onClick={submitFn} />
```

Therefore, you cannot add the catch function like this
```js
const submitFn = handleSubmit(mySubmitFn)
  .catch(err => {
    // do something with the error
  })

<button onClick={submitFn} />
```
It is the `submitFn` returned in this scenario that returns the rejected promise if validation fails, so you need something like this.

```js
const submitFn = (event) => handleSubmit(mySubmitFn)(event)
  .catch(err => {
    // do something with the error
  })

<button onClick={submitFn} />
```

I hope this helps anyone that may still be having trouble.

**Comment by erikras** [comment]
Wish granted: [`v5.1.0`](https://github.com/erikras/redux-form/releases/tag/v5.1.0).

**Comment by andrewmclagan** [comment]
👯
