### ISSUE TITLE
Documentation about propTypes may be wrong

### ISSUE THREAD

**Issue by lasergoat** [erikras/redux-form#62]
In the readme at line 120 it says:

```
class ContactForm extends Component {
  static propTypes = {
    fields: PropTypes.object.isRequired,
    handleSubmit: PropTypes.func.isRequired
  }

```

However, with these deps in `package.json`: 

```
    "babel": "^5.8.21",
    "babel-core": "^5.8.22",
    "babel-loader": "^5.3.2",
    "webpack": "^1.12.0",
    "webpack-dev-server": "^1.10.1"
```

I had to change the line to:

```
  static propTypes: {
```

**Comment by erikras** [comment]
That's pretty weird. I always use `static propTypes = {};`. I've never seen the `:` syntax.

Can you research this in the babel docs?

Also, _brilliant_ username!

<img src="https://overcomebyballoons.files.wordpress.com/2015/01/lasergoat.jpg" width="400"/>

**Comment by rstuven** [comment]
Try adding a `.babelrc` file:
```
{
  "stage": 0
}
```

**Comment by lasergoat** [comment]
Weird, ok, I'm pretty new to babel and such. Us goats...

**Comment by lasergoat** [comment]
@erikras beautiful picture of a laser goat! +1
