### ISSUE TITLE
deep nested arrays not working

### ISSUE THREAD

**Issue by tamagokun** [erikras/redux-form#620]
Here's an example reduxForm (4.1.6) declaration:

```js
@reduxForm({
  form: 'artwork',
  fields: ['artwork[].variants[].id', 'artwork[].variants[].markup'],
  initialValues: {
    artwork: [
      {variants: [
        {id: 1, markup: 10},
        {id: 2, markup: 10}
      ]}
    ]
  }
})
```

However when I log the value of `this.props.fields.artwork`, it turns up empty. I'm suspecting that redux form just isn't understanding the nested shape of the artwork array.

**Comment by tamagokun** [comment]
Interesting update:

If I manually initialize the form, it will actually work!

```js
const values = {
  artwork: [
    {variants: [
      {id: 1, markup: 10},
      {id: 2, markup: 10}
    ]}
  ]
}

@reduxForm({
  form: 'artwork',
  fields: ['artwork[].variants[].id', 'artwork[].variants[].markup']
})
export default class Form extends Component {
  componentDidMount() {
    this.props.initializeForm(values)
  }
}
```

**Comment by tamagokun** [comment]
More findings:

Even though manually calling `initializeForm` appears to make things work, another issue crops up. I am passing some state into child components, and when a portion of deeply nested state is changed, it seems to mutate the parent array/object rather than create a new one, which causes the child components to not update. I ended up having to force the fields to be recreated every render and using `shouldComponentUpdate` to keep things calm.

Here's what I ended up with:

```js
const values = {
  artwork: [
    {variants: [
      {id: 1, markup: 10},
      {id: 2, markup: 10}
    ]}
  ]
}

@reduxForm({
  form: 'artwork',
  fields: ['artwork[].variants[].id', 'artwork[].variants[].markup']
})
export default class Form extends Component {
  componentDidMount() {
    this.props.initializeForm(values)
  }

  render() {
    const {fields, handleSubmit} = this.props
    return <form onSubmit={handleSubmit}>
      {fields.artwork.map((artwork, i) => {
        const fields = {...artwork}
        return <ArtworkForm fields={fields} key={i} />
      }
    </form>
  }
}
```

**Comment by mmakarin** [comment]
My understanding is that you have to declare field of each level separately. In your example it would look like `fields: ['artwork[]', 'artwork[].variants[]', 'artwork[].variants[].id', 'artwork[].variants[].markup'],`

**Comment by ooflorent** [comment]
It's a known issue that nested fields fail to update (see #436).
Redux Form ships several improvements to `initialValues`. Switching to the latest release should fix the form initialization.
