### ISSUE TITLE
How to set field values?

### ISSUE THREAD

**Issue by dukedougal** [erikras/redux-form#622]
This seems like the most obvious of questions but I can't find a simple and direct answer anywhere.

How do I programmatically set field values?

**Comment by davidkpiano** [comment]
From http://erikras.github.io/redux-form/#/api/action-creators you would `dispatch()` the `change(form:String, field:String, value:String)` action creator:

```js
import { change } from 'redux-form';

// in your connected component
dispatch(change('user', 'firstName', 'Bob'));
```

**Comment by dukedougal** [comment]
It says Uncaught ReferenceError: dispatch is not defined

**Comment by dukedougal** [comment]
OK I found I need to do this.props.dispatch

Sorry for the dumb questions.

**Comment by jycr753** [comment]
Just FYI the new Url is http://redux-form.com/6.4.3/docs/api/ActionCreators.md/ for anyone looking.
