### ISSUE TITLE
input re-use and defaultValue

### ISSUE THREAD

**Issue by rhythnic** [erikras/redux-form#627]
In my form I have a fieldset that is populated with data based on the current value of a drop-down menu. The form is being passed initialValues, so the field property objects all have defaultValues. Because you can't update a defaultValue on an input in React, I'm running into an issue. One input in the fieldset will be populated with a defaultValue. Once the drop-down menu changes, and the input receives a new set of props, but not a value prop, it continues to display the defaultValue of the previous set of props.

Does anyone know a possible workaround? I might try to wrap the input component to always have an empty string as a value if the value is undefined.
Is there a way to initialize a reduxForm form without setting the defaultValue on input elements?

**Comment by erikras** [comment]
There is much strangeness around `undefined` values with react inputs. For example, to clear a `<textarea>` or `<select>`, you must change the value to `''`. If you can give a more detailed example with code, I can maybe determine if what you are seeing is `redux-form`'s fault, but I'm not understanding fully how your code is laid out from your description.

**Comment by rhythnic** [comment]
My use case is complicated, so I recreated the issue with a one-field form.  Thanks for helping out and for maintaining redux-form.

```
// Form Component
class ContactForm extends Component {
  render() {
    const {fields: {firstName, lastName, email}, handleSubmit, setting} = this.props;
    const fieldProps = setting === 'last'
      ? Object.assign({placeholder: "Last Name"}, lastName)
      : Object.assign({placeholder: "First Name"}, firstName});
    return (
      <form onSubmit={handleSubmit}>
        <input type="text"  {...fieldProps}/>
        <button type="submit">Submit</button>
      </form>
    );
  }
}

ContactForm = reduxForm({
  form: 'contact',
  fields: ['firstName', 'lastName', 'email']
})(ContactForm);

export default ContactForm;


// Inside Parent Component
// setName is an action creator and this.props.name is coming in via connect
const data = {firstName: 'Saul'}
<button onClick={() => this.props.setName('last')}>Toggle Name</button>
<ContactForm onSubmit={data => console.log(data)} initialValues={data} setting={this.props.name}/>
```

The 'setting' prop is initially 'first', so the input field is given the firstName fields and displays 'Saul'.  When setting changes to 'last', and the input field is given the lastName field props, the input field continues to display 'Saul', because lastName is not defined in initialValues.

In my actual use case, I have an array of objects and a fieldset to edit one item of the array, depending on which index is selected.  When changing items, if on field 'A', the previous item had a defaultValue, and the current item does not have a defaultValue or a value, it will display the defaultValue of the previous item.

**Comment by rhythnic** [comment]
I've solved the issue temporarily by wrapping the input element and filtering out 'defaultValue'.  Initializing values still seems to work fine, so I'm going with this fix for now.
