### ISSUE TITLE
Deep Form with initialValues can not be cleared

### ISSUE THREAD

**Issue by kromit** [erikras/redux-form#628]
I want to modify an existing list of items in a deep form, so I use `initialValues` with a list of items. 
Then item are removed from the form using `items.removeField(index)` and then add some new items, those new items are initialized with values from previously removed items

**Comment by erikras** [comment]
Can you inspect what is happening in the redux store with a `console.log()` or `redux-devtools`?

**Comment by kromit** [comment]
Form with `initialValues={{deepform:[{deepfield:"a"},{deepfield:"b"}],myfield:"123"}}`.
Removing last item: action `{type: "redux-form/REMOVE_ARRAY_VALUE", path: "deepform", index: 1, form: "testform"}` is fired.

everything OK until now.

add new item: action
    
    {
          form: "testform"
          index: undefined
          path: "deepform"
          type: "redux-form/ADD_ARRAY_VALUE"
          value: undefined
          fields: ["deepfield"]
    }

now the form state looks like this

    { 
        myfield:{_isFieldValue: true, initial: "123", value: "123"},
        deepform:[
              {deepfield:{_isFieldValue: true,initial: "a",value: "a",}},
              { _isFieldValue: true, value: undefined} /*no deepfield here?*/
       ]                
    }

the incoming fields look like this:

     {
         myfield:{value:"123", defaultValue:"123", initilValue:"123",...... },
         deepform:[
              {deepfield:{value:"a", defaultValue:"a", initilValue:"a",......}},
              {deepfield:{defaultValue:"b", initilValue:"b",......}}  /* no value here*/
         ]               
     }

**Comment by kromit** [comment]
`<input defaultValue={"b"} initialValue={"b"}/>` 
or
`<input defaultValue={"b"} initialValue={"b"} value={undefined}/>`
or
`<input defaultValue={"b"} initialValue={"b"} value={null}/>`
all show `b` because of reacts internal logic

So the only option is to rid of the `initialValue` and `defaultValue` for new deep form fields.  I like this because an entirely new item can not have any initial/default values.

**Comment by erikras** [comment]
Okay, I understand what's going on. This is related to #621, where `defaultValue` and `initialValue` are falling back to the `initialValues` prop when there is nothing in the Redux store, but it needs to _not_ do that when the form is marked as already initialized.

Fantastic reporting. Thank you.

**Comment by ooflorent** [comment]
@kromit I think v5.1.4 solved this. Can you confirm it?

**Comment by kromit** [comment]
On mobile now. I will check it tomorrow.

Florent Cailhol <notifications@github.com> schrieb am Mi., 11. Mai 2016,
17:41:

**Comment by ooflorent** [comment]
Redux Form no longer uses `defaultValue` (support removed in 5.0.0, see #789). I'm not sure if this issue is still relevant.

**Comment by 2easy** [comment]
Hi, I have similar problem. I've got deep form `product.tagList[]` with initialValues set. Then when I do `tagList.removeField(last)` and `addArrayValue('product', tagList, newTagObject)` - it gets initialized again with the initialValues (on those fields which are not set in newTagObject, but are set in initialValues). Is it expected behavior?

**Comment by kromit** [comment]
@ooflorent I am using 5.2.3 and it seems to be fixed. #662 seems to be the same.

@2easy If your problem persists, you can use `items.addField({"deepField1":"","deepField2":""})` to initialize your new deep form with empty strings.

**Comment by ooflorent** [comment]
Awesome, thanks @kromit
