### ISSUE TITLE
Integrate with flux standard actions

### ISSUE THREAD

**Issue by allanhortle** [erikras/redux-form#63]
It would be great if you could supply FSA actions straight into the `onSubmit` handler

I've got a bunch of actions made with redux-actions that return a promise. But they don't seem to play nice when just passed into `onSubmit`. 

https://github.com/acdlite/redux-actions

**Comment by allanhortle** [comment]
Scratch that. It works perfectly. I just wasn't returning the action/promise from my handleSubmit function. Props on an awesome set of tools. It's wonderful.

**Comment by erikras** [comment]
👍🏻 Thanks!

**Comment by erikras** [comment]
FSA compliance is now published in [`v6.0.0-alpha-7`](https://github.com/erikras/redux-form/releases/tag/v6.0.0-alpha.7).
