### ISSUE TITLE
Is it possible to add a 'type' property in fields?

### ISSUE THREAD

**Issue by DrkCoater** [erikras/redux-form#631]
for indicating whether is field is password, text, textrarea etc?
it's useful for generating markups.

**Comment by erikras** [comment]
That is currently not supported. But you're welcome to write up a proposal as to how it might be accomplished.

**Comment by kristian-puccio** [comment]
Is it needed? I just pass a prop to the form with data derived from the
same source I used to generate the fields list.

I have things like label, type and description.

I loop over this list, create a widget, lookup the appropriate field and
pass that as well
