### ISSUE TITLE
How can I addField to object, not an array?

### ISSUE THREAD

**Issue by stepankuzmin** [erikras/redux-form#633]
Hi there! I want to use redux-form with dynamic fields that are objects and not arrays, e.g. I want to dynamically add new field, that is not listed in form `fields` settings. How can I achieve this?

E.g. my `fields` setting

```js
  const fields = [
    'id',
    'geometry.type',
    'geometry.coordinates',
    'properties[]'
  ]
```
Now I can dynamically add new properties as array, but I want to treat it like an object, because `properties` is an JSON object and it may change later on form usage, so I need something like `properties{}` or something else.

I think, that I can store keys-indexes accordance somewhere and handle it somehow on form changes (e.g. addField with index) but it's really not so good as it can be with using properties as object.

**Comment by erikras** [comment]
You may pass the `fields` array as a prop, which means that the component containing your decorated form can add or remove items from it. This is demonstrated in the [Dynamic Form](http://erikras.github.io/redux-form/#/examples/dynamic) example. You may put any arbitrary items into your `properties` array, but if you want them to be keyed and for the input events to be handled by `redux-form`, you will have to specify their shape, and they all must have the same shape...
```js
const fields = [
  'id',
  'geometry.type',
  'geometry.coordinates',
  'properties[].name',
  'properties[].value'
];
```
...as seen in the [Deep Form](http://erikras.github.io/redux-form/#/examples/deep) example.

Does that help?

**Comment by stepankuzmin** [comment]
Hi @erikras! I think that it may work, thanks for reply!
