### ISSUE TITLE
deep mount point

### ISSUE THREAD

**Issue by pierregm** [erikras/redux-form#634]
Even if it is possible to define an alternate mount point at the root of the main reducer, I can't define a deeper one.

For example, the app I'm working on has a few nested reducers:
``state = combineReducers({settings:..., tables:..., user: userReducer})``
where ``userReducer = combineReducer({info:..., form:formReducer})``.
My mount point would be 'user.form', but that won't work with the current getFormState in 'createReduxFormConnector.js L56`.

Would something like the following work ?
``getFormState = (state, reduxMountPoint) => reduxMountPoint.split('.').reduce((s,k) => s[k], state)``

**Comment by erikras** [comment]
You can provide your own `getFormState()` as a [config parameter](http://erikras.github.io/redux-form/#/api/reduxForm). You can have your mount point wherever you want, as long as the `getFormState()` that you provide can get it from the global state.

**Comment by pierregm** [comment]
Awesome! Thanks a lot for the quick answer.

**Comment by timrichd** [comment]
I find my forms are generally nested deep in my components, and thus i would like the form state to sit in those state slices. Furthermore I'd like to be able to mount different forms at different mount points within the tree. Is this possible at all? If not why did you choose to make all the forms in one namespace?
