### ISSUE TITLE
multi checkbox form

### ISSUE THREAD

**Issue by SpencerCDixon** [erikras/redux-form#635]
I don't know why but I can't seem to conceptualize how to properly build a form that has a bunch of checkboxes and the user can click 1-many of them. 

The fields for the checkboxes are dynamic and come from an async request (or in this case are already stored in my redux store). 

**Here is the scenario:**
User is creating an account.  There are many teams they can be apart of.  When it comes to the team selection process I want a bunch of checkboxes with all the teams.  They can click on which teams they want to be apart of.  (this is a somewhat simplified version of the real multi-step form wizard I'm building)

I have tried following something along the lines of this: https://github.com/lemonCMS/redux-form-generator/blob/master/src/types/checkboxList.js

But I can't get it to work and it also seems somewhat hacky and I feel like there is probably a way to follow one of the examples that erikas has spent so much time building.  I've literally been looking at the examples for the last like 5 hours though and am not making much progress.

Should teams field of my form be an array like this: `teams[]`?  I've tried doing that and then use the `addArrayValue` redux-form method to pass a callback down from my form container to a MultiCheckbox component I created and the MultiCheckbox calls that callback which just delegates to `addArrayValue`.  Should I be using the `change` and `changeWithKey` A-Creators instead??

Any help/guidance would be much appreciated.  If this belongs in SO I can close issue and post there instead.  Thank you ahead of time and if I need to supply more context or code samples please let me know!

**Comment by erikras** [comment]
Does this help? https://github.com/erikras/redux-form/issues/434#issuecomment-169171734

**Comment by SpencerCDixon** [comment]
I ended up getting something functional by following the checkboxList that lemonCMS made.  Here is what it looks like if anyone else needs to do something like this... its not perfect and I'm sure @erikras can do it a better/more redux-formy way.

```
import React, { Component, PropTypes } from 'react';
import { change } from 'redux-form';
import _ from 'lodash';

const propTypes = {
  dispatch: PropTypes.func.isRequired,
  options: PropTypes.arrayOf(
    PropTypes.shape({
      id: PropTypes.number.isRequired,  // comp returns array of ids of selected checkboxes
      name: PropTypes.string.isRequired // name used to display the checkbox
    })
  ).isRequired,
  formName: PropTypes.string.isRequired,
  fieldName: PropTypes.string.isRequired,
  selectedOptions: PropTypes.object.isRequired // Original form field
};

class MultiCheckbox extends Component {
  constructor(props) {
    super(props);
    this.handleChange = this.handleChange.bind(this);
    this.handleSelectAll = this.handleSelectAll.bind(this);
    this.selectedIds = this.selectedIds.bind(this);
    this.addValues = this.addValues.bind(this);
  }

  selectedIds() {
    const { selectedOptions } = this.props;
    if (selectedOptions.value) {
      return selectedOptions.value;
    } else if (selectedOptions.initialValue) {
      return selectedOptions.intialValue;
    } else {
      return [];
    }
  }

  addValues(values) {
    const { formName, fieldName, dispatch } = this.props;
    dispatch(change(formName, fieldName, _.uniq(values)));
  }

  handleSelectAll(e) {
    e.preventDefault();
    let idsToAdd;

    if (this.selectedIds().length > 0) {
      idsToAdd = [];
    } else {
      idsToAdd = this.props.options.map(opt => opt.id);
    }
    this.addValues(idsToAdd);
  }

  handleChange(e, id) {
    const { selectedOptions } = this.props;
    let values = this.selectedIds();

    if (!Array.isArray(values)) { values = [values] };

    if (e.target.checked) {
      values.push(id);
    } else {
      values.splice(_.indexOf(values, id), 1);
    }

    this.addValues(values);
  }

  render() {
    const { options } = this.props;
    const checkBoxes = options.map(opt => {
      return (
        <label key={opt.id}>
          {opt.name}
          <input
            type="checkbox"
            checked={this.selectedIds().indexOf(opt.id) > -1}
            value={JSON.stringify(opt)}
            onChange={(e) => this.handleChange(e, opt.id)} 
          />
        </label>
      )
    });

    return (
      <div>
        <button onClick={this.handleSelectAll}>
          Add All
        </button>
        {checkBoxes}
      </div>
    )
  }
}

MultiCheckbox.propTypes = propTypes;
export default MultiCheckbox;
```

Really don't need to use lodash so if its not already a dep in project you can prob replace all the `_` calls

**Comment by marcosideame** [comment]
@SpencerCDixon 
I changed the component a little because It didn't work, for instance, 
```
import React, { Component, PropTypes } from 'react';
import { change } from 'redux-form';
import _ from 'lodash';

const propTypes = {
    dispatch: PropTypes.func.isRequired,
    options: PropTypes.arrayOf(
        PropTypes.shape({
            id: PropTypes.number.isRequired,  // comp returns array of ids of selected checkboxes
            name: PropTypes.string.isRequired // name used to display the checkbox
        })
    ).isRequired,
    formName: PropTypes.string.isRequired,
    fieldName: PropTypes.string.isRequired,
    selectedOptions: PropTypes.object.isRequired // Original form field
};

class MultiCheckbox extends Component {
    constructor(props) {
        super(props);
        this.handleChange = this.handleChange.bind(this);
        this.handleSelectAll = this.handleSelectAll.bind(this);
        this.selectedIds = this.selectedIds.bind(this);
        this.addValues = this.addValues.bind(this);
        this.state = {
            values: this.selectedIds()
        }
    }

    selectedIds() {
        const { selectedOptions } = this.props;
        if ( selectedOptions!= 'undefined' && selectedOptions.value) {
            return selectedOptions.value;
        } else if (selectedOptions.initialValue) {
            return selectedOptions.intialValue;
        } else {
            return [];
        }
    }

    addValues(values) {
        const { formName, fieldName, dispatch } = this.props;
        this.setState({
            values: values
        })
        dispatch(change(formName, fieldName, values));
    }

    handleSelectAll(e) {
        e.preventDefault();
        let idsToAdd;

        if (this.state.values.length > 0) {
            idsToAdd = [];
        } else {
            idsToAdd = this.props.options.map(opt => opt.id);
        }
        this.addValues(idsToAdd);
    }

    handleChange(e, id) {
        let values = this.state.values;

        if (!Array.isArray(values)) { values = [values] };

        console.log(e.target.checked);
        if (e.target.checked) {
            values.push(id);
        } else {
            values.splice(_.indexOf(values, id), 1);
        }

        this.addValues(values);
    }

    render() {
        const { options, fieldName } = this.props;
        const checkBoxes = options.map(opt => {
            return (
                <div className="radio">
                    <label key={opt.id}>
                        <input
                            type="checkbox"
                            checked={this.state.values.indexOf(opt.id) > -1}
                            value={JSON.stringify(opt)}
                            onChange={(e) => {
                                console.log(this.state.values, opt.id);
                                this.handleChange(e, opt.id)
                                console.log(this.state.values);
                            }}
                        />
                        {opt.name}
                    </label>

                </div>
            )
        });

        return (
            <div>
            {checkBoxes}
            </div>
        )
    }
}

MultiCheckbox.propTypes = propTypes;
export default MultiCheckbox;
```

**Comment by jordanmkoncz** [comment]
@SpencerCDixon @marcosideame I was trying to create the same type of MultiCheckbox component and had issues with both of your solutions. I ended up with a different solution that functions the same as regular inputs and is more similar to examples found in the redux-form docs, and is more simple.

```
import React, {Component, PropTypes} from 'react';
import isUndefined from 'lodash/isUndefined';
import isArray from 'lodash/isArray';

class MultiCheckbox extends Component {
    constructor() {
        super();

        this.getCurrentValues = this.getCurrentValues.bind(this);
        this.handleChange = this.handleChange.bind(this);
    }

    getCurrentValues() {
        const {value, initialValue} = this.props;

        let previousValues = [];

        if (!isUndefined(value) && value !== '') {
            previousValues = value;
        }
        else if (!isUndefined(initialValue) && initialValue !== '') {
            previousValues = initialValue;
        }

        const currentValues = isArray(previousValues) ? [...previousValues] : [previousValues];

        return currentValues;
    }

    handleChange(event, id) {
        const {onChange} = this.props;
        const values = this.getCurrentValues();

        if (event.target.checked) {
            values.push(id);
        }
        else {
            values.splice(values.indexOf(id), 1);
        }

        return onChange(values);
    }

    render() {
        const {options, onBlur, ...rest} = this.props;
        const values = this.getCurrentValues();

        const checkboxes = options.map(option => {
            const isChecked = values.indexOf(option.id) > -1;

            return (
                <div key={option.id}
                     className="checkbox">
                    <label>
                        <input
                            type="checkbox"
                            {...rest}
                            onChange={event => this.handleChange(event, option.id)}
                            onBlur={() => onBlur(values)}
                            checked={isChecked}
                            value={option.id}
                        />

                        {option.label}
                    </label>
                </div>
            );
        });

        return (
            <div className="checkboxes">
                {checkboxes}
            </div>
        );
    }
}

MultiCheckbox.propTypes = {
    options: PropTypes.arrayOf(
        PropTypes.shape({
            id: PropTypes.number.isRequired,
            label: PropTypes.string.isRequired
        })
    ).isRequired,
    onBlur: PropTypes.func.isRequired,
    onChange: PropTypes.func.isRequired,
    value: PropTypes.any.isRequired,
    initialValue: PropTypes.any.isRequired
};

export default MultiCheckbox;
```

This component is being used like so:

```
<MultiCheckbox
    options={options}
    {...field}
/>
```

**Comment by Roomtailors** [comment]
Hi @jordanmkoncz, 
I am quite new to redux-form, can you provide a complete example that shows the full usage of the MultiCheckbox component with all options? That would be a great help to me.

**Comment by jordanmkoncz** [comment]
Hey @Roomtailors, yeah sure, see below for an example of how I'm using this component. Also, since I first posted the component code I've made some minor improvements to it, and I've edited my previous comment above to include my current version of this component.

Example usage of MultiCheckboxField:

```
import React, {Component, PropTypes} from 'react';
import {reduxForm} from 'redux-form';
import MultiCheckboxField from '../components/MultiCheckboxField';

class FavouriteFruitsForm extends Component {
    render() {
        const {
            handleSubmit,
            fields: {
                fruits
            }
        } = this.props;
        
        const fruitOptions = [
            {
                id: 'apple',
                label: 'Apples'
            },
            {
                id: 'banana',
                label: 'Bananas'
            },
            {
                id: 'orange',
                label: 'Oranges'
            }
        ];
        
        return (
            <form onSubmit={handleSubmit}>
                <MultiCheckboxField
                    label="Favourite Fruits"
                    options={fruitOptions}
                    field={fruits}
                />
                
                <button type="submit">
                    Submit
                </button>
            </form>
        )
    }
}

FavouriteFruitsForm.propTypes = {
    handleSubmit: PropTypes.func.isRequired,
    fields: PropTypes.object.isRequired
};

FavouriteFruitsForm = reduxForm({
    form: 'favouriteFruits',
    fields: ['fruits']
})(FavouriteFruitsForm);

export default FavouriteFruitsForm;
```

**Comment by Roomtailors** [comment]
@jordanmkoncz Thanks a lot for your quick answer. This helped my a lot getting it done. It was quite a struggle because I am new to react and redux and I want to do something fairly complicated (for me). I want to build a dynamic multi-step questionnaire that creates all questions and order based on a data-format. Cheers to you!

**Comment by kfatehi** [comment]
I too used MultiCheckboxField posted above (thanks for that), but my usage was like so:

```
<Field name="fruits" component={props=>
  <MultiCheckboxField
    options={fruitOptions}
    field={props.input}
  />
} /> 
```

Reason being that `fields` doesn't appear to be an option on `reduxForm` as far as I can tell. I'm using version 6.1.1 of redux-form

**Comment by jspaine** [comment]
Just did this using a [normalizer](http://redux-form.com/6.6.2/examples/normalizing/):
```js
<Field 
  component={renderFieldGroup}
  normalize={normalizeCheckboxValues}
  {...props}
/>

function renderFieldGroup(input, meta, options, props) {
  return (
    <div>
      {options.map((option, i) =>
        <Checkbox
          key={i}
          {...props}
          value={option}
          onChange={() => props.onChange(option)}
          checked={isChecked(props.value, option)}
        >
          {option}
        </Checkbox>
      )}
    </div>
  )
}

function normalizeCheckboxValues(value, previousValue) {
  // only the onChange event returns a string
  if (typeof value !== 'string') return previousValue
  if (!previousValue || !previousValue.length) return [value]
  if (!previousValue.find(val => val === value))
    return [...previousValue, value]
  return previousValue.filter(val => val !== value)
}
```
There's a few things that caught me out spreading props like that. Don't set type="checkbox" on the redux form Field component. And in renderFieldGroup props.value is the value of the actual field, but the value of the checkboxes needs to be set to the option, so spread the props before setting the value.

**Comment by zentuit** [comment]
@jspaine : what does your `Checkbox` component look like?

**Comment by jspaine** [comment]
@zentuit It can just be `<input type="checkbox" ... />`. But I'm using react-bootstrap so just made a simplified example based on that.

**Comment by khurrams84** [comment]
Can any one post full example of multicheckbox with add and edit example.

**Comment by jordanmkoncz** [comment]
@jspaine Great idea with using `normalize`, just used that for a MultiCheckboxField in v6.

**Comment by galgoketan** [comment]
Hi @jordanmkoncz, 
I am quite new to redux-form, (thanks for the above example) and in my case i need to create checkboxes based on dynamic data and this is what i do..

// using MultiCheckboxField component in redux form
<div className="col-md-12">
     <label className="item-name">Taxes</label>
          <div>
              <MultiCheckboxField
                  label="Taxes"
                  options={this.props.invoicetaxDetail}
                  {...Field}
              />
         </div>
</div>

// MultiCheckboxField component

import React, {Component, PropTypes} from 'react';
import isUndefined from 'lodash/isUndefined';
import isArray from 'lodash/isArray';

class MultiCheckbox extends Component {
    constructor() {
        super();

        this.getCurrentValues = this.getCurrentValues.bind(this);
        this.handleChange = this.handleChange.bind(this);
    }

    getCurrentValues() {
        const {value, initialValue} = this.props;

        let previousValues = [];

        if (!isUndefined(value) && value !== '') {
            previousValues = value;
        }
        else if (!isUndefined(initialValue) && initialValue !== '') {
            previousValues = initialValue;
        }

        const currentValues = isArray(previousValues) ? [...previousValues] : [previousValues];

        return currentValues;
    }

    handleChange(event, id) {
        const {onChange} = this.props;
        const values = this.getCurrentValues();

        if (event.target.checked) {
            values.push(id);
        }
        else {
            values.splice(values.indexOf(id), 1);
        }

        return onChange(values);
    }

    render() {
        const {options, onBlur, ...rest} = this.props;
        const values = this.getCurrentValues();

        const checkboxes = options.map(option => {
            const isChecked = values.indexOf(option.id) > -1;

            return (
                <div key={option.id}
                     className="checkbox">
                    <label>
                        <input
                            type="checkbox"
                            {...rest}
                            onChange={event => this.handleChange(event, option.id)}
                            onBlur={() => onBlur(values)}
                            checked={isChecked}
                            value={option.id}
                        />

                        {option.label}
                    </label>
                </div>
            );
        });

        return (
            <div className="checkboxes">
                {checkboxes}
            </div>
        );
    }
}

MultiCheckbox.propTypes = {
    options: PropTypes.arrayOf(
        PropTypes.shape({
            id: PropTypes.number.isRequired,
            label: PropTypes.string.isRequired
        })
    ).isRequired,
    onBlur: PropTypes.func.isRequired,
    onChange: PropTypes.func.isRequired,
    value: PropTypes.any.isRequired,
    initialValue: PropTypes.any.isRequired
};

export default MultiCheckbox;

// Errors what i getting..

 Uncaught TypeError: onChange is not a function
    at MultiCheckbox.handleChange

 Uncaught TypeError: _onBlur is not a function
    at onBlur

 if anyone can help me in this regard will be appreciated.

**Comment by LazzyLizzard** [comment]
Has any one **really** got this component working? 
I could never obtain correct value from getCurrentValues(), it always returns empty string. What's wrong with it?

**Comment by mschipperheyn** [comment]
use a formSelector to get current values?
