### ISSUE TITLE
Action after submit validation 

### ISSUE THREAD

**Issue by TonyVeigel** [erikras/redux-form#636]
I have read other issues on here regarding submit validation but I guess I still don't understand it. 

First my problem. Trying to do this causes an invariant violation. 
```
const submit = (values) => {
    if (!values.type) {
     return Promise.reject({type: 'Type must be provided.'});
   }else{
     browserHistory.push('/location)
   }
}

<form onSubmit={handleSubmit(submit)}>
```

So I figured that if I do the browserHistory.push after the form is done submitting then that would fix the issue because doing ```onClick={() => browserHistory.push('/location)}``` works just fine. 

sudo:
```
<form onSubmit={handleSubmit(submit).then(() => browserHistory.push('/location))}>
```

How can I get this to work? I have tried different variations and using ```returnRejectedSubmitPromise:true```.

Thanks!

**Comment by erikras** [comment]
What is the nature of the invariant violation? That's pretty strange.

It seems like your
```js
<form onSubmit={handleSubmit(submit).then(() => browserHistory.push('/location'))}>
```
example should work, as long as you return `Promise.resolve()` from your `submit()` if there are no errors.

**Comment by TonyVeigel** [comment]
I think the invariant violation comes from a message that is being displayed on the screen. Further up when the route changes I clear all messages and that seems to be causing the issue. I have racked by brain trying to figure out why.

Uncaught Invariant Violation: findComponentRoot(..., .0.1.0.0.1:$0.1): Unable to find element.

```
const submit = (values) => {
    if (!values.recipientType) {
     return Promise.reject({recipientType: 'Recipient Type must be provided.'});
   }else{
     return Promise.resolve();
   }
}
<form onSubmit={handleSubmit(submit).then(() => browserHistory.push('/location'))}>
```
 Always says  handleSubmit(...).then is not a function

**Comment by erikras** [comment]
This looks like the bug that I _just_ published the fix for. Try [`v4.1.10`](https://github.com/erikras/redux-form/releases/tag/v4.1.10).

**Comment by TonyVeigel** [comment]
I get the same error. Maybe I am doing something else wrong. This is the form minus unnecessary stuff. 

  "name": "redux-form",
  "version": "4.1.10",

```
import React, {Component, PropTypes} from 'react';
import {reduxForm} from 'redux-form';
import { browserHistory } from 'react-router';


const submit = (values) => {
    if (!values.recipientType) {
     return Promise.reject({recipientType: 'Recipient Type must be provided.'});
   }else{
     return Promise.resolve();
   }
}

class RecipientType extends Component {

  static propTypes = {
      fields: PropTypes.object.isRequired
  }

  render(){
    const {fields:{recipientType}, handleSubmit} = this.props;
    return(
      <form onSubmit={handleSubmit(submit).then(()=> browserHistory.push('/location))}>

    </form>
    );
  }
}

export default reduxForm({
  form: 'packageWizard',
  fields: ['recipientType']
})(RecipientType)
```

**Comment by TonyVeigel** [comment]
```
<form onSubmit={e => handleSubmit(submit)(e).then(() => browserHistory.push('/comm/admin/secure/app/package/wizard/recipients'))}>
```

works now, it didn't before 4.1.10
