### ISSUE TITLE
Wrong PropTypes in the dynamic form example?

### ISSUE THREAD

**Issue by rnsloan** [erikras/redux-form#638]
http://erikras.github.io/redux-form/#/examples/dynamic?_k=uloide  

`fields: PropTypes.object.isRequired,` in the `DynamicForm.js` code block , but looking at the parent component above `DynamicFormContainer.js

**Comment by erikras** [comment]
The `fields` object is provided by `redux-form` itself. Note that `DynamicForm` is decorated with `reduxForm()` at the bottom of `DynamicForm.js`.

**Comment by rnsloan** [comment]
Apologies, I am sure I clicked the back button in Chrome when I realised this and yet this issue was still somehow posted.
