### ISSUE TITLE
Multiple field errors?

### ISSUE THREAD

**Issue by JakeGinnivan** [erikras/redux-form#639]
It seems that there is some sort of array normalisation on field errors.

If my submit function returns a rejected promise with:

`"password":["Passwords must have at least one non letter and non digit character.","Passwords must have at least one uppercase ('A'-'Z')."]}` for instance, the `submitError` on that field ends up being `Passwords must have at least one non letter and non digit character.`

Is there any way to leave it as the array so I can display all the errors for that field?

I am working around it with a generic "Password has validation errors" then displaying the list with `_error`. 

Appreciate any direction you can give :)

**Comment by erikras** [comment]
Yes, at the moment, if you give back an array of errors, it will only pull and use the first one.

The same is not true of objects, so if you wanted, you could wrap your array in an object, to bypass the "use first error" logic. e.g.
```js
{
  password: {
    allErrors: [ // <---- arbitrary key
      "Passwords must have at least one non letter and non digit character.",
      "Passwords must have at least one uppercase ('A'-'Z')."
    ]
  }
}
```

**Comment by confiks** [comment]
@erikras Could you give a hint to why multiple validation errors are not supported? Do you think fields should just have a single error, or is this something that is hard to implement / not a priority / etc.? When I filed #523 I thought about writing a PR, but I see the surface area for multiple errors is quite big, and I don't yet know your opinion on the matter.

**Comment by pokonski** [comment]
It would be good to have support for those, since most bigger back-end frameworks do return arrays per field.

**Comment by erikras** [comment]
This is a way in which `redux-form` is opinionated, but where it should _not_ be. It's only a one-line change, but I wonder how many people have been relying on this functionality, thus making this a breaking change. There is another more pressing breaking change, #735, that needs addressing. I might throw this one in with that one.

**Comment by pokonski** [comment]
Cool, thanks for replying. For now I'm using your trick with nesting arrays in an object and that works fine :)

**Comment by tacomanator** [comment]
I just found this issue after creating #1125.

Since you're concerned about it being a breaking change, why not do this in v6 which has a lot of breaking changes anyway? :hear_no_evil:

Anyway, it doesn't seem to work the way described in this issue anymore. I tried returning an array and all values were kept, but the field was still considered valid (as per #1125).

**Comment by danielrob** [comment]
Closing this v5 issue with a workaround that appears fixed in v6+.
