### ISSUE TITLE
Can I use redux-form isomorphically?

### ISSUE THREAD

**Issue by mikhail-riabokon** [erikras/redux-form#64]
For example. I have simple SingUp form
```javascript
import React, {PropTypes, Component} from 'react';
import {connectReduxForm} from 'redux-form';

@connectReduxForm({
  form: 'singup',
  fields: ['name']
})
class SingUp extends Component {
  static propTypes = {
    fields: PropTypes.object
  };

  render() {
    const {fields: {name}} = this.props;

    return (
      <form action="/singup" method="POST">
        <input {...name} type="text"/>
        <div className="errors">{name.error || null}</div>
        <button type="submit">Submit</button>
      </form>
    );
  }
}
```
This component renders on the server.
As I do no have any js handlers for form submit on the client (requirements), then I submit form from the client, post request will passed to the server, server will validate data and send the result. 

The questions is, how to pass form validation result to redux-form on the server?

**Comment by erikras** [comment]
If you upgrade to `v1.5.3`, you can dispatch [`stopSubmit`](https://github.com/erikras/redux-form#-stopsubmitformstring-errorsobject) to set submission errors.

```js
import { stopSubmit } from 'redux-form';

...

dispatch(stopSubmit('singup', { name: 'That username is taken!' }));
```

If you do that before you render the form, the error should show. Let me know if you have any problems.

Also, you probably mean si***gn***Up, not si*ng*Up.
