### ISSUE TITLE
Suppport for JSON object value of a single field on form

### ISSUE THREAD

**Issue by taylordowns2000** [erikras/redux-form#642]
Hi @erikras , thanks for all you've done with redux-form! It's wonderful. I'm currently trying to use redux-form in conjunction with [react-json](https://github.com/arqex/react-json).

We run an open-source data integration platform for the non-profit sector (health, eduction, etc.). Patient data is submitted to openfn.org from one application, then manipulated and forwarded to another. Sometimes our users need to edit the JSON payload before reprocessing an individual transaction. Currently, the only way to do this is to give them a big ugly text editor:
![image](https://cloud.githubusercontent.com/assets/8732845/13010924/0a45cfb6-d1ad-11e5-975d-76bc51ab5315.png)
While it's powerful, it's scary for less technical users. I'm trying to make a clean redux-form where they have inputs for "label", `timeStamp`, and `body`... but the `body` is actually a JSON object, not a string.

In a perfect world, redux-form could see a JSON object like this:
```json
{
  "version": "61",
  "source": "CommCare",
  "type": "patient",
  "name": "Taylor",
  "received_on": "2016-02-02T15:03:17.082625",
  "problem": null
}
```
and actually render _each_ key:value pair as beautiful form fields with initialValue's already populated. We'd only give users the ability to edit the vales, not the keys! I'm under the impression that this isn't possible—it's real JSON data, not a JSON-schema—, so I thought of using redux-form in conjunction with react-json to make a point and click JSON editor like this: 
![image](https://cloud.githubusercontent.com/assets/8732845/13010874/c74a6942-d1ac-11e5-9c6f-1720ebf6a39c.png)

My trouble now is that when the `value` of one of my redux-form `fields` is a JSON object (i.e., I don't use `JSON.stringify(message_body)`) I get an `Uncaught TypeError: Cannot read property 'componentWillReceiveProps' of null`:
![image](https://cloud.githubusercontent.com/assets/8732845/13011133/f7b37726-d1ad-11e5-85b6-75eb4a284961.png)

I know this is a strange one, and thanks so much for your help! If you're interested in this project, more broadly, I'd encourage you to check out our [Github](https://github.com/OpenFn/) and my recent talk on the important of open-source data integration at [PopTech](https://player.vimeo.com/video/143660667).

Best,
Taylor

**Comment by greaber** [comment]
I'm not sure I understand all the issues, but could you write one recursive function to build your form from the JSON object and another to build the fields array and not use react-json?

**Comment by max-mykhailenko** [comment]
Agree with @greaber

**Comment by taylordowns2000** [comment]
Thank you, both! Will give it a whirl. And post back here when done.
