### ISSUE TITLE
Why is form normalize not a normal config?

### ISSUE THREAD

**Issue by tonyxiao** [erikras/redux-form#644]
Why is it something that has to passed into the form reducer itself? Seems rather complex because it requires modifying overall application initialization to change the normalization behavior of one specific form. 

http://erikras.github.io/redux-form/#/api/reducer/normalize

**Comment by erikras** [comment]
By normalizing in the reducer, it guarantees that the data is normalized no matter where it comes from. Your form might be initialized or even edited from different components or processes dispatching actions.

Does that help/make sense?

**Comment by tonyxiao** [comment]
Wouldn't one make the same argument about validation? How come validation is defined on a per form level but normalization is defined on global reducer level?

**Comment by erikras** [comment]
1. Because validation doesn't need to change the data.
2. You might not want to validate all of your form in every decorated element. e.g. [Wizards](http://erikras.github.io/redux-form/#/examples/wizard)

**Comment by BerkeleyTrue** [comment]
Could we have the option to add the normalize in the config?

While your points are valid, it makes for a weird separation. Now the whole app needs to know about the component that holds that particular form.

I'd rather take the small risk and keep all the things that are dealing with this form in one file.

**Comment by gabrielhpugliese** [comment]
I have a question: what if I have a single form factory that accepts different form names and needs normalize on them? What's the approach?

**Comment by gabrielhpugliese** [comment]
I think I've found the answer: `formKey`

**Comment by erikras** [comment]
@gabrielhpugliese, `formKey` is getting removed in the next version in favor of just using different form names. There might be some config-level normalization as well. Thank you for reminding me of this use case.

**Comment by kromit** [comment]
> There might be some config-level normalization as well.

@erikras is there anything new on this? Because this would allow me to actually use normalization. At the current state there is no way I could explain someone why I have to change the central reducer for normalization of a single field in a small form elsewhere..  Everyone in my team I've talked to about normalization in redux-form is asking me the title question. I do understand your reasons to do the normalization in the reducer, but I do not understand why the config is not in the actual config of the form like the validation.

**Comment by BerkeleyTrue** [comment]
@kromit I'd suggest opening a new issue asking to allow normalize in the config.
