### ISSUE TITLE
[Feature Request] Read Dirty State Outside

### ISSUE THREAD

**Issue by hnordt** [erikras/redux-form#648]
Related to #292.

I need to check if a form is dirty outside because I need to check if there are unsaved changes.

Would be awesome if you can include dirty/pristine as saved prop on form state, or maybe create a helper function `isDirty(formName)` just like `getValues(formName)`.

**Comment by hnordt** [comment]
@erikras any change implementing it soon? :D

**Comment by aight8** [comment]
+1 there are several issues related to this "outside form dirty checking". This is a valuable feature since some important use cases based on this (beforeunload and UI change dependent confirming).
Can an admin please check this feature again.

**Comment by erikras** [comment]
I apologize for not responding earlier. This feature will be present in the next version, and I will accept PRs for the current one, but I think my time will be best spent getting the new one published.

**Comment by mumbaisurfer** [comment]
is this change implemented already?

**Comment by eladkarakuli** [comment]
+1

**Comment by lynn** [comment]
This would be really useful. Is it still planned for 6.0.0, @erikras?

**Comment by erikras** [comment]
@lynn `v6` already has access to dirty/pristine state via the instance API, i.e. you will need to have a reference to the instance of the form component. However, a selector, as suggested in this issue, also seems like it could be useful. I will investigate how much work that would be to get into `v6` before release.

**Comment by kristian-puccio** [comment]
I just made a very rudimentary version myself.
Well sortof, I wanted to looks for errors on a form so I just manually
looked up state.form[formName].asyncErrors

I'm guessing that we can be confident about the shape of the state not
changing?

**Comment by pjnovas** [comment]
sooo ... I have dig in the source and I have found a way:

From any component of the app you can do:
```javascript
import {isDirty} from 'redux-form'

const isFormTestDirty = isDirty('form-test-name')

const mapStateToProps = state => ({
  formDirty: isFormTestDirty(state)
})
```

@erikras please confirm this is a valid access and if so I think it would be awesome to have in docs

**Comment by pjnovas** [comment]
well I've just found that on the docs LOL
http://redux-form.com/6.3.1/docs/api/Selectors.md/

**Comment by bittu1028** [comment]
I need the dirty fields and its values outside the form. Is this feature currently available on this version of redux form ?

**Comment by gustavohenke** [comment]
This can be done by using the [`isDirty`](https://redux-form.com/7.2.0/docs/api/selectors.md/#-code-isdirty-formname-string-code-returns-code-state-gt-dirty-boolean-code-) selector.

Also closing due to months of inactivity.
