### ISSUE TITLE
redux-form not compatible with redux-devtools@3.1.x

### ISSUE THREAD

**Issue by smilingpoplar** [erikras/redux-form#649]
[redux-devtools 3.1.0](https://github.com/gaearon/redux-devtools/releases) add checks for undefined `action.type`, redux-form fails when `handleSubmit` wrapping a function which return promise.

**Comment by erikras** [comment]
I'm trying to replicate this. What am I doing wrong?
```js
<form onSubmit={handleSubmit(values =>
  new Promise(resolve => {
    setTimeout(function() {
      console.info(values);
      resolve();
    }, 1000);
  }))}>
  INPUTS HERE
</form>
```
I'm not seeing any errors.

What does your action look like?

**Comment by smilingpoplar** [comment]
from my code, like this: 
'''
<button type="submit" disabled={submitting} onClick={handleSubmit(login)}>login</button>'''

'''
async function login(data, dispatch) {
  try {
    const res = await axios.post(`${apiBase}/login`, data);
    dispatch({ type: Actions.LOGIN_SUCCESS, ...data });
    return Promise.resolve();
  } catch (res) {
    dispatch({ type: Actions.LOGIN_FAILURE });
    return Promise.reject(res.data.error);
  }
}
'''

**Comment by erikras** [comment]
What is the specific action that it fails on? Because it sure looks to me like all of `redux-form`'s proprietary actions have a `type` specified.

**Comment by smilingpoplar** [comment]
No specific action. 
I tried your simple case. It can't work either. 
I think it probably relate to `babel 6` which I just upgraded my project to.

**Comment by smilingpoplar** [comment]
@erikras It turns out that the problem is related to redux-thunk. The `redux-devtools` complains when I define `handleSubmit` as 
```
<form onSubmit={handleSubmit((values, dispatch) =>  {
  ...
})}>
</form>
```
And it's ok when I define `handleSubmit` as
```
<form onSubmit={handleSubmit(values => {
  return dispatch => {
    ...
  }
})}>
</form>
```
