### ISSUE TITLE
Accessiblity: Labels in examples not linked to elements

### ISSUE THREAD

**Issue by callumacrae** [erikras/redux-form#650]
Hello!

First off: I'm willing to send PRs for any changes you approve of :smiley: 

I'm working my way through the docs (trying to find a suitable validation library for our site at work), and found this example:

``` jsx
        <div>
          <label>First Name</label>
          <input type="text" placeholder="First Name" {...firstName}/>
        </div>
        <div>
          <label>Last Name</label>
          <input type="text" placeholder="Last Name" {...lastName}/>
        </div>
```

When the labels aren't linked to the inputs, screen readers won't be able to tell screen reader users what the inputs are. Users will hear only "Input", instead of (for example) "Input, first name", and if they're browsing by input (not uncommon), they won't have heard the label.

It would be better to do the following:

``` jsx
        <div>
          <label>
            First Name
            <input type="text" placeholder="First Name" {...firstName}/>
          </label>
        </div>
        <div>
          <label>
            Last Name
            <input type="text" placeholder="Last Name" {...lastName}/>
          </label>
        </div>
```

Thoughts? I'll update this issue if I find any other issues :)

**Comment by erikras** [comment]
You are referring to the [Examples](http://erikras.github.io/redux-form/#/examples)?

:+1: Sure, go ahead. I am aware of that aspect of accessibility, but went for simpler markup to make the examples simpler. However, I definitely approve of encouraging accessibility, even through demo examples. As long as they render the same (there's some bootstrap magic going on there behind the scenes), I'd be happy to approve a PR to make them more accessible.

If you're just referring to the snippets on the [Getting Started](http://erikras.github.io/redux-form/#/getting-started) page (which is what you have pasted), then you needn't worry about how they render.

Bite off as much or as little as you wish to chew.

**Comment by callumacrae** [comment]
Simple markup is great, but not if people copy it onto their own websites and then have inaccessible websites! I'll send a PR soon :)

**Comment by gustavohenke** [comment]
In case anyone would like to have a spike on this one, go ahead.
I'll close it anyway since it's been a year and no one said a word about it 😢

**Comment by AutoSponge** [comment]
Just because no one offered to fix the examples doesn't mean they're now magically accessible. Basically, no one should copy [examples](http://erikras.github.io/redux-form/#/examples) without understanding they don't work for AT users and, in some cases, you may be breaking the law.
