### ISSUE TITLE
Need Help: Add Test Coverage

### ISSUE THREAD

**Issue by erikras** [erikras/redux-form#651]
I've just spent more hours than I'd like to admit trying to add test coverage to this repo, and have utterly failed. I've been trying to replicate [what `react-redux` is doing](https://github.com/reactjs/react-redux/blob/master/package.json#L14-L16), but with no luck.

```
~/redux-form/src/__tests__/setup.js:1
import { jsdom } from 'jsdom';
^^^^^^

SyntaxError: Unexpected token import
```

It looks like the much-feared upgrade Babel 6 might be in the cards as well. If you appreciate this library and have some experience with test coverage, I would :heart: :heart: :heart: any PR enabling test coverage. It does not necessarily have to be `isparta`, but `isparta` seems pretty nice and sufficient.

**Comment by kristian-puccio** [comment]
I'll have a look at it later if I can but I've found this:
https://github.com/davezuko/react-redux-starter-kit
and it's working there with babel 6.

**Comment by erikras** [comment]
So is `react-redux`. It _shouldn't_ be hard, but like so many build problems, it's a matter of finding the right way to fit the puzzle pieces together.

**Comment by davidkpiano** [comment]
Try:

mocha --require babel-core/register

For the test script

**Comment by erikras** [comment]
@davidkpiano I'm already doing `--compilers js:babel-register`, but that didn't help either. I'll push a branch of where I've gotten to so far.
