### ISSUE TITLE
removeField does not delete the proper index in version 4.2.0

### ISSUE THREAD

**Issue by timaschew** [erikras/redux-form#653]
First of all, thank you for this great library. It's really awesome and has a beautiful API!

----
`child.removeField(index)` is always deleting the last item, not the index which is passed.

I realized it in my form, then I copied the form from the deep example and its the same effect.
On the github page it seems to work, maybe a different version, not 4.2.0

**Comment by erikras** [comment]
No, the github page is `4.2.0`. Very strange.

**Comment by timaschew** [comment]
Sorry, my fault.
I had a typo where the form field is mapped to the input element. So typing text into the array of input elements is working, but when the array is sliced, always the last item in the DOM is removed.
But when the form field is mapped properly, then the values seems to be "reassigned" in the correct order. But when not, then it looks broken, because the content of the input element is still present but not "reassigned"
Here is a demo: https://youtu.be/B0mhi8SQT6w

**Comment by villanuevawill** [comment]
@erikras I will look into this more, but it looks like this is still an issue.  On the github page, if you add Bobby a few times ( and other children), if you click delete next to Bobby, then it will delete the last child to be added and not the child (Bobby) that was clicked.  I'm seeing this issue locally as well, since I am using this feature in a form I'm building.

**Comment by villanuevawill** [comment]
@erikras ^^ Sorry about that - you can ignore this comment.  I had an issue with how I was setting up my keys with react.

**Comment by anyong** [comment]
@timaschew @villanuevawill could you please show what was wrong and how you fixed it? I have the exact same issue...

```jsx
{someFields.map((someField, idx) => {
    return (
        <div key={idx}>
            <input
                type="text"
                {...someField}
            />
            <button onClick={() => someFields.removeField(idx)}>Remove</button>
        </div>
    );
})}
```
