### ISSUE TITLE
onBlur only triggers asyncValidate every second call in custom component onChange handler

### ISSUE THREAD

**Issue by thomasmery** [erikras/redux-form#654]
Hi,

this is is a follow up to: https://github.com/erikras/redux-form/issues/513

The problem is that in:

``` js
<SelectField 
    {...role} 
    onChange={ (event, index, value) => {
        role.onBlur(event);
    } }
>
    {this._renderRoles()}
</SelectField>
```

`role.onBlur(event);` only triggers asyncValidate on every second call

the `onChange` is called every time and I tracked it down to line 78 of createHigherOrderComponent.js:
`if (syncValidationPasses && (isSubmitting || !allPristine || !initialized)) {`
https://github.com/erikras/redux-form/blob/master/src/createHigherOrderComponent.js#L78

where `allPristine` is true every second call which results in skipping the validation
this is caused by the field being dirty only every second call

I tried delaying the `onBlur` call which worked but would mess up the form attributes (the `props.form` passed to the asyncValidate function would have `_asyncValidating` set to the field name and no `_active` property)

so I'm at loss to what to try now , hope some one can help on this

thanks

**Comment by gustavohenke** [comment]
Closing because this issue has not received any new comments after one year.
