### ISSUE TITLE
dynamic form field 'annotations'

### ISSUE THREAD

**Issue by xavierhaurie** [erikras/redux-form#656]
My page has content that is dynamic and changes with the current state of a form. That content is not validation messages. It is stuff like "you have 123 characters left". It's easy to implement ad-hoc, but it would be nice to be able to compute these 'annotations', as well as validation errors and normalized input values in the same class/file because all three may share some data, such as the maximum number of characters for a text input.

**Comment by erikras** [comment]
Shared data could always be imported from a common file.

So you're asking for something parallel to sync validation, where a function is given the form values and returns annotations?

**Comment by xavierhaurie** [comment]
yes exactly :-)

**Comment by xavierhaurie** [comment]
To make things more interesting, it would be great to be able to compute the the annotation based on the pre-normalized field value as well as the normalized value. The use case I have in mind is a text field normalized to 1,000 characters length, and a user copy-and-pasting 1001 characters in it. It would be great to display an annotation such as "you have 0 characters remaining (last 1 character of your input was truncated)"

**Comment by ooflorent** [comment]
This is a usage question, and we encourage you to ask it on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

This is the only way to ensure the same question doesn’t get asked many times in a row, and that folks who have the same question in the future will be able to find it.

I’m closing for these reasons.
