### ISSUE TITLE
Way to edit entity with reference

### ISSUE THREAD

**Issue by krzysztofpniak** [erikras/redux-form#657]
I'm using data from Parse.com REST api. The entry looks like this:
```
{
    "configuration":{
        "__type":"Pointer",
        "className":"Configuration",
        "objectId":"WFWIzf5Y1m"
    },
    "createdAt":"2016-02-17T08:45:15.064Z",
    "name":"KP",
    "objectId":"DQUDbCx5DK",
    "updatedAt":"2016-02-17T08:45:46.699Z"
}
```

How should I write a form to bind a configuration to select control?
I think this question is related a little bit to this one:
https://github.com/erikras/redux-form/issues/642

From my perspective it should stop expanding value at a place defined in the `fields` array on `@reduxForm`.

**Comment by erikras** [comment]
> From my perspective it should stop expanding value at a place defined in the fields array on `@reduxForm`.

If I understand your meaning of "expanding", it does. See [Complex Values](http://erikras.github.io/redux-form/#/examples/complex) example.

**Comment by krzysztofpniak** [comment]
I saw it. I browsed all of the examples before I posted this issue.
I mean I would like to have
```
configuration.value === {
        "__type":"Pointer",
        "className":"Configuration",
        "objectId":"WFWIzf5Y1m"
    }
```
on my form components.

**Comment by erikras** [comment]
I'm not entirely following what you're trying to do, but it sounds like maybe you should write a custom input component to handle your Pointer value. [All it has to handle to work with `redux-form` is `value` and `onChange`](http://erikras.github.io/redux-form/#/faq/custom-component).

**Comment by krzysztofpniak** [comment]
Exactly, I would like to write my own component, but your library seems to not be prepared for it. There is no `value` field on `configuration`, where I write `{...configuration}`. Instead of, your library is adding `value` and `initial` to:
`type`, `className` and `objectId`. That situation I called 'expanding'.

**Comment by krzysztofpniak** [comment]
Ok, sorry for wasting your time, I didn't have the latest version.

**Comment by erikras** [comment]
Okay. Given your record shape you stated above, and that you only want to edit the `name` and `configuration` (I'm assuming that's like a foreign key pointing at a `Configuration` object), you'd do something like this:

```js
class CustomConfigSelector extends Component {
  static propTypes = {
    value: PropTypes.object,
    onChange: PropTypes.func.isRequired
  };

  render() {
    const {value, onChange} = this.props;
    return <div>some selector that uses value and onChange</div>;
  }
}

class ConfigForm extends Component {
  render() {
    const {{fields: {name, configuration}, handleSubmit} = this.props;
    return (
      <form onSubmit={handleSubmit}>
        <input type="text" {...name}/>
        <CustomConfigSelector {...configuration}/>
      </form>
    );
  }
}

export default reduxForm({
  form: 'config',
  fields: ['name', 'configuration', 'objectId'] // objectId is included so that it is in the submitted values
})(ConfigForm);
```
