### ISSUE TITLE
Photo preview example?

### ISSUE THREAD

**Issue by Fedcomp** [erikras/redux-form#658]
Has anyone tried to make photo preview example? You upload picture and it shows the picture using html async readAsDataUrl. The issue is: should i store it in redux? Since redux-form makes form-changed event on every symbol, i think form will perform slow with many base64/blob pictures, because all reducers will copy the whole state for every event.

**Comment by erikras** [comment]
I have done file uploading with `react-dropzone`, but have kept it separate from `redux-form`. The upload action can still go through `redux`, though, and a successful upload can return a url to display the image from the server, which can be stored in `redux`.

Uploading an image by submitting `base64/blob` as json doesn't seem like a very good idea.

I don't have any examples, sorry.

**Comment by VladShcherbin** [comment]
I've also done a custom dropzone element, in onDrop event I took the file, checked it, showed the preview using `readAsDataURL`, uploaded to amazon s3 and updated the form field with the returned path from amazon s3.

**Comment by Fedcomp** [comment]
We use our own storage engine (it makes sense in our project) and we solved it by local state and passing only file handler to redux storage. We found external npm react component for that (react dropzone or similar).

**Comment by ooflorent** [comment]
Great! This is how I usually do.

**Comment by mikethejet** [comment]
where is the binary content of fole i can save for example to rethinkDB using r.binary ? (if i am using react-dropzone in redux) there is not any field that holds the data of file.. ?

**Comment by geekodour** [comment]
@mikethejet did you get any solution to your issue? I am facing similar issues. the preview propertycontains the blob url

**Comment by yokodev** [comment]
@erikras @Fedcomp @VladShcherbin  
 So my use case is **preview/upload/crop** image for the user profile... 
1. redux-form manages the state for all the <Field /> 's that you added within a single  **form** tag
2. There is a **Image previewer component** comprised of a file upload button,openFile, etc. which lives inside this same **form** tag
3. This last component should be handled outside redux-form meaning a regular 
```html <input type="file" {...avatar} value={null}>``` and managed like how? 
I'm confused... 
Is there any example that I can refer to? I was trying to migrate this to v6 :http://redux-form.com/5.3.1/#/examples/file?_k=gffvms but no luck yet
but then I found this https://stackoverflow.com/questions/40990825/error-with-redux-form-using-fileinput and so don't know where to start now
please help...

**Comment by Moejoe90** [comment]
This is a really good example for what your talking about 
https://github.com/BBB/dropzone-redux-form-example
