### ISSUE TITLE
Is there a way to configure the Normalizing API in the reduxForm method

### ISSUE THREAD

**Issue by mauriciosoares** [erikras/redux-form#659]
Hello, is there any way I can configure the `normalizing` API in the same way the `validate` API works?

I mean, today I'm configuring at the `combineReducers` level (I'm getting some trouble with dynamically generated fields)...

My idea is to use like this:

```js
const fields = ['name'];
const normalize = {
  name: e => e.toUpperCase();
}

// component

export default reduxForm({
  form: 'sign-up',
  fields,
  normalize
});
```

Configure it when the `reduxForm` is called.

**Comment by erikras** [comment]
If you want to normalize in the form, you will need to wrap `onChange` or `onBlur` to modify your value.

As for why it's in the reducer, see #644.

**Comment by mauriciosoares** [comment]
thanks @erikras, I'll take a look in this issue. It's indeed in the reducer.
