### ISSUE TITLE
Updating initialValues at runtime

### ISSUE THREAD

**Issue by jeremytrawls** [erikras/redux-form#660]
First off AWESOME project you have here! 

I'm trying to find a way to set the initialValues of a dynamically rendered formComponent.

Below you can get a gist of what my form looks like.  

Userinfo is ALWAYS rendered, however the useraddressinfo and usermembershipinfo portions are only rendered based on the users interaction with the userInfo form.

I'm l looking for a way to set the default values of the state property in both of sub forms, however doing so in the creation of the reduxForm object doesn't work. 

```js
export default reduxForm(
    { 
        form:'ConnectionCard',
        validate
    },
    state => ({
        initialValues:{
            userinfo:{
                visitorType: 'First time visitor'
            },
            useraddressinfo:{
                state: 'Illinois'
            },
            usermembershipinfo:{
                membershipinfoform:{
                    churchstate: 'Illinois'
                }
            }
        }
    })
)(ConnectionCardForm);
```

I've also tried directly setting the fields initial value, which worked, but isn't recognized by the submit method.

Any insight would be greatly appreciated.

**Comment by erikras** [comment]
Well, the primary problem I see is that you are not providing a `fields` array to the `reduxForm()` decorator. It will only submit the values you provide to `fields`.

**Comment by jeremytrawls** [comment]
Ah, yeah I guess I should've explained that bit..lol

I'm actually doing that on the container on the form and passing it as a prop that I get from a reducer, which looks like this:

`  
class App extends Component {

    //set the dynamic fields to pass to the connectionCard
    constructor(props){
        super(props);
    }

    render(){       
        return (
            <ConnectionCard fields={this.props.connectionCardSectionDisplay.formfields}/>
        );

    };
}


`

**Comment by jeremytrawls** [comment]
@erikras  I think what i'm missing based on the deep form example is using the  [] for my dynamically populated fields. From there it looks like i can use the addChildren method and provide the initialValues per the provided API.  

Does this sound like the right approach?

**Comment by erikras** [comment]
Yes, if you don't know your initial values at mount time.

**Comment by jeremytrawls** [comment]
awesome.  Thanks a lot.

**Comment by realneeraj** [comment]
Hi @erikras 
I'm pretty new to React & Redux-Form and at the moment I am in need of some help.

Basically I have listing page with lists and their edit button. When the edit is clicked, I am showing a modal pop up with the fields and doing a API call to fetch the respective list data. 

Could you please let me know how can I pre-populate the fields in the modal pop up with the data received from API call?

A demonstration with a code sample will be much appreciated(like I said my pretty new to React & Redux & Redux-form). 

Thanks in advance!
