### ISSUE TITLE
select elements are not updated after re mounting the form with destroyOnUnmount: false

### ISSUE THREAD

**Issue by timaschew** [erikras/redux-form#661]
I'm using `destroyOnUnmount: false`

and it works fine for normal `<input>` elements if I switch the tab and the form is unmounted and mounted again. But for `<select>` elements it's not working. After re mounting they show the default value (first option). But when focus the form by clicking into any input element, it will trigger a refresh and the select shows the correct value.

Here is a demo (of course the opened select options are not shown, that's a bug of the screencast tool)
https://www.youtube.com/watch?v=ZtBrKtDhvhs&feature=youtu.be

**Comment by erikras** [comment]
:+1: Excellent demo.

What is the state in the redux store? Is the value set? When does it become unset?

**Comment by timaschew** [comment]
> What is the state in the redux store

Here is the state of `form` in my store:

Before unmounting / destroy:

```json
"{
  "registration-new": {
    "_asyncValidating": false,
    "_initialized": false,
    "_submitting": false,
    "_submitFailed": false,
    "bookingId": {
      "visited": true,
      "value": "123",
      "touched": true
    },
    "registrtionType": {
      "visited": true,
      "value": "Gruppenmeldeschein",
      "touched": true
    }
  }
}"
```

after unmonting / destroy (when swtich the tab):

```json
"{
  "registration-new": {
    "_asyncValidating": false,
    "_initialized": false,
    "_submitting": false,
    "_submitFailed": false,
    "bookingId": {
      "visited": true,
      "value": "123",
      "touched": true
    },
    "registrtionType": {
      "visited": true,
      "value": "Gruppenmeldeschein",
      "touched": true
    }
  }
}"
```

after go back and mounting again:

```json
"{
  "registration-new": {
    "_asyncValidating": false,
    "_initialized": false,
    "_submitting": false,
    "_submitFailed": false,
    "bookingId": {
      "visited": true,
      "value": "123",
      "touched": true
    },
    "registrtionType": {
      "visited": true,
      "value": "Gruppenmeldeschein",
      "touched": true
    }
  }
}"
```

After focus the input element:

```json
"{
  "registration-new": {
    "_asyncValidating": false,
    "_initialized": false,
    "_submitting": false,
    "_submitFailed": false,
    "bookingId": {
      "visited": true,
      "value": "123",
      "touched": true
    },
    "registrtionType": {
      "visited": true,
      "value": "Gruppenmeldeschein",
      "touched": true
    }
  }
}"
```

It's always the same!

> Is the value set?

Yes

> When does it become unset

Never, that's the point :)

Another video: https://youtu.be/tKw60JziW9Q

**Comment by timaschew** [comment]
Even if I use time travel feature of the redux devtools and undo the last action `SET_REGISTRAITON_TAB`
Then there is a new action fired: `redux-form/DESTROY` and if I disable this new one the value of the select is still wrong.

BTW: this is my code (only the important stuff)

```js

render() {
   const {fields: {
       bookingId,
       registrtionType,
     }, handleSubmit} = this.props
    return (
          <div className="medium-3 small-6 columns">
            <label>
              <span>Buchungs-Nr.</span>
              <input type="text" {...bookingId} />
            </label>
          </div>

          <div className="medium-6 columns">
            <label>
              <span>Meldescheintyp</span>
              <select {...registrtionType} defaultValue={registrtionType.value} >
               <option>Meldeschein</option>
               <option>Gruppenmeldeschein</option>
               <option>Jahreskurkarte</option>
             </select>
            </label>
          </div>
       )
   }

RegistrationForm = reduxForm({
  form: 'registration-new',
  fields: [
    'bookingId',
    'registrtionType',
  ],
  destroyOnUnmount: false
})(RegistrationForm)

export default RegistrationForm

```

I also tried to use this into the select element: `defaultValue={registrtionType.value}` but didn't change anything.

**Comment by erikras** [comment]
Your code looks just fine. Maybe React would prefer that you specify a `value` prop on each of your options?

```js
<select {...registrtionType}>
  <option value="Meldeschein">Meldeschein</option>
  <option value="Gruppenmeldeschein">Gruppenmeldeschein</option>
  <option value="Jahreskurkarte">Jahreskurkarte</option>
</select>
```

That's about the only difference between your code and the examples, which _will_ maintain a `<select>` value if `destroyOnUnmount` is turned off.

**Comment by timaschew** [comment]
Oh nooo, that's it! I should have realised it by myself!
Thank you :)
