### ISSUE TITLE
Array loads initial data when removing and re-adding elements

### ISSUE THREAD

**Issue by clarkie** [erikras/redux-form#662]
I'm using the mapStateToProps to with the initialValues to populate my form with data form the server. The initial state looks like this:
```
{ 
  "id": 70,
  "about": [
    { 
      "id": 67,
      "title": "afdasdf",
      "content": "adf",
    },
    { 
      "id": 68,
      "title": "124124",
      "content": "123123",
    },
    { 
      "id": 69,
      "title": "677",
      "content": "7",
    }
  ]
}

```

As you can see from the following gif calling `REMOVE_ARRAY_VALUE` followed by `ADD_ARRAY_VALUE` repopulates the form with the initial values. 

![gmqtcdwtmk](https://cloud.githubusercontent.com/assets/2292639/13147214/79568a60-d650-11e5-8ea2-da08d32abc6e.gif)

Looking at the form state immediately after calling `ADD_ARRAY_VALUE` shows that the `about` array has 1 element with out any actual values but the component is showing the values from the initial state:

![image](https://cloud.githubusercontent.com/assets/2292639/13147629/9a5f8210-d651-11e5-934d-7f59c6d7c164.png)

**Comment by clarkie** [comment]
I'm guessing this is linked to #628 ?

**Comment by erikras** [comment]
And #629. It's a known bug.

Excellent reporting. :+1:

**Comment by clarkie** [comment]
@erikras can I help to fix? I might need some pointers
