### ISSUE TITLE
[V5] no documentation for addField/removeField/swapField in API 

### ISSUE THREAD

**Issue by jeremytrawls** [erikras/redux-form#663]
just wanted to note that there's no clear documentation (that I can find) outside of the deepForms examples that explains addField/removeField/swapField

**Comment by erikras** [comment]
Yeah. It's mentioned on the Deep Form example, but not in the API section of the docs. I couldn't figure out where to put it. Maybe it needs its own page.

**Comment by xavierhaurie** [comment]
I was going to ask the same question.

Let's see if I got it right:

* addArrayValue is a standalone function used to add a new array element to an existing form. The array to which the element is added need not exist (?) so I would assume in the following case:

   addArrayValue('myForm', 'myElement[1].subElement');

then myElement[1] must already exist, but subElement need not exist.

* addField, removeField and swapField are functions that are added to all the arrays in the form's state. 

If there is no array to begin with, you need to call addArrayValue, then you can if you want call addField() on the newly created array. Or you can generate the entire array using addArrayValue.

I imagine that these methods dispatch actions which the redux-form reducer acts on.

let me know if any of this is right .. or wrong..

**Comment by erikras** [comment]
I can see where this would be confusing.

> addField, removeField and swapField are functions that are added to all the arrays in the form's state.

Those are the only ones you really need to use. `addArrayValue()` is just the action creator that they use. So you _could_ dispatch that action from outside your component (where you don't have access to `this.props.fields`), but you _probably_ don't need to.

The process goes like this:

1. Have one of the fields in your `fields` config be an array (e.g. `nicknames[]` or `addresses[].street` for an array of subfields)
2. Place a button to add an entry to the array that calls `this.props.fields.nickname.addField()`
3. This makes `this.props.fields.nickname.length === 1` so you can render `<input {...this.props.fields.nickname[0]}/>`

Does that clarify anything?

**Comment by xavierhaurie** [comment]
Yes it's clear now. Thanks!

And thank you for the feature itself. I was somewhat horrified today when I realized I hadn't planned for our forms to be "extensible". I thought I was going to need a major hack. Then I found out you had already solved the problem :-)

**Comment by thurt** [comment]
+1 for adding documentation for this. I couldn't not find anything in google search except for this post.

**Comment by danielrob** [comment]
Closing with bulk close of v5 issues. If this issue still requires action and/or also affects v6/7, please request a reopen with details or raise a new issue. v5 PR's are still welcomed.
