### ISSUE TITLE
Can't get Synchronous Validation working

### ISSUE THREAD

**Issue by timaschew** [erikras/redux-form#665]
I copied the SynchronousValidationForm into my app and it doesn't work, I get this error
__Uncaught Error: You must either pass handleSubmit() an onSubmit function or pass onSubmit as a prop__

Then I changed the `onSubmit` to this here:

```js
console.log('>>>>>>>>1 ', handleSubmit)
    return (<form className="form-horizontal" onSubmit={(...e) => {
      console.log('>>>>>>2 ', handleSubmit)
      alert('wtf')
      handleSubmit.apply(this, e)
      e[0].preventDefault()
    }}>
```

But it still doesn't work, here is the output from the console.

```
>>>>>>>>1  handleSubmit(submitOrEvent) {
        var _this3 = this;

        var _props3 = this.props;
        var onSubmit = _props3.onSubmit;
        var fields = _props3.fields;
        var form = _p…

>>>>>>2  handleSubmit(submitOrEvent) {
        var _this3 = this;

        var _props3 = this.props;
        var onSubmit = _props3.onSubmit;
        var fields = _props3.fields;
        var form = _p…

Uncaught Error: You must either pass handleSubmit() an onSubmit function or pass onSubmit as a prop
```

I don't get it, `onSubmit` is always undefined when I'm in debug mode in this ilne https://github.com/erikras/redux-form/blob/7c7990ece4a7e59f0dee6c8938105e9899d93971/src/createHigherOrderComponent.js#L86

I really just copy paste the whole __SynchronousValidationForm.js__ file.

Here is my setup: https://gist.github.com/timaschew/08dbb6bc68e454b6ff01

**Comment by timaschew** [comment]
The async example is working by the way: http://erikras.github.io/redux-form/#/examples/submit-validation?_k=xw9ii1

**Comment by pindamonhangaba** [comment]
I didn't find this anywhere in the docs, but the `handleSubmit` from props is actually expecting your own submit handler, as in:

    onSubmit={this.props.handleSubmit(this.handleSubmit)}

With `this.handleSubmit` being your components handler.

**Comment by marr** [comment]
@pindamonhangaba @erikras that should definitely be mentioned in the docs. this library is difficult to use at first because of the undocumented and wrong-in-the-examples handleSubmit usage.

**Comment by pindamonhangaba** [comment]
It is [here](http://redux-form.com/4.2.0/#/api/props), but I only found it after I commented here, it should be more explicit, usually `handleSubmit` refers to a handler, not a handler-creator.

**Comment by ooflorent** [comment]
I'm closing the issue since @pindamonhangaba and @marr posted the solution.
