### ISSUE TITLE
Normalize deep form fields

### ISSUE THREAD

**Issue by xavierhaurie** [erikras/redux-form#668]
Sorry if this is a duplicate, but I couldn't find a ticket that asks the following question:

How do you normalize members of an array of fields?

i.e. one of my form fields is arms[].name

how do I set up the normalize object, something like the following:

{
   arms: value => ( map(......) ),
// or:
   'arms[]': value => .... ,
// or:
   'arms[].name' => ... ,
// or:
   'arms.name' => ...

etc

Or is it just not possible with the current code?

Thanks in advance!

**Comment by ooflorent** [comment]
Unfortunately there is no documentation on this. However, `reducer.normalize` is tested. 
You should take a look at the tests to better understand how `normalize` works on deep forms: [`src/__tests__/reducer.spec.js#L3079-L3565`](https://github.com/erikras/redux-form/blob/e65e8c51856f7f744e05b9dea6901a49dc199bea/src/__tests__/reducer.spec.js#L3079-L3565)
