### ISSUE TITLE
Validation for complex form fields

### ISSUE THREAD

**Issue by toddbranch** [erikras/redux-form#669]
Not sure if this is a bug, or I'm just using things incorrectly.

I have a credit card form with an expiry date.  My preferred way of building it is to have an `expiry[]` field which consists of `[expiryMonth, expiryYear]` by convention.  I'd then like to set an `expiry` error - since the error itself a combination of both fields.  Let's say the error is "Invalid expiry.".  The result is that `expiryMonth` gets an error of "I" and `expiryYear` an error of "n" because the code is treating the string as an array of errors.

There are definitely workarounds, but just sharing.  I guess this is actually a feature request - to set the error on `expiry[]` itself.

**Comment by erikras** [comment]
Neither a bug nor incorrect usage. :smile: A single error message for an array of fields is not supported.

You'll have to pick a field to make the error for.
```js
{
  expiry: [
    'Error about the month',
    'Error about the year'
  ]
}
```

Most feature requests about this are more along the lines of `'Please specify at least two phone numbers'`. So, what I'm saying is that, yes, it's a known lack-of-feature.

**Comment by toddbranch** [comment]
:+1:
