### ISSUE TITLE
Bugs Using Custom Theme with Material UI

### ISSUE THREAD

**Issue by gkkirsch** [erikras/redux-form#670]
I love reduxForm and have been implementing it on all my projects. I recently am doing a project with Material UI. ReduxForm was working great until I implement custom theming and followed the instructions here on the Material UI docs. [http://www.material-ui.com/#/customization/themes](url). After I integrated the mui childContext theming my Material UI TextField would dispatch the FOCUS and BLUR actions when clicked. I tried just passing the TextField the value, initialValue and onChange function that you get from ReduxForm which fixed the multiple actions being dispatch but every time the onChange event is fired the blur event is triggered also. Has anyone else tried custom themes with material ui and been successful. 

Can using chidContext affect ReduxForm?

**Comment by genyded** [comment]
It's not really clear what your use case is... can you please post some code that manifests the issue? I am using Material UI with a custom theme (passed via context) and do not have any issues related to that using Redux Form.

**Comment by erikras** [comment]
> Can using chidContext affect ReduxForm?

No.

**Comment by ooflorent** [comment]
This is a usage question, and we encourage you to ask it on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.
