### ISSUE TITLE
It is possible to turn off / turn on the submit button located at parent according to the validity of the child form?

### ISSUE THREAD

**Issue by NaorShlomi** [erikras/redux-form#672]
Hi,

There is way turn off / turn on the submit button located at parent according to the validity of the child form?

**Comment by ptim** [comment]
Not sure if this is helpful, but the function you pass to handleSubmit will not get called unless the form passes synchronous validation..

I think the following anecdote is a crude abbreviation of the flow: 

Given 

- i have a redux-form with a input, and 
- i provide redux-form with a synchronous validator for 'required'
- the field is blank when i arrive on the page

Then:

- redux has wrapped my component, so `this.props.handleSubmit` is provided by redux-form, and each field name I provide to the redux HOC / decorator becomes a redux-form field, with properties described at http://erikras.github.io/redux-form/#/api/props
- the field has the properties: `{ value: "" (or undefined?), touched: false, valid: false }` You can see this at work at https://react-redux.herokuapp.com/survey

When:

- I click in the field, redux-form sets the field to `visited: true`, (and possibly `touched: true` if you've set `touchOnChange: true` in the HOC wrapper)
- when I enter the string 'my input', a change action is dispatched for every keystroke, and the validator is fired every time
- if I delete the field contents, then the validator is still being called on each keystroke, and the validator sets this `field.error` to the message that the validator returns, and the form is marked `valid: false`
- when I hit submit, handleSubmit is called, and all fields are touched (so validation messages [which have already been set] will show [assuming you follow the examples]) but `form.valid` is still false, and **the function I pass _as_ `onSubmit` (which gets wrapped by `handleSubmit`) will not be called**.

I attempted to explain something related here: http://stackoverflow.com/a/34397966/2586761.  

This all forms part of me trying to debug a bug in my wizard code, for which I haven't managed to formulate a sensible question yet.. please correct the many inaccuracies in here :)

**Comment by erikras** [comment]
If, by "turn off / turn on", you mean "toggle the `disabled` prop", then no, there is currently no way for the parent of a decorated redux-form component to know if the form is valid without itself being decorated by `reduxForm()` to the same form name.

Also, :+1: :+1: to @ptim for that amazing explanation.

**Comment by kristian-puccio** [comment]
One way to do this is to dispatch an action from willReceiveProps inside
the component that is wrapped in reduxForm that just says if the form is
valid or not.

Remember to do it in the constructor as well.

Or you could use an event emiter.

**Comment by ooflorent** [comment]
This is a usage question, and we encourage you to ask it on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

This is the only way to ensure the same question doesn’t get asked many times in a row, and that folks who have the same question in the future will be able to find it.

I’m closing for these reasons.
