### ISSUE TITLE
resetForm and ImmutableJS, _isFieldValue

### ISSUE THREAD

**Issue by hpurmann** [erikras/redux-form#675]
We are using ImmutableJS in our state using `.fromJS()` and `.toJS()` to convert from/to plain JS objects for redux-form [as described in the FAQ](https://erikras.github.io/redux-form/#/faq/immutable-js?_k=ie83cx). Resetting forms with `props.resetForm` is not working though. We analyzed the problem and determined that this is caused by the use of the non-enumerable property `_isFieldValue` in the `RESET` reducer. When transforming to immutables and back to plain objects this property is lost and thus the reset is not working as expected.

This should either be mentioned in the documentation with the notice that using ImmutableJS for state is not supported or the `_isFieldValue` mechanism should be changed.

We would obviously prefer the second option, because it keeps the state fully serializable, but we do not have the capacity to implement that at the moment.

**Comment by stevengoldberg** [comment]
:+1:

Ran into a similar issue with `_isFieldValue` myself -- it wasn't getting copied, leading to a `TypeError` on the next update. I resorted to manually copying it onto the new object.

**Comment by timaschew** [comment]
@hpurmann nice catch!

**Comment by hpurmann** [comment]
This problem forces us to store the state for redux-form without Immutables which is an exception to our decision to use Immutables throughout. Is there a reason that the code is currently written that way? Would be nice to get some additional information why it was implemented like this in the first place.

**Comment by hpurmann** [comment]
Oh, I just read the [v5 API proposal](https://github.com/erikras/redux-form/issues/726)

> So, in conclusion, I'm officially forbidding the use of ImmutableJS with redux-form. Deal with it.

So I guess we should keep it like that and use a plain JS objects subtree for `redux-form`, right?

**Comment by hpurmann** [comment]
Haha omg stopped reading at that point. Was just too surprised. FAIL!^^

**Comment by erikras** [comment]
@hpurmann LOL!

**Comment by jdstep** [comment]
Looking forward to official ImmutableJS support. I like both ImmutableJS and redux-form.

I have a temporary solution until official support, in case anyone is looking for a solution to reset the form with a reset button, or some other implementation:

In a callback on the redux form component, call ``this.props.destroyForm()`` and ``this.props.resetForm()``

In the es6 redux form component declaration:
````javascript
constructor(props) {
  super(props);
  this._handleReset = this.handleReset.bind(this);
}

handleReset() {
  this.props.destroyForm();
  this.props.resetForm();
}
````
In the render function:
````jsx
<button type="button" disabled={this.props.submitting} onClick={this._handleReset}>
  Reset
</button>
````

There may be some lingering values that are not reset, however it seems to work for my purposes.

**Comment by ooflorent** [comment]
@jdstep You should really consider using `v6` since it is heavily tested on Immutable.js.
