### ISSUE TITLE
Validate Errors no being passed to Redux-form Field objects

### ISSUE THREAD

**Issue by jeremytrawls** [erikras/redux-form#676]
I have a form that is dynamically generated based on the users input and with that comes runtime validations object updates. 

ALL fields are defined on instantiation of the redux-form. What i'm currently seeing is that after a user adds a second dynamic form based on their inputs and tries to submit the validation function that I pass to 'onSubmit' runs and returns the proper error object, however the field(s) object doesn't no get the error passed to it. 

I have attached a screenshot of what I mean.  in my validate method I'm doing a console.log of all the found errors and then I'm logging out the field of the component right before th render method. 

<img width="552" alt="screen shot 2016-02-22 at 12 10 04 pm" src="https://cloud.githubusercontent.com/assets/6294153/13227756/d994e60a-d95d-11e5-9445-20aeee6532fa.png">

For whatever reason the component is not getting the update command from Redux-form.

If I blur ANY field on the form (new or old components) I then get the errors defined as expected and can show the proper error validation.

Any help would be greatly appreciated.

**Comment by jeremytrawls** [comment]
UPDATE:

I added redux-logger to the project and I am seeing that the action "redux-form/SUBMIT_FAILED" is NOT being triggered again unless a field has been focused.  

 Redux-form is expecting the user to focus on field before it will submit the failed event again and that's definitely problematic in the scenario that I have

**Comment by HelloYie** [comment]
+1

**Comment by vorlov** [comment]
same problem

**Comment by erikras** [comment]
I think this got fixed when the sync errors were moved into the Redux store in `v6.0.0-rc.3`.
