### ISSUE TITLE
question: any way to search documentation?

### ISSUE THREAD

**Issue by tony-kerz** [erikras/redux-form#677]
often package authors maintain documentation along with code in a single repo.

this has the benefit of being able to use github to search against the documentation,
and also for people to submit pull-requests against the documentation.

not the case, here. is there any way to search your documentation, 
or might you consider maintaining it in this repo?

best,
tony.

**Comment by gustavohenke** [comment]
In fact, the docs are all here: https://github.com/erikras/redux-form/tree/v6.4.1/docs

**Comment by gustavohenke** [comment]
Closing due to low demand.
