### ISSUE TITLE
array property doesn't contain initial & value on the property name, but only on each array item 

### ISSUE THREAD

**Issue by randavidovitz** [erikras/redux-form#678]
I have initialized my form based on initial data

`user: {
    subscribed: [ { kk:'aa' }, {kk:'bb'} ]
}`   

I am going to update this property using customized components, so my fields setting was:
`fields: {
   user.subscribed
}`

when looking in redux-dev i see the info as:

`state: {
   ...
   form: {
      myform: {
          user: {
              subscribed: [{ kk:'aa' }, {kk:'bb'}]
          }
      }
   }
   ...
}`

i expect to see initial & value under subscribed...

My problem is that when i call the onchange on the subscribed field , it ads a value property ...
What am i missing ?

**Comment by randavidovitz** [comment]
@erikras , i would love to get your feedback on this? (also i would love to contribute and fix it, but not sure i have all the info yet)

**Comment by randavidovitz** [comment]
The reason for this not to work is since we are using redux-form 3.1.7 in the ultimate redux template

**Comment by erikras** [comment]
Thanks for reporting back your discovery. :+1:
