### ISSUE TITLE
Allow for global promise rejection logging

### ISSUE THREAD

**Issue by kpdecker** [erikras/redux-form#682]
The `returnRejectedSubmitPromise` default setting requires that error logging be done above the redux-forms level as it automatically marks all rejected promises as resolved by not propagating the error. We are able to work around this by applying this flag, but this requires that all forms have this applied otherwise rejections won't propagate up to constructs like `window.onunhandledrejection` and `process.on('unhandledRejection')`.

Since this causes error to be silently dropped, this makes debugging and production monitoring extremely difficult. Not only are the errors missed in production, they aren't shown on local development machine when using inspector. We can work around this by setting the flag, but this must be done on each instance, which I fear will be missed as there are many places which we use forms throughout our app and it's quite simple to miss a flag that is duplicated in so many places.

So my questions are:
1. What is the purpose of this flag? What behavior is this attempting to block?
2. Is it possible to either allow the default to be set system-wide so the system-level promise error handlers can run or provide a app-level hook so we can log these rejections at runtime?

**Comment by skleeschulte** [comment]
+1
I just wanted to open an issue about the exact same thing. It's really problematic that by default all errors in the `onSubmit` handler are silently dropped, for the very reasons you point out.

About your 1st question: I assume it has to do with redux-form's function to add error messages to the form and the form's elements when the submit fails. From [the `onSubmit` docs](http://erikras.github.io/redux-form/#/api/reduxForm):

> If your onSubmit function returns a promise, the submitting property will be set to true until the promise has been resolved or rejected. If it is rejected with an object matching { field1: 'error', field2: 'error' } then the submission errors will be added to each field (to the error prop) just like async validation errors are. If there is an error that is not specific to any field, but applicable to the entire form, you may pass that as if it were the error for a field called _error, and it will be given as the error prop.

So to add submission errors to the form (which can be really handy for form validation responses) we have to return a rejected promise like this:

    function onSubmit() {
        return Promise.reject({ _error: "You just can't satisfy me!" });
    }

This is handled in [handleSubmit.js](https://github.com/erikras/redux-form/blob/0e674b9893b4efba6cae8f7e86d01a77b3bca3cc/src/handleSubmit.js#L10-L22):

    const result = submit(values, dispatch);
    if (isPromise(result)) {
        startSubmit();
        return result.then(submitResult => {
            stopSubmit();
            return submitResult;
        }, submitError => {
            stopSubmit(submitError);
            if (returnRejectedSubmitPromise) {
                return Promise.reject(submitError);
            }
        });
    }

When the Promise is rejected, `stopSubmit` is called with the error value, which in turn fires the `STOP_SUBMIT` action with the error value. So the error value goes into [the reducer](https://github.com/erikras/redux-form/blob/797ac751d7547c8ced16f295c3d529a189e90be7/src/reducer.js#L123-L130) and finally ends up in [`setError`](https://github.com/erikras/redux-form/blob/8a8b808710e20e0cff75deb1cb34959256543a0e/src/setErrors.js#L8). This is fine if the Promise was intentionally rejected to set submission errors. However, all other errors also go to `setError` - and never leave.

Setting `returnRejectedSubmitPromise` to true for all forms has the drawback that all errors bubble up, even the ones from promises which were "only" rejected to set submission errors (although this might still be better than silently dropping the others).

One solution would be to check if `submitError` is an instance of `Error`, and if so then always `return Promise.reject(submitError);`:

    submitError => {
        if (submitError instanceof Error) {
            stopSubmit();
            return Promise.reject(submitError);
        }
        stopSubmit(submitError);
        if (returnRejectedSubmitPromise) {
            return Promise.reject(submitError);
        }
    }

This way at least "real" errors would bubble up; other errors would still be swallowed. The advantage of this solution is that IMHO this could be considered to be a non-breaking change. If I find the time I will make a PR for this.

Another solution would be to implement a special type of error which has to be used to pass submission errors. This could look something like this:

    // onSubmit handler:
    import { SubmissionError } from 'redux-form';
    function onSubmit() {
        return Promise.reject(new SubmissionError({ _error: "You just can't satisfy me!" }));
    }

    // in handleSubmit.js:
    submitError => {
        if (!(submitError instanceof SubmissionError)) {
            stopSubmit();
            return Promise.reject(submitError);
        }
        stopSubmit(submitError);
        if (returnRejectedSubmitPromise) {
            return Promise.reject(submitError);
        }
    }

However this is a breaking change, and there might be more "elegant" solutions if the API has to be changed anyway.

For the mean time and to answer your 2nd question, one quite easy solution to log all the errors from `onSubmit` is by using a redux middleware like this one:

    const reduxFormSubmissionErrorLogger = store => next => action => {
        if (action.type === 'redux-form/STOP_SUBMIT' && action.errors) {
            console.log(action.errors);
        }
        return next(action);
    };

**Comment by ooflorent** [comment]
Thanks @skleeschulte for the detailed anwser!

Changing the behavior of rejecting promise would result in a major breaking change. I think this is covered by the v6 API: [`SubmissionError`](http://redux-form.com/6.0.0-alpha.5/docs/api/SubmissionError.md/).
