### ISSUE TITLE
Drag and drop text inside input fields replace value with "undefined"

### ISSUE THREAD

**Issue by markuso** [erikras/redux-form#687]
When moving text around by dragging and dropping to a new location within an input field the value either disappears or gets replaced with the text "undefined".

To see this in action, try entering some text in the _Notes_ textarea input field on the [simple example form](http://erikras.github.io/redux-form/#/examples/simple) then select some text and drag it to another position within the same input field or onto another input field that already has a value in it.

We have users that actually do this as they move words and sentences around inside an input field.

![drag-drop-issue](https://cloud.githubusercontent.com/assets/56903/13341252/f849ebbe-dc04-11e5-86d5-42d911de0cdd.gif)

**Comment by erikras** [comment]
This is a known bug. #550 Thank you for the excellent screencast.

**Comment by ooflorent** [comment]
Closed in favor or #550.
