### ISSUE TITLE
Wizard: How to display errors on the first-page-with-errors?

### ISSUE THREAD

**Issue by ptim** [erikras/redux-form#690]
Nearly got my wizard working - I wonder if someone can help? 

My form is behaving well with five pages: each has synchronous validation, and I'm POSTing my values when validation passes on the last page.

The server sends me back a more specific validation error,  which applies to (say) page-2. I'm tracking currentPage state using redux rather than local state (as in the example: http://erikras.github.io/redux-form/#/examples/wizard), and I arrive on page 2.. but can't for the life of me figure out how to display the errors for invalid fields..

I'm logging the following in the render() method of my wrapped formPage:

```
this.props.errors: Object {field1: "server error for field"}
this.props.fields.field1.valid: true
this.props.fields.field1.touched: false 
this.props.fields.field1.errors: undefined
```

Do I need to programmatically touch the field somehow?

I've also tried: 

- `dispatch(stopSubmit({field1: 'server error for field'}));` which calls setErrors(), but no dice

TIA, Tim :)

**Comment by erikras** [comment]
If the errors are causing the submit promise to be rejected, they _should_ get set into the `redux-form` reducer already, like in the [Submit Validation](http://erikras.github.io/redux-form/#/examples/submit-validation) example, and also handle touching all the fields. You _are_ specifying all the fields (from all pages) in the `fields` array on the final wizard page?

If you're doing your submission outside the standard submit mechanism for some reason, then yes, you will need to mark the fields as touched and set the submit errors yourself.

```js
import {stopSubmit, touch} from 'redux-form';

dispatch(stopSubmit('myForm', {field1: 'server error for field'}));
dispatch(touch('myForm', 'field1', 'field2', 'fieldN'));
```

If I've misunderstood, perhaps some of the code around your `<form onSubmit>` on the final wizard page might help.

**Comment by ptim** [comment]
Thanks @erikras! I'm passing only relevant fields (and validators) to all bar the last page, which gets all fields.. The main thing I'm doing differently is that I'm constructing my wizard with a sprawling config file and a WizardPageTemplate which renders the fields dynamically.. 

I think touching the fields will do the trick :) I was definitely passing the wrong args :) I've been delving into the source, but it's slow going for me.. dense! Learning a lot :D

I'll report back shortly - it's top of my list for today :)

**Comment by ooflorent** [comment]
I'm closing this issue since it is inactive for more than a month.
Free free to continue the discussion if you have anything to add!
