### ISSUE TITLE
When submitting from parent container, being passed old state

### ISSUE THREAD

**Issue by mhahn** [erikras/redux-form#693]
I have a component that is being submitted from the parent container.

I'm passing `onSubmit` from the parent to the redux form wrapped component. When the function passed to `onSubmit` is called, the value within `collections` isn't the current value.

When I use `getValues` the correct state is returned. Also, in the logs after the change I see that the correct value is displayed in the state.

LMK if thats not enough info.

**Comment by ooflorent** [comment]
I cannot reproduce it. This may be related to your setup. If the issue is still there in v5.2.5, could you reopen this issue and provide a minimal reproducible sample? Thanks!
