### ISSUE TITLE
2 strange issues with select fields

### ISSUE THREAD

**Issue by joemsak** [erikras/redux-form#694]
Hey there, I hope I have provided enough code and a screencast for my issues. Let me know if you need more.

First the code https://gist.github.com/joemsak/77392f27c3084b70a551

And the screencast: 
http://i.imgur.com/HAKKJrC.gifv

So you'll see I added code to a couple of the selects to show an 'Other' field when 'other' is selected. This addition to the code seems to have really messed with the select box. 

It gets stuck on the initialValue option.

If I remove the redux-form part `{...this.props.field}` then the select box works as intended with the 'other' code.

Second, you see my other issue is that even if a select field has an option selected, the required field validation still highlights it as necessary to choose an option. I just have to focus and blur to make it go away.

I've tried to figure it out but I am just stuck.

**Comment by gbrlsepulveda** [comment]
Hey, i have both issues!

I noticed that state has changed, but a select field doesn't update selected option.

**Comment by mihirsoni** [comment]
Hi @joemsak , 

Could try to do this in your code [here](https://gist.github.com/joemsak/77392f27c3084b70a551#file-02-select-with-other-js-L39-L45)?

``` javascript
<select className="form-control"
  {...this.props.field}
  id={this.props.field.name}
  onChange={(event) => {
     this.props.field.onChange(event);
     this.onChange.bind(this)}>
{optipns}
</select>
```

**Comment by ooflorent** [comment]
I'm closing this issue since it is inactive for some time.

This is a usage question, and we encourage you to ask it on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.
