### ISSUE TITLE
Programmatically update field values

### ISSUE THREAD

**Issue by tylerevans** [erikras/redux-form#695]
Hi,

What is the best way to update the value of a field within a function.

See the screenshot attached. I am calling Google autocomplete for address, when I select an address i go to a function - i would then like to update one of my fields with this value.

I am following your Simple Synchronous Validation example, but basically want to trigger the redux action to change the value manually (within a function).

![screen shot 2016-02-29 at 4 59 18 pm](https://cloud.githubusercontent.com/assets/6850548/13386936/e8f373ca-df05-11e5-8ea0-3c8340b40404.png)

**Comment by tylerevans** [comment]
My code:
`
    <Geosuggest onSuggestSelect={::this._updateAddress} inputClassName="form-control" />
    <input className="form-control" type="text" {...address}/>
`

So I go into a function called _updateAddress, but then want to populate and update the address.value (so it will pass the validation etc)

**Comment by KELiON** [comment]
@tylerevans to populate new value to field you can use [onChange](http://erikras.github.io/redux-form/#/api/props) method of `props.fields.address`. Documentation says:

> it expects to either receive the React SyntheticEvent or the new value of the field

so you can call `this.props.fields.address.onChange(new_value)` in `_updateAddress` method

**Comment by tylerevans** [comment]
Great thanks!! works a charm

**Comment by nickbarry** [comment]
For future reference, the new way to do this in version 6 is using this.props.change(field_name, value). See [the docs](http://redux-form.com/6.2.0/docs/api/Props.md/#-change-field-string-value-any-function-).

**Comment by Jimmybee** [comment]
I am using change(form, field_name, value)

However the function doesn't dispatch the action...
Any help would be appreciated. Attached code below.

`import React, { Component } from 'react';
import { Field, reduxForm, change } from 'redux-form';
import { connect } from 'react-redux'

import { load } from '../../reducers/EditAppventure'
import AutoCompleteMap from '../../Components/Common/AutoCompleteMap.js';
import { createGeoPoint } from '../../api/Backendless.js'
import { updateReduxAppventureDetails } from '../../Actions/Actions';

class Location extends Component {


  render() {

    const { handleSubmit, appventure } = this.props;

    return (
      <div>
        <form onSubmit={handleSubmit} className="form-horizontal summaryComponent">
          <div className="form-group">
            <label htmlFor="startingLocationName">Location Name</label>
            <Field name="startingLocationName" component="input" type="text" placeholder="Location Name" className="form-control"/>
          </div>
           <button type="submit">Submit</button>
        </form>
        <AutoCompleteMap placeFound={this.placeFound} appventure={appventure}/>
      </div>
    );
  }

  placeFound(place) {
    let geoPoint = createGeoPoint(place)
    var appventure = {}
    appventure.location = geoPoint
    change("location", "startingLocationName", "value")
  }
}



// Decorate the form component
Location = reduxForm({
  form: 'location' // a unique name for this form
})(Location);

// You have to connect() to any reducers that you wish to connect to yourself
Location = connect(
  state => ({
    initialValues: state.editAppventure
  }),
  { load: load }               // bind account loading action creator
)(Location)

export default Location;`

**Comment by LearningNerdd** [comment]
What if you want to add validation as well as you want to update another field based on some other field.

Example:-
<Field
name="zipcode"
validate={validateZipField}
>
<Field
name="state"
>

My requirement I want to autopopulate my state field based on first two numbers of zipcode.
As soon as the users enters first two number i need to autopopulate the state field which is working fine.
What if I want to add some validations in the zipcode level.
such as the first two numbers needs to be between 11 to 19 and length should be 10.

So if the users enters 2222xxxxxy and removes the focus from the field, then i want to show error for both the fields.

for zip field, enter a valid zipcode and some message or same message for sate field also

**Comment by JetFault** [comment]
Is there a way to call `this.props.change('name', 'val')` and have it also call the `onChange` handler of the input?

I'm using React Material Web Components, and they move the label upward on the input's `change, blur, focus, input` events. But it seems `this.props.change` doesn't call the underlying input's change handler.

**Comment by matttk** [comment]
> Could you able to explain about how to use change()?

You just do this.props.change('nameOfYourField', 'value') and it will update the field in code.

**Comment by heyjaypray** [comment]
how would you go about updating a nest field?

for instance my form has form sections 
this.props.change('Orders.job_info.Address 1', value')
doesn't do anything

i've also tried 
this.props.change('Orders', 'job_info.Address1', 'value')

any ideas?

**Comment by heyjaypray** [comment]
@alexpetrus20  yeah i had to do it on my parent component and i had to do it on componentDidUpdate()
Not sure if my code will help but here it is.  I was also getting async problems which is why i used await

`
```
componentDidUpdate(prevProps, prevState) {
    if (this.props.formState !== prevProps.formState) {


      if (this.props.formState) {

        const update = async () => {

          const form = await this.props.formState;
          const customer = await form.job_info.customer;
          const dimensions = await form.dimensions;

          this.props.dispatch(change('Orders', 'job_info.Address1', customer.Shipping_Address1 || customer.Address1));
          this.props.dispatch(change('Orders', 'job_info.Address2', customer.Shipping_Address2 || customer.Address2));
          this.props.dispatch(change('Orders', 'job_info.City', customer.Shipping_City || customer.City));
          this.props.dispatch(change('Orders', 'job_info.State', customer.Shipping_State || customer.State));
          this.props.dispatch(change('Orders', 'job_info.Zip', customer.Shipping_Zip || customer.Zip));
          this.props.dispatch(change('Orders', 'job_info.Phone', customer.Shipping_Phone || customer.Phone1));




          form.dimensions.table.map((i, index) => {

            if (i.panelsW > 1) {
              if(i.panelsW !== prevProps.formState.dimensions.table[index].panelsW){
                this.props.dispatch(change('Orders', `dimensions.table[${index}].verticalMidRailSize`, i.topRail));
              }
            }

            if (i.panelsH > 1) {
              if(i.panelsH !== prevProps.formState.dimensions.table[index].panelsH){
                this.props.dispatch(change('Orders', `dimensions.table[${index}].horizontalMidRailSize`, i.topRail));
              }
            }

          });

        };

        update();

      }

    }
  }

```
