### ISSUE TITLE
Dependent selects 

### ISSUE THREAD

**Issue by KELiON** [erikras/redux-form#696]
Hello! 

I use redux-form and I have two dependent selects. I can't understand proper way of updating value of second one. My code looks like:

```javascript
renderProjects() {
  // just return static list of <option> tags
}
renderTaskLists() {
  // filter task lists by project_id, sort them and return array of <options>
}
render() {
  const {
    fields: {
      project_id, task_list_id,
    },
    handleSubmit,
  } = this.props;
  return (
    <form onSubmit={handleSubmit}>
      <select {...project_id}>
        {this.renderProjects()}
      </select>
      <select {...task_list_id}>
        {this.renderTaskLists()}
      </select>
    </form>
  )
}
```

So, if I change project `renderTaskLists()` returns new list of options and this list could contain previously selected task_list_id or not. So, in html it is done automatically – first element of list will be selected. But here I have to call `task_list_id.onChange(new_value)`. I don't like placing it in `renderTaskLists()` method, because it will have side-effects, but at the same time adding `onChange` handler to `project_id` field is too much for this task, as I think. What could you suggest?

**Comment by nickpalmer** [comment]
You can use the value for the first select stored in this.props.values.project_id when you are doing the render.

**Comment by jimmybaker** [comment]
How do you do this in v6 now that the fields array is gone?

**Comment by gustavohenke** [comment]
@jimmybaker [Use `Fields` component](http://redux-form.com/6.8.0/docs/api/Fields.md/)
