### ISSUE TITLE
No data in async validation

### ISSUE THREAD

**Issue by michalg42** [erikras/redux-form#697]
Hi!

I have problem with async validation. I'm using Material UI DatePicker - I already had to create wrapper around it to fire custom onChange function, where I just fire this.props.onChange(value). Then I added at the end of it one more line with this.props.asyncValidate() (because asyncValidate doesn't fire after selecting date), but it doesn't work - function does trigger, but it's too early - in values parameters inside asyncValidate my field is still empty.

I realize that probably this problem isn't related strictly to redux-form, but I have an impression that it would be easier to fix it from here than from material UI side. :)

**Comment by ooflorent** [comment]
Hi, thanks for reaching us!

This is a usage question, and we encourage you to ask it on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

This is the only way to ensure the same question doesn’t get asked many times in a row, and that folks who have the same question in the future will be able to find it.

I’m closing for these reasons.
