### ISSUE TITLE
Question: custom async submit that depends on dispatching actions

### ISSUE THREAD

**Issue by gabrielpugliese-luizalabs** [erikras/redux-form#698]
What are your thoughts on passing down action creators from the connected component to the async submit function versus importing the creator and dispatching it?

Passing down:
```
const submit = (someActionCreator) => () => someActionCreator();
```
Importing
```
import { someActionCreator } from 'my-ducks';

const submit = () => (values, dispatch) => dispatch(someActionCreator());
```

**Comment by erikras** [comment]
I prefer my action creators to already be bound to dispatch and passed in as props, via either `connect()` or `reduxForm()`. But it's a matter of taste, really.

**Comment by gabrielpugliese-luizalabs** [comment]
Hmm I see. Thanks for fast answer :)

**Comment by jasan-s** [comment]
Can action creators still be bound to dispatch using reduxForm() in V6?

**Comment by erikras** [comment]
No, you've got to do your own `connect()`ing in V6. `redux-form` had no business supplying that `mapStateToProps` and `mapDispatchToProps` functionality in `v5`.
