### ISSUE TITLE
this.props.onSubmit is undefined in ReduxForm.prototype.handleSubmit function

### ISSUE THREAD

**Issue by JosephShering** [erikras/redux-form#699]
I found this when I passed handleSubmit to my onSubmit. 

```
render() {
        const {
            fields: {
                username,
                email,
                password
            },
            handleSubmit,
            submitting

        } = this.props;

        return (
            <form onSubmit={handleSubmit}>
                <label>
                    Username
                    <input type="text" {...username} />
                </label>
```

**Comment by ffxsam** [comment]
IMO, this is the one problem I've found in this otherwise awesome package. It's not clear what we're supposed to be doing with `handleSubmit`. I'm following all the instructions given, and I always get this error:

>Uncaught Error: You must either pass handleSubmit() an onSubmit function or pass onSubmit as a prop

**Comment by genyded** [comment]
+1

**Comment by jljorgenson18** [comment]
The handleSubmit prop attempts to reference this.props.onSubmit when validation passes. If you wish to reference a different onSubmit function, you can pass it into the handleSubmit as an argument

``<form onSubmit={handleSubmit(this.mySubmitMethod)}>```

Otherwise, your parent class has to pass in an onSubmit function as a prop

```
<MyFormComponent onSubmit={this.myHandleSubmit} />
```
