### ISSUE TITLE
synchronous validation on blur or submit?

### ISSUE THREAD

**Issue by eventhough** [erikras/redux-form#70]
Is there an option we can set that tells our form component to fire the synchronous validation function only onBlur or onSubmit for the entire form? Currently the validate function is fired for both onChange and onBlur.

A problem I am facing is when the server returns errors after the form has been submitted. If my form errors are only shown when `field.error && field.touched`, the user will not see errors set after submission because the fields are not touched yet.

If instead we use `field.error && field.pristine` we get the opposite effect - the user can see submission errors for fields but once we touch the fields all the errors become hidden.

Ideally there would be another prop called `submitted` or something along those lines that would tell us if the form has been submitted at least once already.

**Comment by eventhough** [comment]
Sorry another related question - after I submit a form, I can see a `submitError` property in state but it's not available in field props. Was this by design? Is there a reason why we can't access the `submitError` property? This sounds like exactly what I need.

**Comment by erikras** [comment]
Are you refreshing the page when you submit, or submitting via ajax? The library is designed for the latter, and `touchAll` is called.

`submitError` should also be revealed as `props.fields.yourField.error`. Is it not?

**Comment by eventhough** [comment]
I figured out my issue. I was calling initialize on a form input which reset the error before it could be shown to the user.

Quick question, do you recommend we call `touchAll()` ourselves for every form submit? Is there a reason why it's not called automatically?

**Comment by erikras** [comment]
[`handleSubmit()` calls `touchAll()`](https://github.com/erikras/redux-form/blob/master/src/reduxForm.js#L192).

**Comment by erikras** [comment]
Reopen if this was not sufficiently explained.

**Comment by pavelvolek** [comment]
@erikras I understand how the `touchAll()` is used on `handleSubmit()`. But I do not see how to prevent the fields being marked as `touched` before the form is submitted for the first time. This is done automatically by the `onBlur()` function isn't it? How can I prevent the fields being validated until the first hit on the submit button?

**Comment by erikras** [comment]
@pavelvolek There is a `touchOnBlur` config flag that defaults to `true`. Try changing that.

**Comment by pavelvolek** [comment]
@erikras works fantastic, thank you.

**Comment by jiayihu** [comment]
What about the first question? I have a form with a large number of inputs, so I need to validate only on field blur.

> Is there an option we can set that tells our form component to fire the synchronous validation function only onBlur or onSubmit for the entire form? Currently the validate function is fired for both onChange and onBlur.

**Comment by oyeanuj** [comment]
@jiayihu You could use `asyncValidate` function. Or did you already end up using another solution?

**Comment by juanpasolano** [comment]
@jiayihu How would you use `asyncValidate` to achieve store updates only onBlur and not onChange?

**Comment by jiayihu** [comment]
@oyeanuj `asyncValidate ` does not solve the issue because I may want to validate the single input without affecting the other ones and without requests to the server. For examples checking that a `username` field accepts only words and numbers.

Anyway I might not be sure, since I didn't use `redux-forms` recently, but I think this issue was solved in the latest v6 version with a trick: filtering out `onChange` when passing the field props to the `input`.
For example:
```jsx
const renderField = ({ onChange, ...otherProps } = field.input) => (
  <input {...otherProps} type="text"/>
);

<Field name="myField" component={renderField}/>
```

**Comment by daviscabral** [comment]
@jiayihu if you omit `onChange`, value is never updated. How would you solve that? I am still looking for a solution on that.
