### ISSUE TITLE
Submit only dirty fields

### ISSUE THREAD

**Issue by TheTedAdams** [erikras/redux-form#701]
If there is an easy way to do this I apologize, but I'm having trouble with this one.

I have a form:
```ts
@reduxForm({
    form: 'self',
    fields: []
})
export default class SelfForm extends React.Component<Props, {}> {
    render() {
        const {
            handleSubmit,
        } = this.props;

        return (
            <form onSubmit={handleSubmit}>
                [...]
                <Button type="primary"
                    submit={true}>
                    Save
                </Button>
            </form>
        );
    }
}
```

I use it like
```ts
<SelfForm
    onSubmit={(data) => saveSelf(data)}
    formKey="self"
    fields={[...}
    initialValues={[...} />
```

What I would like to do is have an object with only the dirty field values passed to my onSubmit function. Inside the form I have access to `dirty` flags on the fields, but I'm not sure how to filter the fields down before they get to the `handleSubmit` function.

**Comment by erikras** [comment]
No, that's not a feature of the library. It's up to you to compare `initialValues` with the `data` passed to `saveSelf`. Perhaps something like [`object-diff`](https://www.npmjs.com/package/object-diff)?

Something like...
```js
saveSelf(data) {
  const delta = diff(this.initialValues, data);
  return ajax.post('/api/saveSelf', delta);
}
```

**Comment by aherriot** [comment]
@erikras The initialValues from the props parameter will not contain the initialValues if the form is initialized by dispatching the `initialize` action. Is there another way to get the actual initialValues?

**Comment by nicgordon** [comment]
@aherriot Does the getFormInitialValues selector which is described here solve your issue? http://redux-form.com/6.5.0/docs/api/Selectors.md/

**Comment by deiucanta** [comment]
@erikras Your solution is pretty good but I think `redux-form` should have something like this built in. A simple flag in `reduxForm()` should be fine.

Do you want me to send a PR?

**Comment by vorlov** [comment]
@deiucanta + 1

**Comment by dkniffin** [comment]
@erikras I think this should be built into the library. The specific use case for this is `PATCH`/`PUT` requests. They're intended to only send the updated data, not the entire object. Without this feature, every time someone wants an "edit" form (rather than a "new" form), they'll need to implement this themselves.

**Comment by dkniffin** [comment]
Also, we shouldn't need to use `object-diff` for this, since redux-form already keeps state about whether each field has changed.

**Comment by roytz** [comment]
@deiucanta did you send a pr? Does redux-form now has the functionality to submit only dirty fields?

**Comment by deiucanta** [comment]
@roytz no, I didn't do it since I didn't get the confirmation that it will be merged

**Comment by shai32** [comment]
@erikras please confirm

**Comment by shai32** [comment]
@deiucanta please do a pr, we need it.

**Comment by duro** [comment]
Agreed this is a needed feature. And it needs to be compatible with the immutable version of redux-form as well.

**Comment by benpetty** [comment]
With `immutable.js` I filter `values` against `props.initialValues` in the form's `onSubmit` function:

```js
const onSubmit = (values, dispatch, props) => {

  // props.initialValues.toJS() === { a: 'a', b: 'b', c: 'c' }
  // values.toJS() === { a: 'aaa', b: 'b', c: 'c' }

  const dirty_fields_only = values.filter((value, key) => !(value === props.initialValues.get(key)))

  // dirty_fields_only.toJS() === { a: 'aaa' }

  if (props.dirty) return yourFunction('api/endpoint', dirty_fields_only)
}

<form onSubmit={ handleSubmit(onSubmit) }> ... etc
```

**Comment by mrchief** [comment]
Looks like this feature made it in to v7.3.0? I'm getting only dirty fields but I actually need all the fields. This type of behavior belongs to user land, not the library, precisely for reasons like this.

**Comment by vladimirivanoviliev** [comment]
@mrchief I think you are mixing missing initial values by not sending values that are not changed.  In case you proviede initial values, they all values are send which is different than what we need here.

**Comment by mrchief** [comment]
Ah, I see. Thanks for the clarification.

**Comment by ggregoire** [comment]
A new [selector](https://redux-form.com/7.4.2/docs/api/selectors.md) would be welcome too!

```javascript
function getFormChangedValues = diff(getFormInitialValues(), getFormValues())
```

**Comment by BaptWaels** [comment]
Any update about this one ?
