### ISSUE TITLE
A small breaking change in React v15 impacts redux-form compatibility 

### ISSUE THREAD

**Issue by jmurzy** [erikras/redux-form#703]
I'm getting a bunch of uncontrolled input errors: facebook/react#5864, facebook/react#5821.

Here's a **dirty** workaround:

```javascript
const { fields: { field = '' } } = this.props;
if (!field.value) field.value = '';
```

**Update**
[15.0.0-rc.1](https://facebook.github.io/react/blog/2016/03/07/react-v15-rc1.html) is released.
<s>I realize v0.15 is alpha but I figured I'd report it before it turns into a show-stopping bug.</s>

**Comment by jmurzy** [comment]
@erikras Now that a release candidate has been tagged, can we have a fix for this? 🚧

**Comment by erikras** [comment]
Just to verify that I'm understanding the issue, the problem is that the `value` prop cannot be `undefined`?

```js
const value = undefined;
return <input type="text" value={value}/>; // <-------- bad (uncontrolled)
```

```js
const value = undefined;
return <input type="text" value={value || ''}/>; // <-------- good (controlled)
```

Is that an accurate summary?

**Comment by jmurzy** [comment]
Correct. Components should not switch from uncontrolled to controlled, or vice versa, where

```javascript
controlled = props.checked !== undefined || props.value !== undefined
```

**Comment by erikras** [comment]
How about `null`? Is that okay? Can you run a test on that?

I wonder which is best, `''` or `null`?

**Comment by jmurzy** [comment]
`null` throws

> `value` prop on `input` should not be null. Consider using the empty string to clear the component or `undefined` for uncontrolled components.

**Comment by erikras** [comment]
Excellent! Thanks!

**Comment by erikras** [comment]
Published as [`v4.2.1`](https://github.com/erikras/redux-form/releases/tag/v4.2.1). Thanks for your help, @jmurzy.

**Comment by jmurzy** [comment]
@erikras Awesome! Thanks!

**Comment by ooflorent** [comment]
It's a breaking change... Should have been released as `5.0.0`.

**Comment by ooflorent** [comment]
See #724

**Comment by jmurzy** [comment]
Ugh. 😓 I had a feeling this would've cost us a little more than defaulting to empty strings... 

@erikras Can we reopen this?

**Comment by erikras** [comment]
React v15 support released with [`redux-form v5.0.0`](https://github.com/erikras/redux-form/releases/tag/v5.0.0).

**Comment by gederer** [comment]
I'm seeing this again in 6.0.0-alpha.8.

`Warning: ``value`` prop on ``input`` should not be null. Consider using the empty string to clear the component or ``undefined`` for uncontrolled components.`

**Comment by erikras** [comment]
@gederer Published `null` fix as [`v6.0.0-alpha.9`](https://github.com/erikras/redux-form/releases/tag/v6.0.0-alpha.9).

**Comment by gederer** [comment]
@erikras felicitations and thanks!

**Comment by rogchap** [comment]
I'm still seeing the issue with v6.0.0-alpha.13
It may be because I'm calling `initialize` with no `fields` Array (as we don't do this in v6)
My initialize `data` object may not have all fields (i.e undefined):

``` jsx
const myObj = {
  street: '23 High Street',
  postcode: '90210'
}

dispatch('myForm', myObj)

// This is fine as this is initialized
<Field name="street"
  component={props => {
    return (
      <div>
        <label>Street</label>
        <input type="text' {...props} />
      </div>
    );
  }} />

// This throws warning as it's not in myObj
// worse if "select" input is used as it ignores defaultValue prop and selects first in list)
<Field name="state"
  component={props => {
    return (
      <div>
        <label>State</label>
        <input type="text' {...props} />
      </div>
    );
  }} />
```

**Comment by rogchap** [comment]
`value` changes to `null` `onFocus` of the input

**Comment by nmaves** [comment]
I am still seeing this issue on v5.2.5

**Comment by baldman** [comment]
What @nmaves said, seeing the same issue on v5.2.5

**Comment by ooflorent** [comment]
@nmaves and @baldman: Could you provide a minimal reproducible sample?

**Comment by JeroenNelen** [comment]
@ooflorent I'm seeing this issue when using a Dropdown element from react-toolbox as follows:
<Dropdown source={this.names} {...country} />

Kind regards,

**Comment by craigcartmell** [comment]
Seeing this also in 5.2.2, 5.3.0 and 5.3.1 on the Dropdown element of react-toolbox 1.0.1.

The initial value isn't being rendered correctly initially, despite definitely being correct.

Will try and investigate further.

**Comment by agnihotriketan** [comment]
Using **defaultValue** attribute worked for me in case of onblur.
