### ISSUE TITLE
in Complex Values example, only initial values for colors is working properly

### ISSUE THREAD

**Issue by intrepion** [erikras/redux-form#705]
Referring to this page:  http://erikras.github.io/redux-form/#/examples/complex

in the example code, I see this:

```js
  initialValues: {
    hobbies: [potentialHobbies[0], potentialHobbies[2]],
    favoriteHobby: potentialHobbies[2],
    colors: ['Red', 'Green', 'Blue']
  }
```

But in the actual page, you can clearly see the hobbies are not selected.  Also Favorite Hobby should be set to Hiking. 

![screenshot from 2016-03-02 09 45 17](https://cloud.githubusercontent.com/assets/1489553/13469277/8b5f9eb2-e05b-11e5-9aa9-17439f0debbc.png)

When I do a submit without changing anything, I do get the hobbies I'm expecting:

```js
{
  "hobbies": [
    {
      "id": 1,
      "label": "Guitar",
      "category": "music"
    },
    {
      "id": 3,
      "label": "Hiking",
      "category": "outdoors"
    }
  ],
  "favoriteHobby": {
    "id": 3,
    "label": "Hiking",
    "category": "outdoors"
  },
  "colors": [
    "Red",
    "Green",
    "Blue"
  ]
}
```

**Comment by intrepion** [comment]
I ended up fixing it this way:

in ObjectSelect.js I changed the following:
```jsx
        {options.map(option =>
          <option key={option.id} value={JSON.stringify(option)}>{option.label}</option>)}
```
to
```jsx
        {options.map(option =>
          <option key={option.id} value={option.id}>{option.label}</option>)}
```

in ComplexValuesForm.js I changed the following:
```jsx
  initialValues: {
    hobbies: [potentialHobbies[0], potentialHobbies[2]],
    favoriteHobby: potentialHobbies[2],
    colors: ['Red', 'Green', 'Blue']
  }
```
to
```jsx
  initialValues: {
    hobbies: [1, 3],
    favoriteHobby: 3,
    colors: ['Red', 'Green', 'Blue']
  }
```

**Comment by Dema** [comment]
Just replace value={value} on select with value={value && value.id}. I'm so glad that there is no two-way bindings in react!
