### ISSUE TITLE
for changed checkboxes touched/visited props are not present on FF

### ISSUE THREAD

**Issue by kwynns** [erikras/redux-form#706]
They are present on Chrome, but not FF. I haven't had time to setup an isolated test (suppose it could be something in my app, but can't think of what it would be). It does work as intended in Chrome.

Happens on El Capitan, FF 44.0.2

redux form 4.2.0 and 4.1.0

**Comment by ooflorent** [comment]
I'm unable to reproduce the bug. Can you please provide a minimal reproducible example and then reopen the issue ? My best bet is that `onFocus` and `onBlur` are not correctly propagated.
