### ISSUE TITLE
 Redux form and react native picker undefined value

### ISSUE THREAD

**Issue by gamezj** [erikras/redux-form#707]
Hi, I'am working in a project with redux-form and react native but always get undefined value for my picker

                  <Picker
                      {...region}
                      selectedValue={this.state.region}
                      onValueChange={(region) => this.setState({region, cityIndex:0})}>
                      {Object.keys(CITIES_AND_STATES).map((region) => (
                        <Picker.Item
                          key={region}
                          value={region}
                          label={CITIES_AND_STATES[region].name}
                          />
                      ))}
                    </Picker>
<img width="825" alt="screen shot 2016-03-02 at 3 47 03 pm" src="https://cloud.githubusercontent.com/assets/455605/13473973/14c7f118-e08e-11e5-811e-ccb714d107f6.png">

**Comment by davidkpiano** [comment]
Your `onValueChange` function needs to look like this:

```js
<Picker
  ...
  onValueChange={(val) => {
    region.onChange(val);
    this.setState({ region: val, cityIndex: 0 })>
```

**Comment by gamezj** [comment]
@davidkpiano Thanks a lot!

**Comment by erikras** [comment]
@davidkpiano Thanks for fielding (no pun intended) issues like these. I'm grateful.

**Comment by davidkpiano** [comment]
@erikras Anytime, here to help 🍻
