### ISSUE TITLE
asyncValidate with dynamic fields

### ISSUE THREAD

**Issue by Plummat** [erikras/redux-form#708]
Is there no way to do this? It seems you must pass fields to as asyncBlurFields, but I would not always know what field it is going to be

**Comment by erikras** [comment]
Any field that you can pass into `fields` can be passed in to `asyncBlurFields`. From [docs](http://erikras.github.io/redux-form/#/api/reduxForm):

> __IMPORTANT: All of these configuration options may be passed into reduxForm() at "design time" or passed in as props to your component at runtime.__

If there's a specific shape to your form that you'd like to discuss, let me know.

**Comment by Plummat** [comment]
Despite you putting that in giant letters, I still somehow missed it. Thanks man.

**Comment by anyong** [comment]
@erikras does this include arrays? I can't seem to get `foo[]` working to async validate on blur...

**Comment by beeant** [comment]
@anyong @erikras 
yes, I can't seem to get `foo[]` working too, but it works with `foo[0].attr`
