### ISSUE TITLE
Partially reset form

### ISSUE THREAD

**Issue by 5an1ty** [erikras/redux-form#709]
I have a really complex form and there's a scenario where I would have to reset (clear contents) a couple of fields in the form but not all of them, can I do that?

**Comment by mauriciosoares** [comment]
I don't know if that's the best approach, but if you dispatch an action to `redux-form/CHANGE` specifying the form, field and value, you can reset these manually...

example:

```js
dispatch({
  type: 'redux-form/CHANGE',
  field: 'name',
  value: '',
  form: 'form-name'
})
```

I'm using the `redux-form` internal actions and it works like a charm.

**Comment by mauriciosoares** [comment]
You could create a snippet to partially reset your stuff...

```js
const fields = {name: '', address: ''};

Object.keys(fields).forEach(field => dispatch({
  type: CHANGE,
  value: fields[field],
  form,
  field
}));
```

**Comment by erikras** [comment]
If you need to programmatically set values you can dispatch the `onChange` yourself, either by calling `this.props.fields.myField.onChange('newValue')` from inside your decorated component, or, if you are outside your form, you can dispatch the action yourself. Use the [action creator](http://erikras.github.io/redux-form/#/api/action-creators), though.

```js
import {change} from 'redux-form';

dispatch(change('myForm', 'myField', 'newValue'))
```

**Comment by mauriciosoares** [comment]
Ahh, I didn't check the action creator API reference. thanks!

@erikras, I'll use this issue to ask you a simple question, is there an action creator I can use to set errors to a field? for example:

```js
dispatch(error('form', 'field', 'error message'));
```

Or is there a way to do this?

if you prefer I can open a new issue for this.

**Comment by erikras** [comment]
@mauriciosoares Not an official one, no, but you could use `stopSubmit()` to fake a submission failure.

```js
dispatch(stopSubmit('form', {field: 'errorMessage'}));
```

**Comment by mauriciosoares** [comment]
perfect,

Do you think an error action creator would be useful in the actions API? I'd make use of that... Maybe I can send you a PR with that

**Comment by 5an1ty** [comment]
Thanks for all the replies everyone!

`dispatch(change('myForm', 'myField', 'newValue'))`

The code above worked for me.

**Comment by vadik49b** [comment]
@erikras `dispatch(change('myForm', 'myField', 'newValue'))` will just set new value to the field.
What to do if I want to **reset** the field (including reseting all meta props like touched and visited)?

**Comment by pidov** [comment]
@vadik49b Perhaps I'm late to the party, but I was looking for the same thing and stumbled upon [```clearFields```](https://redux-form.com/7.3.0/docs/api/actioncreators.md/#-code-clearfields-form-string-keeptouched-boolean-persistentsubmiterrors-boolean-fields-string-code-) which works great for my use case. Maybe it would work for you too.
