### ISSUE TITLE
Example for file Upload

### ISSUE THREAD

**Issue by sebas5384** [erikras/redux-form#71]
Hey! awesome work with redux-form!

I'm using it at production, and I'm going to use it for file inputs, but I would appreciate an example or ideia of how it would be done with redux-form.

thanks!

**Comment by BBB** [comment]
As far as I know, this is how:

1) It's important to note that `<input type="file" />` Doesn't support the setting of values
2) You need to do some parsing of the event before calling `fields.yourField.handleChange()`. Something like this:

```JSX
<input
  type="file"
  onChange={
    ( e ) => {      
      e.preventDefault();
      const { fields } = this.props;
      // convert files to an array
      const files = [ ...e.target.files ];
      fields.yourField.handleChange(files);
    }
  }
/>
```

Hope that helps.

@erikras: What do you think about updating `getValue` to support e.target.files? https://github.com/erikras/redux-form/blob/master/src/reduxForm.js#L28

**Comment by sebas5384** [comment]
@BBB thanks for the help! I finally did it using the https://github.com/paramaggarwal/react-dropzone

@erikras great patch! I'll use it in later integrations with other components ;)

**Comment by lemonCMS** [comment]
I have got this working in all current browsers, but IE 9 just return undefined, perhaps for older browsers you could return the field value?

**Comment by erikras** [comment]
@lemonCMS You mean like changing this:
```js
if (type === 'file') {
  return files || dataTransfer && dataTransfer.files;
}
```
to this:
```js
if (type === 'file') {
  return files || dataTransfer && dataTransfer.files || value;
}
```
??

**Comment by lemonCMS** [comment]
Yes :)

**Comment by edorivai** [comment]
I'm kinda struggling getting this to work. I'm under the impression I'm using the file input wrongly.

My initial attempt was to bind the same way I would bind any other input:

```js
<input type='file' {...image} />
```

But as @BBB points out, React complains that `value` cannot be set programatically. Second try; handle the change manually (after @BBB's suggestion):

```js
handleFile(fieldName, event) {
	event.preventDefault();
	const { fields } = this.props;
	// convert files to an array
	const files = [ ...event.target.files ];
	fields[fieldName].handleChange(files);
},
render() {
	(...)
	<input type='file' onChange={this.handleFile.bind(this, 'image')} />
	(...)
}
```

But `handleChange` is not defined on the field. Am I completely misunderstanding the suggestion, or has the API changed since the suggestion was made?

**Comment by lemonCMS** [comment]
I am not sure, but i think i had it working as following.

````javascript
const props = this.props.fields[field.name];

return (
<Input
        type="file"
        onDrop={props.onDrop}
        onChange={props.onChange}
        onFocus={props.onFocus}
        onUpdate={props.onUpdate}
        />
);
````

**Comment by erikras** [comment]
Yes, what @lemonCMS said should work. Although it could just be `<input type="file" {...field}/>`. :smile:

**Comment by edorivai** [comment]
Tried @lemonCMS' approach; changed

```
fields[fieldName].handleChange(files);
```

to

```
fields[fieldName].onChange(files);
```

which works.

**Comment by erikras** [comment]
Yes. `handleChange` went extinct in `v3.0`. :+1:

**Comment by duro** [comment]
@edorivai, @lemonCMS, @sebas5384: Do you guys have any examples of your approach to using file fields with redux-form? Especially if you were able to get it to work with a Dropzone component.

**Comment by edorivai** [comment]
@duro Haven't tried myself, but I think the following would work:

```js
<Dropzone onDrop={this.props.fields.myFileField.onChange}>
        <div>Try dropping some files here, or click to select files to upload.</div>
</Dropzone>
```

**Comment by austinmao** [comment]
+1 does anyone have an example of redux-form + dropzone?

**Comment by capkutay** [comment]
+1

**Comment by kitze** [comment]
@austinmao have you found an example maybe? :)

**Comment by austinmao** [comment]
Nope :(

**Comment by BBB** [comment]
@duro @austinmao @kitze I've put together a simple example of using dropzone with redux-form. http://ollie.relph.me/blog/redux-form-and-dropzone-react-example/ Any questions, just post an issue on the repo!

**Comment by shatran** [comment]
Did anyone had an experience with asyncValidate and Dropzone?
I'm trying to upload a file using react-dropzone and async validate a successful/unsuccessful file upload. The problem is i can't get asyncBlurFields to work with react-dropzone, and calling asyncValidate directly inside onChange doesn't work because 'values' object in asyncValidate is outdated and don't contain the file i want to upload. Any ideas? 
Thanks!

**Comment by serranoarevalo** [comment]
I don't know if this helps anybody but this approach: `<input type="file" {...field} />` didn't threw an error when I specified the `value={null}` inside of it like so:

`<input type="file"  {...profilePic} value={null} />`

**Comment by erikras** [comment]
@serranoarevalo That is, in effect, converting it back to an [uncontrolled input](http://facebook.github.io/react/docs/forms.html#uncontrolled-components), which might be necessary for file inputs, I don't know. The React docs are light on that corner of the DOM.

**Comment by mikethejet** [comment]
where is the binary content of fole i can save for example to rethinkDB using r.binary ? (if i am using react-dropzone in redux) there is not any field that holds the data of file.. ?

**Comment by GuillaumeCisco** [comment]
Hello, is there a simple way to use Dropzone with the new api `Field`, I'm struggling with the `onChange` binding :/ As we cannot access `this.props.fields` anymore. Using a ref ?

Thank you,

**Comment by GuillaumeCisco** [comment]
Hello everybody.
For interested people, I managed to make it work with:
```javascript
<Field name="picture" component={props =>
    <Dropzone
       {...props.input}
        multiple={false}
        style={dropzoneStyle}
        onDrop={(filesToUpload) => {
         this.files = filesToUpload;
         return props.input.onChange(filesToUpload);
         }}
    >
         <div>Try dropping a file here, or click to select file to upload.</div>
    </Dropzone>
    } type="file"/>
    {this.props.files &&
    <div>
        {this.props.files.map((file, i) => <span key={i}>{file.name}</span>)}
    </div>
     }
```

For information `files` is an array declared in my component as : `files: []`.
If you don't need to display current selected files, you can just use `onDrop= props.input.onChange`
Documentation should handle this behavior.

Hope it will helps ;)

**Comment by carpeliam** [comment]
@BBB's earliest comment here works for me (on redux-form@5.3.1 and react@15.1), save for one issue: the first time we select a file, the store is updated with the new form value and the component is rendered with the appropriate value; in subsequent changes to the file input, the store is updated properly and the component is rerendered but always receives the first file we chose.

I've uploaded a minimal example to http://carpeliam.github.io/redux-form-file-input-example, with code at https://github.com/carpeliam/redux-form-file-input-example.

**Comment by carpeliam** [comment]
@erikras not sure if you saw the above comment - should I file a separate issue? Not sure if 5.3.1 is supposed to work with React 15.1 or not.

**Comment by jckdrpr** [comment]
Hi I was trying to use dropzone with redux-form
```jsx
export class Dropzone extends React.Component {
  render() {
    const { id, field, label, labelSm, controlSm, ...other } = this.props;
    return (
      <div>
        <FormGroup
          controlId={id}
          validationState={validationState(field.meta)}
        >
          <Col componentClass={ControlLabel} sm={labelSm}>
            {label}
          </Col>
          <Col sm={controlSm}>
            <ReactDropzone
              {...field.input}
              {...other}
              onDrop={field.input.onChange}
            >
              <div>Try dropping a file here, or click to select file to upload.</div>
            </ReactDropzone>
            <FormControl.Feedback />
            {errorMsg(field.meta)}
          </Col>
        </FormGroup>
        {field.input.value && <div>{field.input.value.map((file, i) => <span key={i}>{file.name}</span>)}</div>}
      </div>
    );
  }
}
```
where `ReactDropzone = require('react-dropzone')`
and using it like this in one of the forms that I have
```jsx
        <Field
          name={'files'}
          component={(field) =>
            <Dropzone
              id={'files'}
              label={'Documents'}
              field={field}
            />
          }
        />
```
And I get a state mutation
```
Uncaught Invariant Violation: A state mutation was detected between dispatches, in the path `form.abc.values.files.0.lastModifiedDate`. This may cause incorrect behavior.
```
where abc is the form name.
Can anyone point out where the problem is?

**Comment by shawnmclean** [comment]
How does the new `<Field>` look with files type? Do I need my own file component? I can't seem to do `type="file"`

**Comment by BBB** [comment]
https://github.com/BBB/dropzone-redux-form-example Has now been updated to work with `v6`. @shawnmclean @jckdrpr You might find it helpful.

**Comment by jckdrpr** [comment]
Hey @BBB I tried out the example on the repo linked in your answer and I added `redux-immutable-state-invariant` to the project and I am getting the same error. Has no one else faced this issue?

Well it does work when there is no `redux-immutable-state-invariant`.

**Comment by asiniy** [comment]
My take

``` javascript
import React from 'react'

class FileInput extends React.Component {
  constructor(props) {
    super(props)
    this.onChange = this.onChange.bind(this)
  }

  onChange(e) {
    const { input: { onChange } } = this.props
    onChange(e.target.files[0])
  }

  render() {
    const { input: { value } } = this.props

    return (<input
      type="file"
      value={value}
      onChange={this.onChange}
    />)
  }
}

export default FileInput
```

and then

``` javascript
import { Field } from 'redux-form'

<Field
  type="file"
  name="poster"
  component={FileInput}
/>
```

Works awesome!

**Comment by SepiaGroup** [comment]
thanks to @BBB i came up with the following

```
import React from 'react';
import Dropzone from 'react-dropzone';

const ReduxFormDropzone = (field) => {
    var props = {...field};  // to be able to pass props to Dropzone 
    delete props.input;     // remove the input property
    delete props.meta;     // remove the meta property
    delete props.dropzoneOnDrop;  // remove the dropzoneOnDrop property

    return (
        <Dropzone
            onDrop={(acceptedFiles, rejectedFiles, e) => {
                field.input.onChange(acceptedFiles);
                field.dropzoneOnDrop && field.dropzoneOnDrop(acceptedFiles, rejectedFiles, e);
            }}
            {...props}
        />
    );
}

export default ReduxFormDropzone;
```

then you just need to do...

```
<Field
    name={"files"}
    component={ReduxFormDropzone}
    style={style.dropzone}
    multiple={false}
    dropzoneOnDrop={this.handleDrop}
/>
```

a couple of notes: 

- on the Field component, to use the Dropzone onDrop you have to use dropzoneOnDrop because Field has a OnDrop 

- I removed a couple of props in the Dropzone component because Dropzone throws warnings for unknown properties, this is just to prevent these warnings.

**Comment by yagneshmodh** [comment]
@BBB I am getting the same error as @jckdrpr . Please suggest some solution for same.

`browser.js?9520:40 Uncaught Error: A state mutation was detected between dispatches, in the path `form.SkillForm.values.files.0.lastModifiedDate`. This may cause incorrect behavior.`

@jckdrpr Have you find any solution for above mention error?

**Comment by aindong** [comment]
@BBB your example returns empty formdata and the server cant find the payload. Any idea?

**Comment by hemedani** [comment]
@asiniy  did not work with v6 throw this error: 
```
Uncaught DOMException: Failed to set the 'value' property on 'HTMLInputElement': This input element accepts a filename, which may only be programmatically set to the empty string.
    at Object.updateWrapper (webpack:///../~/react-dom/lib/ReactDOMInput.js?:156:20)
    at ReactDOMComponent.forceUpdateIfMounted (webpack:///../~/react-dom/lib/ReactDOMInput.js?:34:19)
    at CallbackQueue.notifyAll (webpack:///../~/react-dom/lib/CallbackQueue.js?:76:22)
    at Object.flushBatchedUpdates (webpack:///../~/react-dom/lib/ReactUpdates.js?:180:13)
    at ReactDefaultBatchingStrategyTransaction.closeAll (webpack:///../~/react-dom/lib/Transaction.js?:206:25)
    at ReactDefaultBatchingStrategyTransaction.perform (webpack:///../~/react-dom/lib/Transaction.js?:153:16)
    at Object.batchedUpdates (webpack:///../~/react-dom/lib/ReactDefaultBatchingStrategy.js?:62:26)
    at Object.batchedUpdates (webpack:///../~/react-dom/lib/ReactUpdates.js?:97:27)
    at dispatchEvent (webpack:///../~/react-dom/lib/ReactEventListener.js?:147:20)
```

**Comment by potty** [comment]
My solution based on https://github.com/erikras/redux-form/issues/2532#issuecomment-277926328. I don't know how hacky is it, but works for me:

`import React from 'react'

export const FileInput = ({ input, resetKey }) => {
	const { value, ...inputProps } = input

	const handleChange = (e) => {
		input.onChange(e.target.files[0])
	}

	return (
		<input {...inputProps} key={resetKey} type="file" onChange={handleChange} onBlur={() => {}} />
	)
}`

`<Field name="image" component={FileInput} onChange={this.handleFileChange} />`

I'm saving data URI from image cropper as value of the field. The problem was that onBlur was resetting field value to FileList object, so I had to disable it.

**Comment by jeserodz** [comment]
What worked in my case:

1. Create a functional component that returns an `<input type="file"/>` component.
2. Delete the `value` property from `field.input` in the functional component
3. Use the functional component in `<Field component={} />`
 
```javascript
import React, { Component } from 'react';
import { Field, reduxForm } from 'redux-form';

/** 
 * File input workarround:
 * More info: http://redux-form.com/5.2.5/#/examples/file?_k=57hmlw
 */
const customFileInput = (field) => {
  delete field.input.value; // <-- just delete the value property
  return <input type="file" id="file" {...field.input} />;
};

class SubmitVideoForm extends Component {
  render() {
    return (    
        <form className="submit-video-form">
          
          <Field 
            name="file"
            type="file"
            component={customFileInput}/>

          <input type="submit" value="Submit your video"/>
        </form>
    );
  }
}

SubmitVideoForm = reduxForm({
  form: 'submitVideoForm'
})(SubmitVideoForm);

export default SubmitVideoForm;
```

**Comment by rmontes13** [comment]
Just one thing to point in the answer from @asiniy, just remove the value attribute form the returned input to avoid error "Failed to set the 'value' property on 'HTMLInputElement': This input element accepts a filename, which may only be programmatically set to the empty string."

```
    return (<input
      type="file"
      onChange={this.onChange}
    />)
```

More information http://redux-form.com/5.2.5/#/examples/file?_k=z12d2f

**Comment by vitalykorneev** [comment]
Hi. I have same problem like https://github.com/erikras/redux-form/issues/71#issuecomment-243444038
Is there a way to solve the problem?

**Comment by LulzAugusto** [comment]
I'm having the same problem as @sherubthakur mentioned with `redux-immutable-state-invariant`. Any solutions?

**Comment by rewop** [comment]
About the problem from https://github.com/erikras/redux-form/issues/71#issuecomment-243444038, I found out that `deep-equal` used in [this condition](https://github.com/erikras/redux-form/blob/v5/src/createHigherOrderComponent.js#L55), returns true (equal) from the second part of the condition, given two different instances of File object.

**Comment by rewop** [comment]
A work around for https://github.com/erikras/redux-form/issues/71#issuecomment-243444038  is to not return the File object as value to the `onChange` of the field, but to return an object like: 
```
{
    file: e.target.files[0],
}
```

**Comment by pacozaa** [comment]
@SepiaGroup You are the man!

Do you manage to do the image preview as well?

**Comment by knowvera-michael** [comment]
@pacozaa  glad you found it helpful.

preview should work, what seems to be the issue?

**Comment by SepiaGroup** [comment]
@pacozaa glad you found it helpful.

preview should work, what seems to be the issue?

**Comment by pacozaa** [comment]
@SepiaGroup 
Thank you again!
I forgot they are array value because it assume everything there are multiple files.
So I solve my problem just add `[0]` behind variable!

Anyone who face the same problem please don't forget to add `[0]` like this
`file[0]`

Again use @SepiaGroup trick works like a charm.

**Comment by lupitadavila** [comment]
@LulzAugusto @vitalykorneev I have the same issues as you. Did you ever find a solution?

**Comment by LulzAugusto** [comment]
@lupitadavila Oh sorry for such delay in answering you. About your question, I didn't find a solution, but I've updated `redux-immutable-state-invariant` and I'm now using their `ignore` parameter to pretend that the issue doesn't exist anymore. 😂

**Comment by JohnHour89** [comment]
@GuillaumeCisco hey, I have tried your method mentioned at here https://github.com/erikras/redux-form/issues/71#issuecomment-234234555 it seems work but may I know how to get the url from it? Because the results returned it is always show as [object FileList] as shown in the screenshot below:

![screen shot 2017-12-20 at 8 59 42 am](https://user-images.githubusercontent.com/19371443/34186038-3562a512-e564-11e7-8a6e-35d51ab881db.png)

I just want to get the url from it, thank you

**Comment by GuillaumeCisco** [comment]
Hey @JohnHour89 , please understand how FileList works https://developer.mozilla.org/en-US/docs/Web/API/FileList
It is just an array of objects.
If you want to create an url from a File object, you can use `data` or `blob`
https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL

Hope it will help

**Comment by nguyennb9** [comment]
I have a form which using `onSubmit` of the `Form`:
`<Form onSubmit={handleSubmit(this.onSubmit)}>`

The function onSubmit can only capture the string, number... but not the file 
```
  onSubmit(formData) {
   
  }
```
The examples above using `onChange` method to capture the file, but I want to use `onSubmit`, any suggestion?

**Comment by tini2n** [comment]
Have problem with save in store, file from `input[type="file"]` 😓
I am using Fields Array (`<FieldArray name="companyCertificates" component={InputFile} />`) to generate new inputs after adding file. After input onChange I trying to save `e.target.files[0]` to store through `input.onChange(e.target.files[0])`, but Redux Inspector is showing me empty object. 

Maybe I use not correct method to save or Redux Inspector don't show file value?
 
This my `InputFile` component:
```js
import React, { Component } from 'react';
import { Field } from 'redux-form';

const InputField = ({ input, fields, index }) => {
    delete input.value;

    const fieldAdd = (e, fields) => {

        if (e.target.files[0]) {
            fields.push();
            input.onChange(e.target.files[0])
        }
    };

    return (
        <input type="file"
               {...input}
               onChange={(e) => {
                   e.preventDefault();

                   fieldAdd(e, fields, input);
               }}
               accept=".pdf" />
    )
};

export default class InputFile extends Component {
    constructor (props) {
        super(props);
    };

    componentWillMount () {
        let { fields } = this.props;

        if (fields.length === 0)
            fields.insert(0, null);
    };

    render () {
        let { fields } = this.props;

        return (
            <div className="input-group input-file">
                <div className="files">
                    {fields.map((name, index) => {
                        return (
                            <Field name={name}
                                   key={index}
                                   index={index}
                                   fields={fields}
                                   component={InputField} />
                        )
                    })}
                </div>
            </div>
        )
    }
};
```

Could smbdy help me with saving this file in store to send it later?
Thanx a lot!

**Comment by GuillaumeCisco** [comment]
@tini2n the problem is in thos part
```javascript

// should be a Class
const fieldAdd = (e, fields) => {

        if (e.target.files[0]) {
            // you are pushing nothing
            fields.push();

            // input is unknown
            input.onChange(e.target.files[0])
        }
    };

    return (
        <input type="file"
               {...input}
               onChange={(e) => {
                   e.preventDefault();

                   // passing input parameter but not using it
                   fieldAdd(e, fields, input);
               }}
               accept=".pdf" />
    )
```

**Comment by tini2n** [comment]
@GuillaumeCisco thanx for reply!)

`fields.push()` is FieldsArray's method to add new input elements. Seems that it working well.
`input` is known as input element. Below console.log of it
![image](https://user-images.githubusercontent.com/10106572/38620959-780021dc-3da8-11e8-8cb1-3176abbeaffa.png)

I checked Diff of values and saw that value in store is replaced by empty object:
![image](https://user-images.githubusercontent.com/10106572/38621108-d575c84e-3da8-11e8-95f5-993bd41bb00a.png)

**Comment by GuillaumeCisco** [comment]
@tini2n Your code is too messy. Please clean it, use a Class for `InputField` and declare correctly your functions and parameters.
There is no declaration of FieldArray in your sample code.
Furthermore, you are pushing nothing, see the doc about FieldArray's push method:
```
fields.push(value:Any) : Function
Adds a value to the end of the array. Returns nothing.

This is not a mutator; it dispatches an action which updates the state in Redux, which will cause your component to rerender.
```

**Comment by eleventhaus** [comment]
@tini2n Did you ever get a field array to work with file type inputs?
