### ISSUE TITLE
Passing controlled component values in form

### ISSUE THREAD

**Issue by krmannix** [erikras/redux-form#711]
I would like to pass along the value of a controlled component on a form submission. Looking at other issues (#679) that deal with inputs that will likely not be touched, the solution seems to be setting the initialValue on the first page of the wizard (I'm following the Wizard example).

However, this value is dynamic, and loaded from an async request (example: a version number from a document that is loaded asynchronously). I'm not sure how to define this value when submitting the form - it's current value in the `handleSubmit` function is `undefined`, since it's never touched. I don't want to manually change the state of the form on submission to include this value. Is there a good way to indicate that a components value should be passed along in a submission, even if it was never touched? Or is there a better way to provide this functionality?

Example below:

``` js
render () {
  const {
    fields: { versionNumber },
    version,
    handleSubmit,
  } = this.props
  return (
    <form onSubmit={handleSubmit}>
      <input 
        value={version} // this is submitted as undefined, even when `version` is a value
        {...versionNumber}
      />
      <button type='submit'>
    </form>
  )
}
```

**Comment by erikras** [comment]
You don't need the `<input/>` component if you're not editing that value. If all you want is to turn a prop into a value in your submission, I'd recommend something like this:
```js
<form onSubmit={handleSubmit(data => onSubmit({...data, versionNumber: version}))}>
  // other inputs here
  <button type="submit">Submit</button>
</form>
```
Like that you don't even need to include it in the `fields` array.

**Comment by krmannix** [comment]
@erikras genius, thank you so much. To confirm, I need to return a promise from the `onSubmit` function to trigger the `START-SUBMIT` action?

**Comment by egmanoj** [comment]
@erikras Does the _prop-turned-value_ get validated? I'd like it to, but that doesn't seem to be happening. I'm passing a `validate` function to `reduxForm({...})` and even though this method does get called it is not getting _prop-turned-value_. 

Alternately, how does one validate a _prop-turned-value_?

**Comment by qborreda** [comment]
How would I do that for the validate function? 
Say, I'd like to pass an object with the error messages, composed dynamically according to my `context.locale` value ?

**Comment by RodSwanston** [comment]
How can i send another parameter to validate function?

**Comment by RUIFERNANDE5** [comment]
@erikras how can I do this in react-native? Form element can't seem to work there.
