### ISSUE TITLE
Required context `submitting` was not specified

### ISSUE THREAD

**Issue by foobar8675** [erikras/redux-form#712]
when running the form below, I get this error

Warning: Failed Context Types: Required context `submitting` was not specified in `PasswordReset`. Check the render method of `ReduxForm(PasswordReset)`.

which I don't understand, since i'm setting the submitting value in the first line of render(). Anyways, if anyone has any suggestions, it would be very appreciated.

````
import React, {Component, PropTypes} from 'react';
import {reduxForm} from 'redux-form';
import {resetPassword} from '../actions/index';

import styles from './password_reset.css';

class PasswordReset extends Component {

	static contextTypes = {
		router: PropTypes.object,
		submitting: PropTypes.bool.isRequired
	};

	onSubmit(props) {
	}

	render() {
		const {fields:{password1, password2}, handleSubmit, submitting} = this.props;
		return (
			<form onSubmit={handleSubmit(this.onSubmit.bind(this))}>

				<div className="row">
					<h3 className="text-center">Password Reset</h3>
				</div>

				<div className={`form-group ${password1.touched && password1.invalid ? 'has-danger' : ''}`} >
					<input type="password" placeholder="New Password" className="form-control" {...password1}/>
					<div className={styles.textHelp}>
						{password1.touched ? password1.error : ''}
					</div>
				</div>

				<div className={`form-group ${password2.touched && password2.invalid ? 'has-danger' : ''}`} >
					<input type="password" placeholder="Confirm New Password" className="form-control"  {...password2}/>
					<div className={styles.textHelp}>
						{password2.touched ? password2.error : ''}
					</div>
				</div>

				<div className="row">
					<div className="col-sm-4">
						<button type="submit" disabled={submitting}>Reset Password</button>
					</div>
				</div>
			</form>
		)
	}
}

function validate(values) {
	const errors = {};
	return errors;
}

export default reduxForm({
	form : 'ResetPasswordForm',
	fields : ['password1', 'password2'],
	validate
}, null, {resetPassword})(PasswordReset);
````

**Comment by CodyReichert** [comment]
I might be confused about what you're trying to do - but if you already have `this.props.submitting` why do you need `this.context.submitting`?

**Comment by foobar8675** [comment]
thanks for responding @CodyReichert . I was trying to mimic the example here. http://redux-form.com/4.2.0/#/examples/synchronous-validation?_k=z4zi3n where as i understand, passing the context.submitting to the props.submitting is how you enable/disable the btn. am i missing something?

**Comment by erikras** [comment]
The examples are not using `context` anywhere, nor is `redux-form` `v4.x`. I would remove `submitting` from your `contextTypes`.

**Comment by CodyReichert** [comment]
@foobar8675 no problem. I would, like @erikras said, not worry about any `context` from redux-form. Instead, you would disable the button by using the `submitting` prop only - which it looks like you already have setup correctly.

**Comment by foobar8675** [comment]
got it. my bad. thanks for clarifying :)
