### ISSUE TITLE
Submit form on field change

### ISSUE THREAD

**Issue by rockingskier** [erikras/redux-form#714]
Is it possible to submit the form on field change?

I am looking to automatically continue to the next step of a wizard when the user selects a radio option.  On the first page of my wizard the user picks 1 (and only 1) option that decides the next step. This would allow my users to progress through the wizard a lot more fluidly rather than selecting an option and then pressing submit / continue.

**Comment by LucaColonnello** [comment]
You could wrap the fileds' onChange with a function that call the original onChange and then dispatch the submit action using the handleSubmit in the props.

```js

const onChangeSubmit = (onChange, handleSubmit) => e => {
   onChange(e);
   handleSubmit( );
};

class LoginForm extends Component {
   render() {
     const { user, pass, handleSubmit } = this.props;

     return (
       <form onSubmit={handleSubmit}>
         <input {...user} onChange={onChangeSubmit(user.onChange, handleSubmit)} />
         <input {...pass} onChange={onChangeSubmit(pass.onChange, handleSubmit)} />
         <button onClick={handleSubmit}>Login</button>
       </form>
     );
   }
}

// here redux form connect
```

**Comment by rockingskier** [comment]
I had used created a `handleOnChange` on the class but your suggestiob of a util is perfect, now I can use it on numerous classes

I did have to add a `setTimeout` on the `handleSubmit`

```javascript
export default function onChangeSubmit(onChange, handleSubmit) {
  return (event) => {
    onChange(event);
    setTimeout(() => handleSubmit(), 0);
  };
}
```
