### ISSUE TITLE
GitHub Pages not working

### ISSUE THREAD

**Issue by rjokelai** [erikras/redux-form#719]
Link from README:
http://erikras.github.io/redux-form/#/api

produces an error page: "404 - There isn't a GitHub Pages site here."

**Comment by erikras** [comment]
Thanks

**Comment by erikras** [comment]
http://redux-form.com/4.2.0/#/api <---- there

In the process of a migration to [redux-form.com](http://redux-form.com). Should be fixed now, but your link will remain broken (it forwarded you to the wrong place).
