### ISSUE TITLE
Resetting the form doesn't clear textarea elements

### ISSUE THREAD

**Issue by aaronmcadam** [erikras/redux-form#720]
Here's the code I'm using:

```js
import { reset } from 'redux-form';
dispatch(reset('interviewForm'));
```

As mentioned in https://github.com/erikras/redux-form/issues/11, resetting the form doesn't clear `textarea`s.

I've confirmed it works with `input`s, just not `textareas`.

**Comment by erikras** [comment]
Wow! Referencing issue #11! That must be a record. :smile: 

This is somewhat of a known issue, https://github.com/facebook/react/issues/2533, as shown in the [Simple Form](http://redux-form.com/4.2.0/#/examples/simple) example.

![redux form 2016-03-08 15-10-04](https://cloud.githubusercontent.com/assets/4396759/13603795/f8f1f9c8-e53f-11e5-874b-6701974e5b98.jpg)

If you have some suggestions as to what `redux-form` could do to help, they'd be welcome.

**Comment by aaronmcadam** [comment]
Sorry @erikras, I just found #547! Thanks!
