### ISSUE TITLE
to a newcomer it's hard to figure, how to handle submitting

### ISSUE THREAD

**Issue by sosloow** [erikras/redux-form#721]
I got it, but please, for the future, can you add some brief note about `onSubmit` on the "Getting Started" page?

I haven't found how to listen to submit event, and tried the example, but even there there's no `onSubmit` handler - I had to figure it through the error message.

**Comment by erikras** [comment]
I agree that the docs on that are lacking. I'm in the process of reworking all the docs, and I will definitely take this into consideration.

The definitive docs at the moment is under `handleSubmit` [here](http://redux-form.com/4.2.0/#/api/props).

Thank you for your feedback.

**Comment by fieldju** [comment]
@sosloow How did you wire up the handleSubmit to an action?

**Comment by genyded** [comment]
@sosloow yes - posting an example would be nice since others seem to be running into this too...
