### ISSUE TITLE
swapFields is missing

### ISSUE THREAD

**Issue by luiskhernandez** [erikras/redux-form#723]
Hi, guys.  

version 4.2.0

I have a array inside the fields
 ```const fields = ['surveyName',
                'questions[].description',
                'questions[].options[]'
]```

`this.props.fields.questions` has `addField` and `removeField` but the method `swapField` is missing. Any idea?

**Comment by luiskhernandez** [comment]
I downgrade to version `4.1.2` and it has the method `swapFields`. Is this removed in the latest  version?

**Comment by erikras** [comment]
Hmm... That's pretty odd. [Looks like it should be there](https://github.com/erikras/redux-form/blob/master/src/readField.js#L58). Do you have it if your field is not deeper? I mean, if you just had `questions[]` instead of `questions[].description`? Can you test that for me?

**Comment by luiskhernandez** [comment]
Ups, this is embarrassing. it's working fine. I don't know what i was doing before that the method didn't appear.  Sorry about that.
