### ISSUE TITLE
Revert default value as string

### ISSUE THREAD

**Issue by ooflorent** [erikras/redux-form#724]
Please revert d44bd6a6be36f52c28e082f4d054039647d15368.

It triggers a lot of warnings in on custom inputs where `value` is not a `String`.
This is a really common pattern...

Moreover setting values as empty string could break validators which accept other types.

**Comment by erikras** [comment]
Sorry about that. Was too hasty with that change.

**Comment by ooflorent** [comment]
No problem. I think we should find a better way to handle managed input values.

**Comment by erikras** [comment]
React v15 support released with [`redux-form v5.0.0`](https://github.com/erikras/redux-form/releases/tag/v5.0.0).
