### ISSUE TITLE
Ref to WrappedComponent?

### ISSUE THREAD

**Issue by MrEfrem** [erikras/redux-form#729]
That WrappedComponent is possible to add ref?
Such as it is realized in [react-redux] (https://github.com/reactjs/react-redux/blob/master/src/components/connect.js).
It is necessary to have access to public api WrappedComponent.

**Comment by MrEfrem** [comment]
Hi @erikras. You couldn't share thoughts on this matter? Why are you silent?

**Comment by ooflorent** [comment]
I'm closing this in favor of #840. Feel free to continue the discussion there.
