### ISSUE TITLE
Making multipart form handling easier

### ISSUE THREAD

**Issue by ntucker** [erikras/redux-form#734]
The only way to send attachements with a form is using the multipart content encoding. This means it won't be nested json datastructure, but use the actual names put on fields blah.foo.

Both axios and superagent support creating multipart requests by sending a https://developer.mozilla.org/en/docs/Web/API/FormData FormData object.

It would be nice if there were an option to get FormData from the form submission event. Right now I'm reversing the process you use to construct the object data structure.

**Comment by ooflorent** [comment]
This is a usage question, and we try to use the issue tracker for bug reports and feature requests, as well as some discussions. StackOverflow is better place to ask for help.

You can create an helper to manipule `values` from `onSubmit` to create a `FormData` instance. Since this use case is really specific I don't think it should be included in Redux Form core.

**Comment by ntucker** [comment]
How are attachments really specific? That's a common thing forms do...

**Comment by saiprashanths** [comment]
+1

**Comment by zazapeta** [comment]
Something can be done like this : 
 reduxForm({
  form: 'myForm',
  multipartForm : true, // <- handle this form as a multipart from and send to handleSubmit a FormData object populated by the form's values
  validate
})(MyFormView);

**Comment by kaueburiti** [comment]
This should be included in redux-form core :/
Its a really importante feature.

**Comment by Tenkir** [comment]
This _NEEDS_ to be in the core. This is not a `really specific user case.

**Comment by erikras** [comment]
PRs are always considered.

You guys do understand that the data is kept in JSON (or `Immutable.Map`) in Redux, right? So any multipart form solution is going to have to convert the JSON to `FormData`. I'm not sure why adding that additional code to the core library, for everyone, even without this use case to have to download, is a good solution. It seems like something additional thing that could be included in a project. A quick NPM search discovers a little-used library, [`json-to-form-data`](https://www.npmjs.com/package/json-to-form-data), for example. The fact that it doesn't get much use might be meaningful.

**Comment by tmaclean-LV** [comment]
Not sure if this is the best solution for everyone on here, but assuming you haven't built a wizard form, you can just grab the fields off the DOM. That way you never have to worry about the JSON equivalents. This is especially great for multipart forms i.e. file fields. 

```javascript
const onSubmit = () => {
	const formData = new FormData(document.getElementById('my-form'));
	fetch('http://localhost:8000/my-script', {
		method: 'POST',
		body: formData
	});
};
//...
<MyForm onSubmit={onSubmit} />
//...
class MyForm extends Component {
	static propTypes = {
		handleSubmit: PropTypes.func
	};
	render() {
		return (
			<form onSubmit={this.props.handleSubmit} encType="multipart/form-data" id="my-form">
				<Field label="Name" name="name" component={input} type="text" />
				<Field label="Attachments" name="attachments" component={input} type="file" multiple value={undefined} />
				<button type="submit">Submit</button>
			</form>
		);
	}
}
```

**Comment by SampsonCrowley** [comment]
I just wanted to add on to @tmaclean-LV with what I did to make sure all reduxForm fields were included: (where file is the file field param so it doesn't get overwritten)

```js
const paramsToFormData = (data, params, preceding = '') => {
  for(let [k,v] of Object.entries(params)){
    if(v instanceof Object && v.constructor === Object){
      data = paramsToFormData(data, v, `${preceding}${k}.`)
    } else {
      data.set(`${preceding}${k}`, v)
    }
  }
  return data
}
onSubmit = async ({file, ...params}) => {
  let data = new FormData(document.getElementById('my-form'))
  data = paramsToFormData(data, params, "")
  console.log(data)
}
```

**Comment by gregorskii** [comment]
I did this:

```
export const convertToFormData = (fields) => {
  if (fields) {
    const form_data = new FormData();

    for (var key in fields) {
      if (key === 'file') {
        form_data.append(key, fields[key][0]);
      } else {
        form_data.append(key, fields[key]);
      }
    }

    return form_data;
  }
};
```

Then Axios picks up on the formData object perfectly.
