### ISSUE TITLE
How to startSubmit with formKey and without promise?

### ISSUE THREAD

**Issue by eyaleizenberg** [erikras/redux-form#738]
I have a form called 'comment'. You can either create comments or edit them. Since they all appear on screen, I am use the formKey prop passing either the comment's id when editing or 'newComment' when creating a new comment. Everything works great except for 1 thing - the `submitting` prop.

I am using the `handleSubmit` with `onSubmit` as documented, however my `onSubmit` function doesn't return a promise, I am firing an action which in it's callback passes the data to my reducer.

In my action, right before sending the data to the server, I am using the `startSubmit` method from the redux-form: `dispatch(startSubmit('comment'))`. This however, sets the `submitting` prop on the master comment form state and not on the correct 'sub form' ('newComment' or by the comment's id).

The way I see it there are several solutions here:
1. Switch to promises (something I don't want to do).
2. Change the reduxForm method's `form` key to something dynamic and then use startSubmit with that specific value.
3. Something else I haven't thought of...

I could really use some help here.

Thanks!

**Comment by eyaleizenberg** [comment]
SOLVED! In my `reduxForm` method I needed to omit `form` and then pass that as a prop.

Is this the best way to do this or is there something else?

Thanks.

**Comment by erikras** [comment]
Yes. I need to mark `formKey` as deprecated. You are doing it correctly. :+1:

**Comment by eyaleizenberg** [comment]
@erikras Thanks for your feedback. Just out of curiosity, what does the `key` attribute represent in the form reset event?

<img width="214" alt="screen shot 2016-03-15 at 18 51 00" src="https://cloud.githubusercontent.com/assets/1061345/13786139/03a9f254-eadf-11e5-8874-65eef19b62d7.png">

**Comment by erikras** [comment]
That's the `formKey`, for resetting a keyed form.
