### ISSUE TITLE
Support :invalid pseudoclass on form inputs

### ISSUE THREAD

**Issue by marr** [erikras/redux-form#739]
Hi, I was wondering if there is planned support for the :invalid pseudo-class on invalid form inputs. I'd like a way to not have to dynamically add classes to my input when they have an error, since this is a browser supported feature already (https://developer.mozilla.org/en-US/docs/Web/CSS/:invalid). 

Is this something you plan to support?

Thanks,
Dave

**Comment by erikras** [comment]
Yes, eventually. #254
