### ISSUE TITLE
untouchAll is not defined?

### ISSUE THREAD

**Issue by Bitaru** [erikras/redux-form#74]
Looks like untouchAll is not defined anywhere
https://github.com/erikras/redux-form/blob/2d14c16a70c06f3b1dc153fe0540f85275e5a027/src/reduxForm.js#L276

**Comment by erikras** [comment]
Good catch. :+1:  Typo on my part. Will be fixed soon.

**Comment by Bitaru** [comment]
You are so fast ^^ thx!

**Comment by erikras** [comment]
:runner: :dash: :smile: It's a shame that eslint didn't catch that.

**Comment by erikras** [comment]
Fixed in [v1.6.0](https://github.com/erikras/redux-form/releases/tag/v1.6.0).
