### ISSUE TITLE
Call validate independently of form submission

### ISSUE THREAD

**Issue by anrie** [erikras/redux-form#741]
Hey,

what would be the best way to trigger the synchronous validation independently from actually submitting the form.

I am building a multi step form an before proceeding to the second step I'd like to make sure that certain fields are correctly entered. Hence the idea to reuse my existing validation function.

**Comment by erikras** [comment]
Synchronous validation happens on every render. How would you want to trigger it?

**Comment by davidkpiano** [comment]
Perhaps with an action?

**Comment by erikras** [comment]
> Perhaps with an action?

That doesn't make sense with the current `redux-form` architecture, as the sync validation happens entirely in the component, which does not receive actions. The component is given `this.props.errors` with the results of the sync validation on every render.

**Comment by davidkpiano** [comment]
Might be a good consideration for v5. Keeps component logic simple.

**Comment by anrie** [comment]
My idea was to trigger the validation when a link or a button is pressed and to proceed to the next step only *after* the validation of the fields passed.

So I basically just have to force a rerender and the errors dict should be populated so that I can display the errors like in the synchronous validation example?

**Comment by erikras** [comment]
@anrie It sounds a little like [a wizard form](http://redux-form.com/4.2.0/#/examples/wizard).

**Comment by erikras** [comment]
> Might be a good consideration for v5. Keeps component logic simple.

@davidkpiano Yep, already in the plans. :-)

**Comment by anrie** [comment]
@erikas I'd say it looks pretty much like the wizard form.
Sorry for the noise and thanks for the great library!

**Comment by anaibol** [comment]
Hi! Is this possible in v6? I have a wizard form with multiple steps on the same redux form component. Could I validate each field separately?
Thanks!

**Comment by MaxInMoon** [comment]
@anaibol did you find a way?

**Comment by anaibol** [comment]
@MaxInMoon I don't think so, I used https://github.com/davidkpiano/react-redux-form that uses another approach.
