### ISSUE TITLE
Async validation does not fire with initial values

### ISSUE THREAD

**Issue by VladShcherbin** [erikras/redux-form#742]
Hey, seems like I have the same [issue](https://github.com/erikras/redux-form/issues/614) when async function is not called with initial values.

What am I doing:
I've got a simple form with 3 fields:
- input text
- checkbox
- dropzone (with input inside)

The checkbox has an initial value. The onBlur won't trigger the async validation until I change the value in one of the fields. As in the issue above, [this line](https://github.com/erikras/redux-form/blob/master/src/createHigherOrderComponent.js#L78) is probably causing this.

Is there any fix?

**Comment by jeromebridge** [comment]
I am trying to run validations (at least the async validation) on the initial values of the form when it first comes up.  Is this possible or maybe there is a recommend way to run the async service when the form first comes up?

**Comment by erikras** [comment]
That line is assuming that you would not initialize your form with values that fail async validation. Can you tell me more about your use case? If you just need to do a "required" validation on one of the other fields if the checkbox is checked, that could be done with sync validation, no?

**Comment by jeromebridge** [comment]
The user is entering a new transaction on the page.  I would like the input of the user to be "quoted" while they are entering data on the form as soon as the minimum input is entered by the user.

In some cases the "Initial Values" may be enough minimum input to quote the transaction and sometimes it may not.  I was thinking I would like the redux-form validations to determine if the initial values are adequate to do an initial quote when the user first opens the transaction input page and then do the quote if it is enough input to do the quote.

Maybe there is a better way to approach the problem.  BTW...the [React Redux Example](https://github.com/erikras/react-redux-universal-hot-example) you did is fantastic!!

**Comment by VladShcherbin** [comment]
@erikras if I remember correct, I wanted to validate the file's (image) width & height, so I needed to use async FileReader. I wanted to wrap it in validation rule.

When I was using dropzone and onDrop event, I used **field.onChange**, but it didn't trigger the async validation.

I solved it by moving this image validation into the Dropzone component (to check and only then to call field.onChange), but I can probably reproduce my issue.

**Comment by jeromebridge** [comment]
I am trying to run validations (at least the async validation) on the initial values of the form when it first comes up.  Is this possible or maybe there is a recommend way to run the async service when the form first comes up?

**Comment by tomduncalf** [comment]
My PR for an `alwaysAsyncValidate` option has just been merged, so should be in the next release and should solve your issue: https://github.com/tomduncalf/redux-form/blob/0aaceba223e045b167a0cdd9d563c65a160f3dcd/docs/api/ReduxForm.md#-alwaysasyncvalidate--boolean-optional

**Comment by VladShcherbin** [comment]
@tomduncalf great news! I think, we can close the issue now.

**Comment by erikras** [comment]
Published @tomduncalf's PR as [`v5.2.3`](https://github.com/erikras/redux-form/releases/tag/v5.2.3).

**Comment by VladShcherbin** [comment]
@erikras great, will try it in the next v6 version. Thank you!

**Comment by ssilve1989** [comment]
`alwaysAsyncValidate` does not seem to solve the issue of running async validation on the initial values. For example, I have a field for an authorization token where there is an async validation call to validate the token. However the token can be populated as an initial value if provided in the URL query parameters. Async validation does not seem to be working when it is an initial value
