### ISSUE TITLE
How to setValue of an exiting field when doing an addField() or removeField() in deep form

### ISSUE THREAD

**Issue by narendrp** [erikras/redux-form#745]
I need to changes the value of a field  when I try to addField() or removeField()

**Comment by erikras** [comment]
Sounds like something that is not currently supported, but if you could provide some more code, that'd be helpful.

**Comment by narendrp** [comment]
I want to do something like below where the global.names value is changes when we do addField() or removeField()

```
 <input type={text} {...global.names}/>
  <button type="button"  onClick={() => {
                                                user.addField();  
                                                global.names.value =  difference(defaultInitialNames, Array.splice(global.names.split(','), 0, 2)).join(',')
                                              }}>
                                    </button>
       { users.map((user) => 
        <input type={text} {...user.name}/>
        <input type={text} {...user.age/>
       }
```

**Comment by 592da** [comment]
![image](https://cloud.githubusercontent.com/assets/5786203/13851464/ff366bb0-ec66-11e5-9bff-25f503ff4d52.png)

I think I am dealing with same issue here...
I have on field (marked in blue) that catch onchange event and change other fields values (marked on yellow)

I know it's wrong, but I tried this and it didn't even worked.
```js
              onChange={(val) => {
                if (constTimeRanges[val]) {
                  timeRange.start.value = constTimeRanges[val][0]
                  timeRange.end.value = constTimeRanges[val][1]
                }
              }}
```

is there a way to dispatch some action for this \ call a function that will change other fields values ? Thanks.

**Comment by 592da** [comment]
I solved my issue with field.onChange('value-i-want-to-set')

**Comment by narendrp** [comment]
Thank you @592da it worked. Though I am not sure if it is the correct way to do it..
