### ISSUE TITLE
Add an auto-complete example?

### ISSUE THREAD

**Issue by robomc** [erikras/redux-form#746]
Form fields with (usually async) auto-suggestions are a pretty common feature, and non-obvious to wire up in redux-form.

Some version of this in the examples list would have saved me 4 hours and counting today  :person_frowning:

**Comment by felipeleusin** [comment]
Yeah, I pretty much gave up and just worked around redux-form. I have an autocomplete component that has it's own state (honestly, very little reason for autocomplete to use redux) and it triggers the onChange on redux when a option is selected

**Comment by ptim** [comment]
this issue may be of interest to folk who come after: https://github.com/erikras/redux-form/issues/106#issuecomment-145509415
