### ISSUE TITLE
Why form is not 'dirty' after adding/removing object in array?

### ISSUE THREAD

**Issue by olegkalyta** [erikras/redux-form#749]
I need to save added objects in array & be able to save state, if objects were deleted from array.
In other words, i try to accomplish this behavior:
1. I have initialised array with 1 object inside
2. After adding, removing any objects in this array, i expect to have **dirty** form, but it is not. 

Please check gist with this example:
https://gist.github.com/olegkalyta/f6623b5c645c22581650

**Comment by clayne11** [comment]
Shallow equality cannot detect when you change an element inside an array. You need to return a new array without the element you want to remove rather than mutating the existing array.

**Comment by olegkalyta** [comment]
You mean, explicitly mutate state in my own handle array methods and do not use 
    
    formReducer.plugin 'redux-form/ADD_ARRAY_VALUE' ?

**Comment by olegkalyta** [comment]
In my gist, i use standard methods for adding/removing array elements and i thought, they should return new arrays to change form status to **dirty**.
Anyway, as @clayne11 adviced, i manually return new arrays in plugin, but it still does not work for me.
https://gist.github.com/olegkalyta/d3a1f8e120576add7e55

@erikras is there some sort of best practise for such task?

**Comment by erikras** [comment]
This is unfortunately a known bug (#391, #484) that is being taken into consideration for the next version, but for now, I'm afraid you're going to have to do array `length` checks yourself.

**Comment by skormos** [comment]
+1 for this being implemented. WRT to form dirtiness, if I touch a field, the form is dirty, so why not apply the same at the form level? If I touch the form by adding or removing fields, the form itself should be dirty.

**Comment by ooflorent** [comment]
Please continue the discussion in #391.
