### ISSUE TITLE
Async validation requires a 'valid' attribute?

### ISSUE THREAD

**Issue by yoo2001818** [erikras/redux-form#75]
I was trying to use async validation, but I'm not able to submit the form due to unknown reason.

It turns out that returning an empty object isn't accepted as a valid form.
```js
function validateContactAsync(data, dispatch) {
  // This doesn't validate the form!
  return Promise.resolve({});
}
```

I looked at the redux-form's code and found that isAsyncValid() function only looks at the 'valid' attribute of returned object, unlike isValid() function.
Which means, this works:
```js
function validateContactAsync(data, dispatch) {
  // This does validate the form.
  return Promise.resolve({valid: true});
}
```

Is this an expected behavior? I think sync / async form validation acting differently is wrong.

**Comment by yoo2001818** [comment]
I wrote a simple fix to resolve this problem. This makes async validation act like sync validation.
By the way, I think there are no tests for async validation.

**Comment by erikras** [comment]
Thanks for this. It was a legit bug, and also some wrong-headed thinking on my part. All the validation methods used to allow a `valid` flag to short-circuit the looping of the errors (#21), but the data structure has changed since then, and that was a vestigial remnant.

**Comment by yoo2001818** [comment]
No problem! :)
