### ISSUE TITLE
Ignoring certain validation rules at final submit

### ISSUE THREAD

**Issue by rasmuswoelk** [erikras/redux-form#751]
Hi

I'm creating a checkout form where I "password" and "password again" fields among a lot of other fields of course. When the user type in an email, the form will show a password field only and upon sign in the form will reinitialize with the users own values from his/her account. (I'm not using Redux Form to submit here - just a simple onClick function that send a post request to my server and then reload the user-reducer).

However if the user wants to create an account then I show the before mentioned "password" and "password again" fields.

The problem is that I have both password and password again in the validation function and it will try to validate both fields - even if the user is signed in to an account and these field aren't to be found in the form.

The question is: Can I ignore some validation rules upon submit when the user is signed in? But still use the validation rules when the user decides to create an account? And also can I add my own custom validation error from within my component somewhere (not asyncvalidation).

Screenshot of form: 
https://www.dropbox.com/s/yx48mnbz6rxnvit/Sk%C3%A6rmbillede%202016-03-18%2013.06.16.png?dl=0

I love Redux Form and hope you can provide a solution or work-around for this. If this isn't the appropriate place for such question then you can just close the issue :-)

**Comment by erikras** [comment]
The sync validation function is given the entire record. Could you not include a "sign in" or "sign up" mode somewhere in the form values to check when doing the validation?

**Comment by rasmuswoelk** [comment]
Alright :) Thanks for your answer!

I guess I could check if the signed_in key in my user-reducer is equal to "true" and then make it so that it doesn't validate the password-fields.

The problem is that the validator function is outside my component so I can't seem to update it based on the changing value in the user reducer. 

This might just be me that doesn't know how to get the updated state outside my component. Or is it possible to move the validation function inside my component?

**Comment by rasmuswoelk** [comment]
Ah I get your answer now. I could add a "signedin" field to my fields which I can update with a value from within my component and then check in the validator if it is set or not. That's definitely a solution!
