### ISSUE TITLE
Async validation does not triggering submit

### ISSUE THREAD

**Issue by gbrlsepulveda** [erikras/redux-form#752]
Hello,
i was trying to do a submit with async validation, but it's not working. Async validation is working, but submit is not being triggered.

Inspecting the code, my function return a promise resolved, but submit is not being called.

I don't know if is something that i could be doing wrong.

That's the code

``` javascript
export const validateAsyncFields = (values) => {
  return new Promise((resolve, reject) => {
    let field = asyncFields.filter(x => values[x] ? x : false);

    if (!field.length) {
      resolve();
    } else {
      field = field[0];

      const phoneNumber = values[field].replace(/\D/g, '');
      const type = 'cellphone';

      let invalidFields = {}
      invalidFields[field] = '* invalid';

      const areaCode = phoneNumber.slice(0, 2);
      const number = phoneNumber.slice(2);

      Request.validatePhoneNumber({
        type,
        areaCode,
        number
      }, () => resolve())
      .fail(() => reject(invalidFields));
    }
  });
};
```

**Comment by gustavohenke** [comment]
In v6, you specify your async validation function as `asyncValidate` option of the `reduxForm` HOC, [as documented here](http://redux-form.com/6.3.1/docs/api/ReduxForm.md/).

If you submit that form, it will first trigger your async validation *again*, then it'll take turn.

Let me know if your issue was something else.

**Comment by geminiyellow** [comment]
hmm, same problem, redux-form 7.x . @gbrlsepulveda did you fix it?

**Comment by emanuellarini** [comment]
Got this problem too. 7.0.3 here
