### ISSUE TITLE
Unable to simulate/trigger an onChange event

### ISSUE THREAD

**Issue by wmyers** [erikras/redux-form#755]
I'm probably failing to grasp something obvious, but I'm unable to programatically trigger the onChange method of a redux-form props object, destructured into an `input`. I can only trigger the change event with a physical click.

This could be nothing to do with redux-form but thought I should ask.

I want to programatically trigger a `change` event on a radio-button that is hidden and will cause the visible ones in the group to deselect, and will update the redux-form state value accordingly. 

I'm currently using techniques like:
```
const elem = this.refs.hiddenRadioButton;
const event = new Event('change', {
        'view': window,
        'bubbles': true,
        'cancelable': true
      });
elem.dispatchEvent(event);
```

**Comment by erikras** [comment]
If your radio button is a "field", you can just call
```js
this.props.field.myRadio.onChange('newValue')
```
Is there something more complicated about your scenario?

**Comment by wmyers** [comment]
That fixed it! Thank you very much, and for this library generally.

I also found your comments here useful:
https://github.com/erikras/redux-form/blob/master/src/events/getValue.js#L36

The only additional complexity is that I am triggering this `onChange` inside a `componentWillReceiveProps` handler in a child component, in response to a parent redux-form component UI state change.

As `componentWillReceiveProps` is fired multiple times I have an extra condition to make sure the `onChange` only gets fired once:
```
componentWillReceiveProps(nextProps) {
    if (nextProps.isTimeToClearMyRadioButtons) {
      if (nextProps.reduxFormRadioField.value !== 'radioDeselector') {
        nextProps.reduxFormRadioField.onChange({value: 'radioDeselector'});
      }
    }
  }
```

**Comment by abidibo** [comment]
Hi,
what about triggering the onChange event but with alpha.6 version? No fields props are available here, and I can't find a way to get the field param passed to the component function of the Field component, I'm trying to fire it programmatically for testing purposes

    it('Should show fleetId field if role is changed to fleet*', function () {
      let fields = TestUtils.scryRenderedComponentsWithType(_rendered, Field)
      expect(fields.length).equal(2)
      // I need to trigger onChange on fields[1] here
      fields = TestUtils.scryRenderedComponentsWithType(_rendered, Field)
      expect(fields.length).equal(3)
    })
`

The onChange function of `fields[1]` changes the local state of the component, hiding/showing one field depending on the selected value.
