### ISSUE TITLE
array, params return is string with commas

### ISSUE THREAD

**Issue by dieuit07** [erikras/redux-form#757]
My config:
```
fields: [..... , "phones[]"]
```

Render form:
```
        <div>
          <button type="button" onClick={event => {
            event.preventDefault()
            phones.addField()
          }}><i/> Add Phone
          </button>
        </div>
        {phones.map((phone, index) =>
          <div key={index}>
            <label>Phone #{index + 1}</label>
            <div>
              <Input type="text" placeholder="Phone" value={phone.value} onChange={phone.onChange} title={phone.error}/>
            </div>
          </div>
        )}

```

I add 3 phone number: 111, 222, 333. then submit
params return : "phones"=>"111,222,333"

How could I config it to return an array params?  example: "phones" => ["111", "222", "333"]

**Comment by ooflorent** [comment]
Hi, thanks for coming by.

Please use StackOverflow for usage questions. This is the only way to ensure the same question doesn’t get asked many times in a row, and that folks who have the same question in the future will be able to find it. (Github search is pretty much useless.)

Sorry we couldn’t answer your question here. Please feel free to post a link to the StackOverflow question, and I’ll be happy to try to answer it.
