### ISSUE TITLE
Add id to fields?

### ISSUE THREAD

**Issue by Kerumen** [erikras/redux-form#758]
I have an array of fields with custom state that I want to remove or add. Each field has a component with an internal state. I use the index of the array for the key but if I remove a field, the internal state is messed up.

I'm iterating like this (simplified): 

``` js
{child.map((field, index) => <Autocomplete key={index} field={field} />)}
```

And my Autocomplete component has an internal state changing as the user type.

I have 2 rows: I remove the index 0, the index 1 become the index 0. And the Autocomplete state of the new index 0 get the state of the old index 0 because of the same key.

I thought a lot on how to solve this on my own (I could add ids to each child but I don't wanna touch the field component directly) but didn't manage to find a solution.
So maybe adding custom ids to fields would solve this problem?

**Comment by erikras** [comment]
Hmm... You're suggesting that each field be given a unique id when it is generated?

That's an interesting idea I hadn't considered.

**Comment by Kerumen** [comment]
Yes that's it!

**Comment by xc2** [comment]
+1, and I wonder if I can specific a unique and fixed id to a field when I call `addField`, thus I could make it possible when I typed an `a` in an empty row, then the `a` was added into the array field, the focused row, meanwhile,  keeped focused.

Just like this mockup:
![new mockup 1](https://cloud.githubusercontent.com/assets/18117084/14549757/6f749b14-02f5-11e6-9a01-81a190a22213.png)

**Comment by erikras** [comment]
@xc2 Wow! That's an impressive flow diagram! Interesting, but nonintuitive to me, UI about allowing inputs around whichever input has focus. Yes, having each field have its own unique id will help with that.

I've already coded that into the `v6` rewrite that is coming soonish. (< month ?)

**Comment by davidkpiano** [comment]
@erikras How is the unique ID determined per field? I might be able to offer some insight about this.

**Comment by erikras** [comment]
I was just going to generate them as the Field components are mounted. That seemed sufficient, but I'm open to better ideas.

**Comment by davidkpiano** [comment]
In RRF, one can specify the `model` or a `modelGetter`, which is any function that returns the model given the state (e.g. the entire form model). With that, you can replicate Angular's `track by` concept. For example...

```js
const getBillyModel = ({ users }) => {
  const index = users.findIndex((user) => user.id === 'Billy');

  return `users.${index}`; // e.g. "users.3"
}

// This will basically call:
// getBillyModel(store.getState())
<Field model={getBillyModel}>
```

With lodash and helper functions, it can be simplified:

```js
<Field model={track('users', {id: 'Billy'})}>
```

This way, the model (which is the true location of the piece of state) can be dynamically computed, without having the reference lost, regardless of if an array is shuffled or modified, or even mutated.

**Comment by erikras** [comment]
@davidkpiano I'm confused as to where `'Billy'` is coming from.

**Comment by davidkpiano** [comment]
Let's say you have an array of users:

```js
[
  { id: 'Bob', age: 23 },
  { id: 'Billy', age: 34 },
]
```

and you want your model to track the item where `user.id == 'Billy'`.

**Comment by erikras** [comment]
Sure, but this is sort of a non-issue if your array items already have a unique identifier, is it not?

**Comment by hdmsoftware** [comment]
Has something like this ever been implemented ?
Right now in the field array example we have something like
`const renderHobbies = ({ fields, meta: { error } }) => (
  <ul>
    <li>
      <button type="button" onClick={() => fields.push()}>Add Hobby</button>
    </li>
    {fields.map((hobby, index) =>
      <li key={index}>
        <button
          type="button"
          title="Remove Hobby"
          onClick={() => fields.remove(index)}/>
        <Field
          name={hobby}
          type="text"
          component={renderField}
          label={`Hobby #${index + 1}`}/>
      </li>
    )}
    {error && <li className="error">{error}</li>}
  </ul>
)`

This generates something like hobbies:[hobby1,hobby2]...I would like to have an option to have something like hobbies:[{id:1, name:hobby1}, {id:2, name:hobby2}].

Is there a way to do something like this ?
Thanks

**Comment by dannybit** [comment]
I would also like this feature. I am having problems with react drag and drop.

**Comment by hdmsoftware** [comment]
It is actually fairly easy to add ids. I did it like this

handleAddClick(){
    this.props.fields.push({
                id:uuid.v4(), 
                name:'A new name', 
                description:'A new description'
              });
  };

I hope this helps someone

**Comment by pappasam** [comment]
@hdmsoftware you just saved us a lot of headache, thank you for this.

**Comment by danielrob** [comment]
This thread appears to have died/lost clarity. Doing a code search, I couldn't find that any id generation that ultimately made it in (let me know if I missed something).

Is there anyone who can provide either:
 - a case where adding (uu)ids to your model data is insufficient? 
 - a clear description of a built-in id generation that would be useful, including a description of the benefits?

**Comment by danielrob** [comment]
@hdmsoftware that question would fall under #2735 / #1458.

**Comment by danielrob** [comment]
Closing this proposal due to a lack of a clear problem statement. If this is remedied, it can be reconsidered.
