### ISSUE TITLE
Combine with Draft.js?

### ISSUE THREAD

**Issue by newsiberian** [erikras/redux-form#760]
Hello, I want to make a simple form for "Add new comment" component with fields like, user, email and **Draft.js's** [`editorState`](http://facebook.github.io/draft-js/docs/api-reference-editor-state.html#content). Any idea how could I do this?

**Comment by jljorgenson18** [comment]
I haven't played with Draft.js enough to know for sure but couldn't you just pass a redux-form field's onChange handler into the Editor component and set your editorState as the initial value for that field? Redux-form can save objects as values so saving the editorState as the field values "should" work

```javascript
...
  render() {
    const {myField} = this.props.fields;
    return <Editor editorState={myField.value} onChange={myField.onChange} />;
  }

...
```

**Comment by ooflorent** [comment]
This is a usage question, and we encourage you to ask it on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

This is the only way to ensure the same question doesn’t get asked many times in a row, and that folks who have the same question in the future will be able to find it.

I’m closing for these reasons.

**Comment by simpleblack** [comment]
@newsiberian 
I think that solution.
combine with react-rte
that link https://github.com/sstur/react-rte

**Comment by andrewmclagan** [comment]
Hmm react-rte is simply a wrapper around draft-js. Its really simple to implement this in draft. Perhaps I will attempt a docs PR soon to explain how to integrate Draft-js and redux-form v6
