### ISSUE TITLE
Separate error for array fields

### ISSUE THREAD

**Issue by mmakarin** [erikras/redux-form#762]
Hello. I have some complex validation on array field `details[].periods[]` I have to check periods do not overlap and display the error message if they do. I can't determine which period is causing the error, so I have to set this error for the entire array field. I don't want to set _error field because it's not global form error. There is an `errors` object passed to my form, but it's empty all the time and it's not documented so I can't just grab the error I need and pass it as a prop. Is there any way to do so without creating a faux field just for this error?

**Comment by erikras** [comment]
This is currently not supported, but is on the feature request list. #486

**Comment by ooflorent** [comment]
In closing this issue in favor of #486

**Comment by erikras** [comment]
Good news! Array validation errors in [`v6.0.0-alpha-7`](https://github.com/erikras/redux-form/releases/tag/v6.0.0-alpha.7).
