### ISSUE TITLE
Help need with integration React widget MultiSelect with Redux form

### ISSUE THREAD

**Issue by narendrp** [erikras/redux-form#765]
I am trying to integrate React MultiSelect widget. please see my sample code below.
that,props.fields.userIds does not have onChange gives error as onChange method is not present.

Please advice if I am doing something wrong

    const fields=[
       'userIds[]'
     ];                  

    render() {
        const {
                fields: {
                  userIds
                },
           ......
            } = this.props;

      <form>
      <div className="col-sm-8">
                            <Multiselect
                                name={fields.userIds}
                                field={userIds}
                                valueField='id'
                                textField='name'
                                data={userMap}
                                defaultValue={pluck(userMap, 'id')}
                                onChange = {val => {that.props.fields.userIds.onChange(val)}}
                            />
                        </div>
     </form>

**Comment by narendrp** [comment]
I aslo tries to wrap in a custom component but I think I am missing something. 

_import React, {Component} from 'react';
import Multiselect from 'react-widgets/lib/Multiselect';

class MultiselectInput extends Component{

    constructor(props){
        super(props);
        this._change = this._change.bind(this);
        this.state = {
            val: this.props.defaultValue || []
        }
    }


    _change(val) {
        this.setState({
            val
        });
        this.props.onChange(val);
    }


    render() {
        const that = this;
        debugger
        return (
            <Multiselect
                {...this.props}
                value={this.state.val}
                onChange={this._change}
            />
        )
    }
};

export default MultiselectInput;_

**Comment by narendrp** [comment]
I am declaring userIds[] as an array but the I cannot use userIds.onChange as it is not a field.. What is the approach that needs to be taken when trying to implement custom component on fields with array of values. Thanks in advance for your valuable inputs

**Comment by ooflorent** [comment]
Hi, thanks for coming by.

Please use StackOverflow for usage questions. This is the only way to ensure the same question doesn’t get asked many times in a row, and that folks who have the same question in the future will be able to find it. (Github search is pretty much useless.)

Sorry we couldn’t answer your question here. Please feel free to post a link to the StackOverflow question, and I’ll be happy to try to answer it.
