### ISSUE TITLE
field.onBlur not triggering asyncValidate

### ISSUE THREAD

**Issue by thomasmery** [erikras/redux-form#766]
Hi,

I'm trying to programmatically `blur` a field and subsequently trigger the asyncValidate function I set for the form

it all works well when manually tabbing out of the field

but calling

`myField.onBlur(value)`

changes the field value but does not trigger the asyncValidate function

also it does not seem that the field gets '`touched`' when using `onBlur`

I probably misunderstand some of the concepts but any help would be great

thanks

**Comment by gustavohenke** [comment]
I suppose you were using v5 at the time. Can you check whether the recently released v5.3.4 fixes your problem?

v6 is working properly: https://jsfiddle.net/gustavohenke/uvvsnsfz/
