### ISSUE TITLE
Passing options to onSubmit?

### ISSUE THREAD

**Issue by madshargreave** [erikras/redux-form#767]
Hi

I have a form where the user can either 'Send' or 'Send & Archive' a conversation.

I was to bind an 'archive' flag to the onSubmit callback when the user clicks the Send & Archive, but the parameters are overwritten by the formvalues provided by ReduxForm

How can this be accomplished?

**Comment by erikras** [comment]
How's this?
```js
const makeSender = archive =>
  (values, dispatch) => {
    dispatch(send({
      ...values,
      archive
    }))
  }
}

<button onClick={handleSubmit(makeSender(false))}>Send</button>
<button onClick={handleSubmit(makeSender(true))}>Send & Archive</button>
```
