### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by jean-Phil** [erikras/redux-form#768]
Hello Erik,

I apologize in advance: **this should not be an issue, but a request for help**, however I don't know how else to get in touch with you.

I've managed to build a simple two-page app ( list and form view ) which would do what I intended it to.  However, I am experiencing difficulties with action calls having undesired effects, and I've really spent too much time trying to debug this...  I've reached the stage where I need someone more experienced to look at my code and provide guidance...

Between _@@router/LOCATION_CHANGE_ and _redux-form/DESTROY_ action calls, I am getting  **'Uncaught TypeError: Cannot read property 'type' of undefined'** and I don't seem to be able to fix this. I've searched for similar issues [ eg. https://github.com/reactjs/react-router-redux/issues/182](https://github.com/reactjs/react-router-redux/issues/182) but cannot wrap my head around the problem.  

I am obviously more than willing to compensate you for your time. Please let me know if you could find time to help me solve this.  _I believe an hour may be sufficient._

Thank you in advance!

JP

**Comment by erikras** [comment]
Unfortunately, I don't have near the experience that I'd like to have with `react-router-redux`, as I have not yet found the time to integrate it into my project(s). You need to isolate exactly where the error is occurring, with an exception breakpoint or a sprinkling of console logs. My guess is that it's somewhere in the `react-router-redux` middleware, where somehow an `undefined` action is getting dispatched.

That's about all I can tell you without seeing (and running) your source code.

**Comment by jean-Phil** [comment]
Thank you Erik!  
I would have a few questions regarding redux-form as well.  Would you be available for a quick guidance session?  

If so, please let me know how I can get in touch with you. _My email is on my github homepage, would you want to reach me._

Thank you!

**Comment by jljorgenson18** [comment]
I'm using react-router-redux and redux-form and haven't had any issues yet. Feel free to post a snippet of the form and maybe I can help

**Comment by jean-Phil** [comment]
Thank you, Jesse!  I really appreciate you stepping forth. 

I've uploaded the code to [https://github.com/jean-Phil/redux-form-navig-issue/](https://github.com/jean-Phil/redux-form-navig-issue/), and put my goals and the bugs I encounter in the readme file.

**Comment by erikras** [comment]
When I fill out the required fields and hit "Submit", I'm getting this.
![localhost 3000 formundefined _k 43d2xd6 2016-03-28 17-27-31](https://cloud.githubusercontent.com/assets/4396759/14081327/82a687c2-f50a-11e5-8d77-49555eabf760.jpg)

**Comment by jean-Phil** [comment]
Hello Erik,  Thank you for having a look already. 

The message part of state is not fully implemented yet.  For now, I've pushed a new version, to solidify and clarify that part of the updateMessages fn.  It did not seem to throw on my end.

**Comment by erikras** [comment]
Okay, now I'm not seeing any exceptions. It's dispatching `ADD_UNSAVED_CHANGES`, but no `react-router-redux` actions. Perhaps record a little screencast of how you are recreating it?

**Comment by jean-Phil** [comment]
At this point, it is not navigating automatically back to the **/list** route.  If you want to recreate navigation on your end, you must first clear away the "undefined" from the url, and a button will appear, allowing you to navigate to the other view.  
```
eg.

FROM events-list-and-form/client/index.html#/formundefined?_k=43d2xd6
TO events-list-and-form/client/index.html#/form?_k=43d2xd6

or

FROM events-list-and-form/client/index.html#/listundefined?_k=43d2xd6
TO events-list-and-form/client/index.html#/list?_k=43d2xd6

```

**Comment by jljorgenson18** [comment]
So a few things.

1. If you want to use the react-route-redux actions, you need to add the routerMiddleware. This allows the dispatched history actions to actually change the history

```
const finalCreateStore = applyMiddleware(
    thunk,
    routerMiddleware(hashHistory)
)(createStore);
```

2. The actual actions you are trying to dispatch can just be grabbed directly from the react-router-redux module. For example, you can get the "push" action

``const {push} = require("react-router-redux");``

And then dispatch it. For sake of debugging, try doing the simple case of transition without query or state

``dispatch(push("/form"));``

You do not need to reference the actual history object to dispatch the action with the newest version of react-router-redux.

**Comment by jean-Phil** [comment]
That did the trick, indeed! ... and now initialization and form destruction seem to work fine as well.
_Thanks so much to you both!_
Erik, is it relevant to keep the code up or should I get rid of the repo I just created? Thank you for sharing that library.  It's very well thought out and I've learned a great deal from your code. 
Cheers!

**Comment by erikras** [comment]
You can :skull: it. Glad we could help. Happy coding!

**Comment by jljorgenson18** [comment]
Glad to help and glad its working
