### ISSUE TITLE
Add react-native TextInput support

### ISSUE THREAD

**Issue by mattiamanzati** [erikras/redux-form#77]
In order to add react-native TextInput support I added this snippet here

https://github.com/erikras/redux-form/blob/master/src/reduxForm.js#L32

  if(!(event.nativeEvent === undefined)){
    return event.nativeEvent.text;
  }

**Comment by vkrol** [comment]
This is wrong. For "blur" event event.nativeEvent.text returns undefined https://goo.gl/Bmhd58

**Comment by erikras** [comment]
@vkrol See #80.

**Comment by vkrol** [comment]
@erikras this is the "input" event - https://goo.gl/snO0GB It is definitely a bug.

**Comment by erikras** [comment]
Okay, so what should it be? I don't have any experience with RN.

**Comment by mattiamanzati** [comment]
Maybe this would be better

if(!(event.nativeEvent === undefined || event.nativeEvent.text === undefined)){
return event.nativeEvent.text;
}

**Comment by vkrol** [comment]
@erikras Sorry. This is in the browser, not in RN. I should have said this before.

**Comment by erikras** [comment]
Oh, I see. `nativeEvent` is not `undefined` in the browser, which this change assumed. Got it.

**Comment by vkrol** [comment]
I have a bad news. I found the new bug - this is the "input" event https://goo.gl/hNha7W.

**Comment by erikras** [comment]
Thanks, @vkrol. You're on a roll today! :-)

**Comment by vkrol** [comment]
You're welcome :)
