### ISSUE TITLE
[Enhancement] Form submission count.

### ISSUE THREAD

**Issue by JosephShering** [erikras/redux-form#771]
It would be nice to have a variable in the form props that told me how many times the form submitted. That way, if I have a button, it can be grey when pristine, blue when valid and submittable, or green after it successfully submitted. Checking against `this.props.submitFailed` could also allow me to display red.

**Comment by erikras** [comment]
Interesting idea. Thanks.

**Comment by gustavohenke** [comment]
Closing because this is feature is trivial enough to be implemented in user-land.
Also, it's the least recently updated issue of our repo, what means... there's no demand for it.
