### ISSUE TITLE
Previewing form in Modal from 'react-bootstrap'

### ISSUE THREAD

**Issue by 2easy** [erikras/redux-form#772]
Hi, is there a way to stop automatic destroy action on unmount? I've got specific use case, where user can preview his cart in a modal (using react-bootstrap) like this:

`<Modal show={showCart} onHide={toggleShowCart}><CartFrom /><Modal>`

But when modal hides, `redux-form/DESTROY` gets triggered and user looses all items.

**Comment by mattiamanzati** [comment]
Hi! You can pass "destroyOnUnmount={false}" to your Form component to avoid form state loss whenever the component gets unmounted!

**Comment by ooflorent** [comment]
Hi, thanks for coming by.

Please use StackOverflow for usage questions. This is the only way to ensure the same question doesn’t get asked many times in a row, and that folks who have the same question in the future will be able to find it. (Github search is pretty much useless.)

Sorry we couldn’t answer your question here. Please feel free to post a link to the StackOverflow question, and I’ll be happy to try to answer it.
