### ISSUE TITLE
onSubmitFailed

### ISSUE THREAD

**Issue by MiMaMuh** [erikras/redux-form#776]
Hi,

it would be great if there were a onSubmitFailed prop like the onSubmit one to handle things like shake the submit button when the validation fails ...

I could do it with 'submitting' and see if it changes from true to false, but it would be more convenient with onSumbitFailed ... Thx!

**Comment by pcgilday** [comment]
You can use the `returnRejectedSubmitPromise` flag, and the approach listed in [this](https://github.com/erikras/redux-form/issues/616#issuecomment-209105697) comment to perform any actions when validation fails.

**Comment by pcgilday** [comment]
@erikras Does it make sense to add an example for how to do this, since it seems to be a common question? I am happy to make the example and submit a PR if you believe it warrants one.

**Comment by MiMaMuh** [comment]
Okay, I got it. But I think it is a little bit cumbersom. It would be much easier and semantic of there would be just a onSubmitFailed prop like the onSubmit one. What so you think?

**Comment by puradox** [comment]
@MiMaMuh I agree that an `onSubmitFailed` prop would be a better approach than the current one.

**Comment by pcgilday** [comment]
@MiMaMuh @puradox I would check out the proposal in #726 and see if any of those changes account for the behavior desired.

**Comment by puradox** [comment]
@pcgilday The only proposal that stood out to me, relating this issue, is his section on Form Submission (10 on #726). He doesn't get too in depth on his planned implementation, but it *could* account for our desired behavior. 

While we are waiting for `v6.0`, I might just start a PR in the meantime for `onSubmitFail`, as it seems simple enough to implement.

**Comment by erikras** [comment]
You guys might be interested in [`v5.1.0`](https://github.com/erikras/redux-form/releases/tag/v5.1.0).
