### ISSUE TITLE
Reset all form errors, or the "touched" prop;

### ISSUE THREAD

**Issue by mauriciosoares** [erikras/redux-form#778]
Hey!

Is there a way I can reset all form errors, and reset the `touched` property to false?

Even if there's no public API for that, is there an easy way I can hack `redux-form` to do so?

Thanks!

**Comment by mauriciosoares** [comment]
damn, I just saw the `untouch` action creator in the docs... I'll close it for now

Thanks!

**Comment by mauriciosoares** [comment]
Indeed the `untouch` property worked like a charm.

**Comment by erikras** [comment]
:+1: I often wonder if anyone uses `untouch` (I never do). Glad to get some feedback like this.
