### ISSUE TITLE
How update field? 

### ISSUE THREAD

**Issue by Xurma2** [erikras/redux-form#779]
If I add delete. That field will be deleted from the database. But how to add it? For specific avatar?

```js
this.props.fields.avatar.updateField({
	uuid: i.uuid.value,
	delete: true
});
```

How update field? 

```js
avatar[]
avatar[].delete
avatar[].uuid
```

And how remove by id

```js
this.props.fields.avatar.removeField({
	uuid: i.uuid.value
});
```

**Comment by ooflorent** [comment]
Hi, thanks for coming by.

Please use StackOverflow for usage questions. This is the only way to ensure the same question doesn’t get asked many times in a row, and that folks who have the same question in the future will be able to find it. (Github search is pretty much useless.)

Sorry we couldn’t answer your question here. Please feel free to post a link to the StackOverflow question, and I’ll be happy to try to answer it.

**Comment by Xurma2** [comment]
@erikras help me pleace. I banned it SO
