### ISSUE TITLE
initialState = {} cleans only data, not DOM fields

### ISSUE THREAD

**Issue by igorsantos07** [erikras/redux-form#780]
I have a form embedded into a `react-bootstrap` Modal component, meaning it's hidden from view but not unmounted. It's used both for creation and edition of entries.
I pass into the form `initialValues={this.state.entry}`. When edit is triggered `this.state.entry` contains the entry data and everything goes fine... However, after editing, if the user triggers creation, setting `this.state.entry = {}` will still display a form with the last entry's data - I was expecting that setting an empty object as initialState would clean it. Finally, although the fields are displayed with information filled in, when submitting the data received is empty.

On modal hide I've also tried calling `this.props.destroyForm()` or `resetForm()` and I see these actions being registered in the console, but it still behaves as above.

**Comment by ooflorent** [comment]
Hi, thanks for coming by.

Please use StackOverflow for usage questions. This is the only way to ensure the same question doesn’t get asked many times in a row, and that folks who have the same question in the future will be able to find it. (Github search is pretty much useless.)

Sorry we couldn’t answer your question here. Please feel free to post a link to the StackOverflow question, and I’ll be happy to try to answer it.

**Comment by igorsantos07** [comment]
Sorry @ooflorent but this is not a question. If you read again you'll notice I'm reporting an unexpected behaviour in the library.

**Comment by ooflorent** [comment]
Actually it is! This is a usage issue. Several people may encounter it and StackOverflow is definitively a more appropriate place to expose your use case. If you submit your question there with a reproducible sample, I'll do my best to answer it. As said previously, you can add the link to your question in this issue to drag my attention at it.

**Comment by igorsantos07** [comment]
Ok, so you'd better start explaining people in your readme what are
questions and what are issues, as I'm too stupid to know notice I'm doing a
usage question when I feel I'm reporting some shit that does not work in
this library as it's expected to work.

Feel free to open a question yourself on SE, because this was fixed by
another release of the library and, furthermore, I'm not even on the
project that depends on this... Thing anymore.

Good luck with your SE-based project, Sir :)

Igor Santos
-- Desenvolvedor Web
[enviado do meu celular]
On 29 Apr 2016 02:59, "Florent Cailhol" <notifications@github.com> wrote:

Actually it is! This is a usage issue. Several people may encounter it and
StackOverflow is definitively a more appropriate place to expose your use
case. If you submit your question there with a reproducible sample, I'll do
my best to answer it. As said previously, you can add the link to your
question in this issue to drag my attention at it.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/erikras/redux-form/issues/780#issuecomment-215632968>
