### ISSUE TITLE
[Feature Request] Batch `onChange`

### ISSUE THREAD

**Issue by umidbekkarimov** [erikras/redux-form#781]
I have a form with tons of fields, some of this fields depends to another

Most simple example is address with google autocomplete

```javascript
handleGeoDataChange(value) {
    const {
        untouch,
        fields: {
            geoData,
            businessAddressPostcode,
            businessAddressLine1,
            businessAddressLine2,
            businessAddressTown,
            businessAddressCounty
        }
    } = this.props;

    businessAddressPostcode.onChange(value.postcode);
    businessAddressLine1.onChange(value.addressLine1);
    businessAddressLine2.onChange(value.addressLine2);
    businessAddressTown.onChange(value.town);
    businessAddressCounty.onChange(value.county);

    untouch(
        'businessAddressPostcode',
        'businessAddressLine1',
        'businessAddressLine2',
        'businessAddressTown',
        'businessAddressCounty'
    );

    geoData.onChange(value);
}
```

In this case redux calls 5-6 extra renders on dom, which is not so terrible, but the other example is checkbox group of 90+ items with `All` checkbox above it

```javascript
<Checkbox
    label="All"
    value={fields.length === selectedFields.length}
    onChange={selected => fields.forEach(field => field.onChange({...field.value, selected}))}
 />
```

and it calls 90 + extra calls of render, so i guess you got the idea

Option to update form like that would be just great

```javascript
this.props.batchChange({
    fields: { /* ... new values here ...  */ }
});
```

___

**EDIT:** Provide better example

````javascript
handleGeoDataChange(value) {
    const {
        untouch,
        batchChange
    } = this.props;

    untouch(
        'businessAddressPostcode',
        'businessAddressLine1',
        'businessAddressLine2',
        'businessAddressTown',
        'businessAddressCounty'
    );

    batchChange({
        geoData: value,
        businessAddressPostcode: value.postcode,
        businessAddressLine1: value.addressLine1,
        businessAddressLine2: value.addressLine2,
        businessAddressTown: value.town,
        businessAddressCounty: value.county
    });
}
````

**Comment by erikras** [comment]
Interesting. So passing an object of key-values to `CHANGE` rather than just `field` and `value`.

Excellent idea.

**Comment by umidbekkarimov** [comment]
@erikras what's progress with this?

I got some another idea to solve it - `normalizer` for whole form,
e.g.

```javascript
reduxForm({
    form: 'cool-form',
    normalize(values, prevValues) {
        if (values.geoData !== prevValues.geoData) {
            return {
                ...values, // `values` should be copied, not mutated, or it can be done `redux-form` level
                businessAddressPostcode: value.postcode,
                businessAddressLine1: value.addressLine1,
                businessAddressLine2: value.addressLine2,
                businessAddressTown: value.town,
                businessAddressCounty: value.county
            }
        }        

        return values
    }
})
```

**Comment by umidbekkarimov** [comment]
@erikras is there any progress with this?

Another idea I got to solve this problem - `normalize` whole form
e.g.:

```javascript
reduxForm({
  form: 'my-cool-form',
  normalize(values, prevValues) {
    if (values.geoData !== prevValues.geoData) {
      return {
         ...values, // act like it's reducer, do not mutate
         businessAddressPostcode: geoData.postcode,
         businessAddressLine1: geoData.addressLine1,
         businessAddressLine2: geoData.addressLine2,
         businessAddressTown: geoData.town,
         businessAddressCounty: geoData.county
      }
    }
    return values
  }
})
```

**Comment by erikras** [comment]
I had mostly forgotten about this. (sorry 😳) But every time I think about writing an action to batch other actions, I am reminded that there are middleware libraries out there that do this, and it takes the wind out of my sails.

**Comment by umidbekkarimov** [comment]
> I had mostly forgotten about this. (sorry 😳) 

No problem, sometimes I like when users suffer 😈   and ask me to fix something,

> I am reminded that there are middleware libraries

Can you please tell me more about it? It would be great to control thing from outside

**Comment by erikras** [comment]
> Can you please tell me more about it?

http://lmgtfy.com/?q=redux+batch+middleware 😀

I've never used any of them.

https://github.com/acdlite/redux-batched-updates
https://github.com/mrydengren/redux-batch-middleware
http://jamesknelson.com/can-i-dispatch-multiple-actions-from-redux-action-creators/

**Comment by umidbekkarimov** [comment]
Ok ok ok, it's all about calling multiple actions with one subscribe callback, not so interesting, but you gave me good idea of creating enhancer for redux-form reducer 👍

**Comment by umidbekkarimov** [comment]
So I tried [redux-batched-subscribe](https://github.com/tappleby/redux-batched-subscribe) - and it's resolving issue 👍

@erikras thanks for suggestion, closing.
