### ISSUE TITLE
 _isValueField flag is not accessible from Object.keys

### ISSUE THREAD

**Issue by Msea** [erikras/redux-form#782]
When creating an array field, the field has the _isValueField flag defined here: https://github.com/erikras/redux-form/blob/1a43ff4a9873743232515b081cfa1403e223d05a/src/fieldValue.js#L6 using defineProperty. Because it lacks the enumerable option, it can't be accessed by Object.keys (i.e. because it's Object.defineProperty(object, flag, {value: true}) rather than Object.defineProperty(object, flag, {value: true, enumerable: true})).

I am converting form values to the Immutable.js library. Because this library uses Object.keys under the hood, when it converts array fields they lose the _isValueField flag. And thus the values can't be accessed using the getValues function.

Is there a reason this option isn't supplied? Can it be supplied to enable working with the Immutable.js library?

**Comment by erikras** [comment]
That was a short-sighted (bad) design decision on my part.

`v5`, with estimated (beta) release date of a month from now, has Immutable.js support built in.
