### ISSUE TITLE
Initial value for Material UI checkbox

### ISSUE THREAD

**Issue by genyded** [erikras/redux-form#784]
I have a couple of Material UI Checkboxes on a Redux form and they work fine - except that the initial values are always `undefined`. They look something like this:

```javascript
<Checkbox
  defaultChecked={false}
  checked={ieee.value}
   onCheck={(e, checked) => ieee.onChange(checked)}
/>

<Checkbox
  defaultChecked={true}
  checked=active.value}
  onCheck={(e, checked) => active.onChange(checked)}
/>

```
I also tried setting checked to active.checked and a couple of other things, but no matter what cannot seem to figure out how to get the initial field values to match whether the boxes are checked or not. Once I toggle them by clicking one... the values are fine.

**Comment by genyded** [comment]
Finally figured it out... needed `initialValues: {ieee: true, active: false}` in the form.

**Comment by jasongonzales23** [comment]
Having this issue too, can you please describe a bit more where and how you are setting the initiaValues?

I tried setting it in my container for a route like so:

```
const mapStateToProps = (state) => ({
  NewPatient: state.NewPatient,
  initialValues: {prescribed: true}
})
```

But nothing happens. I suspect that I am just not mapping correctly, but can't really conceive of what the current state is here. For example, the form is an empty object at this point from what I can tell.

TIA!

**Comment by jasongonzales23** [comment]
I figured it out too. I misunderstood where to set these initialValues obviously.

For anyone else having this issue, I set these values in the call to the form like so:

```
NewPatient = reduxForm({
  form: 'NewPatient',
  fields,
  initialValues: {prescribed: true},
  validate
})(NewPatient)
```
