### ISSUE TITLE
How to reset global dirty state?

### ISSUE THREAD

**Issue by max-mykhailenko** [erikras/redux-form#788]
After form submitting (saving) I need to disable save button using `dirty === false`. How I can reset global and individual `dirty` state (reinit form)?

**Comment by erikras** [comment]
You can call `this.props.initializeForm(newValues)` with your new values. Or if you prefer, you can dispatch the action from elsewhere.

```js
import { initialize } from 'redux-form';
...
dispatch(initialize('myForm', newValues))
```

**Comment by java99** [comment]
did try

this.props.dispatch(initialize("positionsConfForm", data, false))

having
