### ISSUE TITLE
React 15 - can't have both value and defaultValue on a textarea

### ISSUE THREAD

**Issue by babsonmatt** [erikras/redux-form#789]
Didn't see an existing issue for this so apologies if this has already been addressed:

`
Warning: Textarea elements must be either controlled or uncontrolled (specify either the value prop, or the defaultValue prop, but not both). Decide between using a controlled or uncontrolled textarea and remove one of these props
`

**Comment by erikras** [comment]
Are you getting this using [`v5.0.0`](https://github.com/erikras/redux-form/releases/tag/v5.0.0)?

**Comment by babsonmatt** [comment]
@erikras yea, v5, sorry for not stating that

**Comment by erikras** [comment]
Thanks. Mistake on my part. Will publish fix soon.

**Comment by babsonmatt** [comment]
np, thanks!

**Comment by erikras** [comment]
Published as [`v5.0.1`](https://github.com/erikras/redux-form/releases/tag/v5.0.1).

**Comment by devangmundhra** [comment]
What is the recommended way of adding a defaultValue now?

**Comment by protoEvangelion** [comment]
@erikras I'm experiencing this error as well but when writing a simple **text input field:**

```jsx
<Field name="company" label="Company Name" defaultValue={company} component={ReduxField} />
```

The `{company}` is just a string of a company and `{ReduxField}` just renders the field.  By the way thanks for creating such an awesome package!
