### ISSUE TITLE
Adding dirty status to the Field , in the redux action / reducer

### ISSUE THREAD

**Issue by raaone7** [erikras/redux-form#791]
How do i over ride the reducer, to include the dirty status. I dont' want to change the redux-form source, so that i can update it. Is there a way to over ride in my app reducer. 

**Source**

```js
 [CHANGE](state, {field, value, touch}) {
    return write(field, previous => {
      const {asyncError, submitError, ...result} = {...previous, value};
      if (touch) {
        result.touched = true;
      }
      return makeFieldValue(result);
    }, state);
  },
```

**Override (something like this)**

```js
 [CHANGE](state, {field, value, touch, dirty}) {
    return write(field, previous => {
      const {asyncError, submitError, ...result} = {...previous, value};
      if (touch) {
        result.touched = true;
      }
      if(dirty) {
        result.dirty = true;
      }
      return makeFieldValue(result);
    }, state);
  },
```

**Objective**

my App is using React, Redux, redux-form, React-router.

I have having 6 tabs in the same parent component, each of the tab is a child component with a redux form in it (with some Input fields). before switching to tabs, i want to check if any of the fields in the same tab is dirty, will display a modal to save it.

To check the dirty fields, i use this , within each of the tab components, and send to parent communication.

	componentWillUpdate() {
		_.each(this.props.fields, function(field) {
		  	console.log(field.name+' : dirty :'+field.dirty);
		});
	}

**Comment by ooflorent** [comment]
Please use StackOverflow for usage questions. This is the only way to ensure the same question doesn’t get asked many times in a row, and that folks who have the same question in the future will be able to find it.

---

You can decorate Redux Form reducer if you don't want to patch the library:

```js
import {actionTypes, reducer as reduxFormReducer} from "redux-form"

function formReducer(state, action) {
  switch (action) {
    case actionTypes.CHANGE:
      const nexState = reduxFormReducer(state, action)
      // Perform the state mutation
      // ...
      return nextState
    
    default:
      return reduxFormReducer(state, action)
  }
}
```

**Comment by raaone7** [comment]
Thank you ooflorent for the advice. Working as expected.

**Comment by vynogradskyi** [comment]
@ooflorent doesn't it brakes the states immutability?

**Comment by ngood97** [comment]
@vynogradskyi He never actually modified the state he just returned what it should be be after the reducer is called
