### ISSUE TITLE
Getting started link in the docs is broken

### ISSUE THREAD

**Issue by andrerpena** [erikras/redux-form#792]
This link in the docs is broken:

![image](https://i.imgur.com/OGBBkjz.png)

It is pointing to [http://redux-form.com/5.0.1/docs/GettingStarted.md](http://redux-form.com/5.0.1/docs/GettingStarted.md) whereas it should point to: [http://redux-form.com/5.0.1/#/getting-started](http://redux-form.com/5.0.1/#/getting-started)

**Comment by ooflorent** [comment]
Fixed by #790
