### ISSUE TITLE
shouldComponentUpdate only if field changed

### ISSUE THREAD

**Issue by rubengrill** [erikras/redux-form#793]
I tried to implement `shouldComponentUpdate` in my component, so that it updates only if a certain field changes (other fields are not of interest, as they are displayed in another tab in my app and thus I'm sure they won't change).

The code looks somewhat like this: 
```js
shouldComponentUpdate(nextProps) {
  return this.props.fields.service !== nextProps.fields.service;
}
```

As my component now never updated, I realized that `this.props.fields` is always === `nextProps.fields`, so whenever a field changes (in my case value changed), then a single object that is passed as props is modified instead of creating a new instance:
https://github.com/erikras/redux-form/blob/v4.2.2/src/createHigherOrderComponent.js#L50
https://github.com/erikras/redux-form/blob/v4.2.2/src/createHigherOrderComponent.js#L102
https://github.com/erikras/redux-form/blob/v4.2.2/src/createHigherOrderComponent.js#L116

Is there a special reason, why the instance field `fields` is updated instead of creating a new object?
Is there another way to check if a field has changed?

**Comment by erikras** [comment]
This is a mysterious phenomenon discussed on #436.

**Comment by ooflorent** [comment]
I'm closing this in favor of #436.
