### ISSUE TITLE
[Feature Proposal] (5.x.x) "Default Empty Values" / "Typed Fields"

### ISSUE THREAD

**Issue by umidbekkarimov** [erikras/redux-form#794]
As started in `5.0.0` version, `null` and `undefined` values converting to `''` (empty string)

And this creates new problems (see #724) with non string or complex values (objects, dates)

For example, we have `DateField` component with prop types:

``` javascript
static propTypes = {
    value: instanceOf(Date),
    minDate: instanceOf(Date),
    maxDate: instanceOf(Date)
};
```

Where `maxDate` and `minDate` can be values of other `fields` (e.g. `fields.startDate` and `fields.endDate`)

Upgrading to `5.X.X` will make this component scream about invalid prop types.

So, my proposal is to somehow define types before converting `null`/`undefined` values to something not nullable.

The easiest way (in my opinion) is to add one more option to `@reduxForm`:

``` javascript
@reduxForm({
    form: 'GarageDealItem',
    fields: [
        'name',
        'count',
        'startDate',
        'endDate',
        'photo',
        'tags[]',
        'location.lat',
        'location.lng'
    ],

    initialValues: {
        startDate: new Date()
    },

    emptyValues: { // or nullValues/undefinedValues/nilValues
        count: 0,
        startDate: null,
        endDate: null,
        photo: null,

        'tags[]': null // in this case i don't really know the better approach
        'location.lat': 0,
        'location.lng': 0
    }
})
export class Form extends Component {
    static propTypes = {
        name: string,
        count: number,
        startDate: instanceOf(Date),
        endDate: instanceOf(Date),
        photo: shape({
            key: string.isRequired,
            url: string.isRequired,
            size: number.isRequired,
            filename: string.isRequired,
            mimetype: string.isRequired
        }),
        tags: arrayOf(shape({
            id: number.isRequired,
            name: string.isRequired
        })),
        location: shape({
           lat: number,
           lng: number
        })
    };
}
```

How you can see, the idea is simple, but has it's problems when you will come to nesting elements

---

The other option is to adopt `React.PropTypes` into `redux-form` `FieldTypes` which will be more complex and will replace `fields` option from `@reduxForm`

``` javascript
@reduxForm({
    form: 'GarageDealItem',
    fieldTypes: {
        name: FieldType.string, // will convert to `''`
        count: FieldType.number, // will convert to `0`
        startDate: FieldType.date, // will convert to `Thu Jan 01 1970 00:00:00` or `null` don't really know 
        endDate: FieldType.date, // same as above
        photo: FieldType.object // will convert to `null`,
        tags: FieldType.arrayOf(FieldType.object),
        location: FieldType.shape({ // will convert to {lat: 0, lng: 0}
             lat: FieldType.number,
             lng: FieldType.number
        })
    },
    initialValues: {
        startDate: new Date()
    }
})
export class Form extends Component {
    static propTypes = {
        name: string,
        count: number,
        startDate: instanceOf(Date),
        endDate: instanceOf(Date),
        photo: shape({
            key: string.isRequired,
            url: string.isRequired,
            size: number.isRequired,
            filename: string.isRequired,
            mimetype: string.isRequired
        }),
        tags: arrayOf(shape({
            id: number.isRequired,
            name: string.isRequired
        })),
        location: shape({
            lat: number,
            lng: number
        })
    };
}
```

In this case `redux-form` will definitely know what type of data it has, and this knowledge can be used not to only set `nil` values to the fields and add features like data converting in `onChange`/`onBlur` methods (**Parsers** described in **Formatters and Parsers** in #726). 

Or maybe can be upgraded to something really big like (inspired by [joi](https://github.com/hapijs/joi)):

``` javascript
@reduxForm({
    fieldTypes: {
         // will automatically validate/normalize values
         year: FieldType.number().integer().min(1900).max(2013),
         name: FieldType.string().alphanum().min(3).max(30).required(),
         startDate: FieldType.date().required(),
         endDate: FieldType.date().min(FieldType.ref('startDate')).required()
    }
})
```

**Comment by erikras** [comment]
First of all, excellent issue, well presented. :+1: 

It seems like providing a `defaultValues`, which is similar to, but different from, `initialValues`, would be sufficient. If it doesn't have a value for the field, it would use the default values, and if it doesn't have a default value, then it would fall back to `''`.

In the mean time, you could certainly do something like:
```js
<DatePicker {...startDate} value={startDate.value || new Date()}/> // since '' is falsy
```
But I agree that this is something that the library should handle.

I'm not convinced, however, that `redux-form` needs to get too far into providing `alphanum()` style validation.

**Comment by umidbekkarimov** [comment]
Thanks you @erikras for response,

I already fixed most of warnings after update, it's not the `bug` i can't handle, it's just some topic to discuss (if anyone interested)
___

The first thing I loved in `redux-form` - is it's simplicity, I used it as tool to store form data and used custom components to handle most of the thing you described in #726 (normalize, debounce, parse, format). 

But as `redux-form` grows and take this kind d44bd6a of manipulation of data to itself, it has to be some option that allows users to control this manipulations.

___
> I'm not convinced, however, that redux-form needs to get too far into providing alphanum() style validation.

I am totally agree with you. It's just daydreams ... may be, one day ... :)

**Comment by mattiamanzati** [comment]
I WANT THIS SO BADLY! :D 
This is exaclty what I pointed out with #176 , but I called it "defaults"!

**Comment by aight8** [comment]
I had a similar case and had to set the default value directly in the custom component.
This feature is really a improvement for this library.

**Comment by erikras** [comment]
`v6` will provide a mechanism to specify a `defaultValue` that will be given as the `value` prop when the current value in the Redux store is `undefined` (and no `initialValue` is given). That seems sufficient, right?

**Comment by mattiamanzati** [comment]
Maybe some kind of "merge" would be nice? Something like value = {...defaultValue, ...initialValue} ?
e.g. you provide a defaultValue for a timestamp field, and it gets merged with the initialValue one if undefined

**Comment by umidbekkarimov** [comment]
@erikras is it resolved in v6 (yeah, i'm still using v5) ? should we close it?

**Comment by vdh** [comment]
@erikras So with the [death of `defaultValue`](https://github.com/erikras/redux-form/pull/1593), is there still a fix available for this issue in `v6`?

These default empty strings are a huge headache in `v5`, I was hoping with `v6` I could retire hacky empty string checking.

I really would desperately prefer to nix empty strings from the state entirely and handle [React's uncontrolled/controlled nonsense](https://github.com/facebook/react/issues/2533) manually at the `Field` / component level 😢
