### ISSUE TITLE
can't specify error for field in array by key via async validation

### ISSUE THREAD

**Issue by babsonmatt** [erikras/redux-form#796]
If I validate sync I can return: 

``` js
const errors = {
  question: 'meh',
    options: {
     1: 'no dice'
   }
};
```

which works just fine, however doing the same from async validation gives the following error:
`Unhandled promise rejection TypeError: array.map is not a function` in the getValue function.

Returning an error like:

``` js

const errors = {
  options: ['error0', 'error1', 'error2']
};
```

works just fine.

Am I doing something wrong here?  

Thanks!

**Comment by erikras** [comment]
Are you wrapping it in a `Promise.reject()`?

**Comment by babsonmatt** [comment]
@erikras Yes, I am.

**Comment by ooflorent** [comment]
Can you provide a reproducible sample?

**Comment by babsonmatt** [comment]
Will do
