### ISSUE TITLE
Best way to do async action and then update deep array values

### ISSUE THREAD

**Issue by licq** [erikras/redux-form#798]
Hi, my question is below:
- one dropdown select on the form
-  when user select one item in the dropdown, dispatch an async action to get data from server
-  after get data, update an array field in the form data

I tried two solutions for this problem:
- plugin. I tried to use plugin to respond to the GET_DATA_SUCCESS action and then return the new state updated based on the data get from the server, but it didn't work. The error is wired.
```
updateField.js:60 Uncaught TypeError: Cannot use 'in' operator to search for 'initial' in name
```
 I think maybe the array value caused this problem

- use mapDispatchToProps to inject a function to do the update in the promise chain
```
fetchTableColumns: (mappings, tableName) => dispatch(fetchTableColumns(tableName)).then((response) => {
    !response.error ? updateMappings(mappings, response.payload.data) : dispatch(fetchTableColumnsFailure(response.payload))
  }),
```

```
const updateMappings = (mappings, tableColumns) => {
  for (let i = 0; i < mappings.length; i++) {
    mappings.removeField()
  }
  tableColumns.forEach(c => {
    mappings.addField({name: c.name})
  })
}
```

I want to know if there is a better way to do things like this. The second way works but not the way I like.

**Comment by ooflorent** [comment]
Hi, thanks for coming by.

Please use StackOverflow for usage questions. This is the only way to ensure the same question doesn’t get asked many times in a row, and that folks who have the same question in the future will be able to find it. (Github search is pretty much useless.)

Sorry we couldn’t answer your question here. Please feel free to post a link to the StackOverflow question, and I’ll be happy to try to answer it.
