### ISSUE TITLE
React-Native android, missing value on blur

### ISSUE THREAD

**Issue by mattiamanzati** [erikras/redux-form#80]
Unlike iOS, when blurring a field android does not pass the form value.
I fixed by making the reducer retain the current value if the action.value is undefined.

    case BLUR:
      return {
        ...state,
        [action.field]: {
          ...state[action.field],
          value: **action.value === undefined ? state[action.field].value ? action.value**,
          touched: !!(action.touch || (state[action.field] || {}).touched)
        },
        _active: undefined
      };

PS: Sorry, I am not able to post PR due to my office firewall D:

**Comment by erikras** [comment]
Thanks for apologizing for your git manners. :smile: 

...and for providing the code for each fix. I'm excited to hear that this library is being used on a React Native app.

**Comment by mattiamanzati** [comment]
Thanks for your awesome library!

**Comment by mattiamanzati** [comment]
Uh, there is a change to add,
instead of action.value === undefined ? state[action.field].value ? action.value
use action.value === undefined ? (state[action.field] || {}).value ? action.value

**Comment by deepaksisodiya** [comment]
My workaround

```
function asyncValidate(values, dispatch, props) {
  const errors = {};
  let emailId;
  if (!values.emailId) {
    // on Android, the values object somehow has emailId as undefined
    emailId = props.values.emailId;
  } else {
    emailId = values.emailId;
  }
 
  return errors;
}
```
