### ISSUE TITLE
Validate called on initial render, how to determine if the form is submitting?

### ISSUE THREAD

**Issue by jshthornton** [erikras/redux-form#800]
The validate function is currently called when reading the fields on form init.
Nothing is passed in the props (except in private properties) to determine if the form is submitting or not.

**Comment by umidbekkarimov** [comment]
`validate` calls on init and when field values change,
It helps to prevent submitting if form is `invalid`

If you want to validate only after submit - you have to return `Promise.reject(errors)` in function you passed to `handleSubmit`

Look at [props](http://redux-form.com/5.0.1/#/api/props) documentation for details
