### ISSUE TITLE
'npm install redux-form' installs 6.0.0-alpha.4 but I can't find any reference to it

### ISSUE THREAD

**Issue by larrydahooster** [erikras/redux-form#802]
When I freshly installed redux-form I got 6.0.0-alpha.4  and also the npm page says that 6.0.0-alpha.4 is the latest of 128 releases.

But 6.x does not seem to be compatible with 5.x because I get the following error: 
Warning: Failed propType: Invalid prop `fields` of type `array` supplied to `AccountOptionsForm`, expected `object`. Check the render method of `Form(AccountOptionsForm)`. 

So since I don't want to run it on a alpha build anyways, I rolled back to 5.0.1. But what bothers me the most is that I can't find any reference to the 6.0.0-alpha.4 release in this git repo. No branch, no tag, no release and no docs.. Can anyone explain to me what is going on here? I am confused.

**Comment by morsdyce** [comment]
It looks like the 6.x alpha has been published without an alpha or prerelease tag which makes it the latest version on npm by default, which is why you're getting the 6.x alpha when you don't specify a version.

**Comment by larrydahooster** [comment]
Thanks for your reply. But how can I access the code then?

**Comment by paparent** [comment]
I had a bug yesterday. I followed the docs, and when I `console.log(this.props.fields)` in the render, I get just the array.. So I did `npm install --save redux-form@5` instead... Might be confusing for beginner like me. Maybe fix the npm to install the v5 ?

**Comment by erikras** [comment]
Damn. I'm sorry about that. I didn't mean for that to happen.

**Comment by erikras** [comment]
Any guidance on how to fix this? `npm` says `"cannot unpublish a version that is >24 hours old"`

**Comment by erikras** [comment]
[Hmm....](http://blog.npmjs.org/post/141905368000/changes-to-npms-unpublish-policy)

Looks like I might have to burn a version number to overcome this. ?

**Comment by erikras** [comment]
I've published [`v6.0.0`](https://github.com/erikras/redux-form/releases/tag/v6.0.0) as the official "**@erikras is an idiot**" release. Sorry about that.

**Comment by erikras** [comment]
Nevermind. I figured out how to fix it without bumping to v6.0.0.

**Comment by paparent** [comment]
Thanks !!! Yes was my 1st day to use it and I was like: Why nothing works!! ahhh!! :)

thanks a lot :)
