### ISSUE TITLE
Get access to the form props without being a React class

### ISSUE THREAD

**Issue by guicar** [erikras/redux-form#804]
Hi,

We are building a page with many independent forms. We would like to know at the top level which ones are currently valid or not.

With [`reduxForm()`](http://redux-form.com/5.0.1/#/api/reduxForm?_k=pbsv9l) we can get access to all the [`props`](http://redux-form.com/5.0.1/#/api/props?_k=zsqq2v), including the `valid` prop. That is good. However, [`reduxForm()`](http://redux-form.com/5.0.1/#/api/reduxForm?_k=pbsv9l) only applies to React classes. Thus this requires us to create one connected React class per form at the top level.

Is there something we are missing? Is there a way to get access to the [`props`](http://redux-form.com/5.0.1/#/api/props?_k=zsqq2v) without being a React class?

**Comment by ooflorent** [comment]
Use Redux's `connect` and `mapStateToProps` to read your form data. You can then manipulate the form using Redux Form actions.
