### ISSUE TITLE
Please expose a method to check isPristine for a form

### ISSUE THREAD

**Issue by r-tock** [erikras/redux-form#806]
We have a use-case like this.

```
<Screen>
<MyForm />
</Screen
```

A screen contains a nested form and we want to expose the isPristine bit on the screen to prevent the navigation when the screen changes routes.

Since we connect MyForm via reduxForm(), the dirty/pristine bits are only exposed to the Form. But Screen wants to  get that information. 

We tried these:
- this.refs.MyForm.props check. But we saw that isDirty is not exposed.
- Add a callback function to the MyForm but this triggers a re-render.
- Directly access the store - The store.form.MyForm has the fields. but to compute the isDirty we have to iterate through it and apply the private isPristine.js you have in your repo on each field. We want to avoid that.

Can you expose a isPristine(FormData) so that we can make this easy for parents to access the information of the child forms.

Or suggest an alternative.

**Comment by aight8** [comment]
+1

**Comment by rogchap** [comment]
This would be great to show a `confirm` dialog when used with react-router's `onLeave`. 
Very useful enhancement. :)

**Comment by jonnolen** [comment]
we are using the persistent form (destroyOnUnmount: false) across a multi-step wizard. We also had to initialize the form with fields across all steps before using it or else our deep forms fields weren't working.

This is my hack to determine dirty/clean:

```
import readFields from 'redux-form/lib/readFields'

let store = createStoreHoweverYouDo();
let allFormFields = ['any', 'field_key', 'that', 'you', 'care', 'about'];

let windowUnloadListener = (getState => {
      return (e) => {
        let state = getState();  //get our state.
        let form = state.form.fund;

        let fields = readFields({ form,
          fields: allFormFields,  //needs to be all fields that you care about retrieving.
          validate(){
            return {};
          },                              //hax replace with your actual validation function to get _meta.allValid
          asyncBlurFields: []   //hax we don't have any but it defaults to [] in createHigherOrderComponent.
        }, {}, {}, ()=>{ }, false);  //hard coded isReactNative to false because it's in a web project.

        console.log("got fields", fields);
        if (!fields._meta.allPristine){
          e.returnValue = "Don't go, your form is dirty."
        }

      }
    })(store.getState)

window.addEventListener('beforeunload', windowUnloadListener);
```

**Comment by erikras** [comment]
`v6` exposes `dirty` and `pristine` instance properties on the decorated form.

**Comment by jonnolen** [comment]
As statics?

**Comment by erikras** [comment]
No, _instance_ properties.

```js
if (this.refs.myForm.dirty) {
  alert('Don\'t go, your form is dirty.')
}
```

**Comment by jonnolen** [comment]
that doesn't work in a situation like a wizard form where each component form is loading a different subset of the fields and you don't have access to all of the forms from one place.

**Comment by erikras** [comment]
`v6` has an [`isPristine()` selector](http://redux-form.com/6.0.2/docs/api/Selectors.md/).

**Comment by WirthAware** [comment]
Any chance to use the selector also in `v5`? Or whats the best way to solve this in `v5`?
