### ISSUE TITLE
Nested fields and errors

### ISSUE THREAD

**Issue by jeremymarc** [erikras/redux-form#807]
I have a redux form, like this:

```js
@reduxForm({
  form: 'signup',
  fields: [ 'users.username', 'users.email'],
})
export default class Signup extends Component {
....
 render() {
    const {user, logout, fields} = this.props;
    return (
      <div>
        {!user &&
        <div>
         <form className="signup-form form-inline" method="post" onSubmit={this.props.handleSubmit(this.onSubmit.bind(this))}>
              <div className="form-group">
               <input type="text" ref="user_username" className="form-control" {...fields['users.username']}/>
              </div>
              {fields['users']['username'].touched && fields['users']['username'].error && <div>{fields['users']['username'].error}</div>}
              <div className="form-group">
               <input type="text" ref="user_email" name="company[users][email]" placeholder="Entrer votre adresse email" className="form-control" {...fields['users']['email']}/>
              </div>
              {fields['users']['email'].touched && fields['users']['email'].error && <div>{fields['users']['email'].error}</div>}
         </form>
         <button className="btn btn-success" onClick={this.props.handleSubmit(this.onSubmit.bind(this))}>Signup</button>
         </div>
        }
  </div>
    );
  }
```
In the reducer, I'm setting the error (from server side like this):

```js
{"users.email":["can't be blank"]}
```

But it doesn't display it under the field (it's working with non nested field). What am I missing?

**Comment by babsonmatt** [comment]
what if you set it as a nested object?

```js
{ users : { email : ['cant be blank'] } }
```

**Comment by jeremymarc** [comment]
@babsonmatt this is coming from the backend (in Rails)

**Comment by babsonmatt** [comment]
should be the same right? just as json with quoted keys?

```js
{ "users" : { "email" : ["cant be blank"] } }
```

**Comment by jeremymarc** [comment]
This is how rails handle nested object. It's sending "users.emails" as key looks like:

`{"users.email":["can't be blank"]}`

**Comment by WirthAware** [comment]
I had a similar problem with a ASP.NET backend. A quick solution i used was to write a function and create a nested object from validation keys that you could return to redux-form. 

But also note redux-form do not support a array for the error value. 
You could use a extra property to store the message array.  

{ "users" : { "email" : { errorMessages: ["cant be blank"] } } } 

or just join the error message array with a special seperator to have a single error value and when you use it convert it back to an array by splitting the string.

**Comment by ooflorent** [comment]
Nested errors must reflect the validated values.
Given the following values:

```js
{
  users: [
    {
      name: "John",
      email: "john@gmail.com"
    },
    {
      name: "Meh",
      email: "invalid_email"
    },
  ]
}
```

If the only errored field is `email` on the second user, the errors must be:

```js
{
  users: [
    null,
    {
      email: "This email is invalid"
    }
  ]
}
```

**Comment by yefim** [comment]
@ooflorent my server is returning the correct nested error object but redux-form doesn't seem to set the error correctly. I'm on v5.3.1.

My field is defined as `'positions[].title'`

And the server responds with `{"positions": [{"title": "Title is required."}]}`

But when I check `positions[0].title.error`, it is not set.

I've got client side validations to work for the nested object and every other (non-nested) field works both with client and server side errors. It's just the `positions[].title` field that doesn't seem to set errors correctly. Please help.
