### ISSUE TITLE
Example sources

### ISSUE THREAD

**Issue by fallenpeace** [erikras/redux-form#808]
Most of the examples only have examples of wiring up redux-form to the input, but the props(functions) that are passed in, are not included in the source code. It would be awesome, if we got the full complete source for the examples, instead of just the form component.

**Comment by fallenpeace** [comment]
Just found this.
https://github.com/raboof/redux-form/commit/e35e7d6d43d3e492c0d5adffa5b4320aac17a8c0

Thanks @raboof

**Comment by fallenpeace** [comment]
Update: 'npm install fails'

**Comment by raboof** [comment]
@fallenpeace it might help if you post the complete output of your 'npm install' failing

**Comment by ooflorent** [comment]
Examples can be found in the [`gh-page`](https://github.com/erikras/redux-form/tree/gh-pages) branch. 

`npm install` works like a charm. Can you delete `node_modules` and rerun `npm install`? If the problem persists, please file an issue including details about your environment and the error output.
