### ISSUE TITLE
example source code unreadable

### ISSUE THREAD

**Issue by JESii** [erikras/redux-form#809]
The code examples on `redux-form.com/5.0.1` are unreadable; they have a black background and the text is a shade of grey that disappears into the background.

One example [is here](http://redux-form.com/5.0.1/#/examples/submit-from-parent?_k=m1lzeo), but all the examples i viewed have the same problem.  The only way to view the code is to highlight/copy/paste somewhere. 

/Users/jseidel/Pictures/2016-04-13_1902_ExamplesUnreadable.png

**Comment by anyong** [comment]
Looks fine to me, could be your browser?

**Comment by erikras** [comment]
_Sounds_ like you're not getting [the code formatting CSS](https://cdn.rawgit.com/google/code-prettify/master/loader/skins/desert.css). My best bet is that you have a security-conscious browser extension that is forbidding third party css.

**Comment by JESii** [comment]
Thanks, Erik... that was the problem: Privacy Badger on Chrome -- it's history now and so is this issue.
