### ISSUE TITLE
Error fields and validation

### ISSUE THREAD

**Issue by FlorianCart** [erikras/redux-form#810]
In my fields, I have this : fields: ['users.username'].
in my render this one :  {fields['users']['username'].touched && fields['users']['username'].error && <div>{fields['users']['username'].error}</div>}
And in my validate form, i don't know how to put the 'users.username' without error.
At the base, i have this : 
if (!values.username) {
    errors.username = 'Required';
  }
  if (values.username && values.username.length < 2) {
    errors.username = 'Il doit y avoir au moins 2 caractères';
  }
But i want to put users.username instead of email. but i can't without error

**Comment by erikras** [comment]
If your field is deep (nested), then your errors must be, too.

If your field is `'users.username'`, then the `values` given to your validation function will be like:
```js
{
  users: {
    username: 'FlorianCart'
  }
}
```
So your error needs to be with a similar structure.
```js
{
  users: {
    username: 'Error goes here'
  }
}
```
So...
```js
function validate(values) {
  const errors = {};
  if (!values.users || !values.username) {
    errors.users = { username: 'Required' };
  }
  if (values.users && values.users.username && values.users.username.length < 2) {
    errors.users = { username: 'Il doit y avoir au moins 2 caractères' };
  }
  return errors;
}
```

**Comment by FlorianCart** [comment]
It's work. But i have a second problem. 
I add email too. After that, username does not work anymore. 
Exemple : 

  if (!values.users || !values.username) {
    errors.users = { username: 'Required' };
  }
  if (values.users && values.users.username && values.users.username.length < 2) {
    errors.users = { username: 'Il doit y avoir au moins 2 caractères' };
  }
  if (!values.email || !values.users) {
    errors.users = { email: 'Required' };
  }
  if (values.users && values.users.email && !/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i.test(values.users.email)) {
    errors.users = { email: 'Email incorrect' };
  }

Render() : 

 {fields['users']['username'].touched && fields['users']['username'].error && <div>{fields['users']['username'].error}</div>}
and 
 {fields['users']['email'].touched && fields['users']['email'].error && <div>{fields['users']['email'].error}</div>}

do you know why ? thanks for the answer
