### ISSUE TITLE
What does the fields export do?

### ISSUE THREAD

**Issue by genyded** [erikras/redux-form#811]
What is the purpose on the fields export at the top of the form files (at least in the examples)? There is not import of it anywhere that I can see. It also seems redundant to have to list all the fields there and in the form initializer.

```javascript
export const fields = [ 'firstName', 'lastName', 'email', 'sex', 'favoriteColor', 'employed', 'notes' ]
```

```javascript
render() {
    const {
      fields: { firstName, lastName, email, sex, favoriteColor, employed, notes },
      handleSubmit,
      resetForm,
      submitting
      } = this.props
...
```

**Comment by erikras** [comment]
Excellent question! :+1: 

That is solely useful for the example website. It is imported by the `Values` component that is showing the current values in JSON elsewhere on the page. You will probably not need to export the `fields` array in your app.
