### ISSUE TITLE
Redux Form not compatible with Login/passwords

### ISSUE THREAD

**Issue by bradennapier** [erikras/redux-form#812]
Hello,
 It woudl appear you can not use Redux Form for Login/Password forms.  The problem is with autofill.  The browser wants to allow the user to save the values, but browsers do not seem to fire any kind of onchange on password fields when they are auto-filled. 

  Therefore, my form renders with all the fields having values, however Redux Form believes that only the username is filled in and the password field is empty.  This changes the first time Redux Form fields are blurred, but that is a problem as when the forms are auto filled, the fields may not need to be blurred at all.

**Comment by jljorgenson18** [comment]
So this is more of a React issue from what I can tell when I ran into this. I haven't checked React v15 yet but the crux of the issue is that the onChange event doesn't fire on autofill on android. What happens is that because the input in redux-form are controlled, the state gets out of sync with what is actually the value in the dom. 

I remember researching this a ton and there wasn't an elegant solution that I could find. On my input form group, I ended up creating an autofill interval to help solve it.

```js
    componentDidMount: function() {
        if(is.mobile()) {
            this.autoFillInterval = setInterval(this.checkIfAutofilled, 1500);
        }
    },

    componentWillUnmount: function() {
        if(this.autoFillInterval) {
            clearInterval(this.autoFillInterval);
        }
    },

    checkIfAutofilled: function() {
        const mainInput = this.refs.mainInput;
        const currentVal = this.props.field.val;
        if(mainInput && mainInput.value !== currentVal) {
            this.onChange({
                target: {
                    value: mainInput.value
                }
            });
        }
    },
```

This wasn't a great solution but it worked

**Comment by erikras** [comment]
Yes, my research on this has also been fruitless. It's a shame that the browser isn't kind enough to fire an `onChange` event when it autofills.

**Comment by echenley** [comment]
This technique seems promising as well. https://medium.com/@dschmidt1992/auto-fill-with-redux-forms-9b51ad8ef962

**Comment by shooftie** [comment]
@echenley, did you manage to get that solution to work. I'm reasonably new to React but there seemed to be some issues with retrieving the autofilled values. Was hoping you might have managed to crack it...

**Comment by chrisfitkin** [comment]
For anyone coming here still, the `react-autofill` package solved this problem for me really well.  Just wrap your form component with this higher order component (HOC) and it will search through the nested form and apply a similar watch and update timer to the form elements.

https://www.npmjs.com/package/react-autofill

I used it like this: 

```javascript
import React from 'react';
import { compose } from 'redux';
import autofill from 'react-autofill';
import submit from './submit'; // my custom submit handler

const MyReduxForm = (props) => {
  const { handleSubmit } = props;
  return (
    <form onSubmit={handleSubmit(submit)}>
        ... // my redux form fields go here
    </form>
  );
};

export default compose(
  reduxForm({
    form: 'MyReduxForm', // a unique identifier for this form
  }),
  autofill
)(MyReduxForm);
```
