### ISSUE TITLE
Change react-redux/native to react-redux in native.js

### ISSUE THREAD

**Issue by robwalkerco** [erikras/redux-form#813]
As mentioned in #608, with react-redux 4.4.2 and redux-form 5.0.1, the file at node_modules/redux-form/lib/native.js needs to be manually edited.
The reference to `react-redux/native` needs to be changed to just `react-redux` or we get an error about being unable to resolve the module.

I'm not sure on that the solution to this is though, without breaking backwards compatibility.

**Comment by mschipperheyn** [comment]
Yeah, this has been mentioned a few times before. It's based on a requirement for an older version of redux. It's time that this gets updated.

**Comment by ooflorent** [comment]
@robwalkerco @mschipperheyn Could one of you guys submit a PR with the required changes? The goal of the PR is not to be merged but to highlight what's wrong

**Comment by robwalkerco** [comment]
Created PR #897 to show required change.

**Comment by erikras** [comment]
Released as [`v5.2.4`](https://github.com/erikras/redux-form/releases/tag/v5.2.4).
