### ISSUE TITLE
startSubmit without using the label form

### ISSUE THREAD

**Issue by juvasquezg** [erikras/redux-form#814]
Hi,

I've been using redux-form and is excellent. I want to add to a page with ASP.Net and the page has a form tag. I can not have two form tags. Can I use redux-form without the form tag?

**Comment by juvasquezg** [comment]
Hi,

mm http://redux-form.com/5.0.1/#/examples/submit-from-parent?_k=02w6fw submit() is undefined.

redux-form 4.2.2.

Thank you!!.

**Comment by ooflorent** [comment]
Hi, thanks for coming by.

This is a usage question, and we encourage you to ask it on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

I’m closing for these reasons.
