### ISSUE TITLE
Infinite loop when trying to intercept onChange

### ISSUE THREAD

**Issue by silvenon** [erikras/redux-form#818]
I'm trying to do something else on change as well as set the value:

```jsx
_handleChange(value) {
  // do something
  this.props.fields.email.onChange(value);
}

<input {...Object.assign(this.props.fields.email, {
  onChange: this._handleChange
 })} />
```

But now I'm getting an infinite loop when I change the input field. What am I doing wrong?

**Comment by davidkpiano** [comment]
You're actually mutating `this.props.fields.email`.

Try `<input {Object.assign({}, this.props.fields.email, {onChange: ... })} />`

**Comment by silvenon** [comment]
@davidkpiano :heart:

**Comment by erikras** [comment]
I don't miss `Object.assign()` one bit after switching to the spread operator. Everyone who's ever used `Object.assign()` has made that same mistake.

The more elegant syntax, in my opinion, looks like this:
```js
<input {...this.props.fields.email} onChange={this._handleChange}/>
```
Later props overwrite earlier props.
