### ISSUE TITLE
Question: How do I set a value in a form?

### ISSUE THREAD

**Issue by jcalfee** [erikras/redux-form#819]
This is not a default value, but rather a value inspired by a mouse click.  For example, user clicks on their balance triggering an update in a transfer form amount.

This has the side effect of the first click triggering a form validation causing the update to fail (one of the other components failed validation).  The second click goes through and the amount appears.

Obviously this is wrong, what is the correct way to put the value in the form without triggering the validation?

```js
const assetBalanceClick = e => {
     e.preventDefault()
     this.refs.amount.value = balanceValue
}

render() --v

<input type="text" placeholder="Amount" {...amount} ref="amount" />
<a onClick={assetBalanceClick}>{balanceValue}</a>
```

**Comment by jcalfee** [comment]
Also noticed the click must be triggering the onBlur event.  The first field became unfocused.

**Comment by TonyVeigel** [comment]
Don't know if I understand the question completely but you can use the onChange()

for instance:
```
onClick(e => amount.onChange(e.target.value))
```

**Comment by erikras** [comment]
First of all...
```js
this.refs.amount.value = balanceValue
```
...is very naughty. You shouldn't be touching the DOM node.

And @TonyVeigel is correct. You need to be changing the value in Redux (not the DOM), and using `this.props.fields.amount.onChange(newValue)` is the easiest way to do that.

**Comment by jcalfee** [comment]
Your on to me, I am dissident and naughty .. They say Americans need to be more like this lol...

So, It works great!  thanks .. The onBlur is still triggering a pre-mature form validation (and error message).  Feel free to close the issue (or I will).  But that would be slick of you had a solution for that.
