### ISSUE TITLE
how to correctly use global error message

### ISSUE THREAD

**Issue by hiEven** [erikras/redux-form#823]
hello, thanks for your awesome work. redux-form is a brilliant tool for me.

however, I just follow your [tutorial](http://redux-form.com/5.0.1/#/examples/submit-validation?_k=7q60a2) to use `_error` object

also I use `invalid` to disable submit button if any error exists

Here is the question, if my submit validation fails and `reject({_error: 'oops'})`

even I change all the values in the form, the `invalid` is still `true` and I can never submit again

Is there any obvious mistake I made ?

thanks again

**Comment by erikras** [comment]
Ha! No, no mistake on your part. Just another edge case I had not considered.

I think you're going to have to not disable your submit button on `invalid`, like the example does.

**Comment by shawnxusy** [comment]
@erikras Got the same problem here - the case kind of gets worse when I have nested / dynamic forms. Implementing 'disabling' submit button seems to involve checking each nested input :(

**Comment by shawnxusy** [comment]
Actually, @hiEven I decided to put global form errors in the form's local state, i.e., `state = { saveError: ''}`
When there's validation error just call `this.setState({saveError: error})`, and in `render()` render `this.state.saveError` if exists.
Basically staying away from the _error, and thus still able to use `invalid` to disable the submit button.

**Comment by hiEven** [comment]
@erikras however, I do some synchronous validation there. If I don't use `invalid` for disabling purpose.
Does that mean I need to handle i.e. `disabled={fields.email.error || fields.password.error}` ?

@shawnxusy 
For now, my workaround is `disabled={invalid && !submitFail}`. It works for me, I can let user submit again and still can validate other values

**Comment by erikras** [comment]
> Does that mean I need to handle i.e. `disabled={fields.email.error || fields.password.error}` ?

I think so, yes. 😞 

> For now, my workaround is `disabled={invalid && !submitFail}`. It works for me, I can let user submit again and still can validate other values

👍 👍

**Comment by hiEven** [comment]
ok, still looking forward to have some way to clean global error.
I am about to close this issue
Thanks a lot.

**Comment by erikras** [comment]
`dispatch(stopSubmit({}))` will clean it, I think, if you want to do it manually. But a more elegant `cleanGlobalErrorOnAnyChange: true` setting to change the default reducer behavior would be nicer.

**Comment by lauterry** [comment]
Hello

Does/Will such a ```cleanGlobalErrorOnAnyChange: true``` exist ? 

Best regards

**Comment by yourGuy** [comment]
I'm still struggling with dismissing the global submission error (I have a typical x button inside the error msg with an action attached to it ) , I'm in 6.6.3
Neither dispatch(stopSubmit({})) nor dispatch(clearSubmitErrors({})) change the error prop or the submitFail prop
