### ISSUE TITLE
Textarea any action within the textarea reset the focus to the end of the text

### ISSUE THREAD

**Issue by lioramsalem90** [erikras/redux-form#824]
When I remove text(or add) from the middle of a sentence the textarea focus is reset to the end of the text.

Example:

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/10909088/14589508/6a3541e6-04ec-11e6-99ea-b37274d79ddd.gif)

All I have is onChange event that dispatch action that update a state (counter of how many chars + the text) to the state. once i remove the onChange everything is fine.

When i remove the onchange everything works, and when i remove the field from redux forms (```....textarea```) everything works. so it seems they don't work well with each other.

Thanks

**Comment by erikras** [comment]
This is a React bug, I think. #786
