### ISSUE TITLE
addField for array field creates the wrong structure if no initial values are passed

### ISSUE THREAD

**Issue by jshthornton** [erikras/redux-form#825]
If you call `addField(undefined, undefined)` in v5.0.1 it creates a non-array field.
You have to call `addField({}, undefined)`.

**Comment by erikras** [comment]
Interesting. Thanks for the excellent bug report.

**Comment by ooflorent** [comment]
@jshthornton Can you add more details or a reproducible sample?

**Comment by danielrob** [comment]
Closing this v5 issue. PR's are accepted for v5, but it is not actively supported.
