### ISSUE TITLE
Provide Lazy Input Wrapper with this library or debouncing option

### ISSUE THREAD

**Issue by aight8** [erikras/redux-form#826]
As we know redux-form hits on large forms some performance problems. I don't know exactly how this could be radically improved in the future because it's in the nature of redux to notify every subscribers. I followed the discussion and very excited to see the redesigned version and of it's benefits.

Nevertheless text input's can be quickly evils in this library, even on small forms, when you hit a key you feel a micro delay - it feels really **clunky** and **funky**.

I build a small wrapper around the input element's which debounce the onChange event so the form is now very responsive (absolutely no delay).

I think we should provide this helpful strategy to all library users because it's essential that users want good performance out of the box. Otherwise every user build his own wrapper and much more user even don't know about this solution.

There is absolutely no disadvantage for this and there is no reason why it should belongs to the userland side.

**Comment by kristian-puccio** [comment]
Do you mind posting your wrapper code?

**Comment by erikras** [comment]
This is precisely the kind of performance problem that prompted the [rewrite to `v6.0`](https://github.com/erikras/redux-form/releases/tag/v6.0.0-alpha.4).

**Comment by ooflorent** [comment]
Prior v6, the best option is to use input components and define `shouldComponentUpdate` on them.
