### ISSUE TITLE
Invalid prop `form` of type `object` supplied to `ReduxFormConnector

### ISSUE THREAD

**Issue by madshargreave** [erikras/redux-form#827]
I have the following form:

```
import React, { Component, PropTypes } from 'react'
import { reduxForm } from 'redux-form'
import { UIInput, UIButton, UIForm, UIField, UIFieldset, UIDivider, UIColorSelect, UIAvatarField } from 'shared/components/ui'

require('./profile_form.scss')

const form = 'profile'
const fields = ['displayName', 'avatar']

@reduxForm({ form, fields })
class ProfileForm extends Component {

  render () {
    const {
      fields: { displayName, avatar },
      user,
      handleSubmit,
      resetForm,
      submitting,
      error,
      dirty
    } = this.props

    return (
      <div className='profile-form'>
          <UIField className='profile-form-field-group-fields' {...displayName} placeholder='Display Name'/>
          <UIButton onClick={this.handleSubmit}/>
      </div>
    )
  }

}

export default ProfileForm

```

But I get the following error

```
Failed propType: Invalid prop `form` of type `object` supplied to `ReduxFormConnector(ProfileForm)`, expected `string`. Check the render method of `ConnectedForm`.
```

Any ideaS?

**Comment by erikras** [comment]
Your code looks fine to me. Can you use the React dev tools to see just what the value of that prop is?

**Comment by madshargreave** [comment]
<img width="224" alt="screen shot 2016-04-18 at 19 39 30" src="https://cloud.githubusercontent.com/assets/5479890/14613588/4d9dded8-059d-11e6-916c-f62b8bac2cdb.png">

**Comment by erikras** [comment]
The `ReduxFormConnector` should be getting a string, and the `ReduxForm` should be getting the object (the Redux state slice).

![screencast 2016-04-18 19-45-05](https://cloud.githubusercontent.com/assets/4396759/14613797/5948e326-059e-11e6-9bf0-9e1f988ef21e.gif)

**Comment by madshargreave** [comment]
Thanks!

I was accidentally overriding the form prop higher up. Works now

**Comment by erikras** [comment]
👍

**Comment by timraasveld** [comment]
I'm having the same problem, but can't figure out why the form prop is getting set to an empty object, nothing that is not mentioned in the "getting started" guide is changing the form prop.
![image](https://cloud.githubusercontent.com/assets/8157262/16654564/b03bef10-4456-11e6-8771-3d5398ac8a7e.png)
I followed [the instructions for my version](http://redux-form.com/5.3.1/#/getting-started?_k=0dzajk) (5.3.1) of redux-form exactly, but can't figure out why this error keeps occurring.

Form definition: https://github.com/roqua/screensmart/blob/1e1a2a05769d780740ff02a7a35aebfc00a2ee6d/app/assets/javascripts/components/InvitationForm.coffee#L49

Container definition: https://github.com/roqua/screensmart/blob/1e1a2a05769d780740ff02a7a35aebfc00a2ee6d/app/assets/javascripts/containers/InvitationFormContainer.coffee#L1

Any ideas? :)

**Comment by pedrommuller** [comment]
that may happen in your combine reducer I had

export const reducers = combineReducers({
  form:formReducer,
  usersReducer:usersReducer
});

that basically was overriding the form from the props of my redux-forms

I changed it to:
export const reducers = combineReducers({
  formReducer:formReducer,
  usersReducer:usersReducer
});

and is working fine now...
