### ISSUE TITLE
asyncValidation submitting bug

### ISSUE THREAD

**Issue by hank7444** [erikras/redux-form#829]
if I choose the async field first, and then click submit button, 
the submit button doesn't submit because it is disabled from "asyncValidating"

![image](https://cloud.githubusercontent.com/assets/4727090/14630419/3299e584-0640-11e6-82e8-6c89ace68475.png)

====

but If I remove "asyncValidating" props from submit button, and then I click many times very quickly,
it will send many requests times.

![image](https://cloud.githubusercontent.com/assets/4727090/14630365/c1027832-063f-11e6-8ce2-69c7b536caea.png)

Have any good idea?

**Comment by erikras** [comment]
Yep, this is a legit bug. `handleSubmit` needs to be smart enough to know about whether async validation is happening.

**Comment by erikras** [comment]
Published fix as [`v6.0.0-alpha.9`](https://github.com/erikras/redux-form/releases/tag/v6.0.0-alpha.9).

**Comment by hank7444** [comment]
@erikras  thx!, I will try it 👍
