### ISSUE TITLE
Add submitSuccess as props available, onSubmitFail not works

### ISSUE THREAD

**Issue by aight8** [erikras/redux-form#831]
There are now in 5.1 new callback events. But it's not possible to check in the form for "submitSuccess". Because !submitFailed is not necessary a successful submit.

ps: onSubmitFail is not called in 5.1 when promise is rejected, onSubmitSuccess will when it's resolved.

edit: I found it out because I tried to provide manually an submitSuccess prop to the form and listen to the onSubmitFail event to reset my custom submitSuccess prop.

**Comment by erikras** [comment]
📟 @puradox

**Comment by erikras** [comment]
Fix published as [`v5.1.1`](https://github.com/erikras/redux-form/releases/tag/v5.1.1). Please verify.
