### ISSUE TITLE
How does a POST request from Redux Form get handled by express?

### ISSUE THREAD

**Issue by hidace** [erikras/redux-form#834]
When you’re using a normal HTML form and you submit a POST request, that request gets sent to the express post route like this:

```
app.post('/some/url', function(req, res) {
  // req from HTML form
});

```
But when you’re using Redux Forms to handle your POST request to an API, does that request then get passed through as the request in the post route the same way? I'm having trouble accessing what my form is submitting in the post route of my express server.

Any and all help is appreciated.

**Comment by erikras** [comment]
`redux-form` assumes that you will be submitting your forms as JSON via AJAX.

**Comment by hidace** [comment]
I'm using axios to make the request, but I just realized what my issue was. I forgot to include the database connection within that POST request to write. 

To answer my question from above - yes, the form does send the request to the post route. You can access it through req.body. Helps to make sure you configure your server and database connection ;-)

Thanks!
