### ISSUE TITLE
Big Form are very slow with redux-form 

### ISSUE THREAD

**Issue by juvasquezg** [erikras/redux-form#835]
Hi,

I have a big form and with redux-form is very slow, Please help me.

Thank you so Much!!

**Comment by erikras** [comment]
There are some strategies discussed on #529.

This was the major impetus for [the `v6` rewrite](https://github.com/erikras/redux-form/releases/tag/v6.0.0-alpha.4). The best option would be to upgrade, but `v6` is not full-featured yet, so you'll need to wait if you are using a `redux-form` feature in `v5` that is not yet implemented.

**Comment by juvasquezg** [comment]
Thank you so much!!!
