### ISSUE TITLE
V6 Seems some css issue with v6 site.

### ISSUE THREAD

**Issue by mihirsoni** [erikras/redux-form#836]
It seems there is something missing in bundling site. there is no CSS as of now  for examples.

http://redux-form.com/6.0.0-alpha.4/examples/syncValidation/

**Comment by erikras** [comment]
Well of course it doesn't work if you don't have my `/etc/hosts` setting and my `nginx` running locally to serve them! :facepalm:

Thanks. 😄

**Comment by mihirsoni** [comment]
@erikras  Thanks :) trying to add some more examples :)
