### ISSUE TITLE
Pass props to initialValue

### ISSUE THREAD

**Issue by michalg42** [erikras/redux-form#837]
Hello.
I have small problem with initializing form. I can set initial values with state from reducers, but I need to set these values with props that I passed to form component.

I know I can do it using componentDidMount for instance, but if there is way to do it better way, I will be happy to know. :)

**Comment by allantl** [comment]
Hi michal,
I believe you can do this, suppose you have two fields in your form component(name, age)
```javascript
let initialValues = {
	initialValues: {
	  name: "John Doe"
	}
};

<ReduxForm {...initialValues} />
```

**Comment by ooflorent** [comment]
As @allantl pointed out, you can pass the `initialValues` from the parent component. If you need complex transforms you can use a HoC or use Redux's `connect` to derive the state:

```js
export default compose(
  connect(
    state => ({
      initialValues: state.user,
    })
  )
  reduxForm({form: "form", fields: ["foo", "bar", "baz"]})
)(MyForm)
```

**Comment by jasan-s** [comment]
does the initializing keys have to be equal to the name of the fields?

**Comment by juanpasolano** [comment]
How would we do this with v6.
If using connect then the parent component can't use the component API.

**Comment by jcperez-ch** [comment]
@juanpasolano I was having same issue, but seems like you can still pass initialValues based on props using the [mergeProps](https://github.com/reactjs/react-redux/blob/master/src/components/connect.js#L35) function of the `connect`decorator as:

```js
@connect(state => state, dispatch => dispatch, (stateProps, dispatchProps, ownProps) => (
   ...stateProps,
   ...dispatchProps,
   initialValues: {
      foo: ownProps.foo
   }
))
@reduxForm({
   form: 'yourForm'
})

```

**Comment by itditp** [comment]
@jcperez-ch thanks a lot

**Comment by mull** [comment]
Has anyone else ran into a maximum call stack error using this technique?

**Comment by idangozlan** [comment]
You can also use `changeFieldValue` method in your constructor.

**Comment by smeijer** [comment]
I need to generate a new random id, whenever the form is submitted and reinitialized. It doesn't seem to be possible at the moment. Any one an idea for a workaround? 

```js
export default compose(
  withProps(({ blogId}) => ({
    form: `${COMMENT_FORM}/${blogId}`,
    enableReinitialize: true,
  })),

  connect(mapStateToProps, mapDispatchToProps),

  reduxForm(),

  withProps(({ blogId, pristine }) => pristine ? {
    initialValues: {
      newId: Random.id(),
      blogId,
    },
  } : undefined),
)(CommentForm);
```

**Comment by gustavohenke** [comment]
@smeijer, the likely reason for this is that Redux Form is not seeing `initialValues` changing - it's placed below `reduxForm` HOC.

You can, however, use [`isPristine` selector](http://redux-form.com/6.5.0/docs/api/Selectors.md/#-ispristine-formname-string-returns-state-pristine-boolean-) and place this logic in your `mapStateToProps`.
