### ISSUE TITLE
Dispatching action for whole form

### ISSUE THREAD

**Issue by shulcsm** [erikras/redux-form#839]
I want to dispatch an action on blur of any field in form without overloading prop of every field. Is there a way to do it?

**Comment by erikras** [comment]
Not built in. But you could certainly write a little utility function to do it.

```js
const addBlurAction = field => ({
  ...field,
  onBlur: event => {
    field.onBlur(event)
    dispatch(customBlurAction())
  }
})
```

And then decorate each field object with that.

```js
<input type="text" {...addBlurAction(firstName)}/>
```

You could even do it higher up.
```js
import mapValues from 'lodash.mapvalues'
...
render() {
  const { firstName, lastName, email } = mapValues(this.props.fields, addBlurAction)
  return (
    <div>
      <input type="text" {...firstName}/>
      <input type="text" {...lastName}/>
      <input type="text" {...email}/>
    </div>
  )
}
```

**Comment by shulcsm** [comment]
Thanks, this was the original idea. I was hoping i'm missing something, but looks like it's the only way. :/
