### ISSUE TITLE
Application Lifecycle?

### ISSUE THREAD

**Issue by asaf** [erikras/redux-form#84]
Hey,

I have a dumb component with a form within it (lets call it `ContactForm`),
A redux connected passes some property from state to the dump component. (lets call it `ContactContainer`)

To initially load the form in `ContactForm`, I'm doing:

```js
//initialize the form with the new contact object if it was changed.
componentWillUpdate(nextProps) {
    if (this.props.contact !== nextProps.contact && nextProps.contact) {
      const { initializeForm, contact } = nextProps;
      initializeForm(contact);
    }
}
```

In `ContactContainer` I do something like:
```js
componentWillMount() {
   //loadData is a dispatched action.
    this.loadData(this.props);
}
```

Redux eventually, at some point publishes the change to `ContactContainer`, which eventually re-renders the `ContactForm` with the new data, `ContactForm:componentWillUpdate` is invoked with a change and form is initialized.

But sometimes...... it seems like `ContactForm:componentWillUpdate` is not invoked at all, this is because Redux was quick enough to process the state changes before the Form component is mounted thus `ContactForm:componentWillUpdate` is not invoked at all.

So I found myself adding in `ContactForm`:

```js
componentWillMount() {
    if (this.props.contact) {
      this.props.initializeForm(this.props.contact);
    }
  }
```

But it smells wrong....

@gaearon This question is not only relevant to the forms,  if you got a moment to say something about this it'll be great, Redux docs looks good at this stage and I know Redux is not a full stack (and I like the freedom of Redux that is still kept properly since your initial commit few months ago!), but if you look at full stacks such EmberJs, Angular, etc, the documentation always explains the full lifecycle (route -> data loading -> controller initialization -> components -> templates, etc...), I think it's worth putting more explanation here.

Thanks!

**Comment by erikras** [comment]
@asaf I'm assuming that you're not doing any server-side rendering, because otherwise your examples make little sense, as `componentWillUpdate` [is not called for the initial render](http://facebook.github.io/react/docs/component-specs.html#updating-componentwillupdate), and therefore is not sufficient to initialize your form. You have not specified exactly what `loadData` _does_ with the data upon fetching it, but perhaps you need something more like this?
```js
// ContactContainer
componentWillMount() {
  this.loadData(this.props)
    .then(data => {
      this.dispatch(initializeForm('contact', data);
    });
}
```

**Comment by asaf** [comment]
@erikras Lets assume it just triggers an API call as in your example, 

This approach is problematic as you skip the reducer computation and directly work with the async call result.

**Comment by erikras** [comment]
Yes, you are correct.

I'm not sure what's best here. In [my app](https://github.com/erikras/react-redux-universal-hot-example), I specifically wait for all "load" promises to return before even calling `React.render()`, so I know that I have all my data.
