### ISSUE TITLE
`withRef: true` won't work.

### ISSUE THREAD

**Issue by rafaelsales** [erikras/redux-form#840]
**Given the MyForm definition file:**

``` javascript
class MyForm extends Component {
  doSomething() {
    console.log('hello')
  }
}

export default reduxForm({
  form: 'MyForm',
  fields: ['name']
},
false, false, false,
{
  withRef: true
})(MyForm)
```

**I create the component like this:**

``` html
<MyForm ref="myForm" />
```

When I call `this.refs.myForm.getWrappedInstance().doSomething()` it just error out saying myForm doesn't have method `doSomething`. Other React component methods will also return `undefined/empty`, like `this.refs.myForm.getWrappedInstance().state`

I also couldn't find any example of using `withRef` in redux-form, but I followed the docs and couldn't get it working.

Thanks

**Comment by erikras** [comment]
Access to your original wrapped component reference isn't really possible because `reduxForm` wraps it in two of its own components as well as the `connect()`. The only thing you're allowed to call from the containing component is [`submit()`](http://redux-form.com/5.1.0/#/examples/submit-from-parent). Sorry.

**Comment by rafaelsales** [comment]
@erikras is there no plan to support that in the future?

**Comment by erikras** [comment]
Just to be clear, you want to be able to call instance methods on your inner component?

**Comment by rafaelsales** [comment]
Correct, just like the ref instance behaves when the component is not wrapped by `reduxForm`.

**Comment by erikras** [comment]
Until I figure out should/if/how to support this, you might find this article interesting. [The HOC Drill Pattern](https://medium.com/@erikras/the-hoc-drill-pattern-a676a3889ced)

**Comment by rafaelsales** [comment]
@erikras Very good article! It's indeed a very nice pattern to overcome this. Thanks for sharing

**Comment by MrEfrem** [comment]
I do in a HOC component and I don't use what callbacks:
```
const reactMethods = [
  'constructor',
  'render',
  'componentWillMount',
  'componentDidMount',
  'componentWillReceiveProps',
  'shouldComponentUpdate',
  'componentWillUpdate',
  'componentDidUpdate',
  'componentWillUnmount',
  'reactMethods',
];
...
componentDidMount() {
  const methods = Object.getOwnPropertyNames(WrappedComponent.prototype);
  const createMethod = methodName => {
    return (...params) => {
      return this.refs.wrappedComponent[methodName](...params);
    };
  };
  for (const method in methods) {
    if (reactMethods.indexOf(methods[method]) === -1) {
      this[methods[method]] = createMethod(methods[method]);
    }
  }
}
...
```

Why not to realize the similar scenario?

**Comment by MrEfrem** [comment]
I proposed the incorrect solution. 
Automatically it isn't correct to transfer methods probably.
But it is possible to make for example the `bindStaticMethods` and `bindProtoMethods` parameters containing an array of methods which could be bind from the `constructor` and from a `prototype` in a HOC component. 
In what specifically to transfer complexity these methods through several levels of attachment of components?
`connect ()` has the `WithRef` parameter that it was possible to get access to a instance.

**Comment by gustavohenke** [comment]
Closing because this seems to be from the old times of v5 and older.

**Comment by chetanvihite** [comment]
[``](`

_url_

`)
