### ISSUE TITLE
Question: how can pass values from a group of textboxes

### ISSUE THREAD

**Issue by richardvaldiviesomacias** [erikras/redux-form#842]
I have a redux form with two address section. I nedd using a checkbox to use the first address. For example the fields shape like address1.street address1.city and the other address address2.street address2.city.  There goes to my component <myaddress address1> <myaddress address2>. Then I clicked to this checkbox and try to shape address2 as address1 and the console for that component still can see address1.street for both. Could you please help me or point to the right direction?

**Comment by hedgerh** [comment]
Hey @richardvaldiviesomacias, I can try and help you in the redux-form Gitter channel.  I didn't understand the last part of what you said, so if you can get a demo or code sample to show me, that'd be great.

Join here:
https://gitter.im/erikras/redux-form

Just say my name (@hedgerh) so it will ping me.

**Comment by ooflorent** [comment]
Hi, thanks for coming by.

This is a usage question, and we encourage you to ask it on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

I’m closing for these reasons.
