### ISSUE TITLE
Add to form field after successful ajax call

### ISSUE THREAD

**Issue by TonyVeigel** [erikras/redux-form#845]
For instance, I make a ajax call to get a couple names, I now want to populate an array form field with those names. I tried using the plugin but when I declare the field in the form, it seems to clear the recipients. Any suggestions? Thanks

plugin code:
```
    case constants.GET_RECIPIENTS:{
      return{
        ...state, recipients:action.recipients
      }
    };
```

**Comment by ooflorent** [comment]
Hi, thanks for coming by.

This is a usage question, and we encourage you to ask it on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

I’m closing for these reasons.
