### ISSUE TITLE
Calculate `form` id from ownProps

### ISSUE THREAD

**Issue by jcalfee** [erikras/redux-form#846]
Does the API easily support multiple forms of the same component but different state?

I'm looking to do this in a flexible way so that I may calculate `form` id from ownProps without having to burden the user of the component.  

So, I would like to move `form` down into `mapStateToProps` like this:

```js
export default reduxForm(
        // config
        {/*form: editorId*/},

        // mapStateToProps
        (state, ownProps) => {
            return { form: ownProps.a + '-' + ownProps.b }
        }
)(MyComponent)
```

When I do this, however, the submit button does not trigger the form onSubmit event.  I tried to wrap this in another component instead, that got a little tricky I was not able to get it to work.

Is this a feature you support or do you an example of how to do this?

**Comment by jcalfee** [comment]
I'm just making a reusable form component. It needs its own unique form ID.  I guess this is more of a about export syntax so I'll close for now.

**Comment by erikras** [comment]
Important: Any config param to `reduxForm()` can be specified as a prop to your decorated form component. Including `form`.

So you could just have `reduxForm()(MyComponent)`, and then later do
```js
<MyComponent form="myForm"/>
```

**Comment by jcalfee** [comment]
Thanks @erikras .. Looks like any property except for `form` can be specified... On another topic, I just found this works:
```
export default formId => reduxForm(
    // config
    { form: formId, fields, validate },

    // mapStateToProps
    (state, ownProps) => {
        ....
    }
}
```

**Comment by jcalfee** [comment]
never-mind .. just retested it does work..

**Comment by jcalfee** [comment]
thanks @erikras
