### ISSUE TITLE
React Checksum Invalid - TextArea

### ISSUE THREAD

**Issue by albertdatui** [erikras/redux-form#85]
Hi guys!
I am having this error when using textarea with redux-form.
I am completely new to react and redux.

```Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:```

 ```(client) $=12:0.0.0.2.0.0.6">
</textarea><br data```

``` (server) $=12:0.0.0.2.0.0.6"></textarea><br data-```

Any help will be much appreciated.

Thanks!

**Comment by erikras** [comment]
That warning is a common bump along the React road, but I'd be very surprised if react-form was the culprit.

**Comment by albertdatui** [comment]
ohh okay. Thanks for your response. :)
