### ISSUE TITLE
"Reusable system of validators", array validator?

### ISSUE THREAD

**Issue by tylercollier** [erikras/redux-form#852]
In the [synchronous validation example](http://redux-form.com/5.1.3/#/examples/synchronous-validation?_k=wfeonu), you mention:

> In your application, you will want to build some type of reusable system of validators.

And then you link to [these example validators](https://github.com/erikras/react-redux-universal-hot-example/blob/master/src/utils/validation.js) from the react-redux-universal-hot-example project.

I was wondering if there's a canonical or de facto list of validators, aside from that example? While I know you couldn't create every validator anyone *might* want, I was surprised to see an array validator missing from the example.

Do you find yourself writing your own validators? Or do you get away with plugging in some third-party library out there like (just from a quick google) [Parsley.js](https://github.com/guillaumepotier/Parsley.js/) or [validator.js](https://github.com/chriso/validator.js)?

**Comment by tylercollier** [comment]
I ended up writing my own `arrayValidator` and it was harder than I thought, so I wanted to leave it for others, or ideally contribute it to that example list of validators if you think it belongs there.

> I'm wondering if this is a good way to do it. If there's a better approach, that's more reason I'd think to have an array validator in that example list.

```javascript
export function arrayValidator(rules) {
	return (data = []) => {
		const errors = [];
		const validator = createValidator(rules);
		data.forEach(value => {
			const error = validator(value);
			if (error) {
				errors.push(error);
			}
		});
		return errors;
	};
}
```

If your list of fields looks like this:

> In this example, we are prompting the user for a list of character names and genders

```javascript
const fields = [
	'characters[].name',
	'characters[].gender'
]
```

Then you would set your validations like this. Note the use of `arrayValidator`. (The `formValidations.required` is from the example list of validators.)

```javascript
const CharacterPrompt = reduxForm({
	form: 'characterPrompt',
	fields: fields,
	validate: formValidations.createValidator({
		characters: formValidations.arrayValidator({
			name: [formValidations.required],
			gender: [formValidations.required]
		})
	})
})(CharacterPrompt)
```

**Comment by erikras** [comment]
I only know of one validation library specifically written with `redux-form` in mind, and that's [`revalidate`](https://github.com/jfairbank/revalidate). But I've heard of other people making other libraries, like [`joi`](https://github.com/hapijs/joi), work. Compiling a list of validation libraries, and evaluating how well they work with `redux-form` might be a good markdown document to have in this repo.

@tomduncalf tweeted about some research he did on this. I think he concluded that [Yup](https://github.com/jquense/yup) is the best for his needs, but it's async only.

**Comment by tomduncalf** [comment]
I've been meaning to write up how I've been doing validation with yup for a while now, as I am pretty happy with it (for more complex validation especially), so this might be the excuse I need :) Will put some examples together and try to post it up later on today.

**Comment by M3lkior** [comment]
For information, These helpers also works in v6. Thanls @erikras

**Comment by Geczy** [comment]
In my case simply doing this worked:

```js
const validate = createValidator({
  email: createValidator({ email_from: [required], subject: [required] }),
})
```
