### ISSUE TITLE
Feature Request: submitSucceed prop

### ISSUE THREAD

**Issue by aight8** [erikras/redux-form#853]
Because when submitFailed is false it's not necessary submitted and valid.

**Comment by aight8** [comment]
**dump**
Easy use case:
I wan to show a success message when the user successful submitted a form. When submitFailed don't necessary means it's submitted too. Is there a redux-form way to solve this? (without set an own state)

**Comment by ooflorent** [comment]
Have you tried using `onSubmitSuccess`? It was added [v5.1.0](https://github.com/erikras/redux-form/releases/tag/v5.1.0). It is not a boolean flag but a callback that gets invoked once the submit has succeeded.

**Comment by aight8** [comment]
Its not in v6. But beside that, why there is no submitSuccess property.
There is on submitFail, on  submitSuccess callback but only a submitFailed property. Why isn't the submitSucess property exists too?

**Comment by ooflorent** [comment]
Feel free to submit a PR to add it! I'll happily review it!

**Comment by kevzettler** [comment]
is this the same idea as https://github.com/erikras/redux-form/issues/94#issuecomment-224716048 ?

**Comment by gustavohenke** [comment]
Done thanks to #1428.

Happy new year, guys!
