### ISSUE TITLE
Undefined values with polymorphic datastructure on submit

### ISSUE THREAD

**Issue by beku8** [erikras/redux-form#854]
I have a dynamic polymorphic data structure, which means nested fields defined, doesn't have to exist. For example

```
  'elements[].type' // either duration or participant
  // here are "duration" fields, should not contain any "participant"
  'elements[].duration.startDate',
  'elements[].duration.endDate',
  // here are "participant" fields, should not contain any "duration"
  'elements[].participant.type',
  'elements[].participant.argumentValues[].value',
```

I just recently upgraded from v3.1.\* to 5.1.0. This used to work fine, but on the form submission I will get undefined values(e.g "duration":undefined for participant object), which I need to clean up manually. Is it expected behaviour? Is there anyway to configure it? Thank you.

**Comment by erikras** [comment]
Interesting... If you could [write a test](https://github.com/erikras/redux-form/blob/master/src/__tests__/createReduxForm.spec.js) to recreate this, that would be very helpful.
