### ISSUE TITLE
Error with Immutable Form example v6

### ISSUE THREAD

**Issue by NgoKnows** [erikras/redux-form#855]
I was trying out the example in for the Immutable Form from the v6 docs and I was getting this error `_immutable.reducer.validation is not a function`, so I pulled down the examples from the repo directly and I got the same error.

**Comment by erikras** [comment]
Thanks! Error on my part.

**Comment by mihirsoni** [comment]
@NgoKnows  Please verify , if it works please close the issue.

**Comment by erikras** [comment]
Yes, this is fixed. Was also broken on `asyncValidation` example.
