### ISSUE TITLE
Persistent input values accross the app

### ISSUE THREAD

**Issue by Ezekiah** [erikras/redux-form#856]
Hello,

Sorry I have a noob question, I wonder how I can make my form input values persistent across all my app
For example in the demo when we fill the survey and then we change the page and go back to the form, all the values are resetted, how can we "record" the survey input values so that if we change to anypage and go back we keep the input values filled.

Thanks.

**Comment by erikras** [comment]
```js
reduxForm({
  form: 'myForm',
  // ...
  destroyOnUnmount: false // <------------- like this
})(MyForm)
```

**Comment by Ezekiah** [comment]
Oh my gosh its magic, thanks :)

**Comment by Ezekiah** [comment]
Hi again, and do you how can i do if I want to persist form values if the user reload the page with F5 ? Data should be stored in express session I think ?
