### ISSUE TITLE
Lodash in v6

### ISSUE THREAD

**Issue by anaibol** [erikras/redux-form#859]
Hi, putting the new version has highly increased the build size (more than 100kb) due mainly to Lodash:
Can we make the dependencies optional? Object.assign polyfill could be also optional. 
![selection_022](https://cloud.githubusercontent.com/assets/3210177/14791542/9b11dd94-0b16-11e6-8594-2c789ceec1bb.png)

**Comment by erikras** [comment]
Two of them were superfluous (see above commit). [The others](https://github.com/erikras/redux-form/blob/v6/package.json#L47-L51) are used, aside from `noop`, which is the most hilarious "dependency" ever.

I'm not an `npm` expert, so I don't really know what you mean by making them "optional". How would I go about that?

**Comment by anaibol** [comment]
Well, maybe "optional" is not the right term. Due the overweight of adding these dependencies I would say to rewrite where they are been used.
Lodash is becoming really fat even if you load parts of it.
Sorted by asc size:

 [239] ./~/lodash.rest/index.js 8.22 kB {0} [built]
 [235] ./~/lodash.every/index.js 9.56 kB {0} [built]
 [236] ./~/lodash.mapvalues/~/lodash.keys/index.js 11.9 kB {0} [built]
 [232] ./~/lodash._baseeach/index.js 14.5 kB {0} [built]
 [105] ./~/lodash._stringtopath/index.js 19.1 kB {0} [built]
 [234] ./~/lodash._createwrapper/index.js 25.7 kB {0} [built]
 [104] ./~/lodash._baseiteratee/index.js 54.2 kB {0} [built]

Lodash gives some abstraction and helpfull utils but I am not sure it worth the cost.

**Comment by erikras** [comment]
Okay. Good info. In `v5`, I had [written `mapValues` myself](https://github.com/erikras/redux-form/blob/master/src/mapValues.js), which is about as trivial an exercise in iteration as you can get, but I leaned on lodash to cut some corners on `v6`, and I thank you for speaking up about it.

**Comment by anaibol** [comment]
So you think it will keep lodash? This library is becoming the defacto form management mechanism with React, like if React had jQuery as dependency but in this case it's like 100kb.
I don't know much of the Redux Form code, but I could try to remove that dependency.

**Comment by erikras** [comment]
Those kilobyte sizes you posted above are ridiculously bloated for the functionality that lodash is giving this library. They should be removed (implemented locally). Thank you for pointing this out.

**Comment by erikras** [comment]
[I ❤️ the spread operator!](https://github.com/erikras/redux-form/blob/v6/src/util/partial.js) 😀

**Comment by anaibol** [comment]
Great! That's an extreme usage lol

**Comment by erikras** [comment]
@anaibol You should know that we've gone back to `lodash` for some stuff. #929

**Comment by anaibol** [comment]
Cool, I will see on the next v6 release if there is a huge weight difference xD

**Comment by erikras** [comment]
Check out [`v6.0.0-alpha.8`](https://github.com/erikras/redux-form/releases/tag/v6.0.0-alpha.8).

**Comment by anaibol** [comment]
Well, in fact it has increased notably (40 - 50 kb), not as much as before but well, it seems that each lodash module have strong dependence between them. Am I the only
