### ISSUE TITLE
add onUpdate in addition to onChange

### ISSUE THREAD

**Issue by nikgraf** [erikras/redux-form#86]
redux-form unfortunately doesn't work with Belle's custom components. To be honest I haven't tried yet, but the only event we don't implement as far as I know is `onChange`. Here the issue: https://github.com/nikgraf/belle/issues/188

We decided to go for `onUpdate` as a standard rather than `onChange`. This is because using native events properly cross-browsers is hard to do and prune to many errors. On the other hand we didn't want to re-implement the custom event objects with all their details. We also decided against implementing an incompatible `onChange` behaviour. see a more detailed post here: https://github.com/nikgraf/belle/issues/58

Would you be willing to implement `onUpdate` next to `onChange` or is something you rather not have in there? I'm happy to submit a PR.

kind Regards

**Comment by erikras** [comment]
Sounds reasonable. Done. [v1.7.0](https://github.com/erikras/redux-form/releases/tag/v1.7.0).

**Comment by nikgraf** [comment]
Wow, thank you very much :+1:
