### ISSUE TITLE
changing initialValues must overwrite current field values by default

### ISSUE THREAD

**Issue by kromit** [erikras/redux-form#862]
Since 5.1.2 the the known behavior of `initialValues` was changed/broken I would like to know a way to reuse an existing form.

There are at least two use cases when the form values must be overwritten by `initialValues`:
1. The form is rendered with disabled input fields and loading indicator during async loading.  Current empty values must be overwritted by `initialValues` applied from async loaded redux state.
2. The form is displayed along with an item list. Selection from the list changes `initialValues` and should overwrite any user input.

The "Initializing From State" can be extended with a second load button with a different data set to demonstrate the expected behavior. 

On the side note: I still do not get why such a breaking change was  introduced in a bugfix instead of a major release since every version until 5.1.2 was working that way. I've looked into #370 and #832. and I must say that there is no such thing like the "right"  behavior. There is only a "least wrong" behavior since the majority of people who are satisfied with currently working behavior do not create/comment on tickets about how satisfied there are, but they also must be taken into account when changing things.

**Comment by erikras** [comment]
> There is only a "least wrong" behavior since the majority of people who are satisfied with currently working behavior do not create/comment on tickets about how satisfied there are, but they also must be taken into account when changing things.

👍 Excellent point.

**Comment by aight8** [comment]
I have exactly the same use case. Happy to see that this way comes back to set new init values. 👍

**Comment by erikras** [comment]
Okay, so it'll have to be a config param. Check out [`v5.2.1`](https://github.com/erikras/redux-form/releases/tag/v5.2.1). You guys won the "default" side of the issue, and those in #832 will have to provide a config parameter to achieve their desired behavior.

**Comment by kromit** [comment]
@erikras Oh wow. THAT was fast! Many thanks for what you are doing.

**Comment by kpdecker** [comment]
Hopefully this doesn't sound too annoyed, but all of the users that deployed the 5.1.3 behavior just got the same breaking change that is complained about in this bug. No real issues with the change but it would be nice if we could follow semver for these sorts of things (I know it's hard, github.com/wycats/handlebars.js was a constant stream of complaints like mine when it was under active development)

**Comment by kpdecker** [comment]
Also would like to add a thank you to @erikras, you are amazingly responsive on this project, so I hope the above comment comes off as constructive and not just complaining :)

**Comment by aight8** [comment]
Are there plans to use this logic in v6 too?

**Comment by erikras** [comment]
@kpdecker Yes, I do try to follow semver, and I feel bad about breaking it with these two updates, hence my scramble to unbreak the change. Since I've already started releasing alphas of the next major version, semver has put me in an awkward spot. Constructive criticism accepted. :-)

@aight8 I plan on `v6` behaving as close to `v5` as possible when it is released, so yes.
