### ISSUE TITLE
this.props.fields.[field].onChange on v6

### ISSUE THREAD

**Issue by anaibol** [erikras/redux-form#867]
On the previous version I used 
```javascript
change = e => {
    this.props.fields.type.onChange(e)
    this.props.handleSubmit()
}

render() {
    return <input onChange={this.change}>
}
```
How should I trigger a field change and form submit at the same time? this.props.fields.type.onChange(e) on the new version?
I am working with wizard forms (multiple redux-forms with same form id) that need to go to next step when an option is selected, without submit button.

**Comment by erikras** [comment]
```js
class MyForm extends Component {
  render() {
    const { handleSubmit } = this.props
    return (
      <div>
        <Field name="type" component={type => 
          <input {...type} onChange={e => {
            type.onChange(e)
            handleSubmit()
          }}/>
        }}>
      </div>
    )
  }
}
```
How's that?

Thank you for kicking the tires on `v6`.

**Comment by anaibol** [comment]
Thanks to you!

**Comment by anaibol** [comment]
And to get values from a "next step"?

I am using ```@connect```:
```javascript
@connect(state => ({ type: state.form.adWizard.values.type }))
@reduxForm({ form: 'adWizard' })
```
Previously I was getting the values from props: ```this.props.type```

**Comment by erikras** [comment]
Yes, your code is correct. I'm considering [exporting some selectors](https://github.com/erikras/redux-form/issues/841#issuecomment-214755109) to make it easier.

**Comment by anaibol** [comment]
Cool
