### ISSUE TITLE
Validate that a nested key has children

### ISSUE THREAD

**Issue by rvirani1** [erikras/redux-form#868]
If I have a number of children elements nested as items, how do I write a validation that at least one child exists?

For example, if my fields look like the following:
```
export const fields = [
   'date',
  'items[].itemType',
  'items[].size',
  'items[].flightsOfStairs',
  'place',
  'startTime'
];
```

How do I validate that there is at least one item?

**Comment by erikras** [comment]
There is not currently a way to attach an error to an array, since arrays aren't really fields. #486 #762

The current least-worst solution is to use the form-wide `_error` key.

**Comment by rvirani1** [comment]
Got it. I can make that work for now.

**Comment by erikras** [comment]
Good news! Array validation errors in [`v6.0.0-alpha-7`](https://github.com/erikras/redux-form/releases/tag/v6.0.0-alpha.7).
