### ISSUE TITLE
Validation is not working in v5.1.3

### ISSUE THREAD

**Issue by gsklee** [erikras/redux-form#872]
I followed the [example](http://redux-form.com/5.2.1/#/examples/synchronous-validation?_k=h0e9a1) but it never worked. There's simply no `error` property appearing under the field object even if my validating function is returning an object full of errors.

**Comment by erikras** [comment]
Well, [the version of that example using `v5.1.3`](http://redux-form.com/5.1.3/#/examples/synchronous-validation) seems to be working. Maybe share some code?

**Comment by gsklee** [comment]
@erikras It's not about versions as both of the examples look exactly identical.

I setup my code exactly as yours do and simply did not see `username.error`, `email.error`, etc. - they are just not there. And I examined your example with your on-site `redux-tool` - they're not there inside the state tree as well. I simply don't understand how your example code could work despite the states were not there.

**Comment by gsklee** [comment]
![http://i.imgur.com/S5PAHRx.png](http://i.imgur.com/S5PAHRx.png)

`email.error` is not there but your app has the information - how is that possible??

**Comment by gsklee** [comment]
AFAIK mine's not working.

**Comment by gsklee** [comment]
Found the issue, nevermind!
