### ISSUE TITLE
Is there a way to reset a form from Container without knowing the name of the form

### ISSUE THREAD

**Issue by thomasmery** [erikras/redux-form#873]
Hi,

I 'need' to reset a form from its Container component and at the moment it seems like it's necessary to call : 

`this.props.reset('submitFromParent')`

as it is shown here : http://redux-form.com/4.2.0/#/examples/submit-from-parent

is there a way I can do this without knowing the 'name' of the Form

like I can do with submit?

feels strange to mix the way I access the form methods

thanks

**Comment by erikras** [comment]
There is not currently a way to do that, no.

**Comment by thomasmery** [comment]
thanks!

But do you understand how  would expect it to work the same way `submit()` does?

**Comment by erikras** [comment]
Yes, I do.

**Comment by thomasmery** [comment]
thanks! 

closing then.
