### ISSUE TITLE
redux-form@6.0.0-alpha.4 can not compatible with webpack2

### ISSUE THREAD

**Issue by zhuzhenzhen** [erikras/redux-form#875]
redux-form@6.0.0-alpha.4 can not compatible with webpack2

**Comment by zhuzhenzhen** [comment]
redux-form@6.0.0-alpha.4 can not compatible with webpack2

**Comment by erikras** [comment]
Can you explain? Error messages?

**Comment by anaibol** [comment]
I am using it with webpack@2.1.0-beta.5 and it seems to work very good!

**Comment by aight8** [comment]
Works here too.

**Comment by ooflorent** [comment]
I'm closing this issue bacause we are not able to reproduce it.
If the problem persists, could you please reopen it and join your `package.json` and the error log?
