### ISSUE TITLE
Two different ways to validate a form depend on two different buttons.

### ISSUE THREAD

**Issue by ErrorPro** [erikras/redux-form#876]
Hi to everybody. Is it possible to have two different validations? So i have two buttons on my form and i want to invoke a different validation for each of them.

**Comment by ooflorent** [comment]
Please try to use StackOverflow for questions using the tag `redux-form`.

- - -

Current API only supports one `validate` callback. However you can write it in a way that it chooses the right validator. The easiest way is to check for a special value:

```js
function validateA(values) { /* ... */ }
function validateB(values) { /* ... */ }

function validate(values) {
  if (values.__type === "A") {
    return validateA(values)
  } else {
    return validateB(values)
  }
}
```

The above solution reads the value of the `__type` field and apply the correct validator. According to your question, you are not depending on any field so you have to trick `validate`.

```js
import {reduxForm, change} from "redux-form"

reduxForm(
  {
    form: "myform",
    fields: ["__type"],
    validate,
  },
  null,
  {
    change,
  }
)(
  class MyForm extends React.Component {
    handleSubmit(type) {
      this.props.change("__type", type)
      this.props.handleSubmit()
    }

    render() {
      return (
        <div>
          <button onClick={() => this.handleSubmit("A")}>Case A</button>
          <button onClick={() => this.handleSubmit("B")}>Case B</button>
        </div>
      )
    }
  }
)
```
