### ISSUE TITLE
Missing initialState in reducer.normalize

### ISSUE THREAD

**Issue by jimpick** [erikras/redux-form#88]
When trying to use reducer.normalize, I was getting this error:

Uncaught TypeError: Cannot read property 'myField' of undefined

Tracing it down, it seems that initialState isn't getting set in reducer.normalize.

I wrote a test and a fix, in pull request #87

**Comment by erikras** [comment]
Fixed by #87, published to [v1.6.8](https://github.com/erikras/redux-form/releases/tag/v1.6.8).
