### ISSUE TITLE
v6: Promise based submit validation errors not processed (solved)

### ISSUE THREAD

**Issue by aight8** [erikras/redux-form#880]
Promise based validation not works in v6.0.0-alpha.5.

Here the submit handler which I used. Tested in reduxForm({}) **or** passed in the container component.
```
onSubmit: () => {
        return new Promise((resolve, reject) => {
               reject({
                      _error: 'Some error',
                       job_title: 'Not valid!'
               });
        })
 },
```

The START_SUBMIT and STOP_SUBMIT action is fired on submit but without the errors. So no errors will show up.

The sync validate method works, when I just return the error object.

**edit:** I tried now to catch the promise directly and fire the SubmissionError exception. Then it works.

```
return new Promise((resolve, reject) => {
            .... reject(error)
        }).catch(errors => {
            throw new SubmissionError(errors);
        });
```

So there are two steps:
You MUST return a promise and you MUST throw the SubmissionError exception with the errors (in the catch block) to return some errors. The second step is little bit unnecessary because I only reject promise with errors when there was an input error. When there was an API error I reject it without errors?

**edit:**
Okey solved I found the way. I just call reject(new SubmissionError({...})). I first try to throw directly the SubmissionError. Don't know that that this works. So problem solved :) 👍

**Comment by erikras** [comment]
So, is there a problem? Maybe a problem in the docs? It sounds like you found your way to where you want to be.
