### ISSUE TITLE
v6 form onChange

### ISSUE THREAD

**Issue by aight8** [erikras/redux-form#883]
I would like to listen if the form changes some value. Then submit myself the form at every change (there are not text inputs but checkboxes etc.) I look at the easiest solution.. but I figured out that I have to listen at Field component level on changes, wrap the field props onChange and execute the handleSubmit method after it executes the fields onChange method one.

Maybe we can introduce a onChange method in the reduxForm configuration?

So #806 this issue could be solved too with this

**Comment by erikras** [comment]
So the form does a deep-equal check in `componentWillReceiveProps` and if the values have changed and it has an `onChange` prop, it calls `this.props.onChange(values)`?

Seems doable.

**Comment by aight8** [comment]
yap when it not eats to much performance. Don't know exactly the inner architecture, but already analyzing it :)

Currently this is my workaround:
```
<Radio
   {...field}
   onChange={value => {
      field.onChange(value);
      handleSubmit();
   }}
   options={options}
 />
```
To every field.

**Comment by aight8** [comment]
Oh no, it not works this way neither. When handleSubmit executes the onSubmit in the reduxForm it receives the old values before ```field.onChange(value);```is called.

An idea how to solve that? 🎃

**Comment by erikras** [comment]
This is a common mistake. I really should make a FAQ about this. It looks reasonable and declarative, but `handleSubmit` submits the values as they currently are in the `props`, and the `props` don't get updated from Redux until the next process tick. You have two options; pick that which least disgusts you.
```js
<input {...field} onChange={event => {
  field.onChange(event)
  setTimeout(handleSubmit)
}}/>
```
or
```js
<input {...field} onChange={event => {
  field.onChange(event)
  handleSubmit(values => {
    this.props.onSubmit({
      ...values,
      myField: event.target.value // <--- manually insert this field's value into submitted json
    })
  })
}}/>
```

**Comment by paulshen** [comment]
Thanks for the reply! In case you're following along (like I was), the last snippet should be

```javascript
handleSubmit(values => {
  this.props.onSubmit({
    ...values,
    myField: event.target.value
  });
})(); // add parentheses here
```

**Comment by erikras** [comment]
Thanks. Updated my comment.

**Comment by nktssh** [comment]
@erikras thanks for sharing this. You should definitely add this in FAQ!
But what if I want to fire callback only if the value is valid (e.g. no `error` passed to component via `validate` function)? How I can handle this situation?
Manually calling the validate function seems a little bit overhead...

**Comment by calvinfroedge** [comment]
I think it would definitely be useful to have a change handler at the form level.

**Comment by enkay** [comment]
Option 1 doesn't seem to work, and with option 2 is there a reason the input field would lose focus after submit?

**Comment by miracle2k** [comment]
Man, React form handling sure sucks.

What lead me to this ticket is that my submit button is outside of my form component. I want to access properties like "dirty" or "anyTouched" to decide whether to show the save button at all, or whether to disable it.

Things I've considered (both of them feel unclean):

1. Move the reduxForm decorator to the parent container, using `propNamespace` to easily pass down the form props to the actual form component. This is my preferred solution, but decoupling the form and the @reduxForm config seems wrong.

2. @connect manually to the store to get the data I want; but that means I cannot access instance-calculated state like "dirty" - it's not in the store.

**Comment by yourfavorite** [comment]
@erikras Any tips on how to handle this onChange treatment in your comment above now that input is out and Field is in? What I have below obviously doesn't work. I'm unsure how to reference the exiting redux-form onChange event.

```javascript
            <Field
              name="freq"
              component="input"
              type="number"
              onChange={event => {
                Field.onChange(event);
                updateSite();
              }}
            />
```

**Comment by oyeanuj** [comment]
@erikras Did this make it to 6.0 release?

**Comment by erikras** [comment]
> Did this make it to 6.0 release?

It did not, I'm afraid. But it's still got the Enhancement tag, and I filter by that when deciding what to implement next.

**Comment by pezza3434** [comment]
For @yourfavorite and for anyone else having this issue, you need to do something like this: 

`const renderField = (field) => (
    <input {...field.input} type="text" onChange={(e) => {
        field.onChangeAction(field.input.value);
        field.input.onChange(e);
    }}/>
);

const SearchFormComponent = React.createClass({
    componentDidUpdate() {
        if(this.props.searchActive) {
            ReactDOM.findDOMNode(this.refs.search).focus();
        }
    },
    render() {
        return (
            <div>
                <span className="search__input">
                    <Field name="search" onChangeAction={this.props.onChangeAction} component={renderField} ref="search" />
                </span>
            </div>
        )
    }
});`

**Comment by srosset81** [comment]
Thanks @pezza3434! But instead of `field.input.value`, you need to use `e.target.value`, otherwise you won't get the actual value of the field, but the previous one.

Here's the solution I use:

```javascript
export class Input extends Component {

    updateValue(e) {
        this.props.onChangeAction(e.target.value);
        this.props.input.onChange(e);
    }

    render() {
        const {input, label, type, meta: {asyncValidating, touched, error}} = this.props;

        return (

            <div className={`form-group ${touched && error ? 'has-error' : ''}`}>
                <label className="control-label">{label}</label>
                <div className={asyncValidating ? 'async-validating' : ''}>
                    <input type={type} className="form-control" {...input} onChange={this.updateValue.bind(this)}/>
                </div>
                <div className="help-block">
                    {touched ? error : ''}
                </div>
            </div>
        );
    }
};
```

**Comment by Billy-** [comment]
@pezza3434 I have used your implementation and it works - except the first input on an empty field causes the field to be de-focused. Does anyone have any idea why this might be? Here's my code:

``` JSX
import React from 'react'
import { connect } from 'react-redux'
import { Field, reduxForm, formValueSelector } from 'redux-form'
import { submitSettings } from '../actions/settingsActions'

let Settings = (state) => {
	const renderField = (field) => (
		<input {...field.input} onChange={(e) => {
			field.onChangeAction(field.input.value)
			field.input.onChange(e)
		}}/>
	)
	console.log(state)
	let { handleSubmit, onSubmit, onChange, settingsData } = state
	let submit = handleSubmit(onSubmit)
	return <form onSubmit={submit}>
		<h2>Settings</h2>
		{ state.isLoading && <p>Loading...</p> }
		{ state.errorMsg && <p><b>{state.errorMsg}</b></p> }
		<label>Repository (user/repo)
			<Field name="repo" component={renderField} type="text" onChangeAction={_ => onChange(submit)}/>
		</label>
		<label>Hook secret
			<Field name="secret" component={renderField} type="text" onChangeAction={_ => onChange(submit)}/>
		</label>
	</form>
}
Settings = reduxForm({form: 'settings'})(Settings)

const mapStateToProps = (state, ownProps) => {
	return { ...state.settings.form }
}

let t
const mapDispatchToProps = (dispatch, ownProps) => {
	return {
		onSubmit: (formData) => {
			console.log('Form submit')
			//dispatch(submitSettings(formData))
		},
		onChange: (submit) => {
			console.log('onChange')
			clearTimeout(t)
			t = setTimeout(submit, 1000)
		}
	}
}
Settings = connect(mapStateToProps, mapDispatchToProps)(Settings)

export default Settings
```
Here's the redux logger output:
![image](https://cloud.githubusercontent.com/assets/4316168/20529409/ec47719a-b0c7-11e6-8886-e8414f91d5db.png)

**Comment by Billy-** [comment]
Please see http://dl-sc-issues.uel.ac.uk/ for live replication of issue - create a user and you will be taken to the "settings" page, which exhibits this bug. Just try entering multiple characters into either field.

**Comment by Billy-** [comment]
Ok I have re-deployed in a droplet: http://178.62.30.69/ Redux dev tools is also enabled.

**Comment by Billy-** [comment]
Not sure how I didn't see #1094 before but that has helped me resolve the issue. Particularly [this comment](https://github.com/erikras/redux-form/issues/1094#issuecomment-229820291). The problem was that my `renderField` function was inside the render function for the component.

**Comment by oyeanuj** [comment]
@srosset81 @pezza3434 @aight8 @paulshen  Did you have a particular way of throwing or handling errors (SubmissionError) in the handleSubmit/onChangeAction function in the code above? I see my errors being swallowed..

**Comment by oyeanuj** [comment]
Actually, deleting my older comment as I got that issue to work. 

So, in case, anyone ends up here trying to make the comments above work for v6, with `handleSubmit`, here is the snippet that works for me.

```js

//This example uses react-debounced-input but it can be any custom component instead.

renderDebouncedInput = (field) => {
  const { handleSubmit, onChangeSubmit } = this.props;

  return (
    <DebounceInput
      debounceTimeout = {500}
      onChange = {(e) => {
      
         //call input.onChange before handleSubmit 
         //if you are relying on the dirty flag in the update function

        field.input.onChange(e); 
        handleSubmit((values, dispatch, props) => {
          const newValues = values;
          newValues[field.name] = e.target.value; //ensuring values has the latest value
          
          //Make sure to return the value of your update function 
          //so that SubmissionError doesn't get lost
          
          return onChangeSubmit(newValues, dispatch, props);
        })();
      }}
      value = {field.input.value}
    />
  );
};
```

Hope this helps someone!

**Comment by lhtdesignde** [comment]
I'm struggling with this as well. I tried a few things suggested here but nothing worked so far. I have a custom select.

```
export const renderSelect = ({input, meta: {touched, error, submitting}}) => (
  <div className={classNames('type-select', {'x-error': touched && error})}>
    <label htmlFor={`${formPrefix}-${input.name}`} className='label'>{label}</label>
    <select {...input}
           id={`${formPrefix}-${input.name}`}
           disabled={submitting}
           aria-required={ariaRequired}
           className={classNames('select', {'x-error': touched && error})}>
      {options}
    </select>
  </div>
);
```

So now i want to submit my select as soon as the value changes but it seems not to submit anything.
```
renderOptions() {
    const {
      submitting,
      handleSubmit
    } = this.props;
return (
      <Field
        name='currency'
        component={renderSelect}
        ariaRequired='true'
        loadingClass={loadingClasses}
        options={options}
        onChange={event => {
          field.onChange(event);
          setTimeout(handleSubmit);
        }}/>
);
}
```

debugging it, field is not defined but it's not even acknowledging the onChange. How do I do this the v6 way?

**Comment by oyeanuj** [comment]
@lhtdesignde You have to set up the `onChange` in your `renderSelect` function, like in my code example above. Initially, I was trying to do it like your code above, but that doesn't work. The `onChange` is available as `field.input.onChange`.

**Comment by lhtdesignde** [comment]
great, that worked! `onChangeSubmitAction` just hands over `handleSubmit`.

```
export const renderSelect = ({input, label, onChangeSubmitAction, meta: {touched, error, submitting}}) => (
  <div className={classNames('type-select', {'x-error': touched && error})}>
    <label className='label'>{label}</label>
    <select {...input}
           disabled={submitting}
           aria-required={ariaRequired}
            onChange={event => {
              input.onChange(event.target.value);
              setTimeout(onChangeSubmitAction);
            }}>
      {options}
    </select>
  </div>
);
```

**Comment by egeste** [comment]
Oh god. I need this.

**Comment by egeste** [comment]
Pull request here https://github.com/erikras/redux-form/pull/2530

**Comment by erikras** [comment]
Fix published in [`v6.6.0`](https://github.com/erikras/redux-form/releases/tag/v6.6.0).

**Comment by Abhijeetjaiswalit** [comment]
@oyeanuj @erikras is there any way to bind default value to react-select field? I' using following value property but it is coming blank on select side.: 

Here is my select ; 

 ```
<Select
                    {...props}
                    value={field.input.value || ''}
                    onChange={(value) => field.input.onChange(value)}
                    options={field.options}
                />
```

here is my redux-form component:

```
<Field
                                      name="province"
                                      component={renderSelectFields.renderselectField}
                                      value={this.state.provinces}
                                      onChange={this.onProvinceChange.bind(this)}
                                      options={this.state.provinceOptions}
                                    />
```

can someone please help me?

**Comment by iOiurson** [comment]
I have tried over and over again to apply this based on your examples, and it still does not work on my side (with v6.8.0).
Is it possible to have some proper documentation on this `onChange()` feature that allows the field to update before the form actually submits ?
