### ISSUE TITLE
Add contribution guidelines

### ISSUE THREAD

**Issue by ooflorent** [erikras/redux-form#884]
With the large adoption of Redux Form, the issue tracker has become the place where developers try to gather support from the community. Lots of issues could have been asked on StackOverflow whose search engine is far better than GitHub's one. This a sad. Some good questions and answers may be lots because newcomers may not find them.

In order to drag the community to more convenient support products (StackOverflow, Reactiflux) it seems mandatory to me to add contribution guidelines to this project (`CONTRIBUTING.md`) and probably a code of conduct (like @reactjs projects).

`CONTRIBUTING.md`...
- MUST explain when, where and how to create an issue
- MUST explain how to submit a PR
- SHOULD explain how to setup, build and test Redux Form code
- SHOULD describe the used code style

[Redux](https://github.com/reactjs/redux/blob/master/CONTRIBUTING.md) and [Elasticsearch](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md) have really good `CONTRIBUTING` files!

I'm creating this issue to gather feedback on this.

**Comment by mihirsoni** [comment]
@ooflorent  This is good, also it would be good to put code architecture / flow  how things work and what things are meant for what. It would be really amazing for new comers  to contribute to the code , or we can also have `Good First Task` Label.

**Comment by gustavohenke** [comment]
Already done by #1000 😜
