### ISSUE TITLE
Submit Validation does not clear `Login failed!` message

### ISSUE THREAD

**Issue by jcalfee** [erikras/redux-form#889]
http://redux-form.com/5.2.1/#/examples/submit-validation?_k=dpmq4k

What is the recommended way to clear the `Login failed!` message?  In the example above, once the user starts editing the form again that message is no longer valid.

**Comment by mihirsoni** [comment]
@jcalfee currently you can't do that as `_error` is already set and it will not go until you have another successful submit. You are correct , it is no longer valid but in any login screen if you retype the message doesn't go aways. Like try logging in gmail.

**Comment by jcalfee** [comment]
We just need to know if it is touched... So, this is the current display:
```js
<div className="error">{error}</div>
```
Adding another object should do the trick:
```js
<div className="error">{_error.touched && _error.value}</div>
```
End user experience is the think to consider here.

**Comment by erikras** [comment]
Yes, a `CHANGE` action will remove the submit or async error from a _field_, but not for the whole form.

I recently added an [`anyTouched`](https://github.com/erikras/redux-form/issues/81#issuecomment-212823536) flag to `v6`. It sounds like what you want is an `anyTouchedSinceLastSubmit` flag that gets set to `false` on every submit fail, and set to `true` any time any field changes.

**Comment by jcalfee** [comment]
Yes it is.. Ok, I'll look at how you did that may be I can figure out how to do something like that on the current release.  Thank you..

**Comment by lauterry** [comment]
Hi @jcalfee 

Have you figured out how to implement a ```anyTouchedSinceLastSubmit``` in the 5.x release ?

Thx
