### ISSUE TITLE
Uncaught TypeError: syncValidate is not a function

### ISSUE THREAD

**Issue by geminiyellow** [erikras/redux-form#89]
somebody could help me?
i follow the README.md, and copy the code from it.
but, `Uncaught TypeError: syncValidate is not a function`, i dont know why.

**Comment by StanBoyet** [comment]
Hi @geminiyellow, 

You closed this issue, I guess you managed to solve it ? What was your way of doing this ?

Thanks,

**Comment by geminiyellow** [comment]
@StanBoyet oh, sorry, it is my fault, i not `exprot default validationFn`.
