### ISSUE TITLE
v6: Cannot call a class as a function (can't pass ES6 class into Field)

### ISSUE THREAD

**Issue by jaraquistain** [erikras/redux-form#891]
I'm not sure if this has already been addressed elsewhere (I did a cursory search and didn't find anything).

I'm finding that with `6.0.0-alpha.6` I am unable to pass a component defined using ES6 `class` syntax into the `Field` component.

The documentation indicates that this should not be a problem at all and yet when I pass my component into the `component` prop of `Field` I get the error `Cannot call a class as a function`

As a workaround I was able to do the following, for now:
```javascript
<Field name="q" component={props => <MyInput {...props} />} placeholder="Search Term" />
```

but I'd really prefer not to have to do that.

As for my component `EoInput` I was using it just fine with v5 so I'm inclined to think that the component itself is unlikely to be the issue. As a test I've also tried converting a few simple component functions into the `class` syntax and all of those gave me the same errors as well

**Comment by ooflorent** [comment]
@jaraquistain Could you give a little more detail about your setup? I'm asking this because there is a test case using an ES6 class and everything works OK...

https://github.com/erikras/redux-form/blob/v6/src/__tests__/Field.spec.js#L24-45

**Comment by jaraquistain** [comment]
@ooflorent Yeah I'll try to give more info below:

- App is based on the [react-redux-universal-hot-example](https://github.com/erikras/react-redux-universal-hot-example) boilerplate and isn't doing anything special as far as the store, containers or anything else. I've got a `SearchForm` component inside of my `App` container that is connected with `redux-form`. `SearchForm` contains 2 components: the `Field` component that is being passed my `AutocompleteInput` component and a submit button.

here's the stack trace of the erro when I changed `AutocompleteInput` to be the `TestInput` component used in the test.
 
```javascript
TypeError: Cannot call a class as a function
exports.default
/Volumes/Development/web-admin/node_modules/babel-runtime/helpers/classCallCheck.js:7:11
TestInput
SearchForm.js:21:1
ConnectedField.render
/Volumes/Development/web-admin/node_modules/redux-form/lib/ConnectedField.js:80:16
[object Object].ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext
/Volumes/Development/web-admin/node_modules/react/lib/ReactCompositeComponent.js:687:34
[object Object].ReactCompositeComponentMixin._renderValidatedComponent
/Volumes/Development/web-admin/node_modules/react/lib/ReactCompositeComponent.js:707:32
[object Object].wrapper [as _renderValidatedComponent]
/Volumes/Development/web-admin/node_modules/react/lib/ReactPerf.js:66:21
[object Object].ReactCompositeComponentMixin.performInitialMount
/Volumes/Development/web-admin/node_modules/react/lib/ReactCompositeComponent.js:291:30
[object Object].ReactCompositeComponentMixin.mountComponent
/Volumes/Development/web-admin/node_modules/react/lib/ReactCompositeComponent.js:222:21
[object Object].wrapper [as mountComponent]
/Volumes/Development/web-admin/node_modules/react/lib/ReactPerf.js:66:21
Object.ReactReconciler.mountComponent
/Volumes/Development/web-admin/node_modules/react/lib/ReactReconciler.js:39:35
```

Let me know if this is enough info or if you think it'd be worthwhile to see the code for my actual form

**Comment by ooflorent** [comment]
It's hard to diagnose the issue here...

> Let me know if this is enough info or if you think it'd be worthwhile to see the code for my actual form

Yes, it would help a lot!

**Comment by jaraquistain** [comment]
@ooflorent Ok I'm going to try an experiment today using as vanilla an implementation as possible to either confirm or rule out that the issue is being introduced by one of my other components. I'll post here with the info when I can

**Comment by jaraquistain** [comment]
Closing this ticket as I can no longer reproduce on newer versions of V6
