### ISSUE TITLE
Validate on blur

### ISSUE THREAD

**Issue by andrewQwer** [erikras/redux-form#894]
Hi, how can I validate form field synchronously on blur, not on change? Also async validation is triggering on both blur and submit, but can I trigger it only once ( either on blur or submit)?

Thanks in advance

**Comment by erikras** [comment]
That's not really an option. I guess that if you wanted to hide the errors when a field was in focus, you could do something like this:
```js
<input type="text" {...firstName}/>
{firstName.touched && firstName.error && !firstName.active && <span>{firstName.error}</span>}
```

**Comment by andrewQwer** [comment]
The problem is that sync validation occurs every time I enter characters in textbox. In case of complex validation rules typing goes with delay.

**Comment by erikras** [comment]
You have sync validation that is so complex that it's slow? Is your form huge? What sort of operation are you performing? `redux-form` was designed with the assumption that sync validation would be very fast operations, like string lengths, number or date ranges, or regex matches.

If your form is large, it might not be sync validation that is holding you up, but the rerendering of the entire form. This was the motivation for rewriting the core of `redux-form` from `v5` to `v6`, which is [still only in `alpha`](http://redux-form.com/6.0.0-alpha.5/docs/MigrationGuide.md/), unfortunately.

**Comment by andrewQwer** [comment]
Ok, got it! As there is no way to run sync validation on blur, maybe there is a chance to do async validate on submit/blur only? For example when I check for email to be unique I show message 'Validating...' during async validation, but it looks strange that the same email is validating again when I hit submit button. This email has already been validated so why we validate it again on submit?

**Comment by erikras** [comment]
> This email has already been validated so why we validate it again on submit?

This is a known issue. More about it here: https://github.com/erikras/redux-form/issues/888#issuecomment-216024016

**Comment by andrewQwer** [comment]
Thanks for your help!
