### ISSUE TITLE
Autosuggestion in redux-form

### ISSUE THREAD

**Issue by appbank2020** [erikras/redux-form#895]
Hi,
I am gonna make autosuggestion field for search suburbs in redux-form.
Can you provide me any sample?
I am using react-autosuggest 3.5.0 now.
Thank you very much.

**Comment by ooflorent** [comment]
This is a usage question, and we encourage you to ask it on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

This is the only way to ensure the same question doesn’t get asked many times in a row, and that folks who have the same question in the future will be able to find it.

I’m closing for these reasons.
