### ISSUE TITLE
InitialValues and array fields is not rendered on server side

### ISSUE THREAD

**Issue by beku8** [erikras/redux-form#896]
I'm trying to initialize my form with the value arrived from `async-connect`. From server, my form doesn't render so when I log the `fields` from the render method, it comes empty. But the `data` provided to the initialValues is not empty:

```
[1] form { panels: [] }
[1] data { formDto: 
[1]    { form: { panels: [Object] },
[1]      tripId: 'dmg1',
[1]      requestId: 'president' } }
```

I've updated to `5.2.3` hoping this was fixed with https://github.com/erikras/redux-form/issues/621, but probably it missed something with the Array fields?

**Comment by ooflorent** [comment]
Thanks for reporting the issue. Unfortunately I'm unable to reproduce the issue. Could you create a minimal gist so I would be able to further investigate?
