### ISSUE TITLE
How can I add properties to a field?

### ISSUE THREAD

**Issue by Darmody** [erikras/redux-form#899]
For example, I have fields like below:

```
 fields: [
  "teachers[].age"
 ]
```

then mapping `teachers[].age` to many `age` input fields.
Now I want to show teachers' name, currently I add a new field `teachers[].name` and render it like:
```
  <h1>{teacher.name.value}</h1>
```

In fact, I just want to show teacher's name, not to make it as a field, How can I achieve that?

**Comment by erikras** [comment]
```js
<h1>{this.props.initialValues.teachers[index].name</h1>
```
Like that?

**Comment by Darmody** [comment]
@erikras That works.
Inspired by your answer, I found `getValues(teachers[index]).title` works fine too.

But I still have to add `"teachers[].age"` to `fields`.

**Comment by ooflorent** [comment]
Editing a form does not force you to access only the form values! You could pass `teachers` props and read what you need.

**Comment by Darmody** [comment]
@ooflorent 

```
 <TeacherField {...fields.teachers[index]} teacher={teachers[index]} />
```

So I have pass field and teacher prop to my input component, right?

**Comment by ooflorent** [comment]
Yes, that's the idea.

**Comment by Darmody** [comment]
@ooflorent I see. thanks u guys.
