### ISSUE TITLE
V6: Error loading reducer state from immutable root state.

### ISSUE THREAD

**Issue by maxmantz** [erikras/redux-form#901]
I have the following reducer setup:

    import { reducer as formReducer } from 'redux-form';
    
    export default combineReducers({
       // my other reducers...
       form: formReducer
    });

Then in my store configuration, I use redux's `compose` to initialize the root state with an ImmutableJS object.
When I load the form on my page, I get the following error:

> routes.js:11Dynamic page loading failed Error: You need to mount the redux-form reducer at "form"

My setup has the reducer at `form`, my redux dev tools even shows it, see the screenshot:
![screenshot](https://cloud.githubusercontent.com/assets/6616421/14996943/ad91a5f0-117c-11e6-98e6-5135db1fb49d.png)

I suspect that because the root state object is also immutable, that redux-form can't find the form state.
I have used the `redux-form/immutable` imports for the form where needed.

**Comment by erikras** [comment]
Are you using [`redux-immutable`](https://github.com/gajus/redux-immutable) or [`redux-immutablejs`](https://github.com/indexiatech/redux-immutablejs) for your `combineReducers()`?

**Comment by maxmantz** [comment]
`redux-immutable` - I have just recently updated to V6 and it seems like the old version of `redux-form` was still in my node modules. A `rimraf` and clean `npm install` fixed the problem. Sorry for the troubles :-)

**Comment by erikras** [comment]
👍 No worries.
