### ISSUE TITLE
asyncBlurFields array issue

### ISSUE THREAD

**Issue by andrewQwer** [erikras/redux-form#904]
Hi, 

I have an array of items with `name` property. I declare it as 'myArr[].name]' in fields section.
What I want to do is to validate name on blur asyncronously, but the only option that works is to declare asyncBlurFields like this:
```javascript
{
asyncBlurFields:['myArr[0].name]'
}
``` 
Without index it doesn't work. Is there any way to validate array fields asyncronously without specifying indexes?

**Comment by erikras** [comment]
Yes, I recently fixed this. But I might not have published it. I'll look in an hour or two.

**Comment by andrewQwer** [comment]
ok, thank you!

**Comment by erikras** [comment]
Yeah, this dupes #869. Have you tried in [`v5.2.2`](https://github.com/erikras/redux-form/releases/tag/v5.2.2)?

**Comment by andrewQwer** [comment]
hm, looks like I am using an outdated version 5.0.1 I will update it and let you know if I still have this issue. Thanks!

**Comment by erikras** [comment]
I'm pretty sure this is fixed. Reopen if not.

**Comment by andrewQwer** [comment]
Yes, it is fixed now. But I have no idea what to reject in promise now. Let's say I am trying to validate 'myArr[].name', so how should I notify form that myArr[].name is invalid? What should I pass to reject?
