### ISSUE TITLE
Responding to other actions when using multiple forms

### ISSUE THREAD

**Issue by mattmarcello** [erikras/redux-form#91]
I have a site with an arbitrary number of forms with unique key properties.  

When using the reducer.Plugin function, is there anyway to know which form has just been submitted?

For example, given two forms with keys "foo" and "bar", when one form needs to respond to a LOGIN_FAILURE event, how do I clear out the password fields for the submitted form?  I would need to know the key of the submitted form in order to access its data in the state tree. 

Thanks in advance for your help and thanks in general :)

**Comment by erikras** [comment]
Sure, the action has the form name in it.

**Comment by mattmarcello** [comment]
Hmm.  I don't exactly understand.  So, I am attempting to respond to another action, not a redux-form action, by using the reducer.Plugin function.  This takes the entire form state tree, which is inclusive of data pertaining to multiple forms. 

```javascript
//state  
 {
    key1: {...formData},
    key2: { ...formData }
   }
```

My action would be something like this 

```javascript
{ type: "AUTH_FAILURE", error: "Incorrect password" }
```

The goal would be to reset the password field of the submitted form.  Perhaps I am using the library incorrectly?

**Comment by erikras** [comment]
Ah, no. Sorry, I misunderstood. You would have to include the name of the form, say `key2`, in your action that you are firing elsewhere for the express purpose of reseting the proper form. Does that help?

**Comment by ooflorent** [comment]
I'm closing this issue since it has been inactive for a long time.

Sorry we couldn’t answer your question here. Please feel free to post a link to the StackOverflow question, and I’ll be happy to try to answer it.
