### ISSUE TITLE
Support for Passing validate function in component props

### ISSUE THREAD

**Issue by zeroasterisk** [erikras/redux-form#910]
Is there any support for passing down a `validate` function from props?

I can get this tool to play nice, in many ways, but with a `Meteor` application, I'd like to share Schema validation on the server and client, but should not mix Meteor code into my React components... 

Therein lies my problem, I should not include a Meteor tool directly from the form component.  I should pass it down from the parent `page` via props.

So....

Is there some way I can accomplish this with your tool?

**Comment by erikras** [comment]
Yes, any config parameter can be passed in as a prop to your decorated form.

**Comment by zeroasterisk** [comment]
Thanks for your answer.

I still can't get it to pass in... I put my Page & Component into a quick gist to discuss further.
https://gist.github.com/zeroasterisk/caa75ebd3c7ea95cc4994a087d0fc0de

Basically, the `Page` (has the `handleValidate()` function) includes `Form` component.

I can not figure out how to configure `redux-form` to use the `handleValidate()` function.

_(probably quite simple, but I'm not seeing it yet)_

**Comment by erikras** [comment]
```js
<MyRequestInviteForm
  currentUser={this.props.currentUser}
//  handleOnSubmit={this.handleOnSubmit.bind(this)}
  onSubmit={this.handleOnSubmit.bind(this)} // <------ prop name is 'onSubmit'
//  handleValidate={this.handleValidate.bind(this)}
  validate={this.handleValidate.bind(this)} // <------ prop name is 'validate'
  schemaInviteRequest={this.props.schemaInviteRequest}
```

**Comment by zeroasterisk** [comment]
Thanks!!!  I'm closer.  

It now validates from a page-passed-in `validate` function _(YAY!)_, 

but it is not using my `onSubmit` function, passed in the same way.

I have updated my gist, can you please take a look and see if it's easy to determine what I'm doing wrong?
https://gist.github.com/zeroasterisk/caa75ebd3c7ea95cc4994a087d0fc0de

```js
          <MyRequestInviteForm
            currentUser={this.props.currentUser}
            onSubmit={this.onSubmit.bind(this)}
            validate={this.validate.bind(this)}
            schemaInviteRequest={this.props.schemaInviteRequest}
            />
```

**Comment by zeroasterisk** [comment]
Nevermind... I figured it out:

`<form onSubmit={handleSubmit}>...</form>`

Inheritance:

```js
<PageComponent> --> `onSubmit`--> <ReduxFormWrapped> --> `handleSubmit` --> <FormComponent>
```

THANKS for your help, and the repo!

I'll be playing with this and probably trying to push the Meteor + Recat community towards it and build some integrations that play nice.

**Comment by zeroasterisk** [comment]
Feedback welcome: https://github.com/zeroasterisk/meteor-simple-schema-transform

**Comment by babsonmatt** [comment]
@zeroasterisk unrelated to the topic at hand but I think you want to avoid using .bind within a render function since it creates a new function every render

see: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md
