### ISSUE TITLE
[PR to come] [6.x.x] Testing best practices and documentation

### ISSUE THREAD

**Issue by andrewmclagan** [erikras/redux-form#911]
I will be submitting a pull request soon for the docs on testing best practices for redux-form.

This will be based around the following toolset, although more related to react testing paradigms then anyone framework:

- AirBnB Enzyme
- Facebook Jest
- Facebook React Test Utils

Will involve ideas around unit tests and integration tests.

**Comment by erikras** [comment]
This sounds great! Thank you.

**Comment by andrewmclagan** [comment]
;-) just checking no-one else is writing similar PR

**Comment by kiki-le-singe** [comment]
Hi,

Any news about this PR?

Thanks
