### ISSUE TITLE
onSubmitSuccess dispatch callback

### ISSUE THREAD

**Issue by LandonSchropp** [erikras/redux-form#914]
Thanks for creating such a helpful library!

The `onSubmit` callback receives two arguments: the form data and the `dispatch` function. The `onSubmitSuccess` only seems to receive the form data. It would be awesome if `onSubmitSuccess` could be updated so it also receives `dispatch`.
- https://github.com/erikras/redux-form/blob/master/src/handleSubmit.js#L13
- https://github.com/erikras/redux-form/blob/master/src/handleSubmit.js#L19

**Comment by ooflorent** [comment]
As requested in #920, `dispatch` should also be exposed to `onSubmitFail`.

**Comment by jessym** [comment]
For anyone looking for an easy workaround: instead of passing onSubmitSuccess and onSubmitFail to the reduxForm config object, you can attach these callbacks to the promise returned by onSubmit, e.g.:

```
function onSubmitSuccess(sucRes, dispatch) {
}

function onSubmitFail(errRes, dispatch) {
}

function onSubmit(values, dispatch) {
  api.submit(values)
    .then(
      (sucRes) => onSubmitSuccess(sucRes, dispatch),
      (errRes) => onSubmitFail(errRes, dispatch)
    );
}

export default reduxForm({
  form,
  fields,
  onSubmit,
})(MyForm);
```

**Comment by lauterry** [comment]
Hello

Is there any reason why you don't provide ```dispatch``` to ```onSubmitSuccess``` and ```onSubmitFail``` ?

I know I can use ```connect``` to  dispatch If I can save several line of codes, it would be nice !

Thanks

**Comment by helgefredheim** [comment]
According to the docs, `dispatch`should be provided to `onSubmitFail`, but it seems only the fields with values are provided... @erikras, is this a bug?

**Comment by gustavohenke** [comment]
This feature is available and working in recent releases of V6.

And have happy new year everyone!
