### ISSUE TITLE
can i get initialValues passed from props?

### ISSUE THREAD

**Issue by SkateFreak** [erikras/redux-form#916]
i have this redux-form code:

    export default reduxForm({
        form: 'form',
        fields,
        initialValues: {
            first_name: 'test'
        },
        validate
    })(MyForm)

i want to pass the initialValues from MyForm.props.initialValues.
how can i access my components props?

**Comment by juanpaco** [comment]
The `mapStateToProps` [mentioned here](http://redux-form.com/5.2.3/#/api/reduxForm?_k=bm9ftq) option will help you with this.

Basically, you make a function such as:
```
function mapStateToProps(state, ownProps) {
  // state will be the state of your redux store
  // ownProps will be your component's props
}
```

This function needs to return a plain object.  [This object gets merged into your components props.](https://github.com/reactjs/react-redux/blob/master/docs/api.md#arguments)

Well, if you return an object with key `initialValues`, your form instance will use those as the initial values.  So, you can remove the `initialValues` from your example above and get something like the following:

```
function mapStateToProps(state, ownProps) {
  return {
    initialValues: {
      first_name: ownProps.propThatHasFirstName
    }
}

export default reduxForm({
    form: 'form',
    fields,
    validate
}, mapStateToProps)(MyForm)
```

Notice that `mapStateToProps` is now also passed as an argument to your `reduxForm` call.

Hope that helps!

**Comment by thomasmery** [comment]
I might not understand the question but can't you just do 

````
<MyForm initialValues={myFormData} />
```
?

**Comment by erikras** [comment]
I, too, am not 100% sure what you mean, but I'm going to guess.

The `initialValues` prop is "consumed" by the `redux-form` HOC (not passed through). However, you are free to pass the same values via any other prop, which will get passed through.

```js
<MyForm
  initialValues={myFormData} // <--- will be used and not passed through
  initialValuesToPassThru={myFormData}/> // <--- will be ignored and passed through
```

**Comment by SkateFreak** [comment]
thank you for your answers.
im running version ```5.2.3```, and i couldn;t get it to work.

the MyForm component sits under a route, and renders:

    return (
        <form initialValues={{ Country: "US" }} onSubmit={handleSubmit}>
        ...
        </form>
    )

should i pass the props from outside the component?

p.s. @juanpaco 's answer works great, but i'd rather @erikras ' approach

**Comment by thomasmery** [comment]
as far as I know you can either pass your `initialValues` as a prop when declaring your component in its container as @erikras has stated

or you can use `mapStateToProps` in your component definition as @juanpaco has explained

does that help?

**Comment by erikras** [comment]
```js
<form initialValues={{ Country: "US" }} onSubmit={handleSubmit}>
// ^^ No, that's the React.DOM.form component. You need to pass it to your
// decorated component. Probably the component that this render() method is in.
```

**Comment by SkateFreak** [comment]
yes, it did help. thank you guys

**Comment by gkatsanos** [comment]
@erikras is this still actual? 

```javascript
import React from 'react';
import { Field, reduxForm } from 'redux-form';

const ModifyItemBody = ({ handleSubmit, body }) => (
  <form onSubmit={handleSubmit} initialValues={{newbody: body}}>
    <Field name="newbody" component="input" type="text"/>
    <button type="submit">Submit</button>
  </form>
);

export default reduxForm({
  form: 'modifyItem', // a unique name for this form
  enableReinitialize: true
})(ModifyItemBody);
```
```
Warning: Unknown prop `initialValues` on <form> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in form (at ModifyItemBody.js:5)
    in ModifyItemBody (created by Form(ModifyItemBody))
    in Form(ModifyItemBody) (created by Connect(Form(ModifyItemBody)))
    in Connect(Form(ModifyItemBody)) (created by ReduxForm)
    in ReduxForm (at Movie.js:10)
    in div (at Movie.js:5)
    in Movie (at MovieList.js:41)
    in div (at MovieList.js:37)
    in MovieList (created by Connect(MovieList))
    in Connect(MovieList) (at App.js:10)
    in div (at App.js:9)
    in App (at index.js:17)
    in Provider (at index.js:16)
```

**Comment by gkatsanos** [comment]
Ah ok, I needed to pass the actual prop when the Component was called:
```
      <ModifyItemBody body={body} onSubmit={handleSubmit} editmode={!editmode} id={id} initialValues={{newbody: body}} />

**Comment by erikras** [comment]
@gkatsanos Perhaps the [IMPORTANT: All of these configuration options may be passed into reduxForm() at "design time" or passed in as props to your component at runtime.](http://redux-form.com/6.6.3/docs/api/ReduxForm.md/#config-properties) could be in a bigger font? That line does cover what you're talking about, right? I'm open to suggestions of how to make the docs clearer. What would you write, and where?

**Comment by gkatsanos** [comment]
Hey Erik, you're right actually in both things:) it's there but yes the fonts are rather problematic.. : 
![image](https://cloud.githubusercontent.com/assets/1768834/25792483/20298e80-33c7-11e7-8ee2-49101c95c515.png)
If the repo for the website is open-sourced I'd like to offer a PR for the CSS/styling with minor tweaks, and also I'd add a line in the FAQ as initialValues seem to be a popular question.
Also, "may be passed into reduxForm().. or passed in as props to your component.." is good, but:
`<MyForm initialValues:{{myFieldName: 'initial-value'}}>` says a lot more without having to explain so much :) The addition of an actual very simple example would be super helpful.
But I think the most important problem of the docs is the lack of a well-functioning search ( look at theirs : https://vuejs.org/v2/guide/ ) .. I had to google in order to find something in the docs :/
again, willing to help if the website's in a repo!

**Comment by oskaryil** [comment]
@thomasmery Thanks, your solution worked!

**Comment by gustavohenke** [comment]
Late answer to https://github.com/erikras/redux-form/issues/916#issuecomment-299783059: it's open source. Just look at the other available branches here :)
The contents of the docs are markdown files you can find in the `master` branch.

cc @gkatsanos

**Comment by mddrill** [comment]
The mapStateToProps doesn't seem to work.

**Comment by mddrill** [comment]
Nevermind. I just had to reverse the order of connect and reduxForm like in this answer https://stackoverflow.com/a/48855532/5605365
