### ISSUE TITLE
v6 Is there a bug with initialValues not resetting?

### ISSUE THREAD

**Issue by darylhedley** [erikras/redux-form#918]
I create a reduxForm with initialValues set as a model retrieved from the server (editing user 1). This works great the first time, however if I then click to edit the second user the first users data is still there even though initialValues is set to the new user model. Has anyone experienced this?

I've been through my props and changed that the new user model is being passed down, which it is until I call reduxForm()

**Comment by darylhedley** [comment]
Look over the code it would seem as though my form fields are holding onto the state of the previous form even though it gets removed when navigating to another page

**Comment by erikras** [comment]
Sounds like `v6` didn't get the recent `overwriteInitialValuesOnChange` thing from [`v5.2.1`](https://github.com/erikras/redux-form/releases/tag/v5.2.1). Everyone has different expectations about what should happen when the initial values change.

**Comment by darylhedley** [comment]
Ah - that makes sense. Been bashing my head against this one for a while. So initialValues is the way to go? Is ``overwriteOnInitialValuesChange`` defaulted to ``true``?

**Comment by simonkoener66** [comment]
I've also experienced this. For example:
in page1.js
`render() {
    ...........
    <MyForm initialValues={values1}/>
    ...........
}`
and in page2.js
`render() {
    ...........
    <MyForm initialValues={values2}/>
    ...........
}`
If user navigates to page2 after page1, MyForm has values from value1 that is set in page1 ignoring initialValues in page2.

**Comment by erikras** [comment]
> Is `overwriteOnInitialValuesChange` defaulted to `true`?

Yes. It's already a freakishly long config param, and I didn't want to prefix it with `dont`.

**Comment by darylhedley** [comment]
@erikras do you know roughly when this will be implemented into v6 alphas?

**Comment by erikras** [comment]
Fix published as [`v6.0.0-alpha.8`](https://github.com/erikras/redux-form/releases/tag/v6.0.0-alpha.8).
