### ISSUE TITLE
Pass dispatch to onSubmitFail

### ISSUE THREAD

**Issue by tylergoodman** [erikras/redux-form#920]
I'd like to be able to dispatch actions from the `onSubmitFail` hook in the event of synchronous validation failure. Could you guys pass `dispatch` to that hook like you do for the `onSubmit` hook?

Alternatively, Is there a different/better way to do this?

**Comment by erikras** [comment]
Sure, that could be added. But in the mean time, you can always `connect()` whatever component your `onSubmitFail` function is in.

**Comment by ooflorent** [comment]
Duplicates #914

**Comment by iampeter** [comment]
@erikras what exactly do you mean by:
> connect() whatever component your onSubmitFail function is in.
?

**Comment by iampeter** [comment]
@erikras OK I answered myself :)
