### ISSUE TITLE
Once a field is initialized to a value, it can't be set to a blank value

### ISSUE THREAD

**Issue by mhahn** [erikras/redux-form#921]
I'm on v6-alpha7.

I have a text field that I initialize to a value within `componentWillMount`. I also have validation logic to make sure the field is required and to display the error to the user if they delete the value.

Right now, when the value is initialized, the "required" error will never display since we can't set a blank value based on:

https://github.com/erikras/redux-form/blob/v6/src/reducer.js#L83

The field will always pass the initial value to the validate and submit functions.

I don't think the value should ever be deleted from the state, even if it is an empty string.

**Comment by erikras** [comment]
This will probably change, but a solution needs to be found to this: https://github.com/erikras/redux-form/issues/879#issuecomment-215822073

Gonna close this as it pretty much dupes #879.
