### ISSUE TITLE
How do I access "props" inside the validate function ?

### ISSUE THREAD

**Issue by iroy2000** [erikras/redux-form#922]
I would like to do something like the following, is that doable ?

```
const validate = values => {
    const errors = {}
/*
    let postExistedCheck = this.props.posts.filter((post) => {
        return post.get('title') == values.title
    });

    if(postExistedCheck.size > 0){
        errors.title = 'Title already Existed'
    }
*/
    return errors
};
```

**Comment by iroy2000** [comment]
I just read the source code directly and found it, thanks :)

**Comment by jay-hat** [comment]
@iroy2000 Can you share how you accessed props inside validate? Thanks!

**Comment by bulleric** [comment]
+1

**Comment by bulleric** [comment]
Define the validate function with

const validate = ( values, props )  => {
  // now you have access to the props inside the validation function 
}

**Comment by swp44744** [comment]
@bulleric invalidate function props are undefined. how are you calling validate function?? can you elaborate please??

**Comment by kylezinter** [comment]
@swp44744 I realize this is old but incase this can help you or someone else in the future. Validate is called by reduxForm() and needs to be passed into it. 

ie.

```
function validate(values, props) {
  // validation logic
  return errors;
}

export default reduxForm({
  form: 'formName',
  validate
})(Component);
```


You can find the doc on the api here - [https://redux-form.com/6.0.0-rc.1/docs/api/reduxform.md/](https://redux-form.com/6.0.0-rc.1/docs/api/reduxform.md/)

And examples of the validation function in use in these spots.
Sync - [https://redux-form.com/6.0.0-rc.1/examples/syncvalidation/](https://redux-form.com/6.0.0-rc.1/examples/syncvalidation/)
Async - [https://redux-form.com/6.0.0-rc.1/examples/asyncvalidation/](https://redux-form.com/6.0.0-rc.1/examples/asyncvalidation/)

**Comment by chetnashah** [comment]
These props no longer give expected props of original component, but rather weird props...

**Comment by danielrob** [comment]
@chetnashah these are the `Form` or `reduxForm` props. For the `Field` props there is a feature request - see #2881.
