### ISSUE TITLE
Access validation errors from outside form component?

### ISSUE THREAD

**Issue by tyleriguchi** [erikras/redux-form#923]
Currently I am trying to figure out if there's a straightforward way to access the validation errors from outside the form component. 

I want to submit from a  [parent component](http://redux-form.com/5.2.3/#/examples/submit-from-parent?_k=uo4b0k) and have that button be disabled if there a validation errors.  The form store doesn't appear to keep track of any of the validation errors. 

Thoughts?

**Comment by erikras** [comment]
`v6` will provide this functionality. However, in the mean time, you could certainly jury rig a solution using [`getValues()`](http://redux-form.com/5.2.3/#/api/get-values) and your validation function.
