### ISSUE TITLE
Autocomplete inputs?

### ISSUE THREAD

**Issue by davidhtien** [erikras/redux-form#926]
I tried to use awesomplete with redux-form and ran into a lot of problems mainly in the fact the jquery setting the value of the field would not trigger a state change and so if you clicked away or did anything else the selected autocomplete value would not remain, does anyone have any experience with this?

**Comment by erikras** [comment]
Mixing React and jQuery is a recipe for trouble, in my experience. React _really_ doesn't like it when you manipulate the DOM out from under it.

**Comment by erikras** [comment]
I have used [`react-select`](http://jedwatson.github.io/react-select/) for autocomplete fields. It plays nicely with `redux-form`.

**Comment by ooflorent** [comment]
As Erik said, you should use a component to achieve this. The problem when using jQuery (or any DOM library) is that React does not operate directly on the DOM but on a virtual representation on the desired DOM tree. If something modify this tree then React won't be able to update the DOM.

`react-select` and `react-selectize` work both well with `redux-form`.

**Comment by davidhtien** [comment]
Hey sorry to bother you guys but I'm trying to use react-select with my form and it keeps getting cleared onBlur, can't really figure out why? Are there any examples of redux-form and react-select working together?

**Comment by kktam** [comment]
@erikras  do you have a sample you can post and share?

**Comment by levulinh** [comment]
@ooflorent Do you have any sample? I'm working on a project and stucking at get react-select working with redux-form.
