### ISSUE TITLE
v6 how to expose input ref for focus() and blur() with the new Field Component?

### ISSUE THREAD

**Issue by ms88privat** [erikras/redux-form#927]
I need to call focus() and blur() programmatically on my input field. But with the new Field wrapper, I don't see an easy way to get access to the ref of the input field. I think the Field Component should implement the methods focus() and blur() if possible.

**Comment by kristian-puccio** [comment]
Yes would be very nice to have

**Comment by erikras** [comment]
To clarify, you mean...
```js
focusMyField() {
  this.refs.myFieldRef.focus()
}

render() {
  return (
    <div>
      <Field name="myField" ref="myFieldRef" component="input"/>
      <button onClick={this.focusMyField.bind(this)}>Focus</button>
    </div>
  )
}
```
??

**Comment by ms88privat** [comment]
@erikras yes

**Comment by eliseumds** [comment]
Ye, makes sense. But we may just need a method to access the rendered field component:

```js
focusMyField() {
  this.refs.myFieldRef.getRenderedComponent().focus()
}

render() {
  return (
    <div>
      <Field name="myField" ref="myFieldRef" component="input"/>
      <button onClick={this.focusMyField.bind(this)}>Focus</button>
    </div>
  )
}
```

Otherwise we might call these methods that are not available on the final component (custom ones).

**Comment by erikras** [comment]
I've implemented `getRenderedComponent()`. It will be published in the next alpha release.

**Comment by erikras** [comment]
Published as [`v6.0.0-alpha.8`](https://github.com/erikras/redux-form/releases/tag/v6.0.0-alpha.8).

**Comment by ms88privat** [comment]
👍 thanks

**Comment by erikras** [comment]
@ms88privat Thanks for bringing my attention to [react-native-stateless-form](https://github.com/danielweinmann/react-native-stateless-form). Very interesting project.

**Comment by ArmorDarks** [comment]
Just in case, there is another method for doing this for stateless components: https://github.com/facebook/react/issues/4936#issuecomment-179917137

**Comment by Noitidart** [comment]
> I've implemented getRenderedComponent(). It will be published in the next alpha release.
Hi there @erikras - I am trying to access the ref from the `onSubmitFail` in my react-native app. However I cannot access that. Is there some way to get the ref to the node in `onSubmitFail`? My goal is to scroll to the `<TextInput />` element.
