### ISSUE TITLE
Clarification for 6.0.0-alpha.7 Immutable Example Instructions

### ISSUE THREAD

**Issue by pherris** [erikras/redux-form#932]
Hey there, nice job on the library - I'm enjoying working with it. While working with the Immutable JS example I ran into an issue where the `validate` method was receiving a plan javascript object instead of an Immutable JS object as expected.  I solved this by importing the reducer from `redux-form/immutable`.

I'd suggest you update [this example](http://redux-form.com/6.0.0-alpha.7/examples/immutable/) to specify that the reducer must also be imported from `redux-form/immutable`:

``` js
import { reducer as formReducer } from 'redux-form/immutable';
```

This was super confusing because I had also refactored my project to use `redux-immutable` while working with this tutorial which I understood would store all state (including `form`) as Immutable JS objects - maybe some extra clarification about where the `values` object comes from would help too.

**Comment by erikras** [comment]
Good idea.

**Comment by ooflorent** [comment]
@pherris It would be awesome if you could submit a PR on the `v6` to add some clarifications!

**Comment by gustavohenke** [comment]
Done in #1718.
