### ISSUE TITLE
[v6] Thoughts on exposing allTouched?

### ISSUE THREAD

**Issue by pbojinov** [erikras/redux-form#933]
Similar to `anyTouched`, which is a super useful helper, adding support for `allTouched` which will return `true` if all of the fields have been marked as touched, `false` otherwise. It was originally referenced in https://github.com/erikras/redux-form/issues/81#issuecomment-212823536

The use case I was thinking is to easily disable a submit button until all of the fields are touched. The alternative is to check for all individual values, eg. `!name.touched && !address.touched`. 

Or would you recommend handling disabling submit button based on touched fields differently, such as through setting an error on sync or async validation?

**Comment by erikras** [comment]
That UI seems pretty confusing. I'd recommend having 'required' sync validation for the fields that are required, and not caring if the user doesn't touch a non-required field. Then you can disable the submit button when `this.props.invalid`.

**Comment by pbojinov** [comment]
@erikras makes sense, I'll go ahead and implement it that way. Thanks!
