### ISSUE TITLE
[v6] Pass component as a child function

### ISSUE THREAD

**Issue by eliseumds** [erikras/redux-form#934]
What's the idea behind the **component** prop? IMHO,  it makes the codebase pretty ugly when one needs something more elaborate like Bootstrap.

Would anything block us from changing the current API to the following?

```js
<Field name="myField">
  {field => <FormControl type="text" {...field} />
</Field>
```

I think it's easier to read and understand because it respects the hierarchy. With `component={}` it looks like it's going to be rendered somewhere else. We could still have the current shortcuts like `type="input"` for the basic cases:

```js
<Field name="amount" type="number" min="0" max="10" />
```

Great job, everyone involved. V6 is simply much better already :)

**Comment by ooflorent** [comment]
> What's the idea behind the component prop? IMHO, it makes the codebase pretty ugly when one needs something more elaborate like Bootstrap.

I'm sorry I don't get your point. Could you elaborate? Since `component` accepts anything that could render a JSX element, your codebase stay clean!

```js
const createFormControl = type =>
  field => <FormControl type={type} {...field} />

const TextControl = createFormControl("text")
const PasswordControl = createFormControl("password")

const MyForm = props => (
  <form onSubmit={props.handleSubmit}>
    <FormGroup controlId="username">
      <ControlText>{"Username"}</ControlText>
      <Field name="username" component={TextControl} />
    </FormGroup>
    <FormGroup controlId="password">
      <ControlText>{"Password"}</ControlText>
      <Field name="password" component={PasswordControl} />
    </FormGroup>
    <Button type="submit">{"Submit"}</Button>
  </form>
)
```

**Comment by erikras** [comment]
@eliseumds In almost any project, you're going to want to create components for your common form structures, like @ooflorent has shown with `TextControl` and `PasswordControl` above. Personally, I prefer to do it at the "row" level (`FormGroup` in @ooflorent's example), so I can decorate the label when the field is in error. My forms tend to look like:

```js
<form onSubmit={props.handleSubmit}>
  <Field name="firstName" label="First Name" component="TextInput"/>
  <Field name="lastName" label="Last Name" component="TextInput"/>
  <Field name="country" label="Country" component="AutocompleteInput" options={countries}/>
</form>
```

It feels pretty darn clean to me.

Also, the "function as only child" pattern is, in my experience, very confusing. `react-redux` suffered from that with its `Provider` component for almost a year before React made a fix, and it caused no end of confusion.

**Comment by eliseumds** [comment]
Your suggestions make sense. I totally forgot that all the props would be passed down to the rendered component, as is written in the docs =S

Thanks!
