### ISSUE TITLE
array changes doesn't trigger form initialization

### ISSUE THREAD

**Issue by andrewQwer** [erikras/redux-form#939]
I specified `initialValues` prop for my form and set `overwriteOnInitialValuesChange: true`. When I load my form I initialize it with same basic values like id and name and then I trigger ajax request to load additional info for my form. Additional info - array of values, so my updated form state look like this:

```js
{
  id: <some_value>,
  name: <some_value>,
  items: [<array of items updated via ajax>]
}
```

The problem is that  initially `items` array is empty and when it's updated via ajax form doesn't reflect these changes. It remains empty even if `items` array have some items, `redux-form/INITIALIZE` action doesn't trigger. I have to manually change some fake property to notify form that initial values have changed. Is it a bug or expected behavior?

**Comment by ooflorent** [comment]
I think it is the expected behavior. I can't tell much without a minimal reproducible sample.

**Comment by andrewQwer** [comment]
OK, I will provide an example soon

**Comment by andrewQwer** [comment]
Sorry, test sample I've prepared works fine. Looks like the problem is on my side.

**Comment by erikras** [comment]
It's amazing how often "make a simple example" exposes error. Happens to me almost daily. 😄
