### ISSUE TITLE
Support for success messages?

### ISSUE THREAD

**Issue by tsemerad** [erikras/redux-form#94]
I have a form whose `onSubmit` function returns a Promise. I have had no trouble accessing the error message returned by the Promise in the redux-form form, but it doesn't look like there's currently a built-in way to store a form's success message in the form's state in the redux store. 

    function handleSubmit() {
        return resetPasswordPromise()
               .catch((error) => Promise.reject({_error: error.message})) // this works
               .then((success) => Promise.resolve({_success: success})); // this doesn't
    }

Later I can access `this.props.error`, but what about the success message? Is there a recommended practice to achieve this?

**Comment by wmertens** [comment]
You should use your reducers to store any results you are interested in in
the store, and then load those as props.
Redux-form does not and should not provide general data storage.

If you really wanted to you could store the result in the state of the form
with setState, but impurities are best reserved for display-related state.

Note that in best practice, that Promise should have been created in an
ActionCreator. Your form should just dispatch that with the provided data
instead.

On Sat, Sep 26, 2015, 03:48 tsemerad <notifications@github.com> wrote:

> I have a form whose onSubmit function returns a Promise. I have had no
> trouble accessing the error message returned by the Promise in the
> redux-form form, but it doesn't look like there's currently a built-in way
> to store a form's success message in the form's state in the redux store.
>
> function handleSubmit() {
>     return resetPasswordPromise
>            .catch((error) => Promise.reject({_error: error.message})); // this works
>            .then((success) => Promise.resolve({_success: success})) // this doesn't
> }
>
> Later I can access this.props.error, but what about the success message?
> Is there a recommended practice to achieve this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/erikras/redux-form/issues/94>.
>
-- 

Wout.
(typed on mobile, excuse terseness)

**Comment by erikras** [comment]
I provided the `error` message, because that is sort of inline with validation, but I agree with @wmertens on this. How you submit and how you respond to a submission is none of redux-form's business.

Does @wmertens's comment make sense, @tsemerad?

**Comment by tsemerad** [comment]
Thanks for the responses. I agree that redux-form should not "provide general data storage", but a simple success message response from the server is a very common piece of "state" for forms. Isn't there value in the redux-form "knowing" the form submission was successful, and how it was successful (similar to how it currently knows that it failed and how it failed)?

I agree that the primary result of a form's submission is generally not the concern of the form. For example, an "Add User" form has no business with a subsequent user object. But a message stating "User added successfully" seems intrinsically associated to the form, since my only purpose for that message is to display it at the top or bottom of the form, exactly how I'd show redux-form's built in error messages.

I definitely considered saving the response message from my `resetPasswordForm` in a separate piece of state, but it seemed a bit awkward to create a separate slice of state just for a success message that is intrinsically associated with my form.

It sounds like you're recommending I have my state something like this:

    {
        auth: { ... },
        form: {
            resetPassword: {
                _error: "User does not exist"
            }
        },
        formSuccessMessages: {
            resetPassword: "Reset password email sent"
        }
    }

Which feels a bit awkward having to access my success and failure messages from 2 separate branches of the store. I could go the path of keeping both my error message and my success message in my own managed state, disregarding redux-form's built-in `error` message:

    {
        auth: { ... },
        form: {
            resetPassword: { ... }
        },
        formMessages: {
            resetPassword: {
                // only one of these would be populated, based on server success/failure
                error: "User does not exist",
                success: "Reset password email sent"
            }
        }
    }  

This way the messages are both in the same branch, but unfortunately it would still be necessary to have my form receive props from both `form` and `formMessages`. 

How would you handle this? It still seems to me that the most elegant way to do this would be to have redux-form state have an optional success message as well as its current support for error messages. This way my forms would only need to be hooked up with `connectReduxForm` (instead of additionally needing to be `connect`ed to the redux store). Also, I wouldn't have to set up a separate reducer to handle each of my forms' success messages.

I admit that I am fairly new to redux-form, but as a newcomer, it is confusing to have a consistent way to organize all of your form's state, including a possible `error` message, but have no mention of a `success` state. Maybe it was my mistake to assume that having one implies the other.

**Comment by wmertens** [comment]
What you propose is indeed a little awkward, but how about having a
notification system in your app? (A little dropdown or something that
displays an array of messages, and a reducer that handles adding/removing
messages and an actioncreator that dispatches notifications and then later
a removal)

Then your form submit actioncreator can send the form, dispatch the
notification about success or failure, and on success navigate to the next
step. The notification can persist during navigation and your form element
stays nice and simple.


On Sun, Sep 27, 2015 at 1:20 AM tsemerad <notifications@github.com> wrote:

> Thanks for the responses. I agree that redux-form should not "provide
> general data storage", but a simple success message response from the
> server is a very common piece of "state" for forms. Isn't there value in
> the redux-form "knowing" the form submission was successful, and how it was
> successful (similar to how it currently knows that it failed and how it
> failed)?
>
> I agree that the primary result of a form's submission is generally not
> the concern of the form. For example, an "Add User" form has no business
> with a subsequent user object. But a message stating "User added
> successfully" seems intrinsically associated to the form, since my only
> purpose for that message is to display it at the top or bottom of the form,
> exactly how I'd show redux-form's built in error messages.
>
> I definitely considered saving the response message from my
> resetPasswordForm in a separate piece of state, but it seemed a bit
> awkward to create a separate slice of state just for a success message that
> is intrinsically associated with my form.
>
> It sounds like you're recommending I have my state something like this:
>
> {
>     auth: { ... },
>     form: {
>         resetPassword: {
>             _error: "User does not exist"
>         }
>     },
>     formSuccessMessages: {
>         resetPassword: "Reset password email sent"
>     }
> }
>
> Which feels a bit awkward having to access my success and failure messages
> from 2 separate branches of the store. I could go the path of keeping both
> my error message and my success message in my own managed state,
> disregarding redux-form's built-in error message:
>
> {
>     auth: { ... },
>     form: {
>         resetPassword: { ... }
>     },
>     formMessages: {
>         resetPassword: {
>             // only one of these would be populated, based on server success/failure
>             error: "User does not exist",
>             success: "Reset password email sent"
>         }
>     }
> }
>
> This way the messages are both in the same branch, but unfortunately it
> would still be necessary to have my form receive props from both form and
> formMessages.
>
> How would you handle this? It still seems to me that the most elegant way
> to do this would be to have redux-form state have an optional success
> message as well as its current support for error messages. This way my
> forms would only need to be hooked up with connectReduxForm (instead of
> additionally needing to be connected to the redux store). Also, I
> wouldn't have to set up a separate reducer to handle each of my forms'
> success messages.
>
> I admit that I am fairly new to redux-form, but as a newcomer, it is
> confusing to have a consistent way to organize all of your form's state,
> including a possible error message, but have no mention of a success
> state. Maybe it was my mistake to assume that having one implies the other.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/erikras/redux-form/issues/94#issuecomment-143504027>.
>
-- 

Wout.
(typed on mobile, excuse terseness)

**Comment by tsemerad** [comment]
I hadn't considered a notification system, but for my use case it would be a bit too much. I don't want users to have a list of messages, just the message(s) related to the form(s) at the current route.

The way that redux-form's error messages work is perfectly elegant - I submit an invalid form, the server responds with a message, and the error message stays in the redux-form's state until the form is unmounted. Navigating away and back to the form clears the error message, as a user would typically expect.

![resetpassworderrormessageflow](https://cloud.githubusercontent.com/assets/961776/10142291/af2148c4-65c6-11e5-9216-9c6378a2f213.gif)

To mimic this same flow with a success message requires significant extra state management, for each form, all of which would be unnecessary if redux-form forms had the *option* to store a success message in their state.

Do you still think it is a bad idea to have a `_success` option, similar to how we have an `_error` option? If so, why is it ok that we have the `_error` option and not the other? I feel like such a success message is equally of concern to the form as an error message is, and really wouldn't make the form much more complex.

Thanks again for your input. I really appreciate the work that's been put into this.

**Comment by erikras** [comment]
The main intent of the `_error` was for form-wide _validation_ errors. You must already have a reducer/actions couplet to handle your ajax request, right? Is it really that much more state?

**Comment by tsemerad** [comment]
Yes I have an action that is called, and I can have a `resetPasswordForm` state to hold the server's success message. It really isn't "that much more state" for a single form, but with at least a dozen or so forms it adds up. I'm fine with going this route if need be, it would just be much cleaner to have the option to set a `_success` message, and more importantly it would be consistent with how redux-form's `_error` message works.

It's just a bit awkward for redux-form to provide everything that my forms needs, except for the success message state. I understand wanting to keep redux-form simple. I would argue that having support for a `_success` message wouldn't add much complexity that wasn't already added by supporting `_error`, since they would work roughly the same. And I still don't see why it is a problem for the form to "know" it was successful when it already knows when it's not successful. Is my use-case really that odd?

I just want to know if you're at all interested in supporting this, and if so, I would love to help implement it.

**Comment by wmertens** [comment]
So how do you propose supporting this? The success value needs to make it
into the form somehow.
The only thing I can think of is that onSubmit can return a promise and if
so, the resolution of that promise will be put in the local form state.
I don't think that is a very useful interface though, you can't then
navigate away for example.

You also speak of dozens of forms but a little notifier would be too much?
It only needs to show a single message…

On Tue, Sep 29, 2015, 01:17 tsemerad <notifications@github.com> wrote:

> Yes I have an action that is called, and I can have a resetPasswordForm
> state to hold the server's success message. It really isn't "that much more
> state" for a single form, but with at least a dozen or so forms it adds up.
> I'm fine with going this route if need be, it would just be much cleaner to
> have the option to set a _success message, and more importantly it would
> be consistent with how redux-form's _error message works.
>
> It's just a bit awkward for redux-form to provide everything that my forms
> needs, except for the success message state. I understand wanting to keep
> redux-form simple. I would argue that having support for a _success
> message wouldn't add much complexity that wasn't already added by
> supporting _error, since they would work roughly the same. And I still
> don't see why it is a problem for the form to "know" it was successful when
> it already knows when it's not successful. Is my use-case really that odd?
>
> I just want to know if you're at all interested in supporting this, and if
> so, I would love to help implement it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/erikras/redux-form/issues/94#issuecomment-143899570>.
>
-- 

Wout.
(typed on mobile, excuse terseness)

**Comment by tsemerad** [comment]
I was thinking it could be supported similar to how the `_error` message is added. Like you said, the resolution of a Promise passed to `onSubmit`, where the result of the resolved Promise has a `message` property.

    function handleSubmit() {
      return resetPasswordAction()
        .catch((error) => Promise.reject({_error: error.message}))
        .then((success) => Promise.resolve({_success: success.message}));
    }

How does supporting this interface prevent you from being able to navigate away? I apologize if this may be a dumb question. Couldn't you just return an object with the `_success` attribute when you're interested in setting a success message, and redux-form would look for that (like it looks for `_error`), but otherwise perform how it usually does?

**Comment by erikras** [comment]
I think this is out of scope of this library. With v3.0, it makes it easy to connect your form to another reducer where you can, and should, store your success message.

**Comment by jakelazaroff** [comment]
I don't understand why this is out of scope; it makes sense for a form to display a success message if the application doesn't navigate away from the form after its submission.

**Comment by export-mike** [comment]
@erikras you have a point, but in some cases that I'm finding I don't need to hook into any other actions or store state in another reducer its effectively fire and forget. but theres always other ways of doing things and its based on the app your building so in my app, I have a

**Comment by kevzettler** [comment]
I second what @jakelazaroff is saying. This seems like a clear obvious concern for the library to handle. It is a common UX paradigm. Most other form libraries support this. I'd expect there to be a `redux-form` prop `success` like `submitting` or `error` that can be subscribed to in the component. I'd ask that if this is 'out of scope' for the source code, an example is added that clearly demonstrates how to handle this paradigm in `redux-form` style.

**Comment by ttaub** [comment]
Checking if a form succeeded to submit is something that almost every form does. It really don't see any way that this functionality is out of the scope of redux-form. You are essentially forcing users to use the global notification paradigm.

**Comment by export-mike** [comment]
In a way I can understand why this hasn't been added, most form submissions
trigger a callback and move onto another view so it's not a problem for
this pattern. That's an assumption on how people will use redux form. I've
recently stopped using redux form for these flags partly the reason being
is I'm using saga's over thunks and now have a generic higher order
component to provide a container with success, error, isFetching,
errorMessage and successMessage props for a given scope.

I.e.

``` export default compose(
     reduxForm({ form: 'example', ... }),
     loading('example')
    )(MyContainer);
```

Within my saga's I can do:

```
function* exampleSaga({payload}){
  // Payload being data from redux form

  try {
    loading.inFlight('example');
    yield Api.submitExample(data);
    loading.success('example', 'wahoo success!');
  } catch (e) {
    loading.fail('example', e, 'oops an error occurred');
  }
}
```

**Comment by kevzettler** [comment]
Think this may have been finally addressed in https://github.com/erikras/redux-form/issues/853

**Comment by TimOgilvy** [comment]
This reads like a long story of DevOps people telling UX designers that they are not professionals.

Perfect Use Case: 
I'm trying to tell a user if a password they are planning to use is any good.  I don't want to do it in application level feedback, I want to do it right there on the form, right next to that field. 

If I give them feedback every step of the way until it's perfect, and then... silence, this is not a good UX conversation.  The UX is abandoning the user once they have things right.  We've been opinionated, terse, verbose in the error feedback, but have then given them nothing once they get it right.

User relationships are about storytelling and conversation.  It might suit us as devs to have nothing else, but when Gran is trying to change her online password, we want to say "hey well done Gran, you just came up with a password that's nice and secure!"

This is a basic premise of good UX design, and, it's totally the responsibility of the feedback part of the form.  I wonder if the Devs saying "nah you don't need this" also don't give their team members any positive feedback?  Specific, positive feedback makes everything better. Have more fun, say well done!   

Let's make this project more human.

**Comment by wmertens** [comment]
I think there have been several approaches mentioned here how you can quite
easily achieve your feedback goal without increasing the maintenance burden
for redux-form.

**Comment by danielrob** [comment]
Locking this issue as it is extremely old, and there are long since solutions for it's resolution as linked above.
