### ISSUE TITLE
[v5] Updating initialValues doesn't always update the form

### ISSUE THREAD

**Issue by nsf** [erikras/redux-form#941]
Hello. It is an interesting bug caused by a very weird workflow perhaps. Bug is valid for version 5.2.3.

It happens only when `destroyOnUnmount == false`. This is the most important part.
1. You load the page with `initialValues=X`, the form gets initialized by `componentWillMount`, all great.
2. You queue your async API for new set of initial values Y.
3. Form gets unmounted because async request results in a spinner component displayed instead of a form.
4. New set of initial values Y is ready and form gets mounted again this time with `initialValues=Y`, but because `destroyOnUnmount == false`, on unmount in step 3 it didn't destroy the form state in redux hence it never gets initialized with new set of initialValues even though the set has changed (`componentWillReceiveProps` is not called on initial mount).

I think this pretty much an invalid behaviour, because doc says it will overwrite the form on `initialValues` change if `overwriteOnInitialValuesChange` is true, which is true in my case.

The problem is that `initialValues` is just a prop and state of the form is stored in redux. And hence in order to handle that scenario correctly you should realize that form state in redux potentially outlives the component itself and as a result `initialValues` need to be stored in redux as well in order to be able to perform a deep comparison between the old set of initial values and a new one.

**Comment by guzcon** [comment]
I have the same problem today. Has this been improved in any way?

**Comment by henrikra** [comment]
Our team faced this same problem today. We have same scenario that destroyOnUnmount == false because we have multistep form. On step 1 initialValues work but on later step it does not work :/

**Comment by danielrob** [comment]
Closing with bulk close of v5 issues. If this issue still requires action and/or also affects v6/7, please request a reopen with details or raise a new issue. v5 PR's are still welcomed.
