### ISSUE TITLE
Form state not persisted between hot reloads.

### ISSUE THREAD

**Issue by MichalZalecki** [erikras/redux-form#946]
Hi!

My forms state is not persisted between hot reloads (react-hot-loader). I don't have such problems with other reducers. Is this intended (can't find such info)? Parent component for form is connected to redux. It's actually annoying when fields I'm showing on the form depends on the previous fields values.

Cheers!

**Comment by ooflorent** [comment]
See #623

**Comment by MichalZalecki** [comment]
:+1:
