### ISSUE TITLE
How do I specify the "form" property (in config) dynamically?

### ISSUE THREAD

**Issue by jcalfee** [erikras/redux-form#949]
I'm trying to do something like this:
```js
export default reduxForm(
    {}, // instead of:   {form: 'formId'},
    (state, ownProps) => ({form: ownProps.id})
...
```
But I get this bright red warning in the chrome console:
>Warning: Failed propType: Required prop `form` was not specified in >`ReduxFormConnector(ReplyEditor)`. Check the render method of 'ConnectedForm'.

This is for a reply editor, where each editor should have its own form state.  Hard-coding `form` in the config causes all the reply editors to share the same reply text.   

It would be great to have this working in the current release (or dot release).

**Comment by ooflorent** [comment]
I'll start by quoting the documentation:

> IMPORTANT: All of these configuration options may be passed into `reduxForm()` at "design time" or passed in as props to your component at runtime.

So, what does it mean? There are multiple way to configure your form.

```js
// 1. Using `config` parameter
reduxForm({
  form: "profile",
  fields: ["username", "email"],
})

// 2. Using properties
<MyForm form="foo" fields={["a", "b"]} />
```

What's interesting here is the 2nd case. You can use this pattern with an higher order component to ease the form configuration.

```js
// 1. Using `react-redux`
connect(
  (state, props) => ({
    initialValues: state.user[props.id],
  })
)

// 2. Using `recompose`
mapProps(
  props => ({
    initialValues: {
      username: props.user.username,
      email: props.user.email,
    }
  })
)
```

**Comment by jcalfee** [comment]
It is the warning.. I am setting form in my props.  I tried initially using `form` on the component then changed to `id` because I though their might be a property name conflict.  So you don't see the warning when your component loads for the first time?
