### ISSUE TITLE
initialValues from Redux Store with CommonJS

### ISSUE THREAD

**Issue by robhadfield** [erikras/redux-form#951]
Hi guys - I was wondering if there was an example anywhere using CommonJS to pull in initial values from a Redux store? I'm struggling to translate the 'Load Account' example in the docs :/ 

Currently:
- the form state works in Redux _(on updated/dirty fields)_
- the state comes from the Redux store just fine
- I can grab the form values on submit
...it's just the initial initialState from the Redux store I need to capture.

Here's a Gist of my component : https://gist.github.com/robhadfield/bb9e22afe12bb590c506dab9b7137447

_(You can see I'm using the Redux store state as initial values inline - I know that's not the right thing to do - just legacy code)_

Thanks in advance
Rob

redux-form@3.0.0-beta-2
redux@3.5.2

**Comment by erikras** [comment]
Man, that's some pretty old code. I'm afraid about the best I can do is point you to [the state of the docs](https://github.com/erikras/redux-form/tree/36018ff091e0e244be389b4efd1389fd1590f35c) (you'll have to build it yourself) from `v3.0.0-beta-2`.

**Comment by robhadfield** [comment]
Oops - I must have been following an old install tutorial.

OK - same question, now on redux-form@3.1.7 :)

**Comment by ooflorent** [comment]
I've answered something similar here: https://github.com/erikras/redux-form/issues/949#issuecomment-218829942

You can wrap your form with `connect`:

```js
connect(
  state => ({
    initialValues: state.school,
  })
)
```

Or use the `initialValues` props from the parent component:

```js
{props.school
  ? <SchoolDetails initialValues={props.school} />
  : null
}
```

**Comment by robhadfield** [comment]
👍 Cheers @ooflorent - bang on.
