### ISSUE TITLE
v6: Warning: The `value` prop supplied to <select> must be an array if `multiple` is true.

### ISSUE THREAD

**Issue by Iuriy-Budnikov** [erikras/redux-form#957]
Warning: The `value` prop supplied to <select> must be an array if `multiple` is true. Check the render method of `ConnectedField`.

**Comment by Iuriy-Budnikov** [comment]
Can you fix value by default from ```value: ""``` to ```value: []``` for multiple select ?

**Comment by chillichicken** [comment]
I still get this error.

 "redux-form": "^6.5.0",

In Render:
    
    <Field name="favoriteColor" component="select" multiple={true} value={[]}>
                            <option></option>
                            <option value="#ff0000">Red</option>
                            <option value="#00ff00">Green</option>
                            <option value="#0000ff">Blue</option>
                        </Field>

In console:

warning.js:36 Warning: The `value` prop supplied to <select> must be an array if `multiple` is true. Check the render method of `ConnectedField`.

Even though I supplied that value.

**Comment by chillichicken** [comment]
OK, I miss understood this component it works when giving the correct type, even though it's a bit ambiguous to declare the "multiple" property twice with multiple = true and type = select-multiple.

<Field name="favoriteColor" component="select" multiple={true} value={[]}  type="select-multiple">
                        <option></option>
                        <option value="#ff0000">Red</option>
                        <option value="#00ff00">Green</option>
                        <option value="#0000ff">Blue</option>
                    </Field>

**Comment by trongphan** [comment]
Use this: **type="select-multiple"** @deathmood

**Comment by deathmood** [comment]
@trongphan thanks -- that worked
