### ISSUE TITLE
docs(props): fix propTypes link & change error type from string to any

### ISSUE THREAD

**Issue by fredrikolovsson** [erikras/redux-form#958]
When upgrading to v6 I read the docs and noticed in props that `error` is a `string`. This was a problem in our app, because we used to set an object on the `_error` key (to be able to display more and nicely formatted information about what happened).

At first I thought the API might have changed, but also the v4 and v5 docs said `error : **string**`, while in fact the [propType is `any`](https://github.com/erikras/redux-form/blob/master/src/createPropTypes.js). I would like to keep it that way, but thought it could be good to edit the docs. Also, the link to the `propTypes` file is broken in the docs.

I will submit a PR with these edits. Thanks for everything you do!

**Comment by erikras** [comment]
Fixed by https://github.com/erikras/redux-form/commit/f2fe04310ce115530abbce61cb469f4be09c2a5c.
