### ISSUE TITLE
form validation trigger [v5.2.3]

### ISSUE THREAD

**Issue by andrewQwer** [erikras/redux-form#960]
Is there any way to trigger form validation manually? For example when I click some button inside a form.

**Comment by ooflorent** [comment]
Unfortunately there is no API to do this. However, it is possible to achieve this with a _hack_. When the form is submitted, the validation is run. You change manually call `handleSubmit` with a `noop` callback to trigger the validation.

```js
// Create a validation handler
const handleValidation = () => handleSubmit(() => {})

// Once clicked, this button will trigger the validation
<Button onClick={handleValidation}>Validate</Button>
```

**Comment by andrewQwer** [comment]
I tried `touchAll` and for some reason it doesn't help.

**Comment by erikras** [comment]
Sync validation happens automatically with every value change, so you can't "trigger it".

You will need to share more of your code, or make a small example, for us to help better.

**Comment by andrewQwer** [comment]
It's ok, thank you.

**Comment by zack-verys** [comment]
Hi @ooflorent, found your _hack_.  Was this intended to somehow **not** also run the form submission if validation passes? Using what you have worked great for running the validation when i wanted, but ends up submitting the form preemptively.  Is there a way to interrupt this?
