### ISSUE TITLE
[v6-alpha.10] Immutable import is broken

### ISSUE THREAD

**Issue by erikras** [erikras/redux-form#962]
The [Immutable Example](http://redux-form.com/6.0.0-alpha.10/examples/immutable/) won't load, because of a strange error:
```
SyntaxError: Unexpected token import
```
It's like it sees the first `import` line in `immutable.js` and it gets confused because it's not webpack/babel built fully or something. Happens in the development environment, too.

Possibly related to #937? @xdissent?

**Comment by ooflorent** [comment]
I'm on it.

**Comment by erikras** [comment]
Fixed by #963.
