### ISSUE TITLE
v6 — submit event isn't cancelled on second submit after validation error

### ISSUE THREAD

**Issue by halayli** [erikras/redux-form#966]
in v6.apha.10, when a submit returns a validation error, the second time a submit happens the submit event isn't cancelled and ends up doing an html form submit

**Comment by halayli** [comment]
@erikras did you by any chance experience this?

**Comment by jaraquistain** [comment]
I'm also experiencing this exact thing. I noticed that after a submit the `handleSubmit` property seems to be disappearing. I've got a component with an `.isRequired` prop type for `handleSubmit` and as soon as I hit the submit button I get a warning from that component that `handleSubmit` was not passed as a prop.

**Comment by erikras** [comment]
I'm pretty sure this was fixed by #1012. Fix released in [`v6.0.0-alpha.14`](https://github.com/erikras/redux-form/releases/tag/v6.0.0-alpha.14).

**Comment by jaraquistain** [comment]
@erikras I'm on alpha 15 now and I can confirm that I am no longer experiencing this issue.
