### ISSUE TITLE
[v6] plugin() api cannot work  

### ISSUE THREAD

**Issue by mauvew** [erikras/redux-form#968]
Thanks for creating this wonderful project.

When I upgrade redux-form from 5.2.3 to 6.0.0-alpha10, and start my web app, it fails and complain about reduxForm.reducer.plugin in the compile process.

The plugin() api works very well on v5.2.3, but suddenly fails when upgrading to 6.0.0-alpha[7,8,9,10]
![image](https://cloud.githubusercontent.com/assets/14197252/15267670/da8c7576-19bf-11e6-8708-077d0db88676.png)

**Comment by erikras** [comment]
You didn't read all the way to the end of the [Migration Guide](http://redux-form.com/6.0.0-alpha.10/docs/MigrationGuide.md/), did you? 😄

**Comment by mauvew** [comment]
haha, I just missed that part. Thanks. 
That would be great, as it is quite useful for clear the form content after submitting successfully. 😄
