### ISSUE TITLE
v6 Fields getting remounted in FieldArray

### ISSUE THREAD

**Issue by JakeGinnivan** [erikras/redux-form#969]
Hey,

I am working on a bit of a demo application and it has a custom input field with some complex interactions, because of this I noticed that everything under the `FieldArray` is being remounted when anything changes. Here is an example which shows the issue:

```js
class Test extends React.Component {
  constructor(props) {
    console.log('Created!')
    super(props)
  }

  render() {
    return <input {...this.props} />
  }
}

// Render of the form component
<form onSubmit={handleSubmit}>
<FieldArray name='test2' component={ingredients => {
        return (
          <div>
            {ingredients.map((name, index) => (
              <Field key={index} name={name} component={ingredient => (
                <Test {...ingredient} />
              )}
              />
            ))}
            <Button onClick={() => ingredients.push()}>Add Ingredient</Button>
          </div>
        )
      }}
      />
</form>
```

Each time I hit the button to add an ingredients all the fields get remounted (I get one 'Created' message when I click the first time, then another 2 when it's clicked the second time), destroying all local state and focus.

**Comment by erikras** [comment]
Excellent reporting. 👍 

There's a chance that #940 fixed this, but I haven't published a release since then.

**Comment by bsr203** [comment]
could be related. 

http://redux-form.com/6.0.0-alpha.10/examples/syncValidation/
If you start typing on `Username` field, it loses focus after first letter.

**Comment by erikras** [comment]
All the focus losing stuff is over on #961.

**Comment by JakeGinnivan** [comment]
6.0.0-alpha.13 fixes this.

Thanks guys! v6 is turning out awesome
