### ISSUE TITLE
InitialValues first render

### ISSUE THREAD

**Issue by timse** [erikras/redux-form#97]
Howdy, i found this issue when trying to render a form on the server via Reacts `React.renderToStaticMarkup`.

When the form is called with `initialValues` the `componentWillMount`-method will successfully invoke the `dispatch` with `initialize`.
However the `render` function will be called with the old reference to `form` which is not yet updated with the initial values and thus renders an empty form without the values.
In the browser this is almost invisible as the change in the store immediatelly calls a second render and the initial values show up.

I thought about a couple of possible solutions but didnt really come up with anything worth considering. Any thoughts on that?

**Comment by erikras** [comment]
Wow, that's really interesting, and makes total sense.

I wonder if the redux-form component could check to see if the form was not yet initialized, and if it wasn't but it _did_ have an `initialValues` prop, to use those values. That's the only solution that comes to me.

Does that make sense?

**Comment by timse** [comment]
yeah i was looking into something like:

instead of:
```
return DecoratedComponent =>
    class ReduxForm extends Component {
    ...
    }
```
this:
```
return DecoratedComponent =>  (...args) => {
       class ReduxForm extends Component {
          ...
       }
    if (args.initialValue) {
       // dispatch
    }

    return new ReduxForm(...args);
```

Problem is, that while bable theoretically supports this pattern and makes this whole constructor apply magic
```
    return new (_bind.apply(ReduxForm, [null].concat(args)))();
```
from
```
    return new ReduxForm(...args);
```

but due to the static props defined with `defaultProps` this currently still breaks with :
`throw new Error('No form name given to redux-form. Must be passed to ' + 'connectReduxForm({form: [form name]}) or as a "formName" prop');`


i could assume i only get a `property` argument (not sure how safe it is)

and make it:
```
return DecoratedComponent =>  (props) => {
       class ReduxForm extends Component {
          ...
       }
    if (args.initialValue) {
       // dispatch
    }

    return new ReduxForm(props);
```

which works perfectly fine.

but both kind of look `hacky`? no?

**Comment by iest** [comment]
@erikras I think this was the problem I was having that I did a terrible job of explaining on reactiflux a few days back...

So following the pattern of passing `initialValues` into the form inside the parent's `render`, I get the behaviour described: the form initially is empty, then re-renders immediately with real values.

I found that if I `dispatch(initialize('myForm', someInitialValues));` inside the parent `componentWillMount`, the form has the correct values from the get-go.

Not sure if that helps but it stopped me getting a load of proptype warnings in my console.

**Comment by wmertens** [comment]
I just encountered the same thing. Your solution sounds right @erikras :-)

**Comment by SpainTrain** [comment]
> I wonder if the redux-form component could check to see if the form was not yet initialized, and if it wasn't but it did have an initialValues prop, to use those values.

Is this what you were driving at - https://github.com/erikras/redux-form/pull/132 ?  That PR fixes the server-side rendering issue for me.

**Comment by erikras** [comment]
@SpainTrain That's a nice PR. Thank you for that!

But it seems like it could be accomplished without adding the `_initialized` flag to the Redux state. We've [already got the props](https://github.com/erikras/redux-form/blob/master/src/createReduxForm.js#L168) in the component, right? So why couldn't [your test](https://github.com/erikras/redux-form/commit/c951302d3917cc12b34d1a1ffcbc86f1b65b97e1#diff-78d6d6a35e23e4108eaaa8737f0c8276R311) happen with the prop that we already have? I don't think we care _that_ much about the value being initialized from somewhere else. If we do, then your method is definitely the way to go. Thoughts?

**Comment by SpainTrain** [comment]
I agree and will do one better :smile_cat:, just using react's `defaultValue` and `defaultChecked` appears to work.  PR is updated, LMK what you think!

**Comment by erikras** [comment]
Released as `v2.2.7`. Awesome work, @SpainTrain!

**Comment by SpainTrain** [comment]
Thanks for a quick turnaround.  No problem.  I'm really digging this lib, so happy to help!

**Comment by andresgutgon** [comment]
## Server side render of form with initialValues
Hi, I'm getting this react warning when I try to pass `initialValues` from parent component to form:

This is how I pass initialValues:
![image](https://cloud.githubusercontent.com/assets/49499/11014836/af356b42-8547-11e5-9520-428fb9970e07.png)

``` javascript
 <MyForm initialValues={{username: 'lol'}}/>
```

**Comment by erikras** [comment]
Oh! This is a bug associated with my fix for textarea initialization. Damn. It will require some more thought. Thanks for pointing this out.

**Comment by erikras** [comment]
@andresgutgon Confirm that SSR is fixed when you can.

**Comment by rewop** [comment]
I am having the same problem with initialisation of values. From the parent I pass the initial value with the prop `initialValues`. While client side in the form I get the `values` prop correctly initialised with the initial values, server side `values` has all the fields set to undefined. The related `defaultValue` property in the field prop is correctly set with the default coming from the initial value though.

**Comment by rewop** [comment]
Just tried the workaround from @iest and it worked for me.

**Comment by alisd23** [comment]
Is there a proper fix for this currently? I'm getting the same issue with react 15.0.02 and redux-forms 5.2.4. Server-side render shows values as undefined in the initial validate function, even though inputs are validated properly. Causing the error flags to be set even though the values are valid.
