### ISSUE TITLE
Trouble setting up development environment

### ISSUE THREAD

**Issue by clayne11** [erikras/redux-form#970]
I'm working on a PR for #908 and I'm having trouble getting my environment set up. Here's what I've tried:

1. Forked and cloned `redux-form` and checked out `ebaeca3` which is `v6.0.0-alpha.10`.
1. In the `redux-form` directory, run `npm link`.
1. In my project ruin `npm link redux-form`.

When I run my app and navigate to a form I get the following error:

```
Uncaught Invariant Violation: removeComponentAsRefFrom(...): Only a ReactOwner can have refs. You might be removing a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).
```

I also tried running using one of the examples with the same steps (using my local development version of `redux-form`) and I'm getting the same error. What am I doing wrong?

**Comment by erikras** [comment]
That is the proper theory, as I understand it, but `npm link` has never worked well for me. I normally do:

```
cd whatever/redux-form
npm run build
cp -r dist/* ../my-project/node_modules/redux-form/dist
```
and then restart `my-project`, because the hot reloading does not always work.

**Comment by erikras** [comment]
This is why, when I'm trying to implement a new feature or fix a bug in `redux-form`, I generally write a test to make sure it works. Not only is that a better way to code, but it lets me avoid all the project context switching crap of copying the built `lib` dir.

**Comment by clayne11** [comment]
Fair enough. Thanks for the help on this.
