### ISSUE TITLE
How to revalidate form programatically?

### ISSUE THREAD

**Issue by furydam** [erikras/redux-form#974]
Hi all,

I use the "react-intl" library for i18n. When I change a language, the form doesn't run a validate function so error messages won't translated. How can I invoke a validation process?

**Comment by erikras** [comment]
It validates on every render, so if you passed your language as a prop to your form component, even if you never did anything with it, it should rerender each time it changes.

Although it seems like you must be doing that already. How is the validation function being informed of the language the errors should be in?

**Comment by erikras** [comment]
@ooflorent, are you doing i18n form errors?

**Comment by ooflorent** [comment]
@erikras Yes, by abusing redux form errors. Instead of defining my errors as strings, I'm defining them as object descriptors:

```js
{type: "length", min: 4, max: 30}
```

Then I'm displaying the error using React Intl's `FormattedMessage`:

```js
const {type, ...values} = err
const errorElement = <FormattedMessage id={`errors.${type}`} values={values} />
```

When the locale changes, I don't need to revalidate the form. `FormattedMessage` will update and the errors would be correctly translated.

**Comment by erikras** [comment]
You know, @ooflorent, that would make a great [example](https://github.com/erikras/redux-form/tree/v6/examples). 😃

**Comment by CarsonF** [comment]
I'm having a problem with this (v6). I'm using `FormattedMessage` in render, but in the case that messages are loaded after my form is rendered, the `FormattedMessage` isn't getting rerendered. Maybe I need to decorate my component with something?

**Comment by danielrob** [comment]
I'm not sure this issue serves a purpose at this point given #975. @CarsonF if you think this is an issue with redux-form, and won't be solved with better internationalization examples/docs, please raise a new issue.
