### ISSUE TITLE
Add an example using internationalized error messages

### ISSUE THREAD

**Issue by ooflorent** [erikras/redux-form#975]
See https://github.com/erikras/redux-form/issues/974#issuecomment-219380643

**Comment by DSoe** [comment]
Hi,

Could you also please add an example using react-i18next internationalized error messages as well? 

I have the followings:

import { translate } from 'react-i18next';

@translate(['common'])
class RegistrationForm extends Component {

  static propTypes = {
    t: PropTypes.func,
  }

....

  render () {
 
    const { handleSubmit, fields: { email, firstName, lastName, password, passwordConfirm }, t} = this.props;
...
}

}
And in the function validate, I don't know how to pass down that t function to validate function.

Thank you in advance

**Comment by DSoe** [comment]
Hi,

I figured it out, and I got it working now. :)

I did the following to pass the t function to the reduxForm. I wrapped translate to the reduxForm.

import { translate } from 'react-i18next';

@translate(['common'])
@reduxForm({
  form: 'registration',
  fields: ['email', 'firstName', 'lastName', 'password', 'passwordConfirm' ],
  validate
}, mapStateToProps)
export default class RegistrationForm extends Component {

  static propTypes = {
    t: PropTypes.func
  }

//...

render () {
    const { handleSubmit, fields: { email, firstName, lastName, password, passwordConfirm }, t} = this.props;
// ...
}
}

function validate(formProps, props) {

  const errors = {};
  const t = props.t;

  if (formProps.email == '') {
    errors.email = t('content.email-required');
  }

  if (!formProps.firstName) {
    errors.firstName = t('content.first-name-required');
  }
//...
}

**Comment by PhamLinh0889** [comment]
Hi @DSoe ,
i copy your code but it not work.
at this: @reduxForm({
  form: 'registration',
  fields: ['email', 'firstName', 'lastName', 'password', 'passwordConfirm' ],
  validate
}, mapStateToProps)
please add function mapStateToProps.
thanks so much

**Comment by gustavohenke** [comment]
Since this issue is quite old and never got much attention, I'm closing it.
