### ISSUE TITLE
How can I switch the disabling of the form fields using v 6 Field or FieldArray?

### ISSUE THREAD

**Issue by JakeLin1024** [erikras/redux-form#976]
Hi,I'm new to the v6 and currently using redux-form v6 and material-ui to set up my form. Now Because of some requirements I need to disable the form fields like groupCode etc as code below.
So I tried to pass a fieldDisabled prop(defalutvalue=false) to MyViewForm and set the fieldDisabled = true after clicking a button outside, but it turned out the field wasn't disabled.
It looks like the Field(same as FieldArray?) wont be rendered even if any props of the MyViewForm change??
what should I do to disable the field?

My code here:

```js
class MyViewForm extends React.Component{

	render(){
			  const {
				fieldDisabled,
				handleSubmit} = this.props;

			  console.log("fieldDisabled=======================>",fieldDisabled);//can see the change here.

			  return (
				<div>
					<form id="fieldForm" onSubmit={handleSubmit}>
						---------TextField wont be disabled.-------------
						<Field name="groupCode" 
							component={(groupCode)=><TextField {...groupCode} id="groupCode" disabled={fieldDisabled} errorText={groupCode.error}/>}/></td>
					</form>
				</div>
			);
	}

}

MyViewForm = reduxForm({ 
  form: 'myViewForm' 
})(MyViewForm)

export default connect(
  state => ({
    initialValues: state.fillout.data   //this works fine.
  })
)(MyViewForm)
```

**Comment by erikras** [comment]
I think this was fixed by #940. I will expedite the next release.

**Comment by JakeLin1024** [comment]
@erikras thanks. As I looked into #940 and i upgraded to alpha 9 but i happened to encounter a same problem as #961.  It seems there is still no proper solution to the issue?

**Comment by erikras** [comment]
Oh, oops. I thought #940 hadn't been published yet. Sorry about that.

**Comment by ooflorent** [comment]
Have you tried something like this?

```js
const EnhancedTextField = props => (
  <TextField {...props} id={props.name} errorText={props.error} />
)

class MyViewForm extends React.Component {
  render() {
    const {fieldDisabled, handleSubmit} = this.props
    return (
      <div>
        <form id="fieldForm" onSubmit={handleSubmit}>
          <Field name="groupCode" 
            disabled={fieldDisabled}
            component={EnhancedTextField}
          />
        </form>
      </div>
    )
  }
}
```

Passing arrow functions to `component` is heavily discourage.
See https://github.com/erikras/redux-form/issues/961#issuecomment-219785684 and answers.

**Comment by JakeLin1024** [comment]
@ooflorent yes, that works...thank you.
