### ISSUE TITLE
Migrating from v5 to v6: how to combine field values ?

### ISSUE THREAD

**Issue by pierregm** [erikras/redux-form#978]
Hello, I posted that question on [stackoverflow](http://stackoverflow.com/q/37244538/1491200?sem=2) but thought it'd be as useful here.
I'm trying to migrate some forms from v5 to v6, where I need to display the combined values of some fields. In v5, I have something like this:

    class MyForm extends Component {
      render() {
        const { fields: { first, last }, handleSubmit } = this.props
        return (
          <form onSubmit={handleSubmit}>
            <div>
              <label>First name</label>
              <input type="text" {...first}/>
            </div>
            <div>
              <label>Last name</label>
              <input type="text" {...last}/>
            </div>
            <button type="submit">Submit</button>
            {/* HERE'S THE DIV I DON'T KNOW HOW TO MIGRATE */}
            <div>
              Welcome {first.value last.value.toUpperCase()}
            </div>
          </form>
        )
      }
    }

but I'm quite at loss with v6. I can't see how to use `Field`, as I need to access 2 fields at once. Could you point me in the right direction (and update the migration docs), or should I stick to v5 ?

**Comment by erikras** [comment]
That's pretty funny. I _literally_, as you were typing your issue, published [an example demonstrating this exact thing](http://redux-form.com/6.0.0-alpha.11/examples/selectingFormValues/). So no fault of yours for not finding it (the functionality was written just hours ago). Just a coincidence.

**Comment by pierregm** [comment]
Yes! I just saw that! Now, does it work with `FieldArray` as well? Each item of my `FieldArray` should display combined field values for that item...

**Comment by erikras** [comment]
Your array is just an array in the values. Should work the same. Report back if it does not.
