### ISSUE TITLE
Field cannot get focus if connect's mapStateToProps returns nested data structure

### ISSUE THREAD

**Issue by Pongetti** [erikras/redux-form#979]
Hello!  Just trying the switch from 5 to 6 today with 6.0.0-alpha.11.

I was finding that none of my fields were getting focus when I clicked on them.  I've narrowed it down to some minimum test code below and find the issue occurs when:
-I have a Field component wrapped inside of a connected component AND
-The connect's mapStateToProps returns nested data

```
@reduxForm({
	form:	'testForm'
})
export class TestingBedPage extends React.Component {
	render() {
		return (
			<div>
				<TestWrapperWorking name="X" />
				<TestWrapperNotWorking name="Y" />
			</div>
		)
	}
}

const TestChild = ({name}) => {
	return <div><Field name={name} component={field => <input type="text" {...field} />} /></div>;
}

const TestWrapperWorking = connect(
	(state) => ({a:'a', b:'b'})
)(TestChild);

const TestWrapperNotWorking = connect(
	(state) => ({a:'a', b:{}})
)(TestChild);

```

As implied, the first input has no issues, the second input cannot get focus.  The focus action is dispatched, it just never gets focus.

I tried a few different versions and it appears that it doesn't become a problem until version 9.

Thanks!

**Comment by brotzky** [comment]
This is most likely related to #961.

**Comment by ooflorent** [comment]
Does `v6.0.0-alpha.13` fix this?

**Comment by Pongetti** [comment]
Yup, alpha 13 appears to have fixed it.  Thanks!
