### ISSUE TITLE
Allow for composable/declarative validation (enhancement)

### ISSUE THREAD

**Issue by davidkpiano** [erikras/redux-form#98]
An idea that I would really like to see for Redux-Form is declaratively defining validation for each field in a form, much in the same spirit as [combineReducers](http://rackt.github.io/redux/docs/api/combineReducers.html) in Redux:

```js
// Example with synchronous validation

ContactForm = connectReduxForm({
  form: 'contact',
  fields: ['name', 'address', 'phone'],
  validate: {
    name: [
      (field) => field.touched && !field.value && 'Required'
    ],
    address: [
      (field) => !field.value && 'Required',
      (field) => field.touched && field.value && field.value.length > 50
        && 'Must be fewer than 50 characters'
    ],
    phone: [
      (field) => field.touched && !/\d{3}-\d{3}-\d{4}/.test(field.value)
        && 'Phone must match the form "999-999-9999"',
      (field, fields) => !fields.fax.value && !field.value && 'Must specify either a phone or fax number'
    ],
    fax: [
      // etc.
    ]
  }
})(ContactForm);
```

The benefits for this are:
- It's declarative; makes it trivial to dynamically add/modify, reference, and share validation
- Can define multiple validation rules per field, which permits _multiple_ validation messages per field
- Both `field` and `form` are passed into each validation function for each field, so validation can be contextual (e.g., based on other fields, such as how `fields.phone` is based on `fields.fax`).
- Validation is aware of the entire `field` object; so verbose validation conditionals such as `{address.error && address.touched && <div>{address.error}</div>}` are reduced to `<div>{address.error}</div>`.
- The final validation object is _actually_ immutable all the way through, instead of constantly and manually mutating an `errors = {}` object. :wink: 

What do you think? I'd be more than happy to submit a pull request if you like this idea/design.

**Comment by rockingskier** [comment]
I like this a lot.  Would you want a way to validate the whole form as well.  Maybe leave validate as is an and add `validateFields`.  Then only call `validate` if there are no errors in `validateFields`.  `validate` might even then be option as you might do all your validation on a field level.

```javascript
  ...
  validateFields: {
    name: [
      (field) => field.touched && !field.value && 'Required'
    ], 
    ...
  },
  validate: function () {
    return {};
  },
  ...
```

**Comment by davidkpiano** [comment]
@rockingskier Good thinking - this brings up another idea, which is separating validation from the fields, and letting the connection between validation and fields be an implementation detail by the developer.

That is, just as redux-form passes `props.fields` into the connected form, it can _also_ pass `props.errors` as well. This allows you to define "pseudo-fields" for validating:

```js
// ...
validate: {
  // ...
  passwords: [  // Note that 'passwords' does NOT exist as a field!
    (field, fields) => fields.password.value !== fields.passwordConfirm.value && 'Passwords do not match.'
  ]
}
```

And then this validation error can be displayed wherever the developer chooses:

```
// ...
render() {
  let { fields, errors } = this.props;

  return (
    // Pretend this error is beneath *both* the password and passwordConfirm fields 
    {errors.passwords.map(error => 
      <div>{error}</div>
    }
  );
}
```

Of course, you can have a `form` pseudofield for validating the entire form, in much the same way.

**Comment by erikras** [comment]
This is very similar to my initial instincts when writing a validation function. [Like this](https://github.com/erikras/react-redux-universal-hot-example/blob/35dda221a48b4602fc3cd746d1c4474c0831cb29/src/components/WidgetForm/widgetValidation.js), which calls [this](https://github.com/erikras/react-redux-universal-hot-example/blob/35dda221a48b4602fc3cd746d1c4474c0831cb29/src/utils/validation.js).

Your idea has some merit. The holes I'm about to poke in it might not be enough to sink it. I'm not convinced that redux-form enforcing this opinionated design is superior to just requiring a function, which could be adapted to any number of existing validation libraries.

Some problems I see with your idea:
* You can no longer use the same validation function on the client and the server if your validation function is concerned with field state.
* It's a mix of concerns that are presently neatly separated, namely validation and error display.
* The reduction of `{address.error && address.touched && <div>{address.error}</div>}` that you state as a benefit could be handled by the simplest `<Error field={address}/>` component very nicely.
* The immutability of the `errors` object is up to how clever you want to be with your validation function. It has nothing to do with the library. The one in the README example was intentionally simplistic.

I could certainly entertain the idea of allowing `fields` to be passed, as a second parameter (to let the same function work on the server) to the `validate` function.

**Comment by wmertens** [comment]
I agree with Erik, but I do like that the "required" error shows up before
fields are touched. This sets up some expectation for the user.

How about adding this to the configuration: required: ['field'],
requiredMsg:'Required'

This does fall over when you need to conditionally require fields though. I
suppose that Error component could just check if the error is "required"
and if so display it always.

On Sun, Sep 27, 2015 at 12:00 PM Erik Rasmussen <notifications@github.com>
wrote:

> This is very similar to my initial instincts when writing a validation
> function. Like this
> <https://github.com/erikras/react-redux-universal-hot-example/blob/35dda221a48b4602fc3cd746d1c4474c0831cb29/src/components/WidgetForm/widgetValidation.js>,
> which calls this
> <https://github.com/erikras/react-redux-universal-hot-example/blob/35dda221a48b4602fc3cd746d1c4474c0831cb29/src/utils/validation.js>
> .
>
> Your idea has some merit. The holes I'm about to poke in it might not be
> enough to sink it. I'm not convinced that redux-form enforcing this
> opinionated design is superior to just requiring a function, which could be
> adapted to any number of existing validation libraries.
>
> Some problems I see with your idea:
>
>    - You can no longer use the same validation function on the client and
>    the server if your validation function is concerned with field state.
>    - It's a mix of concerns that are presently neatly separated, namely
>    validation and error display.
>    - The reduction of {address.error && address.touched &&
>    <div>{address.error}</div>} that you state as a benefit could be
>    handled by the simplest <Error field={address}/> component very nicely.
>    - The immutability of the errors object is up to how clever you want
>    to be with your validation function. It has nothing to do with the library.
>    The one in the README example was intentionally simplistic.
>
> I could certainly entertain the idea of allowing fields to be passed, as
> a second parameter (to let the same function work on the server) to the
> validate function.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/erikras/redux-form/issues/98#issuecomment-143534271>.
>
-- 

Wout.
(typed on mobile, excuse terseness)

**Comment by davidkpiano** [comment]
@erikras The bigger issue is that redux-form assumes validation and fields are a one-to-one relationship. There are many cases where this is not true, especially when:

- A validation error is based on many fields (such as "password" and "passwordConfirm")
- A validation error belongs to the form, and not any particular field.

Having essentially a separate validation reducer will mitigate these complex validation issues, regardless of if it's a single function or an object, like I proposed.

**Comment by wmertens** [comment]
But the only way a user can respond to multi-field errors is to change one
or more fields, so it is ok to duplicate the error message on all involved
fields imho.

What would a form-wide error be? Keep in mind that you can also calculate
validity in render()…

On Sun, Sep 27, 2015, 18:43 David Khourshid <notifications@github.com>
wrote:

> @erikras <https://github.com/erikras> The bigger issue is that redux-form
> assumes validation and fields are a one-to-one relationship. There are many
> cases where this is not true, especially when:
>
>    - A validation error is based on many fields (such as "password" and
>    "passwordConfirm")
>    - A validation error belongs to the form, and not any particular field.
>
> Having essentially a separate validation reducer will mitigate these
> complex validation issues, regardless of if it's a single function or an
> object, like I proposed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/erikras/redux-form/issues/98#issuecomment-143575940>.
>
-- 

Wout.
(typed on mobile, excuse terseness)

**Comment by davidkpiano** [comment]
@wmertens Consider a simple credit card form. Everything may be entered in correctly, but the credit card may come back as invalid (which could be due to a number of things -- wrong card number, expiration date, CVV, etc.) from the server, so "Credit card is invalid. Please check all fields." should not be a field-specific thing.

I agree what @erikras is saying with these, though, so some modifications to my proposal can be made:

> You can no longer use the same validation function on the client and the server if your validation function is concerned with field state.
Okay, let's keep things such as `field.touched` a rendering concern. We can potentially simplify things here too, by passing in only the field values to the validation function.

> It's a mix of concerns that are presently neatly separated, namely validation and error display.
With the above modification, we can actually promote even further separation of concerns. The `validation` object that is returned no longer has to be concerned with specific fields -- the mapping is done at the developer's discretion, and no longer magically done by redux-form.

Another benefit to having a declarative validation object, even though it's opinionated, is that we're now able to have asynchronous validation using promises (or thunks, still not sure which):

```js
validation: {
  'address': [
    (field, fields) => validateAddress(field.value)
      .then( // return an error message if invalid );
  ]
}
```

I'm not a big fan of having two separate `validate` and `asyncValidate` functions.

**Comment by erikras** [comment]
There is already a form-wide error. If you give an error with the key `_error` (not great, but avoids collisions), it will be given as `props.error`. That's a relatively new feature.

**Comment by davidkpiano** [comment]
How would you represent multiple validation messages on a single field, or on the form itself with `_error` (preferably not in a procedural way)? My thinking is that using an object removes magic strings such as `_error` and allows the developer to define their own validation groups. Otherwise they're stuck placing a validation error message to an arbitrary field even though it applies to multiple fields.

**Comment by erikras** [comment]
There's no rule that the error has to be a string. It could just as easily be an array of strings.

I don't think it's particularly good UI to put both a `Start date must be before end date` error on `start` and an `End date must be after start date` error on `end`, but you could totally do that with the existing `{values} => {errors}` paradigm.

**Comment by mschipperheyn** [comment]
+1 for the schema approach. This validation function approach reminds me of the olden days of Java Spring development before the Bean Validation spec. Not a good memory: lots of repetition, brittleness and boiler plate. Ideally, a validator-type would be self contained so that you can validate n 'email-type', or 'phoneNumber-type', minlength, regex, custom function etc., which in turn can have their own error messages 'not an email', 'must be at least {0} characters'. Each form-field could have an array of validation-types.

**Comment by erikras** [comment]
Yes, of course, @mschipperheyn. Any developer worth a dime over minimum wage is going to implement it using [validation types](https://github.com/erikras/react-redux-universal-hot-example/blob/35dda221a48b4602fc3cd746d1c4474c0831cb29/src/components/WidgetForm/widgetValidation.js). The example in the README is only to get the point across as succinctly as possible, not to provide the recommended way of writing validation functions.

What you all seem to be missing is that by minimizing the [API surface area](https://www.youtube.com/watch?v=4anAwXYqLG8), redux-form allows _flexibility_ to use whatever mechanism the developer wants, be it one of the dozens of existing third party validation libraries or their own home grown system. If redux-form forced everyone into a rigid opinionated system, the library would be much less useful.

**Comment by mschipperheyn** [comment]
I agree with you. I hope someone, including myself, will have the time to develop a nice plugin for this sometime soon.
