### ISSUE TITLE
async validate multiple feilds

### ISSUE THREAD

**Issue by upq** [erikras/redux-form#980]
hello
I have 2 feilds that I want to do async validate for

```js
asyncBlurFields: [ 'username', 'email' ],
```

but I want each one to call a different function they both call `asyncValidate` [following this example](http://redux-form.com/5.2.3/#/examples/asynchronous-blur-validation?_k=7yebxo) 

I asked that question in the discord channel as suggested but I got nothing
however I then tried this hack:

```js
const asyncValidate = (values, dispatch , props) => {
  console.log(props.form);
  return new Promise((resolve, reject) => {
    if (props.form._active === 'username'){
      (async function() {
        const resp = await fetch('/graphql', {
          method: 'post',
          headers: {
            Accept: 'application/json',
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            query: '{allUsers(username:"' + values.username + '"){username}}',
          }),
          credentials: 'include',
        });
        const { data } = await resp.json();
        if (data.allUsers.length > 0) {
          reject({ username: 'That username is taken' });
        }else {
          resolve()
        }
      }());
    } else if (props.form._active === 'email') {
      (async function() {
        const resp = await fetch('/graphql', {
          method: 'post',
          headers: {
            Accept: 'application/json',
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            query: '{allUsers(email:"' + values.email + '"){email}}',
          }),
          credentials: 'include',
        });
        const { data } = await resp.json();
        console.log(data);
        if (data.allUsers.length > 0) {
          reject({ email: 'That email is taken' });
        }else {
          resolve()
        }
      }());
    }
  })
}
```

Everything is fine but when I reject the promise when email is taken the error for the username disappears and vice versa.

How can I do that elegantly without bugs?

**Comment by sckoh** [comment]
+1 
I'm using asyncValidate for multiple fields too, username and tel number.
I'm using the same approach as yours, when my telNumber is in error state.
Then, when I blur username field and got a resolve promise for username field,
The error state of telNumber field is gone.

**Comment by skiant** [comment]
In case you're still having this issue, it seems you need to reject the promise with every error.
In our case, I've used Lodash to extract all errors from the `props.form` object.

I push any error the validation might find in this `currentErrors` object and reject the promise with said object if it's not empty.

**Comment by KaboomFox** [comment]
in V6 this will become an issue again because props.form will only return the current form name.

**Comment by peteruithoven** [comment]
Wouldn't it make sense if the [Field component](http://redux-form.com/6.0.0-rc.1/docs/api/Field.md/) had a asyncValidate property? This would enable us to create independent async validation functions per field, in theory. 
If the status of this validation is passed to the component this would also solve https://github.com/erikras/redux-form/issues/900?

**Comment by upq** [comment]
I agree with @peteruithoven  , IMO props are always a friendlier solution.

**Comment by erikras** [comment]
@KaboomFox's fix published in [`v6.0.0-rc.5`](https://github.com/erikras/redux-form/releases/tag/v6.0.0-rc.5).

**Comment by oyeanuj** [comment]
@peteruithoven Did you proposed solution ever make it through? If not, did you @KaboomFox 's solution or something else?

**Comment by oyeanuj** [comment]
@peteruithoven Did you proposed solution ever make it through? If not, did you @KaboomFox 's solution or something else?

@erikras Do you plan to have `asyncValidate` be a field property with access to the `meta` prop?

**Comment by truesik** [comment]
@oyeanuj 
const asyncValidate = (values, dispatch, props, field) => {
   if (field === 'something') {.....

**Comment by peteruithoven** [comment]
@oyeanuj Not that I know of, it's was mostly a issue for the future of the project I'm working on. This has also meant that I haven't found the time to work on this yet.

**Comment by vvgomes** [comment]
A viable solution is:
```javascript
const asyncValidate = (values, dispatch, props) => {
  const previousErrors = props.state.form.myform.asyncErrors;
  const [ currentFieldName, currentFieldValue ] = Object.entries(values)[0];
  asyncOperation(currentFieldName, currentFieldValue).catch(err => {
    throw Object.assign({}, previousErrors, {[currentFieldName]: err});
  });
}
```

**Comment by keatz55** [comment]
Are any of these still relevant answers to the latest build?

**Comment by alopes** [comment]
I had to update @vvgomes fantastic solution to
```
const asyncValidate = (values, dispatch, props) => {
  const previousErrors = props.asyncErrors;
  const [ currentFieldName, currentFieldValue ] = Object.entries(values)[0];
  asyncOperation(currentFieldName, currentFieldValue).catch(err => {
    throw Object.assign({}, previousErrors, {[currentFieldName]: err});
  });
}
```

**Comment by ljwagerfield** [comment]
@keatz55 I'm using `6.6.3` and the changed field name is provided as a 4th parameter, so this works:
```javascript
const asyncValidate = (values, dispatch, props, currentFieldName) => {
  const previousErrors = props.asyncErrors;
  const currentFieldValue = values[currentFieldName];
  asyncOperation(currentFieldName, currentFieldValue).catch(err => {
    return Object.assign({}, previousErrors, {[currentFieldName]: err});
  });
}
```

**Comment by Abhijeetjaiswalit** [comment]
@upq I am able to validate multiple field on onBlur. But I'm unable to get why my submit button is not working after that. Here is my async method. Can you please help me  



import * as api from '../../../tools/apiConfig';
import axios from 'axios';
function asyncValidate(values, dispatch, props, currentFieldName) {
  const locale = props.locale.contactinfo;
  return new Promise((resolve, reject) => {
    if (currentFieldName === 'zip') {
      const field1 = {
        postal_code: values.zip
      }
      axios.post(api.VALIDATE_ZIP, field1).then((response) => {
        if (response.data == false) {
          reject({ zip: locale.postalRemoteValidate });
        }
        else {
          resolve()
        }
      });
    }
    else if (currentFieldName === 'email') {
      let field2 = {
        email: values.email
      }
      axios.post(api.VALIDATE_EMAIL, field2).then((response) => {
        if (response.data == false) {
          reject({ email: locale.emailValidation });
        }
        else {
          resolve()
        }
      })
    }
  })
}

export default asyncValidate;

**Comment by Abhijeetjaiswalit** [comment]
Can anyone please help  me with that? I'm kind of stuck here.

**Comment by vvgomes** [comment]
@Abhijeetjaiswalit first thing you could try is to *throw* the new errors object instead of *rejecting* the promise (with just the new error entry). Something like this:

```javascript
throw Object.assign({}, previousErrors, {[currentFieldName]: err});
```

Besides that, another suggestion to make your design simpler is to remove the field specific logic from your `asyncValidate` definition. You could try to inject another function that takes care of field specific validations so that `asyncValidate` has less reponsibilities (and code).

Hope that helps 😉

**Comment by Abhijeetjaiswalit** [comment]
@vvgomes  thanx for your suggestion. Tried you way. but now it is showing : Uncaught (in promise) Object {zip: "please enter a valid postal code."}  on console.

**Comment by Abhijeetjaiswalit** [comment]
@vvgomes any other suggestion, please?

**Comment by vvgomes** [comment]
@Abhijeetjaiswalit at this point, it's hard to suggest a solution without context. However, you could try to run the official [asyncValidation example](https://github.com/erikras/redux-form/tree/master/examples/asyncValidation) and try to modify it in baby-steps towards your scenario. At one point, you may want to extract the `asyncValidate` function to something similar to what @ljwagerfield suggested earlier in this thread.

**Comment by Abhijeetjaiswalit** [comment]
@vvgomes i've tried everything and then i came here for help. In any case it is showing uncaught (in promis)  error. And if i try to reject in case of  error then it doesn't allow me to submit the form once validation fails.

**Comment by ciro-maciel** [comment]
@vvgomes helped me, I'm posting like it was at the end.

"redux": "^3.7.2",
"redux-form": "^7.0.4"

```
const asyncValidate = (values, dispatch, props, field) => {

    const apiUrl = process.env.API_URL;

    if (field === 'userName') {
        return fetch("${apiUrl}/auth/validations/v1", {
            method: "POST",
            body: JSON.stringify({
                type: 'user-name',
                value: values.userName
            }),
            headers: new Headers({
                "Content-Type": "text/plain"
            })
        }).then(function (response) {
            return response.text();
        }).then(function (data) {
            const previousErrors = props.asyncErrors;
            if (data && (data === true || data === 'true')) {
                throw Object.assign({}, previousErrors, {[field]: 'b591d5f.0450d1b.76ae7b1.d'})
            }
        });
    }

}
```

```
export default reduxForm({
    form: 'signUp',
    destroyOnUnmount: false,
    asyncValidate: asyncValidate,
    asyncBlurFields: ['userName']
})(injectIntl(SignUpForm));
```

**Comment by radzak** [comment]
As far as I can tell from using redux-form: 7.3.0 you must return a promise. So the code above will fail due to: `Uncaught Error: asyncValidate function passed to reduxForm must return a promise`.

Be aware that the `asyncValidate` is invoked before the submit as stated in the docs: 

> Asynchronous validation will be called before the onSubmit is fired, but if all you care about is validation onSubmit, you should use Submit Validation.

Then the `field` parameter is undefined. Just wanted to share that, since I spent a while trying to find that out.

As I only want to validate individual fields on blur with `asyncValidate` I return a promise that resolves right after that:
```javascript
return new Promise(resolve => resolve());
```
Please let me know if there is any cleaner solution if you find one.

@Abhijeetjaiswalit the reason, your submit button is not working is exactly that case, when you don't resolve the promise you return.

**Comment by peeyush-ad2games** [comment]
@radzak I have the same situation where I want to do `asyncValidate` only if there is some value present in the field, but it required the promise to be returned. 

I think there should be a way to not call the function at all from `shouldAsyncValidate` based on values of fields.

`let ReduxifyForm = reduxForm({
  form: 'userForm',
  asyncValidate,
  asyncChangeFields: ['username', 'email'],
  shouldAsyncValidate: ({trigger}) => trigger !== 'submit'
})(Form)

const asyncValidate = (values) => {
  const { username } = values
  if (username) {
    return //server API's using fetch
  }
  return new Promise(resolve => resolve());
}


`

**Comment by vidur149** [comment]
I am facing the same issue. Tried the solution mentioned in the comments as well. Please help



`const asyncValidate = (values, dispatch, props, currentFieldName) => {
  const previousErrors = props.asyncErrors;
  debugger;
  // const currentFieldValue = values[currentFieldName];
  if (currentFieldName === 'mobile_no') {
    return axiosInst
      .get('/number/exists', {
        params: { mobile_no: values.mobile_no },
      })
      .then(response => {
        if (response.data.status !== 'Failed') {
          return axiosInst
            .get('/droppedregistrations/add', {
              params: { mobile_no: values.mobile_no },
            })
            .then(response => {
              console.log('mobile dropped ' + response.data);
            })
            .catch(error => {
              throw Object.assign({}, previousErrors, {
                [currentFieldName]: error.response.data.errors.mobile_no[0],
              });
            });
        } else {
          throw Object.assign({}, previousErrors, {
            [currentFieldName]: 'This mobile number already exists',
          });
        }
      });
  } else if (currentFieldName === 'email') {
    return axiosInst
      .get('/email/exists', {
        params: { email: values.email },
      })
      .then(response => {
        if (response.data.status !== 'Failed') {
          return axiosInst
            .get('/droppedregistrations/add', {
              params: { email: values.email },
            })
            .then(response => {
              // throw Object.assign({}, previousErrors);
              // Promise.reject(new Error('fail'));
              console.log('Email Dropped ' + response.data);
            })
            .catch(error => {
              throw Object.assign({}, previousErrors, {
                [currentFieldName]: error.response.data.errors.email[0],
              });
            });
        } else {
          throw Object.assign({}, previousErrors, {
            [currentFieldName]: 'This email already exists',
          });
        }
      });
  }
};

export default reduxForm({
  form: 'company-step-1',
  validate,
  asyncValidate,
  // asyncBlurFields: ['mobile_no', 'email'],
})(Step1Component);
`

**Comment by radzak** [comment]
@peeyush-ad2games I believe, it's now possible with `shouldAsyncValidate` :)

Take a look at `blurredField` param to [`shouldAsyncValidate`](https://redux-form.com/6.0.0-alpha.11/docs/api/reduxform.md/#-shouldasyncvalidate-params-boolean-optional-) function

**Comment by daton89** [comment]
this is my async validate for username and email

`

const asyncValidate = (values, dispatch, props, field) => {
	return new Promise((resolve, reject) => {
		Axios.get('/api/v1/users', {
			params: {
				_id: values._id,
				[field]: values[field]
			}
		})
			.then(res => {
				if (res.data.total > 0) {
					return reject({
						...props.asyncErrors,
						[field]: 'Questo valore già usato.'
					})
				}
				if (Object.keys(props.asyncErrors).length) {
					return reject(props.asyncErrors)
				}
				return resolve()
			})
			.catch(() => resolve())
	})
}

export default reduxForm({
	form: 'user',
	// validate
	asyncValidate,
	asyncBlurFields: ['username', 'email']
})(UserForm)
`

**Comment by AlbertWhite** [comment]
For me if I have two fields email / password : 
```
  if (fields === 'email' && values.email) {
    promises.push(verifyEmail(values.email, dispatch))
     // don't add the promise with the same "name" of the field
    if(props.asyncErrors && props.asyncErrors.password){
      promises.push(
        new Promise((resolve, reject) => {
          reject({password : props.asyncErrors.password})
        })
      )
    }
  }

  if (fields === 'password' && values.password) {
    promises.push(verifyPassword(values, dispatch))
     // don't add the promise with the same "name" of the field
    if(props.asyncErrors && props.asyncErrors.email){
      promises.push(
        new Promise((resolve, reject) => {
          reject({email: props.asyncErrors.email})
        })
      )
    }
  }
 // return one promise in the end
  return Promise.all(promises).then(() => {})
```
