### ISSUE TITLE
v6: exmples: syncValidation - `validate` functionality is commented out

### ISSUE THREAD

**Issue by bsr203** [erikras/redux-form#982]
https://github.com/erikras/redux-form/blob/v6/examples/syncValidation/src/SyncValidationForm.js

**Comment by ooflorent** [comment]
Sorry, what's the issue here?

**Comment by erikras** [comment]
I fixed this last night. Maybe didn't push. It's uncommented on the website.

**Comment by erikras** [comment]
No, looks like i did
