### ISSUE TITLE
v6.0.0-alpha.13 stops closure from updating

### ISSUE THREAD

**Issue by brotzky** [erikras/redux-form#985]
Initial discussion: https://twitter.com/dennisbrotzky/status/732340403853107204

Updating props (or any variable) doesn't update within the `Field` closure.

```JavaScript
render() {
  const { isLoading } = this.props; // <-- getting isLoading off props

  return (
    <Field
      name="fieldName"
      component={fieldName =>
      <div>
        <input
          type="text"
          disabled={isLoading} // <-- isLoading will not update from initially set value
          {...fieldName}  />
      </div>
    }/>
  )
 }
```

This is specific to v6.0.0-alpha.13 as reverting to previous versions (v6.0.0-alpha.9) works as expected.

**Comment by ooflorent** [comment]
Whenever `component` changes, `Field` does not re-render.
You must add extra props to your `Field` element if you want them to update:

```js
render() {
  const {isLoading} = this.props
  return (
    <Field
      name="fieldName"
      isLoading={isLoading}
      component={field =>
      <div>
        <input
          type="text"
          disabled={field.isLoading}
          {...field}  />
      </div>
    }/>
  )
}
```

**Comment by erikras** [comment]
Excellent. I was too tired to figure this out last night. This needs to be documented in the `Field` docs, asap.

**Comment by brotzky** [comment]
@ooflorent, that's awesome! Thanks so much for the suggestion.

**Comment by JakeLin1024** [comment]
Awesome, you guys are brilliant.

**Comment by JakeLin1024** [comment]
@brotzky  Hi, did you try FieldArray? I found the updating problem had gone, but the losing focus one still there.

**Comment by brotzky** [comment]
@JakeLin1024, no I haven't tried it, sorry.
