### ISSUE TITLE
Passing this.props.data.id into redux form?

### ISSUE THREAD

**Issue by Eric-Tran** [erikras/redux-form#987]
My ListItem component was passed data from another component using:
```

renderData() {


 return (
  <ListItem
       key={data.id}
       data={data} />
           )

```
Now in my ListItem component I have access to the data using this.props.data. I want to pass the id, this.props.data.id to reduxForm or my handleFormSubmit function.

I tried adding a hidden input field to pass the id which didn't work?
```

handleFormSubmit({ id, date }) {

    this.props.post( { id, date })
}
```
And in my render method.....
```

render() {

    const { handleSubmit, fields: { id, date }} = this.props;
     return(
          <div>
          <form className="form-inline" onSubmit={handleSubmit(this.handleFormSubmit.bind(this))}>
              <input {...id} type="hidden" name="id" value={this.props.data.id} />
              <select className="form-control" {...date} >
          <option value="Monday">Monday</option>
              <option value="Tuesday">Tuesday</option>
              <option value="Wednesday">Wednesday</option>
              <option value="Thursday">Thursday</option>
              <option value="Friday">Friday</option>
              <option value="Saturday">Saturday</option>
              <option value="Sunday">Sunday</option>
               </select>
            </form>
         </div>
       )
}


export default reduxForm({

     form: 'day', 
     fields: ['id', 'date']
})
```
There must be another way to add the data into my handleFormSubmit method that I'm not seeing?

**Comment by Eric-Tran** [comment]
Solved it just passed the id in the handleSubmit function..

**Comment by ypyang237** [comment]
Could you please post the complete solved version? I'm running into the same problem as well.
Thanks!

**Comment by Eric-Tran** [comment]
In my handleFormSubmit function which gets called onSubmit, I passed in the id. So onSubmit, this.handleFormSubmit.bind(this, this.props.data.id). Hope this helps.

**Comment by ypyang237** [comment]
Perfect, thanks for the quick reply!
