### ISSUE TITLE
Issue when used with react-native

### ISSUE THREAD

**Issue by chymtt** [erikras/redux-form#99]
I got this weird error while using redux-form with react-native. Whenever a <TextInput> got blurred, the dispatched action always has a value of class SyntheticEvent (supposedly the onBlur SyntheticEvent made by react-native) and hence the value of the field will become a SyntheticEvent instance instead

**Comment by erikras** [comment]
@mattiamanzati, a little help?

**Comment by meoguru** [comment]
:+1: I'm experiencing this too.

**Comment by mattiamanzati** [comment]
I solved replacing 

  if (event.nativeEvent !== undefined && event.nativeEvent.text !== undefined) {
    return event.nativeEvent.text;
  }

with



  if (event.nativeEvent !== undefined) {
    return event.nativeEvent.text;
  }

but this is not a global Solution, since it Will affect the browser Environment :/

**Comment by erikras** [comment]
I think we might need a `reactNative: true` config option to fix these sorts of anomalies.

I'll try and get it fixed for tomorrow.

**Comment by mattiamanzati** [comment]
Personally, I would prefer mounting the reducer from a different path, like redux-form/native (like react-redux does) but that's only a suggestion :D

**Comment by chymtt** [comment]
@mattiamanzati that would be really awesome. I prefer that too

**Comment by erikras** [comment]
Check out [v2.0.0](https://github.com/erikras/redux-form/releases/tag/v2.0.0). Covers all the stuff in this issue.

**Comment by chymtt** [comment]
Thanks. It's working perfectly now!
