### ISSUE TITLE
How to use InitialValues With Deep Form

### ISSUE THREAD

**Issue by theljani** [erikras/redux-form#990]
Hello, 

how can i pass an initial object to a form (seperate component) set inside another global form??
I'm using the deep form concept but i cannot initialize my form.
any help please?

**Comment by ooflorent** [comment]
You can use `initialValues` to initial deep forms.

```js
reduxForm({
  form: "myform",
  fields: [
    "name",
    "phones[]",
    "address.street",
    "address.city",
  ],
  initialValues: {
    name: "John Doe",
    phones: [
      "555-1234",
      "555-5678",
    ],
    address: {
      street: "1052 Huntz Lane",
      city: "Boston",
    }
  }
})
```

In the future, we recommend that you ask questions on StackOverflow first, and file issues if you’re confident the bug is in the library.
