### ISSUE TITLE
add support for changing multiple form value in one action

### ISSUE THREAD

**Issue by sckoh** [erikras/redux-form#995]
If I have an API that return multiple value to prefill the form, I need to dispatch change action many times.
Is it possible to add a action for changing multiple form fields in one dispatch?

**Comment by erikras** [comment]
See #991.

**Comment by bertho-zero** [comment]
I have an input that takes 2 values, so I use Fields but I have a problem when I change the values (always both at the same time), I have tried `redux-batched-actions` but it does not change the problem, it would be really useful to be able to modify several values at one time.

It's for https://github.com/luqin/react-bootstrap-datetimerangepicker

**Comment by gustavohenke** [comment]
@bertho-zero, if you think you could provide a more detailed use case, you should definitely open a new issue. This is one is very old.
