### ISSUE TITLE
v6 When removing all input, pristine is set to true

### ISSUE THREAD

**Issue by ruiaraujo** [erikras/redux-form#997]
This breaks sync validation for required field since it is like a reset has been done when all input is removed on the field.
http://redux-form.com/6.0.0-alpha.13/examples/syncValidation/

**Comment by ooflorent** [comment]
Thanks for reporting this issue.
Could you paste some code so we could investigate what went wrong?

**Comment by ruiaraujo** [comment]
@ooflorent the demo link I posted is that code. ;)

**Comment by ooflorent** [comment]
Could elaborate what's wrong? I played with the form but everything seems fine...

**Comment by ruiaraujo** [comment]
It seems to be an issue cause by lodash-webpack-plugin.

**Comment by ruiaraujo** [comment]
it requires configuring the lodash plugin with placeholders support.
    new LodashModuleReplacementPlugin({ placeholders: true }),

Maybe this should be added to the docs?

**Comment by ooflorent** [comment]
> It seems to be an issue cause by `lodash-webpack-plugin`

Why do think this? Could you please try to explain what is going wrong? I'm sorry but you're giving me enough information to reproduce the issue. Maybe a step list would help.

> Maybe this should be added to the docs?

I don't think so. It is probably a misconfiguration of Redux Form example bundler.

**Comment by jdalton** [comment]
Ya, I'm at a loss too. @ruiaraujo you've managed to confuse everyone 😸

**Comment by ruiaraujo** [comment]
Sorry guys! Yesterday was Google IO day so I was out of office.

So the demo works fine. 
I got confused with the pristine and the touched flags. The problem on my forms was that the touched flag was always false.

I had other issues with lodash-webpack-plugin (which @jdalton fixed very quickly https://github.com/lodash/lodash-webpack-plugin/issues/16) and during that debug process I noticed that redux-form was currying on the touch flag using partialRight (I am not sure of any of this BTW).

So when then I disable lodash-webpack-plugin to check if that was the cause, and indeed it was. Then I looked at the configuration of lodash-webpack-plugin and placeholders seemed to be thing missing so that's the story my very brief comments yesterday.

So in my opinion this bug is not really a bug, although maybe redux form could be refactored to only rely on the 'left' partial instead of doing it from both sides.

**Comment by erikras** [comment]
Doesn't take much to get a day off work in Germany, huh? 😛 

So is this resolved? I'm confused. 😕

**Comment by ruiaraujo** [comment]
From my side, kind of. Although if people use lodash-webpack-plugin, they have to configure as I said above. I think this is related to the partialRight usage. So if redux-form refactors to remove this usage, it would be better IMO. But @jdalton is a better person to ask. 

@erikras I just got out early and left the laptop behind. ;)

**Comment by jdalton** [comment]
The `lodash-webpack-plugin` bug has already been patched and a version released. I don't think redux-form uses lodash.

**Comment by ruiaraujo** [comment]
@jdalton Yes the issue for detecting curry and I am using it. Still it needs the placeholders for correct operation.

If redux-form v6 did not use lodash, why would lodash-webpack-plugin cause any issue? ;-)

**Comment by jdalton** [comment]
Ah I missed it in the search because github doesn't return matches in branches.

**Comment by jdalton** [comment]
This is outside the scope of redux-form. They can't be responsible for every third-party plugin or transform.

**Comment by erikras** [comment]
☝️ There. 😄
