### ISSUE TITLE
v5.2.3 - Change value when using formKey

### ISSUE THREAD

**Issue by tanepiper** [erikras/redux-form#998]
I have a password field in my app that has a generate password button:

```js
<FormGroup controlId="formPassword" validationState={password.error}>
        <ControlLabel>Password</ControlLabel>
        <InputGroup>
          <FormControl type="text" placeholder="Please enter a password" {...password} />
          <InputGroup.Addon>
            <InputGroup.Button>
              <Button onClick={this.generatePassword.bind(this)}>Generate Password</Button>
            </InputGroup.Button>
          </InputGroup.Addon>
          <FormControl.Feedback />
        </InputGroup>
      </FormGroup>
```

```js
  generatePassword() {
    this.props.dispatch(change('pupil', 'password', 'foo'));
  }
```

The above example works if I *don't* use a formKey (for new entries we use "new" otherwise an ID gets passed for the form key). e.g

```js
<PupilForm
  formKey="new" 
  onSubmit={this.onSubmit(null, school.id)} 
  onCancel={this.onCloseForm.bind(this)}
/>
```

If I use a form key, then there seems to be no way to access it as this create a child object for the form.

![pwfield](https://cloud.githubusercontent.com/assets/376930/15356829/0fa7c414-1cf3-11e6-9a92-440b535370ca.png)

Is there any way to do this (without going down the custom component route?)

**Comment by ooflorent** [comment]
First of all there is something you must be aware of: we are currently working on v6 and, in v6, `formKey` no longer exists. Instead you must specify a unique `form` property.

If you want to ease the transition to v6, you should stop using `formKey` and pass `form` from the form's parent.

```js
<PupilForm form="pupil_new" />
<PupilForm form="pupil_password" />
```

Assuming you still want to use `formKey`, even now you know that it is deprecated and will be removed in the next major release, here is how you can specify the form key:

```js
import {changeWithKey} from "redux-form"
dispatch(changeWithKey("pupil", "new", "password", "foo"))
```

**Comment by tanepiper** [comment]
@ooflorent That's great, thanks.  As we're in production we can't rely on 6 at the moment - but I'll make a note for future upgrades.

Thanks.

**Comment by Domiii** [comment]
Oh that's crazy! All documentation I found told me to use `formKey`, and I was wondering why things did not work! An update in the docs and a multi-form example would be just super dandy! :)
